SignalProcessing: SignalProcessing Class Reference
SignalProcessing Class Reference
#include <SignalProcessing.h>
Public Member Functions
void ExponentialSmoothing (double alpha, double *out_vector)
Applies exponential smoothing to the signal vector.
void NormalizeVector ()
Normalizes the signal vector to [0, 1] range.
void ScaleVector (double new_min, double new_max)
Scales the signal vector to a given range [new_min, new_max].
double GetMean ()
Calculates the mean (average) of the signal vector.
double GetVariance ()
Calculates the variance of the signal vector.
double GetStandardDeviation ()
Calculates the standard deviation of the signal vector.
double GetMovingAverage (int window_size)
Calculates the moving average of the last window_size values.
void GetMovingAverageVector (double *out_vector, int window_size)
Calculates the moving average for each position and stores it in out_vector.
SignalProcessing ()
Constructor for SignalProcessing class.
int AddValue (double value)
Adds a value to the signal vector.
int AddValueWithTimestamp (double value, struct timespec ts)
Adds a value with timestamp to the signal vector.
void SetItem (int Item)
Sets the item identifier.
void GetTimespec (struct timespec *td, int index)
Gets the timestamp for a value in the vector.
double GetLastValue ()
Returns the last value added.
int GetMaxCapacity ()
Returns the maximum capacity of the vector.
int GetSize ()
Returns the current size of the vector.
int GetIndex ()
Returns the current index.
int GetItem ()
Returns the item identifier.
void GetVector (double *signalProc_vector)
Copies the signal vector to another vector.
void GetVectorInt (int *signalProc_vector, int size)
Copies the signal vector to an int vector.
void InitVector (double *values, int size)
Initializes the signal vector with given values.
void MultiplyWithValue (double value, int size)
Multiplies the signal vector by a value.
void DivideWithValue (double value, int size)
Divides the signal vector by a value.
void SubstractWithValue (double value, int size)
Subtracts a value from the signal vector.
void AddWithValue (double value, int size)
Adds a value to the signal vector.
void GetVectorWithOffset (double *signalProc_vector, int size, int offset)
Copies the signal vector with offset.
void ClearVector ()
Resets the signal vector.
void NormalDistributionFree ()
Frees memory for probability distribution.
void NormalDistributionPrint (prob_dist *pd)
Prints the normal distribution.
void NormalDistributionCalculate (double *data, int size, prob_dist *pd)
Calculates the normal distribution.
prob_dist * NormalDistributionCreate ()
Creates the normal distribution struct.
void NormalDistributionRun ()
Runs the normal distribution calculation.
void PrintVector ()
Prints the signal vector.
void BuildIndexLookupTable (int first_received)
Builds the index lookup table.
int GetIndexLookupTable (int ReceivedIndex)
Returns the normalized index from the lookup table.
int DetectThresholdCrossing (double threshold, int direction, int *events)
Detects threshold crossing events in the signal vector.
int DetectZeroCrossing (int direction, int *events)
Detects zero-crossing events in the signal vector.
bool GetThresholdCrossingFlag ()
Gets the threshold crossing flag status.
bool GetZeroCrossingFlag ()
Gets the zero crossing flag status.
void ClearEventFlags ()
Clears event detection flags.
int DetectPeaks (int *peaks, int max_peaks)
Detects peaks (local maxima) in the signal vector.
int DetectPeaksWithThreshold (double threshold, int *peaks, int max_peaks)
Detects peaks above a threshold value.
int DetectPeaksWithProminence (double min_prominence, int *peaks, int max_peaks)
Detects peaks with minimum prominence.
int DetectPeaksWithDistance (int min_distance, int *peaks, int max_peaks)
Detects peaks with minimum distance between them.
double GetPeakValue (int peak_index)
Gets the value at a specific peak index.
double GetValue (int index)
Gets the signal value at a specific index.
struct timespec GetTimestamp (int index)
Gets the timestamp at a specific index.
void KalmanFilter (double process_noise, double measurement_noise, double *out_vector, double initial_estimate=0.0, double initial_error=1.0)
Applies a simple 1D Kalman filter for signal denoising.
void WaveletDenoise (double threshold, double *out_vector, int level=1)
Applies wavelet denoising using soft thresholding.
void MedianFilter (int window_size, double *out_vector)
Applies median filter for noise removal.
double EstimateNoiseLevel ()
Estimates noise level using Median Absolute Deviation (MAD)
int DetectAnomaliesZScore (double threshold_sigma, int *anomaly_indices, int max_anomalies)
Detects anomalies using statistical threshold (Z-score method)
int DetectAnomaliesIQR (double iqr_multiplier, int *anomaly_indices, int max_anomalies)
Detects anomalies using Interquartile Range (IQR) method.
int DetectAnomaliesMAD (int window_size, double threshold_factor, int *anomaly_indices, int max_anomalies)
Detects anomalies using Moving Average Deviation method.
int DetectSuddenChanges (double threshold_change, int *anomaly_indices, int max_anomalies)
Detects sudden spikes/changes in signal (rate of change anomaly)
int SegmentByMarkers (int *marker_indices, int num_markers, SegmentStats *segment_stats)
Segments signal by markers/tags (e.g., turbine blades)
int FindMostAnomalousSegment (int *marker_indices, int num_markers, int anomaly_method)
Identifies the segment (e.g., blade) with highest anomaly score.
int DetectPeriodicAnomalies (int period, double tolerance, int *anomaly_indices, int max_anomalies)
Detects anomalies in periodic signals (turbine rotations)
double CalculateAnomalyScore (int method)
Calculates anomaly score for entire signal.
bool FFTAnalysis (int start_index, int window_size, double sampling_rate, FrequencySpectrum *spectrum)
Performs FFT on a window of the signal.
bool FFTAnalysis (double sampling_rate, FrequencySpectrum *spectrum)
Performs FFT on entire signal.
int FindFrequencyPeaks (FrequencySpectrum *spectrum, double min_magnitude, double *peak_frequencies, double *peak_magnitudes, int max_peaks)
Finds peaks in frequency spectrum.
double GetPowerInBand (FrequencySpectrum *spectrum, double freq_low, double freq_high)
Calculates power in a frequency band.
double AnalyzeHarmonics (FrequencySpectrum *spectrum, double fundamental, int num_harmonics, double *harmonic_magnitudes)
Analyzes harmonics of a fundamental frequency.
int CompareSegmentSpectra (int *marker_indices, int num_markers, double sampling_rate, FrequencySpectrum *spectra)
Compares frequency spectra of different segments.
void FreeSpectrum (FrequencySpectrum *spectrum)
Frees memory allocated for frequency spectrum.
double DetectFrequencyAnomalies (FrequencySpectrum *current_spectrum, FrequencySpectrum *baseline_spectrum, double threshold)
Detects frequency anomalies by comparing with baseline spectrum.
bool ExtractMLFeatures (double sampling_rate, MLFeatureVector *features)
Extracts comprehensive feature vector for ML/AI applications.
bool ExtractMLFeaturesFromSegment (int start_index, int window_size, double sampling_rate, MLFeatureVector *features)
Extracts feature vector from a specific segment/window.
int ExtractMLFeaturesRollingWindow (int window_size, int step_size, double sampling_rate, MLDataset *dataset)
Extracts features using rolling window approach.
bool ExportMLFeaturesToH5 (const char *filename, MLFeatureVector *features, const char *path="/Signal", bool save_raw_signal=true)
Exports feature vector and raw signal to HDF5.
int Decimate (int factor, double *out_vector, bool apply_antialiasing=true)
Decimates signal by keeping every Nth sample (downsampling)
int InterpolateLinear (int factor, double *out_vector)
Interpolates signal using linear interpolation (upsampling)
int Resample (double current_rate, double target_rate, double *out_vector)
Resamples signal to a new sampling rate.
int Autocorrelation (int max_lag, double *out_correlation, bool normalize=true)
Computes autocorrelation of the signal.
int CrossCorrelation (double *signal2, int signal2_size, int max_lag, double *out_correlation, bool normalize=true)
Computes cross-correlation between current signal and another signal.
int FindCorrelationPeak (double *correlation, int size, double *peak_value)
Finds the lag with maximum correlation value.
Static Public Member Functions
static int ExportFeaturesToArray (MLFeatureVector *features, double *output_array)
Exports features to a flat array for direct ML library input.
static void NormalizeMLFeatures (MLFeatureVector *features, double *mean_values, double *std_values)
Normalizes feature vector for ML input (z-score normalization)
static bool CreateMLDataset (int capacity, bool with_labels, MLDataset *dataset)
Creates an empty ML dataset with specified capacity.
static void FreeMLDataset (MLDataset *dataset)
Frees memory allocated for ML dataset.
static bool AddFeaturesToDataset (MLDataset *dataset, MLFeatureVector *features, int label=-1)
Adds a feature vector to the dataset.
static bool ComputeTrainingStats (MLDataset *dataset, MLTrainingStats *stats)
Computes training statistics from a dataset.
static bool NormalizeDataset (MLDataset *dataset, MLTrainingStats *stats)
Normalizes all samples in a dataset using training statistics.
static bool ExportDatasetToCSV (MLDataset *dataset, const char *filename, bool include_labels=true)
Exports dataset to CSV file for external ML frameworks.
static int BatchExtractFeatures (double **signals, int *signal_sizes, int num_signals, double sampling_rate, MLDataset *dataset)
Batch prediction interface - extract features from multiple signals.
static bool ExportDatasetToH5 (MLDataset *dataset, const char *filename, bool include_labels=true, const char *path="/ML/Dataset")
Exports ML dataset to HDF5 file using SignalRecorder.
static bool ExportTrainingStatsToH5 (MLTrainingStats *stats, const char *filename, const char *path="/ML/TrainingStats")
Exports training statistics to HDF5 file.
Detailed Description
Definition at line 149 of file SignalProcessing.h.
Constructor & Destructor Documentation
SignalProcessing()
SignalProcessing::SignalProcessing ()
Constructor for SignalProcessing class.
SignalProcessing constructor.
Definition at line 20 of file SignalProcessing.cpp.
References NB_MAX_VALUES, and NormalDistributionCreate().
Member Function Documentation
AddFeaturesToDataset()
bool SignalProcessing::AddFeaturesToDataset (MLDataset * dataset, MLFeatureVector * features, int label = -1) static
Adds a feature vector to the dataset.
Adds feature vector to dataset.
Parameters
dataset Dataset to add to
features Feature vector to add
label Optional label for supervised learning (-1 if no label)
Returns
true if successful, false if dataset is full
Parameters
dataset Dataset to add to
features Features to add
label Optional label
Returns
true if successful
Definition at line 2409 of file SignalProcessing.cpp.
References MLDataset::capacity, MLDataset::has_labels, MLDataset::labels, MLDataset::num_samples, and MLDataset::samples.
Referenced by BatchExtractFeatures(), and ExtractMLFeaturesRollingWindow().
AddValue()
int SignalProcessing::AddValue (double value)
Adds a value to the signal vector.
Adds a value to the signal processing vector.
Parameters
value Value to add
Returns
Current index
Parameters
value Value to be saved in the signal processing vector
Returns
this->index
Definition at line 46 of file SignalProcessing.cpp.
References NB_MAX_VALUES.
Referenced by ApplyFilters(), BatchExtractFeatures(), ComputeFFT(), DetectAnomalies(), ExtractMLFeatures(), ExtractMLFeaturesFromSegment(), GenerateSignal(), and preprocess_signal().
AddValueWithTimestamp()
int SignalProcessing::AddValueWithTimestamp (double value, struct timespec ts)
Adds a value with timestamp to the signal vector.
Parameters
value Value to add
ts Timestamp to associate with the value
Returns
Current index
Parameters
value Value to be saved in the signal processing vector
ts Timestamp to associate with the value
Returns
this->index
Definition at line 74 of file SignalProcessing.cpp.
References NB_MAX_VALUES.
Referenced by acquire_ecg_data().
AddWithValue()
void SignalProcessing::AddWithValue (double value, int size)
Adds a value to the signal vector.
Adds a scalar value to the signal processing vector.
Parameters
value Value
size Size
value Value
size Number of elements to add
Returns
void
Definition at line 258 of file SignalProcessing.cpp.
AnalyzeHarmonics()
double SignalProcessing::AnalyzeHarmonics (FrequencySpectrum * spectrum, double fundamental, int num_harmonics, double * harmonic_magnitudes)
Analyzes harmonics of a fundamental frequency.
Parameters
spectrum Frequency spectrum to analyze
fundamental Fundamental frequency (Hz)
num_harmonics Number of harmonics to analyze
harmonic_magnitudes Output array for harmonic magnitudes
Returns
Total harmonic distortion (THD)
Parameters
spectrum Frequency spectrum
fundamental Fundamental frequency
num_harmonics Number of harmonics to analyze
harmonic_magnitudes Output array for harmonic magnitudes
Returns
Total harmonic distortion (THD)
Definition at line 1904 of file SignalProcessing.cpp.
References FrequencySpectrum::bins, FrequencyBin::frequency, FrequencySpectrum::frequency_resolution, FrequencyBin::magnitude, and FrequencySpectrum::num_bins.
Autocorrelation()
int SignalProcessing::Autocorrelation (int max_lag, double * out_correlation, bool normalize = true)
Computes autocorrelation of the signal.
Computes autocorrelation of signal.
Parameters
max_lag Maximum lag to compute (number of shifts)
out_correlation Output array for autocorrelation values (size >= max_lag+1)
normalize If true, normalizes output to [-1, 1] range
Returns
Number of correlation values computed
Autocorrelation measures similarity of signal with delayed version of itself. Useful for:
Detecting periodicity
Finding fundamental frequency
Measuring signal predictability
Parameters
max_lag Maximum lag to compute
out_correlation Output correlation array
normalize Normalize to [-1, 1]
Returns
Number of correlation values
Definition at line 3059 of file SignalProcessing.cpp.
References GetMean().
BatchExtractFeatures()
int SignalProcessing::BatchExtractFeatures (double ** signals, int * signal_sizes, int num_signals, double sampling_rate, MLDataset * dataset) static
Batch prediction interface - extract features from multiple signals.
Batch feature extraction from multiple signals.
Parameters
signals Array of signal arrays
signal_sizes Array of sizes for each signal
num_signals Number of signals to process
sampling_rate Sampling rate in Hz
dataset Output dataset with features from all signals
Returns
Number of signals successfully processed
Useful for batch inference on multiple sensor readings
Parameters
signals Array of signal arrays
signal_sizes Array of signal sizes
num_signals Number of signals
sampling_rate Sampling rate in Hz
dataset Output dataset
Returns
Number of signals processed
Definition at line 2638 of file SignalProcessing.cpp.
References AddFeaturesToDataset(), AddValue(), MLDataset::capacity, ExtractMLFeatures(), MLDataset::num_samples, sampling_rate, and sp.
BuildIndexLookupTable()
void SignalProcessing::BuildIndexLookupTable (int first_received)
Builds the index lookup table.
Parameters
first_received First received index
Definition at line 419 of file SignalProcessing.cpp.
References MAX_INDX, index_lookup_table::normal, and index_lookup_table::received.
CalculateAnomalyScore()
double SignalProcessing::CalculateAnomalyScore (int method)
Calculates anomaly score for entire signal.
Calculates overall anomaly score for the signal.
Parameters
method Method to use: 0=ZScore, 1=IQR, 2=MaxDeviation
Returns
Anomaly score (higher = more anomalous)
Parameters
method Method: 0=ZScore, 1=IQR, 2=MaxDeviation
Returns
Anomaly score
Definition at line 1529 of file SignalProcessing.cpp.
References GetMean(), GetStandardDeviation(), and NB_MAX_VALUES.
ClearEventFlags()
void SignalProcessing::ClearEventFlags ()
Clears event detection flags.
Definition at line 652 of file SignalProcessing.cpp.
ClearVector()
void SignalProcessing::ClearVector ()
Resets the signal vector.
Clears the signal processing vector.
Definition at line 34 of file SignalProcessing.cpp.
References NB_MAX_VALUES.
Referenced by GenerateSignal().
CompareSegmentSpectra()
int SignalProcessing::CompareSegmentSpectra (int * marker_indices, int num_markers, double sampling_rate, FrequencySpectrum * spectra)
Compares frequency spectra of different segments.
Parameters
marker_indices Array of segment start indices
num_markers Number of segments
sampling_rate Sampling rate in Hz
spectra Output array of spectra for each segment
Returns
Number of spectra computed
Parameters
marker_indices Segment start indices
num_markers Number of segments
sampling_rate Sampling rate
spectra Output array of spectra
Returns
Number of spectra computed
Definition at line 1959 of file SignalProcessing.cpp.
References FFTAnalysis(), and sampling_rate.
ComputeTrainingStats()
bool SignalProcessing::ComputeTrainingStats (MLDataset * dataset, MLTrainingStats * stats) static
Computes training statistics from a dataset.
Computes training statistics from dataset.
Parameters
dataset Dataset to analyze
stats Output statistics (mean, std, min, max for each feature)
Returns
true if successful, false otherwise
Use these statistics to normalize future data with NormalizeMLFeatures()
Parameters
dataset Dataset to analyze
stats Output statistics
Returns
true if successful
Definition at line 2438 of file SignalProcessing.cpp.
References ExportFeaturesToArray(), MLTrainingStats::max_values, MLTrainingStats::mean_values, MLTrainingStats::min_values, MLDataset::num_samples, MLTrainingStats::num_samples, MLDataset::samples, and MLTrainingStats::std_values.
CreateMLDataset()
bool SignalProcessing::CreateMLDataset (int capacity, bool with_labels, MLDataset * dataset) static
Creates an empty ML dataset with specified capacity.
Creates an empty ML dataset.
Parameters
capacity Maximum number of samples to store
with_labels If true, allocates memory for labels (supervised learning)
dataset Output dataset structure
Returns
true if successful, false otherwise
Use this to create batch datasets for training or inference
Parameters
capacity Maximum number of samples
with_labels Allocate memory for labels
dataset Output dataset
Returns
true if successful
Definition at line 2343 of file SignalProcessing.cpp.
References MLDataset::capacity, MLDataset::has_labels, MLDataset::labels, MLDataset::num_samples, and MLDataset::samples.
CrossCorrelation()
int SignalProcessing::CrossCorrelation (double * signal2, int signal2_size, int max_lag, double * out_correlation, bool normalize = true)
Computes cross-correlation between current signal and another signal.
Computes cross-correlation between two signals.
Parameters
signal2 Second signal array
signal2_size Size of second signal
max_lag Maximum lag to compute (positive and negative)
out_correlation Output array for correlation values (size >= 2*max_lag+1)
normalize If true, normalizes output to [-1, 1] range
Returns
Number of correlation values computed
Cross-correlation measures similarity between two signals at different time shifts. Useful for:
Time delay estimation
Pattern matching
Signal alignment
Detecting common patterns
Parameters
signal2 Second signal
signal2_size Size of second signal
max_lag Maximum lag (positive and negative)
out_correlation Output correlation array
normalize Normalize to [-1, 1]
Returns
Number of correlation values
Definition at line 3110 of file SignalProcessing.cpp.
References GetMean().
Decimate()
int SignalProcessing::Decimate (int factor, double * out_vector, bool apply_antialiasing = true)
Decimates signal by keeping every Nth sample (downsampling)
Decimates signal by factor (downsampling)
Parameters
factor Decimation factor (e.g., 2 = keep every 2nd sample, 4 = every 4th)
out_vector Output array for decimated signal (size >= GetIndex()/factor)
apply_antialiasing If true, applies low-pass filter before decimation
Returns
Number of samples in decimated signal
Reduces sampling rate by factor. If apply_antialiasing=true, applies moving average filter to prevent aliasing artifacts.
Parameters
factor Decimation factor
out_vector Output array
apply_antialiasing Apply low-pass filter before decimation
Returns
Number of output samples
Definition at line 2926 of file SignalProcessing.cpp.
References NB_MAX_VALUES.
Referenced by Resample().
DetectAnomaliesIQR()
int SignalProcessing::DetectAnomaliesIQR (double iqr_multiplier, int * anomaly_indices, int max_anomalies)
Detects anomalies using Interquartile Range (IQR) method.
Parameters
iqr_multiplier Multiplier for IQR (typically 1.5 for outliers, 3.0 for extreme outliers)
anomaly_indices Output array to store indices of detected anomalies
max_anomalies Maximum number of anomalies to detect
Returns
Number of anomalies detected
Parameters
iqr_multiplier Multiplier for IQR (1.5 for outliers, 3.0 for extreme)
anomaly_indices Output array for anomaly indices
max_anomalies Maximum number of anomalies to detect
Returns
Number of anomalies detected
Definition at line 1213 of file SignalProcessing.cpp.
References anomaly_indices, and NB_MAX_VALUES.
Referenced by DetectAnomalies().
DetectAnomaliesMAD()
int SignalProcessing::DetectAnomaliesMAD (int window_size, double threshold_factor, int * anomaly_indices, int max_anomalies)
Detects anomalies using Moving Average Deviation method.
Parameters
window_size Window size for moving average
threshold_factor Multiplication factor for deviation threshold
anomaly_indices Output array to store indices of detected anomalies
max_anomalies Maximum number of anomalies to detect
Returns
Number of anomalies detected
Parameters
window_size Window size for moving average
threshold_factor Multiplication factor for deviation threshold
anomaly_indices Output array for anomaly indices
max_anomalies Maximum number of anomalies to detect
Returns
Number of anomalies detected
Definition at line 1256 of file SignalProcessing.cpp.
References anomaly_indices.
Referenced by DetectAnomalies().
DetectAnomaliesZScore()
int SignalProcessing::DetectAnomaliesZScore (double threshold_sigma, int * anomaly_indices, int max_anomalies)
Detects anomalies using statistical threshold (Z-score method)
Detects anomalies using Z-score method (statistical threshold)
Parameters
threshold_sigma Number of standard deviations for anomaly threshold (e.g., 3.0)
anomaly_indices Output array to store indices of detected anomalies
max_anomalies Maximum number of anomalies to detect
Returns
Number of anomalies detected
Parameters
threshold_sigma Number of standard deviations for anomaly threshold
anomaly_indices Output array for anomaly indices
max_anomalies Maximum number of anomalies to detect
Returns
Number of anomalies detected
Definition at line 1181 of file SignalProcessing.cpp.
References anomaly_indices, GetMean(), and GetStandardDeviation().
Referenced by DetectAnomalies().
DetectFrequencyAnomalies()
double SignalProcessing::DetectFrequencyAnomalies (FrequencySpectrum * current_spectrum, FrequencySpectrum * baseline_spectrum, double threshold)
Detects frequency anomalies by comparing with baseline spectrum.
Detects frequency anomalies by comparing with baseline.
Parameters
current_spectrum Current frequency spectrum
baseline_spectrum Baseline (normal) frequency spectrum
threshold Threshold for anomaly detection (ratio)
Returns
Anomaly score (0 = normal, higher = more anomalous)
Parameters
current_spectrum Current spectrum
baseline_spectrum Baseline spectrum
threshold Threshold ratio
Returns
Anomaly score
Definition at line 2002 of file SignalProcessing.cpp.
References FrequencySpectrum::bins, FrequencyBin::magnitude, and FrequencySpectrum::num_bins.
DetectPeaks()
int SignalProcessing::DetectPeaks (int * peaks, int max_peaks)
Detects peaks (local maxima) in the signal vector.
Parameters
peaks Output array to store peak indices
max_peaks Maximum number of peaks to detect
Returns
Number of peaks detected
Definition at line 677 of file SignalProcessing.cpp.
DetectPeaksWithDistance()
int SignalProcessing::DetectPeaksWithDistance (int min_distance, int * peaks, int max_peaks)
Detects peaks with minimum distance between them.
Parameters
min_distance Minimum distance between consecutive peaks
peaks Output array to store peak indices
max_peaks Maximum number of peaks to detect
Returns
Number of peaks detected
Definition at line 787 of file SignalProcessing.cpp.
References NB_MAX_VALUES.
Referenced by detect_r_peaks().
DetectPeaksWithProminence()
int SignalProcessing::DetectPeaksWithProminence (double min_prominence, int * peaks, int max_peaks)
Detects peaks with minimum prominence.
Parameters
min_prominence Minimum prominence (height above surrounding valleys)
peaks Output array to store peak indices
max_peaks Maximum number of peaks to detect
Returns
Number of peaks detected
Definition at line 730 of file SignalProcessing.cpp.
DetectPeaksWithThreshold()
int SignalProcessing::DetectPeaksWithThreshold (double threshold, int * peaks, int max_peaks)
Detects peaks above a threshold value.
Parameters
threshold Minimum value for peak detection
peaks Output array to store peak indices
max_peaks Maximum number of peaks to detect
Returns
Number of peaks detected
Definition at line 703 of file SignalProcessing.cpp.
Referenced by detect_r_peaks().
DetectPeriodicAnomalies()
int SignalProcessing::DetectPeriodicAnomalies (int period, double tolerance, int * anomaly_indices, int max_anomalies)
Detects anomalies in periodic signals (turbine rotations)
Detects anomalies in periodic signals.
Parameters
period Expected period length
tolerance Tolerance for period variations (percentage, e.g., 0.1 for 10%)
anomaly_indices Output array to store indices of detected anomalies
max_anomalies Maximum number of anomalies to detect
Returns
Number of anomalies detected
Parameters
period Expected period length
tolerance Tolerance for period variations (0.0 to 1.0)
anomaly_indices Output array for anomaly indices
max_anomalies Maximum number of anomalies to detect
Returns
Number of anomalies detected
Definition at line 1461 of file SignalProcessing.cpp.
References anomaly_indices, and NB_MAX_VALUES.
DetectSuddenChanges()
int SignalProcessing::DetectSuddenChanges (double threshold_change, int * anomaly_indices, int max_anomalies)
Detects sudden spikes/changes in signal (rate of change anomaly)
Detects sudden changes/spikes in signal (rate of change anomaly)
Parameters
threshold_change Minimum rate of change to be considered anomalous
anomaly_indices Output array to store indices of detected anomalies
max_anomalies Maximum number of anomalies to detect
Returns
Number of anomalies detected
Parameters
threshold_change Minimum rate of change to be considered anomalous
anomaly_indices Output array for anomaly indices
max_anomalies Maximum number of anomalies to detect
Returns
Number of anomalies detected
Definition at line 1298 of file SignalProcessing.cpp.
References anomaly_indices.
DetectThresholdCrossing()
int SignalProcessing::DetectThresholdCrossing (double threshold, int direction, int * events)
Detects threshold crossing events in the signal vector.
Parameters
threshold The threshold value to detect
direction 1 for rising edge (below->above), -1 for falling edge (above->below), 0 for both
events Output array to store indices where crossings occur (size >= GetIndex())
Returns
Number of threshold crossings detected
Definition at line 587 of file SignalProcessing.cpp.
Referenced by detect_events().
DetectZeroCrossing()
int SignalProcessing::DetectZeroCrossing (int direction, int * events)
Detects zero-crossing events in the signal vector.
Parameters
direction 1 for positive crossing (negative->positive), -1 for negative crossing (positive->negative), 0 for both
events Output array to store indices where crossings occur (size >= GetIndex())
Returns
Number of zero crossings detected
Definition at line 614 of file SignalProcessing.cpp.
DivideWithValue()
void SignalProcessing::DivideWithValue (double value, int size)
Divides the signal vector by a value.
Divides the signal processing vector by a scalar value.
Parameters
value Value
size Size
value Value
size Number of elements to divide
Returns
void
Definition at line 241 of file SignalProcessing.cpp.
EstimateNoiseLevel()
double SignalProcessing::EstimateNoiseLevel ()
Estimates noise level using Median Absolute Deviation (MAD)
Returns
Estimated noise standard deviation
Definition at line 1139 of file SignalProcessing.cpp.
References NB_MAX_VALUES.
ExponentialSmoothing()
void SignalProcessing::ExponentialSmoothing (double alpha, double * out_vector)
Applies exponential smoothing to the signal vector.
Parameters
alpha Smoothing factor (0 < alpha <= 1)
out_vector Destination vector for smoothed values (size >= GetIndex())
Definition at line 571 of file SignalProcessing.cpp.
ExportDatasetToCSV()
bool SignalProcessing::ExportDatasetToCSV (MLDataset * dataset, const char * filename, bool include_labels = true) static
Exports dataset to CSV file for external ML frameworks.
Exports dataset to CSV file.
Parameters
dataset Dataset to export
filename Output CSV filename
include_labels If true, includes label column (for supervised learning)
Returns
true if successful, false otherwise
CSV format: feature1,feature2,...,feature21[,label] Compatible with Python pandas, scikit-learn, TensorFlow data loaders
Parameters
dataset Dataset to export
filename Output filename
include_labels Include label column
Returns
true if successful
Definition at line 2534 of file SignalProcessing.cpp.
References ExportFeaturesToArray(), MLDataset::has_labels, MLDataset::labels, MLDataset::num_samples, and MLDataset::samples.
ExportDatasetToH5()
bool SignalProcessing::ExportDatasetToH5 (MLDataset * dataset, const char * filename, bool include_labels = true, const char * path = "/ML/Dataset") static
Exports ML dataset to HDF5 file using SignalRecorder.
Exports ML dataset to HDF5 file.
Parameters
dataset Dataset to export
filename Output HDF5 filename
include_labels If true, includes label dataset
path HDF5 group path (e.g., "/ML/Training")
Returns
true if successful, false otherwise
HDF5 format structure:
/path/features (21 x N matrix) - All features
/path/labels (N vector) - Labels (if include_labels=true)
/path/feature_names (21 strings) - Feature names
Attributes: num_samples, num_features, has_labels
Compatible with:
TensorFlow tf.data from HDF5
PyTorch torch.utils.data with h5py
Keras load from HDF5
MATLAB h5read()
Parameters
dataset Dataset to export
filename Output HDF5 filename
include_labels Include labels dataset
path HDF5 group path
Returns
true if successful
Definition at line 2688 of file SignalProcessing.cpp.
References SignalRecorder::addDoubleVector(), SignalRecorder::addMetadata(), ExportFeaturesToArray(), MLDataset::has_labels, MLDataset::labels, MLDataset::num_samples, and MLDataset::samples.
ExportFeaturesToArray()
int SignalProcessing::ExportFeaturesToArray (MLFeatureVector * features, double * output_array) static
Exports features to a flat array for direct ML library input.
Exports features to flat array for ML libraries.
Parameters
features Feature vector structure
output_array Output array (must be allocated, size >= 21)
Returns
Number of features exported
Exports in order: statistical (8) → frequency (9) → time domain (4) Compatible with TensorFlow, PyTorch, scikit-learn format requirements
Parameters
features Feature structure
output_array Output array (size >= 21)
Returns
Number of features exported
Definition at line 2248 of file SignalProcessing.cpp.
References MLFeatureVector::autocorr_peak, MLFeatureVector::crest_factor, MLFeatureVector::dominant_frequency, MLFeatureVector::energy, MLFeatureVector::kurtosis, MLFeatureVector::mean, MLFeatureVector::mean_crossing_rate, MLFeatureVector::peak_to_peak, MLFeatureVector::power_high_freq, MLFeatureVector::power_low_freq, MLFeatureVector::power_mid_freq, MLFeatureVector::rms, MLFeatureVector::skewness, MLFeatureVector::spectral_centroid, MLFeatureVector::spectral_entropy, MLFeatureVector::spectral_spread, MLFeatureVector::std_dev, MLFeatureVector::total_power, MLFeatureVector::variance, and MLFeatureVector::zero_crossing_rate.
Referenced by ComputeTrainingStats(), ExportDatasetToCSV(), ExportDatasetToH5(), ExportMLFeaturesToH5(), and NormalizeMLFeatures().
ExportMLFeaturesToH5()
bool SignalProcessing::ExportMLFeaturesToH5 (const char * filename, MLFeatureVector * features, const char * path = "/Signal", bool save_raw_signal = true)
Exports feature vector and raw signal to HDF5.
Exports feature vector and optionally raw signal to HDF5.
Parameters
filename Output HDF5 filename
features Feature vector to export
path HDF5 group path (e.g., "/Signals/ECG_001")
save_raw_signal If true, also saves raw signal data
Returns
true if successful, false otherwise
Useful for debugging and visualization - saves both features and original signal
Parameters
filename Output HDF5 filename
features Feature vector to export
path HDF5 group path
save_raw_signal If true, also saves raw signal
Returns
true if successful
Definition at line 2823 of file SignalProcessing.cpp.
References SignalRecorder::addDoubleVector(), SignalRecorder::addMetadata(), and ExportFeaturesToArray().
ExportTrainingStatsToH5()
bool SignalProcessing::ExportTrainingStatsToH5 (MLTrainingStats * stats, const char * filename, const char * path = "/ML/TrainingStats") static
Exports training statistics to HDF5 file.
Exports training statistics to HDF5.
Parameters
stats Training statistics to export
filename Output HDF5 filename
path HDF5 group path
Returns
true if successful, false otherwise
Saves mean, std, min, max for each feature (21 features) Use this to store normalization parameters with your trained model
Parameters
stats Training statistics
filename Output HDF5 filename
path HDF5 group path
Returns
true if successful
Definition at line 2772 of file SignalProcessing.cpp.
References SignalRecorder::addDoubleVector(), SignalRecorder::addMetadata(), MLTrainingStats::max_values, MLTrainingStats::mean_values, MLTrainingStats::min_values, MLTrainingStats::num_samples, and MLTrainingStats::std_values.
ExtractMLFeatures()
bool SignalProcessing::ExtractMLFeatures (double sampling_rate, MLFeatureVector * features)
Extracts comprehensive feature vector for ML/AI applications.
Extracts comprehensive ML feature vector from current signal.
Parameters
sampling_rate Sampling rate in Hz (needed for frequency features)
features Output structure containing all extracted features
Returns
true if successful, false otherwise
Extracts 21 features from the current signal:
Statistical: mean, std_dev, variance, skewness, kurtosis, RMS, peak-to-peak, crest factor
Frequency: dominant freq, spectral centroid, spectral spread, spectral entropy, power bands
Time domain: zero-crossing rate, energy, autocorrelation peak
Perfect for feeding into neural networks, SVMs, or other ML models
Parameters
sampling_rate Sampling rate in Hz
features Output structure for features
Returns
true if successful
Definition at line 2048 of file SignalProcessing.cpp.
References MLFeatureVector::autocorr_peak, FrequencySpectrum::bins, MLFeatureVector::crest_factor, FrequencySpectrum::dominant_frequency, MLFeatureVector::dominant_frequency, MLFeatureVector::energy, FFTAnalysis(), FreeSpectrum(), FrequencyBin::frequency, GetMean(), GetPowerInBand(), GetStandardDeviation(), GetVariance(), MLFeatureVector::kurtosis, FrequencyBin::magnitude, MLFeatureVector::mean, MLFeatureVector::mean_crossing_rate, FrequencySpectrum::num_bins, MLFeatureVector::num_features, MLFeatureVector::peak_to_peak, MLFeatureVector::power_high_freq, MLFeatureVector::power_low_freq, MLFeatureVector::power_mid_freq, MLFeatureVector::rms, sampling_rate, MLFeatureVector::skewness, MLFeatureVector::spectral_centroid, MLFeatureVector::spectral_entropy, MLFeatureVector::spectral_spread, MLFeatureVector::std_dev, FrequencySpectrum::total_power, MLFeatureVector::total_power, MLFeatureVector::variance, and MLFeatureVector::zero_crossing_rate.
Referenced by BatchExtractFeatures(), ExtractMLFeatures(), and ExtractMLFeaturesFromSegment().
ExtractMLFeaturesFromSegment()
bool SignalProcessing::ExtractMLFeaturesFromSegment (int start_index, int window_size, double sampling_rate, MLFeatureVector * features)
Extracts feature vector from a specific segment/window.
Extracts features from a specific segment.
Parameters
start_index Starting index of the segment
window_size Size of the segment to analyze
sampling_rate Sampling rate in Hz
features Output structure containing all extracted features
Returns
true if successful, false otherwise
Parameters
start_index Starting index
window_size Size of segment
sampling_rate Sampling rate in Hz
features Output structure
Returns
true if successful
Definition at line 2221 of file SignalProcessing.cpp.
References AddValue(), ExtractMLFeatures(), and sampling_rate.
Referenced by ExtractMLFeaturesRollingWindow().
ExtractMLFeaturesRollingWindow()
int SignalProcessing::ExtractMLFeaturesRollingWindow (int window_size, int step_size, double sampling_rate, MLDataset * dataset)
Extracts features using rolling window approach.
Extracts features using rolling window.
Parameters
window_size Size of each window
step_size Step between windows (overlap = window_size - step_size)
sampling_rate Sampling rate in Hz
dataset Output dataset containing features from each window
Returns
Number of windows processed
Perfect for time series analysis and streaming data processing Example: window_size=100, step_size=50 creates 50% overlap
Parameters
window_size Size of each window
step_size Step between windows
sampling_rate Sampling rate in Hz
dataset Output dataset
Returns
Number of windows processed
Definition at line 2591 of file SignalProcessing.cpp.
References AddFeaturesToDataset(), MLDataset::capacity, ExtractMLFeaturesFromSegment(), MLDataset::num_samples, and sampling_rate.
FFTAnalysis() [1/2]
bool SignalProcessing::FFTAnalysis (double sampling_rate, FrequencySpectrum * spectrum)
Performs FFT on entire signal.
Performs FFT analysis on entire signal.
Parameters
sampling_rate Sampling rate in Hz
spectrum Output structure containing frequency analysis
Returns
true if successful, false otherwise
Parameters
sampling_rate Sampling rate in Hz
spectrum Output spectrum
Returns
true if successful
Definition at line 1819 of file SignalProcessing.cpp.
References FFTAnalysis(), and sampling_rate.
FFTAnalysis() [2/2]
bool SignalProcessing::FFTAnalysis (int start_index, int window_size, double sampling_rate, FrequencySpectrum * spectrum)
Performs FFT on a window of the signal.
Performs FFT analysis on a window of the signal.
Parameters
start_index Starting index of the window
window_size Size of the window (will be rounded to nearest power of 2)
sampling_rate Sampling rate in Hz
spectrum Output structure containing frequency analysis
Returns
true if successful, false otherwise
Parameters
start_index Starting index
window_size Window size
sampling_rate Sampling rate in Hz
spectrum Output spectrum
Returns
true if successful
Definition at line 1730 of file SignalProcessing.cpp.
References FrequencySpectrum::bins, FrequencySpectrum::dominant_frequency, FrequencyBin::frequency, FrequencySpectrum::frequency_resolution, FrequencyBin::magnitude, FrequencySpectrum::num_bins, FrequencyBin::phase, FrequencyBin::power, sampling_rate, FrequencySpectrum::sampling_rate, FrequencySpectrum::total_power, and FrequencySpectrum::window_size.
Referenced by CompareSegmentSpectra(), ComputeFFT(), ExtractMLFeatures(), and FFTAnalysis().
FindCorrelationPeak()
int SignalProcessing::FindCorrelationPeak (double * correlation, int size, double * peak_value)
Finds the lag with maximum correlation value.
Finds lag with maximum correlation.
Parameters
correlation Correlation array (from Autocorrelation or CrossCorrelation)
size Size of correlation array
peak_value Output parameter for the peak correlation value
Returns
Lag index with maximum correlation
Useful for finding:
Fundamental period (autocorrelation)
Time delay between signals (cross-correlation)
Parameters
correlation Correlation array
size Array size
peak_value Output peak value
Returns
Index of peak
Definition at line 3195 of file SignalProcessing.cpp.
FindFrequencyPeaks()
int SignalProcessing::FindFrequencyPeaks (FrequencySpectrum * spectrum, double min_magnitude, double * peak_frequencies, double * peak_magnitudes, int max_peaks)
Finds peaks in frequency spectrum.
Parameters
spectrum Frequency spectrum to analyze
min_magnitude Minimum magnitude to be considered a peak
peak_frequencies Output array for peak frequencies
peak_magnitudes Output array for peak magnitudes
max_peaks Maximum number of peaks to find
Returns
Number of peaks found
Parameters
spectrum Frequency spectrum
min_magnitude Minimum magnitude threshold
peak_frequencies Output array for frequencies
peak_magnitudes Output array for magnitudes
max_peaks Maximum number of peaks
Returns
Number of peaks found
Definition at line 1831 of file SignalProcessing.cpp.
References FrequencySpectrum::bins, FrequencyBin::frequency, FrequencyBin::magnitude, and FrequencySpectrum::num_bins.
FindMostAnomalousSegment()
int SignalProcessing::FindMostAnomalousSegment (int * marker_indices, int num_markers, int anomaly_method)
Identifies the segment (e.g., blade) with highest anomaly score.
Finds the segment with highest anomaly score.
Parameters
marker_indices Array of indices where each segment starts
num_markers Number of markers
anomaly_method Method to use: 0=ZScore, 1=IQR, 2=MAD, 3=MaxValue
Returns
Index of the most anomalous segment (0-based segment number)
Parameters
marker_indices Array of indices where each segment starts
num_markers Number of markers
anomaly_method Method: 0=ZScore, 1=IQR, 2=MAD, 3=MaxValue
Returns
Index of most anomalous segment
Definition at line 1393 of file SignalProcessing.cpp.
References anomaly_method, SegmentStats::anomaly_score, GetMean(), GetStandardDeviation(), SegmentStats::max_value, SegmentStats::mean, SegmentStats::rms, SegmentByMarkers(), and SegmentStats::std_dev.
FreeMLDataset()
void SignalProcessing::FreeMLDataset (MLDataset * dataset) static
Frees memory allocated for ML dataset.
Frees ML dataset memory.
Parameters
dataset Dataset to free
Definition at line 2380 of file SignalProcessing.cpp.
References MLDataset::capacity, MLDataset::has_labels, MLDataset::labels, MLDataset::num_samples, and MLDataset::samples.
FreeSpectrum()
void SignalProcessing::FreeSpectrum (FrequencySpectrum * spectrum)
Frees memory allocated for frequency spectrum.
Frees memory allocated for spectrum.
Parameters
spectrum Spectrum to free
Definition at line 1987 of file SignalProcessing.cpp.
References FrequencySpectrum::bins, and FrequencySpectrum::num_bins.
Referenced by ComputeFFT(), and ExtractMLFeatures().
GetIndex()
int SignalProcessing::GetIndex ()
Returns the current index.
Gets the current index of the signal processing vector.
Returns
Index
Current index
Definition at line 126 of file SignalProcessing.cpp.
Referenced by acquire_ecg_data(), analyze_statistics(), ApplyFilters(), GetSize(), main(), NormalDistributionRun(), preprocess_signal(), and PrintVector().
GetIndexLookupTable()
int SignalProcessing::GetIndexLookupTable (int ReceivedIndex)
Returns the normalized index from the lookup table.
Gets the index from the lookup table.
Parameters
ReceivedIndex Received index
Returns
Normalized index
Parameters
ReceivedIndex Received index
Returns
Returns the normalized index
Definition at line 444 of file SignalProcessing.cpp.
References MAX_INDX.
GetItem()
int SignalProcessing::GetItem ()
Returns the item identifier.
Gets the item number for the signal processing vector.
Returns
Item
Item number
Definition at line 138 of file SignalProcessing.cpp.
GetLastValue()
double SignalProcessing::GetLastValue ()
Returns the last value added.
Gets the last value of the signal processing vector.
Returns
Value
void
Definition at line 107 of file SignalProcessing.cpp.
GetMaxCapacity()
int SignalProcessing::GetMaxCapacity ()
Returns the maximum capacity of the vector.
Gets the max capacity of the signal processing vector.
Returns
Maximum capacity
Max capacity
Definition at line 120 of file SignalProcessing.cpp.
References NB_MAX_VALUES.
GetMean()
double SignalProcessing::GetMean ()
Calculates the mean (average) of the signal vector.
Returns
Mean value
Definition at line 498 of file SignalProcessing.cpp.
Referenced by analyze_statistics(), Autocorrelation(), CalculateAnomalyScore(), CrossCorrelation(), detect_events(), detect_r_peaks(), DetectAnomaliesZScore(), ExtractMLFeatures(), FindMostAnomalousSegment(), GetVariance(), main(), preprocess_signal(), SaveSignalToHDF5(), and SegmentByMarkers().
GetMovingAverage()
double SignalProcessing::GetMovingAverage (int window_size)
Calculates the moving average of the last window_size values.
Parameters
window_size Number of values to average
Returns
Moving average value
Definition at line 460 of file SignalProcessing.cpp.
GetMovingAverageVector()
void SignalProcessing::GetMovingAverageVector (double * out_vector, int window_size)
Calculates the moving average for each position and stores it in out_vector.
Parameters
out_vector Destination vector
window_size Number of values to average
Definition at line 478 of file SignalProcessing.cpp.
Referenced by preprocess_signal().
GetPeakValue()
double SignalProcessing::GetPeakValue (int peak_index)
Gets the value at a specific peak index.
Parameters
peak_index Index of the peak in the signal vector
Returns
Value at the peak
Definition at line 882 of file SignalProcessing.cpp.
Referenced by detect_r_peaks().
GetPowerInBand()
double SignalProcessing::GetPowerInBand (FrequencySpectrum * spectrum, double freq_low, double freq_high)
Calculates power in a frequency band.
Parameters
spectrum Frequency spectrum to analyze
freq_low Lower frequency bound (Hz)
freq_high Upper frequency bound (Hz)
Returns
Total power in the frequency band
Parameters
spectrum Frequency spectrum
freq_low Lower frequency bound
freq_high Upper frequency bound
Returns
Power in band
Definition at line 1880 of file SignalProcessing.cpp.
References FrequencySpectrum::bins, FrequencyBin::frequency, FrequencySpectrum::num_bins, and FrequencyBin::power.
Referenced by ExtractMLFeatures().
GetSize()
int SignalProcessing::GetSize ()
Returns the current size of the vector.
Gets the size of the signal processing vector.
Returns
Size
Current index
Definition at line 132 of file SignalProcessing.cpp.
References GetIndex().
GetStandardDeviation()
double SignalProcessing::GetStandardDeviation ()
Calculates the standard deviation of the signal vector.
Returns
Standard deviation value
Definition at line 523 of file SignalProcessing.cpp.
References GetVariance().
Referenced by analyze_statistics(), CalculateAnomalyScore(), detect_events(), detect_r_peaks(), DetectAnomaliesZScore(), ExtractMLFeatures(), FindMostAnomalousSegment(), main(), preprocess_signal(), and SaveSignalToHDF5().
GetThresholdCrossingFlag()
bool SignalProcessing::GetThresholdCrossingFlag ()
Gets the threshold crossing flag status.
Returns
True if threshold crossing was detected
Definition at line 639 of file SignalProcessing.cpp.
Referenced by detect_events().
GetTimespec()
void SignalProcessing::GetTimespec (struct timespec * td, int index)
Gets the timestamp for a value in the vector.
Gets the timestamp for a value in the signal processing vector.
Parameters
td timespec struct to store the timestamp
index Value index
td Contains the timestamp of the signal value at index
index The index of the signal value
Returns
void
Definition at line 96 of file SignalProcessing.cpp.
GetTimestamp()
struct timespec SignalProcessing::GetTimestamp (int index)
Gets the timestamp at a specific index.
Parameters
index Index in the signal vector
Returns
Timestamp at the specified index
Definition at line 904 of file SignalProcessing.cpp.
Referenced by main().
GetValue()
double SignalProcessing::GetValue (int index)
Gets the signal value at a specific index.
Parameters
index Index in the signal vector
Returns
Value at the specified index
Definition at line 893 of file SignalProcessing.cpp.
Referenced by analyze_statistics().
GetVariance()
double SignalProcessing::GetVariance ()
Calculates the variance of the signal vector.
Returns
Variance value
Definition at line 510 of file SignalProcessing.cpp.
References GetMean().
Referenced by analyze_statistics(), ExtractMLFeatures(), GetStandardDeviation(), and SaveSignalToHDF5().
GetVector()
void SignalProcessing::GetVector (double * signalProc_vector)
Copies the signal vector to another vector.
Gets the signal processing vector.
Parameters
signalProc_vector Destination vector
signalProc_vector Contains the signal processing vector
Returns
void
Definition at line 145 of file SignalProcessing.cpp.
GetVectorInt()
void SignalProcessing::GetVectorInt (int * signalProc_vector, int size)
Copies the signal vector to an int vector.
Gets the signal processing vector as int.
Parameters
signalProc_vector Destination vector
size Size
signalProc_vector Contains int signal processing vector
Returns
void
Definition at line 158 of file SignalProcessing.cpp.
GetVectorWithOffset()
void SignalProcessing::GetVectorWithOffset (double * signalProc_vector, int size, int offset)
Copies the signal vector with offset.
Gets the signal processing vector with offset.
Parameters
signalProc_vector Destination vector
size Size
offset Offset
signalProc_vector Contains the signal processing vector
Returns
void
Definition at line 184 of file SignalProcessing.cpp.
GetZeroCrossingFlag()
bool SignalProcessing::GetZeroCrossingFlag ()
Gets the zero crossing flag status.
Returns
True if zero crossing was detected
Definition at line 646 of file SignalProcessing.cpp.
InitVector()
void SignalProcessing::InitVector (double * values, int size)
Initializes the signal vector with given values.
Initializes the signal processing vector.
Parameters
values Source vector
size Size
values Contains signal processing vector which will be copied to SignalVector
size Contains size of the signal processing vector which will be copied to SignalVector
Returns
void
Definition at line 198 of file SignalProcessing.cpp.
InterpolateLinear()
int SignalProcessing::InterpolateLinear (int factor, double * out_vector)
Interpolates signal using linear interpolation (upsampling)
Interpolates signal using linear interpolation.
Parameters
factor Interpolation factor (e.g., 2 = double samples, 4 = quadruple)
out_vector Output array for interpolated signal (size >= GetIndex()*factor)
Returns
Number of samples in interpolated signal
Increases sampling rate by inserting linearly interpolated values between existing samples.
Parameters
factor Interpolation factor
out_vector Output array
Returns
Number of output samples
Definition at line 2973 of file SignalProcessing.cpp.
Referenced by Resample().
KalmanFilter()
void SignalProcessing::KalmanFilter (double process_noise, double measurement_noise, double * out_vector, double initial_estimate = 0.0, double initial_error = 1.0)
Applies a simple 1D Kalman filter for signal denoising.
Parameters
process_noise Process noise covariance (Q)
measurement_noise Measurement noise covariance (R)
out_vector Output vector for filtered values (size >= GetIndex())
initial_estimate Initial state estimate (use 0 if unknown)
initial_error Initial error covariance (use 1.0 if unknown)
process_noise Process noise covariance (Q)
measurement_noise Measurement noise covariance (R)
out_vector Output vector for filtered values
initial_estimate Initial state estimate
initial_error Initial error covariance
Definition at line 920 of file SignalProcessing.cpp.
Referenced by ApplyFilters().
MedianFilter()
void SignalProcessing::MedianFilter (int window_size, double * out_vector)
Applies median filter for noise removal.
Parameters
window_size Window size (must be odd number, e.g., 3, 5, 7)
out_vector Output vector for filtered values (size >= GetIndex())
window_size Window size (must be odd)
out_vector Output vector for filtered values
Definition at line 1090 of file SignalProcessing.cpp.
Referenced by ApplyFilters().
MultiplyWithValue()
void SignalProcessing::MultiplyWithValue (double value, int size)
Multiplies the signal vector by a value.
Multiplies the signal processing vector with a scalar value.
Parameters
value Value
size Size
value Value
size Number of elements to multiply
Returns
void
Definition at line 213 of file SignalProcessing.cpp.
NormalDistributionCalculate()
void SignalProcessing::NormalDistributionCalculate (double * data, int size, prob_dist * pd)
Calculates the normal distribution.
Parameters
data Data vector
size Size
pd Distribution struct
data Contains values
size Number of elements to add
pd Probability distribution
Returns
void
Definition at line 291 of file SignalProcessing.cpp.
References CompareProbDistItem(), prob_dist::count, prob_dist_item::frequency, prob_dist::items, M_E, M_PI, prob_dist_item::normal_frequency, prob_dist_item::normal_probability, prob_dist_item::probability, prob_dist::total_frequency, prob_dist::total_normal_frequency, prob_dist::total_normal_probability, prob_dist::total_probability, and prob_dist_item::value.
Referenced by NormalDistributionRun().
NormalDistributionCreate()
prob_dist * SignalProcessing::NormalDistributionCreate ()
Creates the normal distribution struct.
Creates a normal distribution.
Returns
Pointer to created struct
prob_dist
Definition at line 271 of file SignalProcessing.cpp.
References prob_dist::count, prob_dist::items, prob_dist::total_normal_frequency, prob_dist::total_normal_probability, and prob_dist::total_probability.
Referenced by NormalDistributionRun(), and SignalProcessing().
NormalDistributionFree()
void SignalProcessing::NormalDistributionFree ()
Frees memory for probability distribution.
Frees memory allocated for prob_dist.
Parameters
pd Probability distribution
Returns
void
Definition at line 384 of file SignalProcessing.cpp.
References prob_dist::items.
NormalDistributionPrint()
void SignalProcessing::NormalDistributionPrint (prob_dist * pd)
Prints the normal distribution.
Parameters
pd Distribution struct
pd Probability distribution
Returns
void
Definition at line 365 of file SignalProcessing.cpp.
References prob_dist::count, prob_dist_item::frequency, prob_dist::items, prob_dist_item::normal_frequency, prob_dist_item::normal_probability, prob_dist_item::probability, prob_dist::total_frequency, prob_dist::total_normal_frequency, prob_dist::total_normal_probability, prob_dist::total_probability, and prob_dist_item::value.
NormalDistributionRun()
void SignalProcessing::NormalDistributionRun ()
Runs the normal distribution calculation.
Computes the normal distribution and prints the result.
Returns
void
Definition at line 413 of file SignalProcessing.cpp.
References GetIndex(), NormalDistributionCalculate(), and NormalDistributionCreate().
NormalizeDataset()
bool SignalProcessing::NormalizeDataset (MLDataset * dataset, MLTrainingStats * stats) static
Normalizes all samples in a dataset using training statistics.
Normalizes all samples in dataset.
Parameters
dataset Dataset to normalize (modified in place)
stats Training statistics to use for normalization
Returns
true if successful, false otherwise
Parameters
dataset Dataset to normalize
stats Training statistics
Returns
true if successful
Definition at line 2513 of file SignalProcessing.cpp.
References MLTrainingStats::mean_values, NormalizeMLFeatures(), MLDataset::num_samples, MLDataset::samples, and MLTrainingStats::std_values.
NormalizeMLFeatures()
void SignalProcessing::NormalizeMLFeatures (MLFeatureVector * features, double * mean_values, double * std_values) static
Normalizes feature vector for ML input (z-score normalization)
Normalizes features using z-score normalization.
Parameters
features Feature vector to normalize
mean_values Array of mean values for each feature (size 21)
std_values Array of std dev values for each feature (size 21)
Apply this before feeding to neural networks for better convergence Compute mean_values and std_values from your training dataset
Parameters
features Feature vector to normalize
mean_values Mean values from training set
std_values Std dev values from training set
Definition at line 2290 of file SignalProcessing.cpp.
References MLFeatureVector::autocorr_peak, MLFeatureVector::crest_factor, MLFeatureVector::dominant_frequency, MLFeatureVector::energy, ExportFeaturesToArray(), MLFeatureVector::kurtosis, MLFeatureVector::mean, MLFeatureVector::mean_crossing_rate, MLFeatureVector::peak_to_peak, MLFeatureVector::power_high_freq, MLFeatureVector::power_low_freq, MLFeatureVector::power_mid_freq, MLFeatureVector::rms, MLFeatureVector::skewness, MLFeatureVector::spectral_centroid, MLFeatureVector::spectral_entropy, MLFeatureVector::spectral_spread, MLFeatureVector::std_dev, MLFeatureVector::total_power, MLFeatureVector::variance, and MLFeatureVector::zero_crossing_rate.
Referenced by NormalizeDataset().
NormalizeVector()
void SignalProcessing::NormalizeVector ()
Normalizes the signal vector to [0, 1] range.
Definition at line 529 of file SignalProcessing.cpp.
PrintVector()
void SignalProcessing::PrintVector ()
Prints the signal vector.
Prints the signal processing vector.
Returns
void
Definition at line 171 of file SignalProcessing.cpp.
References GetIndex().
Resample()
int SignalProcessing::Resample (double current_rate, double target_rate, double * out_vector)
Resamples signal to a new sampling rate.
Resamples signal to new sampling rate.
Parameters
current_rate Current sampling rate in Hz
target_rate Target sampling rate in Hz
out_vector Output array for resampled signal (size >= calculated new size)
Returns
Number of samples in resampled signal
Combines decimation and interpolation to achieve arbitrary resampling. Example: 100 Hz → 48 Hz for audio processing
Parameters
current_rate Current sampling rate in Hz
target_rate Target sampling rate in Hz
out_vector Output array
Returns
Number of output samples
Definition at line 3020 of file SignalProcessing.cpp.
References Decimate(), and InterpolateLinear().
ScaleVector()
void SignalProcessing::ScaleVector (double new_min, double new_max)
Scales the signal vector to a given range [new_min, new_max].
Parameters
new_min Minimum value of the new range
new_max Maximum value of the new range
Definition at line 549 of file SignalProcessing.cpp.
Referenced by preprocess_signal().
SegmentByMarkers()
int SignalProcessing::SegmentByMarkers (int * marker_indices, int num_markers, SegmentStats * segment_stats)
Segments signal by markers/tags (e.g., turbine blades)
Segments signal by markers and calculates statistics for each segment.
Parameters
marker_indices Array of indices where each segment starts (e.g., blade positions)
num_markers Number of markers
segment_stats Output array to store statistics for each segment
Returns
Number of segments analyzed
Parameters
marker_indices Array of indices where each segment starts
num_markers Number of markers
segment_stats Output array for segment statistics
Returns
Number of segments analyzed
Definition at line 1324 of file SignalProcessing.cpp.
References SegmentStats::anomaly_score, SegmentStats::end_index, GetMean(), SegmentStats::max_value, SegmentStats::mean, SegmentStats::min_value, SegmentStats::num_points, SegmentStats::peak_to_peak, SegmentStats::rms, SegmentStats::segment_id, SegmentStats::start_index, and SegmentStats::std_dev.
Referenced by FindMostAnomalousSegment().
SetItem()
void SignalProcessing::SetItem (int Item)
Sets the item identifier.
Sets the item of the signal processing vector.
Parameters
Item Item value
Item The item
Returns
void
Definition at line 114 of file SignalProcessing.cpp.
SubstractWithValue()
void SignalProcessing::SubstractWithValue (double value, int size)
Subtracts a value from the signal vector.
Subtracts a scalar value from the signal processing vector.
Parameters
value Value
size Size
value Value
size Number of elements to subtract
Returns
void
Definition at line 227 of file SignalProcessing.cpp.
WaveletDenoise()
void SignalProcessing::WaveletDenoise (double threshold, double * out_vector, int level = 1)
Applies wavelet denoising using soft thresholding.
Parameters
threshold Threshold value for wavelet coefficients
out_vector Output vector for denoised values (size >= GetIndex())
level Decomposition level (1-3, default 1)
threshold Threshold value for wavelet coefficients
out_vector Output vector for denoised values
level Decomposition level
Definition at line 1040 of file SignalProcessing.cpp.
Referenced by ApplyFilters().
The documentation for this class was generated from the following files:
source/SignalProcessing.h
source/SignalProcessing.cpp