SignalProcessing: SignalRecorder Class Reference
SignalRecorder Class Reference
#include <SignalRecorder.hpp>
Public Member Functions
SignalRecorder (const std::string &filename)
~SignalRecorder ()
void addMetadata (const std::string &groupName, const std::string &key, const std::string &value)
void addFloatVector (const std::string &path, const std::string &datasetName, const std::vector< float > &data, const std::string &units="")
void addDoubleVector (const std::string &path, const std::string &datasetName, const std::vector< double > &data, const std::string &units="")
void addSynchronizedChannels (const std::string &path, const std::vector< double > &timestamps, const std::vector< std::pair< std::string, std::vector< float > > > &channels)
Detailed Description
Definition at line 10 of file SignalRecorder.hpp.
Constructor & Destructor Documentation
SignalRecorder()
SignalRecorder::SignalRecorder (const std::string & filename) inline
Definition at line 12 of file SignalRecorder.hpp.
~SignalRecorder()
SignalRecorder::~SignalRecorder () inline
Definition at line 20 of file SignalRecorder.hpp.
Member Function Documentation
addDoubleVector()
void SignalRecorder::addDoubleVector (const std::string & path, const std::string & datasetName, const std::vector< double > & data, const std::string & units = "") inline
Definition at line 73 of file SignalRecorder.hpp.
Referenced by addSynchronizedChannels(), SignalProcessing::ExportDatasetToH5(), SignalProcessing::ExportMLFeaturesToH5(), and SignalProcessing::ExportTrainingStatsToH5().
addFloatVector()
void SignalRecorder::addFloatVector (const std::string & path, const std::string & datasetName, const std::vector< float > & data, const std::string & units = "") inline
Definition at line 46 of file SignalRecorder.hpp.
Referenced by addSynchronizedChannels(), and SaveSignalToHDF5().
addMetadata()
void SignalRecorder::addMetadata (const std::string & groupName, const std::string & key, const std::string & value) inline
Definition at line 27 of file SignalRecorder.hpp.
Referenced by addSynchronizedChannels(), SignalProcessing::ExportDatasetToH5(), SignalProcessing::ExportMLFeaturesToH5(), SignalProcessing::ExportTrainingStatsToH5(), and SaveSignalToHDF5().
addSynchronizedChannels()
void SignalRecorder::addSynchronizedChannels (const std::string & path, const std::vector< double > & timestamps, const std::vector< std::pair< std::string, std::vector< float > > > & channels) inline
Definition at line 100 of file SignalRecorder.hpp.
References addDoubleVector(), addFloatVector(), and addMetadata().
The documentation for this class was generated from the following file:
source/SignalRecorder.hpp