SignalProcessing: examples/config_integration_example.cpp File Reference
config_integration_example.cpp File Reference
#include "ImGuiConfig.hpp"
Functions
void InitializeConfiguration ()
void SaveConfiguration ()
void RenderConfigurationUI ()
void AutoSaveConfiguration ()
Variables
ImGuiConfigManager config_manager ("imgui_app.ini")
ImGuiAppConfig app_config = ImGuiConfigManager::GetDefaultConfig()
Function Documentation
AutoSaveConfiguration()
void AutoSaveConfiguration ()
Definition at line 160 of file config_integration_example.cpp.
References SaveConfiguration().
InitializeConfiguration()
void InitializeConfiguration ()
Definition at line 11 of file config_integration_example.cpp.
References anomaly_method, ImGuiAppConfig::anomaly_method, anomaly_threshold, ImGuiAppConfig::anomaly_threshold, app_config, apply_kalman, ImGuiAppConfig::apply_kalman, apply_median, ImGuiAppConfig::apply_median, apply_wavelet, ImGuiAppConfig::apply_wavelet, config_manager, current_signal, frequency, ImGuiAppConfig::frequency, kalman_measure, ImGuiAppConfig::kalman_measure, kalman_process, ImGuiAppConfig::kalman_process, ImGuiAppConfig::last_load_path, ImGuiAppConfig::last_save_path, load_filename, ImGuiConfigManager::LoadConfig(), median_window, ImGuiAppConfig::median_window, noise_level, ImGuiAppConfig::noise_level, sampling_rate, ImGuiAppConfig::sampling_rate, save_filename, session_info, ImGuiAppConfig::session_info, show_anomalies, ImGuiAppConfig::show_anomalies, show_ml_features, ImGuiAppConfig::show_ml_features, signal_length, ImGuiAppConfig::signal_length, and ImGuiAppConfig::signal_type.
Referenced by RenderConfigurationUI().
RenderConfigurationUI()
void RenderConfigurationUI ()
Definition at line 74 of file config_integration_example.cpp.
References anomaly_method, ImGuiAppConfig::anomaly_method, anomaly_threshold, ImGuiAppConfig::anomaly_threshold, app_config, apply_kalman, ImGuiAppConfig::apply_kalman, apply_median, ImGuiAppConfig::apply_median, apply_wavelet, ImGuiAppConfig::apply_wavelet, ImGui::BeginPopup(), ImGui::Button(), ImGui::CollapsingHeader(), config_manager, current_signal, ImGui::EndPopup(), frequency, ImGuiAppConfig::frequency, GenerateSignal(), ImGuiConfigManager::GetDefaultConfig(), InitializeConfiguration(), kalman_measure, ImGuiAppConfig::kalman_measure, kalman_process, ImGuiAppConfig::kalman_process, ImGuiAppConfig::last_load_path, ImGuiAppConfig::last_save_path, load_filename, ImGuiConfigManager::LoadConfig(), median_window, ImGuiAppConfig::median_window, noise_level, ImGuiAppConfig::noise_level, ImGui::OpenPopup(), ImGui::SameLine(), sampling_rate, ImGuiAppConfig::sampling_rate, save_filename, SaveConfiguration(), ImGui::Separator(), session_info, ImGuiAppConfig::session_info, show_anomalies, ImGuiAppConfig::show_anomalies, show_ml_features, ImGuiAppConfig::show_ml_features, signal_length, ImGuiAppConfig::signal_length, ImGuiAppConfig::signal_type, ImGui::Spacing(), ImGui::Text(), and ImGui::TextDisabled().
SaveConfiguration()
void SaveConfiguration ()
Definition at line 45 of file config_integration_example.cpp.
References anomaly_method, ImGuiAppConfig::anomaly_method, anomaly_threshold, ImGuiAppConfig::anomaly_threshold, app_config, apply_kalman, ImGuiAppConfig::apply_kalman, apply_median, ImGuiAppConfig::apply_median, apply_wavelet, ImGuiAppConfig::apply_wavelet, config_manager, current_signal, frequency, ImGuiAppConfig::frequency, kalman_measure, ImGuiAppConfig::kalman_measure, kalman_process, ImGuiAppConfig::kalman_process, ImGuiAppConfig::last_load_path, ImGuiAppConfig::last_save_path, load_filename, median_window, ImGuiAppConfig::median_window, noise_level, ImGuiAppConfig::noise_level, sampling_rate, ImGuiAppConfig::sampling_rate, save_filename, ImGuiConfigManager::SaveConfig(), session_info, ImGuiAppConfig::session_info, show_anomalies, ImGuiAppConfig::show_anomalies, show_ml_features, ImGuiAppConfig::show_ml_features, signal_length, ImGuiAppConfig::signal_length, and ImGuiAppConfig::signal_type.
Referenced by AutoSaveConfiguration(), and RenderConfigurationUI().
Variable Documentation
app_config
ImGuiAppConfig app_config = ImGuiConfigManager::GetDefaultConfig()
Definition at line 8 of file config_integration_example.cpp.
Referenced by InitializeConfiguration(), RenderConfigurationUI(), and SaveConfiguration().
config_manager
ImGuiConfigManager config_manager("imgui_app.ini") ("imgui_app.ini")
Referenced by InitializeConfiguration(), RenderConfigurationUI(), and SaveConfiguration().