SignalProcessing: examples/example_complete.cpp File Reference
example_complete.cpp File Reference
Complete example demonstrating all SignalProcessing features.
#include <stdio.h>
#include <math.h>
#include <time.h>
#include "../source/SignalProcessing.h"
Macros
#define M_PI 3.14159265358979323846
Functions
void acquire_ecg_data (SignalProcessing *sp, double duration_sec, double sampling_rate, double heart_rate)
Simulates ECG data acquisition.
void preprocess_signal (SignalProcessing *sp, SignalProcessing *sp_clean)
Preprocesses the signal.
void detect_r_peaks (SignalProcessing *sp, double sampling_rate)
Detects R-peaks and analyzes heart rate.
void detect_events (SignalProcessing *sp)
Detects arrhythmia events.
void analyze_statistics (SignalProcessing *sp)
Performs statistical analysis.
int main ()
Main function demonstrating complete workflow.
Detailed Description
Complete example demonstrating all SignalProcessing features.
This example shows a typical workflow for processing a simulated ECG signal:
Data acquisition with timestamps
Preprocessing (smoothing, normalization)
Feature detection (R-peaks)
Analysis (heart rate, statistics)
Event detection
Definition in file example_complete.cpp.
Macro Definition Documentation
M_PI
#define M_PI 3.14159265358979323846
Definition at line 19 of file example_complete.cpp.
Function Documentation
acquire_ecg_data()
void acquire_ecg_data (SignalProcessing * sp, double duration_sec, double sampling_rate, double heart_rate)
Simulates ECG data acquisition.
Parameters
sp SignalProcessing object to store data
duration_sec Duration in seconds
sampling_rate Sampling frequency (Hz)
heart_rate Heart rate in BPM
Definition at line 29 of file example_complete.cpp.
References SignalProcessing::AddValueWithTimestamp(), SignalProcessing::GetIndex(), M_PI, sampling_rate, and sp.
Referenced by main().
analyze_statistics()
void analyze_statistics (SignalProcessing * sp)
Performs statistical analysis.
Definition at line 236 of file example_complete.cpp.
References SignalProcessing::GetIndex(), SignalProcessing::GetMean(), SignalProcessing::GetStandardDeviation(), SignalProcessing::GetValue(), SignalProcessing::GetVariance(), and sp.
Referenced by main().
detect_events()
void detect_events (SignalProcessing * sp)
Detects arrhythmia events.
Definition at line 204 of file example_complete.cpp.
References SignalProcessing::DetectThresholdCrossing(), SignalProcessing::GetMean(), SignalProcessing::GetStandardDeviation(), SignalProcessing::GetThresholdCrossingFlag(), and sp.
Referenced by main().
detect_r_peaks()
void detect_r_peaks (SignalProcessing * sp, double sampling_rate)
Detects R-peaks and analyzes heart rate.
Definition at line 131 of file example_complete.cpp.
References SignalProcessing::DetectPeaksWithDistance(), SignalProcessing::DetectPeaksWithThreshold(), SignalProcessing::GetMean(), SignalProcessing::GetPeakValue(), SignalProcessing::GetStandardDeviation(), sampling_rate, and sp.
Referenced by main().
main()
int main ()
Main function demonstrating complete workflow.
Definition at line 269 of file example_complete.cpp.
References acquire_ecg_data(), analyze_statistics(), detect_events(), detect_r_peaks(), SignalProcessing::GetIndex(), SignalProcessing::GetTimestamp(), preprocess_signal(), and sampling_rate.
preprocess_signal()
void preprocess_signal (SignalProcessing * sp, SignalProcessing * sp_clean)
Preprocesses the signal.
Definition at line 105 of file example_complete.cpp.
References SignalProcessing::AddValue(), SignalProcessing::GetIndex(), SignalProcessing::GetMean(), SignalProcessing::GetMovingAverageVector(), SignalProcessing::GetStandardDeviation(), SignalProcessing::ScaleVector(), and sp.
Referenced by main().