SignalProcessing: examples/imgui/backends/imgui_impl_sdl3.cpp File Reference
imgui_impl_sdl3.cpp File Reference
#include "imgui.h"
#include "imgui_impl_sdl3.h"
#include <SDL3/SDL.h>
#include <stdio.h>
Classes
struct ImGui_ImplSDL3_Data
Macros
#define SDL_HAS_CAPTURE_AND_GLOBAL_MOUSE 1
#define SDLK_APOSTROPHE SDLK_QUOTE
#define SDLK_GRAVE SDLK_BACKQUOTE
Functions
static ImGui_ImplSDL3_Data * ImGui_ImplSDL3_GetBackendData ()
static void ImGui_ImplSDL3_UpdateIme ()
static const char * ImGui_ImplSDL3_GetClipboardText (ImGuiContext *)
static void ImGui_ImplSDL3_SetClipboardText (ImGuiContext *, const char *text)
static ImGuiViewport * ImGui_ImplSDL3_GetViewportForWindowID (SDL_WindowID window_id)
static void ImGui_ImplSDL3_PlatformSetImeData (ImGuiContext *, ImGuiViewport *, ImGuiPlatformImeData *data)
ImGuiKey ImGui_ImplSDL3_KeyEventToImGuiKey (SDL_Keycode keycode, SDL_Scancode scancode)
static void ImGui_ImplSDL3_UpdateKeyModifiers (SDL_Keymod sdl_key_mods)
bool ImGui_ImplSDL3_ProcessEvent (const SDL_Event *event)
static void ImGui_ImplSDL3_SetupPlatformHandles (ImGuiViewport *viewport, SDL_Window *window)
static bool ImGui_ImplSDL3_Init (SDL_Window *window, SDL_Renderer *renderer, void *sdl_gl_context)
bool ImGui_ImplSDL3_InitForOpenGL (SDL_Window *window, void *sdl_gl_context)
bool ImGui_ImplSDL3_InitForVulkan (SDL_Window *window)
bool ImGui_ImplSDL3_InitForD3D (SDL_Window *window)
bool ImGui_ImplSDL3_InitForMetal (SDL_Window *window)
bool ImGui_ImplSDL3_InitForSDLRenderer (SDL_Window *window, SDL_Renderer *renderer)
bool ImGui_ImplSDL3_InitForSDLGPU (SDL_Window *window)
bool ImGui_ImplSDL3_InitForOther (SDL_Window *window)
static void ImGui_ImplSDL3_CloseGamepads ()
void ImGui_ImplSDL3_Shutdown ()
static void ImGui_ImplSDL3_UpdateMouseData ()
static void ImGui_ImplSDL3_UpdateMouseCursor ()
void ImGui_ImplSDL3_SetGamepadMode (ImGui_ImplSDL3_GamepadMode mode, SDL_Gamepad **manual_gamepads_array, int manual_gamepads_count)
static void ImGui_ImplSDL3_UpdateGamepadButton (ImGui_ImplSDL3_Data *bd, ImGuiIO &io, ImGuiKey key, SDL_GamepadButton button_no)
static float Saturate (float v)
static void ImGui_ImplSDL3_UpdateGamepadAnalog (ImGui_ImplSDL3_Data *bd, ImGuiIO &io, ImGuiKey key, SDL_GamepadAxis axis_no, float v0, float v1)
static void ImGui_ImplSDL3_UpdateGamepads ()
static void ImGui_ImplSDL3_GetWindowSizeAndFramebufferScale (SDL_Window *window, ImVec2 *out_size, ImVec2 *out_framebuffer_scale)
void ImGui_ImplSDL3_NewFrame ()
Macro Definition Documentation
SDL_HAS_CAPTURE_AND_GLOBAL_MOUSE
#define SDL_HAS_CAPTURE_AND_GLOBAL_MOUSE 1
Definition at line 91 of file imgui_impl_sdl3.cpp.
SDLK_APOSTROPHE
#define SDLK_APOSTROPHE SDLK_QUOTE
Definition at line 98 of file imgui_impl_sdl3.cpp.
SDLK_GRAVE
#define SDLK_GRAVE SDLK_BACKQUOTE
Definition at line 101 of file imgui_impl_sdl3.cpp.
Function Documentation
ImGui_ImplSDL3_CloseGamepads()
static void ImGui_ImplSDL3_CloseGamepads () static
Definition at line 706 of file imgui_impl_sdl3.cpp.
References ImGui_ImplSDL3_Data::GamepadMode, ImGui_ImplSDL3_Data::Gamepads, ImGui_ImplSDL3_GamepadMode_Manual, ImGui_ImplSDL3_GetBackendData(), and ImVector< T >::resize().
Referenced by ImGui_ImplSDL3_SetGamepadMode(), ImGui_ImplSDL3_Shutdown(), and ImGui_ImplSDL3_UpdateGamepads().
ImGui_ImplSDL3_GetBackendData()
static ImGui_ImplSDL3_Data * ImGui_ImplSDL3_GetBackendData () static
Definition at line 140 of file imgui_impl_sdl3.cpp.
References ImGuiIO::BackendPlatformUserData, ImGui::GetCurrentContext(), and ImGui::GetIO().
Referenced by ImGui_ImplSDL3_CloseGamepads(), ImGui_ImplSDL3_GetClipboardText(), ImGui_ImplSDL3_GetViewportForWindowID(), ImGui_ImplSDL3_NewFrame(), ImGui_ImplSDL3_PlatformSetImeData(), ImGui_ImplSDL3_ProcessEvent(), ImGui_ImplSDL3_SetGamepadMode(), ImGui_ImplSDL3_Shutdown(), ImGui_ImplSDL3_UpdateGamepads(), ImGui_ImplSDL3_UpdateIme(), ImGui_ImplSDL3_UpdateMouseCursor(), and ImGui_ImplSDL3_UpdateMouseData().
ImGui_ImplSDL3_GetClipboardText()
static const char * ImGui_ImplSDL3_GetClipboardText (ImGuiContext *) static
Definition at line 149 of file imgui_impl_sdl3.cpp.
References ImGui_ImplSDL3_Data::ClipboardTextData, and ImGui_ImplSDL3_GetBackendData().
Referenced by ImGui_ImplSDL3_Init().
ImGui_ImplSDL3_GetViewportForWindowID()
static ImGuiViewport * ImGui_ImplSDL3_GetViewportForWindowID (SDL_WindowID window_id) static
Definition at line 163 of file imgui_impl_sdl3.cpp.
References ImGui::GetMainViewport(), ImGui_ImplSDL3_GetBackendData(), and ImGui_ImplSDL3_Data::WindowID.
Referenced by ImGui_ImplSDL3_ProcessEvent().
ImGui_ImplSDL3_GetWindowSizeAndFramebufferScale()
static void ImGui_ImplSDL3_GetWindowSizeAndFramebufferScale (SDL_Window * window, ImVec2 * out_size, ImVec2 * out_framebuffer_scale) static
Definition at line 809 of file imgui_impl_sdl3.cpp.
Referenced by ImGui_ImplSDL3_NewFrame().
ImGui_ImplSDL3_Init()
static bool ImGui_ImplSDL3_Init (SDL_Window * window, SDL_Renderer * renderer, void * sdl_gl_context) static
Definition at line 492 of file imgui_impl_sdl3.cpp.
References ImGuiIO::BackendFlags, ImGui_ImplSDL3_Data::BackendPlatformName, ImGuiIO::BackendPlatformName, ImGuiIO::BackendPlatformUserData, ImGui_ImplSDL3_Data::GamepadMode, ImGui::GetIO(), ImGui::GetMainViewport(), ImGui::GetPlatformIO(), IM_ASSERT, IM_NEW, IM_UNUSED, IMGUI_CHECKVERSION, ImGui_ImplSDL3_GamepadMode_AutoFirst, ImGui_ImplSDL3_GetClipboardText(), ImGui_ImplSDL3_PlatformSetImeData(), ImGui_ImplSDL3_SetClipboardText(), ImGui_ImplSDL3_SetupPlatformHandles(), ImGuiBackendFlags_HasMouseCursors, ImGuiBackendFlags_HasSetMousePos, ImGuiMouseCursor_Arrow, ImGuiMouseCursor_Hand, ImGuiMouseCursor_NotAllowed, ImGuiMouseCursor_Progress, ImGuiMouseCursor_ResizeAll, ImGuiMouseCursor_ResizeEW, ImGuiMouseCursor_ResizeNESW, ImGuiMouseCursor_ResizeNS, ImGuiMouseCursor_ResizeNWSE, ImGuiMouseCursor_TextInput, ImGuiMouseCursor_Wait, ImGui_ImplSDL3_Data::MouseCanUseCapture, ImGui_ImplSDL3_Data::MouseCanUseGlobalState, ImGui_ImplSDL3_Data::MouseCursors, ImGuiPlatformIO::Platform_GetClipboardTextFn, ImGuiPlatformIO::Platform_OpenInShellFn, ImGuiPlatformIO::Platform_SetClipboardTextFn, ImGuiPlatformIO::Platform_SetImeDataFn, ImGui_ImplSDL3_Data::Renderer, ImGui_ImplSDL3_Data::WantUpdateGamepadsList, ImGui_ImplSDL3_Data::Window, and ImGui_ImplSDL3_Data::WindowID.
Referenced by ImGui_ImplSDL3_InitForD3D(), ImGui_ImplSDL3_InitForMetal(), ImGui_ImplSDL3_InitForOpenGL(), ImGui_ImplSDL3_InitForOther(), ImGui_ImplSDL3_InitForSDLGPU(), ImGui_ImplSDL3_InitForSDLRenderer(), and ImGui_ImplSDL3_InitForVulkan().
ImGui_ImplSDL3_InitForD3D()
bool ImGui_ImplSDL3_InitForD3D (SDL_Window * window)
Definition at line 582 of file imgui_impl_sdl3.cpp.
References IM_ASSERT, and ImGui_ImplSDL3_Init().
Referenced by main().
ImGui_ImplSDL3_InitForMetal()
bool ImGui_ImplSDL3_InitForMetal (SDL_Window * window)
Definition at line 590 of file imgui_impl_sdl3.cpp.
References ImGui_ImplSDL3_Init().
ImGui_ImplSDL3_InitForOpenGL()
bool ImGui_ImplSDL3_InitForOpenGL (SDL_Window * window, void * sdl_gl_context)
Definition at line 571 of file imgui_impl_sdl3.cpp.
References IM_UNUSED, and ImGui_ImplSDL3_Init().
Referenced by main().
ImGui_ImplSDL3_InitForOther()
bool ImGui_ImplSDL3_InitForOther (SDL_Window * window)
Definition at line 605 of file imgui_impl_sdl3.cpp.
References ImGui_ImplSDL3_Init().
Referenced by main().
ImGui_ImplSDL3_InitForSDLGPU()
bool ImGui_ImplSDL3_InitForSDLGPU (SDL_Window * window)
Definition at line 600 of file imgui_impl_sdl3.cpp.
References ImGui_ImplSDL3_Init().
Referenced by main().
ImGui_ImplSDL3_InitForSDLRenderer()
bool ImGui_ImplSDL3_InitForSDLRenderer (SDL_Window * window, SDL_Renderer * renderer)
Definition at line 595 of file imgui_impl_sdl3.cpp.
References ImGui_ImplSDL3_Init().
Referenced by main().
ImGui_ImplSDL3_InitForVulkan()
bool ImGui_ImplSDL3_InitForVulkan (SDL_Window * window)
Definition at line 577 of file imgui_impl_sdl3.cpp.
References ImGui_ImplSDL3_Init().
Referenced by main().
ImGui_ImplSDL3_KeyEventToImGuiKey()
ImGuiKey ImGui_ImplSDL3_KeyEventToImGuiKey (SDL_Keycode keycode, SDL_Scancode scancode)
Definition at line 211 of file imgui_impl_sdl3.cpp.
References ImGuiKey_0, ImGuiKey_1, ImGuiKey_2, ImGuiKey_3, ImGuiKey_4, ImGuiKey_5, ImGuiKey_6, ImGuiKey_7, ImGuiKey_8, ImGuiKey_9, ImGuiKey_A, ImGuiKey_Apostrophe, ImGuiKey_AppBack, ImGuiKey_AppForward, ImGuiKey_B, ImGuiKey_Backslash, ImGuiKey_Backspace, ImGuiKey_C, ImGuiKey_CapsLock, ImGuiKey_Comma, ImGuiKey_D, ImGuiKey_Delete, ImGuiKey_DownArrow, ImGuiKey_E, ImGuiKey_End, ImGuiKey_Enter, ImGuiKey_Equal, ImGuiKey_Escape, ImGuiKey_F, ImGuiKey_F1, ImGuiKey_F10, ImGuiKey_F11, ImGuiKey_F12, ImGuiKey_F13, ImGuiKey_F14, ImGuiKey_F15, ImGuiKey_F16, ImGuiKey_F17, ImGuiKey_F18, ImGuiKey_F19, ImGuiKey_F2, ImGuiKey_F20, ImGuiKey_F21, ImGuiKey_F22, ImGuiKey_F23, ImGuiKey_F24, ImGuiKey_F3, ImGuiKey_F4, ImGuiKey_F5, ImGuiKey_F6, ImGuiKey_F7, ImGuiKey_F8, ImGuiKey_F9, ImGuiKey_G, ImGuiKey_GraveAccent, ImGuiKey_H, ImGuiKey_Home, ImGuiKey_I, ImGuiKey_Insert, ImGuiKey_J, ImGuiKey_K, ImGuiKey_Keypad0, ImGuiKey_Keypad1, ImGuiKey_Keypad2, ImGuiKey_Keypad3, ImGuiKey_Keypad4, ImGuiKey_Keypad5, ImGuiKey_Keypad6, ImGuiKey_Keypad7, ImGuiKey_Keypad8, ImGuiKey_Keypad9, ImGuiKey_KeypadAdd, ImGuiKey_KeypadDecimal, ImGuiKey_KeypadDivide, ImGuiKey_KeypadEnter, ImGuiKey_KeypadEqual, ImGuiKey_KeypadMultiply, ImGuiKey_KeypadSubtract, ImGuiKey_L, ImGuiKey_LeftAlt, ImGuiKey_LeftArrow, ImGuiKey_LeftBracket, ImGuiKey_LeftCtrl, ImGuiKey_LeftShift, ImGuiKey_LeftSuper, ImGuiKey_M, ImGuiKey_Menu, ImGuiKey_Minus, ImGuiKey_N, ImGuiKey_None, ImGuiKey_NumLock, ImGuiKey_O, ImGuiKey_Oem102, ImGuiKey_P, ImGuiKey_PageDown, ImGuiKey_PageUp, ImGuiKey_Pause, ImGuiKey_Period, ImGuiKey_PrintScreen, ImGuiKey_Q, ImGuiKey_R, ImGuiKey_RightAlt, ImGuiKey_RightArrow, ImGuiKey_RightBracket, ImGuiKey_RightCtrl, ImGuiKey_RightShift, ImGuiKey_RightSuper, ImGuiKey_S, ImGuiKey_ScrollLock, ImGuiKey_Semicolon, ImGuiKey_Slash, ImGuiKey_Space, ImGuiKey_T, ImGuiKey_Tab, ImGuiKey_U, ImGuiKey_UpArrow, ImGuiKey_V, ImGuiKey_W, ImGuiKey_X, ImGuiKey_Y, and ImGuiKey_Z.
Referenced by ImGui_ImplSDL3_ProcessEvent().
ImGui_ImplSDL3_NewFrame()
void ImGui_ImplSDL3_NewFrame ()
Definition at line 832 of file imgui_impl_sdl3.cpp.
References ImGuiIO::AddMousePosEvent(), ImGuiIO::DeltaTime, ImGuiIO::DisplayFramebufferScale, ImGuiIO::DisplaySize, frequency, ImGui::GetFrameCount(), ImGui::GetIO(), IM_ASSERT, ImGui_ImplSDL3_GetBackendData(), ImGui_ImplSDL3_GetWindowSizeAndFramebufferScale(), ImGui_ImplSDL3_UpdateGamepads(), ImGui_ImplSDL3_UpdateIme(), ImGui_ImplSDL3_UpdateMouseCursor(), ImGui_ImplSDL3_UpdateMouseData(), ImGui_ImplSDL3_Data::MouseButtonsDown, ImGui_ImplSDL3_Data::MousePendingLeaveFrame, ImGui_ImplSDL3_Data::MouseWindowID, ImGui_ImplSDL3_Data::Time, and ImGui_ImplSDL3_Data::Window.
Referenced by main().
ImGui_ImplSDL3_PlatformSetImeData()
static void ImGui_ImplSDL3_PlatformSetImeData (ImGuiContext * , ImGuiViewport * , ImGuiPlatformImeData * data) static
Definition at line 169 of file imgui_impl_sdl3.cpp.
References ImGui_ImplSDL3_Data::ImeData, ImGui_ImplSDL3_Data::ImeDirty, ImGui_ImplSDL3_GetBackendData(), and ImGui_ImplSDL3_UpdateIme().
Referenced by ImGui_ImplSDL3_Init().
ImGui_ImplSDL3_ProcessEvent()
bool ImGui_ImplSDL3_ProcessEvent (const SDL_Event * event)
Definition at line 376 of file imgui_impl_sdl3.cpp.
References ImGuiIO::AddFocusEvent(), ImGuiIO::AddInputCharactersUTF8(), ImGuiIO::AddKeyEvent(), ImGuiIO::AddMouseButtonEvent(), ImGuiIO::AddMousePosEvent(), ImGuiIO::AddMouseSourceEvent(), ImGuiIO::AddMouseWheelEvent(), ImGui::GetFrameCount(), ImGui::GetIO(), IM_ASSERT, ImGui_ImplSDL3_GetBackendData(), ImGui_ImplSDL3_GetViewportForWindowID(), ImGui_ImplSDL3_KeyEventToImGuiKey(), ImGui_ImplSDL3_UpdateKeyModifiers(), ImGuiMouseSource_Mouse, ImGuiMouseSource_TouchScreen, ImGui_ImplSDL3_Data::MouseButtonsDown, ImGui_ImplSDL3_Data::MousePendingLeaveFrame, ImGui_ImplSDL3_Data::MouseWindowID, ImGuiIO::SetKeyEventNativeData(), ImGui_ImplSDL3_Data::WantUpdateGamepadsList, ImVec2::x, and ImVec2::y.
Referenced by main().
ImGui_ImplSDL3_SetClipboardText()
static void ImGui_ImplSDL3_SetClipboardText (ImGuiContext * , const char * text) static
Definition at line 158 of file imgui_impl_sdl3.cpp.
Referenced by ImGui_ImplSDL3_Init().
ImGui_ImplSDL3_SetGamepadMode()
void ImGui_ImplSDL3_SetGamepadMode (ImGui_ImplSDL3_GamepadMode mode, SDL_Gamepad ** manual_gamepads_array, int manual_gamepads_count)
Definition at line 715 of file imgui_impl_sdl3.cpp.
References ImGui_ImplSDL3_Data::GamepadMode, ImGui_ImplSDL3_Data::Gamepads, IM_ASSERT, ImGui_ImplSDL3_CloseGamepads(), ImGui_ImplSDL3_GamepadMode_Manual, ImGui_ImplSDL3_GetBackendData(), ImVector< T >::push_back(), and ImGui_ImplSDL3_Data::WantUpdateGamepadsList.
ImGui_ImplSDL3_SetupPlatformHandles()
static void ImGui_ImplSDL3_SetupPlatformHandles (ImGuiViewport * viewport, SDL_Window * window) static
Definition at line 481 of file imgui_impl_sdl3.cpp.
References ImGuiViewport::PlatformHandle, and ImGuiViewport::PlatformHandleRaw.
Referenced by ImGui_ImplSDL3_Init().
ImGui_ImplSDL3_Shutdown()
void ImGui_ImplSDL3_Shutdown ()
Definition at line 612 of file imgui_impl_sdl3.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendPlatformName, ImGuiIO::BackendPlatformUserData, ImGuiPlatformIO::ClearPlatformHandlers(), ImGui_ImplSDL3_Data::ClipboardTextData, ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplSDL3_CloseGamepads(), ImGui_ImplSDL3_GetBackendData(), ImGuiBackendFlags_HasGamepad, ImGuiBackendFlags_HasMouseCursors, ImGuiBackendFlags_HasSetMousePos, ImGuiMouseCursor_COUNT, and ImGui_ImplSDL3_Data::MouseCursors.
Referenced by main().
ImGui_ImplSDL3_UpdateGamepadAnalog()
static void ImGui_ImplSDL3_UpdateGamepadAnalog (ImGui_ImplSDL3_Data * bd, ImGuiIO & io, ImGuiKey key, SDL_GamepadAxis axis_no, float v0, float v1) static
Definition at line 742 of file imgui_impl_sdl3.cpp.
References ImGuiIO::AddKeyAnalogEvent(), ImGui_ImplSDL3_Data::Gamepads, and Saturate().
Referenced by ImGui_ImplSDL3_UpdateGamepads().
ImGui_ImplSDL3_UpdateGamepadButton()
static void ImGui_ImplSDL3_UpdateGamepadButton (ImGui_ImplSDL3_Data * bd, ImGuiIO & io, ImGuiKey key, SDL_GamepadButton button_no) static
Definition at line 733 of file imgui_impl_sdl3.cpp.
References ImGuiIO::AddKeyEvent(), and ImGui_ImplSDL3_Data::Gamepads.
Referenced by ImGui_ImplSDL3_UpdateGamepads().
ImGui_ImplSDL3_UpdateGamepads()
static void ImGui_ImplSDL3_UpdateGamepads () static
Definition at line 754 of file imgui_impl_sdl3.cpp.
References ImGuiIO::BackendFlags, ImGui_ImplSDL3_Data::GamepadMode, ImGui_ImplSDL3_Data::Gamepads, ImGui::GetIO(), ImGui_ImplSDL3_CloseGamepads(), ImGui_ImplSDL3_GamepadMode_AutoFirst, ImGui_ImplSDL3_GamepadMode_Manual, ImGui_ImplSDL3_GetBackendData(), ImGui_ImplSDL3_UpdateGamepadAnalog(), ImGui_ImplSDL3_UpdateGamepadButton(), ImGuiBackendFlags_HasGamepad, ImGuiKey_GamepadBack, ImGuiKey_GamepadDpadDown, ImGuiKey_GamepadDpadLeft, ImGuiKey_GamepadDpadRight, ImGuiKey_GamepadDpadUp, ImGuiKey_GamepadFaceDown, ImGuiKey_GamepadFaceLeft, ImGuiKey_GamepadFaceRight, ImGuiKey_GamepadFaceUp, ImGuiKey_GamepadL1, ImGuiKey_GamepadL2, ImGuiKey_GamepadL3, ImGuiKey_GamepadLStickDown, ImGuiKey_GamepadLStickLeft, ImGuiKey_GamepadLStickRight, ImGuiKey_GamepadLStickUp, ImGuiKey_GamepadR1, ImGuiKey_GamepadR2, ImGuiKey_GamepadR3, ImGuiKey_GamepadRStickDown, ImGuiKey_GamepadRStickLeft, ImGuiKey_GamepadRStickRight, ImGuiKey_GamepadRStickUp, ImGuiKey_GamepadStart, ImVector< T >::push_back(), ImVector< T >::Size, and ImGui_ImplSDL3_Data::WantUpdateGamepadsList.
Referenced by ImGui_ImplSDL3_NewFrame().
ImGui_ImplSDL3_UpdateIme()
static void ImGui_ImplSDL3_UpdateIme () static
Definition at line 178 of file imgui_impl_sdl3.cpp.
References ImGui_ImplSDL3_Data::ImeData, ImGui_ImplSDL3_Data::ImeDirty, ImGui_ImplSDL3_Data::ImeWindow, and ImGui_ImplSDL3_GetBackendData().
Referenced by ImGui_ImplSDL3_NewFrame(), and ImGui_ImplSDL3_PlatformSetImeData().
ImGui_ImplSDL3_UpdateKeyModifiers()
static void ImGui_ImplSDL3_UpdateKeyModifiers (SDL_Keymod sdl_key_mods) static
Definition at line 362 of file imgui_impl_sdl3.cpp.
References ImGuiIO::AddKeyEvent(), ImGui::GetIO(), ImGuiMod_Alt, ImGuiMod_Ctrl, ImGuiMod_Shift, and ImGuiMod_Super.
Referenced by ImGui_ImplSDL3_ProcessEvent().
ImGui_ImplSDL3_UpdateMouseCursor()
static void ImGui_ImplSDL3_UpdateMouseCursor () static
Definition at line 680 of file imgui_impl_sdl3.cpp.
References ImGuiIO::ConfigFlags, ImGui::GetIO(), ImGui::GetMouseCursor(), ImGui_ImplSDL3_GetBackendData(), ImGuiConfigFlags_NoMouseCursorChange, ImGuiMouseCursor_Arrow, ImGuiMouseCursor_None, ImGui_ImplSDL3_Data::MouseCursors, ImGuiIO::MouseDrawCursor, and ImGui_ImplSDL3_Data::MouseLastCursor.
Referenced by ImGui_ImplSDL3_NewFrame().
ImGui_ImplSDL3_UpdateMouseData()
static void ImGui_ImplSDL3_UpdateMouseData () static
Definition at line 632 of file imgui_impl_sdl3.cpp.
References ImGuiIO::AddMousePosEvent(), ImGui::GetIO(), ImGui_ImplSDL3_GetBackendData(), ImGuiMouseButton_COUNT, ImGui::IsMouseDragging(), ImGui_ImplSDL3_Data::MouseButtonsDown, ImGui_ImplSDL3_Data::MouseCanUseCapture, ImGui_ImplSDL3_Data::MouseCanUseGlobalState, ImGuiIO::MousePos, ImGuiIO::WantSetMousePos, ImGui_ImplSDL3_Data::Window, ImVec2::x, and ImVec2::y.
Referenced by ImGui_ImplSDL3_NewFrame().
Saturate()
static float Saturate (float v) inline static
Definition at line 741 of file imgui_impl_sdl3.cpp.
Referenced by ImGui_ImplSDL3_UpdateGamepadAnalog().