SignalProcessing: examples/imgui/imgui_demo.cpp File Reference
imgui_demo.cpp File Reference
#include "imgui.h"
#include <ctype.h>
#include <limits.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <inttypes.h>
Classes
struct ImGuiDemoWindowData
struct ExampleTreeNode
struct ExampleMemberInfo
struct ExampleSelectionWithDeletion
struct ExampleDualListBox
struct ExampleAppConsole
struct ExampleAppLog
struct ExampleAppPropertyEditor
struct MyDocument
struct ExampleAppDocuments
struct ExampleAsset
struct ExampleAssetsBrowser
Namespaces
namespace ImGui
Macros
#define IM_NEWLINE "\n"
#define PRId64 "lld"
#define PRIu64 "llu"
#define IM_MIN(A, B) (((A) < (B)) ? (A) : (B))
#define IM_MAX(A, B) (((A) >= (B)) ? (A) : (B))
#define IM_CLAMP(V, MN, MX) ((V) < (MN) ? (MN) : (V) > (MX) ? (MX) : (V))
#define IMGUI_CDECL
#define IMGUI_DEMO_MARKER(section) do { if (GImGuiDemoMarkerCallback != NULL) GImGuiDemoMarkerCallback("imgui_demo.cpp", __LINE__, section, GImGuiDemoMarkerCallbackUserData); } while (0)
Typedefs
typedef void(* ImGuiDemoMarkerCallback) (const char *file, int line, const char *section, void *user_data)
Functions
static void ShowExampleAppMainMenuBar ()
static void ShowExampleAppAssetsBrowser (bool *p_open)
static void ShowExampleAppConsole (bool *p_open)
static void ShowExampleAppCustomRendering (bool *p_open)
static void ShowExampleAppDocuments (bool *p_open)
static void ShowExampleAppLog (bool *p_open)
static void ShowExampleAppLayout (bool *p_open)
static void ShowExampleAppPropertyEditor (bool *p_open, ImGuiDemoWindowData *demo_data)
static void ShowExampleAppSimpleOverlay (bool *p_open)
static void ShowExampleAppAutoResize (bool *p_open)
static void ShowExampleAppConstrainedResize (bool *p_open)
static void ShowExampleAppFullscreen (bool *p_open)
static void ShowExampleAppLongText (bool *p_open)
static void ShowExampleAppWindowTitles (bool *p_open)
static void ShowExampleMenuFile ()
static void DemoWindowMenuBar (ImGuiDemoWindowData *demo_data)
static void DemoWindowWidgets (ImGuiDemoWindowData *demo_data)
static void DemoWindowLayout ()
static void DemoWindowPopups ()
static void DemoWindowTables ()
static void DemoWindowColumns ()
static void DemoWindowInputs ()
static ExampleTreeNode * ExampleTree_CreateNode (const char *name, int uid, ExampleTreeNode *parent)
static void ExampleTree_DestroyNode (ExampleTreeNode *node)
static void HelpMarker (const char *desc)
static ExampleTreeNode * ExampleTree_CreateDemoTree ()
static void DemoWindowWidgetsBasic ()
static void DemoWindowWidgetsBullets ()
static void DemoWindowWidgetsCollapsingHeaders ()
static void DemoWindowWidgetsColorAndPickers ()
static void DemoWindowWidgetsComboBoxes ()
static void DemoWindowWidgetsDataTypes ()
static void DemoWindowWidgetsDisableBlocks (ImGuiDemoWindowData *demo_data)
static void DemoWindowWidgetsDragAndDrop ()
static void DemoWindowWidgetsDragsAndSliders ()
void ImGui::ShowFontAtlas (ImFontAtlas *atlas)
static void DemoWindowWidgetsFonts ()
static void DemoWindowWidgetsImages ()
static void DemoWindowWidgetsListBoxes ()
static void DemoWindowWidgetsMultiComponents ()
static void DemoWindowWidgetsPlotting ()
static void DemoWindowWidgetsProgressBars ()
static void DemoWindowWidgetsQueryingStatuses ()
static void DemoWindowWidgetsSelectables ()
static void DemoWindowWidgetsSelectionAndMultiSelect (ImGuiDemoWindowData *demo_data)
static void EditTabBarFittingPolicyFlags (ImGuiTabBarFlags *p_flags)
static void DemoWindowWidgetsTabs ()
static void DemoWindowWidgetsText ()
static void DemoWindowWidgetsTextFilter ()
static void DemoWindowWidgetsTextInput ()
static void DemoWindowWidgetsTooltips ()
static void DemoWindowWidgetsTreeNodes ()
static void DemoWindowWidgetsVerticalSliders ()
static void PushStyleCompact ()
static void PopStyleCompact ()
static void EditTableSizingFlags (ImGuiTableFlags *p_flags)
static void EditTableColumnsFlags (ImGuiTableColumnFlags *p_flags)
static void ShowTableColumnsStatusFlags (ImGuiTableColumnFlags flags)
static const char * GetTreeLinesFlagsName (ImGuiTreeNodeFlags flags)
static void PathConcaveShape (ImDrawList *draw_list, float x, float y, float sz)
Variables
ImGuiDemoMarkerCallback GImGuiDemoMarkerCallback = NULL
void * GImGuiDemoMarkerCallbackUserData = NULL
static const ExampleMemberInfo ExampleTreeNodeMemberInfos []
static const char * ExampleNames []
Macro Definition Documentation
IM_CLAMP
#define IM_CLAMP (V, MN, MX) ((V) < (MN) ? (MN) : (V) > (MX) ? (MX) : (V))
Definition at line 216 of file imgui_demo.cpp.
IM_MAX
#define IM_MAX (A, B) (((A) >= (B)) ? (A) : (B))
Definition at line 215 of file imgui_demo.cpp.
IM_MIN
#define IM_MIN (A, B) (((A) < (B)) ? (A) : (B))
Definition at line 214 of file imgui_demo.cpp.
IM_NEWLINE
#define IM_NEWLINE "\n"
Definition at line 190 of file imgui_demo.cpp.
IMGUI_CDECL
#define IMGUI_CDECL
Definition at line 224 of file imgui_demo.cpp.
IMGUI_DEMO_MARKER
#define IMGUI_DEMO_MARKER (section) do { if (GImGuiDemoMarkerCallback != NULL) GImGuiDemoMarkerCallback("imgui_demo.cpp", __LINE__, section, GImGuiDemoMarkerCallbackUserData); } while (0)
Definition at line 291 of file imgui_demo.cpp.
PRId64
#define PRId64 "lld"
Definition at line 206 of file imgui_demo.cpp.
PRIu64
#define PRIu64 "llu"
Definition at line 207 of file imgui_demo.cpp.
Typedef Documentation
ImGuiDemoMarkerCallback
typedef void(* ImGuiDemoMarkerCallback) (const char *file, int line, const char *section, void *user_data)
Definition at line 286 of file imgui_demo.cpp.
Function Documentation
DemoWindowColumns()
static void DemoWindowColumns () static
Definition at line 7569 of file imgui_demo.cpp.
References ImGuiListClipper::Begin(), ImGui::BeginChild(), ImGui::Button(), ImGui::Checkbox(), ImGui::CollapsingHeader(), ImGui::Columns(), ImGuiListClipper::DisplayEnd, ImGuiListClipper::DisplayStart, ImGui::DragInt(), ImGui::EndChild(), ImGui::GetColumnIndex(), ImGui::GetColumnOffset(), ImGui::GetColumnWidth(), ImGui::GetContentRegionAvail(), ImGui::GetFontSize(), HelpMarker(), IMGUI_DEMO_MARKER, ImGuiChildFlags_None, ImGuiSelectableFlags_SpanAllColumns, ImGuiWindowFlags_HorizontalScrollbar, ImGui::InputFloat(), ImGui::IsItemHovered(), ImGui::NextColumn(), ImGui::PopID(), ImGui::PushID(), ImGui::SameLine(), ImGui::Selectable(), ImGui::Separator(), ImGui::SetNextItemWidth(), ImGui::SetNextWindowContentSize(), ImGuiListClipper::Step(), ImGui::Text(), ImGui::TextWrapped(), ImGui::TreeNode(), and ImGui::TreePop().
Referenced by DemoWindowTables().
DemoWindowInputs()
static void DemoWindowInputs () static
Definition at line 7779 of file imgui_demo.cpp.
References ImDrawList::AddLine(), ImGuiIO::BackendFlags, ImGui::BeginChild(), ImGui::BeginDisabled(), ImGui::BeginPopup(), ImGui::Bullet(), ImGui::Button(), ImGui::CheckboxFlags(), ImGui::CollapsingHeader(), ImGui::ColorButton(), ImGui::EndChild(), ImGui::EndDisabled(), ImGui::EndPopup(), ImGui::GetColorU32(), ImGui::GetFontSize(), ImGui::GetForegroundDrawList(), ImGui::GetIO(), ImGui::GetKeyName(), ImGui::GetMouseCursor(), ImGui::GetMouseDragDelta(), ImGui::GetTextLineHeightWithSpacing(), HelpMarker(), IM_ARRAYSIZE, IM_ASSERT, IMGUI_DEMO_MARKER, ImGuiBackendFlags_HasMouseCursors, ImGuiCol_Button, ImGuiCol_ChildBg, ImGuiColorEditFlags_NoDragDrop, ImGuiColorEditFlags_NoTooltip, ImGuiCond_Once, ImGuiInputFlags_Repeat, ImGuiInputFlags_RouteActive, ImGuiInputFlags_RouteAlways, ImGuiInputFlags_RouteFocused, ImGuiInputFlags_RouteGlobal, ImGuiInputFlags_RouteOverActive, ImGuiInputFlags_RouteOverFocused, ImGuiInputFlags_RouteUnlessBgFocused, ImGuiInputFlags_Tooltip, ImGuiItemFlags_NoTabStop, ImGuiKey_A, ImGuiKey_F, ImGuiKey_NamedKey_BEGIN, ImGuiKey_NamedKey_END, ImGuiKey_S, ImGuiMod_Alt, ImGuiMod_Ctrl, ImGuiMouseCursor_Arrow, ImGuiMouseCursor_COUNT, ImGuiSliderFlags_AlwaysClamp, ImGui::Indent(), ImGuiIO::InputQueueCharacters, ImGui::InputText(), ImGui::IsItemActive(), ImGui::IsItemHovered(), ImGui::IsKeyDown(), ImGui::IsMouseDown(), ImGui::IsMouseDragging(), ImGui::IsMousePosValid(), ImGui::IsWindowFocused(), ImGuiIO::KeyAlt, ImGuiIO::KeyCtrl, ImGuiIO::KeyShift, ImGuiIO::KeySuper, ImGuiIO::MouseClickedCount, ImGuiIO::MouseClickedPos, ImGuiIO::MouseDelta, ImGuiIO::MouseDown, ImGuiIO::MouseDownDuration, ImGuiIO::MousePos, ImGuiIO::MouseWheel, ImGuiIO::NavActive, ImGuiIO::NavVisible, ImGui::OpenPopup(), ImGui::PopItemFlag(), ImGui::PopStyleColor(), ImGui::PushItemFlag(), ImGui::PushStyleColor(), ImGui::RadioButton(), ImGui::SameLine(), ImGui::Selectable(), ImGui::Separator(), ImGui::SeparatorText(), ImGui::SetKeyboardFocusHere(), ImGui::SetMouseCursor(), ImGui::SetNextFrameWantCaptureKeyboard(), ImGui::SetNextFrameWantCaptureMouse(), ImGui::SetNextItemOpen(), ImGui::SetNextItemShortcut(), ImGui::SetNextItemWidth(), ImGui::Shortcut(), ImVector< T >::Size, ImGui::SliderFloat(), ImGui::SliderFloat3(), ImGui::SliderInt(), ImGui::Text(), ImGui::TextWrapped(), ImGui::TreeNode(), ImGui::TreePop(), ImGui::Unindent(), ImGuiIO::WantCaptureKeyboard, ImGuiIO::WantCaptureMouse, ImGuiIO::WantCaptureMouseUnlessPopupClose, ImGuiIO::WantSetMousePos, ImGuiIO::WantTextInput, ImVec2::x, and ImVec2::y.
Referenced by ImGui::ShowDemoWindow().
DemoWindowLayout()
static void DemoWindowLayout () static
Definition at line 4312 of file imgui_demo.cpp.
References ImDrawList::AddRectFilled(), ImDrawList::AddText(), ImGui::AlignTextToFramePadding(), ImGui::Begin(), ImGui::BeginChild(), ImGui::BeginGroup(), ImGui::BeginListBox(), ImGui::BeginMenu(), ImGui::BeginMenuBar(), ImGui::BeginTabBar(), ImGui::BeginTabItem(), ImGui::BeginTable(), ImGui::BulletText(), ImGui::Button(), ImGui::CalcTextSize(), ImGui::Checkbox(), ImGui::CheckboxFlags(), ImGui::CollapsingHeader(), ImGui::Columns(), ImGui::Combo(), ImGuiIO::DeltaTime, ImGui::DragFloat(), ImGui::DragFloat2(), ImGui::DragInt(), ImGui::Dummy(), ImGui::End(), ImGui::EndChild(), ImGui::EndGroup(), ImGui::EndListBox(), ImGui::EndMenu(), ImGui::EndMenuBar(), ImGui::EndTabBar(), ImGui::EndTabItem(), ImGui::EndTable(), ImGui::GetColumnWidth(), ImGui::GetContentRegionAvail(), ImGui::GetCursorPosX(), ImGui::GetCursorScreenPos(), ImGui::GetCursorStartPos(), ImGui::GetFont(), ImGui::GetFontSize(), ImGui::GetFrameHeightWithSpacing(), ImGui::GetID(), ImGui::GetIO(), ImGui::GetItemRectMax(), ImGui::GetItemRectMin(), ImGui::GetItemRectSize(), ImGui::GetScrollMaxX(), ImGui::GetScrollMaxY(), ImGui::GetScrollX(), ImGui::GetScrollY(), ImGui::GetStyle(), ImGui::GetStyleColorVec4(), ImGui::GetTextLineHeight(), ImGui::GetTextLineHeightWithSpacing(), ImGui::GetWindowDrawList(), HelpMarker(), ImColor::HSV(), IM_ARRAYSIZE, IM_COL32, IM_COL32_WHITE, IM_MIN, IMGUI_DEMO_MARKER, ImGuiChildFlags_AlwaysUseWindowPadding, ImGuiChildFlags_AutoResizeY, ImGuiChildFlags_Borders, ImGuiChildFlags_FrameStyle, ImGuiChildFlags_None, ImGuiChildFlags_ResizeX, ImGuiChildFlags_ResizeY, ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImGuiCol_ChildBg, ImGuiCol_FrameBg, ImGuiMouseButton_Left, ImGuiStyleVar_ChildRounding, ImGuiStyleVar_FramePadding, ImGuiStyleVar_FrameRounding, ImGuiStyleVar_ItemSpacing, ImGuiTableFlags_Borders, ImGuiTableFlags_NoSavedSettings, ImGuiTableFlags_Resizable, ImGuiTreeNodeFlags_DrawLinesNone, ImGuiWindowFlags_AlwaysVerticalScrollbar, ImGuiWindowFlags_HorizontalScrollbar, ImGuiWindowFlags_MenuBar, ImGuiWindowFlags_None, ImGuiWindowFlags_NoScrollWithMouse, ImGui::Indent(), ImGui::InvisibleButton(), ImGui::IsItemActive(), ImGui::IsItemHovered(), ImGui::IsItemVisible(), ImGui::IsMouseDragging(), ImGuiStyle::ItemInnerSpacing, ImGuiStyle::ItemSpacing, ImGui::ListBox(), ImGuiIO::MouseDelta, ImGui::NextColumn(), ImGui::PlotHistogram(), ImGui::PopClipRect(), ImDrawList::PopClipRect(), ImGui::PopID(), ImGui::PopItemWidth(), ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGui::PushClipRect(), ImDrawList::PushClipRect(), ImGui::PushID(), ImGui::PushItemWidth(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), ImGui::PushStyleVarY(), ImGui::SameLine(), ImGuiStyle::ScrollbarSize, ImGui::Selectable(), ImGui::Separator(), ImGui::SeparatorText(), ImGui::SetCursorPosX(), ImGui::SetCursorScreenPos(), ImGui::SetItemTooltip(), ImGui::SetNextItemAllowOverlap(), ImGui::SetNextItemWidth(), ImGui::SetNextWindowContentSize(), ImGui::SetNextWindowSizeConstraints(), ImGui::SetScrollFromPosX(), ImGui::SetScrollFromPosY(), ImGui::SetScrollHereX(), ImGui::SetScrollHereY(), ImGui::SetScrollX(), ImGui::SetScrollY(), ShowExampleMenuFile(), ImGui::SliderFloat(), ImGui::SliderInt(), ImGui::SmallButton(), ImGui::Spacing(), ImGui::TableNextColumn(), ImGui::Text(), ImGui::TextColored(), ImGui::TextUnformatted(), ImGui::TextWrapped(), ImGui::TreeNode(), ImGui::TreeNodeEx(), ImGui::TreePop(), ImGui::Unindent(), ImGuiStyle::WindowPadding, ImVec2::x, and ImVec2::y.
Referenced by ImGui::ShowDemoWindow().
DemoWindowMenuBar()
static void DemoWindowMenuBar (ImGuiDemoWindowData * demo_data) static
Definition at line 652 of file imgui_demo.cpp.
References ImGui::BeginDisabled(), ImGui::BeginMenu(), ImGui::BeginMenuBar(), ImGui::Checkbox(), ImGuiIO::ConfigDebugHighlightIdConflicts, ImGuiIO::ConfigDebugIsDebuggerPresent, ImGuiIO::ConfigErrorRecoveryEnableAssert, ImGui::DebugStartItemPicker(), ImGui::EndDisabled(), ImGui::EndMenu(), ImGui::EndMenuBar(), ImGui::GetIO(), IMGUI_DEMO_MARKER, ImGui::MenuItem(), ImGui::SeparatorText(), ImGui::SetItemTooltip(), ImGuiDemoWindowData::ShowAbout, ImGuiDemoWindowData::ShowAppAssetsBrowser, ImGuiDemoWindowData::ShowAppAutoResize, ImGuiDemoWindowData::ShowAppConsole, ImGuiDemoWindowData::ShowAppConstrainedResize, ImGuiDemoWindowData::ShowAppCustomRendering, ImGuiDemoWindowData::ShowAppDocuments, ImGuiDemoWindowData::ShowAppFullscreen, ImGuiDemoWindowData::ShowAppLayout, ImGuiDemoWindowData::ShowAppLog, ImGuiDemoWindowData::ShowAppLongText, ImGuiDemoWindowData::ShowAppPropertyEditor, ImGuiDemoWindowData::ShowAppSimpleOverlay, ImGuiDemoWindowData::ShowAppWindowTitles, ImGuiDemoWindowData::ShowDebugLog, ShowExampleMenuFile(), ImGuiDemoWindowData::ShowIDStackTool, ImGuiDemoWindowData::ShowMainMenuBar, ImGuiDemoWindowData::ShowMetrics, ImGuiDemoWindowData::ShowStyleEditor, and ImGui::TextDisabled().
Referenced by ImGui::ShowDemoWindow().
DemoWindowPopups()
static void DemoWindowPopups () static
Definition at line 5199 of file imgui_demo.cpp.
References ImGui::BeginMenu(), ImGui::BeginMenuBar(), ImGui::BeginPopup(), ImGui::BeginPopupContextItem(), ImGui::BeginPopupModal(), ImGui::Button(), ImGui::Checkbox(), ImGui::CloseCurrentPopup(), ImGui::CollapsingHeader(), ImGui::ColorEdit4(), ImGui::Combo(), ImGui::DragFloat(), ImGui::EndMenu(), ImGui::EndMenuBar(), ImGui::EndPopup(), ImGuiViewport::GetCenter(), ImGui::GetMainViewport(), HelpMarker(), IM_ARRAYSIZE, IMGUI_DEMO_MARKER, ImGuiCond_Appearing, ImGuiPopupFlags_MouseButtonRight, ImGuiStyleVar_FramePadding, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_MenuBar, ImGui::InputText(), ImGui::MenuItem(), ImGui::OpenPopup(), ImGui::OpenPopupOnItemClick(), ImGui::PopStyleVar(), ImGui::PushStyleVar(), ImGui::SameLine(), ImGui::Selectable(), ImGui::Separator(), ImGui::SeparatorText(), ImGui::SetItemDefaultFocus(), ImGui::SetItemTooltip(), ImGui::SetNextItemWidth(), ImGui::SetNextWindowPos(), ShowExampleMenuFile(), ImGui::Text(), ImGui::TextUnformatted(), ImGui::TextWrapped(), ImGui::TreeNode(), and ImGui::TreePop().
Referenced by ImGui::ShowDemoWindow().
DemoWindowTables()
static void DemoWindowTables () static
Definition at line 5663 of file imgui_demo.cpp.
References ImGui::AlignTextToFramePadding(), ImGuiListClipper::Begin(), ImGui::BeginDisabled(), ImGui::BeginPopup(), ImGui::BeginPopupContextItem(), ImGui::BeginTable(), ImGui::Button(), ImGui::CalcTextSize(), ImGuiStyle::CellPadding, ImGui::Checkbox(), ImGui::CheckboxFlags(), ImVector< T >::clear(), ImGui::CloseCurrentPopup(), ImDrawList::CmdBuffer, ImGui::CollapsingHeader(), ImGui::ColorButton(), ImGui::Combo(), ImVector< T >::contains(), ImVector< T >::Data, DemoWindowColumns(), ImGuiListClipper::DisplayEnd, ImGuiListClipper::DisplayStart, ImGui::DragFloat(), ImGui::DragFloat2(), ImGui::DragInt(), EditTableColumnsFlags(), EditTableSizingFlags(), ImGui::EndDisabled(), ImGui::EndPopup(), ImGui::EndTable(), ImVector< T >::find_erase_unsorted(), ImGui::GetColorU32(), ImGui::GetContentRegionAvail(), ImGui::GetFontSize(), ImGui::GetFrameHeight(), ImGui::GetIO(), ImGui::GetScrollMaxX(), ImGui::GetScrollMaxY(), ImGui::GetScrollX(), ImGui::GetScrollY(), ImGui::GetStyle(), ImGui::GetTextLineHeightWithSpacing(), ImGui::GetWindowDrawList(), HelpMarker(), IM_ARRAYSIZE, IM_ASSERT, IMGUI_DEMO_MARKER, ImGuiCol_FrameBg, ImGuiColorEditFlags_None, ImGuiSelectableFlags_AllowOverlap, ImGuiSelectableFlags_None, ImGuiSelectableFlags_SpanAllColumns, ImGuiSliderFlags_AlwaysClamp, ImGuiSliderFlags_NoInput, ImGuiStyleVar_CellPadding, ImGuiStyleVar_FramePadding, ImGuiStyleVar_IndentSpacing, ImGuiTableBgTarget_CellBg, ImGuiTableBgTarget_RowBg0, ImGuiTableColumnFlags_AngledHeader, ImGuiTableColumnFlags_DefaultHide, ImGuiTableColumnFlags_DefaultSort, ImGuiTableColumnFlags_IsHovered, ImGuiTableColumnFlags_IsSorted, ImGuiTableColumnFlags_NoHeaderWidth, ImGuiTableColumnFlags_NoHide, ImGuiTableColumnFlags_None, ImGuiTableColumnFlags_NoReorder, ImGuiTableColumnFlags_NoSort, ImGuiTableColumnFlags_PreferSortDescending, ImGuiTableColumnFlags_WidthFixed, ImGuiTableColumnFlags_WidthStretch, ImGuiTableFlags_Borders, ImGuiTableFlags_BordersH, ImGuiTableFlags_BordersInner, ImGuiTableFlags_BordersInnerH, ImGuiTableFlags_BordersInnerV, ImGuiTableFlags_BordersOuter, ImGuiTableFlags_BordersOuterH, ImGuiTableFlags_BordersOuterV, ImGuiTableFlags_BordersV, ImGuiTableFlags_ContextMenuInBody, ImGuiTableFlags_Hideable, ImGuiTableFlags_HighlightHoveredColumn, ImGuiTableFlags_NoBordersInBody, ImGuiTableFlags_NoBordersInBodyUntilResize, ImGuiTableFlags_NoClip, ImGuiTableFlags_NoHostExtendX, ImGuiTableFlags_NoHostExtendY, ImGuiTableFlags_NoKeepColumnsVisible, ImGuiTableFlags_None, ImGuiTableFlags_NoPadInnerX, ImGuiTableFlags_NoPadOuterX, ImGuiTableFlags_NoSavedSettings, ImGuiTableFlags_PadOuterX, ImGuiTableFlags_PreciseWidths, ImGuiTableFlags_Reorderable, ImGuiTableFlags_Resizable, ImGuiTableFlags_RowBg, ImGuiTableFlags_ScrollX, ImGuiTableFlags_ScrollY, ImGuiTableFlags_SizingFixedFit, ImGuiTableFlags_SizingFixedSame, ImGuiTableFlags_SizingStretchProp, ImGuiTableFlags_SizingStretchSame, ImGuiTableFlags_Sortable, ImGuiTableFlags_SortMulti, ImGuiTableFlags_SortTristate, ImGuiTableRowFlags_Headers, ImGuiTableRowFlags_None, ImGuiTreeNodeFlags_Bullet, ImGuiTreeNodeFlags_DefaultOpen, ImGuiTreeNodeFlags_DrawLinesFull, ImGuiTreeNodeFlags_LabelSpanAllColumns, ImGuiTreeNodeFlags_Leaf, ImGuiTreeNodeFlags_NoTreePushOnOpen, ImGuiTreeNodeFlags_SpanAllColumns, ImGuiTreeNodeFlags_SpanFullWidth, ImGuiTreeNodeFlags_SpanLabelWidth, ImGui::Indent(), ImGui::InputText(), ImGui::IsAnyItemHovered(), ImGui::IsItemDeactivated(), ImGui::IsMouseReleased(), ImGui::OpenPopup(), ImGui::PopID(), ImGui::PopItemWidth(), ImGui::PopStyleColor(), PopStyleCompact(), ImGui::PopStyleVar(), ImVector< T >::push_back(), ImGui::PushID(), ImGui::PushItemWidth(), ImGui::PushStyleColor(), PushStyleCompact(), ImGui::PushStyleVar(), ImGui::PushStyleVarY(), ImGui::RadioButton(), ImVector< T >::resize(), ImGui::SameLine(), ImGui::Selectable(), ImGui::Separator(), ImGui::SetNextItemOpen(), ImGui::SetNextItemWidth(), ShowTableColumnsStatusFlags(), ImVector< T >::Size, ImGui::SliderAngle(), ImGui::SliderFloat(), ImGui::SliderFloat2(), ImGui::SliderInt(), ImGui::SmallButton(), ImGui::Spacing(), ImGuiTableSortSpecs::SpecsDirty, ImGuiListClipper::Step(), ImGui::TableAngledHeadersRow(), ImGui::TableGetColumnFlags(), ImGui::TableGetColumnIndex(), ImGui::TableGetColumnName(), ImGui::TableGetRowIndex(), ImGui::TableGetSortSpecs(), ImGui::TableHeader(), ImGui::TableHeadersRow(), ImGui::TableNextColumn(), ImGui::TableNextRow(), ImGui::TableSetBgColor(), ImGui::TableSetColumnIndex(), ImGui::TableSetupColumn(), ImGui::TableSetupScrollFreeze(), ImGui::Text(), ImGui::TextDisabled(), ImGui::TextUnformatted(), ImGui::TextWrapped(), ImGui::TreeNode(), ImGui::TreeNodeEx(), ImGui::TreePop(), ImGui::Unindent(), ImVec2::x, and ImVec2::y.
Referenced by ImGui::ShowDemoWindow().
DemoWindowWidgets()
static void DemoWindowWidgets (ImGuiDemoWindowData * demo_data) static
Definition at line 4261 of file imgui_demo.cpp.
References ImGui::BeginDisabled(), ImGui::CollapsingHeader(), DemoWindowWidgetsBasic(), DemoWindowWidgetsBullets(), DemoWindowWidgetsCollapsingHeaders(), DemoWindowWidgetsColorAndPickers(), DemoWindowWidgetsComboBoxes(), DemoWindowWidgetsDataTypes(), DemoWindowWidgetsDisableBlocks(), DemoWindowWidgetsDragAndDrop(), DemoWindowWidgetsDragsAndSliders(), DemoWindowWidgetsFonts(), DemoWindowWidgetsImages(), DemoWindowWidgetsListBoxes(), DemoWindowWidgetsMultiComponents(), DemoWindowWidgetsPlotting(), DemoWindowWidgetsProgressBars(), DemoWindowWidgetsQueryingStatuses(), DemoWindowWidgetsSelectables(), DemoWindowWidgetsSelectionAndMultiSelect(), DemoWindowWidgetsTabs(), DemoWindowWidgetsText(), DemoWindowWidgetsTextFilter(), DemoWindowWidgetsTextInput(), DemoWindowWidgetsTooltips(), DemoWindowWidgetsTreeNodes(), DemoWindowWidgetsVerticalSliders(), ImGuiDemoWindowData::DisableSections, ImGui::EndDisabled(), and IMGUI_DEMO_MARKER.
Referenced by ImGui::ShowDemoWindow().
DemoWindowWidgetsBasic()
static void DemoWindowWidgetsBasic () static
Definition at line 818 of file imgui_demo.cpp.
References ImGui::AlignTextToFramePadding(), ImGui::ArrowButton(), ImGui::Button(), ImGui::Checkbox(), ImGui::ColorEdit3(), ImGui::ColorEdit4(), ImGui::Combo(), ImGui::DragFloat(), ImGui::DragInt(), ImGui::GetStyle(), HelpMarker(), ImColor::HSV(), IM_ARRAYSIZE, IMGUI_DEMO_MARKER, ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImGuiDir_Left, ImGuiDir_Right, ImGuiItemFlags_ButtonRepeat, ImGuiSliderFlags_AlwaysClamp, ImGuiSliderFlags_Logarithmic, ImGuiSliderFlags_WrapAround, ImGui::InputDouble(), ImGui::InputFloat(), ImGui::InputFloat3(), ImGui::InputInt(), ImGui::InputText(), ImGui::InputTextWithHint(), ImGuiStyle::ItemInnerSpacing, ImGui::LabelText(), ImGui::ListBox(), ImGui::PopID(), ImGui::PopItemFlag(), ImGui::PopStyleColor(), ImGui::PushID(), ImGui::PushItemFlag(), ImGui::PushStyleColor(), ImGui::RadioButton(), ImGui::SameLine(), ImGui::SeparatorText(), ImGui::SetItemTooltip(), ImGui::SliderAngle(), ImGui::SliderFloat(), ImGui::SliderInt(), ImGui::Text(), ImGui::TextLinkOpenURL(), ImGui::TreeNode(), ImGui::TreePop(), and ImVec2::x.
Referenced by DemoWindowWidgets().
DemoWindowWidgetsBullets()
static void DemoWindowWidgetsBullets () static
Definition at line 1033 of file imgui_demo.cpp.
References ImGui::Bullet(), ImGui::BulletText(), IMGUI_DEMO_MARKER, ImGui::SmallButton(), ImGui::Text(), ImGui::TreeNode(), and ImGui::TreePop().
Referenced by DemoWindowWidgets().
DemoWindowWidgetsCollapsingHeaders()
static void DemoWindowWidgetsCollapsingHeaders () static
Definition at line 1055 of file imgui_demo.cpp.
References ImGui::Checkbox(), ImGui::CollapsingHeader(), IMGUI_DEMO_MARKER, ImGuiTreeNodeFlags_None, ImGui::IsItemHovered(), ImGui::Text(), ImGui::TreeNode(), and ImGui::TreePop().
Referenced by DemoWindowWidgets().
DemoWindowWidgetsColorAndPickers()
static void DemoWindowWidgetsColorAndPickers () static
Definition at line 1086 of file imgui_demo.cpp.
References ImGui::AcceptDragDropPayload(), ImGui::BeginDragDropTarget(), ImGui::BeginGroup(), ImGui::BeginPopup(), ImGui::Button(), ImGui::Checkbox(), ImGui::CheckboxFlags(), ImGui::ColorButton(), ImGui::ColorConvertHSVtoRGB(), ImGui::ColorEdit3(), ImGui::ColorEdit4(), ImGui::ColorPicker3(), ImGui::ColorPicker4(), ImGui::Combo(), ImGui::DragFloat4(), ImGui::EndDragDropTarget(), ImGui::EndGroup(), ImGui::EndPopup(), ImGui::GetContentRegionAvail(), ImGui::GetStyle(), HelpMarker(), IM_ARRAYSIZE, IMGUI_DEMO_MARKER, IMGUI_PAYLOAD_TYPE_COLOR_3F, IMGUI_PAYLOAD_TYPE_COLOR_4F, ImGuiColorEditFlags_AlphaBar, ImGuiColorEditFlags_AlphaNoBg, ImGuiColorEditFlags_AlphaOpaque, ImGuiColorEditFlags_AlphaPreviewHalf, ImGuiColorEditFlags_DisplayHex, ImGuiColorEditFlags_DisplayHSV, ImGuiColorEditFlags_DisplayRGB, ImGuiColorEditFlags_Float, ImGuiColorEditFlags_HDR, ImGuiColorEditFlags_InputHSV, ImGuiColorEditFlags_NoAlpha, ImGuiColorEditFlags_NoBorder, ImGuiColorEditFlags_NoColorMarkers, ImGuiColorEditFlags_NoDragDrop, ImGuiColorEditFlags_NoInputs, ImGuiColorEditFlags_NoLabel, ImGuiColorEditFlags_None, ImGuiColorEditFlags_NoOptions, ImGuiColorEditFlags_NoPicker, ImGuiColorEditFlags_NoSidePreview, ImGuiColorEditFlags_NoSmallPreview, ImGuiColorEditFlags_NoTooltip, ImGuiColorEditFlags_PickerHueBar, ImGuiColorEditFlags_PickerHueWheel, ImGuiColorEditFlags_Uint8, ImGuiStyle::ItemSpacing, ImGui::OpenPopup(), ImGui::PopID(), ImGui::PushID(), ImGui::SameLine(), ImGui::Separator(), ImGui::SeparatorText(), ImGui::SetColorEditOptions(), ImGui::SetNextItemWidth(), ImGui::Spacing(), ImGui::Text(), ImGui::TreeNode(), ImGui::TreePop(), ImVec4::w, ImVec2::x, ImVec4::x, and ImVec2::y.
Referenced by DemoWindowWidgets().
DemoWindowWidgetsComboBoxes()
static void DemoWindowWidgetsComboBoxes () static
Definition at line 1287 of file imgui_demo.cpp.
References ImGui::BeginCombo(), ImGui::CheckboxFlags(), ImGuiTextFilter::Clear(), ImGui::Combo(), ImGuiTextFilter::Draw(), ImGui::EndCombo(), HelpMarker(), IM_ARRAYSIZE, IMGUI_DEMO_MARKER, ImGuiComboFlags_HeightLargest, ImGuiComboFlags_HeightMask_, ImGuiComboFlags_HeightRegular, ImGuiComboFlags_HeightSmall, ImGuiComboFlags_NoArrowButton, ImGuiComboFlags_NoPreview, ImGuiComboFlags_PopupAlignLeft, ImGuiComboFlags_WidthFitPreview, ImGuiKey_F, ImGuiMod_Ctrl, ImGui::IsWindowAppearing(), ImGuiTextFilter::PassFilter(), ImGui::SameLine(), ImGui::Selectable(), ImGui::SeparatorText(), ImGui::SetItemDefaultFocus(), ImGui::SetKeyboardFocusHere(), ImGui::SetNextItemShortcut(), ImGui::Spacing(), ImGui::TreeNode(), and ImGui::TreePop().
Referenced by DemoWindowWidgets().
DemoWindowWidgetsDataTypes()
static void DemoWindowWidgetsDataTypes () static
Definition at line 1384 of file imgui_demo.cpp.
References ImGui::Checkbox(), ImGui::CheckboxFlags(), ImGui::DragScalar(), HelpMarker(), IMGUI_DEMO_MARKER, ImGuiDataType_Double, ImGuiDataType_Float, ImGuiDataType_S16, ImGuiDataType_S32, ImGuiDataType_S64, ImGuiDataType_S8, ImGuiDataType_U16, ImGuiDataType_U32, ImGuiDataType_U64, ImGuiDataType_U8, ImGuiInputTextFlags_DisplayEmptyRefVal, ImGuiInputTextFlags_None, ImGuiInputTextFlags_ParseEmptyRefVal, ImGuiInputTextFlags_ReadOnly, ImGuiSliderFlags_Logarithmic, ImGui::InputScalar(), PRId64, PRIu64, ImGui::SameLine(), ImGui::SeparatorText(), ImGui::SliderScalar(), ImGui::TreeNode(), and ImGui::TreePop().
Referenced by DemoWindowWidgets().
DemoWindowWidgetsDisableBlocks()
static void DemoWindowWidgetsDisableBlocks (ImGuiDemoWindowData * demo_data) static
Definition at line 1519 of file imgui_demo.cpp.
References ImGui::Checkbox(), ImGuiDemoWindowData::DisableSections, HelpMarker(), IMGUI_DEMO_MARKER, ImGui::SameLine(), ImGui::TreeNode(), and ImGui::TreePop().
Referenced by DemoWindowWidgets().
DemoWindowWidgetsDragAndDrop()
static void DemoWindowWidgetsDragAndDrop () static
Definition at line 1534 of file imgui_demo.cpp.
References ImGui::AcceptDragDropPayload(), ImGui::BeginDragDropSource(), ImGui::BeginDragDropTarget(), ImGui::Button(), ImGui::ColorButton(), ImGui::ColorEdit3(), ImGui::ColorEdit4(), ImGui::EndDragDropSource(), ImGui::EndDragDropTarget(), ImGui::GetMouseDragDelta(), HelpMarker(), IM_ARRAYSIZE, IM_ASSERT, IM_UNUSED, IMGUI_DEMO_MARKER, IMGUI_PAYLOAD_TYPE_COLOR_4F, ImGuiDragDropFlags_AcceptBeforeDelivery, ImGuiDragDropFlags_AcceptNoPreviewTooltip, ImGuiDragDropFlags_None, ImGuiItemFlags_AllowDuplicateId, ImGuiMouseCursor_NotAllowed, ImGui::IsItemActive(), ImGui::IsItemHovered(), ImGui::PopID(), ImGui::PopItemFlag(), ImGui::PushID(), ImGui::PushItemFlag(), ImGui::RadioButton(), ImGui::ResetMouseDragDelta(), ImGui::SameLine(), ImGui::Selectable(), ImGui::SetDragDropPayload(), ImGui::SetMouseCursor(), ImGui::SetTooltip(), ImGui::Text(), ImGui::TreeNode(), ImGui::TreePop(), and ImVec2::y.
Referenced by DemoWindowWidgets().
DemoWindowWidgetsDragsAndSliders()
static void DemoWindowWidgetsDragsAndSliders () static
Definition at line 1692 of file imgui_demo.cpp.
References ImGui::CheckboxFlags(), ImGui::DragFloat(), ImGui::DragFloat4(), ImGui::DragInt(), HelpMarker(), IMGUI_DEMO_MARKER, ImGuiSliderFlags_AlwaysClamp, ImGuiSliderFlags_ClampOnInput, ImGuiSliderFlags_ClampZeroRange, ImGuiSliderFlags_ColorMarkers, ImGuiSliderFlags_Logarithmic, ImGuiSliderFlags_NoInput, ImGuiSliderFlags_None, ImGuiSliderFlags_NoRoundToFormat, ImGuiSliderFlags_NoSpeedTweaks, ImGuiSliderFlags_WrapAround, ImGui::SameLine(), ImGui::SliderFloat(), ImGui::SliderFloat4(), ImGui::SliderInt(), ImGui::Text(), ImGui::TreeNode(), and ImGui::TreePop().
Referenced by DemoWindowWidgets().
DemoWindowWidgetsFonts()
static void DemoWindowWidgetsFonts () static
Definition at line 1752 of file imgui_demo.cpp.
References ImGuiIO::Fonts, ImGui::GetIO(), IMGUI_DEMO_MARKER, ImGui::ShowFontAtlas(), ImGui::TreeNode(), and ImGui::TreePop().
Referenced by DemoWindowWidgets().
DemoWindowWidgetsImages()
static void DemoWindowWidgetsImages () static
Definition at line 1768 of file imgui_demo.cpp.
References ImGui::BeginItemTooltip(), ImGui::EndTooltip(), ImGuiIO::Fonts, ImGui::GetCursorScreenPos(), ImGui::GetIO(), ImGui::GetStyle(), ImTextureData::Height, IM_MAX, ImGui::ImageButton(), ImGui::ImageWithBg(), IMGUI_DEMO_MARKER, ImGuiStyleVar_FramePadding, ImGuiStyleVar_ImageBorderSize, ImGuiIO::MousePos, ImGui::NewLine(), ImGui::PopID(), ImGui::PopStyleVar(), ImGui::PushID(), ImGui::PushStyleVar(), ImGui::SameLine(), ImFontAtlas::TexData, ImFontAtlas::TexRef, ImGui::Text(), ImGui::TextWrapped(), ImGui::TreeNode(), ImGui::TreePop(), ImTextureData::Width, ImVec2::x, and ImVec2::y.
Referenced by DemoWindowWidgets().
DemoWindowWidgetsListBoxes()
static void DemoWindowWidgetsListBoxes () static
Definition at line 1861 of file imgui_demo.cpp.
References ImGui::BeginListBox(), ImGui::Checkbox(), ImGui::EndListBox(), ImGui::GetTextLineHeightWithSpacing(), HelpMarker(), IM_ARRAYSIZE, IMGUI_DEMO_MARKER, ImGuiSelectableFlags_Highlight, ImGui::IsItemHovered(), ImGui::SameLine(), ImGui::Selectable(), ImGui::SetItemDefaultFocus(), ImGui::Text(), ImGui::TreeNode(), and ImGui::TreePop().
Referenced by DemoWindowWidgets().
DemoWindowWidgetsMultiComponents()
static void DemoWindowWidgetsMultiComponents () static
Definition at line 1926 of file imgui_demo.cpp.
References ImGui::DragFloat2(), ImGui::DragFloat3(), ImGui::DragFloat4(), ImGui::DragFloatRange2(), ImGui::DragInt2(), ImGui::DragInt3(), ImGui::DragInt4(), ImGui::DragIntRange2(), IMGUI_DEMO_MARKER, ImGuiSliderFlags_AlwaysClamp, ImGui::InputFloat2(), ImGui::InputFloat3(), ImGui::InputFloat4(), ImGui::InputInt2(), ImGui::InputInt3(), ImGui::InputInt4(), ImGui::SeparatorText(), ImGui::SliderFloat2(), ImGui::SliderFloat3(), ImGui::SliderFloat4(), ImGui::SliderInt2(), ImGui::SliderInt3(), ImGui::SliderInt4(), ImGui::TreeNode(), and ImGui::TreePop().
Referenced by DemoWindowWidgets().
DemoWindowWidgetsPlotting()
static void DemoWindowWidgetsPlotting () static
Definition at line 1973 of file imgui_demo.cpp.
References ImGui::Checkbox(), ImGui::Combo(), ImGui::GetFontSize(), ImGui::GetTime(), IM_ARRAYSIZE, IMGUI_DEMO_MARKER, ImGui::PlotHistogram(), ImGui::PlotLines(), ImGui::SameLine(), ImGui::Separator(), ImGui::SeparatorText(), ImGui::SetNextItemWidth(), ImGui::SliderInt(), ImGui::Text(), ImGui::TextLinkOpenURL(), ImGui::TreeNode(), and ImGui::TreePop().
Referenced by DemoWindowWidgets().
DemoWindowWidgetsProgressBars()
static void DemoWindowWidgetsProgressBars () static
Definition at line 2049 of file imgui_demo.cpp.
References ImGuiIO::DeltaTime, ImGui::GetIO(), ImGui::GetStyle(), ImGui::GetTime(), IM_CLAMP, IMGUI_DEMO_MARKER, ImGui::ProgressBar(), ImGui::SameLine(), ImGui::Text(), ImGui::TreeNode(), and ImGui::TreePop().
Referenced by DemoWindowWidgets().
DemoWindowWidgetsQueryingStatuses()
static void DemoWindowWidgetsQueryingStatuses () static
Definition at line 2086 of file imgui_demo.cpp.
References ImGui::Begin(), ImGui::BeginChild(), ImGui::BeginDisabled(), ImGui::BeginPopupContextItem(), ImGui::BulletText(), ImGui::Button(), ImGui::Checkbox(), ImGui::ColorEdit4(), ImGui::Combo(), ImGui::End(), ImGui::EndChild(), ImGui::EndDisabled(), ImGui::EndPopup(), ImGui::GetFontSize(), ImGui::GetItemRectMax(), ImGui::GetItemRectMin(), ImGui::GetItemRectSize(), HelpMarker(), IM_ARRAYSIZE, IMGUI_DEMO_MARKER, ImGuiChildFlags_Borders, ImGuiFocusedFlags_AnyWindow, ImGuiFocusedFlags_ChildWindows, ImGuiFocusedFlags_NoPopupHierarchy, ImGuiFocusedFlags_RootWindow, ImGuiHoveredFlags_AllowWhenBlockedByActiveItem, ImGuiHoveredFlags_AllowWhenBlockedByPopup, ImGuiHoveredFlags_AllowWhenDisabled, ImGuiHoveredFlags_AllowWhenOverlappedByItem, ImGuiHoveredFlags_AllowWhenOverlappedByWindow, ImGuiHoveredFlags_AnyWindow, ImGuiHoveredFlags_ChildWindows, ImGuiHoveredFlags_DelayNormal, ImGuiHoveredFlags_DelayShort, ImGuiHoveredFlags_ForTooltip, ImGuiHoveredFlags_NoPopupHierarchy, ImGuiHoveredFlags_RectOnly, ImGuiHoveredFlags_RootWindow, ImGuiHoveredFlags_Stationary, ImGuiInputTextFlags_ReadOnly, ImGuiItemFlags_ButtonRepeat, ImGuiTreeNodeFlags_NoTreePushOnOpen, ImGuiTreeNodeFlags_OpenOnDoubleClick, ImGui::InputFloat(), ImGui::InputFloat3(), ImGui::InputText(), ImGui::InputTextMultiline(), ImGui::IsItemActivated(), ImGui::IsItemActive(), ImGui::IsItemClicked(), ImGui::IsItemDeactivated(), ImGui::IsItemDeactivatedAfterEdit(), ImGui::IsItemEdited(), ImGui::IsItemFocused(), ImGui::IsItemHovered(), ImGui::IsItemToggledOpen(), ImGui::IsItemVisible(), ImGui::IsWindowFocused(), ImGui::IsWindowHovered(), ImGui::ListBox(), ImGui::MenuItem(), ImGui::PopItemFlag(), ImGui::PushItemFlag(), ImGui::SameLine(), ImGui::Selectable(), ImGui::SliderFloat(), ImGui::Text(), ImGui::TreeNode(), ImGui::TreeNodeEx(), and ImGui::TreePop().
Referenced by DemoWindowWidgets().
DemoWindowWidgetsSelectables()
static void DemoWindowWidgetsSelectables () static
Definition at line 2287 of file imgui_demo.cpp.
References ImGui::BeginTable(), ImGui::EndTable(), ImGui::GetTime(), HelpMarker(), IMGUI_DEMO_MARKER, ImGuiSelectableFlags_AllowDoubleClick, ImGuiSelectableFlags_None, ImGuiSelectableFlags_SpanAllColumns, ImGuiStyleVar_SelectableTextAlign, ImGuiTableFlags_Borders, ImGuiTableFlags_NoSavedSettings, ImGuiTableFlags_Resizable, ImGui::IsMouseDoubleClicked(), ImGui::PopID(), ImGui::PopStyleVar(), ImGui::PushID(), ImGui::PushStyleVar(), ImGui::SameLine(), ImGui::Selectable(), ImGui::SetNextItemAllowOverlap(), ImGui::SmallButton(), ImGui::Spacing(), ImGui::TableNextColumn(), ImGui::TableNextRow(), ImGui::Text(), ImGui::TreeNode(), ImGui::TreePop(), ImVec2::x, and ImVec2::y.
Referenced by DemoWindowWidgets().
DemoWindowWidgetsSelectionAndMultiSelect()
static void DemoWindowWidgetsSelectionAndMultiSelect (ImGuiDemoWindowData * demo_data) static
Definition at line 2652 of file imgui_demo.cpp.
References ImGuiSelectionBasicStorage::AdapterIndexToStorageId, ImGuiSelectionExternalStorage::AdapterSetItemSelected, ExampleSelectionWithDeletion::ApplyDeletionPostLoop(), ExampleSelectionWithDeletion::ApplyDeletionPreLoop(), ImGuiSelectionBasicStorage::ApplyRequests(), ImGuiSelectionExternalStorage::ApplyRequests(), ImVector< T >::back(), ImGuiListClipper::Begin(), ImGui::BeginChild(), ImGui::BeginDisabled(), ImGui::BeginDragDropSource(), ImGui::BeginMultiSelect(), ImGui::BeginPopupContextItem(), ImGui::BeginTable(), ImGui::BulletText(), ImGui::Checkbox(), ImGui::CheckboxFlags(), ExampleTreeNode::Childs, ImGuiSelectionBasicStorage::Clear(), ImGui::ColorButton(), ImGuiSelectionBasicStorage::Contains(), ImVector< T >::Data, ImGuiPayload::Data, ImGuiPayload::DataSize, ImGuiDemoWindowData::DemoTree, ImGuiListClipper::DisplayEnd, ImGuiListClipper::DisplayStart, ImGui::EndChild(), ImGui::EndDisabled(), ImGui::EndDragDropSource(), ImGui::EndMultiSelect(), ImGui::EndPopup(), ImGui::EndTable(), ExampleNames, ExampleTree_CreateDemoTree(), ImGuiStorage::GetBool(), ImGui::GetDragDropPayload(), ImGui::GetFontSize(), ImGui::GetIO(), ImGuiSelectionBasicStorage::GetNextSelectedItem(), ImGui::GetStateStorage(), ImGui::GetTextLineHeight(), ImGui::GetTextLineHeightWithSpacing(), HelpMarker(), IM_ARRAYSIZE, IM_COL32_A_MASK, IM_MIN, IMGUI_DEMO_MARKER, ImGuiChildFlags_Borders, ImGuiChildFlags_FrameStyle, ImGuiChildFlags_ResizeY, ImGuiColorEditFlags_NoTooltip, ImGuiInputFlags_Repeat, ImGuiInputTextFlags_ReadOnly, ImGuiKey_Delete, ImGuiMultiSelectFlags_BoxSelect1d, ImGuiMultiSelectFlags_BoxSelect2d, ImGuiMultiSelectFlags_BoxSelectNoScroll, ImGuiMultiSelectFlags_ClearOnClickVoid, ImGuiMultiSelectFlags_ClearOnEscape, ImGuiMultiSelectFlags_NoAutoClear, ImGuiMultiSelectFlags_NoAutoClearOnReselect, ImGuiMultiSelectFlags_NoAutoSelect, ImGuiMultiSelectFlags_NoRangeSelect, ImGuiMultiSelectFlags_NoSelectAll, ImGuiMultiSelectFlags_NoSelectOnRightClick, ImGuiMultiSelectFlags_ScopeRect, ImGuiMultiSelectFlags_ScopeWindow, ImGuiMultiSelectFlags_SelectOnClick, ImGuiMultiSelectFlags_SelectOnClickRelease, ImGuiMultiSelectFlags_SingleSelect, ImGuiSelectableFlags_AllowOverlap, ImGuiSelectableFlags_None, ImGuiSelectableFlags_SpanAllColumns, ImGuiSelectionRequestType_SetAll, ImGuiSelectionRequestType_SetRange, ImGuiStyleVar_CellPadding, ImGuiStyleVar_FramePadding, ImGuiStyleVar_ItemSpacing, ImGuiTableColumnFlags_WidthStretch, ImGuiTableFlags_BordersOuter, ImGuiTableFlags_NoPadOuterX, ImGuiTableFlags_NoSavedSettings, ImGuiTableFlags_Resizable, ImGuiTableFlags_RowBg, ImGuiTableFlags_ScrollY, ImGuiTreeNodeFlags_Bullet, ImGuiTreeNodeFlags_Leaf, ImGuiTreeNodeFlags_NavLeftJumpsToParent, ImGuiTreeNodeFlags_OpenOnArrow, ImGuiTreeNodeFlags_OpenOnDoubleClick, ImGuiTreeNodeFlags_Selected, ImGuiTreeNodeFlags_SpanAvailWidth, ImGuiListClipper::IncludeItemByIndex(), ExampleTreeNode::IndexInParent, ImGui::InputText(), ImGui::IsItemToggledOpen(), ExampleDualListBox::Items, ExampleTreeNode::Parent, ImVector< T >::pop_back(), ImGui::PopID(), ImGui::PopStyleVar(), ImVector< T >::push_back(), ImGui::PushID(), ImGui::PushStyleVar(), ImGui::PushStyleVarY(), ImGui::RadioButton(), ImGuiMultiSelectIO::RangeSrcItem, ImGuiMultiSelectIO::Requests, ImGui::SameLine(), ImGui::Selectable(), ImGui::SeparatorText(), ImGuiStorage::SetBool(), ImGui::SetDragDropPayload(), ImGuiSelectionBasicStorage::SetItemSelected(), ImGui::SetKeyboardFocusHere(), ImGui::SetNextItemSelectionUserData(), ImGui::SetNextItemStorageID(), ImGui::SetNextItemWidth(), ImGui::SetNextWindowContentSize(), ImGui::Shortcut(), ExampleDualListBox::Show(), ImGuiDemoWindowData::ShowAppAssetsBrowser, ImVector< T >::Size, ImGuiSelectionBasicStorage::Size, ImVector< T >::size_in_bytes(), ImGui::SmallButton(), ImGuiListClipper::Step(), ImGui::TableHeadersRow(), ImGui::TableNextColumn(), ImGui::TableNextRow(), ImGui::TableSetupColumn(), ImGui::TableSetupScrollFreeze(), ImGui::Text(), ImGui::TextLinkOpenURL(), ImGui::TreeNode(), ImGui::TreeNodeEx(), ImGui::TreePop(), ExampleTreeNode::UID, ImGuiSelectionBasicStorage::UserData, and ImGuiSelectionExternalStorage::UserData.
Referenced by DemoWindowWidgets().
DemoWindowWidgetsTabs()
static void DemoWindowWidgetsTabs () static
Definition at line 3410 of file imgui_demo.cpp.
References ImGui::AlignTextToFramePadding(), ImGui::BeginPopup(), ImGui::BeginTabBar(), ImGui::BeginTabItem(), ImGui::Checkbox(), ImGui::CheckboxFlags(), ImVector< T >::Data, EditTabBarFittingPolicyFlags(), ImGui::EndPopup(), ImGui::EndTabBar(), ImGui::EndTabItem(), ImVector< T >::erase(), IM_ARRAYSIZE, IMGUI_DEMO_MARKER, ImGuiTabBarFlags_AutoSelectNewTabs, ImGuiTabBarFlags_DrawSelectedOverline, ImGuiTabBarFlags_FittingPolicyShrink, ImGuiTabBarFlags_NoCloseWithMiddleMouseButton, ImGuiTabBarFlags_None, ImGuiTabBarFlags_Reorderable, ImGuiTabBarFlags_TabListPopupButton, ImGuiTabItemFlags_Leading, ImGuiTabItemFlags_None, ImGuiTabItemFlags_NoTooltip, ImGuiTabItemFlags_Trailing, ImGui::OpenPopup(), ImVector< T >::push_back(), ImGui::SameLine(), ImGui::Selectable(), ImGui::Separator(), ImVector< T >::Size, ImGui::TabItemButton(), ImGui::Text(), ImGui::TreeNode(), and ImGui::TreePop().
Referenced by DemoWindowWidgets().
DemoWindowWidgetsText()
static void DemoWindowWidgetsText () static
Definition at line 3554 of file imgui_demo.cpp.
References ImDrawList::AddRect(), ImDrawList::AddRectFilled(), ImGuiStyle::FontScaleDpi, ImGuiStyle::FontScaleMain, ImGuiStyle::FontSizeBase, ImGui::GetCursorPos(), ImGui::GetCursorScreenPos(), ImGui::GetFontSize(), ImGui::GetItemRectMax(), ImGui::GetItemRectMin(), ImGui::GetStyle(), ImGui::GetTextLineHeight(), ImGui::GetWindowDrawList(), HelpMarker(), IM_ARRAYSIZE, IM_COL32, IMGUI_DEMO_MARKER, ImGui::InputText(), ImGui::PopFont(), ImGui::PopTextWrapPos(), ImGui::PushFont(), ImGui::PushTextWrapPos(), ImGui::SameLine(), ImGui::SeparatorText(), ImGui::SliderFloat(), ImGui::Spacing(), ImGui::Text(), ImGui::TextColored(), ImGui::TextDisabled(), ImGui::TextWrapped(), ImGui::TreeNode(), ImGui::TreePop(), ImVec2::x, and ImVec2::y.
Referenced by DemoWindowWidgets().
DemoWindowWidgetsTextFilter()
static void DemoWindowWidgetsTextFilter () static
Definition at line 3673 of file imgui_demo.cpp.
References ImGui::BulletText(), ImGuiTextFilter::Draw(), HelpMarker(), IM_ARRAYSIZE, IMGUI_DEMO_MARKER, ImGuiTextFilter::PassFilter(), ImGui::Text(), ImGui::TreeNode(), and ImGui::TreePop().
Referenced by DemoWindowWidgets().
DemoWindowWidgetsTextInput()
static void DemoWindowWidgetsTextInput () static
Definition at line 3700 of file imgui_demo.cpp.
References ImVector< T >::begin(), ImVector< T >::capacity(), ImGui::CheckboxFlags(), ImVector< T >::empty(), ImGui::GetTextLineHeight(), HelpMarker(), IM_ARRAYSIZE, IM_ASSERT, IMGUI_DEMO_MARKER, ImGuiInputTextFlags_AllowTabInput, ImGuiInputTextFlags_CallbackCharFilter, ImGuiInputTextFlags_CallbackCompletion, ImGuiInputTextFlags_CallbackEdit, ImGuiInputTextFlags_CallbackHistory, ImGuiInputTextFlags_CallbackResize, ImGuiInputTextFlags_CharsDecimal, ImGuiInputTextFlags_CharsHexadecimal, ImGuiInputTextFlags_CharsNoBlank, ImGuiInputTextFlags_CharsUppercase, ImGuiInputTextFlags_CtrlEnterForNewLine, ImGuiInputTextFlags_ElideLeft, ImGuiInputTextFlags_EscapeClearsAll, ImGuiInputTextFlags_None, ImGuiInputTextFlags_NoUndoRedo, ImGuiInputTextFlags_Password, ImGuiInputTextFlags_ReadOnly, ImGuiInputTextFlags_WordWrap, ImGuiKey_DownArrow, ImGuiKey_UpArrow, ImGui::InputText(), ImGui::InputTextMultiline(), ImGui::InputTextWithHint(), ImVector< T >::push_back(), ImVector< T >::resize(), ImGui::SameLine(), ImVector< T >::size(), ImGui::Text(), ImGui::TreeNode(), and ImGui::TreePop().
Referenced by DemoWindowWidgets().
DemoWindowWidgetsTooltips()
static void DemoWindowWidgetsTooltips () static
Definition at line 3920 of file imgui_demo.cpp.
References ImGui::BeginDisabled(), ImGui::BeginItemTooltip(), ImGui::BeginTooltip(), ImGui::Button(), ImGui::EndDisabled(), ImGui::EndTooltip(), ImGui::GetFontSize(), ImGui::GetStyle(), ImGui::GetTime(), HelpMarker(), IM_ARRAYSIZE, IMGUI_DEMO_MARKER, ImGuiHoveredFlags_DelayNone, ImGuiHoveredFlags_DelayNormal, ImGuiHoveredFlags_DelayShort, ImGuiHoveredFlags_ForTooltip, ImGuiHoveredFlags_NoSharedDelay, ImGuiHoveredFlags_Stationary, ImGui::IsItemHovered(), ImGui::PlotLines(), ImGui::ProgressBar(), ImGui::RadioButton(), ImGui::SameLine(), ImGui::SeparatorText(), ImGui::SetItemTooltip(), ImGui::SetTooltip(), ImGui::Text(), ImGui::TreeNode(), and ImGui::TreePop().
Referenced by DemoWindowWidgets().
DemoWindowWidgetsTreeNodes()
static void DemoWindowWidgetsTreeNodes () static
of the loop. May be a pointer to your own node type, etc.
Definition at line 4019 of file imgui_demo.cpp.
References ImGui::BeginDragDropSource(), ImGui::BulletText(), ImGui::Button(), ImGui::Checkbox(), ImGui::CheckboxFlags(), ImGui::EndDragDropSource(), ImGui::GetIO(), ImGui::GetTreeNodeToLabelSpacing(), HelpMarker(), IMGUI_DEMO_MARKER, ImGuiCond_Once, ImGuiTreeNodeFlags_AllowOverlap, ImGuiTreeNodeFlags_DefaultOpen, ImGuiTreeNodeFlags_DrawLinesFull, ImGuiTreeNodeFlags_DrawLinesNone, ImGuiTreeNodeFlags_DrawLinesToNodes, ImGuiTreeNodeFlags_Framed, ImGuiTreeNodeFlags_FramePadding, ImGuiTreeNodeFlags_Leaf, ImGuiTreeNodeFlags_NavLeftJumpsToParent, ImGuiTreeNodeFlags_NoTreePushOnOpen, ImGuiTreeNodeFlags_OpenOnArrow, ImGuiTreeNodeFlags_OpenOnDoubleClick, ImGuiTreeNodeFlags_Selected, ImGuiTreeNodeFlags_SpanAllColumns, ImGuiTreeNodeFlags_SpanAvailWidth, ImGuiTreeNodeFlags_SpanFullWidth, ImGuiTreeNodeFlags_SpanLabelWidth, ImGui::Indent(), ImGui::IsItemClicked(), ImGui::IsItemToggledOpen(), ImGui::PopID(), ImGui::PushID(), ImGui::SameLine(), ImGui::SetDragDropPayload(), ImGui::SetNextItemOpen(), ImGui::SmallButton(), ImGui::Text(), ImGui::TreeNode(), ImGui::TreeNodeEx(), ImGui::TreePop(), and ImGui::Unindent().
Referenced by DemoWindowWidgets().
DemoWindowWidgetsVerticalSliders()
static void DemoWindowWidgetsVerticalSliders () static
Definition at line 4189 of file imgui_demo.cpp.
References ImGui::BeginGroup(), ImGui::EndGroup(), ImColor::HSV(), IMGUI_DEMO_MARKER, ImGuiCol_FrameBg, ImGuiCol_FrameBgActive, ImGuiCol_FrameBgHovered, ImGuiCol_SliderGrab, ImGuiStyleVar_GrabMinSize, ImGuiStyleVar_ItemSpacing, ImGui::IsItemActive(), ImGui::IsItemHovered(), ImGui::PopID(), ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGui::PushID(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), ImGui::SameLine(), ImGui::SetTooltip(), ImGui::TreeNode(), ImGui::TreePop(), ImGui::VSliderFloat(), and ImGui::VSliderInt().
Referenced by DemoWindowWidgets().
EditTabBarFittingPolicyFlags()
static void EditTabBarFittingPolicyFlags (ImGuiTabBarFlags * p_flags) static
Definition at line 3398 of file imgui_demo.cpp.
References ImGui::CheckboxFlags(), ImGuiTabBarFlags_FittingPolicyDefault_, ImGuiTabBarFlags_FittingPolicyMask_, ImGuiTabBarFlags_FittingPolicyMixed, ImGuiTabBarFlags_FittingPolicyScroll, and ImGuiTabBarFlags_FittingPolicyShrink.
Referenced by DemoWindowWidgetsTabs().
EditTableColumnsFlags()
static void EditTableColumnsFlags (ImGuiTableColumnFlags * p_flags) static
Definition at line 5626 of file imgui_demo.cpp.
References ImGui::CheckboxFlags(), HelpMarker(), ImGuiTableColumnFlags_AngledHeader, ImGuiTableColumnFlags_DefaultHide, ImGuiTableColumnFlags_DefaultSort, ImGuiTableColumnFlags_Disabled, ImGuiTableColumnFlags_IndentDisable, ImGuiTableColumnFlags_IndentEnable, ImGuiTableColumnFlags_NoClip, ImGuiTableColumnFlags_NoHeaderLabel, ImGuiTableColumnFlags_NoHeaderWidth, ImGuiTableColumnFlags_NoHide, ImGuiTableColumnFlags_NoReorder, ImGuiTableColumnFlags_NoResize, ImGuiTableColumnFlags_NoSort, ImGuiTableColumnFlags_NoSortAscending, ImGuiTableColumnFlags_NoSortDescending, ImGuiTableColumnFlags_PreferSortAscending, ImGuiTableColumnFlags_PreferSortDescending, ImGuiTableColumnFlags_WidthFixed, ImGuiTableColumnFlags_WidthMask_, ImGuiTableColumnFlags_WidthStretch, and ImGui::SameLine().
Referenced by DemoWindowTables().
EditTableSizingFlags()
static void EditTableSizingFlags (ImGuiTableFlags * p_flags) static
Definition at line 5585 of file imgui_demo.cpp.
References ImGui::BeginCombo(), ImGui::BeginItemTooltip(), ImGui::EndCombo(), ImGui::EndTooltip(), ImGui::GetCursorPosX(), ImGui::GetFontSize(), ImGui::GetStyle(), IM_ARRAYSIZE, ImGuiTableFlags_None, ImGuiTableFlags_SizingFixedFit, ImGuiTableFlags_SizingFixedSame, ImGuiTableFlags_SizingMask_, ImGuiTableFlags_SizingStretchProp, ImGuiTableFlags_SizingStretchSame, ImGui::PopTextWrapPos(), ImGui::PushTextWrapPos(), ImGui::SameLine(), ImGui::Selectable(), ImGui::Separator(), ImGui::SetCursorPosX(), ImGui::Text(), ImGui::TextDisabled(), and ImGui::TextUnformatted().
Referenced by DemoWindowTables().
ExampleTree_CreateDemoTree()
static ExampleTreeNode * ExampleTree_CreateDemoTree () static
Definition at line 785 of file imgui_demo.cpp.
References ExampleTree_CreateNode(), ExampleTreeNode::HasData, IM_ARRAYSIZE, and ExampleTreeNode::Name.
Referenced by DemoWindowWidgetsSelectionAndMultiSelect(), and ShowExampleAppPropertyEditor().
ExampleTree_CreateNode()
static ExampleTreeNode * ExampleTree_CreateNode (const char * name, int uid, ExampleTreeNode * parent) static
Definition at line 764 of file imgui_demo.cpp.
References ExampleTreeNode::Childs, IM_ARRAYSIZE, IM_NEW, ExampleTreeNode::IndexInParent, ExampleTreeNode::Name, ExampleTreeNode::Parent, ImVector< T >::push_back(), ImVector< T >::Size, and ExampleTreeNode::UID.
Referenced by ExampleTree_CreateDemoTree().
ExampleTree_DestroyNode()
static void ExampleTree_DestroyNode (ExampleTreeNode * node) static
Definition at line 776 of file imgui_demo.cpp.
References ExampleTreeNode::Childs, ExampleTree_DestroyNode(), and IM_DELETE().
Referenced by ExampleTree_DestroyNode(), and ImGuiDemoWindowData::~ImGuiDemoWindowData().
GetTreeLinesFlagsName()
static const char * GetTreeLinesFlagsName (ImGuiTreeNodeFlags flags) static
Definition at line 8310 of file imgui_demo.cpp.
References ImGuiTreeNodeFlags_DrawLinesFull, ImGuiTreeNodeFlags_DrawLinesNone, and ImGuiTreeNodeFlags_DrawLinesToNodes.
Referenced by ImGui::ShowStyleEditor().
HelpMarker()
static void HelpMarker (const char * desc) static
Definition at line 273 of file imgui_demo.cpp.
References ImGui::BeginItemTooltip(), ImGui::EndTooltip(), ImGui::GetFontSize(), ImGui::PopTextWrapPos(), ImGui::PushTextWrapPos(), ImGui::TextDisabled(), and ImGui::TextUnformatted().
Referenced by DemoWindowColumns(), DemoWindowInputs(), DemoWindowLayout(), DemoWindowPopups(), DemoWindowTables(), DemoWindowWidgetsBasic(), DemoWindowWidgetsColorAndPickers(), DemoWindowWidgetsComboBoxes(), DemoWindowWidgetsDataTypes(), DemoWindowWidgetsDisableBlocks(), DemoWindowWidgetsDragAndDrop(), DemoWindowWidgetsDragsAndSliders(), DemoWindowWidgetsListBoxes(), DemoWindowWidgetsQueryingStatuses(), DemoWindowWidgetsSelectables(), DemoWindowWidgetsSelectionAndMultiSelect(), DemoWindowWidgetsText(), DemoWindowWidgetsTextFilter(), DemoWindowWidgetsTextInput(), DemoWindowWidgetsTooltips(), DemoWindowWidgetsTreeNodes(), ExampleAssetsBrowser::Draw(), EditTableColumnsFlags(), ImGui::ShowAboutWindow(), ImGui::ShowDemoWindow(), ShowExampleAppCustomRendering(), ShowExampleAppFullscreen(), and ImGui::ShowStyleEditor().
PathConcaveShape()
static void PathConcaveShape (ImDrawList * draw_list, float x, float y, float sz) static
Definition at line 9870 of file imgui_demo.cpp.
References ImDrawList::PathLineTo().
Referenced by ShowExampleAppCustomRendering().
PopStyleCompact()
static void PopStyleCompact () static
Definition at line 5579 of file imgui_demo.cpp.
References ImGui::PopStyleVar().
Referenced by DemoWindowTables().
PushStyleCompact()
static void PushStyleCompact () static
Definition at line 5572 of file imgui_demo.cpp.
References ImGuiStyle::FramePadding, ImGui::GetStyle(), ImGuiStyleVar_FramePadding, ImGuiStyleVar_ItemSpacing, ImGuiStyle::ItemSpacing, ImGui::PushStyleVarY(), and ImVec2::y.
Referenced by DemoWindowTables().
ShowExampleAppAssetsBrowser()
void ShowExampleAppAssetsBrowser (bool * p_open) static
Definition at line 10887 of file imgui_demo.cpp.
References ExampleAssetsBrowser::Draw(), and IMGUI_DEMO_MARKER.
Referenced by ImGui::ShowDemoWindow().
ShowExampleAppAutoResize()
static void ShowExampleAppAutoResize (bool * p_open) static
Definition at line 9618 of file imgui_demo.cpp.
References ImGui::Begin(), ImGui::End(), IMGUI_DEMO_MARKER, ImGuiWindowFlags_AlwaysAutoResize, ImGui::SliderInt(), ImGui::Text(), and ImGui::TextUnformatted().
Referenced by ImGui::ShowDemoWindow().
ShowExampleAppConsole()
static void ShowExampleAppConsole (bool * p_open) static
Definition at line 9162 of file imgui_demo.cpp.
References ExampleAppConsole::Draw().
Referenced by ImGui::ShowDemoWindow().
ShowExampleAppConstrainedResize()
static void ShowExampleAppConstrainedResize (bool * p_open) static
Definition at line 9644 of file imgui_demo.cpp.
References ImGui::Begin(), ImGui::Button(), ImGui::Checkbox(), ImGui::ColorButton(), ImGui::Combo(), ImGui::DragInt(), ImGui::End(), ImGui::GetContentRegionAvail(), ImGui::GetCursorScreenPos(), ImGui::GetFontSize(), ImGui::GetIO(), IM_ARRAYSIZE, IM_MAX, IMGUI_DEMO_MARKER, ImGuiColorEditFlags_NoDragDrop, ImGuiColorEditFlags_NoTooltip, ImGuiStyleVar_WindowPadding, ImGuiWindowFlags_AlwaysAutoResize, ImGui::PopStyleVar(), ImGui::PushStyleVar(), ImGui::SameLine(), ImGui::SetCursorScreenPos(), ImGui::SetNextItemWidth(), ImGui::SetNextWindowSizeConstraints(), ImGui::SetWindowSize(), ImGui::Text(), ImVec2::x, and ImVec2::y.
Referenced by ImGui::ShowDemoWindow().
ShowExampleAppCustomRendering()
static void ShowExampleAppCustomRendering (bool * p_open) static
Definition at line 9878 of file imgui_demo.cpp.
References ImDrawList::AddBezierCubic(), ImDrawList::AddBezierQuadratic(), ImDrawList::AddCircle(), ImDrawList::AddCircleFilled(), ImDrawList::AddEllipse(), ImDrawList::AddEllipseFilled(), ImDrawList::AddLine(), ImDrawList::AddNgon(), ImDrawList::AddNgonFilled(), ImDrawList::AddRect(), ImDrawList::AddRectFilled(), ImDrawList::AddRectFilledMultiColor(), ImDrawList::AddTriangle(), ImDrawList::AddTriangleFilled(), ImVector< T >::back(), ImGui::Begin(), ImGui::BeginPopup(), ImGui::BeginTabBar(), ImGui::BeginTabItem(), ImGui::CalcItemWidth(), ImDrawList::ChannelsMerge(), ImDrawList::ChannelsSetCurrent(), ImDrawList::ChannelsSplit(), ImGui::Checkbox(), ImVector< T >::clear(), ImGui::ColorEdit4(), ImGui::DragFloat(), ImGui::Dummy(), ImGui::End(), ImGui::EndPopup(), ImGui::EndTabBar(), ImGui::EndTabItem(), ImGui::GetBackgroundDrawList(), ImGui::GetColorU32(), ImGui::GetContentRegionAvail(), ImGui::GetCursorScreenPos(), ImGui::GetFontSize(), ImGui::GetForegroundDrawList(), ImGui::GetFrameHeight(), ImGui::GetIO(), ImGui::GetMouseDragDelta(), ImGui::GetStyle(), ImGui::GetWindowDrawList(), ImGui::GetWindowPos(), ImGui::GetWindowSize(), HelpMarker(), IM_COL32, ImDrawFlags_Closed, ImDrawFlags_None, ImDrawFlags_RoundCornersBottomRight, ImDrawFlags_RoundCornersTopLeft, IMGUI_DEMO_MARKER, ImGuiButtonFlags_MouseButtonLeft, ImGuiButtonFlags_MouseButtonRight, ImGuiMouseButton_Left, ImGuiMouseButton_Right, ImGuiPopupFlags_MouseButtonRight, ImGui::InvisibleButton(), ImGui::IsItemActive(), ImGui::IsItemHovered(), ImGui::IsMouseClicked(), ImGui::IsMouseDown(), ImGui::IsMouseDragging(), ImGui::MenuItem(), ImGuiIO::MouseDelta, ImGuiIO::MousePos, ImGui::OpenPopupOnItemClick(), ImDrawList::PathArcTo(), ImDrawList::PathBezierQuadraticCurveTo(), PathConcaveShape(), ImDrawList::PathFillConcave(), ImDrawList::PathFillConvex(), ImDrawList::PathLineTo(), ImDrawList::PathStroke(), ImDrawList::PopClipRect(), ImGui::PopItemWidth(), ImVector< T >::push_back(), ImDrawList::PushClipRect(), ImGui::PushItemWidth(), ImVector< T >::resize(), ImGui::SameLine(), ImGui::Separator(), ImVector< T >::Size, ImVector< T >::size(), ImGui::SliderInt(), ImGui::Text(), ImVec2::x, ImVec4::x, and ImVec2::y.
Referenced by ImGui::ShowDemoWindow().
ShowExampleAppDocuments()
void ShowExampleAppDocuments (bool * p_open) static
Definition at line 10299 of file imgui_demo.cpp.
References ImGui::Begin(), ImGui::BeginChild(), ImGui::BeginMenu(), ImGui::BeginMenuBar(), ImGui::BeginPopup(), ImGui::BeginPopupModal(), ImGui::BeginTabBar(), ImGui::BeginTabItem(), ImGui::Button(), ImGui::Checkbox(), ImVector< T >::clear(), ImGui::CloseCurrentPopup(), ExampleAppDocuments::CloseQueue, ExampleAppDocuments::DisplayDocContents(), ExampleAppDocuments::DisplayDocContextMenu(), ExampleAppDocuments::Documents, MyDocument::DoForceClose(), ImVector< T >::empty(), ImGui::End(), ImGui::EndChild(), ImGui::EndMenu(), ImGui::EndMenuBar(), ImGui::EndPopup(), ImGui::EndTabBar(), ImGui::EndTabItem(), ImGui::GetFontSize(), ImGui::GetID(), ExampleAppDocuments::GetTabName(), ImGui::GetTextLineHeightWithSpacing(), IM_ARRAYSIZE, ImGuiChildFlags_FrameStyle, ImGuiInputTextFlags_EnterReturnsTrue, ImGuiTabBarFlags_DrawSelectedOverline, ImGuiTabBarFlags_FittingPolicyDefault_, ImGuiTabBarFlags_Reorderable, ImGuiTabItemFlags_UnsavedDocument, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_MenuBar, ImGui::InputText(), ImGui::IsPopupOpen(), ImGui::MenuItem(), MyDocument::Name, ExampleAppDocuments::NotifyOfDocumentsClosedElsewhere(), MyDocument::Open, ImGui::OpenPopup(), ImGui::PopID(), ImVector< T >::push_back(), ImGui::PushID(), ExampleAppDocuments::RenamingDoc, ExampleAppDocuments::RenamingStarted, ImGui::SameLine(), ImGui::Separator(), ImGui::SetKeyboardFocusHere(), ImGui::SetNextItemWidth(), ImVector< T >::Size, and ImGui::Text().
Referenced by ImGui::ShowDemoWindow().
ShowExampleAppFullscreen()
static void ShowExampleAppFullscreen (bool * p_open) static
Definition at line 9798 of file imgui_demo.cpp.
References ImGui::Begin(), ImGui::Button(), ImGui::Checkbox(), ImGui::CheckboxFlags(), ImGui::End(), ImGui::GetMainViewport(), HelpMarker(), ImGuiWindowFlags_NoBackground, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoDecoration, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoSavedSettings, ImGuiWindowFlags_NoScrollbar, ImGuiWindowFlags_NoTitleBar, ImGui::Indent(), ImGuiViewport::Pos, ImGui::SameLine(), ImGui::SetNextWindowPos(), ImGui::SetNextWindowSize(), ImGuiViewport::Size, ImGui::Unindent(), ImGuiViewport::WorkPos, and ImGuiViewport::WorkSize.
Referenced by ImGui::ShowDemoWindow().
ShowExampleAppLayout()
static void ShowExampleAppLayout (bool * p_open) static
Definition at line 9335 of file imgui_demo.cpp.
References ImGui::Begin(), ImGui::BeginChild(), ImGui::BeginGroup(), ImGui::BeginMenu(), ImGui::BeginMenuBar(), ImGui::BeginTabBar(), ImGui::BeginTabItem(), ImGui::Button(), ImGui::End(), ImGui::EndChild(), ImGui::EndGroup(), ImGui::EndMenu(), ImGui::EndMenuBar(), ImGui::EndTabBar(), ImGui::EndTabItem(), ImGui::GetFrameHeightWithSpacing(), IMGUI_DEMO_MARKER, ImGuiChildFlags_Borders, ImGuiChildFlags_ResizeX, ImGuiCond_FirstUseEver, ImGuiSelectableFlags_SelectOnNav, ImGuiTabBarFlags_None, ImGuiWindowFlags_MenuBar, ImGui::MenuItem(), ImGui::SameLine(), ImGui::Selectable(), ImGui::Separator(), ImGui::SetNextWindowSize(), ImGui::Text(), and ImGui::TextWrapped().
Referenced by ImGui::ShowDemoWindow().
ShowExampleAppLog()
static void ShowExampleAppLog (bool * p_open) static
Definition at line 9300 of file imgui_demo.cpp.
References ExampleAppLog::AddLog(), ImGui::Begin(), ExampleAppLog::Draw(), ImGui::End(), ImGui::GetFrameCount(), ImGui::GetTime(), IM_ARRAYSIZE, IMGUI_DEMO_MARKER, ImGuiCond_FirstUseEver, ImGui::SetNextWindowSize(), and ImGui::SmallButton().
Referenced by ImGui::ShowDemoWindow().
ShowExampleAppLongText()
static void ShowExampleAppLongText (bool * p_open) static
Definition at line 9555 of file imgui_demo.cpp.
References ImGuiTextBuffer::appendf(), ImGuiTextBuffer::begin(), ImGui::Begin(), ImGuiListClipper::Begin(), ImGui::BeginChild(), ImGui::Button(), ImGuiTextBuffer::clear(), ImGui::Combo(), ImGuiListClipper::DisplayEnd, ImGuiListClipper::DisplayStart, ImGui::End(), ImGuiTextBuffer::end(), ImGui::EndChild(), IMGUI_DEMO_MARKER, ImGuiCond_FirstUseEver, ImGuiStyleVar_ItemSpacing, ImGui::PopStyleVar(), ImGui::PushStyleVar(), ImGui::SameLine(), ImGui::SetNextWindowSize(), ImGuiTextBuffer::size(), ImGuiListClipper::Step(), ImGui::Text(), and ImGui::TextUnformatted().
Referenced by ImGui::ShowDemoWindow().
ShowExampleAppMainMenuBar()
static void ShowExampleAppMainMenuBar () static
Definition at line 8699 of file imgui_demo.cpp.
References ImGui::BeginMainMenuBar(), ImGui::BeginMenu(), ImGui::EndMainMenuBar(), ImGui::EndMenu(), ImGui::MenuItem(), ImGui::Separator(), and ShowExampleMenuFile().
Referenced by ImGui::ShowDemoWindow().
ShowExampleAppPropertyEditor()
static void ShowExampleAppPropertyEditor (bool * p_open, ImGuiDemoWindowData * demo_data) static
Definition at line 9532 of file imgui_demo.cpp.
References ImGui::Begin(), ImGuiDemoWindowData::DemoTree, ExampleAppPropertyEditor::Draw(), ImGui::End(), ExampleTree_CreateDemoTree(), IMGUI_DEMO_MARKER, ImGuiCond_FirstUseEver, and ImGui::SetNextWindowSize().
Referenced by ImGui::ShowDemoWindow().
ShowExampleAppSimpleOverlay()
static void ShowExampleAppSimpleOverlay (bool * p_open) static
Definition at line 9743 of file imgui_demo.cpp.
References ImGui::Begin(), ImGui::BeginPopupContextWindow(), ImGui::End(), ImGui::EndPopup(), ImGui::GetIO(), ImGui::GetMainViewport(), IMGUI_DEMO_MARKER, ImGuiCond_Always, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoDecoration, ImGuiWindowFlags_NoFocusOnAppearing, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoNav, ImGuiWindowFlags_NoSavedSettings, ImGui::IsMousePosValid(), ImGui::MenuItem(), ImGuiIO::MousePos, ImGui::Separator(), ImGui::SetNextWindowBgAlpha(), ImGui::SetNextWindowPos(), ImGui::Text(), ImGuiViewport::WorkPos, ImGuiViewport::WorkSize, ImVec2::x, and ImVec2::y.
Referenced by ImGui::ShowDemoWindow().
ShowExampleAppWindowTitles()
static void ShowExampleAppWindowTitles (bool * p_open) static
Definition at line 9836 of file imgui_demo.cpp.
References ImGui::Begin(), ImGui::End(), ImGui::GetFrameCount(), ImGui::GetMainViewport(), ImGui::GetTime(), IMGUI_DEMO_MARKER, ImGuiCond_FirstUseEver, ImGuiViewport::Pos, ImGui::SetNextWindowPos(), ImGui::Text(), ImVec2::x, and ImVec2::y.
Referenced by ImGui::ShowDemoWindow().
ShowExampleMenuFile()
static void ShowExampleMenuFile () static
Definition at line 8724 of file imgui_demo.cpp.
References ImDrawList::AddRectFilled(), ImGui::BeginChild(), ImGui::BeginMenu(), ImGui::Checkbox(), ImGui::Combo(), ImGui::Dummy(), ImGui::EndChild(), ImGui::EndMenu(), ImGui::GetColorU32(), ImGui::GetCursorScreenPos(), ImGui::GetStyleColorName(), ImGui::GetTextLineHeight(), ImGui::GetWindowDrawList(), IM_ASSERT, IMGUI_DEMO_MARKER, ImGuiChildFlags_Borders, ImGuiCol_COUNT, ImGui::InputFloat(), ImGui::MenuItem(), ImGui::SameLine(), ImGui::Separator(), ShowExampleMenuFile(), ImGui::SliderFloat(), ImGui::Text(), ImVec2::x, and ImVec2::y.
Referenced by DemoWindowLayout(), DemoWindowMenuBar(), DemoWindowPopups(), ShowExampleAppMainMenuBar(), and ShowExampleMenuFile().
ShowTableColumnsStatusFlags()
static void ShowTableColumnsStatusFlags (ImGuiTableColumnFlags flags) static
Definition at line 5651 of file imgui_demo.cpp.
References ImGui::CheckboxFlags(), ImGuiTableColumnFlags_IsEnabled, ImGuiTableColumnFlags_IsHovered, ImGuiTableColumnFlags_IsSorted, and ImGuiTableColumnFlags_IsVisible.
Referenced by DemoWindowTables().
Variable Documentation
ExampleNames
const char* ExampleNames[] static
Initial value:
=
{
    "Artichoke", "Arugula", "Asparagus", "Avocado", "Bamboo Shoots", "Bean Sprouts", "Beans", "Beet", "Belgian Endive", "Bell Pepper",
    "Bitter Gourd", "Bok Choy", "Broccoli", "Brussels Sprouts", "Burdock Root", "Cabbage", "Calabash", "Capers", "Carrot", "Cassava",
    "Cauliflower", "Celery", "Celery Root", "Celcuce", "Chayote", "Chinese Broccoli", "Corn", "Cucumber"
}
Definition at line 2427 of file imgui_demo.cpp.
Referenced by DemoWindowWidgetsSelectionAndMultiSelect(), and ExampleDualListBox::Show().
ExampleTreeNodeMemberInfos
const ExampleMemberInfo ExampleTreeNodeMemberInfos[] static
Initial value:
{
    { "MyName",     ImGuiDataType_String,  1, offsetof(ExampleTreeNode, Name) },
    { "MyBool",     ImGuiDataType_Bool,    1, offsetof(ExampleTreeNode, DataMyBool) },
    { "MyInt",      ImGuiDataType_S32,     1, offsetof(ExampleTreeNode, DataMyInt) },
    { "MyVec2",     ImGuiDataType_Float,   2, offsetof(ExampleTreeNode, DataMyVec2) },
}
Definition at line 756 of file imgui_demo.cpp.
Referenced by ExampleAppPropertyEditor::Draw().
GImGuiDemoMarkerCallback
ImGuiDemoMarkerCallback GImGuiDemoMarkerCallback = NULL
Definition at line 289 of file imgui_demo.cpp.
GImGuiDemoMarkerCallbackUserData
void * GImGuiDemoMarkerCallbackUserData = NULL
Definition at line 290 of file imgui_demo.cpp.