SignalProcessing: examples/imgui/backends/imgui_impl_opengl2.h File Reference
imgui_impl_opengl2.h File Reference
#include "imgui.h"
Functions
IMGUI_IMPL_API bool ImGui_ImplOpenGL2_Init ()
IMGUI_IMPL_API void ImGui_ImplOpenGL2_Shutdown ()
IMGUI_IMPL_API void ImGui_ImplOpenGL2_NewFrame ()
IMGUI_IMPL_API void ImGui_ImplOpenGL2_RenderDrawData (ImDrawData *draw_data)
IMGUI_IMPL_API bool ImGui_ImplOpenGL2_CreateDeviceObjects ()
IMGUI_IMPL_API void ImGui_ImplOpenGL2_DestroyDeviceObjects ()
IMGUI_IMPL_API void ImGui_ImplOpenGL2_UpdateTexture (ImTextureData *tex)
Function Documentation
ImGui_ImplOpenGL2_CreateDeviceObjects()
IMGUI_IMPL_API bool ImGui_ImplOpenGL2_CreateDeviceObjects ()
Definition at line 331 of file imgui_impl_opengl2.cpp.
ImGui_ImplOpenGL2_DestroyDeviceObjects()
IMGUI_IMPL_API void ImGui_ImplOpenGL2_DestroyDeviceObjects ()
Definition at line 336 of file imgui_impl_opengl2.cpp.
References ImGui::GetPlatformIO(), ImGui_ImplOpenGL2_UpdateTexture(), ImTextureStatus_WantDestroy, and ImGuiPlatformIO::Textures.
Referenced by ImGui_ImplOpenGL2_Shutdown().
ImGui_ImplOpenGL2_Init()
IMGUI_IMPL_API bool ImGui_ImplOpenGL2_Init ()
Definition at line 99 of file imgui_impl_opengl2.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGui::GetIO(), IM_ASSERT, IM_NEW, IMGUI_CHECKVERSION, and ImGuiBackendFlags_RendererHasTextures.
Referenced by main(), and main().
ImGui_ImplOpenGL2_NewFrame()
IMGUI_IMPL_API void ImGui_ImplOpenGL2_NewFrame ()
Definition at line 130 of file imgui_impl_opengl2.cpp.
References IM_ASSERT, IM_UNUSED, and ImGui_ImplOpenGL2_GetBackendData().
Referenced by main(), and MainLoopStep().
ImGui_ImplOpenGL2_RenderDrawData()
IMGUI_IMPL_API void ImGui_ImplOpenGL2_RenderDrawData (ImDrawData * draw_data)
Definition at line 184 of file imgui_impl_opengl2.cpp.
References ImDrawCmd::ClipRect, ImDrawList::CmdBuffer, ImDrawData::CmdLists, ImVector< T >::Data, ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImDrawCmd::ElemCount, ImDrawData::FramebufferScale, ImDrawCmd::GetTexID(), GL_BACK, GL_COLOR_BUFFER_BIT, GL_FLOAT, GL_FRONT, GL_POLYGON_MODE, GL_SCISSOR_BOX, GL_TEXTURE_2D, GL_TEXTURE_BINDING_2D, GL_TRIANGLES, GL_UNSIGNED_BYTE, GL_UNSIGNED_INT, GL_UNSIGNED_SHORT, GL_VIEWPORT, glBindTexture, glDrawElements, glGetIntegerv, glPolygonMode, glScissor, glViewport, ImDrawList::IdxBuffer, ImDrawCmd::IdxOffset, ImDrawCallback_ResetRenderState, ImGui_ImplOpenGL2_SetupRenderState(), ImGui_ImplOpenGL2_UpdateTexture(), ImTextureStatus_OK, ImVector< T >::Size, ImDrawData::Textures, ImDrawCmd::UserCallback, ImDrawList::VtxBuffer, ImVec4::w, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by main(), and MainLoopStep().
ImGui_ImplOpenGL2_Shutdown()
IMGUI_IMPL_API void ImGui_ImplOpenGL2_Shutdown ()
Definition at line 114 of file imgui_impl_opengl2.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGuiPlatformIO::ClearRendererHandlers(), ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplOpenGL2_DestroyDeviceObjects(), ImGui_ImplOpenGL2_GetBackendData(), and ImGuiBackendFlags_RendererHasTextures.
Referenced by main(), and main().
ImGui_ImplOpenGL2_UpdateTexture()
IMGUI_IMPL_API void ImGui_ImplOpenGL2_UpdateTexture (ImTextureData * tex)
Definition at line 271 of file imgui_impl_opengl2.cpp.
References ImTextureData::BackendUserData, ImTextureData::Format, ImTextureData::GetPixels(), ImTextureData::GetPixelsAt(), GL_CALL, GL_LINEAR, GL_RGBA, GL_TEXTURE_2D, GL_TEXTURE_BINDING_2D, GL_TEXTURE_MAG_FILTER, GL_TEXTURE_MIN_FILTER, GL_TEXTURE_WRAP_S, GL_TEXTURE_WRAP_T, GL_UNPACK_ALIGNMENT, GL_UNPACK_ROW_LENGTH, GL_UNSIGNED_BYTE, glBindTexture, glDeleteTextures, glGenTextures, glGetIntegerv, glPixelStorei, glTexImage2D, glTexParameteri, glTexSubImage2D, ImTextureData::Height, IM_ASSERT, ImTextureFormat_RGBA32, ImTextureID_Invalid, ImTextureStatus_Destroyed, ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImTextureData::SetStatus(), ImTextureData::SetTexID(), ImTextureData::Status, ImTextureData::TexID, ImTextureData::Updates, and ImTextureData::Width.
Referenced by ImGui_ImplOpenGL2_DestroyDeviceObjects(), and ImGui_ImplOpenGL2_RenderDrawData().