SignalProcessing: examples/imgui/backends/imgui_impl_dx10.cpp File Reference
imgui_impl_dx10.cpp File Reference
#include "imgui.h"
#include "imgui_impl_dx10.h"
#include <stdio.h>
#include <d3d10_1.h>
#include <d3d10.h>
#include <d3dcompiler.h>
Classes
struct ImGui_ImplDX10_Texture
struct ImGui_ImplDX10_Data
struct VERTEX_CONSTANT_BUFFER_DX10
Functions
static ImGui_ImplDX10_Data * ImGui_ImplDX10_GetBackendData ()
static void ImGui_ImplDX10_SetupRenderState (ImDrawData *draw_data, ID3D10Device *device)
void ImGui_ImplDX10_RenderDrawData (ImDrawData *draw_data)
static void ImGui_ImplDX10_DestroyTexture (ImTextureData *tex)
void ImGui_ImplDX10_UpdateTexture (ImTextureData *tex)
bool ImGui_ImplDX10_CreateDeviceObjects ()
void ImGui_ImplDX10_InvalidateDeviceObjects ()
bool ImGui_ImplDX10_Init (ID3D10Device *device)
void ImGui_ImplDX10_Shutdown ()
void ImGui_ImplDX10_NewFrame ()
Function Documentation
ImGui_ImplDX10_CreateDeviceObjects()
bool ImGui_ImplDX10_CreateDeviceObjects ()
Definition at line 406 of file imgui_impl_dx10.cpp.
References ImGui_ImplDX10_GetBackendData(), ImGui_ImplDX10_InvalidateDeviceObjects(), ImGui_ImplDX10_Data::pBlendState, ImGui_ImplDX10_Data::pd3dDevice, ImGui_ImplDX10_Data::pDepthStencilState, ImGui_ImplDX10_Data::pInputLayout, ImGui_ImplDX10_Data::pPixelShader, ImGui_ImplDX10_Data::pRasterizerState, ImGui_ImplDX10_Data::pTexSamplerLinear, ImGui_ImplDX10_Data::pVertexConstantBuffer, and ImGui_ImplDX10_Data::pVertexShader.
Referenced by ImGui_ImplDX10_NewFrame().
ImGui_ImplDX10_DestroyTexture()
static void ImGui_ImplDX10_DestroyTexture (ImTextureData * tex) static
Definition at line 326 of file imgui_impl_dx10.cpp.
References ImTextureData::BackendUserData, IM_ASSERT, IM_DELETE(), ImTextureID_Invalid, ImTextureStatus_Destroyed, ImTextureData::SetStatus(), ImTextureData::SetTexID(), and ImTextureData::TexID.
Referenced by ImGui_ImplDX10_InvalidateDeviceObjects(), and ImGui_ImplDX10_UpdateTexture().
ImGui_ImplDX10_GetBackendData()
static ImGui_ImplDX10_Data * ImGui_ImplDX10_GetBackendData () static
Definition at line 94 of file imgui_impl_dx10.cpp.
References ImGuiIO::BackendRendererUserData, ImGui::GetCurrentContext(), and ImGui::GetIO().
Referenced by ImGui_ImplDX10_CreateDeviceObjects(), ImGui_ImplDX10_InvalidateDeviceObjects(), ImGui_ImplDX10_NewFrame(), ImGui_ImplDX10_RenderDrawData(), ImGui_ImplDX10_SetupRenderState(), ImGui_ImplDX10_Shutdown(), and ImGui_ImplDX10_UpdateTexture().
ImGui_ImplDX10_Init()
bool ImGui_ImplDX10_Init (ID3D10Device * device)
Definition at line 595 of file imgui_impl_dx10.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_NEW, IMGUI_CHECKVERSION, ImGuiBackendFlags_RendererHasTextures, ImGuiBackendFlags_RendererHasVtxOffset, ImGui_ImplDX10_Data::pd3dDevice, ImGui_ImplDX10_Data::pFactory, ImGuiPlatformIO::Renderer_TextureMaxHeight, and ImGuiPlatformIO::Renderer_TextureMaxWidth.
Referenced by main().
ImGui_ImplDX10_InvalidateDeviceObjects()
void ImGui_ImplDX10_InvalidateDeviceObjects ()
Definition at line 573 of file imgui_impl_dx10.cpp.
References ImGui::GetPlatformIO(), ImGui_ImplDX10_DestroyTexture(), ImGui_ImplDX10_GetBackendData(), ImGui_ImplDX10_Data::pBlendState, ImGui_ImplDX10_Data::pd3dDevice, ImGui_ImplDX10_Data::pDepthStencilState, ImGui_ImplDX10_Data::pIB, ImGui_ImplDX10_Data::pInputLayout, ImGui_ImplDX10_Data::pPixelShader, ImGui_ImplDX10_Data::pRasterizerState, ImGui_ImplDX10_Data::pTexSamplerLinear, ImGui_ImplDX10_Data::pVB, ImGui_ImplDX10_Data::pVertexConstantBuffer, ImGui_ImplDX10_Data::pVertexShader, and ImGuiPlatformIO::Textures.
Referenced by ImGui_ImplDX10_CreateDeviceObjects(), and ImGui_ImplDX10_Shutdown().
ImGui_ImplDX10_NewFrame()
void ImGui_ImplDX10_NewFrame ()
Definition at line 647 of file imgui_impl_dx10.cpp.
References IM_ASSERT, ImGui_ImplDX10_CreateDeviceObjects(), ImGui_ImplDX10_GetBackendData(), and ImGui_ImplDX10_Data::pVertexShader.
Referenced by main().
ImGui_ImplDX10_RenderDrawData()
void ImGui_ImplDX10_RenderDrawData (ImDrawData * draw_data)
Definition at line 155 of file imgui_impl_dx10.cpp.
References ImDrawCmd::ClipRect, ImDrawList::CmdBuffer, ImDrawData::CmdLists, ImVector< T >::Data, ImGui_ImplDX10_RenderState::Device, ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImDrawCmd::ElemCount, ImDrawData::FramebufferScale, ImGui::GetPlatformIO(), ImDrawCmd::GetTexID(), ImDrawList::IdxBuffer, ImDrawCmd::IdxOffset, ImDrawCallback_ResetRenderState, ImDrawIdx, ImGui_ImplDX10_GetBackendData(), ImGui_ImplDX10_SetupRenderState(), ImGui_ImplDX10_UpdateTexture(), ImTextureStatus_OK, ImGui_ImplDX10_Data::IndexBufferSize, ImGui_ImplDX10_Data::pd3dDevice, ImGui_ImplDX10_Data::pIB, ImGui_ImplDX10_Data::pTexSamplerLinear, ImGui_ImplDX10_Data::pVB, ImGui_ImplDX10_Data::pVertexConstantBuffer, ImGuiPlatformIO::Renderer_RenderState, ImGui_ImplDX10_RenderState::SamplerDefault, ImVector< T >::Size, ImDrawData::Textures, ImDrawData::TotalIdxCount, ImDrawData::TotalVtxCount, ImDrawCmd::UserCallback, ImGui_ImplDX10_Data::VertexBufferSize, ImGui_ImplDX10_RenderState::VertexConstantBuffer, ImDrawList::VtxBuffer, ImDrawCmd::VtxOffset, ImVec4::w, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by main().
ImGui_ImplDX10_SetupRenderState()
static void ImGui_ImplDX10_SetupRenderState (ImDrawData * draw_data, ID3D10Device * device) static
Definition at line 100 of file imgui_impl_dx10.cpp.
References ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImDrawData::FramebufferScale, ImGui_ImplDX10_GetBackendData(), VERTEX_CONSTANT_BUFFER_DX10::mvp, ImGui_ImplDX10_Data::pBlendState, ImGui_ImplDX10_Data::pDepthStencilState, ImGui_ImplDX10_Data::pIB, ImGui_ImplDX10_Data::pInputLayout, ImGui_ImplDX10_Data::pPixelShader, ImGui_ImplDX10_Data::pRasterizerState, ImGui_ImplDX10_Data::pTexSamplerLinear, ImGui_ImplDX10_Data::pVB, ImGui_ImplDX10_Data::pVertexConstantBuffer, ImGui_ImplDX10_Data::pVertexShader, ImVec2::x, and ImVec2::y.
Referenced by ImGui_ImplDX10_RenderDrawData().
ImGui_ImplDX10_Shutdown()
void ImGui_ImplDX10_Shutdown ()
Definition at line 629 of file imgui_impl_dx10.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGuiPlatformIO::ClearRendererHandlers(), ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplDX10_GetBackendData(), ImGui_ImplDX10_InvalidateDeviceObjects(), ImGuiBackendFlags_RendererHasTextures, ImGuiBackendFlags_RendererHasVtxOffset, ImGui_ImplDX10_Data::pd3dDevice, and ImGui_ImplDX10_Data::pFactory.
Referenced by main().
ImGui_ImplDX10_UpdateTexture()
void ImGui_ImplDX10_UpdateTexture (ImTextureData * tex)
Definition at line 342 of file imgui_impl_dx10.cpp.
References ImTextureData::BackendUserData, ImTextureData::Format, ImTextureData::GetPitch(), ImTextureData::GetPixels(), ImTextureData::GetPixelsAt(), ImTextureData::Height, IM_ASSERT, IM_NEW, ImGui_ImplDX10_DestroyTexture(), ImGui_ImplDX10_GetBackendData(), ImTextureFormat_RGBA32, ImTextureID_Invalid, ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImGui_ImplDX10_Data::pd3dDevice, ImGui_ImplDX10_Texture::pTexture, ImGui_ImplDX10_Texture::pTextureView, ImTextureData::SetStatus(), ImTextureData::SetTexID(), ImTextureData::Status, ImTextureData::TexID, ImTextureData::UnusedFrames, ImTextureData::Updates, and ImTextureData::Width.
Referenced by ImGui_ImplDX10_RenderDrawData().