SignalProcessing: examples/imgui/backends/imgui_impl_glfw.cpp File Reference
imgui_impl_glfw.cpp File Reference
#include "imgui.h"
#include "imgui_impl_glfw.h"
#include <GLFW/glfw3.h>
#include <unistd.h>
#include <stdio.h>
Classes
struct ImGui_ImplGlfw_WindowToContext
struct ImGui_ImplGlfw_Data
Namespaces
namespace ImGui
Macros
#define GLFW_HAS_X11 0
#define GLFW_HAS_WAYLAND 0
#define GLFW_VERSION_COMBINED (GLFW_VERSION_MAJOR * 1000 + GLFW_VERSION_MINOR * 100 + GLFW_VERSION_REVISION)
#define GLFW_HAS_PER_MONITOR_DPI (GLFW_VERSION_COMBINED >= 3300)
#define GLFW_HAS_NEW_CURSORS (0)
#define GLFW_HAS_CREATECURSOR (GLFW_VERSION_COMBINED >= 3100)
#define GLFW_HAS_GAMEPAD_API (GLFW_VERSION_COMBINED >= 3300)
#define GLFW_HAS_GETKEYNAME (GLFW_VERSION_COMBINED >= 3200)
#define GLFW_HAS_GETERROR (GLFW_VERSION_COMBINED >= 3300)
#define GLFW_HAS_GETPLATFORM (GLFW_VERSION_COMBINED >= 3400)
#define MAP_BUTTON(KEY_NO, _UNUSED, BUTTON_NO) do { io.AddKeyEvent(KEY_NO, (buttons_count > BUTTON_NO && buttons[BUTTON_NO] == GLFW_PRESS)); } while (0)
#define MAP_ANALOG(KEY_NO, _UNUSED, AXIS_NO, V0, V1) do { float v = (axes_count > AXIS_NO) ? axes[AXIS_NO] : V0; v = (v - V0) / (V1 - V0); io.AddKeyAnalogEvent(KEY_NO, v > 0.10f, Saturate(v)); } while (0)
Enumerations
enum GlfwClientApi { GlfwClientApi_OpenGL , GlfwClientApi_Vulkan , GlfwClientApi_Unknown }
Functions
static void ImGui_ImplGlfw_ContextMap_Add (GLFWwindow *window, ImGuiContext *ctx)
static void ImGui_ImplGlfw_ContextMap_Remove (GLFWwindow *window)
static ImGuiContext * ImGui_ImplGlfw_ContextMap_Get (GLFWwindow *window)
ImGuiIO & ImGui::GetIO (ImGuiContext *)
static ImGui_ImplGlfw_Data * ImGui_ImplGlfw_GetBackendData ()
static ImGui_ImplGlfw_Data * ImGui_ImplGlfw_GetBackendData (GLFWwindow *window)
static bool ImGui_ImplGlfw_IsWayland ()
ImGuiKey ImGui_ImplGlfw_KeyToImGuiKey (int keycode, int scancode)
static void ImGui_ImplGlfw_UpdateKeyModifiers (ImGuiIO &io, GLFWwindow *window)
static bool ImGui_ImplGlfw_ShouldChainCallback (ImGui_ImplGlfw_Data *bd, GLFWwindow *window)
void ImGui_ImplGlfw_MouseButtonCallback (GLFWwindow *window, int button, int action, int mods)
void ImGui_ImplGlfw_ScrollCallback (GLFWwindow *window, double xoffset, double yoffset)
static int ImGui_ImplGlfw_TranslateUntranslatedKey (int key, int scancode)
void ImGui_ImplGlfw_KeyCallback (GLFWwindow *window, int keycode, int scancode, int action, int mods)
void ImGui_ImplGlfw_WindowFocusCallback (GLFWwindow *window, int focused)
void ImGui_ImplGlfw_CursorPosCallback (GLFWwindow *window, double x, double y)
void ImGui_ImplGlfw_CursorEnterCallback (GLFWwindow *window, int entered)
void ImGui_ImplGlfw_CharCallback (GLFWwindow *window, unsigned int c)
void ImGui_ImplGlfw_MonitorCallback (GLFWmonitor *, int)
void ImGui_ImplGlfw_InstallCallbacks (GLFWwindow *window)
void ImGui_ImplGlfw_RestoreCallbacks (GLFWwindow *window)
void ImGui_ImplGlfw_SetCallbacksChainForAllWindows (bool chain_for_all_windows)
static bool ImGui_ImplGlfw_Init (GLFWwindow *window, bool install_callbacks, GlfwClientApi client_api)
bool ImGui_ImplGlfw_InitForOpenGL (GLFWwindow *window, bool install_callbacks)
bool ImGui_ImplGlfw_InitForVulkan (GLFWwindow *window, bool install_callbacks)
bool ImGui_ImplGlfw_InitForOther (GLFWwindow *window, bool install_callbacks)
void ImGui_ImplGlfw_Shutdown ()
static void ImGui_ImplGlfw_UpdateMouseData ()
static void ImGui_ImplGlfw_UpdateMouseCursor ()
static float Saturate (float v)
static void ImGui_ImplGlfw_UpdateGamepads ()
float ImGui_ImplGlfw_GetContentScaleForWindow (GLFWwindow *window)
float ImGui_ImplGlfw_GetContentScaleForMonitor (GLFWmonitor *monitor)
static void ImGui_ImplGlfw_GetWindowSizeAndFramebufferScale (GLFWwindow *window, ImVec2 *out_size, ImVec2 *out_framebuffer_scale)
void ImGui_ImplGlfw_NewFrame ()
void ImGui_ImplGlfw_Sleep (int milliseconds)
Variables
static ImVector< ImGui_ImplGlfw_WindowToContext > g_ContextMap
Macro Definition Documentation
GLFW_HAS_CREATECURSOR
#define GLFW_HAS_CREATECURSOR (GLFW_VERSION_COMBINED >= 3100)
Definition at line 165 of file imgui_impl_glfw.cpp.
GLFW_HAS_GAMEPAD_API
#define GLFW_HAS_GAMEPAD_API (GLFW_VERSION_COMBINED >= 3300)
Definition at line 166 of file imgui_impl_glfw.cpp.
GLFW_HAS_GETERROR
#define GLFW_HAS_GETERROR (GLFW_VERSION_COMBINED >= 3300)
Definition at line 168 of file imgui_impl_glfw.cpp.
GLFW_HAS_GETKEYNAME
#define GLFW_HAS_GETKEYNAME (GLFW_VERSION_COMBINED >= 3200)
Definition at line 167 of file imgui_impl_glfw.cpp.
GLFW_HAS_GETPLATFORM
#define GLFW_HAS_GETPLATFORM (GLFW_VERSION_COMBINED >= 3400)
Definition at line 169 of file imgui_impl_glfw.cpp.
GLFW_HAS_NEW_CURSORS
#define GLFW_HAS_NEW_CURSORS (0)
Definition at line 163 of file imgui_impl_glfw.cpp.
GLFW_HAS_PER_MONITOR_DPI
#define GLFW_HAS_PER_MONITOR_DPI (GLFW_VERSION_COMBINED >= 3300)
Definition at line 159 of file imgui_impl_glfw.cpp.
GLFW_HAS_WAYLAND
#define GLFW_HAS_WAYLAND 0
Definition at line 121 of file imgui_impl_glfw.cpp.
GLFW_HAS_X11
#define GLFW_HAS_X11 0
Definition at line 116 of file imgui_impl_glfw.cpp.
GLFW_VERSION_COMBINED
#define GLFW_VERSION_COMBINED (GLFW_VERSION_MAJOR * 1000 + GLFW_VERSION_MINOR * 100 + GLFW_VERSION_REVISION)
Definition at line 158 of file imgui_impl_glfw.cpp.
MAP_ANALOG
#define MAP_ANALOG (KEY_NO, _UNUSED, AXIS_NO, V0, V1) do { float v = (axes_count > AXIS_NO) ? axes[AXIS_NO] : V0; v = (v - V0) / (V1 - V0); io.AddKeyAnalogEvent(KEY_NO, v > 0.10f, Saturate(v)); } while (0)
MAP_BUTTON
#define MAP_BUTTON (KEY_NO, _UNUSED, BUTTON_NO) do { io.AddKeyEvent(KEY_NO, (buttons_count > BUTTON_NO && buttons[BUTTON_NO] == GLFW_PRESS)); } while (0)
Enumeration Type Documentation
GlfwClientApi
enum GlfwClientApi
Enumerator
GlfwClientApi_OpenGL
GlfwClientApi_Vulkan
GlfwClientApi_Unknown
Definition at line 181 of file imgui_impl_glfw.cpp.
Function Documentation
ImGui_ImplGlfw_CharCallback()
void ImGui_ImplGlfw_CharCallback (GLFWwindow * window, unsigned int c)
Definition at line 532 of file imgui_impl_glfw.cpp.
References ImGuiIO::AddInputCharacter(), ImGui_ImplGlfw_Data::Context, ImGui::GetIO(), ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_ShouldChainCallback(), and ImGui_ImplGlfw_Data::PrevUserCallbackChar.
Referenced by ImGui_ImplGlfw_InstallCallbacks().
ImGui_ImplGlfw_ContextMap_Add()
static void ImGui_ImplGlfw_ContextMap_Add (GLFWwindow * window, ImGuiContext * ctx) static
Definition at line 177 of file imgui_impl_glfw.cpp.
References g_ContextMap, and ImVector< T >::push_back().
Referenced by ImGui_ImplGlfw_Init().
ImGui_ImplGlfw_ContextMap_Get()
static ImGuiContext * ImGui_ImplGlfw_ContextMap_Get (GLFWwindow * window) static
Definition at line 179 of file imgui_impl_glfw.cpp.
References g_ContextMap.
Referenced by ImGui_ImplGlfw_GetBackendData().
ImGui_ImplGlfw_ContextMap_Remove()
static void ImGui_ImplGlfw_ContextMap_Remove (GLFWwindow * window) static
Definition at line 178 of file imgui_impl_glfw.cpp.
References g_ContextMap.
Referenced by ImGui_ImplGlfw_Shutdown().
ImGui_ImplGlfw_CursorEnterCallback()
void ImGui_ImplGlfw_CursorEnterCallback (GLFWwindow * window, int entered)
Definition at line 512 of file imgui_impl_glfw.cpp.
References ImGuiIO::AddMousePosEvent(), ImGui_ImplGlfw_Data::Context, ImGui::GetIO(), ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_ShouldChainCallback(), ImGui_ImplGlfw_Data::LastValidMousePos, ImGuiIO::MousePos, ImGui_ImplGlfw_Data::MouseWindow, ImGui_ImplGlfw_Data::PrevUserCallbackCursorEnter, ImVec2::x, and ImVec2::y.
Referenced by ImGui_ImplGlfw_InstallCallbacks().
ImGui_ImplGlfw_CursorPosCallback()
void ImGui_ImplGlfw_CursorPosCallback (GLFWwindow * window, double x, double y)
Definition at line 499 of file imgui_impl_glfw.cpp.
References ImGuiIO::AddMousePosEvent(), ImGui_ImplGlfw_Data::Context, ImGui::GetIO(), ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_ShouldChainCallback(), ImGui_ImplGlfw_Data::LastValidMousePos, and ImGui_ImplGlfw_Data::PrevUserCallbackCursorPos.
Referenced by ImGui_ImplGlfw_InstallCallbacks().
ImGui_ImplGlfw_GetBackendData() [1/2]
static ImGui_ImplGlfw_Data * ImGui_ImplGlfw_GetBackendData () static
Definition at line 233 of file imgui_impl_glfw.cpp.
References ImGuiIO::BackendPlatformUserData, ImGui::GetCurrentContext(), and ImGui::GetIO().
Referenced by ImGui_ImplGlfw_CharCallback(), ImGui_ImplGlfw_CursorEnterCallback(), ImGui_ImplGlfw_CursorPosCallback(), ImGui_ImplGlfw_GetContentScaleForWindow(), ImGui_ImplGlfw_GetWindowSizeAndFramebufferScale(), ImGui_ImplGlfw_Init(), ImGui_ImplGlfw_InstallCallbacks(), ImGui_ImplGlfw_KeyCallback(), ImGui_ImplGlfw_MouseButtonCallback(), ImGui_ImplGlfw_NewFrame(), ImGui_ImplGlfw_RestoreCallbacks(), ImGui_ImplGlfw_ScrollCallback(), ImGui_ImplGlfw_SetCallbacksChainForAllWindows(), ImGui_ImplGlfw_Shutdown(), ImGui_ImplGlfw_UpdateMouseCursor(), ImGui_ImplGlfw_UpdateMouseData(), and ImGui_ImplGlfw_WindowFocusCallback().
ImGui_ImplGlfw_GetBackendData() [2/2]
static ImGui_ImplGlfw_Data * ImGui_ImplGlfw_GetBackendData (GLFWwindow * window) static
Definition at line 238 of file imgui_impl_glfw.cpp.
References ImGuiIO::BackendPlatformUserData, ImGui::GetIO(), and ImGui_ImplGlfw_ContextMap_Get().
ImGui_ImplGlfw_GetContentScaleForMonitor()
float ImGui_ImplGlfw_GetContentScaleForMonitor (GLFWmonitor * monitor)
Definition at line 957 of file imgui_impl_glfw.cpp.
References glfwGetMonitorContentScale(), IM_UNUSED, and ImGui_ImplGlfw_IsWayland().
Referenced by main().
ImGui_ImplGlfw_GetContentScaleForWindow()
float ImGui_ImplGlfw_GetContentScaleForWindow (GLFWwindow * window)
Definition at line 940 of file imgui_impl_glfw.cpp.
References glfwGetWindowContentScale(), IM_UNUSED, ImGui_ImplGlfw_GetBackendData(), and ImGui_ImplGlfw_Data::IsWayland.
ImGui_ImplGlfw_GetWindowSizeAndFramebufferScale()
static void ImGui_ImplGlfw_GetWindowSizeAndFramebufferScale (GLFWwindow * window, ImVec2 * out_size, ImVec2 * out_framebuffer_scale) static
Definition at line 973 of file imgui_impl_glfw.cpp.
References glfwGetFramebufferSize(), glfwGetWindowSize(), ImGui_ImplGlfw_GetBackendData(), and ImGui_ImplGlfw_Data::IsWayland.
Referenced by ImGui_ImplGlfw_NewFrame().
ImGui_ImplGlfw_Init()
static bool ImGui_ImplGlfw_Init (GLFWwindow * window, bool install_callbacks, GlfwClientApi client_api) static
Definition at line 658 of file imgui_impl_glfw.cpp.
References ImGuiIO::BackendFlags, ImGui_ImplGlfw_Data::BackendPlatformName, ImGuiIO::BackendPlatformName, ImGuiIO::BackendPlatformUserData, ImGui_ImplGlfw_Data::ClientApi, ImGuiIO::ConfigMacOSXBehaviors, ImGui_ImplGlfw_Data::Context, ImGui::GetCurrentContext(), ImGui::GetIO(), ImGui::GetMainViewport(), ImGui::GetPlatformIO(), GLFW_ARROW_CURSOR, GLFW_HAND_CURSOR, GLFW_HRESIZE_CURSOR, GLFW_IBEAM_CURSOR, GLFW_VERSION_COMBINED, GLFW_VRESIZE_CURSOR, glfwCreateStandardCursor(), glfwGetClipboardString(), glfwGetError(), glfwSetClipboardString(), glfwSetErrorCallback(), IM_ASSERT, IM_NEW, IM_UNUSED, IMGUI_CHECKVERSION, ImGui_ImplGlfw_ContextMap_Add(), ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_InstallCallbacks(), ImGui_ImplGlfw_IsWayland(), ImGuiBackendFlags_HasMouseCursors, ImGuiBackendFlags_HasSetMousePos, ImGuiMouseCursor_Arrow, ImGuiMouseCursor_Hand, ImGuiMouseCursor_NotAllowed, ImGuiMouseCursor_ResizeAll, ImGuiMouseCursor_ResizeEW, ImGuiMouseCursor_ResizeNESW, ImGuiMouseCursor_ResizeNS, ImGuiMouseCursor_ResizeNWSE, ImGuiMouseCursor_TextInput, ImGui_ImplGlfw_Data::IsWayland, ImGuiPlatformIO::Platform_GetClipboardTextFn, ImGuiPlatformIO::Platform_OpenInShellFn, ImGuiPlatformIO::Platform_SetClipboardTextFn, ImGuiViewport::PlatformHandle, ImGuiViewport::PlatformHandleRaw, ImGui_ImplGlfw_Data::Time, and ImGui_ImplGlfw_Data::Window.
Referenced by ImGui_ImplGlfw_InitForOpenGL(), ImGui_ImplGlfw_InitForOther(), and ImGui_ImplGlfw_InitForVulkan().
ImGui_ImplGlfw_InitForOpenGL()
bool ImGui_ImplGlfw_InitForOpenGL (GLFWwindow * window, bool install_callbacks)
Definition at line 767 of file imgui_impl_glfw.cpp.
References GlfwClientApi_OpenGL, and ImGui_ImplGlfw_Init().
Referenced by main(), and main().
ImGui_ImplGlfw_InitForOther()
bool ImGui_ImplGlfw_InitForOther (GLFWwindow * window, bool install_callbacks)
Definition at line 777 of file imgui_impl_glfw.cpp.
References GlfwClientApi_Unknown, and ImGui_ImplGlfw_Init().
Referenced by main().
ImGui_ImplGlfw_InitForVulkan()
bool ImGui_ImplGlfw_InitForVulkan (GLFWwindow * window, bool install_callbacks)
Definition at line 772 of file imgui_impl_glfw.cpp.
References GlfwClientApi_Vulkan, and ImGui_ImplGlfw_Init().
Referenced by main().
ImGui_ImplGlfw_InstallCallbacks()
void ImGui_ImplGlfw_InstallCallbacks (GLFWwindow * window)
Definition at line 598 of file imgui_impl_glfw.cpp.
References glfwSetCharCallback(), glfwSetCursorEnterCallback(), glfwSetCursorPosCallback(), glfwSetKeyCallback(), glfwSetMonitorCallback(), glfwSetMouseButtonCallback(), glfwSetScrollCallback(), glfwSetWindowFocusCallback(), IM_ASSERT, ImGui_ImplGlfw_CharCallback(), ImGui_ImplGlfw_CursorEnterCallback(), ImGui_ImplGlfw_CursorPosCallback(), ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_KeyCallback(), ImGui_ImplGlfw_MonitorCallback(), ImGui_ImplGlfw_MouseButtonCallback(), ImGui_ImplGlfw_ScrollCallback(), ImGui_ImplGlfw_WindowFocusCallback(), ImGui_ImplGlfw_Data::InstalledCallbacks, ImGui_ImplGlfw_Data::PrevUserCallbackChar, ImGui_ImplGlfw_Data::PrevUserCallbackCursorEnter, ImGui_ImplGlfw_Data::PrevUserCallbackCursorPos, ImGui_ImplGlfw_Data::PrevUserCallbackKey, ImGui_ImplGlfw_Data::PrevUserCallbackMonitor, ImGui_ImplGlfw_Data::PrevUserCallbackMousebutton, ImGui_ImplGlfw_Data::PrevUserCallbackScroll, ImGui_ImplGlfw_Data::PrevUserCallbackWindowFocus, and ImGui_ImplGlfw_Data::Window.
Referenced by ImGui_ImplGlfw_Init().
ImGui_ImplGlfw_IsWayland()
static bool ImGui_ImplGlfw_IsWayland () static
Definition at line 246 of file imgui_impl_glfw.cpp.
References glfwGetVersionString().
Referenced by ImGui_ImplGlfw_GetContentScaleForMonitor(), and ImGui_ImplGlfw_Init().
ImGui_ImplGlfw_KeyCallback()
void ImGui_ImplGlfw_KeyCallback (GLFWwindow * window, int keycode, int scancode, int action, int mods)
Definition at line 470 of file imgui_impl_glfw.cpp.
References ImGuiIO::AddKeyEvent(), ImGui_ImplGlfw_Data::Context, ImGui::GetIO(), GLFW_PRESS, GLFW_RELEASE, ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_KeyToImGuiKey(), ImGui_ImplGlfw_ShouldChainCallback(), ImGui_ImplGlfw_TranslateUntranslatedKey(), ImGui_ImplGlfw_UpdateKeyModifiers(), ImGui_ImplGlfw_Data::PrevUserCallbackKey, and ImGuiIO::SetKeyEventNativeData().
Referenced by ImGui_ImplGlfw_InstallCallbacks().
ImGui_ImplGlfw_KeyToImGuiKey()
ImGuiKey ImGui_ImplGlfw_KeyToImGuiKey (int keycode, int scancode)
Definition at line 266 of file imgui_impl_glfw.cpp.
References GLFW_KEY_0, GLFW_KEY_1, GLFW_KEY_2, GLFW_KEY_3, GLFW_KEY_4, GLFW_KEY_5, GLFW_KEY_6, GLFW_KEY_7, GLFW_KEY_8, GLFW_KEY_9, GLFW_KEY_A, GLFW_KEY_APOSTROPHE, GLFW_KEY_B, GLFW_KEY_BACKSLASH, GLFW_KEY_BACKSPACE, GLFW_KEY_C, GLFW_KEY_CAPS_LOCK, GLFW_KEY_COMMA, GLFW_KEY_D, GLFW_KEY_DELETE, GLFW_KEY_DOWN, GLFW_KEY_E, GLFW_KEY_END, GLFW_KEY_ENTER, GLFW_KEY_EQUAL, GLFW_KEY_ESCAPE, GLFW_KEY_F, GLFW_KEY_F1, GLFW_KEY_F10, GLFW_KEY_F11, GLFW_KEY_F12, GLFW_KEY_F13, GLFW_KEY_F14, GLFW_KEY_F15, GLFW_KEY_F16, GLFW_KEY_F17, GLFW_KEY_F18, GLFW_KEY_F19, GLFW_KEY_F2, GLFW_KEY_F20, GLFW_KEY_F21, GLFW_KEY_F22, GLFW_KEY_F23, GLFW_KEY_F24, GLFW_KEY_F3, GLFW_KEY_F4, GLFW_KEY_F5, GLFW_KEY_F6, GLFW_KEY_F7, GLFW_KEY_F8, GLFW_KEY_F9, GLFW_KEY_G, GLFW_KEY_GRAVE_ACCENT, GLFW_KEY_H, GLFW_KEY_HOME, GLFW_KEY_I, GLFW_KEY_INSERT, GLFW_KEY_J, GLFW_KEY_K, GLFW_KEY_KP_0, GLFW_KEY_KP_1, GLFW_KEY_KP_2, GLFW_KEY_KP_3, GLFW_KEY_KP_4, GLFW_KEY_KP_5, GLFW_KEY_KP_6, GLFW_KEY_KP_7, GLFW_KEY_KP_8, GLFW_KEY_KP_9, GLFW_KEY_KP_ADD, GLFW_KEY_KP_DECIMAL, GLFW_KEY_KP_DIVIDE, GLFW_KEY_KP_ENTER, GLFW_KEY_KP_EQUAL, GLFW_KEY_KP_MULTIPLY, GLFW_KEY_KP_SUBTRACT, GLFW_KEY_L, GLFW_KEY_LEFT, GLFW_KEY_LEFT_ALT, GLFW_KEY_LEFT_BRACKET, GLFW_KEY_LEFT_CONTROL, GLFW_KEY_LEFT_SHIFT, GLFW_KEY_LEFT_SUPER, GLFW_KEY_M, GLFW_KEY_MENU, GLFW_KEY_MINUS, GLFW_KEY_N, GLFW_KEY_NUM_LOCK, GLFW_KEY_O, GLFW_KEY_P, GLFW_KEY_PAGE_DOWN, GLFW_KEY_PAGE_UP, GLFW_KEY_PAUSE, GLFW_KEY_PERIOD, GLFW_KEY_PRINT_SCREEN, GLFW_KEY_Q, GLFW_KEY_R, GLFW_KEY_RIGHT, GLFW_KEY_RIGHT_ALT, GLFW_KEY_RIGHT_BRACKET, GLFW_KEY_RIGHT_CONTROL, GLFW_KEY_RIGHT_SHIFT, GLFW_KEY_RIGHT_SUPER, GLFW_KEY_S, GLFW_KEY_SCROLL_LOCK, GLFW_KEY_SEMICOLON, GLFW_KEY_SLASH, GLFW_KEY_SPACE, GLFW_KEY_T, GLFW_KEY_TAB, GLFW_KEY_U, GLFW_KEY_UP, GLFW_KEY_V, GLFW_KEY_W, GLFW_KEY_WORLD_1, GLFW_KEY_WORLD_2, GLFW_KEY_X, GLFW_KEY_Y, GLFW_KEY_Z, IM_UNUSED, ImGuiKey_0, ImGuiKey_1, ImGuiKey_2, ImGuiKey_3, ImGuiKey_4, ImGuiKey_5, ImGuiKey_6, ImGuiKey_7, ImGuiKey_8, ImGuiKey_9, ImGuiKey_A, ImGuiKey_Apostrophe, ImGuiKey_B, ImGuiKey_Backslash, ImGuiKey_Backspace, ImGuiKey_C, ImGuiKey_CapsLock, ImGuiKey_Comma, ImGuiKey_D, ImGuiKey_Delete, ImGuiKey_DownArrow, ImGuiKey_E, ImGuiKey_End, ImGuiKey_Enter, ImGuiKey_Equal, ImGuiKey_Escape, ImGuiKey_F, ImGuiKey_F1, ImGuiKey_F10, ImGuiKey_F11, ImGuiKey_F12, ImGuiKey_F13, ImGuiKey_F14, ImGuiKey_F15, ImGuiKey_F16, ImGuiKey_F17, ImGuiKey_F18, ImGuiKey_F19, ImGuiKey_F2, ImGuiKey_F20, ImGuiKey_F21, ImGuiKey_F22, ImGuiKey_F23, ImGuiKey_F24, ImGuiKey_F3, ImGuiKey_F4, ImGuiKey_F5, ImGuiKey_F6, ImGuiKey_F7, ImGuiKey_F8, ImGuiKey_F9, ImGuiKey_G, ImGuiKey_GraveAccent, ImGuiKey_H, ImGuiKey_Home, ImGuiKey_I, ImGuiKey_Insert, ImGuiKey_J, ImGuiKey_K, ImGuiKey_Keypad0, ImGuiKey_Keypad1, ImGuiKey_Keypad2, ImGuiKey_Keypad3, ImGuiKey_Keypad4, ImGuiKey_Keypad5, ImGuiKey_Keypad6, ImGuiKey_Keypad7, ImGuiKey_Keypad8, ImGuiKey_Keypad9, ImGuiKey_KeypadAdd, ImGuiKey_KeypadDecimal, ImGuiKey_KeypadDivide, ImGuiKey_KeypadEnter, ImGuiKey_KeypadEqual, ImGuiKey_KeypadMultiply, ImGuiKey_KeypadSubtract, ImGuiKey_L, ImGuiKey_LeftAlt, ImGuiKey_LeftArrow, ImGuiKey_LeftBracket, ImGuiKey_LeftCtrl, ImGuiKey_LeftShift, ImGuiKey_LeftSuper, ImGuiKey_M, ImGuiKey_Menu, ImGuiKey_Minus, ImGuiKey_N, ImGuiKey_None, ImGuiKey_NumLock, ImGuiKey_O, ImGuiKey_Oem102, ImGuiKey_P, ImGuiKey_PageDown, ImGuiKey_PageUp, ImGuiKey_Pause, ImGuiKey_Period, ImGuiKey_PrintScreen, ImGuiKey_Q, ImGuiKey_R, ImGuiKey_RightAlt, ImGuiKey_RightArrow, ImGuiKey_RightBracket, ImGuiKey_RightCtrl, ImGuiKey_RightShift, ImGuiKey_RightSuper, ImGuiKey_S, ImGuiKey_ScrollLock, ImGuiKey_Semicolon, ImGuiKey_Slash, ImGuiKey_Space, ImGuiKey_T, ImGuiKey_Tab, ImGuiKey_U, ImGuiKey_UpArrow, ImGuiKey_V, ImGuiKey_W, ImGuiKey_X, ImGuiKey_Y, and ImGuiKey_Z.
Referenced by ImGui_ImplGlfw_KeyCallback().
ImGui_ImplGlfw_MonitorCallback()
void ImGui_ImplGlfw_MonitorCallback (GLFWmonitor * monitor, int event)
Definition at line 542 of file imgui_impl_glfw.cpp.
Referenced by ImGui_ImplGlfw_InstallCallbacks().
ImGui_ImplGlfw_MouseButtonCallback()
void ImGui_ImplGlfw_MouseButtonCallback (GLFWwindow * window, int button, int action, int mods)
Definition at line 409 of file imgui_impl_glfw.cpp.
References ImGuiIO::AddMouseButtonEvent(), ImGui_ImplGlfw_Data::Context, ImGui::GetIO(), GLFW_PRESS, ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_ShouldChainCallback(), ImGui_ImplGlfw_UpdateKeyModifiers(), ImGuiMouseButton_COUNT, and ImGui_ImplGlfw_Data::PrevUserCallbackMousebutton.
Referenced by ImGui_ImplGlfw_InstallCallbacks().
ImGui_ImplGlfw_NewFrame()
void ImGui_ImplGlfw_NewFrame ()
Definition at line 992 of file imgui_impl_glfw.cpp.
References ImGuiIO::DeltaTime, ImGuiIO::DisplayFramebufferScale, ImGuiIO::DisplaySize, ImGui::GetIO(), glfwGetTime(), IM_ASSERT, ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_GetWindowSizeAndFramebufferScale(), ImGui_ImplGlfw_UpdateGamepads(), ImGui_ImplGlfw_UpdateMouseCursor(), ImGui_ImplGlfw_UpdateMouseData(), ImGui_ImplGlfw_Data::Time, and ImGui_ImplGlfw_Data::Window.
Referenced by main(), and main().
ImGui_ImplGlfw_RestoreCallbacks()
void ImGui_ImplGlfw_RestoreCallbacks (GLFWwindow * window)
Definition at line 615 of file imgui_impl_glfw.cpp.
References glfwSetCharCallback(), glfwSetCursorEnterCallback(), glfwSetCursorPosCallback(), glfwSetKeyCallback(), glfwSetMonitorCallback(), glfwSetMouseButtonCallback(), glfwSetScrollCallback(), glfwSetWindowFocusCallback(), IM_ASSERT, ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_Data::InstalledCallbacks, ImGui_ImplGlfw_Data::PrevUserCallbackChar, ImGui_ImplGlfw_Data::PrevUserCallbackCursorEnter, ImGui_ImplGlfw_Data::PrevUserCallbackCursorPos, ImGui_ImplGlfw_Data::PrevUserCallbackKey, ImGui_ImplGlfw_Data::PrevUserCallbackMonitor, ImGui_ImplGlfw_Data::PrevUserCallbackMousebutton, ImGui_ImplGlfw_Data::PrevUserCallbackScroll, ImGui_ImplGlfw_Data::PrevUserCallbackWindowFocus, and ImGui_ImplGlfw_Data::Window.
Referenced by ImGui_ImplGlfw_Shutdown().
ImGui_ImplGlfw_ScrollCallback()
void ImGui_ImplGlfw_ScrollCallback (GLFWwindow * window, double xoffset, double yoffset)
Definition at line 421 of file imgui_impl_glfw.cpp.
References ImGuiIO::AddMouseWheelEvent(), ImGui_ImplGlfw_Data::Context, ImGui::GetIO(), ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_ShouldChainCallback(), and ImGui_ImplGlfw_Data::PrevUserCallbackScroll.
Referenced by ImGui_ImplGlfw_InstallCallbacks().
ImGui_ImplGlfw_SetCallbacksChainForAllWindows()
void ImGui_ImplGlfw_SetCallbacksChainForAllWindows (bool chain_for_all_windows)
Definition at line 644 of file imgui_impl_glfw.cpp.
References ImGui_ImplGlfw_Data::CallbacksChainForAllWindows, and ImGui_ImplGlfw_GetBackendData().
ImGui_ImplGlfw_ShouldChainCallback()
static bool ImGui_ImplGlfw_ShouldChainCallback (ImGui_ImplGlfw_Data * bd, GLFWwindow * window) static
Definition at line 404 of file imgui_impl_glfw.cpp.
References ImGui_ImplGlfw_Data::CallbacksChainForAllWindows, and ImGui_ImplGlfw_Data::Window.
Referenced by ImGui_ImplGlfw_CharCallback(), ImGui_ImplGlfw_CursorEnterCallback(), ImGui_ImplGlfw_CursorPosCallback(), ImGui_ImplGlfw_KeyCallback(), ImGui_ImplGlfw_MouseButtonCallback(), ImGui_ImplGlfw_ScrollCallback(), and ImGui_ImplGlfw_WindowFocusCallback().
ImGui_ImplGlfw_Shutdown()
void ImGui_ImplGlfw_Shutdown ()
Definition at line 782 of file imgui_impl_glfw.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendPlatformName, ImGuiIO::BackendPlatformUserData, ImGuiPlatformIO::ClearPlatformHandlers(), ImGui::GetIO(), ImGui::GetMainViewport(), ImGui::GetPlatformIO(), glfwDestroyCursor(), IM_ASSERT, IM_DELETE(), ImGui_ImplGlfw_ContextMap_Remove(), ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_RestoreCallbacks(), ImGuiBackendFlags_HasGamepad, ImGuiBackendFlags_HasMouseCursors, ImGuiBackendFlags_HasSetMousePos, ImGuiMouseCursor_COUNT, ImGui_ImplGlfw_Data::InstalledCallbacks, ImGuiViewport::PlatformHandleRaw, and ImGui_ImplGlfw_Data::Window.
Referenced by main(), and main().
ImGui_ImplGlfw_Sleep()
void ImGui_ImplGlfw_Sleep (int milliseconds)
Definition at line 1017 of file imgui_impl_glfw.cpp.
Referenced by main().
ImGui_ImplGlfw_TranslateUntranslatedKey()
static int ImGui_ImplGlfw_TranslateUntranslatedKey (int key, int scancode) static
Definition at line 437 of file imgui_impl_glfw.cpp.
References GLFW_KEY_0, GLFW_KEY_A, GLFW_KEY_APOSTROPHE, GLFW_KEY_BACKSLASH, GLFW_KEY_COMMA, GLFW_KEY_EQUAL, GLFW_KEY_GRAVE_ACCENT, GLFW_KEY_KP_0, GLFW_KEY_KP_EQUAL, GLFW_KEY_LEFT_BRACKET, GLFW_KEY_MINUS, GLFW_KEY_PERIOD, GLFW_KEY_RIGHT_BRACKET, GLFW_KEY_SEMICOLON, GLFW_KEY_SLASH, glfwGetError(), glfwGetKeyName(), glfwSetErrorCallback(), IM_ARRAYSIZE, IM_ASSERT, and IM_UNUSED.
Referenced by ImGui_ImplGlfw_KeyCallback().
ImGui_ImplGlfw_UpdateGamepads()
static void ImGui_ImplGlfw_UpdateGamepads () static
Definition at line 886 of file imgui_impl_glfw.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::ConfigFlags, ImGui::GetIO(), GLFW_GAMEPAD_AXIS_LEFT_TRIGGER, GLFW_GAMEPAD_AXIS_LEFT_X, GLFW_GAMEPAD_AXIS_LEFT_Y, GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER, GLFW_GAMEPAD_AXIS_RIGHT_X, GLFW_GAMEPAD_AXIS_RIGHT_Y, GLFW_GAMEPAD_BUTTON_A, GLFW_GAMEPAD_BUTTON_B, GLFW_GAMEPAD_BUTTON_BACK, GLFW_GAMEPAD_BUTTON_DPAD_DOWN, GLFW_GAMEPAD_BUTTON_DPAD_LEFT, GLFW_GAMEPAD_BUTTON_DPAD_RIGHT, GLFW_GAMEPAD_BUTTON_DPAD_UP, GLFW_GAMEPAD_BUTTON_LEFT_BUMPER, GLFW_GAMEPAD_BUTTON_LEFT_THUMB, GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER, GLFW_GAMEPAD_BUTTON_RIGHT_THUMB, GLFW_GAMEPAD_BUTTON_START, GLFW_GAMEPAD_BUTTON_X, GLFW_GAMEPAD_BUTTON_Y, GLFW_JOYSTICK_1, glfwGetGamepadState(), glfwGetJoystickAxes(), glfwGetJoystickButtons(), ImGuiBackendFlags_HasGamepad, ImGuiConfigFlags_NavEnableGamepad, ImGuiKey_GamepadBack, ImGuiKey_GamepadDpadDown, ImGuiKey_GamepadDpadLeft, ImGuiKey_GamepadDpadRight, ImGuiKey_GamepadDpadUp, ImGuiKey_GamepadFaceDown, ImGuiKey_GamepadFaceLeft, ImGuiKey_GamepadFaceRight, ImGuiKey_GamepadFaceUp, ImGuiKey_GamepadL1, ImGuiKey_GamepadL2, ImGuiKey_GamepadL3, ImGuiKey_GamepadLStickDown, ImGuiKey_GamepadLStickLeft, ImGuiKey_GamepadLStickRight, ImGuiKey_GamepadLStickUp, ImGuiKey_GamepadR1, ImGuiKey_GamepadR2, ImGuiKey_GamepadR3, ImGuiKey_GamepadRStickDown, ImGuiKey_GamepadRStickLeft, ImGuiKey_GamepadRStickRight, ImGuiKey_GamepadRStickUp, ImGuiKey_GamepadStart, MAP_ANALOG, and MAP_BUTTON.
Referenced by ImGui_ImplGlfw_NewFrame().
ImGui_ImplGlfw_UpdateKeyModifiers()
static void ImGui_ImplGlfw_UpdateKeyModifiers (ImGuiIO & io, GLFWwindow * window) static
Definition at line 396 of file imgui_impl_glfw.cpp.
References ImGuiIO::AddKeyEvent(), GLFW_KEY_LEFT_ALT, GLFW_KEY_LEFT_CONTROL, GLFW_KEY_LEFT_SHIFT, GLFW_KEY_LEFT_SUPER, GLFW_KEY_RIGHT_ALT, GLFW_KEY_RIGHT_CONTROL, GLFW_KEY_RIGHT_SHIFT, GLFW_KEY_RIGHT_SUPER, GLFW_PRESS, glfwGetKey(), ImGuiMod_Alt, ImGuiMod_Ctrl, ImGuiMod_Shift, and ImGuiMod_Super.
Referenced by ImGui_ImplGlfw_KeyCallback(), and ImGui_ImplGlfw_MouseButtonCallback().
ImGui_ImplGlfw_UpdateMouseCursor()
static void ImGui_ImplGlfw_UpdateMouseCursor () static
Definition at line 847 of file imgui_impl_glfw.cpp.
References ImGuiIO::ConfigFlags, ImGui::GetIO(), ImGui::GetMouseCursor(), GLFW_CURSOR, GLFW_CURSOR_DISABLED, GLFW_CURSOR_HIDDEN, GLFW_CURSOR_NORMAL, glfwGetInputMode(), glfwSetCursor(), glfwSetInputMode(), ImGui_ImplGlfw_GetBackendData(), ImGuiConfigFlags_NoMouseCursorChange, ImGuiMouseCursor_Arrow, ImGuiMouseCursor_None, ImGuiIO::MouseDrawCursor, and ImGui_ImplGlfw_Data::Window.
Referenced by ImGui_ImplGlfw_NewFrame().
ImGui_ImplGlfw_UpdateMouseData()
static void ImGui_ImplGlfw_UpdateMouseData () static
Definition at line 816 of file imgui_impl_glfw.cpp.
References ImGuiIO::AddMousePosEvent(), ImGui::GetIO(), GLFW_FOCUSED, glfwGetCursorPos(), glfwGetWindowAttrib(), glfwSetCursorPos(), ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_Data::LastValidMousePos, ImGuiIO::MousePos, ImGui_ImplGlfw_Data::MouseWindow, ImGuiIO::WantSetMousePos, ImGui_ImplGlfw_Data::Window, ImVec2::x, and ImVec2::y.
Referenced by ImGui_ImplGlfw_NewFrame().
ImGui_ImplGlfw_WindowFocusCallback()
void ImGui_ImplGlfw_WindowFocusCallback (GLFWwindow * window, int focused)
Definition at line 489 of file imgui_impl_glfw.cpp.
References ImGuiIO::AddFocusEvent(), ImGui_ImplGlfw_Data::Context, ImGui::GetIO(), ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_ShouldChainCallback(), and ImGui_ImplGlfw_Data::PrevUserCallbackWindowFocus.
Referenced by ImGui_ImplGlfw_InstallCallbacks().
Saturate()
static float Saturate (float v) inline static
Definition at line 885 of file imgui_impl_glfw.cpp.
Variable Documentation
g_ContextMap
ImVector<ImGui_ImplGlfw_WindowToContext> g_ContextMap static
Definition at line 176 of file imgui_impl_glfw.cpp.
Referenced by ImGui_ImplGlfw_ContextMap_Add(), ImGui_ImplGlfw_ContextMap_Get(), and ImGui_ImplGlfw_ContextMap_Remove().