SignalProcessing: examples/imgui/misc/cpp/imgui_stdlib.cpp File Reference
imgui_stdlib.cpp File Reference
#include "imgui.h"
#include "imgui_stdlib.h"
Classes
struct InputTextCallback_UserData
Functions
static int InputTextCallback (ImGuiInputTextCallbackData *data)
Function Documentation
InputTextCallback()
static int InputTextCallback (ImGuiInputTextCallbackData * data) static
Definition at line 39 of file imgui_stdlib.cpp.
References InputTextCallback_UserData::ChainCallback, InputTextCallback_UserData::ChainCallbackUserData, IM_ASSERT, ImGuiInputTextFlags_CallbackResize, and InputTextCallback_UserData::Str.
Referenced by ImGui::InputText(), ImGui::InputTextMultiline(), and ImGui::InputTextWithHint().