SignalProcessing: examples/imgui/backends/imgui_impl_sdlgpu3.cpp File Reference
imgui_impl_sdlgpu3.cpp File Reference
#include "imgui.h"
#include "imgui_impl_sdlgpu3.h"
#include "imgui_impl_sdlgpu3_shaders.h"
Classes
struct ImGui_ImplSDLGPU3_FrameData
struct ImGui_ImplSDLGPU3_Data
Functions
static void ImGui_ImplSDLGPU3_DestroyFrameData ()
static ImGui_ImplSDLGPU3_Data * ImGui_ImplSDLGPU3_GetBackendData ()
static void ImGui_ImplSDLGPU3_SetupRenderState (ImDrawData *draw_data, ImGui_ImplSDLGPU3_RenderState *render_state, SDL_GPUGraphicsPipeline *pipeline, SDL_GPUCommandBuffer *command_buffer, SDL_GPURenderPass *render_pass, ImGui_ImplSDLGPU3_FrameData *fd, uint32_t fb_width, uint32_t fb_height)
static void CreateOrResizeBuffers (SDL_GPUBuffer **buffer, SDL_GPUTransferBuffer **transferbuffer, uint32_t *old_size, uint32_t new_size, SDL_GPUBufferUsageFlags usage)
void ImGui_ImplSDLGPU3_PrepareDrawData (ImDrawData *draw_data, SDL_GPUCommandBuffer *command_buffer)
void ImGui_ImplSDLGPU3_RenderDrawData (ImDrawData *draw_data, SDL_GPUCommandBuffer *command_buffer, SDL_GPURenderPass *render_pass, SDL_GPUGraphicsPipeline *pipeline)
static void ImGui_ImplSDLGPU3_DestroyTexture (ImTextureData *tex)
void ImGui_ImplSDLGPU3_UpdateTexture (ImTextureData *tex)
static void ImGui_ImplSDLGPU3_CreateShaders ()
static void ImGui_ImplSDLGPU3_CreateGraphicsPipeline ()
void ImGui_ImplSDLGPU3_CreateDeviceObjects ()
void ImGui_ImplSDLGPU3_DestroyDeviceObjects ()
bool ImGui_ImplSDLGPU3_Init (ImGui_ImplSDLGPU3_InitInfo *info)
void ImGui_ImplSDLGPU3_Shutdown ()
void ImGui_ImplSDLGPU3_NewFrame ()
Function Documentation
CreateOrResizeBuffers()
static void CreateOrResizeBuffers (SDL_GPUBuffer ** buffer, SDL_GPUTransferBuffer ** transferbuffer, uint32_t * old_size, uint32_t new_size, SDL_GPUBufferUsageFlags usage) static
Definition at line 128 of file imgui_impl_sdlgpu3.cpp.
References ImGui_ImplSDLGPU3_InitInfo::Device, IM_ASSERT, ImGui_ImplSDLGPU3_GetBackendData(), and ImGui_ImplSDLGPU3_Data::InitInfo.
Referenced by ImGui_ImplSDLGPU3_PrepareDrawData().
ImGui_ImplSDLGPU3_CreateDeviceObjects()
void ImGui_ImplSDLGPU3_CreateDeviceObjects ()
Definition at line 572 of file imgui_impl_sdlgpu3.cpp.
References ImGui_ImplSDLGPU3_InitInfo::Device, IM_ASSERT, ImGui_ImplSDLGPU3_CreateGraphicsPipeline(), ImGui_ImplSDLGPU3_DestroyDeviceObjects(), ImGui_ImplSDLGPU3_GetBackendData(), ImGui_ImplSDLGPU3_Data::InitInfo, and ImGui_ImplSDLGPU3_Data::TexSamplerLinear.
Referenced by ImGui_ImplSDLGPU3_NewFrame().
ImGui_ImplSDLGPU3_CreateGraphicsPipeline()
static void ImGui_ImplSDLGPU3_CreateGraphicsPipeline () static
Definition at line 489 of file imgui_impl_sdlgpu3.cpp.
References ImGui_ImplSDLGPU3_InitInfo::ColorTargetFormat, ImGui_ImplSDLGPU3_InitInfo::Device, ImGui_ImplSDLGPU3_Data::FragmentShader, IM_ASSERT, ImGui_ImplSDLGPU3_CreateShaders(), ImGui_ImplSDLGPU3_GetBackendData(), ImGui_ImplSDLGPU3_Data::InitInfo, ImGui_ImplSDLGPU3_InitInfo::MSAASamples, ImGui_ImplSDLGPU3_Data::Pipeline, and ImGui_ImplSDLGPU3_Data::VertexShader.
Referenced by ImGui_ImplSDLGPU3_CreateDeviceObjects().
ImGui_ImplSDLGPU3_CreateShaders()
static void ImGui_ImplSDLGPU3_CreateShaders () static
Definition at line 411 of file imgui_impl_sdlgpu3.cpp.
References ImGui_ImplSDLGPU3_InitInfo::Device, dxbc_fragment, dxbc_vertex, ImGui_ImplSDLGPU3_Data::FragmentShader, IM_ASSERT, ImGui_ImplSDLGPU3_GetBackendData(), ImGui_ImplSDLGPU3_Data::InitInfo, spirv_fragment, spirv_vertex, and ImGui_ImplSDLGPU3_Data::VertexShader.
Referenced by ImGui_ImplSDLGPU3_CreateGraphicsPipeline().
ImGui_ImplSDLGPU3_DestroyDeviceObjects()
void ImGui_ImplSDLGPU3_DestroyDeviceObjects ()
Definition at line 618 of file imgui_impl_sdlgpu3.cpp.
References ImGui_ImplSDLGPU3_InitInfo::Device, ImGui_ImplSDLGPU3_Data::FragmentShader, ImGui::GetPlatformIO(), ImGui_ImplSDLGPU3_DestroyFrameData(), ImGui_ImplSDLGPU3_DestroyTexture(), ImGui_ImplSDLGPU3_GetBackendData(), ImGui_ImplSDLGPU3_Data::InitInfo, ImGui_ImplSDLGPU3_Data::Pipeline, ImGui_ImplSDLGPU3_Data::TexSamplerLinear, ImGui_ImplSDLGPU3_Data::TexTransferBuffer, ImGuiPlatformIO::Textures, and ImGui_ImplSDLGPU3_Data::VertexShader.
Referenced by ImGui_ImplSDLGPU3_CreateDeviceObjects(), and ImGui_ImplSDLGPU3_Shutdown().
ImGui_ImplSDLGPU3_DestroyFrameData()
void ImGui_ImplSDLGPU3_DestroyFrameData () static
Definition at line 603 of file imgui_impl_sdlgpu3.cpp.
References ImGui_ImplSDLGPU3_InitInfo::Device, ImGui_ImplSDLGPU3_GetBackendData(), ImGui_ImplSDLGPU3_FrameData::IndexBuffer, ImGui_ImplSDLGPU3_FrameData::IndexBufferSize, ImGui_ImplSDLGPU3_FrameData::IndexTransferBuffer, ImGui_ImplSDLGPU3_Data::InitInfo, ImGui_ImplSDLGPU3_Data::MainWindowFrameData, ImGui_ImplSDLGPU3_FrameData::VertexBuffer, ImGui_ImplSDLGPU3_FrameData::VertexBufferSize, and ImGui_ImplSDLGPU3_FrameData::VertexTransferBuffer.
Referenced by ImGui_ImplSDLGPU3_DestroyDeviceObjects().
ImGui_ImplSDLGPU3_DestroyTexture()
static void ImGui_ImplSDLGPU3_DestroyTexture (ImTextureData * tex) static
Definition at line 308 of file imgui_impl_sdlgpu3.cpp.
References ImGui_ImplSDLGPU3_InitInfo::Device, ImTextureData::GetTexID(), ImGui_ImplSDLGPU3_GetBackendData(), ImTextureID_Invalid, ImTextureStatus_Destroyed, ImGui_ImplSDLGPU3_Data::InitInfo, ImTextureData::SetStatus(), and ImTextureData::SetTexID().
Referenced by ImGui_ImplSDLGPU3_DestroyDeviceObjects(), and ImGui_ImplSDLGPU3_UpdateTexture().
ImGui_ImplSDLGPU3_GetBackendData()
static ImGui_ImplSDLGPU3_Data * ImGui_ImplSDLGPU3_GetBackendData () static
Definition at line 82 of file imgui_impl_sdlgpu3.cpp.
References ImGuiIO::BackendRendererUserData, ImGui::GetCurrentContext(), and ImGui::GetIO().
Referenced by CreateOrResizeBuffers(), ImGui_ImplSDLGPU3_CreateDeviceObjects(), ImGui_ImplSDLGPU3_CreateGraphicsPipeline(), ImGui_ImplSDLGPU3_CreateShaders(), ImGui_ImplSDLGPU3_DestroyDeviceObjects(), ImGui_ImplSDLGPU3_DestroyFrameData(), ImGui_ImplSDLGPU3_DestroyTexture(), ImGui_ImplSDLGPU3_NewFrame(), ImGui_ImplSDLGPU3_PrepareDrawData(), ImGui_ImplSDLGPU3_RenderDrawData(), ImGui_ImplSDLGPU3_SetupRenderState(), ImGui_ImplSDLGPU3_Shutdown(), and ImGui_ImplSDLGPU3_UpdateTexture().
ImGui_ImplSDLGPU3_Init()
bool ImGui_ImplSDLGPU3_Init (ImGui_ImplSDLGPU3_InitInfo * info)
Definition at line 636 of file imgui_impl_sdlgpu3.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGui_ImplSDLGPU3_InitInfo::ColorTargetFormat, ImGui_ImplSDLGPU3_InitInfo::Device, ImGui::GetIO(), IM_ASSERT, IM_NEW, IMGUI_CHECKVERSION, ImGuiBackendFlags_RendererHasTextures, ImGuiBackendFlags_RendererHasVtxOffset, and ImGui_ImplSDLGPU3_Data::InitInfo.
Referenced by main().
ImGui_ImplSDLGPU3_NewFrame()
void ImGui_ImplSDLGPU3_NewFrame ()
Definition at line 673 of file imgui_impl_sdlgpu3.cpp.
References IM_ASSERT, ImGui_ImplSDLGPU3_CreateDeviceObjects(), ImGui_ImplSDLGPU3_GetBackendData(), and ImGui_ImplSDLGPU3_Data::TexSamplerLinear.
Referenced by main().
ImGui_ImplSDLGPU3_PrepareDrawData()
void ImGui_ImplSDLGPU3_PrepareDrawData (ImDrawData * draw_data, SDL_GPUCommandBuffer * command_buffer)
Definition at line 156 of file imgui_impl_sdlgpu3.cpp.
References ImDrawData::CmdLists, CreateOrResizeBuffers(), ImVector< T >::Data, ImGui_ImplSDLGPU3_InitInfo::Device, ImDrawData::DisplaySize, ImDrawData::FramebufferScale, ImDrawList::IdxBuffer, ImDrawIdx, ImGui_ImplSDLGPU3_GetBackendData(), ImGui_ImplSDLGPU3_UpdateTexture(), ImTextureStatus_OK, ImGui_ImplSDLGPU3_FrameData::IndexBuffer, ImGui_ImplSDLGPU3_FrameData::IndexBufferSize, ImGui_ImplSDLGPU3_FrameData::IndexTransferBuffer, ImGui_ImplSDLGPU3_Data::InitInfo, ImGui_ImplSDLGPU3_Data::MainWindowFrameData, ImVector< T >::Size, ImDrawData::Textures, ImDrawData::TotalIdxCount, ImDrawData::TotalVtxCount, ImGui_ImplSDLGPU3_FrameData::VertexBuffer, ImGui_ImplSDLGPU3_FrameData::VertexBufferSize, ImGui_ImplSDLGPU3_FrameData::VertexTransferBuffer, ImDrawList::VtxBuffer, ImVec2::x, and ImVec2::y.
Referenced by main().
ImGui_ImplSDLGPU3_RenderDrawData()
void ImGui_ImplSDLGPU3_RenderDrawData (ImDrawData * draw_data, SDL_GPUCommandBuffer * command_buffer, SDL_GPURenderPass * render_pass, SDL_GPUGraphicsPipeline * pipeline)
Definition at line 217 of file imgui_impl_sdlgpu3.cpp.
References ImDrawCmd::ClipRect, ImDrawList::CmdBuffer, ImDrawData::CmdLists, ImGui_ImplSDLGPU3_InitInfo::Device, ImGui_ImplSDLGPU3_RenderState::Device, ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImDrawCmd::ElemCount, ImDrawData::FramebufferScale, ImGui::GetPlatformIO(), ImDrawCmd::GetTexID(), ImDrawList::IdxBuffer, ImDrawCmd::IdxOffset, ImDrawCallback_ResetRenderState, ImGui_ImplSDLGPU3_GetBackendData(), ImGui_ImplSDLGPU3_SetupRenderState(), ImGui_ImplSDLGPU3_Data::InitInfo, ImGui_ImplSDLGPU3_Data::MainWindowFrameData, ImGui_ImplSDLGPU3_Data::Pipeline, ImGuiPlatformIO::Renderer_RenderState, ImGui_ImplSDLGPU3_RenderState::SamplerCurrent, ImGui_ImplSDLGPU3_RenderState::SamplerDefault, ImVector< T >::Size, ImGui_ImplSDLGPU3_Data::TexSamplerLinear, ImDrawCmd::UserCallback, ImDrawList::VtxBuffer, ImDrawCmd::VtxOffset, ImVec4::w, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by main().
ImGui_ImplSDLGPU3_SetupRenderState()
static void ImGui_ImplSDLGPU3_SetupRenderState (ImDrawData * draw_data, ImGui_ImplSDLGPU3_RenderState * render_state, SDL_GPUGraphicsPipeline * pipeline, SDL_GPUCommandBuffer * command_buffer, SDL_GPURenderPass * render_pass, ImGui_ImplSDLGPU3_FrameData * fd, uint32_t fb_width, uint32_t fb_height) static
Definition at line 87 of file imgui_impl_sdlgpu3.cpp.
References ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImGui_ImplSDLGPU3_GetBackendData(), ImGui_ImplSDLGPU3_FrameData::IndexBuffer, ImGui_ImplSDLGPU3_RenderState::SamplerCurrent, ImGui_ImplSDLGPU3_Data::TexSamplerLinear, ImDrawData::TotalVtxCount, ImGui_ImplSDLGPU3_FrameData::VertexBuffer, ImVec2::x, and ImVec2::y.
Referenced by ImGui_ImplSDLGPU3_RenderDrawData().
ImGui_ImplSDLGPU3_Shutdown()
void ImGui_ImplSDLGPU3_Shutdown ()
Definition at line 657 of file imgui_impl_sdlgpu3.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGuiPlatformIO::ClearRendererHandlers(), ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplSDLGPU3_DestroyDeviceObjects(), ImGui_ImplSDLGPU3_GetBackendData(), ImGuiBackendFlags_RendererHasTextures, and ImGuiBackendFlags_RendererHasVtxOffset.
Referenced by main().
ImGui_ImplSDLGPU3_UpdateTexture()
void ImGui_ImplSDLGPU3_UpdateTexture (ImTextureData * tex)
Definition at line 319 of file imgui_impl_sdlgpu3.cpp.
References ImTextureData::BackendUserData, ImTextureData::BytesPerPixel, ImGui_ImplSDLGPU3_InitInfo::Device, ImTextureData::Format, ImTextureData::GetPixelsAt(), ImTextureData::GetTexID(), ImTextureRect::h, ImTextureData::Height, IM_ASSERT, ImGui_ImplSDLGPU3_DestroyTexture(), ImGui_ImplSDLGPU3_GetBackendData(), ImTextureFormat_RGBA32, ImTextureID_Invalid, ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImGui_ImplSDLGPU3_Data::InitInfo, ImTextureData::SetStatus(), ImTextureData::SetTexID(), ImTextureData::Status, ImTextureData::TexID, ImGui_ImplSDLGPU3_Data::TexTransferBuffer, ImGui_ImplSDLGPU3_Data::TexTransferBufferSize, ImTextureData::UnusedFrames, ImTextureData::UpdateRect, ImTextureRect::w, ImTextureData::Width, ImTextureRect::x, and ImTextureRect::y.
Referenced by ImGui_ImplSDLGPU3_PrepareDrawData().