SignalProcessing: examples/imgui/backends/imgui_impl_allegro5.h File Reference
imgui_impl_allegro5.h File Reference
#include "imgui.h"
Functions
IMGUI_IMPL_API bool ImGui_ImplAllegro5_Init (ALLEGRO_DISPLAY *display)
IMGUI_IMPL_API void ImGui_ImplAllegro5_Shutdown ()
IMGUI_IMPL_API void ImGui_ImplAllegro5_NewFrame ()
IMGUI_IMPL_API void ImGui_ImplAllegro5_RenderDrawData (ImDrawData *draw_data)
IMGUI_IMPL_API bool ImGui_ImplAllegro5_ProcessEvent (ALLEGRO_EVENT *event)
IMGUI_IMPL_API void ImGui_ImplAllegro5_SetDisplay (ALLEGRO_DISPLAY *display)
IMGUI_IMPL_API bool ImGui_ImplAllegro5_CreateDeviceObjects ()
IMGUI_IMPL_API void ImGui_ImplAllegro5_InvalidateDeviceObjects ()
IMGUI_IMPL_API void ImGui_ImplAllegro5_UpdateTexture (ImTextureData *tex)
Function Documentation
ImGui_ImplAllegro5_CreateDeviceObjects()
IMGUI_IMPL_API bool ImGui_ImplAllegro5_CreateDeviceObjects ()
Definition at line 244 of file imgui_impl_allegro5.cpp.
References ImGui_ImplAllegro5_GetBackendData(), and ImGui_ImplAllegro5_Data::MouseCursorInvisible.
Referenced by ImGui_ImplAllegro5_NewFrame(), and main().
ImGui_ImplAllegro5_Init()
IMGUI_IMPL_API bool ImGui_ImplAllegro5_Init (ALLEGRO_DISPLAY * display)
Definition at line 472 of file imgui_impl_allegro5.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendPlatformName, ImGuiIO::BackendPlatformUserData, ImGuiIO::BackendRendererName, ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_NEW, IMGUI_CHECKVERSION, ImGui_ImplAllegro5_SetDisplay(), ImGuiBackendFlags_HasMouseCursors, ImGuiBackendFlags_RendererHasTextures, ImGui_ImplAllegro5_Data::LastCursor, ImGuiPlatformIO::Platform_GetClipboardTextFn, and ImGuiPlatformIO::Platform_SetClipboardTextFn.
Referenced by main().
ImGui_ImplAllegro5_InvalidateDeviceObjects()
IMGUI_IMPL_API void ImGui_ImplAllegro5_InvalidateDeviceObjects ()
Definition at line 320 of file imgui_impl_allegro5.cpp.
References ImGui::GetPlatformIO(), ImGui_ImplAllegro5_GetBackendData(), ImGui_ImplAllegro5_UpdateTexture(), ImTextureStatus_WantDestroy, ImGui_ImplAllegro5_Data::MouseCursorInvisible, and ImGuiPlatformIO::Textures.
Referenced by ImGui_ImplAllegro5_Shutdown(), and main().
ImGui_ImplAllegro5_NewFrame()
IMGUI_IMPL_API void ImGui_ImplAllegro5_NewFrame ()
Definition at line 667 of file imgui_impl_allegro5.cpp.
References ImGuiIO::AddKeyEvent(), ImGuiIO::DeltaTime, ImGui_ImplAllegro5_Data::Display, ImGuiIO::DisplaySize, ImGui::GetIO(), IM_ASSERT, ImGui_ImplAllegro5_CreateDeviceObjects(), ImGui_ImplAllegro5_GetBackendData(), ImGui_ImplAllegro5_UpdateMouseCursor(), ImGuiKey_PrintScreen, ImGui_ImplAllegro5_Data::MouseCursorInvisible, and ImGui_ImplAllegro5_Data::Time.
Referenced by main().
ImGui_ImplAllegro5_ProcessEvent()
IMGUI_IMPL_API bool ImGui_ImplAllegro5_ProcessEvent (ALLEGRO_EVENT * event)
Definition at line 562 of file imgui_impl_allegro5.cpp.
References ImGuiIO::AddFocusEvent(), ImGuiIO::AddInputCharacter(), ImGuiIO::AddKeyEvent(), ImGuiIO::AddMouseButtonEvent(), ImGuiIO::AddMousePosEvent(), ImGuiIO::AddMouseWheelEvent(), ImGui_ImplAllegro5_Data::Display, ImGui::GetIO(), IM_ASSERT, ImGui_ImplAllegro5_GetBackendData(), ImGui_ImplAllegro5_KeyCodeToImGuiKey(), ImGui_ImplAllegro5_UpdateKeyModifiers(), and ImGuiIO::SetKeyEventNativeData().
Referenced by main().
ImGui_ImplAllegro5_RenderDrawData()
IMGUI_IMPL_API void ImGui_ImplAllegro5_RenderDrawData (ImDrawData * draw_data)
Definition at line 140 of file imgui_impl_allegro5.cpp.
References ImGui_ImplAllegro5_Data::BufIndices, ImGui_ImplAllegro5_Data::BufVertices, ImDrawCmd::ClipRect, ImDrawList::CmdBuffer, ImDrawData::CmdLists, ImVector< T >::Data, ImDrawData::DisplayPos, ImDrawData::DisplaySize, DRAW_VERT_IMGUI_TO_ALLEGRO, ImDrawCmd::ElemCount, ImDrawCmd::GetTexID(), ImDrawList::IdxBuffer, ImDrawCmd::IdxOffset, ImDrawCallback_ResetRenderState, ImGui_ImplAllegro5_GetBackendData(), ImGui_ImplAllegro5_SetupRenderState(), ImGui_ImplAllegro5_UpdateTexture(), ImTextureStatus_OK, ImVector< T >::resize(), ImVector< T >::Size, ImDrawData::Textures, ImDrawCmd::UserCallback, ImGui_ImplAllegro5_Data::VertexDecl, ImDrawList::VtxBuffer, ImVec4::w, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by main().
ImGui_ImplAllegro5_SetDisplay()
IMGUI_IMPL_API void ImGui_ImplAllegro5_SetDisplay (ALLEGRO_DISPLAY * display)
Definition at line 519 of file imgui_impl_allegro5.cpp.
References ImGui_ImplAllegro5_Data::Display, ImGui_ImplAllegro5_GetBackendData(), and ImGui_ImplAllegro5_Data::VertexDecl.
Referenced by ImGui_ImplAllegro5_Init().
ImGui_ImplAllegro5_Shutdown()
IMGUI_IMPL_API void ImGui_ImplAllegro5_Shutdown ()
Definition at line 498 of file imgui_impl_allegro5.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendPlatformName, ImGuiIO::BackendPlatformUserData, ImGuiIO::BackendRendererName, ImGuiPlatformIO::ClearPlatformHandlers(), ImGuiPlatformIO::ClearRendererHandlers(), ImGui_ImplAllegro5_Data::ClipboardTextData, ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplAllegro5_GetBackendData(), ImGui_ImplAllegro5_InvalidateDeviceObjects(), ImGuiBackendFlags_HasMouseCursors, ImGuiBackendFlags_RendererHasTextures, and ImGui_ImplAllegro5_Data::VertexDecl.
Referenced by main().
ImGui_ImplAllegro5_UpdateTexture()
IMGUI_IMPL_API void ImGui_ImplAllegro5_UpdateTexture (ImTextureData * tex)
Definition at line 257 of file imgui_impl_allegro5.cpp.
References ImTextureData::BackendUserData, ImTextureData::BytesPerPixel, ImTextureData::Format, ImTextureData::GetPixels(), ImTextureData::GetPixelsAt(), ImTextureData::GetSizeInBytes(), ImTextureRect::h, ImTextureData::Height, IM_ASSERT, ImTextureFormat_RGBA32, ImTextureID_Invalid, ImTextureStatus_Destroyed, ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImTextureData::SetStatus(), ImTextureData::SetTexID(), ImTextureData::Status, ImTextureData::TexID, ImTextureData::UpdateRect, ImTextureRect::w, ImTextureData::Width, ImTextureRect::x, and ImTextureRect::y.
Referenced by ImGui_ImplAllegro5_InvalidateDeviceObjects(), and ImGui_ImplAllegro5_RenderDrawData().