SignalProcessing: examples/imgui/backends/imgui_impl_wgpu.h File Reference
imgui_impl_wgpu.h File Reference
#include "imgui.h"
#include <webgpu/webgpu.h>
Classes
struct ImGui_ImplWGPU_InitInfo
struct ImGui_ImplWGPU_RenderState
struct ImGui_ImplWGPU_CreateSurfaceInfo
Functions
IMGUI_IMPL_API bool ImGui_ImplWGPU_Init (ImGui_ImplWGPU_InitInfo *init_info)
IMGUI_IMPL_API void ImGui_ImplWGPU_Shutdown ()
IMGUI_IMPL_API void ImGui_ImplWGPU_NewFrame ()
IMGUI_IMPL_API void ImGui_ImplWGPU_RenderDrawData (ImDrawData *draw_data, WGPURenderPassEncoder pass_encoder)
IMGUI_IMPL_API bool ImGui_ImplWGPU_CreateDeviceObjects ()
IMGUI_IMPL_API void ImGui_ImplWGPU_InvalidateDeviceObjects ()
IMGUI_IMPL_API void ImGui_ImplWGPU_UpdateTexture (ImTextureData *tex)
bool ImGui_ImplWGPU_IsSurfaceStatusError (WGPUSurfaceGetCurrentTextureStatus status)
bool ImGui_ImplWGPU_IsSurfaceStatusSubOptimal (WGPUSurfaceGetCurrentTextureStatus status)
void ImGui_ImplWGPU_DebugPrintAdapterInfo (const WGPUAdapter &adapter)
const char * ImGui_ImplWGPU_GetBackendTypeName (WGPUBackendType type)
const char * ImGui_ImplWGPU_GetAdapterTypeName (WGPUAdapterType type)
WGPUSurface ImGui_ImplWGPU_CreateWGPUSurfaceHelper (ImGui_ImplWGPU_CreateSurfaceInfo *info)
Function Documentation
ImGui_ImplWGPU_CreateDeviceObjects()
IMGUI_IMPL_API bool ImGui_ImplWGPU_CreateDeviceObjects ()
Definition at line 655 of file imgui_impl_wgpu.cpp.
References __shader_frag_wgsl, __shader_vert_wgsl, RenderResources::CommonBindGroup, ImGui_ImplWGPU_Data::depthStencilFormat, RenderResources::ImageBindGroupLayout, ImGui_ImplWGPU_CreateShaderModule(), ImGui_ImplWGPU_CreateUniformBuffer(), ImGui_ImplWGPU_GetBackendData(), ImGui_ImplWGPU_InvalidateDeviceObjects(), ImGui_ImplWGPU_Data::initInfo, MEMALIGN, ImGui_ImplWGPU_InitInfo::PipelineMultisampleState, ImGui_ImplWGPU_Data::pipelineState, ImGui_ImplWGPU_Data::renderResources, ImGui_ImplWGPU_Data::renderTargetFormat, SafeRelease(), RenderResources::Sampler, RenderResources::Uniforms, and ImGui_ImplWGPU_Data::wgpuDevice.
Referenced by ImGui_ImplWGPU_NewFrame().
ImGui_ImplWGPU_CreateWGPUSurfaceHelper()
WGPUSurface ImGui_ImplWGPU_CreateWGPUSurfaceHelper (ImGui_ImplWGPU_CreateSurfaceInfo * info)
Definition at line 1027 of file imgui_impl_wgpu.cpp.
References IM_ASSERT, ImGui_ImplWGPU_CreateSurfaceInfo::Instance, ImGui_ImplWGPU_CreateSurfaceInfo::RawDisplay, ImGui_ImplWGPU_CreateSurfaceInfo::RawInstance, ImGui_ImplWGPU_CreateSurfaceInfo::RawSurface, ImGui_ImplWGPU_CreateSurfaceInfo::RawWindow, and ImGui_ImplWGPU_CreateSurfaceInfo::System.
Referenced by CreateWGPUSurface(), CreateWGPUSurface(), and CreateWGPUSurface().
ImGui_ImplWGPU_DebugPrintAdapterInfo()
void ImGui_ImplWGPU_DebugPrintAdapterInfo (const WGPUAdapter & adapter)
Definition at line 1005 of file imgui_impl_wgpu.cpp.
References ImGui_ImplWGPU_GetAdapterTypeName(), and ImGui_ImplWGPU_GetBackendTypeName().
Referenced by InitWGPU(), and InitWGPU().
ImGui_ImplWGPU_GetAdapterTypeName()
const char * ImGui_ImplWGPU_GetAdapterTypeName (WGPUAdapterType type)
Definition at line 994 of file imgui_impl_wgpu.cpp.
Referenced by ImGui_ImplWGPU_DebugPrintAdapterInfo().
ImGui_ImplWGPU_GetBackendTypeName()
const char * ImGui_ImplWGPU_GetBackendTypeName (WGPUBackendType type)
Definition at line 979 of file imgui_impl_wgpu.cpp.
Referenced by ImGui_ImplWGPU_DebugPrintAdapterInfo().
ImGui_ImplWGPU_Init()
IMGUI_IMPL_API bool ImGui_ImplWGPU_Init (ImGui_ImplWGPU_InitInfo * init_info)
Definition at line 832 of file imgui_impl_wgpu.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, RenderResources::CommonBindGroup, ImGuiStorage::Data, ImGui_ImplWGPU_Data::defaultQueue, ImGui_ImplWGPU_Data::depthStencilFormat, ImGui_ImplWGPU_InitInfo::DepthStencilFormat, ImGui_ImplWGPU_InitInfo::Device, ImGui_ImplWGPU_Data::frameIndex, ImGui::GetIO(), IM_ASSERT, IM_NEW, RenderResources::ImageBindGroupLayout, RenderResources::ImageBindGroups, IMGUI_CHECKVERSION, ImGuiBackendFlags_RendererHasTextures, ImGuiBackendFlags_RendererHasVtxOffset, FrameResources::IndexBuffer, FrameResources::IndexBufferHost, FrameResources::IndexBufferSize, ImGui_ImplWGPU_Data::initInfo, ImGui_ImplWGPU_Data::numFramesInFlight, ImGui_ImplWGPU_InitInfo::NumFramesInFlight, ImGui_ImplWGPU_Data::pFrameResources, ImGui_ImplWGPU_Data::renderResources, ImGui_ImplWGPU_Data::renderTargetFormat, ImGui_ImplWGPU_InitInfo::RenderTargetFormat, ImVector< T >::reserve(), RenderResources::Sampler, RenderResources::Uniforms, FrameResources::VertexBuffer, FrameResources::VertexBufferHost, FrameResources::VertexBufferSize, and ImGui_ImplWGPU_Data::wgpuDevice.
Referenced by main().
ImGui_ImplWGPU_InvalidateDeviceObjects()
IMGUI_IMPL_API void ImGui_ImplWGPU_InvalidateDeviceObjects ()
Definition at line 814 of file imgui_impl_wgpu.cpp.
References ImGui::GetPlatformIO(), ImGui_ImplWGPU_DestroyTexture(), ImGui_ImplWGPU_GetBackendData(), ImGui_ImplWGPU_Data::numFramesInFlight, ImGui_ImplWGPU_Data::pFrameResources, ImGui_ImplWGPU_Data::pipelineState, ImGui_ImplWGPU_Data::renderResources, SafeRelease(), ImGuiPlatformIO::Textures, and ImGui_ImplWGPU_Data::wgpuDevice.
Referenced by ImGui_ImplWGPU_CreateDeviceObjects(), and ImGui_ImplWGPU_Shutdown().
ImGui_ImplWGPU_IsSurfaceStatusError()
bool ImGui_ImplWGPU_IsSurfaceStatusError (WGPUSurfaceGetCurrentTextureStatus status)
Definition at line 922 of file imgui_impl_wgpu.cpp.
Referenced by main().
ImGui_ImplWGPU_IsSurfaceStatusSubOptimal()
bool ImGui_ImplWGPU_IsSurfaceStatusSubOptimal (WGPUSurfaceGetCurrentTextureStatus status)
Definition at line 931 of file imgui_impl_wgpu.cpp.
Referenced by main().
ImGui_ImplWGPU_NewFrame()
IMGUI_IMPL_API void ImGui_ImplWGPU_NewFrame ()
Definition at line 909 of file imgui_impl_wgpu.cpp.
References IM_ASSERT, ImGui_ImplWGPU_CreateDeviceObjects(), ImGui_ImplWGPU_GetBackendData(), and ImGui_ImplWGPU_Data::pipelineState.
Referenced by main().
ImGui_ImplWGPU_RenderDrawData()
IMGUI_IMPL_API void ImGui_ImplWGPU_RenderDrawData (ImDrawData * draw_data, WGPURenderPassEncoder pass_encoder)
Definition at line 368 of file imgui_impl_wgpu.cpp.
References ImDrawCmd::ClipRect, ImDrawList::CmdBuffer, ImDrawData::CmdLists, ImVector< T >::Data, ImGuiStorage::Data, ImGui_ImplWGPU_Data::defaultQueue, ImGui_ImplWGPU_RenderState::Device, ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImDrawCmd::ElemCount, ImDrawData::FramebufferScale, ImGui_ImplWGPU_Data::frameIndex, ImGui::GetPlatformIO(), ImDrawCmd::GetTexID(), ImGuiStorage::GetVoidPtr(), ImDrawList::IdxBuffer, ImDrawCmd::IdxOffset, RenderResources::ImageBindGroupLayout, RenderResources::ImageBindGroups, ImDrawCallback_ResetRenderState, ImGui_ImplWGPU_CreateImageBindGroup(), ImGui_ImplWGPU_GetBackendData(), ImGui_ImplWGPU_SetupRenderState(), ImGui_ImplWGPU_UpdateTexture(), ImHashData(), ImTextureStatus_OK, FrameResources::IndexBuffer, FrameResources::IndexBufferHost, FrameResources::IndexBufferSize, MEMALIGN, ImGui_ImplWGPU_Data::numFramesInFlight, ImGui_ImplWGPU_Data::pFrameResources, ImGuiPlatformIO::Renderer_RenderState, ImGui_ImplWGPU_RenderState::RenderPassEncoder, ImGui_ImplWGPU_Data::renderResources, ImVector< T >::resize(), SafeRelease(), ImGuiStorage::SetVoidPtr(), ImVector< T >::Size, ImDrawData::Textures, ImDrawData::TotalIdxCount, ImDrawData::TotalVtxCount, ImDrawCmd::UserCallback, FrameResources::VertexBuffer, FrameResources::VertexBufferHost, FrameResources::VertexBufferSize, ImDrawList::VtxBuffer, ImDrawCmd::VtxOffset, ImVec4::w, ImGui_ImplWGPU_Data::wgpuDevice, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by main().
ImGui_ImplWGPU_Shutdown()
IMGUI_IMPL_API void ImGui_ImplWGPU_Shutdown ()
Definition at line 887 of file imgui_impl_wgpu.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGuiPlatformIO::ClearRendererHandlers(), ImGui_ImplWGPU_Data::defaultQueue, ImGui_ImplWGPU_Data::frameIndex, ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplWGPU_GetBackendData(), ImGui_ImplWGPU_InvalidateDeviceObjects(), ImGuiBackendFlags_RendererHasTextures, ImGuiBackendFlags_RendererHasVtxOffset, ImGui_ImplWGPU_Data::numFramesInFlight, ImGui_ImplWGPU_Data::pFrameResources, and ImGui_ImplWGPU_Data::wgpuDevice.
Referenced by main().
ImGui_ImplWGPU_UpdateTexture()
IMGUI_IMPL_API void ImGui_ImplWGPU_UpdateTexture (ImTextureData * tex)
Definition at line 554 of file imgui_impl_wgpu.cpp.
References ImTextureData::BackendUserData, ImTextureData::BytesPerPixel, ImGui_ImplWGPU_Data::defaultQueue, ImTextureData::Format, ImTextureData::GetPixelsAt(), ImTextureRect::h, ImTextureData::Height, IM_ASSERT, IM_NEW, ImGui_ImplWGPU_DestroyTexture(), ImGui_ImplWGPU_GetBackendData(), ImTextureFormat_RGBA32, ImTextureID_Invalid, ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImTextureData::SetStatus(), ImTextureData::SetTexID(), ImTextureData::Status, ImTextureData::TexID, ImGui_ImplWGPU_Texture::Texture, ImGui_ImplWGPU_Texture::TextureView, ImTextureData::UnusedFrames, ImTextureData::UpdateRect, ImTextureRect::w, ImGui_ImplWGPU_Data::wgpuDevice, ImTextureData::Width, ImTextureRect::x, and ImTextureRect::y.
Referenced by ImGui_ImplWGPU_RenderDrawData().