SignalProcessing: examples/imgui/backends/imgui_impl_sdl2.cpp File Reference
imgui_impl_sdl2.cpp File Reference
#include "imgui.h"
#include "imgui_impl_sdl2.h"
#include <SDL.h>
#include <SDL_syswm.h>
#include <stdio.h>
Classes
struct ImGui_ImplSDL2_Data
Macros
#define SDL_HAS_CAPTURE_AND_GLOBAL_MOUSE 0
#define SDL_HAS_PER_MONITOR_DPI SDL_VERSION_ATLEAST(2,0,4)
#define SDL_HAS_VULKAN SDL_VERSION_ATLEAST(2,0,6)
#define SDL_HAS_OPEN_URL SDL_VERSION_ATLEAST(2,0,14)
Functions
static ImGui_ImplSDL2_Data * ImGui_ImplSDL2_GetBackendData ()
static const char * ImGui_ImplSDL2_GetClipboardText (ImGuiContext *)
static void ImGui_ImplSDL2_SetClipboardText (ImGuiContext *, const char *text)
static void ImGui_ImplSDL2_PlatformSetImeData (ImGuiContext *, ImGuiViewport *, ImGuiPlatformImeData *data)
ImGuiKey ImGui_ImplSDL2_KeyEventToImGuiKey (SDL_Keycode keycode, SDL_Scancode scancode)
static void ImGui_ImplSDL2_UpdateKeyModifiers (SDL_Keymod sdl_key_mods)
static ImGuiViewport * ImGui_ImplSDL2_GetViewportForWindowID (Uint32 window_id)
bool ImGui_ImplSDL2_ProcessEvent (const SDL_Event *event)
static bool ImGui_ImplSDL2_Init (SDL_Window *window, SDL_Renderer *renderer, void *sdl_gl_context)
bool ImGui_ImplSDL2_InitForOpenGL (SDL_Window *window, void *sdl_gl_context)
bool ImGui_ImplSDL2_InitForVulkan (SDL_Window *window)
bool ImGui_ImplSDL2_InitForD3D (SDL_Window *window)
bool ImGui_ImplSDL2_InitForMetal (SDL_Window *window)
bool ImGui_ImplSDL2_InitForSDLRenderer (SDL_Window *window, SDL_Renderer *renderer)
bool ImGui_ImplSDL2_InitForOther (SDL_Window *window)
static void ImGui_ImplSDL2_CloseGamepads ()
void ImGui_ImplSDL2_Shutdown ()
static void ImGui_ImplSDL2_UpdateMouseData ()
static void ImGui_ImplSDL2_UpdateMouseCursor ()
float ImGui_ImplSDL2_GetContentScaleForWindow (SDL_Window *window)
float ImGui_ImplSDL2_GetContentScaleForDisplay (int display_index)
void ImGui_ImplSDL2_SetGamepadMode (ImGui_ImplSDL2_GamepadMode mode, struct _SDL_GameController **manual_gamepads_array, int manual_gamepads_count)
static void ImGui_ImplSDL2_UpdateGamepadButton (ImGui_ImplSDL2_Data *bd, ImGuiIO &io, ImGuiKey key, SDL_GameControllerButton button_no)
static float Saturate (float v)
static void ImGui_ImplSDL2_UpdateGamepadAnalog (ImGui_ImplSDL2_Data *bd, ImGuiIO &io, ImGuiKey key, SDL_GameControllerAxis axis_no, float v0, float v1)
static void ImGui_ImplSDL2_UpdateGamepads ()
static void ImGui_ImplSDL2_GetWindowSizeAndFramebufferScale (SDL_Window *window, SDL_Renderer *renderer, ImVec2 *out_size, ImVec2 *out_framebuffer_scale)
void ImGui_ImplSDL2_NewFrame ()
Macro Definition Documentation
SDL_HAS_CAPTURE_AND_GLOBAL_MOUSE
#define SDL_HAS_CAPTURE_AND_GLOBAL_MOUSE 0
Definition at line 130 of file imgui_impl_sdl2.cpp.
SDL_HAS_OPEN_URL
#define SDL_HAS_OPEN_URL SDL_VERSION_ATLEAST(2,0,14)
Definition at line 134 of file imgui_impl_sdl2.cpp.
SDL_HAS_PER_MONITOR_DPI
#define SDL_HAS_PER_MONITOR_DPI SDL_VERSION_ATLEAST(2,0,4)
Definition at line 132 of file imgui_impl_sdl2.cpp.
SDL_HAS_VULKAN
#define SDL_HAS_VULKAN SDL_VERSION_ATLEAST(2,0,6)
Definition at line 133 of file imgui_impl_sdl2.cpp.
Function Documentation
ImGui_ImplSDL2_CloseGamepads()
static void ImGui_ImplSDL2_CloseGamepads () static
Definition at line 747 of file imgui_impl_sdl2.cpp.
References ImGui_ImplSDL2_Data::GamepadMode, ImGui_ImplSDL2_Data::Gamepads, ImGui_ImplSDL2_GamepadMode_Manual, ImGui_ImplSDL2_GetBackendData(), and ImVector< T >::resize().
Referenced by ImGui_ImplSDL2_SetGamepadMode(), ImGui_ImplSDL2_Shutdown(), and ImGui_ImplSDL2_UpdateGamepads().
ImGui_ImplSDL2_GetBackendData()
static ImGui_ImplSDL2_Data * ImGui_ImplSDL2_GetBackendData () static
Definition at line 170 of file imgui_impl_sdl2.cpp.
References ImGuiIO::BackendPlatformUserData, ImGui::GetCurrentContext(), and ImGui::GetIO().
Referenced by ImGui_ImplSDL2_CloseGamepads(), ImGui_ImplSDL2_GetClipboardText(), ImGui_ImplSDL2_GetViewportForWindowID(), ImGui_ImplSDL2_NewFrame(), ImGui_ImplSDL2_ProcessEvent(), ImGui_ImplSDL2_SetGamepadMode(), ImGui_ImplSDL2_Shutdown(), ImGui_ImplSDL2_UpdateGamepads(), ImGui_ImplSDL2_UpdateMouseCursor(), and ImGui_ImplSDL2_UpdateMouseData().
ImGui_ImplSDL2_GetClipboardText()
static const char * ImGui_ImplSDL2_GetClipboardText (ImGuiContext *) static
Definition at line 176 of file imgui_impl_sdl2.cpp.
References ImGui_ImplSDL2_Data::ClipboardTextData, and ImGui_ImplSDL2_GetBackendData().
Referenced by ImGui_ImplSDL2_Init().
ImGui_ImplSDL2_GetContentScaleForDisplay()
float ImGui_ImplSDL2_GetContentScaleForDisplay (int display_index)
Definition at line 731 of file imgui_impl_sdl2.cpp.
References IM_UNUSED.
Referenced by ImGui_ImplSDL2_GetContentScaleForWindow(), and main().
ImGui_ImplSDL2_GetContentScaleForWindow()
float ImGui_ImplSDL2_GetContentScaleForWindow (SDL_Window * window)
Definition at line 726 of file imgui_impl_sdl2.cpp.
References ImGui_ImplSDL2_GetContentScaleForDisplay().
ImGui_ImplSDL2_GetViewportForWindowID()
static ImGuiViewport * ImGui_ImplSDL2_GetViewportForWindowID (Uint32 window_id) static
Definition at line 361 of file imgui_impl_sdl2.cpp.
References ImGui::GetMainViewport(), ImGui_ImplSDL2_GetBackendData(), and ImGui_ImplSDL2_Data::WindowID.
Referenced by ImGui_ImplSDL2_ProcessEvent().
ImGui_ImplSDL2_GetWindowSizeAndFramebufferScale()
static void ImGui_ImplSDL2_GetWindowSizeAndFramebufferScale (SDL_Window * window, SDL_Renderer * renderer, ImVec2 * out_size, ImVec2 * out_framebuffer_scale) static
Definition at line 849 of file imgui_impl_sdl2.cpp.
Referenced by ImGui_ImplSDL2_NewFrame().
ImGui_ImplSDL2_Init()
static bool ImGui_ImplSDL2_Init (SDL_Window * window, SDL_Renderer * renderer, void * sdl_gl_context) static
Definition at line 485 of file imgui_impl_sdl2.cpp.
References ImGuiIO::BackendFlags, ImGui_ImplSDL2_Data::BackendPlatformName, ImGuiIO::BackendPlatformName, ImGuiIO::BackendPlatformUserData, ImGui_ImplSDL2_Data::GamepadMode, ImGui::GetIO(), ImGui::GetMainViewport(), ImGui::GetPlatformIO(), IM_ASSERT, IM_NEW, IMGUI_CHECKVERSION, ImGui_ImplSDL2_GamepadMode_AutoFirst, ImGui_ImplSDL2_GetClipboardText(), ImGui_ImplSDL2_PlatformSetImeData(), ImGui_ImplSDL2_SetClipboardText(), ImGuiBackendFlags_HasMouseCursors, ImGuiBackendFlags_HasSetMousePos, ImGuiMouseCursor_Arrow, ImGuiMouseCursor_Hand, ImGuiMouseCursor_NotAllowed, ImGuiMouseCursor_Progress, ImGuiMouseCursor_ResizeAll, ImGuiMouseCursor_ResizeEW, ImGuiMouseCursor_ResizeNESW, ImGuiMouseCursor_ResizeNS, ImGuiMouseCursor_ResizeNWSE, ImGuiMouseCursor_TextInput, ImGuiMouseCursor_Wait, ImGui_ImplSDL2_Data::MouseCanUseCapture, ImGui_ImplSDL2_Data::MouseCanUseGlobalState, ImGui_ImplSDL2_Data::MouseCursors, ImGuiPlatformIO::Platform_ClipboardUserData, ImGuiPlatformIO::Platform_GetClipboardTextFn, ImGuiPlatformIO::Platform_OpenInShellFn, ImGuiPlatformIO::Platform_SetClipboardTextFn, ImGuiPlatformIO::Platform_SetImeDataFn, ImGuiViewport::PlatformHandle, ImGuiViewport::PlatformHandleRaw, ImGui_ImplSDL2_Data::Renderer, ImGui_ImplSDL2_Data::WantUpdateGamepadsList, ImGui_ImplSDL2_Data::Window, and ImGui_ImplSDL2_Data::WindowID.
Referenced by ImGui_ImplSDL2_InitForD3D(), ImGui_ImplSDL2_InitForMetal(), ImGui_ImplSDL2_InitForOpenGL(), ImGui_ImplSDL2_InitForOther(), ImGui_ImplSDL2_InitForSDLRenderer(), and ImGui_ImplSDL2_InitForVulkan().
ImGui_ImplSDL2_InitForD3D()
bool ImGui_ImplSDL2_InitForD3D (SDL_Window * window)
Definition at line 604 of file imgui_impl_sdl2.cpp.
References IM_ASSERT, and ImGui_ImplSDL2_Init().
Referenced by main().
ImGui_ImplSDL2_InitForMetal()
bool ImGui_ImplSDL2_InitForMetal (SDL_Window * window)
Definition at line 612 of file imgui_impl_sdl2.cpp.
References ImGui_ImplSDL2_Init().
ImGui_ImplSDL2_InitForOpenGL()
bool ImGui_ImplSDL2_InitForOpenGL (SDL_Window * window, void * sdl_gl_context)
Definition at line 591 of file imgui_impl_sdl2.cpp.
References ImGui_ImplSDL2_Init().
Referenced by main().
ImGui_ImplSDL2_InitForOther()
bool ImGui_ImplSDL2_InitForOther (SDL_Window * window)
Definition at line 622 of file imgui_impl_sdl2.cpp.
References ImGui_ImplSDL2_Init().
Referenced by main().
ImGui_ImplSDL2_InitForSDLRenderer()
bool ImGui_ImplSDL2_InitForSDLRenderer (SDL_Window * window, SDL_Renderer * renderer)
Definition at line 617 of file imgui_impl_sdl2.cpp.
References ImGui_ImplSDL2_Init().
Referenced by main().
ImGui_ImplSDL2_InitForVulkan()
bool ImGui_ImplSDL2_InitForVulkan (SDL_Window * window)
Definition at line 596 of file imgui_impl_sdl2.cpp.
References IM_ASSERT, and ImGui_ImplSDL2_Init().
Referenced by main().
ImGui_ImplSDL2_KeyEventToImGuiKey()
ImGuiKey ImGui_ImplSDL2_KeyEventToImGuiKey (SDL_Keycode keycode, SDL_Scancode scancode)
Definition at line 206 of file imgui_impl_sdl2.cpp.
References ImGuiKey_0, ImGuiKey_1, ImGuiKey_2, ImGuiKey_3, ImGuiKey_4, ImGuiKey_5, ImGuiKey_6, ImGuiKey_7, ImGuiKey_8, ImGuiKey_9, ImGuiKey_A, ImGuiKey_Apostrophe, ImGuiKey_AppBack, ImGuiKey_AppForward, ImGuiKey_B, ImGuiKey_Backslash, ImGuiKey_Backspace, ImGuiKey_C, ImGuiKey_CapsLock, ImGuiKey_Comma, ImGuiKey_D, ImGuiKey_Delete, ImGuiKey_DownArrow, ImGuiKey_E, ImGuiKey_End, ImGuiKey_Enter, ImGuiKey_Equal, ImGuiKey_Escape, ImGuiKey_F, ImGuiKey_F1, ImGuiKey_F10, ImGuiKey_F11, ImGuiKey_F12, ImGuiKey_F13, ImGuiKey_F14, ImGuiKey_F15, ImGuiKey_F16, ImGuiKey_F17, ImGuiKey_F18, ImGuiKey_F19, ImGuiKey_F2, ImGuiKey_F20, ImGuiKey_F21, ImGuiKey_F22, ImGuiKey_F23, ImGuiKey_F24, ImGuiKey_F3, ImGuiKey_F4, ImGuiKey_F5, ImGuiKey_F6, ImGuiKey_F7, ImGuiKey_F8, ImGuiKey_F9, ImGuiKey_G, ImGuiKey_GraveAccent, ImGuiKey_H, ImGuiKey_Home, ImGuiKey_I, ImGuiKey_Insert, ImGuiKey_J, ImGuiKey_K, ImGuiKey_Keypad0, ImGuiKey_Keypad1, ImGuiKey_Keypad2, ImGuiKey_Keypad3, ImGuiKey_Keypad4, ImGuiKey_Keypad5, ImGuiKey_Keypad6, ImGuiKey_Keypad7, ImGuiKey_Keypad8, ImGuiKey_Keypad9, ImGuiKey_KeypadAdd, ImGuiKey_KeypadDecimal, ImGuiKey_KeypadDivide, ImGuiKey_KeypadEnter, ImGuiKey_KeypadEqual, ImGuiKey_KeypadMultiply, ImGuiKey_KeypadSubtract, ImGuiKey_L, ImGuiKey_LeftAlt, ImGuiKey_LeftArrow, ImGuiKey_LeftBracket, ImGuiKey_LeftCtrl, ImGuiKey_LeftShift, ImGuiKey_LeftSuper, ImGuiKey_M, ImGuiKey_Menu, ImGuiKey_Minus, ImGuiKey_N, ImGuiKey_None, ImGuiKey_NumLock, ImGuiKey_O, ImGuiKey_Oem102, ImGuiKey_P, ImGuiKey_PageDown, ImGuiKey_PageUp, ImGuiKey_Pause, ImGuiKey_Period, ImGuiKey_PrintScreen, ImGuiKey_Q, ImGuiKey_R, ImGuiKey_RightAlt, ImGuiKey_RightArrow, ImGuiKey_RightBracket, ImGuiKey_RightCtrl, ImGuiKey_RightShift, ImGuiKey_RightSuper, ImGuiKey_S, ImGuiKey_ScrollLock, ImGuiKey_Semicolon, ImGuiKey_Slash, ImGuiKey_Space, ImGuiKey_T, ImGuiKey_Tab, ImGuiKey_U, ImGuiKey_UpArrow, ImGuiKey_V, ImGuiKey_W, ImGuiKey_X, ImGuiKey_Y, and ImGuiKey_Z.
Referenced by ImGui_ImplSDL2_ProcessEvent().
ImGui_ImplSDL2_NewFrame()
void ImGui_ImplSDL2_NewFrame ()
Definition at line 870 of file imgui_impl_sdl2.cpp.
References ImGuiIO::AddMousePosEvent(), ImGuiIO::DeltaTime, ImGuiIO::DisplayFramebufferScale, ImGuiIO::DisplaySize, frequency, ImGui::GetFrameCount(), ImGui::GetIO(), IM_ASSERT, ImGui_ImplSDL2_GetBackendData(), ImGui_ImplSDL2_GetWindowSizeAndFramebufferScale(), ImGui_ImplSDL2_UpdateGamepads(), ImGui_ImplSDL2_UpdateMouseCursor(), ImGui_ImplSDL2_UpdateMouseData(), ImGui_ImplSDL2_Data::MouseButtonsDown, ImGui_ImplSDL2_Data::MouseLastLeaveFrame, ImGui_ImplSDL2_Data::MouseWindowID, ImGui_ImplSDL2_Data::Renderer, ImGui_ImplSDL2_Data::Time, and ImGui_ImplSDL2_Data::Window.
Referenced by main().
ImGui_ImplSDL2_PlatformSetImeData()
static void ImGui_ImplSDL2_PlatformSetImeData (ImGuiContext * , ImGuiViewport * , ImGuiPlatformImeData * data) static
Definition at line 191 of file imgui_impl_sdl2.cpp.
Referenced by ImGui_ImplSDL2_Init().
ImGui_ImplSDL2_ProcessEvent()
bool ImGui_ImplSDL2_ProcessEvent (const SDL_Event * event)
Definition at line 372 of file imgui_impl_sdl2.cpp.
References ImGuiIO::AddFocusEvent(), ImGuiIO::AddInputCharactersUTF8(), ImGuiIO::AddKeyEvent(), ImGuiIO::AddMouseButtonEvent(), ImGuiIO::AddMousePosEvent(), ImGuiIO::AddMouseSourceEvent(), ImGuiIO::AddMouseWheelEvent(), ImGui::GetFrameCount(), ImGui::GetIO(), IM_ASSERT, ImGui_ImplSDL2_GetBackendData(), ImGui_ImplSDL2_GetViewportForWindowID(), ImGui_ImplSDL2_KeyEventToImGuiKey(), ImGui_ImplSDL2_UpdateKeyModifiers(), ImGuiMouseSource_Mouse, ImGuiMouseSource_TouchScreen, ImGui_ImplSDL2_Data::MouseButtonsDown, ImGui_ImplSDL2_Data::MouseLastLeaveFrame, ImGui_ImplSDL2_Data::MouseWindowID, ImGuiIO::SetKeyEventNativeData(), ImGui_ImplSDL2_Data::WantUpdateGamepadsList, ImVec2::x, and ImVec2::y.
Referenced by main().
ImGui_ImplSDL2_SetClipboardText()
static void ImGui_ImplSDL2_SetClipboardText (ImGuiContext * , const char * text) static
Definition at line 185 of file imgui_impl_sdl2.cpp.
Referenced by ImGui_ImplSDL2_Init().
ImGui_ImplSDL2_SetGamepadMode()
void ImGui_ImplSDL2_SetGamepadMode (ImGui_ImplSDL2_GamepadMode mode, struct _SDL_GameController ** manual_gamepads_array, int manual_gamepads_count)
Definition at line 756 of file imgui_impl_sdl2.cpp.
References ImGui_ImplSDL2_Data::GamepadMode, ImGui_ImplSDL2_Data::Gamepads, IM_ASSERT, ImGui_ImplSDL2_CloseGamepads(), ImGui_ImplSDL2_GamepadMode_Manual, ImGui_ImplSDL2_GetBackendData(), ImVector< T >::push_back(), and ImGui_ImplSDL2_Data::WantUpdateGamepadsList.
ImGui_ImplSDL2_Shutdown()
void ImGui_ImplSDL2_Shutdown ()
Definition at line 629 of file imgui_impl_sdl2.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendPlatformName, ImGuiIO::BackendPlatformUserData, ImGuiPlatformIO::ClearPlatformHandlers(), ImGui_ImplSDL2_Data::ClipboardTextData, ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplSDL2_CloseGamepads(), ImGui_ImplSDL2_GetBackendData(), ImGuiBackendFlags_HasGamepad, ImGuiBackendFlags_HasMouseCursors, ImGuiBackendFlags_HasSetMousePos, ImGuiMouseCursor_COUNT, and ImGui_ImplSDL2_Data::MouseCursors.
Referenced by main().
ImGui_ImplSDL2_UpdateGamepadAnalog()
static void ImGui_ImplSDL2_UpdateGamepadAnalog (ImGui_ImplSDL2_Data * bd, ImGuiIO & io, ImGuiKey key, SDL_GameControllerAxis axis_no, float v0, float v1) static
Definition at line 783 of file imgui_impl_sdl2.cpp.
References ImGuiIO::AddKeyAnalogEvent(), ImGui_ImplSDL2_Data::Gamepads, and Saturate().
Referenced by ImGui_ImplSDL2_UpdateGamepads().
ImGui_ImplSDL2_UpdateGamepadButton()
static void ImGui_ImplSDL2_UpdateGamepadButton (ImGui_ImplSDL2_Data * bd, ImGuiIO & io, ImGuiKey key, SDL_GameControllerButton button_no) static
Definition at line 774 of file imgui_impl_sdl2.cpp.
References ImGuiIO::AddKeyEvent(), and ImGui_ImplSDL2_Data::Gamepads.
Referenced by ImGui_ImplSDL2_UpdateGamepads().
ImGui_ImplSDL2_UpdateGamepads()
static void ImGui_ImplSDL2_UpdateGamepads () static
Definition at line 795 of file imgui_impl_sdl2.cpp.
References ImGuiIO::BackendFlags, ImGui_ImplSDL2_Data::GamepadMode, ImGui_ImplSDL2_Data::Gamepads, ImGui::GetIO(), ImGui_ImplSDL2_CloseGamepads(), ImGui_ImplSDL2_GamepadMode_AutoFirst, ImGui_ImplSDL2_GamepadMode_Manual, ImGui_ImplSDL2_GetBackendData(), ImGui_ImplSDL2_UpdateGamepadAnalog(), ImGui_ImplSDL2_UpdateGamepadButton(), ImGuiBackendFlags_HasGamepad, ImGuiKey_GamepadBack, ImGuiKey_GamepadDpadDown, ImGuiKey_GamepadDpadLeft, ImGuiKey_GamepadDpadRight, ImGuiKey_GamepadDpadUp, ImGuiKey_GamepadFaceDown, ImGuiKey_GamepadFaceLeft, ImGuiKey_GamepadFaceRight, ImGuiKey_GamepadFaceUp, ImGuiKey_GamepadL1, ImGuiKey_GamepadL2, ImGuiKey_GamepadL3, ImGuiKey_GamepadLStickDown, ImGuiKey_GamepadLStickLeft, ImGuiKey_GamepadLStickRight, ImGuiKey_GamepadLStickUp, ImGuiKey_GamepadR1, ImGuiKey_GamepadR2, ImGuiKey_GamepadR3, ImGuiKey_GamepadRStickDown, ImGuiKey_GamepadRStickLeft, ImGuiKey_GamepadRStickRight, ImGuiKey_GamepadRStickUp, ImGuiKey_GamepadStart, ImVector< T >::push_back(), ImVector< T >::Size, and ImGui_ImplSDL2_Data::WantUpdateGamepadsList.
Referenced by ImGui_ImplSDL2_NewFrame().
ImGui_ImplSDL2_UpdateKeyModifiers()
static void ImGui_ImplSDL2_UpdateKeyModifiers (SDL_Keymod sdl_key_mods) static
Definition at line 352 of file imgui_impl_sdl2.cpp.
References ImGuiIO::AddKeyEvent(), ImGui::GetIO(), ImGuiMod_Alt, ImGuiMod_Ctrl, ImGuiMod_Shift, and ImGuiMod_Super.
Referenced by ImGui_ImplSDL2_ProcessEvent().
ImGui_ImplSDL2_UpdateMouseCursor()
static void ImGui_ImplSDL2_UpdateMouseCursor () static
Definition at line 697 of file imgui_impl_sdl2.cpp.
References ImGuiIO::ConfigFlags, ImGui::GetIO(), ImGui::GetMouseCursor(), ImGui_ImplSDL2_GetBackendData(), ImGuiConfigFlags_NoMouseCursorChange, ImGuiMouseCursor_Arrow, ImGuiMouseCursor_None, ImGui_ImplSDL2_Data::MouseCursors, ImGuiIO::MouseDrawCursor, and ImGui_ImplSDL2_Data::MouseLastCursor.
Referenced by ImGui_ImplSDL2_NewFrame().
ImGui_ImplSDL2_UpdateMouseData()
static void ImGui_ImplSDL2_UpdateMouseData () static
Definition at line 649 of file imgui_impl_sdl2.cpp.
References ImGuiIO::AddMousePosEvent(), ImGui::GetIO(), ImGui_ImplSDL2_GetBackendData(), ImGuiMouseButton_COUNT, ImGui::IsMouseDragging(), ImGui_ImplSDL2_Data::MouseButtonsDown, ImGui_ImplSDL2_Data::MouseCanUseCapture, ImGui_ImplSDL2_Data::MouseCanUseGlobalState, ImGuiIO::MousePos, ImGuiIO::WantSetMousePos, ImGui_ImplSDL2_Data::Window, ImVec2::x, and ImVec2::y.
Referenced by ImGui_ImplSDL2_NewFrame().
Saturate()
static float Saturate (float v) inline static
Definition at line 782 of file imgui_impl_sdl2.cpp.
Referenced by ImGui_ImplSDL2_UpdateGamepadAnalog().