SignalProcessing: examples/imgui/examples/example_glfw_wgpu/main.cpp File Reference
main.cpp File Reference
#include "imgui.h"
#include "imgui_impl_glfw.h"
#include "imgui_impl_wgpu.h"
#include <stdio.h>
#include <stdlib.h>
#include <GLFW/glfw3.h>
#include <webgpu/webgpu.h>
#include <GLFW/glfw3native.h>
Macros
#define GLFW_HAS_X11_OR_WAYLAND 0
Functions
static bool InitWGPU (GLFWwindow *window)
static WGPUSurface CreateWGPUSurface (const WGPUInstance &instance, GLFWwindow *window)
static void glfw_error_callback (int error, const char *description)
static void ResizeSurface (int width, int height)
int main (int, char **)
Variables
static WGPUInstance wgpu_instance = nullptr
static WGPUDevice wgpu_device = nullptr
static WGPUSurface wgpu_surface = nullptr
static WGPUQueue wgpu_queue = nullptr
static WGPUSurfaceConfiguration wgpu_surface_configuration = {}
static int wgpu_surface_width = 1280
static int wgpu_surface_height = 800
Macro Definition Documentation
GLFW_HAS_X11_OR_WAYLAND
#define GLFW_HAS_X11_OR_WAYLAND 0
Definition at line 514 of file main.cpp.
Function Documentation
CreateWGPUSurface()
WGPUSurface CreateWGPUSurface (const WGPUInstance & instance, GLFWwindow * window) static
Definition at line 538 of file main.cpp.
References ImGui_ImplWGPU_CreateWGPUSurfaceHelper(), ImGui_ImplWGPU_CreateSurfaceInfo::Instance, ImGui_ImplWGPU_CreateSurfaceInfo::RawDisplay, ImGui_ImplWGPU_CreateSurfaceInfo::RawInstance, ImGui_ImplWGPU_CreateSurfaceInfo::RawSurface, ImGui_ImplWGPU_CreateSurfaceInfo::RawWindow, and ImGui_ImplWGPU_CreateSurfaceInfo::System.
Referenced by InitWGPU(), and InitWGPU().
glfw_error_callback()
static void glfw_error_callback (int error, const char * description) static
Definition at line 46 of file main.cpp.
InitWGPU()
static bool InitWGPU (GLFWwindow * window) static
Definition at line 409 of file main.cpp.
References CreateWGPUSurface(), IM_ASSERT, ImGui_ImplWGPU_DebugPrintAdapterInfo(), ImGui_ImplWGPU_GetLogLevelName(), wgpu_device, wgpu_instance, wgpu_queue, wgpu_surface, wgpu_surface_configuration, wgpu_surface_height, and wgpu_surface_width.
Referenced by main().
main()
int main (int , char **)
Definition at line 59 of file main.cpp.
References ImGui::Begin(), ImGui::Button(), ImGui::Checkbox(), clear_color, ImGui::ColorEdit3(), ImGuiIO::ConfigFlags, ImGui::CreateContext(), ImGui_ImplWGPU_InitInfo::DepthStencilFormat, ImGui::DestroyContext(), ImGui_ImplWGPU_InitInfo::Device, EMSCRIPTEN_MAINLOOP_BEGIN, EMSCRIPTEN_MAINLOOP_END, ImGui::End(), ImGuiStyle::FontScaleDpi, ImGuiIO::Framerate, ImGui::GetDrawData(), ImGui::GetIO(), ImGui::GetStyle(), GLFW_CLIENT_API, glfw_error_callback(), GLFW_ICONIFIED, GLFW_NO_API, glfwCreateWindow(), glfwDestroyWindow(), glfwGetFramebufferSize(), glfwGetPrimaryMonitor(), glfwGetWindowAttrib(), glfwInit(), glfwPollEvents(), glfwSetErrorCallback(), glfwShowWindow(), glfwTerminate(), glfwWindowHint(), glfwWindowShouldClose(), IMGUI_CHECKVERSION, ImGui_ImplGlfw_GetContentScaleForMonitor(), ImGui_ImplGlfw_InitForOther(), ImGui_ImplGlfw_NewFrame(), ImGui_ImplGlfw_Shutdown(), ImGui_ImplGlfw_Sleep(), ImGui_ImplWGPU_Init(), ImGui_ImplWGPU_IsSurfaceStatusError(), ImGui_ImplWGPU_IsSurfaceStatusSubOptimal(), ImGui_ImplWGPU_NewFrame(), ImGui_ImplWGPU_RenderDrawData(), ImGui_ImplWGPU_Shutdown(), ImGuiConfigFlags_NavEnableGamepad, ImGuiConfigFlags_NavEnableKeyboard, ImGuiIO::IniFilename, InitWGPU(), ImGui::NewFrame(), ImGui_ImplWGPU_InitInfo::NumFramesInFlight, ImGui::Render(), ImGui_ImplWGPU_InitInfo::RenderTargetFormat, ResizeSurface(), ImGui::SameLine(), ImGuiStyle::ScaleAllSizes(), show_another_window, show_demo_window, ImGui::ShowDemoWindow(), ImGui::SliderFloat(), ImGui::StyleColorsDark(), ImGui::Text(), ImVec4::w, wgpu_device, wgpu_instance, wgpu_queue, wgpu_surface, wgpu_surface_configuration, wgpu_surface_height, wgpu_surface_width, ImVec4::x, ImVec4::y, and ImVec4::z.
ResizeSurface()
static void ResizeSurface (int width, int height) static
Definition at line 51 of file main.cpp.
References wgpu_surface, wgpu_surface_configuration, wgpu_surface_height, and wgpu_surface_width.
Referenced by main().
Variable Documentation
wgpu_device
WGPUDevice wgpu_device = nullptr static
Definition at line 35 of file main.cpp.
Referenced by InitWGPU(), InitWGPU(), and main().
wgpu_instance
WGPUInstance wgpu_instance = nullptr static
Definition at line 34 of file main.cpp.
Referenced by InitWGPU(), InitWGPU(), and main().
wgpu_queue
WGPUQueue wgpu_queue = nullptr static
Definition at line 37 of file main.cpp.
Referenced by InitWGPU(), InitWGPU(), and main().
wgpu_surface
WGPUSurface wgpu_surface = nullptr static
Definition at line 36 of file main.cpp.
Referenced by InitWGPU(), InitWGPU(), main(), and ResizeSurface().
wgpu_surface_configuration
WGPUSurfaceConfiguration wgpu_surface_configuration = {} static
Definition at line 38 of file main.cpp.
Referenced by InitWGPU(), InitWGPU(), main(), and ResizeSurface().
wgpu_surface_height
int wgpu_surface_height = 800 static
Definition at line 40 of file main.cpp.
Referenced by InitWGPU(), InitWGPU(), main(), and ResizeSurface().
wgpu_surface_width
int wgpu_surface_width = 1280 static
Definition at line 39 of file main.cpp.
Referenced by InitWGPU(), InitWGPU(), main(), and ResizeSurface().