SignalProcessing: examples/imgui/examples/example_win32_directx10/main.cpp File Reference
main.cpp File Reference
#include "imgui.h"
#include "imgui_impl_win32.h"
#include "imgui_impl_dx10.h"
#include <d3d10_1.h>
#include <d3d10.h>
#include <tchar.h>
Functions
bool CreateDeviceD3D (HWND hWnd)
void CleanupDeviceD3D ()
void CreateRenderTarget ()
void CleanupRenderTarget ()
LRESULT WINAPI WndProc (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam)
int main (int, char **)
IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam)
Variables
static ID3D10Device * g_pd3dDevice = nullptr
static IDXGISwapChain * g_pSwapChain = nullptr
static bool g_SwapChainOccluded = false
static UINT g_ResizeWidth = 0
static UINT g_ResizeHeight = 0
static ID3D10RenderTargetView * g_mainRenderTargetView = nullptr
Function Documentation
CleanupDeviceD3D()
void CleanupDeviceD3D ()
Definition at line 230 of file main.cpp.
References CleanupRenderTarget(), g_pd3dDevice, and g_pSwapChain.
CleanupRenderTarget()
void CleanupRenderTarget ()
Definition at line 245 of file main.cpp.
References g_mainRenderTargetView.
CreateDeviceD3D()
bool CreateDeviceD3D (HWND hWnd)
Definition at line 198 of file main.cpp.
References CreateRenderTarget(), g_pd3dDevice, and g_pSwapChain.
CreateRenderTarget()
void CreateRenderTarget ()
Definition at line 237 of file main.cpp.
References g_mainRenderTargetView, g_pd3dDevice, and g_pSwapChain.
ImGui_ImplWin32_WndProcHandler()
IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam) extern
Definition at line 619 of file imgui_impl_win32.cpp.
Referenced by WndProc().
main()
int main (int , char **)
Definition at line 31 of file main.cpp.
References ImGui::Begin(), ImGui::Button(), ImGui::Checkbox(), CleanupDeviceD3D(), CleanupRenderTarget(), clear_color, ImGui::ColorEdit3(), ImGuiIO::ConfigFlags, ImGui::CreateContext(), CreateDeviceD3D(), CreateRenderTarget(), ImGui::DestroyContext(), ImGui::End(), ImGuiStyle::FontScaleDpi, ImGuiIO::Framerate, g_mainRenderTargetView, g_pd3dDevice, g_pSwapChain, g_ResizeHeight, g_ResizeWidth, g_SwapChainOccluded, ImGui::GetDrawData(), ImGui::GetIO(), ImGui::GetStyle(), IMGUI_CHECKVERSION, ImGui_ImplDX10_Init(), ImGui_ImplDX10_NewFrame(), ImGui_ImplDX10_RenderDrawData(), ImGui_ImplDX10_Shutdown(), ImGui_ImplWin32_EnableDpiAwareness(), ImGui_ImplWin32_GetDpiScaleForMonitor(), ImGui_ImplWin32_Init(), ImGui_ImplWin32_NewFrame(), ImGui_ImplWin32_Shutdown(), ImGuiConfigFlags_NavEnableGamepad, ImGuiConfigFlags_NavEnableKeyboard, ImGui::NewFrame(), ImGui::Render(), ImGui::SameLine(), ImGuiStyle::ScaleAllSizes(), show_another_window, show_demo_window, ImGui::ShowDemoWindow(), ImGui::SliderFloat(), ImGui::StyleColorsDark(), ImGui::Text(), ImVec4::w, WndProc(), ImVec4::x, ImVec4::y, and ImVec4::z.
WndProc()
LRESULT WINAPI WndProc (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam)
Definition at line 258 of file main.cpp.
References g_ResizeHeight, g_ResizeWidth, and ImGui_ImplWin32_WndProcHandler().
Referenced by main().
Variable Documentation
g_mainRenderTargetView
ID3D10RenderTargetView* g_mainRenderTargetView = nullptr static
Definition at line 21 of file main.cpp.
g_pd3dDevice
ID3D10Device* g_pd3dDevice = nullptr static
Definition at line 17 of file main.cpp.
g_pSwapChain
IDXGISwapChain* g_pSwapChain = nullptr static
Definition at line 18 of file main.cpp.
g_ResizeHeight
UINT g_ResizeHeight = 0 static
Definition at line 20 of file main.cpp.
Referenced by main(), and WndProc().
g_ResizeWidth
UINT g_ResizeWidth = 0 static
Definition at line 20 of file main.cpp.
Referenced by main(), and WndProc().
g_SwapChainOccluded
bool g_SwapChainOccluded = false static
Definition at line 19 of file main.cpp.
Referenced by main().