SignalProcessing: examples/imgui/examples/example_sdl3_directx11/main.cpp File Reference
main.cpp File Reference
#include "imgui.h"
#include "imgui_impl_sdl3.h"
#include "imgui_impl_dx11.h"
#include <d3d11.h>
#include <stdio.h>
#include <SDL3/SDL.h>
Functions
bool CreateDeviceD3D (HWND hWnd)
void CleanupDeviceD3D ()
void CreateRenderTarget ()
void CleanupRenderTarget ()
int main (int, char **)
Variables
static ID3D11Device * g_pd3dDevice = nullptr
static ID3D11DeviceContext * g_pd3dDeviceContext = nullptr
static IDXGISwapChain * g_pSwapChain = nullptr
static ID3D11RenderTargetView * g_mainRenderTargetView = nullptr
Function Documentation
CleanupDeviceD3D()
void CleanupDeviceD3D ()
Definition at line 239 of file main.cpp.
References CleanupRenderTarget(), g_pd3dDevice, g_pd3dDeviceContext, and g_pSwapChain.
CleanupRenderTarget()
void CleanupRenderTarget ()
Definition at line 255 of file main.cpp.
References g_mainRenderTargetView.
CreateDeviceD3D()
bool CreateDeviceD3D (HWND hWnd)
Definition at line 205 of file main.cpp.
References CreateRenderTarget(), g_pd3dDevice, g_pd3dDeviceContext, and g_pSwapChain.
CreateRenderTarget()
void CreateRenderTarget ()
Definition at line 247 of file main.cpp.
References g_mainRenderTargetView, g_pd3dDevice, and g_pSwapChain.
main()
int main (int , char **)
Definition at line 30 of file main.cpp.
References ImGui::Begin(), ImGui::Button(), ImGui::Checkbox(), CleanupDeviceD3D(), CleanupRenderTarget(), clear_color, ImGui::ColorEdit3(), ImGuiIO::ConfigFlags, ImGui::CreateContext(), CreateDeviceD3D(), CreateRenderTarget(), ImGui::DestroyContext(), ImGui::End(), ImGuiStyle::FontScaleDpi, ImGuiIO::Framerate, g_mainRenderTargetView, g_pd3dDevice, g_pd3dDeviceContext, g_pSwapChain, ImGui::GetDrawData(), ImGui::GetIO(), ImGui::GetStyle(), IMGUI_CHECKVERSION, ImGui_ImplDX11_Init(), ImGui_ImplDX11_NewFrame(), ImGui_ImplDX11_RenderDrawData(), ImGui_ImplDX11_Shutdown(), ImGui_ImplSDL3_InitForD3D(), ImGui_ImplSDL3_NewFrame(), ImGui_ImplSDL3_ProcessEvent(), ImGui_ImplSDL3_Shutdown(), ImGuiConfigFlags_NavEnableGamepad, ImGuiConfigFlags_NavEnableKeyboard, ImGui::NewFrame(), ImGui::Render(), ImGui::SameLine(), ImGuiStyle::ScaleAllSizes(), show_another_window, show_demo_window, ImGui::ShowDemoWindow(), ImGui::SliderFloat(), ImGui::StyleColorsDark(), ImGui::Text(), ImVec4::w, ImVec4::x, ImVec4::y, and ImVec4::z.
Variable Documentation
g_mainRenderTargetView
ID3D11RenderTargetView* g_mainRenderTargetView = nullptr static
Definition at line 21 of file main.cpp.
g_pd3dDevice
ID3D11Device* g_pd3dDevice = nullptr static
Definition at line 18 of file main.cpp.
g_pd3dDeviceContext
ID3D11DeviceContext* g_pd3dDeviceContext = nullptr static
Definition at line 19 of file main.cpp.
g_pSwapChain
IDXGISwapChain* g_pSwapChain = nullptr static
Definition at line 20 of file main.cpp.