SignalProcessing: examples/imgui/backends/imgui_impl_win32.cpp File Reference
imgui_impl_win32.cpp File Reference
#include "imgui.h"
#include "imgui_impl_win32.h"
#include <windows.h>
#include <windowsx.h>
#include <tchar.h>
#include <dwmapi.h>
#include <xinput.h>
Classes
struct ImGui_ImplWin32_Data
Macros
#define WIN32_LEAN_AND_MEAN
#define IM_SATURATE(V) (V < 0.0f ? 0.0f : V > 1.0f ? 1.0f : V)
#define MAP_BUTTON(KEY_NO, BUTTON_ENUM) { io.AddKeyEvent(KEY_NO, (gamepad.wButtons & BUTTON_ENUM) != 0); }
#define MAP_ANALOG(KEY_NO, VALUE, V0, V1) { float vn = (float)(VALUE - V0) / (float)(V1 - V0); io.AddKeyAnalogEvent(KEY_NO, vn > 0.10f, IM_SATURATE(vn)); }
#define WM_MOUSEHWHEEL 0x020E
#define DBT_DEVNODES_CHANGED 0x0007
#define _IsWindowsVistaOrGreater() _IsWindowsVersionOrGreater(HIBYTE(0x0600), LOBYTE(0x0600), 0)
#define _IsWindows8OrGreater() _IsWindowsVersionOrGreater(HIBYTE(0x0602), LOBYTE(0x0602), 0)
#define _IsWindows8Point1OrGreater() _IsWindowsVersionOrGreater(HIBYTE(0x0603), LOBYTE(0x0603), 0)
#define _IsWindows10OrGreater() _IsWindowsVersionOrGreater(HIBYTE(0x0A00), LOBYTE(0x0A00), 0)
#define DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE (DPI_AWARENESS_CONTEXT)-3
#define DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2 (DPI_AWARENESS_CONTEXT)-4
Typedefs
typedef DWORD(WINAPI * PFN_XInputGetCapabilities) (DWORD, DWORD, XINPUT_CAPABILITIES *)
typedef DWORD(WINAPI * PFN_XInputGetState) (DWORD, XINPUT_STATE *)
typedef HRESULT(WINAPI * PFN_SetProcessDpiAwareness) (PROCESS_DPI_AWARENESS)
typedef HRESULT(WINAPI * PFN_GetDpiForMonitor) (HMONITOR, MONITOR_DPI_TYPE, UINT *, UINT *)
typedef DPI_AWARENESS_CONTEXT(WINAPI * PFN_SetThreadDpiAwarenessContext) (DPI_AWARENESS_CONTEXT)
Enumerations
enum PROCESS_DPI_AWARENESS { PROCESS_DPI_UNAWARE = 0 , PROCESS_SYSTEM_DPI_AWARE = 1 , PROCESS_PER_MONITOR_DPI_AWARE = 2 }
enum MONITOR_DPI_TYPE { MDT_EFFECTIVE_DPI = 0 , MDT_ANGULAR_DPI = 1 , MDT_RAW_DPI = 2 , MDT_DEFAULT = MDT_EFFECTIVE_DPI }
Functions
static ImGui_ImplWin32_Data * ImGui_ImplWin32_GetBackendData ()
static ImGui_ImplWin32_Data * ImGui_ImplWin32_GetBackendData (ImGuiIO &io)
static void ImGui_ImplWin32_UpdateKeyboardCodePage (ImGuiIO &io)
static bool ImGui_ImplWin32_InitEx (void *hwnd, bool platform_has_own_dc)
IMGUI_IMPL_API bool ImGui_ImplWin32_Init (void *hwnd)
IMGUI_IMPL_API bool ImGui_ImplWin32_InitForOpenGL (void *hwnd)
void ImGui_ImplWin32_Shutdown ()
static bool ImGui_ImplWin32_UpdateMouseCursor (ImGuiIO &io, ImGuiMouseCursor imgui_cursor)
static bool IsVkDown (int vk)
static void ImGui_ImplWin32_AddKeyEvent (ImGuiIO &io, ImGuiKey key, bool down, int native_keycode, int native_scancode=-1)
static void ImGui_ImplWin32_ProcessKeyEventsWorkarounds (ImGuiIO &io)
static void ImGui_ImplWin32_UpdateKeyModifiers (ImGuiIO &io)
static void ImGui_ImplWin32_UpdateMouseData (ImGuiIO &io)
static void ImGui_ImplWin32_UpdateGamepads (ImGuiIO &io)
void ImGui_ImplWin32_NewFrame ()
ImGuiKey ImGui_ImplWin32_KeyEventToImGuiKey (WPARAM wParam, LPARAM lParam)
static ImGuiMouseSource ImGui_ImplWin32_GetMouseSourceFromMessageExtraInfo ()
IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam)
IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandlerEx (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam, ImGuiIO &io)
static BOOL _IsWindowsVersionOrGreater (WORD major, WORD minor, WORD)
DECLARE_HANDLE (DPI_AWARENESS_CONTEXT)
void ImGui_ImplWin32_EnableDpiAwareness ()
float ImGui_ImplWin32_GetDpiScaleForMonitor (void *monitor)
float ImGui_ImplWin32_GetDpiScaleForHwnd (void *hwnd)
void ImGui_ImplWin32_EnableAlphaCompositing (void *hwnd)
Macro Definition Documentation
_IsWindows10OrGreater
#define _IsWindows10OrGreater () _IsWindowsVersionOrGreater(HIBYTE(0x0A00), LOBYTE(0x0A00), 0)
Definition at line 865 of file imgui_impl_win32.cpp.
_IsWindows8OrGreater
#define _IsWindows8OrGreater () _IsWindowsVersionOrGreater(HIBYTE(0x0602), LOBYTE(0x0602), 0)
Definition at line 863 of file imgui_impl_win32.cpp.
_IsWindows8Point1OrGreater
#define _IsWindows8Point1OrGreater () _IsWindowsVersionOrGreater(HIBYTE(0x0603), LOBYTE(0x0603), 0)
Definition at line 864 of file imgui_impl_win32.cpp.
_IsWindowsVistaOrGreater
#define _IsWindowsVistaOrGreater () _IsWindowsVersionOrGreater(HIBYTE(0x0600), LOBYTE(0x0600), 0)
Definition at line 862 of file imgui_impl_win32.cpp.
DBT_DEVNODES_CHANGED
#define DBT_DEVNODES_CHANGED 0x0007
Definition at line 591 of file imgui_impl_win32.cpp.
DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE
#define DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE (DPI_AWARENESS_CONTEXT)-3
Definition at line 873 of file imgui_impl_win32.cpp.
DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2
#define DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2 (DPI_AWARENESS_CONTEXT)-4
Definition at line 876 of file imgui_impl_win32.cpp.
IM_SATURATE
#define IM_SATURATE (V) (V < 0.0f ? 0.0f : V > 1.0f ? 1.0f : V)
MAP_ANALOG
#define MAP_ANALOG (KEY_NO, VALUE, V0, V1) { float vn = (float)(VALUE - V0) / (float)(V1 - V0); io.AddKeyAnalogEvent(KEY_NO, vn > 0.10f, IM_SATURATE(vn)); }
MAP_BUTTON
#define MAP_BUTTON (KEY_NO, BUTTON_ENUM) { io.AddKeyEvent(KEY_NO, (gamepad.wButtons & BUTTON_ENUM) != 0); }
WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
Definition at line 88 of file imgui_impl_win32.cpp.
WM_MOUSEHWHEEL
#define WM_MOUSEHWHEEL 0x020E
Definition at line 588 of file imgui_impl_win32.cpp.
Typedef Documentation
PFN_GetDpiForMonitor
typedef HRESULT(WINAPI * PFN_GetDpiForMonitor) (HMONITOR, MONITOR_DPI_TYPE, UINT *, UINT *)
Definition at line 879 of file imgui_impl_win32.cpp.
PFN_SetProcessDpiAwareness
typedef HRESULT(WINAPI * PFN_SetProcessDpiAwareness) (PROCESS_DPI_AWARENESS)
Definition at line 878 of file imgui_impl_win32.cpp.
PFN_SetThreadDpiAwarenessContext
typedef DPI_AWARENESS_CONTEXT(WINAPI * PFN_SetThreadDpiAwarenessContext) (DPI_AWARENESS_CONTEXT)
Definition at line 880 of file imgui_impl_win32.cpp.
PFN_XInputGetCapabilities
typedef DWORD(WINAPI * PFN_XInputGetCapabilities) (DWORD, DWORD, XINPUT_CAPABILITIES *)
Definition at line 98 of file imgui_impl_win32.cpp.
PFN_XInputGetState
typedef DWORD(WINAPI * PFN_XInputGetState) (DWORD, XINPUT_STATE *)
Definition at line 99 of file imgui_impl_win32.cpp.
Enumeration Type Documentation
MONITOR_DPI_TYPE
enum MONITOR_DPI_TYPE
Enumerator
MDT_EFFECTIVE_DPI
MDT_ANGULAR_DPI
MDT_RAW_DPI
MDT_DEFAULT
Definition at line 869 of file imgui_impl_win32.cpp.
PROCESS_DPI_AWARENESS
enum PROCESS_DPI_AWARENESS
Enumerator
PROCESS_DPI_UNAWARE
PROCESS_SYSTEM_DPI_AWARE
PROCESS_PER_MONITOR_DPI_AWARE
Definition at line 868 of file imgui_impl_win32.cpp.
Function Documentation
_IsWindowsVersionOrGreater()
static BOOL _IsWindowsVersionOrGreater (WORD major, WORD minor, WORD) static
Definition at line 842 of file imgui_impl_win32.cpp.
DECLARE_HANDLE()
DECLARE_HANDLE (DPI_AWARENESS_CONTEXT)
ImGui_ImplWin32_AddKeyEvent()
static void ImGui_ImplWin32_AddKeyEvent (ImGuiIO & io, ImGuiKey key, bool down, int native_keycode, int native_scancode = -1) static
Definition at line 282 of file imgui_impl_win32.cpp.
References ImGuiIO::AddKeyEvent(), IM_UNUSED, and ImGuiIO::SetKeyEventNativeData().
Referenced by ImGui_ImplWin32_ProcessKeyEventsWorkarounds(), and ImGui_ImplWin32_WndProcHandlerEx().
ImGui_ImplWin32_EnableAlphaCompositing()
void ImGui_ImplWin32_EnableAlphaCompositing (void * hwnd)
Definition at line 955 of file imgui_impl_win32.cpp.
References _IsWindows8OrGreater, and _IsWindowsVistaOrGreater.
ImGui_ImplWin32_EnableDpiAwareness()
void ImGui_ImplWin32_EnableDpiAwareness ()
Definition at line 883 of file imgui_impl_win32.cpp.
References _IsWindows10OrGreater, _IsWindows8Point1OrGreater, DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2, and PROCESS_PER_MONITOR_DPI_AWARE.
Referenced by main().
ImGui_ImplWin32_GetBackendData() [1/2]
static ImGui_ImplWin32_Data * ImGui_ImplWin32_GetBackendData () static
Definition at line 139 of file imgui_impl_win32.cpp.
References ImGuiIO::BackendPlatformUserData, ImGui::GetCurrentContext(), and ImGui::GetIO().
Referenced by ImGui_ImplWin32_NewFrame(), ImGui_ImplWin32_Shutdown(), ImGui_ImplWin32_UpdateGamepads(), ImGui_ImplWin32_UpdateKeyboardCodePage(), ImGui_ImplWin32_UpdateMouseData(), and ImGui_ImplWin32_WndProcHandlerEx().
ImGui_ImplWin32_GetBackendData() [2/2]
static ImGui_ImplWin32_Data * ImGui_ImplWin32_GetBackendData (ImGuiIO & io) static
Definition at line 143 of file imgui_impl_win32.cpp.
References ImGuiIO::BackendPlatformUserData.
ImGui_ImplWin32_GetDpiScaleForHwnd()
float ImGui_ImplWin32_GetDpiScaleForHwnd (void * hwnd)
Definition at line 938 of file imgui_impl_win32.cpp.
References ImGui_ImplWin32_GetDpiScaleForMonitor().
ImGui_ImplWin32_GetDpiScaleForMonitor()
float ImGui_ImplWin32_GetDpiScaleForMonitor (void * monitor)
Definition at line 912 of file imgui_impl_win32.cpp.
References _IsWindows8Point1OrGreater, IM_ASSERT, and MDT_EFFECTIVE_DPI.
Referenced by ImGui_ImplWin32_GetDpiScaleForHwnd(), and main().
ImGui_ImplWin32_GetMouseSourceFromMessageExtraInfo()
static ImGuiMouseSource ImGui_ImplWin32_GetMouseSourceFromMessageExtraInfo () static
Definition at line 597 of file imgui_impl_win32.cpp.
References ImGuiMouseSource_Mouse, ImGuiMouseSource_Pen, and ImGuiMouseSource_TouchScreen.
Referenced by ImGui_ImplWin32_WndProcHandlerEx().
ImGui_ImplWin32_Init()
IMGUI_IMPL_API bool ImGui_ImplWin32_Init (void * hwnd)
Definition at line 213 of file imgui_impl_win32.cpp.
References ImGui_ImplWin32_InitEx().
Referenced by main().
ImGui_ImplWin32_InitEx()
static bool ImGui_ImplWin32_InitEx (void * hwnd, bool platform_has_own_dc) static
Definition at line 159 of file imgui_impl_win32.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendPlatformName, ImGuiIO::BackendPlatformUserData, ImGui::GetIO(), ImGui::GetMainViewport(), ImGui_ImplWin32_Data::hWnd, IM_ARRAYSIZE, IM_ASSERT, IM_NEW, IM_UNUSED, IMGUI_CHECKVERSION, ImGui_ImplWin32_UpdateKeyboardCodePage(), ImGuiBackendFlags_HasMouseCursors, ImGuiBackendFlags_HasSetMousePos, ImGuiMouseCursor_COUNT, ImGui_ImplWin32_Data::LastMouseCursor, ImGuiViewport::PlatformHandle, ImGuiViewport::PlatformHandleRaw, ImGui_ImplWin32_Data::TicksPerSecond, ImGui_ImplWin32_Data::Time, ImGui_ImplWin32_Data::WantUpdateHasGamepad, ImGui_ImplWin32_Data::XInputDLL, ImGui_ImplWin32_Data::XInputGetCapabilities, and ImGui_ImplWin32_Data::XInputGetState.
Referenced by ImGui_ImplWin32_Init(), and ImGui_ImplWin32_InitForOpenGL().
ImGui_ImplWin32_InitForOpenGL()
IMGUI_IMPL_API bool ImGui_ImplWin32_InitForOpenGL (void * hwnd)
Definition at line 218 of file imgui_impl_win32.cpp.
References ImGui_ImplWin32_InitEx().
Referenced by main().
ImGui_ImplWin32_KeyEventToImGuiKey()
ImGuiKey ImGui_ImplWin32_KeyEventToImGuiKey (WPARAM wParam, LPARAM lParam)
Definition at line 434 of file imgui_impl_win32.cpp.
References ImGuiKey_0, ImGuiKey_1, ImGuiKey_2, ImGuiKey_3, ImGuiKey_4, ImGuiKey_5, ImGuiKey_6, ImGuiKey_7, ImGuiKey_8, ImGuiKey_9, ImGuiKey_A, ImGuiKey_Apostrophe, ImGuiKey_AppBack, ImGuiKey_AppForward, ImGuiKey_B, ImGuiKey_Backslash, ImGuiKey_Backspace, ImGuiKey_C, ImGuiKey_CapsLock, ImGuiKey_Comma, ImGuiKey_D, ImGuiKey_Delete, ImGuiKey_DownArrow, ImGuiKey_E, ImGuiKey_End, ImGuiKey_Enter, ImGuiKey_Equal, ImGuiKey_Escape, ImGuiKey_F, ImGuiKey_F1, ImGuiKey_F10, ImGuiKey_F11, ImGuiKey_F12, ImGuiKey_F13, ImGuiKey_F14, ImGuiKey_F15, ImGuiKey_F16, ImGuiKey_F17, ImGuiKey_F18, ImGuiKey_F19, ImGuiKey_F2, ImGuiKey_F20, ImGuiKey_F21, ImGuiKey_F22, ImGuiKey_F23, ImGuiKey_F24, ImGuiKey_F3, ImGuiKey_F4, ImGuiKey_F5, ImGuiKey_F6, ImGuiKey_F7, ImGuiKey_F8, ImGuiKey_F9, ImGuiKey_G, ImGuiKey_GraveAccent, ImGuiKey_H, ImGuiKey_Home, ImGuiKey_I, ImGuiKey_Insert, ImGuiKey_J, ImGuiKey_K, ImGuiKey_Keypad0, ImGuiKey_Keypad1, ImGuiKey_Keypad2, ImGuiKey_Keypad3, ImGuiKey_Keypad4, ImGuiKey_Keypad5, ImGuiKey_Keypad6, ImGuiKey_Keypad7, ImGuiKey_Keypad8, ImGuiKey_Keypad9, ImGuiKey_KeypadAdd, ImGuiKey_KeypadDecimal, ImGuiKey_KeypadDivide, ImGuiKey_KeypadEnter, ImGuiKey_KeypadMultiply, ImGuiKey_KeypadSubtract, ImGuiKey_L, ImGuiKey_LeftAlt, ImGuiKey_LeftArrow, ImGuiKey_LeftBracket, ImGuiKey_LeftCtrl, ImGuiKey_LeftShift, ImGuiKey_LeftSuper, ImGuiKey_M, ImGuiKey_Menu, ImGuiKey_Minus, ImGuiKey_N, ImGuiKey_None, ImGuiKey_NumLock, ImGuiKey_O, ImGuiKey_Oem102, ImGuiKey_P, ImGuiKey_PageDown, ImGuiKey_PageUp, ImGuiKey_Pause, ImGuiKey_Period, ImGuiKey_PrintScreen, ImGuiKey_Q, ImGuiKey_R, ImGuiKey_RightAlt, ImGuiKey_RightArrow, ImGuiKey_RightBracket, ImGuiKey_RightCtrl, ImGuiKey_RightShift, ImGuiKey_RightSuper, ImGuiKey_S, ImGuiKey_ScrollLock, ImGuiKey_Semicolon, ImGuiKey_Slash, ImGuiKey_Space, ImGuiKey_T, ImGuiKey_Tab, ImGuiKey_U, ImGuiKey_UpArrow, ImGuiKey_V, ImGuiKey_W, ImGuiKey_X, ImGuiKey_Y, and ImGuiKey_Z.
Referenced by ImGui_ImplWin32_WndProcHandlerEx().
ImGui_ImplWin32_NewFrame()
void ImGui_ImplWin32_NewFrame ()
Definition at line 396 of file imgui_impl_win32.cpp.
References ImGuiIO::DeltaTime, ImGuiIO::DisplaySize, ImGui::GetIO(), ImGui::GetMouseCursor(), ImGui_ImplWin32_Data::hWnd, IM_ASSERT, ImGui_ImplWin32_GetBackendData(), ImGui_ImplWin32_ProcessKeyEventsWorkarounds(), ImGui_ImplWin32_UpdateGamepads(), ImGui_ImplWin32_UpdateMouseCursor(), ImGui_ImplWin32_UpdateMouseData(), ImGuiMouseCursor_None, ImGui_ImplWin32_Data::LastMouseCursor, ImGuiIO::MouseDrawCursor, ImGui_ImplWin32_Data::TicksPerSecond, and ImGui_ImplWin32_Data::Time.
Referenced by main().
ImGui_ImplWin32_ProcessKeyEventsWorkarounds()
static void ImGui_ImplWin32_ProcessKeyEventsWorkarounds (ImGuiIO & io) static
Definition at line 289 of file imgui_impl_win32.cpp.
References ImGui_ImplWin32_AddKeyEvent(), ImGuiKey_LeftShift, ImGuiKey_LeftSuper, ImGuiKey_RightShift, ImGuiKey_RightSuper, ImGui::IsKeyDown(), and IsVkDown().
Referenced by ImGui_ImplWin32_NewFrame().
ImGui_ImplWin32_Shutdown()
void ImGui_ImplWin32_Shutdown ()
Definition at line 224 of file imgui_impl_win32.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendPlatformName, ImGuiIO::BackendPlatformUserData, ImGuiPlatformIO::ClearPlatformHandlers(), ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplWin32_GetBackendData(), ImGuiBackendFlags_HasGamepad, ImGuiBackendFlags_HasMouseCursors, ImGuiBackendFlags_HasSetMousePos, and ImGui_ImplWin32_Data::XInputDLL.
Referenced by main().
ImGui_ImplWin32_UpdateGamepads()
static void ImGui_ImplWin32_UpdateGamepads (ImGuiIO & io) static
Definition at line 341 of file imgui_impl_win32.cpp.
References ImGuiIO::BackendFlags, ImGui_ImplWin32_Data::HasGamepad, IM_UNUSED, ImGui_ImplWin32_GetBackendData(), ImGuiBackendFlags_HasGamepad, ImGuiKey_GamepadBack, ImGuiKey_GamepadDpadDown, ImGuiKey_GamepadDpadLeft, ImGuiKey_GamepadDpadRight, ImGuiKey_GamepadDpadUp, ImGuiKey_GamepadFaceDown, ImGuiKey_GamepadFaceLeft, ImGuiKey_GamepadFaceRight, ImGuiKey_GamepadFaceUp, ImGuiKey_GamepadL1, ImGuiKey_GamepadL2, ImGuiKey_GamepadL3, ImGuiKey_GamepadLStickDown, ImGuiKey_GamepadLStickLeft, ImGuiKey_GamepadLStickRight, ImGuiKey_GamepadLStickUp, ImGuiKey_GamepadR1, ImGuiKey_GamepadR2, ImGuiKey_GamepadR3, ImGuiKey_GamepadRStickDown, ImGuiKey_GamepadRStickLeft, ImGuiKey_GamepadRStickRight, ImGuiKey_GamepadRStickUp, ImGuiKey_GamepadStart, MAP_ANALOG, MAP_BUTTON, ImGui_ImplWin32_Data::WantUpdateHasGamepad, ImGui_ImplWin32_Data::XInputGetCapabilities, and ImGui_ImplWin32_Data::XInputGetState.
Referenced by ImGui_ImplWin32_NewFrame().
ImGui_ImplWin32_UpdateKeyboardCodePage()
static void ImGui_ImplWin32_UpdateKeyboardCodePage (ImGuiIO & io) static
Definition at line 149 of file imgui_impl_win32.cpp.
References ImGui_ImplWin32_GetBackendData(), and ImGui_ImplWin32_Data::KeyboardCodePage.
Referenced by ImGui_ImplWin32_InitEx(), and ImGui_ImplWin32_WndProcHandlerEx().
ImGui_ImplWin32_UpdateKeyModifiers()
static void ImGui_ImplWin32_UpdateKeyModifiers (ImGuiIO & io) static
Definition at line 304 of file imgui_impl_win32.cpp.
References ImGuiIO::AddKeyEvent(), ImGuiMod_Alt, ImGuiMod_Ctrl, ImGuiMod_Shift, ImGuiMod_Super, and IsVkDown().
Referenced by ImGui_ImplWin32_WndProcHandlerEx().
ImGui_ImplWin32_UpdateMouseCursor()
static bool ImGui_ImplWin32_UpdateMouseCursor (ImGuiIO & io, ImGuiMouseCursor imgui_cursor) static
Definition at line 244 of file imgui_impl_win32.cpp.
References ImGuiIO::ConfigFlags, ImGuiConfigFlags_NoMouseCursorChange, ImGuiMouseCursor_Arrow, ImGuiMouseCursor_Hand, ImGuiMouseCursor_None, ImGuiMouseCursor_NotAllowed, ImGuiMouseCursor_Progress, ImGuiMouseCursor_ResizeAll, ImGuiMouseCursor_ResizeEW, ImGuiMouseCursor_ResizeNESW, ImGuiMouseCursor_ResizeNS, ImGuiMouseCursor_ResizeNWSE, ImGuiMouseCursor_TextInput, ImGuiMouseCursor_Wait, and ImGuiIO::MouseDrawCursor.
Referenced by ImGui_ImplWin32_NewFrame(), and ImGui_ImplWin32_WndProcHandlerEx().
ImGui_ImplWin32_UpdateMouseData()
static void ImGui_ImplWin32_UpdateMouseData (ImGuiIO & io) static
Definition at line 312 of file imgui_impl_win32.cpp.
References ImGuiIO::AddMousePosEvent(), ImGui_ImplWin32_Data::hWnd, IM_ASSERT, ImGui_ImplWin32_GetBackendData(), ImGuiIO::MousePos, ImGui_ImplWin32_Data::MouseTrackedArea, ImGuiIO::WantSetMousePos, ImVec2::x, and ImVec2::y.
Referenced by ImGui_ImplWin32_NewFrame().
ImGui_ImplWin32_WndProcHandler()
IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam) extern
Definition at line 619 of file imgui_impl_win32.cpp.
References ImGui::GetCurrentContext(), ImGui::GetIO(), and ImGui_ImplWin32_WndProcHandlerEx().
Referenced by WndProc().
ImGui_ImplWin32_WndProcHandlerEx()
IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandlerEx (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam, ImGuiIO & io) extern
Definition at line 629 of file imgui_impl_win32.cpp.
References ImGuiIO::AddFocusEvent(), ImGuiIO::AddInputCharacter(), ImGuiIO::AddInputCharacterUTF16(), ImGuiIO::AddMouseButtonEvent(), ImGuiIO::AddMousePosEvent(), ImGuiIO::AddMouseSourceEvent(), ImGuiIO::AddMouseWheelEvent(), DBT_DEVNODES_CHANGED, ImGui_ImplWin32_AddKeyEvent(), ImGui_ImplWin32_GetBackendData(), ImGui_ImplWin32_GetMouseSourceFromMessageExtraInfo(), ImGui_ImplWin32_KeyEventToImGuiKey(), ImGui_ImplWin32_UpdateKeyboardCodePage(), ImGui_ImplWin32_UpdateKeyModifiers(), ImGui_ImplWin32_UpdateMouseCursor(), ImGuiKey_LeftAlt, ImGuiKey_LeftCtrl, ImGuiKey_LeftShift, ImGuiKey_None, ImGuiKey_PrintScreen, ImGuiKey_RightAlt, ImGuiKey_RightCtrl, ImGuiKey_RightShift, IsVkDown(), ImGui_ImplWin32_Data::KeyboardCodePage, ImGui_ImplWin32_Data::LastMouseCursor, ImGui_ImplWin32_Data::MouseButtonsDown, ImGui_ImplWin32_Data::MouseHwnd, ImGui_ImplWin32_Data::MouseTrackedArea, ImGui_ImplWin32_Data::WantUpdateHasGamepad, and WM_MOUSEHWHEEL.
Referenced by ImGui_ImplWin32_WndProcHandler().
IsVkDown()
static bool IsVkDown (int vk) static
Definition at line 277 of file imgui_impl_win32.cpp.
Referenced by ImGui_ImplWin32_ProcessKeyEventsWorkarounds(), ImGui_ImplWin32_UpdateKeyModifiers(), and ImGui_ImplWin32_WndProcHandlerEx().