SignalProcessing: examples/imgui/backends/imgui_impl_glut.h File Reference
imgui_impl_glut.h File Reference
#include "imgui.h"
Functions
IMGUI_IMPL_API bool ImGui_ImplGLUT_Init ()
IMGUI_IMPL_API void ImGui_ImplGLUT_InstallFuncs ()
IMGUI_IMPL_API void ImGui_ImplGLUT_Shutdown ()
IMGUI_IMPL_API void ImGui_ImplGLUT_NewFrame ()
IMGUI_IMPL_API void ImGui_ImplGLUT_ReshapeFunc (int w, int h)
IMGUI_IMPL_API void ImGui_ImplGLUT_MotionFunc (int x, int y)
IMGUI_IMPL_API void ImGui_ImplGLUT_MouseFunc (int button, int state, int x, int y)
IMGUI_IMPL_API void ImGui_ImplGLUT_MouseWheelFunc (int button, int dir, int x, int y)
IMGUI_IMPL_API void ImGui_ImplGLUT_KeyboardFunc (unsigned char c, int x, int y)
IMGUI_IMPL_API void ImGui_ImplGLUT_KeyboardUpFunc (unsigned char c, int x, int y)
IMGUI_IMPL_API void ImGui_ImplGLUT_SpecialFunc (int key, int x, int y)
IMGUI_IMPL_API void ImGui_ImplGLUT_SpecialUpFunc (int key, int x, int y)
Function Documentation
ImGui_ImplGLUT_Init()
IMGUI_IMPL_API bool ImGui_ImplGLUT_Init ()
Definition at line 167 of file imgui_impl_glut.cpp.
References ImGuiIO::BackendPlatformName, g_Time, ImGui::GetIO(), and IMGUI_CHECKVERSION.
Referenced by main().
ImGui_ImplGLUT_InstallFuncs()
IMGUI_IMPL_API void ImGui_ImplGLUT_InstallFuncs ()
Definition at line 182 of file imgui_impl_glut.cpp.
References ImGui_ImplGLUT_KeyboardFunc(), ImGui_ImplGLUT_KeyboardUpFunc(), ImGui_ImplGLUT_MotionFunc(), ImGui_ImplGLUT_MouseFunc(), ImGui_ImplGLUT_MouseWheelFunc(), ImGui_ImplGLUT_ReshapeFunc(), ImGui_ImplGLUT_SpecialFunc(), and ImGui_ImplGLUT_SpecialUpFunc().
Referenced by main().
ImGui_ImplGLUT_KeyboardFunc()
IMGUI_IMPL_API void ImGui_ImplGLUT_KeyboardFunc (unsigned char c, int x, int y)
Definition at line 231 of file imgui_impl_glut.cpp.
References ImGuiIO::AddInputCharacter(), ImGui::GetIO(), ImGui_ImplGLUT_AddKeyEvent(), ImGui_ImplGLUT_KeyToImGuiKey(), and ImGui_ImplGLUT_UpdateKeyModifiers().
Referenced by ImGui_ImplGLUT_InstallFuncs().
ImGui_ImplGLUT_KeyboardUpFunc()
IMGUI_IMPL_API void ImGui_ImplGLUT_KeyboardUpFunc (unsigned char c, int x, int y)
Definition at line 245 of file imgui_impl_glut.cpp.
References ImGui_ImplGLUT_AddKeyEvent(), ImGui_ImplGLUT_KeyToImGuiKey(), and ImGui_ImplGLUT_UpdateKeyModifiers().
Referenced by ImGui_ImplGLUT_InstallFuncs().
ImGui_ImplGLUT_MotionFunc()
IMGUI_IMPL_API void ImGui_ImplGLUT_MotionFunc (int x, int y)
Definition at line 301 of file imgui_impl_glut.cpp.
References ImGuiIO::AddMousePosEvent(), and ImGui::GetIO().
Referenced by ImGui_ImplGLUT_InstallFuncs().
ImGui_ImplGLUT_MouseFunc()
IMGUI_IMPL_API void ImGui_ImplGLUT_MouseFunc (int button, int state, int x, int y)
Definition at line 272 of file imgui_impl_glut.cpp.
References ImGuiIO::AddMouseButtonEvent(), ImGuiIO::AddMousePosEvent(), and ImGui::GetIO().
Referenced by ImGui_ImplGLUT_InstallFuncs().
ImGui_ImplGLUT_MouseWheelFunc()
IMGUI_IMPL_API void ImGui_ImplGLUT_MouseWheelFunc (int button, int dir, int x, int y)
Referenced by ImGui_ImplGLUT_InstallFuncs().
ImGui_ImplGLUT_NewFrame()
IMGUI_IMPL_API void ImGui_ImplGLUT_NewFrame ()
Definition at line 203 of file imgui_impl_glut.cpp.
References ImGuiIO::DeltaTime, g_Time, and ImGui::GetIO().
Referenced by MainLoopStep().
ImGui_ImplGLUT_ReshapeFunc()
IMGUI_IMPL_API void ImGui_ImplGLUT_ReshapeFunc (int w, int h)
Definition at line 295 of file imgui_impl_glut.cpp.
References ImGuiIO::DisplaySize, and ImGui::GetIO().
Referenced by ImGui_ImplGLUT_InstallFuncs().
ImGui_ImplGLUT_Shutdown()
IMGUI_IMPL_API void ImGui_ImplGLUT_Shutdown ()
Definition at line 197 of file imgui_impl_glut.cpp.
References ImGuiIO::BackendPlatformName, and ImGui::GetIO().
Referenced by main().
ImGui_ImplGLUT_SpecialFunc()
IMGUI_IMPL_API void ImGui_ImplGLUT_SpecialFunc (int key, int x, int y)
Definition at line 254 of file imgui_impl_glut.cpp.
References ImGui_ImplGLUT_AddKeyEvent(), ImGui_ImplGLUT_KeyToImGuiKey(), and ImGui_ImplGLUT_UpdateKeyModifiers().
Referenced by ImGui_ImplGLUT_InstallFuncs().
ImGui_ImplGLUT_SpecialUpFunc()
IMGUI_IMPL_API void ImGui_ImplGLUT_SpecialUpFunc (int key, int x, int y)
Definition at line 263 of file imgui_impl_glut.cpp.
References ImGui_ImplGLUT_AddKeyEvent(), ImGui_ImplGLUT_KeyToImGuiKey(), and ImGui_ImplGLUT_UpdateKeyModifiers().
Referenced by ImGui_ImplGLUT_InstallFuncs().