SignalProcessing: examples/imgui/imgui_draw.cpp File Reference
imgui_draw.cpp File Reference
#include "imgui.h"
#include "imgui_internal.h"
#include <stdio.h>
#include <stdint.h>
#include "imstb_rectpack.h"
#include "imstb_truetype.h"
Classes
struct ImTriangulatorNode
struct ImTriangulatorNodeSpan
struct ImTriangulator
struct ImGui_ImplStbTrueType_FontSrcData
Macros
#define IMGUI_DEFINE_MATH_OPERATORS
#define STBRP_STATIC
#define STBRP_ASSERT(x) do { IM_ASSERT(x); } while (0)
#define STBRP_SORT ImQsort
#define STB_RECT_PACK_IMPLEMENTATION
#define STBTT_malloc(x, u) ((void)(u), IM_ALLOC(x))
#define STBTT_free(x, u) ((void)(u), IM_FREE(x))
#define STBTT_assert(x) do { IM_ASSERT(x); } while(0)
#define STBTT_fmod(x, y) ImFmod(x,y)
#define STBTT_sqrt(x) ImSqrt(x)
#define STBTT_pow(x, y) ImPow(x,y)
#define STBTT_fabs(x) ImFabs(x)
#define STBTT_ifloor(x) ((int)ImFloor(x))
#define STBTT_iceil(x) ((int)ImCeil(x))
#define STBTT_strlen(x) ImStrlen(x)
#define STBTT_STATIC
#define STB_TRUETYPE_IMPLEMENTATION
#define ImDrawCmd_HeaderSize (offsetof(ImDrawCmd, VtxOffset) + sizeof(unsigned int))
#define ImDrawCmd_HeaderCompare(CMD_LHS, CMD_RHS) (memcmp(CMD_LHS, CMD_RHS, ImDrawCmd_HeaderSize))
#define ImDrawCmd_HeaderCopy(CMD_DST, CMD_SRC) (memcpy(CMD_DST, CMD_SRC, ImDrawCmd_HeaderSize))
#define ImDrawCmd_AreSequentialIdxOffset(CMD_0, CMD_1) (CMD_0->IdxOffset + CMD_0->ElemCount == CMD_1->IdxOffset)
#define IM_NORMALIZE2F_OVER_ZERO(VX, VY) { float d2 = VX*VX + VY*VY; if (d2 > 0.0f) { float inv_len = ImRsqrt(d2); VX *= inv_len; VY *= inv_len; } } (void)0
#define IM_FIXNORMAL2F_MAX_INVLEN2 100.0f
#define IM_FIXNORMAL2F(VX, VY) { float d2 = VX*VX + VY*VY; if (d2 > 0.000001f) { float inv_len2 = 1.0f / d2; if (inv_len2 > IM_FIXNORMAL2F_MAX_INVLEN2) inv_len2 = IM_FIXNORMAL2F_MAX_INVLEN2; VX *= inv_len2; VY *= inv_len2; } } (void)0
#define IM_FONTGLYPH_INDEX_UNUSED ((ImU16)-1)
#define IM_FONTGLYPH_INDEX_NOT_FOUND ((ImU16)-2)
#define stb__in2(x) ((i[x] << 8) + i[(x)+1])
#define stb__in3(x) ((i[x] << 16) + stb__in2((x)+1))
#define stb__in4(x) ((i[x] << 24) + stb__in3((x)+1))
Enumerations
enum ImTriangulatorNodeType { ImTriangulatorNodeType_Convex , ImTriangulatorNodeType_Ear , ImTriangulatorNodeType_Reflex }
Functions
ImVec2 ImBezierCubicCalc (const ImVec2 &p1, const ImVec2 &p2, const ImVec2 &p3, const ImVec2 &p4, float t)
ImVec2 ImBezierQuadraticCalc (const ImVec2 &p1, const ImVec2 &p2, const ImVec2 &p3, float t)
static void PathBezierCubicCurveToCasteljau (ImVector< ImVec2 > *path, float x1, float y1, float x2, float y2, float x3, float y3, float x4, float y4, float tess_tol, int level)
static void PathBezierQuadraticCurveToCasteljau (ImVector< ImVec2 > *path, float x1, float y1, float x2, float y2, float x3, float y3, float tess_tol, int level)
static ImDrawFlags FixRectCornerFlags (ImDrawFlags flags)
int ImTextureDataGetFormatBytesPerPixel (ImTextureFormat format)
const char * ImTextureDataGetStatusName (ImTextureStatus status)
const char * ImTextureDataGetFormatName (ImTextureFormat format)
static void ImFontAtlasBuildUpdateRendererHasTexturesFromContext (ImFontAtlas *atlas)
void ImFontAtlasUpdateNewFrame (ImFontAtlas *atlas, int frame_count, bool renderer_has_textures)
void ImFontAtlasTextureBlockConvert (const unsigned char *src_pixels, ImTextureFormat src_fmt, int src_pitch, unsigned char *dst_pixels, ImTextureFormat dst_fmt, int dst_pitch, int w, int h)
void ImFontAtlasTextureBlockPostProcess (ImFontAtlasPostProcessData *data)
void ImFontAtlasTextureBlockPostProcessMultiply (ImFontAtlasPostProcessData *data, float multiply_factor)
void ImFontAtlasTextureBlockFill (ImTextureData *dst_tex, int dst_x, int dst_y, int w, int h, ImU32 col)
void ImFontAtlasTextureBlockCopy (ImTextureData *src_tex, int src_x, int src_y, ImTextureData *dst_tex, int dst_x, int dst_y, int w, int h)
void ImFontAtlasTextureBlockQueueUpload (ImFontAtlas *atlas, ImTextureData *tex, int x, int y, int w, int h)
static void GetTexDataAsFormat (ImFontAtlas *atlas, ImTextureFormat format, unsigned char **out_pixels, int *out_width, int *out_height, int *out_bytes_per_pixel)
static unsigned int stb_decompress_length (const unsigned char *input)
static unsigned int stb_decompress (unsigned char *output, const unsigned char *input, unsigned int length)
static unsigned int Decode85Byte (char c)
static void Decode85 (const unsigned char *src, unsigned char *dst)
static const char * GetDefaultCompressedFontDataTTF (int *out_size)
void ImFontAtlasBuildNotifySetFont (ImFontAtlas *atlas, ImFont *old_font, ImFont *new_font)
bool ImFontAtlasGetMouseCursorTexData (ImFontAtlas *atlas, ImGuiMouseCursor cursor_type, ImVec2 *out_offset, ImVec2 *out_size, ImVec2 out_uv_border[2], ImVec2 out_uv_fill[2])
void ImFontAtlasBuildMain (ImFontAtlas *atlas)
void ImFontAtlasBuildGetOversampleFactors (ImFontConfig *src, ImFontBaked *baked, int *out_oversample_h, int *out_oversample_v)
void ImFontAtlasBuildSetupFontLoader (ImFontAtlas *atlas, const ImFontLoader *font_loader)
void ImFontAtlasBuildLegacyPreloadAllGlyphRanges (ImFontAtlas *atlas)
void ImFontAtlasBuildUpdatePointers (ImFontAtlas *atlas)
void ImFontAtlasBuildRenderBitmapFromString (ImFontAtlas *atlas, int x, int y, int w, int h, const char *in_str, char in_marker_char)
static void ImFontAtlasBuildUpdateBasicTexData (ImFontAtlas *atlas)
static void ImFontAtlasBuildUpdateLinesTexData (ImFontAtlas *atlas)
bool ImFontAtlasFontInitOutput (ImFontAtlas *atlas, ImFont *font)
void ImFontAtlasFontDestroyOutput (ImFontAtlas *atlas, ImFont *font)
bool ImFontAtlasFontSourceInit (ImFontAtlas *atlas, ImFontConfig *src)
void ImFontAtlasFontSourceAddToFont (ImFontAtlas *atlas, ImFont *font, ImFontConfig *src)
void ImFontAtlasFontDestroySourceData (ImFontAtlas *atlas, ImFontConfig *src)
static ImFontGlyph * ImFontAtlasBuildSetupFontBakedEllipsis (ImFontAtlas *atlas, ImFontBaked *baked)
static void ImFontAtlasBuildSetupFontBakedFallback (ImFontBaked *baked)
static void ImFontAtlasBuildSetupFontBakedBlanks (ImFontAtlas *atlas, ImFontBaked *baked)
void ImFontAtlasBuildSetupFontSpecialGlyphs (ImFontAtlas *atlas, ImFont *font, ImFontConfig *src)
void ImFontAtlasBakedDiscardFontGlyph (ImFontAtlas *atlas, ImFont *font, ImFontBaked *baked, ImFontGlyph *glyph)
ImFontBaked * ImFontAtlasBakedAdd (ImFontAtlas *atlas, ImFont *font, float font_size, float font_rasterizer_density, ImGuiID baked_id)
ImFontBaked * ImFontAtlasBakedGetClosestMatch (ImFontAtlas *atlas, ImFont *font, float font_size, float font_rasterizer_density)
void ImFontAtlasBakedDiscard (ImFontAtlas *atlas, ImFont *font, ImFontBaked *baked)
void ImFontAtlasFontDiscardBakes (ImFontAtlas *atlas, ImFont *font, int unused_frames)
void ImFontAtlasBuildDiscardBakes (ImFontAtlas *atlas, int unused_frames)
void ImFontAtlasAddDrawListSharedData (ImFontAtlas *atlas, ImDrawListSharedData *data)
void ImFontAtlasRemoveDrawListSharedData (ImFontAtlas *atlas, ImDrawListSharedData *data)
void ImFontAtlasUpdateDrawListsTextures (ImFontAtlas *atlas, ImTextureRef old_tex, ImTextureRef new_tex)
void ImFontAtlasUpdateDrawListsSharedData (ImFontAtlas *atlas)
static void ImFontAtlasBuildSetTexture (ImFontAtlas *atlas, ImTextureData *tex)
ImTextureData * ImFontAtlasTextureAdd (ImFontAtlas *atlas, int w, int h)
void ImFontAtlasTextureRepack (ImFontAtlas *atlas, int w, int h)
void ImFontAtlasTextureGrow (ImFontAtlas *atlas, int old_tex_w, int old_tex_h)
void ImFontAtlasTextureMakeSpace (ImFontAtlas *atlas)
ImVec2i ImFontAtlasTextureGetSizeEstimate (ImFontAtlas *atlas)
void ImFontAtlasBuildClear (ImFontAtlas *atlas)
void ImFontAtlasTextureCompact (ImFontAtlas *atlas)
void ImFontAtlasBuildInit (ImFontAtlas *atlas)
void ImFontAtlasBuildDestroy (ImFontAtlas *atlas)
void ImFontAtlasPackInit (ImFontAtlas *atlas)
static ImFontAtlasRectId ImFontAtlasPackAllocRectEntry (ImFontAtlas *atlas, int rect_idx)
static ImFontAtlasRectId ImFontAtlasPackReuseRectEntry (ImFontAtlas *atlas, ImFontAtlasRectEntry *index_entry)
void ImFontAtlasPackDiscardRect (ImFontAtlas *atlas, ImFontAtlasRectId id)
ImFontAtlasRectId ImFontAtlasPackAddRect (ImFontAtlas *atlas, int w, int h, ImFontAtlasRectEntry *overwrite_entry)
ImTextureRect * ImFontAtlasPackGetRect (ImFontAtlas *atlas, ImFontAtlasRectId id)
ImTextureRect * ImFontAtlasPackGetRectSafe (ImFontAtlas *atlas, ImFontAtlasRectId id)
static bool ImFontAtlasBuildAcceptCodepointForSource (ImFontConfig *src, ImWchar codepoint)
static void ImFontBaked_BuildGrowIndex (ImFontBaked *baked, int new_size)
static void ImFontAtlas_FontHookRemapCodepoint (ImFontAtlas *atlas, ImFont *font, ImWchar *c)
static ImFontGlyph * ImFontBaked_BuildLoadGlyph (ImFontBaked *baked, ImWchar codepoint, float *only_load_advance_x)
static float ImFontBaked_BuildLoadGlyphAdvanceX (ImFontBaked *baked, ImWchar codepoint)
static float BuildLoadGlyphGetAdvanceOrFallback (ImFontBaked *baked, unsigned int codepoint)
void ImFontAtlasDebugLogTextureRequests (ImFontAtlas *atlas)
static bool ImGui_ImplStbTrueType_FontSrcInit (ImFontAtlas *atlas, ImFontConfig *src)
static void ImGui_ImplStbTrueType_FontSrcDestroy (ImFontAtlas *atlas, ImFontConfig *src)
static bool ImGui_ImplStbTrueType_FontSrcContainsGlyph (ImFontAtlas *atlas, ImFontConfig *src, ImWchar codepoint)
static bool ImGui_ImplStbTrueType_FontBakedInit (ImFontAtlas *atlas, ImFontConfig *src, ImFontBaked *baked, void *)
static bool ImGui_ImplStbTrueType_FontBakedLoadGlyph (ImFontAtlas *atlas, ImFontConfig *src, ImFontBaked *baked, void *, ImWchar codepoint, ImFontGlyph *out_glyph, float *out_advance_x)
const ImFontLoader * ImFontAtlasGetFontLoaderForStbTruetype ()
static void UnpackAccumulativeOffsetsIntoRanges (int base_codepoint, const short *accumulative_offsets, int accumulative_offsets_count, ImWchar *out_ranges)
ImFontGlyph * ImFontAtlasBakedAddFontGlyph (ImFontAtlas *atlas, ImFontBaked *baked, ImFontConfig *src, const ImFontGlyph *in_glyph)
void ImFontAtlasBakedAddFontGlyphAdvancedX (ImFontAtlas *atlas, ImFontBaked *baked, ImFontConfig *src, ImWchar codepoint, float advance_x)
void ImFontAtlasBakedSetFontGlyphBitmap (ImFontAtlas *atlas, ImFontBaked *baked, ImFontConfig *src, ImFontGlyph *glyph, ImTextureRect *r, const unsigned char *src_pixels, ImTextureFormat src_fmt, int src_pitch)
ImGuiID ImFontAtlasBakedGetId (ImGuiID font_id, float baked_size, float rasterizer_density)
ImFontBaked * ImFontAtlasBakedGetOrAdd (ImFontAtlas *atlas, ImFont *font, float font_size, float font_rasterizer_density)
const char * ImTextCalcWordWrapNextLineStart (const char *text, const char *text_end, ImDrawTextFlags flags)
const char * ImFontCalcWordWrapPositionEx (ImFont *font, float size, const char *text, const char *text_end, float wrap_width, ImDrawTextFlags flags)
ImVec2 ImFontCalcTextSizeEx (ImFont *font, float size, float max_width, float wrap_width, const char *text_begin, const char *text_end_display, const char *text_end, const char **out_remaining, ImVec2 *out_offset, ImDrawTextFlags flags)
static float ImAcos01 (float x)
static void stb__match (const unsigned char *data, unsigned int length)
static void stb__lit (const unsigned char *data, unsigned int length)
static const unsigned char * stb_decompress_token (const unsigned char *i)
static unsigned int stb_adler32 (unsigned int adler32, unsigned char *buffer, unsigned int buflen)
Variables
const int FONT_ATLAS_DEFAULT_TEX_DATA_W = 122
const int FONT_ATLAS_DEFAULT_TEX_DATA_H = 27
static const char FONT_ATLAS_DEFAULT_TEX_DATA_PIXELS [FONT_ATLAS_DEFAULT_TEX_DATA_W *FONT_ATLAS_DEFAULT_TEX_DATA_H+1]
static const ImVec2 FONT_ATLAS_DEFAULT_TEX_CURSOR_DATA [ImGuiMouseCursor_COUNT][3]
static unsigned char * stb__barrier_out_e
static unsigned char * stb__barrier_out_b
static const unsigned char * stb__barrier_in_b
static unsigned char * stb__dout
static const unsigned int proggy_clean_ttf_compressed_size = 9583
static const unsigned char proggy_clean_ttf_compressed_data [9583]
Macro Definition Documentation
IM_FIXNORMAL2F
#define IM_FIXNORMAL2F (VX, VY) { float d2 = VX*VX + VY*VY; if (d2 > 0.000001f) { float inv_len2 = 1.0f / d2; if (inv_len2 > IM_FIXNORMAL2F_MAX_INVLEN2) inv_len2 = IM_FIXNORMAL2F_MAX_INVLEN2; VX *= inv_len2; VY *= inv_len2; } } (void)0
Definition at line 802 of file imgui_draw.cpp.
IM_FIXNORMAL2F_MAX_INVLEN2
#define IM_FIXNORMAL2F_MAX_INVLEN2 100.0f
Definition at line 801 of file imgui_draw.cpp.
IM_FONTGLYPH_INDEX_NOT_FOUND
#define IM_FONTGLYPH_INDEX_NOT_FOUND ((ImU16)-2)
Definition at line 2634 of file imgui_draw.cpp.
IM_FONTGLYPH_INDEX_UNUSED
#define IM_FONTGLYPH_INDEX_UNUSED ((ImU16)-1)
Definition at line 2633 of file imgui_draw.cpp.
IM_NORMALIZE2F_OVER_ZERO
#define IM_NORMALIZE2F_OVER_ZERO (VX, VY) { float d2 = VX*VX + VY*VY; if (d2 > 0.0f) { float inv_len = ImRsqrt(d2); VX *= inv_len; VY *= inv_len; } } (void)0
Definition at line 800 of file imgui_draw.cpp.
ImDrawCmd_AreSequentialIdxOffset
#define ImDrawCmd_AreSequentialIdxOffset (CMD_0, CMD_1) (CMD_0->IdxOffset + CMD_0->ElemCount == CMD_1->IdxOffset)
Definition at line 565 of file imgui_draw.cpp.
ImDrawCmd_HeaderCompare
#define ImDrawCmd_HeaderCompare (CMD_LHS, CMD_RHS) (memcmp(CMD_LHS, CMD_RHS, ImDrawCmd_HeaderSize))
Definition at line 563 of file imgui_draw.cpp.
ImDrawCmd_HeaderCopy
#define ImDrawCmd_HeaderCopy (CMD_DST, CMD_SRC) (memcpy(CMD_DST, CMD_SRC, ImDrawCmd_HeaderSize))
Definition at line 564 of file imgui_draw.cpp.
ImDrawCmd_HeaderSize
#define ImDrawCmd_HeaderSize (offsetof(ImDrawCmd, VtxOffset) + sizeof(unsigned int))
Definition at line 562 of file imgui_draw.cpp.
IMGUI_DEFINE_MATH_OPERATORS
#define IMGUI_DEFINE_MATH_OPERATORS
Definition at line 32 of file imgui_draw.cpp.
stb__in2
#define stb__in2 (x) ((i[x] << 8) + i[(x)+1])
Definition at line 6070 of file imgui_draw.cpp.
stb__in3
#define stb__in3 (x) ((i[x] << 16) + stb__in2((x)+1))
Definition at line 6071 of file imgui_draw.cpp.
stb__in4
#define stb__in4 (x) ((i[x] << 24) + stb__in3((x)+1))
Definition at line 6072 of file imgui_draw.cpp.
STB_RECT_PACK_IMPLEMENTATION
#define STB_RECT_PACK_IMPLEMENTATION
Definition at line 128 of file imgui_draw.cpp.
STB_TRUETYPE_IMPLEMENTATION
#define STB_TRUETYPE_IMPLEMENTATION
Definition at line 151 of file imgui_draw.cpp.
STBRP_ASSERT
#define STBRP_ASSERT (x) do { IM_ASSERT(x); } while (0)
Definition at line 126 of file imgui_draw.cpp.
STBRP_SORT
#define STBRP_SORT ImQsort
Definition at line 127 of file imgui_draw.cpp.
STBRP_STATIC
#define STBRP_STATIC
Definition at line 125 of file imgui_draw.cpp.
STBTT_assert
#define STBTT_assert (x) do { IM_ASSERT(x); } while(0)
Definition at line 142 of file imgui_draw.cpp.
STBTT_fabs
#define STBTT_fabs (x) ImFabs(x)
Definition at line 146 of file imgui_draw.cpp.
STBTT_fmod
#define STBTT_fmod (x, y) ImFmod(x,y)
Definition at line 143 of file imgui_draw.cpp.
STBTT_free
#define STBTT_free (x, u) ((void)(u), IM_FREE(x))
Definition at line 141 of file imgui_draw.cpp.
STBTT_iceil
#define STBTT_iceil (x) ((int)ImCeil(x))
Definition at line 148 of file imgui_draw.cpp.
STBTT_ifloor
#define STBTT_ifloor (x) ((int)ImFloor(x))
Definition at line 147 of file imgui_draw.cpp.
STBTT_malloc
#define STBTT_malloc (x, u) ((void)(u), IM_ALLOC(x))
Definition at line 140 of file imgui_draw.cpp.
STBTT_pow
#define STBTT_pow (x, y) ImPow(x,y)
Definition at line 145 of file imgui_draw.cpp.
STBTT_sqrt
#define STBTT_sqrt (x) ImSqrt(x)
Definition at line 144 of file imgui_draw.cpp.
STBTT_STATIC
#define STBTT_STATIC
Definition at line 150 of file imgui_draw.cpp.
STBTT_strlen
#define STBTT_strlen (x) ImStrlen(x)
Definition at line 149 of file imgui_draw.cpp.
Enumeration Type Documentation
ImTriangulatorNodeType
enum ImTriangulatorNodeType
Enumerator
ImTriangulatorNodeType_Convex
ImTriangulatorNodeType_Ear
ImTriangulatorNodeType_Reflex
Definition at line 1808 of file imgui_draw.cpp.
Function Documentation
BuildLoadGlyphGetAdvanceOrFallback()
static float BuildLoadGlyphGetAdvanceOrFallback (ImFontBaked * baked, unsigned int codepoint) static
Definition at line 4524 of file imgui_draw.cpp.
References ImFontBaked_BuildLoadGlyphAdvanceX().
Referenced by ImFontCalcTextSizeEx(), and ImFontCalcWordWrapPositionEx().
Decode85()
static void Decode85 (const unsigned char * src, unsigned char * dst) static
Definition at line 3097 of file imgui_draw.cpp.
References Decode85Byte().
Referenced by ImFontAtlas::AddFontFromMemoryCompressedBase85TTF().
Decode85Byte()
static unsigned int Decode85Byte (char c) static
Definition at line 3096 of file imgui_draw.cpp.
Referenced by Decode85().
FixRectCornerFlags()
static ImDrawFlags FixRectCornerFlags (ImDrawFlags flags) inline static
Definition at line 1432 of file imgui_draw.cpp.
References IM_ASSERT, ImDrawFlags_RoundCornersAll, and ImDrawFlags_RoundCornersMask_.
Referenced by ImDrawList::AddImageRounded(), and ImDrawList::PathRect().
GetDefaultCompressedFontDataTTF()
static const char * GetDefaultCompressedFontDataTTF (int * out_size) static
Definition at line 6339 of file imgui_draw.cpp.
References proggy_clean_ttf_compressed_data, and proggy_clean_ttf_compressed_size.
Referenced by ImFontAtlas::AddFontDefault().
GetTexDataAsFormat()
static void GetTexDataAsFormat (ImFontAtlas * atlas, ImTextureFormat format, unsigned char ** out_pixels, int * out_width, int * out_height, int * out_bytes_per_pixel) static
Definition at line 2987 of file imgui_draw.cpp.
References ImFontAtlas::Build(), ImTextureData::BytesPerPixel, ImTextureData::Height, ImTextureData::Pixels, ImFontAtlas::TexData, ImFontAtlas::TexDesiredFormat, ImFontAtlas::TexIsBuilt, and ImTextureData::Width.
Referenced by ImFontAtlas::GetTexDataAsAlpha8(), and ImFontAtlas::GetTexDataAsRGBA32().
ImAcos01()
static float ImAcos01 (float x) inline static
Definition at line 5909 of file imgui_draw.cpp.
References IM_PI, and ImAcos.
Referenced by ImGui::RenderRectFilledInRangeH().
ImBezierCubicCalc()
ImVec2 ImBezierCubicCalc (const ImVec2 & p1, const ImVec2 & p2, const ImVec2 & p3, const ImVec2 & p4, float t)
Definition at line 1337 of file imgui_draw.cpp.
References ImVec2::x, and ImVec2::y.
Referenced by ImBezierCubicClosestPoint(), and ImDrawList::PathBezierCubicCurveTo().
ImBezierQuadraticCalc()
ImVec2 ImBezierQuadraticCalc (const ImVec2 & p1, const ImVec2 & p2, const ImVec2 & p3, float t)
Definition at line 1347 of file imgui_draw.cpp.
References ImVec2::x, and ImVec2::y.
Referenced by ImDrawList::PathBezierQuadraticCurveTo().
ImFontAtlas_FontHookRemapCodepoint()
static void ImFontAtlas_FontHookRemapCodepoint (ImFontAtlas * atlas, ImFont * font, ImWchar * c) static
Definition at line 4428 of file imgui_draw.cpp.
References ImGuiStorage::Data, ImGuiStorage::GetInt(), IM_UNUSED, ImFont::RemapPairs, and ImVector< T >::Size.
Referenced by ImFontBaked_BuildLoadGlyph(), and ImFont::IsGlyphInFont().
ImFontAtlasAddDrawListSharedData()
void ImFontAtlasAddDrawListSharedData (ImFontAtlas * atlas, ImDrawListSharedData * data)
Definition at line 3903 of file imgui_draw.cpp.
References ImVector< T >::contains(), ImFontAtlas::DrawListSharedDatas, IM_ASSERT, and ImVector< T >::push_back().
Referenced by ImGui::RegisterFontAtlas().
ImFontAtlasBakedAdd()
ImFontBaked * ImFontAtlasBakedAdd (ImFontAtlas * atlas, ImFont * font, float font_size, float font_rasterizer_density, ImGuiID baked_id)
Definition at line 3783 of file imgui_draw.cpp.
References ImFontBaked::BakedId, ImFontAtlasBuilder::BakedPool, ImFontAtlas::Builder, ImFontLoader::FontBakedInit, ImFontLoader::FontBakedSrcLoaderDataSize, ImFontAtlas::FontLoader, ImFontBaked::FontLoaderDatas, ImFontAtlasBuilder::FrameCount, IM_ALLOC, ImFontAtlasBuildSetupFontBakedBlanks(), IMGUI_DEBUG_LOG_FONT, ImFontBaked::LastUsedFrame, ImFontBaked::OwnerFont, ImStableVector< T, BLOCKSIZE >::push_back(), ImFontBaked::RasterizerDensity, ImFontBaked::Size, and ImFont::Sources.
Referenced by ImFontAtlasBakedGetOrAdd().
ImFontAtlasBakedAddFontGlyph()
ImFontGlyph * ImFontAtlasBakedAddFontGlyph (ImFontAtlas * atlas, ImFontBaked * baked, ImFontConfig * src, const ImFontGlyph * in_glyph)
Definition at line 5129 of file imgui_draw.cpp.
References ImFontGlyph::AdvanceX, ImFontGlyph::Codepoint, ImFontGlyph::Colored, ImFontConfig::GlyphExtraAdvanceX, ImFontConfig::GlyphMaxAdvanceX, ImFontConfig::GlyphMinAdvanceX, ImFontBaked::Glyphs, ImTextureRect::h, IM_ASSERT, IM_ROUND, ImClamp(), ImFontAtlasPackGetRect(), ImFontAtlasRectId_Invalid, ImFontBaked_BuildGrowIndex(), ImTrunc(), ImFontBaked::IndexAdvanceX, ImFontBaked::IndexLookup, ImFontBaked::MetricsTotalSurface, ImFontBaked::OwnerFont, ImFontGlyph::PackId, ImFontConfig::PixelSnapH, ImVector< T >::push_back(), ImVector< T >::Size, ImFontBaked::Size, ImFont::Sources, ImFontAtlas::TexData, ImFontAtlas::TexPixelsUseColors, ImFontAtlas::TexUvScale, ImFontGlyph::U0, ImFontGlyph::U1, ImTextureData::UseColors, ImFont::Used8kPagesMap, ImFontGlyph::V0, ImFontGlyph::V1, ImTextureRect::w, ImVec2::x, ImTextureRect::x, ImFontGlyph::X0, ImFontGlyph::X1, ImVec2::y, and ImTextureRect::y.
Referenced by ImFontAtlas::AddCustomRectFontGlyphForSize(), ImFontAtlasBuildSetupFontBakedBlanks(), ImFontAtlasBuildSetupFontBakedEllipsis(), ImFontAtlasBuildSetupFontBakedFallback(), and ImFontBaked_BuildLoadGlyph().
ImFontAtlasBakedAddFontGlyphAdvancedX()
void ImFontAtlasBakedAddFontGlyphAdvancedX (ImFontAtlas * atlas, ImFontBaked * baked, ImFontConfig * src, ImWchar codepoint, float advance_x)
Definition at line 5183 of file imgui_draw.cpp.
References ImFontConfig::GlyphExtraAdvanceX, ImFontConfig::GlyphMaxAdvanceX, ImFontConfig::GlyphMinAdvanceX, IM_ROUND, IM_UNUSED, ImClamp(), ImFontBaked_BuildGrowIndex(), ImFontBaked::IndexAdvanceX, ImFontBaked::OwnerFont, ImFontConfig::PixelSnapH, ImFontBaked::Size, and ImFont::Sources.
Referenced by ImFontBaked_BuildLoadGlyph().
ImFontAtlasBakedDiscard()
void ImFontAtlasBakedDiscard (ImFontAtlas * atlas, ImFont * font, ImFontBaked * baked)
Definition at line 3843 of file imgui_draw.cpp.
References ImFontAtlasBuilder::BakedDiscardedCount, ImFontBaked::BakedId, ImFontAtlasBuilder::BakedMap, ImFontAtlas::Builder, ImFontBaked::ClearOutputData(), ImFontLoader::FontBakedDestroy, ImFontLoader::FontBakedSrcLoaderDataSize, ImFontAtlas::FontLoader, ImFontBaked::FontLoaderDatas, ImFont::GetDebugName(), ImFontBaked::Glyphs, IM_FREE, ImFontAtlasPackDiscardRect(), ImFontAtlasRectId_Invalid, IMGUI_DEBUG_LOG_FONT, ImFont::LastBaked, ImGuiStorage::SetVoidPtr(), ImFontBaked::Size, ImFont::Sources, and ImFontBaked::WantDestroy.
Referenced by ImFontAtlasBuildDiscardBakes(), and ImFontAtlasFontDiscardBakes().
ImFontAtlasBakedDiscardFontGlyph()
void ImFontAtlasBakedDiscardFontGlyph (ImFontAtlas * atlas, ImFont * font, ImFontBaked * baked, ImFontGlyph * glyph)
Definition at line 3768 of file imgui_draw.cpp.
References ImFontGlyph::Codepoint, ImVector< T >::Data, ImFont::EllipsisChar, ImFontBaked::FallbackAdvanceX, ImFont::FallbackChar, ImFontBaked::Glyphs, IM_ASSERT, IM_FONTGLYPH_INDEX_UNUSED, IM_UNUSED, ImFontAtlasPackDiscardRect(), ImFontAtlasRectId_Invalid, ImFontBaked::IndexAdvanceX, ImFontBaked::IndexLookup, ImFontGlyph::PackId, and ImVector< T >::Size.
Referenced by ImFontAtlas::AddCustomRectFontGlyphForSize().
ImFontAtlasBakedGetClosestMatch()
ImFontBaked * ImFontAtlasBakedGetClosestMatch (ImFontAtlas * atlas, ImFont * font, float font_size, float font_rasterizer_density)
Definition at line 3815 of file imgui_draw.cpp.
References ImFontAtlasBuilder::BakedPool, ImFontAtlas::Builder, ImFontBaked::OwnerFont, ImFontBaked::RasterizerDensity, ImFontBaked::Size, ImStableVector< T, BLOCKSIZE >::Size, and ImFontBaked::WantDestroy.
Referenced by ImFontAtlasBakedGetOrAdd().
ImFontAtlasBakedGetId()
ImGuiID ImFontAtlasBakedGetId (ImGuiID font_id, float baked_size, float rasterizer_density)
Definition at line 5295 of file imgui_draw.cpp.
References ImHashData().
Referenced by ImFontAtlasBakedGetOrAdd().
ImFontAtlasBakedGetOrAdd()
ImFontBaked * ImFontAtlasBakedGetOrAdd (ImFontAtlas * atlas, ImFont * font, float font_size, float font_rasterizer_density)
Definition at line 5328 of file imgui_draw.cpp.
References ImFontBaked::BakedId, ImFontAtlasBuilder::BakedMap, ImFontAtlas::Builder, ImFont::Flags, ImFont::FontId, ImGuiStorage::GetVoidPtrRef(), IM_ASSERT, ImFontAtlasBakedAdd(), ImFontAtlasBakedGetClosestMatch(), ImFontAtlasBakedGetId(), ImFontFlags_LockBakedSizes, ImFontAtlas::Locked, ImFontBaked::OwnerFont, and ImFontBaked::Size.
Referenced by ImFont::GetFontBaked().
ImFontAtlasBakedSetFontGlyphBitmap()
void ImFontAtlasBakedSetFontGlyphBitmap (ImFontAtlas * atlas, ImFontBaked * baked, ImFontConfig * src, ImFontGlyph * glyph, ImTextureRect * r, const unsigned char * src_pixels, ImTextureFormat src_fmt, int src_pitch)
Definition at line 5206 of file imgui_draw.cpp.
References ImTextureData::Format, ImTextureData::GetPitch(), ImTextureData::GetPixelsAt(), ImTextureRect::h, ImTextureData::Height, IM_ASSERT, ImFontAtlasTextureBlockConvert(), ImFontAtlasTextureBlockPostProcess(), ImFontAtlasTextureBlockQueueUpload(), ImFontBaked::OwnerFont, ImFontAtlas::TexData, ImTextureRect::w, ImTextureData::Width, ImTextureRect::x, and ImTextureRect::y.
Referenced by ImGui_ImplFreeType_FontBakedLoadGlyph(), and ImGui_ImplStbTrueType_FontBakedLoadGlyph().
ImFontAtlasBuildAcceptCodepointForSource()
static bool ImFontAtlasBuildAcceptCodepointForSource (ImFontConfig * src, ImWchar codepoint) static
Definition at line 4410 of file imgui_draw.cpp.
References ImFontConfig::GlyphExcludeRanges.
Referenced by ImFontBaked_BuildLoadGlyph().
ImFontAtlasBuildClear()
void ImFontAtlasBuildClear (ImFontAtlas * atlas)
Definition at line 4166 of file imgui_draw.cpp.
References ImFontAtlas::Fonts, ImFontAtlasBuildDestroy(), ImFontAtlasBuildInit(), ImFontAtlasFontSourceAddToFont(), ImFontAtlasFontSourceInit(), ImFontAtlasTextureAdd(), ImFontAtlasTextureGetSizeEstimate(), ImFontAtlas::Sources, ImVec2i::x, and ImVec2i::y.
Referenced by ImFontAtlasBuildMain(), and ImGui::ShowFontAtlas().
ImFontAtlasBuildDestroy()
void ImFontAtlasBuildDestroy (ImFontAtlas * atlas)
Definition at line 4240 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontAtlas::FontLoader, ImFontAtlas::FontLoaderData, ImFontAtlas::Fonts, IM_ASSERT, IM_DELETE(), ImFontAtlasFontDestroyOutput(), and ImFontLoader::LoaderShutdown.
Referenced by ImFontAtlas::ClearFonts(), and ImFontAtlasBuildClear().
ImFontAtlasBuildDiscardBakes()
void ImFontAtlasBuildDiscardBakes (ImFontAtlas * atlas, int unused_frames)
Definition at line 3888 of file imgui_draw.cpp.
References ImFontAtlasBuilder::BakedPool, ImFontAtlas::Builder, ImFont::Flags, ImFontAtlasBuilder::FrameCount, ImFontAtlasBakedDiscard(), ImFontFlags_LockBakedSizes, ImFontBaked::LastUsedFrame, ImFontBaked::OwnerFont, ImStableVector< T, BLOCKSIZE >::Size, and ImFontBaked::WantDestroy.
Referenced by ImFontAtlasTextureCompact(), and ImFontAtlasTextureMakeSpace().
ImFontAtlasBuildGetOversampleFactors()
void ImFontAtlasBuildGetOversampleFactors (ImFontConfig * src, ImFontBaked * baked, int * out_oversample_h, int * out_oversample_v)
Definition at line 3393 of file imgui_draw.cpp.
References ImFontConfig::OversampleH, ImFontConfig::OversampleV, ImFontConfig::PixelSnapH, ImFontConfig::RasterizerDensity, ImFontBaked::RasterizerDensity, and ImFontBaked::Size.
Referenced by ImGui::DebugNodeFont(), and ImGui_ImplStbTrueType_FontBakedLoadGlyph().
ImFontAtlasBuildInit()
void ImFontAtlasBuildInit (ImFontAtlas * atlas)
Definition at line 4196 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontAtlas::FontLoader, ImGuiFreeType::GetFontLoader(), IM_ASSERT, IM_NEW, ImFontAtlasBuildUpdateBasicTexData(), ImFontAtlasBuildUpdateLinesTexData(), ImFontAtlasBuildUpdatePointers(), ImFontAtlasBuildUpdateRendererHasTexturesFromContext(), ImFontAtlasGetFontLoaderForStbTruetype(), ImFontAtlasPackInit(), ImFontAtlasTextureAdd(), ImFontAtlasUpdateDrawListsSharedData(), ImUpperPowerOfTwo(), ImFontLoader::LoaderInit, ImTextureData::Pixels, ImFontAtlas::SetFontLoader(), ImFontAtlas::TexData, ImFontAtlas::TexMinHeight, and ImFontAtlas::TexMinWidth.
Referenced by ImFontAtlas::AddCustomRect(), ImFontAtlas::AddFont(), ImFontAtlasBuildClear(), ImFontAtlasBuildMain(), and ImFontAtlasPackGetRectSafe().
ImFontAtlasBuildLegacyPreloadAllGlyphRanges()
void ImFontAtlasBuildLegacyPreloadAllGlyphRanges (ImFontAtlas * atlas)
Definition at line 3429 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontBaked::FindGlyph(), ImFontAtlas::Fonts, ImFontAtlas::GetGlyphRangesDefault(), IM_UNICODE_CODEPOINT_MAX, and ImFontAtlasBuilder::PreloadedAllGlyphsRanges.
Referenced by ImFontAtlasBuildMain().
ImFontAtlasBuildMain()
void ImFontAtlasBuildMain (ImFontAtlas * atlas)
Definition at line 3373 of file imgui_draw.cpp.
References ImFontAtlas::AddFontDefault(), ImFontAtlas::Builder, ImTextureData::Format, IM_ASSERT, ImFontAtlasBuildClear(), ImFontAtlasBuildInit(), ImFontAtlasBuildLegacyPreloadAllGlyphRanges(), ImFontAtlasBuildUpdateRendererHasTexturesFromContext(), ImFontAtlas::Locked, ImFontAtlas::RendererHasTextures, ImVector< T >::Size, ImFontAtlas::Sources, ImFontAtlas::TexData, ImFontAtlas::TexDesiredFormat, and ImFontAtlas::TexIsBuilt.
Referenced by ImFontAtlas::Build(), ImGui::GetDefaultFont(), and ImFontAtlasUpdateNewFrame().
ImFontAtlasBuildNotifySetFont()
void ImFontAtlasBuildNotifySetFont (ImFontAtlas * atlas, ImFont * old_font, ImFont * new_font)
Definition at line 3203 of file imgui_draw.cpp.
References ImFontAtlas::DrawListSharedDatas, ImGui::GetCurrentContext(), ImGui::SetCurrentContext(), and ImGui::SetCurrentFont().
Referenced by ImFontAtlas::ClearFonts(), and ImFontAtlas::RemoveFont().
ImFontAtlasBuildRenderBitmapFromString()
void ImFontAtlasBuildRenderBitmapFromString (ImFontAtlas * atlas, int x, int y, int w, int h, const char * in_str, char in_marker_char)
Definition at line 3459 of file imgui_draw.cpp.
References ImTextureData::Format, ImTextureData::GetPixelsAt(), IM_ASSERT, IM_COL32_BLACK_TRANS, IM_COL32_WHITE, ImTextureFormat_Alpha8, ImTextureFormat_RGBA32, ImFontAtlas::TexData, and ImTextureData::Width.
Referenced by ImFontAtlasBuildUpdateBasicTexData().
ImFontAtlasBuildSetTexture()
static void ImFontAtlasBuildSetTexture (ImFontAtlas * atlas, ImTextureData * tex) static
Definition at line 3953 of file imgui_draw.cpp.
References ImTextureRef::_TexData, ImTextureData::Height, ImFontAtlasUpdateDrawListsTextures(), ImFontAtlas::TexData, ImFontAtlas::TexRef, ImFontAtlas::TexUvScale, and ImTextureData::Width.
Referenced by ImFontAtlasTextureAdd(), and ImFontAtlasTextureRepack().
ImFontAtlasBuildSetupFontBakedBlanks()
static void ImFontAtlasBuildSetupFontBakedBlanks (ImFontAtlas * atlas, ImFontBaked * baked) static
Definition at line 3715 of file imgui_draw.cpp.
References ImFontGlyph::AdvanceX, ImFontGlyph::Codepoint, ImFontBaked::FindGlyphNoFallback(), IM_TABSIZE, ImFontAtlasBakedAddFontGlyph(), and ImFontGlyph::Visible.
Referenced by ImFontAtlasBakedAdd().
ImFontAtlasBuildSetupFontBakedEllipsis()
static ImFontGlyph * ImFontAtlasBuildSetupFontBakedEllipsis (ImFontAtlas * atlas, ImFontBaked * baked) static
Definition at line 3651 of file imgui_draw.cpp.
References ImFontGlyph::AdvanceX, ImFontGlyph::Codepoint, ImFont::EllipsisChar, ImFontBaked::FindGlyphNoFallback(), ImTextureRect::h, IM_ASSERT, ImFontAtlasBakedAddFontGlyph(), ImFontAtlasPackAddRect(), ImFontAtlasPackGetRect(), ImFontAtlasTextureBlockCopy(), ImFontAtlasTextureBlockQueueUpload(), ImMax(), ImFontBaked::OwnerFont, ImFontGlyph::PackId, ImFontAtlas::TexData, ImFontGlyph::Visible, ImTextureRect::w, ImTextureRect::x, ImFontGlyph::X0, ImFontGlyph::X1, ImTextureRect::y, ImFontGlyph::Y0, and ImFontGlyph::Y1.
Referenced by ImFontBaked_BuildLoadGlyph().
ImFontAtlasBuildSetupFontBakedFallback()
static void ImFontAtlasBuildSetupFontBakedFallback (ImFontBaked * baked) static
Definition at line 3695 of file imgui_draw.cpp.
References ImFontGlyph::AdvanceX, ImFontGlyph::Codepoint, ImFontBaked::FallbackAdvanceX, ImFont::FallbackChar, ImFontBaked::FallbackGlyphIndex, ImFontBaked::FindGlyphNoFallback(), ImFontBaked::Glyphs, IM_ASSERT, IM_ROUND, ImFontAtlasBakedAddFontGlyph(), ImVector< T >::index_from_ptr(), ImFont::OwnerAtlas, ImFontBaked::OwnerFont, and ImFontBaked::Size.
Referenced by ImFontBaked_BuildLoadGlyph().
ImFontAtlasBuildSetupFontLoader()
void ImFontAtlasBuildSetupFontLoader (ImFontAtlas * atlas, const ImFontLoader * font_loader)
Definition at line 3403 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontAtlas::FontLoader, ImFontAtlas::FontLoaderData, ImFontAtlas::FontLoaderName, ImFontAtlas::Fonts, IM_ASSERT, ImFontAtlasFontDestroyOutput(), ImFontAtlasFontInitOutput(), ImFontAtlasFontSourceAddToFont(), ImFontLoader::LoaderInit, ImFontLoader::LoaderShutdown, ImFontAtlas::Locked, and ImFontLoader::Name.
Referenced by ImFontAtlas::SetFontLoader().
ImFontAtlasBuildSetupFontSpecialGlyphs()
void ImFontAtlasBuildSetupFontSpecialGlyphs (ImFontAtlas * atlas, ImFont * font, ImFontConfig * src)
Definition at line 3735 of file imgui_draw.cpp.
References ImVector< T >::contains(), ImFont::EllipsisAutoBake, ImFontConfig::EllipsisChar, ImFont::EllipsisChar, ImFont::FallbackChar, IM_ASSERT, IM_UNICODE_CODEPOINT_INVALID, IM_UNUSED, ImFont::IsGlyphInFont(), and ImFont::Sources.
Referenced by ImFontAtlasFontSourceAddToFont().
ImFontAtlasBuildUpdateBasicTexData()
static void ImFontAtlasBuildUpdateBasicTexData (ImFontAtlas * atlas) static
Definition at line 3486 of file imgui_draw.cpp.
References ImFontAtlas::AddCustomRect(), ImFontAtlas::Builder, ImFontAtlas::Flags, FONT_ATLAS_DEFAULT_TEX_DATA_H, FONT_ATLAS_DEFAULT_TEX_DATA_PIXELS, FONT_ATLAS_DEFAULT_TEX_DATA_W, ImFontAtlas::GetCustomRect(), IM_ASSERT, ImFontAtlasBuildRenderBitmapFromString(), ImFontAtlasFlags_NoMouseCursors, ImFontAtlasRectId_Invalid, ImFontAtlasBuilder::PackIdMouseCursors, ImFontAtlas::TexUvScale, ImFontAtlas::TexUvWhitePixel, ImVec2::x, ImFontAtlasRect::x, ImVec2i::x, ImVec2::y, ImFontAtlasRect::y, and ImVec2i::y.
Referenced by ImFontAtlasBuildInit(), and ImFontAtlasTextureRepack().
ImFontAtlasBuildUpdateLinesTexData()
static void ImFontAtlasBuildUpdateLinesTexData (ImFontAtlas * atlas) static
Definition at line 3520 of file imgui_draw.cpp.
References ImFontAtlas::AddCustomRect(), ImFontAtlas::Builder, ImFontAtlas::Flags, ImTextureData::Format, ImFontAtlas::GetCustomRect(), ImTextureData::GetPixelsAt(), ImFontAtlasRect::h, IM_ASSERT, IM_COL32, IM_COL32_WHITE, IM_DRAWLIST_TEX_LINES_WIDTH_MAX, ImFontAtlasFlags_NoBakedLines, ImFontAtlasRectId_Invalid, ImTextureFormat_Alpha8, ImTextureFormat_RGBA32, ImFontAtlasBuilder::PackIdLinesTexData, ImFontAtlas::TexData, ImFontAtlas::TexUvLines, ImFontAtlas::TexUvScale, ImFontAtlasRect::w, ImVec2::x, ImFontAtlasRect::x, ImVec2i::x, ImVec2::y, ImFontAtlasRect::y, and ImVec2i::y.
Referenced by ImFontAtlasBuildInit(), and ImFontAtlasTextureRepack().
ImFontAtlasBuildUpdatePointers()
void ImFontAtlasBuildUpdatePointers (ImFontAtlas * atlas)
Definition at line 3450 of file imgui_draw.cpp.
References ImFontAtlas::Fonts, and ImFontAtlas::Sources.
Referenced by ImFontAtlas::AddFont(), ImFontAtlasBuildInit(), and ImFontAtlas::RemoveFont().
ImFontAtlasBuildUpdateRendererHasTexturesFromContext()
static void ImFontAtlasBuildUpdateRendererHasTexturesFromContext (ImFontAtlas * atlas) static
Definition at line 2727 of file imgui_draw.cpp.
References ImFontAtlas::DrawListSharedDatas, ImGuiBackendFlags_RendererHasTextures, and ImFontAtlas::RendererHasTextures.
Referenced by ImFontAtlasBuildInit(), and ImFontAtlasBuildMain().
ImFontAtlasDebugLogTextureRequests()
void ImFontAtlasDebugLogTextureRequests (ImFontAtlas * atlas)
Definition at line 4531 of file imgui_draw.cpp.
References ImGuiIO::BackendFlags, ImTextureData::BackendUserData, ImGui::DebugTextureIDToU64(), GImGui, ImTextureData::Height, IM_ASSERT, IM_PRIX64, IM_UNUSED, IMGUI_DEBUG_LOG_FONT, ImGuiBackendFlags_RendererHasTextures, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImGuiContext::IO, ImVector< T >::Size, ImTextureData::Status, ImTextureData::TexID, ImFontAtlas::TexList, ImTextureData::UniqueID, ImTextureData::Updates, and ImTextureData::Width.
Referenced by ImGui::Render().
ImFontAtlasFontDestroyOutput()
void ImFontAtlasFontDestroyOutput (ImFontAtlas * atlas, ImFont * font)
Definition at line 3598 of file imgui_draw.cpp.
References ImFont::ClearOutputData(), ImFontAtlas::FontLoader, ImFontLoader::FontSrcDestroy, and ImFont::Sources.
Referenced by ImFontAtlas::ClearInputData(), ImGui::DebugNodeFont(), ImFontAtlasBuildDestroy(), ImFontAtlasBuildSetupFontLoader(), ImFontAtlas::RemoveFont(), and ImGui::ShowFontAtlas().
ImFontAtlasFontDestroySourceData()
void ImFontAtlasFontDestroySourceData (ImFontAtlas * atlas, ImFontConfig * src)
Definition at line 3632 of file imgui_draw.cpp.
References ImFontConfig::FontData, ImFontConfig::FontDataOwnedByAtlas, ImFontConfig::GlyphExcludeRanges, IM_FREE, and IM_UNUSED.
Referenced by ImFontAtlas::AddFont(), ImFontAtlas::ClearInputData(), and ImFontAtlas::RemoveFont().
ImFontAtlasFontDiscardBakes()
void ImFontAtlasFontDiscardBakes (ImFontAtlas * atlas, ImFont * font, int unused_frames)
Definition at line 3873 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontAtlasBuilder::FrameCount, ImFontAtlasBakedDiscard(), ImFontBaked::LastUsedFrame, ImFontBaked::OwnerFont, and ImFontBaked::WantDestroy.
Referenced by ImFont::ClearOutputData(), and ImGui::DebugNodeFont().
ImFontAtlasFontInitOutput()
bool ImFontAtlasFontInitOutput (ImFontAtlas * atlas, ImFont * font)
Definition at line 3587 of file imgui_draw.cpp.
References IM_ASSERT, ImFontAtlasFontSourceInit(), and ImFont::Sources.
Referenced by ImGui::DebugNodeFont(), ImFontAtlasBuildSetupFontLoader(), and ImGui::ShowFontAtlas().
ImFontAtlasFontSourceAddToFont()
void ImFontAtlasFontSourceAddToFont (ImFontAtlas * atlas, ImFont * font, ImFontConfig * src)
Definition at line 3619 of file imgui_draw.cpp.
References ImFont::ClearOutputData(), IM_ASSERT, ImFontAtlasBuildSetupFontSpecialGlyphs(), ImFontConfig::MergeMode, ImFont::OwnerAtlas, ImFont::Sources, and ImFontAtlas::TexIsBuilt.
Referenced by ImFontAtlas::AddFont(), ImFontAtlasBuildClear(), and ImFontAtlasBuildSetupFontLoader().
ImFontAtlasFontSourceInit()
bool ImFontAtlasFontSourceInit (ImFontAtlas * atlas, ImFontConfig * src)
Definition at line 3611 of file imgui_draw.cpp.
References ImFontConfig::FontLoader, ImFontAtlas::FontLoader, and ImFontLoader::FontSrcInit.
Referenced by ImFontAtlas::AddFont(), ImFontAtlasBuildClear(), and ImFontAtlasFontInitOutput().
ImFontAtlasGetFontLoaderForStbTruetype()
const ImFontLoader * ImFontAtlasGetFontLoaderForStbTruetype ()
Definition at line 4737 of file imgui_draw.cpp.
References ImFontLoader::FontBakedDestroy, ImFontLoader::FontBakedInit, ImFontLoader::FontBakedLoadGlyph, ImFontLoader::FontSrcContainsGlyph, ImFontLoader::FontSrcDestroy, ImFontLoader::FontSrcInit, ImGui_ImplStbTrueType_FontBakedInit(), ImGui_ImplStbTrueType_FontBakedLoadGlyph(), ImGui_ImplStbTrueType_FontSrcContainsGlyph(), ImGui_ImplStbTrueType_FontSrcDestroy(), ImGui_ImplStbTrueType_FontSrcInit(), and ImFontLoader::Name.
Referenced by ImFontAtlasBuildInit(), and ImGui::ShowFontAtlas().
ImFontAtlasGetMouseCursorTexData()
bool ImFontAtlasGetMouseCursorTexData (ImFontAtlas * atlas, ImGuiMouseCursor cursor_type, ImVec2 * out_offset, ImVec2 * out_size, ImVec2 out_uv_border[2], ImVec2 out_uv_fill[2])
Definition at line 3352 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontAtlas::Flags, FONT_ATLAS_DEFAULT_TEX_CURSOR_DATA, FONT_ATLAS_DEFAULT_TEX_DATA_W, ImFontAtlasFlags_NoMouseCursors, ImFontAtlasPackGetRect(), ImGuiMouseCursor_COUNT, ImFontAtlasBuilder::PackIdMouseCursors, ImFontAtlas::TexUvScale, ImVec2::x, ImTextureRect::x, and ImTextureRect::y.
Referenced by ImGui::RenderMouseCursor().
ImFontAtlasPackAddRect()
ImFontAtlasRectId ImFontAtlasPackAddRect (ImFontAtlas * atlas, int w, int h, ImFontAtlasRectEntry * overwrite_entry)
Definition at line 4330 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImTextureRect::h, stbrp_rect::h, IM_ASSERT, ImFontAtlasPackAllocRectEntry(), ImFontAtlasPackReuseRectEntry(), ImFontAtlasRectId_Invalid, ImFontAtlasTextureMakeSpace(), IMGUI_DEBUG_LOG_FONT, ImMax(), ImFontAtlasBuilder::LockDisableResize, ImFontAtlasBuilder::MaxRectBounds, ImFontAtlasBuilder::MaxRectSize, ImFontAtlasBuilder::PackContext, ImVector< T >::push_back(), ImFontAtlasBuilder::Rects, ImFontAtlasBuilder::RectsPackedCount, ImFontAtlasBuilder::RectsPackedSurface, ImVector< T >::Size, stbrp_pack_rects(), ImFontAtlas::TexGlyphPadding, ImTextureRect::w, stbrp_rect::w, stbrp_rect::was_packed, ImTextureRect::x, ImVec2i::x, stbrp_rect::x, ImTextureRect::y, ImVec2i::y, and stbrp_rect::y.
Referenced by ImFontAtlas::AddCustomRect(), ImFontAtlas::AddCustomRectFontGlyphForSize(), ImFontAtlasBuildSetupFontBakedEllipsis(), ImFontAtlasTextureRepack(), ImGui_ImplFreeType_FontBakedLoadGlyph(), and ImGui_ImplStbTrueType_FontBakedLoadGlyph().
ImFontAtlasPackAllocRectEntry()
static ImFontAtlasRectId ImFontAtlasPackAllocRectEntry (ImFontAtlas * atlas, int rect_idx) static
Definition at line 4269 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontAtlasRectEntry::Generation, IM_ASSERT, ImFontAtlasRectId_Make(), ImFontAtlasRectEntry::IsUsed, ImFontAtlasBuilder::RectsIndex, ImFontAtlasBuilder::RectsIndexFreeListStart, ImVector< T >::resize(), ImVector< T >::Size, and ImFontAtlasRectEntry::TargetIndex.
Referenced by ImFontAtlasPackAddRect().
ImFontAtlasPackDiscardRect()
void ImFontAtlasPackDiscardRect (ImFontAtlas * atlas, ImFontAtlasRectId id)
Definition at line 4303 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontAtlasRectEntry::Generation, ImTextureRect::h, IM_ASSERT, ImFontAtlasPackGetRect(), ImFontAtlasRectId_GetIndex(), ImFontAtlasRectId_Invalid, ImFontAtlasRectEntry::IsUsed, ImFontAtlasBuilder::RectsDiscardedCount, ImFontAtlasBuilder::RectsDiscardedSurface, ImFontAtlasBuilder::RectsIndex, ImFontAtlasBuilder::RectsIndexFreeListStart, ImFontAtlasRectEntry::TargetIndex, ImFontAtlas::TexGlyphPadding, and ImTextureRect::w.
Referenced by ImFontAtlasBakedDiscard(), ImFontAtlasBakedDiscardFontGlyph(), and ImFontAtlas::RemoveCustomRect().
ImFontAtlasPackGetRect()
ImTextureRect * ImFontAtlasPackGetRect (ImFontAtlas * atlas, ImFontAtlasRectId id)
Definition at line 4378 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontAtlasRectEntry::Generation, IM_ASSERT, ImFontAtlasRectId_GetGeneration(), ImFontAtlasRectId_GetIndex(), ImFontAtlasRectId_Invalid, ImFontAtlasRectEntry::IsUsed, ImFontAtlasBuilder::Rects, ImFontAtlasBuilder::RectsIndex, and ImFontAtlasRectEntry::TargetIndex.
Referenced by ImFontAtlas::AddCustomRect(), ImFontAtlas::AddCustomRectFontGlyphForSize(), ImGui::DebugNodeFontGlyph(), ImFontAtlasBakedAddFontGlyph(), ImFontAtlasBuildSetupFontBakedEllipsis(), ImFontAtlasGetMouseCursorTexData(), ImFontAtlasPackDiscardRect(), ImFontAtlasTextureRepack(), ImGui_ImplFreeType_FontBakedLoadGlyph(), and ImGui_ImplStbTrueType_FontBakedLoadGlyph().
ImFontAtlasPackGetRectSafe()
ImTextureRect * ImFontAtlasPackGetRectSafe (ImFontAtlas * atlas, ImFontAtlasRectId id)
Definition at line 4391 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontAtlasRectEntry::Generation, IM_MSVC_WARNING_SUPPRESS, ImFontAtlasBuildInit(), ImFontAtlasRectId_GetGeneration(), ImFontAtlasRectId_GetIndex(), ImFontAtlasRectId_Invalid, ImFontAtlasRectEntry::IsUsed, ImFontAtlasBuilder::Rects, ImFontAtlasBuilder::RectsIndex, ImVector< T >::Size, and ImFontAtlasRectEntry::TargetIndex.
Referenced by ImFontAtlas::GetCustomRect(), and ImFontAtlas::RemoveCustomRect().
ImFontAtlasPackInit()
void ImFontAtlasPackInit (ImFontAtlas * atlas)
Definition at line 4253 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImTextureData::Height, IM_STATIC_ASSERT, ImFontAtlasBuilder::MaxRectBounds, ImFontAtlasBuilder::MaxRectSize, ImFontAtlasBuilder::PackContext, ImFontAtlasBuilder::PackNodes, ImFontAtlasBuilder::RectsPackedCount, ImFontAtlasBuilder::RectsPackedSurface, stbrp_init_target(), ImFontAtlas::TexData, and ImTextureData::Width.
Referenced by ImFontAtlasBuildInit(), and ImFontAtlasTextureRepack().
ImFontAtlasPackReuseRectEntry()
static ImFontAtlasRectId ImFontAtlasPackReuseRectEntry (ImFontAtlas * atlas, ImFontAtlasRectEntry * index_entry) static
Definition at line 4294 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontAtlasRectEntry::Generation, IM_ASSERT, ImFontAtlasRectId_Make(), ImVector< T >::index_from_ptr(), ImFontAtlasRectEntry::IsUsed, ImFontAtlasBuilder::Rects, ImFontAtlasBuilder::RectsIndex, ImVector< T >::Size, and ImFontAtlasRectEntry::TargetIndex.
Referenced by ImFontAtlasPackAddRect().
ImFontAtlasRemoveDrawListSharedData()
void ImFontAtlasRemoveDrawListSharedData (ImFontAtlas * atlas, ImDrawListSharedData * data)
Definition at line 3909 of file imgui_draw.cpp.
References ImVector< T >::contains(), ImFontAtlas::DrawListSharedDatas, ImVector< T >::find_erase(), and IM_ASSERT.
Referenced by ImGui::UnregisterFontAtlas().
ImFontAtlasTextureAdd()
ImTextureData * ImFontAtlasTextureAdd (ImFontAtlas * atlas, int w, int h)
Definition at line 3964 of file imgui_draw.cpp.
References ImTextureData::Create(), IM_ASSERT, IM_NEW, ImFontAtlasBuildSetTexture(), ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantUpdates, ImVector< T >::push_back(), ImTextureData::Status, ImFontAtlas::TexData, ImFontAtlas::TexDesiredFormat, ImFontAtlas::TexIsBuilt, ImFontAtlas::TexList, ImFontAtlas::TexNextUniqueID, ImTextureData::UniqueID, and ImTextureData::WantDestroyNextFrame.
Referenced by ImFontAtlasBuildClear(), ImFontAtlasBuildInit(), and ImFontAtlasTextureRepack().
ImFontAtlasTextureBlockConvert()
void ImFontAtlasTextureBlockConvert (const unsigned char * src_pixels, ImTextureFormat src_fmt, int src_pitch, unsigned char * dst_pixels, ImTextureFormat dst_fmt, int dst_pitch, int w, int h)
Definition at line 2847 of file imgui_draw.cpp.
References IM_ASSERT, IM_COL32, IM_COL32_A_SHIFT, ImTextureDataGetFormatBytesPerPixel(), ImTextureFormat_Alpha8, and ImTextureFormat_RGBA32.
Referenced by ImFontAtlasBakedSetFontGlyphBitmap().
ImFontAtlasTextureBlockCopy()
void ImFontAtlasTextureBlockCopy (ImTextureData * src_tex, int src_x, int src_y, ImTextureData * dst_tex, int dst_x, int dst_y, int w, int h)
Definition at line 2946 of file imgui_draw.cpp.
References ImTextureData::BytesPerPixel, ImTextureData::Format, ImTextureData::GetPixelsAt(), IM_ASSERT, and ImTextureData::Pixels.
Referenced by ImFontAtlasBuildSetupFontBakedEllipsis(), and ImFontAtlasTextureRepack().
ImFontAtlasTextureBlockFill()
void ImFontAtlasTextureBlockFill (ImTextureData * dst_tex, int dst_x, int dst_y, int w, int h, ImU32 col)
Definition at line 2926 of file imgui_draw.cpp.
References ImTextureData::Format, ImTextureData::GetPixelsAt(), IM_COL32_A_SHIFT, and ImTextureFormat_Alpha8.
ImFontAtlasTextureBlockPostProcess()
void ImFontAtlasTextureBlockPostProcess (ImFontAtlasPostProcessData * data)
Definition at line 2884 of file imgui_draw.cpp.
References ImFontAtlasTextureBlockPostProcessMultiply().
Referenced by ImFontAtlasBakedSetFontGlyphBitmap().
ImFontAtlasTextureBlockPostProcessMultiply()
void ImFontAtlasTextureBlockPostProcessMultiply (ImFontAtlasPostProcessData * data, float multiply_factor)
Definition at line 2891 of file imgui_draw.cpp.
References IM_ASSERT, IM_COL32, IM_COL32_A_SHIFT, IM_COL32_B_SHIFT, IM_COL32_G_SHIFT, IM_COL32_R_SHIFT, ImMin(), ImTextureFormat_Alpha8, and ImTextureFormat_RGBA32.
Referenced by ImFontAtlasTextureBlockPostProcess().
ImFontAtlasTextureBlockQueueUpload()
void ImFontAtlasTextureBlockQueueUpload (ImFontAtlas * atlas, ImTextureData * tex, int x, int y, int w, int h)
Definition at line 2959 of file imgui_draw.cpp.
References ImTextureRect::h, IM_ASSERT, IM_UNUSED, ImMax(), ImMin(), ImTextureStatus_Destroyed, ImTextureStatus_OK, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImVector< T >::push_back(), ImTextureData::Status, ImFontAtlas::TexIsBuilt, ImTextureData::UpdateRect, ImTextureData::Updates, ImTextureData::UsedRect, ImTextureRect::w, ImTextureRect::x, and ImTextureRect::y.
Referenced by ImFontAtlas::AddCustomRect(), ImFontAtlas::AddCustomRectFontGlyphForSize(), ImFontAtlasBakedSetFontGlyphBitmap(), and ImFontAtlasBuildSetupFontBakedEllipsis().
ImFontAtlasTextureCompact()
void ImFontAtlasTextureCompact (ImFontAtlas * atlas)
Definition at line 4181 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImTextureData::Height, ImFontAtlasBuildDiscardBakes(), ImFontAtlasTextureGetSizeEstimate(), ImFontAtlasTextureRepack(), ImFontAtlasBuilder::RectsDiscardedCount, ImFontAtlas::TexData, ImTextureData::Width, ImVec2i::x, and ImVec2i::y.
Referenced by ImFontAtlas::CompactCache().
ImFontAtlasTextureGetSizeEstimate()
ImVec2i ImFontAtlasTextureGetSizeEstimate (ImFontAtlas * atlas)
Definition at line 4131 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontAtlas::Flags, IM_ASSERT, ImFontAtlasFlags_NoPowerOfTwoHeight, ImIsPowerOfTwo(), ImMax(), ImTextureStatus_WantDestroy, ImUpperPowerOfTwo(), ImFontAtlasBuilder::MaxRectSize, ImFontAtlasBuilder::RectsDiscardedSurface, ImFontAtlasBuilder::RectsPackedSurface, ImTextureData::Status, ImFontAtlas::TexData, ImFontAtlas::TexMinHeight, ImFontAtlas::TexMinWidth, ImVec2i::x, and ImVec2i::y.
Referenced by ImFontAtlasBuildClear(), and ImFontAtlasTextureCompact().
ImFontAtlasTextureGrow()
void ImFontAtlasTextureGrow (ImFontAtlas * atlas, int old_tex_w, int old_tex_h)
Definition at line 4085 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImTextureData::Height, IM_ASSERT, ImClamp(), ImFontAtlasTextureRepack(), ImIsPowerOfTwo(), ImMax(), ImUpperPowerOfTwo(), ImFontAtlasBuilder::MaxRectSize, ImFontAtlas::TexData, ImFontAtlas::TexGlyphPadding, ImFontAtlas::TexMaxHeight, ImFontAtlas::TexMaxWidth, ImFontAtlas::TexMinHeight, ImFontAtlas::TexMinWidth, ImTextureData::Width, ImVec2i::x, and ImVec2i::y.
Referenced by ImFontAtlasTextureMakeSpace(), ImFontAtlasTextureRepack(), and ImGui::ShowFontAtlas().
ImFontAtlasTextureMakeSpace()
void ImFontAtlasTextureMakeSpace (ImFontAtlas * atlas)
Definition at line 4117 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImTextureData::Height, ImFontAtlasBuildDiscardBakes(), ImFontAtlasTextureGrow(), ImFontAtlasTextureRepack(), ImFontAtlasBuilder::RectsDiscardedSurface, ImFontAtlasBuilder::RectsPackedSurface, ImFontAtlas::TexData, and ImTextureData::Width.
Referenced by ImFontAtlasPackAddRect().
ImFontAtlasTextureRepack()
void ImFontAtlasTextureRepack (ImFontAtlas * atlas, int w, int h)
Definition at line 4013 of file imgui_draw.cpp.
References ImFontAtlasBuilder::BakedPool, ImFontAtlas::Builder, ImTextureRect::h, ImTextureData::Height, IM_ASSERT, ImFontAtlasBuildSetTexture(), ImFontAtlasBuildUpdateBasicTexData(), ImFontAtlasBuildUpdateLinesTexData(), ImFontAtlasPackAddRect(), ImFontAtlasPackGetRect(), ImFontAtlasPackInit(), ImFontAtlasRectId_GetIndex(), ImFontAtlasRectId_Invalid, ImFontAtlasTextureAdd(), ImFontAtlasTextureBlockCopy(), ImFontAtlasTextureGrow(), ImFontAtlasUpdateDrawListsSharedData(), IMGUI_DEBUG_LOG_FONT, ImVector< T >::index_from_ptr(), ImFontAtlasBuilder::LockDisableResize, ImFontAtlasBuilder::Rects, ImFontAtlasBuilder::RectsDiscardedCount, ImFontAtlasBuilder::RectsDiscardedSurface, ImFontAtlasBuilder::RectsIndex, ImVector< T >::Size, ImStableVector< T, BLOCKSIZE >::Size, ImVector< T >::swap(), ImFontAtlas::TexData, ImFontAtlas::TexUvScale, ImTextureData::UniqueID, ImTextureData::UseColors, ImTextureRect::w, ImTextureData::WantDestroyNextFrame, ImTextureData::Width, ImVec2::x, ImTextureRect::x, ImVec2::y, and ImTextureRect::y.
Referenced by ImFontAtlasTextureCompact(), ImFontAtlasTextureGrow(), and ImFontAtlasTextureMakeSpace().
ImFontAtlasUpdateDrawListsSharedData()
void ImFontAtlasUpdateDrawListsSharedData (ImFontAtlas * atlas)
Definition at line 3942 of file imgui_draw.cpp.
References ImFontAtlas::DrawListSharedDatas, ImFontAtlas::TexUvLines, and ImFontAtlas::TexUvWhitePixel.
Referenced by ImFontAtlasBuildInit(), ImFontAtlasTextureRepack(), and ImGui::SetCurrentFont().
ImFontAtlasUpdateDrawListsTextures()
void ImFontAtlasUpdateDrawListsTextures (ImFontAtlas * atlas, ImTextureRef old_tex, ImTextureRef new_tex)
Definition at line 3916 of file imgui_draw.cpp.
References ImDrawList::_CmdHeader, ImDrawList::_SetTexture(), ImDrawList::_TextureStack, ImDrawList::CmdBuffer, ImFontAtlas::DrawListSharedDatas, ImVector< T >::Size, and ImDrawCmdHeader::TexRef.
Referenced by ImFontAtlasBuildSetTexture().
ImFontAtlasUpdateNewFrame()
void ImFontAtlasUpdateNewFrame (ImFontAtlas * atlas, int frame_count, bool renderer_has_textures)
Definition at line 2746 of file imgui_draw.cpp.
References ImTextureData::BackendUserData, ImFontAtlasBuilder::BakedDiscardedCount, ImFontBaked::BakedId, ImFontAtlasBuilder::BakedMap, ImFontAtlasBuilder::BakedPool, ImVector< T >::begin(), ImFontAtlas::Builder, ImTextureData::DestroyPixels(), ImVector< T >::erase(), ImFontAtlas::Fonts, ImFontAtlasBuilder::FrameCount, ImTextureRect::h, IM_ASSERT, IM_ASSERT_USER_ERROR, IM_DELETE(), ImFontAtlasBuildMain(), ImTextureID_Invalid, ImTextureStatus_Destroyed, ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImFontAtlasBuilder::PreloadedAllGlyphsRanges, ImFontAtlas::RendererHasTextures, ImVector< T >::resize(), ImGuiStorage::SetVoidPtr(), ImVector< T >::Size, ImStableVector< T, BLOCKSIZE >::Size, ImTextureData::Status, ImFontAtlas::TexData, ImTextureData::TexID, ImFontAtlas::TexIsBuilt, ImFontAtlas::TexList, ImTextureData::UnusedFrames, ImTextureData::UpdateRect, ImTextureData::Updates, ImTextureRect::w, ImFontBaked::WantDestroy, ImTextureData::WantDestroyNextFrame, ImTextureRect::x, and ImTextureRect::y.
Referenced by ImGui::UpdateTexturesNewFrame().
ImFontBaked_BuildGrowIndex()
static void ImFontBaked_BuildGrowIndex (ImFontBaked * baked, int new_size) static
Definition at line 4419 of file imgui_draw.cpp.
References IM_ASSERT, IM_FONTGLYPH_INDEX_UNUSED, ImFontBaked::IndexAdvanceX, ImFontBaked::IndexLookup, ImVector< T >::resize(), and ImVector< T >::Size.
Referenced by ImFontAtlasBakedAddFontGlyph(), ImFontAtlasBakedAddFontGlyphAdvancedX(), and ImFontBaked_BuildLoadGlyph().
ImFontBaked_BuildLoadGlyph()
static ImFontGlyph * ImFontBaked_BuildLoadGlyph (ImFontBaked * baked, ImWchar codepoint, float * only_load_advance_x) static
Definition at line 4435 of file imgui_draw.cpp.
References ImFontGlyph::Codepoint, ImFont::EllipsisAutoBake, ImFont::EllipsisChar, ImFontBaked::FallbackAdvanceX, ImFontBaked::FallbackGlyphIndex, ImFont::Flags, ImFontLoader::FontBakedLoadGlyph, ImFontLoader::FontBakedSrcLoaderDataSize, ImFontAtlas::FontLoader, ImFontBaked::FontLoaderDatas, IM_FONTGLYPH_INDEX_NOT_FOUND, ImFontAtlas_FontHookRemapCodepoint(), ImFontAtlasBakedAddFontGlyph(), ImFontAtlasBakedAddFontGlyphAdvancedX(), ImFontAtlasBuildAcceptCodepointForSource(), ImFontAtlasBuildSetupFontBakedEllipsis(), ImFontAtlasBuildSetupFontBakedFallback(), ImFontBaked_BuildGrowIndex(), ImFontFlags_NoLoadGlyphs, ImFontBaked::IndexAdvanceX, ImFontBaked::IndexLookup, ImFontBaked::LoadNoFallback, ImFontAtlas::Locked, ImFont::OwnerAtlas, ImFontBaked::OwnerFont, ImFontGlyph::SourceIdx, and ImFont::Sources.
Referenced by ImFontBaked::FindGlyph(), ImFontBaked::FindGlyphNoFallback(), and ImFontBaked_BuildLoadGlyphAdvanceX().
ImFontBaked_BuildLoadGlyphAdvanceX()
static float ImFontBaked_BuildLoadGlyphAdvanceX (ImFontBaked * baked, ImWchar codepoint) static
Definition at line 4506 of file imgui_draw.cpp.
References ImFontGlyph::AdvanceX, ImFontBaked::FallbackAdvanceX, ImFontBaked_BuildLoadGlyph(), IMGUI_FONT_SIZE_THRESHOLD_FOR_LOADADVANCEXONLYMODE, ImFontBaked::LoadNoRenderOnLayout, and ImFontBaked::Size.
Referenced by BuildLoadGlyphGetAdvanceOrFallback(), and ImFontBaked::GetCharAdvance().
ImFontCalcTextSizeEx()
ImVec2 ImFontCalcTextSizeEx (ImFont * font, float size, float max_width, float wrap_width, const char * text_begin, const char * text_end_display, const char * text_end, const char ** out_remaining, ImVec2 * out_offset, ImDrawTextFlags flags)
Definition at line 5485 of file imgui_draw.cpp.
References BuildLoadGlyphGetAdvanceOrFallback(), ImVector< T >::Data, ImFont::GetFontBaked(), ImDrawTextFlags_StopOnNewLine, ImFontCalcWordWrapPositionEx(), ImMax(), ImStrlen, ImTextCalcWordWrapNextLineStart(), ImTextCharFromUtf8(), ImFontBaked::IndexAdvanceX, ImVector< T >::Size, ImFontBaked::Size, ImVec2::x, and ImVec2::y.
Referenced by ImFont::CalcTextSizeA(), and InputTextCalcTextSize().
ImFontCalcWordWrapPositionEx()
const char * ImFontCalcWordWrapPositionEx (ImFont * font, float size, const char * text, const char * text_end, float wrap_width, ImDrawTextFlags flags)
Definition at line 5377 of file imgui_draw.cpp.
References BuildLoadGlyphGetAdvanceOrFallback(), ImVector< T >::Data, ImFont::GetFontBaked(), IM_ASSERT, ImCharIsBlankW(), ImDrawTextFlags_WrapKeepBlanks, ImTextCharFromUtf8(), ImTextCountUtf8BytesFromChar(), ImFontBaked::IndexAdvanceX, ImVector< T >::Size, and ImFontBaked::Size.
Referenced by ImFont::CalcWordWrapPosition(), ImFontCalcTextSizeEx(), InputTextLineIndexBuild(), ImFont::RenderText(), ImStb::STB_TEXTEDIT_MOVELINEEND_IMPL(), and ImStb::STB_TEXTEDIT_MOVELINESTART_IMPL().
ImGui_ImplStbTrueType_FontBakedInit()
static bool ImGui_ImplStbTrueType_FontBakedInit (ImFontAtlas * atlas, ImFontConfig * src, ImFontBaked * baked, void *) static
Definition at line 4627 of file imgui_draw.cpp.
References ImFontBaked::Ascent, ImFontBaked::Descent, ImGui_ImplStbTrueType_FontSrcData::FontInfo, ImFontConfig::FontLoaderData, IM_UNUSED, ImCeil, ImFloor(), ImFontConfig::MergeMode, ImGui_ImplStbTrueType_FontSrcData::ScaleFactor, ImFontBaked::Size, and stbtt_GetFontVMetrics().
Referenced by ImFontAtlasGetFontLoaderForStbTruetype().
ImGui_ImplStbTrueType_FontBakedLoadGlyph()
static bool ImGui_ImplStbTrueType_FontBakedLoadGlyph (ImFontAtlas * atlas, ImFontConfig * src, ImFontBaked * baked, void * , ImWchar codepoint, ImFontGlyph * out_glyph, float * out_advance_x) static
Definition at line 4645 of file imgui_draw.cpp.
References ImFontGlyph::AdvanceX, ImFontBaked::Ascent, ImFontAtlas::Builder, ImFontGlyph::Codepoint, ImVector< T >::Data, ImGui_ImplStbTrueType_FontSrcData::FontInfo, ImFontConfig::FontLoaderData, ImFontConfig::GlyphOffset, ImTextureRect::h, IM_ASSERT, IM_ROUND, ImFontAtlasBakedSetFontGlyphBitmap(), ImFontAtlasBuildGetOversampleFactors(), ImFontAtlasPackAddRect(), ImFontAtlasPackGetRect(), ImFontAtlasRectId_Invalid, ImTextureFormat_Alpha8, ImFontBaked::OwnerFont, ImFontGlyph::PackId, ImFontConfig::PixelSnapH, ImFontConfig::PixelSnapV, ImFontConfig::RasterizerDensity, ImFontBaked::RasterizerDensity, ImVector< T >::resize(), ImGui_ImplStbTrueType_FontSrcData::ScaleFactor, ImFontBaked::Size, ImFont::Sources, stbtt_FindGlyphIndex(), stbtt_GetGlyphBitmapBox(), stbtt_GetGlyphBitmapBoxSubpixel(), stbtt_GetGlyphHMetrics(), stbtt_MakeGlyphBitmapSubpixelPrefilter(), ImFontAtlasBuilder::TempBuffer, ImFontGlyph::Visible, ImTextureRect::w, ImVec2::x, ImFontGlyph::X0, ImFontGlyph::X1, ImVec2::y, ImFontGlyph::Y0, and ImFontGlyph::Y1.
Referenced by ImFontAtlasGetFontLoaderForStbTruetype().
ImGui_ImplStbTrueType_FontSrcContainsGlyph()
static bool ImGui_ImplStbTrueType_FontSrcContainsGlyph (ImFontAtlas * atlas, ImFontConfig * src, ImWchar codepoint) static
Definition at line 4616 of file imgui_draw.cpp.
References ImGui_ImplStbTrueType_FontSrcData::FontInfo, ImFontConfig::FontLoaderData, IM_ASSERT, IM_UNUSED, and stbtt_FindGlyphIndex().
Referenced by ImFontAtlasGetFontLoaderForStbTruetype().
ImGui_ImplStbTrueType_FontSrcDestroy()
static void ImGui_ImplStbTrueType_FontSrcDestroy (ImFontAtlas * atlas, ImFontConfig * src) static
Definition at line 4608 of file imgui_draw.cpp.
References ImFontConfig::FontLoaderData, IM_DELETE(), and IM_UNUSED.
Referenced by ImFontAtlasGetFontLoaderForStbTruetype().
ImGui_ImplStbTrueType_FontSrcInit()
static bool ImGui_ImplStbTrueType_FontSrcInit (ImFontAtlas * atlas, ImFontConfig * src) static
Definition at line 4574 of file imgui_draw.cpp.
References ImFontConfig::DstFont, ImFontConfig::FontData, ImGui_ImplStbTrueType_FontSrcData::FontInfo, ImFontConfig::FontLoaderData, ImFontConfig::FontNo, IM_ASSERT, IM_ASSERT_USER_ERROR, IM_DELETE(), IM_NEW, IM_UNUSED, ImFontConfig::MergeMode, ImGui_ImplStbTrueType_FontSrcData::ScaleFactor, ImFontConfig::SizePixels, ImFont::Sources, stbtt_GetFontOffsetForIndex(), stbtt_InitFont(), and stbtt_ScaleForPixelHeight().
Referenced by ImFontAtlasGetFontLoaderForStbTruetype().
ImTextCalcWordWrapNextLineStart()
const char * ImTextCalcWordWrapNextLineStart (const char * text, const char * text_end, ImDrawTextFlags flags)
Definition at line 5364 of file imgui_draw.cpp.
References ImCharIsBlankA(), and ImDrawTextFlags_WrapKeepBlanks.
Referenced by ImFontCalcTextSizeEx(), and ImFont::RenderText().
ImTextureDataGetFormatBytesPerPixel()
int ImTextureDataGetFormatBytesPerPixel (ImTextureFormat format)
Definition at line 2434 of file imgui_draw.cpp.
References IM_ASSERT, ImTextureFormat_Alpha8, and ImTextureFormat_RGBA32.
Referenced by ImTextureData::Create(), and ImFontAtlasTextureBlockConvert().
ImTextureDataGetFormatName()
const char * ImTextureDataGetFormatName (ImTextureFormat format)
Definition at line 2458 of file imgui_draw.cpp.
References ImTextureFormat_Alpha8, and ImTextureFormat_RGBA32.
Referenced by ImGui::DebugNodeTexture().
ImTextureDataGetStatusName()
const char * ImTextureDataGetStatusName (ImTextureStatus status)
Definition at line 2445 of file imgui_draw.cpp.
References ImTextureStatus_Destroyed, ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, and ImTextureStatus_WantUpdates.
Referenced by ImGui::DebugNodeTexture().
PathBezierCubicCurveToCasteljau()
static void PathBezierCubicCurveToCasteljau (ImVector< ImVec2 > * path, float x1, float y1, float x2, float y2, float x3, float y3, float x4, float y4, float tess_tol, int level) static
Definition at line 1357 of file imgui_draw.cpp.
References PathBezierCubicCurveToCasteljau(), and ImVector< T >::push_back().
Referenced by ImDrawList::PathBezierCubicCurveTo(), and PathBezierCubicCurveToCasteljau().
PathBezierQuadraticCurveToCasteljau()
static void PathBezierQuadraticCurveToCasteljau (ImVector< ImVec2 > * path, float x1, float y1, float x2, float y2, float x3, float y3, float tess_tol, int level) static
Definition at line 1382 of file imgui_draw.cpp.
References PathBezierQuadraticCurveToCasteljau(), and ImVector< T >::push_back().
Referenced by ImDrawList::PathBezierQuadraticCurveTo(), and PathBezierQuadraticCurveToCasteljau().
stb__lit()
static void stb__lit (const unsigned char * data, unsigned int length) static
Definition at line 6061 of file imgui_draw.cpp.
References IM_ASSERT, stb__barrier_in_b, stb__barrier_out_e, and stb__dout.
Referenced by stb_decompress_token().
stb__match()
static void stb__match (const unsigned char * data, unsigned int length) static
Definition at line 6052 of file imgui_draw.cpp.
References IM_ASSERT, stb__barrier_out_b, stb__barrier_out_e, and stb__dout.
Referenced by stb_decompress_token().
stb_adler32()
static unsigned int stb_adler32 (unsigned int adler32, unsigned char * buffer, unsigned int buflen) static
Definition at line 6091 of file imgui_draw.cpp.
Referenced by stb_decompress().
stb_decompress()
static unsigned int stb_decompress (unsigned char * output, const unsigned char * input, unsigned int length) static
Definition at line 6122 of file imgui_draw.cpp.
References IM_ASSERT, stb__barrier_in_b, stb__barrier_out_b, stb__barrier_out_e, stb__dout, stb__in4, stb_adler32(), stb_decompress_length(), and stb_decompress_token().
Referenced by ImFontAtlas::AddFontFromMemoryCompressedTTF().
stb_decompress_length()
static unsigned int stb_decompress_length (const unsigned char * input) static
Definition at line 6044 of file imgui_draw.cpp.
Referenced by ImFontAtlas::AddFontFromMemoryCompressedTTF(), and stb_decompress().
stb_decompress_token()
static const unsigned char * stb_decompress_token (const unsigned char * i) static
Definition at line 6074 of file imgui_draw.cpp.
References stb__dout, stb__in2, stb__in3, stb__lit(), and stb__match().
Referenced by stb_decompress().
UnpackAccumulativeOffsetsIntoRanges()
static void UnpackAccumulativeOffsetsIntoRanges (int base_codepoint, const short * accumulative_offsets, int accumulative_offsets_count, ImWchar * out_ranges) static
Definition at line 4819 of file imgui_draw.cpp.
Referenced by ImFontAtlas::GetGlyphRangesChineseSimplifiedCommon(), and ImFontAtlas::GetGlyphRangesJapanese().
Variable Documentation
FONT_ATLAS_DEFAULT_TEX_CURSOR_DATA
const ImVec2 FONT_ATLAS_DEFAULT_TEX_CURSOR_DATA[ImGuiMouseCursor_COUNT][3] static
Initial value:
=
{
    { ImVec2( 0,3), ImVec2(12,19), ImVec2( 0, 0) },
    { ImVec2(13,0), ImVec2( 7,16), ImVec2( 1, 8) },
    { ImVec2(31,0), ImVec2(23,23), ImVec2(11,11) },
    { ImVec2(21,0), ImVec2( 9,23), ImVec2( 4,11) },
    { ImVec2(55,18),ImVec2(23, 9), ImVec2(11, 4) },
    { ImVec2(73,0), ImVec2(17,17), ImVec2( 8, 8) },
    { ImVec2(55,0), ImVec2(17,17), ImVec2( 8, 8) },
    { ImVec2(91,0), ImVec2(17,22), ImVec2( 5, 0) },
    { ImVec2(0,3),  ImVec2(12,19), ImVec2(0, 0) },
    { ImVec2(0,3),  ImVec2(12,19), ImVec2(0, 0) },
    { ImVec2(109,0),ImVec2(13,15), ImVec2( 6, 7) },
}
Definition at line 2617 of file imgui_draw.cpp.
Referenced by ImFontAtlasGetMouseCursorTexData().
FONT_ATLAS_DEFAULT_TEX_DATA_H
const int FONT_ATLAS_DEFAULT_TEX_DATA_H = 27
Definition at line 2585 of file imgui_draw.cpp.
Referenced by ImFontAtlasBuildUpdateBasicTexData().
FONT_ATLAS_DEFAULT_TEX_DATA_PIXELS
const char FONT_ATLAS_DEFAULT_TEX_DATA_PIXELS[FONT_ATLAS_DEFAULT_TEX_DATA_W *FONT_ATLAS_DEFAULT_TEX_DATA_H+1] static
Initial value:
=
{
    "..-         -XXXXXXX-    X    -           X           -XXXXXXX          -          XXXXXXX-     XX          - XX       XX "
    "..-         -X.....X-   X.X   -          X.X          -X.....X          -          X.....X-    X..X         -X..X     X..X"
    "---         -XXX.XXX-  X...X  -         X...X         -X....X           -           X....X-    X..X         -X...X   X...X"
    "X           -  X.X  - X.....X -        X.....X        -X...X            -            X...X-    X..X         - X...X X...X "
    "XX          -  X.X  -X.......X-       X.......X       -X..X.X           -           X.X..X-    X..X         -  X...X...X  "
    "X.X         -  X.X  -XXXX.XXXX-       XXXX.XXXX       -X.X X.X          -          X.X X.X-    X..XXX       -   X.....X   "
    "X..X        -  X.X  -   X.X   -          X.X          -XX   X.X         -         X.X   XX-    X..X..XXX    -    X...X    "
    "X...X       -  X.X  -   X.X   -    XX    X.X    XX    -      X.X        -        X.X      -    X..X..X..XX  -     X.X     "
    "X....X      -  X.X  -   X.X   -   X.X    X.X    X.X   -       X.X       -       X.X       -    X..X..X..X.X -    X...X    "
    "X.....X     -  X.X  -   X.X   -  X..X    X.X    X..X  -        X.X      -      X.X        -XXX X..X..X..X..X-   X.....X   "
    "X......X    -  X.X  -   X.X   - X...XXXXXX.XXXXXX...X -         X.X   XX-XX   X.X         -X..XX........X..X-  X...X...X  "
    "X.......X   -  X.X  -   X.X   -X.....................X-          X.X X.X-X.X X.X          -X...X...........X- X...X X...X "
    "X........X  -  X.X  -   X.X   - X...XXXXXX.XXXXXX...X -           X.X..X-X..X.X           - X..............X-X...X   X...X"
    "X.........X -XXX.XXX-   X.X   -  X..X    X.X    X..X  -            X...X-X...X            -  X.............X-X..X     X..X"
    "X..........X-X.....X-   X.X   -   X.X    X.X    X.X   -           X....X-X....X           -  X.............X- XX       XX "
    "X......XXXXX-XXXXXXX-   X.X   -    XX    X.X    XX    -          X.....X-X.....X          -   X............X--------------"
    "X...X..X    ---------   X.X   -          X.X          -          XXXXXXX-XXXXXXX          -   X...........X -             "
    "X..X X..X   -       -XXXX.XXXX-       XXXX.XXXX       -------------------------------------    X..........X -             "
    "X.X  X..X   -       -X.......X-       X.......X       -    XX           XX    -           -    X..........X -             "
    "XX    X..X  -       - X.....X -        X.....X        -   X.X           X.X   -           -     X........X  -             "
    "      X..X  -       -  X...X  -         X...X         -  X..X           X..X  -           -     X........X  -             "
    "       XX   -       -   X.X   -          X.X          - X...XXXXXXXXXXXXX...X -           -     XXXXXXXXXX  -             "
    "-------------       -    X    -           X           -X.....................X-           -------------------             "
    "                    ----------------------------------- X...XXXXXXXXXXXXX...X -                                           "
    "                                                      -  X..X           X..X  -                                           "
    "                                                      -   X.X           X.X   -                                           "
    "                                                      -    XX           XX    -                                           "
}
Definition at line 2586 of file imgui_draw.cpp.
Referenced by ImFontAtlasBuildUpdateBasicTexData().
FONT_ATLAS_DEFAULT_TEX_DATA_W
const int FONT_ATLAS_DEFAULT_TEX_DATA_W = 122
Definition at line 2584 of file imgui_draw.cpp.
Referenced by ImFontAtlasBuildUpdateBasicTexData(), and ImFontAtlasGetMouseCursorTexData().
proggy_clean_ttf_compressed_data
const unsigned char proggy_clean_ttf_compressed_data[9583] static
Definition at line 6169 of file imgui_draw.cpp.
Referenced by GetDefaultCompressedFontDataTTF().
proggy_clean_ttf_compressed_size
const unsigned int proggy_clean_ttf_compressed_size = 9583 static
Definition at line 6168 of file imgui_draw.cpp.
Referenced by GetDefaultCompressedFontDataTTF().
stb__barrier_in_b
const unsigned char* stb__barrier_in_b static
Definition at line 6050 of file imgui_draw.cpp.
Referenced by stb__lit(), and stb_decompress().
stb__barrier_out_b
unsigned char * stb__barrier_out_b static
Definition at line 6049 of file imgui_draw.cpp.
Referenced by stb__match(), and stb_decompress().
stb__barrier_out_e
unsigned char* stb__barrier_out_e static
Definition at line 6049 of file imgui_draw.cpp.
Referenced by stb__lit(), stb__match(), and stb_decompress().
stb__dout
unsigned char* stb__dout static
Definition at line 6051 of file imgui_draw.cpp.
Referenced by stb__lit(), stb__match(), stb_decompress(), and stb_decompress_token().