SignalProcessing: examples/imgui/imgui_internal.h File Reference
imgui_internal.h File Reference
#include "imgui.h"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <limits.h>
Classes
struct ImVec1
struct ImVec2i
struct ImVec2ih
struct ImRect
struct ImBitArray< BITCOUNT, OFFSET >
struct ImBitVector
struct ImSpan< T >
struct ImSpanAllocator< CHUNKS >
struct ImStableVector< T, BLOCKSIZE >
struct ImPool< T >
struct ImChunkStream< T >
struct ImGuiTextIndex
struct ImDrawListSharedData
struct ImDrawDataBuilder
struct ImFontStackData
struct ImGuiStyleVarInfo
struct ImGuiColorMod
struct ImGuiStyleMod
struct ImGuiDataTypeStorage
struct ImGuiDataTypeInfo
struct ImGuiComboPreviewData
struct ImGuiGroupData
struct ImGuiMenuColumns
struct ImGuiInputTextDeactivatedState
struct ImGuiInputTextState
struct ImGuiNextWindowData
struct ImGuiNextItemData
struct ImGuiLastItemData
struct ImGuiTreeNodeStackData
struct ImGuiErrorRecoveryState
struct ImGuiWindowStackData
struct ImGuiShrinkWidthItem
struct ImGuiPtrOrIndex
struct ImGuiDeactivatedItemData
struct ImGuiPopupData
struct ImGuiInputEventMousePos
struct ImGuiInputEventMouseWheel
struct ImGuiInputEventMouseButton
struct ImGuiInputEventKey
struct ImGuiInputEventText
struct ImGuiInputEventAppFocused
struct ImGuiInputEvent
struct ImGuiKeyRoutingData
struct ImGuiKeyRoutingTable
struct ImGuiKeyOwnerData
struct ImGuiListClipperRange
struct ImGuiListClipperData
struct ImGuiNavItemData
struct ImGuiFocusScopeData
struct ImGuiTypingSelectRequest
struct ImGuiTypingSelectState
struct ImGuiOldColumnData
struct ImGuiOldColumns
struct ImGuiBoxSelectState
struct ImGuiMultiSelectTempData
struct ImGuiMultiSelectState
struct ImGuiViewportP
struct ImGuiWindowSettings
struct ImGuiSettingsHandler
struct ImGuiLocEntry
struct ImGuiDebugAllocEntry
struct ImGuiDebugAllocInfo
struct ImGuiMetricsConfig
struct ImGuiStackLevelInfo
struct ImGuiDebugItemPathQuery
struct ImGuiIDStackTool
struct ImGuiContextHook
struct ImGuiContext
struct ImGuiWindowTempData
struct ImGuiWindow
struct ImGuiTabItem
struct ImGuiTabBar
struct ImGuiTableColumn
struct ImGuiTableCellData
struct ImGuiTableHeaderData
struct ImGuiTableInstanceData
struct ImGuiTable
struct ImGuiTableTempData
struct ImGuiTableColumnSettings
struct ImGuiTableSettings
struct ImFontLoader
struct ImFontAtlasRectEntry
struct ImFontAtlasPostProcessData
struct stbrp_context_opaque
struct ImFontAtlasBuilder
Namespaces
namespace ImStb
namespace ImGui
Macros
#define IMGUI_ENABLE_STB_TRUETYPE
#define IMGUI_DEBUG_PRINTF(_FMT, ...) printf(_FMT, __VA_ARGS__)
#define IMGUI_DEBUG_LOG_ERROR(...) do { if (g.DebugLogFlags & ImGuiDebugLogFlags_EventError) IMGUI_DEBUG_LOG(__VA_ARGS__); else g.DebugLogSkippedErrors++; } while (0)
#define IMGUI_DEBUG_LOG_ACTIVEID(...) do { if (g.DebugLogFlags & ImGuiDebugLogFlags_EventActiveId) IMGUI_DEBUG_LOG(__VA_ARGS__); } while (0)
#define IMGUI_DEBUG_LOG_FOCUS(...) do { if (g.DebugLogFlags & ImGuiDebugLogFlags_EventFocus) IMGUI_DEBUG_LOG(__VA_ARGS__); } while (0)
#define IMGUI_DEBUG_LOG_POPUP(...) do { if (g.DebugLogFlags & ImGuiDebugLogFlags_EventPopup) IMGUI_DEBUG_LOG(__VA_ARGS__); } while (0)
#define IMGUI_DEBUG_LOG_NAV(...) do { if (g.DebugLogFlags & ImGuiDebugLogFlags_EventNav) IMGUI_DEBUG_LOG(__VA_ARGS__); } while (0)
#define IMGUI_DEBUG_LOG_SELECTION(...) do { if (g.DebugLogFlags & ImGuiDebugLogFlags_EventSelection) IMGUI_DEBUG_LOG(__VA_ARGS__); } while (0)
#define IMGUI_DEBUG_LOG_CLIPPER(...) do { if (g.DebugLogFlags & ImGuiDebugLogFlags_EventClipper) IMGUI_DEBUG_LOG(__VA_ARGS__); } while (0)
#define IMGUI_DEBUG_LOG_IO(...) do { if (g.DebugLogFlags & ImGuiDebugLogFlags_EventIO) IMGUI_DEBUG_LOG(__VA_ARGS__); } while (0)
#define IMGUI_DEBUG_LOG_FONT(...) do { ImGuiContext* g2 = GImGui; if (g2 && g2->DebugLogFlags & ImGuiDebugLogFlags_EventFont) IMGUI_DEBUG_LOG(__VA_ARGS__); } while (0)
#define IMGUI_DEBUG_LOG_INPUTROUTING(...) do{if (g.DebugLogFlags & ImGuiDebugLogFlags_EventInputRouting)IMGUI_DEBUG_LOG(__VA_ARGS__); } while (0)
#define IM_STATIC_ASSERT(_COND) static_assert(_COND, "")
#define IM_ASSERT_PARANOID(_EXPR)
#define IM_PI 3.14159265358979323846f
#define IM_NEWLINE "\n"
#define IM_TABSIZE (4)
#define IM_MEMALIGN(_OFF, _ALIGN) (((_OFF) + ((_ALIGN) - 1)) & ~((_ALIGN) - 1))
#define IM_F32_TO_INT8_UNBOUND(_VAL) ((int)((_VAL) * 255.0f + ((_VAL)>=0 ? 0.5f : -0.5f)))
#define IM_F32_TO_INT8_SAT(_VAL) ((int)(ImSaturate(_VAL) * 255.0f + 0.5f))
#define IM_TRUNC(_VAL) ((float)(int)(_VAL))
#define IM_ROUND(_VAL) ((float)(int)((_VAL) + 0.5f))
#define IM_FLOOR IM_TRUNC
#define IM_LIKELY
#define IM_UNLIKELY
#define IMGUI_CDECL
#define IM_MSVC_WARNING_SUPPRESS(XXXX)
#define IM_DEBUG_BREAK() IM_ASSERT(0)
#define IM_PRId64 "lld"
#define IM_PRIu64 "llu"
#define IM_PRIX64 "llX"
#define ImStrlen strlen
#define ImMemchr memchr
#define ImFabs(X) fabsf(X)
#define ImSqrt(X) sqrtf(X)
#define ImFmod(X, Y) fmodf((X), (Y))
#define ImCos(X) cosf(X)
#define ImSin(X) sinf(X)
#define ImAcos(X) acosf(X)
#define ImAtan2(Y, X) atan2f((Y), (X))
#define ImAtof(STR) atof(STR)
#define ImCeil(X) ceilf(X)
#define IM_BITARRAY_TESTBIT(_ARRAY, _N) ((_ARRAY[(_N) >> 5] & ((ImU32)1 << ((_N) & 31))) != 0)
#define IM_BITARRAY_CLEARBIT(_ARRAY, _N) ((_ARRAY[(_N) >> 5] &= ~((ImU32)1 << ((_N) & 31))))
#define IM_ROUNDUP_TO_EVEN(_V) ((((_V) + 1) / 2) * 2)
#define IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MIN 4
#define IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MAX 512
#define IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_CALC(_RAD, _MAXERROR) ImClamp(IM_ROUNDUP_TO_EVEN((int)ImCeil(IM_PI / ImAcos(1 - ImMin((_MAXERROR), (_RAD)) / (_RAD)))), IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MIN, IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MAX)
#define IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_CALC_R(_N, _MAXERROR) ((_MAXERROR) / (1 - ImCos(IM_PI / ImMax((float)(_N), IM_PI))))
#define IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_CALC_ERROR(_N, _RAD) ((1 - ImCos(IM_PI / ImMax((float)(_N), IM_PI))) / (_RAD))
#define IM_DRAWLIST_ARCFAST_TABLE_SIZE 48
#define IM_DRAWLIST_ARCFAST_SAMPLE_MAX IM_DRAWLIST_ARCFAST_TABLE_SIZE
#define IMSTB_TEXTEDIT_STRING ImGuiInputTextState
#define IMSTB_TEXTEDIT_CHARTYPE char
#define IMSTB_TEXTEDIT_GETWIDTH_NEWLINE (-1.0f)
#define IMSTB_TEXTEDIT_UNDOSTATECOUNT 99
#define IMSTB_TEXTEDIT_UNDOCHARCOUNT 999
#define ImGuiKey_LegacyNativeKey_BEGIN 0
#define ImGuiKey_LegacyNativeKey_END 512
#define ImGuiKey_Keyboard_BEGIN (ImGuiKey_NamedKey_BEGIN)
#define ImGuiKey_Keyboard_END (ImGuiKey_GamepadStart)
#define ImGuiKey_Gamepad_BEGIN (ImGuiKey_GamepadStart)
#define ImGuiKey_Gamepad_END (ImGuiKey_GamepadRStickDown + 1)
#define ImGuiKey_Mouse_BEGIN (ImGuiKey_MouseLeft)
#define ImGuiKey_Mouse_END (ImGuiKey_MouseWheelY + 1)
#define ImGuiKey_Aliases_BEGIN (ImGuiKey_Mouse_BEGIN)
#define ImGuiKey_Aliases_END (ImGuiKey_Mouse_END)
#define ImGuiKey_NavKeyboardTweakSlow ImGuiMod_Ctrl
#define ImGuiKey_NavKeyboardTweakFast ImGuiMod_Shift
#define ImGuiKey_NavGamepadTweakSlow ImGuiKey_GamepadL1
#define ImGuiKey_NavGamepadTweakFast ImGuiKey_GamepadR1
#define ImGuiKey_NavGamepadActivate (g.IO.ConfigNavSwapGamepadButtons ? ImGuiKey_GamepadFaceRight : ImGuiKey_GamepadFaceDown)
#define ImGuiKey_NavGamepadCancel (g.IO.ConfigNavSwapGamepadButtons ? ImGuiKey_GamepadFaceDown : ImGuiKey_GamepadFaceRight)
#define ImGuiKey_NavGamepadMenu ImGuiKey_GamepadFaceLeft
#define ImGuiKey_NavGamepadInput ImGuiKey_GamepadFaceUp
#define ImGuiKeyOwner_Any ((ImGuiID)0)
#define ImGuiKeyOwner_NoOwner ((ImGuiID)-1)
#define ImGuiSelectionUserData_Invalid ((ImGuiSelectionUserData)-1)
#define IM_ASSERT_USER_ERROR(_EXPR, _MSG) do { if (!(_EXPR) && ImGui::ErrorLog(_MSG)) { IM_ASSERT((_EXPR) && _MSG); } } while (0)
#define IMGUI_WINDOW_HARD_MIN_SIZE 4.0f
#define IM_COL32_DISABLE IM_COL32(0,0,0,1)
#define IMGUI_TABLE_MAX_COLUMNS 512
#define IMGUI_FONT_SIZE_MAX (512.0f)
#define IMGUI_FONT_SIZE_THRESHOLD_FOR_LOADADVANCEXONLYMODE (128.0f)
#define ImFontAtlasRectId_IndexMask_ (0x0007FFFF)
#define ImFontAtlasRectId_GenerationMask_ (0x3FF00000)
#define ImFontAtlasRectId_GenerationShift_ (20)
#define IMGUI_TEST_ENGINE_ITEM_ADD(_ID, _BB, _ITEM_DATA) ((void)0)
#define IMGUI_TEST_ENGINE_ITEM_INFO(_ID, _LABEL, _FLAGS) ((void)g)
Typedefs
typedef int ImGuiLayoutType
typedef int ImDrawTextFlags
typedef int ImGuiActivateFlags
typedef int ImGuiDebugLogFlags
typedef int ImGuiFocusRequestFlags
typedef int ImGuiItemStatusFlags
typedef int ImGuiOldColumnFlags
typedef int ImGuiLogFlags
typedef int ImGuiNavRenderCursorFlags
typedef int ImGuiNavMoveFlags
typedef int ImGuiNextItemDataFlags
typedef int ImGuiNextWindowDataFlags
typedef int ImGuiScrollFlags
typedef int ImGuiSeparatorFlags
typedef int ImGuiTextFlags
typedef int ImGuiTooltipFlags
typedef int ImGuiTypingSelectFlags
typedef int ImGuiWindowBgClickFlags
typedef int ImGuiWindowRefreshFlags
typedef ImS16 ImGuiTableColumnIdx
typedef ImU16 ImGuiTableDrawChannelIdx
typedef FILE * ImFileHandle
typedef ImU32 * ImBitArrayPtr
typedef int ImPoolIdx
typedef ImStb::STB_TexteditState ImStbTexteditState
typedef ImBitArray< ImGuiKey_NamedKey_COUNT, -ImGuiKey_NamedKey_BEGIN > ImBitArrayForNamedKeys
typedef ImS16 ImGuiKeyRoutingIndex
typedef void(* ImGuiErrorCallback) (ImGuiContext *ctx, void *user_data, const char *msg)
typedef void(* ImGuiContextHookCallback) (ImGuiContext *ctx, ImGuiContextHook *hook)
typedef ImFontLoader ImFontBuilderIO
typedef stbrp_node stbrp_node_im
Enumerations
enum ImDrawTextFlags_ { ImDrawTextFlags_None = 0 , ImDrawTextFlags_CpuFineClip = 1 << 0 , ImDrawTextFlags_WrapKeepBlanks = 1 << 1 , ImDrawTextFlags_StopOnNewLine = 1 << 2 }
enum ImGuiDataTypePrivate_ { ImGuiDataType_Pointer = ImGuiDataType_COUNT , ImGuiDataType_ID }
enum ImGuiItemFlagsPrivate_ {
ImGuiItemFlags_Disabled = 1 << 10 , ImGuiItemFlags_ReadOnly = 1 << 11 , ImGuiItemFlags_MixedValue = 1 << 12 , ImGuiItemFlags_NoWindowHoverableCheck = 1 << 13 ,
ImGuiItemFlags_AllowOverlap = 1 << 14 , ImGuiItemFlags_NoNavDisableMouseHover = 1 << 15 , ImGuiItemFlags_NoMarkEdited = 1 << 16 , ImGuiItemFlags_NoFocus = 1 << 17 ,
ImGuiItemFlags_Inputable = 1 << 20 , ImGuiItemFlags_HasSelectionUserData = 1 << 21 , ImGuiItemFlags_IsMultiSelect = 1 << 22 , ImGuiItemFlags_Default_ = ImGuiItemFlags_AutoClosePopups
}
enum ImGuiItemStatusFlags_ {
ImGuiItemStatusFlags_None = 0 , ImGuiItemStatusFlags_HoveredRect = 1 << 0 , ImGuiItemStatusFlags_HasDisplayRect = 1 << 1 , ImGuiItemStatusFlags_Edited = 1 << 2 ,
ImGuiItemStatusFlags_ToggledSelection = 1 << 3 , ImGuiItemStatusFlags_ToggledOpen = 1 << 4 , ImGuiItemStatusFlags_HasDeactivated = 1 << 5 , ImGuiItemStatusFlags_Deactivated = 1 << 6 ,
ImGuiItemStatusFlags_HoveredWindow = 1 << 7 , ImGuiItemStatusFlags_Visible = 1 << 8 , ImGuiItemStatusFlags_HasClipRect = 1 << 9 , ImGuiItemStatusFlags_HasShortcut = 1 << 10
}
enum ImGuiHoveredFlagsPrivate_ { ImGuiHoveredFlags_DelayMask_ = ImGuiHoveredFlags_DelayNone | ImGuiHoveredFlags_DelayShort | ImGuiHoveredFlags_DelayNormal | ImGuiHoveredFlags_NoSharedDelay , ImGuiHoveredFlags_AllowedMaskForIsWindowHovered = ImGuiHoveredFlags_ChildWindows | ImGuiHoveredFlags_RootWindow | ImGuiHoveredFlags_AnyWindow | ImGuiHoveredFlags_NoPopupHierarchy | ImGuiHoveredFlags_AllowWhenBlockedByPopup | ImGuiHoveredFlags_AllowWhenBlockedByActiveItem | ImGuiHoveredFlags_ForTooltip | ImGuiHoveredFlags_Stationary , ImGuiHoveredFlags_AllowedMaskForIsItemHovered = ImGuiHoveredFlags_AllowWhenBlockedByPopup | ImGuiHoveredFlags_AllowWhenBlockedByActiveItem | ImGuiHoveredFlags_AllowWhenOverlapped | ImGuiHoveredFlags_AllowWhenDisabled | ImGuiHoveredFlags_NoNavOverride | ImGuiHoveredFlags_ForTooltip | ImGuiHoveredFlags_Stationary | ImGuiHoveredFlags_DelayMask_ }
enum ImGuiInputTextFlagsPrivate_ { ImGuiInputTextFlags_Multiline = 1 << 26 , ImGuiInputTextFlags_MergedItem = 1 << 27 , ImGuiInputTextFlags_LocalizeDecimalPoint = 1 << 28 }
enum ImGuiButtonFlagsPrivate_ {
ImGuiButtonFlags_PressedOnClick = 1 << 4 , ImGuiButtonFlags_PressedOnClickRelease = 1 << 5 , ImGuiButtonFlags_PressedOnClickReleaseAnywhere = 1 << 6 , ImGuiButtonFlags_PressedOnRelease = 1 << 7 ,
ImGuiButtonFlags_PressedOnDoubleClick = 1 << 8 , ImGuiButtonFlags_PressedOnDragDropHold = 1 << 9 , ImGuiButtonFlags_FlattenChildren = 1 << 11 , ImGuiButtonFlags_AllowOverlap = 1 << 12 ,
ImGuiButtonFlags_AlignTextBaseLine = 1 << 15 , ImGuiButtonFlags_NoKeyModsAllowed = 1 << 16 , ImGuiButtonFlags_NoHoldingActiveId = 1 << 17 , ImGuiButtonFlags_NoNavFocus = 1 << 18 ,
ImGuiButtonFlags_NoHoveredOnFocus = 1 << 19 , ImGuiButtonFlags_NoSetKeyOwner = 1 << 20 , ImGuiButtonFlags_NoTestKeyOwner = 1 << 21 , ImGuiButtonFlags_NoFocus = 1 << 22 ,
ImGuiButtonFlags_PressedOnMask_ = ImGuiButtonFlags_PressedOnClick | ImGuiButtonFlags_PressedOnClickRelease | ImGuiButtonFlags_PressedOnClickReleaseAnywhere | ImGuiButtonFlags_PressedOnRelease | ImGuiButtonFlags_PressedOnDoubleClick | ImGuiButtonFlags_PressedOnDragDropHold , ImGuiButtonFlags_PressedOnDefault_ = ImGuiButtonFlags_PressedOnClickRelease
}
enum ImGuiComboFlagsPrivate_ { ImGuiComboFlags_CustomPreview = 1 << 20 }
enum ImGuiSliderFlagsPrivate_ { ImGuiSliderFlags_Vertical = 1 << 20 , ImGuiSliderFlags_ReadOnly = 1 << 21 }
enum ImGuiSelectableFlagsPrivate_ {
ImGuiSelectableFlags_NoHoldingActiveID = 1 << 20 , ImGuiSelectableFlags_SelectOnClick = 1 << 22 , ImGuiSelectableFlags_SelectOnRelease = 1 << 23 , ImGuiSelectableFlags_SpanAvailWidth = 1 << 24 ,
ImGuiSelectableFlags_SetNavIdOnHover = 1 << 25 , ImGuiSelectableFlags_NoPadWithHalfSpacing = 1 << 26 , ImGuiSelectableFlags_NoSetKeyOwner = 1 << 27
}
enum ImGuiTreeNodeFlagsPrivate_ {
ImGuiTreeNodeFlags_NoNavFocus = 1 << 27 , ImGuiTreeNodeFlags_ClipLabelForTrailingButton = 1 << 28 , ImGuiTreeNodeFlags_UpsideDownArrow = 1 << 29 , ImGuiTreeNodeFlags_OpenOnMask_ = ImGuiTreeNodeFlags_OpenOnDoubleClick | ImGuiTreeNodeFlags_OpenOnArrow ,
ImGuiTreeNodeFlags_DrawLinesMask_ = ImGuiTreeNodeFlags_DrawLinesNone | ImGuiTreeNodeFlags_DrawLinesFull | ImGuiTreeNodeFlags_DrawLinesToNodes
}
enum ImGuiSeparatorFlags_ { ImGuiSeparatorFlags_None = 0 , ImGuiSeparatorFlags_Horizontal = 1 << 0 , ImGuiSeparatorFlags_Vertical = 1 << 1 , ImGuiSeparatorFlags_SpanAllColumns = 1 << 2 }
enum ImGuiFocusRequestFlags_ { ImGuiFocusRequestFlags_None = 0 , ImGuiFocusRequestFlags_RestoreFocusedChild = 1 << 0 , ImGuiFocusRequestFlags_UnlessBelowModal = 1 << 1 }
enum ImGuiTextFlags_ { ImGuiTextFlags_None = 0 , ImGuiTextFlags_NoWidthForLargeClippedText = 1 << 0 }
enum ImGuiTooltipFlags_ { ImGuiTooltipFlags_None = 0 , ImGuiTooltipFlags_OverridePrevious = 1 << 1 }
enum ImGuiLayoutType_ { ImGuiLayoutType_Horizontal = 0 , ImGuiLayoutType_Vertical = 1 }
enum ImGuiLogFlags_ {
ImGuiLogFlags_None = 0 , ImGuiLogFlags_OutputTTY = 1 << 0 , ImGuiLogFlags_OutputFile = 1 << 1 , ImGuiLogFlags_OutputBuffer = 1 << 2 ,
ImGuiLogFlags_OutputClipboard = 1 << 3 , ImGuiLogFlags_OutputMask_ = ImGuiLogFlags_OutputTTY | ImGuiLogFlags_OutputFile | ImGuiLogFlags_OutputBuffer | ImGuiLogFlags_OutputClipboard
}
enum ImGuiAxis { ImGuiAxis_None = -1 , ImGuiAxis_X = 0 , ImGuiAxis_Y = 1 }
enum ImGuiPlotType { ImGuiPlotType_Lines , ImGuiPlotType_Histogram }
enum ImGuiWindowRefreshFlags_ { ImGuiWindowRefreshFlags_None = 0 , ImGuiWindowRefreshFlags_TryToAvoidRefresh = 1 << 0 , ImGuiWindowRefreshFlags_RefreshOnHover = 1 << 1 , ImGuiWindowRefreshFlags_RefreshOnFocus = 1 << 2 }
enum ImGuiWindowBgClickFlags_ { ImGuiWindowBgClickFlags_None = 0 , ImGuiWindowBgClickFlags_Move = 1 << 0 }
enum ImGuiNextWindowDataFlags_ {
ImGuiNextWindowDataFlags_None = 0 , ImGuiNextWindowDataFlags_HasPos = 1 << 0 , ImGuiNextWindowDataFlags_HasSize = 1 << 1 , ImGuiNextWindowDataFlags_HasContentSize = 1 << 2 ,
ImGuiNextWindowDataFlags_HasCollapsed = 1 << 3 , ImGuiNextWindowDataFlags_HasSizeConstraint = 1 << 4 , ImGuiNextWindowDataFlags_HasFocus = 1 << 5 , ImGuiNextWindowDataFlags_HasBgAlpha = 1 << 6 ,
ImGuiNextWindowDataFlags_HasScroll = 1 << 7 , ImGuiNextWindowDataFlags_HasWindowFlags = 1 << 8 , ImGuiNextWindowDataFlags_HasChildFlags = 1 << 9 , ImGuiNextWindowDataFlags_HasRefreshPolicy = 1 << 10
}
enum ImGuiNextItemDataFlags_ {
ImGuiNextItemDataFlags_None = 0 , ImGuiNextItemDataFlags_HasWidth = 1 << 0 , ImGuiNextItemDataFlags_HasOpen = 1 << 1 , ImGuiNextItemDataFlags_HasShortcut = 1 << 2 ,
ImGuiNextItemDataFlags_HasRefVal = 1 << 3 , ImGuiNextItemDataFlags_HasStorageID = 1 << 4 , ImGuiNextItemDataFlags_HasColorMarker = 1 << 5
}
enum ImGuiPopupPositionPolicy { ImGuiPopupPositionPolicy_Default , ImGuiPopupPositionPolicy_ComboBox , ImGuiPopupPositionPolicy_Tooltip }
enum ImGuiInputEventType {
ImGuiInputEventType_None = 0 , ImGuiInputEventType_MousePos , ImGuiInputEventType_MouseWheel , ImGuiInputEventType_MouseButton ,
ImGuiInputEventType_Key , ImGuiInputEventType_Text , ImGuiInputEventType_Focus , ImGuiInputEventType_COUNT
}
enum ImGuiInputSource : int {
ImGuiInputSource_None = 0 , ImGuiInputSource_Mouse , ImGuiInputSource_Keyboard , ImGuiInputSource_Gamepad ,
ImGuiInputSource_COUNT
}
enum ImGuiInputFlagsPrivate_ {
ImGuiInputFlags_RepeatRateDefault = 1 << 1 , ImGuiInputFlags_RepeatRateNavMove = 1 << 2 , ImGuiInputFlags_RepeatRateNavTweak = 1 << 3 , ImGuiInputFlags_RepeatUntilRelease = 1 << 4 ,
ImGuiInputFlags_RepeatUntilKeyModsChange = 1 << 5 , ImGuiInputFlags_RepeatUntilKeyModsChangeFromNone = 1 << 6 , ImGuiInputFlags_RepeatUntilOtherKeyPress = 1 << 7 , ImGuiInputFlags_LockThisFrame = 1 << 20 ,
ImGuiInputFlags_LockUntilRelease = 1 << 21 , ImGuiInputFlags_CondHovered = 1 << 22 , ImGuiInputFlags_CondActive = 1 << 23 , ImGuiInputFlags_CondDefault_ = ImGuiInputFlags_CondHovered | ImGuiInputFlags_CondActive ,
ImGuiInputFlags_RepeatRateMask_ = ImGuiInputFlags_RepeatRateDefault | ImGuiInputFlags_RepeatRateNavMove | ImGuiInputFlags_RepeatRateNavTweak , ImGuiInputFlags_RepeatUntilMask_ = ImGuiInputFlags_RepeatUntilRelease | ImGuiInputFlags_RepeatUntilKeyModsChange | ImGuiInputFlags_RepeatUntilKeyModsChangeFromNone | ImGuiInputFlags_RepeatUntilOtherKeyPress , ImGuiInputFlags_RepeatMask_ = ImGuiInputFlags_Repeat | ImGuiInputFlags_RepeatRateMask_ | ImGuiInputFlags_RepeatUntilMask_ , ImGuiInputFlags_CondMask_ = ImGuiInputFlags_CondHovered | ImGuiInputFlags_CondActive ,
ImGuiInputFlags_RouteTypeMask_ = ImGuiInputFlags_RouteActive | ImGuiInputFlags_RouteFocused | ImGuiInputFlags_RouteGlobal | ImGuiInputFlags_RouteAlways , ImGuiInputFlags_RouteOptionsMask_ = ImGuiInputFlags_RouteOverFocused | ImGuiInputFlags_RouteOverActive | ImGuiInputFlags_RouteUnlessBgFocused | ImGuiInputFlags_RouteFromRootWindow , ImGuiInputFlags_SupportedByIsKeyPressed = ImGuiInputFlags_RepeatMask_ , ImGuiInputFlags_SupportedByIsMouseClicked = ImGuiInputFlags_Repeat ,
ImGuiInputFlags_SupportedByShortcut = ImGuiInputFlags_RepeatMask_ | ImGuiInputFlags_RouteTypeMask_ | ImGuiInputFlags_RouteOptionsMask_ , ImGuiInputFlags_SupportedBySetNextItemShortcut = ImGuiInputFlags_RepeatMask_ | ImGuiInputFlags_RouteTypeMask_ | ImGuiInputFlags_RouteOptionsMask_ | ImGuiInputFlags_Tooltip , ImGuiInputFlags_SupportedBySetKeyOwner = ImGuiInputFlags_LockThisFrame | ImGuiInputFlags_LockUntilRelease , ImGuiInputFlags_SupportedBySetItemKeyOwner = ImGuiInputFlags_SupportedBySetKeyOwner | ImGuiInputFlags_CondMask_
}
enum ImGuiActivateFlags_ {
ImGuiActivateFlags_None = 0 , ImGuiActivateFlags_PreferInput = 1 << 0 , ImGuiActivateFlags_PreferTweak = 1 << 1 , ImGuiActivateFlags_TryToPreserveState = 1 << 2 ,
ImGuiActivateFlags_FromTabbing = 1 << 3 , ImGuiActivateFlags_FromShortcut = 1 << 4 , ImGuiActivateFlags_FromFocusApi = 1 << 5
}
enum ImGuiScrollFlags_ {
ImGuiScrollFlags_None = 0 , ImGuiScrollFlags_KeepVisibleEdgeX = 1 << 0 , ImGuiScrollFlags_KeepVisibleEdgeY = 1 << 1 , ImGuiScrollFlags_KeepVisibleCenterX = 1 << 2 ,
ImGuiScrollFlags_KeepVisibleCenterY = 1 << 3 , ImGuiScrollFlags_AlwaysCenterX = 1 << 4 , ImGuiScrollFlags_AlwaysCenterY = 1 << 5 , ImGuiScrollFlags_NoScrollParent = 1 << 6 ,
ImGuiScrollFlags_MaskX_ = ImGuiScrollFlags_KeepVisibleEdgeX | ImGuiScrollFlags_KeepVisibleCenterX | ImGuiScrollFlags_AlwaysCenterX , ImGuiScrollFlags_MaskY_ = ImGuiScrollFlags_KeepVisibleEdgeY | ImGuiScrollFlags_KeepVisibleCenterY | ImGuiScrollFlags_AlwaysCenterY
}
enum ImGuiNavRenderCursorFlags_ {
ImGuiNavRenderCursorFlags_None = 0 , ImGuiNavRenderCursorFlags_Compact = 1 << 1 , ImGuiNavRenderCursorFlags_AlwaysDraw = 1 << 2 , ImGuiNavRenderCursorFlags_NoRounding = 1 << 3 ,
ImGuiNavHighlightFlags_None = ImGuiNavRenderCursorFlags_None , ImGuiNavHighlightFlags_Compact = ImGuiNavRenderCursorFlags_Compact , ImGuiNavHighlightFlags_AlwaysDraw = ImGuiNavRenderCursorFlags_AlwaysDraw , ImGuiNavHighlightFlags_NoRounding = ImGuiNavRenderCursorFlags_NoRounding
}
enum ImGuiNavMoveFlags_ {
ImGuiNavMoveFlags_None = 0 , ImGuiNavMoveFlags_LoopX = 1 << 0 , ImGuiNavMoveFlags_LoopY = 1 << 1 , ImGuiNavMoveFlags_WrapX = 1 << 2 ,
ImGuiNavMoveFlags_WrapY = 1 << 3 , ImGuiNavMoveFlags_WrapMask_ = ImGuiNavMoveFlags_LoopX | ImGuiNavMoveFlags_LoopY | ImGuiNavMoveFlags_WrapX | ImGuiNavMoveFlags_WrapY , ImGuiNavMoveFlags_AllowCurrentNavId = 1 << 4 , ImGuiNavMoveFlags_AlsoScoreVisibleSet = 1 << 5 ,
ImGuiNavMoveFlags_ScrollToEdgeY = 1 << 6 , ImGuiNavMoveFlags_Forwarded = 1 << 7 , ImGuiNavMoveFlags_DebugNoResult = 1 << 8 , ImGuiNavMoveFlags_FocusApi = 1 << 9 ,
ImGuiNavMoveFlags_IsTabbing = 1 << 10 , ImGuiNavMoveFlags_IsPageMove = 1 << 11 , ImGuiNavMoveFlags_Activate = 1 << 12 , ImGuiNavMoveFlags_NoSelect = 1 << 13 ,
ImGuiNavMoveFlags_NoSetNavCursorVisible = 1 << 14 , ImGuiNavMoveFlags_NoClearActiveId = 1 << 15
}
enum ImGuiNavLayer { ImGuiNavLayer_Main = 0 , ImGuiNavLayer_Menu = 1 , ImGuiNavLayer_COUNT }
enum ImGuiTypingSelectFlags_ { ImGuiTypingSelectFlags_None = 0 , ImGuiTypingSelectFlags_AllowBackspace = 1 << 0 , ImGuiTypingSelectFlags_AllowSingleCharMode = 1 << 1 }
enum ImGuiOldColumnFlags_ {
ImGuiOldColumnFlags_None = 0 , ImGuiOldColumnFlags_NoBorder = 1 << 0 , ImGuiOldColumnFlags_NoResize = 1 << 1 , ImGuiOldColumnFlags_NoPreserveWidths = 1 << 2 ,
ImGuiOldColumnFlags_NoForceWithinWindow = 1 << 3 , ImGuiOldColumnFlags_GrowParentContentsSize = 1 << 4
}
enum ImGuiLocKey : int {
ImGuiLocKey_VersionStr , ImGuiLocKey_TableSizeOne , ImGuiLocKey_TableSizeAllFit , ImGuiLocKey_TableSizeAllDefault ,
ImGuiLocKey_TableResetOrder , ImGuiLocKey_WindowingMainMenuBar , ImGuiLocKey_WindowingPopup , ImGuiLocKey_WindowingUntitled ,
ImGuiLocKey_OpenLink_s , ImGuiLocKey_CopyLink , ImGuiLocKey_COUNT
}
enum ImGuiDebugLogFlags_ {
ImGuiDebugLogFlags_None = 0 , ImGuiDebugLogFlags_EventError = 1 << 0 , ImGuiDebugLogFlags_EventActiveId = 1 << 1 , ImGuiDebugLogFlags_EventFocus = 1 << 2 ,
ImGuiDebugLogFlags_EventPopup = 1 << 3 , ImGuiDebugLogFlags_EventNav = 1 << 4 , ImGuiDebugLogFlags_EventClipper = 1 << 5 , ImGuiDebugLogFlags_EventSelection = 1 << 6 ,
ImGuiDebugLogFlags_EventIO = 1 << 7 , ImGuiDebugLogFlags_EventFont = 1 << 8 , ImGuiDebugLogFlags_EventInputRouting = 1 << 9 , ImGuiDebugLogFlags_EventDocking = 1 << 10 ,
ImGuiDebugLogFlags_EventViewport = 1 << 11 , ImGuiDebugLogFlags_EventMask_ = ImGuiDebugLogFlags_EventError | ImGuiDebugLogFlags_EventActiveId | ImGuiDebugLogFlags_EventFocus | ImGuiDebugLogFlags_EventPopup | ImGuiDebugLogFlags_EventNav | ImGuiDebugLogFlags_EventClipper | ImGuiDebugLogFlags_EventSelection | ImGuiDebugLogFlags_EventIO | ImGuiDebugLogFlags_EventFont | ImGuiDebugLogFlags_EventInputRouting | ImGuiDebugLogFlags_EventDocking | ImGuiDebugLogFlags_EventViewport , ImGuiDebugLogFlags_OutputToTTY = 1 << 20 , ImGuiDebugLogFlags_OutputToDebugger = 1 << 21 ,
ImGuiDebugLogFlags_OutputToTestEngine = 1 << 22
}
enum ImGuiContextHookType {
ImGuiContextHookType_NewFramePre , ImGuiContextHookType_NewFramePost , ImGuiContextHookType_EndFramePre , ImGuiContextHookType_EndFramePost ,
ImGuiContextHookType_RenderPre , ImGuiContextHookType_RenderPost , ImGuiContextHookType_Shutdown , ImGuiContextHookType_PendingRemoval_
}
enum ImGuiTabBarFlagsPrivate_ { ImGuiTabBarFlags_DockNode = 1 << 20 , ImGuiTabBarFlags_IsFocused = 1 << 21 , ImGuiTabBarFlags_SaveSettings = 1 << 22 }
enum ImGuiTabItemFlagsPrivate_ { ImGuiTabItemFlags_SectionMask_ = ImGuiTabItemFlags_Leading | ImGuiTabItemFlags_Trailing , ImGuiTabItemFlags_NoCloseButton = 1 << 20 , ImGuiTabItemFlags_Button = 1 << 21 , ImGuiTabItemFlags_Invisible = 1 << 22 }
Functions
ImGuiID ImHashData (const void *data, size_t data_size, ImGuiID seed=0)
ImGuiID ImHashStr (const char *data, size_t data_size=0, ImGuiID seed=0)
const char * ImHashSkipUncontributingPrefix (const char *label)
void ImQsort (void *base, size_t count, size_t size_of_element, int(*compare_func)(void const *, void const *))
ImU32 ImAlphaBlendColors (ImU32 col_a, ImU32 col_b)
bool ImIsPowerOfTwo (int v)
bool ImIsPowerOfTwo (ImU64 v)
int ImUpperPowerOfTwo (int v)
unsigned int ImCountSetBits (unsigned int v)
int ImStricmp (const char *str1, const char *str2)
int ImStrnicmp (const char *str1, const char *str2, size_t count)
void ImStrncpy (char *dst, const char *src, size_t count)
char * ImStrdup (const char *str)
void * ImMemdup (const void *src, size_t size)
char * ImStrdupcpy (char *dst, size_t *p_dst_size, const char *str)
const char * ImStrchrRange (const char *str_begin, const char *str_end, char c)
const char * ImStreolRange (const char *str, const char *str_end)
const char * ImStristr (const char *haystack, const char *haystack_end, const char *needle, const char *needle_end)
void ImStrTrimBlanks (char *str)
const char * ImStrSkipBlank (const char *str)
int ImStrlenW (const ImWchar *str)
const char * ImStrbol (const char *buf_mid_line, const char *buf_begin)
char ImToUpper (char c)
bool ImCharIsBlankA (char c)
bool ImCharIsBlankW (unsigned int c)
bool ImCharIsXdigitA (char c)
int ImFormatString (char *buf, size_t buf_size, const char *fmt,...)
int ImFormatStringV (char *buf, size_t buf_size, const char *fmt, va_list args)
void ImFormatStringToTempBuffer (const char **out_buf, const char **out_buf_end, const char *fmt,...)
void ImFormatStringToTempBufferV (const char **out_buf, const char **out_buf_end, const char *fmt, va_list args)
const char * ImParseFormatFindStart (const char *format)
const char * ImParseFormatFindEnd (const char *format)
const char * ImParseFormatTrimDecorations (const char *format, char *buf, size_t buf_size)
void ImParseFormatSanitizeForPrinting (const char *fmt_in, char *fmt_out, size_t fmt_out_size)
const char * ImParseFormatSanitizeForScanning (const char *fmt_in, char *fmt_out, size_t fmt_out_size)
int ImParseFormatPrecision (const char *format, int default_value)
int ImTextCharToUtf8 (char out_buf[5], unsigned int c)
int ImTextStrToUtf8 (char *out_buf, int out_buf_size, const ImWchar *in_text, const ImWchar *in_text_end)
int ImTextCharFromUtf8 (unsigned int *out_char, const char *in_text, const char *in_text_end)
int ImTextStrFromUtf8 (ImWchar *out_buf, int out_buf_size, const char *in_text, const char *in_text_end, const char **in_remaining=NULL)
int ImTextCountCharsFromUtf8 (const char *in_text, const char *in_text_end)
int ImTextCountUtf8BytesFromChar (const char *in_text, const char *in_text_end)
int ImTextCountUtf8BytesFromStr (const ImWchar *in_text, const ImWchar *in_text_end)
const char * ImTextFindPreviousUtf8Codepoint (const char *in_text_start, const char *in_p)
const char * ImTextFindValidUtf8CodepointEnd (const char *in_text_start, const char *in_text_end, const char *in_p)
int ImTextCountLines (const char *in_text, const char *in_text_end)
ImVec2 ImFontCalcTextSizeEx (ImFont *font, float size, float max_width, float wrap_width, const char *text_begin, const char *text_end_display, const char *text_end, const char **out_remaining, ImVec2 *out_offset, ImDrawTextFlags flags)
const char * ImFontCalcWordWrapPositionEx (ImFont *font, float size, const char *text, const char *text_end, float wrap_width, ImDrawTextFlags flags=0)
const char * ImTextCalcWordWrapNextLineStart (const char *text, const char *text_end, ImDrawTextFlags flags=0)
ImFileHandle ImFileOpen (const char *filename, const char *mode)
bool ImFileClose (ImFileHandle file)
ImU64 ImFileGetSize (ImFileHandle file)
ImU64 ImFileRead (void *data, ImU64 size, ImU64 count, ImFileHandle file)
ImU64 ImFileWrite (const void *data, ImU64 size, ImU64 count, ImFileHandle file)
void * ImFileLoadToMemory (const char *filename, const char *mode, size_t *out_file_size=NULL, int padding_bytes=0)
float ImPow (float x, float y)
double ImPow (double x, double y)
float ImLog (float x)
double ImLog (double x)
int ImAbs (int x)
float ImAbs (float x)
double ImAbs (double x)
float ImSign (float x)
double ImSign (double x)
float ImRsqrt (float x)
double ImRsqrt (double x)
template<typename T >
T ImMin (T lhs, T rhs)
template<typename T >
T ImMax (T lhs, T rhs)
template<typename T >
T ImClamp (T v, T mn, T mx)
template<typename T >
T ImLerp (T a, T b, float t)
template<typename T >
void ImSwap (T &a, T &b)
template<typename T >
T ImAddClampOverflow (T a, T b, T mn, T mx)
template<typename T >
T ImSubClampOverflow (T a, T b, T mn, T mx)
ImVec2 ImMin (const ImVec2 &lhs, const ImVec2 &rhs)
ImVec2 ImMax (const ImVec2 &lhs, const ImVec2 &rhs)
ImVec2 ImClamp (const ImVec2 &v, const ImVec2 &mn, const ImVec2 &mx)
ImVec2 ImLerp (const ImVec2 &a, const ImVec2 &b, float t)
ImVec2 ImLerp (const ImVec2 &a, const ImVec2 &b, const ImVec2 &t)
ImVec4 ImLerp (const ImVec4 &a, const ImVec4 &b, float t)
float ImSaturate (float f)
float ImLengthSqr (const ImVec2 &lhs)
float ImLengthSqr (const ImVec4 &lhs)
float ImInvLength (const ImVec2 &lhs, float fail_value)
float ImTrunc (float f)
ImVec2 ImTrunc (const ImVec2 &v)
float ImFloor (float f)
ImVec2 ImFloor (const ImVec2 &v)
float ImTrunc64 (float f)
float ImRound64 (float f)
int ImModPositive (int a, int b)
float ImDot (const ImVec2 &a, const ImVec2 &b)
ImVec2 ImRotate (const ImVec2 &v, float cos_a, float sin_a)
float ImLinearSweep (float current, float target, float speed)
float ImLinearRemapClamp (float s0, float s1, float d0, float d1, float x)
ImVec2 ImMul (const ImVec2 &lhs, const ImVec2 &rhs)
bool ImIsFloatAboveGuaranteedIntegerPrecision (float f)
float ImExponentialMovingAverage (float avg, float sample, int n)
ImVec2 ImBezierCubicCalc (const ImVec2 &p1, const ImVec2 &p2, const ImVec2 &p3, const ImVec2 &p4, float t)
ImVec2 ImBezierCubicClosestPoint (const ImVec2 &p1, const ImVec2 &p2, const ImVec2 &p3, const ImVec2 &p4, const ImVec2 &p, int num_segments)
ImVec2 ImBezierCubicClosestPointCasteljau (const ImVec2 &p1, const ImVec2 &p2, const ImVec2 &p3, const ImVec2 &p4, const ImVec2 &p, float tess_tol)
ImVec2 ImBezierQuadraticCalc (const ImVec2 &p1, const ImVec2 &p2, const ImVec2 &p3, float t)
ImVec2 ImLineClosestPoint (const ImVec2 &a, const ImVec2 &b, const ImVec2 &p)
bool ImTriangleContainsPoint (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c, const ImVec2 &p)
ImVec2 ImTriangleClosestPoint (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c, const ImVec2 &p)
void ImTriangleBarycentricCoords (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c, const ImVec2 &p, float &out_u, float &out_v, float &out_w)
float ImTriangleArea (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c)
bool ImTriangleIsClockwise (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c)
size_t ImBitArrayGetStorageSizeInBytes (int bitcount)
void ImBitArrayClearAllBits (ImU32 *arr, int bitcount)
bool ImBitArrayTestBit (const ImU32 *arr, int n)
void ImBitArrayClearBit (ImU32 *arr, int n)
void ImBitArraySetBit (ImU32 *arr, int n)
void ImBitArraySetBitRange (ImU32 *arr, int n, int n2)
ImGuiStoragePair * ImLowerBound (ImGuiStoragePair *in_begin, ImGuiStoragePair *in_end, ImGuiID key)
ImGuiIO & ImGui::GetIO (ImGuiContext *)
ImGuiPlatformIO & ImGui::GetPlatformIO (ImGuiContext *ctx)
ImGuiWindow * ImGui::GetCurrentWindowRead ()
ImGuiWindow * ImGui::GetCurrentWindow ()
ImGuiWindow * ImGui::FindWindowByID (ImGuiID id)
ImGuiWindow * ImGui::FindWindowByName (const char *name)
void ImGui::UpdateWindowParentAndRootLinks (ImGuiWindow *window, ImGuiWindowFlags flags, ImGuiWindow *parent_window)
void ImGui::UpdateWindowSkipRefresh (ImGuiWindow *window)
ImVec2 ImGui::CalcWindowNextAutoFitSize (ImGuiWindow *window)
bool ImGui::IsWindowChildOf (ImGuiWindow *window, ImGuiWindow *potential_parent, bool popup_hierarchy)
bool ImGui::IsWindowInBeginStack (ImGuiWindow *window)
bool ImGui::IsWindowWithinBeginStackOf (ImGuiWindow *window, ImGuiWindow *potential_parent)
bool ImGui::IsWindowAbove (ImGuiWindow *potential_above, ImGuiWindow *potential_below)
bool ImGui::IsWindowNavFocusable (ImGuiWindow *window)
void ImGui::SetWindowPos (ImGuiWindow *window, const ImVec2 &pos, ImGuiCond cond=0)
void ImGui::SetWindowSize (ImGuiWindow *window, const ImVec2 &size, ImGuiCond cond=0)
void ImGui::SetWindowCollapsed (ImGuiWindow *window, bool collapsed, ImGuiCond cond=0)
void ImGui::SetWindowHitTestHole (ImGuiWindow *window, const ImVec2 &pos, const ImVec2 &size)
void ImGui::SetWindowHiddenAndSkipItemsForCurrentFrame (ImGuiWindow *window)
void ImGui::SetWindowParentWindowForFocusRoute (ImGuiWindow *window, ImGuiWindow *parent_window)
ImRect ImGui::WindowRectAbsToRel (ImGuiWindow *window, const ImRect &r)
ImRect ImGui::WindowRectRelToAbs (ImGuiWindow *window, const ImRect &r)
ImVec2 ImGui::WindowPosAbsToRel (ImGuiWindow *window, const ImVec2 &p)
ImVec2 ImGui::WindowPosRelToAbs (ImGuiWindow *window, const ImVec2 &p)
void ImGui::FocusWindow (ImGuiWindow *window, ImGuiFocusRequestFlags flags=0)
void ImGui::FocusTopMostWindowUnderOne (ImGuiWindow *under_this_window, ImGuiWindow *ignore_window, ImGuiViewport *filter_viewport, ImGuiFocusRequestFlags flags)
void ImGui::BringWindowToFocusFront (ImGuiWindow *window)
void ImGui::BringWindowToDisplayFront (ImGuiWindow *window)
void ImGui::BringWindowToDisplayBack (ImGuiWindow *window)
void ImGui::BringWindowToDisplayBehind (ImGuiWindow *window, ImGuiWindow *above_window)
int ImGui::FindWindowDisplayIndex (ImGuiWindow *window)
ImGuiWindow * ImGui::FindBottomMostVisibleWindowWithinBeginStack (ImGuiWindow *window)
void ImGui::SetNextWindowRefreshPolicy (ImGuiWindowRefreshFlags flags)
void ImGui::RegisterUserTexture (ImTextureData *tex)
void ImGui::UnregisterUserTexture (ImTextureData *tex)
void ImGui::RegisterFontAtlas (ImFontAtlas *atlas)
void ImGui::UnregisterFontAtlas (ImFontAtlas *atlas)
void ImGui::SetCurrentFont (ImFont *font, float font_size_before_scaling, float font_size_after_scaling)
void ImGui::UpdateCurrentFontSize (float restore_font_size_after_scaling)
void ImGui::SetFontRasterizerDensity (float rasterizer_density)
float ImGui::GetFontRasterizerDensity ()
float ImGui::GetRoundedFontSize (float size)
ImFont * ImGui::GetDefaultFont ()
void ImGui::PushPasswordFont ()
void ImGui::PopPasswordFont ()
ImDrawList * ImGui::GetForegroundDrawList (ImGuiWindow *window)
ImDrawList * ImGui::GetBackgroundDrawList (ImGuiViewport *viewport)
ImDrawList * ImGui::GetForegroundDrawList (ImGuiViewport *viewport)
void ImGui::AddDrawListToDrawDataEx (ImDrawData *draw_data, ImVector< ImDrawList * > *out_list, ImDrawList *draw_list)
void ImGui::Initialize ()
void ImGui::Shutdown ()
void ImGui::SetContextName (ImGuiContext *ctx, const char *name)
ImGuiID ImGui::AddContextHook (ImGuiContext *ctx, const ImGuiContextHook *hook)
void ImGui::RemoveContextHook (ImGuiContext *ctx, ImGuiID hook_to_remove)
void ImGui::CallContextHooks (ImGuiContext *ctx, ImGuiContextHookType type)
void ImGui::UpdateInputEvents (bool trickle_fast_inputs)
void ImGui::UpdateHoveredWindowAndCaptureFlags (const ImVec2 &mouse_pos)
void ImGui::FindHoveredWindowEx (const ImVec2 &pos, bool find_first_and_in_any_viewport, ImGuiWindow **out_hovered_window, ImGuiWindow **out_hovered_window_under_moving_window)
void ImGui::StartMouseMovingWindow (ImGuiWindow *window)
void ImGui::StopMouseMovingWindow ()
void ImGui::UpdateMouseMovingWindowNewFrame ()
void ImGui::UpdateMouseMovingWindowEndFrame ()
void ImGui::ScaleWindowsInViewport (ImGuiViewportP *viewport, float scale)
void ImGui::SetWindowViewport (ImGuiWindow *window, ImGuiViewportP *viewport)
void ImGui::MarkIniSettingsDirty ()
void ImGui::MarkIniSettingsDirty (ImGuiWindow *window)
void ImGui::ClearIniSettings ()
void ImGui::AddSettingsHandler (const ImGuiSettingsHandler *handler)
void ImGui::RemoveSettingsHandler (const char *type_name)
ImGuiSettingsHandler * ImGui::FindSettingsHandler (const char *type_name)
ImGuiWindowSettings * ImGui::CreateNewWindowSettings (const char *name)
ImGuiWindowSettings * ImGui::FindWindowSettingsByID (ImGuiID id)
ImGuiWindowSettings * ImGui::FindWindowSettingsByWindow (ImGuiWindow *window)
void ImGui::ClearWindowSettings (const char *name)
void ImGui::LocalizeRegisterEntries (const ImGuiLocEntry *entries, int count)
const char * ImGui::LocalizeGetMsg (ImGuiLocKey key)
void ImGui::SetScrollX (ImGuiWindow *window, float scroll_x)
void ImGui::SetScrollY (ImGuiWindow *window, float scroll_y)
void ImGui::SetScrollFromPosX (ImGuiWindow *window, float local_x, float center_x_ratio)
void ImGui::SetScrollFromPosY (ImGuiWindow *window, float local_y, float center_y_ratio)
void ImGui::ScrollToItem (ImGuiScrollFlags flags=0)
void ImGui::ScrollToRect (ImGuiWindow *window, const ImRect &rect, ImGuiScrollFlags flags=0)
ImVec2 ImGui::ScrollToRectEx (ImGuiWindow *window, const ImRect &rect, ImGuiScrollFlags flags=0)
void ImGui::ScrollToBringRectIntoView (ImGuiWindow *window, const ImRect &rect)
ImGuiItemStatusFlags ImGui::GetItemStatusFlags ()
ImGuiItemFlags ImGui::GetItemFlags ()
ImGuiID ImGui::GetActiveID ()
ImGuiID ImGui::GetFocusID ()
void ImGui::SetActiveID (ImGuiID id, ImGuiWindow *window)
void ImGui::SetFocusID (ImGuiID id, ImGuiWindow *window)
void ImGui::ClearActiveID ()
ImGuiID ImGui::GetHoveredID ()
void ImGui::SetHoveredID (ImGuiID id)
void ImGui::KeepAliveID (ImGuiID id)
void ImGui::MarkItemEdited (ImGuiID id)
void ImGui::PushOverrideID (ImGuiID id)
ImGuiID ImGui::GetIDWithSeed (const char *str_id_begin, const char *str_id_end, ImGuiID seed)
ImGuiID ImGui::GetIDWithSeed (int n, ImGuiID seed)
void ImGui::ItemSize (const ImVec2 &size, float text_baseline_y=-1.0f)
void ImGui::ItemSize (const ImRect &bb, float text_baseline_y=-1.0f)
bool ImGui::ItemAdd (const ImRect &bb, ImGuiID id, const ImRect *nav_bb=NULL, ImGuiItemFlags extra_flags=0)
bool ImGui::ItemHoverable (const ImRect &bb, ImGuiID id, ImGuiItemFlags item_flags)
bool ImGui::IsWindowContentHoverable (ImGuiWindow *window, ImGuiHoveredFlags flags=0)
bool ImGui::IsClippedEx (const ImRect &bb, ImGuiID id)
void ImGui::SetLastItemData (ImGuiID item_id, ImGuiItemFlags item_flags, ImGuiItemStatusFlags status_flags, const ImRect &item_rect)
ImVec2 ImGui::CalcItemSize (ImVec2 size, float default_w, float default_h)
float ImGui::CalcWrapWidthForPos (const ImVec2 &pos, float wrap_pos_x)
void ImGui::PushMultiItemsWidths (int components, float width_full)
void ImGui::ShrinkWidths (ImGuiShrinkWidthItem *items, int count, float width_excess, float width_min)
void ImGui::CalcClipRectVisibleItemsY (const ImRect &clip_rect, const ImVec2 &pos, float items_height, int *out_visible_start, int *out_visible_end)
const ImGuiStyleVarInfo * ImGui::GetStyleVarInfo (ImGuiStyleVar idx)
void ImGui::BeginDisabledOverrideReenable ()
void ImGui::EndDisabledOverrideReenable ()
void ImGui::LogBegin (ImGuiLogFlags flags, int auto_open_depth)
void ImGui::LogToBuffer (int auto_open_depth=-1)
void ImGui::LogRenderedText (const ImVec2 *ref_pos, const char *text, const char *text_end=NULL)
void ImGui::LogSetNextTextDecoration (const char *prefix, const char *suffix)
bool ImGui::BeginChildEx (const char *name, ImGuiID id, const ImVec2 &size_arg, ImGuiChildFlags child_flags, ImGuiWindowFlags window_flags)
bool ImGui::BeginPopupEx (ImGuiID id, ImGuiWindowFlags extra_window_flags)
bool ImGui::BeginPopupMenuEx (ImGuiID id, const char *label, ImGuiWindowFlags extra_window_flags)
void ImGui::OpenPopupEx (ImGuiID id, ImGuiPopupFlags popup_flags=ImGuiPopupFlags_None)
void ImGui::ClosePopupToLevel (int remaining, bool restore_focus_to_window_under_popup)
void ImGui::ClosePopupsOverWindow (ImGuiWindow *ref_window, bool restore_focus_to_window_under_popup)
void ImGui::ClosePopupsExceptModals ()
bool ImGui::IsPopupOpen (ImGuiID id, ImGuiPopupFlags popup_flags)
ImRect ImGui::GetPopupAllowedExtentRect (ImGuiWindow *window)
ImGuiWindow * ImGui::GetTopMostPopupModal ()
ImGuiWindow * ImGui::GetTopMostAndVisiblePopupModal ()
ImGuiWindow * ImGui::FindBlockingModal (ImGuiWindow *window)
ImVec2 ImGui::FindBestWindowPosForPopup (ImGuiWindow *window)
ImVec2 ImGui::FindBestWindowPosForPopupEx (const ImVec2 &ref_pos, const ImVec2 &size, ImGuiDir *last_dir, const ImRect &r_outer, const ImRect &r_avoid, ImGuiPopupPositionPolicy policy)
bool ImGui::BeginTooltipEx (ImGuiTooltipFlags tooltip_flags, ImGuiWindowFlags extra_window_flags)
bool ImGui::BeginTooltipHidden ()
bool ImGui::BeginViewportSideBar (const char *name, ImGuiViewport *viewport, ImGuiDir dir, float size, ImGuiWindowFlags window_flags)
bool ImGui::BeginMenuEx (const char *label, const char *icon, bool enabled=true)
bool ImGui::MenuItemEx (const char *label, const char *icon, const char *shortcut=NULL, bool selected=false, bool enabled=true)
bool ImGui::BeginComboPopup (ImGuiID popup_id, const ImRect &bb, ImGuiComboFlags flags)
bool ImGui::BeginComboPreview ()
void ImGui::EndComboPreview ()
void ImGui::NavInitWindow (ImGuiWindow *window, bool force_reinit)
void ImGui::NavInitRequestApplyResult ()
bool ImGui::NavMoveRequestButNoResultYet ()
void ImGui::NavMoveRequestSubmit (ImGuiDir move_dir, ImGuiDir clip_dir, ImGuiNavMoveFlags move_flags, ImGuiScrollFlags scroll_flags)
void ImGui::NavMoveRequestForward (ImGuiDir move_dir, ImGuiDir clip_dir, ImGuiNavMoveFlags move_flags, ImGuiScrollFlags scroll_flags)
void ImGui::NavMoveRequestResolveWithLastItem (ImGuiNavItemData *result)
void ImGui::NavMoveRequestResolveWithPastTreeNode (ImGuiNavItemData *result, const ImGuiTreeNodeStackData *tree_node_data)
void ImGui::NavMoveRequestCancel ()
void ImGui::NavMoveRequestApplyResult ()
void ImGui::NavMoveRequestTryWrapping (ImGuiWindow *window, ImGuiNavMoveFlags move_flags)
void ImGui::NavHighlightActivated (ImGuiID id)
void ImGui::NavClearPreferredPosForAxis (ImGuiAxis axis)
void ImGui::SetNavCursorVisibleAfterMove ()
void ImGui::NavUpdateCurrentWindowIsScrollPushableX ()
void ImGui::SetNavWindow (ImGuiWindow *window)
void ImGui::SetNavID (ImGuiID id, ImGuiNavLayer nav_layer, ImGuiID focus_scope_id, const ImRect &rect_rel)
void ImGui::SetNavFocusScope (ImGuiID focus_scope_id)
void ImGui::FocusItem ()
void ImGui::ActivateItemByID (ImGuiID id)
bool ImGui::IsNamedKey (ImGuiKey key)
bool ImGui::IsNamedKeyOrMod (ImGuiKey key)
bool ImGui::IsLegacyKey (ImGuiKey key)
bool ImGui::IsKeyboardKey (ImGuiKey key)
bool ImGui::IsGamepadKey (ImGuiKey key)
bool ImGui::IsMouseKey (ImGuiKey key)
bool ImGui::IsAliasKey (ImGuiKey key)
bool ImGui::IsLRModKey (ImGuiKey key)
ImGuiKeyChord ImGui::FixupKeyChord (ImGuiKeyChord key_chord)
ImGuiKey ImGui::ConvertSingleModFlagToKey (ImGuiKey key)
ImGuiKeyData * ImGui::GetKeyData (ImGuiContext *ctx, ImGuiKey key)
ImGuiKeyData * ImGui::GetKeyData (ImGuiKey key)
const char * ImGui::GetKeyChordName (ImGuiKeyChord key_chord)
ImGuiKey ImGui::MouseButtonToKey (ImGuiMouseButton button)
bool ImGui::IsMouseDragPastThreshold (ImGuiMouseButton button, float lock_threshold=-1.0f)
ImVec2 ImGui::GetKeyMagnitude2d (ImGuiKey key_left, ImGuiKey key_right, ImGuiKey key_up, ImGuiKey key_down)
float ImGui::GetNavTweakPressedAmount (ImGuiAxis axis)
int ImGui::CalcTypematicRepeatAmount (float t0, float t1, float repeat_delay, float repeat_rate)
void ImGui::GetTypematicRepeatRate (ImGuiInputFlags flags, float *repeat_delay, float *repeat_rate)
void ImGui::TeleportMousePos (const ImVec2 &pos)
void ImGui::SetActiveIdUsingAllKeyboardKeys ()
bool ImGui::IsActiveIdUsingNavDir (ImGuiDir dir)
ImGuiID ImGui::GetKeyOwner (ImGuiKey key)
void ImGui::SetKeyOwner (ImGuiKey key, ImGuiID owner_id, ImGuiInputFlags flags=0)
void ImGui::SetKeyOwnersForKeyChord (ImGuiKeyChord key, ImGuiID owner_id, ImGuiInputFlags flags=0)
void ImGui::SetItemKeyOwner (ImGuiKey key, ImGuiInputFlags flags)
bool ImGui::TestKeyOwner (ImGuiKey key, ImGuiID owner_id)
ImGuiKeyOwnerData * ImGui::GetKeyOwnerData (ImGuiContext *ctx, ImGuiKey key)
bool ImGui::IsKeyDown (ImGuiKey key, ImGuiID owner_id)
bool ImGui::IsKeyPressed (ImGuiKey key, ImGuiInputFlags flags, ImGuiID owner_id=0)
bool ImGui::IsKeyReleased (ImGuiKey key, ImGuiID owner_id)
bool ImGui::IsKeyChordPressed (ImGuiKeyChord key_chord, ImGuiInputFlags flags, ImGuiID owner_id=0)
bool ImGui::IsMouseDown (ImGuiMouseButton button, ImGuiID owner_id)
bool ImGui::IsMouseClicked (ImGuiMouseButton button, ImGuiInputFlags flags, ImGuiID owner_id=0)
bool ImGui::IsMouseReleased (ImGuiMouseButton button, ImGuiID owner_id)
bool ImGui::IsMouseDoubleClicked (ImGuiMouseButton button, ImGuiID owner_id)
bool ImGui::Shortcut (ImGuiKeyChord key_chord, ImGuiInputFlags flags, ImGuiID owner_id)
bool ImGui::SetShortcutRouting (ImGuiKeyChord key_chord, ImGuiInputFlags flags, ImGuiID owner_id)
bool ImGui::TestShortcutRouting (ImGuiKeyChord key_chord, ImGuiID owner_id)
ImGuiKeyRoutingData * ImGui::GetShortcutRoutingData (ImGuiKeyChord key_chord)
void ImGui::PushFocusScope (ImGuiID id)
void ImGui::PopFocusScope ()
ImGuiID ImGui::GetCurrentFocusScope ()
bool ImGui::IsDragDropActive ()
bool ImGui::BeginDragDropTargetCustom (const ImRect &bb, ImGuiID id)
bool ImGui::BeginDragDropTargetViewport (ImGuiViewport *viewport, const ImRect *p_bb=NULL)
void ImGui::ClearDragDrop ()
bool ImGui::IsDragDropPayloadBeingAccepted ()
void ImGui::RenderDragDropTargetRectForItem (const ImRect &bb)
void ImGui::RenderDragDropTargetRectEx (ImDrawList *draw_list, const ImRect &bb)
ImGuiTypingSelectRequest * ImGui::GetTypingSelectRequest (ImGuiTypingSelectFlags flags=ImGuiTypingSelectFlags_None)
int ImGui::TypingSelectFindMatch (ImGuiTypingSelectRequest *req, int items_count, const char *(*get_item_name_func)(void *, int), void *user_data, int nav_item_idx)
int ImGui::TypingSelectFindNextSingleCharMatch (ImGuiTypingSelectRequest *req, int items_count, const char *(*get_item_name_func)(void *, int), void *user_data, int nav_item_idx)
int ImGui::TypingSelectFindBestLeadingMatch (ImGuiTypingSelectRequest *req, int items_count, const char *(*get_item_name_func)(void *, int), void *user_data)
bool ImGui::BeginBoxSelect (const ImRect &scope_rect, ImGuiWindow *window, ImGuiID box_select_id, ImGuiMultiSelectFlags ms_flags)
void ImGui::EndBoxSelect (const ImRect &scope_rect, ImGuiMultiSelectFlags ms_flags)
void ImGui::MultiSelectItemHeader (ImGuiID id, bool *p_selected, ImGuiButtonFlags *p_button_flags)
void ImGui::MultiSelectItemFooter (ImGuiID id, bool *p_selected, bool *p_pressed)
void ImGui::MultiSelectAddSetAll (ImGuiMultiSelectTempData *ms, bool selected)
void ImGui::MultiSelectAddSetRange (ImGuiMultiSelectTempData *ms, bool selected, int range_dir, ImGuiSelectionUserData first_item, ImGuiSelectionUserData last_item)
ImGuiBoxSelectState * ImGui::GetBoxSelectState (ImGuiID id)
ImGuiMultiSelectState * ImGui::GetMultiSelectState (ImGuiID id)
void ImGui::SetWindowClipRectBeforeSetChannel (ImGuiWindow *window, const ImRect &clip_rect)
void ImGui::BeginColumns (const char *str_id, int count, ImGuiOldColumnFlags flags=0)
void ImGui::EndColumns ()
void ImGui::PushColumnClipRect (int column_index)
void ImGui::PushColumnsBackground ()
void ImGui::PopColumnsBackground ()
ImGuiID ImGui::GetColumnsID (const char *str_id, int count)
ImGuiOldColumns * ImGui::FindOrCreateColumns (ImGuiWindow *window, ImGuiID id)
float ImGui::GetColumnOffsetFromNorm (const ImGuiOldColumns *columns, float offset_norm)
float ImGui::GetColumnNormFromOffset (const ImGuiOldColumns *columns, float offset)
void ImGui::TableOpenContextMenu (int column_n=-1)
void ImGui::TableSetColumnWidth (int column_n, float width)
void ImGui::TableSetColumnSortDirection (int column_n, ImGuiSortDirection sort_direction, bool append_to_sort_specs)
int ImGui::TableGetHoveredRow ()
float ImGui::TableGetHeaderRowHeight ()
float ImGui::TableGetHeaderAngledMaxLabelWidth ()
void ImGui::TablePushBackgroundChannel ()
void ImGui::TablePopBackgroundChannel ()
void ImGui::TablePushColumnChannel (int column_n)
void ImGui::TablePopColumnChannel ()
void ImGui::TableAngledHeadersRowEx (ImGuiID row_id, float angle, float max_label_width, const ImGuiTableHeaderData *data, int data_count)
ImGuiTable * ImGui::GetCurrentTable ()
ImGuiTable * ImGui::TableFindByID (ImGuiID id)
bool ImGui::BeginTableEx (const char *name, ImGuiID id, int columns_count, ImGuiTableFlags flags=0, const ImVec2 &outer_size=ImVec2(0, 0), float inner_width=0.0f)
void ImGui::TableBeginInitMemory (ImGuiTable *table, int columns_count)
void ImGui::TableBeginApplyRequests (ImGuiTable *table)
void ImGui::TableSetupDrawChannels (ImGuiTable *table)
void ImGui::TableUpdateLayout (ImGuiTable *table)
void ImGui::TableUpdateBorders (ImGuiTable *table)
void ImGui::TableUpdateColumnsWeightFromWidth (ImGuiTable *table)
void ImGui::TableDrawBorders (ImGuiTable *table)
void ImGui::TableDrawDefaultContextMenu (ImGuiTable *table, ImGuiTableFlags flags_for_section_to_display)
bool ImGui::TableBeginContextMenuPopup (ImGuiTable *table)
void ImGui::TableMergeDrawChannels (ImGuiTable *table)
ImGuiTableInstanceData * ImGui::TableGetInstanceData (ImGuiTable *table, int instance_no)
ImGuiID ImGui::TableGetInstanceID (ImGuiTable *table, int instance_no)
void ImGui::TableFixDisplayOrder (ImGuiTable *table)
void ImGui::TableSortSpecsSanitize (ImGuiTable *table)
void ImGui::TableSortSpecsBuild (ImGuiTable *table)
ImGuiSortDirection ImGui::TableGetColumnNextSortDirection (ImGuiTableColumn *column)
void ImGui::TableFixColumnSortDirection (ImGuiTable *table, ImGuiTableColumn *column)
float ImGui::TableGetColumnWidthAuto (ImGuiTable *table, ImGuiTableColumn *column)
void ImGui::TableBeginRow (ImGuiTable *table)
void ImGui::TableEndRow (ImGuiTable *table)
void ImGui::TableBeginCell (ImGuiTable *table, int column_n)
void ImGui::TableEndCell (ImGuiTable *table)
ImRect ImGui::TableGetCellBgRect (const ImGuiTable *table, int column_n)
const char * ImGui::TableGetColumnName (const ImGuiTable *table, int column_n)
ImGuiID ImGui::TableGetColumnResizeID (ImGuiTable *table, int column_n, int instance_no=0)
float ImGui::TableCalcMaxColumnWidth (const ImGuiTable *table, int column_n)
void ImGui::TableSetColumnWidthAutoSingle (ImGuiTable *table, int column_n)
void ImGui::TableSetColumnWidthAutoAll (ImGuiTable *table)
void ImGui::TableRemove (ImGuiTable *table)
void ImGui::TableGcCompactTransientBuffers (ImGuiTable *table)
void ImGui::TableGcCompactTransientBuffers (ImGuiTableTempData *table)
void ImGui::TableGcCompactSettings ()
void ImGui::TableLoadSettings (ImGuiTable *table)
void ImGui::TableSaveSettings (ImGuiTable *table)
void ImGui::TableResetSettings (ImGuiTable *table)
ImGuiTableSettings * ImGui::TableGetBoundSettings (ImGuiTable *table)
void ImGui::TableSettingsAddSettingsHandler ()
ImGuiTableSettings * ImGui::TableSettingsCreate (ImGuiID id, int columns_count)
ImGuiTableSettings * ImGui::TableSettingsFindByID (ImGuiID id)
ImGuiTabBar * ImGui::GetCurrentTabBar ()
ImGuiTabBar * ImGui::TabBarFindByID (ImGuiID id)
void ImGui::TabBarRemove (ImGuiTabBar *tab_bar)
bool ImGui::BeginTabBarEx (ImGuiTabBar *tab_bar, const ImRect &bb, ImGuiTabBarFlags flags)
ImGuiTabItem * ImGui::TabBarFindTabByID (ImGuiTabBar *tab_bar, ImGuiID tab_id)
ImGuiTabItem * ImGui::TabBarFindTabByOrder (ImGuiTabBar *tab_bar, int order)
ImGuiTabItem * ImGui::TabBarGetCurrentTab (ImGuiTabBar *tab_bar)
int ImGui::TabBarGetTabOrder (ImGuiTabBar *tab_bar, ImGuiTabItem *tab)
const char * ImGui::TabBarGetTabName (ImGuiTabBar *tab_bar, ImGuiTabItem *tab)
void ImGui::TabBarRemoveTab (ImGuiTabBar *tab_bar, ImGuiID tab_id)
void ImGui::TabBarCloseTab (ImGuiTabBar *tab_bar, ImGuiTabItem *tab)
void ImGui::TabBarQueueFocus (ImGuiTabBar *tab_bar, ImGuiTabItem *tab)
void ImGui::TabBarQueueFocus (ImGuiTabBar *tab_bar, const char *tab_name)
void ImGui::TabBarQueueReorder (ImGuiTabBar *tab_bar, ImGuiTabItem *tab, int offset)
void ImGui::TabBarQueueReorderFromMousePos (ImGuiTabBar *tab_bar, ImGuiTabItem *tab, ImVec2 mouse_pos)
bool ImGui::TabBarProcessReorder (ImGuiTabBar *tab_bar)
bool ImGui::TabItemEx (ImGuiTabBar *tab_bar, const char *label, bool *p_open, ImGuiTabItemFlags flags, ImGuiWindow *docked_window)
void ImGui::TabItemSpacing (const char *str_id, ImGuiTabItemFlags flags, float width)
ImVec2 ImGui::TabItemCalcSize (const char *label, bool has_close_button_or_unsaved_marker)
ImVec2 ImGui::TabItemCalcSize (ImGuiWindow *window)
void ImGui::TabItemBackground (ImDrawList *draw_list, const ImRect &bb, ImGuiTabItemFlags flags, ImU32 col)
void ImGui::TabItemLabelAndCloseButton (ImDrawList *draw_list, const ImRect &bb, ImGuiTabItemFlags flags, ImVec2 frame_padding, const char *label, ImGuiID tab_id, ImGuiID close_button_id, bool is_contents_visible, bool *out_just_closed, bool *out_text_clipped)
void ImGui::RenderText (ImVec2 pos, const char *text, const char *text_end=NULL, bool hide_text_after_hash=true)
void ImGui::RenderTextWrapped (ImVec2 pos, const char *text, const char *text_end, float wrap_width)
void ImGui::RenderTextClipped (const ImVec2 &pos_min, const ImVec2 &pos_max, const char *text, const char *text_end, const ImVec2 *text_size_if_known, const ImVec2 &align=ImVec2(0, 0), const ImRect *clip_rect=NULL)
void ImGui::RenderTextClippedEx (ImDrawList *draw_list, const ImVec2 &pos_min, const ImVec2 &pos_max, const char *text, const char *text_end, const ImVec2 *text_size_if_known, const ImVec2 &align=ImVec2(0, 0), const ImRect *clip_rect=NULL)
void ImGui::RenderTextEllipsis (ImDrawList *draw_list, const ImVec2 &pos_min, const ImVec2 &pos_max, float ellipsis_max_x, const char *text, const char *text_end, const ImVec2 *text_size_if_known)
void ImGui::RenderFrame (ImVec2 p_min, ImVec2 p_max, ImU32 fill_col, bool borders=true, float rounding=0.0f)
void ImGui::RenderFrameBorder (ImVec2 p_min, ImVec2 p_max, float rounding=0.0f)
void ImGui::RenderColorComponentMarker (const ImRect &bb, ImU32 col, float rounding)
void ImGui::RenderColorRectWithAlphaCheckerboard (ImDrawList *draw_list, ImVec2 p_min, ImVec2 p_max, ImU32 fill_col, float grid_step, ImVec2 grid_off, float rounding=0.0f, ImDrawFlags flags=0)
void ImGui::RenderNavCursor (const ImRect &bb, ImGuiID id, ImGuiNavRenderCursorFlags flags=ImGuiNavRenderCursorFlags_None)
void ImGui::RenderNavHighlight (const ImRect &bb, ImGuiID id, ImGuiNavRenderCursorFlags flags=ImGuiNavRenderCursorFlags_None)
const char * ImGui::FindRenderedTextEnd (const char *text, const char *text_end=NULL)
void ImGui::RenderMouseCursor (ImVec2 pos, float scale, ImGuiMouseCursor mouse_cursor, ImU32 col_fill, ImU32 col_border, ImU32 col_shadow)
void ImGui::RenderArrow (ImDrawList *draw_list, ImVec2 pos, ImU32 col, ImGuiDir dir, float scale=1.0f)
void ImGui::RenderBullet (ImDrawList *draw_list, ImVec2 pos, ImU32 col)
void ImGui::RenderCheckMark (ImDrawList *draw_list, ImVec2 pos, ImU32 col, float sz)
void ImGui::RenderArrowPointingAt (ImDrawList *draw_list, ImVec2 pos, ImVec2 half_sz, ImGuiDir direction, ImU32 col)
void ImGui::RenderRectFilledInRangeH (ImDrawList *draw_list, const ImRect &rect, ImU32 col, float fill_x0, float fill_x1, float rounding)
void ImGui::RenderRectFilledWithHole (ImDrawList *draw_list, const ImRect &outer, const ImRect &inner, ImU32 col, float rounding)
void ImGui::TextEx (const char *text, const char *text_end=NULL, ImGuiTextFlags flags=0)
void ImGui::TextAligned (float align_x, float size_x, const char *fmt,...)
void ImGui::TextAlignedV (float align_x, float size_x, const char *fmt, va_list args)
bool ImGui::ButtonEx (const char *label, const ImVec2 &size_arg=ImVec2(0, 0), ImGuiButtonFlags flags=0)
bool ImGui::ArrowButtonEx (const char *str_id, ImGuiDir dir, ImVec2 size_arg, ImGuiButtonFlags flags=0)
bool ImGui::ImageButtonEx (ImGuiID id, ImTextureRef tex_ref, const ImVec2 &image_size, const ImVec2 &uv0, const ImVec2 &uv1, const ImVec4 &bg_col, const ImVec4 &tint_col, ImGuiButtonFlags flags=0)
void ImGui::SeparatorEx (ImGuiSeparatorFlags flags, float thickness=1.0f)
void ImGui::SeparatorTextEx (ImGuiID id, const char *label, const char *label_end, float extra_width)
bool ImGui::CheckboxFlags (const char *label, ImS64 *flags, ImS64 flags_value)
bool ImGui::CheckboxFlags (const char *label, ImU64 *flags, ImU64 flags_value)
bool ImGui::CloseButton (ImGuiID id, const ImVec2 &pos)
bool ImGui::CollapseButton (ImGuiID id, const ImVec2 &pos)
void ImGui::Scrollbar (ImGuiAxis axis)
bool ImGui::ScrollbarEx (const ImRect &bb, ImGuiID id, ImGuiAxis axis, ImS64 *p_scroll_v, ImS64 avail_v, ImS64 contents_v, ImDrawFlags draw_rounding_flags=0)
ImRect ImGui::GetWindowScrollbarRect (ImGuiWindow *window, ImGuiAxis axis)
ImGuiID ImGui::GetWindowScrollbarID (ImGuiWindow *window, ImGuiAxis axis)
ImGuiID ImGui::GetWindowResizeCornerID (ImGuiWindow *window, int n)
ImGuiID ImGui::GetWindowResizeBorderID (ImGuiWindow *window, ImGuiDir dir)
bool ImGui::ButtonBehavior (const ImRect &bb, ImGuiID id, bool *out_hovered, bool *out_held, ImGuiButtonFlags flags=0)
bool ImGui::DragBehavior (ImGuiID id, ImGuiDataType data_type, void *p_v, float v_speed, const void *p_min, const void *p_max, const char *format, ImGuiSliderFlags flags)
bool ImGui::SliderBehavior (const ImRect &bb, ImGuiID id, ImGuiDataType data_type, void *p_v, const void *p_min, const void *p_max, const char *format, ImGuiSliderFlags flags, ImRect *out_grab_bb)
bool ImGui::SplitterBehavior (const ImRect &bb, ImGuiID id, ImGuiAxis axis, float *size1, float *size2, float min_size1, float min_size2, float hover_extend=0.0f, float hover_visibility_delay=0.0f, ImU32 bg_col=0)
bool ImGui::TreeNodeBehavior (ImGuiID id, ImGuiTreeNodeFlags flags, const char *label, const char *label_end=NULL)
void ImGui::TreeNodeDrawLineToChildNode (const ImVec2 &target_pos)
void ImGui::TreeNodeDrawLineToTreePop (const ImGuiTreeNodeStackData *data)
void ImGui::TreePushOverrideID (ImGuiID id)
bool ImGui::TreeNodeGetOpen (ImGuiID storage_id)
void ImGui::TreeNodeSetOpen (ImGuiID storage_id, bool open)
bool ImGui::TreeNodeUpdateNextOpen (ImGuiID storage_id, ImGuiTreeNodeFlags flags)
template<typename T , typename SIGNED_T , typename FLOAT_T >
float ImGui::ScaleRatioFromValueT (ImGuiDataType data_type, T v, T v_min, T v_max, bool is_logarithmic, float logarithmic_zero_epsilon, float zero_deadzone_size)
template<typename T , typename SIGNED_T , typename FLOAT_T >
T ImGui::ScaleValueFromRatioT (ImGuiDataType data_type, float t, T v_min, T v_max, bool is_logarithmic, float logarithmic_zero_epsilon, float zero_deadzone_size)
template<typename T , typename SIGNED_T , typename FLOAT_T >
bool ImGui::DragBehaviorT (ImGuiDataType data_type, T *v, float v_speed, T v_min, T v_max, const char *format, ImGuiSliderFlags flags)
template<typename T , typename SIGNED_T , typename FLOAT_T >
bool ImGui::SliderBehaviorT (const ImRect &bb, ImGuiID id, ImGuiDataType data_type, T *v, T v_min, T v_max, const char *format, ImGuiSliderFlags flags, ImRect *out_grab_bb)
template<typename T >
T ImGui::RoundScalarWithFormatT (const char *format, ImGuiDataType data_type, T v)
template<typename T >
bool ImGui::CheckboxFlagsT (const char *label, T *flags, T flags_value)
const ImGuiDataTypeInfo * ImGui::DataTypeGetInfo (ImGuiDataType data_type)
int ImGui::DataTypeFormatString (char *buf, int buf_size, ImGuiDataType data_type, const void *p_data, const char *format)
void ImGui::DataTypeApplyOp (ImGuiDataType data_type, int op, void *output, const void *arg_1, const void *arg_2)
bool ImGui::DataTypeApplyFromText (const char *buf, ImGuiDataType data_type, void *p_data, const char *format, void *p_data_when_empty=NULL)
int ImGui::DataTypeCompare (ImGuiDataType data_type, const void *arg_1, const void *arg_2)
bool ImGui::DataTypeClamp (ImGuiDataType data_type, void *p_data, const void *p_min, const void *p_max)
bool ImGui::DataTypeIsZero (ImGuiDataType data_type, const void *p_data)
bool ImGui::InputTextEx (const char *label, const char *hint, char *buf, int buf_size, const ImVec2 &size_arg, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback=NULL, void *user_data=NULL)
void ImGui::InputTextDeactivateHook (ImGuiID id)
bool ImGui::TempInputText (const ImRect &bb, ImGuiID id, const char *label, char *buf, int buf_size, ImGuiInputTextFlags flags)
bool ImGui::TempInputScalar (const ImRect &bb, ImGuiID id, const char *label, ImGuiDataType data_type, void *p_data, const char *format, const void *p_clamp_min=NULL, const void *p_clamp_max=NULL)
bool ImGui::TempInputIsActive (ImGuiID id)
ImGuiInputTextState * ImGui::GetInputTextState (ImGuiID id)
void ImGui::SetNextItemRefVal (ImGuiDataType data_type, void *p_data)
bool ImGui::IsItemActiveAsInputText ()
void ImGui::ColorTooltip (const char *text, const float *col, ImGuiColorEditFlags flags)
void ImGui::ColorEditOptionsPopup (const float *col, ImGuiColorEditFlags flags)
void ImGui::ColorPickerOptionsPopup (const float *ref_col, ImGuiColorEditFlags flags)
void ImGui::SetNextItemColorMarker (ImU32 col)
int ImGui::PlotEx (ImGuiPlotType plot_type, const char *label, float(*values_getter)(void *data, int idx), void *data, int values_count, int values_offset, const char *overlay_text, float scale_min, float scale_max, const ImVec2 &size_arg)
void ImGui::ShadeVertsLinearColorGradientKeepAlpha (ImDrawList *draw_list, int vert_start_idx, int vert_end_idx, ImVec2 gradient_p0, ImVec2 gradient_p1, ImU32 col0, ImU32 col1)
void ImGui::ShadeVertsLinearUV (ImDrawList *draw_list, int vert_start_idx, int vert_end_idx, const ImVec2 &a, const ImVec2 &b, const ImVec2 &uv_a, const ImVec2 &uv_b, bool clamp)
void ImGui::ShadeVertsTransformPos (ImDrawList *draw_list, int vert_start_idx, int vert_end_idx, const ImVec2 &pivot_in, float cos_a, float sin_a, const ImVec2 &pivot_out)
void ImGui::GcCompactTransientMiscBuffers ()
void ImGui::GcCompactTransientWindowBuffers (ImGuiWindow *window)
void ImGui::GcAwakeTransientWindowBuffers (ImGuiWindow *window)
bool ImGui::ErrorLog (const char *msg)
void ImGui::ErrorRecoveryStoreState (ImGuiErrorRecoveryState *state_out)
void ImGui::ErrorRecoveryTryToRecoverState (const ImGuiErrorRecoveryState *state_in)
void ImGui::ErrorRecoveryTryToRecoverWindowState (const ImGuiErrorRecoveryState *state_in)
void ImGui::ErrorCheckUsingSetCursorPosToExtendParentBoundaries ()
void ImGui::ErrorCheckEndFrameFinalizeErrorTooltip ()
bool ImGui::BeginErrorTooltip ()
void ImGui::EndErrorTooltip ()
void ImGui::DebugAllocHook (ImGuiDebugAllocInfo *info, int frame_count, void *ptr, size_t size)
void ImGui::DebugDrawCursorPos (ImU32 col=(((ImU32)(255)<< 24)|((ImU32)(0)<< 16)|((ImU32)(0)<< 8)|((ImU32)(255)<< 0)))
void ImGui::DebugDrawLineExtents (ImU32 col=(((ImU32)(255)<< 24)|((ImU32)(0)<< 16)|((ImU32)(0)<< 8)|((ImU32)(255)<< 0)))
void ImGui::DebugDrawItemRect (ImU32 col=(((ImU32)(255)<< 24)|((ImU32)(0)<< 16)|((ImU32)(0)<< 8)|((ImU32)(255)<< 0)))
void ImGui::DebugTextUnformattedWithLocateItem (const char *line_begin, const char *line_end)
void ImGui::DebugLocateItem (ImGuiID target_id)
void ImGui::DebugLocateItemOnHover (ImGuiID target_id)
void ImGui::DebugLocateItemResolveWithLastItem ()
void ImGui::DebugBreakClearData ()
bool ImGui::DebugBreakButton (const char *label, const char *description_of_location)
void ImGui::DebugBreakButtonTooltip (bool keyboard_only, const char *description_of_location)
void ImGui::ShowFontAtlas (ImFontAtlas *atlas)
ImU64 ImGui::DebugTextureIDToU64 (ImTextureID tex_id)
void ImGui::DebugHookIdInfo (ImGuiID id, ImGuiDataType data_type, const void *data_id, const void *data_id_end)
void ImGui::DebugNodeColumns (ImGuiOldColumns *columns)
void ImGui::DebugNodeDrawList (ImGuiWindow *window, ImGuiViewportP *viewport, const ImDrawList *draw_list, const char *label)
void ImGui::DebugNodeDrawCmdShowMeshAndBoundingBox (ImDrawList *out_draw_list, const ImDrawList *draw_list, const ImDrawCmd *draw_cmd, bool show_mesh, bool show_aabb)
void ImGui::DebugNodeFont (ImFont *font)
void ImGui::DebugNodeFontGlyphesForSrcMask (ImFont *font, ImFontBaked *baked, int src_mask)
void ImGui::DebugNodeFontGlyph (ImFont *font, const ImFontGlyph *glyph)
void ImGui::DebugNodeTexture (ImTextureData *tex, int int_id, const ImFontAtlasRect *highlight_rect=NULL)
void ImGui::DebugNodeStorage (ImGuiStorage *storage, const char *label)
void ImGui::DebugNodeTabBar (ImGuiTabBar *tab_bar, const char *label)
void ImGui::DebugNodeTable (ImGuiTable *table)
void ImGui::DebugNodeTableSettings (ImGuiTableSettings *settings)
void ImGui::DebugNodeInputTextState (ImGuiInputTextState *state)
void ImGui::DebugNodeTypingSelectState (ImGuiTypingSelectState *state)
void ImGui::DebugNodeMultiSelectState (ImGuiMultiSelectState *state)
void ImGui::DebugNodeWindow (ImGuiWindow *window, const char *label)
void ImGui::DebugNodeWindowSettings (ImGuiWindowSettings *settings)
void ImGui::DebugNodeWindowsList (ImVector< ImGuiWindow * > *windows, const char *label)
void ImGui::DebugNodeWindowsListByBeginStackParent (ImGuiWindow **windows, int windows_size, ImGuiWindow *parent_in_begin_stack)
void ImGui::DebugNodeViewport (ImGuiViewportP *viewport)
void ImGui::DebugRenderKeyboardPreview (ImDrawList *draw_list)
void ImGui::DebugRenderViewportThumbnail (ImDrawList *draw_list, ImGuiViewportP *viewport, const ImRect &bb)
const ImFontLoader * ImFontAtlasGetFontLoaderForStbTruetype ()
bool operator== (const ImTextureRef &lhs, const ImTextureRef &rhs)
bool operator!= (const ImTextureRef &lhs, const ImTextureRef &rhs)
int ImFontAtlasRectId_GetIndex (ImFontAtlasRectId id)
unsigned int ImFontAtlasRectId_GetGeneration (ImFontAtlasRectId id)
ImFontAtlasRectId ImFontAtlasRectId_Make (int index_idx, int gen_idx)
void ImFontAtlasBuildInit (ImFontAtlas *atlas)
void ImFontAtlasBuildDestroy (ImFontAtlas *atlas)
void ImFontAtlasBuildMain (ImFontAtlas *atlas)
void ImFontAtlasBuildSetupFontLoader (ImFontAtlas *atlas, const ImFontLoader *font_loader)
void ImFontAtlasBuildNotifySetFont (ImFontAtlas *atlas, ImFont *old_font, ImFont *new_font)
void ImFontAtlasBuildUpdatePointers (ImFontAtlas *atlas)
void ImFontAtlasBuildRenderBitmapFromString (ImFontAtlas *atlas, int x, int y, int w, int h, const char *in_str, char in_marker_char)
void ImFontAtlasBuildClear (ImFontAtlas *atlas)
ImTextureData * ImFontAtlasTextureAdd (ImFontAtlas *atlas, int w, int h)
void ImFontAtlasTextureMakeSpace (ImFontAtlas *atlas)
void ImFontAtlasTextureRepack (ImFontAtlas *atlas, int w, int h)
void ImFontAtlasTextureGrow (ImFontAtlas *atlas, int old_w=-1, int old_h=-1)
void ImFontAtlasTextureCompact (ImFontAtlas *atlas)
ImVec2i ImFontAtlasTextureGetSizeEstimate (ImFontAtlas *atlas)
void ImFontAtlasBuildSetupFontSpecialGlyphs (ImFontAtlas *atlas, ImFont *font, ImFontConfig *src)
void ImFontAtlasBuildLegacyPreloadAllGlyphRanges (ImFontAtlas *atlas)
void ImFontAtlasBuildGetOversampleFactors (ImFontConfig *src, ImFontBaked *baked, int *out_oversample_h, int *out_oversample_v)
void ImFontAtlasBuildDiscardBakes (ImFontAtlas *atlas, int unused_frames)
bool ImFontAtlasFontSourceInit (ImFontAtlas *atlas, ImFontConfig *src)
void ImFontAtlasFontSourceAddToFont (ImFontAtlas *atlas, ImFont *font, ImFontConfig *src)
void ImFontAtlasFontDestroySourceData (ImFontAtlas *atlas, ImFontConfig *src)
bool ImFontAtlasFontInitOutput (ImFontAtlas *atlas, ImFont *font)
void ImFontAtlasFontDestroyOutput (ImFontAtlas *atlas, ImFont *font)
void ImFontAtlasFontDiscardBakes (ImFontAtlas *atlas, ImFont *font, int unused_frames)
ImGuiID ImFontAtlasBakedGetId (ImGuiID font_id, float baked_size, float rasterizer_density)
ImFontBaked * ImFontAtlasBakedGetOrAdd (ImFontAtlas *atlas, ImFont *font, float font_size, float font_rasterizer_density)
ImFontBaked * ImFontAtlasBakedGetClosestMatch (ImFontAtlas *atlas, ImFont *font, float font_size, float font_rasterizer_density)
ImFontBaked * ImFontAtlasBakedAdd (ImFontAtlas *atlas, ImFont *font, float font_size, float font_rasterizer_density, ImGuiID baked_id)
void ImFontAtlasBakedDiscard (ImFontAtlas *atlas, ImFont *font, ImFontBaked *baked)
ImFontGlyph * ImFontAtlasBakedAddFontGlyph (ImFontAtlas *atlas, ImFontBaked *baked, ImFontConfig *src, const ImFontGlyph *in_glyph)
void ImFontAtlasBakedAddFontGlyphAdvancedX (ImFontAtlas *atlas, ImFontBaked *baked, ImFontConfig *src, ImWchar codepoint, float advance_x)
void ImFontAtlasBakedDiscardFontGlyph (ImFontAtlas *atlas, ImFont *font, ImFontBaked *baked, ImFontGlyph *glyph)
void ImFontAtlasBakedSetFontGlyphBitmap (ImFontAtlas *atlas, ImFontBaked *baked, ImFontConfig *src, ImFontGlyph *glyph, ImTextureRect *r, const unsigned char *src_pixels, ImTextureFormat src_fmt, int src_pitch)
void ImFontAtlasPackInit (ImFontAtlas *atlas)
ImFontAtlasRectId ImFontAtlasPackAddRect (ImFontAtlas *atlas, int w, int h, ImFontAtlasRectEntry *overwrite_entry=NULL)
ImTextureRect * ImFontAtlasPackGetRect (ImFontAtlas *atlas, ImFontAtlasRectId id)
ImTextureRect * ImFontAtlasPackGetRectSafe (ImFontAtlas *atlas, ImFontAtlasRectId id)
void ImFontAtlasPackDiscardRect (ImFontAtlas *atlas, ImFontAtlasRectId id)
void ImFontAtlasUpdateNewFrame (ImFontAtlas *atlas, int frame_count, bool renderer_has_textures)
void ImFontAtlasAddDrawListSharedData (ImFontAtlas *atlas, ImDrawListSharedData *data)
void ImFontAtlasRemoveDrawListSharedData (ImFontAtlas *atlas, ImDrawListSharedData *data)
void ImFontAtlasUpdateDrawListsTextures (ImFontAtlas *atlas, ImTextureRef old_tex, ImTextureRef new_tex)
void ImFontAtlasUpdateDrawListsSharedData (ImFontAtlas *atlas)
void ImFontAtlasTextureBlockConvert (const unsigned char *src_pixels, ImTextureFormat src_fmt, int src_pitch, unsigned char *dst_pixels, ImTextureFormat dst_fmt, int dst_pitch, int w, int h)
void ImFontAtlasTextureBlockPostProcess (ImFontAtlasPostProcessData *data)
void ImFontAtlasTextureBlockPostProcessMultiply (ImFontAtlasPostProcessData *data, float multiply_factor)
void ImFontAtlasTextureBlockFill (ImTextureData *dst_tex, int dst_x, int dst_y, int w, int h, ImU32 col)
void ImFontAtlasTextureBlockCopy (ImTextureData *src_tex, int src_x, int src_y, ImTextureData *dst_tex, int dst_x, int dst_y, int w, int h)
void ImFontAtlasTextureBlockQueueUpload (ImFontAtlas *atlas, ImTextureData *tex, int x, int y, int w, int h)
int ImTextureDataGetFormatBytesPerPixel (ImTextureFormat format)
const char * ImTextureDataGetStatusName (ImTextureStatus status)
const char * ImTextureDataGetFormatName (ImTextureFormat format)
void ImFontAtlasDebugLogTextureRequests (ImFontAtlas *atlas)
bool ImFontAtlasGetMouseCursorTexData (ImFontAtlas *atlas, ImGuiMouseCursor cursor_type, ImVec2 *out_offset, ImVec2 *out_size, ImVec2 out_uv_border[2], ImVec2 out_uv_fill[2])
Variables
ImGuiContext * GImGui
Macro Definition Documentation
IM_ASSERT_PARANOID
#define IM_ASSERT_PARANOID (_EXPR)
Definition at line 263 of file imgui_internal.h.
IM_ASSERT_USER_ERROR
#define IM_ASSERT_USER_ERROR (_EXPR, _MSG) do { if (!(_EXPR) && ImGui::ErrorLog(_MSG)) { IM_ASSERT((_EXPR) && _MSG); } } while (0)
Definition at line 2053 of file imgui_internal.h.
IM_BITARRAY_CLEARBIT
#define IM_BITARRAY_CLEARBIT (_ARRAY, _N) ((_ARRAY[(_N) >> 5] &= ~((ImU32)1 << ((_N) & 31))))
Definition at line 612 of file imgui_internal.h.
IM_BITARRAY_TESTBIT
#define IM_BITARRAY_TESTBIT (_ARRAY, _N) ((_ARRAY[(_N) >> 5] & ((ImU32)1 << ((_N) & 31))) != 0)
Definition at line 611 of file imgui_internal.h.
IM_COL32_DISABLE
#define IM_COL32_DISABLE IM_COL32(0,0,0,1)
Definition at line 2844 of file imgui_internal.h.
IM_DEBUG_BREAK
#define IM_DEBUG_BREAK () IM_ASSERT(0)
Definition at line 323 of file imgui_internal.h.
IM_DRAWLIST_ARCFAST_SAMPLE_MAX
#define IM_DRAWLIST_ARCFAST_SAMPLE_MAX IM_DRAWLIST_ARCFAST_TABLE_SIZE
Definition at line 846 of file imgui_internal.h.
IM_DRAWLIST_ARCFAST_TABLE_SIZE
#define IM_DRAWLIST_ARCFAST_TABLE_SIZE 48
Definition at line 844 of file imgui_internal.h.
IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_CALC
#define IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_CALC (_RAD, _MAXERROR) ImClamp(IM_ROUNDUP_TO_EVEN((int)ImCeil(IM_PI / ImAcos(1 - ImMin((_MAXERROR), (_RAD)) / (_RAD)))), IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MIN, IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MAX)
Definition at line 836 of file imgui_internal.h.
IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_CALC_ERROR
#define IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_CALC_ERROR (_N, _RAD) ((1 - ImCos(IM_PI / ImMax((float)(_N), IM_PI))) / (_RAD))
Definition at line 840 of file imgui_internal.h.
IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_CALC_R
#define IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_CALC_R (_N, _MAXERROR) ((_MAXERROR) / (1 - ImCos(IM_PI / ImMax((float)(_N), IM_PI))))
Definition at line 839 of file imgui_internal.h.
IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MAX
#define IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MAX 512
Definition at line 835 of file imgui_internal.h.
IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MIN
#define IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_MIN 4
Definition at line 834 of file imgui_internal.h.
IM_F32_TO_INT8_SAT
#define IM_F32_TO_INT8_SAT (_VAL) ((int)(ImSaturate(_VAL) * 255.0f + 0.5f))
Definition at line 278 of file imgui_internal.h.
IM_F32_TO_INT8_UNBOUND
#define IM_F32_TO_INT8_UNBOUND (_VAL) ((int)((_VAL) * 255.0f + ((_VAL)>=0 ? 0.5f : -0.5f)))
Definition at line 277 of file imgui_internal.h.
IM_FLOOR
#define IM_FLOOR IM_TRUNC
Definition at line 282 of file imgui_internal.h.
IM_LIKELY
#define IM_LIKELY
Definition at line 290 of file imgui_internal.h.
IM_MEMALIGN
#define IM_MEMALIGN (_OFF, _ALIGN) (((_OFF) + ((_ALIGN) - 1)) & ~((_ALIGN) - 1))
Definition at line 276 of file imgui_internal.h.
IM_MSVC_WARNING_SUPPRESS
#define IM_MSVC_WARNING_SUPPRESS (XXXX)
Definition at line 305 of file imgui_internal.h.
IM_NEWLINE
#define IM_NEWLINE "\n"
Definition at line 271 of file imgui_internal.h.
IM_PI
#define IM_PI 3.14159265358979323846f
Definition at line 267 of file imgui_internal.h.
IM_PRId64
#define IM_PRId64 "lld"
Definition at line 334 of file imgui_internal.h.
IM_PRIu64
#define IM_PRIu64 "llu"
Definition at line 335 of file imgui_internal.h.
IM_PRIX64
#define IM_PRIX64 "llX"
Definition at line 336 of file imgui_internal.h.
IM_ROUND
#define IM_ROUND (_VAL) ((float)(int)((_VAL) + 0.5f))
Definition at line 280 of file imgui_internal.h.
IM_ROUNDUP_TO_EVEN
#define IM_ROUNDUP_TO_EVEN (_V) ((((_V) + 1) / 2) * 2)
Definition at line 833 of file imgui_internal.h.
IM_STATIC_ASSERT
#define IM_STATIC_ASSERT (_COND) static_assert(_COND, "")
Definition at line 255 of file imgui_internal.h.
IM_TABSIZE
#define IM_TABSIZE (4)
Definition at line 274 of file imgui_internal.h.
IM_TRUNC
#define IM_TRUNC (_VAL) ((float)(int)(_VAL))
Definition at line 279 of file imgui_internal.h.
IM_UNLIKELY
#define IM_UNLIKELY
Definition at line 291 of file imgui_internal.h.
ImAcos
#define ImAcos (X) acosf(X)
Definition at line 475 of file imgui_internal.h.
ImAtan2
#define ImAtan2 (Y, X) atan2f((Y), (X))
Definition at line 476 of file imgui_internal.h.
ImAtof
#define ImAtof (STR) atof(STR)
Definition at line 477 of file imgui_internal.h.
ImCeil
#define ImCeil (X) ceilf(X)
Definition at line 478 of file imgui_internal.h.
ImCos
#define ImCos (X) cosf(X)
Definition at line 473 of file imgui_internal.h.
ImFabs
#define ImFabs (X) fabsf(X)
Definition at line 470 of file imgui_internal.h.
ImFmod
#define ImFmod (X, Y) fmodf((X), (Y))
Definition at line 472 of file imgui_internal.h.
ImFontAtlasRectId_GenerationMask_
#define ImFontAtlasRectId_GenerationMask_ (0x3FF00000)
Definition at line 3796 of file imgui_internal.h.
ImFontAtlasRectId_GenerationShift_
#define ImFontAtlasRectId_GenerationShift_ (20)
Definition at line 3797 of file imgui_internal.h.
ImFontAtlasRectId_IndexMask_
#define ImFontAtlasRectId_IndexMask_ (0x0007FFFF)
Definition at line 3795 of file imgui_internal.h.
IMGUI_CDECL
#define IMGUI_CDECL
Definition at line 298 of file imgui_internal.h.
IMGUI_DEBUG_LOG_ACTIVEID
#define IMGUI_DEBUG_LOG_ACTIVEID (...) do { if (g.DebugLogFlags & ImGuiDebugLogFlags_EventActiveId) IMGUI_DEBUG_LOG(__VA_ARGS__); } while (0)
Definition at line 244 of file imgui_internal.h.
IMGUI_DEBUG_LOG_CLIPPER
#define IMGUI_DEBUG_LOG_CLIPPER (...) do { if (g.DebugLogFlags & ImGuiDebugLogFlags_EventClipper) IMGUI_DEBUG_LOG(__VA_ARGS__); } while (0)
Definition at line 249 of file imgui_internal.h.
IMGUI_DEBUG_LOG_ERROR
#define IMGUI_DEBUG_LOG_ERROR (...) do { if (g.DebugLogFlags & ImGuiDebugLogFlags_EventError) IMGUI_DEBUG_LOG(__VA_ARGS__); else g.DebugLogSkippedErrors++; } while (0)
Definition at line 243 of file imgui_internal.h.
IMGUI_DEBUG_LOG_FOCUS
#define IMGUI_DEBUG_LOG_FOCUS (...) do { if (g.DebugLogFlags & ImGuiDebugLogFlags_EventFocus) IMGUI_DEBUG_LOG(__VA_ARGS__); } while (0)
Definition at line 245 of file imgui_internal.h.
IMGUI_DEBUG_LOG_FONT
#define IMGUI_DEBUG_LOG_FONT (...) do { ImGuiContext* g2 = GImGui; if (g2 && g2->DebugLogFlags & ImGuiDebugLogFlags_EventFont) IMGUI_DEBUG_LOG(__VA_ARGS__); } while (0)
Definition at line 251 of file imgui_internal.h.
IMGUI_DEBUG_LOG_INPUTROUTING
#define IMGUI_DEBUG_LOG_INPUTROUTING (...) do{if (g.DebugLogFlags & ImGuiDebugLogFlags_EventInputRouting)IMGUI_DEBUG_LOG(__VA_ARGS__); } while (0)
Definition at line 252 of file imgui_internal.h.
IMGUI_DEBUG_LOG_IO
#define IMGUI_DEBUG_LOG_IO (...) do { if (g.DebugLogFlags & ImGuiDebugLogFlags_EventIO) IMGUI_DEBUG_LOG(__VA_ARGS__); } while (0)
Definition at line 250 of file imgui_internal.h.
IMGUI_DEBUG_LOG_NAV
#define IMGUI_DEBUG_LOG_NAV (...) do { if (g.DebugLogFlags & ImGuiDebugLogFlags_EventNav) IMGUI_DEBUG_LOG(__VA_ARGS__); } while (0)
Definition at line 247 of file imgui_internal.h.
IMGUI_DEBUG_LOG_POPUP
#define IMGUI_DEBUG_LOG_POPUP (...) do { if (g.DebugLogFlags & ImGuiDebugLogFlags_EventPopup) IMGUI_DEBUG_LOG(__VA_ARGS__); } while (0)
Definition at line 246 of file imgui_internal.h.
IMGUI_DEBUG_LOG_SELECTION
#define IMGUI_DEBUG_LOG_SELECTION (...) do { if (g.DebugLogFlags & ImGuiDebugLogFlags_EventSelection) IMGUI_DEBUG_LOG(__VA_ARGS__); } while (0)
Definition at line 248 of file imgui_internal.h.
IMGUI_DEBUG_PRINTF
#define IMGUI_DEBUG_PRINTF (_FMT, ...) printf(_FMT, __VA_ARGS__)
Definition at line 236 of file imgui_internal.h.
IMGUI_ENABLE_STB_TRUETYPE
#define IMGUI_ENABLE_STB_TRUETYPE
Definition at line 128 of file imgui_internal.h.
IMGUI_FONT_SIZE_MAX
#define IMGUI_FONT_SIZE_MAX (512.0f)
Definition at line 3786 of file imgui_internal.h.
IMGUI_FONT_SIZE_THRESHOLD_FOR_LOADADVANCEXONLYMODE
#define IMGUI_FONT_SIZE_THRESHOLD_FOR_LOADADVANCEXONLYMODE (128.0f)
Definition at line 3787 of file imgui_internal.h.
IMGUI_TABLE_MAX_COLUMNS
#define IMGUI_TABLE_MAX_COLUMNS 512
Definition at line 2845 of file imgui_internal.h.
IMGUI_TEST_ENGINE_ITEM_ADD
#define IMGUI_TEST_ENGINE_ITEM_ADD (_ID, _BB, _ITEM_DATA) ((void)0)
Definition at line 3954 of file imgui_internal.h.
IMGUI_TEST_ENGINE_ITEM_INFO
#define IMGUI_TEST_ENGINE_ITEM_INFO (_ID, _LABEL, _FLAGS) ((void)g)
Definition at line 3955 of file imgui_internal.h.
IMGUI_WINDOW_HARD_MIN_SIZE
#define IMGUI_WINDOW_HARD_MIN_SIZE 4.0f
Definition at line 2567 of file imgui_internal.h.
ImGuiKey_Aliases_BEGIN
#define ImGuiKey_Aliases_BEGIN (ImGuiKey_Mouse_BEGIN)
Definition at line 1493 of file imgui_internal.h.
ImGuiKey_Aliases_END
#define ImGuiKey_Aliases_END (ImGuiKey_Mouse_END)
Definition at line 1494 of file imgui_internal.h.
ImGuiKey_Gamepad_BEGIN
#define ImGuiKey_Gamepad_BEGIN (ImGuiKey_GamepadStart)
Definition at line 1489 of file imgui_internal.h.
ImGuiKey_Gamepad_END
#define ImGuiKey_Gamepad_END (ImGuiKey_GamepadRStickDown + 1)
Definition at line 1490 of file imgui_internal.h.
ImGuiKey_Keyboard_BEGIN
#define ImGuiKey_Keyboard_BEGIN (ImGuiKey_NamedKey_BEGIN)
Definition at line 1487 of file imgui_internal.h.
ImGuiKey_Keyboard_END
#define ImGuiKey_Keyboard_END (ImGuiKey_GamepadStart)
Definition at line 1488 of file imgui_internal.h.
ImGuiKey_LegacyNativeKey_BEGIN
#define ImGuiKey_LegacyNativeKey_BEGIN 0
Definition at line 1485 of file imgui_internal.h.
ImGuiKey_LegacyNativeKey_END
#define ImGuiKey_LegacyNativeKey_END 512
Definition at line 1486 of file imgui_internal.h.
ImGuiKey_Mouse_BEGIN
#define ImGuiKey_Mouse_BEGIN (ImGuiKey_MouseLeft)
Definition at line 1491 of file imgui_internal.h.
ImGuiKey_Mouse_END
#define ImGuiKey_Mouse_END (ImGuiKey_MouseWheelY + 1)
Definition at line 1492 of file imgui_internal.h.
ImGuiKey_NavGamepadActivate
#define ImGuiKey_NavGamepadActivate (g.IO.ConfigNavSwapGamepadButtons ? ImGuiKey_GamepadFaceRight : ImGuiKey_GamepadFaceDown)
Definition at line 1501 of file imgui_internal.h.
ImGuiKey_NavGamepadCancel
#define ImGuiKey_NavGamepadCancel (g.IO.ConfigNavSwapGamepadButtons ? ImGuiKey_GamepadFaceDown : ImGuiKey_GamepadFaceRight)
Definition at line 1502 of file imgui_internal.h.
ImGuiKey_NavGamepadInput
#define ImGuiKey_NavGamepadInput ImGuiKey_GamepadFaceUp
Definition at line 1504 of file imgui_internal.h.
ImGuiKey_NavGamepadMenu
#define ImGuiKey_NavGamepadMenu ImGuiKey_GamepadFaceLeft
Definition at line 1503 of file imgui_internal.h.
ImGuiKey_NavGamepadTweakFast
#define ImGuiKey_NavGamepadTweakFast ImGuiKey_GamepadR1
Definition at line 1500 of file imgui_internal.h.
ImGuiKey_NavGamepadTweakSlow
#define ImGuiKey_NavGamepadTweakSlow ImGuiKey_GamepadL1
Definition at line 1499 of file imgui_internal.h.
ImGuiKey_NavKeyboardTweakFast
#define ImGuiKey_NavKeyboardTweakFast ImGuiMod_Shift
Definition at line 1498 of file imgui_internal.h.
ImGuiKey_NavKeyboardTweakSlow
#define ImGuiKey_NavKeyboardTweakSlow ImGuiMod_Ctrl
Definition at line 1497 of file imgui_internal.h.
ImGuiKeyOwner_Any
#define ImGuiKeyOwner_Any ((ImGuiID)0)
Definition at line 1556 of file imgui_internal.h.
ImGuiKeyOwner_NoOwner
#define ImGuiKeyOwner_NoOwner ((ImGuiID)-1)
Definition at line 1557 of file imgui_internal.h.
ImGuiSelectionUserData_Invalid
#define ImGuiSelectionUserData_Invalid ((ImGuiSelectionUserData)-1)
Definition at line 1895 of file imgui_internal.h.
ImMemchr
#define ImMemchr memchr
Definition at line 387 of file imgui_internal.h.
ImSin
#define ImSin (X) sinf(X)
Definition at line 474 of file imgui_internal.h.
ImSqrt
#define ImSqrt (X) sqrtf(X)
Definition at line 471 of file imgui_internal.h.
IMSTB_TEXTEDIT_CHARTYPE
#define IMSTB_TEXTEDIT_CHARTYPE char
Definition at line 1214 of file imgui_internal.h.
IMSTB_TEXTEDIT_GETWIDTH_NEWLINE
#define IMSTB_TEXTEDIT_GETWIDTH_NEWLINE (-1.0f)
Definition at line 1215 of file imgui_internal.h.
IMSTB_TEXTEDIT_STRING
#define IMSTB_TEXTEDIT_STRING ImGuiInputTextState
Definition at line 1213 of file imgui_internal.h.
IMSTB_TEXTEDIT_UNDOCHARCOUNT
#define IMSTB_TEXTEDIT_UNDOCHARCOUNT 999
Definition at line 1217 of file imgui_internal.h.
IMSTB_TEXTEDIT_UNDOSTATECOUNT
#define IMSTB_TEXTEDIT_UNDOSTATECOUNT 99
Definition at line 1216 of file imgui_internal.h.
ImStrlen
#define ImStrlen strlen
Definition at line 386 of file imgui_internal.h.
Typedef Documentation
ImBitArrayForNamedKeys
typedef ImBitArray<ImGuiKey_NamedKey_COUNT, -ImGuiKey_NamedKey_BEGIN> ImBitArrayForNamedKeys
Definition at line 1482 of file imgui_internal.h.
ImBitArrayPtr
typedef ImU32* ImBitArrayPtr
Definition at line 631 of file imgui_internal.h.
ImDrawTextFlags
typedef int ImDrawTextFlags
Definition at line 196 of file imgui_internal.h.
ImFileHandle
typedef FILE* ImFileHandle
Definition at line 455 of file imgui_internal.h.
ImFontBuilderIO
typedef ImFontLoader ImFontBuilderIO
Definition at line 3779 of file imgui_internal.h.
ImGuiActivateFlags
typedef int ImGuiActivateFlags
Definition at line 197 of file imgui_internal.h.
ImGuiContextHookCallback
typedef void(* ImGuiContextHookCallback) (ImGuiContext *ctx, ImGuiContextHook *hook)
Definition at line 2161 of file imgui_internal.h.
ImGuiDebugLogFlags
typedef int ImGuiDebugLogFlags
Definition at line 198 of file imgui_internal.h.
ImGuiErrorCallback
typedef void(* ImGuiErrorCallback) (ImGuiContext *ctx, void *user_data, const char *msg)
Definition at line 2057 of file imgui_internal.h.
ImGuiFocusRequestFlags
typedef int ImGuiFocusRequestFlags
Definition at line 199 of file imgui_internal.h.
ImGuiItemStatusFlags
typedef int ImGuiItemStatusFlags
Definition at line 200 of file imgui_internal.h.
ImGuiKeyRoutingIndex
typedef ImS16 ImGuiKeyRoutingIndex
Definition at line 1560 of file imgui_internal.h.
ImGuiLayoutType
typedef int ImGuiLayoutType
Definition at line 193 of file imgui_internal.h.
ImGuiLogFlags
typedef int ImGuiLogFlags
Definition at line 202 of file imgui_internal.h.
ImGuiNavMoveFlags
typedef int ImGuiNavMoveFlags
Definition at line 204 of file imgui_internal.h.
ImGuiNavRenderCursorFlags
typedef int ImGuiNavRenderCursorFlags
Definition at line 203 of file imgui_internal.h.
ImGuiNextItemDataFlags
typedef int ImGuiNextItemDataFlags
Definition at line 205 of file imgui_internal.h.
ImGuiNextWindowDataFlags
typedef int ImGuiNextWindowDataFlags
Definition at line 206 of file imgui_internal.h.
ImGuiOldColumnFlags
typedef int ImGuiOldColumnFlags
Definition at line 201 of file imgui_internal.h.
ImGuiScrollFlags
typedef int ImGuiScrollFlags
Definition at line 207 of file imgui_internal.h.
ImGuiSeparatorFlags
typedef int ImGuiSeparatorFlags
Definition at line 208 of file imgui_internal.h.
ImGuiTableColumnIdx
typedef ImS16 ImGuiTableColumnIdx
Definition at line 216 of file imgui_internal.h.
ImGuiTableDrawChannelIdx
typedef ImU16 ImGuiTableDrawChannelIdx
Definition at line 217 of file imgui_internal.h.
ImGuiTextFlags
typedef int ImGuiTextFlags
Definition at line 209 of file imgui_internal.h.
ImGuiTooltipFlags
typedef int ImGuiTooltipFlags
Definition at line 210 of file imgui_internal.h.
ImGuiTypingSelectFlags
typedef int ImGuiTypingSelectFlags
Definition at line 211 of file imgui_internal.h.
ImGuiWindowBgClickFlags
typedef int ImGuiWindowBgClickFlags
Definition at line 212 of file imgui_internal.h.
ImGuiWindowRefreshFlags
typedef int ImGuiWindowRefreshFlags
Definition at line 213 of file imgui_internal.h.
ImPoolIdx
typedef int ImPoolIdx
Definition at line 749 of file imgui_internal.h.
ImStbTexteditState
typedef ImStb::STB_TexteditState ImStbTexteditState
Definition at line 1219 of file imgui_internal.h.
stbrp_node_im
typedef stbrp_node stbrp_node_im
Definition at line 3837 of file imgui_internal.h.
Enumeration Type Documentation
ImDrawTextFlags_
enum ImDrawTextFlags_
Enumerator
ImDrawTextFlags_None
ImDrawTextFlags_CpuFineClip
ImDrawTextFlags_WrapKeepBlanks
ImDrawTextFlags_StopOnNewLine
Definition at line 433 of file imgui_internal.h.
ImGuiActivateFlags_
enum ImGuiActivateFlags_
Enumerator
ImGuiActivateFlags_None
ImGuiActivateFlags_PreferInput
ImGuiActivateFlags_PreferTweak
ImGuiActivateFlags_TryToPreserveState
ImGuiActivateFlags_FromTabbing
ImGuiActivateFlags_FromShortcut
ImGuiActivateFlags_FromFocusApi
Definition at line 1675 of file imgui_internal.h.
ImGuiAxis
enum ImGuiAxis
Enumerator
ImGuiAxis_None
ImGuiAxis_X
ImGuiAxis_Y
Definition at line 1137 of file imgui_internal.h.
ImGuiButtonFlagsPrivate_
enum ImGuiButtonFlagsPrivate_
Enumerator
ImGuiButtonFlags_PressedOnClick
ImGuiButtonFlags_PressedOnClickRelease
ImGuiButtonFlags_PressedOnClickReleaseAnywhere
ImGuiButtonFlags_PressedOnRelease
ImGuiButtonFlags_PressedOnDoubleClick
ImGuiButtonFlags_PressedOnDragDropHold
ImGuiButtonFlags_FlattenChildren
ImGuiButtonFlags_AllowOverlap
ImGuiButtonFlags_AlignTextBaseLine
ImGuiButtonFlags_NoKeyModsAllowed
ImGuiButtonFlags_NoHoldingActiveId
ImGuiButtonFlags_NoNavFocus
ImGuiButtonFlags_NoHoveredOnFocus
ImGuiButtonFlags_NoSetKeyOwner
ImGuiButtonFlags_NoTestKeyOwner
ImGuiButtonFlags_NoFocus
ImGuiButtonFlags_PressedOnMask_
ImGuiButtonFlags_PressedOnDefault_
Definition at line 1024 of file imgui_internal.h.
ImGuiComboFlagsPrivate_
enum ImGuiComboFlagsPrivate_
Enumerator
ImGuiComboFlags_CustomPreview
Definition at line 1051 of file imgui_internal.h.
ImGuiContextHookType
enum ImGuiContextHookType
Enumerator
ImGuiContextHookType_NewFramePre
ImGuiContextHookType_NewFramePost
ImGuiContextHookType_EndFramePre
ImGuiContextHookType_EndFramePost
ImGuiContextHookType_RenderPre
ImGuiContextHookType_RenderPost
ImGuiContextHookType_Shutdown
ImGuiContextHookType_PendingRemoval_
Definition at line 2162 of file imgui_internal.h.
ImGuiDataTypePrivate_
enum ImGuiDataTypePrivate_
Enumerator
ImGuiDataType_Pointer
ImGuiDataType_ID
Definition at line 942 of file imgui_internal.h.
ImGuiDebugLogFlags_
enum ImGuiDebugLogFlags_
Enumerator
ImGuiDebugLogFlags_None
ImGuiDebugLogFlags_EventError
ImGuiDebugLogFlags_EventActiveId
ImGuiDebugLogFlags_EventFocus
ImGuiDebugLogFlags_EventPopup
ImGuiDebugLogFlags_EventNav
ImGuiDebugLogFlags_EventClipper
ImGuiDebugLogFlags_EventSelection
ImGuiDebugLogFlags_EventIO
ImGuiDebugLogFlags_EventFont
ImGuiDebugLogFlags_EventInputRouting
ImGuiDebugLogFlags_EventDocking
ImGuiDebugLogFlags_EventViewport
ImGuiDebugLogFlags_EventMask_
ImGuiDebugLogFlags_OutputToTTY
ImGuiDebugLogFlags_OutputToDebugger
ImGuiDebugLogFlags_OutputToTestEngine
Definition at line 2064 of file imgui_internal.h.
ImGuiFocusRequestFlags_
enum ImGuiFocusRequestFlags_
Enumerator
ImGuiFocusRequestFlags_None
ImGuiFocusRequestFlags_RestoreFocusedChild
ImGuiFocusRequestFlags_UnlessBelowModal
Definition at line 1097 of file imgui_internal.h.
ImGuiHoveredFlagsPrivate_
enum ImGuiHoveredFlagsPrivate_
Enumerator
ImGuiHoveredFlags_DelayMask_
ImGuiHoveredFlags_AllowedMaskForIsWindowHovered
ImGuiHoveredFlags_AllowedMaskForIsItemHovered
Definition at line 1007 of file imgui_internal.h.
ImGuiInputEventType
enum ImGuiInputEventType
Enumerator
ImGuiInputEventType_None
ImGuiInputEventType_MousePos
ImGuiInputEventType_MouseWheel
ImGuiInputEventType_MouseButton
ImGuiInputEventType_Key
ImGuiInputEventType_Text
ImGuiInputEventType_Focus
ImGuiInputEventType_COUNT
Definition at line 1506 of file imgui_internal.h.
ImGuiInputFlagsPrivate_
enum ImGuiInputFlagsPrivate_
Enumerator
ImGuiInputFlags_RepeatRateDefault
ImGuiInputFlags_RepeatRateNavMove
ImGuiInputFlags_RepeatRateNavTweak
ImGuiInputFlags_RepeatUntilRelease
ImGuiInputFlags_RepeatUntilKeyModsChange
ImGuiInputFlags_RepeatUntilKeyModsChangeFromNone
ImGuiInputFlags_RepeatUntilOtherKeyPress
ImGuiInputFlags_LockThisFrame
ImGuiInputFlags_LockUntilRelease
ImGuiInputFlags_CondHovered
ImGuiInputFlags_CondActive
ImGuiInputFlags_CondDefault_
ImGuiInputFlags_RepeatRateMask_
ImGuiInputFlags_RepeatUntilMask_
ImGuiInputFlags_RepeatMask_
ImGuiInputFlags_CondMask_
ImGuiInputFlags_RouteTypeMask_
ImGuiInputFlags_RouteOptionsMask_
ImGuiInputFlags_SupportedByIsKeyPressed
ImGuiInputFlags_SupportedByIsMouseClicked
ImGuiInputFlags_SupportedByShortcut
ImGuiInputFlags_SupportedBySetNextItemShortcut
ImGuiInputFlags_SupportedBySetKeyOwner
ImGuiInputFlags_SupportedBySetItemKeyOwner
Definition at line 1602 of file imgui_internal.h.
ImGuiInputSource
enum ImGuiInputSource : int
Enumerator
ImGuiInputSource_None
ImGuiInputSource_Mouse
ImGuiInputSource_Keyboard
ImGuiInputSource_Gamepad
ImGuiInputSource_COUNT
Definition at line 1518 of file imgui_internal.h.
ImGuiInputTextFlagsPrivate_
enum ImGuiInputTextFlagsPrivate_
Enumerator
ImGuiInputTextFlags_Multiline
ImGuiInputTextFlags_MergedItem
ImGuiInputTextFlags_LocalizeDecimalPoint
Definition at line 1015 of file imgui_internal.h.
ImGuiItemFlagsPrivate_
enum ImGuiItemFlagsPrivate_
Enumerator
ImGuiItemFlags_Disabled
ImGuiItemFlags_ReadOnly
ImGuiItemFlags_MixedValue
ImGuiItemFlags_NoWindowHoverableCheck
ImGuiItemFlags_AllowOverlap
ImGuiItemFlags_NoNavDisableMouseHover
ImGuiItemFlags_NoMarkEdited
ImGuiItemFlags_NoFocus
ImGuiItemFlags_Inputable
ImGuiItemFlags_HasSelectionUserData
ImGuiItemFlags_IsMultiSelect
ImGuiItemFlags_Default_
Definition at line 955 of file imgui_internal.h.
ImGuiItemStatusFlags_
enum ImGuiItemStatusFlags_
Enumerator
ImGuiItemStatusFlags_None
ImGuiItemStatusFlags_HoveredRect
ImGuiItemStatusFlags_HasDisplayRect
ImGuiItemStatusFlags_Edited
ImGuiItemStatusFlags_ToggledSelection
ImGuiItemStatusFlags_ToggledOpen
ImGuiItemStatusFlags_HasDeactivated
ImGuiItemStatusFlags_Deactivated
ImGuiItemStatusFlags_HoveredWindow
ImGuiItemStatusFlags_Visible
ImGuiItemStatusFlags_HasClipRect
ImGuiItemStatusFlags_HasShortcut
Definition at line 980 of file imgui_internal.h.
ImGuiLayoutType_
enum ImGuiLayoutType_
Enumerator
ImGuiLayoutType_Horizontal
ImGuiLayoutType_Vertical
Definition at line 1118 of file imgui_internal.h.
ImGuiLocKey
enum ImGuiLocKey : int
Enumerator
ImGuiLocKey_VersionStr
ImGuiLocKey_TableSizeOne
ImGuiLocKey_TableSizeAllFit
ImGuiLocKey_TableSizeAllDefault
ImGuiLocKey_TableResetOrder
ImGuiLocKey_WindowingMainMenuBar
ImGuiLocKey_WindowingPopup
ImGuiLocKey_WindowingUntitled
ImGuiLocKey_OpenLink_s
ImGuiLocKey_CopyLink
ImGuiLocKey_COUNT
Definition at line 2022 of file imgui_internal.h.
ImGuiLogFlags_
enum ImGuiLogFlags_
Enumerator
ImGuiLogFlags_None
ImGuiLogFlags_OutputTTY
ImGuiLogFlags_OutputFile
ImGuiLogFlags_OutputBuffer
ImGuiLogFlags_OutputClipboard
ImGuiLogFlags_OutputMask_
Definition at line 1125 of file imgui_internal.h.
ImGuiNavLayer
enum ImGuiNavLayer
Enumerator
ImGuiNavLayer_Main
ImGuiNavLayer_Menu
ImGuiNavLayer_COUNT
Definition at line 1738 of file imgui_internal.h.
ImGuiNavMoveFlags_
enum ImGuiNavMoveFlags_
Enumerator
ImGuiNavMoveFlags_None
ImGuiNavMoveFlags_LoopX
ImGuiNavMoveFlags_LoopY
ImGuiNavMoveFlags_WrapX
ImGuiNavMoveFlags_WrapY
ImGuiNavMoveFlags_WrapMask_
ImGuiNavMoveFlags_AllowCurrentNavId
ImGuiNavMoveFlags_AlsoScoreVisibleSet
ImGuiNavMoveFlags_ScrollToEdgeY
ImGuiNavMoveFlags_Forwarded
ImGuiNavMoveFlags_DebugNoResult
ImGuiNavMoveFlags_FocusApi
ImGuiNavMoveFlags_IsTabbing
ImGuiNavMoveFlags_IsPageMove
ImGuiNavMoveFlags_Activate
ImGuiNavMoveFlags_NoSelect
ImGuiNavMoveFlags_NoSetNavCursorVisible
ImGuiNavMoveFlags_NoClearActiveId
Definition at line 1716 of file imgui_internal.h.
ImGuiNavRenderCursorFlags_
enum ImGuiNavRenderCursorFlags_
Enumerator
ImGuiNavRenderCursorFlags_None
ImGuiNavRenderCursorFlags_Compact
ImGuiNavRenderCursorFlags_AlwaysDraw
ImGuiNavRenderCursorFlags_NoRounding
ImGuiNavHighlightFlags_None
ImGuiNavHighlightFlags_Compact
ImGuiNavHighlightFlags_AlwaysDraw
ImGuiNavHighlightFlags_NoRounding
Definition at line 1701 of file imgui_internal.h.
ImGuiNextItemDataFlags_
enum ImGuiNextItemDataFlags_
Enumerator
ImGuiNextItemDataFlags_None
ImGuiNextItemDataFlags_HasWidth
ImGuiNextItemDataFlags_HasOpen
ImGuiNextItemDataFlags_HasShortcut
ImGuiNextItemDataFlags_HasRefVal
ImGuiNextItemDataFlags_HasStorageID
ImGuiNextItemDataFlags_HasColorMarker
Definition at line 1335 of file imgui_internal.h.
ImGuiNextWindowDataFlags_
enum ImGuiNextWindowDataFlags_
Enumerator
ImGuiNextWindowDataFlags_None
ImGuiNextWindowDataFlags_HasPos
ImGuiNextWindowDataFlags_HasSize
ImGuiNextWindowDataFlags_HasContentSize
ImGuiNextWindowDataFlags_HasCollapsed
ImGuiNextWindowDataFlags_HasSizeConstraint
ImGuiNextWindowDataFlags_HasFocus
ImGuiNextWindowDataFlags_HasBgAlpha
ImGuiNextWindowDataFlags_HasScroll
ImGuiNextWindowDataFlags_HasWindowFlags
ImGuiNextWindowDataFlags_HasChildFlags
ImGuiNextWindowDataFlags_HasRefreshPolicy
Definition at line 1291 of file imgui_internal.h.
ImGuiOldColumnFlags_
enum ImGuiOldColumnFlags_
Enumerator
ImGuiOldColumnFlags_None
ImGuiOldColumnFlags_NoBorder
ImGuiOldColumnFlags_NoResize
ImGuiOldColumnFlags_NoPreserveWidths
ImGuiOldColumnFlags_NoForceWithinWindow
ImGuiOldColumnFlags_GrowParentContentsSize
Definition at line 1811 of file imgui_internal.h.
ImGuiPlotType
enum ImGuiPlotType
Enumerator
ImGuiPlotType_Lines
ImGuiPlotType_Histogram
Definition at line 1144 of file imgui_internal.h.
ImGuiPopupPositionPolicy
enum ImGuiPopupPositionPolicy
Enumerator
ImGuiPopupPositionPolicy_Default
ImGuiPopupPositionPolicy_ComboBox
ImGuiPopupPositionPolicy_Tooltip
Definition at line 1455 of file imgui_internal.h.
ImGuiScrollFlags_
enum ImGuiScrollFlags_
Enumerator
ImGuiScrollFlags_None
ImGuiScrollFlags_KeepVisibleEdgeX
ImGuiScrollFlags_KeepVisibleEdgeY
ImGuiScrollFlags_KeepVisibleCenterX
ImGuiScrollFlags_KeepVisibleCenterY
ImGuiScrollFlags_AlwaysCenterX
ImGuiScrollFlags_AlwaysCenterY
ImGuiScrollFlags_NoScrollParent
ImGuiScrollFlags_MaskX_
ImGuiScrollFlags_MaskY_
Definition at line 1687 of file imgui_internal.h.
ImGuiSelectableFlagsPrivate_
enum ImGuiSelectableFlagsPrivate_
Enumerator
ImGuiSelectableFlags_NoHoldingActiveID
ImGuiSelectableFlags_SelectOnClick
ImGuiSelectableFlags_SelectOnRelease
ImGuiSelectableFlags_SpanAvailWidth
ImGuiSelectableFlags_SetNavIdOnHover
ImGuiSelectableFlags_NoPadWithHalfSpacing
ImGuiSelectableFlags_NoSetKeyOwner
Definition at line 1064 of file imgui_internal.h.
ImGuiSeparatorFlags_
enum ImGuiSeparatorFlags_
Enumerator
ImGuiSeparatorFlags_None
ImGuiSeparatorFlags_Horizontal
ImGuiSeparatorFlags_Vertical
ImGuiSeparatorFlags_SpanAllColumns
Definition at line 1086 of file imgui_internal.h.
ImGuiSliderFlagsPrivate_
enum ImGuiSliderFlagsPrivate_
Enumerator
ImGuiSliderFlags_Vertical
ImGuiSliderFlags_ReadOnly
Definition at line 1057 of file imgui_internal.h.
ImGuiTabBarFlagsPrivate_
enum ImGuiTabBarFlagsPrivate_
Enumerator
ImGuiTabBarFlags_DockNode
ImGuiTabBarFlags_IsFocused
ImGuiTabBarFlags_SaveSettings
Definition at line 2761 of file imgui_internal.h.
ImGuiTabItemFlagsPrivate_
enum ImGuiTabItemFlagsPrivate_
Enumerator
ImGuiTabItemFlags_SectionMask_
ImGuiTabItemFlags_NoCloseButton
ImGuiTabItemFlags_Button
ImGuiTabItemFlags_Invisible
Definition at line 2769 of file imgui_internal.h.
ImGuiTextFlags_
enum ImGuiTextFlags_
Enumerator
ImGuiTextFlags_None
ImGuiTextFlags_NoWidthForLargeClippedText
Definition at line 1104 of file imgui_internal.h.
ImGuiTooltipFlags_
enum ImGuiTooltipFlags_
Enumerator
ImGuiTooltipFlags_None
ImGuiTooltipFlags_OverridePrevious
Definition at line 1110 of file imgui_internal.h.
ImGuiTreeNodeFlagsPrivate_
enum ImGuiTreeNodeFlagsPrivate_
Enumerator
ImGuiTreeNodeFlags_NoNavFocus
ImGuiTreeNodeFlags_ClipLabelForTrailingButton
ImGuiTreeNodeFlags_UpsideDownArrow
ImGuiTreeNodeFlags_OpenOnMask_
ImGuiTreeNodeFlags_DrawLinesMask_
Definition at line 1077 of file imgui_internal.h.
ImGuiTypingSelectFlags_
enum ImGuiTypingSelectFlags_
Enumerator
ImGuiTypingSelectFlags_None
ImGuiTypingSelectFlags_AllowBackspace
ImGuiTypingSelectFlags_AllowSingleCharMode
Definition at line 1774 of file imgui_internal.h.
ImGuiWindowBgClickFlags_
enum ImGuiWindowBgClickFlags_
Enumerator
ImGuiWindowBgClickFlags_None
ImGuiWindowBgClickFlags_Move
Definition at line 1285 of file imgui_internal.h.
ImGuiWindowRefreshFlags_
enum ImGuiWindowRefreshFlags_
Enumerator
ImGuiWindowRefreshFlags_None
ImGuiWindowRefreshFlags_TryToAvoidRefresh
ImGuiWindowRefreshFlags_RefreshOnHover
ImGuiWindowRefreshFlags_RefreshOnFocus
Definition at line 1276 of file imgui_internal.h.
Function Documentation
ImAbs() [1/3]
double ImAbs (double x) inline
Definition at line 485 of file imgui_internal.h.
ImAbs() [2/3]
float ImAbs (float x) inline
Definition at line 484 of file imgui_internal.h.
ImAbs() [3/3]
int ImAbs (int x) inline
Definition at line 483 of file imgui_internal.h.
Referenced by ImDrawList::_PathArcToFastEx(), BoxSelectScrollWithMouseDrag(), ImPlot::CalcLogarithmicExponents(), ImAlmostEqual(), ImPlot::Locator_SymLog(), LockWheelingWindow(), ImDrawList::PathArcTo(), ImPlotAxis::PixelSize(), ImPlot::RendererBarsFillV< _Getter1, _Getter2 >::Render(), ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::Render(), ImPlot::RendererBarsLineV< _Getter1, _Getter2 >::Render(), ImPlot::RendererBarsLineH< _Getter1, _Getter2 >::Render(), ImGui::TableAngledHeadersRowEx(), and ImGui::UpdateMouseWheel().
ImAddClampOverflow()
template<typename T > T ImAddClampOverflow (T a, T b, T mn, T mx)
Definition at line 502 of file imgui_internal.h.
Referenced by ImGui::DataTypeApplyOp().
ImAlphaBlendColors()
ImU32 ImAlphaBlendColors (ImU32 col_a, ImU32 col_b)
Definition at line 2729 of file imgui.cpp.
References IM_COL32, IM_COL32_A_SHIFT, IM_COL32_B_SHIFT, IM_COL32_G_SHIFT, IM_COL32_R_SHIFT, and ImLerp().
Referenced by ImGui::RenderColorRectWithAlphaCheckerboard().
ImBezierCubicCalc()
ImVec2 ImBezierCubicCalc (const ImVec2 & p1, const ImVec2 & p2, const ImVec2 & p3, const ImVec2 & p4, float t)
Definition at line 1337 of file imgui_draw.cpp.
References ImVec2::x, and ImVec2::y.
Referenced by ImBezierCubicClosestPoint(), and ImDrawList::PathBezierCubicCurveTo().
ImBezierCubicClosestPoint()
ImVec2 ImBezierCubicClosestPoint (const ImVec2 & p1, const ImVec2 & p2, const ImVec2 & p3, const ImVec2 & p4, const ImVec2 & p, int num_segments)
Definition at line 1954 of file imgui.cpp.
References IM_ASSERT, ImBezierCubicCalc(), ImLengthSqr(), and ImLineClosestPoint().
ImBezierCubicClosestPointCasteljau()
ImVec2 ImBezierCubicClosestPointCasteljau (const ImVec2 & p1, const ImVec2 & p2, const ImVec2 & p3, const ImVec2 & p4, const ImVec2 & p, float tess_tol)
Definition at line 2012 of file imgui.cpp.
References IM_ASSERT, ImBezierCubicClosestPointCasteljauStep(), ImVec2::x, and ImVec2::y.
ImBezierQuadraticCalc()
ImVec2 ImBezierQuadraticCalc (const ImVec2 & p1, const ImVec2 & p2, const ImVec2 & p3, float t)
Definition at line 1347 of file imgui_draw.cpp.
References ImVec2::x, and ImVec2::y.
Referenced by ImDrawList::PathBezierQuadraticCurveTo().
ImBitArrayClearAllBits()
void ImBitArrayClearAllBits (ImU32 * arr, int bitcount) inline
Definition at line 614 of file imgui_internal.h.
References ImBitArrayGetStorageSizeInBytes().
Referenced by ImGui::TableUpdateLayout().
ImBitArrayClearBit()
void ImBitArrayClearBit (ImU32 * arr, int n) inline
Definition at line 616 of file imgui_internal.h.
Referenced by ImBitArray< BITCOUNT, OFFSET >::ClearBit(), ImBitVector::ClearBit(), and ImGui::TableMergeDrawChannels().
ImBitArrayGetStorageSizeInBytes()
size_t ImBitArrayGetStorageSizeInBytes (int bitcount) inline
Definition at line 613 of file imgui_internal.h.
Referenced by ImBitArrayClearAllBits(), ImGui::TableBeginInitMemory(), ImGui::TableMergeDrawChannels(), and ImGui::TableSetupDrawChannels().
ImBitArraySetBit()
void ImBitArraySetBit (ImU32 * arr, int n) inline
Definition at line 617 of file imgui_internal.h.
Referenced by ImBitArray< BITCOUNT, OFFSET >::SetBit(), ImBitVector::SetBit(), ImGui::TableMergeDrawChannels(), and ImGui::TableUpdateLayout().
ImBitArraySetBitRange()
void ImBitArraySetBitRange (ImU32 * arr, int n, int n2) inline
Definition at line 618 of file imgui_internal.h.
Referenced by ImBitArray< BITCOUNT, OFFSET >::SetBitRange(), and ImGui::TableMergeDrawChannels().
ImBitArrayTestBit()
bool ImBitArrayTestBit (const ImU32 * arr, int n) inline
Definition at line 615 of file imgui_internal.h.
ImCharIsBlankA()
bool ImCharIsBlankA (char c) inline
Definition at line 403 of file imgui_internal.h.
Referenced by ImGuiTextFilter::Build(), ImGui::ColorEdit4(), ImGui::DataTypeApplyFromText(), ImTextCalcWordWrapNextLineStart(), and ImGui::RenderTextEllipsis().
ImCharIsBlankW()
bool ImCharIsBlankW (unsigned int c) inline
Definition at line 404 of file imgui_internal.h.
Referenced by ImGui::GetTypingSelectRequest(), ImFontCalcWordWrapPositionEx(), InputTextFilterCharacter(), ImStb::is_word_boundary_from_left(), and ImStb::is_word_boundary_from_right().
ImCharIsXdigitA()
bool ImCharIsXdigitA (char c) inline
Definition at line 405 of file imgui_internal.h.
Referenced by ImGui::DebugTextUnformattedWithLocateItem().
ImClamp() [1/2]
ImVec2 ImClamp (const ImVec2 & v, const ImVec2 & mn, const ImVec2 & mx) inline
Definition at line 507 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
ImClamp() [2/2]
template<typename T > T ImClamp (T v, T mn, T mx)
Definition at line 499 of file imgui_internal.h.
Referenced by ImDrawList::_PathArcToFastEx(), ImDrawList::AddCircle(), ImDrawList::AddCircleFilled(), ImGui::BeginBoxSelect(), ImGui::BeginMenuEx(), CalcResizePosSizeFromAnyCorner(), CalcWindowAutoFitSize(), CalcWindowSizeAfterConstraint(), ClampWindowPos(), ImRect::ClipWithFull(), ImGui::ColorEdit4(), ImPlot::ColormapSlider(), ImGui::ColorPicker4(), ImGui::DataTypeApplyFromText(), ImGui::EndBoxSelect(), ImPlot::EndPlot(), ImPlot::EndSubplots(), ImGui::FindBestWindowPosForPopupEx(), ImPlot::float(), ImGui::ImageButtonEx(), ImFontAtlasBakedAddFontGlyph(), ImFontAtlasBakedAddFontGlyphAdvancedX(), ImFontAtlasTextureGrow(), ImGuiListClipper_StepInternal(), ImGui::InputTextEx(), ImGuiInputTextCallbackData::InsertChars(), ImPlotColormapData::LerpTable(), ImPlot::Locator_Time(), ImGui::NavCalcPreferredRefPos(), ImGui::NavProcessItem(), ImPlot::GetterHeatmapColMaj< T >::operator()(), ImGui::PlotEx(), ImGui::ProgressBar(), ImGui::RenderColorRectWithAlphaCheckerboard(), ImPlot::RenderGridLinesX(), ImPlot::RenderGridLinesY(), ImPlot::RenderHeatmap(), ImGui::RenderRectFilledInRangeH(), ImGui::RenderWindowTitleBarContents(), ImGui::ScrollbarEx(), ImGui::ShadeVertsLinearColorGradientKeepAlpha(), ImGui::ShadeVertsLinearUV(), ImStb::STB_TEXTEDIT_INSERTCHARS(), ImGui::TableSetColumnWidth(), ImGui::TableUpdateLayout(), ImPlot::TransformForward_Logit(), ImGui::UpdateCurrentFontSize(), ImGui::UpdateMouseWheel(), and ImGui::UpdateWindowManualResize().
ImCountSetBits()
unsigned int ImCountSetBits (unsigned int v) inline
Definition at line 383 of file imgui_internal.h.
Referenced by ImGui::Begin(), and ImGui::DebugNodeFont().
ImDot()
float ImDot (const ImVec2 & a, const ImVec2 & b) inline
Definition at line 522 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::ShadeVertsLinearColorGradientKeepAlpha().
ImExponentialMovingAverage()
float ImExponentialMovingAverage (float avg, float sample, int n) inline
Definition at line 528 of file imgui_internal.h.
Referenced by ImGui::UpdateMouseWheel().
ImFileClose()
bool ImFileClose (ImFileHandle file)
Definition at line 2458 of file imgui.cpp.
Referenced by ImFileLoadToMemory(), ImGui::LogFinish(), ImGui::SaveIniSettingsToDisk(), and ImGui::Shutdown().
ImFileGetSize()
ImU64 ImFileGetSize (ImFileHandle file)
Definition at line 2459 of file imgui.cpp.
Referenced by ImFileLoadToMemory().
ImFileLoadToMemory()
void * ImFileLoadToMemory (const char * filename, const char * mode, size_t * out_file_size = NULL, int padding_bytes = 0)
Definition at line 2467 of file imgui.cpp.
References IM_ALLOC, IM_ASSERT, IM_FREE, ImFileClose(), ImFileGetSize(), ImFileOpen(), and ImFileRead().
Referenced by ImFontAtlas::AddFontFromFileTTF(), and ImGui::LoadIniSettingsFromDisk().
ImFileOpen()
ImFileHandle ImFileOpen (const char * filename, const char * mode)
Definition at line 2433 of file imgui.cpp.
References ImVector< T >::Data, IM_ARRAYSIZE, and ImVector< T >::resize().
Referenced by ImFileLoadToMemory(), ImGui::LogToFile(), and ImGui::SaveIniSettingsToDisk().
ImFileRead()
ImU64 ImFileRead (void * data, ImU64 size, ImU64 count, ImFileHandle file)
Definition at line 2460 of file imgui.cpp.
Referenced by ImFileLoadToMemory().
ImFileWrite()
ImU64 ImFileWrite (const void * data, ImU64 size, ImU64 count, ImFileHandle file)
Definition at line 2461 of file imgui.cpp.
Referenced by LogTextV(), and ImGui::SaveIniSettingsToDisk().
ImFloor() [1/2]
ImVec2 ImFloor (const ImVec2 & v) inline
Definition at line 518 of file imgui_internal.h.
References ImFloor(), ImVec2::x, and ImVec2::y.
ImFloor() [2/2]
float ImFloor (float f) inline
Definition at line 517 of file imgui_internal.h.
Referenced by ImGuiIO::AddMousePosEvent(), ImPlot::AddTextVertical(), ImGui::Begin(), BoxSelectScrollWithMouseDrag(), ImPlot::EndPlot(), ImPlot::EndSubplots(), ImFloor(), ImGui_ImplStbTrueType_FontBakedInit(), ImDrawList::PathArcTo(), ScaleWindow(), ImGui::TableAngledHeadersRowEx(), ImGui::TextLink(), and ImGui::UpdateMouseInputs().
ImFontAtlasAddDrawListSharedData()
void ImFontAtlasAddDrawListSharedData (ImFontAtlas * atlas, ImDrawListSharedData * data)
Definition at line 3903 of file imgui_draw.cpp.
References ImVector< T >::contains(), ImFontAtlas::DrawListSharedDatas, IM_ASSERT, and ImVector< T >::push_back().
Referenced by ImGui::RegisterFontAtlas().
ImFontAtlasBakedAdd()
ImFontBaked * ImFontAtlasBakedAdd (ImFontAtlas * atlas, ImFont * font, float font_size, float font_rasterizer_density, ImGuiID baked_id)
Definition at line 3783 of file imgui_draw.cpp.
References ImFontBaked::BakedId, ImFontAtlasBuilder::BakedPool, ImFontAtlas::Builder, ImFontLoader::FontBakedInit, ImFontLoader::FontBakedSrcLoaderDataSize, ImFontAtlas::FontLoader, ImFontBaked::FontLoaderDatas, ImFontAtlasBuilder::FrameCount, IM_ALLOC, ImFontAtlasBuildSetupFontBakedBlanks(), IMGUI_DEBUG_LOG_FONT, ImFontBaked::LastUsedFrame, ImFontBaked::OwnerFont, ImStableVector< T, BLOCKSIZE >::push_back(), ImFontBaked::RasterizerDensity, ImFontBaked::Size, and ImFont::Sources.
Referenced by ImFontAtlasBakedGetOrAdd().
ImFontAtlasBakedAddFontGlyph()
ImFontGlyph * ImFontAtlasBakedAddFontGlyph (ImFontAtlas * atlas, ImFontBaked * baked, ImFontConfig * src, const ImFontGlyph * in_glyph)
Definition at line 5129 of file imgui_draw.cpp.
References ImFontGlyph::AdvanceX, ImFontGlyph::Codepoint, ImFontGlyph::Colored, ImFontConfig::GlyphExtraAdvanceX, ImFontConfig::GlyphMaxAdvanceX, ImFontConfig::GlyphMinAdvanceX, ImFontBaked::Glyphs, ImTextureRect::h, IM_ASSERT, IM_ROUND, ImClamp(), ImFontAtlasPackGetRect(), ImFontAtlasRectId_Invalid, ImFontBaked_BuildGrowIndex(), ImTrunc(), ImFontBaked::IndexAdvanceX, ImFontBaked::IndexLookup, ImFontBaked::MetricsTotalSurface, ImFontBaked::OwnerFont, ImFontGlyph::PackId, ImFontConfig::PixelSnapH, ImVector< T >::push_back(), ImVector< T >::Size, ImFontBaked::Size, ImFont::Sources, ImFontAtlas::TexData, ImFontAtlas::TexPixelsUseColors, ImFontAtlas::TexUvScale, ImFontGlyph::U0, ImFontGlyph::U1, ImTextureData::UseColors, ImFont::Used8kPagesMap, ImFontGlyph::V0, ImFontGlyph::V1, ImTextureRect::w, ImVec2::x, ImTextureRect::x, ImFontGlyph::X0, ImFontGlyph::X1, ImVec2::y, and ImTextureRect::y.
Referenced by ImFontAtlas::AddCustomRectFontGlyphForSize(), ImFontAtlasBuildSetupFontBakedBlanks(), ImFontAtlasBuildSetupFontBakedEllipsis(), ImFontAtlasBuildSetupFontBakedFallback(), and ImFontBaked_BuildLoadGlyph().
ImFontAtlasBakedAddFontGlyphAdvancedX()
void ImFontAtlasBakedAddFontGlyphAdvancedX (ImFontAtlas * atlas, ImFontBaked * baked, ImFontConfig * src, ImWchar codepoint, float advance_x)
Definition at line 5183 of file imgui_draw.cpp.
References ImFontConfig::GlyphExtraAdvanceX, ImFontConfig::GlyphMaxAdvanceX, ImFontConfig::GlyphMinAdvanceX, IM_ROUND, IM_UNUSED, ImClamp(), ImFontBaked_BuildGrowIndex(), ImFontBaked::IndexAdvanceX, ImFontBaked::OwnerFont, ImFontConfig::PixelSnapH, ImFontBaked::Size, and ImFont::Sources.
Referenced by ImFontBaked_BuildLoadGlyph().
ImFontAtlasBakedDiscard()
void ImFontAtlasBakedDiscard (ImFontAtlas * atlas, ImFont * font, ImFontBaked * baked)
Definition at line 3843 of file imgui_draw.cpp.
References ImFontAtlasBuilder::BakedDiscardedCount, ImFontBaked::BakedId, ImFontAtlasBuilder::BakedMap, ImFontAtlas::Builder, ImFontBaked::ClearOutputData(), ImFontLoader::FontBakedDestroy, ImFontLoader::FontBakedSrcLoaderDataSize, ImFontAtlas::FontLoader, ImFontBaked::FontLoaderDatas, ImFont::GetDebugName(), ImFontBaked::Glyphs, IM_FREE, ImFontAtlasPackDiscardRect(), ImFontAtlasRectId_Invalid, IMGUI_DEBUG_LOG_FONT, ImFont::LastBaked, ImGuiStorage::SetVoidPtr(), ImFontBaked::Size, ImFont::Sources, and ImFontBaked::WantDestroy.
Referenced by ImFontAtlasBuildDiscardBakes(), and ImFontAtlasFontDiscardBakes().
ImFontAtlasBakedDiscardFontGlyph()
void ImFontAtlasBakedDiscardFontGlyph (ImFontAtlas * atlas, ImFont * font, ImFontBaked * baked, ImFontGlyph * glyph)
Definition at line 3768 of file imgui_draw.cpp.
References ImFontGlyph::Codepoint, ImVector< T >::Data, ImFont::EllipsisChar, ImFontBaked::FallbackAdvanceX, ImFont::FallbackChar, ImFontBaked::Glyphs, IM_ASSERT, IM_FONTGLYPH_INDEX_UNUSED, IM_UNUSED, ImFontAtlasPackDiscardRect(), ImFontAtlasRectId_Invalid, ImFontBaked::IndexAdvanceX, ImFontBaked::IndexLookup, ImFontGlyph::PackId, and ImVector< T >::Size.
Referenced by ImFontAtlas::AddCustomRectFontGlyphForSize().
ImFontAtlasBakedGetClosestMatch()
ImFontBaked * ImFontAtlasBakedGetClosestMatch (ImFontAtlas * atlas, ImFont * font, float font_size, float font_rasterizer_density)
Definition at line 3815 of file imgui_draw.cpp.
References ImFontAtlasBuilder::BakedPool, ImFontAtlas::Builder, ImFontBaked::OwnerFont, ImFontBaked::RasterizerDensity, ImFontBaked::Size, ImStableVector< T, BLOCKSIZE >::Size, and ImFontBaked::WantDestroy.
Referenced by ImFontAtlasBakedGetOrAdd().
ImFontAtlasBakedGetId()
ImGuiID ImFontAtlasBakedGetId (ImGuiID font_id, float baked_size, float rasterizer_density)
Definition at line 5295 of file imgui_draw.cpp.
References ImHashData().
Referenced by ImFontAtlasBakedGetOrAdd().
ImFontAtlasBakedGetOrAdd()
ImFontBaked * ImFontAtlasBakedGetOrAdd (ImFontAtlas * atlas, ImFont * font, float font_size, float font_rasterizer_density)
Definition at line 5328 of file imgui_draw.cpp.
References ImFontBaked::BakedId, ImFontAtlasBuilder::BakedMap, ImFontAtlas::Builder, ImFont::Flags, ImFont::FontId, ImGuiStorage::GetVoidPtrRef(), IM_ASSERT, ImFontAtlasBakedAdd(), ImFontAtlasBakedGetClosestMatch(), ImFontAtlasBakedGetId(), ImFontFlags_LockBakedSizes, ImFontAtlas::Locked, ImFontBaked::OwnerFont, and ImFontBaked::Size.
Referenced by ImFont::GetFontBaked().
ImFontAtlasBakedSetFontGlyphBitmap()
void ImFontAtlasBakedSetFontGlyphBitmap (ImFontAtlas * atlas, ImFontBaked * baked, ImFontConfig * src, ImFontGlyph * glyph, ImTextureRect * r, const unsigned char * src_pixels, ImTextureFormat src_fmt, int src_pitch)
Definition at line 5206 of file imgui_draw.cpp.
References ImTextureData::Format, ImTextureData::GetPitch(), ImTextureData::GetPixelsAt(), ImTextureRect::h, ImTextureData::Height, IM_ASSERT, ImFontAtlasTextureBlockConvert(), ImFontAtlasTextureBlockPostProcess(), ImFontAtlasTextureBlockQueueUpload(), ImFontBaked::OwnerFont, ImFontAtlas::TexData, ImTextureRect::w, ImTextureData::Width, ImTextureRect::x, and ImTextureRect::y.
Referenced by ImGui_ImplFreeType_FontBakedLoadGlyph(), and ImGui_ImplStbTrueType_FontBakedLoadGlyph().
ImFontAtlasBuildClear()
void ImFontAtlasBuildClear (ImFontAtlas * atlas)
Definition at line 4166 of file imgui_draw.cpp.
References ImFontAtlas::Fonts, ImFontAtlasBuildDestroy(), ImFontAtlasBuildInit(), ImFontAtlasFontSourceAddToFont(), ImFontAtlasFontSourceInit(), ImFontAtlasTextureAdd(), ImFontAtlasTextureGetSizeEstimate(), ImFontAtlas::Sources, ImVec2i::x, and ImVec2i::y.
Referenced by ImFontAtlasBuildMain(), and ImGui::ShowFontAtlas().
ImFontAtlasBuildDestroy()
void ImFontAtlasBuildDestroy (ImFontAtlas * atlas)
Definition at line 4240 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontAtlas::FontLoader, ImFontAtlas::FontLoaderData, ImFontAtlas::Fonts, IM_ASSERT, IM_DELETE(), ImFontAtlasFontDestroyOutput(), and ImFontLoader::LoaderShutdown.
Referenced by ImFontAtlas::ClearFonts(), and ImFontAtlasBuildClear().
ImFontAtlasBuildDiscardBakes()
void ImFontAtlasBuildDiscardBakes (ImFontAtlas * atlas, int unused_frames)
Definition at line 3888 of file imgui_draw.cpp.
References ImFontAtlasBuilder::BakedPool, ImFontAtlas::Builder, ImFont::Flags, ImFontAtlasBuilder::FrameCount, ImFontAtlasBakedDiscard(), ImFontFlags_LockBakedSizes, ImFontBaked::LastUsedFrame, ImFontBaked::OwnerFont, ImStableVector< T, BLOCKSIZE >::Size, and ImFontBaked::WantDestroy.
Referenced by ImFontAtlasTextureCompact(), and ImFontAtlasTextureMakeSpace().
ImFontAtlasBuildGetOversampleFactors()
void ImFontAtlasBuildGetOversampleFactors (ImFontConfig * src, ImFontBaked * baked, int * out_oversample_h, int * out_oversample_v)
Definition at line 3393 of file imgui_draw.cpp.
References ImFontConfig::OversampleH, ImFontConfig::OversampleV, ImFontConfig::PixelSnapH, ImFontConfig::RasterizerDensity, ImFontBaked::RasterizerDensity, and ImFontBaked::Size.
Referenced by ImGui::DebugNodeFont(), and ImGui_ImplStbTrueType_FontBakedLoadGlyph().
ImFontAtlasBuildInit()
void ImFontAtlasBuildInit (ImFontAtlas * atlas)
Definition at line 4196 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontAtlas::FontLoader, ImGuiFreeType::GetFontLoader(), IM_ASSERT, IM_NEW, ImFontAtlasBuildUpdateBasicTexData(), ImFontAtlasBuildUpdateLinesTexData(), ImFontAtlasBuildUpdatePointers(), ImFontAtlasBuildUpdateRendererHasTexturesFromContext(), ImFontAtlasGetFontLoaderForStbTruetype(), ImFontAtlasPackInit(), ImFontAtlasTextureAdd(), ImFontAtlasUpdateDrawListsSharedData(), ImUpperPowerOfTwo(), ImFontLoader::LoaderInit, ImTextureData::Pixels, ImFontAtlas::SetFontLoader(), ImFontAtlas::TexData, ImFontAtlas::TexMinHeight, and ImFontAtlas::TexMinWidth.
Referenced by ImFontAtlas::AddCustomRect(), ImFontAtlas::AddFont(), ImFontAtlasBuildClear(), ImFontAtlasBuildMain(), and ImFontAtlasPackGetRectSafe().
ImFontAtlasBuildLegacyPreloadAllGlyphRanges()
void ImFontAtlasBuildLegacyPreloadAllGlyphRanges (ImFontAtlas * atlas)
Definition at line 3429 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontBaked::FindGlyph(), ImFontAtlas::Fonts, ImFontAtlas::GetGlyphRangesDefault(), IM_UNICODE_CODEPOINT_MAX, and ImFontAtlasBuilder::PreloadedAllGlyphsRanges.
Referenced by ImFontAtlasBuildMain().
ImFontAtlasBuildMain()
void ImFontAtlasBuildMain (ImFontAtlas * atlas)
Definition at line 3373 of file imgui_draw.cpp.
References ImFontAtlas::AddFontDefault(), ImFontAtlas::Builder, ImTextureData::Format, IM_ASSERT, ImFontAtlasBuildClear(), ImFontAtlasBuildInit(), ImFontAtlasBuildLegacyPreloadAllGlyphRanges(), ImFontAtlasBuildUpdateRendererHasTexturesFromContext(), ImFontAtlas::Locked, ImFontAtlas::RendererHasTextures, ImVector< T >::Size, ImFontAtlas::Sources, ImFontAtlas::TexData, ImFontAtlas::TexDesiredFormat, and ImFontAtlas::TexIsBuilt.
Referenced by ImFontAtlas::Build(), ImGui::GetDefaultFont(), and ImFontAtlasUpdateNewFrame().
ImFontAtlasBuildNotifySetFont()
void ImFontAtlasBuildNotifySetFont (ImFontAtlas * atlas, ImFont * old_font, ImFont * new_font)
Definition at line 3203 of file imgui_draw.cpp.
References ImFontAtlas::DrawListSharedDatas, ImGui::GetCurrentContext(), ImGui::SetCurrentContext(), and ImGui::SetCurrentFont().
Referenced by ImFontAtlas::ClearFonts(), and ImFontAtlas::RemoveFont().
ImFontAtlasBuildRenderBitmapFromString()
void ImFontAtlasBuildRenderBitmapFromString (ImFontAtlas * atlas, int x, int y, int w, int h, const char * in_str, char in_marker_char)
Definition at line 3459 of file imgui_draw.cpp.
References ImTextureData::Format, ImTextureData::GetPixelsAt(), IM_ASSERT, IM_COL32_BLACK_TRANS, IM_COL32_WHITE, ImTextureFormat_Alpha8, ImTextureFormat_RGBA32, ImFontAtlas::TexData, and ImTextureData::Width.
Referenced by ImFontAtlasBuildUpdateBasicTexData().
ImFontAtlasBuildSetupFontLoader()
void ImFontAtlasBuildSetupFontLoader (ImFontAtlas * atlas, const ImFontLoader * font_loader)
Definition at line 3403 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontAtlas::FontLoader, ImFontAtlas::FontLoaderData, ImFontAtlas::FontLoaderName, ImFontAtlas::Fonts, IM_ASSERT, ImFontAtlasFontDestroyOutput(), ImFontAtlasFontInitOutput(), ImFontAtlasFontSourceAddToFont(), ImFontLoader::LoaderInit, ImFontLoader::LoaderShutdown, ImFontAtlas::Locked, and ImFontLoader::Name.
Referenced by ImFontAtlas::SetFontLoader().
ImFontAtlasBuildSetupFontSpecialGlyphs()
void ImFontAtlasBuildSetupFontSpecialGlyphs (ImFontAtlas * atlas, ImFont * font, ImFontConfig * src)
Definition at line 3735 of file imgui_draw.cpp.
References ImVector< T >::contains(), ImFont::EllipsisAutoBake, ImFontConfig::EllipsisChar, ImFont::EllipsisChar, ImFont::FallbackChar, IM_ASSERT, IM_UNICODE_CODEPOINT_INVALID, IM_UNUSED, ImFont::IsGlyphInFont(), and ImFont::Sources.
Referenced by ImFontAtlasFontSourceAddToFont().
ImFontAtlasBuildUpdatePointers()
void ImFontAtlasBuildUpdatePointers (ImFontAtlas * atlas)
Definition at line 3450 of file imgui_draw.cpp.
References ImFontAtlas::Fonts, and ImFontAtlas::Sources.
Referenced by ImFontAtlas::AddFont(), ImFontAtlasBuildInit(), and ImFontAtlas::RemoveFont().
ImFontAtlasDebugLogTextureRequests()
void ImFontAtlasDebugLogTextureRequests (ImFontAtlas * atlas)
Definition at line 4531 of file imgui_draw.cpp.
References ImGuiIO::BackendFlags, ImTextureData::BackendUserData, ImGui::DebugTextureIDToU64(), GImGui, ImTextureData::Height, IM_ASSERT, IM_PRIX64, IM_UNUSED, IMGUI_DEBUG_LOG_FONT, ImGuiBackendFlags_RendererHasTextures, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImGuiContext::IO, ImVector< T >::Size, ImTextureData::Status, ImTextureData::TexID, ImFontAtlas::TexList, ImTextureData::UniqueID, ImTextureData::Updates, and ImTextureData::Width.
Referenced by ImGui::Render().
ImFontAtlasFontDestroyOutput()
void ImFontAtlasFontDestroyOutput (ImFontAtlas * atlas, ImFont * font)
Definition at line 3598 of file imgui_draw.cpp.
References ImFont::ClearOutputData(), ImFontAtlas::FontLoader, ImFontLoader::FontSrcDestroy, and ImFont::Sources.
Referenced by ImFontAtlas::ClearInputData(), ImGui::DebugNodeFont(), ImFontAtlasBuildDestroy(), ImFontAtlasBuildSetupFontLoader(), ImFontAtlas::RemoveFont(), and ImGui::ShowFontAtlas().
ImFontAtlasFontDestroySourceData()
void ImFontAtlasFontDestroySourceData (ImFontAtlas * atlas, ImFontConfig * src)
Definition at line 3632 of file imgui_draw.cpp.
References ImFontConfig::FontData, ImFontConfig::FontDataOwnedByAtlas, ImFontConfig::GlyphExcludeRanges, IM_FREE, and IM_UNUSED.
Referenced by ImFontAtlas::AddFont(), ImFontAtlas::ClearInputData(), and ImFontAtlas::RemoveFont().
ImFontAtlasFontDiscardBakes()
void ImFontAtlasFontDiscardBakes (ImFontAtlas * atlas, ImFont * font, int unused_frames)
Definition at line 3873 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontAtlasBuilder::FrameCount, ImFontAtlasBakedDiscard(), ImFontBaked::LastUsedFrame, ImFontBaked::OwnerFont, and ImFontBaked::WantDestroy.
Referenced by ImFont::ClearOutputData(), and ImGui::DebugNodeFont().
ImFontAtlasFontInitOutput()
bool ImFontAtlasFontInitOutput (ImFontAtlas * atlas, ImFont * font)
Definition at line 3587 of file imgui_draw.cpp.
References IM_ASSERT, ImFontAtlasFontSourceInit(), and ImFont::Sources.
Referenced by ImGui::DebugNodeFont(), ImFontAtlasBuildSetupFontLoader(), and ImGui::ShowFontAtlas().
ImFontAtlasFontSourceAddToFont()
void ImFontAtlasFontSourceAddToFont (ImFontAtlas * atlas, ImFont * font, ImFontConfig * src)
Definition at line 3619 of file imgui_draw.cpp.
References ImFont::ClearOutputData(), IM_ASSERT, ImFontAtlasBuildSetupFontSpecialGlyphs(), ImFontConfig::MergeMode, ImFont::OwnerAtlas, ImFont::Sources, and ImFontAtlas::TexIsBuilt.
Referenced by ImFontAtlas::AddFont(), ImFontAtlasBuildClear(), and ImFontAtlasBuildSetupFontLoader().
ImFontAtlasFontSourceInit()
bool ImFontAtlasFontSourceInit (ImFontAtlas * atlas, ImFontConfig * src)
Definition at line 3611 of file imgui_draw.cpp.
References ImFontConfig::FontLoader, ImFontAtlas::FontLoader, and ImFontLoader::FontSrcInit.
Referenced by ImFontAtlas::AddFont(), ImFontAtlasBuildClear(), and ImFontAtlasFontInitOutput().
ImFontAtlasGetFontLoaderForStbTruetype()
const ImFontLoader * ImFontAtlasGetFontLoaderForStbTruetype ()
Definition at line 4737 of file imgui_draw.cpp.
References ImFontLoader::FontBakedDestroy, ImFontLoader::FontBakedInit, ImFontLoader::FontBakedLoadGlyph, ImFontLoader::FontSrcContainsGlyph, ImFontLoader::FontSrcDestroy, ImFontLoader::FontSrcInit, ImGui_ImplStbTrueType_FontBakedInit(), ImGui_ImplStbTrueType_FontBakedLoadGlyph(), ImGui_ImplStbTrueType_FontSrcContainsGlyph(), ImGui_ImplStbTrueType_FontSrcDestroy(), ImGui_ImplStbTrueType_FontSrcInit(), and ImFontLoader::Name.
Referenced by ImFontAtlasBuildInit(), and ImGui::ShowFontAtlas().
ImFontAtlasGetMouseCursorTexData()
bool ImFontAtlasGetMouseCursorTexData (ImFontAtlas * atlas, ImGuiMouseCursor cursor_type, ImVec2 * out_offset, ImVec2 * out_size, ImVec2 out_uv_border[2], ImVec2 out_uv_fill[2])
Definition at line 3352 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontAtlas::Flags, FONT_ATLAS_DEFAULT_TEX_CURSOR_DATA, FONT_ATLAS_DEFAULT_TEX_DATA_W, ImFontAtlasFlags_NoMouseCursors, ImFontAtlasPackGetRect(), ImGuiMouseCursor_COUNT, ImFontAtlasBuilder::PackIdMouseCursors, ImFontAtlas::TexUvScale, ImVec2::x, ImTextureRect::x, and ImTextureRect::y.
Referenced by ImGui::RenderMouseCursor().
ImFontAtlasPackAddRect()
ImFontAtlasRectId ImFontAtlasPackAddRect (ImFontAtlas * atlas, int w, int h, ImFontAtlasRectEntry * overwrite_entry = NULL)
Definition at line 4330 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImTextureRect::h, stbrp_rect::h, IM_ASSERT, ImFontAtlasPackAllocRectEntry(), ImFontAtlasPackReuseRectEntry(), ImFontAtlasRectId_Invalid, ImFontAtlasTextureMakeSpace(), IMGUI_DEBUG_LOG_FONT, ImMax(), ImFontAtlasBuilder::LockDisableResize, ImFontAtlasBuilder::MaxRectBounds, ImFontAtlasBuilder::MaxRectSize, ImFontAtlasBuilder::PackContext, ImVector< T >::push_back(), ImFontAtlasBuilder::Rects, ImFontAtlasBuilder::RectsPackedCount, ImFontAtlasBuilder::RectsPackedSurface, ImVector< T >::Size, stbrp_pack_rects(), ImFontAtlas::TexGlyphPadding, ImTextureRect::w, stbrp_rect::w, stbrp_rect::was_packed, ImTextureRect::x, ImVec2i::x, stbrp_rect::x, ImTextureRect::y, ImVec2i::y, and stbrp_rect::y.
Referenced by ImFontAtlas::AddCustomRect(), ImFontAtlas::AddCustomRectFontGlyphForSize(), ImFontAtlasBuildSetupFontBakedEllipsis(), ImFontAtlasTextureRepack(), ImGui_ImplFreeType_FontBakedLoadGlyph(), and ImGui_ImplStbTrueType_FontBakedLoadGlyph().
ImFontAtlasPackDiscardRect()
void ImFontAtlasPackDiscardRect (ImFontAtlas * atlas, ImFontAtlasRectId id)
Definition at line 4303 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontAtlasRectEntry::Generation, ImTextureRect::h, IM_ASSERT, ImFontAtlasPackGetRect(), ImFontAtlasRectId_GetIndex(), ImFontAtlasRectId_Invalid, ImFontAtlasRectEntry::IsUsed, ImFontAtlasBuilder::RectsDiscardedCount, ImFontAtlasBuilder::RectsDiscardedSurface, ImFontAtlasBuilder::RectsIndex, ImFontAtlasBuilder::RectsIndexFreeListStart, ImFontAtlasRectEntry::TargetIndex, ImFontAtlas::TexGlyphPadding, and ImTextureRect::w.
Referenced by ImFontAtlasBakedDiscard(), ImFontAtlasBakedDiscardFontGlyph(), and ImFontAtlas::RemoveCustomRect().
ImFontAtlasPackGetRect()
ImTextureRect * ImFontAtlasPackGetRect (ImFontAtlas * atlas, ImFontAtlasRectId id)
Definition at line 4378 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontAtlasRectEntry::Generation, IM_ASSERT, ImFontAtlasRectId_GetGeneration(), ImFontAtlasRectId_GetIndex(), ImFontAtlasRectId_Invalid, ImFontAtlasRectEntry::IsUsed, ImFontAtlasBuilder::Rects, ImFontAtlasBuilder::RectsIndex, and ImFontAtlasRectEntry::TargetIndex.
Referenced by ImFontAtlas::AddCustomRect(), ImFontAtlas::AddCustomRectFontGlyphForSize(), ImGui::DebugNodeFontGlyph(), ImFontAtlasBakedAddFontGlyph(), ImFontAtlasBuildSetupFontBakedEllipsis(), ImFontAtlasGetMouseCursorTexData(), ImFontAtlasPackDiscardRect(), ImFontAtlasTextureRepack(), ImGui_ImplFreeType_FontBakedLoadGlyph(), and ImGui_ImplStbTrueType_FontBakedLoadGlyph().
ImFontAtlasPackGetRectSafe()
ImTextureRect * ImFontAtlasPackGetRectSafe (ImFontAtlas * atlas, ImFontAtlasRectId id)
Definition at line 4391 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontAtlasRectEntry::Generation, IM_MSVC_WARNING_SUPPRESS, ImFontAtlasBuildInit(), ImFontAtlasRectId_GetGeneration(), ImFontAtlasRectId_GetIndex(), ImFontAtlasRectId_Invalid, ImFontAtlasRectEntry::IsUsed, ImFontAtlasBuilder::Rects, ImFontAtlasBuilder::RectsIndex, ImVector< T >::Size, and ImFontAtlasRectEntry::TargetIndex.
Referenced by ImFontAtlas::GetCustomRect(), and ImFontAtlas::RemoveCustomRect().
ImFontAtlasPackInit()
void ImFontAtlasPackInit (ImFontAtlas * atlas)
Definition at line 4253 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImTextureData::Height, IM_STATIC_ASSERT, ImFontAtlasBuilder::MaxRectBounds, ImFontAtlasBuilder::MaxRectSize, ImFontAtlasBuilder::PackContext, ImFontAtlasBuilder::PackNodes, ImFontAtlasBuilder::RectsPackedCount, ImFontAtlasBuilder::RectsPackedSurface, stbrp_init_target(), ImFontAtlas::TexData, and ImTextureData::Width.
Referenced by ImFontAtlasBuildInit(), and ImFontAtlasTextureRepack().
ImFontAtlasRectId_GetGeneration()
unsigned int ImFontAtlasRectId_GetGeneration (ImFontAtlasRectId id) inline
Definition at line 3799 of file imgui_internal.h.
References ImFontAtlasRectId_GenerationMask_, and ImFontAtlasRectId_GenerationShift_.
Referenced by ImFontAtlasPackGetRect(), and ImFontAtlasPackGetRectSafe().
ImFontAtlasRectId_GetIndex()
int ImFontAtlasRectId_GetIndex (ImFontAtlasRectId id) inline
Definition at line 3798 of file imgui_internal.h.
References ImFontAtlasRectId_IndexMask_.
Referenced by ImFontAtlasPackDiscardRect(), ImFontAtlasPackGetRect(), ImFontAtlasPackGetRectSafe(), and ImFontAtlasTextureRepack().
ImFontAtlasRectId_Make()
ImFontAtlasRectId ImFontAtlasRectId_Make (int index_idx, int gen_idx) inline
Definition at line 3800 of file imgui_internal.h.
References IM_ASSERT, ImFontAtlasRectId_GenerationMask_, ImFontAtlasRectId_GenerationShift_, and ImFontAtlasRectId_IndexMask_.
Referenced by ImFontAtlasPackAllocRectEntry(), ImFontAtlasPackReuseRectEntry(), and ImGui::ShowFontAtlas().
ImFontAtlasRemoveDrawListSharedData()
void ImFontAtlasRemoveDrawListSharedData (ImFontAtlas * atlas, ImDrawListSharedData * data)
Definition at line 3909 of file imgui_draw.cpp.
References ImVector< T >::contains(), ImFontAtlas::DrawListSharedDatas, ImVector< T >::find_erase(), and IM_ASSERT.
Referenced by ImGui::UnregisterFontAtlas().
ImFontAtlasTextureAdd()
ImTextureData * ImFontAtlasTextureAdd (ImFontAtlas * atlas, int w, int h)
Definition at line 3964 of file imgui_draw.cpp.
References ImTextureData::Create(), IM_ASSERT, IM_NEW, ImFontAtlasBuildSetTexture(), ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantUpdates, ImVector< T >::push_back(), ImTextureData::Status, ImFontAtlas::TexData, ImFontAtlas::TexDesiredFormat, ImFontAtlas::TexIsBuilt, ImFontAtlas::TexList, ImFontAtlas::TexNextUniqueID, ImTextureData::UniqueID, and ImTextureData::WantDestroyNextFrame.
Referenced by ImFontAtlasBuildClear(), ImFontAtlasBuildInit(), and ImFontAtlasTextureRepack().
ImFontAtlasTextureBlockConvert()
void ImFontAtlasTextureBlockConvert (const unsigned char * src_pixels, ImTextureFormat src_fmt, int src_pitch, unsigned char * dst_pixels, ImTextureFormat dst_fmt, int dst_pitch, int w, int h)
Definition at line 2847 of file imgui_draw.cpp.
References IM_ASSERT, IM_COL32, IM_COL32_A_SHIFT, ImTextureDataGetFormatBytesPerPixel(), ImTextureFormat_Alpha8, and ImTextureFormat_RGBA32.
Referenced by ImFontAtlasBakedSetFontGlyphBitmap().
ImFontAtlasTextureBlockCopy()
void ImFontAtlasTextureBlockCopy (ImTextureData * src_tex, int src_x, int src_y, ImTextureData * dst_tex, int dst_x, int dst_y, int w, int h)
Definition at line 2946 of file imgui_draw.cpp.
References ImTextureData::BytesPerPixel, ImTextureData::Format, ImTextureData::GetPixelsAt(), IM_ASSERT, and ImTextureData::Pixels.
Referenced by ImFontAtlasBuildSetupFontBakedEllipsis(), and ImFontAtlasTextureRepack().
ImFontAtlasTextureBlockFill()
void ImFontAtlasTextureBlockFill (ImTextureData * dst_tex, int dst_x, int dst_y, int w, int h, ImU32 col)
Definition at line 2926 of file imgui_draw.cpp.
References ImTextureData::Format, ImTextureData::GetPixelsAt(), IM_COL32_A_SHIFT, and ImTextureFormat_Alpha8.
ImFontAtlasTextureBlockPostProcess()
void ImFontAtlasTextureBlockPostProcess (ImFontAtlasPostProcessData * data)
Definition at line 2884 of file imgui_draw.cpp.
References ImFontAtlasTextureBlockPostProcessMultiply().
Referenced by ImFontAtlasBakedSetFontGlyphBitmap().
ImFontAtlasTextureBlockPostProcessMultiply()
void ImFontAtlasTextureBlockPostProcessMultiply (ImFontAtlasPostProcessData * data, float multiply_factor)
Definition at line 2891 of file imgui_draw.cpp.
References IM_ASSERT, IM_COL32, IM_COL32_A_SHIFT, IM_COL32_B_SHIFT, IM_COL32_G_SHIFT, IM_COL32_R_SHIFT, ImMin(), ImTextureFormat_Alpha8, and ImTextureFormat_RGBA32.
Referenced by ImFontAtlasTextureBlockPostProcess().
ImFontAtlasTextureBlockQueueUpload()
void ImFontAtlasTextureBlockQueueUpload (ImFontAtlas * atlas, ImTextureData * tex, int x, int y, int w, int h)
Definition at line 2959 of file imgui_draw.cpp.
References ImTextureRect::h, IM_ASSERT, IM_UNUSED, ImMax(), ImMin(), ImTextureStatus_Destroyed, ImTextureStatus_OK, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImVector< T >::push_back(), ImTextureData::Status, ImFontAtlas::TexIsBuilt, ImTextureData::UpdateRect, ImTextureData::Updates, ImTextureData::UsedRect, ImTextureRect::w, ImTextureRect::x, and ImTextureRect::y.
Referenced by ImFontAtlas::AddCustomRect(), ImFontAtlas::AddCustomRectFontGlyphForSize(), ImFontAtlasBakedSetFontGlyphBitmap(), and ImFontAtlasBuildSetupFontBakedEllipsis().
ImFontAtlasTextureCompact()
void ImFontAtlasTextureCompact (ImFontAtlas * atlas)
Definition at line 4181 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImTextureData::Height, ImFontAtlasBuildDiscardBakes(), ImFontAtlasTextureGetSizeEstimate(), ImFontAtlasTextureRepack(), ImFontAtlasBuilder::RectsDiscardedCount, ImFontAtlas::TexData, ImTextureData::Width, ImVec2i::x, and ImVec2i::y.
Referenced by ImFontAtlas::CompactCache().
ImFontAtlasTextureGetSizeEstimate()
ImVec2i ImFontAtlasTextureGetSizeEstimate (ImFontAtlas * atlas)
Definition at line 4131 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImFontAtlas::Flags, IM_ASSERT, ImFontAtlasFlags_NoPowerOfTwoHeight, ImIsPowerOfTwo(), ImMax(), ImTextureStatus_WantDestroy, ImUpperPowerOfTwo(), ImFontAtlasBuilder::MaxRectSize, ImFontAtlasBuilder::RectsDiscardedSurface, ImFontAtlasBuilder::RectsPackedSurface, ImTextureData::Status, ImFontAtlas::TexData, ImFontAtlas::TexMinHeight, ImFontAtlas::TexMinWidth, ImVec2i::x, and ImVec2i::y.
Referenced by ImFontAtlasBuildClear(), and ImFontAtlasTextureCompact().
ImFontAtlasTextureGrow()
void ImFontAtlasTextureGrow (ImFontAtlas * atlas, int old_w = -1, int old_h = -1)
Definition at line 4085 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImTextureData::Height, IM_ASSERT, ImClamp(), ImFontAtlasTextureRepack(), ImIsPowerOfTwo(), ImMax(), ImUpperPowerOfTwo(), ImFontAtlasBuilder::MaxRectSize, ImFontAtlas::TexData, ImFontAtlas::TexGlyphPadding, ImFontAtlas::TexMaxHeight, ImFontAtlas::TexMaxWidth, ImFontAtlas::TexMinHeight, ImFontAtlas::TexMinWidth, ImTextureData::Width, ImVec2i::x, and ImVec2i::y.
Referenced by ImFontAtlasTextureMakeSpace(), ImFontAtlasTextureRepack(), and ImGui::ShowFontAtlas().
ImFontAtlasTextureMakeSpace()
void ImFontAtlasTextureMakeSpace (ImFontAtlas * atlas)
Definition at line 4117 of file imgui_draw.cpp.
References ImFontAtlas::Builder, ImTextureData::Height, ImFontAtlasBuildDiscardBakes(), ImFontAtlasTextureGrow(), ImFontAtlasTextureRepack(), ImFontAtlasBuilder::RectsDiscardedSurface, ImFontAtlasBuilder::RectsPackedSurface, ImFontAtlas::TexData, and ImTextureData::Width.
Referenced by ImFontAtlasPackAddRect().
ImFontAtlasTextureRepack()
void ImFontAtlasTextureRepack (ImFontAtlas * atlas, int w, int h)
Definition at line 4013 of file imgui_draw.cpp.
References ImFontAtlasBuilder::BakedPool, ImFontAtlas::Builder, ImTextureRect::h, ImTextureData::Height, IM_ASSERT, ImFontAtlasBuildSetTexture(), ImFontAtlasBuildUpdateBasicTexData(), ImFontAtlasBuildUpdateLinesTexData(), ImFontAtlasPackAddRect(), ImFontAtlasPackGetRect(), ImFontAtlasPackInit(), ImFontAtlasRectId_GetIndex(), ImFontAtlasRectId_Invalid, ImFontAtlasTextureAdd(), ImFontAtlasTextureBlockCopy(), ImFontAtlasTextureGrow(), ImFontAtlasUpdateDrawListsSharedData(), IMGUI_DEBUG_LOG_FONT, ImVector< T >::index_from_ptr(), ImFontAtlasBuilder::LockDisableResize, ImFontAtlasBuilder::Rects, ImFontAtlasBuilder::RectsDiscardedCount, ImFontAtlasBuilder::RectsDiscardedSurface, ImFontAtlasBuilder::RectsIndex, ImVector< T >::Size, ImStableVector< T, BLOCKSIZE >::Size, ImVector< T >::swap(), ImFontAtlas::TexData, ImFontAtlas::TexUvScale, ImTextureData::UniqueID, ImTextureData::UseColors, ImTextureRect::w, ImTextureData::WantDestroyNextFrame, ImTextureData::Width, ImVec2::x, ImTextureRect::x, ImVec2::y, and ImTextureRect::y.
Referenced by ImFontAtlasTextureCompact(), ImFontAtlasTextureGrow(), and ImFontAtlasTextureMakeSpace().
ImFontAtlasUpdateDrawListsSharedData()
void ImFontAtlasUpdateDrawListsSharedData (ImFontAtlas * atlas)
Definition at line 3942 of file imgui_draw.cpp.
References ImFontAtlas::DrawListSharedDatas, ImFontAtlas::TexUvLines, and ImFontAtlas::TexUvWhitePixel.
Referenced by ImFontAtlasBuildInit(), ImFontAtlasTextureRepack(), and ImGui::SetCurrentFont().
ImFontAtlasUpdateDrawListsTextures()
void ImFontAtlasUpdateDrawListsTextures (ImFontAtlas * atlas, ImTextureRef old_tex, ImTextureRef new_tex)
Definition at line 3916 of file imgui_draw.cpp.
References ImDrawList::_CmdHeader, ImDrawList::_SetTexture(), ImDrawList::_TextureStack, ImDrawList::CmdBuffer, ImFontAtlas::DrawListSharedDatas, ImVector< T >::Size, and ImDrawCmdHeader::TexRef.
Referenced by ImFontAtlasBuildSetTexture().
ImFontAtlasUpdateNewFrame()
void ImFontAtlasUpdateNewFrame (ImFontAtlas * atlas, int frame_count, bool renderer_has_textures)
Definition at line 2746 of file imgui_draw.cpp.
References ImTextureData::BackendUserData, ImFontAtlasBuilder::BakedDiscardedCount, ImFontBaked::BakedId, ImFontAtlasBuilder::BakedMap, ImFontAtlasBuilder::BakedPool, ImVector< T >::begin(), ImFontAtlas::Builder, ImTextureData::DestroyPixels(), ImVector< T >::erase(), ImFontAtlas::Fonts, ImFontAtlasBuilder::FrameCount, ImTextureRect::h, IM_ASSERT, IM_ASSERT_USER_ERROR, IM_DELETE(), ImFontAtlasBuildMain(), ImTextureID_Invalid, ImTextureStatus_Destroyed, ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImFontAtlasBuilder::PreloadedAllGlyphsRanges, ImFontAtlas::RendererHasTextures, ImVector< T >::resize(), ImGuiStorage::SetVoidPtr(), ImVector< T >::Size, ImStableVector< T, BLOCKSIZE >::Size, ImTextureData::Status, ImFontAtlas::TexData, ImTextureData::TexID, ImFontAtlas::TexIsBuilt, ImFontAtlas::TexList, ImTextureData::UnusedFrames, ImTextureData::UpdateRect, ImTextureData::Updates, ImTextureRect::w, ImFontBaked::WantDestroy, ImTextureData::WantDestroyNextFrame, ImTextureRect::x, and ImTextureRect::y.
Referenced by ImGui::UpdateTexturesNewFrame().
ImFontCalcTextSizeEx()
ImVec2 ImFontCalcTextSizeEx (ImFont * font, float size, float max_width, float wrap_width, const char * text_begin, const char * text_end_display, const char * text_end, const char ** out_remaining, ImVec2 * out_offset, ImDrawTextFlags flags)
Definition at line 5485 of file imgui_draw.cpp.
References BuildLoadGlyphGetAdvanceOrFallback(), ImVector< T >::Data, ImFont::GetFontBaked(), ImDrawTextFlags_StopOnNewLine, ImFontCalcWordWrapPositionEx(), ImMax(), ImStrlen, ImTextCalcWordWrapNextLineStart(), ImTextCharFromUtf8(), ImFontBaked::IndexAdvanceX, ImVector< T >::Size, ImFontBaked::Size, ImVec2::x, and ImVec2::y.
Referenced by ImFont::CalcTextSizeA(), and InputTextCalcTextSize().
ImFontCalcWordWrapPositionEx()
const char * ImFontCalcWordWrapPositionEx (ImFont * font, float size, const char * text, const char * text_end, float wrap_width, ImDrawTextFlags flags = 0)
Definition at line 5377 of file imgui_draw.cpp.
References BuildLoadGlyphGetAdvanceOrFallback(), ImVector< T >::Data, ImFont::GetFontBaked(), IM_ASSERT, ImCharIsBlankW(), ImDrawTextFlags_WrapKeepBlanks, ImTextCharFromUtf8(), ImTextCountUtf8BytesFromChar(), ImFontBaked::IndexAdvanceX, ImVector< T >::Size, and ImFontBaked::Size.
Referenced by ImFont::CalcWordWrapPosition(), ImFontCalcTextSizeEx(), InputTextLineIndexBuild(), ImFont::RenderText(), ImStb::STB_TEXTEDIT_MOVELINEEND_IMPL(), and ImStb::STB_TEXTEDIT_MOVELINESTART_IMPL().
ImFormatString()
int ImFormatString (char * buf, size_t buf_size, const char * fmt, ...)
Definition at line 2223 of file imgui.cpp.
Referenced by ImFontAtlas::AddFontDefault(), ImFontAtlas::AddFontFromFileTTF(), ImGui::BeginComboPopup(), ImGui::BeginPopupEx(), ImGui::BeginPopupMenuEx(), ImGui::BeginTooltipEx(), ImGui::ColorEdit4(), ImGui::ColorEditOptionsPopup(), ImGui::DataTypeFormatString(), DebugItemPathQuery_FormatLevelInfo(), ImGui::DebugNodeDrawList(), ImGui::DebugNodeTabBar(), ImGui::DebugNodeTable(), ImGui::DebugNodeWindowsListByBeginStackParent(), ImPlot::FormatDate(), ImPlot::Formatter_Default(), ImPlot::Formatter_Logit(), FormatTextureRefForDebugDisplay(), ImPlot::FormatTime(), ImGui::GetKeyChordName(), ImGui::NavScoreItem(), ImGui::ProgressBar(), ImPlot::RenderHeatmap(), ImPlot::ShowDatePicker(), ImGui::ShowMetricsWindow(), ImPlot::ShowMetricsWindow(), ImPlot::ShowPlotContextMenu(), ImGui::TableHeader(), ImGui::TableMergeDrawChannels(), and ImGui::Value().
ImFormatStringToTempBuffer()
void ImFormatStringToTempBuffer (const char ** out_buf, const char ** out_buf_end, const char * fmt, ...)
Definition at line 2257 of file imgui.cpp.
References ImFormatStringToTempBufferV().
Referenced by ImGui::BeginChildEx(), ImGui::DebugHookIdInfo(), and ImGui::ShowFontAtlas().
ImFormatStringToTempBufferV()
void ImFormatStringToTempBufferV (const char ** out_buf, const char ** out_buf_end, const char * fmt, va_list args)
Definition at line 2269 of file imgui.cpp.
References ImVector< T >::Data, GImGui, ImFormatStringV(), ImMin(), ImStrlen, ImVector< T >::Size, and ImGuiContext::TempBuffer.
Referenced by ImGui::BulletTextV(), ImFormatStringToTempBuffer(), ImGui::LabelTextV(), ImGui::TextAlignedV(), ImGui::TextV(), ImGui::TreeNodeExV(), and ImGui::TreeNodeExV().
ImFormatStringV()
int ImFormatStringV (char * buf, size_t buf_size, const char * fmt, va_list args)
Definition at line 2241 of file imgui.cpp.
Referenced by ImGuiTextBuffer::appendfv(), and ImFormatStringToTempBufferV().
ImHashData()
ImGuiID ImHashData (const void * data, size_t data_size, ImGuiID seed = 0)
Definition at line 2349 of file imgui.cpp.
Referenced by ImGuiWindow::GetID(), ImGuiWindow::GetID(), ImGuiWindow::GetIDFromPos(), ImGuiWindow::GetIDFromRectangle(), ImGui::GetIDWithSeed(), ImGui::GetWindowResizeBorderID(), and ImGui::GetWindowResizeCornerID().
ImHashSkipUncontributingPrefix()
const char * ImHashSkipUncontributingPrefix (const char * label)
Definition at line 2417 of file imgui.cpp.
Referenced by ImGui::CreateNewWindowSettings(), and DebugItemPathQuery_FormatLevelInfo().
ImHashStr()
ImGuiID ImHashStr (const char * data, size_t data_size = 0, ImGuiID seed = 0)
Definition at line 2377 of file imgui.cpp.
References GCrc32LookupTable.
Referenced by ImPlotColormapData::Append(), ImGui::BeginChildEx(), ImGui::BeginCombo(), ImGui::BeginDragDropSource(), ImGui::ClearWindowSettings(), ImGui::CreateNewWindowSettings(), ImGui::FindSettingsHandler(), ImGui::FindWindowByName(), ImGuiWindow::GetID(), ImGui::GetIDWithSeed(), ImPlotColormapData::GetIndex(), ImGui::GetWindowResizeBorderID(), ImGui::GetWindowResizeCornerID(), ImGuiWindow::ImGuiWindow(), ImGui::Initialize(), ImGui::NavUpdateWindowing(), ImGui::NewFrame(), ImGui::TabBarCalcTabID(), ImGui::TableBeginContextMenuPopup(), ImGui::TableOpenContextMenu(), ImGui::TableSettingsAddSettingsHandler(), and WindowSettingsHandler_ReadOpen().
ImInvLength()
float ImInvLength (const ImVec2 & lhs, float fail_value) inline
Definition at line 514 of file imgui_internal.h.
References ImRsqrt(), ImVec2::x, and ImVec2::y.
ImIsFloatAboveGuaranteedIntegerPrecision()
bool ImIsFloatAboveGuaranteedIntegerPrecision (float f) inline
Definition at line 527 of file imgui_internal.h.
Referenced by ImGuiListClipper_StepInternal().
ImIsPowerOfTwo() [1/2]
bool ImIsPowerOfTwo (ImU64 v) inline
Definition at line 381 of file imgui_internal.h.
ImIsPowerOfTwo() [2/2]
bool ImIsPowerOfTwo (int v) inline
Definition at line 380 of file imgui_internal.h.
Referenced by ImGui::BeginComboPopup(), ImGui::ColorEdit4(), ImGui::ColorPicker4(), ImFontAtlasTextureGetSizeEstimate(), ImFontAtlasTextureGrow(), ImGui::LogBegin(), ImGui::ScrollToRectEx(), ImGui::SeparatorEx(), ImGui::SetColorEditOptions(), ImPlot::SetNextAxisLimits(), ImGui::SetNextWindowCollapsed(), ImGui::SetNextWindowPos(), ImGui::SetNextWindowSize(), ImGui::SetShortcutRouting(), ImGui::SetWindowPos(), ImGui::SetWindowSize(), and TableSetupColumnFlags().
ImLengthSqr() [1/2]
float ImLengthSqr (const ImVec2 & lhs) inline
Definition at line 512 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::Begin(), ImGui::ColorPicker4(), ImPlot::EndPlot(), ImBezierCubicClosestPoint(), ImBezierCubicClosestPointCasteljauStep(), ImTriangleClosestPoint(), ImGui::ShadeVertsLinearColorGradientKeepAlpha(), ImPlot::UpdateInput(), ImGui::UpdateMouseInputs(), and ImGui::UpdateMouseWheel().
ImLengthSqr() [2/2]
float ImLengthSqr (const ImVec4 & lhs) inline
Definition at line 513 of file imgui_internal.h.
References ImVec4::w, ImVec4::x, ImVec4::y, and ImVec4::z.
ImLerp() [1/4]
ImVec2 ImLerp (const ImVec2 & a, const ImVec2 & b, const ImVec2 & t) inline
Definition at line 509 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
ImLerp() [2/4]
ImVec2 ImLerp (const ImVec2 & a, const ImVec2 & b, float t) inline
Definition at line 508 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
ImLerp() [3/4]
ImVec4 ImLerp (const ImVec4 & a, const ImVec4 & b, float t) inline
Definition at line 510 of file imgui_internal.h.
References ImVec4::w, ImVec4::x, ImVec4::y, and ImVec4::z.
ImLerp() [4/4]
template<typename T > T ImLerp (T a, T b, float t)
Definition at line 500 of file imgui_internal.h.
Referenced by ImGui::BeginErrorTooltip(), CalcResizePosSizeFromAnyCorner(), CalcScrollEdgeSnap(), ImGui::ColorPicker4(), ImGui::GetColumnOffset(), ImAlphaBlendColors(), ImGui::NavScoreItem(), ImGui::PlotEx(), ImGui::ProgressBar(), ImGui::RenderWindowDecorations(), RenderWindowOuterSingleBorder(), ImGui::ScrollbarEx(), ImGui::SetScrollHereX(), ImGui::SetScrollHereY(), ShowDebugLogFlag(), ImGui::StyleColorsClassic(), ImGui::StyleColorsDark(), ImGui::StyleColorsLight(), ImGui::TabItemEx(), and ImGui::UpdateWindowManualResize().
ImLinearRemapClamp()
float ImLinearRemapClamp (float s0, float s1, float d0, float d1, float x) inline
Definition at line 525 of file imgui_internal.h.
References ImSaturate().
Referenced by BoxSelectScrollWithMouseDrag().
ImLinearSweep()
float ImLinearSweep (float current, float target, float speed) inline
Definition at line 524 of file imgui_internal.h.
References ImMax(), and ImMin().
Referenced by ImGui::TabBarLayout().
ImLineClosestPoint()
ImVec2 ImLineClosestPoint (const ImVec2 & a, const ImVec2 & b, const ImVec2 & p)
Definition at line 2022 of file imgui.cpp.
References ImVec2::x, and ImVec2::y.
Referenced by ImBezierCubicClosestPoint(), ImBezierCubicClosestPointCasteljauStep(), and ImTriangleClosestPoint().
ImLog() [1/2]
double ImLog (double x) inline
Definition at line 482 of file imgui_internal.h.
ImLog() [2/2]
float ImLog (float x) inline
Definition at line 481 of file imgui_internal.h.
ImLowerBound()
ImGuiStoragePair * ImLowerBound (ImGuiStoragePair * in_begin, ImGuiStoragePair * in_end, ImGuiID key)
Definition at line 2815 of file imgui.cpp.
References ImGuiStoragePair::key.
Referenced by ImGuiStorage::GetFloat(), ImGuiStorage::GetFloatRef(), ImGuiStorage::GetInt(), ImGuiStorage::GetIntRef(), ImGuiStorage::GetVoidPtr(), ImGuiStorage::GetVoidPtrRef(), ImGuiStorage::SetFloat(), ImGuiStorage::SetInt(), and ImGuiStorage::SetVoidPtr().
ImMax() [1/2]
ImVec2 ImMax (const ImVec2 & lhs, const ImVec2 & rhs) inline
Definition at line 506 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
ImMax() [2/2]
template<typename T > T ImMax (T lhs, T rhs)
Definition at line 498 of file imgui_internal.h.
Referenced by ImDrawList::AddEllipse(), ImDrawList::AddEllipseFilled(), ImDrawList::AddPolyline(), ImDrawList::AddText(), ImGui::AlignTextToFramePadding(), ImGuiTextIndex::append(), ImGui::ArrowButtonEx(), ImGui::Begin(), ImGui::BeginBoxSelect(), ImGui::BeginColumns(), ImGui::BeginCombo(), ImGui::BeginComboPopup(), ImGui::BeginListBox(), ImGui::BeginMainMenuBar(), ImGui::BeginMenuBar(), ImGui::BeginMenuEx(), ImGui::BeginTableEx(), ImGui::Bullet(), ImGui::ButtonBehavior(), ImGui::CalcClipRectVisibleItemsY(), ImGui::CalcItemSize(), ImGui::CalcItemWidth(), ImPlot::CalcLogarithmicExponents(), CalcNextScrollFromScrollTargetAndClamp(), CalcResizePosSizeFromAnyCorner(), CalcScopeRect(), CalcWindowContentSizes(), CalcWindowMinSize(), CalcWindowSizeAfterConstraint(), ImGuiViewportP::CalcWorkRectSize(), ImGui::CalcWrapWidthForPos(), ImGui::Checkbox(), ImRect::ClipWith(), ImGui::CollapsingHeader(), ImGui::ColorEdit4(), ImPlot::ColormapScale(), ImGui::ColorPicker4(), ImGui::ColorPickerOptionsPopup(), ImGui::DebugNodeTexture(), ImGuiMenuColumns::DeclColumns(), ImGui::DragFloatRange2(), ImGui::DragIntRange2(), ImPlot::DragLineX(), ImPlot::DragLineY(), ImPlot::DragPoint(), ImPlot::DragRect(), ImGui::EndColumns(), ImGui::EndComboPreview(), ImGui::EndGroup(), ImGui::EndMenuBar(), ImGui::EndMultiSelect(), ImPlot::EndPlot(), ImGui::EndTabBar(), ImGui::EndTable(), ImGui::FindBestWindowPosForPopupEx(), ImGui::FindHoveredWindowEx(), GetDraggedColumnOffset(), ImPlot::GetPlotSelection(), ImGui::GetWindowScrollbarRect(), ImGui::Image(), ImFontAtlasBuildSetupFontBakedEllipsis(), ImFontAtlasPackAddRect(), ImFontAtlasTextureBlockQueueUpload(), ImFontAtlasTextureGetSizeEstimate(), ImFontAtlasTextureGrow(), ImFontCalcTextSizeEx(), ImGuiListClipper_SeekCursorAndSetupPrevLine(), ImGuiListClipper_SortAndFuseRanges(), ImGuiListClipper_StepInternal(), ImLinearSweep(), ImGui::InputScalar(), ImGui::InputTextEx(), ImGuiInputTextCallbackData::InsertChars(), ImGui::ItemSize(), ImGui::LabelTextV(), ImPlot::Locator_Default(), ImPlot::Locator_SymLog(), ImGui::MenuItemEx(), ImGui::MultiSelectItemFooter(), ImGui::NavUpdate(), ImGui::NavUpdatePageUpPageDown(), ImGui::NavUpdateWindowing(), ImGui::NewFrame(), ImGui::NextColumn(), ImPlot::PadAndDatumAxesX(), ImDrawList::PathArcTo(), ImDrawList::PathEllipticalArcTo(), ImGui::PlotEx(), ImDrawList::PushClipRect(), ImGui::PushMultiItemsWidths(), ImGui::RadioButton(), ImPlot::RendererLineStrip< _Getter >::Render(), ImPlot::RendererLineStripSkip< _Getter >::Render(), ImPlot::RendererLineSegments1< _Getter >::Render(), ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Render(), ImPlot::RendererBarsFillV< _Getter1, _Getter2 >::Render(), ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::Render(), ImPlot::RendererBarsLineV< _Getter1, _Getter2 >::Render(), ImPlot::RendererBarsLineH< _Getter1, _Getter2 >::Render(), ImPlot::RendererStairsPre< _Getter >::Render(), ImPlot::RendererStairsPost< _Getter >::Render(), ImPlot::RendererStairsPreShaded< _Getter >::Render(), ImPlot::RendererStairsPostShaded< _Getter >::Render(), ImPlot::RendererShaded< _Getter1, _Getter2 >::Render(), ImPlot::RendererRectC< _Getter >::Render(), ImGui::RenderCheckMark(), ImGui::RenderRectFilledInRangeH(), ImGui::RenderTextClippedEx(), ImGui::RenderTextEllipsis(), ImGui::RenderWindowOuterBorders(), ImGui::RenderWindowTitleBarContents(), ImGui::ScrollbarEx(), ImGui::Selectable(), ImGui::SeparatorTextEx(), ImGui::SetColumnOffset(), ImPlotAxis::SetRange(), ImGui::SetScrollHereX(), ImGui::SetScrollHereY(), ImPlot::SetupFinish(), ImGui::ShadeVertsLinearUV(), ImGui::ShrinkWidths(), ImGui::SplitterBehavior(), ImStb::STB_TEXTEDIT_INSERTCHARS(), ImGui::TabBarLayout(), ImGui::TabBarScrollClamp(), ImGui::TabBarScrollingButtons(), ImGui::TabBarScrollToTab(), ImGui::TabItemBackground(), ImGui::TabItemEx(), ImGui::TabItemLabelAndCloseButton(), ImGui::TableAngledHeadersRowEx(), ImGui::TableDrawBorders(), ImGui::TableEndCell(), ImGui::TableEndRow(), ImGui::TableGetCellBgRect(), ImGui::TableGetColumnWidthAuto(), ImGui::TableGetHeaderAngledMaxLabelWidth(), ImGui::TableGetHeaderRowHeight(), ImGui::TableHeader(), ImGui::TableMergeDrawChannels(), ImGui::TableNextRow(), ImGui::TableSetColumnSortDirection(), ImGui::TableSetColumnWidth(), ImGui::TableUpdateBorders(), ImGui::TableUpdateLayout(), ImGui::TextAlignedV(), ImGui::TextEx(), ImGui::TreeNodeBehavior(), ImGui::TreeNodeDrawLineToChildNode(), ImGui::TreeNodeDrawLineToTreePop(), ImGui::UpdateHoveredWindowAndCaptureFlags(), ImPlot::UpdateInput(), ImGui::UpdateMouseInputs(), and ImGui::UpdateWindowManualResize().
ImMemdup()
void * ImMemdup (const void * src, size_t size)
Definition at line 2105 of file imgui.cpp.
References IM_ALLOC.
Referenced by ImFontAtlas::AddFont().
ImMin() [1/2]
ImVec2 ImMin (const ImVec2 & lhs, const ImVec2 & rhs) inline
Definition at line 505 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
ImMin() [2/2]
template<typename T > T ImMin (T lhs, T rhs)
Definition at line 497 of file imgui_internal.h.
Referenced by ImDrawList::AddText(), ImGui::BeginBoxSelect(), ImGui::BeginColumns(), ImGui::BeginMenuEx(), ImGui::BeginTableEx(), ImGui::Bullet(), ImPlot::CalcLogarithmicExponents(), CalcNextScrollFromScrollTargetAndClamp(), CalcScopeRect(), CalcWindowAutoFitSize(), ImRect::ClipWith(), ImGui::ColorButton(), ImPlot::ColormapScale(), ImGuiInputTextState::CursorClamp(), ImGui::DebugNodeTabBar(), ImGui::DebugTextureIDToU64(), ImGui::DragFloatRange2(), ImGui::DragIntRange2(), ImPlot::DragRect(), ImGui::EndColumns(), ImPlot::EndPlot(), ImPlot::EndSubplots(), ImGui::EndTable(), ImGui::FindBestWindowPosForPopupEx(), ImPlot::FitterBarV< _Getter1, _Getter2 >::Fit(), ImPlot::FitterBarH< _Getter1, _Getter2 >::Fit(), GetDraggedColumnOffset(), ImPlot::GetPlotSelection(), ImGui::ImageButtonEx(), ImFontAtlasTextureBlockPostProcessMultiply(), ImFontAtlasTextureBlockQueueUpload(), ImFormatStringToTempBufferV(), ImGuiListClipper_SortAndFuseRanges(), ImGuiListClipper_StepInternal(), ImLinearSweep(), ImParseFormatTrimDecorations(), ImTextCharFromUtf8(), ImTriangleClosestPoint(), ImGui::InputTextEx(), InputTextReconcileUndoState(), ImGui::ListBox(), LockWheelingWindow(), NavBiasScoringRect(), ImGui::NavCalcPreferredRefPos(), ImGui::NavUpdateCreateMoveRequest(), ImGui::NavUpdateWindowing(), ImGui::NewFrame(), ImDrawList::PathRect(), ImGui::PlotEx(), ImPlot::RendererLineStrip< _Getter >::Render(), ImPlot::RendererLineStripSkip< _Getter >::Render(), ImPlot::RendererLineSegments1< _Getter >::Render(), ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Render(), ImPlot::RendererBarsFillV< _Getter1, _Getter2 >::Render(), ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::Render(), ImPlot::RendererBarsLineV< _Getter1, _Getter2 >::Render(), ImPlot::RendererBarsLineH< _Getter1, _Getter2 >::Render(), ImPlot::RendererStairsPre< _Getter >::Render(), ImPlot::RendererStairsPost< _Getter >::Render(), ImPlot::RendererStairsPreShaded< _Getter >::Render(), ImPlot::RendererStairsPostShaded< _Getter >::Render(), ImPlot::RendererShaded< _Getter1, _Getter2 >::Render(), ImPlot::RendererRectC< _Getter >::Render(), ImGui::RenderColorComponentMarker(), ImGui::RenderColorRectWithAlphaCheckerboard(), ImPlot::RenderPrimitivesEx(), ImGui::RenderRectFilledInRangeH(), ImGui::RenderWindowTitleBarContents(), ImGui::ScrollbarEx(), ImGui::ScrollToRectEx(), ImGui::Selectable(), ImGui::SetColumnOffset(), ImPlotAxis::SetRange(), ImPlot::SetupFinish(), ImGui::ShadeVertsLinearUV(), ImGui::ShrinkWidths(), ImGui::TabBarLayout(), ImGui::TabBarScrollClamp(), ImGui::TabItemBackground(), ImGui::TabItemCalcSize(), ImGui::TableAngledHeadersRowEx(), ImGui::TableDrawBorders(), ImGui::TableEndRow(), ImGui::TableGetCellBgRect(), ImGui::TableHeader(), ImGui::TableMergeDrawChannels(), ImGui::TableSetupScrollFreeze(), ImGui::TableUpdateLayout(), ImGui::TextAlignedV(), ImGui::TreeNodeBehavior(), ImGui::TreeNodeDrawLineToChildNode(), ImGui::TreeNodeDrawLineToTreePop(), ImPlot::UpdateInput(), ImGui::UpdateMouseWheel(), and ImGui::UpdateWindowManualResize().
ImModPositive()
int ImModPositive (int a, int b) inline
Definition at line 521 of file imgui_internal.h.
ImMul()
ImVec2 ImMul (const ImVec2 & lhs, const ImVec2 & rhs) inline
Definition at line 526 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::ShadeVertsLinearUV().
ImParseFormatFindEnd()
const char * ImParseFormatFindEnd (const char * format)
Definition at line 3582 of file imgui_widgets.cpp.
Referenced by ImParseFormatSanitizeForPrinting(), ImParseFormatSanitizeForScanning(), and ImParseFormatTrimDecorations().
ImParseFormatFindStart()
const char * ImParseFormatFindStart (const char * format)
Definition at line 3569 of file imgui_widgets.cpp.
Referenced by ImParseFormatPrecision(), and ImParseFormatTrimDecorations().
ImParseFormatPrecision()
int ImParseFormatPrecision (const char * format, int default_value)
Definition at line 3669 of file imgui_widgets.cpp.
References ImParseFormatFindStart().
ImParseFormatSanitizeForPrinting()
void ImParseFormatSanitizeForPrinting (const char * fmt_in, char * fmt_out, size_t fmt_out_size)
Definition at line 3619 of file imgui_widgets.cpp.
References IM_ASSERT, IM_UNUSED, and ImParseFormatFindEnd().
ImParseFormatSanitizeForScanning()
const char * ImParseFormatSanitizeForScanning (const char * fmt_in, char * fmt_out, size_t fmt_out_size)
Definition at line 3634 of file imgui_widgets.cpp.
References IM_ASSERT, IM_UNUSED, and ImParseFormatFindEnd().
Referenced by ImGui::DataTypeApplyFromText().
ImParseFormatTrimDecorations()
const char * ImParseFormatTrimDecorations (const char * format, char * buf, size_t buf_size)
Definition at line 3604 of file imgui_widgets.cpp.
References ImMin(), ImParseFormatFindEnd(), ImParseFormatFindStart(), and ImStrncpy().
Referenced by ImGui::TempInputScalar().
ImPow() [1/2]
double ImPow (double x, double y) inline
Definition at line 480 of file imgui_internal.h.
ImPow() [2/2]
float ImPow (float x, float y) inline
Definition at line 479 of file imgui_internal.h.
Referenced by ImPlot::AddTicksLogarithmic(), GetMinimumStepAtDecimalPrecision(), ImPlot::NiceNum(), ImPlot::TransformInverse_Log10(), and ImPlot::TransformInverse_Logit().
ImQsort()
void ImQsort (void * base, size_t count, size_t size_of_element, int(*)(void const *, void const *) compare_func) inline
Definition at line 373 of file imgui_internal.h.
Referenced by AddWindowToSortBuffer(), ImGui::BeginTabBarEx(), ImGuiStorage::BuildSortByKey(), ImGuiSelectionBasicStorage::GetNextSelectedItem(), ImGui::ShowMetricsWindow(), ImGui::ShrinkWidths(), ImGui::TabBarLayout(), and ImGui::TableFixDisplayOrder().
ImRotate()
ImVec2 ImRotate (const ImVec2 & v, float cos_a, float sin_a) inline
Definition at line 523 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::ColorPicker4(), ImGui::ShadeVertsTransformPos(), and ImGui::TableAngledHeadersRowEx().
ImRound64()
float ImRound64 (float f) inline
Definition at line 520 of file imgui_internal.h.
Referenced by CalcNextScrollFromScrollTargetAndClamp().
ImRsqrt() [1/2]
double ImRsqrt (double x) inline
Definition at line 493 of file imgui_internal.h.
ImRsqrt() [2/2]
float ImRsqrt (float x) inline
Definition at line 491 of file imgui_internal.h.
Referenced by ImInvLength().
ImSaturate()
float ImSaturate (float f) inline
Definition at line 511 of file imgui_internal.h.
Referenced by ImGui::ColorPicker4(), ImLinearRemapClamp(), ImGui::NavUpdateWindowing(), ImGui::PlotEx(), ImGui::ProgressBar(), ImGui::RenderWindowTitleBarContents(), ImGui::ScrollbarEx(), ImGui::TabItemEx(), and ImGui::TextLink().
ImSign() [1/2]
double ImSign (double x) inline
Definition at line 487 of file imgui_internal.h.
ImSign() [2/2]
float ImSign (float x) inline
Definition at line 486 of file imgui_internal.h.
Referenced by ImPlot::AddTicksLogarithmic(), and BoxSelectScrollWithMouseDrag().
ImStrbol()
const char * ImStrbol (const char * buf_mid_line, const char * buf_begin)
Definition at line 2146 of file imgui.cpp.
References IM_ASSERT_PARANOID, and ImStrlen.
Referenced by ImStb::STB_TEXTEDIT_MOVELINEEND_IMPL(), and ImStb::STB_TEXTEDIT_MOVELINESTART_IMPL().
ImStrchrRange()
const char * ImStrchrRange (const char * str_begin, const char * str_end, char c)
Definition at line 2125 of file imgui.cpp.
References ImMemchr.
Referenced by ImGui::LoadIniSettingsFromMemory().
ImStrdup()
char * ImStrdup (const char * str)
Definition at line 2098 of file imgui.cpp.
References IM_ALLOC, and ImStrlen.
Referenced by ImGuiWindow::ImGuiWindow().
ImStrdupcpy()
char * ImStrdupcpy (char * dst, size_t * p_dst_size, const char * str)
Definition at line 2111 of file imgui.cpp.
References IM_ALLOC, IM_FREE, and ImStrlen.
Referenced by ImGui::Begin().
ImStreolRange()
const char * ImStreolRange (const char * str, const char * str_end)
Definition at line 2140 of file imgui.cpp.
References ImMemchr.
Referenced by ImGui::LogRenderedText().
ImStricmp()
int ImStricmp (const char * str1, const char * str2)
Definition at line 2075 of file imgui.cpp.
References ImToUpper().
ImStristr()
const char * ImStristr (const char * haystack, const char * haystack_end, const char * needle, const char * needle_end)
Definition at line 2154 of file imgui.cpp.
References ImStrlen, and ImToUpper().
Referenced by ImGuiTextFilter::PassFilter().
ImStrlenW()
int ImStrlenW (const ImWchar * str)
Definition at line 2131 of file imgui.cpp.
ImStrncpy()
void ImStrncpy (char * dst, const char * src, size_t count)
Definition at line 2089 of file imgui.cpp.
Referenced by ImGuiTextFilter::ImGuiTextFilter(), ImParseFormatTrimDecorations(), ImGui::InputTextEx(), ImGui::SetContextName(), ImGui::SetDragDropPayload(), and ImPlot::SetupAxisFormat().
ImStrnicmp()
int ImStrnicmp (const char * str1, const char * str2, size_t count)
Definition at line 2082 of file imgui.cpp.
References ImToUpper().
ImStrSkipBlank()
const char * ImStrSkipBlank (const char * str)
Definition at line 2192 of file imgui.cpp.
Referenced by TableSettingsHandler_ReadLine().
ImStrTrimBlanks()
void ImStrTrimBlanks (char * str)
Definition at line 2177 of file imgui.cpp.
Referenced by ImGui::TempInputScalar().
ImSubClampOverflow()
template<typename T > T ImSubClampOverflow (T a, T b, T mn, T mx)
Definition at line 503 of file imgui_internal.h.
Referenced by ImGui::DataTypeApplyOp().
ImSwap()
template<typename T > void ImSwap (T & a, T & b)
Definition at line 501 of file imgui_internal.h.
Referenced by ImGui::ColorConvertRGBtoHSV(), ImGuiListClipper_SortAndFuseRanges(), ImGui::InputTextEx(), ImGuiSelectionBasicStorage::Swap(), ImGui::TableSetupScrollFreeze(), ImGui::TempInputScalar(), and ImGui::UpdateWindowManualResize().
ImTextCalcWordWrapNextLineStart()
const char * ImTextCalcWordWrapNextLineStart (const char * text, const char * text_end, ImDrawTextFlags flags = 0)
Definition at line 5364 of file imgui_draw.cpp.
References ImCharIsBlankA(), and ImDrawTextFlags_WrapKeepBlanks.
Referenced by ImFontCalcTextSizeEx(), and ImFont::RenderText().
ImTextCharFromUtf8()
int ImTextCharFromUtf8 (unsigned int * out_char, const char * in_text, const char * in_text_end)
Definition at line 2515 of file imgui.cpp.
References IM_UNICODE_CODEPOINT_INVALID, IM_UNICODE_CODEPOINT_MAX, and ImMin().
Referenced by ImGuiIO::AddInputCharactersUTF8(), ImFontGlyphRangesBuilder::AddText(), ImPlot::AddTextVertical(), DebugItemPathQuery_GetResultAsPath(), ImGui::DebugTextEncoding(), ImFontCalcTextSizeEx(), ImFontCalcWordWrapPositionEx(), ImStb::IMSTB_TEXTEDIT_GETNEXTCHARINDEX_IMPL(), ImTextCountCharsFromUtf8(), ImTextCountUtf8BytesFromChar(), ImTextFindValidUtf8CodepointEnd(), ImTextStrFromUtf8(), ImGui::InputTextEx(), ImStb::is_word_boundary_from_left(), ImStb::is_word_boundary_from_right(), ImFont::RenderText(), and ImStb::STB_TEXTEDIT_GETWIDTH().
ImTextCharToUtf8()
int ImTextCharToUtf8 (char out_buf[5], unsigned int c)
Definition at line 2632 of file imgui.cpp.
References ImTextCharToUtf8_inline().
Referenced by ImGui::DebugNodeFont(), DebugPrintInputEvent(), ImGui::GetTypingSelectRequest(), ImGui::InputTextEx(), and ImGuiInputTextState::OnCharPressed().
ImTextCountCharsFromUtf8()
int ImTextCountCharsFromUtf8 (const char * in_text, const char * in_text_end)
Definition at line 2584 of file imgui.cpp.
References ImTextCharFromUtf8().
ImTextCountLines()
int ImTextCountLines (const char * in_text, const char * in_text_end)
Definition at line 2708 of file imgui.cpp.
References ImMemchr, and ImStrlen.
Referenced by ImGui::TableAngledHeadersRowEx().
ImTextCountUtf8BytesFromChar()
int ImTextCountUtf8BytesFromChar (const char * in_text, const char * in_text_end)
Definition at line 2640 of file imgui.cpp.
References ImTextCharFromUtf8().
Referenced by ImGui::GetTypingSelectRequest(), ImFontCalcWordWrapPositionEx(), and ImTextCountUtf8BytesFromStr().
ImTextCountUtf8BytesFromStr()
int ImTextCountUtf8BytesFromStr (const ImWchar * in_text, const ImWchar * in_text_end)
Definition at line 2671 of file imgui.cpp.
References ImTextCountUtf8BytesFromChar().
Referenced by ImGui::GetTypingSelectRequest().
ImTextFindPreviousUtf8Codepoint()
const char * ImTextFindPreviousUtf8Codepoint (const char * in_text_start, const char * in_p)
Definition at line 2685 of file imgui.cpp.
Referenced by ImGui::GetTypingSelectRequest(), ImStb::IMSTB_TEXTEDIT_GETPREVCHARINDEX_IMPL(), ImTextFindValidUtf8CodepointEnd(), ImStb::is_word_boundary_from_left(), and ImStb::is_word_boundary_from_right().
ImTextFindValidUtf8CodepointEnd()
const char * ImTextFindValidUtf8CodepointEnd (const char * in_text_start, const char * in_text_end, const char * in_p)
Definition at line 2696 of file imgui.cpp.
References IM_UNICODE_CODEPOINT_INVALID, ImTextCharFromUtf8(), and ImTextFindPreviousUtf8Codepoint().
Referenced by ImGuiInputTextCallbackData::InsertChars(), and ImStb::STB_TEXTEDIT_INSERTCHARS().
ImTextStrFromUtf8()
int ImTextStrFromUtf8 (ImWchar * out_buf, int out_buf_size, const char * in_text, const char * in_text_end, const char ** in_remaining = NULL)
Definition at line 2568 of file imgui.cpp.
References ImTextCharFromUtf8().
ImTextStrToUtf8()
int ImTextStrToUtf8 (char * out_buf, int out_buf_size, const ImWchar * in_text, const ImWchar * in_text_end)
Definition at line 2655 of file imgui.cpp.
References ImTextCharToUtf8_inline().
ImTextureDataGetFormatBytesPerPixel()
int ImTextureDataGetFormatBytesPerPixel (ImTextureFormat format)
Definition at line 2434 of file imgui_draw.cpp.
References IM_ASSERT, ImTextureFormat_Alpha8, and ImTextureFormat_RGBA32.
Referenced by ImTextureData::Create(), and ImFontAtlasTextureBlockConvert().
ImTextureDataGetFormatName()
const char * ImTextureDataGetFormatName (ImTextureFormat format)
Definition at line 2458 of file imgui_draw.cpp.
References ImTextureFormat_Alpha8, and ImTextureFormat_RGBA32.
Referenced by ImGui::DebugNodeTexture().
ImTextureDataGetStatusName()
const char * ImTextureDataGetStatusName (ImTextureStatus status)
Definition at line 2445 of file imgui_draw.cpp.
References ImTextureStatus_Destroyed, ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, and ImTextureStatus_WantUpdates.
Referenced by ImGui::DebugNodeTexture().
ImToUpper()
char ImToUpper (char c) inline
Definition at line 402 of file imgui_internal.h.
Referenced by ImStricmp(), ImStrimatchlen(), ImStristr(), and ImStrnicmp().
ImTriangleArea()
float ImTriangleArea (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c) inline
Definition at line 540 of file imgui_internal.h.
References ImFabs, ImVec2::x, and ImVec2::y.
Referenced by ImGui::DebugNodeDrawList().
ImTriangleBarycentricCoords()
void ImTriangleBarycentricCoords (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c, const ImVec2 & p, float & out_u, float & out_v, float & out_w)
Definition at line 2043 of file imgui.cpp.
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::ColorPicker4().
ImTriangleClosestPoint()
ImVec2 ImTriangleClosestPoint (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c, const ImVec2 & p)
Definition at line 2054 of file imgui.cpp.
References ImLengthSqr(), ImLineClosestPoint(), and ImMin().
Referenced by ImGui::ColorPicker4().
ImTriangleContainsPoint()
bool ImTriangleContainsPoint (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c, const ImVec2 & p)
Definition at line 2035 of file imgui.cpp.
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::BeginMenuEx(), ImGui::ColorPicker4(), and ImTriangulator::IsEar().
ImTriangleIsClockwise()
bool ImTriangleIsClockwise (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c) inline
Definition at line 541 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
Referenced by ImTriangulator::BuildReflexes(), and ImTriangulator::ReclassifyNode().
ImTrunc() [1/2]
ImVec2 ImTrunc (const ImVec2 & v) inline
Definition at line 516 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
ImTrunc() [2/2]
float ImTrunc (float f) inline
Definition at line 515 of file imgui_internal.h.
Referenced by ApplyWindowSettings(), ImGui::Begin(), ImGui::BeginColumns(), ImGui::BeginListBox(), ImGui::BeginTableEx(), ImGui::CloseButton(), ImGui::DebugNodeDrawCmdShowMeshAndBoundingBox(), ImGui::DebugRenderViewportThumbnail(), ImGui::EndColumns(), ImGui::EndTable(), GetDraggedColumnOffset(), ImFontAtlasBakedAddFontGlyph(), ImGui::InputTextEx(), ImGui::ListBox(), ImGui::NavCalcPreferredRefPos(), ImGui::NavUpdate(), ImGui::NavUpdateWindowing(), ImGui::RenderTextEllipsis(), ImGuiStyle::ScaleAllSizes(), ScaleWindow(), ImGui::ScrollToRectEx(), ImGui::SeparatorTextEx(), ImGui::SetNextWindowContentSize(), ImGui::SetWindowPos(), ImGui::ShrinkWidths(), ImGui::TableAngledHeadersRowEx(), ImGui::TableHeader(), ImGui::TableUpdateBorders(), ImGui::TableUpdateLayout(), ImGui::TextAlignedV(), ImGui::TreeNodeDrawLineToChildNode(), ImGui::TreeNodeDrawLineToTreePop(), ImGui::UpdateMouseWheel(), and ImGui::UpdateWindowManualResize().
ImTrunc64()
float ImTrunc64 (float f) inline
Definition at line 519 of file imgui_internal.h.
Referenced by CalcWindowContentSizes().
ImUpperPowerOfTwo()
int ImUpperPowerOfTwo (int v) inline
Definition at line 382 of file imgui_internal.h.
Referenced by ImFontAtlasBuildInit(), ImFontAtlasTextureGetSizeEstimate(), and ImFontAtlasTextureGrow().
operator!=()
bool operator!= (const ImTextureRef & lhs, const ImTextureRef & rhs) inline
Definition at line 3792 of file imgui_internal.h.
References ImTextureRef::_TexData, and ImTextureRef::_TexID.
operator==()
bool operator== (const ImTextureRef & lhs, const ImTextureRef & rhs) inline
Definition at line 3791 of file imgui_internal.h.
References ImTextureRef::_TexData, and ImTextureRef::_TexID.
Variable Documentation
GImGui
ImGuiContext* GImGui extern
Definition at line 1390 of file imgui.cpp.
Referenced by ImGui::AcceptDragDropPayload(), ImGui::ActivateItemByID(), ImGui::AddSettingsHandler(), ImPlot::AddTextVertical(), AddWindowToDrawData(), ImGui::AlignTextToFramePadding(), ImGui::ArrowButtonEx(), ImGui::Begin(), ImPlot::BeginAlignedPlots(), ImGui::BeginBoxSelect(), ImGui::BeginChildEx(), ImGui::BeginColumns(), ImGui::BeginCombo(), ImGui::BeginComboPopup(), ImGui::BeginComboPreview(), ImGui::BeginDisabled(), ImGui::BeginDisabledOverrideReenable(), ImGui::BeginDragDropSource(), ImPlot::BeginDragDropSourceAxis(), ImPlot::BeginDragDropSourcePlot(), ImGui::BeginDragDropTarget(), ImGui::BeginDragDropTargetCustom(), ImGui::BeginDragDropTargetViewport(), ImGui::BeginErrorTooltip(), ImGui::BeginGroup(), ImPlot::BeginLegendPopup(), ImGui::BeginListBox(), ImGui::BeginMainMenuBar(), ImGui::BeginMenuEx(), ImGui::BeginMultiSelect(), ImPlot::BeginPlot(), ImGui::BeginPopup(), ImGui::BeginPopupContextItem(), ImGui::BeginPopupContextVoid(), ImGui::BeginPopupContextWindow(), ImGui::BeginPopupEx(), ImGui::BeginPopupMenuEx(), ImGui::BeginPopupModal(), ImPlot::BeginSubplots(), ImGui::BeginTabBar(), ImGui::BeginTabBarEx(), ImGui::BeginTabItem(), ImGui::BeginTableEx(), ImGui::BeginTooltipEx(), ImGui::BeginTooltipHidden(), BoxSelectActivateDrag(), BoxSelectDeactivateDrag(), BoxSelectPreStartDrag(), BoxSelectScrollWithMouseDrag(), ImGui::BringWindowToDisplayBack(), ImGui::BringWindowToDisplayBehind(), ImGui::BringWindowToDisplayFront(), ImGui::BringWindowToFocusFront(), ImGui::Bullet(), ImGui::BulletTextV(), ImGui::ButtonBehavior(), ImGui::ButtonEx(), CalcDelayFromHoveredFlags(), ImGui::CalcItemWidth(), CalcMaxPopupHeightFromItemCount(), CalcRoutingScore(), CalcScopeRect(), ImGui::CalcTextSize(), CalcWindowAutoFitSize(), CalcWindowMinSize(), CalcWindowSizeAfterConstraint(), ImGui::CalcWrapWidthForPos(), ImGui::Checkbox(), ImGui::CheckboxFlagsT(), ImGui::ClearDragDrop(), ImGui::ClearIniSettings(), ImGui::CloseButton(), ImGui::CloseCurrentPopup(), ImGui::ClosePopupsExceptModals(), ImGui::ClosePopupsOverWindow(), ImGui::ClosePopupToLevel(), ImGui::CollapseButton(), ImGui::CollapsingHeader(), ImGui::ColorButton(), ImGui::ColorEdit4(), ImGui::ColorEditOptionsPopup(), ColorEditRestoreH(), ColorEditRestoreHS(), ImPlot::ColormapButton(), ImPlot::ColormapScale(), ImPlot::ColormapSlider(), ImGui::ColorPicker4(), ImGui::ColorPickerOptionsPopup(), ImGui::ColorTooltip(), ImGui::Combo(), CreateNewWindow(), ImGui::CreateNewWindowSettings(), ImGui::DataTypeIsZero(), ImGui::DebugBreakButton(), ImGui::DebugBreakClearData(), ImGui::DebugDrawCursorPos(), ImGui::DebugDrawItemRect(), ImGui::DebugDrawLineExtents(), ImGui::DebugFlashStyleColor(), DebugFlashStyleColorStop(), ImGui::DebugHookIdInfo(), DebugItemPathQuery_FormatLevelInfo(), ImGui::DebugLocateItem(), ImGui::DebugLocateItemOnHover(), ImGui::DebugLocateItemResolveWithLastItem(), DebugLogMultiSelectRequests(), ImGui::DebugLogV(), ImGui::DebugNodeDrawList(), ImGui::DebugNodeFont(), ImGui::DebugNodeInputTextState(), ImGui::DebugNodeTable(), ImGui::DebugNodeTexture(), ImGui::DebugNodeViewport(), ImGui::DebugNodeWindow(), DebugPrintInputEvent(), ImGui::DebugRenderViewportThumbnail(), ImGui::DebugStartItemPicker(), ImGui::DebugTextUnformattedWithLocateItem(), ImGui::DragBehavior(), ImGui::DragFloatRange2(), ImGui::DragIntRange2(), ImGui::DragScalar(), ImGui::DragScalarN(), ImGui::End(), ImGui::EndBoxSelect(), ImGui::EndChild(), ImGui::EndColumns(), ImGui::EndCombo(), ImGui::EndComboPreview(), ImGui::EndDisabled(), ImGui::EndDisabledOverrideReenable(), ImGui::EndDragDropSource(), ImGui::EndDragDropTarget(), ImGui::EndFrame(), ImGui::EndGroup(), ImGui::EndListBox(), ImGui::EndMainMenuBar(), ImGui::EndMenu(), ImGui::EndMenuBar(), ImGui::EndMultiSelect(), ImPlot::EndPlot(), ImGui::EndPopup(), ImPlot::EndSubplots(), ImGui::EndTabBar(), ImGui::EndTabItem(), ImGui::EndTable(), ImGui::ErrorCheckEndFrameFinalizeErrorTooltip(), ImGui::ErrorCheckEndFrameSanityChecks(), ImGui::ErrorCheckNewFrameSanityChecks(), ImGui::ErrorCheckUsingSetCursorPosToExtendParentBoundaries(), ImGui::ErrorLog(), ImGui::ErrorRecoveryStoreState(), ImGui::ErrorRecoveryTryToRecoverState(), ImGui::ErrorRecoveryTryToRecoverWindowState(), FindBestWheelingWindow(), ImGui::FindBestWindowPosForPopup(), ImGui::FindBlockingModal(), ImGui::FindBottomMostVisibleWindowWithinBeginStack(), ImGui::FindHoveredWindowEx(), ImGui::FindSettingsHandler(), ImGui::FindWindowByID(), ImGui::FindWindowDisplayIndex(), ImGui::FindWindowFocusIndex(), FindWindowNavFocusable(), ImGui::FindWindowSettingsByID(), ImGui::FindWindowSettingsByWindow(), ImGui::FocusItem(), ImGui::FocusTopMostWindowUnderOne(), ImGui::FocusWindow(), ImGui::GcCompactTransientMiscBuffers(), ImGui::GetActiveID(), ImGui::GetBackgroundDrawList(), ImGui::GetBoxSelectState(), ImGui::GetClipboardText(), ImGui::GetColorU32(), ImGui::GetColorU32(), ImGui::GetColorU32(), ImGui::GetColumnWidth(), ImGui::GetContentRegionAvail(), ImGui::GetCurrentContext(), ImGui::GetCurrentFocusScope(), ImGui::GetCurrentTabBar(), ImGui::GetCurrentTable(), ImGui::GetCurrentWindow(), ImGui::GetCurrentWindowRead(), ImGui::GetDefaultFont(), ImGui::GetDragDropPayload(), GetDraggedColumnOffset(), ImGui::GetDrawData(), ImGui::GetDrawListSharedData(), ImGui::GetFocusID(), ImGui::GetFont(), ImGui::GetFontBaked(), ImGui::GetFontRasterizerDensity(), ImGui::GetFontSize(), ImGui::GetFontTexUvWhitePixel(), ImGui::GetForegroundDrawList(), ImGui::GetFrameCount(), ImGui::GetFrameHeight(), ImGui::GetFrameHeightWithSpacing(), ImGui::GetHoveredID(), ImGui::GetID(), ImGui::GetID(), ImGui::GetID(), ImGui::GetID(), ImGui::GetIDWithSeed(), ImGui::GetIDWithSeed(), ImGui::GetInputTextState(), ImGui::GetIO(), ImGui::GetItemFlags(), ImGui::GetItemID(), ImGui::GetItemRectMax(), ImGui::GetItemRectMin(), ImGui::GetItemRectSize(), ImGui::GetItemStatusFlags(), ImGui::GetKeyChordName(), ImGui::GetKeyData(), ImGui::GetKeyOwner(), ImGui::GetKeyPressedAmount(), ImGui::GetMainViewport(), ImGui::GetMouseClickedCount(), ImGui::GetMouseCursor(), ImGui::GetMouseDragDelta(), ImGui::GetMousePos(), ImGui::GetMousePosOnOpeningCurrentPopup(), ImGui::GetMultiSelectState(), ImGui::GetNavTweakPressedAmount(), ImGui::GetPlatformIO(), ImPlot::GetPlot(), ImGui::GetPopupAllowedExtentRect(), GetRoutingIdFromOwnerId(), ImGui::GetScrollMaxX(), ImGui::GetScrollMaxY(), ImGui::GetScrollX(), ImGui::GetScrollY(), ImGui::GetShortcutRoutingData(), GetSkipItemForListClipping(), ImGui::GetStateStorage(), ImGui::GetStyle(), ImGui::GetStyleColorVec4(), GetTabBarFromTabBarRef(), GetTabBarRefFromTabBar(), ImGui::GetTextLineHeight(), ImGui::GetTextLineHeightWithSpacing(), ImGui::GetTime(), ImGui::GetTopMostAndVisiblePopupModal(), ImGui::GetTopMostPopupModal(), ImGui::GetTreeNodeToLabelSpacing(), ImGui::GetTypematicRepeatRate(), ImGui::GetTypingSelectRequest(), GetViewportBgFgDrawList(), ImGui::GetWindowContentRegionMax(), ImGui::GetWindowContentRegionMin(), ImGui::GetWindowHeight(), ImGui::GetWindowPos(), ImGui::GetWindowScrollbarRect(), ImGui::GetWindowWidth(), ImGui::Image(), ImGui::ImageButton(), ImGui::ImageButtonEx(), ImGui::ImageWithBg(), ImFontAtlasDebugLogTextureRequests(), ImFormatStringToTempBufferV(), ImGuiListClipper_SeekCursorAndSetupPrevLine(), ImGui::Indent(), ImGui::Initialize(), ImGui::InputScalar(), ImGui::InputScalarN(), ImGui::InputTextDeactivateHook(), ImGui::InputTextEx(), InputTextFilterCharacter(), InputTextLineIndexBuild(), ImGui::InvisibleButton(), ImGui::IsActiveIdUsingNavDir(), ImGui::IsAnyItemActive(), ImGui::IsAnyItemFocused(), ImGui::IsAnyItemHovered(), ImGui::IsAnyMouseDown(), ImGui::IsClippedEx(), ImGui::IsDragDropActive(), ImGui::IsDragDropPayloadBeingAccepted(), ImGui::IsItemActivated(), ImGui::IsItemActive(), ImGui::IsItemActiveAsInputText(), ImGui::IsItemDeactivated(), ImGui::IsItemDeactivatedAfterEdit(), ImGui::IsItemEdited(), ImGui::IsItemFocused(), ImGui::IsItemHovered(), ImGui::IsItemToggledOpen(), ImGui::IsItemToggledSelection(), ImGui::IsItemVisible(), IsKeyChordPotentiallyCharInput(), ImGui::IsKeyChordPressed(), ImGui::IsKeyPressed(), ImGui::IsMouseClicked(), ImGui::IsMouseDoubleClicked(), ImGui::IsMouseDoubleClicked(), ImGui::IsMouseDown(), ImGui::IsMouseDown(), ImGui::IsMouseDragging(), ImGui::IsMouseDragPastThreshold(), ImGui::IsMouseHoveringRect(), ImGui::IsMousePosValid(), ImGui::IsMouseReleased(), ImGui::IsMouseReleased(), ImGui::IsMouseReleasedWithDelay(), ImGui::IsPopupOpen(), ImGui::IsPopupOpen(), ImGui::IsRectVisible(), ImGui::IsRectVisible(), IsRootOfOpenMenuSet(), ImGui::IsWindowAbove(), ImGui::IsWindowContentHoverable(), ImGui::IsWindowFocused(), ImGui::IsWindowHovered(), ImGui::IsWindowInBeginStack(), ImGui::ItemAdd(), ImGui::ItemHandleShortcut(), ImGui::ItemHoverable(), ImGui::ItemSize(), ImGui::KeepAliveID(), ImGui::LabelTextV(), ImGui::ListBox(), ImGui::LoadIniSettingsFromMemory(), ImGui::LocalizeGetMsg(), ImGui::LocalizeRegisterEntries(), LockWheelingWindow(), ImGui::LogBegin(), ImGui::LogButtons(), ImGui::LogFinish(), ImGui::LogRenderedText(), ImGui::LogSetNextTextDecoration(), ImGui::LogText(), ImGui::LogTextV(), ImGui::LogToBuffer(), ImGui::LogToClipboard(), ImGui::LogToFile(), ImGui::LogToTTY(), ImGui::MarkIniSettingsDirty(), ImGui::MarkIniSettingsDirty(), ImGui::MarkItemEdited(), ImGui::MemAlloc(), ImGui::MemFree(), ImGui::MenuItemEx(), ImGui::MultiSelectItemFooter(), ImGui::MultiSelectItemHeader(), ImGui::NavApplyItemToResult(), NavBiasScoringRect(), ImGui::NavCalcPreferredRefPos(), ImGui::NavCalcPreferredRefPosSource(), ImGui::NavClearPreferredPosForAxis(), ImGui::NavEndFrame(), ImGui::NavHighlightActivated(), ImGui::NavInitRequestApplyResult(), ImGui::NavInitWindow(), ImGui::NavMoveRequestApplyResult(), ImGui::NavMoveRequestButNoResultYet(), ImGui::NavMoveRequestCancel(), ImGui::NavMoveRequestForward(), ImGui::NavMoveRequestResolveWithLastItem(), ImGui::NavMoveRequestResolveWithPastTreeNode(), ImGui::NavMoveRequestSubmit(), ImGui::NavMoveRequestTryWrapping(), ImGui::NavProcessItem(), ImGui::NavProcessItemForTabbingRequest(), ImGui::NavRestoreLayer(), ImGui::NavScoreItem(), ImGui::NavUpdate(), ImGui::NavUpdateAnyRequestFlag(), ImGui::NavUpdateCancelRequest(), ImGui::NavUpdateCreateMoveRequest(), ImGui::NavUpdateCreateTabbingRequest(), ImGui::NavUpdateCreateWrappingRequest(), ImGui::NavUpdateCurrentWindowIsScrollPushableX(), ImGui::NavUpdatePageUpPageDown(), ImGui::NavUpdateWindowing(), ImGui::NavUpdateWindowingApplyFocus(), ImGui::NavUpdateWindowingOverlay(), NavUpdateWindowingTarget(), ImGui::NewFrame(), ImGui::NewLine(), ImGui::NextColumn(), ImGui::OpenPopup(), ImGui::OpenPopupEx(), ImGui::OpenPopupOnItemClick(), ImGui::PlotEx(), ImGui::PopFocusScope(), ImGui::PopFont(), ImGui::PopID(), ImGui::PopItemFlag(), ImGui::PopItemWidth(), ImGui::PopPasswordFont(), ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGui::PopTextWrapPos(), ImGui::ProgressBar(), ImGui::PushFocusScope(), ImGui::PushFont(), ImGui::PushID(), ImGui::PushID(), ImGui::PushID(), ImGui::PushID(), ImGui::PushItemFlag(), ImGui::PushItemWidth(), ImGui::PushMultiItemsWidths(), ImGui::PushOverrideID(), ImGui::PushPasswordFont(), ImGui::PushStyleColor(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), ImGui::PushStyleVar(), ImGui::PushStyleVarX(), ImGui::PushStyleVarY(), ImGui::PushTextWrapPos(), ImGui::RadioButton(), ImGui::RegisterFontAtlas(), ImGui::RegisterUserTexture(), ImGui::RemoveSettingsHandler(), ImGui::Render(), ImGui::RenderColorComponentMarker(), ImGui::RenderDimmedBackgrounds(), ImGui::RenderDragDropTargetRectEx(), ImGui::RenderDragDropTargetRectForItem(), ImGui::RenderFrame(), ImGui::RenderFrameBorder(), ImGui::RenderMouseCursor(), ImGui::RenderNavCursor(), ImGui::RenderText(), ImGui::RenderTextClipped(), ImGui::RenderTextEllipsis(), ImGui::RenderTextWrapped(), RenderViewportsThumbnails(), ImGui::RenderWindowDecorations(), ImGui::RenderWindowOuterBorders(), ImGui::RenderWindowTitleBarContents(), ImGui::ResetMouseDragDelta(), ImGui::SameLine(), SameLineOrWrap(), ImGui::SaveIniSettingsToDisk(), ImGui::SaveIniSettingsToMemory(), ImGui::ScaleWindowsInViewport(), ImGui::Scrollbar(), ImGui::ScrollbarEx(), ImGui::ScrollToItem(), ImGui::ScrollToRectEx(), ImGui::Selectable(), ImGui::Separator(), ImGui::SeparatorEx(), ImGui::SeparatorTextEx(), ImGui::SetActiveID(), ImGui::SetActiveIdUsingAllKeyboardKeys(), ImGui::SetClipboardText(), ImGui::SetColorEditOptions(), ImGui::SetColumnOffset(), ImGui::SetCurrentContext(), ImGui::SetCurrentFont(), SetCurrentWindow(), ImGui::SetDragDropPayload(), ImGui::SetFocusID(), ImGui::SetFontRasterizerDensity(), ImGui::SetHoveredID(), ImGui::SetItemDefaultFocus(), ImGui::SetItemKeyOwner(), ImGui::SetKeyboardFocusHere(), ImGui::SetKeyOwner(), ImGui::SetLastItemData(), ImGui::SetLastItemDataForChildWindowItem(), ImGui::SetLastItemDataForWindow(), ImGui::SetMouseCursor(), ImGui::SetNavCursorVisible(), ImGui::SetNavCursorVisibleAfterMove(), ImGui::SetNavFocusScope(), ImGui::SetNavID(), ImGui::SetNavWindow(), ImGui::SetNextFrameWantCaptureKeyboard(), ImGui::SetNextFrameWantCaptureMouse(), ImGui::SetNextItemAllowOverlap(), ImGui::SetNextItemColorMarker(), ImGui::SetNextItemOpen(), ImGui::SetNextItemRefVal(), ImGui::SetNextItemSelectionUserData(), ImGui::SetNextItemShortcut(), ImGui::SetNextItemStorageID(), ImGui::SetNextItemWidth(), ImGui::SetNextWindowBgAlpha(), ImGui::SetNextWindowCollapsed(), ImGui::SetNextWindowContentSize(), ImGui::SetNextWindowFocus(), ImGui::SetNextWindowPos(), ImGui::SetNextWindowRefreshPolicy(), ImGui::SetNextWindowScroll(), ImGui::SetNextWindowSize(), ImGui::SetNextWindowSizeConstraints(), ImGui::SetScrollFromPosX(), ImGui::SetScrollFromPosY(), ImGui::SetScrollHereX(), ImGui::SetScrollHereY(), ImGui::SetScrollX(), ImGui::SetScrollY(), ImGui::SetShortcutRouting(), ImGui::SetStateStorage(), ImGui::SetTabItemClosed(), SetupDrawListSharedData(), ImPlot::SetupFinish(), ImGui::SetWindowCollapsed(), ImGui::SetWindowFocus(), ImGui::SetWindowSize(), ImGui::Shortcut(), ImPlot::ShowAltLegend(), ShowDebugLogFlag(), ImGui::ShowDebugLogWindow(), ImGui::ShowFontAtlas(), ImGui::ShowIDStackToolWindow(), ImGui::ShowMetricsWindow(), ImGui::Shutdown(), ImGui::SliderScalar(), ImGui::SliderScalarN(), ImGui::SmallButton(), ImGui::SplitterBehavior(), ImGui::StartMouseMovingWindow(), ImGui::StopMouseMovingWindow(), ImGui::TabBarCalcMaxTabWidth(), ImGui::TabBarCalcTabID(), ImGui::TabBarFindByID(), ImGui::TabBarLayout(), ImGui::TabBarQueueReorderFromMousePos(), ImGui::TabBarRemove(), ImGui::TabBarScrollingButtons(), ImGui::TabBarScrollToTab(), ImGui::TabBarTabListPopupButton(), ImGui::TabItemBackground(), ImGui::TabItemButton(), ImGui::TabItemCalcSize(), ImGui::TabItemEx(), ImGui::TabItemLabelAndCloseButton(), ImGui::TabItemSpacing(), ImGui::TableAngledHeadersRow(), ImGui::TableAngledHeadersRowEx(), ImGui::TableBeginCell(), ImGui::TableDrawDefaultContextMenu(), ImGui::TableEndRow(), ImGui::TableFindByID(), ImGui::TableFixDisplayOrder(), ImGui::TableGcCompactSettings(), ImGui::TableGcCompactTransientBuffers(), ImGui::TableGetBoundSettings(), ImGui::TableGetColumnCount(), ImGui::TableGetColumnFlags(), ImGui::TableGetColumnIndex(), ImGui::TableGetColumnName(), ImGui::TableGetHeaderAngledMaxLabelWidth(), ImGui::TableGetHeaderRowHeight(), ImGui::TableGetHoveredColumn(), ImGui::TableGetHoveredRow(), ImGui::TableGetRowIndex(), ImGui::TableGetSortSpecs(), ImGui::TableHeader(), ImGui::TableHeadersRow(), ImGui::TableLoadSettings(), ImGui::TableMergeDrawChannels(), ImGui::TableNextColumn(), ImGui::TableNextRow(), ImGui::TableOpenContextMenu(), ImGui::TablePopBackgroundChannel(), ImGui::TablePopColumnChannel(), ImGui::TablePushBackgroundChannel(), ImGui::TablePushColumnChannel(), ImGui::TableRemove(), ImGui::TableSaveSettings(), ImGui::TableSetBgColor(), ImGui::TableSetColumnEnabled(), ImGui::TableSetColumnIndex(), ImGui::TableSetColumnSortDirection(), ImGui::TableSetColumnWidth(), ImGui::TableSettingsCreate(), ImGui::TableSettingsFindByID(), ImGui::TableSetupColumn(), ImGui::TableSetupScrollFreeze(), ImGui::TableUpdateBorders(), ImGui::TableUpdateLayout(), ImGui::TeleportMousePos(), ImGui::TempInputIsActive(), ImGui::TempInputScalar(), ImGui::TempInputText(), ImGui::TestKeyOwner(), ImGui::TextDisabledV(), ImGui::TextEx(), ImGui::TextLink(), ImGui::TextLinkOpenURL(), ImGui::TextWrappedV(), ImGui::TreeNodeBehavior(), ImGui::TreeNodeDrawLineToChildNode(), ImGui::TreeNodeDrawLineToTreePop(), ImGui::TreeNodeGetOpen(), ImGui::TreeNodeSetOpen(), TreeNodeStoreStackData(), ImGui::TreeNodeUpdateNextOpen(), ImGui::TreePop(), ImGui::TreePushOverrideID(), ImGui::Unindent(), ImGui::UnregisterFontAtlas(), ImGui::UnregisterUserTexture(), ImGui::UpdateCurrentFontSize(), ImGui::UpdateDebugToolFlashStyleColor(), ImGui::UpdateDebugToolItemPathQuery(), ImGui::UpdateDebugToolItemPicker(), ImGui::UpdateFontsNewFrame(), ImGui::UpdateHoveredWindowAndCaptureFlags(), ImPlot::UpdateInput(), ImGui::UpdateInputEvents(), ImGui::UpdateKeyboardInputs(), ImGui::UpdateKeyRoutingTable(), ImGui::UpdateMouseInputs(), ImGui::UpdateMouseMovingWindowEndFrame(), ImGui::UpdateMouseMovingWindowNewFrame(), ImGui::UpdateMouseWheel(), ImGui::UpdateSettings(), ImGui::UpdateTexturesEndFrame(), ImGui::UpdateTexturesNewFrame(), ImGui::UpdateViewportsNewFrame(), ImGui::UpdateWindowInFocusOrderList(), ImGui::UpdateWindowManualResize(), ImGui::UpdateWindowSkipRefresh(), and ImGui::VSliderScalar().