SignalProcessing: examples/imgui/examples/example_glut_opengl2/main.cpp File Reference
main.cpp File Reference
#include "imgui.h"
#include "imgui_impl_glut.h"
#include "imgui_impl_opengl2.h"
#include <GL/freeglut.h>
Macros
#define GL_SILENCE_DEPRECATION
Functions
void MainLoopStep ()
int main (int argc, char **argv)
Variables
static bool show_demo_window = true
static bool show_another_window = false
static ImVec4 clear_color = ImVec4(0.45f, 0.55f, 0.60f, 1.00f)
Macro Definition Documentation
GL_SILENCE_DEPRECATION
#define GL_SILENCE_DEPRECATION
Definition at line 24 of file main.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 43 of file main.cpp.
References ImGuiIO::ConfigFlags, ImGui::CreateContext(), ImGui::DestroyContext(), ImGui::GetIO(), IMGUI_CHECKVERSION, ImGui_ImplGLUT_Init(), ImGui_ImplGLUT_InstallFuncs(), ImGui_ImplGLUT_Shutdown(), ImGui_ImplOpenGL2_Init(), ImGui_ImplOpenGL2_Shutdown(), ImGuiConfigFlags_NavEnableKeyboard, MainLoopStep(), and ImGui::StyleColorsDark().
MainLoopStep()
void MainLoopStep ()
Definition at line 109 of file main.cpp.
References ImGui::Begin(), ImGui::Button(), ImGui::Checkbox(), clear_color, ImGui::ColorEdit3(), ImGuiIO::DisplaySize, ImGui::End(), ImGuiIO::Framerate, ImGui::GetDrawData(), ImGui::GetIO(), GL_COLOR_BUFFER_BIT, glClear, glClearColor, glViewport, ImGui_ImplGLUT_NewFrame(), ImGui_ImplOpenGL2_NewFrame(), ImGui_ImplOpenGL2_RenderDrawData(), ImGui::NewFrame(), ImGui::Render(), ImGui::SameLine(), show_another_window, show_demo_window, ImGui::ShowDemoWindow(), ImGui::SliderFloat(), ImGui::Text(), ImVec4::w, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Variable Documentation
clear_color
ImVec4 clear_color = ImVec4(0.45f, 0.55f, 0.60f, 1.00f) static
Definition at line 41 of file main.cpp.
Referenced by main(), MainLoopStep(), and MainLoopStep().
show_another_window
bool show_another_window = false static
Definition at line 40 of file main.cpp.
Referenced by main(), MainLoopStep(), and MainLoopStep().
show_demo_window
bool show_demo_window = true static
Definition at line 39 of file main.cpp.
Referenced by main(), MainLoopStep(), and MainLoopStep().