SignalProcessing: examples/imgui/backends/imgui_impl_sdlrenderer2.cpp File Reference
imgui_impl_sdlrenderer2.cpp File Reference
#include "imgui.h"
#include "imgui_impl_sdlrenderer2.h"
#include <stdint.h>
#include <SDL.h>
Classes
struct ImGui_ImplSDLRenderer2_Data
Functions
static ImGui_ImplSDLRenderer2_Data * ImGui_ImplSDLRenderer2_GetBackendData ()
bool ImGui_ImplSDLRenderer2_Init (SDL_Renderer *renderer)
void ImGui_ImplSDLRenderer2_Shutdown ()
static void ImGui_ImplSDLRenderer2_SetupRenderState (SDL_Renderer *renderer)
void ImGui_ImplSDLRenderer2_NewFrame ()
void ImGui_ImplSDLRenderer2_RenderDrawData (ImDrawData *draw_data, SDL_Renderer *renderer)
void ImGui_ImplSDLRenderer2_UpdateTexture (ImTextureData *tex)
void ImGui_ImplSDLRenderer2_CreateDeviceObjects ()
void ImGui_ImplSDLRenderer2_DestroyDeviceObjects ()
Function Documentation
ImGui_ImplSDLRenderer2_CreateDeviceObjects()
void ImGui_ImplSDLRenderer2_CreateDeviceObjects ()
Definition at line 279 of file imgui_impl_sdlrenderer2.cpp.
ImGui_ImplSDLRenderer2_DestroyDeviceObjects()
void ImGui_ImplSDLRenderer2_DestroyDeviceObjects ()
Definition at line 283 of file imgui_impl_sdlrenderer2.cpp.
References ImGui::GetPlatformIO(), ImGui_ImplSDLRenderer2_UpdateTexture(), ImTextureStatus_WantDestroy, and ImGuiPlatformIO::Textures.
Referenced by ImGui_ImplSDLRenderer2_Shutdown().
ImGui_ImplSDLRenderer2_GetBackendData()
static ImGui_ImplSDLRenderer2_Data * ImGui_ImplSDLRenderer2_GetBackendData () static
Definition at line 68 of file imgui_impl_sdlrenderer2.cpp.
References ImGuiIO::BackendRendererUserData, ImGui::GetCurrentContext(), and ImGui::GetIO().
Referenced by ImGui_ImplSDLRenderer2_NewFrame(), ImGui_ImplSDLRenderer2_Shutdown(), and ImGui_ImplSDLRenderer2_UpdateTexture().
ImGui_ImplSDLRenderer2_Init()
bool ImGui_ImplSDLRenderer2_Init (SDL_Renderer * renderer)
Definition at line 74 of file imgui_impl_sdlrenderer2.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGui::GetIO(), IM_ASSERT, IM_NEW, IMGUI_CHECKVERSION, ImGuiBackendFlags_RendererHasTextures, ImGuiBackendFlags_RendererHasVtxOffset, and ImGui_ImplSDLRenderer2_Data::Renderer.
Referenced by main().
ImGui_ImplSDLRenderer2_NewFrame()
void ImGui_ImplSDLRenderer2_NewFrame ()
Definition at line 117 of file imgui_impl_sdlrenderer2.cpp.
References IM_ASSERT, IM_UNUSED, and ImGui_ImplSDLRenderer2_GetBackendData().
Referenced by main().
ImGui_ImplSDLRenderer2_RenderDrawData()
void ImGui_ImplSDLRenderer2_RenderDrawData (ImDrawData * draw_data, SDL_Renderer * renderer)
Definition at line 124 of file imgui_impl_sdlrenderer2.cpp.
References ImDrawCmd::ClipRect, ImDrawList::CmdBuffer, ImDrawData::CmdLists, ImVector< T >::Data, ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImDrawCmd::ElemCount, ImDrawData::FramebufferScale, ImGui::GetPlatformIO(), ImDrawCmd::GetTexID(), ImDrawList::IdxBuffer, ImDrawCmd::IdxOffset, ImDrawCallback_ResetRenderState, ImGui_ImplSDLRenderer2_SetupRenderState(), ImGui_ImplSDLRenderer2_UpdateTexture(), ImTextureStatus_OK, ImGui_ImplSDLRenderer2_RenderState::Renderer, ImGuiPlatformIO::Renderer_RenderState, ImVector< T >::Size, ImDrawData::Textures, ImDrawCmd::UserCallback, ImDrawList::VtxBuffer, ImDrawCmd::VtxOffset, ImVec4::w, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by main().
ImGui_ImplSDLRenderer2_SetupRenderState()
static void ImGui_ImplSDLRenderer2_SetupRenderState (SDL_Renderer * renderer) static
Definition at line 109 of file imgui_impl_sdlrenderer2.cpp.
Referenced by ImGui_ImplSDLRenderer2_RenderDrawData().
ImGui_ImplSDLRenderer2_Shutdown()
void ImGui_ImplSDLRenderer2_Shutdown ()
Definition at line 93 of file imgui_impl_sdlrenderer2.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGuiPlatformIO::ClearRendererHandlers(), ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplSDLRenderer2_DestroyDeviceObjects(), ImGui_ImplSDLRenderer2_GetBackendData(), ImGuiBackendFlags_RendererHasTextures, and ImGuiBackendFlags_RendererHasVtxOffset.
Referenced by main().
ImGui_ImplSDLRenderer2_UpdateTexture()
void ImGui_ImplSDLRenderer2_UpdateTexture (ImTextureData * tex)
Definition at line 233 of file imgui_impl_sdlrenderer2.cpp.
References ImTextureData::BackendUserData, ImTextureData::Format, ImTextureData::GetPitch(), ImTextureData::GetPixels(), ImTextureData::GetPixelsAt(), ImTextureData::Height, IM_ASSERT, ImGui_ImplSDLRenderer2_GetBackendData(), ImTextureFormat_RGBA32, ImTextureID_Invalid, ImTextureStatus_Destroyed, ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImGui_ImplSDLRenderer2_Data::Renderer, ImTextureData::SetStatus(), ImTextureData::SetTexID(), ImTextureData::Status, ImTextureData::TexID, ImTextureData::Updates, and ImTextureData::Width.
Referenced by ImGui_ImplSDLRenderer2_DestroyDeviceObjects(), and ImGui_ImplSDLRenderer2_RenderDrawData().