SignalProcessing: examples/imgui/backends/imgui_impl_glfw.h File Reference
imgui_impl_glfw.h File Reference
#include "imgui.h"
Functions
IMGUI_IMPL_API bool ImGui_ImplGlfw_InitForOpenGL (GLFWwindow *window, bool install_callbacks)
IMGUI_IMPL_API bool ImGui_ImplGlfw_InitForVulkan (GLFWwindow *window, bool install_callbacks)
IMGUI_IMPL_API bool ImGui_ImplGlfw_InitForOther (GLFWwindow *window, bool install_callbacks)
IMGUI_IMPL_API void ImGui_ImplGlfw_Shutdown ()
IMGUI_IMPL_API void ImGui_ImplGlfw_NewFrame ()
IMGUI_IMPL_API void ImGui_ImplGlfw_InstallCallbacks (GLFWwindow *window)
IMGUI_IMPL_API void ImGui_ImplGlfw_RestoreCallbacks (GLFWwindow *window)
IMGUI_IMPL_API void ImGui_ImplGlfw_SetCallbacksChainForAllWindows (bool chain_for_all_windows)
IMGUI_IMPL_API void ImGui_ImplGlfw_WindowFocusCallback (GLFWwindow *window, int focused)
IMGUI_IMPL_API void ImGui_ImplGlfw_CursorEnterCallback (GLFWwindow *window, int entered)
IMGUI_IMPL_API void ImGui_ImplGlfw_CursorPosCallback (GLFWwindow *window, double x, double y)
IMGUI_IMPL_API void ImGui_ImplGlfw_MouseButtonCallback (GLFWwindow *window, int button, int action, int mods)
IMGUI_IMPL_API void ImGui_ImplGlfw_ScrollCallback (GLFWwindow *window, double xoffset, double yoffset)
IMGUI_IMPL_API void ImGui_ImplGlfw_KeyCallback (GLFWwindow *window, int key, int scancode, int action, int mods)
IMGUI_IMPL_API void ImGui_ImplGlfw_CharCallback (GLFWwindow *window, unsigned int c)
IMGUI_IMPL_API void ImGui_ImplGlfw_MonitorCallback (GLFWmonitor *monitor, int event)
IMGUI_IMPL_API void ImGui_ImplGlfw_Sleep (int milliseconds)
IMGUI_IMPL_API float ImGui_ImplGlfw_GetContentScaleForWindow (GLFWwindow *window)
IMGUI_IMPL_API float ImGui_ImplGlfw_GetContentScaleForMonitor (GLFWmonitor *monitor)
Function Documentation
ImGui_ImplGlfw_CharCallback()
IMGUI_IMPL_API void ImGui_ImplGlfw_CharCallback (GLFWwindow * window, unsigned int c)
Definition at line 532 of file imgui_impl_glfw.cpp.
References ImGuiIO::AddInputCharacter(), ImGui_ImplGlfw_Data::Context, ImGui::GetIO(), ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_ShouldChainCallback(), and ImGui_ImplGlfw_Data::PrevUserCallbackChar.
Referenced by ImGui_ImplGlfw_InstallCallbacks().
ImGui_ImplGlfw_CursorEnterCallback()
IMGUI_IMPL_API void ImGui_ImplGlfw_CursorEnterCallback (GLFWwindow * window, int entered)
Definition at line 512 of file imgui_impl_glfw.cpp.
References ImGuiIO::AddMousePosEvent(), ImGui_ImplGlfw_Data::Context, ImGui::GetIO(), ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_ShouldChainCallback(), ImGui_ImplGlfw_Data::LastValidMousePos, ImGuiIO::MousePos, ImGui_ImplGlfw_Data::MouseWindow, ImGui_ImplGlfw_Data::PrevUserCallbackCursorEnter, ImVec2::x, and ImVec2::y.
Referenced by ImGui_ImplGlfw_InstallCallbacks().
ImGui_ImplGlfw_CursorPosCallback()
IMGUI_IMPL_API void ImGui_ImplGlfw_CursorPosCallback (GLFWwindow * window, double x, double y)
Definition at line 499 of file imgui_impl_glfw.cpp.
References ImGuiIO::AddMousePosEvent(), ImGui_ImplGlfw_Data::Context, ImGui::GetIO(), ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_ShouldChainCallback(), ImGui_ImplGlfw_Data::LastValidMousePos, and ImGui_ImplGlfw_Data::PrevUserCallbackCursorPos.
Referenced by ImGui_ImplGlfw_InstallCallbacks().
ImGui_ImplGlfw_GetContentScaleForMonitor()
IMGUI_IMPL_API float ImGui_ImplGlfw_GetContentScaleForMonitor (GLFWmonitor * monitor)
Definition at line 957 of file imgui_impl_glfw.cpp.
References glfwGetMonitorContentScale(), IM_UNUSED, and ImGui_ImplGlfw_IsWayland().
Referenced by main().
ImGui_ImplGlfw_GetContentScaleForWindow()
IMGUI_IMPL_API float ImGui_ImplGlfw_GetContentScaleForWindow (GLFWwindow * window)
Definition at line 940 of file imgui_impl_glfw.cpp.
References glfwGetWindowContentScale(), IM_UNUSED, ImGui_ImplGlfw_GetBackendData(), and ImGui_ImplGlfw_Data::IsWayland.
ImGui_ImplGlfw_InitForOpenGL()
IMGUI_IMPL_API bool ImGui_ImplGlfw_InitForOpenGL (GLFWwindow * window, bool install_callbacks)
Definition at line 767 of file imgui_impl_glfw.cpp.
References GlfwClientApi_OpenGL, and ImGui_ImplGlfw_Init().
Referenced by main(), and main().
ImGui_ImplGlfw_InitForOther()
IMGUI_IMPL_API bool ImGui_ImplGlfw_InitForOther (GLFWwindow * window, bool install_callbacks)
Definition at line 777 of file imgui_impl_glfw.cpp.
References GlfwClientApi_Unknown, and ImGui_ImplGlfw_Init().
Referenced by main().
ImGui_ImplGlfw_InitForVulkan()
IMGUI_IMPL_API bool ImGui_ImplGlfw_InitForVulkan (GLFWwindow * window, bool install_callbacks)
Definition at line 772 of file imgui_impl_glfw.cpp.
References GlfwClientApi_Vulkan, and ImGui_ImplGlfw_Init().
Referenced by main().
ImGui_ImplGlfw_InstallCallbacks()
IMGUI_IMPL_API void ImGui_ImplGlfw_InstallCallbacks (GLFWwindow * window)
Definition at line 598 of file imgui_impl_glfw.cpp.
References glfwSetCharCallback(), glfwSetCursorEnterCallback(), glfwSetCursorPosCallback(), glfwSetKeyCallback(), glfwSetMonitorCallback(), glfwSetMouseButtonCallback(), glfwSetScrollCallback(), glfwSetWindowFocusCallback(), IM_ASSERT, ImGui_ImplGlfw_CharCallback(), ImGui_ImplGlfw_CursorEnterCallback(), ImGui_ImplGlfw_CursorPosCallback(), ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_KeyCallback(), ImGui_ImplGlfw_MonitorCallback(), ImGui_ImplGlfw_MouseButtonCallback(), ImGui_ImplGlfw_ScrollCallback(), ImGui_ImplGlfw_WindowFocusCallback(), ImGui_ImplGlfw_Data::InstalledCallbacks, ImGui_ImplGlfw_Data::PrevUserCallbackChar, ImGui_ImplGlfw_Data::PrevUserCallbackCursorEnter, ImGui_ImplGlfw_Data::PrevUserCallbackCursorPos, ImGui_ImplGlfw_Data::PrevUserCallbackKey, ImGui_ImplGlfw_Data::PrevUserCallbackMonitor, ImGui_ImplGlfw_Data::PrevUserCallbackMousebutton, ImGui_ImplGlfw_Data::PrevUserCallbackScroll, ImGui_ImplGlfw_Data::PrevUserCallbackWindowFocus, and ImGui_ImplGlfw_Data::Window.
Referenced by ImGui_ImplGlfw_Init().
ImGui_ImplGlfw_KeyCallback()
IMGUI_IMPL_API void ImGui_ImplGlfw_KeyCallback (GLFWwindow * window, int key, int scancode, int action, int mods)
Definition at line 470 of file imgui_impl_glfw.cpp.
References ImGuiIO::AddKeyEvent(), ImGui_ImplGlfw_Data::Context, ImGui::GetIO(), GLFW_PRESS, GLFW_RELEASE, ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_KeyToImGuiKey(), ImGui_ImplGlfw_ShouldChainCallback(), ImGui_ImplGlfw_TranslateUntranslatedKey(), ImGui_ImplGlfw_UpdateKeyModifiers(), ImGui_ImplGlfw_Data::PrevUserCallbackKey, and ImGuiIO::SetKeyEventNativeData().
Referenced by ImGui_ImplGlfw_InstallCallbacks().
ImGui_ImplGlfw_MonitorCallback()
IMGUI_IMPL_API void ImGui_ImplGlfw_MonitorCallback (GLFWmonitor * monitor, int event)
Definition at line 542 of file imgui_impl_glfw.cpp.
Referenced by ImGui_ImplGlfw_InstallCallbacks().
ImGui_ImplGlfw_MouseButtonCallback()
IMGUI_IMPL_API void ImGui_ImplGlfw_MouseButtonCallback (GLFWwindow * window, int button, int action, int mods)
Definition at line 409 of file imgui_impl_glfw.cpp.
References ImGuiIO::AddMouseButtonEvent(), ImGui_ImplGlfw_Data::Context, ImGui::GetIO(), GLFW_PRESS, ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_ShouldChainCallback(), ImGui_ImplGlfw_UpdateKeyModifiers(), ImGuiMouseButton_COUNT, and ImGui_ImplGlfw_Data::PrevUserCallbackMousebutton.
Referenced by ImGui_ImplGlfw_InstallCallbacks().
ImGui_ImplGlfw_NewFrame()
IMGUI_IMPL_API void ImGui_ImplGlfw_NewFrame ()
Definition at line 992 of file imgui_impl_glfw.cpp.
References ImGuiIO::DeltaTime, ImGuiIO::DisplayFramebufferScale, ImGuiIO::DisplaySize, ImGui::GetIO(), glfwGetTime(), IM_ASSERT, ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_GetWindowSizeAndFramebufferScale(), ImGui_ImplGlfw_UpdateGamepads(), ImGui_ImplGlfw_UpdateMouseCursor(), ImGui_ImplGlfw_UpdateMouseData(), ImGui_ImplGlfw_Data::Time, and ImGui_ImplGlfw_Data::Window.
Referenced by main(), and main().
ImGui_ImplGlfw_RestoreCallbacks()
IMGUI_IMPL_API void ImGui_ImplGlfw_RestoreCallbacks (GLFWwindow * window)
Definition at line 615 of file imgui_impl_glfw.cpp.
References glfwSetCharCallback(), glfwSetCursorEnterCallback(), glfwSetCursorPosCallback(), glfwSetKeyCallback(), glfwSetMonitorCallback(), glfwSetMouseButtonCallback(), glfwSetScrollCallback(), glfwSetWindowFocusCallback(), IM_ASSERT, ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_Data::InstalledCallbacks, ImGui_ImplGlfw_Data::PrevUserCallbackChar, ImGui_ImplGlfw_Data::PrevUserCallbackCursorEnter, ImGui_ImplGlfw_Data::PrevUserCallbackCursorPos, ImGui_ImplGlfw_Data::PrevUserCallbackKey, ImGui_ImplGlfw_Data::PrevUserCallbackMonitor, ImGui_ImplGlfw_Data::PrevUserCallbackMousebutton, ImGui_ImplGlfw_Data::PrevUserCallbackScroll, ImGui_ImplGlfw_Data::PrevUserCallbackWindowFocus, and ImGui_ImplGlfw_Data::Window.
Referenced by ImGui_ImplGlfw_Shutdown().
ImGui_ImplGlfw_ScrollCallback()
IMGUI_IMPL_API void ImGui_ImplGlfw_ScrollCallback (GLFWwindow * window, double xoffset, double yoffset)
Definition at line 421 of file imgui_impl_glfw.cpp.
References ImGuiIO::AddMouseWheelEvent(), ImGui_ImplGlfw_Data::Context, ImGui::GetIO(), ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_ShouldChainCallback(), and ImGui_ImplGlfw_Data::PrevUserCallbackScroll.
Referenced by ImGui_ImplGlfw_InstallCallbacks().
ImGui_ImplGlfw_SetCallbacksChainForAllWindows()
IMGUI_IMPL_API void ImGui_ImplGlfw_SetCallbacksChainForAllWindows (bool chain_for_all_windows)
Definition at line 644 of file imgui_impl_glfw.cpp.
References ImGui_ImplGlfw_Data::CallbacksChainForAllWindows, and ImGui_ImplGlfw_GetBackendData().
ImGui_ImplGlfw_Shutdown()
IMGUI_IMPL_API void ImGui_ImplGlfw_Shutdown ()
Definition at line 782 of file imgui_impl_glfw.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendPlatformName, ImGuiIO::BackendPlatformUserData, ImGuiPlatformIO::ClearPlatformHandlers(), ImGui::GetIO(), ImGui::GetMainViewport(), ImGui::GetPlatformIO(), glfwDestroyCursor(), IM_ASSERT, IM_DELETE(), ImGui_ImplGlfw_ContextMap_Remove(), ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_RestoreCallbacks(), ImGuiBackendFlags_HasGamepad, ImGuiBackendFlags_HasMouseCursors, ImGuiBackendFlags_HasSetMousePos, ImGuiMouseCursor_COUNT, ImGui_ImplGlfw_Data::InstalledCallbacks, ImGuiViewport::PlatformHandleRaw, and ImGui_ImplGlfw_Data::Window.
Referenced by main(), and main().
ImGui_ImplGlfw_Sleep()
IMGUI_IMPL_API void ImGui_ImplGlfw_Sleep (int milliseconds)
Definition at line 1017 of file imgui_impl_glfw.cpp.
Referenced by main().
ImGui_ImplGlfw_WindowFocusCallback()
IMGUI_IMPL_API void ImGui_ImplGlfw_WindowFocusCallback (GLFWwindow * window, int focused)
Definition at line 489 of file imgui_impl_glfw.cpp.
References ImGuiIO::AddFocusEvent(), ImGui_ImplGlfw_Data::Context, ImGui::GetIO(), ImGui_ImplGlfw_GetBackendData(), ImGui_ImplGlfw_ShouldChainCallback(), and ImGui_ImplGlfw_Data::PrevUserCallbackWindowFocus.
Referenced by ImGui_ImplGlfw_InstallCallbacks().