SignalProcessing: examples/imgui/backends/imgui_impl_vulkan.h File Reference
imgui_impl_vulkan.h File Reference
#include "imgui.h"
#include <vulkan/vulkan.h>
Classes
struct ImGui_ImplVulkan_PipelineInfo
struct ImGui_ImplVulkan_InitInfo
struct ImGui_ImplVulkan_RenderState
struct ImGui_ImplVulkanH_Frame
struct ImGui_ImplVulkanH_FrameSemaphores
struct ImGui_ImplVulkanH_Window
Macros
#define IMGUI_IMPL_VULKAN_MINIMUM_IMAGE_SAMPLER_POOL_SIZE (8)
Functions
IMGUI_IMPL_API bool ImGui_ImplVulkan_Init (ImGui_ImplVulkan_InitInfo *info)
IMGUI_IMPL_API void ImGui_ImplVulkan_Shutdown ()
IMGUI_IMPL_API void ImGui_ImplVulkan_NewFrame ()
IMGUI_IMPL_API void ImGui_ImplVulkan_RenderDrawData (ImDrawData *draw_data, VkCommandBuffer command_buffer, VkPipeline pipeline=VK_NULL_HANDLE)
IMGUI_IMPL_API void ImGui_ImplVulkan_SetMinImageCount (uint32_t min_image_count)
IMGUI_IMPL_API void ImGui_ImplVulkan_CreateMainPipeline (const ImGui_ImplVulkan_PipelineInfo *info)
IMGUI_IMPL_API void ImGui_ImplVulkan_UpdateTexture (ImTextureData *tex)
IMGUI_IMPL_API VkDescriptorSet ImGui_ImplVulkan_AddTexture (VkSampler sampler, VkImageView image_view, VkImageLayout image_layout)
IMGUI_IMPL_API void ImGui_ImplVulkan_RemoveTexture (VkDescriptorSet descriptor_set)
IMGUI_IMPL_API bool ImGui_ImplVulkan_LoadFunctions (uint32_t api_version, PFN_vkVoidFunction(*loader_func)(const char *function_name, void *user_data), void *user_data=nullptr)
IMGUI_IMPL_API void ImGui_ImplVulkanH_CreateOrResizeWindow (VkInstance instance, VkPhysicalDevice physical_device, VkDevice device, ImGui_ImplVulkanH_Window *wd, uint32_t queue_family, const VkAllocationCallbacks *allocator, int w, int h, uint32_t min_image_count, VkImageUsageFlags image_usage)
IMGUI_IMPL_API void ImGui_ImplVulkanH_DestroyWindow (VkInstance instance, VkDevice device, ImGui_ImplVulkanH_Window *wd, const VkAllocationCallbacks *allocator)
IMGUI_IMPL_API VkSurfaceFormatKHR ImGui_ImplVulkanH_SelectSurfaceFormat (VkPhysicalDevice physical_device, VkSurfaceKHR surface, const VkFormat *request_formats, int request_formats_count, VkColorSpaceKHR request_color_space)
IMGUI_IMPL_API VkPresentModeKHR ImGui_ImplVulkanH_SelectPresentMode (VkPhysicalDevice physical_device, VkSurfaceKHR surface, const VkPresentModeKHR *request_modes, int request_modes_count)
IMGUI_IMPL_API VkPhysicalDevice ImGui_ImplVulkanH_SelectPhysicalDevice (VkInstance instance)
IMGUI_IMPL_API uint32_t ImGui_ImplVulkanH_SelectQueueFamilyIndex (VkPhysicalDevice physical_device)
IMGUI_IMPL_API int ImGui_ImplVulkanH_GetMinImageCountFromPresentMode (VkPresentModeKHR present_mode)
Macro Definition Documentation
IMGUI_IMPL_VULKAN_MINIMUM_IMAGE_SAMPLER_POOL_SIZE
#define IMGUI_IMPL_VULKAN_MINIMUM_IMAGE_SAMPLER_POOL_SIZE (8)
Definition at line 75 of file imgui_impl_vulkan.h.
Function Documentation
ImGui_ImplVulkan_AddTexture()
IMGUI_IMPL_API VkDescriptorSet ImGui_ImplVulkan_AddTexture (VkSampler sampler, VkImageView image_view, VkImageLayout image_layout)
Definition at line 1347 of file imgui_impl_vulkan.cpp.
References check_vk_result(), ImGui_ImplVulkan_Data::DescriptorPool, ImGui_ImplVulkan_InitInfo::DescriptorPool, ImGui_ImplVulkan_Data::DescriptorSetLayout, ImGui_ImplVulkan_InitInfo::Device, ImGui_ImplVulkan_GetBackendData(), and ImGui_ImplVulkan_Data::VulkanInitInfo.
Referenced by ImGui_ImplVulkan_UpdateTexture().
ImGui_ImplVulkan_CreateMainPipeline()
IMGUI_IMPL_API void ImGui_ImplVulkan_CreateMainPipeline (const ImGui_ImplVulkan_PipelineInfo * info)
Definition at line 1142 of file imgui_impl_vulkan.cpp.
References ImGui_ImplVulkan_InitInfo::Allocator, ImVector< T >::Data, ImGui_ImplVulkan_InitInfo::Device, ImGui_ImplVulkan_CreatePipeline(), ImGui_ImplVulkan_GetBackendData(), ImGui_ImplVulkan_Data::Pipeline, ImGui_ImplVulkan_InitInfo::PipelineCache, ImGui_ImplVulkan_InitInfo::PipelineInfoMain, ImGui_ImplVulkan_Data::PipelineRenderingCreateInfoColorAttachmentFormats, ImVector< T >::resize(), ImVector< T >::size_in_bytes(), ImVector< T >::swap(), ImGui_ImplVulkan_InitInfo::UseDynamicRendering, and ImGui_ImplVulkan_Data::VulkanInitInfo.
Referenced by ImGui_ImplVulkan_CreateDeviceObjects().
ImGui_ImplVulkan_Init()
IMGUI_IMPL_API bool ImGui_ImplVulkan_Init (ImGui_ImplVulkan_InitInfo * info)
Definition at line 1251 of file imgui_impl_vulkan.cpp.
References ImGui_ImplVulkan_InitInfo::ApiVersion, ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGui_ImplVulkan_InitInfo::DescriptorPool, ImGui_ImplVulkan_InitInfo::DescriptorPoolSize, ImGui_ImplVulkan_InitInfo::Device, g_FunctionsLoaded, ImGui::GetIO(), IM_ASSERT, IM_NEW, ImGui_ImplVulkan_InitInfo::ImageCount, IMGUI_CHECKVERSION, ImGui_ImplVulkan_CreateDeviceObjects(), ImGui_ImplVulkan_GetDefaultApiVersion(), ImGuiBackendFlags_RendererHasTextures, ImGuiBackendFlags_RendererHasVtxOffset, ImGui_ImplVulkan_InitInfo::Instance, ImGui_ImplVulkan_InitInfo::MinImageCount, ImGui_ImplVulkan_Data::NonCoherentAtomSize, ImGui_ImplVulkan_InitInfo::PhysicalDevice, ImGui_ImplVulkan_InitInfo::PipelineInfoMain, ImGui_ImplVulkan_InitInfo::Queue, ImGui_ImplVulkan_PipelineInfo::RenderPass, ImGui_ImplVulkan_InitInfo::UseDynamicRendering, and ImGui_ImplVulkan_Data::VulkanInitInfo.
Referenced by main().
ImGui_ImplVulkan_LoadFunctions()
IMGUI_IMPL_API bool ImGui_ImplVulkan_LoadFunctions (uint32_t api_version, PFN_vkVoidFunction(*)(const char *function_name, void *user_data) loader_func, void * user_data = nullptr)
Definition at line 1222 of file imgui_impl_vulkan.cpp.
References g_FunctionsLoaded, IM_UNUSED, and ImGui_ImplVulkan_GetDefaultApiVersion().
ImGui_ImplVulkan_NewFrame()
IMGUI_IMPL_API void ImGui_ImplVulkan_NewFrame ()
Definition at line 1324 of file imgui_impl_vulkan.cpp.
References IM_ASSERT, IM_UNUSED, and ImGui_ImplVulkan_GetBackendData().
Referenced by main().
ImGui_ImplVulkan_RemoveTexture()
IMGUI_IMPL_API void ImGui_ImplVulkan_RemoveTexture (VkDescriptorSet descriptor_set)
Definition at line 1382 of file imgui_impl_vulkan.cpp.
References ImGui_ImplVulkan_Data::DescriptorPool, ImGui_ImplVulkan_InitInfo::DescriptorPool, ImGui_ImplVulkan_InitInfo::Device, ImGui_ImplVulkan_GetBackendData(), and ImGui_ImplVulkan_Data::VulkanInitInfo.
Referenced by ImGui_ImplVulkan_DestroyTexture().
ImGui_ImplVulkan_RenderDrawData()
IMGUI_IMPL_API void ImGui_ImplVulkan_RenderDrawData (ImDrawData * draw_data, VkCommandBuffer command_buffer, VkPipeline pipeline = VK_NULL_HANDLE)
Definition at line 513 of file imgui_impl_vulkan.cpp.
References AlignBufferSize(), ImGui_ImplVulkan_Data::BufferMemoryAlignment, check_vk_result(), ImDrawCmd::ClipRect, ImDrawList::CmdBuffer, ImDrawData::CmdLists, ImGui_ImplVulkan_RenderState::CommandBuffer, ImGui_ImplVulkan_WindowRenderBuffers::Count, CreateOrResizeBuffer(), ImVector< T >::Data, ImGui_ImplVulkan_InitInfo::Device, ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImDrawCmd::ElemCount, ImDrawData::FramebufferScale, ImGui_ImplVulkan_WindowRenderBuffers::FrameRenderBuffers, ImGui::GetPlatformIO(), ImDrawCmd::GetTexID(), ImDrawList::IdxBuffer, ImDrawCmd::IdxOffset, IM_ASSERT, ImGui_ImplVulkan_InitInfo::ImageCount, ImDrawCallback_ResetRenderState, ImGui_ImplVulkan_GetBackendData(), ImGui_ImplVulkan_SetupRenderState(), ImGui_ImplVulkan_UpdateTexture(), ImTextureStatus_OK, ImGui_ImplVulkan_WindowRenderBuffers::Index, ImGui_ImplVulkan_FrameRenderBuffers::IndexBuffer, ImGui_ImplVulkan_FrameRenderBuffers::IndexBufferMemory, ImGui_ImplVulkan_FrameRenderBuffers::IndexBufferSize, ImGui_ImplVulkan_Data::MainWindowRenderBuffers, ImGui_ImplVulkan_Data::Pipeline, ImGui_ImplVulkan_RenderState::Pipeline, ImGui_ImplVulkan_Data::PipelineLayout, ImGui_ImplVulkan_RenderState::PipelineLayout, ImGuiPlatformIO::Renderer_RenderState, ImVector< T >::resize(), ImVector< T >::Size, ImVector< T >::size_in_bytes(), ImDrawData::Textures, ImDrawData::TotalIdxCount, ImDrawData::TotalVtxCount, ImDrawCmd::UserCallback, ImGui_ImplVulkan_FrameRenderBuffers::VertexBuffer, ImGui_ImplVulkan_FrameRenderBuffers::VertexBufferMemory, ImGui_ImplVulkan_FrameRenderBuffers::VertexBufferSize, ImDrawList::VtxBuffer, ImDrawCmd::VtxOffset, ImGui_ImplVulkan_Data::VulkanInitInfo, ImVec4::w, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by FrameRender().
ImGui_ImplVulkan_SetMinImageCount()
IMGUI_IMPL_API void ImGui_ImplVulkan_SetMinImageCount (uint32_t min_image_count)
Definition at line 1331 of file imgui_impl_vulkan.cpp.
References ImGui_ImplVulkan_InitInfo::Allocator, check_vk_result(), ImGui_ImplVulkan_InitInfo::Device, IM_ASSERT, ImGui_ImplVulkan_DestroyWindowRenderBuffers(), ImGui_ImplVulkan_GetBackendData(), ImGui_ImplVulkan_Data::MainWindowRenderBuffers, ImGui_ImplVulkan_InitInfo::MinImageCount, and ImGui_ImplVulkan_Data::VulkanInitInfo.
Referenced by main(), and WndProc().
ImGui_ImplVulkan_Shutdown()
IMGUI_IMPL_API void ImGui_ImplVulkan_Shutdown ()
Definition at line 1308 of file imgui_impl_vulkan.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGuiPlatformIO::ClearRendererHandlers(), ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplVulkan_DestroyDeviceObjects(), ImGui_ImplVulkan_GetBackendData(), ImGuiBackendFlags_RendererHasTextures, and ImGuiBackendFlags_RendererHasVtxOffset.
Referenced by main().
ImGui_ImplVulkan_UpdateTexture()
IMGUI_IMPL_API void ImGui_ImplVulkan_UpdateTexture (ImTextureData * tex)
Definition at line 686 of file imgui_impl_vulkan.cpp.
References AlignBufferSize(), ImGui_ImplVulkan_InitInfo::Allocator, ImTextureData::BackendUserData, ImGui_ImplVulkan_Data::BufferMemoryAlignment, ImTextureData::BytesPerPixel, check_vk_result(), ImGui_ImplVulkan_Texture::DescriptorSet, ImGui_ImplVulkan_InitInfo::Device, ImTextureData::Format, ImTextureData::GetPixelsAt(), ImTextureRect::h, ImTextureData::Height, IM_ASSERT, IM_MAX, IM_NEW, ImGui_ImplVulkan_Texture::Image, ImGui_ImplVulkan_InitInfo::ImageCount, ImGui_ImplVulkan_Texture::ImageView, ImGui_ImplVulkan_AddTexture(), ImGui_ImplVulkan_DestroyTexture(), ImGui_ImplVulkan_GetBackendData(), ImGui_ImplVulkan_MemoryType(), ImTextureFormat_RGBA32, ImTextureID_Invalid, ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImGui_ImplVulkan_Texture::Memory, ImGui_ImplVulkan_InitInfo::MinAllocationSize, ImGui_ImplVulkan_Data::NonCoherentAtomSize, ImGui_ImplVulkan_InitInfo::Queue, ImTextureData::SetStatus(), ImTextureData::SetTexID(), ImTextureData::Status, ImGui_ImplVulkan_Data::TexCommandBuffer, ImGui_ImplVulkan_Data::TexCommandPool, ImTextureData::TexID, ImGui_ImplVulkan_Data::TexSamplerLinear, ImTextureData::UnusedFrames, ImTextureData::UpdateRect, ImGui_ImplVulkan_Data::VulkanInitInfo, ImTextureRect::w, ImTextureData::Width, ImTextureRect::x, and ImTextureRect::y.
Referenced by ImGui_ImplVulkan_RenderDrawData().
ImGui_ImplVulkanH_CreateOrResizeWindow()
IMGUI_IMPL_API void ImGui_ImplVulkanH_CreateOrResizeWindow (VkInstance instance, VkPhysicalDevice physical_device, VkDevice device, ImGui_ImplVulkanH_Window * wd, uint32_t queue_family, const VkAllocationCallbacks * allocator, int w, int h, uint32_t min_image_count, VkImageUsageFlags image_usage)
Definition at line 1772 of file imgui_impl_vulkan.cpp.
References check_vk_result(), ImGui_ImplVulkanH_Window::Frames, g_FunctionsLoaded, IM_ASSERT, ImGui_ImplVulkanH_Window::ImageCount, ImGui_ImplVulkanH_CreateWindowCommandBuffers(), and ImGui_ImplVulkanH_CreateWindowSwapChain().
Referenced by main(), SetupVulkanWindow(), and WndProc().
ImGui_ImplVulkanH_DestroyWindow()
IMGUI_IMPL_API void ImGui_ImplVulkanH_DestroyWindow (VkInstance instance, VkDevice device, ImGui_ImplVulkanH_Window * wd, const VkAllocationCallbacks * allocator)
Definition at line 1856 of file imgui_impl_vulkan.cpp.
References ImVector< T >::clear(), ImGui_ImplVulkanH_Window::Frames, ImGui_ImplVulkanH_Window::FrameSemaphores, ImGui_ImplVulkanH_Window::ImageCount, ImGui_ImplVulkanH_DestroyFrame(), ImGui_ImplVulkanH_DestroyFrameSemaphores(), ImGui_ImplVulkanH_Window::Pipeline, ImGui_ImplVulkanH_Window::RenderPass, ImGui_ImplVulkanH_Window::SemaphoreCount, ImGui_ImplVulkanH_Window::Surface, and ImGui_ImplVulkanH_Window::Swapchain.
Referenced by CleanupVulkanWindow().
ImGui_ImplVulkanH_GetMinImageCountFromPresentMode()
IMGUI_IMPL_API int ImGui_ImplVulkanH_GetMinImageCountFromPresentMode (VkPresentModeKHR present_mode)
Definition at line 1586 of file imgui_impl_vulkan.cpp.
References IM_ASSERT.
Referenced by ImGui_ImplVulkanH_CreateWindowSwapChain().
ImGui_ImplVulkanH_SelectPhysicalDevice()
IMGUI_IMPL_API VkPhysicalDevice ImGui_ImplVulkanH_SelectPhysicalDevice (VkInstance instance)
Definition at line 1493 of file imgui_impl_vulkan.cpp.
References check_vk_result(), ImVector< T >::Data, IM_ASSERT, and ImVector< T >::resize().
Referenced by SetupVulkan().
ImGui_ImplVulkanH_SelectPresentMode()
IMGUI_IMPL_API VkPresentModeKHR ImGui_ImplVulkanH_SelectPresentMode (VkPhysicalDevice physical_device, VkSurfaceKHR surface, const VkPresentModeKHR * request_modes, int request_modes_count)
Definition at line 1470 of file imgui_impl_vulkan.cpp.
References ImVector< T >::Data, g_FunctionsLoaded, IM_ASSERT, and ImVector< T >::resize().
Referenced by SetupVulkanWindow().
ImGui_ImplVulkanH_SelectQueueFamilyIndex()
IMGUI_IMPL_API uint32_t ImGui_ImplVulkanH_SelectQueueFamilyIndex (VkPhysicalDevice physical_device)
Definition at line 1523 of file imgui_impl_vulkan.cpp.
References ImVector< T >::Data, and ImVector< T >::resize().
Referenced by SetupVulkan().
ImGui_ImplVulkanH_SelectSurfaceFormat()
IMGUI_IMPL_API VkSurfaceFormatKHR ImGui_ImplVulkanH_SelectSurfaceFormat (VkPhysicalDevice physical_device, VkSurfaceKHR surface, const VkFormat * request_formats, int request_formats_count, VkColorSpaceKHR request_color_space)
Definition at line 1425 of file imgui_impl_vulkan.cpp.
References ImVector< T >::Data, g_FunctionsLoaded, IM_ASSERT, and ImVector< T >::resize().
Referenced by SetupVulkanWindow().