SignalProcessing: examples/imgui/imgui_widgets.cpp File Reference
imgui_widgets.cpp File Reference
#include "imgui.h"
#include "imgui_internal.h"
#include <stdint.h>
#include "imstb_textedit.h"
Classes
struct ImGuiGetNameFromIndexOldToNewCallbackData
struct ImGuiPlotArrayGetterData
struct ImGuiTabBarSection
Namespaces
namespace ImStb
namespace ImGui
Macros
#define IMGUI_DEFINE_MATH_OPERATORS
#define IMSTB_TEXTEDIT_GETNEXTCHARINDEX IMSTB_TEXTEDIT_GETNEXTCHARINDEX_IMPL
#define IMSTB_TEXTEDIT_GETPREVCHARINDEX IMSTB_TEXTEDIT_GETPREVCHARINDEX_IMPL
#define STB_TEXTEDIT_MOVEWORDLEFT STB_TEXTEDIT_MOVEWORDLEFT_IMPL
#define STB_TEXTEDIT_MOVEWORDRIGHT STB_TEXTEDIT_MOVEWORDRIGHT_IMPL
#define STB_TEXTEDIT_MOVELINESTART STB_TEXTEDIT_MOVELINESTART_IMPL
#define STB_TEXTEDIT_MOVELINEEND STB_TEXTEDIT_MOVELINEEND_IMPL
#define STB_TEXTEDIT_K_LEFT 0x200000
#define STB_TEXTEDIT_K_RIGHT 0x200001
#define STB_TEXTEDIT_K_UP 0x200002
#define STB_TEXTEDIT_K_DOWN 0x200003
#define STB_TEXTEDIT_K_LINESTART 0x200004
#define STB_TEXTEDIT_K_LINEEND 0x200005
#define STB_TEXTEDIT_K_TEXTSTART 0x200006
#define STB_TEXTEDIT_K_TEXTEND 0x200007
#define STB_TEXTEDIT_K_DELETE 0x200008
#define STB_TEXTEDIT_K_BACKSPACE 0x200009
#define STB_TEXTEDIT_K_UNDO 0x20000A
#define STB_TEXTEDIT_K_REDO 0x20000B
#define STB_TEXTEDIT_K_WORDLEFT 0x20000C
#define STB_TEXTEDIT_K_WORDRIGHT 0x20000D
#define STB_TEXTEDIT_K_PGUP 0x20000E
#define STB_TEXTEDIT_K_PGDOWN 0x20000F
#define STB_TEXTEDIT_K_SHIFT 0x400000
#define IMSTB_TEXTEDIT_IMPLEMENTATION
#define IMSTB_TEXTEDIT_memmove memmove
Functions
static bool InputTextFilterCharacter (ImGuiContext *ctx, unsigned int *p_char, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback, void *user_data, bool input_source_is_clipboard=false)
static ImVec2 InputTextCalcTextSize (ImGuiContext *ctx, const char *text_begin, const char *text_end_display, const char *text_end, const char **out_remaining=NULL, ImVec2 *out_offset=NULL, ImDrawTextFlags flags=0)
static int ShrinkWidthItemComparer (const void *lhs, const void *rhs)
static float CalcMaxPopupHeightFromItemCount (int items_count)
static const char * Items_ArrayGetter (void *data, int idx)
static const char * Items_SingleStringGetter (void *data, int idx)
static const char * ImGuiGetNameFromIndexOldToNewCallback (void *user_data, int idx)
template<typename T >
static int DataTypeCompareT (const T *lhs, const T *rhs)
template<typename T >
static bool DataTypeClampT (T *v, const T *v_min, const T *v_max)
static float GetMinimumStepAtDecimalPrecision (int decimal_precision)
const char * ImParseFormatFindStart (const char *fmt)
const char * ImParseFormatFindEnd (const char *fmt)
const char * ImParseFormatTrimDecorations (const char *fmt, char *buf, size_t buf_size)
void ImParseFormatSanitizeForPrinting (const char *fmt_in, char *fmt_out, size_t fmt_out_size)
const char * ImParseFormatSanitizeForScanning (const char *fmt_in, char *fmt_out, size_t fmt_out_size)
template<typename TYPE >
static const char * ImAtoi (const char *src, TYPE *output)
int ImParseFormatPrecision (const char *fmt, int default_precision)
static int ImStb::STB_TEXTEDIT_STRINGLEN (const ImGuiInputTextState *obj)
static char ImStb::STB_TEXTEDIT_GETCHAR (const ImGuiInputTextState *obj, int idx)
static float ImStb::STB_TEXTEDIT_GETWIDTH (ImGuiInputTextState *obj, int line_start_idx, int char_idx)
static void ImStb::STB_TEXTEDIT_LAYOUTROW (StbTexteditRow *r, ImGuiInputTextState *obj, int line_start_idx)
static int ImStb::IMSTB_TEXTEDIT_GETNEXTCHARINDEX_IMPL (ImGuiInputTextState *obj, int idx)
static int ImStb::IMSTB_TEXTEDIT_GETPREVCHARINDEX_IMPL (ImGuiInputTextState *obj, int idx)
static bool ImStb::ImCharIsSeparatorW (unsigned int c)
static int ImStb::is_word_boundary_from_right (ImGuiInputTextState *obj, int idx)
static int ImStb::is_word_boundary_from_left (ImGuiInputTextState *obj, int idx)
static int ImStb::STB_TEXTEDIT_MOVEWORDLEFT_IMPL (ImGuiInputTextState *obj, int idx)
static int ImStb::STB_TEXTEDIT_MOVEWORDRIGHT_MAC (ImGuiInputTextState *obj, int idx)
static int ImStb::STB_TEXTEDIT_MOVEWORDRIGHT_WIN (ImGuiInputTextState *obj, int idx)
static int ImStb::STB_TEXTEDIT_MOVEWORDRIGHT_IMPL (ImGuiInputTextState *obj, int idx)
static int ImStb::STB_TEXTEDIT_MOVELINESTART_IMPL (ImGuiInputTextState *obj, ImStb::STB_TexteditState *state, int cursor)
static int ImStb::STB_TEXTEDIT_MOVELINEEND_IMPL (ImGuiInputTextState *obj, ImStb::STB_TexteditState *state, int cursor)
static void ImStb::STB_TEXTEDIT_DELETECHARS (ImGuiInputTextState *obj, int pos, int n)
static int ImStb::STB_TEXTEDIT_INSERTCHARS (ImGuiInputTextState *obj, int pos, const char *new_text, int new_text_len)
static void ImStb::stb_textedit_replace (ImGuiInputTextState *str, STB_TexteditState *state, const char *text, int text_len)
static void InputTextReconcileUndoState (ImGuiInputTextState *state, const char *old_buf, int old_length, const char *new_buf, int new_length)
static int * ImLowerBound (int *in_begin, int *in_end, int v)
static int InputTextLineIndexBuild (ImGuiInputTextFlags flags, ImGuiTextIndex *line_index, const char *buf, const char *buf_end, float wrap_width, int max_output_buffer_size, const char **out_buf_end)
static ImVec2 InputTextLineIndexGetPosOffset (ImGuiContext &g, ImGuiInputTextState *state, ImGuiTextIndex *line_index, const char *buf, const char *buf_end, int cursor_n)
static void ColorEditRestoreH (const float *col, float *H)
static void ColorEditRestoreHS (const float *col, float *H, float *S, float *V)
static void RenderArrowsForVerticalBar (ImDrawList *draw_list, ImVec2 pos, ImVec2 half_sz, float bar_w, float alpha)
static void TreeNodeStoreStackData (ImGuiTreeNodeFlags flags, float x1)
static int ImStrimatchlen (const char *s1, const char *s1_end, const char *s2)
static void BoxSelectPreStartDrag (ImGuiID id, ImGuiSelectionUserData clicked_item)
static void BoxSelectActivateDrag (ImGuiBoxSelectState *bs, ImGuiWindow *window)
static void BoxSelectDeactivateDrag (ImGuiBoxSelectState *bs)
static void BoxSelectScrollWithMouseDrag (ImGuiBoxSelectState *bs, ImGuiWindow *window, const ImRect &inner_r)
static void DebugLogMultiSelectRequests (const char *function, const ImGuiMultiSelectIO *io)
static ImRect CalcScopeRect (ImGuiMultiSelectTempData *ms, ImGuiWindow *window)
static int PairComparerByValueInt (const void *lhs, const void *rhs)
static void ImGuiSelectionBasicStorage_BatchSetItemSelected (ImGuiSelectionBasicStorage *selection, ImGuiID id, bool selected, int size_before_amends, int selection_order)
static void ImGuiSelectionBasicStorage_BatchFinish (ImGuiSelectionBasicStorage *selection, bool selected, int size_before_amends)
static float Plot_ArrayGetter (void *data, int idx)
static bool IsRootOfOpenMenuSet ()
static void ImGui::TabBarLayout (ImGuiTabBar *tab_bar)
static ImU32 ImGui::TabBarCalcTabID (ImGuiTabBar *tab_bar, const char *label, ImGuiWindow *docked_window)
static float ImGui::TabBarCalcMaxTabWidth ()
static float ImGui::TabBarScrollClamp (ImGuiTabBar *tab_bar, float scrolling)
static void ImGui::TabBarScrollToTab (ImGuiTabBar *tab_bar, ImGuiID tab_id, ImGuiTabBarSection *sections)
static ImGuiTabItem * ImGui::TabBarScrollingButtons (ImGuiTabBar *tab_bar)
static ImGuiTabItem * ImGui::TabBarTabListPopupButton (ImGuiTabBar *tab_bar)
static int TabItemGetSectionIdx (const ImGuiTabItem *tab)
static int TabItemComparerBySection (const void *lhs, const void *rhs)
static int TabItemComparerByBeginOrder (const void *lhs, const void *rhs)
static ImGuiTabBar * GetTabBarFromTabBarRef (const ImGuiPtrOrIndex &ref)
static ImGuiPtrOrIndex GetTabBarRefFromTabBar (ImGuiTabBar *tab_bar)
static float TabBarCalcScrollableWidth (ImGuiTabBar *tab_bar, ImGuiTabBarSection *sections)
Variables
static const float DRAGDROP_HOLD_TO_OPEN_TIMER = 0.70f
static const float DRAG_MOUSE_THRESHOLD_FACTOR = 0.50f
static const signed char IM_S8_MIN = -128
static const signed char IM_S8_MAX = 127
static const unsigned char IM_U8_MIN = 0
static const unsigned char IM_U8_MAX = 0xFF
static const signed short IM_S16_MIN = -32768
static const signed short IM_S16_MAX = 32767
static const unsigned short IM_U16_MIN = 0
static const unsigned short IM_U16_MAX = 0xFFFF
static const ImS32 IM_S32_MIN = INT_MIN
static const ImS32 IM_S32_MAX = INT_MAX
static const ImU32 IM_U32_MIN = 0
static const ImU32 IM_U32_MAX = UINT_MAX
static const ImS64 IM_S64_MIN = -9223372036854775807LL - 1
static const ImS64 IM_S64_MAX = 9223372036854775807LL
static const ImU64 IM_U64_MIN = 0
static const ImU64 IM_U64_MAX = (2ULL * 9223372036854775807LL + 1)
static const ImU32 GDefaultRgbaColorMarkers [4]
static const ImGuiDataTypeInfo GDataTypeInfo []
static char ImStb::STB_TEXTEDIT_NEWLINE = '\n'
Macro Definition Documentation
IMGUI_DEFINE_MATH_OPERATORS
#define IMGUI_DEFINE_MATH_OPERATORS
Definition at line 40 of file imgui_widgets.cpp.
IMSTB_TEXTEDIT_GETNEXTCHARINDEX
#define IMSTB_TEXTEDIT_GETNEXTCHARINDEX IMSTB_TEXTEDIT_GETNEXTCHARINDEX_IMPL
Definition at line 4002 of file imgui_widgets.cpp.
IMSTB_TEXTEDIT_GETPREVCHARINDEX
#define IMSTB_TEXTEDIT_GETPREVCHARINDEX IMSTB_TEXTEDIT_GETPREVCHARINDEX_IMPL
Definition at line 4003 of file imgui_widgets.cpp.
IMSTB_TEXTEDIT_IMPLEMENTATION
#define IMSTB_TEXTEDIT_IMPLEMENTATION
Definition at line 4227 of file imgui_widgets.cpp.
IMSTB_TEXTEDIT_memmove
#define IMSTB_TEXTEDIT_memmove memmove
Definition at line 4228 of file imgui_widgets.cpp.
STB_TEXTEDIT_K_BACKSPACE
#define STB_TEXTEDIT_K_BACKSPACE 0x200009
Definition at line 4218 of file imgui_widgets.cpp.
STB_TEXTEDIT_K_DELETE
#define STB_TEXTEDIT_K_DELETE 0x200008
Definition at line 4217 of file imgui_widgets.cpp.
STB_TEXTEDIT_K_DOWN
#define STB_TEXTEDIT_K_DOWN 0x200003
Definition at line 4212 of file imgui_widgets.cpp.
STB_TEXTEDIT_K_LEFT
#define STB_TEXTEDIT_K_LEFT 0x200000
Definition at line 4209 of file imgui_widgets.cpp.
STB_TEXTEDIT_K_LINEEND
#define STB_TEXTEDIT_K_LINEEND 0x200005
Definition at line 4214 of file imgui_widgets.cpp.
STB_TEXTEDIT_K_LINESTART
#define STB_TEXTEDIT_K_LINESTART 0x200004
Definition at line 4213 of file imgui_widgets.cpp.
STB_TEXTEDIT_K_PGDOWN
#define STB_TEXTEDIT_K_PGDOWN 0x20000F
Definition at line 4224 of file imgui_widgets.cpp.
STB_TEXTEDIT_K_PGUP
#define STB_TEXTEDIT_K_PGUP 0x20000E
Definition at line 4223 of file imgui_widgets.cpp.
STB_TEXTEDIT_K_REDO
#define STB_TEXTEDIT_K_REDO 0x20000B
Definition at line 4220 of file imgui_widgets.cpp.
STB_TEXTEDIT_K_RIGHT
#define STB_TEXTEDIT_K_RIGHT 0x200001
Definition at line 4210 of file imgui_widgets.cpp.
STB_TEXTEDIT_K_SHIFT
#define STB_TEXTEDIT_K_SHIFT 0x400000
Definition at line 4225 of file imgui_widgets.cpp.
STB_TEXTEDIT_K_TEXTEND
#define STB_TEXTEDIT_K_TEXTEND 0x200007
Definition at line 4216 of file imgui_widgets.cpp.
STB_TEXTEDIT_K_TEXTSTART
#define STB_TEXTEDIT_K_TEXTSTART 0x200006
Definition at line 4215 of file imgui_widgets.cpp.
STB_TEXTEDIT_K_UNDO
#define STB_TEXTEDIT_K_UNDO 0x20000A
Definition at line 4219 of file imgui_widgets.cpp.
STB_TEXTEDIT_K_UP
#define STB_TEXTEDIT_K_UP 0x200002
Definition at line 4211 of file imgui_widgets.cpp.
STB_TEXTEDIT_K_WORDLEFT
#define STB_TEXTEDIT_K_WORDLEFT 0x20000C
Definition at line 4221 of file imgui_widgets.cpp.
STB_TEXTEDIT_K_WORDRIGHT
#define STB_TEXTEDIT_K_WORDRIGHT 0x20000D
Definition at line 4222 of file imgui_widgets.cpp.
STB_TEXTEDIT_MOVELINEEND
#define STB_TEXTEDIT_MOVELINEEND STB_TEXTEDIT_MOVELINEEND_IMPL
Definition at line 4162 of file imgui_widgets.cpp.
STB_TEXTEDIT_MOVELINESTART
#define STB_TEXTEDIT_MOVELINESTART STB_TEXTEDIT_MOVELINESTART_IMPL
Definition at line 4161 of file imgui_widgets.cpp.
STB_TEXTEDIT_MOVEWORDLEFT
#define STB_TEXTEDIT_MOVEWORDLEFT STB_TEXTEDIT_MOVEWORDLEFT_IMPL
Definition at line 4092 of file imgui_widgets.cpp.
STB_TEXTEDIT_MOVEWORDRIGHT
#define STB_TEXTEDIT_MOVEWORDRIGHT STB_TEXTEDIT_MOVEWORDRIGHT_IMPL
Definition at line 4093 of file imgui_widgets.cpp.
Function Documentation
BoxSelectActivateDrag()
static void BoxSelectActivateDrag (ImGuiBoxSelectState * bs, ImGuiWindow * window) static
Definition at line 7699 of file imgui_widgets.cpp.
References GImGui, ImGuiBoxSelectState::ID, IMGUI_DEBUG_LOG_SELECTION, ImGuiMod_Ctrl, ImGuiMod_Shift, ImGuiBoxSelectState::IsActive, ImGuiBoxSelectState::IsStartedFromVoid, ImGuiBoxSelectState::IsStarting, ImGuiBoxSelectState::KeyMods, ImGuiBoxSelectState::RequestClear, ImGui::SetActiveID(), ImGui::SetActiveIdUsingAllKeyboardKeys(), and ImGuiBoxSelectState::Window.
Referenced by ImGui::BeginBoxSelect().
BoxSelectDeactivateDrag()
static void BoxSelectDeactivateDrag (ImGuiBoxSelectState * bs) static
Definition at line 7712 of file imgui_widgets.cpp.
References ImGuiContext::ActiveId, ImGui::ClearActiveID(), GImGui, ImGuiBoxSelectState::ID, IMGUI_DEBUG_LOG_SELECTION, ImGuiBoxSelectState::IsActive, and ImGuiBoxSelectState::IsStarting.
Referenced by ImGui::BeginBoxSelect(), and ImGui::BeginMultiSelect().
BoxSelectPreStartDrag()
static void BoxSelectPreStartDrag (ImGuiID id, ImGuiSelectionUserData clicked_item) static
Definition at line 7686 of file imgui_widgets.cpp.
References ImGuiContext::BoxSelectState, ImGuiContext::CurrentWindow, ImGuiBoxSelectState::EndPosRel, GImGui, ImGuiBoxSelectState::ID, ImGuiSelectionUserData_Invalid, ImGuiContext::IO, ImGuiBoxSelectState::IsStartedFromVoid, ImGuiBoxSelectState::IsStartedSetNavIdOnce, ImGuiBoxSelectState::IsStarting, ImGuiIO::KeyMods, ImGuiBoxSelectState::KeyMods, ImGuiIO::MousePos, ImGuiBoxSelectState::ScrollAccum, ImGuiBoxSelectState::StartPosRel, and ImGui::WindowPosAbsToRel().
Referenced by ImGui::EndMultiSelect(), and ImGui::MultiSelectItemFooter().
BoxSelectScrollWithMouseDrag()
static void BoxSelectScrollWithMouseDrag (ImGuiBoxSelectState * bs, ImGuiWindow * window, const ImRect & inner_r) static
Definition at line 7724 of file imgui_widgets.cpp.
References ImGuiIO::DeltaTime, ImGuiContext::FontSize, GImGui, IM_ASSERT, ImAbs(), ImFloor(), ImLinearRemapClamp(), ImSign(), ImGuiContext::IO, ImRect::Max, ImRect::Min, ImGuiIO::MousePos, ImGuiWindow::Scroll, ImGuiBoxSelectState::ScrollAccum, ImGuiWindow::ScrollMax, ImGui::SetScrollX(), ImGui::SetScrollY(), and ImGuiBoxSelectState::Window.
Referenced by ImGui::EndBoxSelect().
CalcMaxPopupHeightFromItemCount()
static float CalcMaxPopupHeightFromItemCount (int items_count) static
Definition at line 1902 of file imgui_widgets.cpp.
References ImGuiContext::FontSize, GImGui, ImGuiStyle::ItemSpacing, ImGuiContext::Style, ImGuiStyle::WindowPadding, and ImVec2::y.
Referenced by ImGui::BeginComboPopup(), and ImGui::Combo().
CalcScopeRect()
static ImRect CalcScopeRect (ImGuiMultiSelectTempData * ms, ImGuiWindow * window) static
Definition at line 7849 of file imgui_widgets.cpp.
References ImGuiContext::CurrentTable, ImGuiWindowTempData::CursorMaxPos, ImGuiWindow::DC, ImGuiWindow::DecoInnerSizeX1, ImGuiWindow::DecoInnerSizeY1, ImGuiMultiSelectTempData::Flags, GImGui, ImGuiTable::HostClipRect, ImGuiMultiSelectFlags_ScopeRect, ImMax(), ImMin(), ImGuiWindow::InnerClipRect, ImRect::Max, ImRect::Min, and ImGuiMultiSelectTempData::ScopeRectMin.
Referenced by ImGui::BeginMultiSelect(), and ImGui::EndMultiSelect().
ColorEditRestoreH()
static void ColorEditRestoreH (const float * col, float * H) static
Definition at line 5702 of file imgui_widgets.cpp.
References ImGui::ColorConvertFloat4ToU32(), ImGuiContext::ColorEditCurrentID, ImGuiContext::ColorEditSavedColor, ImGuiContext::ColorEditSavedHue, ImGuiContext::ColorEditSavedID, GImGui, and IM_ASSERT.
Referenced by ImGui::ColorPicker4().
ColorEditRestoreHS()
static void ColorEditRestoreHS (const float * col, float * H, float * S, float * V) static
Definition at line 5713 of file imgui_widgets.cpp.
References ImGui::ColorConvertFloat4ToU32(), ImGuiContext::ColorEditCurrentID, ImGuiContext::ColorEditSavedColor, ImGuiContext::ColorEditSavedHue, ImGuiContext::ColorEditSavedID, ImGuiContext::ColorEditSavedSat, GImGui, and IM_ASSERT.
Referenced by ImGui::ColorEdit4(), and ImGui::ColorPicker4().
DataTypeClampT()
template<typename T > static bool DataTypeClampT (T * v, const T * v_min, const T * v_max) static
Definition at line 2429 of file imgui_widgets.cpp.
DataTypeCompareT()
template<typename T > static int DataTypeCompareT (const T * lhs, const T * rhs) static
Definition at line 2401 of file imgui_widgets.cpp.
DebugLogMultiSelectRequests()
static void DebugLogMultiSelectRequests (const char * function, const ImGuiMultiSelectIO * io) static
Definition at line 7838 of file imgui_widgets.cpp.
References GImGui, IM_PRId64, IM_PRIX64, IM_UNUSED, IMGUI_DEBUG_LOG_SELECTION, ImGuiSelectionRequestType_SetAll, ImGuiSelectionRequestType_SetRange, and ImGuiMultiSelectIO::Requests.
Referenced by ImGui::BeginMultiSelect(), and ImGui::EndMultiSelect().
GetMinimumStepAtDecimalPrecision()
static float GetMinimumStepAtDecimalPrecision (int decimal_precision) static
Definition at line 2463 of file imgui_widgets.cpp.
References IM_ARRAYSIZE, and ImPow().
GetTabBarFromTabBarRef()
static ImGuiTabBar * GetTabBarFromTabBarRef (const ImGuiPtrOrIndex & ref) static
Definition at line 9584 of file imgui_widgets.cpp.
References ImPool< T >::GetByIndex(), GImGui, ImGuiPtrOrIndex::Index, ImGuiPtrOrIndex::Ptr, and ImGuiContext::TabBars.
Referenced by ImGui::EndTabBar().
GetTabBarRefFromTabBar()
static ImGuiPtrOrIndex GetTabBarRefFromTabBar (ImGuiTabBar * tab_bar) static
Definition at line 9590 of file imgui_widgets.cpp.
References ImPool< T >::Contains(), ImPool< T >::GetIndex(), GImGui, and ImGuiContext::TabBars.
Referenced by ImGui::BeginTabBarEx().
ImAtoi()
template<typename TYPE > static const char * ImAtoi (const char * src, TYPE * output) static
Definition at line 3655 of file imgui_widgets.cpp.
ImGuiGetNameFromIndexOldToNewCallback()
static const char * ImGuiGetNameFromIndexOldToNewCallback (void * user_data, int idx) static
Definition at line 2209 of file imgui_widgets.cpp.
ImGuiSelectionBasicStorage_BatchFinish()
static void ImGuiSelectionBasicStorage_BatchFinish (ImGuiSelectionBasicStorage * selection, bool selected, int size_before_amends) static
Definition at line 8499 of file imgui_widgets.cpp.
References ImGuiSelectionBasicStorage::_Storage, ImGuiStorage::BuildSortByKey(), and ImGuiSelectionBasicStorage::Size.
Referenced by ImGuiSelectionBasicStorage::ApplyRequests().
ImGuiSelectionBasicStorage_BatchSetItemSelected()
static void ImGuiSelectionBasicStorage_BatchSetItemSelected (ImGuiSelectionBasicStorage * selection, ImGuiID id, bool selected, int size_before_amends, int selection_order) static
Definition at line 8485 of file imgui_widgets.cpp.
References ImGuiSelectionBasicStorage::_Storage, ImVector< T >::Data, ImGuiStorage::Data, ImLowerBound(), ImGuiStoragePair::key, ImVector< T >::push_back(), ImGuiSelectionBasicStorage::Size, and ImGuiStoragePair::val_i.
Referenced by ImGuiSelectionBasicStorage::ApplyRequests().
ImLowerBound()
static int * ImLowerBound (int * in_begin, int * in_end, int v) static
Definition at line 4557 of file imgui_widgets.cpp.
Referenced by ImGuiSelectionBasicStorage_BatchSetItemSelected(), and InputTextLineIndexGetPosOffset().
ImParseFormatFindEnd()
const char * ImParseFormatFindEnd (const char * fmt)
Definition at line 3582 of file imgui_widgets.cpp.
Referenced by ImParseFormatSanitizeForPrinting(), ImParseFormatSanitizeForScanning(), and ImParseFormatTrimDecorations().
ImParseFormatFindStart()
const char * ImParseFormatFindStart (const char * fmt)
Definition at line 3569 of file imgui_widgets.cpp.
Referenced by ImParseFormatPrecision(), and ImParseFormatTrimDecorations().
ImParseFormatPrecision()
int ImParseFormatPrecision (const char * fmt, int default_precision)
Definition at line 3669 of file imgui_widgets.cpp.
References ImParseFormatFindStart().
ImParseFormatSanitizeForPrinting()
void ImParseFormatSanitizeForPrinting (const char * fmt_in, char * fmt_out, size_t fmt_out_size)
Definition at line 3619 of file imgui_widgets.cpp.
References IM_ASSERT, IM_UNUSED, and ImParseFormatFindEnd().
ImParseFormatSanitizeForScanning()
const char * ImParseFormatSanitizeForScanning (const char * fmt_in, char * fmt_out, size_t fmt_out_size)
Definition at line 3634 of file imgui_widgets.cpp.
References IM_ASSERT, IM_UNUSED, and ImParseFormatFindEnd().
Referenced by ImGui::DataTypeApplyFromText().
ImParseFormatTrimDecorations()
const char * ImParseFormatTrimDecorations (const char * fmt, char * buf, size_t buf_size)
Definition at line 3604 of file imgui_widgets.cpp.
References ImMin(), ImParseFormatFindEnd(), ImParseFormatFindStart(), and ImStrncpy().
Referenced by ImGui::TempInputScalar().
ImStrimatchlen()
static int ImStrimatchlen (const char * s1, const char * s1_end, const char * s2) static
Definition at line 7588 of file imgui_widgets.cpp.
References ImToUpper().
Referenced by ImGui::TypingSelectFindBestLeadingMatch(), and ImGui::TypingSelectFindNextSingleCharMatch().
InputTextCalcTextSize()
static ImVec2 InputTextCalcTextSize (ImGuiContext * ctx, const char * text_begin, const char * text_end_display, const char * text_end, const char ** out_remaining = NULL, ImVec2 * out_offset = NULL, ImDrawTextFlags flags = 0) static
Definition at line 3970 of file imgui_widgets.cpp.
References ImGuiContext::Font, ImGuiContext::FontSize, IM_ASSERT, ImFontCalcTextSizeEx(), ImGuiContext::InputTextState, and ImGuiInputTextState::WrapWidth.
Referenced by InputTextLineIndexGetPosOffset(), and ImStb::STB_TEXTEDIT_LAYOUTROW().
InputTextFilterCharacter()
static bool InputTextFilterCharacter (ImGuiContext * ctx, unsigned int * p_char, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback, void * user_data, bool input_source_is_clipboard = false) static
Definition at line 4400 of file imgui_widgets.cpp.
References ImGuiInputTextCallbackData::Ctx, ImGuiInputTextCallbackData::EventChar, ImGuiInputTextCallbackData::EventFlag, ImGuiInputTextCallbackData::Flags, GImGui, IM_UNICODE_CODEPOINT_MAX, ImCharIsBlankW(), ImGuiInputTextFlags_AllowTabInput, ImGuiInputTextFlags_CallbackCharFilter, ImGuiInputTextFlags_CharsDecimal, ImGuiInputTextFlags_CharsHexadecimal, ImGuiInputTextFlags_CharsNoBlank, ImGuiInputTextFlags_CharsScientific, ImGuiInputTextFlags_CharsUppercase, ImGuiInputTextFlags_LocalizeDecimalPoint, ImGuiInputTextFlags_Multiline, ImGuiPlatformIO::Platform_LocaleDecimalPoint, ImGuiContext::PlatformIO, and ImGuiInputTextCallbackData::UserData.
Referenced by ImGui::InputTextEx().
InputTextLineIndexBuild()
static int InputTextLineIndexBuild (ImGuiInputTextFlags flags, ImGuiTextIndex * line_index, const char * buf, const char * buf_end, float wrap_width, int max_output_buffer_size, const char ** out_buf_end) static
Definition at line 4579 of file imgui_widgets.cpp.
References ImGuiContext::Font, ImGuiContext::FontSize, GImGui, ImDrawTextFlags_WrapKeepBlanks, ImFontCalcWordWrapPositionEx(), ImGuiInputTextFlags_WordWrap, ImMemchr, ImGuiTextIndex::Offsets, and ImVector< T >::push_back().
Referenced by ImGui::InputTextEx().
InputTextLineIndexGetPosOffset()
static ImVec2 InputTextLineIndexGetPosOffset (ImGuiContext & g, ImGuiInputTextState * state, ImGuiTextIndex * line_index, const char * buf, const char * buf_end, int cursor_n) static
Definition at line 4630 of file imgui_widgets.cpp.
References ImVector< T >::begin(), ImVector< T >::end(), ImGuiContext::FontSize, ImGuiTextIndex::get_line_begin(), ImDrawTextFlags_WrapKeepBlanks, ImGuiDir_Right, ImLowerBound(), ImVector< T >::index_from_ptr(), InputTextCalcTextSize(), ImGuiInputTextState::LastMoveDirectionLR, ImGuiTextIndex::Offsets, ImGuiInputTextState::WrapWidth, and ImVec2::x.
Referenced by ImGui::InputTextEx().
InputTextReconcileUndoState()
static void InputTextReconcileUndoState (ImGuiInputTextState * state, const char * old_buf, int old_length, const char * new_buf, int new_length) static
Definition at line 4509 of file imgui_widgets.cpp.
References ImMin(), IMSTB_TEXTEDIT_CHARTYPE, and ImGuiInputTextState::Stb.
Referenced by ImGui::InputTextEx().
IsRootOfOpenMenuSet()
static bool IsRootOfOpenMenuSet () static
Definition at line 9154 of file imgui_widgets.cpp.
References ImGuiContext::BeginPopupStack, ImGuiContext::CurrentWindow, ImGuiWindow::DC, ImGuiWindow::Flags, GImGui, ImGuiWindowFlags_ChildMenu, ImGui::IsWindowChildOf(), ImGuiWindowTempData::NavLayerCurrent, ImGuiContext::OpenPopupStack, ImGuiPopupData::ParentNavLayer, ImVector< T >::Size, and ImGuiPopupData::Window.
Referenced by ImGui::BeginMenuEx(), and ImGui::MenuItemEx().
Items_ArrayGetter()
static const char * Items_ArrayGetter (void * data, int idx) static
Definition at line 2115 of file imgui_widgets.cpp.
Referenced by ImGui::Combo(), and ImGui::ListBox().
Items_SingleStringGetter()
static const char * Items_SingleStringGetter (void * data, int idx) static
Definition at line 2122 of file imgui_widgets.cpp.
References ImStrlen.
Referenced by ImGui::Combo().
PairComparerByValueInt()
static int PairComparerByValueInt (const void * lhs, const void * rhs) static
Definition at line 8448 of file imgui_widgets.cpp.
Referenced by ImGuiSelectionBasicStorage::GetNextSelectedItem().
Plot_ArrayGetter()
static float Plot_ArrayGetter (void * data, int idx) static
Definition at line 8860 of file imgui_widgets.cpp.
References ImGuiPlotArrayGetterData::Stride, and ImGuiPlotArrayGetterData::Values.
Referenced by ImGui::PlotHistogram(), and ImGui::PlotLines().
RenderArrowsForVerticalBar()
static void RenderArrowsForVerticalBar (ImDrawList * draw_list, ImVec2 pos, ImVec2 half_sz, float bar_w, float alpha) static
Definition at line 5996 of file imgui_widgets.cpp.
References IM_COL32, IM_F32_TO_INT8_SAT, ImGuiDir_Left, ImGuiDir_Right, ImGui::RenderArrowPointingAt(), ImVec2::x, and ImVec2::y.
Referenced by ImGui::ColorPicker4().
ShrinkWidthItemComparer()
static int ShrinkWidthItemComparer (const void * lhs, const void * rhs) static
Definition at line 1834 of file imgui_widgets.cpp.
References ImGuiShrinkWidthItem::Index, and ImGuiShrinkWidthItem::Width.
Referenced by ImGui::ShrinkWidths().
TabBarCalcScrollableWidth()
static float TabBarCalcScrollableWidth (ImGuiTabBar * tab_bar, ImGuiTabBarSection * sections) static
Definition at line 9731 of file imgui_widgets.cpp.
References ImGuiTabBar::BarRect, ImRect::GetWidth(), ImGuiTabBarSection::Spacing, and ImGuiTabBarSection::Width.
Referenced by ImGui::TabBarLayout(), and ImGui::TabBarScrollToTab().
TabItemComparerByBeginOrder()
static int TabItemComparerByBeginOrder (const void * lhs, const void * rhs) static
Definition at line 9577 of file imgui_widgets.cpp.
References ImGuiTabItem::BeginOrder.
Referenced by ImGui::BeginTabBarEx().
TabItemComparerBySection()
static int TabItemComparerBySection (const void * lhs, const void * rhs) static
Definition at line 9566 of file imgui_widgets.cpp.
References ImGuiTabItem::IndexDuringLayout, and TabItemGetSectionIdx().
Referenced by ImGui::TabBarLayout().
TabItemGetSectionIdx()
static int TabItemGetSectionIdx (const ImGuiTabItem * tab) inline static
Definition at line 9561 of file imgui_widgets.cpp.
References ImGuiTabItem::Flags, ImGuiTabItemFlags_Leading, and ImGuiTabItemFlags_Trailing.
Referenced by ImGui::TabBarLayout(), and TabItemComparerBySection().
TreeNodeStoreStackData()
static void TreeNodeStoreStackData (ImGuiTreeNodeFlags flags, float x1) static
Definition at line 6782 of file imgui_widgets.cpp.
References ImGuiTable::CurrentColumn, ImGuiContext::CurrentTable, ImGuiContext::CurrentWindow, ImVector< T >::Data, ImGuiWindow::DC, ImGuiTreeNodeStackData::DrawLinesTableColumn, ImGuiTreeNodeStackData::DrawLinesToNodesY2, ImGuiTreeNodeStackData::DrawLinesX1, ImGuiContext::FontSize, ImGuiStyle::FramePadding, GImGui, ImGuiLastItemData::ID, ImGuiTreeNodeStackData::ID, ImGuiTreeNodeFlags_DrawLinesFull, ImGuiTreeNodeFlags_DrawLinesToNodes, ImGuiLastItemData::ItemFlags, ImGuiTreeNodeStackData::ItemFlags, ImGuiContext::LastItemData, ImGuiLastItemData::NavRect, ImGuiTreeNodeStackData::NavRect, ImVector< T >::resize(), ImVector< T >::Size, ImGuiContext::Style, ImGuiWindowTempData::TreeDepth, ImGuiTreeNodeStackData::TreeFlags, ImGuiWindowTempData::TreeHasStackDataDepthMask, ImGuiContext::TreeNodeStack, ImGuiWindowTempData::TreeRecordsClippedNodesY2Mask, and ImVec2::x.
Referenced by ImGui::TreeNodeBehavior().
Variable Documentation
DRAG_MOUSE_THRESHOLD_FACTOR
const float DRAG_MOUSE_THRESHOLD_FACTOR = 0.50f static
Definition at line 103 of file imgui_widgets.cpp.
Referenced by ImGui::DragScalar().
DRAGDROP_HOLD_TO_OPEN_TIMER
const float DRAGDROP_HOLD_TO_OPEN_TIMER = 0.70f static
Definition at line 102 of file imgui_widgets.cpp.
Referenced by ImGui::ButtonBehavior().
GDataTypeInfo
const ImGuiDataTypeInfo GDataTypeInfo[] static
Initial value:
=
{
    { sizeof(char),             "S8",   "%d",   "%d"    },
    { sizeof(unsigned char),    "U8",   "%u",   "%u"    },
    { sizeof(short),            "S16",  "%d",   "%d"    },
    { sizeof(unsigned short),   "U16",  "%u",   "%u"    },
    { sizeof(int),              "S32",  "%d",   "%d"    },
    { sizeof(unsigned int),     "U32",  "%u",   "%u"    },
    { sizeof(ImS64),            "S64",  "%lld", "%lld"  },
    { sizeof(ImU64),            "U64",  "%llu", "%llu"  },
    { sizeof(float),            "float", "%.3f","%f"    },
    { sizeof(double),           "double","%f",  "%lf"   },
    { sizeof(bool),             "bool", "%d",   "%d"    },
    { 0,                        "char*","%s",   "%s"    },
}
Definition at line 2248 of file imgui_widgets.cpp.
Referenced by ImGui::DataTypeGetInfo(), ImGui::DragScalarN(), ImGui::InputScalarN(), and ImGui::SliderScalarN().
GDefaultRgbaColorMarkers
const ImU32 GDefaultRgbaColorMarkers[4] static
Initial value:
=
{
    (((ImU32)( 255 )<< 24 ) | ((ImU32)( 20 )<< 16 ) | ((ImU32)( 20 )<< 8 ) | ((ImU32)( 240 )<< 0 )), (((ImU32)( 255 )<< 24 ) | ((ImU32)( 20 )<< 16 ) | ((ImU32)( 240 )<< 8 ) | ((ImU32)( 20 )<< 0 )), (((ImU32)( 255 )<< 24 ) | ((ImU32)( 240 )<< 16 ) | ((ImU32)( 20 )<< 8 ) | ((ImU32)( 20 )<< 0 )), (((ImU32)( 255 )<< 24 ) | ((ImU32)( 140 )<< 16 ) | ((ImU32)( 140 )<< 8 ) | ((ImU32)( 140 )<< 0 ))
}
Definition at line 2243 of file imgui_widgets.cpp.
Referenced by ImGui::ColorEdit4(), ImGui::DragScalarN(), and ImGui::SliderScalarN().
IM_S16_MAX
const signed short IM_S16_MAX = 32767 static
Definition at line 111 of file imgui_widgets.cpp.
Referenced by ImGui::DataTypeApplyFromText(), ImGui::DataTypeApplyOp(), and ImGui::DragBehavior().
IM_S16_MIN
const signed short IM_S16_MIN = -32768 static
Definition at line 110 of file imgui_widgets.cpp.
Referenced by ImGui::DataTypeApplyFromText(), ImGui::DataTypeApplyOp(), and ImGui::DragBehavior().
IM_S32_MAX
const ImS32 IM_S32_MAX = INT_MAX static
Definition at line 115 of file imgui_widgets.cpp.
Referenced by ImGui::DataTypeApplyOp(), ImGui::DragBehavior(), and ImGui::SliderBehavior().
IM_S32_MIN
const ImS32 IM_S32_MIN = INT_MIN static
Definition at line 114 of file imgui_widgets.cpp.
Referenced by ImGui::DataTypeApplyOp(), ImGui::DragBehavior(), and ImGui::SliderBehavior().
IM_S64_MAX
const ImS64 IM_S64_MAX = 9223372036854775807LL static
Definition at line 123 of file imgui_widgets.cpp.
Referenced by ImGui::DataTypeApplyOp(), ImGui::DragBehavior(), and ImGui::SliderBehavior().
IM_S64_MIN
const ImS64 IM_S64_MIN = -9223372036854775807LL - 1 static
Definition at line 122 of file imgui_widgets.cpp.
Referenced by ImGui::DataTypeApplyOp(), ImGui::DragBehavior(), and ImGui::SliderBehavior().
IM_S8_MAX
const signed char IM_S8_MAX = 127 static
Definition at line 107 of file imgui_widgets.cpp.
Referenced by ImGui::DataTypeApplyFromText(), ImGui::DataTypeApplyOp(), and ImGui::DragBehavior().
IM_S8_MIN
const signed char IM_S8_MIN = -128 static
Definition at line 106 of file imgui_widgets.cpp.
Referenced by ImGui::DataTypeApplyFromText(), ImGui::DataTypeApplyOp(), and ImGui::DragBehavior().
IM_U16_MAX
const unsigned short IM_U16_MAX = 0xFFFF static
Definition at line 113 of file imgui_widgets.cpp.
Referenced by ImGui::DataTypeApplyFromText(), ImGui::DataTypeApplyOp(), and ImGui::DragBehavior().
IM_U16_MIN
const unsigned short IM_U16_MIN = 0 static
Definition at line 112 of file imgui_widgets.cpp.
Referenced by ImGui::DataTypeApplyFromText(), ImGui::DataTypeApplyOp(), and ImGui::DragBehavior().
IM_U32_MAX
const ImU32 IM_U32_MAX = UINT_MAX static
Definition at line 117 of file imgui_widgets.cpp.
Referenced by ImGui::DataTypeApplyOp(), ImGui::DragBehavior(), and ImGui::SliderBehavior().
IM_U32_MIN
const ImU32 IM_U32_MIN = 0 static
Definition at line 116 of file imgui_widgets.cpp.
Referenced by ImGui::DataTypeApplyOp(), and ImGui::DragBehavior().
IM_U64_MAX
const ImU64 IM_U64_MAX = (2ULL * 9223372036854775807LL + 1) static
Definition at line 129 of file imgui_widgets.cpp.
Referenced by ImGui::DataTypeApplyOp(), ImGui::DragBehavior(), and ImGui::SliderBehavior().
IM_U64_MIN
const ImU64 IM_U64_MIN = 0 static
Definition at line 125 of file imgui_widgets.cpp.
Referenced by ImGui::DataTypeApplyOp(), and ImGui::DragBehavior().
IM_U8_MAX
const unsigned char IM_U8_MAX = 0xFF static
Definition at line 109 of file imgui_widgets.cpp.
Referenced by ImGui::DataTypeApplyFromText(), ImGui::DataTypeApplyOp(), and ImGui::DragBehavior().
IM_U8_MIN
const unsigned char IM_U8_MIN = 0 static
Definition at line 108 of file imgui_widgets.cpp.
Referenced by ImGui::DataTypeApplyFromText(), ImGui::DataTypeApplyOp(), and ImGui::DragBehavior().