SignalProcessing: examples/imgui/backends/imgui_impl_sdl2.h File Reference
imgui_impl_sdl2.h File Reference
#include "imgui.h"
Typedefs
typedef union SDL_Event SDL_Event
Enumerations
enum ImGui_ImplSDL2_GamepadMode { ImGui_ImplSDL2_GamepadMode_AutoFirst , ImGui_ImplSDL2_GamepadMode_AutoAll , ImGui_ImplSDL2_GamepadMode_Manual }
Functions
IMGUI_IMPL_API bool ImGui_ImplSDL2_InitForOpenGL (SDL_Window *window, void *sdl_gl_context)
IMGUI_IMPL_API bool ImGui_ImplSDL2_InitForVulkan (SDL_Window *window)
IMGUI_IMPL_API bool ImGui_ImplSDL2_InitForD3D (SDL_Window *window)
IMGUI_IMPL_API bool ImGui_ImplSDL2_InitForMetal (SDL_Window *window)
IMGUI_IMPL_API bool ImGui_ImplSDL2_InitForSDLRenderer (SDL_Window *window, SDL_Renderer *renderer)
IMGUI_IMPL_API bool ImGui_ImplSDL2_InitForOther (SDL_Window *window)
IMGUI_IMPL_API void ImGui_ImplSDL2_Shutdown ()
IMGUI_IMPL_API void ImGui_ImplSDL2_NewFrame ()
IMGUI_IMPL_API bool ImGui_ImplSDL2_ProcessEvent (const SDL_Event *event)
IMGUI_IMPL_API float ImGui_ImplSDL2_GetContentScaleForWindow (SDL_Window *window)
IMGUI_IMPL_API float ImGui_ImplSDL2_GetContentScaleForDisplay (int display_index)
IMGUI_IMPL_API void ImGui_ImplSDL2_SetGamepadMode (ImGui_ImplSDL2_GamepadMode mode, struct _SDL_GameController **manual_gamepads_array=nullptr, int manual_gamepads_count=-1)
Typedef Documentation
SDL_Event
typedef union SDL_Event SDL_Event
Definition at line 28 of file imgui_impl_sdl2.h.
Enumeration Type Documentation
ImGui_ImplSDL2_GamepadMode
enum ImGui_ImplSDL2_GamepadMode
Enumerator
ImGui_ImplSDL2_GamepadMode_AutoFirst
ImGui_ImplSDL2_GamepadMode_AutoAll
ImGui_ImplSDL2_GamepadMode_Manual
Definition at line 47 of file imgui_impl_sdl2.h.
Function Documentation
ImGui_ImplSDL2_GetContentScaleForDisplay()
IMGUI_IMPL_API float ImGui_ImplSDL2_GetContentScaleForDisplay (int display_index)
Definition at line 731 of file imgui_impl_sdl2.cpp.
References IM_UNUSED.
Referenced by ImGui_ImplSDL2_GetContentScaleForWindow(), and main().
ImGui_ImplSDL2_GetContentScaleForWindow()
IMGUI_IMPL_API float ImGui_ImplSDL2_GetContentScaleForWindow (SDL_Window * window)
Definition at line 726 of file imgui_impl_sdl2.cpp.
References ImGui_ImplSDL2_GetContentScaleForDisplay().
ImGui_ImplSDL2_InitForD3D()
IMGUI_IMPL_API bool ImGui_ImplSDL2_InitForD3D (SDL_Window * window)
Definition at line 604 of file imgui_impl_sdl2.cpp.
References IM_ASSERT, and ImGui_ImplSDL2_Init().
Referenced by main().
ImGui_ImplSDL2_InitForMetal()
IMGUI_IMPL_API bool ImGui_ImplSDL2_InitForMetal (SDL_Window * window)
Definition at line 612 of file imgui_impl_sdl2.cpp.
References ImGui_ImplSDL2_Init().
ImGui_ImplSDL2_InitForOpenGL()
IMGUI_IMPL_API bool ImGui_ImplSDL2_InitForOpenGL (SDL_Window * window, void * sdl_gl_context)
Definition at line 591 of file imgui_impl_sdl2.cpp.
References ImGui_ImplSDL2_Init().
Referenced by main().
ImGui_ImplSDL2_InitForOther()
IMGUI_IMPL_API bool ImGui_ImplSDL2_InitForOther (SDL_Window * window)
Definition at line 622 of file imgui_impl_sdl2.cpp.
References ImGui_ImplSDL2_Init().
Referenced by main().
ImGui_ImplSDL2_InitForSDLRenderer()
IMGUI_IMPL_API bool ImGui_ImplSDL2_InitForSDLRenderer (SDL_Window * window, SDL_Renderer * renderer)
Definition at line 617 of file imgui_impl_sdl2.cpp.
References ImGui_ImplSDL2_Init().
Referenced by main().
ImGui_ImplSDL2_InitForVulkan()
IMGUI_IMPL_API bool ImGui_ImplSDL2_InitForVulkan (SDL_Window * window)
Definition at line 596 of file imgui_impl_sdl2.cpp.
References IM_ASSERT, and ImGui_ImplSDL2_Init().
Referenced by main().
ImGui_ImplSDL2_NewFrame()
IMGUI_IMPL_API void ImGui_ImplSDL2_NewFrame ()
Definition at line 870 of file imgui_impl_sdl2.cpp.
References ImGuiIO::AddMousePosEvent(), ImGuiIO::DeltaTime, ImGuiIO::DisplayFramebufferScale, ImGuiIO::DisplaySize, frequency, ImGui::GetFrameCount(), ImGui::GetIO(), IM_ASSERT, ImGui_ImplSDL2_GetBackendData(), ImGui_ImplSDL2_GetWindowSizeAndFramebufferScale(), ImGui_ImplSDL2_UpdateGamepads(), ImGui_ImplSDL2_UpdateMouseCursor(), ImGui_ImplSDL2_UpdateMouseData(), ImGui_ImplSDL2_Data::MouseButtonsDown, ImGui_ImplSDL2_Data::MouseLastLeaveFrame, ImGui_ImplSDL2_Data::MouseWindowID, ImGui_ImplSDL2_Data::Renderer, ImGui_ImplSDL2_Data::Time, and ImGui_ImplSDL2_Data::Window.
Referenced by main().
ImGui_ImplSDL2_ProcessEvent()
IMGUI_IMPL_API bool ImGui_ImplSDL2_ProcessEvent (const SDL_Event * event)
Definition at line 372 of file imgui_impl_sdl2.cpp.
References ImGuiIO::AddFocusEvent(), ImGuiIO::AddInputCharactersUTF8(), ImGuiIO::AddKeyEvent(), ImGuiIO::AddMouseButtonEvent(), ImGuiIO::AddMousePosEvent(), ImGuiIO::AddMouseSourceEvent(), ImGuiIO::AddMouseWheelEvent(), ImGui::GetFrameCount(), ImGui::GetIO(), IM_ASSERT, ImGui_ImplSDL2_GetBackendData(), ImGui_ImplSDL2_GetViewportForWindowID(), ImGui_ImplSDL2_KeyEventToImGuiKey(), ImGui_ImplSDL2_UpdateKeyModifiers(), ImGuiMouseSource_Mouse, ImGuiMouseSource_TouchScreen, ImGui_ImplSDL2_Data::MouseButtonsDown, ImGui_ImplSDL2_Data::MouseLastLeaveFrame, ImGui_ImplSDL2_Data::MouseWindowID, ImGuiIO::SetKeyEventNativeData(), ImGui_ImplSDL2_Data::WantUpdateGamepadsList, ImVec2::x, and ImVec2::y.
Referenced by main().
ImGui_ImplSDL2_SetGamepadMode()
IMGUI_IMPL_API void ImGui_ImplSDL2_SetGamepadMode (ImGui_ImplSDL2_GamepadMode mode, struct _SDL_GameController ** manual_gamepads_array = nullptr, int manual_gamepads_count = -1)
Definition at line 756 of file imgui_impl_sdl2.cpp.
References ImGui_ImplSDL2_Data::GamepadMode, ImGui_ImplSDL2_Data::Gamepads, IM_ASSERT, ImGui_ImplSDL2_CloseGamepads(), ImGui_ImplSDL2_GamepadMode_Manual, ImGui_ImplSDL2_GetBackendData(), ImVector< T >::push_back(), and ImGui_ImplSDL2_Data::WantUpdateGamepadsList.
ImGui_ImplSDL2_Shutdown()
IMGUI_IMPL_API void ImGui_ImplSDL2_Shutdown ()
Definition at line 629 of file imgui_impl_sdl2.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendPlatformName, ImGuiIO::BackendPlatformUserData, ImGuiPlatformIO::ClearPlatformHandlers(), ImGui_ImplSDL2_Data::ClipboardTextData, ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplSDL2_CloseGamepads(), ImGui_ImplSDL2_GetBackendData(), ImGuiBackendFlags_HasGamepad, ImGuiBackendFlags_HasMouseCursors, ImGuiBackendFlags_HasSetMousePos, ImGuiMouseCursor_COUNT, and ImGui_ImplSDL2_Data::MouseCursors.
Referenced by main().