SignalProcessing: examples/imgui/examples/example_android_opengl3/main.cpp File Reference
main.cpp File Reference
#include "imgui.h"
#include "imgui_impl_android.h"
#include "imgui_impl_opengl3.h"
#include <android/log.h>
#include <android_native_app_glue.h>
#include <android/asset_manager.h>
#include <EGL/egl.h>
#include <GLES3/gl3.h>
#include <string>
Functions
static void Init (struct android_app *app)
static void Shutdown ()
static void MainLoopStep ()
static int ShowSoftKeyboardInput ()
static int PollUnicodeChars ()
static int GetAssetData (const char *filename, void **out_data)
static void handleAppCmd (struct android_app *app, int32_t appCmd)
static int32_t handleInputEvent (struct android_app *app, AInputEvent *inputEvent)
void android_main (struct android_app *app)
Variables
static EGLDisplay g_EglDisplay = EGL_NO_DISPLAY
static EGLSurface g_EglSurface = EGL_NO_SURFACE
static EGLContext g_EglContext = EGL_NO_CONTEXT
static struct android_app * g_App = nullptr
static bool g_Initialized = false
static char g_LogTag [] = "ImGuiExample"
static std::string g_IniFilename = ""
Function Documentation
android_main()
void android_main (struct android_app * app)
Definition at line 60 of file main.cpp.
References g_Initialized, handleAppCmd(), handleInputEvent(), MainLoopStep(), and Shutdown().
GetAssetData()
static int GetAssetData (const char * filename, void ** out_data) static
Definition at line 369 of file main.cpp.
References g_App, IM_ALLOC, and IM_ASSERT.
handleAppCmd()
static void handleAppCmd (struct android_app * app, int32_t appCmd) static
Definition at line 37 of file main.cpp.
References Init(), and Shutdown().
Referenced by android_main().
handleInputEvent()
static int32_t handleInputEvent (struct android_app * app, AInputEvent * inputEvent) static
Definition at line 55 of file main.cpp.
References ImGui_ImplAndroid_HandleInputEvent().
Referenced by android_main().
Init()
void Init (struct android_app * app) static
Definition at line 94 of file main.cpp.
References ImFontAtlas::AddFontDefault(), ImGui::CreateContext(), ImGuiIO::Fonts, g_App, g_EglContext, g_EglDisplay, g_EglSurface, g_IniFilename, g_Initialized, g_LogTag, ImGui::GetIO(), ImGui::GetStyle(), IMGUI_CHECKVERSION, ImGui_ImplAndroid_Init(), ImGui_ImplOpenGL3_Init(), ImGuiIO::IniFilename, ImGuiStyle::ScaleAllSizes(), ImFontConfig::SizePixels, and ImGui::StyleColorsDark().
Referenced by handleAppCmd().
MainLoopStep()
void MainLoopStep () static
Definition at line 193 of file main.cpp.
References ImGui::Begin(), ImGui::Button(), ImGui::Checkbox(), clear_color, ImGui::ColorEdit3(), ImGuiIO::DisplaySize, ImGui::End(), ImGuiIO::Framerate, g_EglDisplay, g_EglSurface, ImGui::GetDrawData(), ImGui::GetIO(), GL_COLOR_BUFFER_BIT, glClear, glClearColor, glViewport, ImGui_ImplAndroid_NewFrame(), ImGui_ImplOpenGL3_NewFrame(), ImGui_ImplOpenGL3_RenderDrawData(), ImGui::NewFrame(), PollUnicodeChars(), ImGui::Render(), ImGui::SameLine(), show_another_window, show_demo_window, ImGui::ShowDemoWindow(), ShowSoftKeyboardInput(), ImGui::SliderFloat(), ImGui::Text(), ImVec4::w, ImGuiIO::WantTextInput, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by android_main(), and main().
PollUnicodeChars()
static int PollUnicodeChars () static
Definition at line 334 of file main.cpp.
References ImGuiIO::AddInputCharacter(), g_App, and ImGui::GetIO().
Referenced by MainLoopStep().
ShowSoftKeyboardInput()
static int ShowSoftKeyboardInput () static
Definition at line 301 of file main.cpp.
References g_App.
Referenced by MainLoopStep().
Shutdown()
void Shutdown () static
Definition at line 266 of file main.cpp.
References ImGui::DestroyContext(), g_App, g_EglContext, g_EglDisplay, g_EglSurface, g_Initialized, ImGui_ImplAndroid_Shutdown(), and ImGui_ImplOpenGL3_Shutdown().
Referenced by android_main(), ImGui::DestroyContext(), and handleAppCmd().
Variable Documentation
g_App
struct android_app* g_App = nullptr static
Definition at line 23 of file main.cpp.
Referenced by GetAssetData(), Init(), PollUnicodeChars(), ShowSoftKeyboardInput(), and Shutdown().
g_EglContext
EGLContext g_EglContext = EGL_NO_CONTEXT static
Definition at line 22 of file main.cpp.
Referenced by Init(), and Shutdown().
g_EglDisplay
EGLDisplay g_EglDisplay = EGL_NO_DISPLAY static
Definition at line 20 of file main.cpp.
Referenced by Init(), MainLoopStep(), and Shutdown().
g_EglSurface
EGLSurface g_EglSurface = EGL_NO_SURFACE static
Definition at line 21 of file main.cpp.
Referenced by Init(), MainLoopStep(), and Shutdown().
g_IniFilename
std::string g_IniFilename = "" static
Definition at line 26 of file main.cpp.
Referenced by Init().
g_Initialized
bool g_Initialized = false static
Definition at line 24 of file main.cpp.
Referenced by android_main(), Init(), and Shutdown().
g_LogTag
char g_LogTag[] = "ImGuiExample" static
Definition at line 25 of file main.cpp.
Referenced by Init().