SignalProcessing: examples/imgui/backends/imgui_impl_win32.h File Reference
imgui_impl_win32.h File Reference
#include "imgui.h"
Functions
IMGUI_IMPL_API bool ImGui_ImplWin32_Init (void *hwnd)
IMGUI_IMPL_API bool ImGui_ImplWin32_InitForOpenGL (void *hwnd)
IMGUI_IMPL_API void ImGui_ImplWin32_Shutdown ()
IMGUI_IMPL_API void ImGui_ImplWin32_NewFrame ()
IMGUI_IMPL_API void ImGui_ImplWin32_EnableDpiAwareness ()
IMGUI_IMPL_API float ImGui_ImplWin32_GetDpiScaleForHwnd (void *hwnd)
IMGUI_IMPL_API float ImGui_ImplWin32_GetDpiScaleForMonitor (void *monitor)
IMGUI_IMPL_API void ImGui_ImplWin32_EnableAlphaCompositing (void *hwnd)
Function Documentation
ImGui_ImplWin32_EnableAlphaCompositing()
IMGUI_IMPL_API void ImGui_ImplWin32_EnableAlphaCompositing (void * hwnd)
Definition at line 955 of file imgui_impl_win32.cpp.
References _IsWindows8OrGreater, and _IsWindowsVistaOrGreater.
ImGui_ImplWin32_EnableDpiAwareness()
IMGUI_IMPL_API void ImGui_ImplWin32_EnableDpiAwareness ()
Definition at line 883 of file imgui_impl_win32.cpp.
References _IsWindows10OrGreater, _IsWindows8Point1OrGreater, DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2, and PROCESS_PER_MONITOR_DPI_AWARE.
Referenced by main().
ImGui_ImplWin32_GetDpiScaleForHwnd()
IMGUI_IMPL_API float ImGui_ImplWin32_GetDpiScaleForHwnd (void * hwnd)
Definition at line 938 of file imgui_impl_win32.cpp.
References ImGui_ImplWin32_GetDpiScaleForMonitor().
ImGui_ImplWin32_GetDpiScaleForMonitor()
IMGUI_IMPL_API float ImGui_ImplWin32_GetDpiScaleForMonitor (void * monitor)
Definition at line 912 of file imgui_impl_win32.cpp.
References _IsWindows8Point1OrGreater, IM_ASSERT, and MDT_EFFECTIVE_DPI.
Referenced by ImGui_ImplWin32_GetDpiScaleForHwnd(), and main().
ImGui_ImplWin32_Init()
IMGUI_IMPL_API bool ImGui_ImplWin32_Init (void * hwnd)
Definition at line 213 of file imgui_impl_win32.cpp.
References ImGui_ImplWin32_InitEx().
Referenced by main().
ImGui_ImplWin32_InitForOpenGL()
IMGUI_IMPL_API bool ImGui_ImplWin32_InitForOpenGL (void * hwnd)
Definition at line 218 of file imgui_impl_win32.cpp.
References ImGui_ImplWin32_InitEx().
Referenced by main().
ImGui_ImplWin32_NewFrame()
IMGUI_IMPL_API void ImGui_ImplWin32_NewFrame ()
Definition at line 396 of file imgui_impl_win32.cpp.
References ImGuiIO::DeltaTime, ImGuiIO::DisplaySize, ImGui::GetIO(), ImGui::GetMouseCursor(), ImGui_ImplWin32_Data::hWnd, IM_ASSERT, ImGui_ImplWin32_GetBackendData(), ImGui_ImplWin32_ProcessKeyEventsWorkarounds(), ImGui_ImplWin32_UpdateGamepads(), ImGui_ImplWin32_UpdateMouseCursor(), ImGui_ImplWin32_UpdateMouseData(), ImGuiMouseCursor_None, ImGui_ImplWin32_Data::LastMouseCursor, ImGuiIO::MouseDrawCursor, ImGui_ImplWin32_Data::TicksPerSecond, and ImGui_ImplWin32_Data::Time.
Referenced by main().
ImGui_ImplWin32_Shutdown()
IMGUI_IMPL_API void ImGui_ImplWin32_Shutdown ()
Definition at line 224 of file imgui_impl_win32.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendPlatformName, ImGuiIO::BackendPlatformUserData, ImGuiPlatformIO::ClearPlatformHandlers(), ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplWin32_GetBackendData(), ImGuiBackendFlags_HasGamepad, ImGuiBackendFlags_HasMouseCursors, ImGuiBackendFlags_HasSetMousePos, and ImGui_ImplWin32_Data::XInputDLL.
Referenced by main().