SignalProcessing: examples/imgui/backends/imgui_impl_android.h File Reference
imgui_impl_android.h File Reference
#include "imgui.h"
Functions
IMGUI_IMPL_API bool ImGui_ImplAndroid_Init (ANativeWindow *window)
IMGUI_IMPL_API int32_t ImGui_ImplAndroid_HandleInputEvent (const AInputEvent *input_event)
IMGUI_IMPL_API void ImGui_ImplAndroid_Shutdown ()
IMGUI_IMPL_API void ImGui_ImplAndroid_NewFrame ()
Function Documentation
ImGui_ImplAndroid_HandleInputEvent()
IMGUI_IMPL_API int32_t ImGui_ImplAndroid_HandleInputEvent (const AInputEvent * input_event)
Definition at line 159 of file imgui_impl_android.cpp.
References ImGuiIO::AddKeyEvent(), ImGuiIO::AddMouseButtonEvent(), ImGuiIO::AddMousePosEvent(), ImGuiIO::AddMouseSourceEvent(), ImGuiIO::AddMouseWheelEvent(), ImGui::GetIO(), ImGui_ImplAndroid_KeyCodeToImGuiKey(), ImGuiKey_None, ImGuiMod_Alt, ImGuiMod_Ctrl, ImGuiMod_Shift, ImGuiMod_Super, ImGuiMouseSource_Mouse, ImGuiMouseSource_Pen, ImGuiMouseSource_TouchScreen, and ImGuiIO::SetKeyEventNativeData().
Referenced by handleInputEvent().
ImGui_ImplAndroid_Init()
IMGUI_IMPL_API bool ImGui_ImplAndroid_Init (ANativeWindow * window)
Definition at line 264 of file imgui_impl_android.cpp.
References ImGuiIO::BackendPlatformName, g_Time, g_Window, ImGui::GetIO(), and IMGUI_CHECKVERSION.
Referenced by Init().
ImGui_ImplAndroid_NewFrame()
IMGUI_IMPL_API void ImGui_ImplAndroid_NewFrame ()
Definition at line 284 of file imgui_impl_android.cpp.
References ImGuiIO::DeltaTime, ImGuiIO::DisplayFramebufferScale, ImGuiIO::DisplaySize, g_Time, g_Window, and ImGui::GetIO().
Referenced by MainLoopStep().
ImGui_ImplAndroid_Shutdown()
IMGUI_IMPL_API void ImGui_ImplAndroid_Shutdown ()
Definition at line 278 of file imgui_impl_android.cpp.
References ImGuiIO::BackendPlatformName, and ImGui::GetIO().
Referenced by Shutdown().