SignalProcessing: examples/imgui/backends/imgui_impl_glut.cpp File Reference
imgui_impl_glut.cpp File Reference
#include "imgui.h"
#include "imgui_impl_glut.h"
#include <GL/freeglut.h>
Macros
#define GL_SILENCE_DEPRECATION
Functions
static ImGuiKey ImGui_ImplGLUT_KeyToImGuiKey (int key)
bool ImGui_ImplGLUT_Init ()
void ImGui_ImplGLUT_InstallFuncs ()
void ImGui_ImplGLUT_Shutdown ()
void ImGui_ImplGLUT_NewFrame ()
static void ImGui_ImplGLUT_UpdateKeyModifiers ()
static void ImGui_ImplGLUT_AddKeyEvent (ImGuiKey key, bool down, int native_keycode)
void ImGui_ImplGLUT_KeyboardFunc (unsigned char c, int x, int y)
void ImGui_ImplGLUT_KeyboardUpFunc (unsigned char c, int x, int y)
void ImGui_ImplGLUT_SpecialFunc (int key, int x, int y)
void ImGui_ImplGLUT_SpecialUpFunc (int key, int x, int y)
void ImGui_ImplGLUT_MouseFunc (int glut_button, int state, int x, int y)
void ImGui_ImplGLUT_ReshapeFunc (int w, int h)
void ImGui_ImplGLUT_MotionFunc (int x, int y)
Variables
static int g_Time = 0
Macro Definition Documentation
GL_SILENCE_DEPRECATION
#define GL_SILENCE_DEPRECATION
Definition at line 40 of file imgui_impl_glut.cpp.
Function Documentation
ImGui_ImplGLUT_AddKeyEvent()
static void ImGui_ImplGLUT_AddKeyEvent (ImGuiKey key, bool down, int native_keycode) static
Definition at line 224 of file imgui_impl_glut.cpp.
References ImGuiIO::AddKeyEvent(), ImGui::GetIO(), and ImGuiIO::SetKeyEventNativeData().
Referenced by ImGui_ImplGLUT_KeyboardFunc(), ImGui_ImplGLUT_KeyboardUpFunc(), ImGui_ImplGLUT_SpecialFunc(), and ImGui_ImplGLUT_SpecialUpFunc().
ImGui_ImplGLUT_Init()
bool ImGui_ImplGLUT_Init ()
Definition at line 167 of file imgui_impl_glut.cpp.
References ImGuiIO::BackendPlatformName, g_Time, ImGui::GetIO(), and IMGUI_CHECKVERSION.
Referenced by main().
ImGui_ImplGLUT_InstallFuncs()
void ImGui_ImplGLUT_InstallFuncs ()
Definition at line 182 of file imgui_impl_glut.cpp.
References ImGui_ImplGLUT_KeyboardFunc(), ImGui_ImplGLUT_KeyboardUpFunc(), ImGui_ImplGLUT_MotionFunc(), ImGui_ImplGLUT_MouseFunc(), ImGui_ImplGLUT_MouseWheelFunc(), ImGui_ImplGLUT_ReshapeFunc(), ImGui_ImplGLUT_SpecialFunc(), and ImGui_ImplGLUT_SpecialUpFunc().
Referenced by main().
ImGui_ImplGLUT_KeyboardFunc()
void ImGui_ImplGLUT_KeyboardFunc (unsigned char c, int x, int y)
Definition at line 231 of file imgui_impl_glut.cpp.
References ImGuiIO::AddInputCharacter(), ImGui::GetIO(), ImGui_ImplGLUT_AddKeyEvent(), ImGui_ImplGLUT_KeyToImGuiKey(), and ImGui_ImplGLUT_UpdateKeyModifiers().
Referenced by ImGui_ImplGLUT_InstallFuncs().
ImGui_ImplGLUT_KeyboardUpFunc()
void ImGui_ImplGLUT_KeyboardUpFunc (unsigned char c, int x, int y)
Definition at line 245 of file imgui_impl_glut.cpp.
References ImGui_ImplGLUT_AddKeyEvent(), ImGui_ImplGLUT_KeyToImGuiKey(), and ImGui_ImplGLUT_UpdateKeyModifiers().
Referenced by ImGui_ImplGLUT_InstallFuncs().
ImGui_ImplGLUT_KeyToImGuiKey()
static ImGuiKey ImGui_ImplGLUT_KeyToImGuiKey (int key) static
Definition at line 54 of file imgui_impl_glut.cpp.
References ImGuiKey_0, ImGuiKey_1, ImGuiKey_2, ImGuiKey_3, ImGuiKey_4, ImGuiKey_5, ImGuiKey_6, ImGuiKey_7, ImGuiKey_8, ImGuiKey_9, ImGuiKey_A, ImGuiKey_Apostrophe, ImGuiKey_B, ImGuiKey_Backslash, ImGuiKey_Backspace, ImGuiKey_C, ImGuiKey_Comma, ImGuiKey_D, ImGuiKey_Delete, ImGuiKey_DownArrow, ImGuiKey_E, ImGuiKey_End, ImGuiKey_Enter, ImGuiKey_Equal, ImGuiKey_Escape, ImGuiKey_F, ImGuiKey_F1, ImGuiKey_F10, ImGuiKey_F11, ImGuiKey_F12, ImGuiKey_F2, ImGuiKey_F3, ImGuiKey_F4, ImGuiKey_F5, ImGuiKey_F6, ImGuiKey_F7, ImGuiKey_F8, ImGuiKey_F9, ImGuiKey_G, ImGuiKey_GraveAccent, ImGuiKey_H, ImGuiKey_Home, ImGuiKey_I, ImGuiKey_Insert, ImGuiKey_J, ImGuiKey_K, ImGuiKey_KeypadAdd, ImGuiKey_KeypadMultiply, ImGuiKey_L, ImGuiKey_LeftAlt, ImGuiKey_LeftArrow, ImGuiKey_LeftBracket, ImGuiKey_LeftCtrl, ImGuiKey_LeftShift, ImGuiKey_M, ImGuiKey_Minus, ImGuiKey_N, ImGuiKey_None, ImGuiKey_NumLock, ImGuiKey_O, ImGuiKey_P, ImGuiKey_PageDown, ImGuiKey_PageUp, ImGuiKey_Period, ImGuiKey_Q, ImGuiKey_R, ImGuiKey_RightAlt, ImGuiKey_RightArrow, ImGuiKey_RightBracket, ImGuiKey_RightCtrl, ImGuiKey_RightShift, ImGuiKey_S, ImGuiKey_Semicolon, ImGuiKey_Slash, ImGuiKey_Space, ImGuiKey_T, ImGuiKey_Tab, ImGuiKey_U, ImGuiKey_UpArrow, ImGuiKey_V, ImGuiKey_W, ImGuiKey_X, ImGuiKey_Y, and ImGuiKey_Z.
Referenced by ImGui_ImplGLUT_KeyboardFunc(), ImGui_ImplGLUT_KeyboardUpFunc(), ImGui_ImplGLUT_SpecialFunc(), and ImGui_ImplGLUT_SpecialUpFunc().
ImGui_ImplGLUT_MotionFunc()
void ImGui_ImplGLUT_MotionFunc (int x, int y)
Definition at line 301 of file imgui_impl_glut.cpp.
References ImGuiIO::AddMousePosEvent(), and ImGui::GetIO().
Referenced by ImGui_ImplGLUT_InstallFuncs().
ImGui_ImplGLUT_MouseFunc()
void ImGui_ImplGLUT_MouseFunc (int glut_button, int state, int x, int y)
Definition at line 272 of file imgui_impl_glut.cpp.
References ImGuiIO::AddMouseButtonEvent(), ImGuiIO::AddMousePosEvent(), and ImGui::GetIO().
Referenced by ImGui_ImplGLUT_InstallFuncs().
ImGui_ImplGLUT_NewFrame()
void ImGui_ImplGLUT_NewFrame ()
Definition at line 203 of file imgui_impl_glut.cpp.
References ImGuiIO::DeltaTime, g_Time, and ImGui::GetIO().
Referenced by MainLoopStep().
ImGui_ImplGLUT_ReshapeFunc()
void ImGui_ImplGLUT_ReshapeFunc (int w, int h)
Definition at line 295 of file imgui_impl_glut.cpp.
References ImGuiIO::DisplaySize, and ImGui::GetIO().
Referenced by ImGui_ImplGLUT_InstallFuncs().
ImGui_ImplGLUT_Shutdown()
void ImGui_ImplGLUT_Shutdown ()
Definition at line 197 of file imgui_impl_glut.cpp.
References ImGuiIO::BackendPlatformName, and ImGui::GetIO().
Referenced by main().
ImGui_ImplGLUT_SpecialFunc()
void ImGui_ImplGLUT_SpecialFunc (int key, int x, int y)
Definition at line 254 of file imgui_impl_glut.cpp.
References ImGui_ImplGLUT_AddKeyEvent(), ImGui_ImplGLUT_KeyToImGuiKey(), and ImGui_ImplGLUT_UpdateKeyModifiers().
Referenced by ImGui_ImplGLUT_InstallFuncs().
ImGui_ImplGLUT_SpecialUpFunc()
void ImGui_ImplGLUT_SpecialUpFunc (int key, int x, int y)
Definition at line 263 of file imgui_impl_glut.cpp.
References ImGui_ImplGLUT_AddKeyEvent(), ImGui_ImplGLUT_KeyToImGuiKey(), and ImGui_ImplGLUT_UpdateKeyModifiers().
Referenced by ImGui_ImplGLUT_InstallFuncs().
ImGui_ImplGLUT_UpdateKeyModifiers()
static void ImGui_ImplGLUT_UpdateKeyModifiers () static
Definition at line 215 of file imgui_impl_glut.cpp.
References ImGuiIO::AddKeyEvent(), ImGui::GetIO(), ImGuiMod_Alt, ImGuiMod_Ctrl, and ImGuiMod_Shift.
Referenced by ImGui_ImplGLUT_KeyboardFunc(), ImGui_ImplGLUT_KeyboardUpFunc(), ImGui_ImplGLUT_SpecialFunc(), and ImGui_ImplGLUT_SpecialUpFunc().
Variable Documentation
g_Time
int g_Time = 0 static
Definition at line 51 of file imgui_impl_glut.cpp.
Referenced by ImGui_ImplGLUT_Init(), and ImGui_ImplGLUT_NewFrame().