SignalProcessing: examples/imgui/backends/imgui_impl_opengl3.cpp File Reference
imgui_impl_opengl3.cpp File Reference
#include "imgui.h"
#include "imgui_impl_opengl3.h"
#include <stdio.h>
#include <stdint.h>
#include "imgui_impl_opengl3_loader.h"
Classes
struct ImGui_ImplOpenGL3_Data
Macros
#define IMGL3W_IMPL
#define IMGUI_IMPL_OPENGL_LOADER_IMGL3W
#define IMGUI_IMPL_OPENGL_USE_VERTEX_ARRAY
#define IMGUI_IMPL_OPENGL_HAS_EXTENSIONS
#define IMGUI_IMPL_OPENGL_MAY_HAVE_POLYGON_MODE
#define IMGUI_IMPL_OPENGL_MAY_HAVE_BIND_BUFFER_PIXEL_UNPACK
#define IMGUI_IMPL_OPENGL_MAY_HAVE_PRIMITIVE_RESTART
#define IMGUI_IMPL_OPENGL_MAY_HAVE_VTX_OFFSET
#define IMGUI_IMPL_OPENGL_MAY_HAVE_BIND_SAMPLER
#define GL_CALL(_CALL) _CALL
Functions
static ImGui_ImplOpenGL3_Data * ImGui_ImplOpenGL3_GetBackendData ()
bool ImGui_ImplOpenGL3_InitLoader ()
bool ImGui_ImplOpenGL3_Init (const char *glsl_version)
void ImGui_ImplOpenGL3_Shutdown ()
void ImGui_ImplOpenGL3_NewFrame ()
static void ImGui_ImplOpenGL3_SetupRenderState (ImDrawData *draw_data, int fb_width, int fb_height, GLuint vertex_array_object)
void ImGui_ImplOpenGL3_RenderDrawData (ImDrawData *draw_data)
static void ImGui_ImplOpenGL3_DestroyTexture (ImTextureData *tex)
void ImGui_ImplOpenGL3_UpdateTexture (ImTextureData *tex)
static bool CheckShader (GLuint handle, const char *desc)
static bool CheckProgram (GLuint handle, const char *desc)
bool ImGui_ImplOpenGL3_CreateDeviceObjects ()
void ImGui_ImplOpenGL3_DestroyDeviceObjects ()
Macro Definition Documentation
GL_CALL
#define GL_CALL (_CALL) _CALL
Definition at line 227 of file imgui_impl_opengl3.cpp.
IMGL3W_IMPL
#define IMGL3W_IMPL
Definition at line 178 of file imgui_impl_opengl3.cpp.
IMGUI_IMPL_OPENGL_HAS_EXTENSIONS
#define IMGUI_IMPL_OPENGL_HAS_EXTENSIONS
Definition at line 197 of file imgui_impl_opengl3.cpp.
IMGUI_IMPL_OPENGL_LOADER_IMGL3W
#define IMGUI_IMPL_OPENGL_LOADER_IMGL3W
Definition at line 179 of file imgui_impl_opengl3.cpp.
IMGUI_IMPL_OPENGL_MAY_HAVE_BIND_BUFFER_PIXEL_UNPACK
#define IMGUI_IMPL_OPENGL_MAY_HAVE_BIND_BUFFER_PIXEL_UNPACK
Definition at line 203 of file imgui_impl_opengl3.cpp.
IMGUI_IMPL_OPENGL_MAY_HAVE_BIND_SAMPLER
#define IMGUI_IMPL_OPENGL_MAY_HAVE_BIND_SAMPLER
Definition at line 218 of file imgui_impl_opengl3.cpp.
IMGUI_IMPL_OPENGL_MAY_HAVE_POLYGON_MODE
#define IMGUI_IMPL_OPENGL_MAY_HAVE_POLYGON_MODE
Definition at line 198 of file imgui_impl_opengl3.cpp.
IMGUI_IMPL_OPENGL_MAY_HAVE_PRIMITIVE_RESTART
#define IMGUI_IMPL_OPENGL_MAY_HAVE_PRIMITIVE_RESTART
Definition at line 208 of file imgui_impl_opengl3.cpp.
IMGUI_IMPL_OPENGL_MAY_HAVE_VTX_OFFSET
#define IMGUI_IMPL_OPENGL_MAY_HAVE_VTX_OFFSET
Definition at line 213 of file imgui_impl_opengl3.cpp.
IMGUI_IMPL_OPENGL_USE_VERTEX_ARRAY
#define IMGUI_IMPL_OPENGL_USE_VERTEX_ARRAY
Definition at line 185 of file imgui_impl_opengl3.cpp.
Function Documentation
CheckProgram()
static bool CheckProgram (GLuint handle, const char * desc) static
Definition at line 820 of file imgui_impl_opengl3.cpp.
References ImVector< T >::begin(), GL_FALSE, GL_INFO_LOG_LENGTH, GL_LINK_STATUS, GL_TRUE, glGetProgramInfoLog, glGetProgramiv, ImGui_ImplOpenGL3_Data::GlslVersionString, ImGui_ImplOpenGL3_GetBackendData(), and ImVector< T >::resize().
Referenced by ImGui_ImplOpenGL3_CreateDeviceObjects().
CheckShader()
static bool CheckShader (GLuint handle, const char * desc) static
Definition at line 801 of file imgui_impl_opengl3.cpp.
References ImVector< T >::begin(), GL_COMPILE_STATUS, GL_FALSE, GL_INFO_LOG_LENGTH, GL_TRUE, glGetShaderInfoLog, glGetShaderiv, ImGui_ImplOpenGL3_Data::GlslVersionString, ImGui_ImplOpenGL3_GetBackendData(), and ImVector< T >::resize().
Referenced by ImGui_ImplOpenGL3_CreateDeviceObjects().
ImGui_ImplOpenGL3_CreateDeviceObjects()
bool ImGui_ImplOpenGL3_CreateDeviceObjects ()
Definition at line 838 of file imgui_impl_opengl3.cpp.
References ImGui_ImplOpenGL3_Data::AttribLocationProjMtx, ImGui_ImplOpenGL3_Data::AttribLocationTex, ImGui_ImplOpenGL3_Data::AttribLocationVtxColor, ImGui_ImplOpenGL3_Data::AttribLocationVtxPos, ImGui_ImplOpenGL3_Data::AttribLocationVtxUV, CheckProgram(), CheckShader(), ImGui_ImplOpenGL3_Data::ElementsHandle, GL_ARRAY_BUFFER, GL_ARRAY_BUFFER_BINDING, GL_CALL, GL_FRAGMENT_SHADER, GL_PIXEL_UNPACK_BUFFER, GL_PIXEL_UNPACK_BUFFER_BINDING, GL_TEXTURE_2D, GL_TEXTURE_BINDING_2D, GL_VERTEX_ARRAY_BINDING, GL_VERTEX_SHADER, glAttachShader, glBindBuffer, glBindTexture, glBindVertexArray, glCompileShader, glCreateProgram, glCreateShader, glDeleteShader, glDetachShader, glGenBuffers, glGetAttribLocation, glGetIntegerv, glGetUniformLocation, glLinkProgram, glShaderSource, ImGui_ImplOpenGL3_Data::GlslVersionString, ImGui_ImplOpenGL3_Data::GlVersion, ImGui_ImplOpenGL3_GetBackendData(), ImGui_ImplOpenGL3_Data::ShaderHandle, and ImGui_ImplOpenGL3_Data::VboHandle.
Referenced by ImGui_ImplOpenGL3_NewFrame().
ImGui_ImplOpenGL3_DestroyDeviceObjects()
void ImGui_ImplOpenGL3_DestroyDeviceObjects ()
Definition at line 1036 of file imgui_impl_opengl3.cpp.
References ImGui_ImplOpenGL3_Data::ElementsHandle, ImGui::GetPlatformIO(), glDeleteBuffers, glDeleteProgram, ImGui_ImplOpenGL3_DestroyTexture(), ImGui_ImplOpenGL3_GetBackendData(), ImGui_ImplOpenGL3_Data::ShaderHandle, ImGuiPlatformIO::Textures, and ImGui_ImplOpenGL3_Data::VboHandle.
Referenced by ImGui_ImplOpenGL3_Shutdown().
ImGui_ImplOpenGL3_DestroyTexture()
static void ImGui_ImplOpenGL3_DestroyTexture (ImTextureData * tex) static
Definition at line 714 of file imgui_impl_opengl3.cpp.
References glDeleteTextures, ImTextureID_Invalid, ImTextureStatus_Destroyed, ImTextureData::SetStatus(), ImTextureData::SetTexID(), and ImTextureData::TexID.
Referenced by ImGui_ImplOpenGL3_DestroyDeviceObjects(), and ImGui_ImplOpenGL3_UpdateTexture().
ImGui_ImplOpenGL3_GetBackendData()
static ImGui_ImplOpenGL3_Data * ImGui_ImplOpenGL3_GetBackendData () static
Definition at line 260 of file imgui_impl_opengl3.cpp.
References ImGuiIO::BackendRendererUserData, ImGui::GetCurrentContext(), and ImGui::GetIO().
Referenced by CheckProgram(), CheckShader(), ImGui_ImplOpenGL3_CreateDeviceObjects(), ImGui_ImplOpenGL3_DestroyDeviceObjects(), ImGui_ImplOpenGL3_NewFrame(), ImGui_ImplOpenGL3_RenderDrawData(), ImGui_ImplOpenGL3_SetupRenderState(), ImGui_ImplOpenGL3_Shutdown(), and ImGui_ImplOpenGL3_UpdateTexture().
ImGui_ImplOpenGL3_Init()
bool ImGui_ImplOpenGL3_Init (const char * glsl_version)
Definition at line 305 of file imgui_impl_opengl3.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGui::GetIO(), ImGui::GetPlatformIO(), GL_CONTEXT_COMPATIBILITY_PROFILE_BIT, GL_CONTEXT_PROFILE_MASK, GL_EXTENSIONS, GL_MAJOR_VERSION, GL_MAX_TEXTURE_SIZE, GL_MINOR_VERSION, GL_NUM_EXTENSIONS, GL_RENDERER, GL_TEXTURE_BINDING_2D, GL_VENDOR, GL_VERSION, glGetIntegerv, glGetString, glGetStringi, ImGui_ImplOpenGL3_Data::GlProfileIsCompat, ImGui_ImplOpenGL3_Data::GlProfileIsES2, ImGui_ImplOpenGL3_Data::GlProfileIsES3, ImGui_ImplOpenGL3_Data::GlProfileMask, ImGui_ImplOpenGL3_Data::GlslVersionString, ImGui_ImplOpenGL3_Data::GlVersion, ImGui_ImplOpenGL3_Data::HasBindSampler, ImGui_ImplOpenGL3_Data::HasClipOrigin, ImGui_ImplOpenGL3_Data::HasPolygonMode, IM_ARRAYSIZE, IM_ASSERT, IM_NEW, IM_UNUSED, IMGUI_CHECKVERSION, ImGui_ImplOpenGL3_InitLoader(), ImGuiBackendFlags_RendererHasTextures, ImGuiBackendFlags_RendererHasVtxOffset, ImGui_ImplOpenGL3_Data::MaxTextureSize, ImGuiPlatformIO::Renderer_TextureMaxHeight, ImGuiPlatformIO::Renderer_TextureMaxWidth, and ImGui_ImplOpenGL3_Data::UseBufferSubData.
Referenced by Init(), main(), and main().
ImGui_ImplOpenGL3_InitLoader()
bool ImGui_ImplOpenGL3_InitLoader ()
Definition at line 291 of file imgui_impl_opengl3.cpp.
References glGetIntegerv, and imgl3wInit().
Referenced by ImGui_ImplOpenGL3_Init(), ImGui_ImplOpenGL3_NewFrame(), and ImGui_ImplOpenGL3_RenderDrawData().
ImGui_ImplOpenGL3_NewFrame()
void ImGui_ImplOpenGL3_NewFrame ()
Definition at line 440 of file imgui_impl_opengl3.cpp.
References IM_ASSERT, ImGui_ImplOpenGL3_CreateDeviceObjects(), ImGui_ImplOpenGL3_GetBackendData(), ImGui_ImplOpenGL3_InitLoader(), and ImGui_ImplOpenGL3_Data::ShaderHandle.
Referenced by main(), main(), and MainLoopStep().
ImGui_ImplOpenGL3_RenderDrawData()
void ImGui_ImplOpenGL3_RenderDrawData (ImDrawData * draw_data)
Definition at line 529 of file imgui_impl_opengl3.cpp.
References ImGui_ImplOpenGL3_Data::AttribLocationVtxColor, ImGui_ImplOpenGL3_Data::AttribLocationVtxPos, ImGui_ImplOpenGL3_Data::AttribLocationVtxUV, ImDrawCmd::ClipRect, ImDrawList::CmdBuffer, ImDrawData::CmdLists, ImVector< T >::Data, ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImDrawCmd::ElemCount, ImDrawData::FramebufferScale, ImDrawCmd::GetTexID(), GL_ACTIVE_TEXTURE, GL_ARRAY_BUFFER, GL_ARRAY_BUFFER_BINDING, GL_BACK, GL_BLEND, GL_BLEND_DST_ALPHA, GL_BLEND_DST_RGB, GL_BLEND_EQUATION_ALPHA, GL_BLEND_EQUATION_RGB, GL_BLEND_SRC_ALPHA, GL_BLEND_SRC_RGB, GL_CALL, GL_CULL_FACE, GL_CURRENT_PROGRAM, GL_DEPTH_TEST, GL_ELEMENT_ARRAY_BUFFER, GL_ELEMENT_ARRAY_BUFFER_BINDING, GL_FALSE, GL_FRONT, GL_FRONT_AND_BACK, GL_POLYGON_MODE, GL_PRIMITIVE_RESTART, GL_SAMPLER_BINDING, GL_SCISSOR_BOX, GL_SCISSOR_TEST, GL_STENCIL_TEST, GL_STREAM_DRAW, GL_TEXTURE0, GL_TEXTURE_2D, GL_TEXTURE_BINDING_2D, GL_TRIANGLES, GL_UNSIGNED_INT, GL_UNSIGNED_SHORT, GL_VERTEX_ARRAY_BINDING, GL_VIEWPORT, glActiveTexture, glBindBuffer, glBindSampler, glBindTexture, glBindVertexArray, glBlendEquationSeparate, glBlendFuncSeparate, glBufferData, glBufferSubData, glDeleteVertexArrays, glDisable, glDrawElements, glDrawElementsBaseVertex, glEnable, glGenVertexArrays, glGetIntegerv, glIsEnabled, glIsProgram, glPolygonMode, ImGui_ImplOpenGL3_Data::GlProfileIsCompat, ImGui_ImplOpenGL3_Data::GlProfileIsES3, glScissor, glUseProgram, ImGui_ImplOpenGL3_Data::GlVersion, glViewport, ImGui_ImplOpenGL3_Data::HasBindSampler, ImGui_ImplOpenGL3_Data::HasPolygonMode, ImDrawList::IdxBuffer, ImDrawCmd::IdxOffset, ImDrawCallback_ResetRenderState, ImDrawIdx, ImGui_ImplOpenGL3_GetBackendData(), ImGui_ImplOpenGL3_InitLoader(), ImGui_ImplOpenGL3_SetupRenderState(), ImGui_ImplOpenGL3_UpdateTexture(), ImTextureStatus_OK, ImGui_ImplOpenGL3_Data::IndexBufferSize, ImVector< T >::Size, ImDrawData::Textures, ImGui_ImplOpenGL3_Data::UseBufferSubData, ImDrawCmd::UserCallback, ImGui_ImplOpenGL3_Data::VertexBufferSize, ImDrawList::VtxBuffer, ImDrawCmd::VtxOffset, ImVec4::w, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by main(), main(), and MainLoopStep().
ImGui_ImplOpenGL3_SetupRenderState()
static void ImGui_ImplOpenGL3_SetupRenderState (ImDrawData * draw_data, int fb_width, int fb_height, GLuint vertex_array_object) static
Definition at line 452 of file imgui_impl_opengl3.cpp.
References ImGui_ImplOpenGL3_Data::AttribLocationProjMtx, ImGui_ImplOpenGL3_Data::AttribLocationTex, ImGui_ImplOpenGL3_Data::AttribLocationVtxColor, ImGui_ImplOpenGL3_Data::AttribLocationVtxPos, ImGui_ImplOpenGL3_Data::AttribLocationVtxUV, ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImGui_ImplOpenGL3_Data::ElementsHandle, GL_ARRAY_BUFFER, GL_BLEND, GL_CALL, GL_CLIP_ORIGIN, GL_CULL_FACE, GL_DEPTH_TEST, GL_ELEMENT_ARRAY_BUFFER, GL_FALSE, GL_FILL, GL_FLOAT, GL_FRONT_AND_BACK, GL_FUNC_ADD, GL_ONE, GL_ONE_MINUS_SRC_ALPHA, GL_PRIMITIVE_RESTART, GL_SCISSOR_TEST, GL_SRC_ALPHA, GL_STENCIL_TEST, GL_TRUE, GL_UNSIGNED_BYTE, GL_UPPER_LEFT, glBindBuffer, glBindSampler, glBindVertexArray, glBlendEquation, glBlendFuncSeparate, glDisable, glEnable, glEnableVertexAttribArray, glGetIntegerv, glPolygonMode, ImGui_ImplOpenGL3_Data::GlProfileIsES3, glUniform1i, glUniformMatrix4fv, glUseProgram, ImGui_ImplOpenGL3_Data::GlVersion, glVertexAttribPointer, glViewport, ImGui_ImplOpenGL3_Data::HasBindSampler, ImGui_ImplOpenGL3_Data::HasClipOrigin, ImGui_ImplOpenGL3_Data::HasPolygonMode, ImGui_ImplOpenGL3_GetBackendData(), ImGui_ImplOpenGL3_Data::ShaderHandle, ImGui_ImplOpenGL3_Data::VboHandle, ImVec2::x, and ImVec2::y.
Referenced by ImGui_ImplOpenGL3_RenderDrawData().
ImGui_ImplOpenGL3_Shutdown()
void ImGui_ImplOpenGL3_Shutdown ()
Definition at line 420 of file imgui_impl_opengl3.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGuiPlatformIO::ClearRendererHandlers(), ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), imgl3wShutdown(), ImGui_ImplOpenGL3_DestroyDeviceObjects(), ImGui_ImplOpenGL3_GetBackendData(), ImGuiBackendFlags_RendererHasTextures, and ImGuiBackendFlags_RendererHasVtxOffset.
Referenced by main(), main(), and Shutdown().
ImGui_ImplOpenGL3_UpdateTexture()
void ImGui_ImplOpenGL3_UpdateTexture (ImTextureData * tex)
Definition at line 724 of file imgui_impl_opengl3.cpp.
References ImTextureData::BackendUserData, ImTextureData::BytesPerPixel, ImVector< T >::Data, ImVector< T >::end(), ImTextureData::Format, ImTextureData::GetPixels(), ImTextureData::GetPixelsAt(), GL_CALL, GL_CLAMP_TO_EDGE, GL_LINEAR, GL_RGBA, GL_TEXTURE_2D, GL_TEXTURE_BINDING_2D, GL_TEXTURE_MAG_FILTER, GL_TEXTURE_MIN_FILTER, GL_TEXTURE_WRAP_S, GL_TEXTURE_WRAP_T, GL_UNPACK_ALIGNMENT, GL_UNPACK_ROW_LENGTH, GL_UNSIGNED_BYTE, glBindTexture, glGenTextures, glGetIntegerv, glPixelStorei, glTexImage2D, glTexParameteri, glTexSubImage2D, ImTextureData::Height, IM_ASSERT, ImGui_ImplOpenGL3_DestroyTexture(), ImGui_ImplOpenGL3_GetBackendData(), ImTextureFormat_RGBA32, ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImVector< T >::resize(), ImTextureData::SetStatus(), ImTextureData::SetTexID(), ImTextureData::Status, ImGui_ImplOpenGL3_Data::TempBuffer, ImTextureData::TexID, ImTextureData::UnusedFrames, ImTextureData::Updates, and ImTextureData::Width.
Referenced by ImGui_ImplOpenGL3_RenderDrawData().