SignalProcessing: examples/imgui/backends/imgui_impl_dx11.cpp File Reference
imgui_impl_dx11.cpp File Reference
#include "imgui.h"
#include "imgui_impl_dx11.h"
#include <stdio.h>
#include <d3d11.h>
#include <d3dcompiler.h>
Classes
struct ImGui_ImplDX11_Texture
struct ImGui_ImplDX11_Data
struct VERTEX_CONSTANT_BUFFER_DX11
Functions
static ImGui_ImplDX11_Data * ImGui_ImplDX11_GetBackendData ()
static void ImGui_ImplDX11_SetupRenderState (const ImDrawData *draw_data, ID3D11DeviceContext *device_ctx)
void ImGui_ImplDX11_RenderDrawData (ImDrawData *draw_data)
static void ImGui_ImplDX11_DestroyTexture (ImTextureData *tex)
void ImGui_ImplDX11_UpdateTexture (ImTextureData *tex)
bool ImGui_ImplDX11_CreateDeviceObjects ()
void ImGui_ImplDX11_InvalidateDeviceObjects ()
bool ImGui_ImplDX11_Init (ID3D11Device *device, ID3D11DeviceContext *device_context)
void ImGui_ImplDX11_Shutdown ()
void ImGui_ImplDX11_NewFrame ()
Function Documentation
ImGui_ImplDX11_CreateDeviceObjects()
bool ImGui_ImplDX11_CreateDeviceObjects ()
Definition at line 421 of file imgui_impl_dx11.cpp.
References ImGui_ImplDX11_GetBackendData(), ImGui_ImplDX11_InvalidateDeviceObjects(), ImGui_ImplDX11_Data::pBlendState, ImGui_ImplDX11_Data::pd3dDevice, ImGui_ImplDX11_Data::pDepthStencilState, ImGui_ImplDX11_Data::pInputLayout, ImGui_ImplDX11_Data::pPixelShader, ImGui_ImplDX11_Data::pRasterizerState, ImGui_ImplDX11_Data::pTexSamplerLinear, ImGui_ImplDX11_Data::pVertexConstantBuffer, and ImGui_ImplDX11_Data::pVertexShader.
Referenced by ImGui_ImplDX11_NewFrame().
ImGui_ImplDX11_DestroyTexture()
static void ImGui_ImplDX11_DestroyTexture (ImTextureData * tex) static
Definition at line 342 of file imgui_impl_dx11.cpp.
References ImTextureData::BackendUserData, IM_ASSERT, IM_DELETE(), ImTextureID_Invalid, ImTextureStatus_Destroyed, ImTextureData::SetStatus(), ImTextureData::SetTexID(), and ImTextureData::TexID.
Referenced by ImGui_ImplDX11_InvalidateDeviceObjects(), and ImGui_ImplDX11_UpdateTexture().
ImGui_ImplDX11_GetBackendData()
static ImGui_ImplDX11_Data * ImGui_ImplDX11_GetBackendData () static
Definition at line 97 of file imgui_impl_dx11.cpp.
References ImGuiIO::BackendRendererUserData, ImGui::GetCurrentContext(), and ImGui::GetIO().
Referenced by ImGui_ImplDX11_CreateDeviceObjects(), ImGui_ImplDX11_InvalidateDeviceObjects(), ImGui_ImplDX11_NewFrame(), ImGui_ImplDX11_RenderDrawData(), ImGui_ImplDX11_SetupRenderState(), ImGui_ImplDX11_Shutdown(), and ImGui_ImplDX11_UpdateTexture().
ImGui_ImplDX11_Init()
bool ImGui_ImplDX11_Init (ID3D11Device * device, ID3D11DeviceContext * device_context)
Definition at line 611 of file imgui_impl_dx11.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_NEW, IMGUI_CHECKVERSION, ImGuiBackendFlags_RendererHasTextures, ImGuiBackendFlags_RendererHasVtxOffset, ImGui_ImplDX11_Data::pd3dDevice, ImGui_ImplDX11_Data::pd3dDeviceContext, ImGui_ImplDX11_Data::pFactory, ImGuiPlatformIO::Renderer_TextureMaxHeight, and ImGuiPlatformIO::Renderer_TextureMaxWidth.
Referenced by main().
ImGui_ImplDX11_InvalidateDeviceObjects()
void ImGui_ImplDX11_InvalidateDeviceObjects ()
Definition at line 588 of file imgui_impl_dx11.cpp.
References ImGui::GetPlatformIO(), ImGui_ImplDX11_DestroyTexture(), ImGui_ImplDX11_GetBackendData(), ImGui_ImplDX11_Data::pBlendState, ImGui_ImplDX11_Data::pd3dDevice, ImGui_ImplDX11_Data::pDepthStencilState, ImGui_ImplDX11_Data::pIB, ImGui_ImplDX11_Data::pInputLayout, ImGui_ImplDX11_Data::pPixelShader, ImGui_ImplDX11_Data::pRasterizerState, ImGui_ImplDX11_Data::pTexSamplerLinear, ImGui_ImplDX11_Data::pVB, ImGui_ImplDX11_Data::pVertexConstantBuffer, ImGui_ImplDX11_Data::pVertexShader, and ImGuiPlatformIO::Textures.
Referenced by ImGui_ImplDX11_CreateDeviceObjects(), and ImGui_ImplDX11_Shutdown().
ImGui_ImplDX11_NewFrame()
void ImGui_ImplDX11_NewFrame ()
Definition at line 667 of file imgui_impl_dx11.cpp.
References IM_ASSERT, ImGui_ImplDX11_CreateDeviceObjects(), ImGui_ImplDX11_GetBackendData(), and ImGui_ImplDX11_Data::pVertexShader.
Referenced by main().
ImGui_ImplDX11_RenderDrawData()
void ImGui_ImplDX11_RenderDrawData (ImDrawData * draw_data)
Definition at line 161 of file imgui_impl_dx11.cpp.
References ImDrawCmd::ClipRect, ImDrawList::CmdBuffer, ImDrawData::CmdLists, ImVector< T >::Data, ImGui_ImplDX11_RenderState::Device, ImGui_ImplDX11_RenderState::DeviceContext, ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImDrawCmd::ElemCount, ImDrawData::FramebufferScale, ImGui::GetPlatformIO(), ImDrawCmd::GetTexID(), ImDrawList::IdxBuffer, ImDrawCmd::IdxOffset, ImDrawCallback_ResetRenderState, ImDrawIdx, ImGui_ImplDX11_GetBackendData(), ImGui_ImplDX11_SetupRenderState(), ImGui_ImplDX11_UpdateTexture(), ImTextureStatus_OK, ImGui_ImplDX11_Data::IndexBufferSize, ImGui_ImplDX11_Data::pd3dDevice, ImGui_ImplDX11_Data::pd3dDeviceContext, ImGui_ImplDX11_Data::pIB, ImGui_ImplDX11_Data::pTexSamplerLinear, ImGui_ImplDX11_Data::pVB, ImGui_ImplDX11_Data::pVertexConstantBuffer, ImGuiPlatformIO::Renderer_RenderState, ImGui_ImplDX11_RenderState::SamplerDefault, ImVector< T >::Size, ImDrawData::Textures, ImDrawData::TotalIdxCount, ImDrawData::TotalVtxCount, ImDrawCmd::UserCallback, ImGui_ImplDX11_Data::VertexBufferSize, ImGui_ImplDX11_RenderState::VertexConstantBuffer, ImDrawList::VtxBuffer, ImDrawCmd::VtxOffset, ImVec4::w, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by main().
ImGui_ImplDX11_SetupRenderState()
static void ImGui_ImplDX11_SetupRenderState (const ImDrawData * draw_data, ID3D11DeviceContext * device_ctx) static
Definition at line 103 of file imgui_impl_dx11.cpp.
References ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImDrawData::FramebufferScale, ImGui_ImplDX11_GetBackendData(), VERTEX_CONSTANT_BUFFER_DX11::mvp, ImGui_ImplDX11_Data::pBlendState, ImGui_ImplDX11_Data::pDepthStencilState, ImGui_ImplDX11_Data::pIB, ImGui_ImplDX11_Data::pInputLayout, ImGui_ImplDX11_Data::pPixelShader, ImGui_ImplDX11_Data::pRasterizerState, ImGui_ImplDX11_Data::pTexSamplerLinear, ImGui_ImplDX11_Data::pVB, ImGui_ImplDX11_Data::pVertexConstantBuffer, ImGui_ImplDX11_Data::pVertexShader, ImVec2::x, and ImVec2::y.
Referenced by ImGui_ImplDX11_RenderDrawData().
ImGui_ImplDX11_Shutdown()
void ImGui_ImplDX11_Shutdown ()
Definition at line 648 of file imgui_impl_dx11.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGuiPlatformIO::ClearRendererHandlers(), ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplDX11_GetBackendData(), ImGui_ImplDX11_InvalidateDeviceObjects(), ImGuiBackendFlags_RendererHasTextures, ImGuiBackendFlags_RendererHasVtxOffset, ImGui_ImplDX11_Data::pd3dDevice, ImGui_ImplDX11_Data::pd3dDeviceContext, and ImGui_ImplDX11_Data::pFactory.
Referenced by main().
ImGui_ImplDX11_UpdateTexture()
void ImGui_ImplDX11_UpdateTexture (ImTextureData * tex)
Definition at line 358 of file imgui_impl_dx11.cpp.
References ImTextureData::BackendUserData, ImTextureData::Format, ImTextureData::GetPitch(), ImTextureData::GetPixels(), ImTextureData::GetPixelsAt(), ImTextureData::Height, IM_ASSERT, IM_NEW, ImGui_ImplDX11_DestroyTexture(), ImGui_ImplDX11_GetBackendData(), ImTextureFormat_RGBA32, ImTextureID_Invalid, ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImGui_ImplDX11_Data::pd3dDevice, ImGui_ImplDX11_Data::pd3dDeviceContext, ImGui_ImplDX11_Texture::pTexture, ImGui_ImplDX11_Texture::pTextureView, ImTextureData::SetStatus(), ImTextureData::SetTexID(), ImTextureData::Status, ImTextureData::TexID, ImTextureData::UnusedFrames, ImTextureData::Updates, and ImTextureData::Width.
Referenced by ImGui_ImplDX11_RenderDrawData().