SignalProcessing: examples/imgui/examples/example_glfw_vulkan/main.cpp File Reference
main.cpp File Reference
#include "imgui.h"
#include "imgui_impl_glfw.h"
#include "imgui_impl_vulkan.h"
#include <stdio.h>
#include <stdlib.h>
#include <GLFW/glfw3.h>
Macros
#define GLFW_INCLUDE_NONE
#define GLFW_INCLUDE_VULKAN
Functions
static void glfw_error_callback (int error, const char *description)
static void check_vk_result (VkResult err)
static bool IsExtensionAvailable (const ImVector< VkExtensionProperties > &properties, const char *extension)
static void SetupVulkan (ImVector< const char * > instance_extensions)
static void SetupVulkanWindow (ImGui_ImplVulkanH_Window *wd, VkSurfaceKHR surface, int width, int height)
static void CleanupVulkan ()
static void CleanupVulkanWindow ()
static void FrameRender (ImGui_ImplVulkanH_Window *wd, ImDrawData *draw_data)
static void FramePresent (ImGui_ImplVulkanH_Window *wd)
int main (int, char **)
Variables
static VkAllocationCallbacks * g_Allocator = nullptr
static VkInstance g_Instance = VK_NULL_HANDLE
static VkPhysicalDevice g_PhysicalDevice = VK_NULL_HANDLE
static VkDevice g_Device = VK_NULL_HANDLE
static uint32_t g_QueueFamily = (uint32_t)-1
static VkQueue g_Queue = VK_NULL_HANDLE
static VkPipelineCache g_PipelineCache = VK_NULL_HANDLE
static VkDescriptorPool g_DescriptorPool = VK_NULL_HANDLE
static ImGui_ImplVulkanH_Window g_MainWindowData
static uint32_t g_MinImageCount = 2
static bool g_SwapChainRebuild = false
Macro Definition Documentation
GLFW_INCLUDE_NONE
#define GLFW_INCLUDE_NONE
Definition at line 21 of file main.cpp.
GLFW_INCLUDE_VULKAN
#define GLFW_INCLUDE_VULKAN
Definition at line 22 of file main.cpp.
Function Documentation
check_vk_result()
static void check_vk_result (VkResult err) static
Definition at line 62 of file main.cpp.
Referenced by FramePresent(), FrameRender(), main(), and SetupVulkan().
CleanupVulkan()
static void CleanupVulkan () static
Definition at line 245 of file main.cpp.
References g_Allocator, g_DebugReport, g_DescriptorPool, g_Device, and g_Instance.
Referenced by main().
CleanupVulkanWindow()
static void CleanupVulkanWindow () static
Definition at line 259 of file main.cpp.
References g_Allocator, g_Device, g_Instance, g_MainWindowData, and ImGui_ImplVulkanH_DestroyWindow().
Referenced by main().
FramePresent()
static void FramePresent (ImGui_ImplVulkanH_Window * wd) static
Definition at line 329 of file main.cpp.
References check_vk_result(), ImGui_ImplVulkanH_Window::FrameIndex, ImGui_ImplVulkanH_Window::FrameSemaphores, g_Queue, g_SwapChainRebuild, ImGui_ImplVulkanH_Window::SemaphoreCount, ImGui_ImplVulkanH_Window::SemaphoreIndex, and ImGui_ImplVulkanH_Window::Swapchain.
Referenced by main().
FrameRender()
static void FrameRender (ImGui_ImplVulkanH_Window * wd, ImDrawData * draw_data) static
Definition at line 264 of file main.cpp.
References check_vk_result(), ImGui_ImplVulkanH_Window::ClearValue, ImGui_ImplVulkanH_Frame::CommandBuffer, ImGui_ImplVulkanH_Frame::CommandPool, ImGui_ImplVulkanH_Frame::Fence, ImGui_ImplVulkanH_Frame::Framebuffer, ImGui_ImplVulkanH_Window::FrameIndex, ImGui_ImplVulkanH_Window::Frames, ImGui_ImplVulkanH_Window::FrameSemaphores, g_Device, g_Queue, g_SwapChainRebuild, ImGui_ImplVulkanH_Window::Height, ImGui_ImplVulkan_RenderDrawData(), ImGui_ImplVulkanH_Window::RenderPass, ImGui_ImplVulkanH_Window::SemaphoreIndex, ImGui_ImplVulkanH_Window::Swapchain, and ImGui_ImplVulkanH_Window::Width.
Referenced by main().
glfw_error_callback()
static void glfw_error_callback (int error, const char * description) static
Definition at line 58 of file main.cpp.
IsExtensionAvailable()
static bool IsExtensionAvailable (const ImVector< VkExtensionProperties > & properties, const char * extension) static
Definition at line 80 of file main.cpp.
Referenced by SetupVulkan().
main()
int main (int , char **)
Definition at line 352 of file main.cpp.
References ImGui_ImplVulkan_InitInfo::Allocator, ImGui::Begin(), ImGui::Button(), check_vk_result(), ImGui::Checkbox(), ImGui_ImplVulkan_InitInfo::CheckVkResultFn, CleanupVulkan(), CleanupVulkanWindow(), clear_color, ImGui_ImplVulkanH_Window::ClearValue, ImGui::ColorEdit3(), ImGuiIO::ConfigFlags, ImGui::CreateContext(), ImGui_ImplVulkan_InitInfo::DescriptorPool, ImGui::DestroyContext(), ImGui_ImplVulkan_InitInfo::Device, ImDrawData::DisplaySize, ImGui::End(), ImGuiStyle::FontScaleDpi, ImGui_ImplVulkanH_Window::FrameIndex, FramePresent(), ImGuiIO::Framerate, FrameRender(), g_Allocator, g_DescriptorPool, g_Device, g_Instance, g_MainWindowData, g_MinImageCount, g_PhysicalDevice, g_PipelineCache, g_Queue, g_QueueFamily, g_SwapChainRebuild, ImGui::GetDrawData(), ImGui::GetIO(), ImGui::GetStyle(), GLFW_CLIENT_API, glfw_error_callback(), GLFW_ICONIFIED, GLFW_NO_API, glfwCreateWindow(), glfwDestroyWindow(), glfwGetFramebufferSize(), glfwGetPrimaryMonitor(), glfwGetRequiredInstanceExtensions(), glfwGetWindowAttrib(), glfwInit(), glfwPollEvents(), glfwSetErrorCallback(), glfwTerminate(), glfwVulkanSupported(), glfwWindowHint(), glfwWindowShouldClose(), ImGui_ImplVulkanH_Window::Height, ImGui_ImplVulkan_InitInfo::ImageCount, ImGui_ImplVulkanH_Window::ImageCount, IMGUI_CHECKVERSION, ImGui_ImplGlfw_GetContentScaleForMonitor(), ImGui_ImplGlfw_InitForVulkan(), ImGui_ImplGlfw_NewFrame(), ImGui_ImplGlfw_Shutdown(), ImGui_ImplGlfw_Sleep(), ImGui_ImplVulkan_Init(), ImGui_ImplVulkan_NewFrame(), ImGui_ImplVulkan_SetMinImageCount(), ImGui_ImplVulkan_Shutdown(), ImGui_ImplVulkanH_CreateOrResizeWindow(), ImGuiConfigFlags_NavEnableGamepad, ImGuiConfigFlags_NavEnableKeyboard, ImGui_ImplVulkan_InitInfo::Instance, ImGui_ImplVulkan_InitInfo::MinImageCount, ImGui_ImplVulkan_PipelineInfo::MSAASamples, ImGui::NewFrame(), ImGui_ImplVulkan_InitInfo::PhysicalDevice, ImGui_ImplVulkan_InitInfo::PipelineCache, ImGui_ImplVulkan_InitInfo::PipelineInfoMain, ImVector< T >::push_back(), ImGui_ImplVulkan_InitInfo::Queue, ImGui_ImplVulkan_InitInfo::QueueFamily, ImGui::Render(), ImGui_ImplVulkan_PipelineInfo::RenderPass, ImGui_ImplVulkanH_Window::RenderPass, ImGui::SameLine(), ImGuiStyle::ScaleAllSizes(), SetupVulkan(), SetupVulkanWindow(), show_another_window, show_demo_window, ImGui::ShowDemoWindow(), ImGui::SliderFloat(), ImGui::StyleColorsDark(), ImGui_ImplVulkan_PipelineInfo::Subpass, ImGui::Text(), ImVec4::w, ImGui_ImplVulkanH_Window::Width, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
SetupVulkan()
static void SetupVulkan (ImVector< const char * > instance_extensions) static
Definition at line 88 of file main.cpp.
References check_vk_result(), ImVector< T >::Data, g_Allocator, g_DebugReport, g_DescriptorPool, g_Device, g_Instance, g_PhysicalDevice, g_Queue, g_QueueFamily, IM_ARRAYSIZE, IM_ASSERT, IMGUI_IMPL_VULKAN_MINIMUM_IMAGE_SAMPLER_POOL_SIZE, ImGui_ImplVulkanH_SelectPhysicalDevice(), ImGui_ImplVulkanH_SelectQueueFamilyIndex(), IsExtensionAvailable(), ImVector< T >::push_back(), ImVector< T >::resize(), and ImVector< T >::Size.
Referenced by main().
SetupVulkanWindow()
static void SetupVulkanWindow (ImGui_ImplVulkanH_Window * wd, VkSurfaceKHR surface, int width, int height) static
Definition at line 213 of file main.cpp.
References g_Allocator, g_Device, g_Instance, g_MinImageCount, g_PhysicalDevice, g_QueueFamily, IM_ARRAYSIZE, IM_ASSERT, ImGui_ImplVulkanH_CreateOrResizeWindow(), ImGui_ImplVulkanH_SelectPresentMode(), ImGui_ImplVulkanH_SelectSurfaceFormat(), ImGui_ImplVulkanH_Window::PresentMode, ImGui_ImplVulkanH_Window::Surface, and ImGui_ImplVulkanH_Window::SurfaceFormat.
Referenced by main().
Variable Documentation
g_Allocator
VkAllocationCallbacks* g_Allocator = nullptr static
Definition at line 45 of file main.cpp.
Referenced by CleanupVulkan(), CleanupVulkanWindow(), main(), SetupVulkan(), SetupVulkanWindow(), and WndProc().
g_DescriptorPool
VkDescriptorPool g_DescriptorPool = VK_NULL_HANDLE static
Definition at line 52 of file main.cpp.
Referenced by CleanupVulkan(), main(), and SetupVulkan().
g_Device
VkDevice g_Device = VK_NULL_HANDLE static
Definition at line 48 of file main.cpp.
Referenced by CleanupVulkan(), CleanupVulkanWindow(), FrameRender(), main(), SetupVulkan(), SetupVulkanWindow(), and WndProc().
g_Instance
VkInstance g_Instance = VK_NULL_HANDLE static
Definition at line 46 of file main.cpp.
Referenced by CleanupVulkan(), CleanupVulkanWindow(), main(), SetupVulkan(), SetupVulkanWindow(), and WndProc().
g_MainWindowData
ImGui_ImplVulkanH_Window g_MainWindowData static
Definition at line 54 of file main.cpp.
Referenced by CleanupVulkanWindow(), main(), and WndProc().
g_MinImageCount
uint32_t g_MinImageCount = 2 static
Definition at line 55 of file main.cpp.
Referenced by main(), SetupVulkanWindow(), and WndProc().
g_PhysicalDevice
VkPhysicalDevice g_PhysicalDevice = VK_NULL_HANDLE static
Definition at line 47 of file main.cpp.
Referenced by main(), SetupVulkan(), SetupVulkanWindow(), and WndProc().
g_PipelineCache
VkPipelineCache g_PipelineCache = VK_NULL_HANDLE static
Definition at line 51 of file main.cpp.
Referenced by main().
g_Queue
VkQueue g_Queue = VK_NULL_HANDLE static
Definition at line 50 of file main.cpp.
Referenced by FramePresent(), FrameRender(), main(), and SetupVulkan().
g_QueueFamily
uint32_t g_QueueFamily = (uint32_t)-1 static
Definition at line 49 of file main.cpp.
Referenced by main(), SetupVulkan(), SetupVulkanWindow(), and WndProc().
g_SwapChainRebuild
bool g_SwapChainRebuild = false static
Definition at line 56 of file main.cpp.
Referenced by FramePresent(), FrameRender(), main(), and WndProc().