SignalProcessing: examples/imgui/backends/imgui_impl_wgpu.cpp File Reference
imgui_impl_wgpu.cpp File Reference
#include "imgui.h"
#include "imgui_impl_wgpu.h"
#include <limits.h>
#include <stdio.h>
Classes
struct ImGui_ImplWGPU_Texture
struct RenderResources
struct FrameResources
struct Uniforms
struct ImGui_ImplWGPU_Data
Macros
#define MEMALIGN(_SIZE, _ALIGN) (((_SIZE) + ((_ALIGN) - 1)) & ~((_ALIGN) - 1))
Functions
ImGuiID ImHashData (const void *data_p, size_t data_size, ImU32 seed)
static ImGui_ImplWGPU_Data * ImGui_ImplWGPU_GetBackendData ()
static void SafeRelease (ImDrawIdx *&res)
static void SafeRelease (ImDrawVert *&res)
static void SafeRelease (WGPUBindGroupLayout &res)
static void SafeRelease (WGPUBindGroup &res)
static void SafeRelease (WGPUBuffer &res)
static void SafeRelease (WGPUPipelineLayout &res)
static void SafeRelease (WGPURenderPipeline &res)
static void SafeRelease (WGPUSampler &res)
static void SafeRelease (WGPUShaderModule &res)
static void SafeRelease (RenderResources &res)
static void SafeRelease (FrameResources &res)
static WGPUProgrammableStageDescriptor ImGui_ImplWGPU_CreateShaderModule (const char *wgsl_source)
static WGPUBindGroup ImGui_ImplWGPU_CreateImageBindGroup (WGPUBindGroupLayout layout, WGPUTextureView texture)
static void ImGui_ImplWGPU_SetupRenderState (ImDrawData *draw_data, WGPURenderPassEncoder ctx, FrameResources *fr)
void ImGui_ImplWGPU_RenderDrawData (ImDrawData *draw_data, WGPURenderPassEncoder pass_encoder)
static void ImGui_ImplWGPU_DestroyTexture (ImTextureData *tex)
void ImGui_ImplWGPU_UpdateTexture (ImTextureData *tex)
static void ImGui_ImplWGPU_CreateUniformBuffer ()
bool ImGui_ImplWGPU_CreateDeviceObjects ()
void ImGui_ImplWGPU_InvalidateDeviceObjects ()
bool ImGui_ImplWGPU_Init (ImGui_ImplWGPU_InitInfo *init_info)
void ImGui_ImplWGPU_Shutdown ()
void ImGui_ImplWGPU_NewFrame ()
bool ImGui_ImplWGPU_IsSurfaceStatusError (WGPUSurfaceGetCurrentTextureStatus status)
bool ImGui_ImplWGPU_IsSurfaceStatusSubOptimal (WGPUSurfaceGetCurrentTextureStatus status)
const char * ImGui_ImplWGPU_GetLogLevelName (WGPULogLevel level)
const char * ImGui_ImplWGPU_GetBackendTypeName (WGPUBackendType type)
const char * ImGui_ImplWGPU_GetAdapterTypeName (WGPUAdapterType type)
void ImGui_ImplWGPU_DebugPrintAdapterInfo (const WGPUAdapter &adapter)
WGPUSurface ImGui_ImplWGPU_CreateWGPUSurfaceHelper (ImGui_ImplWGPU_CreateSurfaceInfo *info)
Variables
static const char __shader_vert_wgsl []
static const char __shader_frag_wgsl []
Macro Definition Documentation
MEMALIGN
#define MEMALIGN (_SIZE, _ALIGN) (((_SIZE) + ((_ALIGN) - 1)) & ~((_ALIGN) - 1))
Definition at line 76 of file imgui_impl_wgpu.cpp.
Function Documentation
ImGui_ImplWGPU_CreateDeviceObjects()
bool ImGui_ImplWGPU_CreateDeviceObjects ()
Definition at line 655 of file imgui_impl_wgpu.cpp.
References __shader_frag_wgsl, __shader_vert_wgsl, RenderResources::CommonBindGroup, ImGui_ImplWGPU_Data::depthStencilFormat, RenderResources::ImageBindGroupLayout, ImGui_ImplWGPU_CreateShaderModule(), ImGui_ImplWGPU_CreateUniformBuffer(), ImGui_ImplWGPU_GetBackendData(), ImGui_ImplWGPU_InvalidateDeviceObjects(), ImGui_ImplWGPU_Data::initInfo, MEMALIGN, ImGui_ImplWGPU_InitInfo::PipelineMultisampleState, ImGui_ImplWGPU_Data::pipelineState, ImGui_ImplWGPU_Data::renderResources, ImGui_ImplWGPU_Data::renderTargetFormat, SafeRelease(), RenderResources::Sampler, RenderResources::Uniforms, and ImGui_ImplWGPU_Data::wgpuDevice.
Referenced by ImGui_ImplWGPU_NewFrame().
ImGui_ImplWGPU_CreateImageBindGroup()
static WGPUBindGroup ImGui_ImplWGPU_CreateImageBindGroup (WGPUBindGroupLayout layout, WGPUTextureView texture) static
Definition at line 288 of file imgui_impl_wgpu.cpp.
References ImGui_ImplWGPU_GetBackendData(), and ImGui_ImplWGPU_Data::wgpuDevice.
Referenced by ImGui_ImplWGPU_RenderDrawData().
ImGui_ImplWGPU_CreateShaderModule()
static WGPUProgrammableStageDescriptor ImGui_ImplWGPU_CreateShaderModule (const char * wgsl_source) static
Definition at line 260 of file imgui_impl_wgpu.cpp.
References ImGui_ImplWGPU_GetBackendData(), and ImGui_ImplWGPU_Data::wgpuDevice.
Referenced by ImGui_ImplWGPU_CreateDeviceObjects().
ImGui_ImplWGPU_CreateUniformBuffer()
static void ImGui_ImplWGPU_CreateUniformBuffer () static
Definition at line 637 of file imgui_impl_wgpu.cpp.
References ImGui_ImplWGPU_GetBackendData(), MEMALIGN, ImGui_ImplWGPU_Data::renderResources, RenderResources::Uniforms, and ImGui_ImplWGPU_Data::wgpuDevice.
Referenced by ImGui_ImplWGPU_CreateDeviceObjects().
ImGui_ImplWGPU_CreateWGPUSurfaceHelper()
WGPUSurface ImGui_ImplWGPU_CreateWGPUSurfaceHelper (ImGui_ImplWGPU_CreateSurfaceInfo * info)
Definition at line 1027 of file imgui_impl_wgpu.cpp.
References IM_ASSERT, ImGui_ImplWGPU_CreateSurfaceInfo::Instance, ImGui_ImplWGPU_CreateSurfaceInfo::RawDisplay, ImGui_ImplWGPU_CreateSurfaceInfo::RawInstance, ImGui_ImplWGPU_CreateSurfaceInfo::RawSurface, ImGui_ImplWGPU_CreateSurfaceInfo::RawWindow, and ImGui_ImplWGPU_CreateSurfaceInfo::System.
Referenced by CreateWGPUSurface(), CreateWGPUSurface(), and CreateWGPUSurface().
ImGui_ImplWGPU_DebugPrintAdapterInfo()
void ImGui_ImplWGPU_DebugPrintAdapterInfo (const WGPUAdapter & adapter)
Definition at line 1005 of file imgui_impl_wgpu.cpp.
References ImGui_ImplWGPU_GetAdapterTypeName(), and ImGui_ImplWGPU_GetBackendTypeName().
Referenced by InitWGPU(), and InitWGPU().
ImGui_ImplWGPU_DestroyTexture()
static void ImGui_ImplWGPU_DestroyTexture (ImTextureData * tex) static
Definition at line 538 of file imgui_impl_wgpu.cpp.
References ImTextureData::BackendUserData, IM_ASSERT, IM_DELETE(), ImTextureID_Invalid, ImTextureStatus_Destroyed, ImTextureData::SetStatus(), ImTextureData::SetTexID(), and ImTextureData::TexID.
Referenced by ImGui_ImplWGPU_InvalidateDeviceObjects(), and ImGui_ImplWGPU_UpdateTexture().
ImGui_ImplWGPU_GetAdapterTypeName()
const char * ImGui_ImplWGPU_GetAdapterTypeName (WGPUAdapterType type)
Definition at line 994 of file imgui_impl_wgpu.cpp.
Referenced by ImGui_ImplWGPU_DebugPrintAdapterInfo().
ImGui_ImplWGPU_GetBackendData()
static ImGui_ImplWGPU_Data * ImGui_ImplWGPU_GetBackendData () static
Definition at line 127 of file imgui_impl_wgpu.cpp.
References ImGuiIO::BackendRendererUserData, ImGui::GetCurrentContext(), and ImGui::GetIO().
Referenced by ImGui_ImplWGPU_CreateDeviceObjects(), ImGui_ImplWGPU_CreateImageBindGroup(), ImGui_ImplWGPU_CreateShaderModule(), ImGui_ImplWGPU_CreateUniformBuffer(), ImGui_ImplWGPU_InvalidateDeviceObjects(), ImGui_ImplWGPU_NewFrame(), ImGui_ImplWGPU_RenderDrawData(), ImGui_ImplWGPU_SetupRenderState(), ImGui_ImplWGPU_Shutdown(), and ImGui_ImplWGPU_UpdateTexture().
ImGui_ImplWGPU_GetBackendTypeName()
const char * ImGui_ImplWGPU_GetBackendTypeName (WGPUBackendType type)
Definition at line 979 of file imgui_impl_wgpu.cpp.
Referenced by ImGui_ImplWGPU_DebugPrintAdapterInfo().
ImGui_ImplWGPU_GetLogLevelName()
const char * ImGui_ImplWGPU_GetLogLevelName (WGPULogLevel level)
Definition at line 965 of file imgui_impl_wgpu.cpp.
Referenced by InitWGPU(), and InitWGPU().
ImGui_ImplWGPU_Init()
bool ImGui_ImplWGPU_Init (ImGui_ImplWGPU_InitInfo * init_info)
Definition at line 832 of file imgui_impl_wgpu.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, RenderResources::CommonBindGroup, ImGuiStorage::Data, ImGui_ImplWGPU_Data::defaultQueue, ImGui_ImplWGPU_Data::depthStencilFormat, ImGui_ImplWGPU_InitInfo::DepthStencilFormat, ImGui_ImplWGPU_InitInfo::Device, ImGui_ImplWGPU_Data::frameIndex, ImGui::GetIO(), IM_ASSERT, IM_NEW, RenderResources::ImageBindGroupLayout, RenderResources::ImageBindGroups, IMGUI_CHECKVERSION, ImGuiBackendFlags_RendererHasTextures, ImGuiBackendFlags_RendererHasVtxOffset, FrameResources::IndexBuffer, FrameResources::IndexBufferHost, FrameResources::IndexBufferSize, ImGui_ImplWGPU_Data::initInfo, ImGui_ImplWGPU_Data::numFramesInFlight, ImGui_ImplWGPU_InitInfo::NumFramesInFlight, ImGui_ImplWGPU_Data::pFrameResources, ImGui_ImplWGPU_Data::renderResources, ImGui_ImplWGPU_Data::renderTargetFormat, ImGui_ImplWGPU_InitInfo::RenderTargetFormat, ImVector< T >::reserve(), RenderResources::Sampler, RenderResources::Uniforms, FrameResources::VertexBuffer, FrameResources::VertexBufferHost, FrameResources::VertexBufferSize, and ImGui_ImplWGPU_Data::wgpuDevice.
Referenced by main().
ImGui_ImplWGPU_InvalidateDeviceObjects()
void ImGui_ImplWGPU_InvalidateDeviceObjects ()
Definition at line 814 of file imgui_impl_wgpu.cpp.
References ImGui::GetPlatformIO(), ImGui_ImplWGPU_DestroyTexture(), ImGui_ImplWGPU_GetBackendData(), ImGui_ImplWGPU_Data::numFramesInFlight, ImGui_ImplWGPU_Data::pFrameResources, ImGui_ImplWGPU_Data::pipelineState, ImGui_ImplWGPU_Data::renderResources, SafeRelease(), ImGuiPlatformIO::Textures, and ImGui_ImplWGPU_Data::wgpuDevice.
Referenced by ImGui_ImplWGPU_CreateDeviceObjects(), and ImGui_ImplWGPU_Shutdown().
ImGui_ImplWGPU_IsSurfaceStatusError()
bool ImGui_ImplWGPU_IsSurfaceStatusError (WGPUSurfaceGetCurrentTextureStatus status)
Definition at line 922 of file imgui_impl_wgpu.cpp.
Referenced by main().
ImGui_ImplWGPU_IsSurfaceStatusSubOptimal()
bool ImGui_ImplWGPU_IsSurfaceStatusSubOptimal (WGPUSurfaceGetCurrentTextureStatus status)
Definition at line 931 of file imgui_impl_wgpu.cpp.
Referenced by main().
ImGui_ImplWGPU_NewFrame()
void ImGui_ImplWGPU_NewFrame ()
Definition at line 909 of file imgui_impl_wgpu.cpp.
References IM_ASSERT, ImGui_ImplWGPU_CreateDeviceObjects(), ImGui_ImplWGPU_GetBackendData(), and ImGui_ImplWGPU_Data::pipelineState.
Referenced by main().
ImGui_ImplWGPU_RenderDrawData()
void ImGui_ImplWGPU_RenderDrawData (ImDrawData * draw_data, WGPURenderPassEncoder pass_encoder)
Definition at line 368 of file imgui_impl_wgpu.cpp.
References ImDrawCmd::ClipRect, ImDrawList::CmdBuffer, ImDrawData::CmdLists, ImVector< T >::Data, ImGuiStorage::Data, ImGui_ImplWGPU_Data::defaultQueue, ImGui_ImplWGPU_RenderState::Device, ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImDrawCmd::ElemCount, ImDrawData::FramebufferScale, ImGui_ImplWGPU_Data::frameIndex, ImGui::GetPlatformIO(), ImDrawCmd::GetTexID(), ImGuiStorage::GetVoidPtr(), ImDrawList::IdxBuffer, ImDrawCmd::IdxOffset, RenderResources::ImageBindGroupLayout, RenderResources::ImageBindGroups, ImDrawCallback_ResetRenderState, ImGui_ImplWGPU_CreateImageBindGroup(), ImGui_ImplWGPU_GetBackendData(), ImGui_ImplWGPU_SetupRenderState(), ImGui_ImplWGPU_UpdateTexture(), ImHashData(), ImTextureStatus_OK, FrameResources::IndexBuffer, FrameResources::IndexBufferHost, FrameResources::IndexBufferSize, MEMALIGN, ImGui_ImplWGPU_Data::numFramesInFlight, ImGui_ImplWGPU_Data::pFrameResources, ImGuiPlatformIO::Renderer_RenderState, ImGui_ImplWGPU_RenderState::RenderPassEncoder, ImGui_ImplWGPU_Data::renderResources, ImVector< T >::resize(), SafeRelease(), ImGuiStorage::SetVoidPtr(), ImVector< T >::Size, ImDrawData::Textures, ImDrawData::TotalIdxCount, ImDrawData::TotalVtxCount, ImDrawCmd::UserCallback, FrameResources::VertexBuffer, FrameResources::VertexBufferHost, FrameResources::VertexBufferSize, ImDrawList::VtxBuffer, ImDrawCmd::VtxOffset, ImVec4::w, ImGui_ImplWGPU_Data::wgpuDevice, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by main().
ImGui_ImplWGPU_SetupRenderState()
static void ImGui_ImplWGPU_SetupRenderState (ImDrawData * draw_data, WGPURenderPassEncoder ctx, FrameResources * fr) static
Definition at line 300 of file imgui_impl_wgpu.cpp.
References RenderResources::CommonBindGroup, ImGui_ImplWGPU_Data::defaultQueue, ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImDrawData::FramebufferScale, Uniforms::Gamma, ImDrawIdx, ImGui_ImplWGPU_GetBackendData(), FrameResources::IndexBuffer, FrameResources::IndexBufferSize, Uniforms::MVP, ImGui_ImplWGPU_Data::pipelineState, ImGui_ImplWGPU_Data::renderResources, ImGui_ImplWGPU_Data::renderTargetFormat, RenderResources::Uniforms, FrameResources::VertexBuffer, FrameResources::VertexBufferSize, ImVec2::x, and ImVec2::y.
Referenced by ImGui_ImplWGPU_RenderDrawData().
ImGui_ImplWGPU_Shutdown()
void ImGui_ImplWGPU_Shutdown ()
Definition at line 887 of file imgui_impl_wgpu.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGuiPlatformIO::ClearRendererHandlers(), ImGui_ImplWGPU_Data::defaultQueue, ImGui_ImplWGPU_Data::frameIndex, ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplWGPU_GetBackendData(), ImGui_ImplWGPU_InvalidateDeviceObjects(), ImGuiBackendFlags_RendererHasTextures, ImGuiBackendFlags_RendererHasVtxOffset, ImGui_ImplWGPU_Data::numFramesInFlight, ImGui_ImplWGPU_Data::pFrameResources, and ImGui_ImplWGPU_Data::wgpuDevice.
Referenced by main().
ImGui_ImplWGPU_UpdateTexture()
void ImGui_ImplWGPU_UpdateTexture (ImTextureData * tex)
Definition at line 554 of file imgui_impl_wgpu.cpp.
References ImTextureData::BackendUserData, ImTextureData::BytesPerPixel, ImGui_ImplWGPU_Data::defaultQueue, ImTextureData::Format, ImTextureData::GetPixelsAt(), ImTextureRect::h, ImTextureData::Height, IM_ASSERT, IM_NEW, ImGui_ImplWGPU_DestroyTexture(), ImGui_ImplWGPU_GetBackendData(), ImTextureFormat_RGBA32, ImTextureID_Invalid, ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImTextureData::SetStatus(), ImTextureData::SetTexID(), ImTextureData::Status, ImTextureData::TexID, ImGui_ImplWGPU_Texture::Texture, ImGui_ImplWGPU_Texture::TextureView, ImTextureData::UnusedFrames, ImTextureData::UpdateRect, ImTextureRect::w, ImGui_ImplWGPU_Data::wgpuDevice, ImTextureData::Width, ImTextureRect::x, and ImTextureRect::y.
Referenced by ImGui_ImplWGPU_RenderDrawData().
ImHashData()
ImGuiID ImHashData (const void * data_p, size_t data_size, ImU32 seed) extern
Definition at line 2349 of file imgui.cpp.
References GCrc32LookupTable.
Referenced by ImFontAtlasBakedGetId(), and ImGui_ImplWGPU_RenderDrawData().
SafeRelease() [1/11]
static void SafeRelease (FrameResources & res) static
Definition at line 252 of file imgui_impl_wgpu.cpp.
References FrameResources::IndexBuffer, FrameResources::IndexBufferHost, SafeRelease(), FrameResources::VertexBuffer, and FrameResources::VertexBufferHost.
SafeRelease() [2/11]
static void SafeRelease (ImDrawIdx *& res) static
Definition at line 190 of file imgui_impl_wgpu.cpp.
Referenced by ImGui_ImplWGPU_CreateDeviceObjects(), ImGui_ImplWGPU_InvalidateDeviceObjects(), ImGui_ImplWGPU_RenderDrawData(), SafeRelease(), and SafeRelease().
SafeRelease() [3/11]
static void SafeRelease (ImDrawVert *& res) static
Definition at line 196 of file imgui_impl_wgpu.cpp.
SafeRelease() [4/11]
static void SafeRelease (RenderResources & res) static
Definition at line 244 of file imgui_impl_wgpu.cpp.
References RenderResources::CommonBindGroup, RenderResources::ImageBindGroupLayout, SafeRelease(), RenderResources::Sampler, and RenderResources::Uniforms.
SafeRelease() [5/11]
static void SafeRelease (WGPUBindGroup & res) static
Definition at line 208 of file imgui_impl_wgpu.cpp.
SafeRelease() [6/11]
static void SafeRelease (WGPUBindGroupLayout & res) static
Definition at line 202 of file imgui_impl_wgpu.cpp.
SafeRelease() [7/11]
static void SafeRelease (WGPUBuffer & res) static
Definition at line 214 of file imgui_impl_wgpu.cpp.
SafeRelease() [8/11]
static void SafeRelease (WGPUPipelineLayout & res) static
Definition at line 220 of file imgui_impl_wgpu.cpp.
SafeRelease() [9/11]
static void SafeRelease (WGPURenderPipeline & res) static
Definition at line 226 of file imgui_impl_wgpu.cpp.
SafeRelease() [10/11]
static void SafeRelease (WGPUSampler & res) static
Definition at line 232 of file imgui_impl_wgpu.cpp.
SafeRelease() [11/11]
static void SafeRelease (WGPUShaderModule & res) static
Definition at line 238 of file imgui_impl_wgpu.cpp.
Variable Documentation
__shader_frag_wgsl
const char __shader_frag_wgsl[] static
Initial value:
= R"(
struct VertexOutput {
    @builtin(position) position: vec4<f32>,
    @location(0) color: vec4<f32>,
    @location(1) uv: vec2<f32>,
};
struct Uniforms {
    mvp: mat4x4<f32>,
    gamma: f32,
};
@group(0) @binding(0) var<uniform> uniforms: Uniforms;
@group(0) @binding(1) var s: sampler;
@group(1) @binding(0) var t: texture_2d<f32>;
@fragment
fn main(in: VertexOutput) -> @location(0) vec4<f32> {
    let color = in.color * textureSample(t, s, in.uv);
    let corrected_color = pow(color.rgb, vec3<f32>(uniforms.gamma));
    return vec4<f32>(corrected_color, color.a);
}
)"
Definition at line 166 of file imgui_impl_wgpu.cpp.
Referenced by ImGui_ImplWGPU_CreateDeviceObjects().
__shader_vert_wgsl
const char __shader_vert_wgsl[] static
Initial value:
= R"(
struct VertexInput {
    @location(0) position: vec2<f32>,
    @location(1) uv: vec2<f32>,
    @location(2) color: vec4<f32>,
};
struct VertexOutput {
    @builtin(position) position: vec4<f32>,
    @location(0) color: vec4<f32>,
    @location(1) uv: vec2<f32>,
};
struct Uniforms {
    mvp: mat4x4<f32>,
    gamma: f32,
};
@group(0) @binding(0) var<uniform> uniforms: Uniforms;
@vertex
fn main(in: VertexInput) -> VertexOutput {
    var out: VertexOutput;
    out.position = uniforms.mvp * vec4<f32>(in.position, 0.0, 1.0);
    out.color = in.color;
    out.uv = in.uv;
    return out;
}
)"
Definition at line 136 of file imgui_impl_wgpu.cpp.
Referenced by ImGui_ImplWGPU_CreateDeviceObjects().