SignalProcessing: examples/imgui/backends/imgui_impl_sdl3.h File Reference
imgui_impl_sdl3.h File Reference
#include "imgui.h"
Typedefs
typedef union SDL_Event SDL_Event
Enumerations
enum ImGui_ImplSDL3_GamepadMode { ImGui_ImplSDL3_GamepadMode_AutoFirst , ImGui_ImplSDL3_GamepadMode_AutoAll , ImGui_ImplSDL3_GamepadMode_Manual }
Functions
IMGUI_IMPL_API bool ImGui_ImplSDL3_InitForOpenGL (SDL_Window *window, void *sdl_gl_context)
IMGUI_IMPL_API bool ImGui_ImplSDL3_InitForVulkan (SDL_Window *window)
IMGUI_IMPL_API bool ImGui_ImplSDL3_InitForD3D (SDL_Window *window)
IMGUI_IMPL_API bool ImGui_ImplSDL3_InitForMetal (SDL_Window *window)
IMGUI_IMPL_API bool ImGui_ImplSDL3_InitForSDLRenderer (SDL_Window *window, SDL_Renderer *renderer)
IMGUI_IMPL_API bool ImGui_ImplSDL3_InitForSDLGPU (SDL_Window *window)
IMGUI_IMPL_API bool ImGui_ImplSDL3_InitForOther (SDL_Window *window)
IMGUI_IMPL_API void ImGui_ImplSDL3_Shutdown ()
IMGUI_IMPL_API void ImGui_ImplSDL3_NewFrame ()
IMGUI_IMPL_API bool ImGui_ImplSDL3_ProcessEvent (const SDL_Event *event)
IMGUI_IMPL_API void ImGui_ImplSDL3_SetGamepadMode (ImGui_ImplSDL3_GamepadMode mode, SDL_Gamepad **manual_gamepads_array=nullptr, int manual_gamepads_count=-1)
Typedef Documentation
SDL_Event
typedef union SDL_Event SDL_Event
Definition at line 28 of file imgui_impl_sdl3.h.
Enumeration Type Documentation
ImGui_ImplSDL3_GamepadMode
enum ImGui_ImplSDL3_GamepadMode
Enumerator
ImGui_ImplSDL3_GamepadMode_AutoFirst
ImGui_ImplSDL3_GamepadMode_AutoAll
ImGui_ImplSDL3_GamepadMode_Manual
Definition at line 44 of file imgui_impl_sdl3.h.
Function Documentation
ImGui_ImplSDL3_InitForD3D()
IMGUI_IMPL_API bool ImGui_ImplSDL3_InitForD3D (SDL_Window * window)
Definition at line 582 of file imgui_impl_sdl3.cpp.
References IM_ASSERT, and ImGui_ImplSDL3_Init().
Referenced by main().
ImGui_ImplSDL3_InitForMetal()
IMGUI_IMPL_API bool ImGui_ImplSDL3_InitForMetal (SDL_Window * window)
Definition at line 590 of file imgui_impl_sdl3.cpp.
References ImGui_ImplSDL3_Init().
ImGui_ImplSDL3_InitForOpenGL()
IMGUI_IMPL_API bool ImGui_ImplSDL3_InitForOpenGL (SDL_Window * window, void * sdl_gl_context)
Definition at line 571 of file imgui_impl_sdl3.cpp.
References IM_UNUSED, and ImGui_ImplSDL3_Init().
Referenced by main().
ImGui_ImplSDL3_InitForOther()
IMGUI_IMPL_API bool ImGui_ImplSDL3_InitForOther (SDL_Window * window)
Definition at line 605 of file imgui_impl_sdl3.cpp.
References ImGui_ImplSDL3_Init().
Referenced by main().
ImGui_ImplSDL3_InitForSDLGPU()
IMGUI_IMPL_API bool ImGui_ImplSDL3_InitForSDLGPU (SDL_Window * window)
Definition at line 600 of file imgui_impl_sdl3.cpp.
References ImGui_ImplSDL3_Init().
Referenced by main().
ImGui_ImplSDL3_InitForSDLRenderer()
IMGUI_IMPL_API bool ImGui_ImplSDL3_InitForSDLRenderer (SDL_Window * window, SDL_Renderer * renderer)
Definition at line 595 of file imgui_impl_sdl3.cpp.
References ImGui_ImplSDL3_Init().
Referenced by main().
ImGui_ImplSDL3_InitForVulkan()
IMGUI_IMPL_API bool ImGui_ImplSDL3_InitForVulkan (SDL_Window * window)
Definition at line 577 of file imgui_impl_sdl3.cpp.
References ImGui_ImplSDL3_Init().
Referenced by main().
ImGui_ImplSDL3_NewFrame()
IMGUI_IMPL_API void ImGui_ImplSDL3_NewFrame ()
Definition at line 832 of file imgui_impl_sdl3.cpp.
References ImGuiIO::AddMousePosEvent(), ImGuiIO::DeltaTime, ImGuiIO::DisplayFramebufferScale, ImGuiIO::DisplaySize, frequency, ImGui::GetFrameCount(), ImGui::GetIO(), IM_ASSERT, ImGui_ImplSDL3_GetBackendData(), ImGui_ImplSDL3_GetWindowSizeAndFramebufferScale(), ImGui_ImplSDL3_UpdateGamepads(), ImGui_ImplSDL3_UpdateIme(), ImGui_ImplSDL3_UpdateMouseCursor(), ImGui_ImplSDL3_UpdateMouseData(), ImGui_ImplSDL3_Data::MouseButtonsDown, ImGui_ImplSDL3_Data::MousePendingLeaveFrame, ImGui_ImplSDL3_Data::MouseWindowID, ImGui_ImplSDL3_Data::Time, and ImGui_ImplSDL3_Data::Window.
Referenced by main().
ImGui_ImplSDL3_ProcessEvent()
IMGUI_IMPL_API bool ImGui_ImplSDL3_ProcessEvent (const SDL_Event * event)
Definition at line 376 of file imgui_impl_sdl3.cpp.
References ImGuiIO::AddFocusEvent(), ImGuiIO::AddInputCharactersUTF8(), ImGuiIO::AddKeyEvent(), ImGuiIO::AddMouseButtonEvent(), ImGuiIO::AddMousePosEvent(), ImGuiIO::AddMouseSourceEvent(), ImGuiIO::AddMouseWheelEvent(), ImGui::GetFrameCount(), ImGui::GetIO(), IM_ASSERT, ImGui_ImplSDL3_GetBackendData(), ImGui_ImplSDL3_GetViewportForWindowID(), ImGui_ImplSDL3_KeyEventToImGuiKey(), ImGui_ImplSDL3_UpdateKeyModifiers(), ImGuiMouseSource_Mouse, ImGuiMouseSource_TouchScreen, ImGui_ImplSDL3_Data::MouseButtonsDown, ImGui_ImplSDL3_Data::MousePendingLeaveFrame, ImGui_ImplSDL3_Data::MouseWindowID, ImGuiIO::SetKeyEventNativeData(), ImGui_ImplSDL3_Data::WantUpdateGamepadsList, ImVec2::x, and ImVec2::y.
Referenced by main().
ImGui_ImplSDL3_SetGamepadMode()
IMGUI_IMPL_API void ImGui_ImplSDL3_SetGamepadMode (ImGui_ImplSDL3_GamepadMode mode, SDL_Gamepad ** manual_gamepads_array = nullptr, int manual_gamepads_count = -1)
Definition at line 715 of file imgui_impl_sdl3.cpp.
References ImGui_ImplSDL3_Data::GamepadMode, ImGui_ImplSDL3_Data::Gamepads, IM_ASSERT, ImGui_ImplSDL3_CloseGamepads(), ImGui_ImplSDL3_GamepadMode_Manual, ImGui_ImplSDL3_GetBackendData(), ImVector< T >::push_back(), and ImGui_ImplSDL3_Data::WantUpdateGamepadsList.
ImGui_ImplSDL3_Shutdown()
IMGUI_IMPL_API void ImGui_ImplSDL3_Shutdown ()
Definition at line 612 of file imgui_impl_sdl3.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendPlatformName, ImGuiIO::BackendPlatformUserData, ImGuiPlatformIO::ClearPlatformHandlers(), ImGui_ImplSDL3_Data::ClipboardTextData, ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplSDL3_CloseGamepads(), ImGui_ImplSDL3_GetBackendData(), ImGuiBackendFlags_HasGamepad, ImGuiBackendFlags_HasMouseCursors, ImGuiBackendFlags_HasSetMousePos, ImGuiMouseCursor_COUNT, and ImGui_ImplSDL3_Data::MouseCursors.
Referenced by main().