SignalProcessing: examples/imgui/backends/imgui_impl_dx12.cpp File Reference
imgui_impl_dx12.cpp File Reference
#include "imgui.h"
#include "imgui_impl_dx12.h"
#include <d3d12.h>
#include <dxgi1_5.h>
#include <d3dcompiler.h>
Classes
struct ImGui_ImplDX12_Texture
struct ImGui_ImplDX12_Data
struct ImGui_ImplDX12_RenderBuffers
struct VERTEX_CONSTANT_BUFFER_DX12
Typedefs
typedef decltype(D3D12SerializeRootSignature) * _PFN_D3D12_SERIALIZE_ROOT_SIGNATURE
Functions
static ImGui_ImplDX12_Data * ImGui_ImplDX12_GetBackendData ()
static void ImGui_ImplDX12_SetupRenderState (ImDrawData *draw_data, ID3D12GraphicsCommandList *command_list, ImGui_ImplDX12_RenderBuffers *fr)
template<typename T >
static void SafeRelease (T *&res)
void ImGui_ImplDX12_RenderDrawData (ImDrawData *draw_data, ID3D12GraphicsCommandList *command_list)
static void ImGui_ImplDX12_DestroyTexture (ImTextureData *tex)
void ImGui_ImplDX12_UpdateTexture (ImTextureData *tex)
bool ImGui_ImplDX12_CreateDeviceObjects ()
void ImGui_ImplDX12_InvalidateDeviceObjects ()
static void ImGui_ImplDX12_InitLegacySingleDescriptorMode (ImGui_ImplDX12_InitInfo *init_info)
bool ImGui_ImplDX12_Init (ImGui_ImplDX12_InitInfo *init_info)
bool ImGui_ImplDX12_Init (ID3D12Device *device, int num_frames_in_flight, DXGI_FORMAT rtv_format, ID3D12DescriptorHeap *srv_descriptor_heap, D3D12_CPU_DESCRIPTOR_HANDLE font_srv_cpu_desc_handle, D3D12_GPU_DESCRIPTOR_HANDLE font_srv_gpu_desc_handle)
void ImGui_ImplDX12_Shutdown ()
void ImGui_ImplDX12_NewFrame ()
Typedef Documentation
_PFN_D3D12_SERIALIZE_ROOT_SIGNATURE
typedef decltype(D3D12SerializeRootSignature) * _PFN_D3D12_SERIALIZE_ROOT_SIGNATURE
Definition at line 77 of file imgui_impl_dx12.cpp.
Function Documentation
ImGui_ImplDX12_CreateDeviceObjects()
bool ImGui_ImplDX12_CreateDeviceObjects ()
Definition at line 553 of file imgui_impl_dx12.cpp.
References ImGui_ImplDX12_Data::DSVFormat, ImGui_ImplDX12_Data::Fence, ImGui_ImplDX12_Data::FenceEvent, IM_ARRAYSIZE, IM_ASSERT, ImGui_ImplDX12_GetBackendData(), ImGui_ImplDX12_InvalidateDeviceObjects(), ImGui_ImplDX12_Data::pd3dDevice, ImGui_ImplDX12_Data::pdxgiFactory, ImGui_ImplDX12_Data::pPipelineState, ImGui_ImplDX12_Data::pRootSignature, ImGui_ImplDX12_Data::pTexCmdAllocator, ImGui_ImplDX12_Data::pTexCmdList, ImGui_ImplDX12_Data::RTVFormat, and ImGui_ImplDX12_Data::tearingSupport.
Referenced by ImGui_ImplDX12_NewFrame().
ImGui_ImplDX12_DestroyTexture()
static void ImGui_ImplDX12_DestroyTexture (ImTextureData * tex) static
Definition at line 350 of file imgui_impl_dx12.cpp.
References ImTextureData::BackendUserData, IM_ASSERT, IM_DELETE(), ImGui_ImplDX12_GetBackendData(), ImTextureID_Invalid, ImTextureStatus_Destroyed, ImGui_ImplDX12_Data::InitInfo, SafeRelease(), ImTextureData::SetStatus(), ImTextureData::SetTexID(), ImGui_ImplDX12_InitInfo::SrvDescriptorFreeFn, and ImTextureData::TexID.
Referenced by ImGui_ImplDX12_InvalidateDeviceObjects(), and ImGui_ImplDX12_UpdateTexture().
ImGui_ImplDX12_GetBackendData()
static ImGui_ImplDX12_Data * ImGui_ImplDX12_GetBackendData () static
Definition at line 124 of file imgui_impl_dx12.cpp.
References ImGuiIO::BackendRendererUserData, ImGui::GetCurrentContext(), and ImGui::GetIO().
Referenced by ImGui_ImplDX12_CreateDeviceObjects(), ImGui_ImplDX12_DestroyTexture(), ImGui_ImplDX12_Init(), ImGui_ImplDX12_InitLegacySingleDescriptorMode(), ImGui_ImplDX12_InvalidateDeviceObjects(), ImGui_ImplDX12_NewFrame(), ImGui_ImplDX12_RenderDrawData(), ImGui_ImplDX12_SetupRenderState(), ImGui_ImplDX12_Shutdown(), and ImGui_ImplDX12_UpdateTexture().
ImGui_ImplDX12_Init() [1/2]
bool ImGui_ImplDX12_Init (ID3D12Device * device, int num_frames_in_flight, DXGI_FORMAT rtv_format, ID3D12DescriptorHeap * srv_descriptor_heap, D3D12_CPU_DESCRIPTOR_HANDLE font_srv_cpu_desc_handle, D3D12_GPU_DESCRIPTOR_HANDLE font_srv_gpu_desc_handle)
Definition at line 915 of file imgui_impl_dx12.cpp.
References ImGuiIO::BackendFlags, ImGui_ImplDX12_InitInfo::CommandQueue, ImGui_ImplDX12_Data::commandQueueOwned, ImGui_ImplDX12_InitInfo::Device, ImGui::GetIO(), IM_ASSERT, ImGui_ImplDX12_GetBackendData(), ImGui_ImplDX12_Init(), ImGui_ImplDX12_InitInfo::LegacySingleSrvCpuDescriptor, ImGui_ImplDX12_InitInfo::LegacySingleSrvGpuDescriptor, ImGui_ImplDX12_InitInfo::NumFramesInFlight, ImGui_ImplDX12_InitInfo::RTVFormat, and ImGui_ImplDX12_InitInfo::SrvDescriptorHeap.
ImGui_ImplDX12_Init() [2/2]
bool ImGui_ImplDX12_Init (ImGui_ImplDX12_InitInfo * init_info)
Definition at line 866 of file imgui_impl_dx12.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGui_ImplDX12_InitInfo::CommandQueue, ImGui_ImplDX12_InitInfo::Device, ImGui_ImplDX12_Data::DSVFormat, ImGui_ImplDX12_InitInfo::DSVFormat, ImGui_ImplDX12_Data::frameIndex, ImGui::GetIO(), IM_ASSERT, IM_NEW, IMGUI_CHECKVERSION, ImGui_ImplDX12_InitLegacySingleDescriptorMode(), ImGuiBackendFlags_RendererHasTextures, ImGuiBackendFlags_RendererHasVtxOffset, ImGui_ImplDX12_RenderBuffers::IndexBuffer, ImGui_ImplDX12_RenderBuffers::IndexBufferSize, ImGui_ImplDX12_Data::InitInfo, ImGui_ImplDX12_Data::numFramesInFlight, ImGui_ImplDX12_InitInfo::NumFramesInFlight, ImGui_ImplDX12_Data::pCommandQueue, ImGui_ImplDX12_Data::pd3dDevice, ImGui_ImplDX12_Data::pd3dSrvDescHeap, ImGui_ImplDX12_Data::pFrameResources, ImGui_ImplDX12_Data::RTVFormat, ImGui_ImplDX12_InitInfo::RTVFormat, ImGui_ImplDX12_InitInfo::SrvDescriptorAllocFn, ImGui_ImplDX12_InitInfo::SrvDescriptorFreeFn, ImGui_ImplDX12_InitInfo::SrvDescriptorHeap, ImGui_ImplDX12_Data::tearingSupport, ImGui_ImplDX12_RenderBuffers::VertexBuffer, and ImGui_ImplDX12_RenderBuffers::VertexBufferSize.
Referenced by ImGui_ImplDX12_Init(), and main().
ImGui_ImplDX12_InitLegacySingleDescriptorMode()
static void ImGui_ImplDX12_InitLegacySingleDescriptorMode (ImGui_ImplDX12_InitInfo * init_info) static
Definition at line 845 of file imgui_impl_dx12.cpp.
References IM_ASSERT, ImGui_ImplDX12_GetBackendData(), ImGui_ImplDX12_Data::InitInfo, ImGui_ImplDX12_Data::LegacySingleDescriptorUsed, ImGui_ImplDX12_InitInfo::LegacySingleSrvCpuDescriptor, ImGui_ImplDX12_InitInfo::LegacySingleSrvGpuDescriptor, ImGui_ImplDX12_InitInfo::SrvDescriptorAllocFn, and ImGui_ImplDX12_InitInfo::SrvDescriptorFreeFn.
Referenced by ImGui_ImplDX12_Init().
ImGui_ImplDX12_InvalidateDeviceObjects()
void ImGui_ImplDX12_InvalidateDeviceObjects ()
Definition at line 806 of file imgui_impl_dx12.cpp.
References ImGui_ImplDX12_Data::commandQueueOwned, ImGui_ImplDX12_Data::Fence, ImGui_ImplDX12_Data::FenceEvent, ImGui::GetPlatformIO(), ImGui_ImplDX12_DestroyTexture(), ImGui_ImplDX12_GetBackendData(), ImGui_ImplDX12_RenderBuffers::IndexBuffer, ImGui_ImplDX12_Data::numFramesInFlight, ImGui_ImplDX12_Data::pCommandQueue, ImGui_ImplDX12_Data::pd3dDevice, ImGui_ImplDX12_Data::pdxgiFactory, ImGui_ImplDX12_Data::pFrameResources, ImGui_ImplDX12_Data::pPipelineState, ImGui_ImplDX12_Data::pRootSignature, ImGui_ImplDX12_Data::pTexCmdAllocator, ImGui_ImplDX12_Data::pTexCmdList, ImGui_ImplDX12_Data::pTexUploadBuffer, ImGui_ImplDX12_Data::pTexUploadBufferMapped, ImGui_ImplDX12_Data::pTexUploadBufferSize, SafeRelease(), ImGuiPlatformIO::Textures, and ImGui_ImplDX12_RenderBuffers::VertexBuffer.
Referenced by ImGui_ImplDX12_CreateDeviceObjects(), and ImGui_ImplDX12_Shutdown().
ImGui_ImplDX12_NewFrame()
void ImGui_ImplDX12_NewFrame ()
Definition at line 959 of file imgui_impl_dx12.cpp.
References IM_ASSERT, ImGui_ImplDX12_CreateDeviceObjects(), ImGui_ImplDX12_GetBackendData(), and ImGui_ImplDX12_Data::pPipelineState.
Referenced by main().
ImGui_ImplDX12_RenderDrawData()
void ImGui_ImplDX12_RenderDrawData (ImDrawData * draw_data, ID3D12GraphicsCommandList * command_list)
Definition at line 207 of file imgui_impl_dx12.cpp.
References ImDrawCmd::ClipRect, ImDrawList::CmdBuffer, ImDrawData::CmdLists, ImGui_ImplDX12_RenderState::CommandList, ImVector< T >::Data, ImGui_ImplDX12_RenderState::Device, ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImDrawCmd::ElemCount, ImDrawData::FramebufferScale, ImGui_ImplDX12_Data::frameIndex, ImGui::GetPlatformIO(), ImDrawCmd::GetTexID(), ImDrawList::IdxBuffer, ImDrawCmd::IdxOffset, IM_ASSERT, ImDrawCallback_ResetRenderState, ImDrawIdx, ImGui_ImplDX12_GetBackendData(), ImGui_ImplDX12_SetupRenderState(), ImGui_ImplDX12_UpdateTexture(), ImTextureStatus_OK, ImGui_ImplDX12_RenderBuffers::IndexBuffer, ImGui_ImplDX12_RenderBuffers::IndexBufferSize, ImGui_ImplDX12_Data::numFramesInFlight, ImGui_ImplDX12_Data::pd3dDevice, ImGui_ImplDX12_Data::pFrameResources, ImGuiPlatformIO::Renderer_RenderState, SafeRelease(), ImVector< T >::Size, ImDrawData::Textures, ImDrawData::TotalIdxCount, ImDrawData::TotalVtxCount, ImDrawCmd::UserCallback, ImGui_ImplDX12_RenderBuffers::VertexBuffer, ImGui_ImplDX12_RenderBuffers::VertexBufferSize, ImDrawList::VtxBuffer, ImDrawCmd::VtxOffset, ImVec4::w, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by main().
ImGui_ImplDX12_SetupRenderState()
static void ImGui_ImplDX12_SetupRenderState (ImDrawData * draw_data, ID3D12GraphicsCommandList * command_list, ImGui_ImplDX12_RenderBuffers * fr) static
Definition at line 144 of file imgui_impl_dx12.cpp.
References ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImDrawData::FramebufferScale, ImDrawIdx, ImGui_ImplDX12_GetBackendData(), ImGui_ImplDX12_RenderBuffers::IndexBuffer, ImGui_ImplDX12_RenderBuffers::IndexBufferSize, VERTEX_CONSTANT_BUFFER_DX12::mvp, ImGui_ImplDX12_Data::pPipelineState, ImGui_ImplDX12_Data::pRootSignature, ImGui_ImplDX12_RenderBuffers::VertexBuffer, ImGui_ImplDX12_RenderBuffers::VertexBufferSize, ImVec2::x, and ImVec2::y.
Referenced by ImGui_ImplDX12_RenderDrawData().
ImGui_ImplDX12_Shutdown()
void ImGui_ImplDX12_Shutdown ()
Definition at line 942 of file imgui_impl_dx12.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGuiPlatformIO::ClearRendererHandlers(), ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplDX12_GetBackendData(), ImGui_ImplDX12_InvalidateDeviceObjects(), ImGuiBackendFlags_RendererHasTextures, ImGuiBackendFlags_RendererHasVtxOffset, and ImGui_ImplDX12_Data::pFrameResources.
Referenced by main().
ImGui_ImplDX12_UpdateTexture()
void ImGui_ImplDX12_UpdateTexture (ImTextureData * tex)
Definition at line 369 of file imgui_impl_dx12.cpp.
References ImTextureData::BackendUserData, ImTextureData::BytesPerPixel, ImGui_ImplDX12_Data::Fence, ImGui_ImplDX12_Data::FenceEvent, ImGui_ImplDX12_Data::FenceLastSignaledValue, ImTextureData::Format, ImTextureData::GetPixelsAt(), ImTextureRect::h, ImTextureData::Height, ImGui_ImplDX12_Texture::hFontSrvCpuDescHandle, ImGui_ImplDX12_Texture::hFontSrvGpuDescHandle, IM_ASSERT, IM_NEW, ImGui_ImplDX12_DestroyTexture(), ImGui_ImplDX12_GetBackendData(), ImTextureFormat_RGBA32, ImTextureID_Invalid, ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImGui_ImplDX12_Data::InitInfo, ImGui_ImplDX12_Data::numFramesInFlight, ImGui_ImplDX12_Data::pCommandQueue, ImGui_ImplDX12_Data::pd3dDevice, ImGui_ImplDX12_Data::pTexCmdAllocator, ImGui_ImplDX12_Data::pTexCmdList, ImGui_ImplDX12_Texture::pTextureResource, ImGui_ImplDX12_Data::pTexUploadBuffer, ImGui_ImplDX12_Data::pTexUploadBufferMapped, ImGui_ImplDX12_Data::pTexUploadBufferSize, SafeRelease(), ImTextureData::SetStatus(), ImTextureData::SetTexID(), ImGui_ImplDX12_InitInfo::SrvDescriptorAllocFn, ImTextureData::Status, ImTextureData::TexID, ImTextureData::UnusedFrames, ImTextureData::UpdateRect, ImTextureRect::w, ImTextureData::Width, ImTextureRect::x, and ImTextureRect::y.
Referenced by ImGui_ImplDX12_RenderDrawData().
SafeRelease()
template<typename T > static void SafeRelease (T *& res) inline static
Definition at line 199 of file imgui_impl_dx12.cpp.
Referenced by ImGui_ImplDX12_DestroyTexture(), ImGui_ImplDX12_InvalidateDeviceObjects(), ImGui_ImplDX12_RenderDrawData(), and ImGui_ImplDX12_UpdateTexture().