SignalProcessing: examples/imgui/examples/example_win32_directx12/main.cpp File Reference
main.cpp File Reference
#include "imgui.h"
#include "imgui_impl_win32.h"
#include "imgui_impl_dx12.h"
#include <d3d12.h>
#include <dxgi1_5.h>
#include <tchar.h>
Classes
struct FrameContext
struct ExampleDescriptorHeapAllocator
Functions
bool CreateDeviceD3D (HWND hWnd)
void CleanupDeviceD3D ()
void CreateRenderTarget ()
void CleanupRenderTarget ()
void WaitForPendingOperations ()
FrameContext * WaitForNextFrameContext ()
LRESULT WINAPI WndProc (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam)
int main (int, char **)
IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam)
Variables
static const int APP_NUM_FRAMES_IN_FLIGHT = 2
static const int APP_NUM_BACK_BUFFERS = 2
static const int APP_SRV_HEAP_SIZE = 64
static FrameContext g_frameContext [APP_NUM_FRAMES_IN_FLIGHT] = {}
static UINT g_frameIndex = 0
static ID3D12Device * g_pd3dDevice = nullptr
static ID3D12DescriptorHeap * g_pd3dRtvDescHeap = nullptr
static ID3D12DescriptorHeap * g_pd3dSrvDescHeap = nullptr
static ExampleDescriptorHeapAllocator g_pd3dSrvDescHeapAlloc
static ID3D12CommandQueue * g_pd3dCommandQueue = nullptr
static ID3D12GraphicsCommandList * g_pd3dCommandList = nullptr
static ID3D12Fence * g_fence = nullptr
static HANDLE g_fenceEvent = nullptr
static UINT64 g_fenceLastSignaledValue = 0
static IDXGISwapChain3 * g_pSwapChain = nullptr
static bool g_SwapChainTearingSupport = false
static bool g_SwapChainOccluded = false
static HANDLE g_hSwapChainWaitableObject = nullptr
static ID3D12Resource * g_mainRenderTargetResource [APP_NUM_BACK_BUFFERS] = {}
static D3D12_CPU_DESCRIPTOR_HANDLE g_mainRenderTargetDescriptor [APP_NUM_BACK_BUFFERS] = {}
Function Documentation
CleanupDeviceD3D()
void CleanupDeviceD3D ()
Definition at line 449 of file main.cpp.
References APP_NUM_FRAMES_IN_FLIGHT, CleanupRenderTarget(), FrameContext::CommandAllocator, g_fence, g_fenceEvent, g_frameContext, g_hSwapChainWaitableObject, g_pd3dCommandList, g_pd3dCommandQueue, g_pd3dDevice, g_pd3dRtvDescHeap, g_pd3dSrvDescHeap, and g_pSwapChain.
CleanupRenderTarget()
void CleanupRenderTarget ()
Definition at line 485 of file main.cpp.
References APP_NUM_BACK_BUFFERS, g_mainRenderTargetResource, and WaitForPendingOperations().
CreateDeviceD3D()
bool CreateDeviceD3D (HWND hWnd)
Definition at line 312 of file main.cpp.
References APP_NUM_BACK_BUFFERS, APP_NUM_FRAMES_IN_FLIGHT, APP_SRV_HEAP_SIZE, FrameContext::CommandAllocator, ExampleDescriptorHeapAllocator::Create(), CreateRenderTarget(), g_fence, g_fenceEvent, g_frameContext, g_hSwapChainWaitableObject, g_mainRenderTargetDescriptor, g_pd3dCommandList, g_pd3dCommandQueue, g_pd3dDevice, g_pd3dRtvDescHeap, g_pd3dSrvDescHeap, g_pd3dSrvDescHeapAlloc, g_pSwapChain, and g_SwapChainTearingSupport.
CreateRenderTarget()
void CreateRenderTarget ()
Definition at line 474 of file main.cpp.
References APP_NUM_BACK_BUFFERS, g_mainRenderTargetDescriptor, g_mainRenderTargetResource, g_pd3dDevice, and g_pSwapChain.
ImGui_ImplWin32_WndProcHandler()
IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam) extern
Definition at line 619 of file imgui_impl_win32.cpp.
main()
int main (int , char **)
Definition at line 111 of file main.cpp.
References ExampleDescriptorHeapAllocator::Alloc(), APP_NUM_FRAMES_IN_FLIGHT, ImGui::Begin(), ImGui::Button(), ImGui::Checkbox(), CleanupDeviceD3D(), clear_color, ImGui::ColorEdit3(), FrameContext::CommandAllocator, ImGui_ImplDX12_InitInfo::CommandQueue, ImGuiIO::ConfigFlags, ImGui::CreateContext(), CreateDeviceD3D(), ImGui::DestroyContext(), ImGui_ImplDX12_InitInfo::Device, ImGui_ImplDX12_InitInfo::DSVFormat, ImGui::End(), FrameContext::FenceValue, ImGuiStyle::FontScaleDpi, ImGuiIO::Framerate, ExampleDescriptorHeapAllocator::Free(), g_fence, g_fenceLastSignaledValue, g_frameIndex, g_mainRenderTargetDescriptor, g_mainRenderTargetResource, g_pd3dCommandList, g_pd3dCommandQueue, g_pd3dDevice, g_pd3dSrvDescHeap, g_pd3dSrvDescHeapAlloc, g_pSwapChain, g_SwapChainOccluded, ImGui::GetDrawData(), ImGui::GetIO(), ImGui::GetStyle(), IMGUI_CHECKVERSION, ImGui_ImplDX12_Init(), ImGui_ImplDX12_NewFrame(), ImGui_ImplDX12_RenderDrawData(), ImGui_ImplDX12_Shutdown(), ImGui_ImplWin32_EnableDpiAwareness(), ImGui_ImplWin32_GetDpiScaleForMonitor(), ImGui_ImplWin32_Init(), ImGui_ImplWin32_NewFrame(), ImGui_ImplWin32_Shutdown(), ImGuiConfigFlags_NavEnableGamepad, ImGuiConfigFlags_NavEnableKeyboard, ImGui::NewFrame(), ImGui_ImplDX12_InitInfo::NumFramesInFlight, ImGui::Render(), ImGui_ImplDX12_InitInfo::RTVFormat, ImGui::SameLine(), ImGuiStyle::ScaleAllSizes(), show_another_window, show_demo_window, ImGui::ShowDemoWindow(), ImGui::SliderFloat(), ImGui_ImplDX12_InitInfo::SrvDescriptorAllocFn, ImGui_ImplDX12_InitInfo::SrvDescriptorFreeFn, ImGui_ImplDX12_InitInfo::SrvDescriptorHeap, ImGui::StyleColorsDark(), ImGui::Text(), ImVec4::w, WaitForNextFrameContext(), WaitForPendingOperations(), WndProc(), ImVec4::x, ImVec4::y, and ImVec4::z.
WaitForNextFrameContext()
FrameContext * WaitForNextFrameContext ()
Definition at line 501 of file main.cpp.
References APP_NUM_FRAMES_IN_FLIGHT, FrameContext::FenceValue, g_fence, g_fenceEvent, g_frameContext, g_frameIndex, and g_hSwapChainWaitableObject.
Referenced by main().
WaitForPendingOperations()
void WaitForPendingOperations ()
Definition at line 493 of file main.cpp.
References g_fence, g_fenceEvent, g_fenceLastSignaledValue, and g_pd3dCommandQueue.
Referenced by CleanupRenderTarget(), and main().
WndProc()
LRESULT WINAPI WndProc (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam)
Definition at line 524 of file main.cpp.
References CleanupRenderTarget(), CreateRenderTarget(), g_pd3dDevice, g_pSwapChain, IM_ASSERT, and ImGui_ImplWin32_WndProcHandler().
Variable Documentation
APP_NUM_BACK_BUFFERS
const int APP_NUM_BACK_BUFFERS = 2 static
Definition at line 27 of file main.cpp.
Referenced by CleanupRenderTarget(), CreateDeviceD3D(), and CreateRenderTarget().
APP_NUM_FRAMES_IN_FLIGHT
const int APP_NUM_FRAMES_IN_FLIGHT = 2 static
Definition at line 26 of file main.cpp.
Referenced by CleanupDeviceD3D(), CreateDeviceD3D(), main(), and WaitForNextFrameContext().
APP_SRV_HEAP_SIZE
const int APP_SRV_HEAP_SIZE = 64 static
Definition at line 28 of file main.cpp.
Referenced by CreateDeviceD3D().
g_fence
ID3D12Fence* g_fence = nullptr static
Definition at line 91 of file main.cpp.
Referenced by CleanupDeviceD3D(), CreateDeviceD3D(), main(), WaitForNextFrameContext(), and WaitForPendingOperations().
g_fenceEvent
HANDLE g_fenceEvent = nullptr static
Definition at line 92 of file main.cpp.
Referenced by CleanupDeviceD3D(), CreateDeviceD3D(), WaitForNextFrameContext(), and WaitForPendingOperations().
g_fenceLastSignaledValue
UINT64 g_fenceLastSignaledValue = 0 static
Definition at line 93 of file main.cpp.
Referenced by main(), and WaitForPendingOperations().
g_frameContext
FrameContext g_frameContext[APP_NUM_FRAMES_IN_FLIGHT] = {} static
Definition at line 82 of file main.cpp.
Referenced by CleanupDeviceD3D(), CreateDeviceD3D(), and WaitForNextFrameContext().
g_frameIndex
UINT g_frameIndex = 0 static
Definition at line 83 of file main.cpp.
Referenced by main(), and WaitForNextFrameContext().
g_hSwapChainWaitableObject
HANDLE g_hSwapChainWaitableObject = nullptr static
Definition at line 97 of file main.cpp.
Referenced by CleanupDeviceD3D(), CreateDeviceD3D(), and WaitForNextFrameContext().
g_mainRenderTargetDescriptor
D3D12_CPU_DESCRIPTOR_HANDLE g_mainRenderTargetDescriptor[APP_NUM_BACK_BUFFERS] = {} static
Definition at line 99 of file main.cpp.
Referenced by CreateDeviceD3D(), CreateRenderTarget(), and main().
g_mainRenderTargetResource
ID3D12Resource* g_mainRenderTargetResource[APP_NUM_BACK_BUFFERS] = {} static
Definition at line 98 of file main.cpp.
Referenced by CleanupRenderTarget(), CreateRenderTarget(), and main().
g_pd3dCommandList
ID3D12GraphicsCommandList* g_pd3dCommandList = nullptr static
Definition at line 90 of file main.cpp.
Referenced by CleanupDeviceD3D(), CreateDeviceD3D(), and main().
g_pd3dCommandQueue
ID3D12CommandQueue* g_pd3dCommandQueue = nullptr static
Definition at line 89 of file main.cpp.
Referenced by CleanupDeviceD3D(), CreateDeviceD3D(), main(), and WaitForPendingOperations().
g_pd3dDevice
ID3D12Device* g_pd3dDevice = nullptr static
Definition at line 85 of file main.cpp.
g_pd3dRtvDescHeap
ID3D12DescriptorHeap* g_pd3dRtvDescHeap = nullptr static
Definition at line 86 of file main.cpp.
Referenced by CleanupDeviceD3D(), and CreateDeviceD3D().
g_pd3dSrvDescHeap
ID3D12DescriptorHeap* g_pd3dSrvDescHeap = nullptr static
Definition at line 87 of file main.cpp.
Referenced by CleanupDeviceD3D(), CreateDeviceD3D(), and main().
g_pd3dSrvDescHeapAlloc
ExampleDescriptorHeapAllocator g_pd3dSrvDescHeapAlloc static
Definition at line 88 of file main.cpp.
Referenced by CreateDeviceD3D(), and main().
g_pSwapChain
IDXGISwapChain3* g_pSwapChain = nullptr static
Definition at line 94 of file main.cpp.
g_SwapChainOccluded
bool g_SwapChainOccluded = false static
Definition at line 96 of file main.cpp.
g_SwapChainTearingSupport
bool g_SwapChainTearingSupport = false static
Definition at line 95 of file main.cpp.
Referenced by CreateDeviceD3D().