SignalProcessing: examples/imgui/backends/imgui_impl_sdlrenderer3.cpp File Reference
imgui_impl_sdlrenderer3.cpp File Reference
#include "imgui.h"
#include "imgui_impl_sdlrenderer3.h"
#include <stdint.h>
#include <SDL3/SDL.h>
Classes
struct ImGui_ImplSDLRenderer3_Data
Functions
static ImGui_ImplSDLRenderer3_Data * ImGui_ImplSDLRenderer3_GetBackendData ()
bool ImGui_ImplSDLRenderer3_Init (SDL_Renderer *renderer)
void ImGui_ImplSDLRenderer3_Shutdown ()
static void ImGui_ImplSDLRenderer3_SetupRenderState (SDL_Renderer *renderer)
void ImGui_ImplSDLRenderer3_NewFrame ()
static int SDL_RenderGeometryRaw8BitColor (SDL_Renderer *renderer, ImVector< SDL_FColor > &colors_out, SDL_Texture *texture, const float *xy, int xy_stride, const SDL_Color *color, int color_stride, const float *uv, int uv_stride, int num_vertices, const void *indices, int num_indices, int size_indices)
void ImGui_ImplSDLRenderer3_RenderDrawData (ImDrawData *draw_data, SDL_Renderer *renderer)
void ImGui_ImplSDLRenderer3_UpdateTexture (ImTextureData *tex)
void ImGui_ImplSDLRenderer3_CreateDeviceObjects ()
void ImGui_ImplSDLRenderer3_DestroyDeviceObjects ()
Function Documentation
ImGui_ImplSDLRenderer3_CreateDeviceObjects()
void ImGui_ImplSDLRenderer3_CreateDeviceObjects ()
Definition at line 295 of file imgui_impl_sdlrenderer3.cpp.
ImGui_ImplSDLRenderer3_DestroyDeviceObjects()
void ImGui_ImplSDLRenderer3_DestroyDeviceObjects ()
Definition at line 299 of file imgui_impl_sdlrenderer3.cpp.
References ImGui::GetPlatformIO(), ImGui_ImplSDLRenderer3_UpdateTexture(), ImTextureStatus_WantDestroy, and ImGuiPlatformIO::Textures.
Referenced by ImGui_ImplSDLRenderer3_Shutdown().
ImGui_ImplSDLRenderer3_GetBackendData()
static ImGui_ImplSDLRenderer3_Data * ImGui_ImplSDLRenderer3_GetBackendData () static
Definition at line 66 of file imgui_impl_sdlrenderer3.cpp.
References ImGuiIO::BackendRendererUserData, ImGui::GetCurrentContext(), and ImGui::GetIO().
Referenced by ImGui_ImplSDLRenderer3_NewFrame(), ImGui_ImplSDLRenderer3_RenderDrawData(), ImGui_ImplSDLRenderer3_Shutdown(), and ImGui_ImplSDLRenderer3_UpdateTexture().
ImGui_ImplSDLRenderer3_Init()
bool ImGui_ImplSDLRenderer3_Init (SDL_Renderer * renderer)
Definition at line 72 of file imgui_impl_sdlrenderer3.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGui::GetIO(), IM_ASSERT, IM_NEW, IMGUI_CHECKVERSION, ImGuiBackendFlags_RendererHasTextures, ImGuiBackendFlags_RendererHasVtxOffset, and ImGui_ImplSDLRenderer3_Data::Renderer.
Referenced by main().
ImGui_ImplSDLRenderer3_NewFrame()
void ImGui_ImplSDLRenderer3_NewFrame ()
Definition at line 115 of file imgui_impl_sdlrenderer3.cpp.
References IM_ASSERT, IM_UNUSED, and ImGui_ImplSDLRenderer3_GetBackendData().
Referenced by main().
ImGui_ImplSDLRenderer3_RenderDrawData()
void ImGui_ImplSDLRenderer3_RenderDrawData (ImDrawData * draw_data, SDL_Renderer * renderer)
Definition at line 140 of file imgui_impl_sdlrenderer3.cpp.
References ImDrawCmd::ClipRect, ImDrawList::CmdBuffer, ImDrawData::CmdLists, ImGui_ImplSDLRenderer3_Data::ColorBuffer, ImVector< T >::Data, ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImDrawCmd::ElemCount, ImDrawData::FramebufferScale, ImGui::GetPlatformIO(), ImDrawCmd::GetTexID(), ImDrawList::IdxBuffer, ImDrawCmd::IdxOffset, ImDrawCallback_ResetRenderState, ImGui_ImplSDLRenderer3_GetBackendData(), ImGui_ImplSDLRenderer3_SetupRenderState(), ImGui_ImplSDLRenderer3_UpdateTexture(), ImTextureStatus_OK, ImGui_ImplSDLRenderer3_RenderState::Renderer, ImGuiPlatformIO::Renderer_RenderState, SDL_RenderGeometryRaw8BitColor(), ImVector< T >::Size, ImDrawData::Textures, ImDrawCmd::UserCallback, ImDrawList::VtxBuffer, ImDrawCmd::VtxOffset, ImVec4::w, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by main().
ImGui_ImplSDLRenderer3_SetupRenderState()
static void ImGui_ImplSDLRenderer3_SetupRenderState (SDL_Renderer * renderer) static
Definition at line 107 of file imgui_impl_sdlrenderer3.cpp.
Referenced by ImGui_ImplSDLRenderer3_RenderDrawData().
ImGui_ImplSDLRenderer3_Shutdown()
void ImGui_ImplSDLRenderer3_Shutdown ()
Definition at line 91 of file imgui_impl_sdlrenderer3.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGuiPlatformIO::ClearRendererHandlers(), ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplSDLRenderer3_DestroyDeviceObjects(), ImGui_ImplSDLRenderer3_GetBackendData(), ImGuiBackendFlags_RendererHasTextures, and ImGuiBackendFlags_RendererHasVtxOffset.
Referenced by main().
ImGui_ImplSDLRenderer3_UpdateTexture()
void ImGui_ImplSDLRenderer3_UpdateTexture (ImTextureData * tex)
Definition at line 249 of file imgui_impl_sdlrenderer3.cpp.
References ImTextureData::BackendUserData, ImTextureData::Format, ImTextureData::GetPitch(), ImTextureData::GetPixels(), ImTextureData::GetPixelsAt(), ImTextureData::Height, IM_ASSERT, ImGui_ImplSDLRenderer3_GetBackendData(), ImTextureFormat_RGBA32, ImTextureID_Invalid, ImTextureStatus_Destroyed, ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImGui_ImplSDLRenderer3_Data::Renderer, ImTextureData::SetStatus(), ImTextureData::SetTexID(), ImTextureData::Status, ImTextureData::TexID, ImTextureData::Updates, and ImTextureData::Width.
Referenced by ImGui_ImplSDLRenderer3_DestroyDeviceObjects(), and ImGui_ImplSDLRenderer3_RenderDrawData().
SDL_RenderGeometryRaw8BitColor()
static int SDL_RenderGeometryRaw8BitColor (SDL_Renderer * renderer, ImVector< SDL_FColor > & colors_out, SDL_Texture * texture, const float * xy, int xy_stride, const SDL_Color * color, int color_stride, const float * uv, int uv_stride, int num_vertices, const void * indices, int num_indices, int size_indices) static
Definition at line 123 of file imgui_impl_sdlrenderer3.cpp.
References ImVector< T >::Data, and ImVector< T >::resize().
Referenced by ImGui_ImplSDLRenderer3_RenderDrawData().