SignalProcessing: examples/imgui/backends/imgui_impl_sdlrenderer3.h File Reference
imgui_impl_sdlrenderer3.h File Reference
#include "imgui.h"
Classes
struct ImGui_ImplSDLRenderer3_RenderState
Functions
IMGUI_IMPL_API bool ImGui_ImplSDLRenderer3_Init (SDL_Renderer *renderer)
IMGUI_IMPL_API void ImGui_ImplSDLRenderer3_Shutdown ()
IMGUI_IMPL_API void ImGui_ImplSDLRenderer3_NewFrame ()
IMGUI_IMPL_API void ImGui_ImplSDLRenderer3_RenderDrawData (ImDrawData *draw_data, SDL_Renderer *renderer)
IMGUI_IMPL_API void ImGui_ImplSDLRenderer3_CreateDeviceObjects ()
IMGUI_IMPL_API void ImGui_ImplSDLRenderer3_DestroyDeviceObjects ()
IMGUI_IMPL_API void ImGui_ImplSDLRenderer3_UpdateTexture (ImTextureData *tex)
Function Documentation
ImGui_ImplSDLRenderer3_CreateDeviceObjects()
IMGUI_IMPL_API void ImGui_ImplSDLRenderer3_CreateDeviceObjects ()
Definition at line 295 of file imgui_impl_sdlrenderer3.cpp.
ImGui_ImplSDLRenderer3_DestroyDeviceObjects()
IMGUI_IMPL_API void ImGui_ImplSDLRenderer3_DestroyDeviceObjects ()
Definition at line 299 of file imgui_impl_sdlrenderer3.cpp.
References ImGui::GetPlatformIO(), ImGui_ImplSDLRenderer3_UpdateTexture(), ImTextureStatus_WantDestroy, and ImGuiPlatformIO::Textures.
Referenced by ImGui_ImplSDLRenderer3_Shutdown().
ImGui_ImplSDLRenderer3_Init()
IMGUI_IMPL_API bool ImGui_ImplSDLRenderer3_Init (SDL_Renderer * renderer)
Definition at line 72 of file imgui_impl_sdlrenderer3.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGui::GetIO(), IM_ASSERT, IM_NEW, IMGUI_CHECKVERSION, ImGuiBackendFlags_RendererHasTextures, ImGuiBackendFlags_RendererHasVtxOffset, and ImGui_ImplSDLRenderer3_Data::Renderer.
Referenced by main().
ImGui_ImplSDLRenderer3_NewFrame()
IMGUI_IMPL_API void ImGui_ImplSDLRenderer3_NewFrame ()
Definition at line 115 of file imgui_impl_sdlrenderer3.cpp.
References IM_ASSERT, IM_UNUSED, and ImGui_ImplSDLRenderer3_GetBackendData().
Referenced by main().
ImGui_ImplSDLRenderer3_RenderDrawData()
IMGUI_IMPL_API void ImGui_ImplSDLRenderer3_RenderDrawData (ImDrawData * draw_data, SDL_Renderer * renderer)
Definition at line 140 of file imgui_impl_sdlrenderer3.cpp.
References ImDrawCmd::ClipRect, ImDrawList::CmdBuffer, ImDrawData::CmdLists, ImGui_ImplSDLRenderer3_Data::ColorBuffer, ImVector< T >::Data, ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImDrawCmd::ElemCount, ImDrawData::FramebufferScale, ImGui::GetPlatformIO(), ImDrawCmd::GetTexID(), ImDrawList::IdxBuffer, ImDrawCmd::IdxOffset, ImDrawCallback_ResetRenderState, ImGui_ImplSDLRenderer3_GetBackendData(), ImGui_ImplSDLRenderer3_SetupRenderState(), ImGui_ImplSDLRenderer3_UpdateTexture(), ImTextureStatus_OK, ImGui_ImplSDLRenderer3_RenderState::Renderer, ImGuiPlatformIO::Renderer_RenderState, SDL_RenderGeometryRaw8BitColor(), ImVector< T >::Size, ImDrawData::Textures, ImDrawCmd::UserCallback, ImDrawList::VtxBuffer, ImDrawCmd::VtxOffset, ImVec4::w, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by main().
ImGui_ImplSDLRenderer3_Shutdown()
IMGUI_IMPL_API void ImGui_ImplSDLRenderer3_Shutdown ()
Definition at line 91 of file imgui_impl_sdlrenderer3.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGuiPlatformIO::ClearRendererHandlers(), ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplSDLRenderer3_DestroyDeviceObjects(), ImGui_ImplSDLRenderer3_GetBackendData(), ImGuiBackendFlags_RendererHasTextures, and ImGuiBackendFlags_RendererHasVtxOffset.
Referenced by main().
ImGui_ImplSDLRenderer3_UpdateTexture()
IMGUI_IMPL_API void ImGui_ImplSDLRenderer3_UpdateTexture (ImTextureData * tex)
Definition at line 249 of file imgui_impl_sdlrenderer3.cpp.
References ImTextureData::BackendUserData, ImTextureData::Format, ImTextureData::GetPitch(), ImTextureData::GetPixels(), ImTextureData::GetPixelsAt(), ImTextureData::Height, IM_ASSERT, ImGui_ImplSDLRenderer3_GetBackendData(), ImTextureFormat_RGBA32, ImTextureID_Invalid, ImTextureStatus_Destroyed, ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImGui_ImplSDLRenderer3_Data::Renderer, ImTextureData::SetStatus(), ImTextureData::SetTexID(), ImTextureData::Status, ImTextureData::TexID, ImTextureData::Updates, and ImTextureData::Width.
Referenced by ImGui_ImplSDLRenderer3_DestroyDeviceObjects(), and ImGui_ImplSDLRenderer3_RenderDrawData().