SignalProcessing: examples/imgui_demo.cpp File Reference
imgui_demo.cpp File Reference
#include "../source/SignalProcessing.h"
#include "../source/SignalRecorder.hpp"
#include "imgui.h"
#include "imgui_impl_glfw.h"
#include "imgui_impl_opengl3.h"
#include "implot.h"
#include <GLFW/glfw3.h>
#include <stdio.h>
#include <math.h>
#include <vector>
#include <ctime>
#include <string>
#include <unistd.h>
#include <limits.h>
#include "ImGuiConfig.hpp"
Macros
#define M_PI 3.14159265358979323846
Enumerations
enum SignalType { SIGNAL_SINE , SIGNAL_ECG , SIGNAL_TURBINE , SIGNAL_NOISE }
Functions
void GenerateSignal ()
void ApplyFilters ()
void InitializeConfiguration ()
void SaveConfiguration ()
void RenderConfigurationUI ()
void DetectAnomalies ()
void ComputeFFT ()
void ExtractMLFeatures ()
void SaveSignalToHDF5 ()
void LoadSignalFromHDF5 ()
int main (int, char **)
Variables
SignalProcessing sp
std::vector< double > signal_data
std::vector< double > filtered_data
std::vector< double > fft_frequencies
std::vector< double > fft_magnitudes
int signal_length = 500
double sampling_rate = 100.0
int current_signal = SIGNAL_ECG
float noise_level = 0.1f
float frequency = 1.2f
bool apply_kalman = false
bool apply_median = false
bool apply_wavelet = false
float kalman_process = 0.01f
float kalman_measure = 0.1f
int median_window = 5
bool show_anomalies = false
int anomaly_method = 0
float anomaly_threshold = 3.0f
std::vector< int > anomaly_indices
bool show_ml_features = false
MLFeatureVector ml_features
bool show_save_dialog = false
char save_filename [256] = "signal_recording.h5"
char session_info [256] = "Interactive ImGui Session"
bool save_success = false
bool save_error = false
char save_message [512] = ""
bool show_load_dialog = false
char load_filename [256] = "signal_recording.h5"
bool load_success = false
bool load_error = false
char load_message [512] = ""
std::vector< double > loaded_signal
std::vector< double > loaded_filtered
std::vector< int > loaded_anomalies
std::vector< double > loaded_fft_freq
std::vector< double > loaded_fft_mag
char loaded_info [512] = ""
bool show_loaded_data = false
ImGuiConfigManager config_manager ("imgui_app.ini")
ImGuiAppConfig app_config = ImGuiConfigManager::GetDefaultConfig()
Macro Definition Documentation
M_PI
#define M_PI 3.14159265358979323846
Definition at line 22 of file imgui_demo.cpp.
Enumeration Type Documentation
SignalType
enum SignalType
Enumerator
SIGNAL_SINE
SIGNAL_ECG
SIGNAL_TURBINE
SIGNAL_NOISE
Definition at line 35 of file imgui_demo.cpp.
Function Documentation
ApplyFilters()
void ApplyFilters ()
Definition at line 272 of file imgui_demo.cpp.
References SignalProcessing::AddValue(), apply_kalman, apply_median, apply_wavelet, filtered_data, SignalProcessing::GetIndex(), kalman_measure, kalman_process, SignalProcessing::KalmanFilter(), median_window, SignalProcessing::MedianFilter(), signal_data, signal_length, sp, and SignalProcessing::WaveletDenoise().
Referenced by main().
ComputeFFT()
void ComputeFFT ()
Definition at line 341 of file imgui_demo.cpp.
References SignalProcessing::AddValue(), FrequencySpectrum::bins, fft_frequencies, fft_magnitudes, SignalProcessing::FFTAnalysis(), filtered_data, SignalProcessing::FreeSpectrum(), FrequencyBin::frequency, FrequencyBin::magnitude, FrequencySpectrum::num_bins, and sampling_rate.
Referenced by main().
DetectAnomalies()
void DetectAnomalies ()
Definition at line 312 of file imgui_demo.cpp.
References SignalProcessing::AddValue(), anomaly_indices, anomaly_method, anomaly_threshold, SignalProcessing::DetectAnomaliesIQR(), SignalProcessing::DetectAnomaliesMAD(), SignalProcessing::DetectAnomaliesZScore(), and filtered_data.
Referenced by main().
ExtractMLFeatures()
void ExtractMLFeatures ()
Definition at line 361 of file imgui_demo.cpp.
References SignalProcessing::AddValue(), SignalProcessing::ExtractMLFeatures(), filtered_data, ml_features, and sampling_rate.
Referenced by main().
GenerateSignal()
void GenerateSignal ()
Definition at line 225 of file imgui_demo.cpp.
References SignalProcessing::AddValue(), SignalProcessing::ClearVector(), current_signal, frequency, M_PI, noise_level, sampling_rate, signal_data, SIGNAL_ECG, signal_length, SIGNAL_NOISE, SIGNAL_SINE, SIGNAL_TURBINE, and sp.
Referenced by main(), and RenderConfigurationUI().
InitializeConfiguration()
void InitializeConfiguration ()
Definition at line 88 of file imgui_demo.cpp.
References anomaly_method, ImGuiAppConfig::anomaly_method, anomaly_threshold, ImGuiAppConfig::anomaly_threshold, app_config, apply_kalman, ImGuiAppConfig::apply_kalman, apply_median, ImGuiAppConfig::apply_median, apply_wavelet, ImGuiAppConfig::apply_wavelet, config_manager, current_signal, frequency, ImGuiAppConfig::frequency, kalman_measure, ImGuiAppConfig::kalman_measure, kalman_process, ImGuiAppConfig::kalman_process, ImGuiAppConfig::last_load_path, ImGuiAppConfig::last_save_path, load_filename, ImGuiConfigManager::LoadConfig(), median_window, ImGuiAppConfig::median_window, noise_level, ImGuiAppConfig::noise_level, sampling_rate, ImGuiAppConfig::sampling_rate, save_filename, session_info, ImGuiAppConfig::session_info, show_anomalies, ImGuiAppConfig::show_anomalies, show_ml_features, ImGuiAppConfig::show_ml_features, signal_length, ImGuiAppConfig::signal_length, and ImGuiAppConfig::signal_type.
Referenced by main(), and RenderConfigurationUI().
LoadSignalFromHDF5()
void LoadSignalFromHDF5 ()
Definition at line 513 of file imgui_demo.cpp.
References load_error, load_filename, load_message, load_success, loaded_anomalies, loaded_fft_freq, loaded_fft_mag, loaded_filtered, loaded_info, loaded_signal, and show_loaded_data.
Referenced by main().
main()
int main (int , char **)
Definition at line 656 of file imgui_demo.cpp.
References anomaly_indices, anomaly_method, anomaly_threshold, apply_kalman, apply_median, apply_wavelet, ApplyFilters(), MLFeatureVector::autocorr_peak, ImGui::Begin(), ImGui::BeginChild(), ImPlot::BeginPlot(), ImGui::BeginPopupModal(), ImGui::BulletText(), ImGui::Button(), ImGui::Checkbox(), ImGui::Columns(), ImGui::Combo(), ComputeFFT(), ImGuiIO::ConfigFlags, ImPlot::CreateContext(), ImGui::CreateContext(), MLFeatureVector::crest_factor, current_signal, ImGui::DestroyContext(), ImPlot::DestroyContext(), DetectAnomalies(), MLFeatureVector::dominant_frequency, ImGui::End(), ImGui::EndChild(), ImPlot::EndPlot(), ImGui::EndPopup(), MLFeatureVector::energy, ExtractMLFeatures(), fft_frequencies, fft_magnitudes, filtered_data, frequency, GenerateSignal(), ImGuiViewport::GetCenter(), ImGui::GetDrawData(), ImGui::GetIO(), ImGui::GetMainViewport(), SignalProcessing::GetMean(), SignalProcessing::GetStandardDeviation(), GL_COLOR_BUFFER_BIT, glClear, glClearColor, GLFW_CONTEXT_VERSION_MAJOR, GLFW_CONTEXT_VERSION_MINOR, glfwCreateWindow(), glfwDestroyWindow(), glfwGetFramebufferSize(), glfwInit(), glfwMakeContextCurrent(), glfwPollEvents(), glfwSwapBuffers(), glfwSwapInterval(), glfwTerminate(), glfwWindowHint(), glfwWindowShouldClose(), glViewport, ImAxis_X1, IMGUI_CHECKVERSION, ImGui_ImplGlfw_InitForOpenGL(), ImGui_ImplGlfw_NewFrame(), ImGui_ImplGlfw_Shutdown(), ImGui_ImplOpenGL3_Init(), ImGui_ImplOpenGL3_NewFrame(), ImGui_ImplOpenGL3_RenderDrawData(), ImGui_ImplOpenGL3_Shutdown(), ImGuiCond_Always, ImGuiCond_Appearing, ImGuiConfigFlags_NavEnableKeyboard, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoResize, ImGuiWindowFlags_NoTitleBar, InitializeConfiguration(), ImGui::InputText(), kalman_measure, kalman_process, MLFeatureVector::kurtosis, load_error, load_filename, load_message, load_success, loaded_anomalies, loaded_fft_freq, loaded_fft_mag, loaded_filtered, loaded_info, loaded_signal, LoadSignalFromHDF5(), MLFeatureVector::mean, MLFeatureVector::mean_crossing_rate, median_window, ml_features, ImGui::NewFrame(), ImGui::NextColumn(), noise_level, ImGui::OpenPopup(), MLFeatureVector::peak_to_peak, ImPlot::PlotLine(), ImPlot::PlotScatter(), MLFeatureVector::power_high_freq, MLFeatureVector::power_low_freq, MLFeatureVector::power_mid_freq, ImGui::Render(), RenderConfigurationUI(), MLFeatureVector::rms, ImGui::SameLine(), save_error, save_filename, save_message, save_success, SaveConfiguration(), SaveSignalToHDF5(), ImGui::Separator(), session_info, ImGui::SetNextWindowPos(), ImGui::SetNextWindowSize(), ImPlot::SetupAxes(), ImPlot::SetupAxisLimits(), show_anomalies, show_load_dialog, show_loaded_data, show_ml_features, show_save_dialog, signal_data, signal_length, MLFeatureVector::skewness, ImGui::SliderFloat(), ImGui::SliderInt(), sp, ImGui::Spacing(), MLFeatureVector::spectral_centroid, MLFeatureVector::spectral_entropy, MLFeatureVector::spectral_spread, MLFeatureVector::std_dev, ImGui::StyleColorsDark(), ImGui::Text(), ImGui::TextColored(), ImGui::TextWrapped(), MLFeatureVector::total_power, MLFeatureVector::variance, and MLFeatureVector::zero_crossing_rate.
RenderConfigurationUI()
void RenderConfigurationUI ()
Definition at line 151 of file imgui_demo.cpp.
References anomaly_method, ImGuiAppConfig::anomaly_method, anomaly_threshold, ImGuiAppConfig::anomaly_threshold, app_config, apply_kalman, ImGuiAppConfig::apply_kalman, apply_median, ImGuiAppConfig::apply_median, apply_wavelet, ImGuiAppConfig::apply_wavelet, ImGui::BeginPopup(), ImGui::Button(), ImGui::CollapsingHeader(), config_manager, current_signal, ImGui::EndPopup(), frequency, ImGuiAppConfig::frequency, GenerateSignal(), ImGuiConfigManager::GetDefaultConfig(), InitializeConfiguration(), kalman_measure, ImGuiAppConfig::kalman_measure, kalman_process, ImGuiAppConfig::kalman_process, ImGuiAppConfig::last_load_path, ImGuiAppConfig::last_save_path, load_filename, ImGuiConfigManager::LoadConfig(), median_window, ImGuiAppConfig::median_window, noise_level, ImGuiAppConfig::noise_level, ImGui::OpenPopup(), ImGui::SameLine(), sampling_rate, ImGuiAppConfig::sampling_rate, save_filename, SaveConfiguration(), ImGui::Separator(), session_info, ImGuiAppConfig::session_info, show_anomalies, ImGuiAppConfig::show_anomalies, show_ml_features, ImGuiAppConfig::show_ml_features, signal_length, ImGuiAppConfig::signal_length, ImGuiAppConfig::signal_type, ImGui::Spacing(), ImGui::Text(), and ImGui::TextDisabled().
Referenced by main().
SaveConfiguration()
void SaveConfiguration ()
Definition at line 122 of file imgui_demo.cpp.
References anomaly_method, ImGuiAppConfig::anomaly_method, anomaly_threshold, ImGuiAppConfig::anomaly_threshold, app_config, apply_kalman, ImGuiAppConfig::apply_kalman, apply_median, ImGuiAppConfig::apply_median, apply_wavelet, ImGuiAppConfig::apply_wavelet, config_manager, current_signal, frequency, ImGuiAppConfig::frequency, kalman_measure, ImGuiAppConfig::kalman_measure, kalman_process, ImGuiAppConfig::kalman_process, ImGuiAppConfig::last_load_path, ImGuiAppConfig::last_save_path, load_filename, median_window, ImGuiAppConfig::median_window, noise_level, ImGuiAppConfig::noise_level, sampling_rate, ImGuiAppConfig::sampling_rate, save_filename, ImGuiConfigManager::SaveConfig(), session_info, ImGuiAppConfig::session_info, show_anomalies, ImGuiAppConfig::show_anomalies, show_ml_features, ImGuiAppConfig::show_ml_features, signal_length, ImGuiAppConfig::signal_length, and ImGuiAppConfig::signal_type.
Referenced by main(), and RenderConfigurationUI().
SaveSignalToHDF5()
void SaveSignalToHDF5 ()
Definition at line 370 of file imgui_demo.cpp.
References SignalRecorder::addFloatVector(), SignalRecorder::addMetadata(), anomaly_indices, anomaly_method, anomaly_threshold, apply_kalman, apply_median, apply_wavelet, MLFeatureVector::autocorr_peak, MLFeatureVector::crest_factor, current_signal, MLFeatureVector::dominant_frequency, MLFeatureVector::energy, fft_frequencies, fft_magnitudes, filtered_data, frequency, SignalProcessing::GetMean(), SignalProcessing::GetStandardDeviation(), SignalProcessing::GetVariance(), kalman_measure, kalman_process, MLFeatureVector::kurtosis, MLFeatureVector::mean, MLFeatureVector::mean_crossing_rate, median_window, ml_features, noise_level, MLFeatureVector::peak_to_peak, MLFeatureVector::power_high_freq, MLFeatureVector::power_low_freq, MLFeatureVector::power_mid_freq, MLFeatureVector::rms, sampling_rate, save_error, save_filename, save_message, save_success, session_info, show_ml_features, signal_data, signal_length, MLFeatureVector::skewness, sp, MLFeatureVector::spectral_centroid, MLFeatureVector::spectral_entropy, MLFeatureVector::spectral_spread, MLFeatureVector::std_dev, MLFeatureVector::total_power, MLFeatureVector::variance, and MLFeatureVector::zero_crossing_rate.
Referenced by main().
Variable Documentation
anomaly_indices
std::vector<int> anomaly_indices
Definition at line 52 of file imgui_demo.cpp.
Referenced by DetectAnomalies(), SignalProcessing::DetectAnomaliesIQR(), SignalProcessing::DetectAnomaliesMAD(), SignalProcessing::DetectAnomaliesZScore(), SignalProcessing::DetectPeriodicAnomalies(), SignalProcessing::DetectSuddenChanges(), main(), and SaveSignalToHDF5().
anomaly_method
int anomaly_method = 0
Definition at line 50 of file imgui_demo.cpp.
Referenced by DetectAnomalies(), SignalProcessing::FindMostAnomalousSegment(), InitializeConfiguration(), main(), RenderConfigurationUI(), SaveConfiguration(), and SaveSignalToHDF5().
anomaly_threshold
float anomaly_threshold = 3.0f
Definition at line 51 of file imgui_demo.cpp.
Referenced by DetectAnomalies(), InitializeConfiguration(), main(), RenderConfigurationUI(), SaveConfiguration(), and SaveSignalToHDF5().
app_config
ImGuiAppConfig app_config = ImGuiConfigManager::GetDefaultConfig()
Definition at line 81 of file imgui_demo.cpp.
Referenced by InitializeConfiguration(), RenderConfigurationUI(), and SaveConfiguration().
apply_kalman
bool apply_kalman = false
Definition at line 41 of file imgui_demo.cpp.
Referenced by ApplyFilters(), InitializeConfiguration(), main(), RenderConfigurationUI(), SaveConfiguration(), and SaveSignalToHDF5().
apply_median
bool apply_median = false
Definition at line 42 of file imgui_demo.cpp.
Referenced by ApplyFilters(), InitializeConfiguration(), main(), RenderConfigurationUI(), SaveConfiguration(), and SaveSignalToHDF5().
apply_wavelet
bool apply_wavelet = false
Definition at line 43 of file imgui_demo.cpp.
Referenced by ApplyFilters(), InitializeConfiguration(), main(), RenderConfigurationUI(), SaveConfiguration(), and SaveSignalToHDF5().
config_manager
ImGuiConfigManager config_manager("imgui_app.ini") ("imgui_app.ini")
Referenced by InitializeConfiguration(), RenderConfigurationUI(), and SaveConfiguration().
current_signal
int current_signal = SIGNAL_ECG
Definition at line 36 of file imgui_demo.cpp.
Referenced by GenerateSignal(), InitializeConfiguration(), main(), RenderConfigurationUI(), SaveConfiguration(), and SaveSignalToHDF5().
fft_frequencies
std::vector<double> fft_frequencies
Definition at line 29 of file imgui_demo.cpp.
Referenced by ComputeFFT(), main(), and SaveSignalToHDF5().
fft_magnitudes
std::vector<double> fft_magnitudes
Definition at line 30 of file imgui_demo.cpp.
Referenced by ComputeFFT(), main(), and SaveSignalToHDF5().
filtered_data
std::vector<double> filtered_data
Definition at line 28 of file imgui_demo.cpp.
Referenced by ApplyFilters(), ComputeFFT(), DetectAnomalies(), ExtractMLFeatures(), main(), and SaveSignalToHDF5().
frequency
float frequency = 1.2f
Definition at line 38 of file imgui_demo.cpp.
Referenced by ImPlot::Demo_LegendPopups(), GenerateSignal(), ImGui_ImplSDL2_NewFrame(), ImGui_ImplSDL3_NewFrame(), InitializeConfiguration(), main(), RenderConfigurationUI(), SaveConfiguration(), and SaveSignalToHDF5().
kalman_measure
float kalman_measure = 0.1f
Definition at line 45 of file imgui_demo.cpp.
Referenced by ApplyFilters(), InitializeConfiguration(), main(), RenderConfigurationUI(), SaveConfiguration(), and SaveSignalToHDF5().
kalman_process
float kalman_process = 0.01f
Definition at line 44 of file imgui_demo.cpp.
Referenced by ApplyFilters(), InitializeConfiguration(), main(), RenderConfigurationUI(), SaveConfiguration(), and SaveSignalToHDF5().
load_error
bool load_error = false
Definition at line 69 of file imgui_demo.cpp.
Referenced by LoadSignalFromHDF5(), and main().
load_filename
char load_filename[256] = "signal_recording.h5"
Definition at line 67 of file imgui_demo.cpp.
Referenced by InitializeConfiguration(), LoadSignalFromHDF5(), main(), RenderConfigurationUI(), and SaveConfiguration().
load_message
char load_message[512] = ""
Definition at line 70 of file imgui_demo.cpp.
Referenced by LoadSignalFromHDF5(), and main().
load_success
bool load_success = false
Definition at line 68 of file imgui_demo.cpp.
Referenced by LoadSignalFromHDF5(), and main().
loaded_anomalies
std::vector<int> loaded_anomalies
Definition at line 73 of file imgui_demo.cpp.
Referenced by LoadSignalFromHDF5(), and main().
loaded_fft_freq
std::vector<double> loaded_fft_freq
Definition at line 74 of file imgui_demo.cpp.
Referenced by LoadSignalFromHDF5(), and main().
loaded_fft_mag
std::vector<double> loaded_fft_mag
Definition at line 75 of file imgui_demo.cpp.
Referenced by LoadSignalFromHDF5(), and main().
loaded_filtered
std::vector<double> loaded_filtered
Definition at line 72 of file imgui_demo.cpp.
Referenced by LoadSignalFromHDF5(), and main().
loaded_info
char loaded_info[512] = ""
Definition at line 76 of file imgui_demo.cpp.
Referenced by LoadSignalFromHDF5(), and main().
loaded_signal
std::vector<double> loaded_signal
Definition at line 71 of file imgui_demo.cpp.
Referenced by LoadSignalFromHDF5(), and main().
median_window
int median_window = 5
Definition at line 46 of file imgui_demo.cpp.
Referenced by ApplyFilters(), InitializeConfiguration(), main(), RenderConfigurationUI(), SaveConfiguration(), and SaveSignalToHDF5().
ml_features
MLFeatureVector ml_features
Definition at line 56 of file imgui_demo.cpp.
Referenced by ExtractMLFeatures(), main(), and SaveSignalToHDF5().
noise_level
float noise_level = 0.1f
Definition at line 37 of file imgui_demo.cpp.
Referenced by GenerateSignal(), InitializeConfiguration(), main(), RenderConfigurationUI(), SaveConfiguration(), and SaveSignalToHDF5().
sampling_rate
double sampling_rate = 100.0
Definition at line 32 of file imgui_demo.cpp.
Referenced by acquire_ecg_data(), SignalProcessing::BatchExtractFeatures(), SignalProcessing::CompareSegmentSpectra(), ComputeFFT(), detect_r_peaks(), ExtractMLFeatures(), SignalProcessing::ExtractMLFeatures(), SignalProcessing::ExtractMLFeaturesFromSegment(), SignalProcessing::ExtractMLFeaturesRollingWindow(), SignalProcessing::FFTAnalysis(), SignalProcessing::FFTAnalysis(), GenerateSignal(), InitializeConfiguration(), main(), RenderConfigurationUI(), SaveConfiguration(), and SaveSignalToHDF5().
save_error
bool save_error = false
Definition at line 63 of file imgui_demo.cpp.
Referenced by main(), and SaveSignalToHDF5().
save_filename
char save_filename[256] = "signal_recording.h5"
Definition at line 60 of file imgui_demo.cpp.
Referenced by InitializeConfiguration(), main(), RenderConfigurationUI(), SaveConfiguration(), and SaveSignalToHDF5().
save_message
char save_message[512] = ""
Definition at line 64 of file imgui_demo.cpp.
Referenced by main(), and SaveSignalToHDF5().
save_success
bool save_success = false
Definition at line 62 of file imgui_demo.cpp.
Referenced by main(), and SaveSignalToHDF5().
session_info
char session_info[256] = "Interactive ImGui Session"
Definition at line 61 of file imgui_demo.cpp.
Referenced by InitializeConfiguration(), main(), RenderConfigurationUI(), SaveConfiguration(), and SaveSignalToHDF5().
show_anomalies
bool show_anomalies = false
Definition at line 49 of file imgui_demo.cpp.
Referenced by InitializeConfiguration(), main(), RenderConfigurationUI(), and SaveConfiguration().
show_load_dialog
bool show_load_dialog = false
Definition at line 66 of file imgui_demo.cpp.
Referenced by main().
show_loaded_data
bool show_loaded_data = false
Definition at line 77 of file imgui_demo.cpp.
Referenced by LoadSignalFromHDF5(), and main().
show_ml_features
bool show_ml_features = false
Definition at line 55 of file imgui_demo.cpp.
Referenced by InitializeConfiguration(), main(), RenderConfigurationUI(), SaveConfiguration(), and SaveSignalToHDF5().
show_save_dialog
bool show_save_dialog = false
Definition at line 59 of file imgui_demo.cpp.
Referenced by main().
signal_data
std::vector<double> signal_data
Definition at line 27 of file imgui_demo.cpp.
Referenced by ApplyFilters(), GenerateSignal(), main(), and SaveSignalToHDF5().
signal_length
int signal_length = 500
Definition at line 31 of file imgui_demo.cpp.
Referenced by ApplyFilters(), GenerateSignal(), InitializeConfiguration(), main(), RenderConfigurationUI(), SaveConfiguration(), and SaveSignalToHDF5().
sp
SignalProcessing sp
Definition at line 26 of file imgui_demo.cpp.
Referenced by acquire_ecg_data(), analyze_statistics(), ApplyFilters(), SignalProcessing::BatchExtractFeatures(), detect_events(), detect_r_peaks(), GenerateSignal(), main(), preprocess_signal(), and SaveSignalToHDF5().