SignalProcessing: examples/imgui/examples/example_win32_opengl3/main.cpp File Reference
main.cpp File Reference
#include "imgui.h"
#include "imgui_impl_opengl3.h"
#include "imgui_impl_win32.h"
#include <windows.h>
#include <GL/gl.h>
#include <tchar.h>
Classes
struct WGL_WindowData
Macros
#define WIN32_LEAN_AND_MEAN
Functions
bool CreateDeviceWGL (HWND hWnd, WGL_WindowData *data)
void CleanupDeviceWGL (HWND hWnd, WGL_WindowData *data)
void ResetDeviceWGL ()
LRESULT WINAPI WndProc (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam)
int main (int, char **)
IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam)
Variables
static HGLRC g_hRC
static WGL_WindowData g_MainWindow
static int g_Width
static int g_Height
Macro Definition Documentation
WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
Definition at line 15 of file main.cpp.
Function Documentation
CleanupDeviceWGL()
void CleanupDeviceWGL (HWND hWnd, WGL_WindowData * data)
Definition at line 214 of file main.cpp.
Referenced by main().
CreateDeviceWGL()
bool CreateDeviceWGL (HWND hWnd, WGL_WindowData * data)
Definition at line 191 of file main.cpp.
References g_hRC.
Referenced by main().
ImGui_ImplWin32_WndProcHandler()
IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam) extern
Definition at line 619 of file imgui_impl_win32.cpp.
main()
int main (int , char **)
Definition at line 37 of file main.cpp.
References ImGui::Begin(), ImGui::Button(), ImGui::Checkbox(), CleanupDeviceWGL(), clear_color, ImGui::ColorEdit3(), ImGuiIO::ConfigFlags, ImGui::CreateContext(), CreateDeviceWGL(), ImGui::DestroyContext(), ImGui::End(), ImGuiStyle::FontScaleDpi, ImGuiIO::Framerate, g_Height, g_hRC, g_MainWindow, g_Width, ImGui::GetDrawData(), ImGui::GetIO(), ImGui::GetStyle(), GL_COLOR_BUFFER_BIT, glClear, glClearColor, glViewport, WGL_WindowData::hDC, IMGUI_CHECKVERSION, ImGui_ImplOpenGL3_Init(), ImGui_ImplOpenGL3_NewFrame(), ImGui_ImplOpenGL3_RenderDrawData(), ImGui_ImplOpenGL3_Shutdown(), ImGui_ImplWin32_EnableDpiAwareness(), ImGui_ImplWin32_GetDpiScaleForMonitor(), ImGui_ImplWin32_InitForOpenGL(), ImGui_ImplWin32_NewFrame(), ImGui_ImplWin32_Shutdown(), ImGuiConfigFlags_NavEnableGamepad, ImGuiConfigFlags_NavEnableKeyboard, ImGui::NewFrame(), ImGui::Render(), ImGui::SameLine(), ImGuiStyle::ScaleAllSizes(), show_another_window, show_demo_window, ImGui::ShowDemoWindow(), ImGui::SliderFloat(), ImGui::StyleColorsDark(), ImGui::Text(), ImVec4::w, WndProc(), ImVec4::x, ImVec4::y, and ImVec4::z.
ResetDeviceWGL()
void ResetDeviceWGL ()
WndProc()
LRESULT WINAPI WndProc (HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam)
Definition at line 228 of file main.cpp.
References g_Height, g_Width, and ImGui_ImplWin32_WndProcHandler().
Variable Documentation
g_Height
int g_Height static
Definition at line 28 of file main.cpp.
Referenced by main(), and WndProc().
g_hRC
HGLRC g_hRC static
Definition at line 25 of file main.cpp.
Referenced by CreateDeviceWGL(), and main().
g_MainWindow
WGL_WindowData g_MainWindow static
Definition at line 26 of file main.cpp.
Referenced by main().
g_Width
int g_Width static
Definition at line 27 of file main.cpp.
Referenced by main(), and WndProc().