SignalProcessing: examples/imgui/backends/imgui_impl_vulkan.cpp File Reference
imgui_impl_vulkan.cpp File Reference
#include "imgui.h"
#include "imgui_impl_vulkan.h"
#include <stdio.h>
Classes
struct ImGui_ImplVulkan_FrameRenderBuffers
struct ImGui_ImplVulkan_WindowRenderBuffers
struct ImGui_ImplVulkan_Texture
struct ImGui_ImplVulkan_Data
Macros
#define IM_MAX(A, B) (((A) >= (B)) ? (A) : (B))
Typedefs
typedef void VkPipelineRenderingCreateInfoKHR
Functions
bool ImGui_ImplVulkan_CreateDeviceObjects ()
void ImGui_ImplVulkan_DestroyDeviceObjects ()
void ImGui_ImplVulkan_DestroyFrameRenderBuffers (VkDevice device, ImGui_ImplVulkan_FrameRenderBuffers *buffers, const VkAllocationCallbacks *allocator)
void ImGui_ImplVulkan_DestroyWindowRenderBuffers (VkDevice device, ImGui_ImplVulkan_WindowRenderBuffers *buffers, const VkAllocationCallbacks *allocator)
void ImGui_ImplVulkanH_DestroyFrame (VkDevice device, ImGui_ImplVulkanH_Frame *fd, const VkAllocationCallbacks *allocator)
void ImGui_ImplVulkanH_DestroyFrameSemaphores (VkDevice device, ImGui_ImplVulkanH_FrameSemaphores *fsd, const VkAllocationCallbacks *allocator)
void ImGui_ImplVulkanH_CreateWindowSwapChain (VkPhysicalDevice physical_device, VkDevice device, ImGui_ImplVulkanH_Window *wd, const VkAllocationCallbacks *allocator, int w, int h, uint32_t min_image_count, VkImageUsageFlags image_usage)
void ImGui_ImplVulkanH_CreateWindowCommandBuffers (VkPhysicalDevice physical_device, VkDevice device, ImGui_ImplVulkanH_Window *wd, uint32_t queue_family, const VkAllocationCallbacks *allocator)
static ImGui_ImplVulkan_Data * ImGui_ImplVulkan_GetBackendData ()
static uint32_t ImGui_ImplVulkan_MemoryType (VkMemoryPropertyFlags properties, uint32_t type_bits)
static void check_vk_result (VkResult err)
static VkDeviceSize AlignBufferSize (VkDeviceSize size, VkDeviceSize alignment)
static void CreateOrResizeBuffer (VkBuffer &buffer, VkDeviceMemory &buffer_memory, VkDeviceSize &buffer_size, VkDeviceSize new_size, VkBufferUsageFlagBits usage)
static void ImGui_ImplVulkan_SetupRenderState (ImDrawData *draw_data, VkPipeline pipeline, VkCommandBuffer command_buffer, ImGui_ImplVulkan_FrameRenderBuffers *rb, int fb_width, int fb_height)
void ImGui_ImplVulkan_RenderDrawData (ImDrawData *draw_data, VkCommandBuffer command_buffer, VkPipeline pipeline)
static void ImGui_ImplVulkan_DestroyTexture (ImTextureData *tex)
void ImGui_ImplVulkan_UpdateTexture (ImTextureData *tex)
static void ImGui_ImplVulkan_CreateShaderModules (VkDevice device, const VkAllocationCallbacks *allocator)
static VkPipeline ImGui_ImplVulkan_CreatePipeline (VkDevice device, const VkAllocationCallbacks *allocator, VkPipelineCache pipelineCache, const ImGui_ImplVulkan_PipelineInfo *info)
void ImGui_ImplVulkan_CreateMainPipeline (const ImGui_ImplVulkan_PipelineInfo *pipeline_info_in)
static uint32_t ImGui_ImplVulkan_GetDefaultApiVersion ()
bool ImGui_ImplVulkan_LoadFunctions (uint32_t api_version, PFN_vkVoidFunction(*loader_func)(const char *function_name, void *user_data), void *user_data)
bool ImGui_ImplVulkan_Init (ImGui_ImplVulkan_InitInfo *info)
void ImGui_ImplVulkan_Shutdown ()
void ImGui_ImplVulkan_NewFrame ()
void ImGui_ImplVulkan_SetMinImageCount (uint32_t min_image_count)
VkDescriptorSet ImGui_ImplVulkan_AddTexture (VkSampler sampler, VkImageView image_view, VkImageLayout image_layout)
void ImGui_ImplVulkan_RemoveTexture (VkDescriptorSet descriptor_set)
VkSurfaceFormatKHR ImGui_ImplVulkanH_SelectSurfaceFormat (VkPhysicalDevice physical_device, VkSurfaceKHR surface, const VkFormat *request_formats, int request_formats_count, VkColorSpaceKHR request_color_space)
VkPresentModeKHR ImGui_ImplVulkanH_SelectPresentMode (VkPhysicalDevice physical_device, VkSurfaceKHR surface, const VkPresentModeKHR *request_modes, int request_modes_count)
VkPhysicalDevice ImGui_ImplVulkanH_SelectPhysicalDevice (VkInstance instance)
uint32_t ImGui_ImplVulkanH_SelectQueueFamilyIndex (VkPhysicalDevice physical_device)
int ImGui_ImplVulkanH_GetMinImageCountFromPresentMode (VkPresentModeKHR present_mode)
void ImGui_ImplVulkanH_CreateOrResizeWindow (VkInstance instance, VkPhysicalDevice physical_device, VkDevice device, ImGui_ImplVulkanH_Window *wd, uint32_t queue_family, const VkAllocationCallbacks *allocator, int width, int height, uint32_t min_image_count, VkImageUsageFlags image_usage)
void ImGui_ImplVulkanH_DestroyWindow (VkInstance instance, VkDevice device, ImGui_ImplVulkanH_Window *wd, const VkAllocationCallbacks *allocator)
Variables
static bool g_FunctionsLoaded = true
static uint32_t __glsl_shader_vert_spv []
static uint32_t __glsl_shader_frag_spv []
Macro Definition Documentation
IM_MAX
#define IM_MAX (A, B) (((A) >= (B)) ? (A) : (B))
Definition at line 108 of file imgui_impl_vulkan.cpp.
Typedef Documentation
VkPipelineRenderingCreateInfoKHR
typedef void VkPipelineRenderingCreateInfoKHR
Definition at line 921 of file imgui_impl_vulkan.cpp.
Function Documentation
AlignBufferSize()
static VkDeviceSize AlignBufferSize (VkDeviceSize size, VkDeviceSize alignment) inline static
Definition at line 429 of file imgui_impl_vulkan.cpp.
Referenced by CreateOrResizeBuffer(), ImGui_ImplVulkan_RenderDrawData(), and ImGui_ImplVulkan_UpdateTexture().
check_vk_result()
static void check_vk_result (VkResult err) static
Definition at line 418 of file imgui_impl_vulkan.cpp.
References ImGui_ImplVulkan_InitInfo::CheckVkResultFn, ImGui_ImplVulkan_GetBackendData(), and ImGui_ImplVulkan_Data::VulkanInitInfo.
Referenced by CreateOrResizeBuffer(), ImGui_ImplVulkan_AddTexture(), ImGui_ImplVulkan_CreateDeviceObjects(), ImGui_ImplVulkan_CreatePipeline(), ImGui_ImplVulkan_CreateShaderModules(), ImGui_ImplVulkan_RenderDrawData(), ImGui_ImplVulkan_SetMinImageCount(), ImGui_ImplVulkan_UpdateTexture(), ImGui_ImplVulkanH_CreateOrResizeWindow(), ImGui_ImplVulkanH_CreateWindowCommandBuffers(), ImGui_ImplVulkanH_CreateWindowSwapChain(), and ImGui_ImplVulkanH_SelectPhysicalDevice().
CreateOrResizeBuffer()
static void CreateOrResizeBuffer (VkBuffer & buffer, VkDeviceMemory & buffer_memory, VkDeviceSize & buffer_size, VkDeviceSize new_size, VkBufferUsageFlagBits usage) static
Definition at line 434 of file imgui_impl_vulkan.cpp.
References AlignBufferSize(), ImGui_ImplVulkan_InitInfo::Allocator, ImGui_ImplVulkan_Data::BufferMemoryAlignment, check_vk_result(), ImGui_ImplVulkan_InitInfo::Device, IM_MAX, ImGui_ImplVulkan_GetBackendData(), ImGui_ImplVulkan_MemoryType(), ImGui_ImplVulkan_InitInfo::MinAllocationSize, and ImGui_ImplVulkan_Data::VulkanInitInfo.
Referenced by ImGui_ImplVulkan_RenderDrawData().
ImGui_ImplVulkan_AddTexture()
VkDescriptorSet ImGui_ImplVulkan_AddTexture (VkSampler sampler, VkImageView image_view, VkImageLayout image_layout)
Definition at line 1347 of file imgui_impl_vulkan.cpp.
References check_vk_result(), ImGui_ImplVulkan_Data::DescriptorPool, ImGui_ImplVulkan_InitInfo::DescriptorPool, ImGui_ImplVulkan_Data::DescriptorSetLayout, ImGui_ImplVulkan_InitInfo::Device, ImGui_ImplVulkan_GetBackendData(), and ImGui_ImplVulkan_Data::VulkanInitInfo.
Referenced by ImGui_ImplVulkan_UpdateTexture().
ImGui_ImplVulkan_CreateDeviceObjects()
bool ImGui_ImplVulkan_CreateDeviceObjects ()
Definition at line 1040 of file imgui_impl_vulkan.cpp.
References ImGui_ImplVulkan_InitInfo::Allocator, check_vk_result(), ImGui_ImplVulkan_Data::DescriptorPool, ImGui_ImplVulkan_InitInfo::DescriptorPoolSize, ImGui_ImplVulkan_Data::DescriptorSetLayout, ImGui_ImplVulkan_InitInfo::Device, IM_ASSERT, IMGUI_IMPL_VULKAN_MINIMUM_IMAGE_SAMPLER_POOL_SIZE, ImGui_ImplVulkan_CreateMainPipeline(), ImGui_ImplVulkan_GetBackendData(), ImGui_ImplVulkan_InitInfo::PipelineInfoMain, ImGui_ImplVulkan_Data::PipelineLayout, ImGui_ImplVulkan_InitInfo::QueueFamily, ImGui_ImplVulkan_PipelineInfo::RenderPass, ImGui_ImplVulkan_Data::TexCommandBuffer, ImGui_ImplVulkan_Data::TexCommandPool, ImGui_ImplVulkan_Data::TexSamplerLinear, ImGui_ImplVulkan_InitInfo::UseDynamicRendering, and ImGui_ImplVulkan_Data::VulkanInitInfo.
Referenced by ImGui_ImplVulkan_Init().
ImGui_ImplVulkan_CreateMainPipeline()
void ImGui_ImplVulkan_CreateMainPipeline (const ImGui_ImplVulkan_PipelineInfo * pipeline_info_in)
Definition at line 1142 of file imgui_impl_vulkan.cpp.
References ImGui_ImplVulkan_InitInfo::Allocator, ImVector< T >::Data, ImGui_ImplVulkan_InitInfo::Device, ImGui_ImplVulkan_CreatePipeline(), ImGui_ImplVulkan_GetBackendData(), ImGui_ImplVulkan_Data::Pipeline, ImGui_ImplVulkan_InitInfo::PipelineCache, ImGui_ImplVulkan_InitInfo::PipelineInfoMain, ImGui_ImplVulkan_Data::PipelineRenderingCreateInfoColorAttachmentFormats, ImVector< T >::resize(), ImVector< T >::size_in_bytes(), ImVector< T >::swap(), ImGui_ImplVulkan_InitInfo::UseDynamicRendering, and ImGui_ImplVulkan_Data::VulkanInitInfo.
Referenced by ImGui_ImplVulkan_CreateDeviceObjects().
ImGui_ImplVulkan_CreatePipeline()
static VkPipeline ImGui_ImplVulkan_CreatePipeline (VkDevice device, const VkAllocationCallbacks * allocator, VkPipelineCache pipelineCache, const ImGui_ImplVulkan_PipelineInfo * info) static
Definition at line 924 of file imgui_impl_vulkan.cpp.
References check_vk_result(), IM_ARRAYSIZE, IM_ASSERT, ImGui_ImplVulkan_CreateShaderModules(), ImGui_ImplVulkan_GetBackendData(), ImGui_ImplVulkan_PipelineInfo::MSAASamples, ImGui_ImplVulkan_Data::PipelineCreateFlags, ImGui_ImplVulkan_Data::PipelineLayout, ImGui_ImplVulkan_PipelineInfo::RenderPass, ImGui_ImplVulkan_Data::ShaderModuleFrag, ImGui_ImplVulkan_Data::ShaderModuleVert, ImGui_ImplVulkan_PipelineInfo::Subpass, ImGui_ImplVulkan_InitInfo::UseDynamicRendering, and ImGui_ImplVulkan_Data::VulkanInitInfo.
Referenced by ImGui_ImplVulkan_CreateMainPipeline().
ImGui_ImplVulkan_CreateShaderModules()
static void ImGui_ImplVulkan_CreateShaderModules (VkDevice device, const VkAllocationCallbacks * allocator) static
Definition at line 894 of file imgui_impl_vulkan.cpp.
References __glsl_shader_frag_spv, __glsl_shader_vert_spv, check_vk_result(), ImGui_ImplVulkan_InitInfo::CustomShaderFragCreateInfo, ImGui_ImplVulkan_InitInfo::CustomShaderVertCreateInfo, ImGui_ImplVulkan_GetBackendData(), ImGui_ImplVulkan_Data::ShaderModuleFrag, ImGui_ImplVulkan_Data::ShaderModuleVert, and ImGui_ImplVulkan_Data::VulkanInitInfo.
Referenced by ImGui_ImplVulkan_CreatePipeline().
ImGui_ImplVulkan_DestroyDeviceObjects()
void ImGui_ImplVulkan_DestroyDeviceObjects ()
Definition at line 1170 of file imgui_impl_vulkan.cpp.
References ImGui_ImplVulkan_InitInfo::Allocator, ImGui_ImplVulkan_Data::DescriptorPool, ImGui_ImplVulkan_Data::DescriptorSetLayout, ImGui_ImplVulkan_InitInfo::Device, ImGui::GetPlatformIO(), ImGui_ImplVulkan_DestroyTexture(), ImGui_ImplVulkan_DestroyWindowRenderBuffers(), ImGui_ImplVulkan_GetBackendData(), ImGui_ImplVulkan_Data::MainWindowRenderBuffers, ImGui_ImplVulkan_Data::Pipeline, ImGui_ImplVulkan_Data::PipelineLayout, ImGui_ImplVulkan_Data::ShaderModuleFrag, ImGui_ImplVulkan_Data::ShaderModuleVert, ImGui_ImplVulkan_Data::TexCommandBuffer, ImGui_ImplVulkan_Data::TexCommandPool, ImGui_ImplVulkan_Data::TexSamplerLinear, ImGuiPlatformIO::Textures, and ImGui_ImplVulkan_Data::VulkanInitInfo.
Referenced by ImGui_ImplVulkan_Shutdown().
ImGui_ImplVulkan_DestroyFrameRenderBuffers()
void ImGui_ImplVulkan_DestroyFrameRenderBuffers (VkDevice device, ImGui_ImplVulkan_FrameRenderBuffers * buffers, const VkAllocationCallbacks * allocator)
Definition at line 1390 of file imgui_impl_vulkan.cpp.
References ImGui_ImplVulkan_FrameRenderBuffers::IndexBuffer, ImGui_ImplVulkan_FrameRenderBuffers::IndexBufferMemory, ImGui_ImplVulkan_FrameRenderBuffers::IndexBufferSize, ImGui_ImplVulkan_FrameRenderBuffers::VertexBuffer, ImGui_ImplVulkan_FrameRenderBuffers::VertexBufferMemory, and ImGui_ImplVulkan_FrameRenderBuffers::VertexBufferSize.
Referenced by ImGui_ImplVulkan_DestroyWindowRenderBuffers().
ImGui_ImplVulkan_DestroyTexture()
static void ImGui_ImplVulkan_DestroyTexture (ImTextureData * tex) static
Definition at line 666 of file imgui_impl_vulkan.cpp.
References ImGui_ImplVulkan_InitInfo::Allocator, ImTextureData::BackendUserData, ImGui_ImplVulkan_InitInfo::Device, IM_ASSERT, IM_DELETE(), ImGui_ImplVulkan_GetBackendData(), ImGui_ImplVulkan_RemoveTexture(), ImTextureID_Invalid, ImTextureStatus_Destroyed, ImTextureData::SetStatus(), ImTextureData::SetTexID(), ImTextureData::TexID, and ImGui_ImplVulkan_Data::VulkanInitInfo.
Referenced by ImGui_ImplVulkan_DestroyDeviceObjects(), and ImGui_ImplVulkan_UpdateTexture().
ImGui_ImplVulkan_DestroyWindowRenderBuffers()
void ImGui_ImplVulkan_DestroyWindowRenderBuffers (VkDevice device, ImGui_ImplVulkan_WindowRenderBuffers * buffers, const VkAllocationCallbacks * allocator)
Definition at line 1400 of file imgui_impl_vulkan.cpp.
References ImVector< T >::clear(), ImGui_ImplVulkan_WindowRenderBuffers::Count, ImGui_ImplVulkan_WindowRenderBuffers::FrameRenderBuffers, ImGui_ImplVulkan_DestroyFrameRenderBuffers(), and ImGui_ImplVulkan_WindowRenderBuffers::Index.
Referenced by ImGui_ImplVulkan_DestroyDeviceObjects(), and ImGui_ImplVulkan_SetMinImageCount().
ImGui_ImplVulkan_GetBackendData()
static ImGui_ImplVulkan_Data * ImGui_ImplVulkan_GetBackendData () static
Definition at line 401 of file imgui_impl_vulkan.cpp.
References ImGuiIO::BackendRendererUserData, ImGui::GetCurrentContext(), and ImGui::GetIO().
Referenced by check_vk_result(), CreateOrResizeBuffer(), ImGui_ImplVulkan_AddTexture(), ImGui_ImplVulkan_CreateDeviceObjects(), ImGui_ImplVulkan_CreateMainPipeline(), ImGui_ImplVulkan_CreatePipeline(), ImGui_ImplVulkan_CreateShaderModules(), ImGui_ImplVulkan_DestroyDeviceObjects(), ImGui_ImplVulkan_DestroyTexture(), ImGui_ImplVulkan_MemoryType(), ImGui_ImplVulkan_NewFrame(), ImGui_ImplVulkan_RemoveTexture(), ImGui_ImplVulkan_RenderDrawData(), ImGui_ImplVulkan_SetMinImageCount(), ImGui_ImplVulkan_SetupRenderState(), ImGui_ImplVulkan_Shutdown(), and ImGui_ImplVulkan_UpdateTexture().
ImGui_ImplVulkan_GetDefaultApiVersion()
static uint32_t ImGui_ImplVulkan_GetDefaultApiVersion () static
Definition at line 1213 of file imgui_impl_vulkan.cpp.
Referenced by ImGui_ImplVulkan_Init(), and ImGui_ImplVulkan_LoadFunctions().
ImGui_ImplVulkan_Init()
bool ImGui_ImplVulkan_Init (ImGui_ImplVulkan_InitInfo * info)
Definition at line 1251 of file imgui_impl_vulkan.cpp.
References ImGui_ImplVulkan_InitInfo::ApiVersion, ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGui_ImplVulkan_InitInfo::DescriptorPool, ImGui_ImplVulkan_InitInfo::DescriptorPoolSize, ImGui_ImplVulkan_InitInfo::Device, g_FunctionsLoaded, ImGui::GetIO(), IM_ASSERT, IM_NEW, ImGui_ImplVulkan_InitInfo::ImageCount, IMGUI_CHECKVERSION, ImGui_ImplVulkan_CreateDeviceObjects(), ImGui_ImplVulkan_GetDefaultApiVersion(), ImGuiBackendFlags_RendererHasTextures, ImGuiBackendFlags_RendererHasVtxOffset, ImGui_ImplVulkan_InitInfo::Instance, ImGui_ImplVulkan_InitInfo::MinImageCount, ImGui_ImplVulkan_Data::NonCoherentAtomSize, ImGui_ImplVulkan_InitInfo::PhysicalDevice, ImGui_ImplVulkan_InitInfo::PipelineInfoMain, ImGui_ImplVulkan_InitInfo::Queue, ImGui_ImplVulkan_PipelineInfo::RenderPass, ImGui_ImplVulkan_InitInfo::UseDynamicRendering, and ImGui_ImplVulkan_Data::VulkanInitInfo.
Referenced by main().
ImGui_ImplVulkan_LoadFunctions()
bool ImGui_ImplVulkan_LoadFunctions (uint32_t api_version, PFN_vkVoidFunction(*)(const char *function_name, void *user_data) loader_func, void * user_data)
Definition at line 1222 of file imgui_impl_vulkan.cpp.
References g_FunctionsLoaded, IM_UNUSED, and ImGui_ImplVulkan_GetDefaultApiVersion().
ImGui_ImplVulkan_MemoryType()
static uint32_t ImGui_ImplVulkan_MemoryType (VkMemoryPropertyFlags properties, uint32_t type_bits) static
Definition at line 406 of file imgui_impl_vulkan.cpp.
References ImGui_ImplVulkan_GetBackendData(), ImGui_ImplVulkan_InitInfo::PhysicalDevice, and ImGui_ImplVulkan_Data::VulkanInitInfo.
Referenced by CreateOrResizeBuffer(), and ImGui_ImplVulkan_UpdateTexture().
ImGui_ImplVulkan_NewFrame()
void ImGui_ImplVulkan_NewFrame ()
Definition at line 1324 of file imgui_impl_vulkan.cpp.
References IM_ASSERT, IM_UNUSED, and ImGui_ImplVulkan_GetBackendData().
Referenced by main().
ImGui_ImplVulkan_RemoveTexture()
void ImGui_ImplVulkan_RemoveTexture (VkDescriptorSet descriptor_set)
Definition at line 1382 of file imgui_impl_vulkan.cpp.
References ImGui_ImplVulkan_Data::DescriptorPool, ImGui_ImplVulkan_InitInfo::DescriptorPool, ImGui_ImplVulkan_InitInfo::Device, ImGui_ImplVulkan_GetBackendData(), and ImGui_ImplVulkan_Data::VulkanInitInfo.
Referenced by ImGui_ImplVulkan_DestroyTexture().
ImGui_ImplVulkan_RenderDrawData()
void ImGui_ImplVulkan_RenderDrawData (ImDrawData * draw_data, VkCommandBuffer command_buffer, VkPipeline pipeline)
Definition at line 513 of file imgui_impl_vulkan.cpp.
References AlignBufferSize(), ImGui_ImplVulkan_Data::BufferMemoryAlignment, check_vk_result(), ImDrawCmd::ClipRect, ImDrawList::CmdBuffer, ImDrawData::CmdLists, ImGui_ImplVulkan_RenderState::CommandBuffer, ImGui_ImplVulkan_WindowRenderBuffers::Count, CreateOrResizeBuffer(), ImVector< T >::Data, ImGui_ImplVulkan_InitInfo::Device, ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImDrawCmd::ElemCount, ImDrawData::FramebufferScale, ImGui_ImplVulkan_WindowRenderBuffers::FrameRenderBuffers, ImGui::GetPlatformIO(), ImDrawCmd::GetTexID(), ImDrawList::IdxBuffer, ImDrawCmd::IdxOffset, IM_ASSERT, ImGui_ImplVulkan_InitInfo::ImageCount, ImDrawCallback_ResetRenderState, ImGui_ImplVulkan_GetBackendData(), ImGui_ImplVulkan_SetupRenderState(), ImGui_ImplVulkan_UpdateTexture(), ImTextureStatus_OK, ImGui_ImplVulkan_WindowRenderBuffers::Index, ImGui_ImplVulkan_FrameRenderBuffers::IndexBuffer, ImGui_ImplVulkan_FrameRenderBuffers::IndexBufferMemory, ImGui_ImplVulkan_FrameRenderBuffers::IndexBufferSize, ImGui_ImplVulkan_Data::MainWindowRenderBuffers, ImGui_ImplVulkan_Data::Pipeline, ImGui_ImplVulkan_RenderState::Pipeline, ImGui_ImplVulkan_Data::PipelineLayout, ImGui_ImplVulkan_RenderState::PipelineLayout, ImGuiPlatformIO::Renderer_RenderState, ImVector< T >::resize(), ImVector< T >::Size, ImVector< T >::size_in_bytes(), ImDrawData::Textures, ImDrawData::TotalIdxCount, ImDrawData::TotalVtxCount, ImDrawCmd::UserCallback, ImGui_ImplVulkan_FrameRenderBuffers::VertexBuffer, ImGui_ImplVulkan_FrameRenderBuffers::VertexBufferMemory, ImGui_ImplVulkan_FrameRenderBuffers::VertexBufferSize, ImDrawList::VtxBuffer, ImDrawCmd::VtxOffset, ImGui_ImplVulkan_Data::VulkanInitInfo, ImVec4::w, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by FrameRender().
ImGui_ImplVulkan_SetMinImageCount()
void ImGui_ImplVulkan_SetMinImageCount (uint32_t min_image_count)
Definition at line 1331 of file imgui_impl_vulkan.cpp.
References ImGui_ImplVulkan_InitInfo::Allocator, check_vk_result(), ImGui_ImplVulkan_InitInfo::Device, IM_ASSERT, ImGui_ImplVulkan_DestroyWindowRenderBuffers(), ImGui_ImplVulkan_GetBackendData(), ImGui_ImplVulkan_Data::MainWindowRenderBuffers, ImGui_ImplVulkan_InitInfo::MinImageCount, and ImGui_ImplVulkan_Data::VulkanInitInfo.
Referenced by main(), and WndProc().
ImGui_ImplVulkan_SetupRenderState()
static void ImGui_ImplVulkan_SetupRenderState (ImDrawData * draw_data, VkPipeline pipeline, VkCommandBuffer command_buffer, ImGui_ImplVulkan_FrameRenderBuffers * rb, int fb_width, int fb_height) static
Definition at line 468 of file imgui_impl_vulkan.cpp.
References ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImGui_ImplVulkan_GetBackendData(), ImGui_ImplVulkan_FrameRenderBuffers::IndexBuffer, ImGui_ImplVulkan_Data::PipelineLayout, ImDrawData::TotalVtxCount, ImGui_ImplVulkan_FrameRenderBuffers::VertexBuffer, ImVec2::x, and ImVec2::y.
Referenced by ImGui_ImplVulkan_RenderDrawData().
ImGui_ImplVulkan_Shutdown()
void ImGui_ImplVulkan_Shutdown ()
Definition at line 1308 of file imgui_impl_vulkan.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGuiPlatformIO::ClearRendererHandlers(), ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplVulkan_DestroyDeviceObjects(), ImGui_ImplVulkan_GetBackendData(), ImGuiBackendFlags_RendererHasTextures, and ImGuiBackendFlags_RendererHasVtxOffset.
Referenced by main().
ImGui_ImplVulkan_UpdateTexture()
void ImGui_ImplVulkan_UpdateTexture (ImTextureData * tex)
Definition at line 686 of file imgui_impl_vulkan.cpp.
References AlignBufferSize(), ImGui_ImplVulkan_InitInfo::Allocator, ImTextureData::BackendUserData, ImGui_ImplVulkan_Data::BufferMemoryAlignment, ImTextureData::BytesPerPixel, check_vk_result(), ImGui_ImplVulkan_Texture::DescriptorSet, ImGui_ImplVulkan_InitInfo::Device, ImTextureData::Format, ImTextureData::GetPixelsAt(), ImTextureRect::h, ImTextureData::Height, IM_ASSERT, IM_MAX, IM_NEW, ImGui_ImplVulkan_Texture::Image, ImGui_ImplVulkan_InitInfo::ImageCount, ImGui_ImplVulkan_Texture::ImageView, ImGui_ImplVulkan_AddTexture(), ImGui_ImplVulkan_DestroyTexture(), ImGui_ImplVulkan_GetBackendData(), ImGui_ImplVulkan_MemoryType(), ImTextureFormat_RGBA32, ImTextureID_Invalid, ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImGui_ImplVulkan_Texture::Memory, ImGui_ImplVulkan_InitInfo::MinAllocationSize, ImGui_ImplVulkan_Data::NonCoherentAtomSize, ImGui_ImplVulkan_InitInfo::Queue, ImTextureData::SetStatus(), ImTextureData::SetTexID(), ImTextureData::Status, ImGui_ImplVulkan_Data::TexCommandBuffer, ImGui_ImplVulkan_Data::TexCommandPool, ImTextureData::TexID, ImGui_ImplVulkan_Data::TexSamplerLinear, ImTextureData::UnusedFrames, ImTextureData::UpdateRect, ImGui_ImplVulkan_Data::VulkanInitInfo, ImTextureRect::w, ImTextureData::Width, ImTextureRect::x, and ImTextureRect::y.
Referenced by ImGui_ImplVulkan_RenderDrawData().
ImGui_ImplVulkanH_CreateOrResizeWindow()
void ImGui_ImplVulkanH_CreateOrResizeWindow (VkInstance instance, VkPhysicalDevice physical_device, VkDevice device, ImGui_ImplVulkanH_Window * wd, uint32_t queue_family, const VkAllocationCallbacks * allocator, int width, int height, uint32_t min_image_count, VkImageUsageFlags image_usage)
Definition at line 1772 of file imgui_impl_vulkan.cpp.
References check_vk_result(), ImGui_ImplVulkanH_Window::Frames, g_FunctionsLoaded, IM_ASSERT, ImGui_ImplVulkanH_Window::ImageCount, ImGui_ImplVulkanH_CreateWindowCommandBuffers(), and ImGui_ImplVulkanH_CreateWindowSwapChain().
Referenced by main(), SetupVulkanWindow(), and WndProc().
ImGui_ImplVulkanH_CreateWindowCommandBuffers()
void ImGui_ImplVulkanH_CreateWindowCommandBuffers (VkPhysicalDevice physical_device, VkDevice device, ImGui_ImplVulkanH_Window * wd, uint32_t queue_family, const VkAllocationCallbacks * allocator)
Definition at line 1536 of file imgui_impl_vulkan.cpp.
References check_vk_result(), ImGui_ImplVulkanH_Frame::CommandBuffer, ImGui_ImplVulkanH_Frame::CommandPool, ImGui_ImplVulkanH_Frame::Fence, ImGui_ImplVulkanH_Window::Frames, ImGui_ImplVulkanH_Window::FrameSemaphores, IM_ASSERT, IM_UNUSED, ImGui_ImplVulkanH_FrameSemaphores::ImageAcquiredSemaphore, ImGui_ImplVulkanH_Window::ImageCount, ImGui_ImplVulkanH_FrameSemaphores::RenderCompleteSemaphore, and ImGui_ImplVulkanH_Window::SemaphoreCount.
Referenced by ImGui_ImplVulkanH_CreateOrResizeWindow().
ImGui_ImplVulkanH_CreateWindowSwapChain()
void ImGui_ImplVulkanH_CreateWindowSwapChain (VkPhysicalDevice physical_device, VkDevice device, ImGui_ImplVulkanH_Window * wd, const VkAllocationCallbacks * allocator, int w, int h, uint32_t min_image_count, VkImageUsageFlags image_usage)
Definition at line 1599 of file imgui_impl_vulkan.cpp.
References ImGui_ImplVulkanH_Frame::Backbuffer, ImGui_ImplVulkanH_Frame::BackbufferView, check_vk_result(), ImVector< T >::clear(), ImGui_ImplVulkanH_Window::ClearEnable, ImVector< T >::Data, ImGui_ImplVulkanH_Frame::Framebuffer, ImGui_ImplVulkanH_Window::Frames, ImGui_ImplVulkanH_Window::FrameSemaphores, ImGui_ImplVulkanH_Window::Height, IM_ARRAYSIZE, IM_ASSERT, ImGui_ImplVulkanH_Window::ImageCount, ImGui_ImplVulkanH_DestroyFrame(), ImGui_ImplVulkanH_DestroyFrameSemaphores(), ImGui_ImplVulkanH_GetMinImageCountFromPresentMode(), ImGui_ImplVulkanH_Window::Pipeline, ImGui_ImplVulkanH_Window::PresentMode, ImGui_ImplVulkanH_Window::RenderPass, ImVector< T >::resize(), ImGui_ImplVulkanH_Window::SemaphoreCount, ImVector< T >::size_in_bytes(), ImGui_ImplVulkanH_Window::Surface, ImGui_ImplVulkanH_Window::SurfaceFormat, ImGui_ImplVulkanH_Window::Swapchain, ImGui_ImplVulkanH_Window::UseDynamicRendering, and ImGui_ImplVulkanH_Window::Width.
Referenced by ImGui_ImplVulkanH_CreateOrResizeWindow().
ImGui_ImplVulkanH_DestroyFrame()
void ImGui_ImplVulkanH_DestroyFrame (VkDevice device, ImGui_ImplVulkanH_Frame * fd, const VkAllocationCallbacks * allocator)
Definition at line 1875 of file imgui_impl_vulkan.cpp.
References ImGui_ImplVulkanH_Frame::BackbufferView, ImGui_ImplVulkanH_Frame::CommandBuffer, ImGui_ImplVulkanH_Frame::CommandPool, ImGui_ImplVulkanH_Frame::Fence, and ImGui_ImplVulkanH_Frame::Framebuffer.
Referenced by ImGui_ImplVulkanH_CreateWindowSwapChain(), and ImGui_ImplVulkanH_DestroyWindow().
ImGui_ImplVulkanH_DestroyFrameSemaphores()
void ImGui_ImplVulkanH_DestroyFrameSemaphores (VkDevice device, ImGui_ImplVulkanH_FrameSemaphores * fsd, const VkAllocationCallbacks * allocator)
Definition at line 1888 of file imgui_impl_vulkan.cpp.
References ImGui_ImplVulkanH_FrameSemaphores::ImageAcquiredSemaphore, and ImGui_ImplVulkanH_FrameSemaphores::RenderCompleteSemaphore.
Referenced by ImGui_ImplVulkanH_CreateWindowSwapChain(), and ImGui_ImplVulkanH_DestroyWindow().
ImGui_ImplVulkanH_DestroyWindow()
void ImGui_ImplVulkanH_DestroyWindow (VkInstance instance, VkDevice device, ImGui_ImplVulkanH_Window * wd, const VkAllocationCallbacks * allocator)
Definition at line 1856 of file imgui_impl_vulkan.cpp.
References ImVector< T >::clear(), ImGui_ImplVulkanH_Window::Frames, ImGui_ImplVulkanH_Window::FrameSemaphores, ImGui_ImplVulkanH_Window::ImageCount, ImGui_ImplVulkanH_DestroyFrame(), ImGui_ImplVulkanH_DestroyFrameSemaphores(), ImGui_ImplVulkanH_Window::Pipeline, ImGui_ImplVulkanH_Window::RenderPass, ImGui_ImplVulkanH_Window::SemaphoreCount, ImGui_ImplVulkanH_Window::Surface, and ImGui_ImplVulkanH_Window::Swapchain.
Referenced by CleanupVulkanWindow().
ImGui_ImplVulkanH_GetMinImageCountFromPresentMode()
int ImGui_ImplVulkanH_GetMinImageCountFromPresentMode (VkPresentModeKHR present_mode)
Definition at line 1586 of file imgui_impl_vulkan.cpp.
References IM_ASSERT.
Referenced by ImGui_ImplVulkanH_CreateWindowSwapChain().
ImGui_ImplVulkanH_SelectPhysicalDevice()
VkPhysicalDevice ImGui_ImplVulkanH_SelectPhysicalDevice (VkInstance instance)
Definition at line 1493 of file imgui_impl_vulkan.cpp.
References check_vk_result(), ImVector< T >::Data, IM_ASSERT, and ImVector< T >::resize().
Referenced by SetupVulkan().
ImGui_ImplVulkanH_SelectPresentMode()
VkPresentModeKHR ImGui_ImplVulkanH_SelectPresentMode (VkPhysicalDevice physical_device, VkSurfaceKHR surface, const VkPresentModeKHR * request_modes, int request_modes_count)
Definition at line 1470 of file imgui_impl_vulkan.cpp.
References ImVector< T >::Data, g_FunctionsLoaded, IM_ASSERT, and ImVector< T >::resize().
Referenced by SetupVulkanWindow().
ImGui_ImplVulkanH_SelectQueueFamilyIndex()
uint32_t ImGui_ImplVulkanH_SelectQueueFamilyIndex (VkPhysicalDevice physical_device)
Definition at line 1523 of file imgui_impl_vulkan.cpp.
References ImVector< T >::Data, and ImVector< T >::resize().
Referenced by SetupVulkan().
ImGui_ImplVulkanH_SelectSurfaceFormat()
VkSurfaceFormatKHR ImGui_ImplVulkanH_SelectSurfaceFormat (VkPhysicalDevice physical_device, VkSurfaceKHR surface, const VkFormat * request_formats, int request_formats_count, VkColorSpaceKHR request_color_space)
Definition at line 1425 of file imgui_impl_vulkan.cpp.
References ImVector< T >::Data, g_FunctionsLoaded, IM_ASSERT, and ImVector< T >::resize().
Referenced by SetupVulkanWindow().
Variable Documentation
__glsl_shader_frag_spv
uint32_t __glsl_shader_frag_spv[] static
Initial value:
=
{
    0x07230203,0x00010000,0x00080001,0x0000001e,0x00000000,0x00020011,0x00000001,0x0006000b,
    0x00000001,0x4c534c47,0x6474732e,0x3035342e,0x00000000,0x0003000e,0x00000000,0x00000001,
    0x0007000f,0x00000004,0x00000004,0x6e69616d,0x00000000,0x00000009,0x0000000d,0x00030010,
    0x00000004,0x00000007,0x00030003,0x00000002,0x000001c2,0x00040005,0x00000004,0x6e69616d,
    0x00000000,0x00040005,0x00000009,0x6c6f4366,0x0000726f,0x00030005,0x0000000b,0x00000000,
    0x00050006,0x0000000b,0x00000000,0x6f6c6f43,0x00000072,0x00040006,0x0000000b,0x00000001,
    0x00005655,0x00030005,0x0000000d,0x00006e49,0x00050005,0x00000016,0x78655473,0x65727574,
    0x00000000,0x00040047,0x00000009,0x0000001e,0x00000000,0x00040047,0x0000000d,0x0000001e,
    0x00000000,0x00040047,0x00000016,0x00000022,0x00000000,0x00040047,0x00000016,0x00000021,
    0x00000000,0x00020013,0x00000002,0x00030021,0x00000003,0x00000002,0x00030016,0x00000006,
    0x00000020,0x00040017,0x00000007,0x00000006,0x00000004,0x00040020,0x00000008,0x00000003,
    0x00000007,0x0004003b,0x00000008,0x00000009,0x00000003,0x00040017,0x0000000a,0x00000006,
    0x00000002,0x0004001e,0x0000000b,0x00000007,0x0000000a,0x00040020,0x0000000c,0x00000001,
    0x0000000b,0x0004003b,0x0000000c,0x0000000d,0x00000001,0x00040015,0x0000000e,0x00000020,
    0x00000001,0x0004002b,0x0000000e,0x0000000f,0x00000000,0x00040020,0x00000010,0x00000001,
    0x00000007,0x00090019,0x00000013,0x00000006,0x00000001,0x00000000,0x00000000,0x00000000,
    0x00000001,0x00000000,0x0003001b,0x00000014,0x00000013,0x00040020,0x00000015,0x00000000,
    0x00000014,0x0004003b,0x00000015,0x00000016,0x00000000,0x0004002b,0x0000000e,0x00000018,
    0x00000001,0x00040020,0x00000019,0x00000001,0x0000000a,0x00050036,0x00000002,0x00000004,
    0x00000000,0x00000003,0x000200f8,0x00000005,0x00050041,0x00000010,0x00000011,0x0000000d,
    0x0000000f,0x0004003d,0x00000007,0x00000012,0x00000011,0x0004003d,0x00000014,0x00000017,
    0x00000016,0x00050041,0x00000019,0x0000001a,0x0000000d,0x00000018,0x0004003d,0x0000000a,
    0x0000001b,0x0000001a,0x00050057,0x00000007,0x0000001c,0x00000017,0x0000001b,0x00050085,
    0x00000007,0x0000001d,0x00000012,0x0000001c,0x0003003e,0x00000009,0x0000001d,0x000100fd,
    0x00010038
}
Definition at line 365 of file imgui_impl_vulkan.cpp.
Referenced by ImGui_ImplVulkan_CreateShaderModules().
__glsl_shader_vert_spv
uint32_t __glsl_shader_vert_spv[] static
Definition at line 308 of file imgui_impl_vulkan.cpp.
Referenced by ImGui_ImplVulkan_CreateShaderModules().
g_FunctionsLoaded
bool g_FunctionsLoaded = true static
Definition at line 135 of file imgui_impl_vulkan.cpp.
Referenced by ImGui_ImplVulkan_Init(), ImGui_ImplVulkan_LoadFunctions(), ImGui_ImplVulkanH_CreateOrResizeWindow(), ImGui_ImplVulkanH_SelectPresentMode(), and ImGui_ImplVulkanH_SelectSurfaceFormat().