SignalProcessing: examples/imgui/backends/imgui_impl_allegro5.cpp File Reference
imgui_impl_allegro5.cpp File Reference
#include "imgui.h"
#include "imgui_impl_allegro5.h"
#include <stdint.h>
#include <cstring>
#include <allegro5/allegro.h>
#include <allegro5/allegro_primitives.h>
Classes
struct ImDrawVertAllegro
struct ImGui_ImplAllegro5_Data
Macros
#define ALLEGRO_HAS_CLIPBOARD ((ALLEGRO_VERSION_INT & ~ALLEGRO_UNSTABLE_BIT) >= ((5 << 24) | (1 << 16) | (12 << 8)))
#define ALLEGRO_HAS_DRAW_INDEXED_PRIM ((ALLEGRO_VERSION_INT & ~ALLEGRO_UNSTABLE_BIT) >= ((5 << 24) | (2 << 16) | (5 << 8)))
#define DRAW_VERT_IMGUI_TO_ALLEGRO(DST, SRC) { (DST)->pos = (SRC)->pos; (DST)->uv = (SRC)->uv; unsigned char* c = (unsigned char*)&(SRC)->col; (DST)->col = al_map_rgba(c[0], c[1], c[2], c[3]); }
Functions
static ImGui_ImplAllegro5_Data * ImGui_ImplAllegro5_GetBackendData ()
static void ImGui_ImplAllegro5_SetupRenderState (ImDrawData *draw_data)
void ImGui_ImplAllegro5_RenderDrawData (ImDrawData *draw_data)
bool ImGui_ImplAllegro5_CreateDeviceObjects ()
void ImGui_ImplAllegro5_UpdateTexture (ImTextureData *tex)
void ImGui_ImplAllegro5_InvalidateDeviceObjects ()
ImGuiKey ImGui_ImplAllegro5_KeyCodeToImGuiKey (int key_code)
bool ImGui_ImplAllegro5_Init (ALLEGRO_DISPLAY *display)
void ImGui_ImplAllegro5_Shutdown ()
void ImGui_ImplAllegro5_SetDisplay (ALLEGRO_DISPLAY *display)
static void ImGui_ImplAllegro5_UpdateKeyModifiers ()
bool ImGui_ImplAllegro5_ProcessEvent (ALLEGRO_EVENT *ev)
static void ImGui_ImplAllegro5_UpdateMouseCursor ()
void ImGui_ImplAllegro5_NewFrame ()
Macro Definition Documentation
ALLEGRO_HAS_CLIPBOARD
#define ALLEGRO_HAS_CLIPBOARD ((ALLEGRO_VERSION_INT & ~ALLEGRO_UNSTABLE_BIT) >= ((5 << 24) | (1 << 16) | (12 << 8)))
Definition at line 76 of file imgui_impl_allegro5.cpp.
ALLEGRO_HAS_DRAW_INDEXED_PRIM
#define ALLEGRO_HAS_DRAW_INDEXED_PRIM ((ALLEGRO_VERSION_INT & ~ALLEGRO_UNSTABLE_BIT) >= ((5 << 24) | (2 << 16) | (5 << 8)))
Definition at line 77 of file imgui_impl_allegro5.cpp.
DRAW_VERT_IMGUI_TO_ALLEGRO
#define DRAW_VERT_IMGUI_TO_ALLEGRO (DST, SRC) { (DST)->pos = (SRC)->pos; (DST)->uv = (SRC)->uv; unsigned char* c = (unsigned char*)&(SRC)->col; (DST)->col = al_map_rgba(c[0], c[1], c[2], c[3]); }
Definition at line 95 of file imgui_impl_allegro5.cpp.
Function Documentation
ImGui_ImplAllegro5_CreateDeviceObjects()
bool ImGui_ImplAllegro5_CreateDeviceObjects ()
Definition at line 244 of file imgui_impl_allegro5.cpp.
References ImGui_ImplAllegro5_GetBackendData(), and ImGui_ImplAllegro5_Data::MouseCursorInvisible.
Referenced by ImGui_ImplAllegro5_NewFrame(), and main().
ImGui_ImplAllegro5_GetBackendData()
static ImGui_ImplAllegro5_Data * ImGui_ImplAllegro5_GetBackendData () static
Definition at line 117 of file imgui_impl_allegro5.cpp.
References ImGuiIO::BackendPlatformUserData, ImGui::GetCurrentContext(), and ImGui::GetIO().
Referenced by ImGui_ImplAllegro5_CreateDeviceObjects(), ImGui_ImplAllegro5_InvalidateDeviceObjects(), ImGui_ImplAllegro5_NewFrame(), ImGui_ImplAllegro5_ProcessEvent(), ImGui_ImplAllegro5_RenderDrawData(), ImGui_ImplAllegro5_SetDisplay(), ImGui_ImplAllegro5_Shutdown(), and ImGui_ImplAllegro5_UpdateMouseCursor().
ImGui_ImplAllegro5_Init()
bool ImGui_ImplAllegro5_Init (ALLEGRO_DISPLAY * display)
Definition at line 472 of file imgui_impl_allegro5.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendPlatformName, ImGuiIO::BackendPlatformUserData, ImGuiIO::BackendRendererName, ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_NEW, IMGUI_CHECKVERSION, ImGui_ImplAllegro5_SetDisplay(), ImGuiBackendFlags_HasMouseCursors, ImGuiBackendFlags_RendererHasTextures, ImGui_ImplAllegro5_Data::LastCursor, ImGuiPlatformIO::Platform_GetClipboardTextFn, and ImGuiPlatformIO::Platform_SetClipboardTextFn.
Referenced by main().
ImGui_ImplAllegro5_InvalidateDeviceObjects()
void ImGui_ImplAllegro5_InvalidateDeviceObjects ()
Definition at line 320 of file imgui_impl_allegro5.cpp.
References ImGui::GetPlatformIO(), ImGui_ImplAllegro5_GetBackendData(), ImGui_ImplAllegro5_UpdateTexture(), ImTextureStatus_WantDestroy, ImGui_ImplAllegro5_Data::MouseCursorInvisible, and ImGuiPlatformIO::Textures.
Referenced by ImGui_ImplAllegro5_Shutdown(), and main().
ImGui_ImplAllegro5_KeyCodeToImGuiKey()
ImGuiKey ImGui_ImplAllegro5_KeyCodeToImGuiKey (int key_code)
Definition at line 359 of file imgui_impl_allegro5.cpp.
References ImGuiKey_0, ImGuiKey_1, ImGuiKey_2, ImGuiKey_3, ImGuiKey_4, ImGuiKey_5, ImGuiKey_6, ImGuiKey_7, ImGuiKey_8, ImGuiKey_9, ImGuiKey_A, ImGuiKey_Apostrophe, ImGuiKey_B, ImGuiKey_Backslash, ImGuiKey_Backspace, ImGuiKey_C, ImGuiKey_CapsLock, ImGuiKey_Comma, ImGuiKey_D, ImGuiKey_Delete, ImGuiKey_DownArrow, ImGuiKey_E, ImGuiKey_End, ImGuiKey_Enter, ImGuiKey_Equal, ImGuiKey_Escape, ImGuiKey_F, ImGuiKey_F1, ImGuiKey_F10, ImGuiKey_F11, ImGuiKey_F12, ImGuiKey_F2, ImGuiKey_F3, ImGuiKey_F4, ImGuiKey_F5, ImGuiKey_F6, ImGuiKey_F7, ImGuiKey_F8, ImGuiKey_F9, ImGuiKey_G, ImGuiKey_GraveAccent, ImGuiKey_H, ImGuiKey_Home, ImGuiKey_I, ImGuiKey_Insert, ImGuiKey_J, ImGuiKey_K, ImGuiKey_Keypad0, ImGuiKey_Keypad1, ImGuiKey_Keypad2, ImGuiKey_Keypad3, ImGuiKey_Keypad4, ImGuiKey_Keypad5, ImGuiKey_Keypad6, ImGuiKey_Keypad7, ImGuiKey_Keypad8, ImGuiKey_Keypad9, ImGuiKey_KeypadAdd, ImGuiKey_KeypadDecimal, ImGuiKey_KeypadDivide, ImGuiKey_KeypadEnter, ImGuiKey_KeypadEqual, ImGuiKey_KeypadMultiply, ImGuiKey_KeypadSubtract, ImGuiKey_L, ImGuiKey_LeftAlt, ImGuiKey_LeftArrow, ImGuiKey_LeftBracket, ImGuiKey_LeftCtrl, ImGuiKey_LeftShift, ImGuiKey_LeftSuper, ImGuiKey_M, ImGuiKey_Menu, ImGuiKey_Minus, ImGuiKey_N, ImGuiKey_None, ImGuiKey_NumLock, ImGuiKey_O, ImGuiKey_P, ImGuiKey_PageDown, ImGuiKey_PageUp, ImGuiKey_Pause, ImGuiKey_Period, ImGuiKey_PrintScreen, ImGuiKey_Q, ImGuiKey_R, ImGuiKey_RightAlt, ImGuiKey_RightArrow, ImGuiKey_RightBracket, ImGuiKey_RightCtrl, ImGuiKey_RightShift, ImGuiKey_RightSuper, ImGuiKey_S, ImGuiKey_ScrollLock, ImGuiKey_Semicolon, ImGuiKey_Slash, ImGuiKey_Space, ImGuiKey_T, ImGuiKey_Tab, ImGuiKey_U, ImGuiKey_UpArrow, ImGuiKey_V, ImGuiKey_W, ImGuiKey_X, ImGuiKey_Y, and ImGuiKey_Z.
Referenced by ImGui_ImplAllegro5_ProcessEvent().
ImGui_ImplAllegro5_NewFrame()
void ImGui_ImplAllegro5_NewFrame ()
Definition at line 667 of file imgui_impl_allegro5.cpp.
References ImGuiIO::AddKeyEvent(), ImGuiIO::DeltaTime, ImGui_ImplAllegro5_Data::Display, ImGuiIO::DisplaySize, ImGui::GetIO(), IM_ASSERT, ImGui_ImplAllegro5_CreateDeviceObjects(), ImGui_ImplAllegro5_GetBackendData(), ImGui_ImplAllegro5_UpdateMouseCursor(), ImGuiKey_PrintScreen, ImGui_ImplAllegro5_Data::MouseCursorInvisible, and ImGui_ImplAllegro5_Data::Time.
Referenced by main().
ImGui_ImplAllegro5_ProcessEvent()
bool ImGui_ImplAllegro5_ProcessEvent (ALLEGRO_EVENT * ev)
Definition at line 562 of file imgui_impl_allegro5.cpp.
References ImGuiIO::AddFocusEvent(), ImGuiIO::AddInputCharacter(), ImGuiIO::AddKeyEvent(), ImGuiIO::AddMouseButtonEvent(), ImGuiIO::AddMousePosEvent(), ImGuiIO::AddMouseWheelEvent(), ImGui_ImplAllegro5_Data::Display, ImGui::GetIO(), IM_ASSERT, ImGui_ImplAllegro5_GetBackendData(), ImGui_ImplAllegro5_KeyCodeToImGuiKey(), ImGui_ImplAllegro5_UpdateKeyModifiers(), and ImGuiIO::SetKeyEventNativeData().
Referenced by main().
ImGui_ImplAllegro5_RenderDrawData()
void ImGui_ImplAllegro5_RenderDrawData (ImDrawData * draw_data)
Definition at line 140 of file imgui_impl_allegro5.cpp.
References ImGui_ImplAllegro5_Data::BufIndices, ImGui_ImplAllegro5_Data::BufVertices, ImDrawCmd::ClipRect, ImDrawList::CmdBuffer, ImDrawData::CmdLists, ImVector< T >::Data, ImDrawData::DisplayPos, ImDrawData::DisplaySize, DRAW_VERT_IMGUI_TO_ALLEGRO, ImDrawCmd::ElemCount, ImDrawCmd::GetTexID(), ImDrawList::IdxBuffer, ImDrawCmd::IdxOffset, ImDrawCallback_ResetRenderState, ImGui_ImplAllegro5_GetBackendData(), ImGui_ImplAllegro5_SetupRenderState(), ImGui_ImplAllegro5_UpdateTexture(), ImTextureStatus_OK, ImVector< T >::resize(), ImVector< T >::Size, ImDrawData::Textures, ImDrawCmd::UserCallback, ImGui_ImplAllegro5_Data::VertexDecl, ImDrawList::VtxBuffer, ImVec4::w, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by main().
ImGui_ImplAllegro5_SetDisplay()
void ImGui_ImplAllegro5_SetDisplay (ALLEGRO_DISPLAY * display)
Definition at line 519 of file imgui_impl_allegro5.cpp.
References ImGui_ImplAllegro5_Data::Display, ImGui_ImplAllegro5_GetBackendData(), and ImGui_ImplAllegro5_Data::VertexDecl.
Referenced by ImGui_ImplAllegro5_Init().
ImGui_ImplAllegro5_SetupRenderState()
static void ImGui_ImplAllegro5_SetupRenderState (ImDrawData * draw_data) static
Definition at line 119 of file imgui_impl_allegro5.cpp.
References ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImVec2::x, and ImVec2::y.
Referenced by ImGui_ImplAllegro5_RenderDrawData().
ImGui_ImplAllegro5_Shutdown()
void ImGui_ImplAllegro5_Shutdown ()
Definition at line 498 of file imgui_impl_allegro5.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendPlatformName, ImGuiIO::BackendPlatformUserData, ImGuiIO::BackendRendererName, ImGuiPlatformIO::ClearPlatformHandlers(), ImGuiPlatformIO::ClearRendererHandlers(), ImGui_ImplAllegro5_Data::ClipboardTextData, ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplAllegro5_GetBackendData(), ImGui_ImplAllegro5_InvalidateDeviceObjects(), ImGuiBackendFlags_HasMouseCursors, ImGuiBackendFlags_RendererHasTextures, and ImGui_ImplAllegro5_Data::VertexDecl.
Referenced by main().
ImGui_ImplAllegro5_UpdateKeyModifiers()
static void ImGui_ImplAllegro5_UpdateKeyModifiers () static
Definition at line 547 of file imgui_impl_allegro5.cpp.
References ImGuiIO::AddKeyEvent(), ImGui::GetIO(), ImGuiMod_Alt, ImGuiMod_Ctrl, ImGuiMod_Shift, and ImGuiMod_Super.
Referenced by ImGui_ImplAllegro5_ProcessEvent().
ImGui_ImplAllegro5_UpdateMouseCursor()
static void ImGui_ImplAllegro5_UpdateMouseCursor () static
Definition at line 628 of file imgui_impl_allegro5.cpp.
References ImGuiIO::ConfigFlags, ImGui_ImplAllegro5_Data::Display, ImGui::GetIO(), ImGui::GetMouseCursor(), ImGui_ImplAllegro5_GetBackendData(), ImGuiConfigFlags_NoMouseCursorChange, ImGuiMouseCursor_None, ImGuiMouseCursor_NotAllowed, ImGuiMouseCursor_Progress, ImGuiMouseCursor_ResizeAll, ImGuiMouseCursor_ResizeEW, ImGuiMouseCursor_ResizeNESW, ImGuiMouseCursor_ResizeNS, ImGuiMouseCursor_ResizeNWSE, ImGuiMouseCursor_TextInput, ImGuiMouseCursor_Wait, ImGui_ImplAllegro5_Data::LastCursor, ImGui_ImplAllegro5_Data::MouseCursorInvisible, and ImGuiIO::MouseDrawCursor.
Referenced by ImGui_ImplAllegro5_NewFrame().
ImGui_ImplAllegro5_UpdateTexture()
void ImGui_ImplAllegro5_UpdateTexture (ImTextureData * tex)
Definition at line 257 of file imgui_impl_allegro5.cpp.
References ImTextureData::BackendUserData, ImTextureData::BytesPerPixel, ImTextureData::Format, ImTextureData::GetPixels(), ImTextureData::GetPixelsAt(), ImTextureData::GetSizeInBytes(), ImTextureRect::h, ImTextureData::Height, IM_ASSERT, ImTextureFormat_RGBA32, ImTextureID_Invalid, ImTextureStatus_Destroyed, ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImTextureData::SetStatus(), ImTextureData::SetTexID(), ImTextureData::Status, ImTextureData::TexID, ImTextureData::UpdateRect, ImTextureRect::w, ImTextureData::Width, ImTextureRect::x, and ImTextureRect::y.
Referenced by ImGui_ImplAllegro5_InvalidateDeviceObjects(), and ImGui_ImplAllegro5_RenderDrawData().