SignalProcessing: examples/imgui/backends/imgui_impl_android.cpp File Reference
imgui_impl_android.cpp File Reference
#include "imgui.h"
#include "imgui_impl_android.h"
#include <time.h>
#include <android/native_window.h>
#include <android/input.h>
#include <android/keycodes.h>
#include <android/log.h>
Functions
static ImGuiKey ImGui_ImplAndroid_KeyCodeToImGuiKey (int32_t key_code)
int32_t ImGui_ImplAndroid_HandleInputEvent (const AInputEvent *input_event)
bool ImGui_ImplAndroid_Init (ANativeWindow *window)
void ImGui_ImplAndroid_Shutdown ()
void ImGui_ImplAndroid_NewFrame ()
Variables
static double g_Time = 0.0
static ANativeWindow * g_Window
static char g_LogTag [] = "ImGuiExample"
Function Documentation
ImGui_ImplAndroid_HandleInputEvent()
int32_t ImGui_ImplAndroid_HandleInputEvent (const AInputEvent * input_event)
Definition at line 159 of file imgui_impl_android.cpp.
References ImGuiIO::AddKeyEvent(), ImGuiIO::AddMouseButtonEvent(), ImGuiIO::AddMousePosEvent(), ImGuiIO::AddMouseSourceEvent(), ImGuiIO::AddMouseWheelEvent(), ImGui::GetIO(), ImGui_ImplAndroid_KeyCodeToImGuiKey(), ImGuiKey_None, ImGuiMod_Alt, ImGuiMod_Ctrl, ImGuiMod_Shift, ImGuiMod_Super, ImGuiMouseSource_Mouse, ImGuiMouseSource_Pen, ImGuiMouseSource_TouchScreen, and ImGuiIO::SetKeyEventNativeData().
Referenced by handleInputEvent().
ImGui_ImplAndroid_Init()
bool ImGui_ImplAndroid_Init (ANativeWindow * window)
Definition at line 264 of file imgui_impl_android.cpp.
References ImGuiIO::BackendPlatformName, g_Time, g_Window, ImGui::GetIO(), and IMGUI_CHECKVERSION.
Referenced by Init().
ImGui_ImplAndroid_KeyCodeToImGuiKey()
static ImGuiKey ImGui_ImplAndroid_KeyCodeToImGuiKey (int32_t key_code) static
Definition at line 46 of file imgui_impl_android.cpp.
References ImGuiKey_0, ImGuiKey_1, ImGuiKey_2, ImGuiKey_3, ImGuiKey_4, ImGuiKey_5, ImGuiKey_6, ImGuiKey_7, ImGuiKey_8, ImGuiKey_9, ImGuiKey_A, ImGuiKey_Apostrophe, ImGuiKey_B, ImGuiKey_Backslash, ImGuiKey_Backspace, ImGuiKey_C, ImGuiKey_CapsLock, ImGuiKey_Comma, ImGuiKey_D, ImGuiKey_Delete, ImGuiKey_DownArrow, ImGuiKey_E, ImGuiKey_End, ImGuiKey_Enter, ImGuiKey_Equal, ImGuiKey_Escape, ImGuiKey_F, ImGuiKey_F1, ImGuiKey_F10, ImGuiKey_F11, ImGuiKey_F12, ImGuiKey_F2, ImGuiKey_F3, ImGuiKey_F4, ImGuiKey_F5, ImGuiKey_F6, ImGuiKey_F7, ImGuiKey_F8, ImGuiKey_F9, ImGuiKey_G, ImGuiKey_GraveAccent, ImGuiKey_H, ImGuiKey_Home, ImGuiKey_I, ImGuiKey_Insert, ImGuiKey_J, ImGuiKey_K, ImGuiKey_Keypad0, ImGuiKey_Keypad1, ImGuiKey_Keypad2, ImGuiKey_Keypad3, ImGuiKey_Keypad4, ImGuiKey_Keypad5, ImGuiKey_Keypad6, ImGuiKey_Keypad7, ImGuiKey_Keypad8, ImGuiKey_Keypad9, ImGuiKey_KeypadAdd, ImGuiKey_KeypadDecimal, ImGuiKey_KeypadDivide, ImGuiKey_KeypadEnter, ImGuiKey_KeypadEqual, ImGuiKey_KeypadMultiply, ImGuiKey_KeypadSubtract, ImGuiKey_L, ImGuiKey_LeftAlt, ImGuiKey_LeftArrow, ImGuiKey_LeftBracket, ImGuiKey_LeftCtrl, ImGuiKey_LeftShift, ImGuiKey_LeftSuper, ImGuiKey_M, ImGuiKey_Menu, ImGuiKey_Minus, ImGuiKey_N, ImGuiKey_None, ImGuiKey_NumLock, ImGuiKey_O, ImGuiKey_P, ImGuiKey_PageDown, ImGuiKey_PageUp, ImGuiKey_Pause, ImGuiKey_Period, ImGuiKey_PrintScreen, ImGuiKey_Q, ImGuiKey_R, ImGuiKey_RightAlt, ImGuiKey_RightArrow, ImGuiKey_RightBracket, ImGuiKey_RightCtrl, ImGuiKey_RightShift, ImGuiKey_RightSuper, ImGuiKey_S, ImGuiKey_ScrollLock, ImGuiKey_Semicolon, ImGuiKey_Slash, ImGuiKey_Space, ImGuiKey_T, ImGuiKey_Tab, ImGuiKey_U, ImGuiKey_UpArrow, ImGuiKey_V, ImGuiKey_W, ImGuiKey_X, ImGuiKey_Y, and ImGuiKey_Z.
Referenced by ImGui_ImplAndroid_HandleInputEvent().
ImGui_ImplAndroid_NewFrame()
void ImGui_ImplAndroid_NewFrame ()
Definition at line 284 of file imgui_impl_android.cpp.
References ImGuiIO::DeltaTime, ImGuiIO::DisplayFramebufferScale, ImGuiIO::DisplaySize, g_Time, g_Window, and ImGui::GetIO().
Referenced by MainLoopStep().
ImGui_ImplAndroid_Shutdown()
void ImGui_ImplAndroid_Shutdown ()
Definition at line 278 of file imgui_impl_android.cpp.
References ImGuiIO::BackendPlatformName, and ImGui::GetIO().
Referenced by Shutdown().
Variable Documentation
g_LogTag
char g_LogTag[] = "ImGuiExample" static
Definition at line 44 of file imgui_impl_android.cpp.
g_Time
double g_Time = 0.0 static
Definition at line 42 of file imgui_impl_android.cpp.
Referenced by ImGui_ImplAndroid_Init(), and ImGui_ImplAndroid_NewFrame().
g_Window
ANativeWindow* g_Window static
Definition at line 43 of file imgui_impl_android.cpp.
Referenced by ImGui_ImplAndroid_Init(), and ImGui_ImplAndroid_NewFrame().