SignalProcessing: examples/imgui/backends/imgui_impl_dx9.cpp File Reference
imgui_impl_dx9.cpp File Reference
#include "imgui.h"
#include "imgui_impl_dx9.h"
#include <d3d9.h>
Classes
struct ImGui_ImplDX9_Data
struct CUSTOMVERTEX
Macros
#define D3DFVF_CUSTOMVERTEX (D3DFVF_XYZ|D3DFVF_DIFFUSE|D3DFVF_TEX1)
#define IMGUI_COL_TO_DX9_ARGB(_COL) (((_COL) & 0xFF00FF00) | (((_COL) & 0xFF0000) >> 16) | (((_COL) & 0xFF) << 16))
Functions
static ImGui_ImplDX9_Data * ImGui_ImplDX9_GetBackendData ()
static void ImGui_ImplDX9_SetupRenderState (ImDrawData *draw_data)
void ImGui_ImplDX9_RenderDrawData (ImDrawData *draw_data)
static bool ImGui_ImplDX9_CheckFormatSupport (LPDIRECT3DDEVICE9 pDevice, D3DFORMAT format)
bool ImGui_ImplDX9_Init (IDirect3DDevice9 *device)
void ImGui_ImplDX9_Shutdown ()
static void ImGui_ImplDX9_CopyTextureRegion (bool tex_use_colors, const ImU32 *src, int src_pitch, ImU32 *dst, int dst_pitch, int w, int h)
void ImGui_ImplDX9_UpdateTexture (ImTextureData *tex)
bool ImGui_ImplDX9_CreateDeviceObjects ()
void ImGui_ImplDX9_InvalidateDeviceObjects ()
void ImGui_ImplDX9_NewFrame ()
Macro Definition Documentation
D3DFVF_CUSTOMVERTEX
#define D3DFVF_CUSTOMVERTEX (D3DFVF_XYZ|D3DFVF_DIFFUSE|D3DFVF_TEX1)
Definition at line 75 of file imgui_impl_dx9.cpp.
IMGUI_COL_TO_DX9_ARGB
#define IMGUI_COL_TO_DX9_ARGB (_COL) (((_COL) & 0xFF00FF00) | (((_COL) & 0xFF0000) >> 16) | (((_COL) & 0xFF) << 16))
Definition at line 80 of file imgui_impl_dx9.cpp.
Function Documentation
ImGui_ImplDX9_CheckFormatSupport()
static bool ImGui_ImplDX9_CheckFormatSupport (LPDIRECT3DDEVICE9 pDevice, D3DFORMAT format) static
Definition at line 309 of file imgui_impl_dx9.cpp.
Referenced by ImGui_ImplDX9_Init().
ImGui_ImplDX9_CopyTextureRegion()
static void ImGui_ImplDX9_CopyTextureRegion (bool tex_use_colors, const ImU32 * src, int src_pitch, ImU32 * dst, int dst_pitch, int w, int h) static
Definition at line 368 of file imgui_impl_dx9.cpp.
References ImGui_ImplDX9_Data::HasRgbaSupport, IM_UNUSED, IMGUI_COL_TO_DX9_ARGB, and ImGui_ImplDX9_GetBackendData().
Referenced by ImGui_ImplDX9_UpdateTexture().
ImGui_ImplDX9_CreateDeviceObjects()
bool ImGui_ImplDX9_CreateDeviceObjects ()
Definition at line 446 of file imgui_impl_dx9.cpp.
References ImGui_ImplDX9_GetBackendData(), and ImGui_ImplDX9_Data::pd3dDevice.
Referenced by ResetDevice().
ImGui_ImplDX9_GetBackendData()
static ImGui_ImplDX9_Data * ImGui_ImplDX9_GetBackendData () static
Definition at line 85 of file imgui_impl_dx9.cpp.
References ImGuiIO::BackendRendererUserData, ImGui::GetCurrentContext(), and ImGui::GetIO().
Referenced by ImGui_ImplDX9_CopyTextureRegion(), ImGui_ImplDX9_CreateDeviceObjects(), ImGui_ImplDX9_InvalidateDeviceObjects(), ImGui_ImplDX9_NewFrame(), ImGui_ImplDX9_RenderDrawData(), ImGui_ImplDX9_SetupRenderState(), ImGui_ImplDX9_Shutdown(), and ImGui_ImplDX9_UpdateTexture().
ImGui_ImplDX9_Init()
bool ImGui_ImplDX9_Init (IDirect3DDevice9 * device)
Definition at line 327 of file imgui_impl_dx9.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGui::GetIO(), ImGui::GetPlatformIO(), ImGui_ImplDX9_Data::HasRgbaSupport, IM_ASSERT, IM_NEW, IMGUI_CHECKVERSION, ImGui_ImplDX9_CheckFormatSupport(), ImGuiBackendFlags_RendererHasTextures, ImGuiBackendFlags_RendererHasVtxOffset, ImGui_ImplDX9_Data::pd3dDevice, ImGuiPlatformIO::Renderer_TextureMaxHeight, and ImGuiPlatformIO::Renderer_TextureMaxWidth.
Referenced by main().
ImGui_ImplDX9_InvalidateDeviceObjects()
void ImGui_ImplDX9_InvalidateDeviceObjects ()
Definition at line 454 of file imgui_impl_dx9.cpp.
References ImGui::GetPlatformIO(), ImGui_ImplDX9_GetBackendData(), ImGui_ImplDX9_UpdateTexture(), ImTextureStatus_WantDestroy, ImGui_ImplDX9_Data::pd3dDevice, ImGui_ImplDX9_Data::pIB, ImGui_ImplDX9_Data::pVB, and ImGuiPlatformIO::Textures.
Referenced by ImGui_ImplDX9_Shutdown(), and ResetDevice().
ImGui_ImplDX9_NewFrame()
void ImGui_ImplDX9_NewFrame ()
Definition at line 471 of file imgui_impl_dx9.cpp.
References IM_ASSERT, IM_UNUSED, and ImGui_ImplDX9_GetBackendData().
Referenced by main().
ImGui_ImplDX9_RenderDrawData()
void ImGui_ImplDX9_RenderDrawData (ImDrawData * draw_data)
Definition at line 165 of file imgui_impl_dx9.cpp.
References ImDrawCmd::ClipRect, ImDrawList::CmdBuffer, ImDrawData::CmdLists, CUSTOMVERTEX::col, ImDrawVert::col, D3DFVF_CUSTOMVERTEX, ImVector< T >::Data, ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImDrawCmd::ElemCount, ImDrawCmd::GetTexID(), ImDrawList::IdxBuffer, ImDrawCmd::IdxOffset, ImDrawCallback_ResetRenderState, ImDrawIdx, IMGUI_COL_TO_DX9_ARGB, ImGui_ImplDX9_GetBackendData(), ImGui_ImplDX9_SetupRenderState(), ImGui_ImplDX9_UpdateTexture(), ImTextureStatus_OK, ImGui_ImplDX9_Data::IndexBufferSize, ImGui_ImplDX9_Data::pd3dDevice, ImGui_ImplDX9_Data::pIB, CUSTOMVERTEX::pos, ImDrawVert::pos, ImGui_ImplDX9_Data::pVB, ImVector< T >::Size, ImDrawData::Textures, ImDrawData::TotalIdxCount, ImDrawData::TotalVtxCount, ImDrawCmd::UserCallback, CUSTOMVERTEX::uv, ImDrawVert::uv, ImGui_ImplDX9_Data::VertexBufferSize, ImDrawList::VtxBuffer, ImDrawCmd::VtxOffset, ImVec4::w, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by main().
ImGui_ImplDX9_SetupRenderState()
static void ImGui_ImplDX9_SetupRenderState (ImDrawData * draw_data) static
Definition at line 91 of file imgui_impl_dx9.cpp.
References ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImGui_ImplDX9_GetBackendData(), ImGui_ImplDX9_Data::pd3dDevice, ImVec2::x, and ImVec2::y.
Referenced by ImGui_ImplDX9_RenderDrawData().
ImGui_ImplDX9_Shutdown()
void ImGui_ImplDX9_Shutdown ()
Definition at line 350 of file imgui_impl_dx9.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGuiPlatformIO::ClearRendererHandlers(), ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplDX9_GetBackendData(), ImGui_ImplDX9_InvalidateDeviceObjects(), ImGuiBackendFlags_RendererHasTextures, ImGuiBackendFlags_RendererHasVtxOffset, and ImGui_ImplDX9_Data::pd3dDevice.
Referenced by main().
ImGui_ImplDX9_UpdateTexture()
void ImGui_ImplDX9_UpdateTexture (ImTextureData * tex)
Definition at line 389 of file imgui_impl_dx9.cpp.
References ImTextureData::BackendUserData, ImTextureData::Format, ImTextureData::GetPixels(), ImTextureData::GetPixelsAt(), ImTextureRect::h, ImGui_ImplDX9_Data::HasRgbaSupport, ImTextureData::Height, IM_ASSERT, ImGui_ImplDX9_CopyTextureRegion(), ImGui_ImplDX9_GetBackendData(), ImTextureFormat_RGBA32, ImTextureID_Invalid, ImTextureStatus_Destroyed, ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImGui_ImplDX9_Data::pd3dDevice, ImTextureData::SetStatus(), ImTextureData::SetTexID(), ImTextureData::Status, ImTextureData::TexID, ImTextureData::UpdateRect, ImTextureData::Updates, ImTextureData::UseColors, ImTextureRect::w, ImTextureData::Width, ImTextureRect::x, and ImTextureRect::y.
Referenced by ImGui_ImplDX9_InvalidateDeviceObjects(), and ImGui_ImplDX9_RenderDrawData().