SignalProcessing: examples/imgui/misc/freetype/imgui_freetype.cpp File Reference
imgui_freetype.cpp File Reference
#include "imgui.h"
#include "imgui_freetype.h"
#include "imgui_internal.h"
#include <stdint.h>
#include <ft2build.h>
#include <FT_FREETYPE_H>
#include <FT_MODULE_H>
#include <FT_GLYPH_H>
#include <FT_SIZES_H>
#include <FT_SYNTHESIS_H>
Classes
struct ImGui_ImplFreeType_Data
struct ImGui_ImplFreeType_FontSrcData
struct ImGui_ImplFreeType_FontSrcBakedData
Macros
#define FT_CEIL(X) (((X + 63) & -64) / 64)
#define FT_SCALEFACTOR 64.0f
#define DE_MULTIPLY(color, alpha) ImMin((ImU32)(255.0f * (float)color / (float)(alpha + FLT_MIN) + 0.5f), 255u)
Functions
static void * ImGuiFreeTypeDefaultAllocFunc (size_t size, void *user_data)
static void ImGuiFreeTypeDefaultFreeFunc (void *ptr, void *user_data)
static const FT_Glyph_Metrics * ImGui_ImplFreeType_LoadGlyph (ImGui_ImplFreeType_FontSrcData *src_data, uint32_t codepoint)
static void ImGui_ImplFreeType_BlitGlyph (const FT_Bitmap *ft_bitmap, uint32_t *dst, uint32_t dst_pitch)
static void * FreeType_Alloc (FT_Memory, long size)
static void FreeType_Free (FT_Memory, void *block)
static void * FreeType_Realloc (FT_Memory, long cur_size, long new_size, void *block)
static bool ImGui_ImplFreeType_LoaderInit (ImFontAtlas *atlas)
static void ImGui_ImplFreeType_LoaderShutdown (ImFontAtlas *atlas)
static bool ImGui_ImplFreeType_FontSrcInit (ImFontAtlas *atlas, ImFontConfig *src)
static void ImGui_ImplFreeType_FontSrcDestroy (ImFontAtlas *atlas, ImFontConfig *src)
static bool ImGui_ImplFreeType_FontBakedInit (ImFontAtlas *atlas, ImFontConfig *src, ImFontBaked *baked, void *loader_data_for_baked_src)
static void ImGui_ImplFreeType_FontBakedDestroy (ImFontAtlas *atlas, ImFontConfig *src, ImFontBaked *baked, void *loader_data_for_baked_src)
static bool ImGui_ImplFreeType_FontBakedLoadGlyph (ImFontAtlas *atlas, ImFontConfig *src, ImFontBaked *baked, void *loader_data_for_baked_src, ImWchar codepoint, ImFontGlyph *out_glyph, float *out_advance_x)
static bool ImGui_ImplFreetype_FontSrcContainsGlyph (ImFontAtlas *atlas, ImFontConfig *src, ImWchar codepoint)
Variables
static void *(* GImGuiFreeTypeAllocFunc)(size_t size, void *user_data) = ImGuiFreeTypeDefaultAllocFunc
static void(* GImGuiFreeTypeFreeFunc)(void *ptr, void *user_data) = ImGuiFreeTypeDefaultFreeFunc
static void * GImGuiFreeTypeAllocatorUserData = nullptr
Macro Definition Documentation
DE_MULTIPLY
#define DE_MULTIPLY (color, alpha) ImMin((ImU32)(255.0f * (float)color / (float)(alpha + FLT_MIN) + 0.5f), 255u)
FT_CEIL
#define FT_CEIL (X) (((X + 63) & -64) / 64)
Definition at line 110 of file imgui_freetype.cpp.
FT_SCALEFACTOR
#define FT_SCALEFACTOR 64.0f
Definition at line 111 of file imgui_freetype.cpp.
Function Documentation
FreeType_Alloc()
static void * FreeType_Alloc (FT_Memory , long size) static
Definition at line 314 of file imgui_freetype.cpp.
References GImGuiFreeTypeAllocatorUserData, and GImGuiFreeTypeAllocFunc.
Referenced by ImGui_ImplFreeType_LoaderInit().
FreeType_Free()
static void FreeType_Free (FT_Memory , void * block) static
Definition at line 319 of file imgui_freetype.cpp.
References GImGuiFreeTypeAllocatorUserData, and GImGuiFreeTypeFreeFunc.
Referenced by ImGui_ImplFreeType_LoaderInit().
FreeType_Realloc()
static void * FreeType_Realloc (FT_Memory , long cur_size, long new_size, void * block) static
Definition at line 324 of file imgui_freetype.cpp.
References GImGuiFreeTypeAllocatorUserData, GImGuiFreeTypeAllocFunc, and GImGuiFreeTypeFreeFunc.
Referenced by ImGui_ImplFreeType_LoaderInit().
ImGui_ImplFreeType_BlitGlyph()
static void ImGui_ImplFreeType_BlitGlyph (const FT_Bitmap * ft_bitmap, uint32_t * dst, uint32_t dst_pitch) static
Definition at line 263 of file imgui_freetype.cpp.
References DE_MULTIPLY, IM_ASSERT, and IM_COL32.
Referenced by ImGui_ImplFreeType_FontBakedLoadGlyph().
ImGui_ImplFreeType_FontBakedDestroy()
static void ImGui_ImplFreeType_FontBakedDestroy (ImFontAtlas * atlas, ImFontConfig * src, ImFontBaked * baked, void * loader_data_for_baked_src) static
Definition at line 467 of file imgui_freetype.cpp.
References ImGui_ImplFreeType_FontSrcBakedData::FtSize, IM_ASSERT, and IM_UNUSED.
Referenced by ImGuiFreeType::GetFontLoader().
ImGui_ImplFreeType_FontBakedInit()
static bool ImGui_ImplFreeType_FontBakedInit (ImFontAtlas * atlas, ImFontConfig * src, ImFontBaked * baked, void * loader_data_for_baked_src) static
Definition at line 421 of file imgui_freetype.cpp.
References ImFontBaked::Ascent, ImGui_ImplFreeType_FontSrcData::BakedLastActivated, ImFontBaked::Descent, ImFontConfig::FontLoaderData, FT_CEIL, ImGui_ImplFreeType_FontSrcData::FtFace, ImGui_ImplFreeType_FontSrcBakedData::FtSize, IM_ASSERT, IM_PLACEMENT_NEW, IM_UNUSED, ImGuiFreeTypeLoaderFlags_Bitmap, ImFontConfig::MergeMode, ImFontBaked::OwnerFont, ImFontConfig::RasterizerDensity, ImFontBaked::RasterizerDensity, ImFontBaked::Size, ImFontConfig::SizePixels, ImFont::Sources, and ImGui_ImplFreeType_FontSrcData::UserFlags.
Referenced by ImGuiFreeType::GetFontLoader().
ImGui_ImplFreeType_FontBakedLoadGlyph()
static bool ImGui_ImplFreeType_FontBakedLoadGlyph (ImFontAtlas * atlas, ImFontConfig * src, ImFontBaked * baked, void * loader_data_for_baked_src, ImWchar codepoint, ImFontGlyph * out_glyph, float * out_advance_x) static
Definition at line 478 of file imgui_freetype.cpp.
References ImFontGlyph::AdvanceX, ImFontBaked::Ascent, ImGui_ImplFreeType_FontSrcData::BakedLastActivated, ImFontAtlas::Builder, ImFontGlyph::Codepoint, ImFontGlyph::Colored, ImVector< T >::Data, ImFontConfig::FontLoaderData, FT_SCALEFACTOR, ImGui_ImplFreeType_FontSrcData::FtFace, ImGui_ImplFreeType_FontSrcBakedData::FtSize, ImFontConfig::GlyphOffset, IM_ASSERT, IM_ROUND, ImFontAtlasBakedSetFontGlyphBitmap(), ImFontAtlasPackAddRect(), ImFontAtlasPackGetRect(), ImFontAtlasRectId_Invalid, ImGui_ImplFreeType_BlitGlyph(), ImGui_ImplFreeType_LoadGlyph(), ImGuiFreeTypeLoaderFlags_Monochrome, ImTextureFormat_RGBA32, ImFontBaked::OwnerFont, ImFontGlyph::PackId, ImFontConfig::PixelSnapH, ImFontConfig::PixelSnapV, ImFontConfig::RasterizerDensity, ImFontBaked::RasterizerDensity, ImVector< T >::resize(), ImFontBaked::Size, ImFont::Sources, ImFontAtlasBuilder::TempBuffer, ImGui_ImplFreeType_FontSrcData::UserFlags, ImFontGlyph::Visible, ImVec2::x, ImFontGlyph::X0, ImFontGlyph::X1, ImVec2::y, ImFontGlyph::Y0, and ImFontGlyph::Y1.
Referenced by ImGuiFreeType::GetFontLoader().
ImGui_ImplFreetype_FontSrcContainsGlyph()
static bool ImGui_ImplFreetype_FontSrcContainsGlyph (ImFontAtlas * atlas, ImFontConfig * src, ImWchar codepoint) static
Definition at line 569 of file imgui_freetype.cpp.
References ImFontConfig::FontLoaderData, ImGui_ImplFreeType_FontSrcData::FtFace, and IM_UNUSED.
Referenced by ImGuiFreeType::GetFontLoader().
ImGui_ImplFreeType_FontSrcDestroy()
static void ImGui_ImplFreeType_FontSrcDestroy (ImFontAtlas * atlas, ImFontConfig * src) static
Definition at line 413 of file imgui_freetype.cpp.
References ImFontConfig::FontLoaderData, IM_DELETE(), and IM_UNUSED.
Referenced by ImGuiFreeType::GetFontLoader().
ImGui_ImplFreeType_FontSrcInit()
static bool ImGui_ImplFreeType_FontSrcInit (ImFontAtlas * atlas, ImFontConfig * src) static
Definition at line 396 of file imgui_freetype.cpp.
References ImFontConfig::FontLoaderData, ImFontAtlas::FontLoaderData, ImFontAtlas::FontLoaderFlags, IM_ASSERT, IM_DELETE(), IM_NEW, ImGui_ImplFreeType_FontSrcData::InitFont(), and ImGui_ImplFreeType_Data::Library.
Referenced by ImGuiFreeType::GetFontLoader().
ImGui_ImplFreeType_LoaderInit()
static bool ImGui_ImplFreeType_LoaderInit (ImFontAtlas * atlas) static
Definition at line 347 of file imgui_freetype.cpp.
References ImFontAtlas::FontLoaderData, FreeType_Alloc(), FreeType_Free(), FreeType_Realloc(), IM_ASSERT, IM_DELETE(), IM_NEW, ImGui_ImplFreeType_Data::Library, and ImGui_ImplFreeType_Data::MemoryManager.
Referenced by ImGuiFreeType::GetFontLoader().
ImGui_ImplFreeType_LoaderShutdown()
static void ImGui_ImplFreeType_LoaderShutdown (ImFontAtlas * atlas) static
Definition at line 387 of file imgui_freetype.cpp.
References ImFontAtlas::FontLoaderData, IM_ASSERT, IM_DELETE(), and ImGui_ImplFreeType_Data::Library.
Referenced by ImGuiFreeType::GetFontLoader().
ImGui_ImplFreeType_LoadGlyph()
static const FT_Glyph_Metrics * ImGui_ImplFreeType_LoadGlyph (ImGui_ImplFreeType_FontSrcData * src_data, uint32_t codepoint) static
Definition at line 222 of file imgui_freetype.cpp.
References ImGui_ImplFreeType_FontSrcData::FtFace, IM_ASSERT, ImGuiFreeTypeLoaderFlags_Bold, ImGuiFreeTypeLoaderFlags_Oblique, ImGui_ImplFreeType_FontSrcData::LoadFlags, and ImGui_ImplFreeType_FontSrcData::UserFlags.
Referenced by ImGui_ImplFreeType_FontBakedLoadGlyph().
ImGuiFreeTypeDefaultAllocFunc()
static void * ImGuiFreeTypeDefaultAllocFunc (size_t size, void * user_data) static
Definition at line 90 of file imgui_freetype.cpp.
References IM_ALLOC, and IM_UNUSED.
ImGuiFreeTypeDefaultFreeFunc()
static void ImGuiFreeTypeDefaultFreeFunc (void * ptr, void * user_data) static
Definition at line 91 of file imgui_freetype.cpp.
References IM_FREE, and IM_UNUSED.
Variable Documentation
GImGuiFreeTypeAllocatorUserData
void* GImGuiFreeTypeAllocatorUserData = nullptr static
Definition at line 96 of file imgui_freetype.cpp.
Referenced by FreeType_Alloc(), FreeType_Free(), FreeType_Realloc(), and ImGuiFreeType::SetAllocatorFunctions().
GImGuiFreeTypeAllocFunc
void *(* GImGuiFreeTypeAllocFunc) (size_t size, void *user_data) (size_t size, void * user_data) = ImGuiFreeTypeDefaultAllocFunc static
Definition at line 94 of file imgui_freetype.cpp.
Referenced by FreeType_Alloc(), FreeType_Realloc(), and ImGuiFreeType::SetAllocatorFunctions().
GImGuiFreeTypeFreeFunc
void(* GImGuiFreeTypeFreeFunc) (void *ptr, void *user_data) (void * ptr, void * user_data) = ImGuiFreeTypeDefaultFreeFunc static
Definition at line 95 of file imgui_freetype.cpp.
Referenced by FreeType_Free(), FreeType_Realloc(), and ImGuiFreeType::SetAllocatorFunctions().