SignalProcessing: examples/imgui/backends/imgui_impl_opengl2.cpp File Reference
imgui_impl_opengl2.cpp File Reference
#include "imgui.h"
#include "imgui_impl_opengl2.h"
#include <stdint.h>
#include <GL/gl.h>
Classes
struct ImGui_ImplOpenGL2_Data
Macros
#define GL_CALL(_CALL) _CALL
Functions
static ImGui_ImplOpenGL2_Data * ImGui_ImplOpenGL2_GetBackendData ()
bool ImGui_ImplOpenGL2_Init ()
void ImGui_ImplOpenGL2_Shutdown ()
void ImGui_ImplOpenGL2_NewFrame ()
static void ImGui_ImplOpenGL2_SetupRenderState (ImDrawData *draw_data, int fb_width, int fb_height)
void ImGui_ImplOpenGL2_RenderDrawData (ImDrawData *draw_data)
void ImGui_ImplOpenGL2_UpdateTexture (ImTextureData *tex)
bool ImGui_ImplOpenGL2_CreateDeviceObjects ()
void ImGui_ImplOpenGL2_DestroyDeviceObjects ()
Macro Definition Documentation
GL_CALL
#define GL_CALL (_CALL) _CALL
Definition at line 82 of file imgui_impl_opengl2.cpp.
Function Documentation
ImGui_ImplOpenGL2_CreateDeviceObjects()
bool ImGui_ImplOpenGL2_CreateDeviceObjects ()
Definition at line 331 of file imgui_impl_opengl2.cpp.
ImGui_ImplOpenGL2_DestroyDeviceObjects()
void ImGui_ImplOpenGL2_DestroyDeviceObjects ()
Definition at line 336 of file imgui_impl_opengl2.cpp.
References ImGui::GetPlatformIO(), ImGui_ImplOpenGL2_UpdateTexture(), ImTextureStatus_WantDestroy, and ImGuiPlatformIO::Textures.
Referenced by ImGui_ImplOpenGL2_Shutdown().
ImGui_ImplOpenGL2_GetBackendData()
static ImGui_ImplOpenGL2_Data * ImGui_ImplOpenGL2_GetBackendData () static
Definition at line 93 of file imgui_impl_opengl2.cpp.
References ImGuiIO::BackendRendererUserData, ImGui::GetCurrentContext(), and ImGui::GetIO().
Referenced by ImGui_ImplOpenGL2_NewFrame(), and ImGui_ImplOpenGL2_Shutdown().
ImGui_ImplOpenGL2_Init()
bool ImGui_ImplOpenGL2_Init ()
Definition at line 99 of file imgui_impl_opengl2.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGui::GetIO(), IM_ASSERT, IM_NEW, IMGUI_CHECKVERSION, and ImGuiBackendFlags_RendererHasTextures.
Referenced by main(), and main().
ImGui_ImplOpenGL2_NewFrame()
void ImGui_ImplOpenGL2_NewFrame ()
Definition at line 130 of file imgui_impl_opengl2.cpp.
References IM_ASSERT, IM_UNUSED, and ImGui_ImplOpenGL2_GetBackendData().
Referenced by main(), and MainLoopStep().
ImGui_ImplOpenGL2_RenderDrawData()
void ImGui_ImplOpenGL2_RenderDrawData (ImDrawData * draw_data)
Definition at line 184 of file imgui_impl_opengl2.cpp.
References ImDrawCmd::ClipRect, ImDrawList::CmdBuffer, ImDrawData::CmdLists, ImVector< T >::Data, ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImDrawCmd::ElemCount, ImDrawData::FramebufferScale, ImDrawCmd::GetTexID(), GL_BACK, GL_COLOR_BUFFER_BIT, GL_FLOAT, GL_FRONT, GL_POLYGON_MODE, GL_SCISSOR_BOX, GL_TEXTURE_2D, GL_TEXTURE_BINDING_2D, GL_TRIANGLES, GL_UNSIGNED_BYTE, GL_UNSIGNED_INT, GL_UNSIGNED_SHORT, GL_VIEWPORT, glBindTexture, glDrawElements, glGetIntegerv, glPolygonMode, glScissor, glViewport, ImDrawList::IdxBuffer, ImDrawCmd::IdxOffset, ImDrawCallback_ResetRenderState, ImGui_ImplOpenGL2_SetupRenderState(), ImGui_ImplOpenGL2_UpdateTexture(), ImTextureStatus_OK, ImVector< T >::Size, ImDrawData::Textures, ImDrawCmd::UserCallback, ImDrawList::VtxBuffer, ImVec4::w, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by main(), and MainLoopStep().
ImGui_ImplOpenGL2_SetupRenderState()
static void ImGui_ImplOpenGL2_SetupRenderState (ImDrawData * draw_data, int fb_width, int fb_height) static
Definition at line 137 of file imgui_impl_opengl2.cpp.
References ImDrawData::DisplayPos, ImDrawData::DisplaySize, GL_BLEND, GL_CALL, GL_CULL_FACE, GL_DEPTH_TEST, GL_FILL, GL_FRONT_AND_BACK, GL_ONE_MINUS_SRC_ALPHA, GL_SCISSOR_TEST, GL_SRC_ALPHA, GL_STENCIL_TEST, GL_TEXTURE_2D, glDisable, glEnable, glPolygonMode, glViewport, ImVec2::x, and ImVec2::y.
Referenced by ImGui_ImplOpenGL2_RenderDrawData().
ImGui_ImplOpenGL2_Shutdown()
void ImGui_ImplOpenGL2_Shutdown ()
Definition at line 114 of file imgui_impl_opengl2.cpp.
References ImGuiIO::BackendFlags, ImGuiIO::BackendRendererName, ImGuiIO::BackendRendererUserData, ImGuiPlatformIO::ClearRendererHandlers(), ImGui::GetIO(), ImGui::GetPlatformIO(), IM_ASSERT, IM_DELETE(), ImGui_ImplOpenGL2_DestroyDeviceObjects(), ImGui_ImplOpenGL2_GetBackendData(), and ImGuiBackendFlags_RendererHasTextures.
Referenced by main(), and main().
ImGui_ImplOpenGL2_UpdateTexture()
void ImGui_ImplOpenGL2_UpdateTexture (ImTextureData * tex)
Definition at line 271 of file imgui_impl_opengl2.cpp.
References ImTextureData::BackendUserData, ImTextureData::Format, ImTextureData::GetPixels(), ImTextureData::GetPixelsAt(), GL_CALL, GL_LINEAR, GL_RGBA, GL_TEXTURE_2D, GL_TEXTURE_BINDING_2D, GL_TEXTURE_MAG_FILTER, GL_TEXTURE_MIN_FILTER, GL_TEXTURE_WRAP_S, GL_TEXTURE_WRAP_T, GL_UNPACK_ALIGNMENT, GL_UNPACK_ROW_LENGTH, GL_UNSIGNED_BYTE, glBindTexture, glDeleteTextures, glGenTextures, glGetIntegerv, glPixelStorei, glTexImage2D, glTexParameteri, glTexSubImage2D, ImTextureData::Height, IM_ASSERT, ImTextureFormat_RGBA32, ImTextureID_Invalid, ImTextureStatus_Destroyed, ImTextureStatus_OK, ImTextureStatus_WantCreate, ImTextureStatus_WantDestroy, ImTextureStatus_WantUpdates, ImTextureData::SetStatus(), ImTextureData::SetTexID(), ImTextureData::Status, ImTextureData::TexID, ImTextureData::Updates, and ImTextureData::Width.
Referenced by ImGui_ImplOpenGL2_DestroyDeviceObjects(), and ImGui_ImplOpenGL2_RenderDrawData().