SignalProcessing: examples/imgui/backends/imgui_impl_null.h File Reference
imgui_impl_null.h File Reference
#include "imgui.h"
Functions
IMGUI_IMPL_API bool ImGui_ImplNull_Init ()
IMGUI_IMPL_API void ImGui_ImplNull_Shutdown ()
IMGUI_IMPL_API void ImGui_ImplNull_NewFrame ()
IMGUI_IMPL_API bool ImGui_ImplNullPlatform_Init ()
IMGUI_IMPL_API void ImGui_ImplNullPlatform_Shutdown ()
IMGUI_IMPL_API void ImGui_ImplNullPlatform_NewFrame ()
IMGUI_IMPL_API bool ImGui_ImplNullRender_Init ()
IMGUI_IMPL_API void ImGui_ImplNullRender_Shutdown ()
IMGUI_IMPL_API void ImGui_ImplNullRender_NewFrame ()
IMGUI_IMPL_API void ImGui_ImplNullRender_RenderDrawData (ImDrawData *draw_data)
Function Documentation
ImGui_ImplNull_Init()
IMGUI_IMPL_API bool ImGui_ImplNull_Init ()
Definition at line 25 of file imgui_impl_null.cpp.
References ImGui_ImplNullPlatform_Init(), and ImGui_ImplNullRender_Init().
ImGui_ImplNull_NewFrame()
IMGUI_IMPL_API void ImGui_ImplNull_NewFrame ()
Definition at line 38 of file imgui_impl_null.cpp.
References ImGui_ImplNullPlatform_NewFrame(), and ImGui_ImplNullRender_NewFrame().
ImGui_ImplNull_Shutdown()
IMGUI_IMPL_API void ImGui_ImplNull_Shutdown ()
Definition at line 32 of file imgui_impl_null.cpp.
References ImGui_ImplNullPlatform_Shutdown(), and ImGui_ImplNullRender_Shutdown().
ImGui_ImplNullPlatform_Init()
IMGUI_IMPL_API bool ImGui_ImplNullPlatform_Init ()
Definition at line 44 of file imgui_impl_null.cpp.
References ImGuiIO::BackendFlags, ImGui::GetIO(), and ImGuiBackendFlags_HasMouseCursors.
Referenced by ImGui_ImplNull_Init(), and main().
ImGui_ImplNullPlatform_NewFrame()
IMGUI_IMPL_API void ImGui_ImplNullPlatform_NewFrame ()
Definition at line 57 of file imgui_impl_null.cpp.
References ImGuiIO::DeltaTime, ImGuiIO::DisplaySize, and ImGui::GetIO().
Referenced by ImGui_ImplNull_NewFrame(), and main().
ImGui_ImplNullPlatform_Shutdown()
IMGUI_IMPL_API void ImGui_ImplNullPlatform_Shutdown ()
Definition at line 51 of file imgui_impl_null.cpp.
References ImGuiIO::BackendFlags, and ImGui::GetIO().
Referenced by ImGui_ImplNull_Shutdown(), and main().
ImGui_ImplNullRender_Init()
IMGUI_IMPL_API bool ImGui_ImplNullRender_Init ()
Definition at line 64 of file imgui_impl_null.cpp.
References ImGuiIO::BackendFlags, ImGui::GetIO(), ImGuiBackendFlags_RendererHasTextures, and ImGuiBackendFlags_RendererHasVtxOffset.
Referenced by ImGui_ImplNull_Init(), and main().
ImGui_ImplNullRender_NewFrame()
IMGUI_IMPL_API void ImGui_ImplNullRender_NewFrame ()
Definition at line 79 of file imgui_impl_null.cpp.
Referenced by ImGui_ImplNull_NewFrame(), and main().
ImGui_ImplNullRender_RenderDrawData()
IMGUI_IMPL_API void ImGui_ImplNullRender_RenderDrawData (ImDrawData * draw_data)
Definition at line 94 of file imgui_impl_null.cpp.
References ImGui_ImplNullRender_UpdateTexture(), ImTextureStatus_OK, and ImDrawData::Textures.
ImGui_ImplNullRender_Shutdown()
IMGUI_IMPL_API void ImGui_ImplNullRender_Shutdown ()
Definition at line 72 of file imgui_impl_null.cpp.
References ImGuiIO::BackendFlags, and ImGui::GetIO().
Referenced by ImGui_ImplNull_Shutdown(), and main().