SignalProcessing: examples/implot/example/main.cpp File Reference
main.cpp File Reference
#include "imgui.h"
#include "imgui_impl_glfw.h"
#include "imgui_impl_opengl3.h"
#include "implot.h"
#include <GLFW/glfw3.h>
#include <iostream>
Functions
void glfw_error_callback (int error, const char *description)
int main ()
Function Documentation
glfw_error_callback()
void glfw_error_callback (int error, const char * description)
Definition at line 32 of file main.cpp.
main()
int main ()
Definition at line 34 of file main.cpp.
References ImPlot::CreateContext(), ImGui::CreateContext(), ImGui::DestroyContext(), ImPlot::DestroyContext(), ImGui::GetDrawData(), GL_COLOR_BUFFER_BIT, GL_TRUE, glClear, glClearColor, GLFW_CONTEXT_VERSION_MAJOR, GLFW_CONTEXT_VERSION_MINOR, glfw_error_callback(), GLFW_OPENGL_CORE_PROFILE, GLFW_OPENGL_FORWARD_COMPAT, GLFW_OPENGL_PROFILE, glfwCreateWindow(), glfwDestroyWindow(), glfwGetFramebufferSize(), glfwInit(), glfwMakeContextCurrent(), glfwPollEvents(), glfwSetErrorCallback(), glfwSwapBuffers(), glfwSwapInterval(), glfwTerminate(), glfwWindowHint(), glfwWindowShouldClose(), glViewport, IMGUI_CHECKVERSION, ImGui_ImplGlfw_InitForOpenGL(), ImGui_ImplGlfw_NewFrame(), ImGui_ImplGlfw_Shutdown(), ImGui_ImplOpenGL3_Init(), ImGui_ImplOpenGL3_NewFrame(), ImGui_ImplOpenGL3_RenderDrawData(), ImGui_ImplOpenGL3_Shutdown(), ImGui::NewFrame(), ImGui::Render(), ImGui::ShowDemoWindow(), ImPlot::ShowDemoWindow(), and ImGui::StyleColorsDark().