SignalProcessing: examples/implot/implot_internal.h File Reference
implot_internal.h File Reference
#include <time.h>
#include "imgui_internal.h"
Classes
struct ImPlotDateTimeSpec
struct ImPlotTime
struct ImPlotColormapData
struct ImPlotPointError
struct ImPlotAnnotation
struct ImPlotAnnotationCollection
struct ImPlotTag
struct ImPlotTagCollection
struct ImPlotTick
struct ImPlotTicker
struct ImPlotAxis
struct ImPlotAlignmentData
struct ImPlotItem
struct ImPlotLegend
struct ImPlotItemGroup
struct ImPlotPlot
struct ImPlotSubplot
struct ImPlotNextPlotData
struct ImPlotNextItemData
struct ImPlotContext
struct ImPlot::Formatter_Time_Data
Namespaces
namespace ImPlot
Macros
#define GetBufSize GetSize
#define IMPLOT_MIN_TIME 0
#define IMPLOT_MAX_TIME 32503680000
#define IMPLOT_LABEL_FORMAT "%g"
#define IMPLOT_LABEL_MAX_SIZE 32
#define IMPLOT_NUM_X_AXES ImAxis_Y1
#define IMPLOT_NUM_Y_AXES (ImAxis_COUNT - IMPLOT_NUM_X_AXES)
#define IM_COL32_SPLIT_RGB(col, r, g, b)
Typedefs
typedef int ImPlotTimeUnit
typedef int ImPlotDateFmt
typedef int ImPlotTimeFmt
typedef void(* ImPlotLocator) (ImPlotTicker &ticker, const ImPlotRange &range, float pixels, bool vertical, ImPlotFormatter formatter, void *formatter_data)
Enumerations
enum ImPlotTimeUnit_ {
ImPlotTimeUnit_Us , ImPlotTimeUnit_Ms , ImPlotTimeUnit_S , ImPlotTimeUnit_Min ,
ImPlotTimeUnit_Hr , ImPlotTimeUnit_Day , ImPlotTimeUnit_Mo , ImPlotTimeUnit_Yr ,
ImPlotTimeUnit_COUNT
}
enum ImPlotDateFmt_ {
ImPlotDateFmt_None = 0 , ImPlotDateFmt_DayMo , ImPlotDateFmt_DayMoYr , ImPlotDateFmt_MoYr ,
ImPlotDateFmt_Mo , ImPlotDateFmt_Yr
}
enum ImPlotTimeFmt_ {
ImPlotTimeFmt_None = 0 , ImPlotTimeFmt_Us , ImPlotTimeFmt_SUs , ImPlotTimeFmt_SMs ,
ImPlotTimeFmt_S , ImPlotTimeFmt_MinSMs , ImPlotTimeFmt_HrMinSMs , ImPlotTimeFmt_HrMinS ,
ImPlotTimeFmt_HrMin , ImPlotTimeFmt_Hr
}
Functions
static float ImLog10 (float x)
static double ImLog10 (double x)
static float ImSinh (float x)
static double ImSinh (double x)
static float ImAsinh (float x)
static double ImAsinh (double x)
template<typename TSet , typename TFlag >
static bool ImHasFlag (TSet set, TFlag flag)
template<typename TSet , typename TFlag >
static void ImFlipFlag (TSet &set, TFlag flag)
template<typename T >
static T ImRemap (T x, T x0, T x1, T y0, T y1)
template<typename T >
static T ImRemap01 (T x, T x0, T x1)
static int ImPosMod (int l, int r)
static bool ImNan (double val)
static bool ImNanOrInf (double val)
static double ImConstrainNan (double val)
static double ImConstrainInf (double val)
static double ImConstrainLog (double val)
static double ImConstrainTime (double val)
static bool ImAlmostEqual (double v1, double v2, int ulp=2)
template<typename T >
static T ImMinArray (const T *values, int count)
template<typename T >
static T ImMaxArray (const T *values, int count)
template<typename T >
static void ImMinMaxArray (const T *values, int count, T *min_out, T *max_out)
template<typename T >
static T ImSum (const T *values, int count)
template<typename T >
static double ImMean (const T *values, int count)
template<typename T >
static double ImStdDev (const T *values, int count)
static ImU32 ImMixU32 (ImU32 a, ImU32 b, ImU32 s)
static ImU32 ImLerpU32 (const ImU32 *colors, int size, float t)
static ImU32 ImAlphaU32 (ImU32 col, float alpha)
template<typename T >
static bool ImOverlaps (T min_a, T max_a, T min_b, T max_b)
static ImPlotTime operator+ (const ImPlotTime &lhs, const ImPlotTime &rhs)
static ImPlotTime operator- (const ImPlotTime &lhs, const ImPlotTime &rhs)
static bool operator== (const ImPlotTime &lhs, const ImPlotTime &rhs)
static bool operator< (const ImPlotTime &lhs, const ImPlotTime &rhs)
static bool operator> (const ImPlotTime &lhs, const ImPlotTime &rhs)
static bool operator<= (const ImPlotTime &lhs, const ImPlotTime &rhs)
static bool operator>= (const ImPlotTime &lhs, const ImPlotTime &rhs)
void ImPlot::Initialize (ImPlotContext *ctx)
void ImPlot::ResetCtxForNextPlot (ImPlotContext *ctx)
void ImPlot::ResetCtxForNextAlignedPlots (ImPlotContext *ctx)
void ImPlot::ResetCtxForNextSubplot (ImPlotContext *ctx)
ImPlotPlot * ImPlot::GetPlot (const char *title)
ImPlotPlot * ImPlot::GetCurrentPlot ()
void ImPlot::BustPlotCache ()
void ImPlot::ShowPlotContextMenu (ImPlotPlot &plot)
static void ImPlot::SetupLock ()
void ImPlot::SubplotNextCell ()
void ImPlot::ShowSubplotsContextMenu (ImPlotSubplot &subplot)
IMPLOT_API bool ImPlot::BeginItem (const char *label_id, ImPlotItemFlags flags=0, ImPlotCol recolor_from=IMPLOT_AUTO)
template<typename _Fitter >
bool ImPlot::BeginItemEx (const char *label_id, const _Fitter &fitter, ImPlotItemFlags flags=0, ImPlotCol recolor_from=IMPLOT_AUTO)
IMPLOT_API void ImPlot::EndItem ()
IMPLOT_API ImPlotItem * ImPlot::RegisterOrGetItem (const char *label_id, ImPlotItemFlags flags, bool *just_created=nullptr)
IMPLOT_API ImPlotItem * ImPlot::GetItem (const char *label_id)
IMPLOT_API ImPlotItem * ImPlot::GetCurrentItem ()
IMPLOT_API void ImPlot::BustItemCache ()
static bool ImPlot::AnyAxesInputLocked (ImPlotAxis *axes, int count)
static bool ImPlot::AllAxesInputLocked (ImPlotAxis *axes, int count)
static bool ImPlot::AnyAxesHeld (ImPlotAxis *axes, int count)
static bool ImPlot::AnyAxesHovered (ImPlotAxis *axes, int count)
static bool ImPlot::FitThisFrame ()
static void ImPlot::FitPointX (double x)
static void ImPlot::FitPointY (double y)
static void ImPlot::FitPoint (const ImPlotPoint &p)
static bool ImPlot::RangesOverlap (const ImPlotRange &r1, const ImPlotRange &r2)
void ImPlot::ShowAxisContextMenu (ImPlotAxis &axis, ImPlotAxis *equal_axis, bool)
ImVec2 ImPlot::GetLocationPos (const ImRect &outer_rect, const ImVec2 &inner_size, ImPlotLocation loc, const ImVec2 &pad)
ImVec2 ImPlot::CalcLegendSize (ImPlotItemGroup &items, const ImVec2 &pad, const ImVec2 &spacing, bool vertical)
bool ImPlot::ClampLegendRect (ImRect &legend_rect, const ImRect &outer_rect, const ImVec2 &pad)
bool ImPlot::ShowLegendEntries (ImPlotItemGroup &items, const ImRect &legend_bb, bool hovered, const ImVec2 &pad, const ImVec2 &spacing, bool vertical, ImDrawList &DrawList)
void ImPlot::ShowAltLegend (const char *title_id, bool vertical, const ImVec2 size, bool interactable)
bool ImPlot::ShowLegendContextMenu (ImPlotLegend &legend, bool visible)
void ImPlot::LabelAxisValue (const ImPlotAxis &axis, double value, char *buff, int size, bool round)
static const ImPlotNextItemData & ImPlot::GetItemData ()
static bool ImPlot::IsColorAuto (const ImVec4 &col)
static bool ImPlot::IsColorAuto (ImPlotCol idx)
ImVec4 ImPlot::GetAutoColor (ImPlotCol idx)
static ImVec4 ImPlot::GetStyleColorVec4 (ImPlotCol idx)
static ImU32 ImPlot::GetStyleColorU32 (ImPlotCol idx)
void ImPlot::AddTextVertical (ImDrawList *DrawList, ImVec2 pos, ImU32 col, const char *text_begin, const char *text_end)
void ImPlot::AddTextCentered (ImDrawList *DrawList, ImVec2 top_center, ImU32 col, const char *text_begin, const char *text_end)
static ImVec2 ImPlot::CalcTextSizeVertical (const char *text)
static ImU32 ImPlot::CalcTextColor (const ImVec4 &bg)
static ImU32 ImPlot::CalcTextColor (ImU32 bg)
static ImU32 ImPlot::CalcHoverColor (ImU32 col)
static ImVec2 ImPlot::ClampLabelPos (ImVec2 pos, const ImVec2 &size, const ImVec2 &Min, const ImVec2 &Max)
ImU32 ImPlot::GetColormapColorU32 (int idx, ImPlotColormap cmap)
ImU32 ImPlot::NextColormapColorU32 ()
ImU32 ImPlot::SampleColormapU32 (float t, ImPlotColormap cmap)
void ImPlot::RenderColorBar (const ImU32 *colors, int size, ImDrawList &DrawList, const ImRect &bounds, bool vert, bool reversed, bool continuous)
double ImPlot::NiceNum (double x, bool round)
static int ImPlot::OrderOfMagnitude (double val)
static int ImPlot::OrderToPrecision (int order)
static int ImPlot::Precision (double val)
static double ImPlot::RoundTo (double val, int prec)
static ImVec2 ImPlot::Intersection (const ImVec2 &a1, const ImVec2 &a2, const ImVec2 &b1, const ImVec2 &b2)
template<typename T >
void ImPlot::FillRange (ImVector< T > &buffer, int n, T vmin, T vmax)
template<typename T >
static void ImPlot::CalculateBins (const T *values, int count, ImPlotBin meth, const ImPlotRange &range, int &bins_out, double &width_out)
static bool ImPlot::IsLeapYear (int year)
static int ImPlot::GetDaysInMonth (int year, int month)
ImPlotTime ImPlot::MkGmtTime (struct tm *ptm)
tm * ImPlot::GetGmtTime (const ImPlotTime &t, tm *ptm)
ImPlotTime ImPlot::MkLocTime (struct tm *ptm)
tm * ImPlot::GetLocTime (const ImPlotTime &t, tm *ptm)
static ImPlotTime ImPlot::MkTime (struct tm *ptm)
static tm * ImPlot::GetTime (const ImPlotTime &t, tm *ptm)
ImPlotTime ImPlot::MakeTime (int year, int month, int day, int hour, int min, int sec, int us)
int ImPlot::GetYear (const ImPlotTime &t)
int ImPlot::GetMonth (const ImPlotTime &t)
ImPlotTime ImPlot::AddTime (const ImPlotTime &t, ImPlotTimeUnit unit, int count)
ImPlotTime ImPlot::FloorTime (const ImPlotTime &t, ImPlotTimeUnit unit)
ImPlotTime ImPlot::CeilTime (const ImPlotTime &t, ImPlotTimeUnit unit)
ImPlotTime ImPlot::RoundTime (const ImPlotTime &t, ImPlotTimeUnit unit)
ImPlotTime ImPlot::CombineDateTime (const ImPlotTime &date_part, const ImPlotTime &tod_part)
static ImPlotTime ImPlot::Now ()
static ImPlotTime ImPlot::Today ()
int ImPlot::FormatTime (const ImPlotTime &t, char *buffer, int size, ImPlotTimeFmt fmt, bool use_24_hr_clk)
int ImPlot::FormatDate (const ImPlotTime &t, char *buffer, int size, ImPlotDateFmt fmt, bool use_iso_8601)
int ImPlot::FormatDateTime (const ImPlotTime &t, char *buffer, int size, ImPlotDateTimeSpec fmt)
bool ImPlot::ShowDatePicker (const char *id, int *level, ImPlotTime *t, const ImPlotTime *t1, const ImPlotTime *t2)
bool ImPlot::ShowTimePicker (const char *id, ImPlotTime *t)
static double ImPlot::TransformForward_Log10 (double v, void *)
static double ImPlot::TransformInverse_Log10 (double v, void *)
static double ImPlot::TransformForward_SymLog (double v, void *)
static double ImPlot::TransformInverse_SymLog (double v, void *)
static double ImPlot::TransformForward_Logit (double v, void *)
static double ImPlot::TransformInverse_Logit (double v, void *)
static int ImPlot::Formatter_Default (double value, char *buff, int size, void *data)
static int ImPlot::Formatter_Logit (double value, char *buff, int size, void *)
static int ImPlot::Formatter_Time (double, char *buff, int size, void *data)
void ImPlot::Locator_Default (ImPlotTicker &ticker, const ImPlotRange &range, float pixels, bool vertical, ImPlotFormatter formatter, void *formatter_data)
void ImPlot::Locator_Time (ImPlotTicker &ticker, const ImPlotRange &range, float pixels, bool vertical, ImPlotFormatter formatter, void *formatter_data)
void ImPlot::Locator_Log10 (ImPlotTicker &ticker, const ImPlotRange &range, float pixels, bool vertical, ImPlotFormatter formatter, void *formatter_data)
void ImPlot::Locator_SymLog (ImPlotTicker &ticker, const ImPlotRange &range, float pixels, bool vertical, ImPlotFormatter formatter, void *formatter_data)
Variables
IMPLOT_API ImPlotContext * GImPlot
Macro Definition Documentation
GetBufSize
#define GetBufSize GetSize
Definition at line 45 of file implot_internal.h.
IM_COL32_SPLIT_RGB
#define IM_COL32_SPLIT_RGB (col, r, g, b)
Value:
    ImU32 r = ((col >> IM_COL32_R_SHIFT) & 0xFF); \
    ImU32 g = ((col >> IM_COL32_G_SHIFT) & 0xFF); \
    ImU32 b = ((col >> IM_COL32_B_SHIFT) & 0xFF);
Definition at line 72 of file implot_internal.h.
IMPLOT_LABEL_FORMAT
#define IMPLOT_LABEL_FORMAT "%g"
Definition at line 60 of file implot_internal.h.
IMPLOT_LABEL_MAX_SIZE
#define IMPLOT_LABEL_MAX_SIZE 32
Definition at line 62 of file implot_internal.h.
IMPLOT_MAX_TIME
#define IMPLOT_MAX_TIME 32503680000
Definition at line 58 of file implot_internal.h.
IMPLOT_MIN_TIME
#define IMPLOT_MIN_TIME 0
Definition at line 56 of file implot_internal.h.
IMPLOT_NUM_X_AXES
#define IMPLOT_NUM_X_AXES ImAxis_Y1
Definition at line 68 of file implot_internal.h.
IMPLOT_NUM_Y_AXES
#define IMPLOT_NUM_Y_AXES (ImAxis_COUNT - IMPLOT_NUM_X_AXES)
Definition at line 69 of file implot_internal.h.
Typedef Documentation
ImPlotDateFmt
typedef int ImPlotDateFmt
Definition at line 231 of file implot_internal.h.
ImPlotLocator
typedef void(* ImPlotLocator) (ImPlotTicker &ticker, const ImPlotRange &range, float pixels, bool vertical, ImPlotFormatter formatter, void *formatter_data)
Definition at line 272 of file implot_internal.h.
ImPlotTimeFmt
typedef int ImPlotTimeFmt
Definition at line 232 of file implot_internal.h.
ImPlotTimeUnit
typedef int ImPlotTimeUnit
Definition at line 230 of file implot_internal.h.
Enumeration Type Documentation
ImPlotDateFmt_
enum ImPlotDateFmt_
Enumerator
ImPlotDateFmt_None
ImPlotDateFmt_DayMo
ImPlotDateFmt_DayMoYr
ImPlotDateFmt_MoYr
ImPlotDateFmt_Mo
ImPlotDateFmt_Yr
Definition at line 246 of file implot_internal.h.
ImPlotTimeFmt_
enum ImPlotTimeFmt_
Enumerator
ImPlotTimeFmt_None
ImPlotTimeFmt_Us
ImPlotTimeFmt_SUs
ImPlotTimeFmt_SMs
ImPlotTimeFmt_S
ImPlotTimeFmt_MinSMs
ImPlotTimeFmt_HrMinSMs
ImPlotTimeFmt_HrMinS
ImPlotTimeFmt_HrMin
ImPlotTimeFmt_Hr
Definition at line 255 of file implot_internal.h.
ImPlotTimeUnit_
enum ImPlotTimeUnit_
Enumerator
ImPlotTimeUnit_Us
ImPlotTimeUnit_Ms
ImPlotTimeUnit_S
ImPlotTimeUnit_Min
ImPlotTimeUnit_Hr
ImPlotTimeUnit_Day
ImPlotTimeUnit_Mo
ImPlotTimeUnit_Yr
ImPlotTimeUnit_COUNT
Definition at line 234 of file implot_internal.h.
Function Documentation
ImAlmostEqual()
static bool ImAlmostEqual (double v1, double v2, int ulp = 2) inline static
Definition at line 136 of file implot_internal.h.
References ImAbs().
Referenced by ImPlotAxis::ApplyFit(), and ImPlot::SetupFinish().
ImAlphaU32()
static ImU32 ImAlphaU32 (ImU32 col, float alpha) inline static
Definition at line 216 of file implot_internal.h.
References IM_COL32_A_SHIFT.
Referenced by ImPlot::ShowLegendEntries().
ImAsinh() [1/2]
static double ImAsinh (double x) inline static
Definition at line 108 of file implot_internal.h.
ImAsinh() [2/2]
static float ImAsinh (float x) inline static
Definition at line 107 of file implot_internal.h.
Referenced by ImPlot::TransformForward_SymLog().
ImConstrainInf()
static double ImConstrainInf (double val) inline static
Definition at line 130 of file implot_internal.h.
Referenced by ImPlotAxis::Constrain(), ImPlotAxis::SetMax(), and ImPlotAxis::SetMin().
ImConstrainLog()
static double ImConstrainLog (double val) inline static
Definition at line 132 of file implot_internal.h.
ImConstrainNan()
static double ImConstrainNan (double val) inline static
Definition at line 128 of file implot_internal.h.
References ImNan().
Referenced by ImPlotAxis::Constrain(), ImPlotAxis::SetMax(), and ImPlotAxis::SetMin().
ImConstrainTime()
static double ImConstrainTime (double val) inline static
Definition at line 134 of file implot_internal.h.
References IMPLOT_MAX_TIME, and IMPLOT_MIN_TIME.
ImFlipFlag()
template<typename TSet , typename TFlag > static void ImFlipFlag (TSet & set, TFlag flag) inline static
Definition at line 114 of file implot_internal.h.
References ImHasFlag().
Referenced by ImPlot::EndPlot(), ImPlot::EndSubplots(), ImPlot::ShowAxisContextMenu(), ImPlot::ShowPlotContextMenu(), and ImPlot::ShowSubplotsContextMenu().
ImHasFlag()
template<typename TSet , typename TFlag > static bool ImHasFlag (TSet set, TFlag flag) inline static
Definition at line 111 of file implot_internal.h.
Referenced by ImPlot::BeginItem(), ImPlot::BeginItemEx(), ImPlot::BeginPlot(), ImPlot::BeginSubplots(), ImPlotAxis::CanInitFit(), ImPlot::ColormapScale(), ImPlot::DragLineX(), ImPlot::DragLineY(), ImPlot::DragPoint(), ImPlot::DragRect(), ImPlot::EndPlot(), ImPlot::EndSubplots(), ImPlotAxis::ExtendFitWith(), ImPlot::GetLineRenderProps(), ImPlot::GetLocationPos(), ImPlotAxis::HasGridLines(), ImPlotAxis::HasLabel(), ImPlotAxis::HasMenus(), ImPlotAxis::HasTickLabels(), ImPlotAxis::HasTickMarks(), ImPlotPlot::HasTitle(), ImPlot::if(), ImFlipFlag(), ImPlotAxis::IsAutoFitting(), ImPlotAxis::IsForeground(), ImPlotAxis::IsInverted(), ImPlotAxis::IsLockedMax(), ImPlotAxis::IsLockedMin(), ImPlotAxis::IsOpposite(), ImPlotAxis::IsPanLocked(), ImPlot::PlotBars(), ImPlot::PlotBars(), ImPlot::PlotErrorBars(), ImPlot::PlotHeatmap(), ImPlot::PlotLineEx(), ImPlot::PlotScatterEx(), ImPlot::PlotStairsEx(), ImPlot::PlotStems(), ImPlot::PlotStems(), ImPlot::PlotText(), ImPlot::RegisterOrGetItem(), ImPlot::SetupFinish(), ImPlot::ShowLegendContextMenu(), ImPlot::ShowLegendEntries(), ImPlot::ShowPlotContextMenu(), ImPlot::ShowSubplotsContextMenu(), ImPlot::SubplotSetCell(), ImPlot::SubplotSetCell(), and ImPlot::UpdateInput().
ImLerpU32()
static ImU32 ImLerpU32 (const ImU32 * colors, int size, float t) inline static
Definition at line 203 of file implot_internal.h.
References ImMixU32(), and ImRemap01().
ImLog10() [1/2]
static double ImLog10 (double x) inline static
Definition at line 104 of file implot_internal.h.
ImLog10() [2/2]
static float ImLog10 (float x) inline static
Definition at line 103 of file implot_internal.h.
Referenced by ImPlot::CalcLogarithmicExponents(), ImPlot::NiceNum(), ImPlot::TransformForward_Log10(), and ImPlot::TransformForward_Logit().
ImMaxArray()
template<typename T > static T ImMaxArray (const T * values, int count) inline static
Definition at line 142 of file implot_internal.h.
ImMean()
template<typename T > static double ImMean (const T * values, int count) inline static
Definition at line 163 of file implot_internal.h.
Referenced by ImStdDev().
ImMinArray()
template<typename T > static T ImMinArray (const T * values, int count) inline static
Definition at line 139 of file implot_internal.h.
ImMinMaxArray()
template<typename T > static void ImMinMaxArray (const T * values, int count, T * min_out, T * max_out) inline static
Definition at line 145 of file implot_internal.h.
Referenced by ImPlot::if(), ImPlot::if(), ImPlot::if(), and ImPlot::RenderHeatmap().
ImMixU32()
static ImU32 ImMixU32 (ImU32 a, ImU32 b, ImU32 s) inline static
Definition at line 181 of file implot_internal.h.
Referenced by ImPlotColormapData::_AppendTable(), ImPlot::CalcHoverColor(), ImLerpU32(), and ImPlot::ShowLegendEntries().
ImNan()
static bool ImNan (double val) inline static
Definition at line 124 of file implot_internal.h.
Referenced by ImConstrainNan(), ImNanOrInf(), and ImPlot::RendererLineStripSkip< _Getter >::Render().
ImNanOrInf()
static bool ImNanOrInf (double val) inline static
Definition at line 126 of file implot_internal.h.
References ImNan().
Referenced by ImPlotAxis::ApplyFit(), ImPlotAxis::ExtendFit(), and ImPlotAxis::ExtendFitWith().
ImOverlaps()
template<typename T > static bool ImOverlaps (T min_a, T max_a, T min_b, T max_b) inline static
Definition at line 222 of file implot_internal.h.
ImPosMod()
static int ImPosMod (int l, int r) inline static
Definition at line 122 of file implot_internal.h.
ImRemap()
template<typename T > static T ImRemap (T x, T x0, T x1, T y0, T y1) inline static
Definition at line 117 of file implot_internal.h.
Referenced by ImPlot::ColormapScale(), ImPlot::RenderGridLinesX(), ImPlot::RenderGridLinesY(), and ImPlot::UpdateInput().
ImRemap01()
template<typename T > static T ImRemap01 (T x, T x0, T x1) inline static
Definition at line 120 of file implot_internal.h.
Referenced by ImPlot::float(), ImLerpU32(), ImPlot::GetterHeatmapColMaj< T >::operator()(), and ImPlot::RenderHeatmap().
ImSinh() [1/2]
static double ImSinh (double x) inline static
Definition at line 106 of file implot_internal.h.
ImSinh() [2/2]
static float ImSinh (float x) inline static
Definition at line 105 of file implot_internal.h.
Referenced by ImPlot::TransformInverse_SymLog().
ImStdDev()
template<typename T > static double ImStdDev (const T * values, int count) inline static
Definition at line 172 of file implot_internal.h.
References ImMean().
Referenced by ImPlot::CalculateBins().
ImSum()
template<typename T > static T ImSum (const T * values, int count) inline static
Definition at line 155 of file implot_internal.h.
Referenced by ImPlot::BeginSubplots().
operator+()
static ImPlotTime operator+ (const ImPlotTime & lhs, const ImPlotTime & rhs) inline static
Definition at line 304 of file implot_internal.h.
References ImPlotTime::S, and ImPlotTime::Us.
operator-()
static ImPlotTime operator- (const ImPlotTime & lhs, const ImPlotTime & rhs) inline static
Definition at line 306 of file implot_internal.h.
References ImPlotTime::S, and ImPlotTime::Us.
operator<()
static bool operator< (const ImPlotTime & lhs, const ImPlotTime & rhs) inline static
Definition at line 310 of file implot_internal.h.
References ImPlotTime::S, and ImPlotTime::Us.
operator<=()
static bool operator<= (const ImPlotTime & lhs, const ImPlotTime & rhs) inline static
Definition at line 314 of file implot_internal.h.
operator==()
static bool operator== (const ImPlotTime & lhs, const ImPlotTime & rhs) inline static
Definition at line 308 of file implot_internal.h.
References ImPlotTime::S, and ImPlotTime::Us.
operator>()
static bool operator> (const ImPlotTime & lhs, const ImPlotTime & rhs) inline static
Definition at line 312 of file implot_internal.h.
operator>=()
static bool operator>= (const ImPlotTime & lhs, const ImPlotTime & rhs) inline static
Definition at line 316 of file implot_internal.h.
Variable Documentation
GImPlot
IMPLOT_API ImPlotContext* GImPlot extern
Definition at line 162 of file implot.cpp.
Referenced by ImPlot::AddColormap(), ImPlot::AddColormap(), ImPlot::AddTime(), ImPlot::Annotation(), ImPlot::AnnotationV(), ImPlot::ApplyNextPlotData(), ImPlot::BeginAlignedPlots(), ImPlot::BeginDragDropSourceAxis(), ImPlot::BeginDragDropSourceItem(), ImPlot::BeginDragDropSourcePlot(), ImPlot::BeginDragDropTargetAxis(), ImPlot::BeginDragDropTargetLegend(), ImPlot::BeginDragDropTargetPlot(), ImPlot::BeginItem(), ImPlot::BeginLegendPopup(), ImPlot::BeginPlot(), ImPlot::BeginSubplots(), ImPlot::BustColorCache(), ImPlot::BustItemCache(), ImPlot::BustPlotCache(), ImPlot::CancelPlotSelection(), ImPlot::ColormapButton(), ImPlot::ColormapIcon(), ImPlot::ColormapScale(), ImPlot::ColormapSlider(), ImPlot::CombineDateTime(), ImPlot::CreateContext(), ImPlot::DestroyContext(), ImPlot::DragLineX(), ImPlot::DragLineY(), ImPlot::DragPoint(), ImPlot::DragRect(), ImPlot::EndAlignedPlots(), ImPlot::EndItem(), ImPlot::EndPlot(), ImPlot::EndSubplots(), ImPlot::FitThisFrame(), ImPlot::float(), ImPlot::FloorTime(), ImPlot::FormatDate(), ImPlot::FormatTime(), ImPlot::GetColormapColorU32(), ImPlot::GetColormapCount(), ImPlot::GetColormapIndex(), ImPlot::GetColormapName(), ImPlot::GetColormapSize(), ImPlot::GetCurrentContext(), ImPlot::GetCurrentItem(), ImPlot::GetCurrentPlot(), ImPlot::GetInputMap(), ImPlot::GetItem(), ImPlot::GetItemData(), ImPlot::GetLastItemColor(), ImPlot::GetMonth(), ImPlot::GetPlot(), ImPlot::GetPlotLimits(), ImPlot::GetPlotMousePos(), ImPlot::GetPlotPos(), ImPlot::GetPlotSelection(), ImPlot::GetPlotSize(), ImPlot::GetStyle(), ImPlot::GetStyleColorVec4(), ImPlot::GetYear(), ImPlot::HideNextItem(), ImPlot::IsAxisHovered(), ImPlot::IsColorAuto(), ImPlot::IsLegendEntryHovered(), ImPlot::IsPlotHovered(), ImPlot::IsPlotSelected(), ImPlot::IsSubplotsHovered(), ImPlot::LabelAxisValue(), ImPlot::LegendSortingComp(), ImPlot::MakeTime(), ImPlot::NextColormapColorU32(), ImPlot::GetterHeatmapColMaj< T >::operator()(), ImPlot::PadAndDatumAxesX(), ImPlot::PadAndDatumAxesY(), ImPlot::PixelsToPlot(), ImPlot::PlotText(), ImPlot::PlotToPixels(), ImPlot::PopColormap(), ImPlot::PopStyleColor(), ImPlot::PopStyleVar(), ImPlot::PushColormap(), ImPlot::PushColormap(), ImPlot::PushPlotClipRect(), ImPlot::PushStyleColor(), ImPlot::PushStyleColor(), ImPlot::PushStyleVar(), ImPlot::PushStyleVar(), ImPlot::PushStyleVar(), ImPlot::RegisterOrGetItem(), ImPlot::RenderHeatmap(), ImPlot::SampleColormapU32(), ImPlot::SetAxes(), ImPlot::SetAxis(), ImPlot::SetCurrentContext(), ImPlot::SetNextAxisLimits(), ImPlot::SetNextAxisLinks(), ImPlot::SetNextAxisToFit(), ImPlot::SetNextErrorBarStyle(), ImPlot::SetNextFillStyle(), ImPlot::SetNextLineStyle(), ImPlot::SetNextMarkerStyle(), ImPlot::SetupAxis(), ImPlot::SetupAxisFormat(), ImPlot::SetupAxisFormat(), ImPlot::SetupAxisLimits(), ImPlot::SetupAxisLimitsConstraints(), ImPlot::SetupAxisLinks(), ImPlot::SetupAxisScale(), ImPlot::SetupAxisScale(), ImPlot::SetupAxisTicks(), ImPlot::SetupAxisTicks(), ImPlot::SetupAxisZoomConstraints(), ImPlot::SetupFinish(), ImPlot::SetupLegend(), ImPlot::SetupLock(), ImPlot::SetupMouseText(), ImPlot::ShowAltLegend(), ImPlot::ShowColormapSelector(), ImPlot::ShowDatePicker(), ImPlot::ShowLegendEntries(), ImPlot::ShowMetricsWindow(), ImPlot::ShowPlotContextMenu(), ImPlot::ShowStyleEditor(), ImPlot::ShowTimePicker(), ImPlot::SubplotNextCell(), ImPlot::SubplotSetCell(), ImPlot::SubplotSetCell(), ImPlot::Tag(), ImPlot::TagV(), ImPlot::TagX(), ImPlot::TagX(), ImPlot::TagXV(), ImPlot::TagY(), ImPlot::TagY(), ImPlot::TagYV(), ImPlot::UpdateAxisColors(), and ImPlot::UpdateInput().