SignalProcessing: examples/imgui/imstb_truetype.h File Reference
imstb_truetype.h File Reference
Classes
struct stbtt__buf
struct stbtt_bakedchar
struct stbtt_aligned_quad
struct stbtt_packedchar
struct stbtt_pack_range
struct stbtt_pack_context
struct stbtt_fontinfo
struct stbtt_kerningentry
struct stbtt_vertex
struct stbtt__bitmap
Macros
#define __STB_INCLUDE_STB_TRUETYPE_H__
#define STBTT_DEF extern
#define STBTT_POINT_SIZE(x) (-(x))
#define stbtt_vertex_type short
#define STBTT_MACSTYLE_DONTCARE 0
#define STBTT_MACSTYLE_BOLD 1
#define STBTT_MACSTYLE_ITALIC 2
#define STBTT_MACSTYLE_UNDERSCORE 4
#define STBTT_MACSTYLE_NONE 8
Typedefs
typedef struct stbtt_pack_context stbtt_pack_context
typedef struct stbtt_fontinfo stbtt_fontinfo
typedef struct stbrp_rect stbrp_rect
typedef struct stbtt_kerningentry stbtt_kerningentry
Enumerations
enum { STBTT_vmove =1 , STBTT_vline , STBTT_vcurve , STBTT_vcubic }
enum { STBTT_PLATFORM_ID_UNICODE =0 , STBTT_PLATFORM_ID_MAC =1 , STBTT_PLATFORM_ID_ISO =2 , STBTT_PLATFORM_ID_MICROSOFT =3 }
enum {
STBTT_UNICODE_EID_UNICODE_1_0 =0 , STBTT_UNICODE_EID_UNICODE_1_1 =1 , STBTT_UNICODE_EID_ISO_10646 =2 , STBTT_UNICODE_EID_UNICODE_2_0_BMP =3 ,
STBTT_UNICODE_EID_UNICODE_2_0_FULL =4
}
enum { STBTT_MS_EID_SYMBOL =0 , STBTT_MS_EID_UNICODE_BMP =1 , STBTT_MS_EID_SHIFTJIS =2 , STBTT_MS_EID_UNICODE_FULL =10 }
enum {
STBTT_MAC_EID_ROMAN =0 , STBTT_MAC_EID_ARABIC =4 , STBTT_MAC_EID_JAPANESE =1 , STBTT_MAC_EID_HEBREW =5 ,
STBTT_MAC_EID_CHINESE_TRAD =2 , STBTT_MAC_EID_GREEK =6 , STBTT_MAC_EID_KOREAN =3 , STBTT_MAC_EID_RUSSIAN =7
}
enum {
STBTT_MS_LANG_ENGLISH =0x0409 , STBTT_MS_LANG_ITALIAN =0x0410 , STBTT_MS_LANG_CHINESE =0x0804 , STBTT_MS_LANG_JAPANESE =0x0411 ,
STBTT_MS_LANG_DUTCH =0x0413 , STBTT_MS_LANG_KOREAN =0x0412 , STBTT_MS_LANG_FRENCH =0x040c , STBTT_MS_LANG_RUSSIAN =0x0419 ,
STBTT_MS_LANG_GERMAN =0x0407 , STBTT_MS_LANG_SPANISH =0x0409 , STBTT_MS_LANG_HEBREW =0x040d , STBTT_MS_LANG_SWEDISH =0x041D
}
enum {
STBTT_MAC_LANG_ENGLISH =0 , STBTT_MAC_LANG_JAPANESE =11 , STBTT_MAC_LANG_ARABIC =12 , STBTT_MAC_LANG_KOREAN =23 ,
STBTT_MAC_LANG_DUTCH =4 , STBTT_MAC_LANG_RUSSIAN =32 , STBTT_MAC_LANG_FRENCH =1 , STBTT_MAC_LANG_SPANISH =6 ,
STBTT_MAC_LANG_GERMAN =2 , STBTT_MAC_LANG_SWEDISH =5 , STBTT_MAC_LANG_HEBREW =10 , STBTT_MAC_LANG_CHINESE_SIMPLIFIED =33 ,
STBTT_MAC_LANG_ITALIAN =3 , STBTT_MAC_LANG_CHINESE_TRAD =19
}
Functions
int stbtt_BakeFontBitmap (const unsigned char *data, int offset, float pixel_height, unsigned char *pixels, int pw, int ph, int first_char, int num_chars, stbtt_bakedchar *chardata)
void stbtt_GetBakedQuad (const stbtt_bakedchar *chardata, int pw, int ph, int char_index, float *xpos, float *ypos, stbtt_aligned_quad *q, int opengl_fillrule)
void stbtt_GetScaledFontVMetrics (const unsigned char *fontdata, int index, float size, float *ascent, float *descent, float *lineGap)
int stbtt_PackBegin (stbtt_pack_context *spc, unsigned char *pixels, int width, int height, int stride_in_bytes, int padding, void *alloc_context)
void stbtt_PackEnd (stbtt_pack_context *spc)
int stbtt_PackFontRange (stbtt_pack_context *spc, const unsigned char *fontdata, int font_index, float font_size, int first_unicode_char_in_range, int num_chars_in_range, stbtt_packedchar *chardata_for_range)
int stbtt_PackFontRanges (stbtt_pack_context *spc, const unsigned char *fontdata, int font_index, stbtt_pack_range *ranges, int num_ranges)
void stbtt_PackSetOversampling (stbtt_pack_context *spc, unsigned int h_oversample, unsigned int v_oversample)
void stbtt_PackSetSkipMissingCodepoints (stbtt_pack_context *spc, int skip)
void stbtt_GetPackedQuad (const stbtt_packedchar *chardata, int pw, int ph, int char_index, float *xpos, float *ypos, stbtt_aligned_quad *q, int align_to_integer)
int stbtt_PackFontRangesGatherRects (stbtt_pack_context *spc, const stbtt_fontinfo *info, stbtt_pack_range *ranges, int num_ranges, stbrp_rect *rects)
void stbtt_PackFontRangesPackRects (stbtt_pack_context *spc, stbrp_rect *rects, int num_rects)
int stbtt_PackFontRangesRenderIntoRects (stbtt_pack_context *spc, const stbtt_fontinfo *info, stbtt_pack_range *ranges, int num_ranges, stbrp_rect *rects)
int stbtt_GetNumberOfFonts (const unsigned char *data)
int stbtt_GetFontOffsetForIndex (const unsigned char *data, int index)
int stbtt_InitFont (stbtt_fontinfo *info, const unsigned char *data, int offset)
int stbtt_FindGlyphIndex (const stbtt_fontinfo *info, int unicode_codepoint)
float stbtt_ScaleForPixelHeight (const stbtt_fontinfo *info, float pixels)
float stbtt_ScaleForMappingEmToPixels (const stbtt_fontinfo *info, float pixels)
void stbtt_GetFontVMetrics (const stbtt_fontinfo *info, int *ascent, int *descent, int *lineGap)
int stbtt_GetFontVMetricsOS2 (const stbtt_fontinfo *info, int *typoAscent, int *typoDescent, int *typoLineGap)
void stbtt_GetFontBoundingBox (const stbtt_fontinfo *info, int *x0, int *y0, int *x1, int *y1)
void stbtt_GetCodepointHMetrics (const stbtt_fontinfo *info, int codepoint, int *advanceWidth, int *leftSideBearing)
int stbtt_GetCodepointKernAdvance (const stbtt_fontinfo *info, int ch1, int ch2)
int stbtt_GetCodepointBox (const stbtt_fontinfo *info, int codepoint, int *x0, int *y0, int *x1, int *y1)
void stbtt_GetGlyphHMetrics (const stbtt_fontinfo *info, int glyph_index, int *advanceWidth, int *leftSideBearing)
int stbtt_GetGlyphKernAdvance (const stbtt_fontinfo *info, int glyph1, int glyph2)
int stbtt_GetGlyphBox (const stbtt_fontinfo *info, int glyph_index, int *x0, int *y0, int *x1, int *y1)
int stbtt_GetKerningTableLength (const stbtt_fontinfo *info)
int stbtt_GetKerningTable (const stbtt_fontinfo *info, stbtt_kerningentry *table, int table_length)
int stbtt_IsGlyphEmpty (const stbtt_fontinfo *info, int glyph_index)
int stbtt_GetCodepointShape (const stbtt_fontinfo *info, int unicode_codepoint, stbtt_vertex **vertices)
int stbtt_GetGlyphShape (const stbtt_fontinfo *info, int glyph_index, stbtt_vertex **vertices)
void stbtt_FreeShape (const stbtt_fontinfo *info, stbtt_vertex *vertices)
unsigned char * stbtt_FindSVGDoc (const stbtt_fontinfo *info, int gl)
int stbtt_GetCodepointSVG (const stbtt_fontinfo *info, int unicode_codepoint, const char **svg)
int stbtt_GetGlyphSVG (const stbtt_fontinfo *info, int gl, const char **svg)
void stbtt_FreeBitmap (unsigned char *bitmap, void *userdata)
unsigned char * stbtt_GetCodepointBitmap (const stbtt_fontinfo *info, float scale_x, float scale_y, int codepoint, int *width, int *height, int *xoff, int *yoff)
unsigned char * stbtt_GetCodepointBitmapSubpixel (const stbtt_fontinfo *info, float scale_x, float scale_y, float shift_x, float shift_y, int codepoint, int *width, int *height, int *xoff, int *yoff)
void stbtt_MakeCodepointBitmap (const stbtt_fontinfo *info, unsigned char *output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, int codepoint)
void stbtt_MakeCodepointBitmapSubpixel (const stbtt_fontinfo *info, unsigned char *output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, float shift_x, float shift_y, int codepoint)
void stbtt_MakeCodepointBitmapSubpixelPrefilter (const stbtt_fontinfo *info, unsigned char *output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, float shift_x, float shift_y, int oversample_x, int oversample_y, float *sub_x, float *sub_y, int codepoint)
void stbtt_GetCodepointBitmapBox (const stbtt_fontinfo *font, int codepoint, float scale_x, float scale_y, int *ix0, int *iy0, int *ix1, int *iy1)
void stbtt_GetCodepointBitmapBoxSubpixel (const stbtt_fontinfo *font, int codepoint, float scale_x, float scale_y, float shift_x, float shift_y, int *ix0, int *iy0, int *ix1, int *iy1)
unsigned char * stbtt_GetGlyphBitmap (const stbtt_fontinfo *info, float scale_x, float scale_y, int glyph, int *width, int *height, int *xoff, int *yoff)
unsigned char * stbtt_GetGlyphBitmapSubpixel (const stbtt_fontinfo *info, float scale_x, float scale_y, float shift_x, float shift_y, int glyph, int *width, int *height, int *xoff, int *yoff)
void stbtt_MakeGlyphBitmap (const stbtt_fontinfo *info, unsigned char *output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, int glyph)
void stbtt_MakeGlyphBitmapSubpixel (const stbtt_fontinfo *info, unsigned char *output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, float shift_x, float shift_y, int glyph)
void stbtt_MakeGlyphBitmapSubpixelPrefilter (const stbtt_fontinfo *info, unsigned char *output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, float shift_x, float shift_y, int oversample_x, int oversample_y, float *sub_x, float *sub_y, int glyph)
void stbtt_GetGlyphBitmapBox (const stbtt_fontinfo *font, int glyph, float scale_x, float scale_y, int *ix0, int *iy0, int *ix1, int *iy1)
void stbtt_GetGlyphBitmapBoxSubpixel (const stbtt_fontinfo *font, int glyph, float scale_x, float scale_y, float shift_x, float shift_y, int *ix0, int *iy0, int *ix1, int *iy1)
void stbtt_Rasterize (stbtt__bitmap *result, float flatness_in_pixels, stbtt_vertex *vertices, int num_verts, float scale_x, float scale_y, float shift_x, float shift_y, int x_off, int y_off, int invert, void *userdata)
void stbtt_FreeSDF (unsigned char *bitmap, void *userdata)
unsigned char * stbtt_GetGlyphSDF (const stbtt_fontinfo *info, float scale, int glyph, int padding, unsigned char onedge_value, float pixel_dist_scale, int *width, int *height, int *xoff, int *yoff)
unsigned char * stbtt_GetCodepointSDF (const stbtt_fontinfo *info, float scale, int codepoint, int padding, unsigned char onedge_value, float pixel_dist_scale, int *width, int *height, int *xoff, int *yoff)
int stbtt_FindMatchingFont (const unsigned char *fontdata, const char *name, int flags)
int stbtt_CompareUTF8toUTF16_bigendian (const char *s1, int len1, const char *s2, int len2)
const char * stbtt_GetFontNameString (const stbtt_fontinfo *font, int *length, int platformID, int encodingID, int languageID, int nameID)
Macro Definition Documentation
__STB_INCLUDE_STB_TRUETYPE_H__
#define __STB_INCLUDE_STB_TRUETYPE_H__
Definition at line 505 of file imstb_truetype.h.
STBTT_DEF
#define STBTT_DEF extern
Definition at line 510 of file imstb_truetype.h.
STBTT_MACSTYLE_BOLD
#define STBTT_MACSTYLE_BOLD 1
Definition at line 1032 of file imstb_truetype.h.
STBTT_MACSTYLE_DONTCARE
#define STBTT_MACSTYLE_DONTCARE 0
Definition at line 1031 of file imstb_truetype.h.
STBTT_MACSTYLE_ITALIC
#define STBTT_MACSTYLE_ITALIC 2
Definition at line 1033 of file imstb_truetype.h.
STBTT_MACSTYLE_NONE
#define STBTT_MACSTYLE_NONE 8
Definition at line 1035 of file imstb_truetype.h.
STBTT_MACSTYLE_UNDERSCORE
#define STBTT_MACSTYLE_UNDERSCORE 4
Definition at line 1034 of file imstb_truetype.h.
STBTT_POINT_SIZE
#define STBTT_POINT_SIZE (x) (-(x))
Definition at line 607 of file imstb_truetype.h.
stbtt_vertex_type
#define stbtt_vertex_type short
Definition at line 839 of file imstb_truetype.h.
Typedef Documentation
stbrp_rect
typedef struct stbrp_rect stbrp_rect
Definition at line 590 of file imstb_truetype.h.
stbtt_fontinfo
typedef struct stbtt_fontinfo stbtt_fontinfo
Definition at line 588 of file imstb_truetype.h.
stbtt_kerningentry
typedef struct stbtt_kerningentry stbtt_kerningentry
stbtt_pack_context
typedef struct stbtt_pack_context stbtt_pack_context
Definition at line 587 of file imstb_truetype.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
STBTT_vmove
STBTT_vline
STBTT_vcurve
STBTT_vcubic
Definition at line 829 of file imstb_truetype.h.
anonymous enum
anonymous enum
Enumerator
STBTT_PLATFORM_ID_UNICODE
STBTT_PLATFORM_ID_MAC
STBTT_PLATFORM_ID_ISO
STBTT_PLATFORM_ID_MICROSOFT
Definition at line 1049 of file imstb_truetype.h.
anonymous enum
anonymous enum
Enumerator
STBTT_UNICODE_EID_UNICODE_1_0
STBTT_UNICODE_EID_UNICODE_1_1
STBTT_UNICODE_EID_ISO_10646
STBTT_UNICODE_EID_UNICODE_2_0_BMP
STBTT_UNICODE_EID_UNICODE_2_0_FULL
Definition at line 1056 of file imstb_truetype.h.
anonymous enum
anonymous enum
Enumerator
STBTT_MS_EID_SYMBOL
STBTT_MS_EID_UNICODE_BMP
STBTT_MS_EID_SHIFTJIS
STBTT_MS_EID_UNICODE_FULL
Definition at line 1064 of file imstb_truetype.h.
anonymous enum
anonymous enum
Enumerator
STBTT_MAC_EID_ROMAN
STBTT_MAC_EID_ARABIC
STBTT_MAC_EID_JAPANESE
STBTT_MAC_EID_HEBREW
STBTT_MAC_EID_CHINESE_TRAD
STBTT_MAC_EID_GREEK
STBTT_MAC_EID_KOREAN
STBTT_MAC_EID_RUSSIAN
Definition at line 1071 of file imstb_truetype.h.
anonymous enum
anonymous enum
Enumerator
STBTT_MS_LANG_ENGLISH
STBTT_MS_LANG_ITALIAN
STBTT_MS_LANG_CHINESE
STBTT_MS_LANG_JAPANESE
STBTT_MS_LANG_DUTCH
STBTT_MS_LANG_KOREAN
STBTT_MS_LANG_FRENCH
STBTT_MS_LANG_RUSSIAN
STBTT_MS_LANG_GERMAN
STBTT_MS_LANG_SPANISH
STBTT_MS_LANG_HEBREW
STBTT_MS_LANG_SWEDISH
Definition at line 1078 of file imstb_truetype.h.
anonymous enum
anonymous enum
Enumerator
STBTT_MAC_LANG_ENGLISH
STBTT_MAC_LANG_JAPANESE
STBTT_MAC_LANG_ARABIC
STBTT_MAC_LANG_KOREAN
STBTT_MAC_LANG_DUTCH
STBTT_MAC_LANG_RUSSIAN
STBTT_MAC_LANG_FRENCH
STBTT_MAC_LANG_SPANISH
STBTT_MAC_LANG_GERMAN
STBTT_MAC_LANG_SWEDISH
STBTT_MAC_LANG_HEBREW
STBTT_MAC_LANG_CHINESE_SIMPLIFIED
STBTT_MAC_LANG_ITALIAN
STBTT_MAC_LANG_CHINESE_TRAD
Definition at line 1088 of file imstb_truetype.h.
Function Documentation
stbtt_BakeFontBitmap()
int stbtt_BakeFontBitmap (const unsigned char * data, int offset, float pixel_height, unsigned char * pixels, int pw, int ph, int first_char, int num_chars, stbtt_bakedchar * chardata) extern
stbtt_CompareUTF8toUTF16_bigendian()
int stbtt_CompareUTF8toUTF16_bigendian (const char * s1, int len1, const char * s2, int len2) extern
stbtt_FindGlyphIndex()
int stbtt_FindGlyphIndex (const stbtt_fontinfo * info, int unicode_codepoint) extern
Referenced by ImGui_ImplStbTrueType_FontBakedLoadGlyph(), and ImGui_ImplStbTrueType_FontSrcContainsGlyph().
stbtt_FindMatchingFont()
int stbtt_FindMatchingFont (const unsigned char * fontdata, const char * name, int flags) extern
stbtt_FindSVGDoc()
unsigned char * stbtt_FindSVGDoc (const stbtt_fontinfo * info, int gl) extern
stbtt_FreeBitmap()
void stbtt_FreeBitmap (unsigned char * bitmap, void * userdata) extern
stbtt_FreeSDF()
void stbtt_FreeSDF (unsigned char * bitmap, void * userdata) extern
stbtt_FreeShape()
void stbtt_FreeShape (const stbtt_fontinfo * info, stbtt_vertex * vertices) extern
stbtt_GetBakedQuad()
void stbtt_GetBakedQuad (const stbtt_bakedchar * chardata, int pw, int ph, int char_index, float * xpos, float * ypos, stbtt_aligned_quad * q, int opengl_fillrule) extern
stbtt_GetCodepointBitmap()
unsigned char * stbtt_GetCodepointBitmap (const stbtt_fontinfo * info, float scale_x, float scale_y, int codepoint, int * width, int * height, int * xoff, int * yoff) extern
stbtt_GetCodepointBitmapBox()
void stbtt_GetCodepointBitmapBox (const stbtt_fontinfo * font, int codepoint, float scale_x, float scale_y, int * ix0, int * iy0, int * ix1, int * iy1) extern
stbtt_GetCodepointBitmapBoxSubpixel()
void stbtt_GetCodepointBitmapBoxSubpixel (const stbtt_fontinfo * font, int codepoint, float scale_x, float scale_y, float shift_x, float shift_y, int * ix0, int * iy0, int * ix1, int * iy1) extern
stbtt_GetCodepointBitmapSubpixel()
unsigned char * stbtt_GetCodepointBitmapSubpixel (const stbtt_fontinfo * info, float scale_x, float scale_y, float shift_x, float shift_y, int codepoint, int * width, int * height, int * xoff, int * yoff) extern
stbtt_GetCodepointBox()
int stbtt_GetCodepointBox (const stbtt_fontinfo * info, int codepoint, int * x0, int * y0, int * x1, int * y1) extern
stbtt_GetCodepointHMetrics()
void stbtt_GetCodepointHMetrics (const stbtt_fontinfo * info, int codepoint, int * advanceWidth, int * leftSideBearing) extern
stbtt_GetCodepointKernAdvance()
int stbtt_GetCodepointKernAdvance (const stbtt_fontinfo * info, int ch1, int ch2) extern
stbtt_GetCodepointSDF()
unsigned char * stbtt_GetCodepointSDF (const stbtt_fontinfo * info, float scale, int codepoint, int padding, unsigned char onedge_value, float pixel_dist_scale, int * width, int * height, int * xoff, int * yoff) extern
stbtt_GetCodepointShape()
int stbtt_GetCodepointShape (const stbtt_fontinfo * info, int unicode_codepoint, stbtt_vertex ** vertices) extern
stbtt_GetCodepointSVG()
int stbtt_GetCodepointSVG (const stbtt_fontinfo * info, int unicode_codepoint, const char ** svg) extern
stbtt_GetFontBoundingBox()
void stbtt_GetFontBoundingBox (const stbtt_fontinfo * info, int * x0, int * y0, int * x1, int * y1) extern
stbtt_GetFontNameString()
const char * stbtt_GetFontNameString (const stbtt_fontinfo * font, int * length, int platformID, int encodingID, int languageID, int nameID) extern
stbtt_GetFontOffsetForIndex()
int stbtt_GetFontOffsetForIndex (const unsigned char * data, int index) extern
Referenced by ImGui_ImplStbTrueType_FontSrcInit().
stbtt_GetFontVMetrics()
void stbtt_GetFontVMetrics (const stbtt_fontinfo * info, int * ascent, int * descent, int * lineGap) extern
Referenced by ImGui_ImplStbTrueType_FontBakedInit().
stbtt_GetFontVMetricsOS2()
int stbtt_GetFontVMetricsOS2 (const stbtt_fontinfo * info, int * typoAscent, int * typoDescent, int * typoLineGap) extern
stbtt_GetGlyphBitmap()
unsigned char * stbtt_GetGlyphBitmap (const stbtt_fontinfo * info, float scale_x, float scale_y, int glyph, int * width, int * height, int * xoff, int * yoff) extern
stbtt_GetGlyphBitmapBox()
void stbtt_GetGlyphBitmapBox (const stbtt_fontinfo * font, int glyph, float scale_x, float scale_y, int * ix0, int * iy0, int * ix1, int * iy1) extern
Referenced by ImGui_ImplStbTrueType_FontBakedLoadGlyph().
stbtt_GetGlyphBitmapBoxSubpixel()
void stbtt_GetGlyphBitmapBoxSubpixel (const stbtt_fontinfo * font, int glyph, float scale_x, float scale_y, float shift_x, float shift_y, int * ix0, int * iy0, int * ix1, int * iy1) extern
Referenced by ImGui_ImplStbTrueType_FontBakedLoadGlyph().
stbtt_GetGlyphBitmapSubpixel()
unsigned char * stbtt_GetGlyphBitmapSubpixel (const stbtt_fontinfo * info, float scale_x, float scale_y, float shift_x, float shift_y, int glyph, int * width, int * height, int * xoff, int * yoff) extern
stbtt_GetGlyphBox()
int stbtt_GetGlyphBox (const stbtt_fontinfo * info, int glyph_index, int * x0, int * y0, int * x1, int * y1) extern
stbtt_GetGlyphHMetrics()
void stbtt_GetGlyphHMetrics (const stbtt_fontinfo * info, int glyph_index, int * advanceWidth, int * leftSideBearing) extern
Referenced by ImGui_ImplStbTrueType_FontBakedLoadGlyph().
stbtt_GetGlyphKernAdvance()
int stbtt_GetGlyphKernAdvance (const stbtt_fontinfo * info, int glyph1, int glyph2) extern
stbtt_GetGlyphSDF()
unsigned char * stbtt_GetGlyphSDF (const stbtt_fontinfo * info, float scale, int glyph, int padding, unsigned char onedge_value, float pixel_dist_scale, int * width, int * height, int * xoff, int * yoff) extern
stbtt_GetGlyphShape()
int stbtt_GetGlyphShape (const stbtt_fontinfo * info, int glyph_index, stbtt_vertex ** vertices) extern
stbtt_GetGlyphSVG()
int stbtt_GetGlyphSVG (const stbtt_fontinfo * info, int gl, const char ** svg) extern
stbtt_GetKerningTable()
int stbtt_GetKerningTable (const stbtt_fontinfo * info, stbtt_kerningentry * table, int table_length) extern
stbtt_GetKerningTableLength()
int stbtt_GetKerningTableLength (const stbtt_fontinfo * info) extern
stbtt_GetNumberOfFonts()
int stbtt_GetNumberOfFonts (const unsigned char * data) extern
stbtt_GetPackedQuad()
void stbtt_GetPackedQuad (const stbtt_packedchar * chardata, int pw, int ph, int char_index, float * xpos, float * ypos, stbtt_aligned_quad * q, int align_to_integer) extern
stbtt_GetScaledFontVMetrics()
void stbtt_GetScaledFontVMetrics (const unsigned char * fontdata, int index, float size, float * ascent, float * descent, float * lineGap) extern
stbtt_InitFont()
int stbtt_InitFont (stbtt_fontinfo * info, const unsigned char * data, int offset) extern
Referenced by ImGui_ImplStbTrueType_FontSrcInit().
stbtt_IsGlyphEmpty()
int stbtt_IsGlyphEmpty (const stbtt_fontinfo * info, int glyph_index) extern
stbtt_MakeCodepointBitmap()
void stbtt_MakeCodepointBitmap (const stbtt_fontinfo * info, unsigned char * output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, int codepoint) extern
stbtt_MakeCodepointBitmapSubpixel()
void stbtt_MakeCodepointBitmapSubpixel (const stbtt_fontinfo * info, unsigned char * output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, float shift_x, float shift_y, int codepoint) extern
stbtt_MakeCodepointBitmapSubpixelPrefilter()
void stbtt_MakeCodepointBitmapSubpixelPrefilter (const stbtt_fontinfo * info, unsigned char * output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, float shift_x, float shift_y, int oversample_x, int oversample_y, float * sub_x, float * sub_y, int codepoint) extern
stbtt_MakeGlyphBitmap()
void stbtt_MakeGlyphBitmap (const stbtt_fontinfo * info, unsigned char * output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, int glyph) extern
stbtt_MakeGlyphBitmapSubpixel()
void stbtt_MakeGlyphBitmapSubpixel (const stbtt_fontinfo * info, unsigned char * output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, float shift_x, float shift_y, int glyph) extern
stbtt_MakeGlyphBitmapSubpixelPrefilter()
void stbtt_MakeGlyphBitmapSubpixelPrefilter (const stbtt_fontinfo * info, unsigned char * output, int out_w, int out_h, int out_stride, float scale_x, float scale_y, float shift_x, float shift_y, int oversample_x, int oversample_y, float * sub_x, float * sub_y, int glyph) extern
Referenced by ImGui_ImplStbTrueType_FontBakedLoadGlyph().
stbtt_PackBegin()
int stbtt_PackBegin (stbtt_pack_context * spc, unsigned char * pixels, int width, int height, int stride_in_bytes, int padding, void * alloc_context) extern
stbtt_PackEnd()
void stbtt_PackEnd (stbtt_pack_context * spc) extern
stbtt_PackFontRange()
int stbtt_PackFontRange (stbtt_pack_context * spc, const unsigned char * fontdata, int font_index, float font_size, int first_unicode_char_in_range, int num_chars_in_range, stbtt_packedchar * chardata_for_range) extern
stbtt_PackFontRanges()
int stbtt_PackFontRanges (stbtt_pack_context * spc, const unsigned char * fontdata, int font_index, stbtt_pack_range * ranges, int num_ranges) extern
stbtt_PackFontRangesGatherRects()
int stbtt_PackFontRangesGatherRects (stbtt_pack_context * spc, const stbtt_fontinfo * info, stbtt_pack_range * ranges, int num_ranges, stbrp_rect * rects) extern
stbtt_PackFontRangesPackRects()
void stbtt_PackFontRangesPackRects (stbtt_pack_context * spc, stbrp_rect * rects, int num_rects) extern
stbtt_PackFontRangesRenderIntoRects()
int stbtt_PackFontRangesRenderIntoRects (stbtt_pack_context * spc, const stbtt_fontinfo * info, stbtt_pack_range * ranges, int num_ranges, stbrp_rect * rects) extern
stbtt_PackSetOversampling()
void stbtt_PackSetOversampling (stbtt_pack_context * spc, unsigned int h_oversample, unsigned int v_oversample) extern
stbtt_PackSetSkipMissingCodepoints()
void stbtt_PackSetSkipMissingCodepoints (stbtt_pack_context * spc, int skip) extern
stbtt_Rasterize()
void stbtt_Rasterize (stbtt__bitmap * result, float flatness_in_pixels, stbtt_vertex * vertices, int num_verts, float scale_x, float scale_y, float shift_x, float shift_y, int x_off, int y_off, int invert, void * userdata) extern
stbtt_ScaleForMappingEmToPixels()
float stbtt_ScaleForMappingEmToPixels (const stbtt_fontinfo * info, float pixels) extern
stbtt_ScaleForPixelHeight()
float stbtt_ScaleForPixelHeight (const stbtt_fontinfo * info, float pixels) extern
Referenced by ImGui_ImplStbTrueType_FontSrcInit().