SignalProcessing: ImPlot Namespace Reference
ImPlot Namespace Reference
Classes
struct Fitter1
struct Fitter2
struct FitterBarH
struct FitterBarV
struct FitterRect
struct FitterX
struct FitterY
struct Formatter_Time_Data
struct GetterError
struct GetterFuncPtr
Interprets a user's function pointer as ImPlotPoints.
struct GetterHeatmapColMaj
struct GetterLoop
struct GetterOverrideX
struct GetterOverrideY
struct GetterXY
struct HugeTimeData
struct ImPlotStyleVarInfo
struct IndexerAdd
struct IndexerConst
struct IndexerIdx
struct IndexerLin
struct MaxIdx
struct NormalDistribution
struct RectC
struct RendererBarsFillH
struct RendererBarsFillV
struct RendererBarsLineH
struct RendererBarsLineV
struct RendererBase
struct RendererLineSegments1
struct RendererLineSegments2
struct RendererLineStrip
struct RendererLineStripSkip
struct RendererMarkersFill
struct RendererMarkersLine
struct RendererRectC
struct RendererShaded
struct RendererStairsPost
struct RendererStairsPostShaded
struct RendererStairsPre
struct RendererStairsPreShaded
struct RollingBuffer
struct ScrollingBuffer
struct Transformer1
struct Transformer2
Functions
const char * GetStyleColorName (ImPlotCol col)
const char * GetMarkerName (ImPlotMarker marker)
ImVec4 GetAutoColor (ImPlotCol idx)
static const ImPlotStyleVarInfo * GetPlotStyleVarInfo (ImPlotStyleVar idx)
void AddTextVertical (ImDrawList *DrawList, ImVec2 pos, ImU32 col, const char *text_begin, const char *text_end)
void AddTextCentered (ImDrawList *DrawList, ImVec2 top_center, ImU32 col, const char *text_begin, const char *text_end)
double NiceNum (double x, bool round)
void SetImGuiContext (ImGuiContext *ctx)
ImPlotContext * CreateContext ()
void DestroyContext (ImPlotContext *ctx)
ImPlotContext * GetCurrentContext ()
void SetCurrentContext (ImPlotContext *ctx)
void Initialize (ImPlotContext *ctx)
void ResetCtxForNextPlot (ImPlotContext *ctx)
void ResetCtxForNextAlignedPlots (ImPlotContext *ctx)
void ResetCtxForNextSubplot (ImPlotContext *ctx)
ImPlotPlot * GetPlot (const char *title)
ImPlotPlot * GetCurrentPlot ()
void BustPlotCache ()
ImVec2 GetLocationPos (const ImRect &outer_rect, const ImVec2 &inner_size, ImPlotLocation loc, const ImVec2 &pad)
ImVec2 CalcLegendSize (ImPlotItemGroup &items, const ImVec2 &pad, const ImVec2 &spacing, bool vertical)
bool ClampLegendRect (ImRect &legend_rect, const ImRect &outer_rect, const ImVec2 &pad)
int LegendSortingComp (const void *_a, const void *_b)
bool ShowLegendEntries (ImPlotItemGroup &items, const ImRect &legend_bb, bool hovered, const ImVec2 &pad, const ImVec2 &spacing, bool vertical, ImDrawList &DrawList)
void Locator_Default (ImPlotTicker &ticker, const ImPlotRange &range, float pixels, bool vertical, ImPlotFormatter formatter, void *formatter_data)
bool CalcLogarithmicExponents (const ImPlotRange &range, float pix, bool vertical, int &exp_min, int &exp_max, int &exp_step)
void AddTicksLogarithmic (const ImPlotRange &range, int exp_min, int exp_max, int exp_step, ImPlotTicker &ticker, ImPlotFormatter formatter, void *data)
void Locator_Log10 (ImPlotTicker &ticker, const ImPlotRange &range, float pixels, bool vertical, ImPlotFormatter formatter, void *formatter_data)
float CalcSymLogPixel (double plt, const ImPlotRange &range, float pixels)
void Locator_SymLog (ImPlotTicker &ticker, const ImPlotRange &range, float pixels, bool vertical, ImPlotFormatter formatter, void *formatter_data)
void AddTicksCustom (const double *values, const char *const labels[], int n, ImPlotTicker &ticker, ImPlotFormatter formatter, void *data)
ImPlotTimeUnit GetUnitForRange (double range)
int LowerBoundStep (int max_divs, const int *divs, const int *step, int size)
int GetTimeStep (int max_divs, ImPlotTimeUnit unit)
ImPlotTime MkGmtTime (struct tm *ptm)
tm * GetGmtTime (const ImPlotTime &t, tm *ptm)
ImPlotTime MkLocTime (struct tm *ptm)
tm * GetLocTime (const ImPlotTime &t, tm *ptm)
ImPlotTime MakeTime (int year, int month, int day, int hour, int min, int sec, int us)
int GetYear (const ImPlotTime &t)
int GetMonth (const ImPlotTime &t)
ImPlotTime AddTime (const ImPlotTime &t, ImPlotTimeUnit unit, int count)
ImPlotTime FloorTime (const ImPlotTime &t, ImPlotTimeUnit unit)
ImPlotTime CeilTime (const ImPlotTime &t, ImPlotTimeUnit unit)
ImPlotTime RoundTime (const ImPlotTime &t, ImPlotTimeUnit unit)
ImPlotTime CombineDateTime (const ImPlotTime &date_part, const ImPlotTime &tod_part)
int FormatTime (const ImPlotTime &t, char *buffer, int size, ImPlotTimeFmt fmt, bool use_24_hr_clk)
int FormatDate (const ImPlotTime &t, char *buffer, int size, ImPlotDateFmt fmt, bool use_iso_8601)
int FormatDateTime (const ImPlotTime &t, char *buffer, int size, ImPlotDateTimeSpec fmt)
float GetDateTimeWidth (ImPlotDateTimeSpec fmt)
bool TimeLabelSame (const char *l1, const char *l2)
ImPlotDateTimeSpec GetDateTimeFmt (const ImPlotDateTimeSpec *ctx, ImPlotTimeUnit idx)
void Locator_Time (ImPlotTicker &ticker, const ImPlotRange &range, float pixels, bool vertical, ImPlotFormatter formatter, void *formatter_data)
template<typename F >
bool DragFloat (const char *, F *, float, F, F)
template<>
bool DragFloat< double > (const char *label, double *v, float v_speed, double v_min, double v_max)
template<>
bool DragFloat< float > (const char *label, float *v, float v_speed, float v_min, float v_max)
void BeginDisabledControls (bool cond)
void EndDisabledControls (bool cond)
void ShowAxisContextMenu (ImPlotAxis &axis, ImPlotAxis *equal_axis, bool)
bool ShowLegendContextMenu (ImPlotLegend &legend, bool visible)
void ShowSubplotsContextMenu (ImPlotSubplot &subplot)
void ShowPlotContextMenu (ImPlotPlot &plot)
static int AxisPrecision (const ImPlotAxis &axis)
static double RoundAxisValue (const ImPlotAxis &axis, double value)
void LabelAxisValue (const ImPlotAxis &axis, double value, char *buff, int size, bool round)
void UpdateAxisColors (ImPlotAxis &axis)
void PadAndDatumAxesX (ImPlotPlot &plot, float &pad_T, float &pad_B, ImPlotAlignmentData *align)
void PadAndDatumAxesY (ImPlotPlot &plot, float &pad_L, float &pad_R, ImPlotAlignmentData *align)
static void RenderGridLinesX (ImDrawList &DrawList, const ImPlotTicker &ticker, const ImRect &rect, ImU32 col_maj, ImU32 col_min, float size_maj, float size_min)
static void RenderGridLinesY (ImDrawList &DrawList, const ImPlotTicker &ticker, const ImRect &rect, ImU32 col_maj, ImU32 col_min, float size_maj, float size_min)
static void RenderSelectionRect (ImDrawList &DrawList, const ImVec2 &p_min, const ImVec2 &p_max, const ImVec4 &col)
bool UpdateInput (ImPlotPlot &plot)
void ApplyNextPlotData (ImAxis idx)
void SetupAxis (ImAxis idx, const char *label, ImPlotAxisFlags flags)
void SetupAxisLimits (ImAxis idx, double min_lim, double max_lim, ImPlotCond cond)
void SetupAxisFormat (ImAxis idx, const char *fmt)
void SetupAxisLinks (ImAxis idx, double *min_lnk, double *max_lnk)
void SetupAxisFormat (ImAxis idx, ImPlotFormatter formatter, void *data)
void SetupAxisTicks (ImAxis idx, const double *values, int n_ticks, const char *const labels[], bool show_default)
void SetupAxisTicks (ImAxis idx, double v_min, double v_max, int n_ticks, const char *const labels[], bool show_default)
void SetupAxisScale (ImAxis idx, ImPlotScale scale)
void SetupAxisScale (ImAxis idx, ImPlotTransform fwd, ImPlotTransform inv, void *data)
void SetupAxisLimitsConstraints (ImAxis idx, double v_min, double v_max)
void SetupAxisZoomConstraints (ImAxis idx, double z_min, double z_max)
void SetupAxes (const char *x_label, const char *y_label, ImPlotAxisFlags x_flags, ImPlotAxisFlags y_flags)
void SetupAxesLimits (double x_min, double x_max, double y_min, double y_max, ImPlotCond cond)
void SetupLegend (ImPlotLocation location, ImPlotLegendFlags flags)
void SetupMouseText (ImPlotLocation location, ImPlotMouseTextFlags flags)
void SetNextAxisLimits (ImAxis axis, double v_min, double v_max, ImPlotCond cond)
void SetNextAxisLinks (ImAxis axis, double *link_min, double *link_max)
void SetNextAxisToFit (ImAxis axis)
void SetNextAxesLimits (double x_min, double x_max, double y_min, double y_max, ImPlotCond cond)
void SetNextAxesToFit ()
bool BeginPlot (const char *title_id, const ImVec2 &size, ImPlotFlags flags)
void SetupFinish ()
void EndPlot ()
void SubplotSetCell (int row, int col)
void SubplotSetCell (int idx)
void SubplotNextCell ()
bool BeginSubplots (const char *title, int rows, int cols, const ImVec2 &size, ImPlotSubplotFlags flags, float *row_sizes, float *col_sizes)
void EndSubplots ()
void SetAxis (ImAxis axis)
void SetAxes (ImAxis x_idx, ImAxis y_idx)
ImPlotPoint PixelsToPlot (float x, float y, ImAxis x_idx, ImAxis y_idx)
ImPlotPoint PixelsToPlot (const ImVec2 &pix, ImAxis x_idx, ImAxis y_idx)
ImVec2 PlotToPixels (double x, double y, ImAxis x_idx, ImAxis y_idx)
ImVec2 PlotToPixels (const ImPlotPoint &plt, ImAxis x_idx, ImAxis y_idx)
ImVec2 GetPlotPos ()
ImVec2 GetPlotSize ()
ImPlotPoint GetPlotMousePos (ImAxis x_idx, ImAxis y_idx)
ImPlotRect GetPlotLimits (ImAxis x_idx, ImAxis y_idx)
bool IsPlotHovered ()
bool IsAxisHovered (ImAxis axis)
bool IsSubplotsHovered ()
bool IsPlotSelected ()
ImPlotRect GetPlotSelection (ImAxis x_idx, ImAxis y_idx)
void CancelPlotSelection ()
void HideNextItem (bool hidden, ImPlotCond cond)
void Annotation (double x, double y, const ImVec4 &col, const ImVec2 &offset, bool clamp, bool round)
void AnnotationV (double x, double y, const ImVec4 &col, const ImVec2 &offset, bool clamp, const char *fmt, va_list args)
void Annotation (double x, double y, const ImVec4 &col, const ImVec2 &offset, bool clamp, const char *fmt,...)
void TagV (ImAxis axis, double v, const ImVec4 &col, const char *fmt, va_list args)
void Tag (ImAxis axis, double v, const ImVec4 &col, const char *fmt,...)
void Tag (ImAxis axis, double v, const ImVec4 &color, bool round)
void TagX (double x, const ImVec4 &color, bool round)
void TagX (double x, const ImVec4 &color, const char *fmt,...)
void TagXV (double x, const ImVec4 &color, const char *fmt, va_list args)
void TagY (double y, const ImVec4 &color, bool round)
void TagY (double y, const ImVec4 &color, const char *fmt,...)
void TagYV (double y, const ImVec4 &color, const char *fmt, va_list args)
bool DragPoint (int n_id, double *x, double *y, const ImVec4 &col, float radius, ImPlotDragToolFlags flags, bool *out_clicked, bool *out_hovered, bool *out_held)
bool DragLineX (int n_id, double *value, const ImVec4 &col, float thickness, ImPlotDragToolFlags flags, bool *out_clicked, bool *out_hovered, bool *out_held)
bool DragLineY (int n_id, double *value, const ImVec4 &col, float thickness, ImPlotDragToolFlags flags, bool *out_clicked, bool *out_hovered, bool *out_held)
bool DragRect (int n_id, double *x_min, double *y_min, double *x_max, double *y_max, const ImVec4 &col, ImPlotDragToolFlags flags, bool *out_clicked, bool *out_hovered, bool *out_held)
bool DragRect (int id, ImPlotRect *bounds, const ImVec4 &col, ImPlotDragToolFlags flags, bool *out_clicked, bool *out_hovered, bool *out_held)
bool IsLegendEntryHovered (const char *label_id)
bool BeginLegendPopup (const char *label_id, ImGuiMouseButton mouse_button)
void EndLegendPopup ()
void ShowAltLegend (const char *title_id, bool vertical, const ImVec2 size, bool interactable)
bool BeginDragDropTargetPlot ()
bool BeginDragDropTargetAxis (ImAxis axis)
bool BeginDragDropTargetLegend ()
void EndDragDropTarget ()
bool BeginDragDropSourcePlot (ImGuiDragDropFlags flags)
bool BeginDragDropSourceAxis (ImAxis idx, ImGuiDragDropFlags flags)
bool BeginDragDropSourceItem (const char *label_id, ImGuiDragDropFlags flags)
void EndDragDropSource ()
bool BeginAlignedPlots (const char *group_id, bool vertical)
void EndAlignedPlots ()
ImPlotStyle & GetStyle ()
void PushStyleColor (ImPlotCol idx, ImU32 col)
void PushStyleColor (ImPlotCol idx, const ImVec4 &col)
void PopStyleColor (int count)
void PushStyleVar (ImPlotStyleVar idx, float val)
void PushStyleVar (ImPlotStyleVar idx, int val)
void PushStyleVar (ImPlotStyleVar idx, const ImVec2 &val)
void PopStyleVar (int count)
ImPlotColormap AddColormap (const char *name, const ImVec4 *colormap, int size, bool qual)
ImPlotColormap AddColormap (const char *name, const ImU32 *colormap, int size, bool qual)
int GetColormapCount ()
const char * GetColormapName (ImPlotColormap colormap)
ImPlotColormap GetColormapIndex (const char *name)
void PushColormap (ImPlotColormap colormap)
void PushColormap (const char *name)
void PopColormap (int count)
ImU32 NextColormapColorU32 ()
ImVec4 NextColormapColor ()
int GetColormapSize (ImPlotColormap cmap)
ImU32 GetColormapColorU32 (int idx, ImPlotColormap cmap)
ImVec4 GetColormapColor (int idx, ImPlotColormap cmap)
ImU32 SampleColormapU32 (float t, ImPlotColormap cmap)
ImVec4 SampleColormap (float t, ImPlotColormap cmap)
void RenderColorBar (const ImU32 *colors, int size, ImDrawList &DrawList, const ImRect &bounds, bool vert, bool reversed, bool continuous)
void ColormapScale (const char *label, double scale_min, double scale_max, const ImVec2 &size, const char *format, ImPlotColormapScaleFlags flags, ImPlotColormap cmap)
bool ColormapSlider (const char *label, float *t, ImVec4 *out, const char *format, ImPlotColormap cmap)
bool ColormapButton (const char *label, const ImVec2 &size_arg, ImPlotColormap cmap)
ImPlotInputMap & GetInputMap ()
void MapInputDefault (ImPlotInputMap *dst)
void MapInputReverse (ImPlotInputMap *dst)
void ItemIcon (const ImVec4 &col)
void ItemIcon (ImU32 col)
void ColormapIcon (ImPlotColormap cmap)
ImDrawList * GetPlotDrawList ()
void PushPlotClipRect (float expand)
void PopPlotClipRect ()
static void HelpMarker (const char *desc)
bool ShowStyleSelector (const char *label)
bool ShowColormapSelector (const char *label)
bool ShowInputMapSelector (const char *label)
void ShowStyleEditor (ImPlotStyle *ref)
void ShowUserGuide ()
void ShowTicksMetrics (const ImPlotTicker &ticker)
void ShowAxisMetrics (const ImPlotPlot &plot, const ImPlotAxis &axis)
void ShowMetricsWindow (bool *p_popen)
bool ShowDatePicker (const char *id, int *level, ImPlotTime *t, const ImPlotTime *t1, const ImPlotTime *t2)
bool ShowTimePicker (const char *id, ImPlotTime *t)
void StyleColorsAuto (ImPlotStyle *dst)
void StyleColorsClassic (ImPlotStyle *dst)
void StyleColorsDark (ImPlotStyle *dst)
void StyleColorsLight (ImPlotStyle *dst)
bool BeginPlot (const char *title, const char *x_label, const char *y1_label, const ImVec2 &size, ImPlotFlags flags, ImPlotAxisFlags x_flags, ImPlotAxisFlags y1_flags, ImPlotAxisFlags y2_flags, ImPlotAxisFlags y3_flags, const char *y2_label, const char *y3_label)
template<typename T >
void PlotLine (const char *label_id, const T *values, int count, double xscale=1, double xstart=0, ImPlotLineFlags flags=0, int offset=0, int stride=sizeof(T))
template<typename T >
void PlotLine (const char *label_id, const T *xs, const T *ys, int count, ImPlotLineFlags flags=0, int offset=0, int stride=sizeof(T))
void PlotLineG (const char *label_id, ImPlotGetter getter, void *data, int count, ImPlotLineFlags flags=0)
template<typename T >
void PlotScatter (const char *label_id, const T *values, int count, double xscale=1, double xstart=0, ImPlotScatterFlags flags=0, int offset=0, int stride=sizeof(T))
template<typename T >
void PlotScatter (const char *label_id, const T *xs, const T *ys, int count, ImPlotScatterFlags flags=0, int offset=0, int stride=sizeof(T))
void PlotScatterG (const char *label_id, ImPlotGetter getter, void *data, int count, ImPlotScatterFlags flags=0)
template<typename T >
void PlotStairs (const char *label_id, const T *values, int count, double xscale=1, double xstart=0, ImPlotStairsFlags flags=0, int offset=0, int stride=sizeof(T))
template<typename T >
void PlotStairs (const char *label_id, const T *xs, const T *ys, int count, ImPlotStairsFlags flags=0, int offset=0, int stride=sizeof(T))
void PlotStairsG (const char *label_id, ImPlotGetter getter, void *data, int count, ImPlotStairsFlags flags=0)
template<typename T >
void PlotShaded (const char *label_id, const T *values, int count, double yref=0, double xscale=1, double xstart=0, ImPlotShadedFlags flags=0, int offset=0, int stride=sizeof(T))
template<typename T >
void PlotShaded (const char *label_id, const T *xs, const T *ys, int count, double yref=0, ImPlotShadedFlags flags=0, int offset=0, int stride=sizeof(T))
template<typename T >
void PlotShaded (const char *label_id, const T *xs, const T *ys1, const T *ys2, int count, ImPlotShadedFlags flags=0, int offset=0, int stride=sizeof(T))
void PlotShadedG (const char *label_id, ImPlotGetter getter1, void *data1, ImPlotGetter getter2, void *data2, int count, ImPlotShadedFlags flags=0)
template<typename T >
void PlotBars (const char *label_id, const T *values, int count, double bar_size=0.67, double shift=0, ImPlotBarsFlags flags=0, int offset=0, int stride=sizeof(T))
template<typename T >
void PlotBars (const char *label_id, const T *xs, const T *ys, int count, double bar_size, ImPlotBarsFlags flags=0, int offset=0, int stride=sizeof(T))
void PlotBarsG (const char *label_id, ImPlotGetter getter, void *data, int count, double bar_size, ImPlotBarsFlags flags=0)
template<typename T >
void PlotBarGroups (const char *const label_ids[], const T *values, int item_count, int group_count, double group_size=0.67, double shift=0, ImPlotBarGroupsFlags flags=0)
template<typename T >
void PlotErrorBars (const char *label_id, const T *xs, const T *ys, const T *err, int count, ImPlotErrorBarsFlags flags=0, int offset=0, int stride=sizeof(T))
template<typename T >
void PlotErrorBars (const char *label_id, const T *xs, const T *ys, const T *neg, const T *pos, int count, ImPlotErrorBarsFlags flags=0, int offset=0, int stride=sizeof(T))
template<typename T >
void PlotStems (const char *label_id, const T *values, int count, double ref=0, double scale=1, double start=0, ImPlotStemsFlags flags=0, int offset=0, int stride=sizeof(T))
template<typename T >
void PlotStems (const char *label_id, const T *xs, const T *ys, int count, double ref=0, ImPlotStemsFlags flags=0, int offset=0, int stride=sizeof(T))
template<typename T >
void PlotInfLines (const char *label_id, const T *values, int count, ImPlotInfLinesFlags flags=0, int offset=0, int stride=sizeof(T))
template<typename T >
void PlotPieChart (const char *const label_ids[], const T *values, int count, double x, double y, double radius, ImPlotFormatter fmt, void *fmt_data=nullptr, double angle0=90, ImPlotPieChartFlags flags=0)
template<typename T >
void PlotPieChart (const char *const label_ids[], const T *values, int count, double x, double y, double radius, const char *label_fmt="%.1f", double angle0=90, ImPlotPieChartFlags flags=0)
template<typename T >
void PlotHeatmap (const char *label_id, const T *values, int rows, int cols, double scale_min=0, double scale_max=0, const char *label_fmt="%.1f", const ImPlotPoint &bounds_min=ImPlotPoint(0, 0), const ImPlotPoint &bounds_max=ImPlotPoint(1, 1), ImPlotHeatmapFlags flags=0)
template<typename T >
double PlotHistogram (const char *label_id, const T *values, int count, int bins=ImPlotBin_Sturges, double bar_scale=1.0, ImPlotRange range=ImPlotRange(), ImPlotHistogramFlags flags=0)
template<typename T >
double PlotHistogram2D (const char *label_id, const T *xs, const T *ys, int count, int x_bins=ImPlotBin_Sturges, int y_bins=ImPlotBin_Sturges, ImPlotRect range=ImPlotRect(), ImPlotHistogramFlags flags=0)
template<typename T >
void PlotDigital (const char *label_id, const T *xs, const T *ys, int count, ImPlotDigitalFlags flags=0, int offset=0, int stride=sizeof(T))
void PlotDigitalG (const char *label_id, ImPlotGetter getter, void *data, int count, ImPlotDigitalFlags flags=0)
void PlotImage (const char *label_id, ImTextureID tex_ref, const ImPlotPoint &bounds_min, const ImPlotPoint &bounds_max, const ImVec2 &uv0=ImVec2(0, 0), const ImVec2 &uv1=ImVec2(1, 1), const ImVec4 &tint_col=ImVec4(1, 1, 1, 1), ImPlotImageFlags flags=0)
void PlotText (const char *text, double x, double y, const ImVec2 &pix_offset=ImVec2(0, 0), ImPlotTextFlags flags=0)
void PlotDummy (const char *label_id, ImPlotDummyFlags flags=0)
void SetNextLineStyle (const ImVec4 &col=ImVec4(0, 0, 0,-1), float weight=-1)
void SetNextFillStyle (const ImVec4 &col=ImVec4(0, 0, 0,-1), float alpha_mod=-1)
void SetNextMarkerStyle (ImPlotMarker marker=-1, float size=-1, const ImVec4 &fill=ImVec4(0, 0, 0,-1), float weight=-1, const ImVec4 &outline=ImVec4(0, 0, 0,-1))
void SetNextErrorBarStyle (const ImVec4 &col=ImVec4(0, 0, 0,-1), float size=-1, float weight=-1)
ImVec4 GetLastItemColor ()
void BustColorCache (const char *plot_title_id=nullptr)
void ShowDemoWindow (bool *p_open=nullptr)
template<typename T >
T RandomRange (T min, T max)
ImVec4 RandomColor ()
double RandomGauss ()
void Demo_Help ()
void ButtonSelector (const char *label, ImGuiMouseButton *b)
void ModSelector (const char *label, int *k)
void InputMapping (const char *label, ImGuiMouseButton *b, int *k)
void ShowInputMapping ()
void Demo_Config ()
void Demo_LinePlots ()
void Demo_FilledLinePlots ()
void Demo_ShadedPlots ()
void Demo_ScatterPlots ()
void Demo_StairstepPlots ()
void Demo_BarPlots ()
void Demo_BarGroups ()
void Demo_BarStacks ()
void Demo_ErrorBars ()
void Demo_StemPlots ()
void Demo_InfiniteLines ()
void Demo_PieCharts ()
void Demo_Heatmaps ()
void Demo_Histogram ()
void Demo_Histogram2D ()
void Demo_DigitalPlots ()
void Demo_Images ()
void Demo_RealtimePlots ()
void Demo_MarkersAndText ()
void Demo_NaNValues ()
void Demo_LogScale ()
void Demo_SymmetricLogScale ()
void Demo_TimeScale ()
static double TransformForward_Sqrt (double v, void *)
static double TransformInverse_Sqrt (double v, void *)
void Demo_CustomScale ()
void Demo_MultipleAxes ()
void Demo_LinkedAxes ()
void Demo_AxisConstraints ()
void Demo_EqualAxes ()
void Demo_AutoFittingData ()
ImPlotPoint SinewaveGetter (int i, void *data)
void Demo_SubplotsSizing ()
void Demo_SubplotItemSharing ()
void Demo_SubplotAxisLinking ()
void Demo_LegendOptions ()
void Demo_DragPoints ()
void Demo_DragLines ()
void Demo_DragRects ()
ImPlotPoint FindCentroid (const ImVector< ImPlotPoint > &data, const ImPlotRect &bounds, int &cnt)
void Demo_Querying ()
void Demo_Annotations ()
void Demo_Tags ()
void Demo_DragAndDrop ()
void Demo_Tables ()
void Demo_OffsetAndStride ()
void Demo_CustomDataAndGetters ()
int MetricFormatter (double value, char *buff, int size, void *data)
void Demo_TickLabels ()
void Demo_CustomStyles ()
void Demo_CustomRendering ()
void Demo_LegendPopups ()
void Demo_ColormapWidgets ()
void Demo_CustomPlottersAndTooltips ()
void DemoHeader (const char *label, void(*demo)())
static void SetupLock ()
IMPLOT_API bool BeginItem (const char *label_id, ImPlotItemFlags flags=0, ImPlotCol recolor_from=IMPLOT_AUTO)
template<typename _Fitter >
bool BeginItemEx (const char *label_id, const _Fitter &fitter, ImPlotItemFlags flags=0, ImPlotCol recolor_from=IMPLOT_AUTO)
IMPLOT_API void EndItem ()
IMPLOT_API ImPlotItem * RegisterOrGetItem (const char *label_id, ImPlotItemFlags flags, bool *just_created=nullptr)
IMPLOT_API ImPlotItem * GetItem (const char *label_id)
IMPLOT_API ImPlotItem * GetCurrentItem ()
IMPLOT_API void BustItemCache ()
static bool AnyAxesInputLocked (ImPlotAxis *axes, int count)
static bool AllAxesInputLocked (ImPlotAxis *axes, int count)
static bool AnyAxesHeld (ImPlotAxis *axes, int count)
static bool AnyAxesHovered (ImPlotAxis *axes, int count)
static bool FitThisFrame ()
static void FitPointX (double x)
static void FitPointY (double y)
static void FitPoint (const ImPlotPoint &p)
static bool RangesOverlap (const ImPlotRange &r1, const ImPlotRange &r2)
static const ImPlotNextItemData & GetItemData ()
static bool IsColorAuto (const ImVec4 &col)
static bool IsColorAuto (ImPlotCol idx)
static ImVec4 GetStyleColorVec4 (ImPlotCol idx)
static ImU32 GetStyleColorU32 (ImPlotCol idx)
static ImVec2 CalcTextSizeVertical (const char *text)
static ImU32 CalcTextColor (const ImVec4 &bg)
static ImU32 CalcTextColor (ImU32 bg)
static ImU32 CalcHoverColor (ImU32 col)
static ImVec2 ClampLabelPos (ImVec2 pos, const ImVec2 &size, const ImVec2 &Min, const ImVec2 &Max)
static int OrderOfMagnitude (double val)
static int OrderToPrecision (int order)
static int Precision (double val)
static double RoundTo (double val, int prec)
static ImVec2 Intersection (const ImVec2 &a1, const ImVec2 &a2, const ImVec2 &b1, const ImVec2 &b2)
template<typename T >
void FillRange (ImVector< T > &buffer, int n, T vmin, T vmax)
template<typename T >
static void CalculateBins (const T *values, int count, ImPlotBin meth, const ImPlotRange &range, int &bins_out, double &width_out)
static bool IsLeapYear (int year)
static int GetDaysInMonth (int year, int month)
static ImPlotTime MkTime (struct tm *ptm)
static tm * GetTime (const ImPlotTime &t, tm *ptm)
static ImPlotTime Now ()
static ImPlotTime Today ()
static double TransformForward_Log10 (double v, void *)
static double TransformInverse_Log10 (double v, void *)
static double TransformForward_SymLog (double v, void *)
static double TransformInverse_SymLog (double v, void *)
static double TransformForward_Logit (double v, void *)
static double TransformInverse_Logit (double v, void *)
static int Formatter_Default (double value, char *buff, int size, void *data)
static int Formatter_Logit (double value, char *buff, int size, void *)
static int Formatter_Time (double, char *buff, int size, void *data)
void GetLineRenderProps (const ImDrawList &draw_list, float &half_weight, ImVec2 &tex_uv0, ImVec2 &tex_uv1)
void PrimLine (ImDrawList &draw_list, const ImVec2 &P1, const ImVec2 &P2, float half_weight, ImU32 col, const ImVec2 &tex_uv0, const ImVec2 tex_uv1)
void PrimRectFill (ImDrawList &draw_list, const ImVec2 &Pmin, const ImVec2 &Pmax, ImU32 col, const ImVec2 &uv)
void PrimRectLine (ImDrawList &draw_list, const ImVec2 &Pmin, const ImVec2 &Pmax, float weight, ImU32 col, const ImVec2 &uv)
bool IsItemHidden (const char *label_id)
template<typename T >
T IndexData (const T *data, int idx, int count, int offset, int stride)
template<class _Renderer >
void RenderPrimitivesEx (const _Renderer &renderer, ImDrawList &draw_list, const ImRect &cull_rect)
Renders primitive shapes in bulk as efficiently as possible.
template<template< class > class _Renderer, class _Getter , typename ... Args>
void RenderPrimitives1 (const _Getter &getter, Args... args)
template<template< class, class > class _Renderer, class _Getter1 , class _Getter2 , typename ... Args>
void RenderPrimitives2 (const _Getter1 &getter1, const _Getter2 &getter2, Args... args)
template<typename _Getter >
void RenderMarkers (const _Getter &getter, ImPlotMarker marker, float size, bool rend_fill, ImU32 col_fill, bool rend_line, ImU32 col_line, float weight)
template<typename _Getter >
void PlotLineEx (const char *label_id, const _Getter &getter, ImPlotLineFlags flags)
template void PlotLine< ImS8 > (const char *label_id, const ImS8 *values, int count, double xscale, double x0, ImPlotLineFlags flags, int offset, int stride)
template void PlotLine< ImS8 > (const char *label_id, const ImS8 *xs, const ImS8 *ys, int count, ImPlotLineFlags flags, int offset, int stride)
template void PlotLine< ImU8 > (const char *label_id, const ImU8 *values, int count, double xscale, double x0, ImPlotLineFlags flags, int offset, int stride)
template void PlotLine< ImU8 > (const char *label_id, const ImU8 *xs, const ImU8 *ys, int count, ImPlotLineFlags flags, int offset, int stride)
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() float (double) _END void PlotLineG(const char *label_id
PlotLineEx (label_id, getter, flags)
template<typename Getter >
void PlotScatterEx (const char *label_id, const Getter &getter, ImPlotScatterFlags flags)
template void PlotScatter< ImS8 > (const char *label_id, const ImS8 *values, int count, double xscale, double x0, ImPlotScatterFlags flags, int offset, int stride)
template void PlotScatter< ImS8 > (const char *label_id, const ImS8 *xs, const ImS8 *ys, int count, ImPlotScatterFlags flags, int offset, int stride)
template void PlotScatter< ImU8 > (const char *label_id, const ImU8 *values, int count, double xscale, double x0, ImPlotScatterFlags flags, int offset, int stride)
template void PlotScatter< ImU8 > (const char *label_id, const ImU8 *xs, const ImU8 *ys, int count, ImPlotScatterFlags flags, int offset, int stride)
return PlotScatterEx (label_id, getter, flags)
template<typename Getter >
void PlotStairsEx (const char *label_id, const Getter &getter, ImPlotStairsFlags flags)
template void PlotStairs< ImS8 > (const char *label_id, const ImS8 *values, int count, double xscale, double x0, ImPlotStairsFlags flags, int offset, int stride)
template void PlotStairs< ImS8 > (const char *label_id, const ImS8 *xs, const ImS8 *ys, int count, ImPlotStairsFlags flags, int offset, int stride)
template void PlotStairs< ImU8 > (const char *label_id, const ImU8 *values, int count, double xscale, double x0, ImPlotStairsFlags flags, int offset, int stride)
template void PlotStairs< ImU8 > (const char *label_id, const ImU8 *xs, const ImU8 *ys, int count, ImPlotStairsFlags flags, int offset, int stride)
return PlotStairsEx (label_id, getter, flags)
template<typename Getter1 , typename Getter2 >
void PlotShadedEx (const char *label_id, const Getter1 &getter1, const Getter2 &getter2, ImPlotShadedFlags flags)
template void PlotShaded< ImS8 > (const char *label_id, const ImS8 *values, int count, double y_ref, double xscale, double x0, ImPlotShadedFlags flags, int offset, int stride)
template void PlotShaded< ImS8 > (const char *label_id, const ImS8 *xs, const ImS8 *ys, int count, double y_ref, ImPlotShadedFlags flags, int offset, int stride)
template void PlotShaded< ImS8 > (const char *label_id, const ImS8 *xs, const ImS8 *ys1, const ImS8 *ys2, int count, ImPlotShadedFlags flags, int offset, int stride)
template void PlotShaded< ImU8 > (const char *label_id, const ImU8 *values, int count, double y_ref, double xscale, double x0, ImPlotShadedFlags flags, int offset, int stride)
template void PlotShaded< ImU8 > (const char *label_id, const ImU8 *xs, const ImU8 *ys, int count, double y_ref, ImPlotShadedFlags flags, int offset, int stride)
template void PlotShaded< ImU8 > (const char *label_id, const ImU8 *xs, const ImU8 *ys1, const ImU8 *ys2, int count, ImPlotShadedFlags flags, int offset, int stride)
PlotShadedEx (label_id, getter1, getter2, flags)
template<typename Getter1 , typename Getter2 >
void PlotBarsVEx (const char *label_id, const Getter1 &getter1, const Getter2 getter2, double width, ImPlotBarsFlags flags)
template<typename Getter1 , typename Getter2 >
void PlotBarsHEx (const char *label_id, const Getter1 &getter1, const Getter2 &getter2, double height, ImPlotBarsFlags flags)
template void PlotBars< ImS8 > (const char *label_id, const ImS8 *values, int count, double bar_size, double shift, ImPlotBarsFlags flags, int offset, int stride)
template void PlotBars< ImS8 > (const char *label_id, const ImS8 *xs, const ImS8 *ys, int count, double bar_size, ImPlotBarsFlags flags, int offset, int stride)
template void PlotBars< ImU8 > (const char *label_id, const ImU8 *values, int count, double bar_size, double shift, ImPlotBarsFlags flags, int offset, int stride)
template void PlotBars< ImU8 > (const char *label_id, const ImU8 *xs, const ImU8 *ys, int count, double bar_size, ImPlotBarsFlags flags, int offset, int stride)
template void PlotBarGroups< ImU8 > (const char *const label_ids[], const ImU8 *values, int items, int groups, double width, double shift, ImPlotBarGroupsFlags flags)
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() _GetterNeg void PlotErrorBarsVEx (const char *label_id, const _GetterPos &getter_pos, const _GetterNeg &getter_neg, ImPlotErrorBarsFlags flags)
template<typename _GetterPos , typename _GetterNeg >
void PlotErrorBarsHEx (const char *label_id, const _GetterPos &getter_pos, const _GetterNeg &getter_neg, ImPlotErrorBarsFlags flags)
template void PlotErrorBars< ImS8 > (const char *label_id, const ImS8 *xs, const ImS8 *ys, const ImS8 *err, int count, ImPlotErrorBarsFlags flags, int offset, int stride)
template void PlotErrorBars< ImS8 > (const char *label_id, const ImS8 *xs, const ImS8 *ys, const ImS8 *neg, const ImS8 *pos, int count, ImPlotErrorBarsFlags flags, int offset, int stride)
template void PlotErrorBars< ImU8 > (const char *label_id, const ImU8 *xs, const ImU8 *ys, const ImU8 *err, int count, ImPlotErrorBarsFlags flags, int offset, int stride)
template void PlotErrorBars< ImU8 > (const char *label_id, const ImU8 *xs, const ImU8 *ys, const ImU8 *neg, const ImU8 *pos, int count, ImPlotErrorBarsFlags flags, int offset, int stride)
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() _GetterB void PlotStemsEx (const char *label_id, const _GetterM &getter_mark, const _GetterB &getter_base, ImPlotStemsFlags flags)
template void PlotStems< ImS8 > (const char *label_id, const ImS8 *values, int count, double ref, double scale, double start, ImPlotStemsFlags flags, int offset, int stride)
template void PlotStems< ImS8 > (const char *label_id, const ImS8 *xs, const ImS8 *ys, int count, double ref, ImPlotStemsFlags flags, int offset, int stride)
template void PlotStems< ImU8 > (const char *label_id, const ImU8 *values, int count, double ref, double scale, double start, ImPlotStemsFlags flags, int offset, int stride)
template void PlotStems< ImU8 > (const char *label_id, const ImU8 *xs, const ImU8 *ys, int count, double ref, ImPlotStemsFlags flags, int offset, int stride)
if (ImHasFlag(flags, ImPlotInfLinesFlags_Horizontal))
if (BeginItemEx(label_id, FitterX< GetterXY< IndexerIdx< T >, IndexerConst > >(get_min), flags, ImPlotCol_Line))
template void PlotInfLines< ImS8 > (const char *label_id, const ImS8 *xs, int count, ImPlotInfLinesFlags flags, int offset, int stride)
template void PlotInfLines< ImU8 > (const char *label_id, const ImU8 *xs, int count, ImPlotInfLinesFlags flags, int offset, int stride)
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() float (double) _END inline void RenderPieSlice(ImDrawList &draw_list
template void PlotPieChart< ImU8 > (const char *const label_ids[], const ImU8 *values, int count, double x, double y, double radius, const char *fmt, double angle0, ImPlotPieChartFlags flags)
ImPlotPoint center (x, y)
PushPlotClipRect ()
PlotPieChartEx (label_ids, values, count, center, radius, angle0, flags)
if (fmt !=nullptr)
template void PlotPieChart (const char *const label_ids[], const ImS8 *values, int count, double x, double y, double radius, ImPlotFormatter fmt, void *fmt_data, double angle0, ImPlotPieChartFlags flags)
template void PlotPieChart (const char *const label_ids[], const ImU8 *values, int count, double x, double y, double radius, ImPlotFormatter fmt, void *fmt_data, double angle0, ImPlotPieChartFlags flags)
template<typename T >
void RenderHeatmap (ImDrawList &draw_list, const T *values, int rows, int cols, double scale_min, double scale_max, const char *fmt, const ImPlotPoint &bounds_min, const ImPlotPoint &bounds_max, bool reverse_y, bool col_maj)
template void PlotHeatmap< ImS8 > (const char *label_id, const ImS8 *values, int rows, int cols, double scale_min, double scale_max, const char *fmt, const ImPlotPoint &bounds_min, const ImPlotPoint &bounds_max, ImPlotHeatmapFlags flags)
template void PlotHeatmap< ImU8 > (const char *label_id, const ImU8 *values, int rows, int cols, double scale_min, double scale_max, const char *fmt, const ImPlotPoint &bounds_min, const ImPlotPoint &bounds_max, ImPlotHeatmapFlags flags)
if (count<=0||bins==0) return 0
if (range.Min==0 &&range.Max==0)
if (bins< 0) CalculateBins(values
bin_centers resize (bins)
for (int b=0;b< bins;++b)
if (cumulative &&density)
else if (cumulative)
else if (density)
if (ImHasFlag(flags, ImPlotHistogramFlags_Horizontal)) PlotBars(label_id
else PlotBars (label_id, &bin_centers.Data[0], &bin_counts.Data[0], bins, bar_scale *width)
template double PlotHistogram< ImS8 > (const char *label_id, const ImS8 *values, int count, int bins, double bar_scale, ImPlotRange range, ImPlotHistogramFlags flags)
template double PlotHistogram< ImU8 > (const char *label_id, const ImU8 *values, int count, int bins, double bar_scale, ImPlotRange range, ImPlotHistogramFlags flags)
if (range.X.Min==0 &&range.X.Max==0)
if (range.Y.Min==0 &&range.Y.Max==0)
if (BeginItemEx(label_id, FitterRect(range)))
template double PlotHistogram2D< ImS8 > (const char *label_id, const ImS8 *xs, const ImS8 *ys, int count, int x_bins, int y_bins, ImPlotRect range, ImPlotHistogramFlags flags)
template double PlotHistogram2D< ImU8 > (const char *label_id, const ImU8 *xs, const ImU8 *ys, int count, int x_bins, int y_bins, ImPlotRect range, ImPlotHistogramFlags flags)
template void PlotDigital< ImU8 > (const char *label_id, const ImU8 *xs, const ImU8 *ys, int count, ImPlotDigitalFlags flags, int offset, int stride)
return PlotDigitalEx (label_id, getter, flags)
Variables
static const ImPlotStyleVarInfo GPlotStyleVarInfo []
static const float TICK_FILL_X = 0.8f
static const float TICK_FILL_Y = 1.0f
static const double TimeUnitSpans [ImPlotTimeUnit_COUNT]
static const char * MONTH_NAMES [] = {"January","February","March","April","May","June","July","August","September","October","November","December"}
static const char * WD_ABRVS [] = {"Su","Mo","Tu","We","Th","Fr","Sa"}
static const char * MONTH_ABRVS [] = {"Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"}
static const ImPlotDateTimeSpec TimeFormatLevel0 [ImPlotTimeUnit_COUNT]
static const ImPlotDateTimeSpec TimeFormatLevel1 [ImPlotTimeUnit_COUNT]
static const ImPlotDateTimeSpec TimeFormatLevel1First [ImPlotTimeUnit_COUNT]
static const ImPlotDateTimeSpec TimeFormatMouseCursor [ImPlotTimeUnit_COUNT]
static const float MOUSE_CURSOR_DRAG_THRESHOLD = 5.0f
static const float BOX_SELECT_DRAG_THRESHOLD = 4.0f
static const float SUBPLOT_BORDER_SIZE = 1.0f
static const float SUBPLOT_SPLITTER_HALF_THICKNESS = 4.0f
static const float SUBPLOT_SPLITTER_FEEDBACK_TIMER = 0.06f
static const float DRAG_GRAB_HALF_SIZE = 4.0f
static const float ITEM_HIGHLIGHT_LINE_SCALE = 2.0f
static const float ITEM_HIGHLIGHT_MARK_SCALE = 1.25f
static const ImVec2 MARKER_FILL_CIRCLE [10] = {ImVec2(1.0f, 0.0f), ImVec2(0.809017f, 0.58778524f),ImVec2(0.30901697f, 0.95105654f),ImVec2(-0.30901703f, 0.9510565f),ImVec2(-0.80901706f, 0.5877852f),ImVec2(-1.0f, 0.0f),ImVec2(-0.80901694f, -0.58778536f),ImVec2(-0.3090171f, -0.9510565f),ImVec2(0.30901712f, -0.9510565f),ImVec2(0.80901694f, -0.5877853f)}
static const ImVec2 MARKER_FILL_SQUARE [4] = {ImVec2(0.70710678118f , 0.70710678118f), ImVec2(0.70710678118f ,- 0.70710678118f), ImVec2(- 0.70710678118f ,- 0.70710678118f), ImVec2(- 0.70710678118f , 0.70710678118f)}
static const ImVec2 MARKER_FILL_DIAMOND [4] = {ImVec2(1, 0), ImVec2(0, -1), ImVec2(-1, 0), ImVec2(0, 1)}
static const ImVec2 MARKER_FILL_UP [3] = {ImVec2(0.86602540378f ,0.5f),ImVec2(0,-1),ImVec2(- 0.86602540378f ,0.5f)}
static const ImVec2 MARKER_FILL_DOWN [3] = {ImVec2(0.86602540378f ,-0.5f),ImVec2(0,1),ImVec2(- 0.86602540378f ,-0.5f)}
static const ImVec2 MARKER_FILL_LEFT [3] = {ImVec2(-1,0), ImVec2(0.5, 0.86602540378f), ImVec2(0.5, - 0.86602540378f)}
static const ImVec2 MARKER_FILL_RIGHT [3] = {ImVec2(1,0), ImVec2(-0.5, 0.86602540378f), ImVec2(-0.5, - 0.86602540378f)}
static const ImVec2 MARKER_LINE_CIRCLE [20]
static const ImVec2 MARKER_LINE_SQUARE [8] = {ImVec2(0.70710678118f , 0.70710678118f), ImVec2(0.70710678118f ,- 0.70710678118f), ImVec2(0.70710678118f ,- 0.70710678118f), ImVec2(- 0.70710678118f ,- 0.70710678118f), ImVec2(- 0.70710678118f ,- 0.70710678118f), ImVec2(- 0.70710678118f , 0.70710678118f), ImVec2(- 0.70710678118f , 0.70710678118f), ImVec2(0.70710678118f , 0.70710678118f)}
static const ImVec2 MARKER_LINE_DIAMOND [8] = {ImVec2(1, 0), ImVec2(0, -1), ImVec2(0, -1), ImVec2(-1, 0), ImVec2(-1, 0), ImVec2(0, 1), ImVec2(0, 1), ImVec2(1, 0)}
static const ImVec2 MARKER_LINE_UP [6] = {ImVec2(0.86602540378f ,0.5f), ImVec2(0,-1),ImVec2(0,-1),ImVec2(- 0.86602540378f ,0.5f),ImVec2(- 0.86602540378f ,0.5f),ImVec2(0.86602540378f ,0.5f)}
static const ImVec2 MARKER_LINE_DOWN [6] = {ImVec2(0.86602540378f ,-0.5f),ImVec2(0,1),ImVec2(0,1),ImVec2(- 0.86602540378f ,-0.5f), ImVec2(- 0.86602540378f ,-0.5f), ImVec2(0.86602540378f ,-0.5f)}
static const ImVec2 MARKER_LINE_LEFT [6] = {ImVec2(-1,0), ImVec2(0.5, 0.86602540378f), ImVec2(0.5, 0.86602540378f), ImVec2(0.5, - 0.86602540378f) , ImVec2(0.5, - 0.86602540378f) , ImVec2(-1,0) }
static const ImVec2 MARKER_LINE_RIGHT [6] = {ImVec2(1,0), ImVec2(-0.5, 0.86602540378f), ImVec2(-0.5, 0.86602540378f), ImVec2(-0.5, - 0.86602540378f), ImVec2(-0.5, - 0.86602540378f), ImVec2(1,0) }
static const ImVec2 MARKER_LINE_ASTERISK [6] = {ImVec2(- 0.86602540378f , -0.5f), ImVec2(0.86602540378f , 0.5f), ImVec2(- 0.86602540378f , 0.5f), ImVec2(0.86602540378f , -0.5f), ImVec2(0, -1), ImVec2(0, 1)}
static const ImVec2 MARKER_LINE_PLUS [4] = {ImVec2(-1, 0), ImVec2(1, 0), ImVec2(0, -1), ImVec2(0, 1)}
static const ImVec2 MARKER_LINE_CROSS [4] = {ImVec2(- 0.70710678118f ,- 0.70710678118f),ImVec2(0.70710678118f , 0.70710678118f),ImVec2(0.70710678118f ,- 0.70710678118f),ImVec2(- 0.70710678118f , 0.70710678118f)}
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() ImPlotGetter getter_func
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() ImPlotGetter void * data
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() ImPlotGetter void int count
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() ImPlotGetter void int ImPlotLineFlags flags
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() ImPlotGetter getter_func1
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() ImPlotGetter void * data1
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() ImPlotGetter void ImPlotGetter getter_func2
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() ImPlotGetter void ImPlotGetter void * data2
GetterFuncPtr getter2 (getter_func2, data2, count)
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() ImPlotGetter void int double bar_size
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T * values
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T int ImPlotInfLinesFlags int offset
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T int ImPlotInfLinesFlags int int stride
else
GetterXY< IndexerIdx< T >, IndexerConst > get_max (IndexerIdx< T >(values, count, offset, stride), IndexerConst(lims.Y.Max), count)
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const ImPlotPoint & center
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const ImPlotPoint double radius
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const ImPlotPoint double double a0
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const ImPlotPoint double double double a1
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const ImPlotPoint double double double ImU32 col
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const ImPlotPoint double double double ImU32 bool detached
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T int double x
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T int double double y
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T int double double double ImPlotFormatter fmt
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T int double double double ImPlotFormatter void * fmt_data
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T int double double double ImPlotFormatter void double angle0
ImDrawList & draw_list = *GetPlotDrawList()
const bool ignore_hidden = ImHasFlag(flags, ImPlotPieChartFlags_IgnoreHidden)
const double sum = PieChartSum(values, count, ignore_hidden)
const bool normalize = ImHasFlag(flags, ImPlotPieChartFlags_Normalize) || sum > 1.0
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T int int bins = x_bins * y_bins
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T int int double bar_scale
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T int int double ImPlotRange range
const bool density = ImHasFlag(flags, ImPlotHistogramFlags_Density)
const bool outliers = !ImHasFlag(flags, ImPlotHistogramFlags_NoOutliers)
double width = range.Size() / bins
ImPlotContext & gp = *GImPlot
ImVector< double > & bin_centers = gp.TempDouble1
ImVector< double > & bin_counts = gp.TempDouble2
int below = 0
int counted = 0
double max_count = 0
&bin_counts Data [0]
&bin_counts &bin_centers bar_scale ImPlotBarsFlags_Horizontal
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T * xs
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T const T * ys
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T const T int int x_bins
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T const T int int int y_bins
const bool col_maj = ImHasFlag(flags, ImPlotHistogramFlags_ColMajor)
double height = range.Y.Size() / y_bins
range X
range Y
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() Getter getter
Function Documentation
AddColormap() [1/2]
ImPlotColormap ImPlot::AddColormap (const char * name, const ImU32 * colormap, int size, bool qual)
Definition at line 4509 of file implot.cpp.
References ImPlotColormapData::Append(), ImPlotContext::ColormapData, ImPlotColormapData::GetIndex(), GImPlot, gp, and IM_ASSERT_USER_ERROR.
AddColormap() [2/2]
ImPlotColormap ImPlot::AddColormap (const char * name, const ImVec4 * colormap, int size, bool qual)
Definition at line 4498 of file implot.cpp.
References ImPlotColormapData::Append(), ImGui::ColorConvertFloat4ToU32(), ImPlotContext::ColormapData, ImVector< T >::Data, ImPlotColormapData::GetIndex(), GImPlot, gp, IM_ASSERT_USER_ERROR, and ImVector< T >::resize().
Referenced by Demo_BarStacks(), and ShowStyleEditor().
AddTextCentered()
IMPLOT_API void ImPlot::AddTextCentered (ImDrawList * DrawList, ImVec2 top_center, ImU32 col, const char * text_begin, const char * text_end)
Definition at line 389 of file implot.cpp.
References ImDrawList::AddText(), ImGui::CalcTextSize(), col, ImGui::FindRenderedTextEnd(), ImGui::GetTextLineHeight(), ImVec2::x, ImVec2::y, and y.
Referenced by BeginSubplots(), and EndPlot().
AddTextVertical()
IMPLOT_API void ImPlot::AddTextVertical (ImDrawList * DrawList, ImVec2 pos, ImU32 col, const char * text_begin, const char * text_end)
Definition at line 341 of file implot.cpp.
References ImFontGlyph::AdvanceX, col, ImFontBaked::FindGlyph(), ImGuiContext::Font, ImGuiContext::FontSize, ImFont::GetFontBaked(), GImGui, ImFloor(), ImTextCharFromUtf8(), ImDrawList::PrimQuadUV(), ImDrawList::PrimReserve(), ImDrawList::PrimUnreserve(), ImFontBaked::Size, ImFontGlyph::U0, ImFontGlyph::U1, ImFontGlyph::V0, ImFontGlyph::V1, ImVec2::x, ImFontGlyph::X0, ImFontGlyph::X1, ImVec2::y, ImFontGlyph::Y0, and ImFontGlyph::Y1.
Referenced by ColormapScale(), PlotText(), and SetupFinish().
AddTicksCustom()
void ImPlot::AddTicksCustom (const double * values, const char *const labels[], int n, ImPlotTicker & ticker, ImPlotFormatter formatter, void * data)
Definition at line 843 of file implot.cpp.
References ImPlotTicker::AddTick(), data, and values.
Referenced by SetupAxisTicks().
AddTicksLogarithmic()
void ImPlot::AddTicksLogarithmic (const ImPlotRange & range, int exp_min, int exp_max, int exp_step, ImPlotTicker & ticker, ImPlotFormatter formatter, void * data)
Definition at line 782 of file implot.cpp.
References ImPlotTicker::AddTick(), data, ImPow(), ImSign(), ImPlotRange::Max, ImPlotRange::Min, and range.
Referenced by Locator_Log10(), and Locator_SymLog().
AddTime()
IMPLOT_API ImPlotTime ImPlot::AddTime (const ImPlotTime & t, ImPlotTimeUnit unit, int count)
Definition at line 994 of file implot.cpp.
References count, GetDaysInMonth(), GetTime(), GetYear(), GImPlot, ImPlotTimeUnit_Day, ImPlotTimeUnit_Hr, ImPlotTimeUnit_Min, ImPlotTimeUnit_Mo, ImPlotTimeUnit_Ms, ImPlotTimeUnit_S, ImPlotTimeUnit_Us, ImPlotTimeUnit_Yr, IsLeapYear(), ImPlotTime::RollOver(), ImPlotTime::S, ImPlotContext::Tm, and ImPlotTime::Us.
Referenced by CeilTime(), Locator_Time(), RoundTime(), ShowAxisContextMenu(), and ShowDatePicker().
AllAxesInputLocked()
static bool ImPlot::AllAxesInputLocked (ImPlotAxis * axes, int count) inline static
Definition at line 1373 of file implot_internal.h.
References count.
Referenced by UpdateInput().
Annotation() [1/2]
void ImPlot::Annotation (double x, double y, const ImVec4 & col, const ImVec2 & offset, bool clamp, bool round)
Definition at line 3808 of file implot.cpp.
References Annotation(), ImPlotPlot::Axes, col, ImPlotContext::CurrentPlot, ImPlotPlot::CurrentX, ImPlotPlot::CurrentY, GImPlot, gp, IM_ASSERT_USER_ERROR, IMPLOT_LABEL_MAX_SIZE, LabelAxisValue(), offset, SetupLock(), x, and y.
Referenced by Annotation(), Demo_Annotations(), and Demo_TimeScale().
Annotation() [2/2]
void ImPlot::Annotation (double x, double y, const ImVec4 & col, const ImVec2 & offset, bool clamp, const char * fmt, ...)
Definition at line 3831 of file implot.cpp.
References AnnotationV(), col, fmt, offset, x, and y.
AnnotationV()
void ImPlot::AnnotationV (double x, double y, const ImVec4 & col, const ImVec2 & offset, bool clamp, const char * fmt, va_list args)
Definition at line 3821 of file implot.cpp.
References ImPlotContext::Annotations, ImPlotAnnotationCollection::AppendV(), CalcTextColor(), col, ImPlotContext::CurrentPlot, fmt, ImGui::GetColorU32(), GetStyleColorU32(), GImPlot, gp, IM_ASSERT_USER_ERROR, IMPLOT_AUTO, ImPlotCol_InlayText, offset, PlotToPixels(), SetupLock(), x, and y.
Referenced by Annotation().
AnyAxesHeld()
static bool ImPlot::AnyAxesHeld (ImPlotAxis * axes, int count) inline static
Definition at line 1381 of file implot_internal.h.
References count.
Referenced by EndPlot(), and UpdateInput().
AnyAxesHovered()
static bool ImPlot::AnyAxesHovered (ImPlotAxis * axes, int count) inline static
Definition at line 1389 of file implot_internal.h.
References count.
Referenced by UpdateInput().
AnyAxesInputLocked()
static bool ImPlot::AnyAxesInputLocked (ImPlotAxis * axes, int count) inline static
Definition at line 1364 of file implot_internal.h.
References count.
ApplyNextPlotData()
void ImPlot::ApplyNextPlotData (ImAxis idx)
Definition at line 2100 of file implot.cpp.
References ImPlotPlot::Axes, ImPlotContext::CurrentPlot, ImPlotAxis::Enabled, GImPlot, gp, ImPlotAxis::HasRange, ImPlotNextPlotData::HasRange, ImPlotCond_Always, ImPlotPlot::Initialized, ImPlotAxis::LinkedMax, ImPlotNextPlotData::LinkedMax, ImPlotAxis::LinkedMin, ImPlotNextPlotData::LinkedMin, ImPlotContext::NextPlotData, ImPlotAxis::PullLinks(), ImPlotNextPlotData::Range, ImPlotAxis::RangeCond, ImPlotNextPlotData::RangeCond, and ImPlotAxis::SetRange().
Referenced by BeginPlot().
AxisPrecision()
static int ImPlot::AxisPrecision (const ImPlotAxis & axis) inline static
Definition at line 1591 of file implot.cpp.
References Precision(), ImPlotAxis::Range, range, ImPlotRange::Size(), ImPlotTicker::TickCount(), ImPlotAxis::Ticker, and ImPlotTicker::Ticks.
Referenced by RoundAxisValue().
BeginAlignedPlots()
bool ImPlot::BeginAlignedPlots (const char * group_id, bool vertical)
Definition at line 4357 of file implot.cpp.
References ImPlotContext::AlignmentData, ImPlotAlignmentData::Begin(), ImPlotContext::CurrentAlignmentH, ImPlotContext::CurrentAlignmentV, ImGuiContext::CurrentWindow, ImGuiWindow::GetID(), ImPool< T >::GetOrAddByKey(), GImGui, GImPlot, gp, IM_ASSERT_USER_ERROR, ImPlotAlignmentData::Reset(), ImGuiWindow::SkipItems, and ImPlotAlignmentData::Vertical.
Referenced by Demo_LinkedAxes().
BeginDisabledControls()
void ImPlot::BeginDisabledControls (bool cond) inline
Definition at line 1334 of file implot.cpp.
References ImGui::GetStyle(), ImGuiItemFlags_Disabled, ImGuiStyleVar_Alpha, ImGui::PushItemFlag(), and ImGui::PushStyleVar().
Referenced by ShowAxisContextMenu(), ShowDatePicker(), ShowPlotContextMenu(), and ShowSubplotsContextMenu().
BeginDragDropSourceAxis()
bool ImPlot::BeginDragDropSourceAxis (ImAxis idx, ImGuiDragDropFlags flags)
Definition at line 4327 of file implot.cpp.
References ImPlotPlot::Axes, ImGui::BeginDragDropSource(), ImPlotContext::CurrentPlot, ImGuiContext::DragDropPayload, flags, GImGui, GImPlot, gp, ImPlotAxis::HoverRect, ImPlotAxis::ID, ImPlotContext::InputMap, ImGuiContext::IO, ImGui::ItemAdd(), ImGuiIO::KeyMods, ImPlotInputMap::OverrideMod, SetupLock(), and ImGuiPayload::SourceId.
Referenced by Demo_DragAndDrop().
BeginDragDropSourceItem()
bool ImPlot::BeginDragDropSourceItem (const char * label_id, ImGuiDragDropFlags flags)
Definition at line 4336 of file implot.cpp.
References ImGui::BeginDragDropSource(), ImPlotContext::CurrentItems, flags, ImGui::GetIDWithSeed(), ImPlotItemGroup::GetItem(), GImPlot, gp, ImPlotItem::ID, ImPlotItemGroup::ID, IM_ASSERT_USER_ERROR, ImGui::ItemAdd(), ImPlotItem::LegendHoverRect, and SetupLock().
Referenced by Demo_DragAndDrop(), and Demo_SubplotItemSharing().
BeginDragDropSourcePlot()
bool ImPlot::BeginDragDropSourcePlot (ImGuiDragDropFlags flags)
Definition at line 4318 of file implot.cpp.
References ImGui::BeginDragDropSource(), ImPlotContext::CurrentPlot, ImGuiContext::DragDropPayload, flags, GImGui, GImPlot, gp, ImPlotPlot::ID, ImPlotContext::InputMap, ImGuiContext::IO, ImGui::ItemAdd(), ImGuiIO::KeyMods, ImPlotInputMap::OverrideMod, ImPlotPlot::PlotRect, SetupLock(), and ImGuiPayload::SourceId.
Referenced by Demo_DragAndDrop().
BeginDragDropTargetAxis()
bool ImPlot::BeginDragDropTargetAxis (ImAxis axis)
Definition at line 4297 of file implot.cpp.
References ImPlotPlot::Axes, ImGui::BeginDragDropTargetCustom(), ImPlotContext::CurrentPlot, ImRect::Expand(), GImPlot, ImPlotAxis::HoverRect, ImPlotAxis::ID, and SetupLock().
Referenced by Demo_DragAndDrop().
BeginDragDropTargetLegend()
bool ImPlot::BeginDragDropTargetLegend ()
Definition at line 4306 of file implot.cpp.
References ImGui::BeginDragDropTargetCustom(), ImPlotContext::CurrentItems, GImPlot, ImPlotItemGroup::ID, ImPlotItemGroup::Legend, ImPlotLegend::RectClamped, and SetupLock().
Referenced by Demo_DragAndDrop().
BeginDragDropTargetPlot()
bool ImPlot::BeginDragDropTargetPlot ()
Definition at line 4290 of file implot.cpp.
References ImGui::BeginDragDropTargetCustom(), ImPlotContext::CurrentPlot, GImPlot, gp, ImPlotPlot::ID, ImPlotPlot::PlotRect, and SetupLock().
Referenced by Demo_DragAndDrop(), and Demo_SubplotItemSharing().
BeginItem()
bool ImPlot::BeginItem (const char * label_id, ImPlotItemFlags flags = 0, ImPlotCol recolor_from = IMPLOT_AUTO)
Definition at line 399 of file implot_items.cpp.
References ImPlotPlot::Axes, ImPlotItem::Color, ImGui::ColorConvertFloat4ToU32(), ImGui::ColorConvertU32ToFloat4(), ImPlotAxis::ColorHiLi, ImPlotNextItemData::Colors, ImPlotStyle::Colors, ImPlotContext::CurrentItem, ImPlotContext::CurrentItems, ImPlotContext::CurrentPlot, ImPlotPlot::CurrentX, ImPlotPlot::CurrentY, ImPlotStyle::DigitalBitGap, ImPlotNextItemData::DigitalBitGap, ImPlotStyle::DigitalBitHeight, ImPlotNextItemData::DigitalBitHeight, ImPlotPlot::EnabledAxesX(), ImPlotPlot::EnabledAxesY(), ImPlotStyle::ErrorBarSize, ImPlotNextItemData::ErrorBarSize, ImPlotStyle::ErrorBarWeight, ImPlotNextItemData::ErrorBarWeight, ImPlotStyle::FillAlpha, ImPlotNextItemData::FillAlpha, ImPlotLegend::Flags, flags, GetStyleColorVec4(), GImPlot, gp, ImPlotNextItemData::HasHidden, ImPlotNextItemData::Hidden, ImPlotNextItemData::HiddenCond, IM_ASSERT_USER_ERROR, ImGuiCond_Always, ImHasFlag(), ImPlotCol_ErrorBar, ImPlotCol_Fill, ImPlotCol_Line, ImPlotCol_MarkerFill, ImPlotCol_MarkerOutline, ImPlotLegendFlags_NoHighlightAxis, ImPlotLegendFlags_NoHighlightItem, IsColorAuto(), ITEM_HIGHLIGHT_LINE_SCALE, ITEM_HIGHLIGHT_MARK_SCALE, ImPlotItemGroup::Legend, ImPlotItem::LegendHovered, ImPlotStyle::LineWeight, ImPlotNextItemData::LineWeight, ImPlotStyle::Marker, ImPlotNextItemData::Marker, ImPlotStyle::MarkerSize, ImPlotNextItemData::MarkerSize, ImPlotStyle::MarkerWeight, ImPlotNextItemData::MarkerWeight, NextColormapColorU32(), ImPlotContext::NextItemData, ImPlotContext::PreviousItem, PushPlotClipRect(), RegisterOrGetItem(), ImPlotNextItemData::RenderFill, ImPlotNextItemData::RenderLine, ImPlotNextItemData::RenderMarkerFill, ImPlotNextItemData::RenderMarkerLine, ImPlotNextItemData::Reset(), SetupLock(), ImPlotItem::Show, ImPlotContext::Style, and ImVec4::w.
Referenced by BeginItemEx(), MyImPlot::PlotCandlestick(), and PlotDummy().
BeginItemEx()
template<typename _Fitter > bool ImPlot::BeginItemEx (const char * label_id, const _Fitter & fitter, ImPlotItemFlags flags = 0, ImPlotCol recolor_from = IMPLOT_AUTO)
Definition at line 1337 of file implot_internal.h.
References ImPlotPlot::Axes, BeginItem(), ImPlotPlot::CurrentX, ImPlotPlot::CurrentY, ImPlotPlot::FitThisFrame, flags, GetCurrentPlot(), ImHasFlag(), and ImPlotItemFlags_NoFit.
Referenced by if(), PlotBarsHEx(), PlotBarsVEx(), PlotErrorBarsHEx(), PlotErrorBarsVEx(), PlotHeatmap(), PlotImage(), PlotLineEx(), PlotScatterEx(), PlotShadedEx(), PlotStairsEx(), and PlotStemsEx().
BeginLegendPopup()
bool ImPlot::BeginLegendPopup (const char * label_id, ImGuiMouseButton mouse_button)
Definition at line 4229 of file implot.cpp.
References ImGui::BeginPopupEx(), ImPlotContext::CurrentItems, ImGuiContext::CurrentWindow, ImGui::GetIDWithSeed(), ImPlotItemGroup::GetItem(), GImGui, GImPlot, gp, ImPlotItemGroup::ID, IM_ASSERT_USER_ERROR, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoSavedSettings, ImGuiWindowFlags_NoTitleBar, ImGui::IsMouseReleased(), ImPlotItem::LegendHovered, ImGui::OpenPopupEx(), SetupLock(), and ImGuiWindow::SkipItems.
Referenced by Demo_LegendPopups().
BeginPlot() [1/2]
bool ImPlot::BeginPlot (const char * title, const char * x_label, const char * y1_label, const ImVec2 & size, ImPlotFlags flags, ImPlotAxisFlags x_flags, ImPlotAxisFlags y1_flags, ImPlotAxisFlags y2_flags, ImPlotAxisFlags y3_flags, const char * y2_label, const char * y3_label)
Definition at line 5886 of file implot.cpp.
References BeginPlot(), flags, ImAxis_X1, ImAxis_Y1, ImAxis_Y2, ImAxis_Y3, ImHasFlag(), ImPlotFlags_YAxis2, ImPlotFlags_YAxis3, and SetupAxis().
BeginPlot() [2/2]
bool ImPlot::BeginPlot (const char * title_id, const ImVec2 & size, ImPlotFlags flags)
Definition at line 2373 of file implot.cpp.
References ApplyNextPlotData(), ImPlotPlot::Axes, ImGui::CalcItemSize(), ImPlotSubplot::CellSize, ImPlotPlot::ClearTextBuffer(), ImPlotSubplot::CurrentIdx, ImPlotContext::CurrentItems, ImPlotContext::CurrentPlot, ImPlotContext::CurrentSubplot, ImGuiContext::CurrentWindow, ImPlotPlot::CurrentX, ImPlotPlot::CurrentY, ImGuiWindowTempData::CursorPos, ImGuiWindow::DC, ImPlotAxis::Enabled, ImPlotPlot::Flags, flags, ImPlotPlot::FrameRect, ImPool< T >::GetByKey(), ImGuiWindow::GetID(), ImPool< T >::GetOrAddByKey(), GImGui, GImPlot, gp, ImPlotItemGroup::ID, ImPlotPlot::ID, IM_ASSERT_USER_ERROR, ImAxis_COUNT, ImAxis_X1, ImAxis_Y1, ImGui::ItemAdd(), ImPlotPlot::Items, ImGui::ItemSize(), ImPlotPlot::JustCreated, ImPlotStyle::PlotDefaultSize, ImPlotStyle::PlotMinSize, ImPlotContext::Plots, ImPlotPlot::PreviousFlags, ImGui::PushID(), ImPlotAxis::Reset(), ResetCtxForNextPlot(), ImPlotPlot::SetTitle(), SetupAxis(), ImPlotPlot::SetupLocked, ImGuiWindow::SkipItems, ImPlotContext::Style, UpdateAxisColors(), ImVec2::x, and ImVec2::y.
Referenced by BeginPlot(), Demo_Annotations(), Demo_AutoFittingData(), Demo_AxisConstraints(), Demo_BarGroups(), Demo_BarPlots(), Demo_BarStacks(), Demo_Config(), Demo_CustomDataAndGetters(), Demo_CustomPlottersAndTooltips(), Demo_CustomRendering(), Demo_CustomScale(), Demo_CustomStyles(), Demo_DigitalPlots(), Demo_DragAndDrop(), Demo_DragLines(), Demo_DragPoints(), Demo_DragRects(), Demo_EqualAxes(), Demo_ErrorBars(), Demo_FilledLinePlots(), Demo_Heatmaps(), Demo_Histogram(), Demo_Histogram2D(), Demo_Images(), Demo_InfiniteLines(), Demo_LegendOptions(), Demo_LegendPopups(), Demo_LinePlots(), Demo_LinkedAxes(), Demo_LogScale(), Demo_MarkersAndText(), Demo_MultipleAxes(), Demo_NaNValues(), Demo_OffsetAndStride(), Demo_PieCharts(), Demo_Querying(), Demo_RealtimePlots(), Demo_ScatterPlots(), Demo_ShadedPlots(), Demo_StairstepPlots(), Demo_StemPlots(), Demo_SubplotAxisLinking(), Demo_SubplotItemSharing(), Demo_SubplotsSizing(), Demo_SymmetricLogScale(), Demo_Tags(), Demo_TickLabels(), Demo_TimeScale(), main(), and MyImPlot::Sparkline().
BeginSubplots()
bool ImPlot::BeginSubplots (const char * title, int rows, int cols, const ImVec2 & size, ImPlotSubplotFlags flags, float * row_sizes, float * col_sizes)
Definition at line 3342 of file implot.cpp.
References ImDrawList::AddLine(), AddTextCentered(), ImGui::ButtonBehavior(), ImGui::CalcItemSize(), CalcLegendSize(), ImGui::CalcTextSize(), col, ImPlotSubplot::ColAlignmentData, ImPlotSubplot::ColLinkData, ImGui::ColorConvertFloat4ToU32(), ImGuiStyle::Colors, ImPlotSubplot::ColRatios, ImPlotSubplot::Cols, ImRect::Contains(), ImPlotContext::CurrentItems, ImPlotContext::CurrentSubplot, ImGuiContext::CurrentWindow, ImGuiWindowTempData::CursorPos, ImGuiWindow::DC, ImGui::FindRenderedTextEnd(), ImPlotLegend::Flags, ImPlotSubplot::Flags, flags, ImPlotSubplot::FrameHovered, ImPlotSubplot::FrameRect, ImPool< T >::GetByKey(), ImRect::GetCenter(), ImRect::GetHeight(), ImGuiWindow::GetID(), ImPlotItemGroup::GetLegendCount(), ImGui::GetMouseDragDelta(), ImGui::GetMousePos(), ImPool< T >::GetOrAddByKey(), ImGui::GetStyle(), GetStyleColorU32(), ImRect::GetWidth(), ImGui::GetWindowDrawList(), GImGui, GImPlot, gp, ImPlotSubplot::GridRect, ImPlotSubplot::HasTitle, ImGuiContext::HoveredIdTimer, ImPlotItemGroup::ID, ImPlotSubplot::ID, IM_ASSERT_USER_ERROR, IM_COL32_BLACK_TRANS, IM_ROUND, ImGuiButtonFlags_FlattenChildren, ImGuiButtonFlags_PressedOnClick, ImGuiButtonFlags_PressedOnDoubleClick, ImGuiCol_SeparatorActive, ImGuiCol_SeparatorHovered, ImGuiHoveredFlags_AllowWhenBlockedByActiveItem, ImGuiHoveredFlags_ChildWindows, ImGuiMouseCursor_ResizeEW, ImGuiMouseCursor_ResizeNS, ImGuiStyleVar_FrameBorderSize, ImHasFlag(), ImPlotCol_FrameBg, ImPlotCol_TitleText, ImPlotFlags_NoTitle, ImPlotLegendFlags_Horizontal, ImPlotLocation_East, ImPlotLocation_North, ImPlotLocation_South, ImPlotLocation_West, ImPlotStyleVar_PlotMinSize, ImPlotStyleVar_PlotPadding, ImPlotSubplotFlags_NoLegend, ImPlotSubplotFlags_NoResize, ImPlotSubplotFlags_NoTitle, ImPlotSubplotFlags_ShareItems, ImSum(), ImGui::IsMouseDoubleClicked(), ImGui::IsWindowHovered(), ImPlotSubplot::Items, ImGui::KeepAliveID(), ImPlotStyle::LabelPadding, ImPlotItemGroup::Legend, ImPlotStyle::LegendInnerPadding, ImPlotStyle::LegendPadding, ImPlotStyle::LegendSpacing, ImPlotLegend::Location, ImRect::Max, ImRect::Min, ImPlotStyle::PlotDefaultSize, ImPlotStyle::PlotPadding, ImPlotSubplot::PreviousFlags, ImGui::PushID(), PushStyleColor(), ImGui::PushStyleVar(), PushStyleVar(), ImGui::RenderFrame(), ImPlotLegend::Reset(), ImVector< T >::resize(), ImPlotSubplot::RowAlignmentData, ImPlotSubplot::RowLinkData, ImPlotSubplot::RowRatios, ImPlotSubplot::Rows, ImGui::SetMouseCursor(), ImGuiWindow::SkipItems, ImGuiContext::Style, ImPlotContext::Style, SUBPLOT_BORDER_SIZE, SUBPLOT_SPLITTER_FEEDBACK_TIMER, SUBPLOT_SPLITTER_HALF_THICKNESS, ImPlotContext::Subplots, SubplotSetCell(), ImPlotSubplot::TempSizes, ImVec2::x, and ImVec2::y.
Referenced by Demo_SubplotAxisLinking(), Demo_SubplotItemSharing(), and Demo_SubplotsSizing().
BustColorCache()
void ImPlot::BustColorCache (const char * plot_title_id = nullptr)
Definition at line 373 of file implot_items.cpp.
References BustItemCache(), ImPool< T >::GetByKey(), ImGui::GetCurrentWindow(), ImGuiWindow::GetID(), GImPlot, gp, ImPlotPlot::Items, ImPlotSubplot::Items, ImPlotContext::Plots, ImPlotItemGroup::Reset(), and ImPlotContext::Subplots.
Referenced by Demo_Heatmaps().
BustItemCache()
void ImPlot::BustItemCache ()
Definition at line 361 of file implot_items.cpp.
References ImPool< T >::GetBufSize(), ImPool< T >::GetByIndex(), GImPlot, gp, ImPlotPlot::Items, ImPlotSubplot::Items, ImPlotContext::Plots, ImPlotItemGroup::Reset(), and ImPlotContext::Subplots.
Referenced by BustColorCache(), ShowColormapSelector(), ShowMetricsWindow(), and ShowStyleEditor().
BustPlotCache()
IMPLOT_API void ImPlot::BustPlotCache ()
Definition at line 547 of file implot.cpp.
References ImPool< T >::Clear(), GImPlot, gp, ImPlotContext::Plots, and ImPlotContext::Subplots.
Referenced by ShowMetricsWindow().
ButtonSelector()
void ImPlot::ButtonSelector (const char * label, ImGuiMouseButton * b)
Definition at line 215 of file implot_demo.cpp.
References ImGuiMouseButton_Left, ImGuiMouseButton_Middle, ImGuiMouseButton_Right, ImGui::PopID(), ImGui::PushID(), ImGui::RadioButton(), and ImGui::SameLine().
Referenced by InputMapping().
CalcHoverColor()
static ImU32 ImPlot::CalcHoverColor (ImU32 col) inline static
Definition at line 1487 of file implot_internal.h.
References CalcTextColor(), col, and ImMixU32().
CalcLegendSize()
IMPLOT_API ImVec2 ImPlot::CalcLegendSize (ImPlotItemGroup & items, const ImVec2 & pad, const ImVec2 & spacing, bool vertical)
Definition at line 577 of file implot.cpp.
References ImGui::CalcTextSize(), ImPlotItemGroup::GetLegendCount(), ImPlotItemGroup::GetLegendLabel(), ImGui::GetTextLineHeight(), ImVec2::x, and ImVec2::y.
Referenced by BeginSubplots(), EndPlot(), EndSubplots(), SetupFinish(), and ShowAltLegend().
CalcLogarithmicExponents()
bool ImPlot::CalcLogarithmicExponents (const ImPlotRange & range, float pix, bool vertical, int & exp_min, int & exp_max, int & exp_step)
Definition at line 763 of file implot.cpp.
References IM_ROUND, ImAbs(), ImLog10(), ImMax(), ImMin(), ImPlotRange::Max, ImPlotRange::Min, and range.
Referenced by Locator_Log10(), and Locator_SymLog().
CalcSymLogPixel()
float ImPlot::CalcSymLogPixel (double plt, const ImPlotRange & range, float pixels)
Definition at line 809 of file implot.cpp.
References ImPlotRange::Max, ImPlotRange::Min, range, ImPlotRange::Size(), and TransformForward_SymLog().
Referenced by Locator_SymLog().
CalcTextColor() [1/2]
static ImU32 ImPlot::CalcTextColor (const ImVec4 & bg) inline static
Definition at line 1484 of file implot_internal.h.
References IM_COL32_BLACK, IM_COL32_WHITE, ImVec4::x, ImVec4::y, and ImVec4::z.
Referenced by AnnotationV(), CalcHoverColor(), CalcTextColor(), ColormapButton(), ColormapScale(), ColormapSlider(), if(), RenderHeatmap(), and TagV().
CalcTextColor() [2/2]
static ImU32 ImPlot::CalcTextColor (ImU32 bg) inline static
Definition at line 1485 of file implot_internal.h.
References CalcTextColor(), and ImGui::ColorConvertU32ToFloat4().
CalcTextSizeVertical()
static ImVec2 ImPlot::CalcTextSizeVertical (const char * text) inline static
Definition at line 1479 of file implot_internal.h.
References ImGui::CalcTextSize(), ImVec2::x, and ImVec2::y.
Referenced by PlotText(), and SetupFinish().
CalculateBins()
template<typename T > static void ImPlot::CalculateBins (const T * values, int count, ImPlotBin meth, const ImPlotRange & range, int & bins_out, double & width_out) inline static
Definition at line 1542 of file implot_internal.h.
References count, ImPlotBin_Rice, ImPlotBin_Scott, ImPlotBin_Sqrt, ImPlotBin_Sturges, ImStdDev(), range, ImPlotRange::Size(), and values.
CancelPlotSelection()
void ImPlot::CancelPlotSelection ()
Definition at line 3788 of file implot.cpp.
References ImPlotContext::CurrentPlot, GImPlot, gp, IM_ASSERT_USER_ERROR, ImPlotPlot::Selected, ImPlotPlot::Selecting, and SetupLock().
Referenced by Demo_Querying().
CeilTime()
IMPLOT_API ImPlotTime ImPlot::CeilTime (const ImPlotTime & t, ImPlotTimeUnit unit)
Definition at line 1043 of file implot.cpp.
References AddTime(), and FloorTime().
Referenced by Locator_Time().
center()
ImPlotPoint ImPlot::center (x , y)
ClampLabelPos()
static ImVec2 ImPlot::ClampLabelPos (ImVec2 pos, const ImVec2 & size, const ImVec2 & Min, const ImVec2 & Max) inline static
Definition at line 1490 of file implot_internal.h.
References ImVec2::x, and ImVec2::y.
Referenced by EndPlot().
ClampLegendRect()
IMPLOT_API bool ImPlot::ClampLegendRect (ImRect & legend_rect, const ImRect & outer_rect, const ImVec2 & pad)
Definition at line 598 of file implot.cpp.
References ImRect::Max, ImRect::Min, ImVec2::x, and ImVec2::y.
Referenced by EndPlot(), and EndSubplots().
ColormapButton()
bool ImPlot::ColormapButton (const char * label, const ImVec2 & size_arg, ImPlotColormap cmap)
Definition at line 4759 of file implot.cpp.
References ImGui::Button(), ImGuiStyle::ButtonTextAlign, ImGui::CalcItemSize(), CalcTextColor(), ImGui::CalcTextSize(), ImPlotStyle::Colormap, ImPlotContext::ColormapData, ImPlotColormapData::Count, count, ImGuiContext::CurrentWindow, ImGuiWindowTempData::CursorPos, ImGuiWindow::DC, ImGuiStyle::FramePadding, ImGui::GetCurrentWindow(), ImPlotColormapData::GetKeyCount(), ImPlotColormapData::GetKeys(), ImGui::GetWindowDrawList(), GImGui, GImPlot, gp, IM_ASSERT_USER_ERROR, IM_COL32_BLACK_TRANS, ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImGuiCol_Text, ImGuiStyleVar_FrameRounding, IMPLOT_AUTO, ImPlotColormapData::IsQual(), ImPlotColormapData::LerpTable(), ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), RenderColorBar(), ImGuiWindow::SkipItems, ImGuiContext::Style, ImPlotContext::Style, ImVec2::x, and ImVec2::y.
Referenced by Demo_ColormapWidgets(), Demo_Heatmaps(), and ShowStyleEditor().
ColormapIcon()
void ImPlot::ColormapIcon (ImPlotColormap cmap)
Definition at line 4847 of file implot.cpp.
References ImPlotContext::ColormapData, ImGuiWindowTempData::CursorPos, ImGuiWindow::DC, ImGui::Dummy(), ImGui::GetCurrentWindow(), ImPlotColormapData::GetKeyCount(), ImPlotColormapData::GetKeys(), ImGui::GetTextLineHeight(), ImGui::GetWindowDrawList(), GImPlot, gp, ImPlotColormapData::IsQual(), and RenderColorBar().
Referenced by Demo_ColormapWidgets().
ColormapScale()
void ImPlot::ColormapScale (const char * label, double scale_min, double scale_max, const ImVec2 & size, const char * format, ImPlotColormapScaleFlags flags, ImPlotColormap cmap)
Definition at line 4636 of file implot.cpp.
References ImDrawList::AddLine(), ImDrawList::AddRect(), ImDrawList::AddText(), AddTextVertical(), ImGui::CalcItemSize(), CalcTextColor(), ImGui::CalcTextSize(), ImPlotStyle::Colormap, ImPlotContext::ColormapData, ImPlotColormapData::Count, ImPlotContext::CTicker, ImGuiContext::CurrentWindow, ImGuiWindowTempData::CursorPos, ImGuiWindow::DC, ImGuiWindow::DrawList, ImGui::FindRenderedTextEnd(), flags, float(), Formatter_Default(), ImGuiStyle::FrameRounding, ImRect::GetCenter(), ImGui::GetColorU32(), ImGuiWindow::GetID(), ImPlotColormapData::GetKeyCount(), ImPlotColormapData::GetKeys(), GetStyleColorU32(), ImPlotTicker::GetText(), GImGui, GImPlot, gp, IM_ASSERT_USER_ERROR, ImGuiCol_Text, ImHasFlag(), ImMax(), ImMin(), IMPLOT_AUTO, ImPlotCol_FrameBg, ImPlotCol_PlotBorder, ImPlotColormapScaleFlags_Invert, ImPlotColormapScaleFlags_NoLabel, ImPlotColormapScaleFlags_Opposite, ImRemap(), ImPlotColormapData::IsQual(), ImGui::ItemAdd(), ImGui::ItemSize(), ImPlotStyle::LabelPadding, ImPlotColormapData::LerpTable(), Locator_Default(), ImPlotStyle::MajorTickLen, ImPlotStyle::MajorTickSize, ImRect::Max, ImPlotRange::Max, ImPlotTicker::MaxSize, ImRect::Min, ImPlotRange::Min, ImPlotStyle::MinorTickLen, ImPlotStyle::MinorTickSize, ImPlotStyle::PlotDefaultSize, ImPlotStyle::PlotMinSize, ImPlotStyle::PlotPadding, ImGui::PopClipRect(), ImGui::PushClipRect(), range, RenderColorBar(), ImGui::RenderFrame(), ImPlotTicker::Reset(), ImGuiWindow::SkipItems, ImGuiContext::Style, ImPlotContext::Style, ImPlotTicker::TickCount(), ImPlotTicker::Ticks, ImVec2::x, and ImVec2::y.
Referenced by Demo_ColormapWidgets(), Demo_Heatmaps(), and Demo_Histogram2D().
ColormapSlider()
bool ImPlot::ColormapSlider (const char * label, float * t, ImVec4 * out, const char * format, ImPlotColormap cmap)
Definition at line 4725 of file implot.cpp.
References ImGui::CalcItemWidth(), CalcTextColor(), ImGui::ColorConvertU32ToFloat4(), ImPlotStyle::Colormap, ImPlotContext::ColormapData, ImPlotColormapData::Count, count, ImGuiContext::CurrentWindow, ImGuiWindowTempData::CursorPos, ImGuiWindow::DC, ImGui::GetCurrentWindow(), ImGui::GetFrameHeight(), ImPlotColormapData::GetKeyCount(), ImPlotColormapData::GetKeys(), ImGui::GetWindowDrawList(), GImGui, GImPlot, gp, IM_ASSERT_USER_ERROR, IM_COL32_BLACK_TRANS, ImClamp(), ImGuiCol_FrameBg, ImGuiCol_FrameBgActive, ImGuiCol_FrameBgHovered, ImGuiCol_SliderGrab, ImGuiCol_SliderGrabActive, ImGuiStyleVar_FrameRounding, ImGuiStyleVar_GrabMinSize, IMPLOT_AUTO, ImPlotColormapData::IsQual(), ImPlotColormapData::LerpTable(), ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), RenderColorBar(), ImGuiWindow::SkipItems, ImGui::SliderFloat(), ImPlotContext::Style, ImVec2::x, and ImVec2::y.
Referenced by Demo_ColormapWidgets(), and ShowMetricsWindow().
CombineDateTime()
IMPLOT_API ImPlotTime ImPlot::CombineDateTime (const ImPlotTime & date_part, const ImPlotTime & tod_part)
Definition at line 1055 of file implot.cpp.
References GetTime(), GImPlot, gp, MkTime(), ImPlotContext::Tm, ImPlotTime::Us, and y.
Referenced by ShowAxisContextMenu().
CreateContext()
ImPlotContext * ImPlot::CreateContext ()
Definition at line 437 of file implot.cpp.
References GImPlot, IM_NEW, Initialize(), and SetCurrentContext().
Referenced by main(), and main().
Demo_Annotations()
void ImPlot::Demo_Annotations ()
Definition at line 1646 of file implot_demo.cpp.
References Annotation(), BeginPlot(), ImGui::Checkbox(), col, EndPlot(), GetLastItemColor(), PlotBars(), PlotScatter(), and SetupAxesLimits().
Referenced by ShowDemoWindow().
Demo_AutoFittingData()
void ImPlot::Demo_AutoFittingData ()
Definition at line 1247 of file implot_demo.cpp.
References BeginPlot(), ImGui::BulletText(), ImGui::CheckboxFlags(), data, EndPlot(), ImPlotAxisFlags_AutoFit, ImPlotAxisFlags_None, ImPlotAxisFlags_RangeFit, PlotLine(), PlotStems(), ImGui::SameLine(), SetupAxes(), and ImGui::TextUnformatted().
Referenced by ShowDemoWindow().
Demo_AxisConstraints()
void ImPlot::Demo_AxisConstraints ()
Definition at line 1207 of file implot_demo.cpp.
References BeginPlot(), CHECKBOX_FLAG, ImGui::DragFloat2(), EndPlot(), flags, ImAxis_X1, ImAxis_Y1, ImPlotAxisFlags_PanStretch, SetupAxes(), SetupAxesLimits(), SetupAxisLimitsConstraints(), and SetupAxisZoomConstraints().
Referenced by ShowDemoWindow().
Demo_BarGroups()
void ImPlot::Demo_BarGroups ()
Definition at line 462 of file implot_demo.cpp.
References BeginPlot(), ImGui::Checkbox(), ImGui::CheckboxFlags(), data, EndPlot(), flags, ImAxis_X1, ImAxis_Y1, ImPlotAxisFlags_AutoFit, ImPlotBarGroupsFlags_Horizontal, ImPlotBarGroupsFlags_Stacked, ImPlotLegendFlags_Outside, ImPlotLocation_East, PlotBarGroups(), ImGui::SameLine(), SetupAxes(), SetupAxisTicks(), SetupLegend(), ImGui::SliderFloat(), and ImGui::SliderInt().
Referenced by ShowDemoWindow().
Demo_BarPlots()
void ImPlot::Demo_BarPlots ()
Definition at line 451 of file implot_demo.cpp.
References BeginPlot(), data, EndPlot(), ImPlotBarsFlags_Horizontal, and PlotBars().
Referenced by ShowDemoWindow().
Demo_BarStacks()
void ImPlot::Demo_BarStacks ()
Definition at line 503 of file implot_demo.cpp.
References AddColormap(), BeginPlot(), ImGui::Checkbox(), EndPlot(), ImGui::GetTextLineHeight(), ImAxis_Y1, ImPlotAxisFlags_AutoFit, ImPlotAxisFlags_Invert, ImPlotAxisFlags_NoDecorations, ImPlotBarGroupsFlags_Horizontal, ImPlotBarGroupsFlags_Stacked, ImPlotFlags_NoMouseText, ImPlotLegendFlags_Horizontal, ImPlotLegendFlags_Outside, ImPlotLocation_South, PlotBarGroups(), PopColormap(), PushColormap(), SetupAxes(), SetupAxisTicks(), and SetupLegend().
Referenced by ShowDemoWindow().
Demo_ColormapWidgets()
void ImPlot::Demo_ColormapWidgets ()
Definition at line 2126 of file implot_demo.cpp.
References CHECKBOX_FLAG, col, ImGui::ColorButton(), ColormapButton(), ColormapIcon(), ColormapScale(), ColormapSlider(), flags, GetColormapCount(), ImGuiColorEditFlags_NoInputs, ImPlotColormap_Viridis, ImPlotColormapScaleFlags_Invert, ImPlotColormapScaleFlags_NoLabel, ImPlotColormapScaleFlags_Opposite, ImGui::InputFloat2(), ImGui::SameLine(), and ImGui::Text().
Referenced by ShowDemoWindow().
Demo_Config()
void ImPlot::Demo_Config ()
Definition at line 263 of file implot_demo.cpp.
References BeginPlot(), ImGui::Checkbox(), EndPlot(), GetStyle(), ImAxis_X1, ImPlotScale_Time, PlotLine(), ImGui::PopID(), ImGui::PushID(), ImGui::Separator(), SetupAxisLimits(), SetupAxisScale(), ShowColormapSelector(), ImGui::ShowFontSelector(), ShowInputMapSelector(), ImGui::ShowStyleSelector(), ShowStyleSelector(), x, and y.
Referenced by ShowDemoWindow().
Demo_CustomDataAndGetters()
void ImPlot::Demo_CustomDataAndGetters ()
Definition at line 1944 of file implot_demo.cpp.
References BeginPlot(), ImGui::BulletText(), data1, data2, EndPlot(), ImPlotStyleVar_FillAlpha, ImGui::Indent(), PlotLine(), PlotLineG(), PlotShadedG(), PopStyleVar(), PushStyleVar(), MyImPlot::SawWave(), MyImPlot::SineWave(), MyImPlot::Spiral(), ImGui::Unindent(), x, and y.
Referenced by ShowDemoWindow().
Demo_CustomPlottersAndTooltips()
void ImPlot::Demo_CustomPlottersAndTooltips ()
Definition at line 2152 of file implot_demo.cpp.
References BeginPlot(), ImGui::BulletText(), ImGui::Checkbox(), ImGui::ColorEdit4(), EndPlot(), GetStyle(), ImAxis_X1, ImAxis_Y1, ImGuiColorEditFlags_NoInputs, ImPlotAxisFlags_AutoFit, ImPlotAxisFlags_RangeFit, ImPlotScale_Time, MyImPlot::PlotCandlestick(), ImGui::SameLine(), SetupAxes(), SetupAxesLimits(), SetupAxisFormat(), SetupAxisLimitsConstraints(), SetupAxisScale(), SetupAxisZoomConstraints(), ImPlotStyle::UseLocalTime, and ImVec4::x.
Referenced by ShowDemoWindow().
Demo_CustomRendering()
void ImPlot::Demo_CustomRendering ()
Definition at line 2058 of file implot_demo.cpp.
References ImDrawList::AddCircleFilled(), ImDrawList::AddRect(), BeginPlot(), EndPlot(), GetPlotDrawList(), IM_COL32, PlotToPixels(), PopPlotClipRect(), and PushPlotClipRect().
Referenced by ShowDemoWindow().
Demo_CustomScale()
void ImPlot::Demo_CustomScale ()
Definition at line 1103 of file implot_demo.cpp.
References BeginPlot(), EndPlot(), ImAxis_X1, ImAxis_Y1, PlotLine(), SetupAxis(), SetupAxisLimitsConstraints(), SetupAxisScale(), TransformForward_Sqrt(), and TransformInverse_Sqrt().
Referenced by ShowDemoWindow().
Demo_CustomStyles()
void ImPlot::Demo_CustomStyles ()
Definition at line 2035 of file implot_demo.cpp.
References BeginPlot(), EndPlot(), GetStyle(), ImPlotColormap_Deep, NextColormapColor(), PlotBars(), PlotLine(), PlotScatter(), PopColormap(), PushColormap(), SetupAxes(), SetupAxesLimits(), and MyImPlot::StyleSeaborn().
Referenced by ShowDemoWindow().
Demo_DigitalPlots()
void ImPlot::Demo_DigitalPlots ()
Definition at line 807 of file implot_demo.cpp.
References ImPlot::ScrollingBuffer::AddPoint(), BeginPlot(), ImGui::BulletText(), ImGui::Checkbox(), Data, ImGuiIO::DeltaTime, EndPlot(), ImGui::GetIO(), ImAxis_X1, ImAxis_Y1, ImGuiCond_Always, ImGuiCond_Once, ImGui::Indent(), ImPlot::ScrollingBuffer::Offset, PlotDigital(), PlotLine(), ImGui::SameLine(), SetupAxisLimits(), ImGui::Text(), ImGui::Unindent(), x, and y.
Referenced by ShowDemoWindow().
Demo_DragAndDrop()
void ImPlot::Demo_DragAndDrop ()
Definition at line 1695 of file implot_demo.cpp.
References ImGui::AcceptDragDropPayload(), ImGui::BeginChild(), ImGui::BeginDragDropSource(), BeginDragDropSourceAxis(), BeginDragDropSourceItem(), BeginDragDropSourcePlot(), ImGui::BeginDragDropTarget(), BeginDragDropTargetAxis(), BeginDragDropTargetLegend(), BeginDragDropTargetPlot(), BeginPlot(), ImGui::BulletText(), ImGui::Button(), ImPlotStyle::Colors, Data, ImGui::EndChild(), ImGui::EndDragDropSource(), EndDragDropSource(), ImGui::EndDragDropTarget(), EndDragDropTarget(), EndPlot(), flags, GetStyle(), ImGui::GetTextLineHeight(), ImAxis_X1, ImAxis_Y1, ImAxis_Y2, ImAxis_Y3, ImGuiDragDropFlags_None, ImPlotAxisFlags_Lock, ImPlotAxisFlags_NoGridLines, ImPlotAxisFlags_NoHighlight, ImPlotAxisFlags_NoTickLabels, ImPlotAxisFlags_Opposite, ImPlotCol_AxisBg, ImGui::Indent(), ItemIcon(), PlotLine(), PopStyleColor(), PushStyleColor(), RandomColor(), ImGui::SameLine(), ImGui::Selectable(), SetAxis(), ImGui::SetDragDropPayload(), SetNextLineStyle(), SetupAxis(), ImGui::TextUnformatted(), ImGui::Unindent(), x, and y.
Referenced by ShowDemoWindow().
Demo_DragLines()
void ImPlot::Demo_DragLines ()
Definition at line 1479 of file implot_demo.cpp.
References BeginPlot(), ImGui::BulletText(), ImGui::CheckboxFlags(), DragLineX(), DragLineY(), EndPlot(), flags, IMPLOT_AUTO_COL, ImPlotDragToolFlags_NoCursors, ImPlotDragToolFlags_NoFit, ImPlotDragToolFlags_NoInputs, ImPlotDragToolFlags_None, PlotLine(), ImGui::SameLine(), SetNextLineStyle(), SetupAxesLimits(), xs, and ys.
Referenced by ShowDemoWindow().
Demo_DragPoints()
void ImPlot::Demo_DragPoints ()
Definition at line 1436 of file implot_demo.cpp.
References BeginPlot(), ImGui::BulletText(), ImGui::CheckboxFlags(), DragPoint(), EndPlot(), flags, ImPlotAxisFlags_NoTickLabels, ImPlotAxisFlags_NoTickMarks, ImPlotDragToolFlags_NoCursors, ImPlotDragToolFlags_NoFit, ImPlotDragToolFlags_NoInputs, ImPlotDragToolFlags_None, ImPlotFlags_CanvasOnly, PlotLine(), ImGui::SameLine(), SetNextLineStyle(), SetupAxes(), SetupAxesLimits(), x, and y.
Referenced by ShowDemoWindow().
Demo_DragRects()
void ImPlot::Demo_DragRects ()
Definition at line 1513 of file implot_demo.cpp.
References BeginPlot(), ImGui::BulletText(), ImGui::CheckboxFlags(), ImPlotStyle::Colors, DragRect(), EndPlot(), flags, GetStyle(), ImGui::GetTextLineHeight(), ImGuiCond_Always, ImPlotAxisFlags_NoDecorations, ImPlotAxisFlags_NoTickLabels, ImPlotCol_PlotBg, ImPlotDragToolFlags_NoCursors, ImPlotDragToolFlags_NoFit, ImPlotDragToolFlags_NoInputs, ImPlotDragToolFlags_None, ImPlotFlags_CanvasOnly, ImPlotRange::Max, ImPlotRange::Min, PlotLine(), PopStyleColor(), PushStyleColor(), ImGui::SameLine(), SetupAxes(), SetupAxesLimits(), ImGui::Text(), ImPlotRect::X, and ImPlotRect::Y.
Referenced by ShowDemoWindow().
Demo_EqualAxes()
void ImPlot::Demo_EqualAxes ()
Definition at line 1226 of file implot_demo.cpp.
References BeginPlot(), ImGui::BulletText(), EndPlot(), ImAxis_X2, ImAxis_Y2, ImPlotAxisFlags_AuxDefault, ImPlotFlags_Equal, PI, PlotLine(), SetAxes(), and SetupAxis().
Referenced by ShowDemoWindow().
Demo_ErrorBars()
void ImPlot::Demo_ErrorBars ()
Definition at line 551 of file implot_demo.cpp.
References BeginPlot(), EndPlot(), GetColormapColor(), ImPlotCol_ErrorBar, ImPlotErrorBarsFlags_Horizontal, ImPlotMarker_Square, PlotBars(), PlotErrorBars(), PlotLine(), PlotScatter(), PopStyleColor(), PushStyleColor(), SetNextErrorBarStyle(), SetNextMarkerStyle(), SetupAxesLimits(), and xs.
Referenced by ShowDemoWindow().
Demo_FilledLinePlots()
void ImPlot::Demo_FilledLinePlots ()
Definition at line 313 of file implot_demo.cpp.
References BeginPlot(), ImGui::Checkbox(), ImGui::DragFloat(), EndPlot(), flags, float(), ImPlotStyleVar_FillAlpha, PlotLine(), PlotShaded(), PopStyleVar(), PushStyleVar(), ImGui::RadioButton(), RandomRange(), ImGui::SameLine(), ImGui::SetNextItemWidth(), SetupAxes(), and SetupAxesLimits().
Referenced by ShowDemoWindow().
Demo_Heatmaps()
void ImPlot::Demo_Heatmaps ()
Definition at line 646 of file implot_demo.cpp.
References BeginPlot(), BustColorCache(), ImGui::CheckboxFlags(), ColormapButton(), ColormapScale(), ImGui::DragFloatRange2(), EndPlot(), GetColormapCount(), GetColormapName(), ImGui::GetTextLineHeight(), ImGui::GetTime(), ImAxis_X1, ImAxis_Y1, ImPlotAxisFlags_Lock, ImPlotAxisFlags_NoDecorations, ImPlotAxisFlags_NoGridLines, ImPlotAxisFlags_NoTickMarks, ImPlotColormap_Viridis, ImPlotFlags_NoLegend, ImPlotFlags_NoMouseText, ImPlotHeatmapFlags_ColMajor, ImGui::LabelText(), PlotHeatmap(), PopColormap(), PushColormap(), RandomRange(), ImGui::SameLine(), ImGui::SetNextItemWidth(), SetupAxes(), SetupAxesLimits(), and SetupAxisTicks().
Referenced by ShowDemoWindow().
Demo_Help()
void ImPlot::Demo_Help ()
Definition at line 190 of file implot_demo.cpp.
References ImGui::BulletText(), ImGui::GetIO(), ImGuiBackendFlags_RendererHasVtxOffset, ImGui::Indent(), ImGui::Separator(), ShowUserGuide(), ImGui::Text(), and ImGui::Unindent().
Referenced by ShowDemoWindow().
Demo_Histogram()
void ImPlot::Demo_Histogram ()
Definition at line 713 of file implot_demo.cpp.
References BeginPlot(), bins, ImGui::Checkbox(), ImGui::CheckboxFlags(), ImPlot::NormalDistribution< N >::Data, ImGui::DragFloat2(), EndPlot(), IMPLOT_AUTO_COL, ImPlotAxisFlags_AutoFit, ImPlotBin_Rice, ImPlotBin_Scott, ImPlotBin_Sqrt, ImPlotBin_Sturges, ImPlotHistogramFlags_Cumulative, ImPlotHistogramFlags_Density, ImPlotHistogramFlags_Horizontal, ImPlotHistogramFlags_NoOutliers, PlotHistogram(), PlotLine(), ImGui::RadioButton(), range, ImGui::SameLine(), SetNextFillStyle(), ImGui::SetNextItemWidth(), SetupAxes(), ImGui::SliderInt(), x, and y.
Referenced by ShowDemoWindow().
Demo_Histogram2D()
void ImPlot::Demo_Histogram2D ()
Definition at line 778 of file implot_demo.cpp.
References BeginPlot(), ImGui::CheckboxFlags(), ColormapScale(), count, ImPlot::NormalDistribution< N >::Data, EndPlot(), flags, ImGui::GetContentRegionAvail(), ImGui::GetStyle(), ImPlotAxisFlags_AutoFit, ImPlotAxisFlags_Foreground, ImPlotHistogramFlags_Density, max_count, PlotHistogram2D(), PopColormap(), PushColormap(), ImGui::SameLine(), SetupAxes(), SetupAxesLimits(), ImGui::SliderInt(), ImGui::SliderInt2(), and x.
Referenced by ShowDemoWindow().
Demo_Images()
void ImPlot::Demo_Images ()
Definition at line 864 of file implot_demo.cpp.
References BeginPlot(), ImGui::BulletText(), ImGui::ColorEdit4(), EndPlot(), ImGui::GetIO(), PlotImage(), ImGui::SliderFloat2(), ImVec2::x, and ImVec4::x.
Referenced by ShowDemoWindow().
Demo_InfiniteLines()
void ImPlot::Demo_InfiniteLines ()
Definition at line 600 of file implot_demo.cpp.
References BeginPlot(), EndPlot(), ImPlotAxisFlags_NoInitialFit, ImPlotInfLinesFlags_Horizontal, PlotInfLines(), and SetupAxes().
Referenced by ShowDemoWindow().
Demo_LegendOptions()
void ImPlot::Demo_LegendOptions ()
Definition at line 1390 of file implot_demo.cpp.
References BeginPlot(), CHECKBOX_FLAG, ImGui::CheckboxFlags(), data1, data2, EndPlot(), flags, GetStyle(), ImPlotLegendFlags_Horizontal, ImPlotLegendFlags_Outside, ImPlotLegendFlags_Reverse, ImPlotLegendFlags_Sort, ImPlotLocation_East, ImPlotLocation_North, ImPlotLocation_South, ImPlotLocation_West, PlotDummy(), PlotLineG(), ImGui::SameLine(), MyImPlot::SawWave(), SetupLegend(), ImGui::SliderFloat2(), and ImGui::SliderInt().
Referenced by ShowDemoWindow().
Demo_LegendPopups()
void ImPlot::Demo_LegendPopups ()
Definition at line 2073 of file implot_demo.cpp.
References BeginLegendPopup(), BeginPlot(), ImGui::BulletText(), ImGui::Checkbox(), ImGui::ColorEdit3(), EndLegendPopup(), EndPlot(), frequency, ImPlotMarker_Square, ImPlotStyleVar_FillAlpha, PlotBars(), PlotLine(), PlotShaded(), PopStyleVar(), PushStyleVar(), ImGui::Separator(), SetNextFillStyle(), SetNextLineStyle(), SetNextMarkerStyle(), SetupAxesLimits(), ImGui::SliderFloat(), and ImVec4::x.
Referenced by ShowDemoWindow().
Demo_LinePlots()
void ImPlot::Demo_LinePlots ()
Definition at line 291 of file implot_demo.cpp.
References BeginPlot(), EndPlot(), ImGui::GetTime(), ImPlotLineFlags_Segments, ImPlotMarker_Circle, PlotLine(), SetNextMarkerStyle(), and SetupAxes().
Referenced by ShowDemoWindow().
Demo_LinkedAxes()
void ImPlot::Demo_LinkedAxes ()
Definition at line 1178 of file implot_demo.cpp.
References BeginAlignedPlots(), BeginPlot(), ImGui::Checkbox(), data, ImGui::DragScalarN(), EndAlignedPlots(), EndPlot(), ImAxis_X1, ImAxis_Y1, ImGuiDataType_Double, ImPlotRange::Max, ImPlotRange::Min, PlotLine(), ImGui::SameLine(), SetupAxisLinks(), ImPlotRect::X, and ImPlotRect::Y.
Referenced by ShowDemoWindow().
Demo_LogScale()
void ImPlot::Demo_LogScale ()
Definition at line 1008 of file implot_demo.cpp.
References BeginPlot(), EndPlot(), ImAxis_X1, ImPlotScale_Log10, PlotLine(), SetupAxesLimits(), SetupAxisScale(), and xs.
Referenced by ShowDemoWindow().
Demo_MarkersAndText()
void ImPlot::Demo_MarkersAndText ()
Definition at line 938 of file implot_demo.cpp.
References BeginPlot(), ImGui::DragFloat(), EndPlot(), GetStyle(), IMPLOT_AUTO_COL, ImPlotAxisFlags_NoDecorations, ImPlotCol_InlayText, ImPlotFlags_CanvasOnly, ImPlotMarker_COUNT, ImPlotTextFlags_Vertical, ImPlotStyle::MarkerSize, ImPlotStyle::MarkerWeight, PlotLine(), PlotText(), ImGui::PopID(), PopStyleColor(), ImGui::PushID(), PushStyleColor(), SetNextMarkerStyle(), SetupAxes(), SetupAxesLimits(), xs, and ys.
Referenced by ShowDemoWindow().
Demo_MultipleAxes()
void ImPlot::Demo_MultipleAxes ()
Definition at line 1120 of file implot_demo.cpp.
References BeginPlot(), ImGui::BulletText(), ImGui::Checkbox(), EndPlot(), ImAxis_X1, ImAxis_X2, ImAxis_Y1, ImAxis_Y2, ImAxis_Y3, ImPlotAxisFlags_AuxDefault, PlotLine(), ImGui::SameLine(), SetAxes(), SetupAxes(), SetupAxesLimits(), SetupAxis(), SetupAxisLimits(), and xs.
Referenced by ShowDemoWindow().
Demo_NaNValues()
void ImPlot::Demo_NaNValues ()
Definition at line 983 of file implot_demo.cpp.
References BeginPlot(), ImGui::Checkbox(), ImGui::CheckboxFlags(), data1, data2, EndPlot(), flags, ImPlotLineFlags_SkipNaN, ImPlotMarker_Square, PlotBars(), PlotLine(), ImGui::SameLine(), and SetNextMarkerStyle().
Referenced by ShowDemoWindow().
Demo_OffsetAndStride()
void ImPlot::Demo_OffsetAndStride ()
Definition at line 1909 of file implot_demo.cpp.
References BeginPlot(), ImGui::BulletText(), EndPlot(), ImPlotColormap_Jet, ImPlotFlags_Equal, offset, PlotLine(), PopColormap(), PushColormap(), and ImGui::SliderInt().
Referenced by ShowDemoWindow().
Demo_PieCharts()
void ImPlot::Demo_PieCharts ()
Definition at line 612 of file implot_demo.cpp.
References BeginPlot(), CHECKBOX_FLAG, data1, data2, ImGui::DragFloat4(), EndPlot(), flags, ImGui::GetTextLineHeight(), ImPlotAxisFlags_NoDecorations, ImPlotColormap_Pastel, ImPlotFlags_Equal, ImPlotFlags_NoMouseText, ImPlotPieChartFlags_Exploding, ImPlotPieChartFlags_IgnoreHidden, ImPlotPieChartFlags_Normalize, PlotPieChart(), PopColormap(), PushColormap(), ImGui::SameLine(), ImGui::SetNextItemWidth(), SetupAxes(), and SetupAxesLimits().
Referenced by ShowDemoWindow().
Demo_Querying()
void ImPlot::Demo_Querying ()
Definition at line 1589 of file implot_demo.cpp.
References BeginPlot(), ImGui::BulletText(), ImGui::Button(), CancelPlotSelection(), data, DragRect(), EndPlot(), FindCentroid(), GetInputMap(), ImGui::GetIO(), GetPlotLimits(), GetPlotMousePos(), GetPlotSelection(), ImPlotMarker_Square, ImGui::IsMouseClicked(), IsPlotHovered(), IsPlotSelected(), PlotScatter(), ImVector< T >::push_back(), RandomRange(), SetNextMarkerStyle(), SetupAxesLimits(), ImVector< T >::shrink(), ImVector< T >::size(), ImPlotPoint::x, x, X, ImPlotPoint::y, and y.
Referenced by ShowDemoWindow().
Demo_RealtimePlots()
void ImPlot::Demo_RealtimePlots ()
Definition at line 893 of file implot_demo.cpp.
References ImPlot::ScrollingBuffer::AddPoint(), ImPlot::RollingBuffer::AddPoint(), BeginPlot(), ImGui::BulletText(), ImPlot::ScrollingBuffer::Data, ImPlot::RollingBuffer::Data, ImGuiIO::DeltaTime, EndPlot(), flags, ImGui::GetIO(), ImGui::GetMousePos(), ImGui::GetTextLineHeight(), ImAxis_X1, ImAxis_Y1, ImGuiCond_Always, IMPLOT_AUTO_COL, ImPlotAxisFlags_NoTickLabels, ImPlot::ScrollingBuffer::Offset, PlotLine(), PlotShaded(), SetNextFillStyle(), SetupAxes(), SetupAxisLimits(), ImVector< T >::size(), ImGui::SliderFloat(), ImPlot::RollingBuffer::Span, ImVec2::x, and ImVec2::y.
Referenced by ShowDemoWindow().
Demo_ScatterPlots()
void ImPlot::Demo_ScatterPlots ()
Definition at line 396 of file implot_demo.cpp.
References BeginPlot(), EndPlot(), float(), GetColormapColor(), IMPLOT_AUTO, ImPlotMarker_Square, ImPlotStyleVar_FillAlpha, PlotScatter(), PopStyleVar(), PushStyleVar(), and SetNextMarkerStyle().
Referenced by ShowDemoWindow().
Demo_ShadedPlots()
void ImPlot::Demo_ShadedPlots ()
Definition at line 367 of file implot_demo.cpp.
References BeginPlot(), ImGui::DragFloat(), EndPlot(), ImPlotLegendFlags_Reverse, ImPlotLocation_NorthWest, ImPlotStyleVar_FillAlpha, PlotLine(), PlotShaded(), PopStyleVar(), PushStyleVar(), RandomRange(), SetupLegend(), xs, and ys.
Referenced by ShowDemoWindow().
Demo_StairstepPlots()
void ImPlot::Demo_StairstepPlots ()
Definition at line 421 of file implot_demo.cpp.
References BeginPlot(), CHECKBOX_FLAG, EndPlot(), flags, IMPLOT_AUTO_COL, ImPlotCol_Line, ImPlotMarker_Circle, ImPlotStairsFlags_PreStep, ImPlotStairsFlags_Shaded, PlotLine(), PlotStairs(), PopStyleColor(), PushStyleColor(), SetNextFillStyle(), SetNextMarkerStyle(), SetupAxes(), and SetupAxesLimits().
Referenced by ShowDemoWindow().
Demo_StemPlots()
void ImPlot::Demo_StemPlots ()
Definition at line 581 of file implot_demo.cpp.
References BeginPlot(), EndPlot(), ImAxis_X1, ImAxis_Y1, ImPlotMarker_Circle, PlotStems(), SetNextMarkerStyle(), SetupAxisLimits(), and xs.
Referenced by ShowDemoWindow().
Demo_SubplotAxisLinking()
void ImPlot::Demo_SubplotAxisLinking ()
Definition at line 1366 of file implot_demo.cpp.
References BeginPlot(), BeginSubplots(), ImGui::CheckboxFlags(), EndPlot(), EndSubplots(), flags, ImPlotSubplotFlags_LinkAllX, ImPlotSubplotFlags_LinkAllY, ImPlotSubplotFlags_LinkCols, ImPlotSubplotFlags_LinkRows, PlotLineG(), SetupAxesLimits(), and SinewaveGetter().
Referenced by ShowDemoWindow().
Demo_SubplotItemSharing()
void ImPlot::Demo_SubplotItemSharing ()
Definition at line 1322 of file implot_demo.cpp.
References ImGui::AcceptDragDropPayload(), BeginDragDropSourceItem(), BeginDragDropTargetPlot(), BeginPlot(), BeginSubplots(), ImGui::BulletText(), ImGui::CheckboxFlags(), EndDragDropSource(), EndDragDropTarget(), EndPlot(), EndSubplots(), flags, GetLastItemColor(), ImPlotLegendFlags_Horizontal, ImPlotLegendFlags_Sort, ImPlotLocation_South, ImPlotSubplotFlags_ColMajor, ImPlotSubplotFlags_ShareItems, ItemIcon(), PlotLineG(), ImGui::SameLine(), ImGui::SetDragDropPayload(), SetupLegend(), SinewaveGetter(), and ImGui::TextUnformatted().
Referenced by ShowDemoWindow().
Demo_SubplotsSizing()
void ImPlot::Demo_SubplotsSizing ()
Definition at line 1283 of file implot_demo.cpp.
References BeginPlot(), BeginSubplots(), ImGui::CheckboxFlags(), ImGui::DragScalarN(), EndPlot(), EndSubplots(), flags, ImGuiDataType_Float, ImPlotAxisFlags_NoDecorations, ImPlotColormap_Jet, ImPlotFlags_NoLegend, ImPlotSubplotFlags_NoLegend, ImPlotSubplotFlags_NoResize, ImPlotSubplotFlags_NoTitle, ImPlotSubplotFlags_ShareItems, PlotLineG(), SampleColormap(), SetNextLineStyle(), SetupAxes(), SinewaveGetter(), ImGui::SliderInt(), and ImGui::TextColored().
Referenced by ShowDemoWindow().
Demo_SymmetricLogScale()
void ImPlot::Demo_SymmetricLogScale ()
Definition at line 1029 of file implot_demo.cpp.
References BeginPlot(), EndPlot(), ImAxis_X1, ImPlotScale_SymLog, PlotLine(), SetupAxisScale(), and xs.
Referenced by ShowDemoWindow().
Demo_Tables()
void ImPlot::Demo_Tables ()
Definition at line 1868 of file implot_demo.cpp.
References ImGui::BeginTable(), ImGui::BulletText(), ImGui::Checkbox(), data, ImGui::EndTable(), flags, GetColormapColor(), ImGuiTableColumnFlags_WidthFixed, ImGuiTableFlags_BordersOuter, ImGuiTableFlags_BordersV, ImGuiTableFlags_Reorderable, ImGuiTableFlags_Resizable, ImGuiTableFlags_RowBg, ImPlotColormap_Cool, offset, PopColormap(), ImGui::PopID(), PushColormap(), ImGui::PushID(), RandomRange(), MyImPlot::Sparkline(), ImGui::TableHeadersRow(), ImGui::TableNextRow(), ImGui::TableSetColumnIndex(), ImGui::TableSetupColumn(), and ImGui::Text().
Referenced by ShowDemoWindow().
Demo_Tags()
void ImPlot::Demo_Tags ()
Definition at line 1673 of file implot_demo.cpp.
References BeginPlot(), ImGui::Checkbox(), DragLineY(), EndPlot(), ImAxis_X2, ImAxis_Y2, ImPlotDragToolFlags_NoFit, SetAxes(), SetupAxis(), TagX(), and TagY().
Referenced by ShowDemoWindow().
Demo_TickLabels()
void ImPlot::Demo_TickLabels ()
Definition at line 1996 of file implot_demo.cpp.
References BeginPlot(), ImGui::Checkbox(), EndPlot(), ImAxis_X1, ImAxis_Y1, ImAxis_Y2, ImAxis_Y3, ImPlotAxisFlags_AuxDefault, MetricFormatter(), ImGui::SameLine(), SetupAxesLimits(), SetupAxis(), SetupAxisFormat(), and SetupAxisTicks().
Referenced by ShowDemoWindow().
Demo_TimeScale()
void ImPlot::Demo_TimeScale ()
Definition at line 1046 of file implot_demo.cpp.
References Annotation(), BeginPlot(), ImGui::BulletText(), ImGui::Button(), ImGui::Checkbox(), data, EndPlot(), GetLastItemColor(), GetPlotLimits(), GetStyle(), ImPlot::HugeTimeData::GetY(), ImAxis_X1, ImPlotScale_Time, ImPlotRange::Max, ImPlotRange::Min, PlotLine(), PlotScatter(), ImGui::SameLine(), SetupAxesLimits(), SetupAxisScale(), ImPlotRange::Size(), ImPlot::HugeTimeData::Size, and ImPlotRect::X.
Referenced by ShowDemoWindow().
DemoHeader()
void ImPlot::DemoHeader (const char * label, void(*)() demo)
Definition at line 2184 of file implot_demo.cpp.
References ImGui::TreeNodeEx(), and ImGui::TreePop().
Referenced by ShowDemoWindow().
DestroyContext()
void ImPlot::DestroyContext (ImPlotContext * ctx)
Definition at line 445 of file implot.cpp.
References GImPlot, IM_DELETE(), and SetCurrentContext().
Referenced by main(), and main().
DragFloat()
template<typename F > bool ImPlot::DragFloat (const char * , F * , float , F , F)
Definition at line 1320 of file implot.cpp.
Referenced by ShowAxisContextMenu().
DragFloat< double >()
template<> bool ImPlot::DragFloat< double > (const char * label, double * v, float v_speed, double v_min, double v_max)
Definition at line 1325 of file implot.cpp.
References ImGui::DragScalar(), and ImGuiDataType_Double.
DragFloat< float >()
template<> bool ImPlot::DragFloat< float > (const char * label, float * v, float v_speed, float v_min, float v_max)
Definition at line 1330 of file implot.cpp.
References ImGui::DragScalar(), and ImGuiDataType_Float.
DragLineX()
bool ImPlot::DragLineX (int n_id, double * value, const ImVec4 & col, float thickness, ImPlotDragToolFlags flags, bool * out_clicked, bool * out_hovered, bool * out_held)
Definition at line 3955 of file implot.cpp.
References ImDrawList::AddLine(), ImGui::ButtonBehavior(), col, ImGui::ColorConvertFloat4ToU32(), ImPlotContext::CurrentPlot, DRAG_GRAB_HALF_SIZE, FitPointX(), FitThisFrame(), flags, ImGui::GetCurrentWindow(), ImGuiWindow::GetID(), GetPlotDrawList(), GetPlotMousePos(), ImGui::GetStyleColorVec4(), GImPlot, gp, IM_ASSERT_USER_ERROR, IM_ROUND, ImGuiCol_Text, ImGuiMouseCursor_ResizeEW, ImHasFlag(), ImMax(), IMPLOT_AUTO, ImPlotDragToolFlags_Delayed, ImPlotDragToolFlags_NoCursors, ImPlotDragToolFlags_NoFit, ImPlotDragToolFlags_NoInputs, IsColorAuto(), ImGui::IsMouseDragging(), ImGui::KeepAliveID(), ImPlotStyle::MajorTickLen, ImRect::Max, ImRect::Min, ImPlotPlot::PlotRect, PlotToPixels(), PopPlotClipRect(), PushPlotClipRect(), ImGui::SetMouseCursor(), SetupLock(), ImPlotContext::Style, ImVec2::x, ImPlotPoint::x, x, and ImVec2::y.
Referenced by Demo_DragLines().
DragLineY()
bool ImPlot::DragLineY (int n_id, double * value, const ImVec4 & col, float thickness, ImPlotDragToolFlags flags, bool * out_clicked, bool * out_hovered, bool * out_held)
Definition at line 4010 of file implot.cpp.
References ImDrawList::AddLine(), ImGui::ButtonBehavior(), col, ImGui::ColorConvertFloat4ToU32(), ImPlotContext::CurrentPlot, DRAG_GRAB_HALF_SIZE, FitPointY(), FitThisFrame(), flags, ImGui::GetCurrentWindow(), ImGuiWindow::GetID(), GetPlotDrawList(), GetPlotMousePos(), ImGui::GetStyleColorVec4(), GImPlot, gp, IM_ASSERT_USER_ERROR, IM_ROUND, ImGuiCol_Text, ImGuiMouseCursor_ResizeNS, ImHasFlag(), ImMax(), IMPLOT_AUTO, ImPlotDragToolFlags_Delayed, ImPlotDragToolFlags_NoCursors, ImPlotDragToolFlags_NoFit, ImPlotDragToolFlags_NoInputs, IsColorAuto(), ImGui::IsMouseDragging(), ImGui::KeepAliveID(), ImPlotStyle::MajorTickLen, ImRect::Max, ImRect::Min, ImPlotPlot::PlotRect, PlotToPixels(), ImGui::PopID(), PopPlotClipRect(), ImGui::PushID(), PushPlotClipRect(), ImGui::SetMouseCursor(), SetupLock(), ImPlotContext::Style, ImVec2::x, ImVec2::y, ImPlotPoint::y, and y.
Referenced by Demo_DragLines(), and Demo_Tags().
DragPoint()
bool ImPlot::DragPoint (int n_id, double * x, double * y, const ImVec4 & col, float radius, ImPlotDragToolFlags flags, bool * out_clicked, bool * out_hovered, bool * out_held)
Definition at line 3906 of file implot.cpp.
References ImDrawList::AddCircleFilled(), ImGui::ButtonBehavior(), col, ImGui::ColorConvertFloat4ToU32(), ImPlotContext::CurrentPlot, DRAG_GRAB_HALF_SIZE, FitPoint(), FitThisFrame(), flags, ImGui::GetCurrentWindow(), ImGuiWindow::GetID(), GetPlotDrawList(), GetPlotMousePos(), ImGui::GetStyleColorVec4(), GImPlot, IM_ASSERT_USER_ERROR, ImGuiCol_Text, ImGuiMouseCursor_Hand, ImHasFlag(), ImMax(), IMPLOT_AUTO, ImPlotDragToolFlags_Delayed, ImPlotDragToolFlags_NoCursors, ImPlotDragToolFlags_NoFit, ImPlotDragToolFlags_NoInputs, IsColorAuto(), ImGui::IsMouseDragging(), ImGui::KeepAliveID(), PlotToPixels(), ImGui::PopID(), PopPlotClipRect(), ImGui::PushID(), PushPlotClipRect(), radius, ImGui::SetMouseCursor(), SetupLock(), ImVec2::x, ImPlotPoint::x, x, ImVec2::y, ImPlotPoint::y, and y.
Referenced by Demo_DragPoints().
DragRect() [1/2]
bool ImPlot::DragRect (int id, ImPlotRect * bounds, const ImVec4 & col, ImPlotDragToolFlags flags, bool * out_clicked, bool * out_hovered, bool * out_held)
Definition at line 4212 of file implot.cpp.
References col, DragRect(), flags, ImPlotRange::Max, ImPlotRange::Min, ImPlotRect::X, and ImPlotRect::Y.
DragRect() [2/2]
bool ImPlot::DragRect (int n_id, double * x_min, double * y_min, double * x_max, double * y_max, const ImVec4 & col, ImPlotDragToolFlags flags, bool * out_clicked, bool * out_hovered, bool * out_held)
Definition at line 4066 of file implot.cpp.
References ImDrawList::AddCircleFilled(), ImDrawList::AddRect(), ImDrawList::AddRectFilled(), ImGui::ButtonBehavior(), col, ImGui::ColorConvertFloat4ToU32(), ImRect::Contains(), ImPlotContext::CurrentPlot, DRAG_GRAB_HALF_SIZE, ImRect::Expand(), FitPoint(), FitThisFrame(), flags, ImGui::GetCurrentWindow(), ImGuiWindow::GetID(), ImGui::GetIO(), ImGui::GetMousePos(), GetPlotDrawList(), GetPlotLimits(), GetPlotMousePos(), ImGui::GetStyleColorVec4(), GImPlot, IM_ASSERT_USER_ERROR, ImGuiCol_Text, ImGuiMouseCursor_ResizeAll, ImGuiMouseCursor_ResizeEW, ImGuiMouseCursor_ResizeNESW, ImGuiMouseCursor_ResizeNS, ImGuiMouseCursor_ResizeNWSE, ImHasFlag(), ImMax(), ImMin(), IMPLOT_AUTO, ImPlotDragToolFlags_Delayed, ImPlotDragToolFlags_NoCursors, ImPlotDragToolFlags_NoFit, ImPlotDragToolFlags_NoInputs, IsColorAuto(), ImGui::IsMouseClicked(), ImGui::IsMouseDoubleClicked(), ImGui::IsMouseDown(), ImGui::IsMouseDragging(), ImGui::KeepAliveID(), ImRect::Max, ImPlotRange::Max, ImRect::Min, ImPlotRange::Min, PixelsToPlot(), PlotToPixels(), ImGui::PopID(), PopPlotClipRect(), ImGui::PushID(), PushPlotClipRect(), ImGui::SetMouseCursor(), SetupLock(), ImVec4::w, ImVec2::x, ImPlotPoint::x, ImPlotRect::X, x, ImVec2::y, ImPlotPoint::y, ImPlotRect::Y, and y.
Referenced by Demo_DragRects(), Demo_Querying(), and DragRect().
EndAlignedPlots()
void ImPlot::EndAlignedPlots ()
Definition at line 4378 of file implot.cpp.
References ImPlotContext::CurrentAlignmentH, ImPlotContext::CurrentAlignmentV, ImPlotAlignmentData::End(), GImPlot, gp, IM_ASSERT_USER_ERROR, and ResetCtxForNextAlignedPlots().
Referenced by Demo_LinkedAxes().
EndDisabledControls()
void ImPlot::EndDisabledControls (bool cond) inline
Definition at line 1341 of file implot.cpp.
References ImGui::PopItemFlag(), and ImGui::PopStyleVar().
Referenced by ShowAxisContextMenu(), ShowDatePicker(), ShowPlotContextMenu(), and ShowSubplotsContextMenu().
EndDragDropSource()
void ImPlot::EndDragDropSource ()
Definition at line 4348 of file implot.cpp.
References ImGui::EndDragDropSource(), and SetupLock().
Referenced by Demo_DragAndDrop(), and Demo_SubplotItemSharing().
EndDragDropTarget()
void ImPlot::EndDragDropTarget ()
Definition at line 4313 of file implot.cpp.
References ImGui::EndDragDropTarget(), and SetupLock().
Referenced by Demo_DragAndDrop(), and Demo_SubplotItemSharing().
EndItem()
void ImPlot::EndItem ()
Definition at line 480 of file implot_items.cpp.
References ImPlotContext::CurrentItem, GImPlot, gp, ImPlotContext::NextItemData, PopPlotClipRect(), ImPlotContext::PreviousItem, and ImPlotNextItemData::Reset().
Referenced by if(), if(), if(), PlotBarsHEx(), PlotBarsVEx(), MyImPlot::PlotCandlestick(), PlotDummy(), PlotErrorBarsHEx(), PlotErrorBarsVEx(), PlotHeatmap(), PlotImage(), PlotLineEx(), PlotScatterEx(), PlotShadedEx(), PlotStairsEx(), and PlotStemsEx().
EndLegendPopup()
void ImPlot::EndLegendPopup ()
Definition at line 4245 of file implot.cpp.
References ImGui::EndPopup(), and SetupLock().
Referenced by Demo_LegendPopups().
EndPlot()
void ImPlot::EndPlot ()
Definition at line 2767 of file implot.cpp.
References ImDrawList::AddLine(), ImDrawList::AddRect(), ImDrawList::AddRectFilled(), ImDrawList::AddText(), AddTextCentered(), ImDrawList::AddTriangleFilled(), ImPlotStyle::AnnotationPadding, ImPlotAnnotationCollection::Annotations, ImPlotContext::Annotations, AnyAxesHeld(), ImGuiTextBuffer::append(), ImPlotAxis::ApplyFit(), ImPlotPlot::Axes, ImPlotTag::Axis, ImGui::BeginPopup(), ImGuiTextBuffer::Buf, ImGui::ButtonBehavior(), ImGuiTextBuffer::c_str(), CalcLegendSize(), ImGui::CalcTextSize(), ImPlotPlot::CanvasRect, ImPlotAnnotation::Clamp, ClampLabelPos(), ClampLegendRect(), col, ImPlotAnnotation::ColorBg, ImPlotTag::ColorBg, ImPlotAnnotation::ColorFg, ImPlotTag::ColorFg, ImPlotAxis::ColorHov, ImPlotAxis::ColorMaj, ImPlotAxis::ColorMin, ImPlotAxis::ColorTick, ImRect::Contains(), ImPlotRange::Contains(), ImPlotContext::CurrentItems, ImPlotContext::CurrentPlot, ImPlotContext::CurrentSubplot, ImGuiContext::CurrentWindow, ImPlotAxis::Datum1, ImGuiWindow::DrawList, ImGuiTextBuffer::empty(), ImPlotAxis::Enabled, ImGui::EndPopup(), ImRect::Expand(), ImPlotStyle::FitPadding, ImPlotAxis::FitThisFrame, ImPlotPlot::FitThisFrame, ImPlotAxis::Flags, ImPlotLegend::Flags, ImPlotPlot::Flags, ImGuiWindow::FontRefSize, Formatter_Default(), ImPlotPlot::FrameRect, ImPlotAxis::GetAspect(), ImPlotPlot::GetAxisLabel(), ImRect::GetBL(), ImRect::GetBR(), ImRect::GetCenter(), ImGui::GetCurrentWindow(), ImGui::GetIO(), ImPlotItemGroup::GetItemByIndex(), ImPlotItemGroup::GetItemCount(), ImPlotItemGroup::GetLegendCount(), GetLocationPos(), ImRect::GetSize(), GetStyleColorU32(), GetStyleColorVec4(), ImPlotAnnotationCollection::GetText(), ImPlotTagCollection::GetText(), ImPlotPlot::GetTitle(), ImRect::GetTL(), ImRect::GetTR(), GImGui, GImPlot, gp, ImPlotAxis::HasGridLines(), ImPlotAxis::HasLabel(), ImPlotAxis::HasMenus(), ImPlotAxis::HasTickMarks(), ImPlotPlot::HasTitle(), ImPlotAxis::Held, ImPlotLegend::Held, ImPlotPlot::Held, ImPlotAxis::Hovered, ImPlotLegend::Hovered, ImPlotPlot::Hovered, ImPlotItemGroup::ID, ImPlotPlot::ID, IM_ASSERT_USER_ERROR, IM_ROUND, ImAxis_COUNT, ImAxis_X1, ImAxis_Y1, ImClamp(), ImDrawFlags_RoundCornersAll, ImFlipFlag(), ImFloor(), ImGuiButtonFlags_AllowOverlap, ImGuiButtonFlags_FlattenChildren, ImGuiButtonFlags_MouseButtonLeft, ImGuiButtonFlags_MouseButtonMiddle, ImGuiButtonFlags_MouseButtonRight, ImGuiButtonFlags_PressedOnClick, ImGuiButtonFlags_PressedOnDoubleClick, ImGuiKey_MouseWheelY, ImGuiMouseCursor_None, ImHasFlag(), ImLengthSqr(), ImMax(), ImMin(), IMPLOT_LABEL_FORMAT, IMPLOT_LABEL_MAX_SIZE, IMPLOT_NUM_X_AXES, IMPLOT_NUM_Y_AXES, ImPlotAxisFlags_NoSideSwitch, ImPlotAxisFlags_Opposite, ImPlotCol_Crosshairs, ImPlotCol_InlayText, ImPlotCol_LegendBg, ImPlotCol_LegendBorder, ImPlotCol_PlotBorder, ImPlotCol_Selection, ImPlotCol_TitleText, ImPlotFlags_Crosshairs, ImPlotFlags_Equal, ImPlotFlags_NoLegend, ImPlotFlags_NoMenus, ImPlotFlags_NoMouseText, ImPlotLegendFlags_Horizontal, ImPlotLegendFlags_NoMenus, ImPlotLegendFlags_Outside, ImPlotMouseTextFlags_NoAuxAxes, ImPlotMouseTextFlags_NoFormat, ImPlotMouseTextFlags_ShowAlways, ImPlotPlot::Initialized, ImPlotAxis::IsForeground(), ImPlotAxis::IsOpposite(), ImGui::IsWindowHovered(), ImPlotPlot::Items, ImGui::KeepAliveID(), LabelAxisValue(), ImPlotStyle::LabelPadding, ImPlotItemGroup::Legend, ImPlotItem::LegendHovered, ImPlotStyle::LegendInnerPadding, ImPlotStyle::LegendPadding, ImPlotStyle::LegendSpacing, ImPlotTick::Level, ImPlotLegend::Location, ImPlotTick::Major, ImPlotStyle::MajorGridSize, ImPlotStyle::MajorTickLen, ImPlotStyle::MajorTickSize, ImRect::Max, ImRect::Min, ImPlotStyle::MinorGridSize, ImPlotStyle::MinorTickLen, ImPlotStyle::MinorTickSize, ImGuiIO::MousePos, ImPlotStyle::MousePosPadding, ImPlotContext::MousePosStringBuilder, ImPlotPlot::MouseTextFlags, ImPlotPlot::MouseTextLocation, ImGuiIO::MouseWheel, ImPlotAnnotation::Offset, ImPlotContext::OpenContextThisFrame, ImGui::OpenPopup(), ImPlotAxis::OrthoAxis, ImPlotTicker::OverrideSizeLate(), ImPlotTick::PixelPos, ImPlotAxis::PixelsToPlot(), ImPlotStyle::PlotBorderSize, ImPlotStyle::PlotPadding, ImPlotPlot::PlotRect, ImPlotAxis::PlotToPixels(), ImGui::PopClipRect(), ImGui::PopID(), PopPlotClipRect(), ImPlotAnnotation::Pos, ImGui::PushClipRect(), ImGui::PushID(), ImPlotAxis::PushLinks(), ImGui::PushOverrideID(), PushPlotClipRect(), ImPlotAxis::Range, ImPlotLegend::Rect, ImPlotLegend::RectClamped, RenderGridLinesX(), RenderGridLinesY(), RenderSelectionRect(), ResetCtxForNextPlot(), ImPlotLegend::Scroll, ImPlotItem::SeenThisFrame, ImPlotPlot::Selected, ImPlotPlot::Selecting, ImPlotPlot::SelectRect, ImGui::Separator(), ImPlotAxis::SetAspect(), ImGui::SetKeyOwner(), ImGui::SetMouseCursor(), SetupLock(), ShowAxisContextMenu(), ShowLegendContextMenu(), ShowLegendEntries(), ShowPlotContextMenu(), ImVector< T >::shrink(), ImPlotAnnotationCollection::Size, ImPlotTagCollection::Size, ImPlotContext::Style, SubplotNextCell(), ImPlotTagCollection::Tags, ImPlotContext::Tags, ImGui::Text(), ImPlotTicker::TickCount(), ImPlotAxis::Ticker, ImPlotTicker::Ticks, ImPlotTag::Value, ImPlotAxis::Vertical, ImVec4::w, ImVec2::x, ImPlotPlot::XAxis(), ImVec2::y, and ImPlotPlot::YAxis().
Referenced by Demo_Annotations(), Demo_AutoFittingData(), Demo_AxisConstraints(), Demo_BarGroups(), Demo_BarPlots(), Demo_BarStacks(), Demo_Config(), Demo_CustomDataAndGetters(), Demo_CustomPlottersAndTooltips(), Demo_CustomRendering(), Demo_CustomScale(), Demo_CustomStyles(), Demo_DigitalPlots(), Demo_DragAndDrop(), Demo_DragLines(), Demo_DragPoints(), Demo_DragRects(), Demo_EqualAxes(), Demo_ErrorBars(), Demo_FilledLinePlots(), Demo_Heatmaps(), Demo_Histogram(), Demo_Histogram2D(), Demo_Images(), Demo_InfiniteLines(), Demo_LegendOptions(), Demo_LegendPopups(), Demo_LinePlots(), Demo_LinkedAxes(), Demo_LogScale(), Demo_MarkersAndText(), Demo_MultipleAxes(), Demo_NaNValues(), Demo_OffsetAndStride(), Demo_PieCharts(), Demo_Querying(), Demo_RealtimePlots(), Demo_ScatterPlots(), Demo_ShadedPlots(), Demo_StairstepPlots(), Demo_StemPlots(), Demo_SubplotAxisLinking(), Demo_SubplotItemSharing(), Demo_SubplotsSizing(), Demo_SymmetricLogScale(), Demo_Tags(), Demo_TickLabels(), Demo_TimeScale(), main(), and MyImPlot::Sparkline().
EndSubplots()
void ImPlot::EndSubplots ()
Definition at line 3544 of file implot.cpp.
References ImDrawList::AddRect(), ImDrawList::AddRectFilled(), ImGui::BeginPopup(), ImGui::ButtonBehavior(), CalcLegendSize(), ClampLegendRect(), ImPlotSubplot::ColAlignmentData, ImPlotSubplot::Cols, ImRect::Contains(), ImPlotContext::CurrentItems, ImPlotContext::CurrentSubplot, ImGuiContext::CurrentWindow, ImGuiWindowTempData::CursorPos, ImGuiWindow::DC, ImGui::Dummy(), ImGui::EndPopup(), ImPlotLegend::Flags, ImPlotSubplot::Flags, ImGuiWindow::FontRefSize, ImPlotSubplot::FrameHovered, ImPlotSubplot::FrameRect, ImGui::GetCurrentWindow(), ImGui::GetIO(), ImPlotItemGroup::GetItemByIndex(), ImPlotItemGroup::GetItemCount(), ImPlotItemGroup::GetLegendCount(), GetLocationPos(), ImRect::GetSize(), GetStyleColorU32(), ImGui::GetWindowDrawList(), GImGui, GImPlot, gp, ImPlotLegend::Held, ImPlotLegend::Hovered, ImPlotItemGroup::ID, IM_ASSERT_USER_ERROR, ImClamp(), ImFlipFlag(), ImFloor(), ImGuiButtonFlags_AllowOverlap, ImGuiButtonFlags_FlattenChildren, ImGuiButtonFlags_MouseButtonLeft, ImGuiButtonFlags_MouseButtonMiddle, ImGuiButtonFlags_MouseButtonRight, ImGuiButtonFlags_PressedOnClick, ImGuiButtonFlags_PressedOnDoubleClick, ImGuiKey_MouseWheelY, ImHasFlag(), ImMin(), ImPlotCol_LegendBg, ImPlotCol_LegendBorder, ImPlotFlags_NoLegend, ImPlotLegendFlags_Horizontal, ImPlotLegendFlags_NoMenus, ImPlotSubplotFlags_NoLegend, ImPlotSubplotFlags_NoMenus, ImPlotSubplotFlags_ShareItems, ImPlotContext::InputMap, ImPlotSubplot::Items, ImGui::KeepAliveID(), ImPlotItemGroup::Legend, ImPlotItem::LegendHovered, ImPlotStyle::LegendInnerPadding, ImPlotStyle::LegendSpacing, ImPlotLegend::Location, ImRect::Max, ImPlotInputMap::Menu, ImRect::Min, ImGuiIO::MouseReleased, ImGuiIO::MouseWheel, ImGui::OpenPopup(), ImPlotStyle::PlotPadding, ImGui::PopClipRect(), ImGui::PopID(), PopStyleColor(), PopStyleVar(), ImGui::PopStyleVar(), ImGui::PushClipRect(), ImPlotLegend::Rect, ImPlotLegend::RectClamped, ResetCtxForNextSubplot(), ImPlotSubplot::RowAlignmentData, ImPlotSubplot::Rows, ImPlotLegend::Scroll, ImPlotItem::SeenThisFrame, ImGui::Separator(), ImGui::SetKeyOwner(), ShowLegendContextMenu(), ShowLegendEntries(), ImPlotContext::Style, ImGui::Text(), ImVec2::x, and ImVec2::y.
Referenced by Demo_SubplotAxisLinking(), Demo_SubplotItemSharing(), and Demo_SubplotsSizing().
FillRange()
template<typename T > void ImPlot::FillRange (ImVector< T > & buffer, int n, T vmin, T vmax)
Definition at line 1532 of file implot_internal.h.
References ImVector< T >::resize().
Referenced by SetupAxisTicks().
FindCentroid()
ImPlotPoint ImPlot::FindCentroid (const ImVector< ImPlotPoint > & data, const ImPlotRect & bounds, int & cnt)
Definition at line 1565 of file implot_demo.cpp.
References ImPlotRect::Contains(), data, ImPlotRange::Max, ImPlotRange::Min, ImPlotPoint::x, ImPlotRect::X, ImPlotPoint::y, and ImPlotRect::Y.
Referenced by Demo_Querying().
FitPoint()
static void ImPlot::FitPoint (const ImPlotPoint & p) inline static
Definition at line 1417 of file implot_internal.h.
References ImPlotPlot::Axes, ImPlotPlot::CurrentX, ImPlotPlot::CurrentY, ImPlotAxis::ExtendFitWith(), GetCurrentPlot(), ImPlotPoint::x, and ImPlotPoint::y.
Referenced by DragPoint(), DragRect(), MyImPlot::PlotCandlestick(), and PlotText().
FitPointX()
static void ImPlot::FitPointX (double x) inline static
Definition at line 1403 of file implot_internal.h.
References ImPlotPlot::Axes, ImPlotPlot::CurrentX, ImPlotAxis::ExtendFit(), GetCurrentPlot(), and x.
Referenced by DragLineX().
FitPointY()
static void ImPlot::FitPointY (double y) inline static
Definition at line 1410 of file implot_internal.h.
References ImPlotPlot::Axes, ImPlotPlot::CurrentY, ImPlotAxis::ExtendFit(), GetCurrentPlot(), and y.
Referenced by DragLineY().
FitThisFrame()
static bool ImPlot::FitThisFrame () inline static
Definition at line 1398 of file implot_internal.h.
References ImPlotContext::CurrentPlot, ImPlotPlot::FitThisFrame, and GImPlot.
Referenced by DragLineX(), DragLineY(), DragPoint(), DragRect(), MyImPlot::PlotCandlestick(), and PlotText().
float() [1/2]
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() ImPlot::float (double) &
float() [2/2]
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() ImPlot::float (double) const
Definition at line 2373 of file implot_items.cpp.
References ImPlot::RectC::Color, ImPlotStyle::Colormap, ImPlotContext::ColormapData, GImPlot, gp, ImPlot::RectC::HalfSize, height, ImClamp(), IMPLOT_INLINE, ImRemap01(), ImPlotColormapData::LerpTable(), ImPlot::RectC::Pos, ImPlotContext::Style, values, and width.
Referenced by ColormapScale(), Demo_FilledLinePlots(), Demo_ScatterPlots(), Locator_Time(), and PushStyleVar().
FloorTime()
IMPLOT_API ImPlotTime ImPlot::FloorTime (const ImPlotTime & t, ImPlotTimeUnit unit)
Definition at line 1026 of file implot.cpp.
References GetTime(), GImPlot, gp, ImPlotTimeUnit_Day, ImPlotTimeUnit_Hr, ImPlotTimeUnit_Min, ImPlotTimeUnit_Mo, ImPlotTimeUnit_Ms, ImPlotTimeUnit_S, ImPlotTimeUnit_Us, ImPlotTimeUnit_Yr, MkTime(), ImPlotTime::S, ImPlotContext::Tm, and ImPlotTime::Us.
Referenced by CeilTime(), Locator_Time(), RoundTime(), ShowDatePicker(), and Today().
for()
ImPlot::for ()
Definition at line 2573 of file implot_items.cpp.
References bin_centers, bin_counts, ImPlotRange::Min, range, and width.
FormatDate()
IMPLOT_API int ImPlot::FormatDate (const ImPlotTime & t, char * buffer, int size, ImPlotDateFmt fmt, bool use_iso_8601)
Definition at line 1116 of file implot.cpp.
References fmt, GetTime(), GImPlot, ImFormatString(), ImPlotDateFmt_DayMo, ImPlotDateFmt_DayMoYr, ImPlotDateFmt_Mo, ImPlotDateFmt_MoYr, ImPlotDateFmt_Yr, MONTH_ABRVS, and ImPlotContext::Tm.
Referenced by FormatDateTime(), and MyImPlot::PlotCandlestick().
FormatDateTime()
IMPLOT_API int ImPlot::FormatDateTime (const ImPlotTime & t, char * buffer, int size, ImPlotDateTimeSpec fmt)
Definition at line 1145 of file implot.cpp.
References fmt, FormatDate(), FormatTime(), ImPlotDateFmt_None, and ImPlotTimeFmt_None.
Referenced by Formatter_Time(), GetDateTimeWidth(), and LabelAxisValue().
Formatter_Default()
static int ImPlot::Formatter_Default (double value, char * buff, int size, void * data) inline static
Definition at line 1673 of file implot_internal.h.
References data, fmt, and ImFormatString().
Referenced by ColormapScale(), EndPlot(), SetupAxisTicks(), and SetupFinish().
Formatter_Logit()
static int ImPlot::Formatter_Logit (double value, char * buff, int size, void *) inline static
Definition at line 1678 of file implot_internal.h.
References ImFormatString().
Formatter_Time()
static int ImPlot::Formatter_Time (double , char * buff, int size, void * data) inline static
Definition at line 1694 of file implot_internal.h.
References data, FormatDateTime(), ImPlot::Formatter_Time_Data::Spec, and ImPlot::Formatter_Time_Data::Time.
Referenced by Locator_Time().
FormatTime()
IMPLOT_API int ImPlot::FormatTime (const ImPlotTime & t, char * buffer, int size, ImPlotTimeFmt fmt, bool use_24_hr_clk)
Definition at line 1076 of file implot.cpp.
References fmt, GetTime(), GImPlot, ImFormatString(), ImPlotTimeFmt_Hr, ImPlotTimeFmt_HrMin, ImPlotTimeFmt_HrMinS, ImPlotTimeFmt_HrMinSMs, ImPlotTimeFmt_MinSMs, ImPlotTimeFmt_S, ImPlotTimeFmt_SMs, ImPlotTimeFmt_SUs, ImPlotTimeFmt_Us, ImPlotContext::Tm, and ImPlotTime::Us.
Referenced by FormatDateTime().
GetAutoColor()
IMPLOT_API ImVec4 ImPlot::GetAutoColor (ImPlotCol idx)
Definition at line 263 of file implot.cpp.
References col, ImGui::GetStyleColorVec4(), GetStyleColorVec4(), ImGuiCol_Border, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImGuiCol_FrameBg, ImGuiCol_PopupBg, ImGuiCol_Text, ImGuiCol_WindowBg, ImPlotCol_AxisBg, ImPlotCol_AxisBgActive, ImPlotCol_AxisBgHovered, ImPlotCol_AxisGrid, ImPlotCol_AxisText, ImPlotCol_AxisTick, ImPlotCol_Crosshairs, ImPlotCol_ErrorBar, ImPlotCol_Fill, ImPlotCol_FrameBg, ImPlotCol_InlayText, ImPlotCol_LegendBg, ImPlotCol_LegendBorder, ImPlotCol_LegendText, ImPlotCol_Line, ImPlotCol_MarkerFill, ImPlotCol_MarkerOutline, ImPlotCol_PlotBg, ImPlotCol_PlotBorder, ImPlotCol_Selection, and ImPlotCol_TitleText.
Referenced by GetStyleColorVec4().
GetColormapColor()
ImVec4 ImPlot::GetColormapColor (int idx, ImPlotColormap cmap)
Definition at line 4584 of file implot.cpp.
References ImGui::ColorConvertU32ToFloat4(), and GetColormapColorU32().
Referenced by Demo_ErrorBars(), Demo_ScatterPlots(), and Demo_Tables().
GetColormapColorU32()
IMPLOT_API ImU32 ImPlot::GetColormapColorU32 (int idx, ImPlotColormap cmap)
Definition at line 4576 of file implot.cpp.
References ImPlotStyle::Colormap, ImPlotContext::ColormapData, ImPlotColormapData::Count, ImPlotColormapData::GetKeyColor(), ImPlotColormapData::GetKeyCount(), GImPlot, gp, IM_ASSERT_USER_ERROR, IMPLOT_AUTO, and ImPlotContext::Style.
Referenced by GetColormapColor(), RenderHeatmap(), and ShowStyleEditor().
GetColormapCount()
int ImPlot::GetColormapCount ()
Definition at line 4516 of file implot.cpp.
References ImPlotContext::ColormapData, ImPlotColormapData::Count, GImPlot, and gp.
Referenced by Demo_ColormapWidgets(), and Demo_Heatmaps().
GetColormapIndex()
ImPlotColormap ImPlot::GetColormapIndex (const char * name)
Definition at line 4526 of file implot.cpp.
References ImPlotContext::ColormapData, ImPlotColormapData::GetIndex(), GImPlot, and gp.
GetColormapName()
const char * ImPlot::GetColormapName (ImPlotColormap colormap)
Definition at line 4521 of file implot.cpp.
References ImPlotContext::ColormapData, ImPlotColormapData::GetName(), GImPlot, and gp.
Referenced by Demo_Heatmaps(), and ShowStyleEditor().
GetColormapSize()
int ImPlot::GetColormapSize (ImPlotColormap cmap)
Definition at line 4569 of file implot.cpp.
References ImPlotStyle::Colormap, ImPlotContext::ColormapData, ImPlotColormapData::Count, ImPlotColormapData::GetKeyCount(), GImPlot, gp, IM_ASSERT_USER_ERROR, IMPLOT_AUTO, and ImPlotContext::Style.
Referenced by ShowStyleEditor().
GetCurrentContext()
ImPlotContext * ImPlot::GetCurrentContext ()
Definition at line 453 of file implot.cpp.
References GImPlot.
GetCurrentItem()
ImPlotItem * ImPlot::GetCurrentItem ()
Definition at line 321 of file implot_items.cpp.
References ImPlotContext::CurrentItem, GImPlot, and gp.
Referenced by MyImPlot::PlotCandlestick(), and PlotImage().
GetCurrentPlot()
IMPLOT_API ImPlotPlot * ImPlot::GetCurrentPlot ()
Definition at line 543 of file implot.cpp.
References ImPlotContext::CurrentPlot, and GImPlot.
Referenced by BeginItemEx(), FitPoint(), FitPointX(), FitPointY(), RenderPrimitives1(), and RenderPrimitives2().
GetDateTimeFmt()
ImPlotDateTimeSpec ImPlot::GetDateTimeFmt (const ImPlotDateTimeSpec * ctx, ImPlotTimeUnit idx) inline
Definition at line 1215 of file implot.cpp.
References fmt, GetStyle(), ImPlotStyle::Use24HourClock, ImPlotStyle::UseISO8601, and ImPlotDateTimeSpec::UseISO8601.
Referenced by LabelAxisValue(), and Locator_Time().
GetDateTimeWidth()
float ImPlot::GetDateTimeWidth (ImPlotDateTimeSpec fmt) inline
Definition at line 1157 of file implot.cpp.
References ImGui::CalcTextSize(), fmt, FormatDateTime(), MakeTime(), and ImVec2::x.
Referenced by Locator_Time().
GetDaysInMonth()
static int ImPlot::GetDaysInMonth (int year, int month) inline static
Definition at line 1570 of file implot_internal.h.
References IsLeapYear().
Referenced by AddTime(), and ShowDatePicker().
GetGmtTime()
IMPLOT_API tm * ImPlot::GetGmtTime (const ImPlotTime & t, tm * ptm)
Definition at line 928 of file implot.cpp.
References ImPlotTime::S.
Referenced by GetTime().
GetInputMap()
ImPlotInputMap & ImPlot::GetInputMap ()
Definition at line 4792 of file implot.cpp.
References GImPlot, gp, IM_ASSERT_USER_ERROR, and ImPlotContext::InputMap.
Referenced by Demo_Querying(), MapInputDefault(), MapInputReverse(), and ShowInputMapping().
GetItem()
ImPlotItem * ImPlot::GetItem (const char * label_id)
Definition at line 311 of file implot_items.cpp.
References ImPlotContext::CurrentItems, ImPlotItemGroup::GetItem(), GImPlot, and gp.
Referenced by if(), and IsItemHidden().
GetItemData()
static const ImPlotNextItemData & ImPlot::GetItemData () inline static
Definition at line 1461 of file implot_internal.h.
References GImPlot, and ImPlotContext::NextItemData.
Referenced by if(), if(), PlotBarsHEx(), PlotBarsVEx(), PlotErrorBarsHEx(), PlotErrorBarsVEx(), PlotLineEx(), PlotScatterEx(), PlotShadedEx(), PlotStairsEx(), and PlotStemsEx().
GetLastItemColor()
ImVec4 ImPlot::GetLastItemColor ()
Definition at line 354 of file implot_items.cpp.
References ImPlotItem::Color, ImGui::ColorConvertU32ToFloat4(), GImPlot, gp, and ImPlotContext::PreviousItem.
Referenced by Demo_Annotations(), Demo_SubplotItemSharing(), and Demo_TimeScale().
GetLineRenderProps()
void ImPlot::GetLineRenderProps (const ImDrawList & draw_list, float & half_weight, ImVec2 & tex_uv0, ImVec2 & tex_uv1) inline
Definition at line 123 of file implot_items.cpp.
References ImDrawList::_Data, draw_list, ImDrawList::Flags, ImDrawListFlags_AntiAliasedLines, ImDrawListFlags_AntiAliasedLinesUseTex, ImHasFlag(), ImDrawListSharedData::TexUvLines, ImDrawListSharedData::TexUvWhitePixel, ImVec4::w, ImVec4::x, ImVec4::y, and ImVec4::z.
Referenced by ImPlot::RendererLineStrip< _Getter >::Init(), ImPlot::RendererLineStripSkip< _Getter >::Init(), ImPlot::RendererLineSegments1< _Getter >::Init(), ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Init(), and ImPlot::RendererMarkersLine< _Getter >::Init().
GetLocationPos()
IMPLOT_API ImVec2 ImPlot::GetLocationPos (const ImRect & outer_rect, const ImVec2 & inner_size, ImPlotLocation loc, const ImVec2 & pad)
Definition at line 557 of file implot.cpp.
References ImRect::GetCenter(), IM_ROUND, ImHasFlag(), ImPlotLocation_East, ImPlotLocation_North, ImPlotLocation_South, ImPlotLocation_West, ImRect::Max, ImRect::Min, ImVec2::x, and ImVec2::y.
Referenced by EndPlot(), EndSubplots(), and ShowAltLegend().
GetLocTime()
IMPLOT_API tm * ImPlot::GetLocTime (const ImPlotTime & t, tm * ptm)
Definition at line 948 of file implot.cpp.
References ImPlotTime::S.
Referenced by GetTime().
GetMarkerName()
const char * ImPlot::GetMarkerName (ImPlotMarker marker)
Definition at line 246 of file implot.cpp.
References ImPlotMarker_Asterisk, ImPlotMarker_Circle, ImPlotMarker_Cross, ImPlotMarker_Diamond, ImPlotMarker_Down, ImPlotMarker_Left, ImPlotMarker_None, ImPlotMarker_Plus, ImPlotMarker_Right, ImPlotMarker_Square, and ImPlotMarker_Up.
GetMonth()
IMPLOT_API int ImPlot::GetMonth (const ImPlotTime & t)
Definition at line 988 of file implot.cpp.
References GetTime(), GImPlot, and ImPlotContext::Tm.
GetPlot()
IMPLOT_API ImPlotPlot * ImPlot::GetPlot (const char * title)
Definition at line 537 of file implot.cpp.
References ImGuiContext::CurrentWindow, ImPool< T >::GetByKey(), ImGuiWindow::GetID(), GImGui, GImPlot, and ImPlotContext::Plots.
Referenced by ShowAltLegend().
GetPlotDrawList()
ImDrawList * ImPlot::GetPlotDrawList ()
Definition at line 4859 of file implot.cpp.
References ImGui::GetWindowDrawList().
Referenced by Demo_CustomRendering(), DragLineX(), DragLineY(), DragPoint(), DragRect(), if(), MyImPlot::PlotCandlestick(), PlotErrorBarsHEx(), PlotErrorBarsVEx(), PlotHeatmap(), PlotImage(), PlotText(), RenderPrimitives1(), and RenderPrimitives2().
GetPlotLimits()
ImPlotRect ImPlot::GetPlotLimits (ImAxis x_idx, ImAxis y_idx)
Definition at line 3729 of file implot.cpp.
References ImPlotPlot::Axes, ImPlotContext::CurrentPlot, ImPlotPlot::CurrentX, ImPlotPlot::CurrentY, GImPlot, gp, IM_ASSERT_USER_ERROR, ImAxis_COUNT, ImAxis_X1, ImAxis_Y1, IMPLOT_AUTO, ImPlotAxis::Range, SetupLock(), ImPlotRect::X, and ImPlotRect::Y.
Referenced by Demo_Querying(), Demo_TimeScale(), DragRect(), PlotShaded(), and PlotShaded().
GetPlotMousePos()
ImPlotPoint ImPlot::GetPlotMousePos (ImAxis x_idx, ImAxis y_idx)
Definition at line 3723 of file implot.cpp.
References ImPlotContext::CurrentPlot, ImGui::GetMousePos(), GImPlot, IM_ASSERT_USER_ERROR, PixelsToPlot(), and SetupLock().
Referenced by Demo_Querying(), DragLineX(), DragLineY(), DragPoint(), DragRect(), and MyImPlot::PlotCandlestick().
GetPlotPos()
ImVec2 ImPlot::GetPlotPos ()
Definition at line 3709 of file implot.cpp.
References ImPlotContext::CurrentPlot, GImPlot, gp, IM_ASSERT_USER_ERROR, ImRect::Min, ImPlotPlot::PlotRect, and SetupLock().
Referenced by MyImPlot::PlotCandlestick().
GetPlotSelection()
ImPlotRect ImPlot::GetPlotSelection (ImAxis x_idx, ImAxis y_idx)
Definition at line 3771 of file implot.cpp.
References ImPlotContext::CurrentPlot, GImPlot, gp, IM_ASSERT_USER_ERROR, ImMax(), ImMin(), ImRect::Max, ImPlotRange::Max, ImRect::Min, ImPlotRange::Min, PixelsToPlot(), ImPlotPlot::PlotRect, ImPlotPlot::Selected, ImPlotPlot::SelectRect, SetupLock(), ImPlotPoint::x, ImPlotRect::X, ImPlotPoint::y, and ImPlotRect::Y.
Referenced by Demo_Querying().
GetPlotSize()
ImVec2 ImPlot::GetPlotSize ()
Definition at line 3716 of file implot.cpp.
References ImPlotContext::CurrentPlot, ImRect::GetSize(), GImPlot, gp, IM_ASSERT_USER_ERROR, ImPlotPlot::PlotRect, and SetupLock().
Referenced by MyImPlot::PlotCandlestick().
GetPlotStyleVarInfo()
static const ImPlotStyleVarInfo * ImPlot::GetPlotStyleVarInfo (ImPlotStyleVar idx) static
Definition at line 331 of file implot.cpp.
References GPlotStyleVarInfo, IM_ARRAYSIZE, IM_ASSERT, and ImPlotStyleVar_COUNT.
Referenced by PopStyleVar(), PushStyleVar(), PushStyleVar(), and PushStyleVar().
GetStyle()
ImPlotStyle & ImPlot::GetStyle ()
Definition at line 4392 of file implot.cpp.
References GImPlot, gp, IM_ASSERT_USER_ERROR, and ImPlotContext::Style.
Referenced by Demo_Config(), Demo_CustomPlottersAndTooltips(), Demo_CustomStyles(), Demo_DragAndDrop(), Demo_DragRects(), Demo_LegendOptions(), Demo_MarkersAndText(), Demo_TimeScale(), GetDateTimeFmt(), GetTime(), MkTime(), MyImPlot::PlotCandlestick(), ShowStyleEditor(), StyleColorsAuto(), StyleColorsClassic(), StyleColorsDark(), StyleColorsLight(), and MyImPlot::StyleSeaborn().
GetStyleColorName()
const char * ImPlot::GetStyleColorName (ImPlotCol col)
Definition at line 219 of file implot.cpp.
References col, and ImPlotCol_COUNT.
Referenced by ShowStyleEditor().
GetStyleColorU32()
static ImU32 ImPlot::GetStyleColorU32 (ImPlotCol idx) inline static
Definition at line 1472 of file implot_internal.h.
References ImGui::ColorConvertFloat4ToU32(), and GetStyleColorVec4().
Referenced by AnnotationV(), BeginSubplots(), ColormapScale(), EndPlot(), EndSubplots(), PlotText(), SetupFinish(), ShowAltLegend(), ShowLegendEntries(), TagV(), and UpdateAxisColors().
GetStyleColorVec4()
static ImVec4 ImPlot::GetStyleColorVec4 (ImPlotCol idx) inline static
Definition at line 1471 of file implot_internal.h.
References ImPlotStyle::Colors, GetAutoColor(), GImPlot, IsColorAuto(), and ImPlotContext::Style.
Referenced by BeginItem(), EndPlot(), GetAutoColor(), GetStyleColorU32(), ShowStyleEditor(), and UpdateAxisColors().
GetTime()
static tm * ImPlot::GetTime (const ImPlotTime & t, tm * ptm) inline static
Definition at line 1594 of file implot_internal.h.
References GetGmtTime(), GetLocTime(), and GetStyle().
Referenced by AddTime(), CombineDateTime(), FloorTime(), FormatDate(), FormatTime(), GetMonth(), GetYear(), ShowDatePicker(), and ShowTimePicker().
GetTimeStep()
int ImPlot::GetTimeStep (int max_divs, ImPlotTimeUnit unit) inline
Definition at line 887 of file implot.cpp.
References ImPlotTimeUnit_Day, ImPlotTimeUnit_Hr, ImPlotTimeUnit_Min, ImPlotTimeUnit_Mo, ImPlotTimeUnit_Ms, ImPlotTimeUnit_S, ImPlotTimeUnit_Us, and LowerBoundStep().
Referenced by Locator_Time().
GetUnitForRange()
ImPlotTimeUnit ImPlot::GetUnitForRange (double range) inline
Definition at line 868 of file implot.cpp.
References IMPLOT_MAX_TIME, ImPlotTimeUnit_COUNT, ImPlotTimeUnit_Yr, and range.
Referenced by LabelAxisValue(), and Locator_Time().
GetYear()
IMPLOT_API int ImPlot::GetYear (const ImPlotTime & t)
Definition at line 982 of file implot.cpp.
References GetTime(), GImPlot, and ImPlotContext::Tm.
Referenced by AddTime(), Locator_Time(), and ShowDatePicker().
HelpMarker()
static void ImPlot::HelpMarker (const char * desc) static
Definition at line 4877 of file implot.cpp.
References ImGui::BeginTooltip(), ImGui::EndTooltip(), ImGui::GetFontSize(), ImGui::IsItemHovered(), ImGui::PopTextWrapPos(), ImGui::PushTextWrapPos(), ImGui::TextDisabled(), and ImGui::TextUnformatted().
Referenced by ShowStyleEditor().
HideNextItem()
void ImPlot::HideNextItem (bool hidden, ImPlotCond cond)
Definition at line 3797 of file implot.cpp.
References GImPlot, gp, ImPlotNextItemData::HasHidden, ImPlotNextItemData::Hidden, ImPlotNextItemData::HiddenCond, and ImPlotContext::NextItemData.
if() [1/13]
ImPlot::if (BeginItemEx(label_id, FitterRect(range)))
Definition at line 2692 of file implot_items.cpp.
References bin_counts, col_maj, ImVector< T >::Data, draw_list, EndItem(), GetPlotDrawList(), ImPlotRange::Max, max_count, ImPlotRange::Min, range, RenderHeatmap(), x_bins, and y_bins.
if() [2/13]
ImPlot::if (BeginItemEx(label_id, FitterX< GetterXY< IndexerIdx< T >, IndexerConst > >(get_min), flags, ImPlotCol_Line))
Definition at line 2183 of file implot_items.cpp.
References ImPlotNextItemData::Colors, count, EndItem(), get_max, ImGui::GetColorU32(), GetItemData(), ImPlotCol_Line, ImPlotNextItemData::LineWeight, and ImPlotNextItemData::RenderLine.
if() [3/13]
ImPlot::if ()
if() [4/13]
ImPlot::if (count<=0|| bins = =0)
if() [5/13]
ImPlot::if (cumulative && density)
Definition at line 2592 of file implot_items.cpp.
References below, bin_counts, bins, count, counted, max_count, and outliers.
if() [6/13]
else ImPlot::if (cumulative)
Definition at line 2602 of file implot_items.cpp.
References below, bin_counts, bins, max_count, and outliers.
if() [7/13]
ImPlot::if (density)
Definition at line 2609 of file implot_items.cpp.
References bin_counts, bins, count, counted, max_count, outliers, and width.
if() [8/13]
ImPlot::if (fmt ! = nullptr)
Definition at line 2343 of file implot_items.cpp.
References a0, a1, ImDrawList::AddText(), angle0, CalcTextColor(), ImGui::CalcTextSize(), center, col, ImPlotItem::Color, ImGui::ColorConvertU32ToFloat4(), count, draw_list, flags, fmt, fmt_data, GetItem(), ignore_hidden, IM_ASSERT, IM_PI, ImHasFlag(), IMPLOT_AUTO, ImPlotPieChartFlags_Exploding, IsLegendEntryHovered(), normalize, offset, PlotToPixels(), radius, ImPlotItem::Show, sum, values, ImPlotPoint::x, and ImPlotPoint::y.
if() [9/13]
ImPlot::if (ImHasFlag(flags, ImPlotHistogramFlags_Horizontal))
if() [10/13]
ImPlot::if (ImHasFlag(flags, ImPlotInfLinesFlags_Horizontal))
Definition at line 2165 of file implot_items.cpp.
References BeginItemEx(), ImPlotNextItemData::Colors, count, EndItem(), flags, ImGui::GetColorU32(), GetItemData(), ImPlotCol_Line, ImPlotNextItemData::LineWeight, ImPlotRange::Max, ImPlotRange::Min, offset, ImPlotNextItemData::RenderLine, stride, values, and ImPlotRect::X.
if() [11/13]
ImPlot::if (range. Min = = 0 && range.Max == 0)
Definition at line 2553 of file implot_items.cpp.
References count, ImMinMaxArray(), ImPlotRange::Max, ImPlotRange::Min, range, and values.
if() [12/13]
ImPlot::if (range.X. Min = = 0 && range.X.Max == 0)
Definition at line 2640 of file implot_items.cpp.
References count, ImMinMaxArray(), ImPlotRange::Max, ImPlotRange::Min, range, and xs.
if() [13/13]
ImPlot::if (range.Y. Min = = 0 && range.Y.Max == 0)
Definition at line 2646 of file implot_items.cpp.
References count, ImMinMaxArray(), ImPlotRange::Max, ImPlotRange::Min, range, and ys.
IndexData()
template<typename T > T ImPlot::IndexData (const T * data, int idx, int count, int offset, int stride) inline
Definition at line 496 of file implot_items.cpp.
References count, data, offset, and stride.
Referenced by ImPlot::IndexerIdx< T >::operator()(), and ImPlot::GetterError< T >::operator()().
Initialize()
IMPLOT_API void ImPlot::Initialize (ImPlotContext * ctx)
Definition at line 464 of file implot.cpp.
References IM_COL32_BLACK, IM_COL32_WHITE, IM_RGB, IMPLOT_APPEND_CMAP, ResetCtxForNextAlignedPlots(), ResetCtxForNextPlot(), and ResetCtxForNextSubplot().
Referenced by CreateContext().
InputMapping()
void ImPlot::InputMapping (const char * label, ImGuiMouseButton * b, int * k)
Definition at line 237 of file implot_demo.cpp.
References ButtonSelector(), ImGui::LabelText(), ModSelector(), and ImGui::SameLine().
Referenced by ShowInputMapping().
Intersection()
static ImVec2 ImPlot::Intersection (const ImVec2 & a1, const ImVec2 & a2, const ImVec2 & b1, const ImVec2 & b2) inline static
Definition at line 1524 of file implot_internal.h.
References a1, ImVec2::x, ImPlotPoint::x, ImVec2::y, and ImPlotPoint::y.
Referenced by ImPlot::RendererShaded< _Getter1, _Getter2 >::Render().
IsAxisHovered()
bool ImPlot::IsAxisHovered (ImAxis axis)
Definition at line 3751 of file implot.cpp.
References ImPlotPlot::Axes, ImPlotContext::CurrentPlot, GImPlot, gp, ImPlotAxis::Hovered, IM_ASSERT_USER_ERROR, and SetupLock().
IsColorAuto() [1/2]
static bool ImPlot::IsColorAuto (const ImVec4 & col) inline static
Definition at line 1464 of file implot_internal.h.
References col.
Referenced by BeginItem(), DragLineX(), DragLineY(), DragPoint(), DragRect(), GetStyleColorVec4(), IsColorAuto(), and ShowStyleEditor().
IsColorAuto() [2/2]
static bool ImPlot::IsColorAuto (ImPlotCol idx) inline static
Definition at line 1466 of file implot_internal.h.
References ImPlotStyle::Colors, GImPlot, IsColorAuto(), and ImPlotContext::Style.
IsItemHidden()
bool ImPlot::IsItemHidden (const char * label_id)
Definition at line 316 of file implot_items.cpp.
References GetItem(), and ImPlotItem::Show.
IsLeapYear()
static bool ImPlot::IsLeapYear (int year) inline static
Definition at line 1566 of file implot_internal.h.
Referenced by AddTime(), and GetDaysInMonth().
IsLegendEntryHovered()
bool ImPlot::IsLegendEntryHovered (const char * label_id)
Definition at line 4220 of file implot.cpp.
References ImPlotContext::CurrentItems, ImGui::GetIDWithSeed(), ImPlotItemGroup::GetItem(), GImPlot, gp, ImPlotItemGroup::ID, IM_ASSERT_USER_ERROR, ImPlotItem::LegendHovered, and SetupLock().
Referenced by if().
IsPlotHovered()
bool ImPlot::IsPlotHovered ()
Definition at line 3744 of file implot.cpp.
References ImPlotContext::CurrentPlot, GImPlot, gp, ImPlotPlot::Hovered, IM_ASSERT_USER_ERROR, and SetupLock().
Referenced by Demo_Querying(), and MyImPlot::PlotCandlestick().
IsPlotSelected()
bool ImPlot::IsPlotSelected ()
Definition at line 3764 of file implot.cpp.
References ImPlotContext::CurrentPlot, GImPlot, gp, IM_ASSERT_USER_ERROR, ImPlotPlot::Selected, and SetupLock().
Referenced by Demo_Querying().
IsSubplotsHovered()
bool ImPlot::IsSubplotsHovered ()
Definition at line 3758 of file implot.cpp.
References ImPlotContext::CurrentSubplot, ImPlotSubplot::FrameHovered, GImPlot, gp, and IM_ASSERT_USER_ERROR.
ItemIcon() [1/2]
void ImPlot::ItemIcon (const ImVec4 & col)
Definition at line 4834 of file implot.cpp.
References col, ImGui::ColorConvertFloat4ToU32(), and ItemIcon().
Referenced by Demo_DragAndDrop(), Demo_SubplotItemSharing(), and ItemIcon().
ItemIcon() [2/2]
void ImPlot::ItemIcon (ImU32 col)
Definition at line 4838 of file implot.cpp.
References ImDrawList::AddRectFilled(), col, ImGuiWindowTempData::CursorPos, ImGuiWindow::DC, ImGui::Dummy(), ImGui::GetCurrentWindow(), ImGui::GetTextLineHeight(), and ImGui::GetWindowDrawList().
LabelAxisValue()
IMPLOT_API void ImPlot::LabelAxisValue (const ImPlotAxis & axis, double value, char * buff, int size, bool round)
Definition at line 1600 of file implot.cpp.
References ImPlotContext::CurrentPlot, FormatDateTime(), ImPlotAxis::Formatter, ImPlotAxis::FormatterData, ImPlotTime::FromDouble(), GetDateTimeFmt(), ImRect::GetHeight(), GetUnitForRange(), ImRect::GetWidth(), GImPlot, gp, ImPlotAxis::Locator, Locator_Time(), ImPlotPlot::PlotRect, ImPlotAxis::Range, RoundAxisValue(), ImPlotRange::Size(), TimeFormatMouseCursor, and ImPlotAxis::Vertical.
Referenced by Annotation(), EndPlot(), and Tag().
LegendSortingComp()
int ImPlot::LegendSortingComp (const void * _a, const void * _b)
Definition at line 620 of file implot.cpp.
References ImPlotItemGroup::GetLegendLabel(), GImPlot, and ImPlotContext::SortItems.
Referenced by ShowLegendEntries().
Locator_Default()
IMPLOT_API void ImPlot::Locator_Default (ImPlotTicker & ticker, const ImPlotRange & range, float pixels, bool vertical, ImPlotFormatter formatter, void * formatter_data)
Definition at line 723 of file implot.cpp.
References ImPlotTicker::AddTick(), ImPlotRange::Contains(), IM_ROUND, ImMax(), ImPlotTick::LabelSize, ImPlotRange::Max, ImPlotRange::Min, NiceNum(), range, ImPlotRange::Size(), TICK_FILL_X, TICK_FILL_Y, ImPlotTicker::TickCount(), ImPlotTicker::Ticks, ImVec2::x, and ImVec2::y.
Referenced by ColormapScale(), Locator_SymLog(), and SetupFinish().
Locator_Log10()
IMPLOT_API void ImPlot::Locator_Log10 (ImPlotTicker & ticker, const ImPlotRange & range, float pixels, bool vertical, ImPlotFormatter formatter, void * formatter_data)
Definition at line 803 of file implot.cpp.
References AddTicksLogarithmic(), CalcLogarithmicExponents(), and range.
Referenced by Locator_SymLog(), and SetupAxisScale().
Locator_SymLog()
IMPLOT_API void ImPlot::Locator_SymLog (ImPlotTicker & ticker, const ImPlotRange & range, float pixels, bool vertical, ImPlotFormatter formatter, void * formatter_data)
Definition at line 820 of file implot.cpp.
References ImPlotTicker::AddTick(), AddTicksLogarithmic(), CalcLogarithmicExponents(), CalcSymLogPixel(), ImAbs(), ImMax(), Locator_Default(), Locator_Log10(), ImPlotRange::Max, ImPlotRange::Min, and range.
Referenced by SetupAxisScale().
Locator_Time()
IMPLOT_API void ImPlot::Locator_Time (ImPlotTicker & ticker, const ImPlotRange & range, float pixels, bool vertical, ImPlotFormatter formatter, void * formatter_data)
Definition at line 1223 of file implot.cpp.
References ImPlotTicker::AddTick(), AddTime(), ImGuiTextBuffer::Buf, CeilTime(), ImVector< T >::Data, float(), FloorTime(), Formatter_Time(), ImPlotTime::FromDouble(), GetDateTimeFmt(), GetDateTimeWidth(), ImPlotTicker::GetText(), GetTimeStep(), GetUnitForRange(), GetYear(), IM_ASSERT_USER_ERROR, ImClamp(), ImPlotTimeUnit_COUNT, ImPlotTimeUnit_Yr, MakeTime(), ImPlotRange::Max, ImPlotRange::Min, NiceNum(), range, ImPlotTick::ShowLabel, ImPlotRange::Size(), ImPlot::Formatter_Time_Data::Spec, ImPlotTicker::TextBuffer, ImPlotTick::TextOffset, ImPlot::Formatter_Time_Data::Time, TimeFormatLevel0, TimeFormatLevel1, TimeFormatLevel1First, TimeLabelSame(), TimeUnitSpans, ImPlotTime::ToDouble(), ImPlot::Formatter_Time_Data::UserFormatter, ImPlot::Formatter_Time_Data::UserFormatterData, and y.
Referenced by LabelAxisValue(), and SetupAxisScale().
LowerBoundStep()
int ImPlot::LowerBoundStep (int max_divs, const int * divs, const int * step, int size) inline
Definition at line 877 of file implot.cpp.
Referenced by GetTimeStep().
MakeTime()
IMPLOT_API ImPlotTime ImPlot::MakeTime (int year, int month, int day, int hour, int min, int sec, int us)
Definition at line 959 of file implot.cpp.
References GImPlot, MkTime(), ImPlotContext::Tm, and ImPlotTime::Us.
Referenced by GetDateTimeWidth(), Locator_Time(), and ShowDatePicker().
MapInputDefault()
void ImPlot::MapInputDefault (ImPlotInputMap * dst)
Definition at line 4798 of file implot.cpp.
References ImPlotInputMap::Fit, GetInputMap(), ImGuiMod_Alt, ImGuiMod_Ctrl, ImGuiMod_None, ImGuiMod_Shift, ImGuiMouseButton_Left, ImGuiMouseButton_Right, ImPlotInputMap::Menu, ImPlotInputMap::OverrideMod, ImPlotInputMap::Pan, ImPlotInputMap::PanMod, ImPlotInputMap::Select, ImPlotInputMap::SelectCancel, ImPlotInputMap::SelectHorzMod, ImPlotInputMap::SelectMod, ImPlotInputMap::SelectVertMod, ImPlotInputMap::ZoomMod, and ImPlotInputMap::ZoomRate.
Referenced by ImPlotInputMap::ImPlotInputMap(), and ShowInputMapSelector().
MapInputReverse()
void ImPlot::MapInputReverse (ImPlotInputMap * dst)
Definition at line 4814 of file implot.cpp.
References ImPlotInputMap::Fit, GetInputMap(), ImGuiMod_Alt, ImGuiMod_Ctrl, ImGuiMod_None, ImGuiMod_Shift, ImGuiMouseButton_Left, ImGuiMouseButton_Right, ImPlotInputMap::Menu, ImPlotInputMap::OverrideMod, ImPlotInputMap::Pan, ImPlotInputMap::PanMod, ImPlotInputMap::Select, ImPlotInputMap::SelectCancel, ImPlotInputMap::SelectHorzMod, ImPlotInputMap::SelectMod, ImPlotInputMap::SelectVertMod, ImPlotInputMap::ZoomMod, and ImPlotInputMap::ZoomRate.
Referenced by ShowInputMapSelector().
MetricFormatter()
int ImPlot::MetricFormatter (double value, char * buff, int size, void * data)
Definition at line 1981 of file implot_demo.cpp.
References data.
Referenced by Demo_TickLabels().
MkGmtTime()
IMPLOT_API ImPlotTime ImPlot::MkGmtTime (struct tm * ptm)
Definition at line 916 of file implot.cpp.
References ImPlotTime::S.
Referenced by MkTime().
MkLocTime()
IMPLOT_API ImPlotTime ImPlot::MkLocTime (struct tm * ptm)
Definition at line 940 of file implot.cpp.
References ImPlotTime::S.
Referenced by MkTime().
MkTime()
static ImPlotTime ImPlot::MkTime (struct tm * ptm) inline static
Definition at line 1589 of file implot_internal.h.
References GetStyle(), MkGmtTime(), and MkLocTime().
Referenced by CombineDateTime(), FloorTime(), MakeTime(), and ShowTimePicker().
ModSelector()
void ImPlot::ModSelector (const char * label, int * k)
Definition at line 228 of file implot_demo.cpp.
References ImGui::CheckboxFlags(), ImGuiMod_Alt, ImGuiMod_Ctrl, ImGuiMod_Shift, ImGuiMod_Super, ImGui::PopID(), ImGui::PushID(), and ImGui::SameLine().
Referenced by InputMapping().
NextColormapColor()
ImVec4 ImPlot::NextColormapColor ()
Definition at line 4565 of file implot.cpp.
References ImGui::ColorConvertU32ToFloat4(), and NextColormapColorU32().
Referenced by Demo_CustomStyles().
NextColormapColorU32()
IMPLOT_API ImU32 ImPlot::NextColormapColorU32 ()
Definition at line 4556 of file implot.cpp.
References col, ImPlotStyle::Colormap, ImPlotContext::ColormapData, ImPlotItemGroup::ColormapIdx, ImPlotContext::CurrentItems, ImPlotColormapData::GetKeyColor(), ImPlotColormapData::GetKeyCount(), GImPlot, gp, IM_ASSERT_USER_ERROR, and ImPlotContext::Style.
Referenced by BeginItem(), and NextColormapColor().
NiceNum()
IMPLOT_API double ImPlot::NiceNum (double x, bool round)
Definition at line 404 of file implot.cpp.
References ImLog10(), ImPow(), and x.
Referenced by Locator_Default(), and Locator_Time().
Now()
static ImPlotTime ImPlot::Now () inline static
Definition at line 1619 of file implot_internal.h.
References ImPlotTime::FromDouble().
Referenced by Today().
OrderOfMagnitude()
static int ImPlot::OrderOfMagnitude (double val) inline static
Definition at line 1515 of file implot_internal.h.
Referenced by Precision().
OrderToPrecision()
static int ImPlot::OrderToPrecision (int order) inline static
Definition at line 1517 of file implot_internal.h.
Referenced by Precision().
PadAndDatumAxesX()
void ImPlot::PadAndDatumAxesX (ImPlotPlot & plot, float & pad_T, float & pad_B, ImPlotAlignmentData * align)
Definition at line 1630 of file implot.cpp.
References ImPlotPlot::AxesRect, ImPlotPlot::CanvasRect, ImPlotAxis::Datum1, ImPlotAxis::Datum2, ImPlotAxis::Enabled, ImGui::GetTextLineHeight(), GImPlot, gp, ImPlotAxis::HasLabel(), ImPlotAxis::HasTickLabels(), ImMax(), IMPLOT_NUM_X_AXES, ImPlotScale_Time, ImPlotAxis::IsOpposite(), ImPlotStyle::LabelPadding, ImRect::Max, ImPlotTicker::MaxSize, ImRect::Min, ImPlotStyle::MinorTickLen, ImPlotAxis::Scale, ImPlotContext::Style, ImPlotAxis::Ticker, ImPlotAlignmentData::Update(), ImVec2::x, ImPlotPlot::XAxis(), and ImVec2::y.
Referenced by SetupFinish().
PadAndDatumAxesY()
void ImPlot::PadAndDatumAxesY (ImPlotPlot & plot, float & pad_L, float & pad_R, ImPlotAlignmentData * align)
Definition at line 1695 of file implot.cpp.
References ImPlotPlot::AxesRect, ImPlotPlot::CanvasRect, ImPlotAxis::Datum1, ImPlotAxis::Datum2, ImPlotAxis::Enabled, ImGui::GetTextLineHeight(), GImPlot, gp, ImPlotAxis::HasLabel(), ImPlotAxis::HasTickLabels(), IMPLOT_NUM_Y_AXES, ImPlotAxis::IsOpposite(), ImPlotStyle::LabelPadding, ImRect::Max, ImPlotTicker::MaxSize, ImRect::Min, ImPlotStyle::MinorTickLen, ImPlotPlot::PlotRect, ImPlotContext::Style, ImPlotAxis::Ticker, ImPlotAlignmentData::Update(), ImVec2::x, ImVec2::y, and ImPlotPlot::YAxis().
Referenced by SetupFinish().
PixelsToPlot() [1/2]
ImPlotPoint ImPlot::PixelsToPlot (const ImVec2 & pix, ImAxis x_idx, ImAxis y_idx)
Definition at line 3689 of file implot.cpp.
References PixelsToPlot(), ImVec2::x, and ImVec2::y.
PixelsToPlot() [2/2]
ImPlotPoint ImPlot::PixelsToPlot (float x, float y, ImAxis x_idx, ImAxis y_idx)
Definition at line 3677 of file implot.cpp.
References ImPlotPlot::Axes, ImPlotContext::CurrentPlot, ImPlotPlot::CurrentX, ImPlotPlot::CurrentY, GImPlot, gp, IM_ASSERT_USER_ERROR, ImAxis_COUNT, ImAxis_X1, ImAxis_Y1, IMPLOT_AUTO, ImPlotAxis::PixelsToPlot(), SetupLock(), x, and y.
Referenced by DragRect(), GetPlotMousePos(), GetPlotSelection(), PixelsToPlot(), and PlotText().
PlotBarGroups()
template<typename T > void ImPlot::PlotBarGroups (const char *const label_ids[], const T * values, int item_count, int group_count, double group_size = 0.67, double shift = 0, ImPlotBarGroupsFlags flags = 0)
Referenced by Demo_BarGroups(), and Demo_BarStacks().
PlotBarGroups< ImU8 >()
template void ImPlot::PlotBarGroups< ImU8 > (const char *const label_ids[], const ImU8 * values, int items, int groups, double width, double shift, ImPlotBarGroupsFlags flags)
PlotBars() [1/3]
template<typename T > void ImPlot::PlotBars (const char * label_id, const T * values, int count, double bar_size = 0.67, double shift = 0, ImPlotBarsFlags flags = 0, int offset = 0, int stride = sizeof(T))
Definition at line 1875 of file implot_items.cpp.
References bar_size, count, flags, getter2, ImHasFlag(), ImPlotBarsFlags_Horizontal, offset, PlotBarsHEx(), PlotBarsVEx(), stride, and values.
Referenced by Demo_Annotations(), Demo_BarPlots(), Demo_CustomStyles(), Demo_ErrorBars(), Demo_LegendPopups(), and Demo_NaNValues().
PlotBars() [2/3]
template<typename T > void ImPlot::PlotBars (const char * label_id, const T * xs, const T * ys, int count, double bar_size, ImPlotBarsFlags flags = 0, int offset = 0, int stride = sizeof(T))
Definition at line 1889 of file implot_items.cpp.
References bar_size, count, flags, getter2, ImHasFlag(), ImPlotBarsFlags_Horizontal, offset, PlotBarsHEx(), PlotBarsVEx(), stride, xs, and ys.
PlotBars() [3/3]
else ImPlot::PlotBars (label_id , &bin_centers. Data[0], &bin_counts. Data[0], bins , bar_scale * width)
PlotBars< ImS8 >() [1/2]
template void ImPlot::PlotBars< ImS8 > (const char * label_id, const ImS8 * values, int count, double bar_size, double shift, ImPlotBarsFlags flags, int offset, int stride)
PlotBars< ImS8 >() [2/2]
template void ImPlot::PlotBars< ImS8 > (const char * label_id, const ImS8 * xs, const ImS8 * ys, int count, double bar_size, ImPlotBarsFlags flags, int offset, int stride)
PlotBars< ImU8 >() [1/2]
template void ImPlot::PlotBars< ImU8 > (const char * label_id, const ImU8 * values, int count, double bar_size, double shift, ImPlotBarsFlags flags, int offset, int stride)
PlotBars< ImU8 >() [2/2]
template void ImPlot::PlotBars< ImU8 > (const char * label_id, const ImU8 * xs, const ImU8 * ys, int count, double bar_size, ImPlotBarsFlags flags, int offset, int stride)
PlotBarsG()
void ImPlot::PlotBarsG (const char * label_id, ImPlotGetter getter, void * data, int count, double bar_size, ImPlotBarsFlags flags = 0)
PlotBarsHEx()
template<typename Getter1 , typename Getter2 > void ImPlot::PlotBarsHEx (const char * label_id, const Getter1 & getter1, const Getter2 & getter2, double height, ImPlotBarsFlags flags)
Definition at line 1851 of file implot_items.cpp.
References BeginItemEx(), ImPlotNextItemData::Colors, ImPlot::GetterFuncPtr::Count, EndItem(), flags, ImGui::GetColorU32(), GetItemData(), getter2, height, ImPlotCol_Fill, ImPlotCol_Line, ImPlotNextItemData::LineWeight, ImPlotNextItemData::RenderFill, and ImPlotNextItemData::RenderLine.
Referenced by PlotBars(), and PlotBars().
PlotBarsVEx()
template<typename Getter1 , typename Getter2 > void ImPlot::PlotBarsVEx (const char * label_id, const Getter1 & getter1, const Getter2 getter2, double width, ImPlotBarsFlags flags)
Definition at line 1827 of file implot_items.cpp.
References BeginItemEx(), ImPlotNextItemData::Colors, ImPlot::GetterFuncPtr::Count, EndItem(), flags, ImGui::GetColorU32(), GetItemData(), getter2, ImPlotCol_Fill, ImPlotCol_Line, ImPlotNextItemData::LineWeight, ImPlotNextItemData::RenderFill, ImPlotNextItemData::RenderLine, and width.
Referenced by PlotBars(), and PlotBars().
PlotDigital()
template<typename T > void ImPlot::PlotDigital (const char * label_id, const T * xs, const T * ys, int count, ImPlotDigitalFlags flags = 0, int offset = 0, int stride = sizeof(T))
Referenced by Demo_DigitalPlots().
PlotDigital< ImU8 >()
template void ImPlot::PlotDigital< ImU8 > (const char * label_id, const ImU8 * xs, const ImU8 * ys, int count, ImPlotDigitalFlags flags, int offset, int stride)
References count, data, getter, and getter_func.
PlotDigitalEx()
return ImPlot::PlotDigitalEx (label_id , getter , flags)
PlotDigitalG()
void ImPlot::PlotDigitalG (const char * label_id, ImPlotGetter getter, void * data, int count, ImPlotDigitalFlags flags = 0)
PlotDummy()
void ImPlot::PlotDummy (const char * label_id, ImPlotDummyFlags flags = 0)
Definition at line 2845 of file implot_items.cpp.
References BeginItem(), EndItem(), flags, and ImPlotCol_Line.
Referenced by Demo_LegendOptions().
PlotErrorBars() [1/2]
template<typename T > void ImPlot::PlotErrorBars (const char * label_id, const T * xs, const T * ys, const T * err, int count, ImPlotErrorBarsFlags flags = 0, int offset = 0, int stride = sizeof(T))
Definition at line 2061 of file implot_items.cpp.
References count, flags, offset, PlotErrorBars(), stride, xs, and ys.
Referenced by Demo_ErrorBars(), and PlotErrorBars().
PlotErrorBars() [2/2]
template<typename T > void ImPlot::PlotErrorBars (const char * label_id, const T * xs, const T * ys, const T * neg, const T * pos, int count, ImPlotErrorBarsFlags flags = 0, int offset = 0, int stride = sizeof(T))
Definition at line 2066 of file implot_items.cpp.
References count, flags, getter, ImHasFlag(), ImPlotErrorBarsFlags_Horizontal, offset, PlotErrorBarsHEx(), PlotErrorBarsVEx(), stride, xs, and ys.
PlotErrorBars< ImS8 >() [1/2]
template void ImPlot::PlotErrorBars< ImS8 > (const char * label_id, const ImS8 * xs, const ImS8 * ys, const ImS8 * err, int count, ImPlotErrorBarsFlags flags, int offset, int stride)
PlotErrorBars< ImS8 >() [2/2]
template void ImPlot::PlotErrorBars< ImS8 > (const char * label_id, const ImS8 * xs, const ImS8 * ys, const ImS8 * neg, const ImS8 * pos, int count, ImPlotErrorBarsFlags flags, int offset, int stride)
PlotErrorBars< ImU8 >() [1/2]
template void ImPlot::PlotErrorBars< ImU8 > (const char * label_id, const ImU8 * xs, const ImU8 * ys, const ImU8 * err, int count, ImPlotErrorBarsFlags flags, int offset, int stride)
PlotErrorBars< ImU8 >() [2/2]
template void ImPlot::PlotErrorBars< ImU8 > (const char * label_id, const ImU8 * xs, const ImU8 * ys, const ImU8 * neg, const ImU8 * pos, int count, ImPlotErrorBarsFlags flags, int offset, int stride)
PlotErrorBarsHEx()
template<typename _GetterPos , typename _GetterNeg > void ImPlot::PlotErrorBarsHEx (const char * label_id, const _GetterPos & getter_pos, const _GetterNeg & getter_neg, ImPlotErrorBarsFlags flags)
Definition at line 2036 of file implot_items.cpp.
References ImDrawList::AddLine(), BeginItemEx(), col, ImPlotNextItemData::Colors, draw_list, EndItem(), ImPlotNextItemData::ErrorBarSize, ImPlotNextItemData::ErrorBarWeight, flags, ImGui::GetColorU32(), GetItemData(), GetPlotDrawList(), IMPLOT_AUTO, ImPlotCol_ErrorBar, and PlotToPixels().
Referenced by PlotErrorBars().
PlotErrorBarsVEx()
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() _GetterNeg void ImPlot::PlotErrorBarsVEx (const char * label_id, const _GetterPos & getter_pos, const _GetterNeg & getter_neg, ImPlotErrorBarsFlags flags)
Definition at line 2011 of file implot_items.cpp.
References ImDrawList::AddLine(), BeginItemEx(), col, ImPlotNextItemData::Colors, draw_list, EndItem(), ImPlotNextItemData::ErrorBarSize, ImPlotNextItemData::ErrorBarWeight, flags, ImGui::GetColorU32(), GetItemData(), GetPlotDrawList(), IMPLOT_AUTO, ImPlotCol_ErrorBar, and PlotToPixels().
Referenced by PlotErrorBars().
PlotHeatmap()
template<typename T > void ImPlot::PlotHeatmap (const char * label_id, const T * values, int rows, int cols, double scale_min = 0, double scale_max = 0, const char * label_fmt = "%.1f", const ImPlotPoint & bounds_min = ImPlotPoint(0,0), const ImPlotPoint & bounds_max = ImPlotPoint(1,1), ImPlotHeatmapFlags flags = 0)
Definition at line 2523 of file implot_items.cpp.
References BeginItemEx(), col_maj, draw_list, EndItem(), flags, fmt, GetPlotDrawList(), ImHasFlag(), ImPlotHeatmapFlags_ColMajor, RenderHeatmap(), and values.
Referenced by Demo_Heatmaps().
PlotHeatmap< ImS8 >()
template void ImPlot::PlotHeatmap< ImS8 > (const char * label_id, const ImS8 * values, int rows, int cols, double scale_min, double scale_max, const char * fmt, const ImPlotPoint & bounds_min, const ImPlotPoint & bounds_max, ImPlotHeatmapFlags flags)
PlotHeatmap< ImU8 >()
template void ImPlot::PlotHeatmap< ImU8 > (const char * label_id, const ImU8 * values, int rows, int cols, double scale_min, double scale_max, const char * fmt, const ImPlotPoint & bounds_min, const ImPlotPoint & bounds_max, ImPlotHeatmapFlags flags)
PlotHistogram()
template<typename T > double ImPlot::PlotHistogram (const char * label_id, const T * values, int count, int bins = ImPlotBin_Sturges, double bar_scale = 1.0, ImPlotRange range = ImPlotRange(), ImPlotHistogramFlags flags = 0)
Referenced by Demo_Histogram().
PlotHistogram2D()
template<typename T > double ImPlot::PlotHistogram2D (const char * label_id, const T * xs, const T * ys, int count, int x_bins = ImPlotBin_Sturges, int y_bins = ImPlotBin_Sturges, ImPlotRect range = ImPlotRect(), ImPlotHistogramFlags flags = 0)
Referenced by Demo_Histogram2D().
PlotHistogram2D< ImS8 >()
template double ImPlot::PlotHistogram2D< ImS8 > (const char * label_id, const ImS8 * xs, const ImS8 * ys, int count, int x_bins, int y_bins, ImPlotRect range, ImPlotHistogramFlags flags)
PlotHistogram2D< ImU8 >()
template double ImPlot::PlotHistogram2D< ImU8 > (const char * label_id, const ImU8 * xs, const ImU8 * ys, int count, int x_bins, int y_bins, ImPlotRect range, ImPlotHistogramFlags flags)
PlotHistogram< ImS8 >()
template double ImPlot::PlotHistogram< ImS8 > (const char * label_id, const ImS8 * values, int count, int bins, double bar_scale, ImPlotRange range, ImPlotHistogramFlags flags)
PlotHistogram< ImU8 >()
template double ImPlot::PlotHistogram< ImU8 > (const char * label_id, const ImU8 * values, int count, int bins, double bar_scale, ImPlotRange range, ImPlotHistogramFlags flags)
PlotImage()
void ImPlot::PlotImage (const char * label_id, ImTextureID tex_ref, const ImPlotPoint & bounds_min, const ImPlotPoint & bounds_max, const ImVec2 & uv0 = ImVec2(0,0), const ImVec2 & uv1 = ImVec2(1,1), const ImVec4 & tint_col = ImVec4(1,1,1,1), ImPlotImageFlags flags = 0)
Definition at line 2794 of file implot_items.cpp.
References ImDrawList::AddImage(), BeginItemEx(), ImPlotItem::Color, ImGui::ColorConvertFloat4ToU32(), draw_list, EndItem(), GetCurrentItem(), GetPlotDrawList(), IMPLOT_AUTO, PlotToPixels(), PopPlotClipRect(), PushPlotClipRect(), ImPlotPoint::x, and ImPlotPoint::y.
Referenced by Demo_Images().
PlotInfLines()
template<typename T > void ImPlot::PlotInfLines (const char * label_id, const T * values, int count, ImPlotInfLinesFlags flags = 0, int offset = 0, int stride = sizeof(T))
Referenced by Demo_InfiniteLines().
PlotInfLines< ImS8 >()
template void ImPlot::PlotInfLines< ImS8 > (const char * label_id, const ImS8 * xs, int count, ImPlotInfLinesFlags flags, int offset, int stride)
PlotInfLines< ImU8 >()
template void ImPlot::PlotInfLines< ImU8 > (const char * label_id, const ImU8 * xs, int count, ImPlotInfLinesFlags flags, int offset, int stride)
PlotLine() [1/2]
template<typename T > void ImPlot::PlotLine (const char * label_id, const T * values, int count, double xscale = 1, double xstart = 0, ImPlotLineFlags flags = 0, int offset = 0, int stride = sizeof(T))
Definition at line 1621 of file implot_items.cpp.
References count, flags, getter, offset, PlotLineEx(), stride, and values.
Referenced by Demo_AutoFittingData(), Demo_Config(), Demo_CustomDataAndGetters(), Demo_CustomScale(), Demo_CustomStyles(), Demo_DigitalPlots(), Demo_DragAndDrop(), Demo_DragLines(), Demo_DragPoints(), Demo_DragRects(), Demo_EqualAxes(), Demo_ErrorBars(), Demo_FilledLinePlots(), Demo_Histogram(), Demo_LegendPopups(), Demo_LinePlots(), Demo_LinkedAxes(), Demo_LogScale(), Demo_MarkersAndText(), Demo_MultipleAxes(), Demo_NaNValues(), Demo_OffsetAndStride(), Demo_RealtimePlots(), Demo_ShadedPlots(), Demo_StairstepPlots(), Demo_SymmetricLogScale(), Demo_TimeScale(), main(), and MyImPlot::Sparkline().
PlotLine() [2/2]
template<typename T > void ImPlot::PlotLine (const char * label_id, const T * xs, const T * ys, int count, ImPlotLineFlags flags = 0, int offset = 0, int stride = sizeof(T))
Definition at line 1627 of file implot_items.cpp.
References count, flags, getter, offset, PlotLineEx(), stride, xs, and ys.
PlotLine< ImS8 >() [1/2]
template void ImPlot::PlotLine< ImS8 > (const char * label_id, const ImS8 * values, int count, double xscale, double x0, ImPlotLineFlags flags, int offset, int stride)
PlotLine< ImS8 >() [2/2]
template void ImPlot::PlotLine< ImS8 > (const char * label_id, const ImS8 * xs, const ImS8 * ys, int count, ImPlotLineFlags flags, int offset, int stride)
PlotLine< ImU8 >() [1/2]
template void ImPlot::PlotLine< ImU8 > (const char * label_id, const ImU8 * values, int count, double xscale, double x0, ImPlotLineFlags flags, int offset, int stride)
PlotLine< ImU8 >() [2/2]
template void ImPlot::PlotLine< ImU8 > (const char * label_id, const ImU8 * xs, const ImU8 * ys, int count, ImPlotLineFlags flags, int offset, int stride)
PlotLineEx() [1/2]
template<typename _Getter > void ImPlot::PlotLineEx (const char * label_id, const _Getter & getter, ImPlotLineFlags flags)
Definition at line 1574 of file implot_items.cpp.
References BeginItemEx(), ImPlotNextItemData::Colors, EndItem(), flags, ImGui::GetColorU32(), GetItemData(), getter, getter2, ImHasFlag(), ImPlotCol_Fill, ImPlotCol_Line, ImPlotCol_MarkerFill, ImPlotCol_MarkerOutline, ImPlotLineFlags_Loop, ImPlotLineFlags_NoClip, ImPlotLineFlags_Segments, ImPlotLineFlags_Shaded, ImPlotLineFlags_SkipNaN, ImPlotMarker_None, ImPlotNextItemData::LineWeight, ImPlotNextItemData::Marker, ImPlotNextItemData::MarkerSize, ImPlotNextItemData::MarkerWeight, PopPlotClipRect(), PushPlotClipRect(), ImPlotNextItemData::RenderFill, ImPlotNextItemData::RenderLine, ImPlotNextItemData::RenderMarkerFill, and ImPlotNextItemData::RenderMarkerLine.
Referenced by PlotLine(), and PlotLine().
PlotLineEx() [2/2]
ImPlot::PlotLineEx (label_id , getter , flags)
PlotLineG()
void ImPlot::PlotLineG (const char * label_id, ImPlotGetter getter, void * data, int count, ImPlotLineFlags flags = 0)
Referenced by Demo_CustomDataAndGetters(), Demo_LegendOptions(), Demo_SubplotAxisLinking(), Demo_SubplotItemSharing(), and Demo_SubplotsSizing().
PlotPieChart() [1/4]
template void ImPlot::PlotPieChart (const char *const label_ids[], const ImS8 * values, int count, double x, double y, double radius, ImPlotFormatter fmt, void * fmt_data, double angle0, ImPlotPieChartFlags flags)
PlotPieChart() [2/4]
template void ImPlot::PlotPieChart (const char *const label_ids[], const ImU8 * values, int count, double x, double y, double radius, ImPlotFormatter fmt, void * fmt_data, double angle0, ImPlotPieChartFlags flags)
PlotPieChart() [3/4]
template<typename T > void ImPlot::PlotPieChart (const char *const label_ids[], const T * values, int count, double x, double y, double radius, const char * label_fmt = "%.1f", double angle0 = 90, ImPlotPieChartFlags flags = 0)
PlotPieChart() [4/4]
template<typename T > void ImPlot::PlotPieChart (const char *const label_ids[], const T * values, int count, double x, double y, double radius, ImPlotFormatter fmt, void * fmt_data = nullptr, double angle0 = 90, ImPlotPieChartFlags flags = 0)
Referenced by Demo_PieCharts().
PlotPieChart< ImU8 >()
template void ImPlot::PlotPieChart< ImU8 > (const char *const label_ids[], const ImU8 * values, int count, double x, double y, double radius, const char * fmt, double angle0, ImPlotPieChartFlags flags)
PlotPieChartEx()
ImPlot::PlotPieChartEx (label_ids , values , count , center , radius , angle0 , flags)
PlotScatter() [1/2]
template<typename T > void ImPlot::PlotScatter (const char * label_id, const T * values, int count, double xscale = 1, double xstart = 0, ImPlotScatterFlags flags = 0, int offset = 0, int stride = sizeof(T))
Definition at line 1671 of file implot_items.cpp.
References count, flags, getter, offset, PlotScatterEx(), stride, and values.
Referenced by Demo_Annotations(), Demo_CustomStyles(), Demo_ErrorBars(), Demo_Querying(), Demo_ScatterPlots(), Demo_TimeScale(), and main().
PlotScatter() [2/2]
template<typename T > void ImPlot::PlotScatter (const char * label_id, const T * xs, const T * ys, int count, ImPlotScatterFlags flags = 0, int offset = 0, int stride = sizeof(T))
Definition at line 1677 of file implot_items.cpp.
References count, flags, getter, offset, PlotScatterEx(), stride, xs, and ys.
PlotScatter< ImS8 >() [1/2]
template void ImPlot::PlotScatter< ImS8 > (const char * label_id, const ImS8 * values, int count, double xscale, double x0, ImPlotScatterFlags flags, int offset, int stride)
References count, data, getter, and getter_func.
PlotScatter< ImS8 >() [2/2]
template void ImPlot::PlotScatter< ImS8 > (const char * label_id, const ImS8 * xs, const ImS8 * ys, int count, ImPlotScatterFlags flags, int offset, int stride)
PlotScatter< ImU8 >() [1/2]
template void ImPlot::PlotScatter< ImU8 > (const char * label_id, const ImU8 * values, int count, double xscale, double x0, ImPlotScatterFlags flags, int offset, int stride)
PlotScatter< ImU8 >() [2/2]
template void ImPlot::PlotScatter< ImU8 > (const char * label_id, const ImU8 * xs, const ImU8 * ys, int count, ImPlotScatterFlags flags, int offset, int stride)
PlotScatterEx() [1/2]
template<typename Getter > void ImPlot::PlotScatterEx (const char * label_id, const Getter & getter, ImPlotScatterFlags flags)
Definition at line 1649 of file implot_items.cpp.
References BeginItemEx(), ImPlotNextItemData::Colors, EndItem(), flags, ImGui::GetColorU32(), GetItemData(), getter, ImHasFlag(), ImPlotCol_MarkerFill, ImPlotCol_MarkerOutline, ImPlotMarker_Circle, ImPlotMarker_None, ImPlotScatterFlags_NoClip, ImPlotNextItemData::Marker, ImPlotNextItemData::MarkerSize, ImPlotNextItemData::MarkerWeight, PopPlotClipRect(), PushPlotClipRect(), ImPlotNextItemData::RenderMarkerFill, and ImPlotNextItemData::RenderMarkerLine.
Referenced by PlotScatter(), and PlotScatter().
PlotScatterEx() [2/2]
return ImPlot::PlotScatterEx (label_id , getter , flags)
PlotScatterG()
void ImPlot::PlotScatterG (const char * label_id, ImPlotGetter getter, void * data, int count, ImPlotScatterFlags flags = 0)
PlotShaded() [1/3]
template<typename T > void ImPlot::PlotShaded (const char * label_id, const T * values, int count, double yref = 0, double xscale = 1, double xstart = 0, ImPlotShadedFlags flags = 0, int offset = 0, int stride = sizeof(T))
Definition at line 1779 of file implot_items.cpp.
References count, flags, GetPlotLimits(), getter2, IMPLOT_AUTO, ImPlotRange::Max, ImPlotRange::Min, offset, PlotShadedEx(), stride, values, and ImPlotRect::Y.
Referenced by Demo_FilledLinePlots(), Demo_LegendPopups(), Demo_RealtimePlots(), and Demo_ShadedPlots().
PlotShaded() [2/3]
template<typename T > void ImPlot::PlotShaded (const char * label_id, const T * xs, const T * ys, int count, double yref = 0, ImPlotShadedFlags flags = 0, int offset = 0, int stride = sizeof(T))
Definition at line 1790 of file implot_items.cpp.
References count, flags, GetPlotLimits(), getter2, IMPLOT_AUTO, ImPlotRange::Max, ImPlotRange::Min, offset, PlotShadedEx(), stride, xs, ImPlotRect::Y, and ys.
PlotShaded() [3/3]
template<typename T > void ImPlot::PlotShaded (const char * label_id, const T * xs, const T * ys1, const T * ys2, int count, ImPlotShadedFlags flags = 0, int offset = 0, int stride = sizeof(T))
Definition at line 1802 of file implot_items.cpp.
References count, flags, getter2, offset, PlotShadedEx(), stride, and xs.
PlotShaded< ImS8 >() [1/3]
template void ImPlot::PlotShaded< ImS8 > (const char * label_id, const ImS8 * values, int count, double y_ref, double xscale, double x0, ImPlotShadedFlags flags, int offset, int stride)
PlotShaded< ImS8 >() [2/3]
template void ImPlot::PlotShaded< ImS8 > (const char * label_id, const ImS8 * xs, const ImS8 * ys, int count, double y_ref, ImPlotShadedFlags flags, int offset, int stride)
PlotShaded< ImS8 >() [3/3]
template void ImPlot::PlotShaded< ImS8 > (const char * label_id, const ImS8 * xs, const ImS8 * ys1, const ImS8 * ys2, int count, ImPlotShadedFlags flags, int offset, int stride)
PlotShaded< ImU8 >() [1/3]
template void ImPlot::PlotShaded< ImU8 > (const char * label_id, const ImU8 * values, int count, double y_ref, double xscale, double x0, ImPlotShadedFlags flags, int offset, int stride)
PlotShaded< ImU8 >() [2/3]
template void ImPlot::PlotShaded< ImU8 > (const char * label_id, const ImU8 * xs, const ImU8 * ys, int count, double y_ref, ImPlotShadedFlags flags, int offset, int stride)
PlotShaded< ImU8 >() [3/3]
template void ImPlot::PlotShaded< ImU8 > (const char * label_id, const ImU8 * xs, const ImU8 * ys1, const ImU8 * ys2, int count, ImPlotShadedFlags flags, int offset, int stride)
PlotShadedEx() [1/2]
template<typename Getter1 , typename Getter2 > void ImPlot::PlotShadedEx (const char * label_id, const Getter1 & getter1, const Getter2 & getter2, ImPlotShadedFlags flags)
Definition at line 1763 of file implot_items.cpp.
References BeginItemEx(), col, ImPlotNextItemData::Colors, ImPlot::GetterFuncPtr::Count, EndItem(), flags, ImGui::GetColorU32(), GetItemData(), getter2, ImPlotCol_Fill, and ImPlotNextItemData::RenderFill.
Referenced by PlotShaded(), PlotShaded(), and PlotShaded().
PlotShadedEx() [2/2]
ImPlot::PlotShadedEx (label_id , getter1 , getter2 , flags)
PlotShadedG()
void ImPlot::PlotShadedG (const char * label_id, ImPlotGetter getter1, void * data1, ImPlotGetter getter2, void * data2, int count, ImPlotShadedFlags flags = 0)
Referenced by Demo_CustomDataAndGetters().
PlotStairs() [1/2]
template<typename T > void ImPlot::PlotStairs (const char * label_id, const T * values, int count, double xscale = 1, double xstart = 0, ImPlotStairsFlags flags = 0, int offset = 0, int stride = sizeof(T))
Definition at line 1735 of file implot_items.cpp.
References count, flags, getter, offset, PlotStairsEx(), stride, and values.
Referenced by Demo_StairstepPlots().
PlotStairs() [2/2]
template<typename T > void ImPlot::PlotStairs (const char * label_id, const T * xs, const T * ys, int count, ImPlotStairsFlags flags = 0, int offset = 0, int stride = sizeof(T))
Definition at line 1741 of file implot_items.cpp.
References count, flags, getter, offset, PlotStairsEx(), stride, xs, and ys.
PlotStairs< ImS8 >() [1/2]
template void ImPlot::PlotStairs< ImS8 > (const char * label_id, const ImS8 * values, int count, double xscale, double x0, ImPlotStairsFlags flags, int offset, int stride)
References count, data, getter, and getter_func.
PlotStairs< ImS8 >() [2/2]
template void ImPlot::PlotStairs< ImS8 > (const char * label_id, const ImS8 * xs, const ImS8 * ys, int count, ImPlotStairsFlags flags, int offset, int stride)
PlotStairs< ImU8 >() [1/2]
template void ImPlot::PlotStairs< ImU8 > (const char * label_id, const ImU8 * values, int count, double xscale, double x0, ImPlotStairsFlags flags, int offset, int stride)
PlotStairs< ImU8 >() [2/2]
template void ImPlot::PlotStairs< ImU8 > (const char * label_id, const ImU8 * xs, const ImU8 * ys, int count, ImPlotStairsFlags flags, int offset, int stride)
PlotStairsEx() [1/2]
template<typename Getter > void ImPlot::PlotStairsEx (const char * label_id, const Getter & getter, ImPlotStairsFlags flags)
Definition at line 1699 of file implot_items.cpp.
References BeginItemEx(), ImPlotNextItemData::Colors, EndItem(), flags, ImGui::GetColorU32(), GetItemData(), getter, ImHasFlag(), ImPlotCol_Fill, ImPlotCol_Line, ImPlotCol_MarkerFill, ImPlotCol_MarkerOutline, ImPlotMarker_None, ImPlotStairsFlags_PreStep, ImPlotStairsFlags_Shaded, ImPlotNextItemData::LineWeight, ImPlotNextItemData::Marker, ImPlotNextItemData::MarkerSize, ImPlotNextItemData::MarkerWeight, PopPlotClipRect(), PushPlotClipRect(), ImPlotNextItemData::RenderFill, ImPlotNextItemData::RenderLine, ImPlotNextItemData::RenderMarkerFill, and ImPlotNextItemData::RenderMarkerLine.
Referenced by PlotStairs(), and PlotStairs().
PlotStairsEx() [2/2]
return ImPlot::PlotStairsEx (label_id , getter , flags)
PlotStairsG()
void ImPlot::PlotStairsG (const char * label_id, ImPlotGetter getter, void * data, int count, ImPlotStairsFlags flags = 0)
PlotStems() [1/2]
template<typename T > void ImPlot::PlotStems (const char * label_id, const T * values, int count, double ref = 0, double scale = 1, double start = 0, ImPlotStemsFlags flags = 0, int offset = 0, int stride = sizeof(T))
Definition at line 2124 of file implot_items.cpp.
References count, flags, ImHasFlag(), ImPlotStemsFlags_Horizontal, offset, PlotStemsEx(), stride, and values.
Referenced by Demo_AutoFittingData(), and Demo_StemPlots().
PlotStems() [2/2]
template<typename T > void ImPlot::PlotStems (const char * label_id, const T * xs, const T * ys, int count, double ref = 0, ImPlotStemsFlags flags = 0, int offset = 0, int stride = sizeof(T))
Definition at line 2138 of file implot_items.cpp.
References count, flags, ImHasFlag(), ImPlotStemsFlags_Horizontal, offset, PlotStemsEx(), stride, xs, and ys.
PlotStems< ImS8 >() [1/2]
template void ImPlot::PlotStems< ImS8 > (const char * label_id, const ImS8 * values, int count, double ref, double scale, double start, ImPlotStemsFlags flags, int offset, int stride)
PlotStems< ImS8 >() [2/2]
template void ImPlot::PlotStems< ImS8 > (const char * label_id, const ImS8 * xs, const ImS8 * ys, int count, double ref, ImPlotStemsFlags flags, int offset, int stride)
PlotStems< ImU8 >() [1/2]
template void ImPlot::PlotStems< ImU8 > (const char * label_id, const ImU8 * values, int count, double ref, double scale, double start, ImPlotStemsFlags flags, int offset, int stride)
PlotStems< ImU8 >() [2/2]
template void ImPlot::PlotStems< ImU8 > (const char * label_id, const ImU8 * xs, const ImU8 * ys, int count, double ref, ImPlotStemsFlags flags, int offset, int stride)
PlotStemsEx()
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() _GetterB void ImPlot::PlotStemsEx (const char * label_id, const _GetterM & getter_mark, const _GetterB & getter_base, ImPlotStemsFlags flags)
Definition at line 2099 of file implot_items.cpp.
References BeginItemEx(), ImPlotNextItemData::Colors, EndItem(), flags, ImGui::GetColorU32(), GetItemData(), ImPlotCol_Line, ImPlotCol_MarkerFill, ImPlotCol_MarkerOutline, ImPlotMarker_None, ImPlotNextItemData::LineWeight, ImPlotNextItemData::Marker, ImPlotNextItemData::MarkerSize, ImPlotNextItemData::MarkerWeight, PopPlotClipRect(), PushPlotClipRect(), ImPlotNextItemData::RenderLine, ImPlotNextItemData::RenderMarkerFill, and ImPlotNextItemData::RenderMarkerLine.
Referenced by PlotStems(), and PlotStems().
PlotText()
void ImPlot::PlotText (const char * text, double x, double y, const ImVec2 & pix_offset = ImVec2(0,0), ImPlotTextFlags flags = 0)
Definition at line 2813 of file implot_items.cpp.
References ImDrawList::AddText(), AddTextVertical(), ImGui::CalcTextSize(), CalcTextSizeVertical(), ImPlotContext::CurrentPlot, draw_list, FitPoint(), FitThisFrame(), flags, GetPlotDrawList(), GetStyleColorU32(), GImPlot, IM_ASSERT_USER_ERROR, ImHasFlag(), IMPLOT_AUTO, ImPlotCol_InlayText, ImPlotItemFlags_NoFit, ImPlotTextFlags_Vertical, PixelsToPlot(), PlotToPixels(), PopPlotClipRect(), PushPlotClipRect(), SetupLock(), ImVec2::x, x, ImVec2::y, and y.
Referenced by Demo_MarkersAndText().
PlotToPixels() [1/2]
ImVec2 ImPlot::PlotToPixels (const ImPlotPoint & plt, ImAxis x_idx, ImAxis y_idx)
Definition at line 3705 of file implot.cpp.
References PlotToPixels(), ImPlotPoint::x, and ImPlotPoint::y.
PlotToPixels() [2/2]
ImVec2 ImPlot::PlotToPixels (double x, double y, ImAxis x_idx, ImAxis y_idx)
Definition at line 3693 of file implot.cpp.
References ImPlotPlot::Axes, ImPlotContext::CurrentPlot, ImPlotPlot::CurrentX, ImPlotPlot::CurrentY, GImPlot, gp, IM_ASSERT_USER_ERROR, ImAxis_COUNT, ImAxis_X1, ImAxis_Y1, IMPLOT_AUTO, ImPlotAxis::PlotToPixels(), SetupLock(), x, and y.
Referenced by AnnotationV(), Demo_CustomRendering(), DragLineX(), DragLineY(), DragPoint(), DragRect(), if(), MyImPlot::PlotCandlestick(), PlotErrorBarsHEx(), PlotErrorBarsVEx(), PlotImage(), PlotText(), and PlotToPixels().
PopColormap()
void ImPlot::PopColormap (int count)
Definition at line 4545 of file implot.cpp.
References ImVector< T >::back(), ImPlotStyle::Colormap, ImPlotContext::ColormapModifiers, count, GImPlot, gp, IM_ASSERT_USER_ERROR, ImVector< T >::pop_back(), ImVector< T >::Size, and ImPlotContext::Style.
Referenced by Demo_BarStacks(), Demo_CustomStyles(), Demo_Heatmaps(), Demo_Histogram2D(), Demo_OffsetAndStride(), Demo_PieCharts(), and Demo_Tables().
PopPlotClipRect()
ImPlot::PopPlotClipRect ()
Definition at line 4872 of file implot.cpp.
References ImGui::PopClipRect(), and SetupLock().
Referenced by Demo_CustomRendering(), DragLineX(), DragLineY(), DragPoint(), DragRect(), EndItem(), EndPlot(), MyImPlot::PlotCandlestick(), PlotImage(), PlotLineEx(), PlotScatterEx(), PlotStairsEx(), PlotStemsEx(), and PlotText().
PopStyleColor()
void ImPlot::PopStyleColor (int count)
Definition at line 4416 of file implot.cpp.
References ImVector< T >::back(), ImGuiColorMod::BackupValue, ImGuiColorMod::Col, ImPlotContext::ColorModifiers, ImPlotStyle::Colors, count, GImPlot, gp, IM_ASSERT_USER_ERROR, ImVector< T >::pop_back(), ImVector< T >::Size, and ImPlotContext::Style.
Referenced by Demo_DragAndDrop(), Demo_DragRects(), Demo_ErrorBars(), Demo_MarkersAndText(), Demo_StairstepPlots(), and EndSubplots().
PopStyleVar()
void ImPlot::PopStyleVar (int count)
Definition at line 4472 of file implot.cpp.
References ImVector< T >::back(), ImGuiStyleMod::BackupFloat, ImGuiStyleMod::BackupInt, ImPlot::ImPlotStyleVarInfo::Count, count, data, GetPlotStyleVarInfo(), ImPlot::ImPlotStyleVarInfo::GetVarPtr(), GImPlot, gp, IM_ASSERT_USER_ERROR, ImGuiDataType_Float, ImGuiDataType_S32, ImVector< T >::pop_back(), ImVector< T >::Size, ImPlotContext::Style, ImPlotContext::StyleModifiers, ImPlot::ImPlotStyleVarInfo::Type, and ImGuiStyleMod::VarIdx.
Referenced by Demo_CustomDataAndGetters(), Demo_FilledLinePlots(), Demo_LegendPopups(), Demo_ScatterPlots(), Demo_ShadedPlots(), EndSubplots(), and MyImPlot::Sparkline().
Precision()
static int ImPlot::Precision (double val) inline static
Definition at line 1519 of file implot_internal.h.
References OrderOfMagnitude(), and OrderToPrecision().
Referenced by AxisPrecision().
PrimLine()
void ImPlot::PrimLine (ImDrawList & draw_list, const ImVec2 & P1, const ImVec2 & P2, float half_weight, ImU32 col, const ImVec2 & tex_uv0, const ImVec2 tex_uv1) inline
Definition at line 137 of file implot_items.cpp.
References ImDrawList::_IdxWritePtr, ImDrawList::_VtxCurrentIdx, ImDrawList::_VtxWritePtr, ImDrawVert::col, col, draw_list, ImDrawIdx, IMPLOT_NORMALIZE2F_OVER_ZERO, ImDrawVert::pos, ImDrawVert::uv, ImVec2::x, and ImVec2::y.
Referenced by ImPlot::RendererLineStrip< _Getter >::Render(), ImPlot::RendererLineStripSkip< _Getter >::Render(), ImPlot::RendererLineSegments1< _Getter >::Render(), ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Render(), and ImPlot::RendererMarkersLine< _Getter >::Render().
PrimRectFill()
void ImPlot::PrimRectFill (ImDrawList & draw_list, const ImVec2 & Pmin, const ImVec2 & Pmax, ImU32 col, const ImVec2 & uv) inline
Definition at line 170 of file implot_items.cpp.
References ImDrawList::_IdxWritePtr, ImDrawList::_VtxCurrentIdx, ImDrawList::_VtxWritePtr, ImDrawVert::col, col, draw_list, ImDrawIdx, ImDrawVert::pos, ImDrawVert::uv, ImVec2::x, and ImVec2::y.
Referenced by ImPlot::RendererBarsFillV< _Getter1, _Getter2 >::Render(), ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::Render(), ImPlot::RendererStairsPre< _Getter >::Render(), ImPlot::RendererStairsPost< _Getter >::Render(), ImPlot::RendererStairsPreShaded< _Getter >::Render(), ImPlot::RendererStairsPostShaded< _Getter >::Render(), and ImPlot::RendererRectC< _Getter >::Render().
PrimRectLine()
void ImPlot::PrimRectLine (ImDrawList & draw_list, const ImVec2 & Pmin, const ImVec2 & Pmax, float weight, ImU32 col, const ImVec2 & uv) inline
Definition at line 196 of file implot_items.cpp.
References ImDrawList::_IdxWritePtr, ImDrawList::_VtxCurrentIdx, ImDrawList::_VtxWritePtr, ImDrawVert::col, col, draw_list, ImDrawIdx, ImDrawVert::pos, ImDrawVert::uv, ImVec2::x, and ImVec2::y.
Referenced by ImPlot::RendererBarsLineV< _Getter1, _Getter2 >::Render(), and ImPlot::RendererBarsLineH< _Getter1, _Getter2 >::Render().
PushColormap() [1/2]
void ImPlot::PushColormap (const char * name)
Definition at line 4538 of file implot.cpp.
References ImPlotContext::ColormapData, ImPlotColormapData::GetIndex(), GImPlot, gp, IM_ASSERT_USER_ERROR, and PushColormap().
PushColormap() [2/2]
void ImPlot::PushColormap (ImPlotColormap colormap)
Definition at line 4531 of file implot.cpp.
References ImPlotStyle::Colormap, ImPlotContext::ColormapData, ImPlotContext::ColormapModifiers, ImPlotColormapData::Count, GImPlot, gp, IM_ASSERT_USER_ERROR, ImVector< T >::push_back(), and ImPlotContext::Style.
Referenced by Demo_BarStacks(), Demo_CustomStyles(), Demo_Heatmaps(), Demo_Histogram2D(), Demo_OffsetAndStride(), Demo_PieCharts(), Demo_Tables(), and PushColormap().
PushPlotClipRect() [1/2]
ImPlot::PushPlotClipRect ()
Referenced by BeginItem(), Demo_CustomRendering(), DragLineX(), DragLineY(), DragPoint(), DragRect(), EndPlot(), MyImPlot::PlotCandlestick(), PlotImage(), PlotLineEx(), PlotScatterEx(), PlotStairsEx(), PlotStemsEx(), and PlotText().
PushPlotClipRect() [2/2]
void ImPlot::PushPlotClipRect (float expand)
Definition at line 4863 of file implot.cpp.
References ImPlotContext::CurrentPlot, ImRect::Expand(), GImPlot, gp, IM_ASSERT_USER_ERROR, ImRect::Max, ImRect::Min, ImPlotPlot::PlotRect, ImGui::PushClipRect(), and SetupLock().
PushStyleColor() [1/2]
void ImPlot::PushStyleColor (ImPlotCol idx, const ImVec4 & col)
Definition at line 4407 of file implot.cpp.
References ImGuiColorMod::BackupValue, ImGuiColorMod::Col, col, ImPlotContext::ColorModifiers, ImPlotStyle::Colors, GImPlot, gp, ImVector< T >::push_back(), and ImPlotContext::Style.
PushStyleColor() [2/2]
void ImPlot::PushStyleColor (ImPlotCol idx, ImU32 col)
Definition at line 4398 of file implot.cpp.
References ImGuiColorMod::BackupValue, ImGuiColorMod::Col, col, ImGui::ColorConvertU32ToFloat4(), ImPlotContext::ColorModifiers, ImPlotStyle::Colors, GImPlot, gp, ImVector< T >::push_back(), and ImPlotContext::Style.
Referenced by BeginSubplots(), Demo_DragAndDrop(), Demo_DragRects(), Demo_ErrorBars(), Demo_MarkersAndText(), and Demo_StairstepPlots().
PushStyleVar() [1/3]
void ImPlot::PushStyleVar (ImPlotStyleVar idx, const ImVec2 & val)
Definition at line 4458 of file implot.cpp.
References ImPlot::ImPlotStyleVarInfo::Count, GetPlotStyleVarInfo(), ImPlot::ImPlotStyleVarInfo::GetVarPtr(), GImPlot, gp, IM_ASSERT, ImGuiDataType_Float, ImVector< T >::push_back(), ImPlotContext::Style, ImPlotContext::StyleModifiers, and ImPlot::ImPlotStyleVarInfo::Type.
PushStyleVar() [2/3]
void ImPlot::PushStyleVar (ImPlotStyleVar idx, float val)
Definition at line 4428 of file implot.cpp.
References ImPlot::ImPlotStyleVarInfo::Count, GetPlotStyleVarInfo(), ImPlot::ImPlotStyleVarInfo::GetVarPtr(), GImPlot, gp, IM_ASSERT, ImGuiDataType_Float, ImVector< T >::push_back(), ImPlotContext::Style, ImPlotContext::StyleModifiers, and ImPlot::ImPlotStyleVarInfo::Type.
Referenced by BeginSubplots(), Demo_CustomDataAndGetters(), Demo_FilledLinePlots(), Demo_LegendPopups(), Demo_ScatterPlots(), Demo_ShadedPlots(), and MyImPlot::Sparkline().
PushStyleVar() [3/3]
void ImPlot::PushStyleVar (ImPlotStyleVar idx, int val)
Definition at line 4440 of file implot.cpp.
References ImPlot::ImPlotStyleVarInfo::Count, float(), GetPlotStyleVarInfo(), ImPlot::ImPlotStyleVarInfo::GetVarPtr(), GImPlot, gp, IM_ASSERT, ImGuiDataType_Float, ImGuiDataType_S32, ImVector< T >::push_back(), ImPlotContext::Style, ImPlotContext::StyleModifiers, and ImPlot::ImPlotStyleVarInfo::Type.
RandomColor()
ImVec4 ImPlot::RandomColor ()
Definition at line 87 of file implot_demo.cpp.
References col, RandomRange(), ImPlotPoint::x, and ImPlotPoint::y.
Referenced by Demo_DragAndDrop().
RandomGauss()
double ImPlot::RandomGauss ()
Definition at line 96 of file implot_demo.cpp.
References X.
Referenced by ImPlot::NormalDistribution< N >::NormalDistribution().
RandomRange()
template<typename T > T ImPlot::RandomRange (T min, T max) inline
Definition at line 82 of file implot_demo.cpp.
Referenced by Demo_FilledLinePlots(), Demo_Heatmaps(), Demo_Querying(), Demo_ShadedPlots(), Demo_Tables(), and RandomColor().
RangesOverlap()
static bool ImPlot::RangesOverlap (const ImPlotRange & r1, const ImPlotRange & r2) inline static
Definition at line 1426 of file implot_internal.h.
References ImPlotRange::Max, and ImPlotRange::Min.
RegisterOrGetItem()
ImPlotItem * ImPlot::RegisterOrGetItem (const char * label_id, ImPlotItemFlags flags, bool * just_created = nullptr)
Definition at line 288 of file implot_items.cpp.
References ImGuiTextBuffer::append(), ImPlotContext::CurrentItems, ImGui::FindRenderedTextEnd(), flags, ImPlotItemGroup::GetItem(), ImPlotItemGroup::GetItemID(), ImPlotItemGroup::GetItemIndex(), ImPlotItemGroup::GetOrAddItem(), GImPlot, gp, ImPlotItem::ID, ImHasFlag(), ImPlotItemFlags_NoLegend, ImPlotLegend::Indices, ImPlotLegend::Labels, ImPlotItemGroup::Legend, ImPlotItem::NameOffset, ImVector< T >::push_back(), ImPlotItem::SeenThisFrame, ImPlotItem::Show, and ImGuiTextBuffer::size().
Referenced by BeginItem().
RenderColorBar()
IMPLOT_API void ImPlot::RenderColorBar (const ImU32 * colors, int size, ImDrawList & DrawList, const ImRect & bounds, bool vert, bool reversed, bool continuous)
Definition at line 4599 of file implot.cpp.
References ImDrawList::AddRectFilledMultiColor(), ImRect::GetHeight(), ImRect::GetWidth(), ImRect::Max, ImRect::Min, ImRect::TranslateX(), ImRect::TranslateY(), ImVec2::x, and ImVec2::y.
Referenced by ColormapButton(), ColormapIcon(), ColormapScale(), and ColormapSlider().
RenderGridLinesX()
static void ImPlot::RenderGridLinesX (ImDrawList & DrawList, const ImPlotTicker & ticker, const ImRect & rect, ImU32 col_maj, ImU32 col_min, float size_maj, float size_min) inline static
Definition at line 1781 of file implot.cpp.
References ImDrawList::AddLine(), col_maj, ImGui::ColorConvertFloat4ToU32(), ImGui::ColorConvertU32ToFloat4(), density, ImRect::GetWidth(), ImClamp(), ImRemap(), ImPlotTick::Level, ImPlotTick::Major, ImRect::Max, ImRect::Min, ImPlotTick::PixelPos, ImPlotTicker::TickCount(), ImPlotTicker::Ticks, ImVec4::w, ImVec2::x, and ImVec2::y.
Referenced by EndPlot(), and SetupFinish().
RenderGridLinesY()
static void ImPlot::RenderGridLinesY (ImDrawList & DrawList, const ImPlotTicker & ticker, const ImRect & rect, ImU32 col_maj, ImU32 col_min, float size_maj, float size_min) inline static
Definition at line 1799 of file implot.cpp.
References ImDrawList::AddLine(), col_maj, ImGui::ColorConvertFloat4ToU32(), ImGui::ColorConvertU32ToFloat4(), density, ImRect::GetHeight(), ImClamp(), ImRemap(), ImPlotTick::Major, ImRect::Max, ImRect::Min, ImPlotTick::PixelPos, ImPlotTicker::TickCount(), ImPlotTicker::Ticks, ImVec4::w, ImVec2::x, and ImVec2::y.
Referenced by EndPlot(), and SetupFinish().
RenderHeatmap()
template<typename T > void ImPlot::RenderHeatmap (ImDrawList & draw_list, const T * values, int rows, int cols, double scale_min, double scale_max, const char * fmt, const ImPlotPoint & bounds_min, const ImPlotPoint & bounds_max, bool reverse_y, bool col_maj)
Definition at line 2451 of file implot_items.cpp.
References ImDrawList::AddRectFilled(), ImDrawList::AddText(), CalcTextColor(), ImGui::CalcTextSize(), col, col_maj, ImPlotStyle::Colormap, draw_list, fmt, GetColormapColorU32(), getter, GImPlot, gp, ImClamp(), ImFormatString(), ImMinMaxArray(), ImRemap01(), SampleColormap(), ImPlotContext::Style, values, ImPlotPoint::x, and ImPlotPoint::y.
Referenced by if(), and PlotHeatmap().
RenderMarkers()
template<typename _Getter > void ImPlot::RenderMarkers (const _Getter & getter, ImPlotMarker marker, float size, bool rend_fill, ImU32 col_fill, bool rend_line, ImU32 col_line, float weight)
Definition at line 1541 of file implot_items.cpp.
References getter, ImPlotMarker_Asterisk, ImPlotMarker_Circle, ImPlotMarker_Cross, ImPlotMarker_Diamond, ImPlotMarker_Down, ImPlotMarker_Left, ImPlotMarker_Plus, ImPlotMarker_Right, ImPlotMarker_Square, ImPlotMarker_Up, MARKER_FILL_CIRCLE, MARKER_FILL_DIAMOND, MARKER_FILL_DOWN, MARKER_FILL_LEFT, MARKER_FILL_RIGHT, MARKER_FILL_SQUARE, MARKER_FILL_UP, MARKER_LINE_ASTERISK, MARKER_LINE_CIRCLE, MARKER_LINE_CROSS, MARKER_LINE_DIAMOND, MARKER_LINE_DOWN, MARKER_LINE_LEFT, MARKER_LINE_PLUS, MARKER_LINE_RIGHT, MARKER_LINE_SQUARE, and MARKER_LINE_UP.
RenderPrimitives1()
template<template< class > class _Renderer, class _Getter , typename ... Args> void ImPlot::RenderPrimitives1 (const _Getter & getter, Args... args)
Definition at line 1404 of file implot_items.cpp.
References draw_list, GetCurrentPlot(), GetPlotDrawList(), getter, ImPlotPlot::PlotRect, and RenderPrimitivesEx().
RenderPrimitives2()
template<template< class, class > class _Renderer, class _Getter1 , class _Getter2 , typename ... Args> void ImPlot::RenderPrimitives2 (const _Getter1 & getter1, const _Getter2 & getter2, Args... args)
Definition at line 1411 of file implot_items.cpp.
References draw_list, GetCurrentPlot(), GetPlotDrawList(), getter2, ImPlotPlot::PlotRect, and RenderPrimitivesEx().
RenderPrimitivesEx()
template<class _Renderer > void ImPlot::RenderPrimitivesEx (const _Renderer & renderer, ImDrawList & draw_list, const ImRect & cull_rect)
Renders primitive shapes in bulk as efficiently as possible.
Definition at line 1365 of file implot_items.cpp.
References ImDrawList::_VtxCurrentIdx, draw_list, ImMin(), ImDrawList::PrimReserve(), and ImDrawList::PrimUnreserve().
Referenced by RenderPrimitives1(), and RenderPrimitives2().
RenderSelectionRect()
static void ImPlot::RenderSelectionRect (ImDrawList & DrawList, const ImVec2 & p_min, const ImVec2 & p_max, const ImVec4 & col) inline static
Definition at line 1815 of file implot.cpp.
References ImDrawList::AddRect(), ImDrawList::AddRectFilled(), col, and ImGui::GetColorU32().
Referenced by EndPlot().
ResetCtxForNextAlignedPlots()
IMPLOT_API void ImPlot::ResetCtxForNextAlignedPlots (ImPlotContext * ctx)
Definition at line 522 of file implot.cpp.
References ImPlotContext::CurrentAlignmentH, and ImPlotContext::CurrentAlignmentV.
Referenced by EndAlignedPlots(), and Initialize().
ResetCtxForNextPlot()
IMPLOT_API void ImPlot::ResetCtxForNextPlot (ImPlotContext * ctx)
Definition at line 504 of file implot.cpp.
References ImPlotContext::Annotations, ImPlotContext::CurrentItem, ImPlotContext::CurrentPlot, ImPlotContext::DigitalPlotItemCnt, ImPlotContext::DigitalPlotOffset, ImPlotContext::NextItemData, ImPlotContext::NextPlotData, ImPlotContext::OpenContextThisFrame, ImPlotContext::PreviousItem, ImPlotAnnotationCollection::Reset(), ImPlotTagCollection::Reset(), ImPlotNextPlotData::Reset(), ImPlotNextItemData::Reset(), and ImPlotContext::Tags.
Referenced by BeginPlot(), EndPlot(), and Initialize().
ResetCtxForNextSubplot()
IMPLOT_API void ImPlot::ResetCtxForNextSubplot (ImPlotContext * ctx)
Definition at line 527 of file implot.cpp.
References ImPlotContext::CurrentAlignmentH, ImPlotContext::CurrentAlignmentV, and ImPlotContext::CurrentSubplot.
Referenced by EndSubplots(), and Initialize().
resize()
bin_counts ImPlot::resize (bins)
RoundAxisValue()
static double ImPlot::RoundAxisValue (const ImPlotAxis & axis, double value) inline static
Definition at line 1596 of file implot.cpp.
References AxisPrecision(), and RoundTo().
Referenced by LabelAxisValue().
RoundTime()
IMPLOT_API ImPlotTime ImPlot::RoundTime (const ImPlotTime & t, ImPlotTimeUnit unit)
Definition at line 1047 of file implot.cpp.
References AddTime(), FloorTime(), ImPlotTime::S, and ImPlotTime::Us.
Referenced by MyImPlot::PlotCandlestick().
RoundTo()
static double ImPlot::RoundTo (double val, int prec) inline static
Definition at line 1521 of file implot_internal.h.
Referenced by RoundAxisValue().
SampleColormap()
ImVec4 ImPlot::SampleColormap (float t, ImPlotColormap cmap)
Definition at line 4595 of file implot.cpp.
References ImGui::ColorConvertU32ToFloat4(), and SampleColormapU32().
Referenced by Demo_SubplotsSizing(), and RenderHeatmap().
SampleColormapU32()
IMPLOT_API ImU32 ImPlot::SampleColormapU32 (float t, ImPlotColormap cmap)
Definition at line 4588 of file implot.cpp.
References ImPlotStyle::Colormap, ImPlotContext::ColormapData, ImPlotColormapData::Count, GImPlot, gp, IM_ASSERT_USER_ERROR, IMPLOT_AUTO, ImPlotColormapData::LerpTable(), and ImPlotContext::Style.
Referenced by SampleColormap().
SetAxes()
void ImPlot::SetAxes (ImAxis x_idx, ImAxis y_idx)
Definition at line 3665 of file implot.cpp.
References ImPlotPlot::Axes, ImPlotContext::CurrentPlot, ImPlotPlot::CurrentX, ImPlotPlot::CurrentY, ImPlotAxis::Enabled, GImPlot, gp, IM_ASSERT_USER_ERROR, ImAxis_COUNT, ImAxis_X1, ImAxis_Y1, and SetupLock().
Referenced by Demo_EqualAxes(), Demo_MultipleAxes(), and Demo_Tags().
SetAxis()
void ImPlot::SetAxis (ImAxis axis)
Definition at line 3653 of file implot.cpp.
References ImPlotPlot::Axes, ImPlotContext::CurrentPlot, ImPlotPlot::CurrentX, ImPlotPlot::CurrentY, ImPlotAxis::Enabled, GImPlot, gp, IM_ASSERT_USER_ERROR, ImAxis_COUNT, ImAxis_X1, ImAxis_Y1, and SetupLock().
Referenced by Demo_DragAndDrop().
SetCurrentContext()
void ImPlot::SetCurrentContext (ImPlotContext * ctx)
Definition at line 457 of file implot.cpp.
References GImPlot.
Referenced by CreateContext(), and DestroyContext().
SetImGuiContext()
void ImPlot::SetImGuiContext (ImGuiContext * ctx)
Definition at line 433 of file implot.cpp.
References ImGui::SetCurrentContext().
SetNextAxesLimits()
void ImPlot::SetNextAxesLimits (double x_min, double x_max, double y_min, double y_max, ImPlotCond cond)
Definition at line 2359 of file implot.cpp.
References ImAxis_X1, ImAxis_Y1, and SetNextAxisLimits().
SetNextAxesToFit()
void ImPlot::SetNextAxesToFit ()
Definition at line 2364 of file implot.cpp.
References ImAxis_COUNT, and SetNextAxisToFit().
SetNextAxisLimits()
void ImPlot::SetNextAxisLimits (ImAxis axis, double v_min, double v_max, ImPlotCond cond)
Definition at line 2336 of file implot.cpp.
References ImPlotContext::CurrentPlot, GImPlot, gp, ImPlotNextPlotData::HasRange, IM_ASSERT, IM_ASSERT_USER_ERROR, ImIsPowerOfTwo(), ImPlotRange::Max, ImPlotRange::Min, ImPlotContext::NextPlotData, ImPlotNextPlotData::Range, and ImPlotNextPlotData::RangeCond.
Referenced by SetNextAxesLimits().
SetNextAxisLinks()
void ImPlot::SetNextAxisLinks (ImAxis axis, double * link_min, double * link_max)
Definition at line 2346 of file implot.cpp.
References ImPlotContext::CurrentPlot, GImPlot, gp, IM_ASSERT_USER_ERROR, ImPlotNextPlotData::LinkedMax, ImPlotNextPlotData::LinkedMin, and ImPlotContext::NextPlotData.
Referenced by SubplotSetCell().
SetNextAxisToFit()
void ImPlot::SetNextAxisToFit (ImAxis axis)
Definition at line 2353 of file implot.cpp.
References ImPlotContext::CurrentPlot, ImPlotNextPlotData::Fit, GImPlot, gp, IM_ASSERT_USER_ERROR, and ImPlotContext::NextPlotData.
Referenced by SetNextAxesToFit().
SetNextErrorBarStyle()
void ImPlot::SetNextErrorBarStyle (const ImVec4 & col = ImVec4(0,0,0,-1), float size = -1, float weight = -1)
Definition at line 347 of file implot_items.cpp.
References col, ImPlotNextItemData::Colors, ImPlotNextItemData::ErrorBarSize, ImPlotNextItemData::ErrorBarWeight, GImPlot, gp, ImPlotCol_ErrorBar, and ImPlotContext::NextItemData.
Referenced by Demo_ErrorBars().
SetNextFillStyle()
void ImPlot::SetNextFillStyle (const ImVec4 & col = ImVec4(0,0,0,-1), float alpha_mod = -1)
Definition at line 332 of file implot_items.cpp.
References col, ImPlotNextItemData::Colors, ImPlotNextItemData::FillAlpha, GImPlot, gp, ImPlotCol_Fill, and ImPlotContext::NextItemData.
Referenced by Demo_Histogram(), Demo_LegendPopups(), Demo_RealtimePlots(), Demo_StairstepPlots(), and MyImPlot::Sparkline().
SetNextLineStyle()
void ImPlot::SetNextLineStyle (const ImVec4 & col = ImVec4(0,0,0,-1), float weight = -1)
Definition at line 326 of file implot_items.cpp.
References col, ImPlotNextItemData::Colors, GImPlot, gp, ImPlotCol_Line, ImPlotNextItemData::LineWeight, and ImPlotContext::NextItemData.
Referenced by Demo_DragAndDrop(), Demo_DragLines(), Demo_DragPoints(), Demo_LegendPopups(), Demo_SubplotsSizing(), and MyImPlot::Sparkline().
SetNextMarkerStyle()
void ImPlot::SetNextMarkerStyle (ImPlotMarker marker = -1, float size = -1, const ImVec4 & fill = ImVec4(0,0,0,-1), float weight = -1, const ImVec4 & outline = ImVec4(0,0,0,-1))
Definition at line 338 of file implot_items.cpp.
References ImPlotNextItemData::Colors, GImPlot, gp, ImPlotCol_MarkerFill, ImPlotCol_MarkerOutline, ImPlotNextItemData::Marker, ImPlotNextItemData::MarkerSize, ImPlotNextItemData::MarkerWeight, and ImPlotContext::NextItemData.
Referenced by Demo_ErrorBars(), Demo_LegendPopups(), Demo_LinePlots(), Demo_MarkersAndText(), Demo_NaNValues(), Demo_Querying(), Demo_ScatterPlots(), Demo_StairstepPlots(), and Demo_StemPlots().
SetupAxes()
void ImPlot::SetupAxes (const char * x_label, const char * y_label, ImPlotAxisFlags x_flags, ImPlotAxisFlags y_flags)
Definition at line 2297 of file implot.cpp.
References ImAxis_X1, ImAxis_Y1, and SetupAxis().
Referenced by Demo_AutoFittingData(), Demo_AxisConstraints(), Demo_BarGroups(), Demo_BarStacks(), Demo_CustomPlottersAndTooltips(), Demo_CustomStyles(), Demo_DragPoints(), Demo_DragRects(), Demo_FilledLinePlots(), Demo_Heatmaps(), Demo_Histogram(), Demo_Histogram2D(), Demo_InfiniteLines(), Demo_LinePlots(), Demo_MarkersAndText(), Demo_MultipleAxes(), Demo_PieCharts(), Demo_RealtimePlots(), Demo_StairstepPlots(), Demo_SubplotsSizing(), main(), and MyImPlot::Sparkline().
SetupAxesLimits()
void ImPlot::SetupAxesLimits (double x_min, double x_max, double y_min, double y_max, ImPlotCond cond)
Definition at line 2302 of file implot.cpp.
References ImAxis_X1, ImAxis_Y1, and SetupAxisLimits().
Referenced by Demo_Annotations(), Demo_AxisConstraints(), Demo_CustomPlottersAndTooltips(), Demo_CustomStyles(), Demo_DragLines(), Demo_DragPoints(), Demo_DragRects(), Demo_ErrorBars(), Demo_FilledLinePlots(), Demo_Heatmaps(), Demo_Histogram2D(), Demo_LegendPopups(), Demo_LogScale(), Demo_MarkersAndText(), Demo_MultipleAxes(), Demo_PieCharts(), Demo_Querying(), Demo_StairstepPlots(), Demo_SubplotAxisLinking(), Demo_TickLabels(), Demo_TimeScale(), and MyImPlot::Sparkline().
SetupAxis()
void ImPlot::SetupAxis (ImAxis idx, const char * label, ImPlotAxisFlags flags)
Definition at line 2126 of file implot.cpp.
References ImPlotPlot::Axes, ImPlotContext::CurrentPlot, ImPlotAxis::Enabled, ImPlotAxis::Flags, flags, GImPlot, gp, ImPlotAxis::ID, ImPlotPlot::ID, IM_ASSERT_USER_ERROR, ImPlotPlot::JustCreated, ImPlotAxis::PreviousFlags, ImPlotPlot::SetAxisLabel(), ImPlotPlot::SetupLocked, and UpdateAxisColors().
Referenced by BeginPlot(), BeginPlot(), Demo_CustomScale(), Demo_DragAndDrop(), Demo_EqualAxes(), Demo_MultipleAxes(), Demo_Tags(), Demo_TickLabels(), and SetupAxes().
SetupAxisFormat() [1/2]
void ImPlot::SetupAxisFormat (ImAxis idx, const char * fmt)
Definition at line 2160 of file implot.cpp.
References ImPlotPlot::Axes, ImPlotContext::CurrentPlot, ImPlotAxis::Enabled, fmt, ImPlotAxis::FormatSpec, GImPlot, gp, ImPlotAxis::HasFormatSpec, IM_ASSERT_USER_ERROR, ImStrncpy(), and ImPlotPlot::SetupLocked.
Referenced by Demo_CustomPlottersAndTooltips(), and Demo_TickLabels().
SetupAxisFormat() [2/2]
void ImPlot::SetupAxisFormat (ImAxis idx, ImPlotFormatter formatter, void * data)
Definition at line 2184 of file implot.cpp.
References ImPlotPlot::Axes, ImPlotContext::CurrentPlot, data, ImPlotAxis::Enabled, ImPlotAxis::Formatter, ImPlotAxis::FormatterData, GImPlot, gp, IM_ASSERT_USER_ERROR, and ImPlotPlot::SetupLocked.
SetupAxisLimits()
void ImPlot::SetupAxisLimits (ImAxis idx, double min_lim, double max_lim, ImPlotCond cond)
Definition at line 2147 of file implot.cpp.
References ImPlotPlot::Axes, ImPlotContext::CurrentPlot, ImPlotAxis::Enabled, GImPlot, gp, ImPlotAxis::HasRange, IM_ASSERT_USER_ERROR, ImPlotCond_Always, ImPlotPlot::Initialized, ImPlotAxis::RangeCond, ImPlotAxis::SetRange(), and ImPlotPlot::SetupLocked.
Referenced by Demo_Config(), Demo_DigitalPlots(), Demo_MultipleAxes(), Demo_RealtimePlots(), Demo_StemPlots(), main(), and SetupAxesLimits().
SetupAxisLimitsConstraints()
void ImPlot::SetupAxisLimitsConstraints (ImAxis idx, double v_min, double v_max)
Definition at line 2275 of file implot.cpp.
References ImPlotPlot::Axes, ImPlotAxis::ConstraintRange, ImPlotContext::CurrentPlot, ImPlotAxis::Enabled, GImPlot, gp, IM_ASSERT_USER_ERROR, ImPlotRange::Max, ImPlotRange::Min, and ImPlotPlot::SetupLocked.
Referenced by Demo_AxisConstraints(), Demo_CustomPlottersAndTooltips(), and Demo_CustomScale().
SetupAxisLinks()
void ImPlot::SetupAxisLinks (ImAxis idx, double * min_lnk, double * max_lnk)
Definition at line 2172 of file implot.cpp.
References ImPlotPlot::Axes, ImPlotContext::CurrentPlot, ImPlotAxis::Enabled, GImPlot, gp, IM_ASSERT_USER_ERROR, ImPlotAxis::LinkedMax, ImPlotAxis::LinkedMin, ImPlotAxis::PullLinks(), and ImPlotPlot::SetupLocked.
Referenced by Demo_LinkedAxes().
SetupAxisScale() [1/2]
void ImPlot::SetupAxisScale (ImAxis idx, ImPlotScale scale)
Definition at line 2220 of file implot.cpp.
References ImPlotPlot::Axes, ImPlotAxis::ConstraintRange, ImPlotContext::CurrentPlot, ImPlotAxis::Enabled, GImPlot, gp, IM_ASSERT_USER_ERROR, IMPLOT_MAX_TIME, IMPLOT_MIN_TIME, ImPlotScale_Log10, ImPlotScale_SymLog, ImPlotScale_Time, ImPlotTicker::Levels, ImPlotAxis::Locator, Locator_Log10(), Locator_SymLog(), Locator_Time(), ImPlotAxis::Scale, ImPlotPlot::SetupLocked, ImPlotAxis::Ticker, ImPlotAxis::TransformData, ImPlotAxis::TransformForward, TransformForward_Log10(), TransformForward_SymLog(), ImPlotAxis::TransformInverse, TransformInverse_Log10(), and TransformInverse_SymLog().
Referenced by Demo_Config(), Demo_CustomPlottersAndTooltips(), Demo_CustomScale(), Demo_LogScale(), Demo_SymmetricLogScale(), and Demo_TimeScale().
SetupAxisScale() [2/2]
void ImPlot::SetupAxisScale (ImAxis idx, ImPlotTransform fwd, ImPlotTransform inv, void * data)
Definition at line 2262 of file implot.cpp.
References ImPlotPlot::Axes, ImPlotContext::CurrentPlot, data, ImPlotAxis::Enabled, GImPlot, gp, IM_ASSERT_USER_ERROR, IMPLOT_AUTO, ImPlotAxis::Scale, ImPlotPlot::SetupLocked, ImPlotAxis::TransformData, ImPlotAxis::TransformForward, and ImPlotAxis::TransformInverse.
SetupAxisTicks() [1/2]
void ImPlot::SetupAxisTicks (ImAxis idx, const double * values, int n_ticks, const char *const labels[], bool show_default)
Definition at line 2195 of file implot.cpp.
References AddTicksCustom(), ImPlotPlot::Axes, ImPlotContext::CurrentPlot, ImPlotAxis::Enabled, ImPlotAxis::FormatSpec, ImPlotAxis::Formatter, Formatter_Default(), ImPlotAxis::FormatterData, GImPlot, gp, ImPlotAxis::HasFormatSpec, IM_ASSERT_USER_ERROR, IMPLOT_LABEL_FORMAT, ImPlotPlot::SetupLocked, ImPlotAxis::ShowDefaultTicks, ImPlotAxis::Ticker, and values.
Referenced by Demo_BarGroups(), Demo_BarStacks(), Demo_Heatmaps(), Demo_TickLabels(), and SetupAxisTicks().
SetupAxisTicks() [2/2]
void ImPlot::SetupAxisTicks (ImAxis idx, double v_min, double v_max, int n_ticks, const char *const labels[], bool show_default)
Definition at line 2211 of file implot.cpp.
References ImPlotContext::CurrentPlot, ImVector< T >::Data, FillRange(), GImPlot, gp, IM_ASSERT_USER_ERROR, SetupAxisTicks(), ImPlotPlot::SetupLocked, and ImPlotContext::TempDouble1.
SetupAxisZoomConstraints()
void ImPlot::SetupAxisZoomConstraints (ImAxis idx, double z_min, double z_max)
Definition at line 2286 of file implot.cpp.
References ImPlotPlot::Axes, ImPlotAxis::ConstraintZoom, ImPlotContext::CurrentPlot, ImPlotAxis::Enabled, GImPlot, gp, IM_ASSERT_USER_ERROR, ImPlotRange::Max, ImPlotRange::Min, and ImPlotPlot::SetupLocked.
Referenced by Demo_AxisConstraints(), and Demo_CustomPlottersAndTooltips().
SetupFinish()
void ImPlot::SetupFinish ()
Definition at line 2467 of file implot.cpp.
References ImDrawList::AddRectFilled(), ImDrawList::AddText(), AddTextVertical(), ImPlotPlot::Axes, ImPlotPlot::AxesRect, CalcLegendSize(), ImGui::CalcTextSize(), CalcTextSizeVertical(), ImPlotAxis::CanInitFit(), ImPlotPlot::CanvasRect, ImPlotAxis::ColorAct, ImPlotAxis::ColorBg, ImPlotAxis::ColorHiLi, ImPlotAxis::ColorHov, ImPlotAxis::ColorMaj, ImPlotAxis::ColorMin, ImPlotAxis::ColorTxt, ImPlotAxis::Constrain(), ImPlotContext::CurrentAlignmentH, ImPlotContext::CurrentAlignmentV, ImPlotContext::CurrentItems, ImPlotContext::CurrentPlot, ImGuiContext::CurrentWindow, ImPlotAxis::Datum1, ImPlotAxis::Datum2, ImGuiWindow::DrawList, ImPlotAxis::Enabled, ImPlotNextPlotData::Fit, ImPlotAxis::FitThisFrame, ImPlotPlot::FitThisFrame, ImPlotAxis::Flags, ImPlotLegend::Flags, ImPlotPlot::Flags, ImPlotAxis::FormatSpec, ImPlotAxis::Formatter, Formatter_Default(), ImPlotAxis::FormatterData, ImPlotPlot::FrameRect, ImGuiStyle::FrameRounding, ImPlotAxis::GetAspect(), ImPlotPlot::GetAxisLabel(), ImRect::GetCenter(), ImRect::GetHeight(), ImPlotItemGroup::GetLegendCount(), GetStyleColorU32(), ImPlotTicker::GetText(), ImGui::GetTextLineHeight(), ImPlotPlot::GetTitle(), ImRect::GetWidth(), GImGui, GImPlot, gp, ImPlotAxis::HasFormatSpec, ImPlotAxis::HasGridLines(), ImPlotAxis::HasLabel(), ImPlotAxis::HasRange, ImPlotAxis::HasTickLabels(), ImPlotPlot::HasTitle(), ImPlotAxis::Held, ImPlotPlot::Held, ImPlotAxis::Hovered, ImPlotAxis::HoverRect, ImPlotItemGroup::ID, IM_ASSERT_USER_ERROR, IM_COL32_BLACK_TRANS, IM_ROUND, ImAlmostEqual(), ImAxis_COUNT, ImAxis_X1, ImAxis_Y1, ImHasFlag(), ImMax(), ImMin(), IMPLOT_LABEL_FORMAT, IMPLOT_NUM_X_AXES, IMPLOT_NUM_Y_AXES, ImPlotAxisFlags_NoHighlight, ImPlotCol_FrameBg, ImPlotCol_PlotBg, ImPlotFlags_Equal, ImPlotFlags_NoFrame, ImPlotFlags_NoInputs, ImPlotFlags_NoLegend, ImPlotLegendFlags_Horizontal, ImPlotLegendFlags_Outside, ImPlotLocation_East, ImPlotLocation_North, ImPlotLocation_South, ImPlotLocation_West, ImPlotPlot::Initialized, ImPlotAxis::IsAutoFitting(), ImPlotAxis::IsForeground(), ImPlotAxis::IsInputLocked(), ImPlotAxis::IsInverted(), ImPlotAxis::IsOpposite(), ImPlotPlot::Items, ImPlotStyle::LabelPadding, ImPlotTick::LabelSize, ImPlotItemGroup::Legend, ImPlotStyle::LegendInnerPadding, ImPlotStyle::LegendPadding, ImPlotStyle::LegendSpacing, ImPlotTick::Level, ImPlotTicker::Levels, ImPlotLegend::Location, ImPlotAxis::Locator, Locator_Default(), ImPlotStyle::MajorGridSize, ImRect::Max, ImPlotTicker::MaxSize, ImRect::Min, ImPlotStyle::MinorGridSize, ImPlotContext::NextPlotData, ImPlotAxis::OrthoAxis, PadAndDatumAxesX(), PadAndDatumAxesY(), ImPlotAxis::PixelMax, ImPlotAxis::PixelMin, ImPlotTick::PixelPos, ImPlotStyle::PlotPadding, ImPlotTick::PlotPos, ImPlotPlot::PlotRect, ImPlotAxis::PlotToPixels(), ImGui::PushOverrideID(), ImPlotAxis::Range, ImGui::RenderFrame(), RenderGridLinesX(), RenderGridLinesY(), ImPlotLegend::Reset(), ImPlotAxis::SetAspect(), ImPlotPlot::SetupLocked, ImPlotAxis::ShowDefaultTicks, ImPlotTick::ShowLabel, ImGuiContext::Style, ImPlotContext::Style, ImPlotTicker::TickCount(), ImPlotAxis::Ticker, ImPlotTicker::Ticks, UpdateInput(), ImPlotAxis::UpdateTransformCache(), ImPlotAxis::WillRender(), ImVec2::x, ImPlotPlot::XAxis(), ImVec2::y, and ImPlotPlot::YAxis().
Referenced by SetupLock().
SetupLegend()
void ImPlot::SetupLegend (ImPlotLocation location, ImPlotLegendFlags flags)
Definition at line 2307 of file implot.cpp.
References ImPlotContext::CurrentItems, ImPlotContext::CurrentPlot, ImPlotContext::CurrentSubplot, ImPlotLegend::Flags, flags, GImPlot, gp, IM_ASSERT_USER_ERROR, ImPlotItemGroup::Legend, ImPlotLegend::Location, ImPlotLegend::PreviousFlags, ImPlotLegend::PreviousLocation, and ImPlotPlot::SetupLocked.
Referenced by Demo_BarGroups(), Demo_BarStacks(), Demo_LegendOptions(), Demo_ShadedPlots(), and Demo_SubplotItemSharing().
SetupLock()
static void ImPlot::SetupLock () inline static
Definition at line 1311 of file implot_internal.h.
References ImPlotContext::CurrentPlot, GImPlot, gp, SetupFinish(), and ImPlotPlot::SetupLocked.
Referenced by Annotation(), AnnotationV(), BeginDragDropSourceAxis(), BeginDragDropSourceItem(), BeginDragDropSourcePlot(), BeginDragDropTargetAxis(), BeginDragDropTargetLegend(), BeginDragDropTargetPlot(), BeginItem(), BeginLegendPopup(), CancelPlotSelection(), DragLineX(), DragLineY(), DragPoint(), DragRect(), EndDragDropSource(), EndDragDropTarget(), EndLegendPopup(), EndPlot(), GetPlotLimits(), GetPlotMousePos(), GetPlotPos(), GetPlotSelection(), GetPlotSize(), IsAxisHovered(), IsLegendEntryHovered(), IsPlotHovered(), IsPlotSelected(), PixelsToPlot(), PlotText(), PlotToPixels(), PopPlotClipRect(), PushPlotClipRect(), SetAxes(), SetAxis(), Tag(), and TagV().
SetupMouseText()
void ImPlot::SetupMouseText (ImPlotLocation location, ImPlotMouseTextFlags flags)
Definition at line 2324 of file implot.cpp.
References ImPlotContext::CurrentPlot, flags, GImPlot, gp, IM_ASSERT_USER_ERROR, ImPlotPlot::MouseTextFlags, ImPlotPlot::MouseTextLocation, and ImPlotPlot::SetupLocked.
ShowAltLegend()
IMPLOT_API void ImPlot::ShowAltLegend (const char * title_id, bool vertical, const ImVec2 size, bool interactable)
Definition at line 4250 of file implot.cpp.
References ImDrawList::AddRect(), ImDrawList::AddRectFilled(), ImGui::CalcItemSize(), CalcLegendSize(), ImRect::Contains(), ImGuiContext::CurrentWindow, ImGuiWindowTempData::CursorPos, ImGuiWindow::DC, ImGuiWindow::DrawList, ImGuiStyle::FrameRounding, ImGui::GetIO(), GetLocationPos(), GetPlot(), GetStyleColorU32(), GImGui, GImPlot, gp, ImPlotCol_FrameBg, ImPlotCol_LegendBg, ImPlotCol_LegendBorder, ImGui::ItemAdd(), ImPlotPlot::Items, ImGui::ItemSize(), ImPlotStyle::LegendInnerPadding, ImPlotStyle::LegendPadding, ImPlotStyle::LegendSpacing, ImRect::Max, ImRect::Min, ImDrawList::PopClipRect(), ImDrawList::PushClipRect(), ImGui::RenderFrame(), ShowLegendEntries(), ImGuiWindow::SkipItems, ImGuiContext::Style, ImPlotContext::Style, ImVec2::x, and ImVec2::y.
ShowAxisContextMenu()
IMPLOT_API void ImPlot::ShowAxisContextMenu (ImPlotAxis & axis, ImPlotAxis * equal_axis, bool)
Definition at line 1348 of file implot.cpp.
References AddTime(), BeginDisabledControls(), ImGui::BeginMenu(), ImGui::Checkbox(), ImGui::CheckboxFlags(), CombineDateTime(), DragFloat(), EndDisabledControls(), ImGui::EndMenu(), ImPlotAxis::Flags, ImPlotTime::FromDouble(), ImPlotAxis::GetAspect(), ImPlotAxis::HasGridLines(), ImPlotAxis::HasLabel(), ImPlotAxis::HasTickLabels(), ImPlotAxis::HasTickMarks(), ImFlipFlag(), ImPlotAxisFlags_AutoFit, ImPlotAxisFlags_Invert, ImPlotAxisFlags_LockMax, ImPlotAxisFlags_LockMin, ImPlotAxisFlags_NoGridLines, ImPlotAxisFlags_NoLabel, ImPlotAxisFlags_NoTickLabels, ImPlotAxisFlags_NoTickMarks, ImPlotAxisFlags_Opposite, ImPlotScale_Time, ImPlotTimeUnit_S, ImPlotAxis::IsAutoFitting(), ImPlotAxis::IsLockedMax(), ImPlotAxis::IsLockedMin(), ImPlotAxis::IsRangeLocked(), ImPlotAxis::LabelOffset, ImPlotRange::Max, ImPlotRange::Min, ImPlotAxis::PickerLevel, ImPlotAxis::PickerTimeMax, ImPlotAxis::PickerTimeMin, ImGui::PushItemWidth(), ImPlotAxis::Range, ImGui::SameLine(), ImPlotAxis::Scale, ImGui::Separator(), ImPlotAxis::SetAspect(), ImPlotAxis::SetMax(), ImPlotAxis::SetMin(), ImPlotAxis::SetRange(), ShowDatePicker(), ShowTimePicker(), ImPlotRange::Size(), and ImPlotTime::ToDouble().
Referenced by EndPlot(), and ShowPlotContextMenu().
ShowAxisMetrics()
void ImPlot::ShowAxisMetrics (const ImPlotPlot & plot, const ImPlotAxis & axis)
Definition at line 5218 of file implot.cpp.
References ImGui::BulletText(), ImPlotAxis::Flags, ImPlotAxis::GetAspect(), ImPlotPlot::GetAxisLabel(), ImPlotAxis::HasRange, ImPlotAxis::Held, ImPlotAxis::Hovered, ImPlotAxis::ID, ImPlotAxis::LabelOffset, ImPlotAxis::LinkedMax, ImPlotAxis::LinkedMin, ImPlotRange::Max, ImPlotRange::Min, ImPlotAxis::OrthoAxis, ImPlotAxis::PixelMax, ImPlotAxis::PixelMin, ImPlotAxis::PixelSize(), ImPlotAxis::Range, ImPlotAxis::ScaleMax, ImPlotAxis::ScaleToPixel, ShowTicksMetrics(), ImPlotAxis::Ticker, ImGui::TreeNode(), and ImGui::TreePop().
Referenced by ShowMetricsWindow().
ShowColormapSelector()
bool ImPlot::ShowColormapSelector (const char * label)
Definition at line 4905 of file implot.cpp.
References ImGui::BeginCombo(), BustItemCache(), ImPlotStyle::Colormap, ImPlotContext::ColormapData, ImPlotColormapData::Count, ImGui::EndCombo(), ImPlotColormapData::GetName(), GImPlot, gp, ImGui::Selectable(), and ImPlotContext::Style.
Referenced by Demo_Config().
ShowDatePicker()
IMPLOT_API bool ImPlot::ShowDatePicker (const char * id, int * level, ImPlotTime * t, const ImPlotTime * t1, const ImPlotTime * t2)
Definition at line 5455 of file implot.cpp.
References AddTime(), ImGui::ArrowButtonEx(), BeginDisabledControls(), ImGui::BeginGroup(), ImGui::Button(), ImGuiStyle::Colors, ImGui::Dummy(), EndDisabledControls(), ImGui::EndGroup(), FloorTime(), GetDaysInMonth(), ImGui::GetFrameHeight(), ImGui::GetStyle(), GetTime(), GetYear(), GImPlot, ImFormatString(), ImGuiCol_Button, ImGuiCol_Text, ImGuiCol_TextDisabled, ImGuiDir_Down, ImGuiDir_Up, ImGuiItemFlags_Disabled, ImGuiStyleVar_ItemSpacing, ImPlotTimeUnit_Day, ImPlotTimeUnit_Mo, ImPlotTimeUnit_Yr, MakeTime(), MONTH_ABRVS, MONTH_NAMES, ImGui::PopID(), ImGui::PopItemFlag(), ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGui::PushID(), ImGui::PushItemFlag(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), ImGui::SameLine(), ImPlotContext::Tm, WD_ABRVS, ImVec2::x, and ImVec2::y.
Referenced by ShowAxisContextMenu().
ShowDemoWindow()
void ImPlot::ShowDemoWindow (bool * p_open = nullptr)
Definition at line 2191 of file implot_demo.cpp.
References ImGuiIO::BackendFlags, ImGui::Begin(), ImGui::BeginMenu(), ImGui::BeginMenuBar(), ImGui::BeginTabBar(), ImGui::BeginTabItem(), Demo_Annotations(), Demo_AutoFittingData(), Demo_AxisConstraints(), Demo_BarGroups(), Demo_BarPlots(), Demo_BarStacks(), Demo_ColormapWidgets(), Demo_Config(), Demo_CustomDataAndGetters(), Demo_CustomPlottersAndTooltips(), Demo_CustomRendering(), Demo_CustomScale(), Demo_CustomStyles(), Demo_DigitalPlots(), Demo_DragAndDrop(), Demo_DragLines(), Demo_DragPoints(), Demo_DragRects(), Demo_EqualAxes(), Demo_ErrorBars(), Demo_FilledLinePlots(), Demo_Heatmaps(), Demo_Help(), Demo_Histogram(), Demo_Histogram2D(), Demo_Images(), Demo_InfiniteLines(), Demo_LegendOptions(), Demo_LegendPopups(), Demo_LinePlots(), Demo_LinkedAxes(), Demo_LogScale(), Demo_MarkersAndText(), Demo_MultipleAxes(), Demo_NaNValues(), Demo_OffsetAndStride(), Demo_PieCharts(), Demo_Querying(), Demo_RealtimePlots(), Demo_ScatterPlots(), Demo_ShadedPlots(), Demo_StairstepPlots(), Demo_StemPlots(), Demo_SubplotAxisLinking(), Demo_SubplotItemSharing(), Demo_SubplotsSizing(), Demo_SymmetricLogScale(), Demo_Tables(), Demo_Tags(), Demo_TickLabels(), Demo_TimeScale(), DemoHeader(), ImGui::End(), ImGui::EndMenu(), ImGui::EndMenuBar(), ImGui::EndTabBar(), ImGui::EndTabItem(), ImGui::GetIO(), ImDrawIdx, ImGuiBackendFlags_RendererHasVtxOffset, ImGuiCol_Text, ImGuiCond_Appearing, ImGuiCond_FirstUseEver, ImGuiWindowFlags_MenuBar, IMPLOT_VERSION, IMPLOT_VERSION_NUM, ImGui::MenuItem(), ImGui::PopStyleColor(), ImGui::PushStyleColor(), ImGui::Separator(), ImGui::SetNextWindowPos(), ImGui::SetNextWindowSize(), ImGui::ShowDemoWindow(), ImGui::ShowMetricsWindow(), ShowMetricsWindow(), ImGui::ShowStyleEditor(), ShowStyleEditor(), ImGui::Spacing(), ImGui::Text(), and ImGui::TextWrapped().
Referenced by main().
ShowInputMapping()
void ImPlot::ShowInputMapping ()
Definition at line 249 of file implot_demo.cpp.
References ImPlotInputMap::Fit, GetInputMap(), InputMapping(), ImPlotInputMap::Menu, ImPlotInputMap::OverrideMod, ImPlotInputMap::Pan, ImPlotInputMap::PanMod, ImPlotInputMap::Select, ImPlotInputMap::SelectCancel, ImPlotInputMap::SelectHorzMod, ImPlotInputMap::SelectMod, ImPlotInputMap::SelectVertMod, ImGui::SliderFloat(), ImPlotInputMap::ZoomMod, and ImPlotInputMap::ZoomRate.
ShowInputMapSelector()
bool ImPlot::ShowInputMapSelector (const char * label)
Definition at line 4922 of file implot.cpp.
References ImGui::Combo(), MapInputDefault(), and MapInputReverse().
Referenced by Demo_Config().
ShowLegendContextMenu()
IMPLOT_API bool ImPlot::ShowLegendContextMenu (ImPlotLegend & legend, bool visible)
Definition at line 1463 of file implot.cpp.
References ImGui::Button(), ImPlotLegend::CanGoInside, ImGui::Checkbox(), ImGui::CheckboxFlags(), ImPlotLegend::Flags, ImGui::GetFrameHeight(), ImGuiStyleVar_ItemSpacing, ImHasFlag(), ImPlotLegendFlags_Horizontal, ImPlotLegendFlags_Outside, ImPlotLocation_East, ImPlotLocation_North, ImPlotLocation_NorthEast, ImPlotLocation_NorthWest, ImPlotLocation_South, ImPlotLocation_SouthEast, ImPlotLocation_SouthWest, ImPlotLocation_West, ImGui::InvisibleButton(), ImPlotLegend::Location, ImGui::PopStyleVar(), ImGui::PushStyleVar(), ImGui::RadioButton(), and ImGui::SameLine().
Referenced by EndPlot(), EndSubplots(), and ShowPlotContextMenu().
ShowLegendEntries()
IMPLOT_API bool ImPlot::ShowLegendEntries (ImPlotItemGroup & items, const ImRect & legend_bb, bool hovered, const ImVec2 & pad, const ImVec2 & spacing, bool vertical, ImDrawList & DrawList)
Definition at line 629 of file implot.cpp.
References ImDrawList::AddRectFilled(), ImDrawList::AddText(), ImGui::ButtonBehavior(), ImGui::CalcTextSize(), ImPlotItem::Color, ImVector< T >::Data, ImGui::FindRenderedTextEnd(), ImPlotLegend::Flags, ImGui::GetColorU32(), ImPlotItemGroup::GetLegendCount(), ImPlotItemGroup::GetLegendItem(), ImPlotItemGroup::GetLegendLabel(), GetStyleColorU32(), ImGui::GetTextLineHeight(), GImPlot, gp, ImPlotItem::ID, ImAlphaU32(), ImGuiCol_TextDisabled, ImHasFlag(), ImMixU32(), ImPlotCol_LegendText, ImPlotLegendFlags_NoButtons, ImPlotLegendFlags_NoHighlightAxis, ImPlotLegendFlags_NoHighlightItem, ImPlotLegendFlags_Reverse, ImPlotLegendFlags_Sort, ImGui::KeepAliveID(), ImPlotItemGroup::Legend, ImPlotItem::LegendHovered, ImPlotItem::LegendHoverRect, LegendSortingComp(), ImRect::Max, ImRect::Min, ImVector< T >::resize(), ImPlotItem::Show, ImPlotContext::SortItems, ImPlotContext::TempInt1, ImVec2::x, and ImVec2::y.
Referenced by EndPlot(), EndSubplots(), and ShowAltLegend().
ShowMetricsWindow()
void ImPlot::ShowMetricsWindow (bool * p_popen)
Definition at line 5245 of file implot.cpp.
References ImDrawList::AddRect(), ImPlotPlot::Axes, ImPlotPlot::AxesRect, ImGui::Begin(), ImGuiTextBuffer::Buf, ImGui::Bullet(), ImGui::BulletText(), BustItemCache(), BustPlotCache(), ImGui::Button(), ImPlotPlot::CanvasRect, ImGui::Checkbox(), col, ImPlotItem::Color, ImGui::ColorButton(), ImGui::ColorConvertFloat4ToU32(), ImGui::ColorConvertU32ToFloat4(), ImGui::ColorEdit4(), ImPlotContext::ColormapData, ColormapSlider(), ImPlotPlot::ContextLocked, ImPlotColormapData::Count, count, ImVector< T >::Data, ImPlotAxis::Enabled, ImGui::End(), ImPlotPlot::Flags, ImPlotSubplot::Flags, ImPlotSubplot::FrameHovered, ImGuiIO::Framerate, ImPlotPlot::FrameRect, ImPlotSubplot::FrameRect, ImPool< T >::GetBufSize(), ImPool< T >::GetByIndex(), ImGui::GetForegroundDrawList(), ImGui::GetFrameHeight(), ImGui::GetIO(), ImPlotItemGroup::GetItemByIndex(), ImPlotItemGroup::GetItemCount(), ImPlotColormapData::GetKeyCount(), ImPlotItemGroup::GetLegendCount(), ImPlotColormapData::GetName(), ImGui::GetStyle(), ImPlotColormapData::GetTableColor(), ImPlotColormapData::GetTableSize(), ImPlotPlot::GetTitle(), GImPlot, gp, ImPlotSubplot::GridRect, ImPlotPlot::HasTitle(), ImPlotPlot::Held, ImPlotLegend::Hovered, ImPlotPlot::Hovered, ImPlotAxis::HoverRect, ImPlotAxis::ID, ImPlotItem::ID, ImPlotPlot::ID, ImPlotSubplot::ID, IM_COL32, ImAxis_COUNT, ImFormatString(), ImGuiCol_FrameBg, ImGuiColorEditFlags_NoInputs, ImGuiStyleVar_ItemSpacing, IMPLOT_NUM_X_AXES, IMPLOT_NUM_Y_AXES, IMPLOT_VERSION, ImGui::Indent(), ImPlotPlot::Initialized, ImPlotColormapData::IsQual(), ImPlotPlot::Items, ImPlotSubplot::Items, ImGuiStyle::ItemSpacing, ImPlotLegend::Labels, ImPlotItemGroup::Legend, ImPlotItem::LegendHovered, ImRect::Max, ImRect::Min, ImGuiIO::MousePos, ImPlotItem::NameOffset, ImPlotPlot::PlotRect, ImPlotContext::Plots, ImGui::PopID(), ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGui::PushID(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), ImPlotLegend::Rect, ImPlotLegend::RectClamped, ImGui::SameLine(), ImPlotPlot::Selected, ImPlotPlot::Selecting, ImGui::Separator(), ImGui::SetNextItemWidth(), ImPlotItem::Show, ShowAxisMetrics(), ImVector< T >::Size, ImPlotContext::Subplots, ImPlotColormapData::Tables, ImGui::Text(), ImGui::TreeNode(), ImGui::TreePop(), ImGui::Unindent(), ImVec2::x, ImVec4::x, ImPlotPlot::XAxis(), ImVec2::y, and ImPlotPlot::YAxis().
Referenced by ShowDemoWindow().
ShowPlotContextMenu()
IMPLOT_API void ImPlot::ShowPlotContextMenu (ImPlotPlot & plot)
Definition at line 1516 of file implot.cpp.
References BeginDisabledControls(), ImGui::BeginMenu(), ImPlotContext::CurrentItems, ImPlotContext::CurrentSubplot, ImPlotAxis::Enabled, EndDisabledControls(), ImGui::EndMenu(), ImPlotLegend::Flags, ImPlotPlot::Flags, ImPlotSubplot::Flags, ImPlotPlot::GetAxisLabel(), GImPlot, gp, ImPlotAxis::HasLabel(), ImPlotAxis::HasMenus(), ImPlotPlot::HasTitle(), ImFlipFlag(), ImFormatString(), ImHasFlag(), IMPLOT_NUM_X_AXES, IMPLOT_NUM_Y_AXES, ImPlotFlags_Crosshairs, ImPlotFlags_Equal, ImPlotFlags_NoBoxSelect, ImPlotFlags_NoLegend, ImPlotFlags_NoMouseText, ImPlotFlags_NoTitle, ImPlotLegendFlags_NoMenus, ImPlotSubplotFlags_NoLegend, ImPlotSubplotFlags_NoMenus, ImPlotPlot::Items, ImPlotSubplot::Items, ImPlotItemGroup::Legend, ImGui::MenuItem(), ImPlotAxis::OrthoAxis, ImGui::PopID(), ImGui::PushID(), ImGui::Separator(), ShowAxisContextMenu(), ShowLegendContextMenu(), ShowSubplotsContextMenu(), ImPlotPlot::TitleOffset, ImPlotPlot::XAxis(), and ImPlotPlot::YAxis().
Referenced by EndPlot().
ShowStyleEditor()
void ImPlot::ShowStyleEditor (ImPlotStyle * ref)
Definition at line 4937 of file implot.cpp.
References AddColormap(), ImPlotStyle::AnnotationPadding, ImGui::BeginGroup(), ImGui::BeginTabBar(), ImGui::BeginTabItem(), BustItemCache(), ImGui::Button(), ImGui::Checkbox(), col, ImGui::ColorConvertFloat4ToU32(), ImGui::ColorConvertU32ToFloat4(), ImGui::ColorEdit4(), ImPlotStyle::Colormap, ColormapButton(), ImPlotContext::ColormapData, ImPlotStyle::Colors, ImGui::Combo(), ImPlotColormapData::Count, ImVector< T >::Data, ImPlotStyle::DigitalBitGap, ImPlotStyle::DigitalBitHeight, ImGuiTextFilter::Draw(), ImGui::EndGroup(), ImGui::EndTabBar(), ImGui::EndTabItem(), ImPlotStyle::ErrorBarSize, ImPlotStyle::ErrorBarWeight, ImPlotStyle::FillAlpha, ImPlotStyle::FitPadding, GetColormapColorU32(), GetColormapName(), GetColormapSize(), ImGui::GetFontSize(), ImPlotColormapData::GetIndex(), ImPlotColormapData::GetKeyColor(), ImPlotColormapData::GetKeyCount(), ImGui::GetStyle(), GetStyle(), GetStyleColorName(), GetStyleColorVec4(), GImPlot, gp, HelpMarker(), ImGuiColorEditFlags_AlphaOpaque, ImGuiColorEditFlags_AlphaPreview, ImGuiColorEditFlags_AlphaPreviewHalf, ImGuiColorEditFlags_NoInputs, ImGuiColorEditFlags_None, ImGuiInputTextFlags_CharsNoBlank, ImGuiStyleVar_Alpha, IMPLOT_AUTO_COL, ImPlotCol_COUNT, ImGui::InputText(), IsColorAuto(), ImPlotStyle::LabelPadding, ImPlotStyle::LegendInnerPadding, ImPlotStyle::LegendPadding, ImPlotStyle::LegendSpacing, ImPlotStyle::LineWeight, ImGui::LogFinish(), ImGui::LogText(), ImGui::LogToClipboard(), ImGui::LogToTTY(), ImPlotStyle::MajorGridSize, ImPlotStyle::MajorTickLen, ImPlotStyle::MajorTickSize, ImPlotStyle::MarkerSize, ImPlotStyle::MarkerWeight, ImPlotStyle::MinorAlpha, ImPlotStyle::MinorGridSize, ImPlotStyle::MinorTickLen, ImPlotStyle::MinorTickSize, ImPlotStyle::MousePosPadding, ImGuiTextFilter::PassFilter(), ImPlotStyle::PlotBorderSize, ImPlotStyle::PlotDefaultSize, ImPlotStyle::PlotMinSize, ImPlotStyle::PlotPadding, ImVector< T >::pop_back(), ImGui::PopID(), ImGui::PopItemWidth(), ImGui::PopStyleVar(), ImVector< T >::push_back(), ImGui::PushID(), ImGui::PushItemWidth(), ImGui::PushStyleVar(), ImGui::RadioButton(), ImGui::SameLine(), ImGui::Separator(), ImPlotColormapData::SetKeyColor(), ImGui::SetNextItemWidth(), ShowStyleSelector(), ImVector< T >::Size, ImGui::SliderFloat(), ImGui::SliderFloat2(), ImPlotContext::Style, ImGui::Text(), ImVec4::x, ImPlotPoint::x, x, and ImPlotPoint::y.
Referenced by ShowDemoWindow().
ShowStyleSelector()
bool ImPlot::ShowStyleSelector (const char * label)
Definition at line 4888 of file implot.cpp.
References ImGui::Combo(), StyleColorsAuto(), StyleColorsClassic(), StyleColorsDark(), and StyleColorsLight().
Referenced by Demo_Config(), and ShowStyleEditor().
ShowSubplotsContextMenu()
IMPLOT_API void ImPlot::ShowSubplotsContextMenu (ImPlotSubplot & subplot)
Definition at line 1489 of file implot.cpp.
References BeginDisabledControls(), ImGui::BeginMenu(), EndDisabledControls(), ImGui::EndMenu(), ImPlotSubplot::Flags, ImPlotSubplot::HasTitle, ImFlipFlag(), ImHasFlag(), ImPlotSubplotFlags_LinkAllX, ImPlotSubplotFlags_LinkAllY, ImPlotSubplotFlags_LinkCols, ImPlotSubplotFlags_LinkRows, ImPlotSubplotFlags_NoAlign, ImPlotSubplotFlags_NoResize, ImPlotSubplotFlags_NoTitle, ImPlotSubplotFlags_ShareItems, and ImGui::MenuItem().
Referenced by ShowPlotContextMenu().
ShowTicksMetrics()
void ImPlot::ShowTicksMetrics (const ImPlotTicker & ticker)
Definition at line 5213 of file implot.cpp.
References ImGui::BulletText(), ImPlotTicker::MaxSize, ImPlotTicker::TickCount(), ImVec2::x, and ImVec2::y.
Referenced by ShowAxisMetrics().
ShowTimePicker()
IMPLOT_API bool ImPlot::ShowTimePicker (const char * id, ImPlotTime * t)
Definition at line 5666 of file implot.cpp.
References ImGui::BeginCombo(), ImGui::Button(), ImGui::CalcTextSize(), ImGui::EndCombo(), ImGui::GetFrameHeight(), ImGui::GetStyle(), ImGui::GetStyleColorVec4(), GetTime(), GImPlot, gp, height, ImGuiCol_Button, ImGuiCol_ButtonHovered, ImGuiCol_FrameBg, ImGuiCol_FrameBgHovered, ImGuiComboFlags_NoArrowButton, ImGuiStyleVar_ItemSpacing, ImGuiStyleVar_ScrollbarSize, ImGuiStyle::ItemSpacing, MkTime(), ImGui::PopID(), ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGui::PushID(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), ImGui::SameLine(), ImGui::Selectable(), ImGui::SetNextItemWidth(), ImPlotContext::Style, ImGui::Text(), ImPlotContext::Tm, ImPlotStyle::Use24HourClock, width, and ImVec2::x.
Referenced by ShowAxisContextMenu().
ShowUserGuide()
void ImPlot::ShowUserGuide ()
Definition at line 5187 of file implot.cpp.
References ImGui::BulletText(), ImGui::Indent(), and ImGui::Unindent().
Referenced by Demo_Help().
SinewaveGetter()
ImPlotPoint ImPlot::SinewaveGetter (int i, void * data)
Definition at line 1278 of file implot_demo.cpp.
References data.
Referenced by Demo_SubplotAxisLinking(), Demo_SubplotItemSharing(), and Demo_SubplotsSizing().
StyleColorsAuto()
void ImPlot::StyleColorsAuto (ImPlotStyle * dst)
Definition at line 5763 of file implot.cpp.
References ImPlotStyle::Colors, GetStyle(), IMPLOT_AUTO_COL, ImPlotCol_AxisBg, ImPlotCol_AxisBgActive, ImPlotCol_AxisBgHovered, ImPlotCol_AxisGrid, ImPlotCol_AxisText, ImPlotCol_AxisTick, ImPlotCol_Crosshairs, ImPlotCol_ErrorBar, ImPlotCol_Fill, ImPlotCol_FrameBg, ImPlotCol_InlayText, ImPlotCol_LegendBg, ImPlotCol_LegendBorder, ImPlotCol_LegendText, ImPlotCol_Line, ImPlotCol_MarkerFill, ImPlotCol_MarkerOutline, ImPlotCol_PlotBg, ImPlotCol_PlotBorder, ImPlotCol_Selection, ImPlotCol_TitleText, and ImPlotStyle::MinorAlpha.
Referenced by ImPlotStyle::ImPlotStyle(), and ShowStyleSelector().
StyleColorsClassic()
void ImPlot::StyleColorsClassic (ImPlotStyle * dst)
Definition at line 5793 of file implot.cpp.
References ImPlotStyle::Colors, GetStyle(), IMPLOT_AUTO_COL, ImPlotCol_AxisBg, ImPlotCol_AxisBgActive, ImPlotCol_AxisBgHovered, ImPlotCol_AxisGrid, ImPlotCol_AxisText, ImPlotCol_AxisTick, ImPlotCol_Crosshairs, ImPlotCol_ErrorBar, ImPlotCol_Fill, ImPlotCol_FrameBg, ImPlotCol_InlayText, ImPlotCol_LegendBg, ImPlotCol_LegendBorder, ImPlotCol_LegendText, ImPlotCol_Line, ImPlotCol_MarkerFill, ImPlotCol_MarkerOutline, ImPlotCol_PlotBg, ImPlotCol_PlotBorder, ImPlotCol_Selection, ImPlotCol_TitleText, and ImPlotStyle::MinorAlpha.
Referenced by ShowStyleSelector().
StyleColorsDark()
void ImPlot::StyleColorsDark (ImPlotStyle * dst)
Definition at line 5822 of file implot.cpp.
References ImPlotStyle::Colors, GetStyle(), IMPLOT_AUTO_COL, ImPlotCol_AxisBg, ImPlotCol_AxisBgActive, ImPlotCol_AxisBgHovered, ImPlotCol_AxisGrid, ImPlotCol_AxisText, ImPlotCol_AxisTick, ImPlotCol_Crosshairs, ImPlotCol_ErrorBar, ImPlotCol_Fill, ImPlotCol_FrameBg, ImPlotCol_InlayText, ImPlotCol_LegendBg, ImPlotCol_LegendBorder, ImPlotCol_LegendText, ImPlotCol_Line, ImPlotCol_MarkerFill, ImPlotCol_MarkerOutline, ImPlotCol_PlotBg, ImPlotCol_PlotBorder, ImPlotCol_Selection, ImPlotCol_TitleText, and ImPlotStyle::MinorAlpha.
Referenced by ShowStyleSelector().
StyleColorsLight()
void ImPlot::StyleColorsLight (ImPlotStyle * dst)
Definition at line 5851 of file implot.cpp.
References ImPlotStyle::Colors, GetStyle(), IMPLOT_AUTO_COL, ImPlotCol_AxisBg, ImPlotCol_AxisBgActive, ImPlotCol_AxisBgHovered, ImPlotCol_AxisGrid, ImPlotCol_AxisText, ImPlotCol_AxisTick, ImPlotCol_Crosshairs, ImPlotCol_ErrorBar, ImPlotCol_Fill, ImPlotCol_FrameBg, ImPlotCol_InlayText, ImPlotCol_LegendBg, ImPlotCol_LegendBorder, ImPlotCol_LegendText, ImPlotCol_Line, ImPlotCol_MarkerFill, ImPlotCol_MarkerOutline, ImPlotCol_PlotBg, ImPlotCol_PlotBorder, ImPlotCol_Selection, ImPlotCol_TitleText, and ImPlotStyle::MinorAlpha.
Referenced by ShowStyleSelector().
SubplotNextCell()
IMPLOT_API void ImPlot::SubplotNextCell ()
Definition at line 3336 of file implot.cpp.
References ImPlotSubplot::CurrentIdx, ImPlotContext::CurrentSubplot, GImPlot, gp, and SubplotSetCell().
Referenced by EndPlot().
SubplotSetCell() [1/2]
void ImPlot::SubplotSetCell (int idx)
Definition at line 3319 of file implot.cpp.
References col, ImPlotSubplot::Cols, ImPlotContext::CurrentSubplot, ImPlotSubplot::Flags, GImPlot, gp, ImHasFlag(), ImPlotSubplotFlags_ColMajor, ImPlotSubplot::Rows, and SubplotSetCell().
SubplotSetCell() [2/2]
void ImPlot::SubplotSetCell (int row, int col)
Definition at line 3278 of file implot.cpp.
References ImPlotSubplot::CellSize, col, ImPlotSubplot::ColAlignmentData, ImPlotSubplot::ColLinkData, ImPlotSubplot::ColRatios, ImPlotSubplot::Cols, ImPlotContext::CurrentAlignmentH, ImPlotContext::CurrentAlignmentV, ImPlotSubplot::CurrentIdx, ImPlotContext::CurrentSubplot, ImGuiWindowTempData::CursorPos, ImGuiWindow::DC, ImPlotSubplot::Flags, ImGui::GetCurrentWindow(), ImRect::GetHeight(), ImRect::GetSize(), ImRect::GetWidth(), GImPlot, gp, ImPlotSubplot::GridRect, IM_ROUND, ImAxis_X1, ImAxis_Y1, ImHasFlag(), ImPlotSubplotFlags_ColMajor, ImPlotSubplotFlags_LinkAllX, ImPlotSubplotFlags_LinkAllY, ImPlotSubplotFlags_LinkCols, ImPlotSubplotFlags_LinkRows, ImPlotSubplotFlags_NoAlign, ImRect::Min, ImPlotSubplot::RowAlignmentData, ImPlotSubplot::RowLinkData, ImPlotSubplot::RowRatios, ImPlotSubplot::Rows, SetNextAxisLinks(), ImVec2::x, and ImVec2::y.
Referenced by BeginSubplots(), SubplotNextCell(), and SubplotSetCell().
Tag() [1/2]
void ImPlot::Tag (ImAxis axis, double v, const ImVec4 & col, const char * fmt, ...)
Definition at line 3846 of file implot.cpp.
References col, fmt, and TagV().
Referenced by Tag(), TagX(), and TagY().
Tag() [2/2]
void ImPlot::Tag (ImAxis axis, double v, const ImVec4 & color, bool round)
Definition at line 3853 of file implot.cpp.
References ImPlotPlot::Axes, ImPlotContext::CurrentPlot, GImPlot, gp, IMPLOT_LABEL_MAX_SIZE, LabelAxisValue(), SetupLock(), and Tag().
TagV()
void ImPlot::TagV (ImAxis axis, double v, const ImVec4 & col, const char * fmt, va_list args)
Definition at line 3838 of file implot.cpp.
References ImPlotTagCollection::AppendV(), CalcTextColor(), col, fmt, ImGui::GetColorU32(), GetStyleColorU32(), GImPlot, gp, ImPlotCol_AxisText, SetupLock(), and ImPlotContext::Tags.
Referenced by Tag(), TagX(), TagXV(), TagY(), and TagYV().
TagX() [1/2]
void ImPlot::TagX (double x, const ImVec4 & color, bool round)
Definition at line 3862 of file implot.cpp.
References ImPlotContext::CurrentPlot, ImPlotPlot::CurrentX, GImPlot, gp, IM_ASSERT_USER_ERROR, Tag(), and x.
Referenced by Demo_Tags().
TagX() [2/2]
void ImPlot::TagX (double x, const ImVec4 & color, const char * fmt, ...)
Definition at line 3868 of file implot.cpp.
References ImPlotContext::CurrentPlot, ImPlotPlot::CurrentX, fmt, GImPlot, gp, IM_ASSERT_USER_ERROR, TagV(), and x.
TagXV()
void ImPlot::TagXV (double x, const ImVec4 & color, const char * fmt, va_list args)
Definition at line 3877 of file implot.cpp.
References ImPlotContext::CurrentPlot, ImPlotPlot::CurrentX, fmt, GImPlot, gp, IM_ASSERT_USER_ERROR, TagV(), and x.
TagY() [1/2]
void ImPlot::TagY (double y, const ImVec4 & color, bool round)
Definition at line 3883 of file implot.cpp.
References ImPlotContext::CurrentPlot, ImPlotPlot::CurrentY, GImPlot, gp, IM_ASSERT_USER_ERROR, Tag(), and y.
Referenced by Demo_Tags().
TagY() [2/2]
void ImPlot::TagY (double y, const ImVec4 & color, const char * fmt, ...)
Definition at line 3889 of file implot.cpp.
References ImPlotContext::CurrentPlot, ImPlotPlot::CurrentY, fmt, GImPlot, gp, IM_ASSERT_USER_ERROR, TagV(), and y.
TagYV()
void ImPlot::TagYV (double y, const ImVec4 & color, const char * fmt, va_list args)
Definition at line 3898 of file implot.cpp.
References ImPlotContext::CurrentPlot, ImPlotPlot::CurrentY, fmt, GImPlot, gp, IM_ASSERT_USER_ERROR, TagV(), and y.
TimeLabelSame()
bool ImPlot::TimeLabelSame (const char * l1, const char * l2) inline
Definition at line 1164 of file implot.cpp.
Referenced by Locator_Time().
Today()
static ImPlotTime ImPlot::Today () inline static
Definition at line 1621 of file implot_internal.h.
References FloorTime(), ImPlotTimeUnit_Day, and Now().
TransformForward_Log10()
static double ImPlot::TransformForward_Log10 (double v, void *) inline static
Definition at line 1643 of file implot_internal.h.
References ImLog10().
Referenced by SetupAxisScale().
TransformForward_Logit()
static double ImPlot::TransformForward_Logit (double v, void *) inline static
Definition at line 1660 of file implot_internal.h.
References ImClamp(), and ImLog10().
TransformForward_Sqrt()
static double ImPlot::TransformForward_Sqrt (double v, void *) inline static
Definition at line 1095 of file implot_demo.cpp.
Referenced by Demo_CustomScale().
TransformForward_SymLog()
static double ImPlot::TransformForward_SymLog (double v, void *) inline static
Definition at line 1652 of file implot_internal.h.
References ImAsinh().
Referenced by CalcSymLogPixel(), and SetupAxisScale().
TransformInverse_Log10()
static double ImPlot::TransformInverse_Log10 (double v, void *) inline static
Definition at line 1648 of file implot_internal.h.
References ImPow().
Referenced by SetupAxisScale().
TransformInverse_Logit()
static double ImPlot::TransformInverse_Logit (double v, void *) inline static
Definition at line 1665 of file implot_internal.h.
References ImPow().
TransformInverse_Sqrt()
static double ImPlot::TransformInverse_Sqrt (double v, void *) inline static
Definition at line 1099 of file implot_demo.cpp.
Referenced by Demo_CustomScale().
TransformInverse_SymLog()
static double ImPlot::TransformInverse_SymLog (double v, void *) inline static
Definition at line 1656 of file implot_internal.h.
References ImSinh().
Referenced by SetupAxisScale().
UpdateAxisColors()
void ImPlot::UpdateAxisColors (ImPlotAxis & axis)
Definition at line 1618 of file implot.cpp.
References ImPlotAxis::ColorAct, ImPlotAxis::ColorBg, ImPlotAxis::ColorHov, ImPlotAxis::ColorMaj, ImPlotAxis::ColorMin, ImPlotAxis::ColorTick, ImPlotAxis::ColorTxt, ImGui::GetColorU32(), GetStyleColorU32(), GetStyleColorVec4(), GImPlot, ImPlotCol_AxisBg, ImPlotCol_AxisBgActive, ImPlotCol_AxisBgHovered, ImPlotCol_AxisGrid, ImPlotCol_AxisText, ImPlotCol_AxisTick, ImPlotStyle::MinorAlpha, and ImPlotContext::Style.
Referenced by BeginPlot(), and SetupAxis().
UpdateInput()
bool ImPlot::UpdateInput (ImPlotPlot & plot)
Definition at line 1829 of file implot.cpp.
References AllAxesInputLocked(), AnyAxesHeld(), AnyAxesHovered(), ImPlotPlot::Axes, BOX_SELECT_DRAG_THRESHOLD, ImGui::ButtonBehavior(), ImPlotPlot::ContextLocked, ImGuiContext::DragDropActive, ImPlotAxis::Enabled, ImPlotInputMap::Fit, ImPlotAxis::FitThisFrame, ImPlotPlot::FitThisFrame, ImPlotPlot::Flags, ImPlotAxis::GetAspect(), ImGui::GetIO(), ImGui::GetMouseDragDelta(), ImRect::GetSize(), GImGui, GImPlot, gp, ImPlotAxis::Held, ImPlotPlot::Held, ImPlotAxis::Hovered, ImPlotPlot::Hovered, ImPlotAxis::HoverRect, ImPlotAxis::ID, ImPlotPlot::ID, ImAxis_COUNT, ImAxis_X1, ImAxis_Y1, ImFabs, ImGuiButtonFlags_AllowOverlap, ImGuiButtonFlags_FlattenChildren, ImGuiButtonFlags_MouseButtonLeft, ImGuiButtonFlags_MouseButtonMiddle, ImGuiButtonFlags_MouseButtonRight, ImGuiButtonFlags_PressedOnClick, ImGuiButtonFlags_PressedOnDoubleClick, ImGuiKey_MouseWheelY, ImGuiMouseCursor_NotAllowed, ImGuiMouseCursor_ResizeAll, ImGuiMouseCursor_ResizeEW, ImGuiMouseCursor_ResizeNS, ImHasFlag(), ImLengthSqr(), ImMax(), ImMin(), IMPLOT_NUM_X_AXES, IMPLOT_NUM_Y_AXES, ImPlotFlags_Equal, ImPlotFlags_NoBoxSelect, ImRemap(), ImPlotContext::InputMap, ImPlotAxis::IsInputLocked(), ImPlotPlot::IsInputLocked(), ImPlotAxis::IsInverted(), ImPlotAxis::IsPanLocked(), ImGui::KeepAliveID(), ImGuiIO::KeyMods, ImRect::Max, ImPlotInputMap::Menu, ImRect::Min, MOUSE_CURSOR_DRAG_THRESHOLD, ImGuiIO::MouseClicked, ImGuiIO::MouseDelta, ImGuiIO::MouseDoubleClicked, ImGuiIO::MouseDown, ImGuiIO::MouseDragMaxDistanceSqr, ImGuiIO::MousePos, ImGuiIO::MouseReleased, ImGuiIO::MouseWheel, ImPlotContext::OpenContextThisFrame, ImPlotAxis::OrthoAxis, ImPlotInputMap::OverrideMod, ImPlotInputMap::Pan, ImPlotInputMap::PanMod, ImPlotAxis::PixelsToPlot(), ImPlotPlot::PlotRect, ImPlotInputMap::Select, ImPlotInputMap::SelectCancel, ImPlotPlot::Selected, ImPlotInputMap::SelectHorzMod, ImPlotPlot::Selecting, ImPlotInputMap::SelectMod, ImPlotPlot::SelectRect, ImPlotPlot::SelectStart, ImPlotInputMap::SelectVertMod, ImPlotAxis::SetAspect(), ImGui::SetKeyOwner(), ImPlotAxis::SetMax(), ImPlotAxis::SetMin(), ImGui::SetMouseCursor(), ImVec2::x, ImPlotPlot::XAxis(), ImVec2::y, ImPlotPlot::YAxis(), ImPlotInputMap::ZoomMod, and ImPlotInputMap::ZoomRate.
Referenced by SetupFinish().
Variable Documentation
a0
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const ImPlotPoint double double ImPlot::a0
Definition at line 2204 of file implot_items.cpp.
Referenced by if().
a1
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const ImPlotPoint double double double ImPlot::a1
Definition at line 2204 of file implot_items.cpp.
Referenced by if(), and Intersection().
angle0
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T int double double double ImPlotFormatter void double ImPlot::angle0
Definition at line 2332 of file implot_items.cpp.
Referenced by if().
bar_scale
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T int int double ImPlot::bar_scale
Definition at line 2544 of file implot_items.cpp.
bar_size
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() ImPlotGetter void int double ImPlot::bar_size
Definition at line 1908 of file implot_items.cpp.
Referenced by PlotBars(), and PlotBars().
below
int ImPlot::below = 0
Definition at line 2571 of file implot_items.cpp.
Referenced by if(), and if().
bin_centers
ImVector<double>& ImPlot::bin_centers = gp.TempDouble1
Definition at line 2567 of file implot_items.cpp.
Referenced by for().
bin_counts
ImVector< double > & ImPlot::bin_counts = gp.TempDouble2
Definition at line 2568 of file implot_items.cpp.
Referenced by for(), if(), if(), if(), and if().
bins
const int ImPlot::bins = x_bins * y_bins
Definition at line 2544 of file implot_items.cpp.
Referenced by Demo_Histogram(), if(), if(), and if().
BOX_SELECT_DRAG_THRESHOLD
const float ImPlot::BOX_SELECT_DRAG_THRESHOLD = 4.0f static
Definition at line 1827 of file implot.cpp.
Referenced by UpdateInput().
center
ImPlotPoint ImPlot::center(x, y)
Definition at line 2204 of file implot_items.cpp.
Referenced by if().
col
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const ImPlotPoint double double double ImU32 ImPlot::col
Definition at line 2204 of file implot_items.cpp.
Referenced by AddTextCentered(), AddTextVertical(), Annotation(), Annotation(), AnnotationV(), BeginSubplots(), CalcHoverColor(), Demo_Annotations(), Demo_ColormapWidgets(), DragLineX(), DragLineY(), DragPoint(), DragRect(), DragRect(), EndPlot(), GetAutoColor(), GetStyleColorName(), if(), IsColorAuto(), ItemIcon(), ItemIcon(), NextColormapColorU32(), PlotErrorBarsHEx(), PlotErrorBarsVEx(), PlotShadedEx(), PrimLine(), PrimRectFill(), PrimRectLine(), PushStyleColor(), PushStyleColor(), RandomColor(), RenderHeatmap(), RenderSelectionRect(), SetNextErrorBarStyle(), SetNextFillStyle(), SetNextLineStyle(), ShowMetricsWindow(), ShowStyleEditor(), SubplotSetCell(), SubplotSetCell(), Tag(), and TagV().
col_maj
const bool ImPlot::col_maj = ImHasFlag(flags, ImPlotHistogramFlags_ColMajor)
Definition at line 2635 of file implot_items.cpp.
Referenced by if(), PlotHeatmap(), RenderGridLinesX(), RenderGridLinesY(), and RenderHeatmap().
count
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() ImPlotGetter void int ImPlot::count
Definition at line 1639 of file implot_items.cpp.
Referenced by AddTime(), AllAxesInputLocked(), AnyAxesHeld(), AnyAxesHovered(), AnyAxesInputLocked(), CalculateBins(), ColormapButton(), ColormapSlider(), Demo_Histogram2D(), ImPlot::FitterBarV< _Getter1, _Getter2 >::Fit(), ImPlot::FitterBarH< _Getter1, _Getter2 >::Fit(), if(), if(), if(), if(), if(), if(), if(), if(), IndexData(), PlotBars(), PlotBars(), PlotDigital< ImU8 >(), PlotErrorBars(), PlotErrorBars(), PlotLine(), PlotLine(), PlotScatter(), PlotScatter(), PlotScatter< ImS8 >(), PlotShaded(), PlotShaded(), PlotShaded(), PlotStairs(), PlotStairs(), PlotStairs< ImS8 >(), PlotStems(), PlotStems(), PopColormap(), PopStyleColor(), PopStyleVar(), and ShowMetricsWindow().
counted
int ImPlot::counted = 0
Definition at line 2577 of file implot_items.cpp.
Referenced by if(), and if().
data
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() ImPlotGetter void* ImPlot::data
Definition at line 1639 of file implot_items.cpp.
Referenced by AddTicksCustom(), AddTicksLogarithmic(), Demo_AutoFittingData(), Demo_BarGroups(), Demo_BarPlots(), Demo_LinkedAxes(), Demo_Querying(), Demo_Tables(), Demo_TimeScale(), FindCentroid(), Formatter_Default(), Formatter_Time(), IndexData(), MetricFormatter(), PlotDigital< ImU8 >(), PlotScatter< ImS8 >(), PlotStairs< ImS8 >(), PopStyleVar(), SetupAxisFormat(), SetupAxisScale(), and SinewaveGetter().
Data
&bin_counts &bin_centers ImPlot::Data
Definition at line 2616 of file implot_items.cpp.
Referenced by Demo_DigitalPlots(), and Demo_DragAndDrop().
data1
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() ImPlotGetter void* ImPlot::data1
Definition at line 1816 of file implot_items.cpp.
Referenced by Demo_CustomDataAndGetters(), Demo_LegendOptions(), Demo_NaNValues(), and Demo_PieCharts().
data2
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() ImPlotGetter void ImPlotGetter void* ImPlot::data2
Definition at line 1816 of file implot_items.cpp.
Referenced by Demo_CustomDataAndGetters(), Demo_LegendOptions(), Demo_NaNValues(), and Demo_PieCharts().
density
const bool ImPlot::density = ImHasFlag(flags, ImPlotHistogramFlags_Density)
Definition at line 2547 of file implot_items.cpp.
Referenced by RenderGridLinesX(), and RenderGridLinesY().
detached
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const ImPlotPoint double double double ImU32 bool ImPlot::detached
Definition at line 2204 of file implot_items.cpp.
DRAG_GRAB_HALF_SIZE
const float ImPlot::DRAG_GRAB_HALF_SIZE = 4.0f static
Definition at line 3904 of file implot.cpp.
Referenced by DragLineX(), DragLineY(), DragPoint(), and DragRect().
draw_list
ImDrawList& ImPlot::draw_list = *GetPlotDrawList()
Definition at line 2334 of file implot_items.cpp.
Referenced by GetLineRenderProps(), if(), if(), ImPlot::RendererLineStrip< _Getter >::Init(), ImPlot::RendererLineStripSkip< _Getter >::Init(), ImPlot::RendererLineSegments1< _Getter >::Init(), ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Init(), ImPlot::RendererBarsFillV< _Getter1, _Getter2 >::Init(), ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::Init(), ImPlot::RendererBarsLineV< _Getter1, _Getter2 >::Init(), ImPlot::RendererBarsLineH< _Getter1, _Getter2 >::Init(), ImPlot::RendererStairsPre< _Getter >::Init(), ImPlot::RendererStairsPost< _Getter >::Init(), ImPlot::RendererStairsPreShaded< _Getter >::Init(), ImPlot::RendererStairsPostShaded< _Getter >::Init(), ImPlot::RendererShaded< _Getter1, _Getter2 >::Init(), ImPlot::RendererRectC< _Getter >::Init(), ImPlot::RendererMarkersFill< _Getter >::Init(), ImPlot::RendererMarkersLine< _Getter >::Init(), PlotErrorBarsHEx(), PlotErrorBarsVEx(), PlotHeatmap(), PlotImage(), PlotText(), PrimLine(), PrimRectFill(), PrimRectLine(), ImPlot::RendererLineStrip< _Getter >::Render(), ImPlot::RendererLineStripSkip< _Getter >::Render(), ImPlot::RendererLineSegments1< _Getter >::Render(), ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Render(), ImPlot::RendererBarsFillV< _Getter1, _Getter2 >::Render(), ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::Render(), ImPlot::RendererBarsLineV< _Getter1, _Getter2 >::Render(), ImPlot::RendererBarsLineH< _Getter1, _Getter2 >::Render(), ImPlot::RendererStairsPre< _Getter >::Render(), ImPlot::RendererStairsPost< _Getter >::Render(), ImPlot::RendererStairsPreShaded< _Getter >::Render(), ImPlot::RendererStairsPostShaded< _Getter >::Render(), ImPlot::RendererShaded< _Getter1, _Getter2 >::Render(), ImPlot::RendererRectC< _Getter >::Render(), ImPlot::RendererMarkersFill< _Getter >::Render(), ImPlot::RendererMarkersLine< _Getter >::Render(), RenderHeatmap(), RenderPrimitives1(), RenderPrimitives2(), and RenderPrimitivesEx().
else
ImPlot::else
Initial value:
{
        GetterXY<IndexerIdx<T>,IndexerConst> get_min(IndexerIdx<T>(values,count,offset,stride),IndexerConst(lims.Y.Min),count)
Definition at line 2180 of file implot_items.cpp.
flags
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() ImPlotGetter void int ImPlotDigitalFlags ImPlot::flags
Initial value:
{
    GetterFuncPtr getter(getter_func,data, count)
Definition at line 1639 of file implot_items.cpp.
Referenced by BeginDragDropSourceAxis(), BeginDragDropSourceItem(), BeginDragDropSourcePlot(), BeginItem(), BeginItemEx(), BeginPlot(), BeginPlot(), BeginSubplots(), ColormapScale(), Demo_AxisConstraints(), Demo_BarGroups(), Demo_ColormapWidgets(), Demo_DragAndDrop(), Demo_DragLines(), Demo_DragPoints(), Demo_DragRects(), Demo_FilledLinePlots(), Demo_Histogram2D(), Demo_LegendOptions(), Demo_NaNValues(), Demo_PieCharts(), Demo_RealtimePlots(), Demo_StairstepPlots(), Demo_SubplotAxisLinking(), Demo_SubplotItemSharing(), Demo_SubplotsSizing(), Demo_Tables(), DragLineX(), DragLineY(), DragPoint(), DragRect(), DragRect(), if(), if(), PlotBars(), PlotBars(), PlotBarsHEx(), PlotBarsVEx(), PlotDummy(), PlotErrorBars(), PlotErrorBars(), PlotErrorBarsHEx(), PlotErrorBarsVEx(), PlotHeatmap(), PlotLine(), PlotLine(), PlotLineEx(), PlotScatter(), PlotScatter(), PlotScatterEx(), PlotShaded(), PlotShaded(), PlotShaded(), PlotShadedEx(), PlotStairs(), PlotStairs(), PlotStairsEx(), PlotStems(), PlotStems(), PlotStemsEx(), PlotText(), RegisterOrGetItem(), SetupAxis(), SetupLegend(), and SetupMouseText().
fmt
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T int double double double ImPlotFormatter ImPlot::fmt
Definition at line 2332 of file implot_items.cpp.
Referenced by Annotation(), AnnotationV(), FormatDate(), FormatDateTime(), Formatter_Default(), FormatTime(), GetDateTimeFmt(), GetDateTimeWidth(), if(), PlotHeatmap(), RenderHeatmap(), SetupAxisFormat(), Tag(), TagV(), TagX(), TagXV(), TagY(), and TagYV().
fmt_data
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T int double double double ImPlotFormatter void* ImPlot::fmt_data
Definition at line 2332 of file implot_items.cpp.
Referenced by if().
get_max
GetterXY< IndexerIdx< T >, IndexerConst > ImPlot::get_max(IndexerIdx< T >(values, count, offset, stride), IndexerConst(lims.Y.Max), count) (IndexerIdx< T > values, count, offset, stride, IndexerConst(lims.Y.Max) , count)
Referenced by if().
getter
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() Getter ImPlot::getter
Definition at line 2714 of file implot_items.cpp.
Referenced by PlotDigital< ImU8 >(), PlotErrorBars(), PlotLine(), PlotLine(), PlotLineEx(), PlotScatter(), PlotScatter(), PlotScatter< ImS8 >(), PlotScatterEx(), PlotStairs(), PlotStairs(), PlotStairs< ImS8 >(), PlotStairsEx(), RenderHeatmap(), RenderMarkers(), and RenderPrimitives1().
getter2
GetterFuncPtr ImPlot::getter2(getter_func2, data2, count) (getter_func2 , data2 , count)
Referenced by PlotBars(), PlotBars(), PlotBarsHEx(), PlotBarsVEx(), PlotLineEx(), PlotShaded(), PlotShaded(), PlotShaded(), PlotShadedEx(), and RenderPrimitives2().
getter_func
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() ImPlotGetter ImPlot::getter_func
Definition at line 1639 of file implot_items.cpp.
Referenced by PlotDigital< ImU8 >(), PlotScatter< ImS8 >(), and PlotStairs< ImS8 >().
getter_func1
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() ImPlotGetter ImPlot::getter_func1
Definition at line 1816 of file implot_items.cpp.
getter_func2
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() ImPlotGetter void ImPlotGetter ImPlot::getter_func2
Definition at line 1816 of file implot_items.cpp.
gp
ImPlotContext & ImPlot::gp = *GImPlot
Definition at line 2566 of file implot_items.cpp.
Referenced by AddColormap(), AddColormap(), Annotation(), AnnotationV(), ApplyNextPlotData(), BeginAlignedPlots(), BeginDragDropSourceAxis(), BeginDragDropSourceItem(), BeginDragDropSourcePlot(), BeginDragDropTargetPlot(), BeginItem(), BeginLegendPopup(), BeginPlot(), BeginSubplots(), BustColorCache(), BustItemCache(), BustPlotCache(), CancelPlotSelection(), ColormapButton(), ColormapIcon(), ColormapScale(), ColormapSlider(), CombineDateTime(), DragLineX(), DragLineY(), EndAlignedPlots(), EndItem(), EndPlot(), EndSubplots(), float(), FloorTime(), GetColormapColorU32(), GetColormapCount(), GetColormapIndex(), GetColormapName(), GetColormapSize(), GetCurrentItem(), GetInputMap(), GetItem(), GetLastItemColor(), GetPlotLimits(), GetPlotPos(), GetPlotSelection(), GetPlotSize(), GetStyle(), HideNextItem(), IsAxisHovered(), IsLegendEntryHovered(), IsPlotHovered(), IsPlotSelected(), IsSubplotsHovered(), LabelAxisValue(), NextColormapColorU32(), ImPlot::GetterHeatmapColMaj< T >::operator()(), PadAndDatumAxesX(), PadAndDatumAxesY(), PixelsToPlot(), PlotToPixels(), PopColormap(), PopStyleColor(), PopStyleVar(), PushColormap(), PushColormap(), PushPlotClipRect(), PushStyleColor(), PushStyleColor(), PushStyleVar(), PushStyleVar(), PushStyleVar(), RegisterOrGetItem(), RenderHeatmap(), SampleColormapU32(), SetAxes(), SetAxis(), SetNextAxisLimits(), SetNextAxisLinks(), SetNextAxisToFit(), SetNextErrorBarStyle(), SetNextFillStyle(), SetNextLineStyle(), SetNextMarkerStyle(), SetupAxis(), SetupAxisFormat(), SetupAxisFormat(), SetupAxisLimits(), SetupAxisLimitsConstraints(), SetupAxisLinks(), SetupAxisScale(), SetupAxisScale(), SetupAxisTicks(), SetupAxisTicks(), SetupAxisZoomConstraints(), SetupFinish(), SetupLegend(), SetupLock(), SetupMouseText(), ShowAltLegend(), ShowColormapSelector(), ShowLegendEntries(), ShowMetricsWindow(), ShowPlotContextMenu(), ShowStyleEditor(), ShowTimePicker(), SubplotNextCell(), SubplotSetCell(), SubplotSetCell(), Tag(), TagV(), TagX(), TagX(), TagXV(), TagY(), TagY(), TagYV(), and UpdateInput().
GPlotStyleVarInfo
const ImPlotStyleVarInfo ImPlot::GPlotStyleVarInfo[] static
Definition at line 298 of file implot.cpp.
Referenced by GetPlotStyleVarInfo().
height
else ImPlot::height = range.Y.Size() / y_bins
Definition at line 2653 of file implot_items.cpp.
Referenced by float(), PlotBarsHEx(), and ShowTimePicker().
ignore_hidden
const bool ImPlot::ignore_hidden = ImHasFlag(flags, ImPlotPieChartFlags_IgnoreHidden)
Definition at line 2336 of file implot_items.cpp.
Referenced by if().
ImPlotBarsFlags_Horizontal
& bin_counts & bin_centers bar_scale ImPlot::ImPlotBarsFlags_Horizontal
Definition at line 2616 of file implot_items.cpp.
Referenced by Demo_BarPlots(), PlotBars(), and PlotBars().
ITEM_HIGHLIGHT_LINE_SCALE
const float ImPlot::ITEM_HIGHLIGHT_LINE_SCALE = 2.0f static
Definition at line 395 of file implot_items.cpp.
Referenced by BeginItem().
ITEM_HIGHLIGHT_MARK_SCALE
const float ImPlot::ITEM_HIGHLIGHT_MARK_SCALE = 1.25f static
Definition at line 396 of file implot_items.cpp.
Referenced by BeginItem().
MARKER_FILL_CIRCLE
const ImVec2 ImPlot::MARKER_FILL_CIRCLE[10] = {ImVec2(1.0f, 0.0f), ImVec2(0.809017f, 0.58778524f),ImVec2(0.30901697f, 0.95105654f),ImVec2(-0.30901703f, 0.9510565f),ImVec2(-0.80901706f, 0.5877852f),ImVec2(-1.0f, 0.0f),ImVec2(-0.80901694f, -0.58778536f),ImVec2(-0.3090171f, -0.9510565f),ImVec2(0.30901712f, -0.9510565f),ImVec2(0.80901694f, -0.5877853f)} static
Definition at line 1500 of file implot_items.cpp.
Referenced by RenderMarkers().
MARKER_FILL_DIAMOND
const ImVec2 ImPlot::MARKER_FILL_DIAMOND[4] = {ImVec2(1, 0), ImVec2(0, -1), ImVec2(-1, 0), ImVec2(0, 1)} static
Definition at line 1502 of file implot_items.cpp.
Referenced by RenderMarkers().
MARKER_FILL_DOWN
const ImVec2 ImPlot::MARKER_FILL_DOWN[3] = {ImVec2(0.86602540378f ,-0.5f),ImVec2(0,1),ImVec2(- 0.86602540378f ,-0.5f)} static
Definition at line 1504 of file implot_items.cpp.
Referenced by RenderMarkers().
MARKER_FILL_LEFT
const ImVec2 ImPlot::MARKER_FILL_LEFT[3] = {ImVec2(-1,0), ImVec2(0.5, 0.86602540378f), ImVec2(0.5, - 0.86602540378f)} static
Definition at line 1505 of file implot_items.cpp.
Referenced by RenderMarkers().
MARKER_FILL_RIGHT
const ImVec2 ImPlot::MARKER_FILL_RIGHT[3] = {ImVec2(1,0), ImVec2(-0.5, 0.86602540378f), ImVec2(-0.5, - 0.86602540378f)} static
Definition at line 1506 of file implot_items.cpp.
Referenced by RenderMarkers().
MARKER_FILL_SQUARE
const ImVec2 ImPlot::MARKER_FILL_SQUARE[4] = {ImVec2(0.70710678118f , 0.70710678118f), ImVec2(0.70710678118f ,- 0.70710678118f), ImVec2(- 0.70710678118f ,- 0.70710678118f), ImVec2(- 0.70710678118f , 0.70710678118f)} static
Definition at line 1501 of file implot_items.cpp.
Referenced by RenderMarkers().
MARKER_FILL_UP
const ImVec2 ImPlot::MARKER_FILL_UP[3] = {ImVec2(0.86602540378f ,0.5f),ImVec2(0,-1),ImVec2(- 0.86602540378f ,0.5f)} static
Definition at line 1503 of file implot_items.cpp.
Referenced by RenderMarkers().
MARKER_LINE_ASTERISK
const ImVec2 ImPlot::MARKER_LINE_ASTERISK[6] = {ImVec2(- 0.86602540378f , -0.5f), ImVec2(0.86602540378f , 0.5f), ImVec2(- 0.86602540378f , 0.5f), ImVec2(0.86602540378f , -0.5f), ImVec2(0, -1), ImVec2(0, 1)} static
Definition at line 1536 of file implot_items.cpp.
Referenced by RenderMarkers().
MARKER_LINE_CIRCLE
const ImVec2 ImPlot::MARKER_LINE_CIRCLE[20] static
Initial value:
= {
    ImVec2(1.0f, 0.0f),
    ImVec2(0.809017f, 0.58778524f),
    ImVec2(0.809017f, 0.58778524f),
    ImVec2(0.30901697f, 0.95105654f),
    ImVec2(0.30901697f, 0.95105654f),
    ImVec2(-0.30901703f, 0.9510565f),
    ImVec2(-0.30901703f, 0.9510565f),
    ImVec2(-0.80901706f, 0.5877852f),
    ImVec2(-0.80901706f, 0.5877852f),
    ImVec2(-1.0f, 0.0f),
    ImVec2(-1.0f, 0.0f),
    ImVec2(-0.80901694f, -0.58778536f),
    ImVec2(-0.80901694f, -0.58778536f),
    ImVec2(-0.3090171f, -0.9510565f),
    ImVec2(-0.3090171f, -0.9510565f),
    ImVec2(0.30901712f, -0.9510565f),
    ImVec2(0.30901712f, -0.9510565f),
    ImVec2(0.80901694f, -0.5877853f),
    ImVec2(0.80901694f, -0.5877853f),
    ImVec2(1.0f, 0.0f)
}
Definition at line 1508 of file implot_items.cpp.
Referenced by RenderMarkers().
MARKER_LINE_CROSS
const ImVec2 ImPlot::MARKER_LINE_CROSS[4] = {ImVec2(- 0.70710678118f ,- 0.70710678118f),ImVec2(0.70710678118f , 0.70710678118f),ImVec2(0.70710678118f ,- 0.70710678118f),ImVec2(- 0.70710678118f , 0.70710678118f)} static
Definition at line 1538 of file implot_items.cpp.
Referenced by RenderMarkers().
MARKER_LINE_DIAMOND
const ImVec2 ImPlot::MARKER_LINE_DIAMOND[8] = {ImVec2(1, 0), ImVec2(0, -1), ImVec2(0, -1), ImVec2(-1, 0), ImVec2(-1, 0), ImVec2(0, 1), ImVec2(0, 1), ImVec2(1, 0)} static
Definition at line 1531 of file implot_items.cpp.
Referenced by RenderMarkers().
MARKER_LINE_DOWN
const ImVec2 ImPlot::MARKER_LINE_DOWN[6] = {ImVec2(0.86602540378f ,-0.5f),ImVec2(0,1),ImVec2(0,1),ImVec2(- 0.86602540378f ,-0.5f), ImVec2(- 0.86602540378f ,-0.5f), ImVec2(0.86602540378f ,-0.5f)} static
Definition at line 1533 of file implot_items.cpp.
Referenced by RenderMarkers().
MARKER_LINE_LEFT
const ImVec2 ImPlot::MARKER_LINE_LEFT[6] = {ImVec2(-1,0), ImVec2(0.5, 0.86602540378f), ImVec2(0.5, 0.86602540378f), ImVec2(0.5, - 0.86602540378f) , ImVec2(0.5, - 0.86602540378f) , ImVec2(-1,0) } static
Definition at line 1534 of file implot_items.cpp.
Referenced by RenderMarkers().
MARKER_LINE_PLUS
const ImVec2 ImPlot::MARKER_LINE_PLUS[4] = {ImVec2(-1, 0), ImVec2(1, 0), ImVec2(0, -1), ImVec2(0, 1)} static
Definition at line 1537 of file implot_items.cpp.
Referenced by RenderMarkers().
MARKER_LINE_RIGHT
const ImVec2 ImPlot::MARKER_LINE_RIGHT[6] = {ImVec2(1,0), ImVec2(-0.5, 0.86602540378f), ImVec2(-0.5, 0.86602540378f), ImVec2(-0.5, - 0.86602540378f), ImVec2(-0.5, - 0.86602540378f), ImVec2(1,0) } static
Definition at line 1535 of file implot_items.cpp.
Referenced by RenderMarkers().
MARKER_LINE_SQUARE
const ImVec2 ImPlot::MARKER_LINE_SQUARE[8] = {ImVec2(0.70710678118f , 0.70710678118f), ImVec2(0.70710678118f ,- 0.70710678118f), ImVec2(0.70710678118f ,- 0.70710678118f), ImVec2(- 0.70710678118f ,- 0.70710678118f), ImVec2(- 0.70710678118f ,- 0.70710678118f), ImVec2(- 0.70710678118f , 0.70710678118f), ImVec2(- 0.70710678118f , 0.70710678118f), ImVec2(0.70710678118f , 0.70710678118f)} static
Definition at line 1530 of file implot_items.cpp.
Referenced by RenderMarkers().
MARKER_LINE_UP
const ImVec2 ImPlot::MARKER_LINE_UP[6] = {ImVec2(0.86602540378f ,0.5f), ImVec2(0,-1),ImVec2(0,-1),ImVec2(- 0.86602540378f ,0.5f),ImVec2(- 0.86602540378f ,0.5f),ImVec2(0.86602540378f ,0.5f)} static
Definition at line 1532 of file implot_items.cpp.
Referenced by RenderMarkers().
max_count
return ImPlot::max_count = 0
Definition at line 2578 of file implot_items.cpp.
Referenced by Demo_Histogram2D(), if(), if(), if(), and if().
MONTH_ABRVS
const char* ImPlot::MONTH_ABRVS[] = {"Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"} static
Definition at line 1074 of file implot.cpp.
Referenced by FormatDate(), and ShowDatePicker().
MONTH_NAMES
const char* ImPlot::MONTH_NAMES[] = {"January","February","March","April","May","June","July","August","September","October","November","December"} static
Definition at line 1072 of file implot.cpp.
Referenced by ShowDatePicker().
MOUSE_CURSOR_DRAG_THRESHOLD
const float ImPlot::MOUSE_CURSOR_DRAG_THRESHOLD = 5.0f static
Definition at line 1826 of file implot.cpp.
Referenced by UpdateInput().
normalize
const bool ImPlot::normalize = ImHasFlag(flags, ImPlotPieChartFlags_Normalize) || sum > 1.0
Definition at line 2338 of file implot_items.cpp.
Referenced by if().
offset
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T int ImPlotInfLinesFlags int ImPlot::offset
Definition at line 2163 of file implot_items.cpp.
Referenced by Annotation(), Annotation(), AnnotationV(), Demo_OffsetAndStride(), Demo_Tables(), if(), if(), IndexData(), PlotBars(), PlotBars(), PlotErrorBars(), PlotErrorBars(), PlotLine(), PlotLine(), PlotScatter(), PlotScatter(), PlotShaded(), PlotShaded(), PlotShaded(), PlotStairs(), PlotStairs(), PlotStems(), and PlotStems().
outliers
const bool ImPlot::outliers = !ImHasFlag(flags, ImPlotHistogramFlags_NoOutliers)
Definition at line 2548 of file implot_items.cpp.
Referenced by if(), if(), and if().
radius
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T int double double double ImPlot::radius
Definition at line 2204 of file implot_items.cpp.
Referenced by DragPoint(), and if().
range
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T const T int int int ImPlotRect ImPlot::range
Definition at line 2544 of file implot_items.cpp.
Referenced by AddTicksLogarithmic(), AxisPrecision(), CalcLogarithmicExponents(), CalcSymLogPixel(), CalculateBins(), ColormapScale(), Demo_Histogram(), for(), GetUnitForRange(), if(), if(), if(), if(), Locator_Default(), Locator_Log10(), Locator_SymLog(), and Locator_Time().
stride
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T int ImPlotInfLinesFlags int int ImPlot::stride
Initial value:
{
    const ImPlotRect lims = GetPlotLimits( -1 , -1 )
Definition at line 2163 of file implot_items.cpp.
Referenced by if(), IndexData(), PlotBars(), PlotBars(), PlotErrorBars(), PlotErrorBars(), PlotLine(), PlotLine(), PlotScatter(), PlotScatter(), PlotShaded(), PlotShaded(), PlotShaded(), PlotStairs(), PlotStairs(), PlotStems(), and PlotStems().
SUBPLOT_BORDER_SIZE
const float ImPlot::SUBPLOT_BORDER_SIZE = 1.0f static
Definition at line 3274 of file implot.cpp.
Referenced by BeginSubplots().
SUBPLOT_SPLITTER_FEEDBACK_TIMER
const float ImPlot::SUBPLOT_SPLITTER_FEEDBACK_TIMER = 0.06f static
Definition at line 3276 of file implot.cpp.
Referenced by BeginSubplots().
SUBPLOT_SPLITTER_HALF_THICKNESS
const float ImPlot::SUBPLOT_SPLITTER_HALF_THICKNESS = 4.0f static
Definition at line 3275 of file implot.cpp.
Referenced by BeginSubplots().
sum
const double ImPlot::sum = PieChartSum(values, count, ignore_hidden)
Definition at line 2337 of file implot_items.cpp.
Referenced by if().
TICK_FILL_X
const float ImPlot::TICK_FILL_X = 0.8f static
Definition at line 720 of file implot.cpp.
Referenced by Locator_Default().
TICK_FILL_Y
const float ImPlot::TICK_FILL_Y = 1.0f static
Definition at line 721 of file implot.cpp.
Referenced by Locator_Default().
TimeFormatLevel0
const ImPlotDateTimeSpec ImPlot::TimeFormatLevel0[ImPlotTimeUnit_COUNT] static
Initial value:
= {
    ImPlotDateTimeSpec(ImPlotDateFmt_None,  ImPlotTimeFmt_Us),
    ImPlotDateTimeSpec(ImPlotDateFmt_None,  ImPlotTimeFmt_SMs),
    ImPlotDateTimeSpec(ImPlotDateFmt_None,  ImPlotTimeFmt_S),
    ImPlotDateTimeSpec(ImPlotDateFmt_None,  ImPlotTimeFmt_HrMin),
    ImPlotDateTimeSpec(ImPlotDateFmt_None,  ImPlotTimeFmt_Hr),
    ImPlotDateTimeSpec(ImPlotDateFmt_DayMo, ImPlotTimeFmt_None),
    ImPlotDateTimeSpec(ImPlotDateFmt_Mo,    ImPlotTimeFmt_None),
    ImPlotDateTimeSpec(ImPlotDateFmt_Yr,    ImPlotTimeFmt_None)
}
Definition at line 1171 of file implot.cpp.
Referenced by Locator_Time().
TimeFormatLevel1
const ImPlotDateTimeSpec ImPlot::TimeFormatLevel1[ImPlotTimeUnit_COUNT] static
Initial value:
= {
    ImPlotDateTimeSpec(ImPlotDateFmt_None,    ImPlotTimeFmt_HrMin),
    ImPlotDateTimeSpec(ImPlotDateFmt_None,    ImPlotTimeFmt_HrMinS),
    ImPlotDateTimeSpec(ImPlotDateFmt_None,    ImPlotTimeFmt_HrMin),
    ImPlotDateTimeSpec(ImPlotDateFmt_None,    ImPlotTimeFmt_HrMin),
    ImPlotDateTimeSpec(ImPlotDateFmt_DayMoYr, ImPlotTimeFmt_None),
    ImPlotDateTimeSpec(ImPlotDateFmt_DayMoYr, ImPlotTimeFmt_None),
    ImPlotDateTimeSpec(ImPlotDateFmt_Yr,      ImPlotTimeFmt_None),
    ImPlotDateTimeSpec(ImPlotDateFmt_Yr,      ImPlotTimeFmt_None)
}
Definition at line 1182 of file implot.cpp.
Referenced by Locator_Time().
TimeFormatLevel1First
const ImPlotDateTimeSpec ImPlot::TimeFormatLevel1First[ImPlotTimeUnit_COUNT] static
Initial value:
= {
    ImPlotDateTimeSpec(ImPlotDateFmt_DayMoYr, ImPlotTimeFmt_HrMinS),
    ImPlotDateTimeSpec(ImPlotDateFmt_DayMoYr, ImPlotTimeFmt_HrMinS),
    ImPlotDateTimeSpec(ImPlotDateFmt_DayMoYr, ImPlotTimeFmt_HrMin),
    ImPlotDateTimeSpec(ImPlotDateFmt_DayMoYr, ImPlotTimeFmt_HrMin),
    ImPlotDateTimeSpec(ImPlotDateFmt_DayMoYr, ImPlotTimeFmt_None),
    ImPlotDateTimeSpec(ImPlotDateFmt_DayMoYr, ImPlotTimeFmt_None),
    ImPlotDateTimeSpec(ImPlotDateFmt_Yr,      ImPlotTimeFmt_None),
    ImPlotDateTimeSpec(ImPlotDateFmt_Yr,      ImPlotTimeFmt_None)
}
Definition at line 1193 of file implot.cpp.
Referenced by Locator_Time().
TimeFormatMouseCursor
const ImPlotDateTimeSpec ImPlot::TimeFormatMouseCursor[ImPlotTimeUnit_COUNT] static
Initial value:
= {
    ImPlotDateTimeSpec(ImPlotDateFmt_None,     ImPlotTimeFmt_Us),
    ImPlotDateTimeSpec(ImPlotDateFmt_None,     ImPlotTimeFmt_SUs),
    ImPlotDateTimeSpec(ImPlotDateFmt_None,     ImPlotTimeFmt_SMs),
    ImPlotDateTimeSpec(ImPlotDateFmt_None,     ImPlotTimeFmt_HrMinS),
    ImPlotDateTimeSpec(ImPlotDateFmt_None,     ImPlotTimeFmt_HrMin),
    ImPlotDateTimeSpec(ImPlotDateFmt_DayMo,    ImPlotTimeFmt_Hr),
    ImPlotDateTimeSpec(ImPlotDateFmt_DayMoYr,  ImPlotTimeFmt_None),
    ImPlotDateTimeSpec(ImPlotDateFmt_MoYr,     ImPlotTimeFmt_None)
}
Definition at line 1204 of file implot.cpp.
Referenced by LabelAxisValue().
TimeUnitSpans
const double ImPlot::TimeUnitSpans[ImPlotTimeUnit_COUNT] static
Initial value:
= {
    0.000001,
    0.001,
    1,
    60,
    3600,
    86400,
    2629800,
    31557600
}
Definition at line 857 of file implot.cpp.
Referenced by Locator_Time().
values
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T* ImPlot::values
Definition at line 2163 of file implot_items.cpp.
Referenced by AddTicksCustom(), CalculateBins(), float(), if(), if(), if(), PlotBars(), PlotHeatmap(), PlotLine(), PlotScatter(), PlotShaded(), PlotStairs(), PlotStems(), RenderHeatmap(), and SetupAxisTicks().
WD_ABRVS
const char* ImPlot::WD_ABRVS[] = {"Su","Mo","Tu","We","Th","Fr","Sa"} static
Definition at line 1073 of file implot.cpp.
Referenced by ShowDatePicker().
width
else ImPlot::width = range.Size() / bins
Definition at line 2560 of file implot_items.cpp.
Referenced by float(), for(), if(), PlotBarsVEx(), and ShowTimePicker().
x
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T int double ImPlot::x
Definition at line 2332 of file implot_items.cpp.
Referenced by ImPlot::ScrollingBuffer::AddPoint(), ImPlot::RollingBuffer::AddPoint(), Annotation(), Annotation(), AnnotationV(), Demo_Config(), Demo_CustomDataAndGetters(), Demo_DigitalPlots(), Demo_DragAndDrop(), Demo_DragPoints(), Demo_Histogram(), Demo_Histogram2D(), Demo_Querying(), DragLineX(), DragPoint(), DragRect(), FitPointX(), NiceNum(), ImPlot::Transformer2::operator()(), PixelsToPlot(), PlotText(), PlotToPixels(), ShowStyleEditor(), TagX(), TagX(), and TagXV().
X
range ImPlot::X
Definition at line 2655 of file implot_items.cpp.
Referenced by Demo_Querying(), and RandomGauss().
x_bins
range ImPlot::x_bins
Definition at line 2630 of file implot_items.cpp.
Referenced by if().
xs
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T* ImPlot::xs
Definition at line 2630 of file implot_items.cpp.
Referenced by Demo_DragLines(), Demo_ErrorBars(), Demo_LogScale(), Demo_MarkersAndText(), Demo_MultipleAxes(), Demo_ShadedPlots(), Demo_StemPlots(), Demo_SymmetricLogScale(), if(), PlotBars(), PlotErrorBars(), PlotErrorBars(), PlotLine(), PlotScatter(), PlotShaded(), PlotShaded(), PlotStairs(), and PlotStems().
y
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T int double double ImPlot::y
Definition at line 2332 of file implot_items.cpp.
Referenced by ImPlot::ScrollingBuffer::AddPoint(), ImPlot::RollingBuffer::AddPoint(), AddTextCentered(), Annotation(), Annotation(), AnnotationV(), CombineDateTime(), Demo_Config(), Demo_CustomDataAndGetters(), Demo_DigitalPlots(), Demo_DragAndDrop(), Demo_DragPoints(), Demo_Histogram(), Demo_Querying(), DragLineY(), DragPoint(), DragRect(), FitPointY(), Locator_Time(), ImPlot::Transformer2::operator()(), PixelsToPlot(), PlotText(), PlotToPixels(), TagY(), TagY(), and TagYV().
Y
range ImPlot::Y
Definition at line 2659 of file implot_items.cpp.
y_bins
range ImPlot::y_bins
Definition at line 2630 of file implot_items.cpp.
Referenced by if().
ys
_INSTANTIATE_FOR_NUMERIC_TYPES_1() ImS16() ImU16() ImS32() ImU32() ImS64() ImU64() const T const T* ImPlot::ys
Definition at line 2630 of file implot_items.cpp.
Referenced by Demo_DragLines(), Demo_MarkersAndText(), Demo_ShadedPlots(), if(), PlotBars(), PlotErrorBars(), PlotErrorBars(), PlotLine(), PlotScatter(), PlotShaded(), PlotStairs(), and PlotStems().