SignalProcessing: ImStb Namespace Reference
ImStb Namespace Reference
Functions
static int STB_TEXTEDIT_STRINGLEN (const ImGuiInputTextState *obj)
static char STB_TEXTEDIT_GETCHAR (const ImGuiInputTextState *obj, int idx)
static float STB_TEXTEDIT_GETWIDTH (ImGuiInputTextState *obj, int line_start_idx, int char_idx)
static void STB_TEXTEDIT_LAYOUTROW (StbTexteditRow *r, ImGuiInputTextState *obj, int line_start_idx)
static int IMSTB_TEXTEDIT_GETNEXTCHARINDEX_IMPL (ImGuiInputTextState *obj, int idx)
static int IMSTB_TEXTEDIT_GETPREVCHARINDEX_IMPL (ImGuiInputTextState *obj, int idx)
static bool ImCharIsSeparatorW (unsigned int c)
static int is_word_boundary_from_right (ImGuiInputTextState *obj, int idx)
static int is_word_boundary_from_left (ImGuiInputTextState *obj, int idx)
static int STB_TEXTEDIT_MOVEWORDLEFT_IMPL (ImGuiInputTextState *obj, int idx)
static int STB_TEXTEDIT_MOVEWORDRIGHT_MAC (ImGuiInputTextState *obj, int idx)
static int STB_TEXTEDIT_MOVEWORDRIGHT_WIN (ImGuiInputTextState *obj, int idx)
static int STB_TEXTEDIT_MOVEWORDRIGHT_IMPL (ImGuiInputTextState *obj, int idx)
static int STB_TEXTEDIT_MOVELINESTART_IMPL (ImGuiInputTextState *obj, ImStb::STB_TexteditState *state, int cursor)
static int STB_TEXTEDIT_MOVELINEEND_IMPL (ImGuiInputTextState *obj, ImStb::STB_TexteditState *state, int cursor)
static void STB_TEXTEDIT_DELETECHARS (ImGuiInputTextState *obj, int pos, int n)
static int STB_TEXTEDIT_INSERTCHARS (ImGuiInputTextState *obj, int pos, const char *new_text, int new_text_len)
static void stb_textedit_replace (ImGuiInputTextState *str, STB_TexteditState *state, const char *text, int text_len)
Variables
static char STB_TEXTEDIT_NEWLINE = '\n'
Function Documentation
ImCharIsSeparatorW()
static bool ImStb::ImCharIsSeparatorW (unsigned int c) static
Definition at line 4021 of file imgui_widgets.cpp.
Referenced by is_word_boundary_from_left(), and is_word_boundary_from_right().
IMSTB_TEXTEDIT_GETNEXTCHARINDEX_IMPL()
static int ImStb::IMSTB_TEXTEDIT_GETNEXTCHARINDEX_IMPL (ImGuiInputTextState * obj, int idx) static
Definition at line 4005 of file imgui_widgets.cpp.
References ImTextCharFromUtf8(), ImGuiInputTextState::TextLen, and ImGuiInputTextState::TextSrc.
IMSTB_TEXTEDIT_GETPREVCHARINDEX_IMPL()
static int ImStb::IMSTB_TEXTEDIT_GETPREVCHARINDEX_IMPL (ImGuiInputTextState * obj, int idx) static
Definition at line 4013 of file imgui_widgets.cpp.
References ImTextFindPreviousUtf8Codepoint(), and ImGuiInputTextState::TextSrc.
is_word_boundary_from_left()
static int ImStb::is_word_boundary_from_left (ImGuiInputTextState * obj, int idx) static
Definition at line 4052 of file imgui_widgets.cpp.
References ImGuiInputTextState::Flags, ImCharIsBlankW(), ImCharIsSeparatorW(), ImGuiInputTextFlags_Password, ImTextCharFromUtf8(), ImTextFindPreviousUtf8Codepoint(), ImGuiInputTextState::TextLen, and ImGuiInputTextState::TextSrc.
Referenced by STB_TEXTEDIT_MOVEWORDRIGHT_MAC().
is_word_boundary_from_right()
static int ImStb::is_word_boundary_from_right (ImGuiInputTextState * obj, int idx) static
Definition at line 4035 of file imgui_widgets.cpp.
References ImGuiInputTextState::Flags, ImCharIsBlankW(), ImCharIsSeparatorW(), ImGuiInputTextFlags_Password, ImTextCharFromUtf8(), ImTextFindPreviousUtf8Codepoint(), ImGuiInputTextState::TextLen, and ImGuiInputTextState::TextSrc.
Referenced by STB_TEXTEDIT_MOVEWORDLEFT_IMPL(), and STB_TEXTEDIT_MOVEWORDRIGHT_WIN().
STB_TEXTEDIT_DELETECHARS()
static void ImStb::STB_TEXTEDIT_DELETECHARS (ImGuiInputTextState * obj, int pos, int n) static
Definition at line 4164 of file imgui_widgets.cpp.
References ImVector< T >::Data, ImGuiInputTextState::Edited, IM_ASSERT, ImGuiInputTextState::TextA, ImGuiInputTextState::TextLen, and ImGuiInputTextState::TextSrc.
Referenced by stb_textedit_replace().
STB_TEXTEDIT_GETCHAR()
static char ImStb::STB_TEXTEDIT_GETCHAR (const ImGuiInputTextState * obj, int idx) static
Definition at line 3986 of file imgui_widgets.cpp.
References IM_ASSERT, and ImGuiInputTextState::TextSrc.
Referenced by ImGui::InputTextEx(), STB_TEXTEDIT_MOVELINEEND_IMPL(), and STB_TEXTEDIT_MOVELINESTART_IMPL().
STB_TEXTEDIT_GETWIDTH()
static float ImStb::STB_TEXTEDIT_GETWIDTH (ImGuiInputTextState * obj, int line_start_idx, int char_idx) static
Definition at line 3987 of file imgui_widgets.cpp.
References ImGuiInputTextState::Ctx, ImGuiContext::FontBaked, ImGuiContext::FontBakedScale, ImFontBaked::GetCharAdvance(), IMSTB_TEXTEDIT_GETWIDTH_NEWLINE, ImTextCharFromUtf8(), ImGuiInputTextState::TextLen, and ImGuiInputTextState::TextSrc.
STB_TEXTEDIT_INSERTCHARS()
static int ImStb::STB_TEXTEDIT_INSERTCHARS (ImGuiInputTextState * obj, int pos, const char * new_text, int new_text_len) static
Definition at line 4175 of file imgui_widgets.cpp.
References ImGuiInputTextState::BufCapacity, ImVector< T >::Data, ImGuiInputTextState::Edited, ImGuiInputTextState::Flags, IM_ASSERT, ImClamp(), ImGuiInputTextFlags_CallbackResize, ImMax(), ImTextFindValidUtf8CodepointEnd(), ImVector< T >::resize(), ImVector< T >::Size, ImGuiInputTextState::TextA, ImGuiInputTextState::TextLen, and ImGuiInputTextState::TextSrc.
Referenced by stb_textedit_replace().
STB_TEXTEDIT_LAYOUTROW()
static void ImStb::STB_TEXTEDIT_LAYOUTROW (StbTexteditRow * r, ImGuiInputTextState * obj, int line_start_idx) static
Definition at line 3989 of file imgui_widgets.cpp.
References StbTexteditRow::baseline_y_delta, ImGuiInputTextState::Ctx, ImDrawTextFlags_StopOnNewLine, ImDrawTextFlags_WrapKeepBlanks, InputTextCalcTextSize(), StbTexteditRow::num_chars, ImGuiInputTextState::TextLen, ImGuiInputTextState::TextSrc, ImVec2::x, StbTexteditRow::x0, StbTexteditRow::x1, ImVec2::y, StbTexteditRow::ymax, and StbTexteditRow::ymin.
STB_TEXTEDIT_MOVELINEEND_IMPL()
static int ImStb::STB_TEXTEDIT_MOVELINEEND_IMPL (ImGuiInputTextState * obj, ImStb::STB_TexteditState * state, int cursor) static
Definition at line 4132 of file imgui_widgets.cpp.
References ImGuiInputTextState::Ctx, ImGuiContext::Font, ImGuiContext::FontSize, ImDrawTextFlags_WrapKeepBlanks, ImFontCalcWordWrapPositionEx(), ImGuiDir_Left, IMSTB_TEXTEDIT_GETNEXTCHARINDEX, ImStrbol(), ImGuiInputTextState::LastMoveDirectionLR, STB_TEXTEDIT_GETCHAR(), STB_TEXTEDIT_NEWLINE, STB_TEXTEDIT_STRINGLEN(), ImGuiInputTextState::TextLen, ImGuiInputTextState::TextSrc, and ImGuiInputTextState::WrapWidth.
STB_TEXTEDIT_MOVELINESTART_IMPL()
static int ImStb::STB_TEXTEDIT_MOVELINESTART_IMPL (ImGuiInputTextState * obj, ImStb::STB_TexteditState * state, int cursor) static
Definition at line 4096 of file imgui_widgets.cpp.
References ImGuiInputTextState::Ctx, ImGuiContext::Font, ImGuiContext::FontSize, ImDrawTextFlags_WrapKeepBlanks, ImFontCalcWordWrapPositionEx(), ImGuiDir_Left, IMSTB_TEXTEDIT_GETPREVCHARINDEX, ImStrbol(), ImGuiInputTextState::LastMoveDirectionLR, STB_TEXTEDIT_GETCHAR(), STB_TEXTEDIT_NEWLINE, ImGuiInputTextState::TextA, ImGuiInputTextState::TextLen, ImGuiInputTextState::TextSrc, and ImGuiInputTextState::WrapWidth.
STB_TEXTEDIT_MOVEWORDLEFT_IMPL()
static int ImStb::STB_TEXTEDIT_MOVEWORDLEFT_IMPL (ImGuiInputTextState * obj, int idx) static
Definition at line 4068 of file imgui_widgets.cpp.
References IMSTB_TEXTEDIT_GETPREVCHARINDEX, and is_word_boundary_from_right().
STB_TEXTEDIT_MOVEWORDRIGHT_IMPL()
static int ImStb::STB_TEXTEDIT_MOVEWORDRIGHT_IMPL (ImGuiInputTextState * obj, int idx) static
Definition at line 4091 of file imgui_widgets.cpp.
References ImGuiIO::ConfigMacOSXBehaviors, ImGuiInputTextState::Ctx, ImGuiContext::IO, STB_TEXTEDIT_MOVEWORDRIGHT_MAC(), and STB_TEXTEDIT_MOVEWORDRIGHT_WIN().
STB_TEXTEDIT_MOVEWORDRIGHT_MAC()
static int ImStb::STB_TEXTEDIT_MOVEWORDRIGHT_MAC (ImGuiInputTextState * obj, int idx) static
Definition at line 4075 of file imgui_widgets.cpp.
References IMSTB_TEXTEDIT_GETNEXTCHARINDEX, is_word_boundary_from_left(), and ImGuiInputTextState::TextLen.
Referenced by ImGui::InputTextEx(), and STB_TEXTEDIT_MOVEWORDRIGHT_IMPL().
STB_TEXTEDIT_MOVEWORDRIGHT_WIN()
static int ImStb::STB_TEXTEDIT_MOVEWORDRIGHT_WIN (ImGuiInputTextState * obj, int idx) static
Definition at line 4083 of file imgui_widgets.cpp.
References IMSTB_TEXTEDIT_GETNEXTCHARINDEX, is_word_boundary_from_right(), and ImGuiInputTextState::TextLen.
Referenced by STB_TEXTEDIT_MOVEWORDRIGHT_IMPL().
stb_textedit_replace()
static void ImStb::stb_textedit_replace (ImGuiInputTextState * str, STB_TexteditState * state, const char * text, int text_len) static
Definition at line 4233 of file imgui_widgets.cpp.
References STB_TexteditState::cursor, STB_TexteditState::has_preferred_x, IM_ASSERT, STB_TexteditState::select_end, STB_TexteditState::select_start, STB_TEXTEDIT_DELETECHARS(), STB_TEXTEDIT_INSERTCHARS(), and ImGuiInputTextState::TextLen.
STB_TEXTEDIT_STRINGLEN()
static int ImStb::STB_TEXTEDIT_STRINGLEN (const ImGuiInputTextState * obj) static
Definition at line 3985 of file imgui_widgets.cpp.
References ImGuiInputTextState::TextLen.
Referenced by STB_TEXTEDIT_MOVELINEEND_IMPL().
Variable Documentation
STB_TEXTEDIT_NEWLINE
char ImStb::STB_TEXTEDIT_NEWLINE = '\n' static
Definition at line 3988 of file imgui_widgets.cpp.
Referenced by STB_TEXTEDIT_MOVELINEEND_IMPL(), and STB_TEXTEDIT_MOVELINESTART_IMPL().