SignalProcessing: MyImPlot Namespace Reference
MyImPlot Namespace Reference
Classes
struct Vector2f
struct WaveData
Functions
ImPlotPoint SineWave (int idx, void *wave_data)
ImPlotPoint SawWave (int idx, void *wave_data)
ImPlotPoint Spiral (int idx, void *wave_data)
void Sparkline (const char *id, const float *values, int count, float min_v, float max_v, int offset, const ImVec4 &col, const ImVec2 &size)
void PlotCandlestick (const char *label_id, const double *xs, const double *opens, const double *closes, const double *lows, const double *highs, int count, bool tooltip=true, float width_percent=0.25f, ImVec4 bullCol=ImVec4(0, 1, 0, 1), ImVec4 bearCol=ImVec4(1, 0, 0, 1))
void StyleSeaborn ()
template<typename T >
int BinarySearch (const T *arr, int l, int r, T x)
Function Documentation
BinarySearch()
template<typename T > int MyImPlot::BinarySearch (const T * arr, int l, int r, T x)
Definition at line 2427 of file implot_demo.cpp.
References BinarySearch().
Referenced by BinarySearch(), and PlotCandlestick().
PlotCandlestick()
void MyImPlot::PlotCandlestick (const char * label_id, const double * xs, const double * opens, const double * closes, const double * lows, const double * highs, int count, bool tooltip = true, float width_percent = 0.25f, ImVec4 bullCol = ImVec4(0,1,0,1), ImVec4 bearCol = ImVec4(1,0,0,1))
Definition at line 2439 of file implot_demo.cpp.
References ImDrawList::AddLine(), ImDrawList::AddRectFilled(), ImPlot::BeginItem(), ImGui::BeginTooltip(), BinarySearch(), ImPlotItem::Color, ImPlot::EndItem(), ImGui::EndTooltip(), ImPlot::FitPoint(), ImPlot::FitThisFrame(), ImPlot::FormatDate(), ImPlotTime::FromDouble(), ImGui::GetColorU32(), ImPlot::GetCurrentItem(), ImPlot::GetPlotDrawList(), ImPlot::GetPlotMousePos(), ImPlot::GetPlotPos(), ImPlot::GetPlotSize(), ImPlot::GetStyle(), IM_COL32, ImPlotDateFmt_DayMoYr, ImPlotTimeUnit_Day, ImPlot::IsPlotHovered(), ImPlot::PlotToPixels(), ImPlot::PopPlotClipRect(), ImPlot::PushPlotClipRect(), ImPlot::RoundTime(), ImGui::Text(), ImPlotTime::ToDouble(), ImVec2::x, ImPlotPoint::x, ImVec2::y, and ImPlotPoint::y.
Referenced by ImPlot::Demo_CustomPlottersAndTooltips().
SawWave()
ImPlotPoint MyImPlot::SawWave (int idx, void * wave_data)
Definition at line 2333 of file implot_demo.cpp.
References MyImPlot::WaveData::Amp, MyImPlot::WaveData::Freq, MyImPlot::WaveData::Offset, and MyImPlot::WaveData::X.
Referenced by ImPlot::Demo_CustomDataAndGetters(), and ImPlot::Demo_LegendOptions().
SineWave()
ImPlotPoint MyImPlot::SineWave (int idx, void * wave_data)
Definition at line 2327 of file implot_demo.cpp.
References MyImPlot::WaveData::Amp, MyImPlot::WaveData::Freq, MyImPlot::WaveData::Offset, and MyImPlot::WaveData::X.
Referenced by ImPlot::Demo_CustomDataAndGetters().
Sparkline()
void MyImPlot::Sparkline (const char * id, const float * values, int count, float min_v, float max_v, int offset, const ImVec4 & col, const ImVec2 & size)
Definition at line 2350 of file implot_demo.cpp.
References ImPlot::BeginPlot(), ImPlot::EndPlot(), ImGuiCond_Always, ImPlotAxisFlags_NoDecorations, ImPlotFlags_CanvasOnly, ImPlotLineFlags_Shaded, ImPlotStyleVar_PlotPadding, ImPlot::PlotLine(), ImPlot::PopStyleVar(), ImPlot::PushStyleVar(), ImPlot::SetNextFillStyle(), ImPlot::SetNextLineStyle(), ImPlot::SetupAxes(), and ImPlot::SetupAxesLimits().
Referenced by ImPlot::Demo_Tables().
Spiral()
ImPlotPoint MyImPlot::Spiral (int idx, void * wave_data)
Definition at line 2339 of file implot_demo.cpp.
Referenced by ImPlot::Demo_CustomDataAndGetters().
StyleSeaborn()
void MyImPlot::StyleSeaborn ()
Definition at line 2363 of file implot_demo.cpp.
References ImPlotStyle::Colors, ImPlotStyle::DigitalBitGap, ImPlotStyle::DigitalBitHeight, ImPlotStyle::ErrorBarSize, ImPlotStyle::ErrorBarWeight, ImPlotStyle::FillAlpha, ImPlot::GetStyle(), IMPLOT_AUTO_COL, ImPlotCol_AxisBgActive, ImPlotCol_AxisBgHovered, ImPlotCol_AxisGrid, ImPlotCol_AxisText, ImPlotCol_Crosshairs, ImPlotCol_ErrorBar, ImPlotCol_Fill, ImPlotCol_FrameBg, ImPlotCol_InlayText, ImPlotCol_LegendBg, ImPlotCol_LegendBorder, ImPlotCol_LegendText, ImPlotCol_Line, ImPlotCol_MarkerFill, ImPlotCol_MarkerOutline, ImPlotCol_PlotBg, ImPlotCol_PlotBorder, ImPlotCol_Selection, ImPlotCol_TitleText, ImPlotMarker_None, ImPlotStyle::LabelPadding, ImPlotStyle::LegendPadding, ImPlotStyle::LineWeight, ImPlotStyle::MajorGridSize, ImPlotStyle::MajorTickLen, ImPlotStyle::MajorTickSize, ImPlotStyle::Marker, ImPlotStyle::MarkerSize, ImPlotStyle::MarkerWeight, ImPlotStyle::MinorAlpha, ImPlotStyle::MinorGridSize, ImPlotStyle::MinorTickLen, ImPlotStyle::MinorTickSize, ImPlotStyle::MousePosPadding, ImPlotStyle::PlotBorderSize, ImPlotStyle::PlotMinSize, and ImPlotStyle::PlotPadding.
Referenced by ImPlot::Demo_CustomStyles().