SignalProcessing: ImGuiFreeType Namespace Reference
ImGuiFreeType Namespace Reference
Functions
IMGUI_API const ImFontLoader * GetFontLoader ()
IMGUI_API void SetAllocatorFunctions (void *(*alloc_func)(size_t sz, void *user_data), void(*free_func)(void *ptr, void *user_data), void *user_data=nullptr)
IMGUI_API bool DebugEditFontLoaderFlags (ImGuiFreeTypeLoaderFlags *p_font_loader_flags)
Function Documentation
DebugEditFontLoaderFlags()
bool ImGuiFreeType::DebugEditFontLoaderFlags (ImGuiFreeTypeLoaderFlags * p_font_loader_flags)
Definition at line 600 of file imgui_freetype.cpp.
References ImGui::CheckboxFlags(), ImGuiFreeTypeLoaderFlags_Bitmap, ImGuiFreeTypeLoaderFlags_Bold, ImGuiFreeTypeLoaderFlags_ForceAutoHint, ImGuiFreeTypeLoaderFlags_LightHinting, ImGuiFreeTypeLoaderFlags_LoadColor, ImGuiFreeTypeLoaderFlags_Monochrome, ImGuiFreeTypeLoaderFlags_MonoHinting, ImGuiFreeTypeLoaderFlags_NoAutoHint, ImGuiFreeTypeLoaderFlags_NoHinting, and ImGuiFreeTypeLoaderFlags_Oblique.
Referenced by ImGui::DebugNodeFont(), and ImGui::ShowFontAtlas().
GetFontLoader()
const ImFontLoader * ImGuiFreeType::GetFontLoader ()
Definition at line 577 of file imgui_freetype.cpp.
References ImFontLoader::FontBakedDestroy, ImFontLoader::FontBakedInit, ImFontLoader::FontBakedLoadGlyph, ImFontLoader::FontBakedSrcLoaderDataSize, ImFontLoader::FontSrcContainsGlyph, ImFontLoader::FontSrcDestroy, ImFontLoader::FontSrcInit, ImGui_ImplFreeType_FontBakedDestroy(), ImGui_ImplFreeType_FontBakedInit(), ImGui_ImplFreeType_FontBakedLoadGlyph(), ImGui_ImplFreetype_FontSrcContainsGlyph(), ImGui_ImplFreeType_FontSrcDestroy(), ImGui_ImplFreeType_FontSrcInit(), ImGui_ImplFreeType_LoaderInit(), ImGui_ImplFreeType_LoaderShutdown(), ImFontLoader::LoaderInit, ImFontLoader::LoaderShutdown, and ImFontLoader::Name.
Referenced by ImFontAtlasBuildInit(), and ImGui::ShowFontAtlas().
SetAllocatorFunctions()
void ImGuiFreeType::SetAllocatorFunctions (void *(*)(size_t sz, void *user_data) alloc_func, void(*)(void *ptr, void *user_data) free_func, void * user_data = nullptr)
Definition at line 593 of file imgui_freetype.cpp.
References GImGuiFreeTypeAllocatorUserData, GImGuiFreeTypeAllocFunc, and GImGuiFreeTypeFreeFunc.