SignalProcessing: ImPlotTicker Struct Reference
ImPlotTicker Struct Reference
#include <implot_internal.h>
Public Member Functions
ImPlotTicker ()
ImPlotTick & AddTick (double value, bool major, int level, bool show_label, const char *label)
ImPlotTick & AddTick (double value, bool major, int level, bool show_label, ImPlotFormatter formatter, void *data)
ImPlotTick & AddTick (ImPlotTick tick)
const char * GetText (int idx) const
const char * GetText (const ImPlotTick &tick)
void OverrideSizeLate (const ImVec2 &size)
void Reset ()
int TickCount () const
Public Attributes
ImVector< ImPlotTick > Ticks
ImGuiTextBuffer TextBuffer
ImVec2 MaxSize
ImVec2 LateSize
int Levels
Detailed Description
Definition at line 575 of file implot_internal.h.
Constructor & Destructor Documentation
ImPlotTicker()
ImPlotTicker::ImPlotTicker () inline
Definition at line 582 of file implot_internal.h.
References Reset().
Member Function Documentation
AddTick() [1/3]
ImPlotTick & ImPlotTicker::AddTick (double value, bool major, int level, bool show_label, const char * label) inline
Definition at line 586 of file implot_internal.h.
References AddTick(), ImGuiTextBuffer::append(), ImGuiTextBuffer::Buf, ImGui::CalcTextSize(), ImVector< T >::Data, ImPlotTick::LabelSize, ImGuiTextBuffer::size(), TextBuffer, and ImPlotTick::TextOffset.
Referenced by AddTick(), AddTick(), ImPlot::AddTicksCustom(), ImPlot::AddTicksLogarithmic(), ImPlot::Locator_Default(), ImPlot::Locator_SymLog(), and ImPlot::Locator_Time().
AddTick() [2/3]
ImPlotTick & ImPlotTicker::AddTick (double value, bool major, int level, bool show_label, ImPlotFormatter formatter, void * data) inline
Definition at line 596 of file implot_internal.h.
References AddTick(), ImGuiTextBuffer::append(), ImGuiTextBuffer::Buf, ImGui::CalcTextSize(), ImVector< T >::Data, IMPLOT_LABEL_MAX_SIZE, ImPlotTick::LabelSize, ImPlotTick::PlotPos, ImGuiTextBuffer::size(), TextBuffer, and ImPlotTick::TextOffset.
AddTick() [3/3]
ImPlotTick & ImPlotTicker::AddTick (ImPlotTick tick) inline
Definition at line 608 of file implot_internal.h.
References ImVector< T >::back(), ImPlotTick::Idx, ImPlotTick::LabelSize, MaxSize, ImVector< T >::push_back(), ImPlotTick::ShowLabel, ImVector< T >::size(), Ticks, ImVec2::x, and ImVec2::y.
GetText() [1/2]
const char * ImPlotTicker::GetText (const ImPlotTick & tick) inline
Definition at line 622 of file implot_internal.h.
References GetText(), and ImPlotTick::Idx.
GetText() [2/2]
const char * ImPlotTicker::GetText (int idx) const inline
Definition at line 618 of file implot_internal.h.
References ImGuiTextBuffer::Buf, ImVector< T >::Data, TextBuffer, and Ticks.
Referenced by ImPlot::ColormapScale(), GetText(), ImPlot::Locator_Time(), and ImPlot::SetupFinish().
OverrideSizeLate()
void ImPlotTicker::OverrideSizeLate (const ImVec2 & size) inline
Definition at line 626 of file implot_internal.h.
References LateSize, ImVec2::x, and ImVec2::y.
Referenced by ImPlot::EndPlot().
Reset()
void ImPlotTicker::Reset () inline
Definition at line 631 of file implot_internal.h.
References ImGuiTextBuffer::Buf, LateSize, Levels, MaxSize, ImVector< T >::shrink(), TextBuffer, and Ticks.
Referenced by ImPlot::ColormapScale(), ImPlotTicker(), and ImPlotAxis::Reset().
TickCount()
int ImPlotTicker::TickCount () const inline
Definition at line 639 of file implot_internal.h.
References ImVector< T >::Size, and Ticks.
Referenced by ImPlot::AxisPrecision(), ImPlot::ColormapScale(), ImPlot::EndPlot(), ImPlot::Locator_Default(), ImPlot::RenderGridLinesX(), ImPlot::RenderGridLinesY(), ImPlot::SetupFinish(), and ImPlot::ShowTicksMetrics().
Member Data Documentation
LateSize
ImVec2 ImPlotTicker::LateSize
Definition at line 579 of file implot_internal.h.
Referenced by OverrideSizeLate(), and Reset().
Levels
int ImPlotTicker::Levels
Definition at line 580 of file implot_internal.h.
Referenced by Reset(), ImPlot::SetupAxisScale(), and ImPlot::SetupFinish().
MaxSize
ImVec2 ImPlotTicker::MaxSize
Definition at line 578 of file implot_internal.h.
Referenced by AddTick(), ImPlot::ColormapScale(), ImPlot::PadAndDatumAxesX(), ImPlot::PadAndDatumAxesY(), Reset(), ImPlot::SetupFinish(), and ImPlot::ShowTicksMetrics().
TextBuffer
ImGuiTextBuffer ImPlotTicker::TextBuffer
Definition at line 577 of file implot_internal.h.
Referenced by AddTick(), AddTick(), GetText(), ImPlot::Locator_Time(), and Reset().
Ticks
ImVector<ImPlotTick> ImPlotTicker::Ticks
Definition at line 576 of file implot_internal.h.
Referenced by AddTick(), ImPlot::AxisPrecision(), ImPlot::ColormapScale(), ImPlot::EndPlot(), GetText(), ImPlot::Locator_Default(), ImPlot::RenderGridLinesX(), ImPlot::RenderGridLinesY(), Reset(), ImPlot::SetupFinish(), and TickCount().
The documentation for this struct was generated from the following file:
examples/implot/implot_internal.h