SignalProcessing: ImPlot::RendererLineSegments1< _Getter > Struct Template Reference
ImPlot::RendererLineSegments1< _Getter > Struct Template Reference
Public Member Functions
RendererLineSegments1 (const _Getter &getter, ImU32 col, float weight)
void Init (ImDrawList &draw_list) const
bool Render (ImDrawList &draw_list, const ImRect &cull_rect, int prim) const
Public Member Functions inherited from ImPlot::RendererBase
RendererBase (int prims, int idx_consumed, int vtx_consumed)
Public Attributes
const _Getter & Getter
const ImU32 Col
float HalfWeight
ImVec2 UV0
ImVec2 UV1
Public Attributes inherited from ImPlot::RendererBase
const int Prims
Transformer2 Transformer
const int IdxConsumed
const int VtxConsumed
Detailed Description
template<class _Getter>
struct ImPlot::RendererLineSegments1< _Getter >
Definition at line 932 of file implot_items.cpp.
Constructor & Destructor Documentation
RendererLineSegments1()
template<class _Getter > ImPlot::RendererLineSegments1< _Getter >::RendererLineSegments1 (const _Getter & getter, ImU32 col, float weight) inline
Definition at line 933 of file implot_items.cpp.
Member Function Documentation
Init()
template<class _Getter > void ImPlot::RendererLineSegments1< _Getter >::Init (ImDrawList & draw_list) const inline
Definition at line 939 of file implot_items.cpp.
References ImPlot::draw_list, ImPlot::GetLineRenderProps(), ImPlot::RendererLineSegments1< _Getter >::HalfWeight, ImPlot::RendererLineSegments1< _Getter >::UV0, and ImPlot::RendererLineSegments1< _Getter >::UV1.
Render()
template<class _Getter > bool ImPlot::RendererLineSegments1< _Getter >::Render (ImDrawList & draw_list, const ImRect & cull_rect, int prim) const inline
Definition at line 942 of file implot_items.cpp.
References ImPlot::RendererLineSegments1< _Getter >::Col, ImPlot::draw_list, ImPlot::RendererLineSegments1< _Getter >::Getter, ImPlot::RendererLineSegments1< _Getter >::HalfWeight, ImMax(), ImMin(), ImRect::Overlaps(), ImPlot::PrimLine(), ImPlot::RendererBase::Transformer, ImPlot::RendererLineSegments1< _Getter >::UV0, and ImPlot::RendererLineSegments1< _Getter >::UV1.
Member Data Documentation
Col
template<class _Getter > const ImU32 ImPlot::RendererLineSegments1< _Getter >::Col
Definition at line 951 of file implot_items.cpp.
Referenced by ImPlot::RendererLineSegments1< _Getter >::Render().
Getter
template<class _Getter > const _Getter& ImPlot::RendererLineSegments1< _Getter >::Getter
Definition at line 950 of file implot_items.cpp.
Referenced by ImPlot::RendererLineSegments1< _Getter >::Render().
HalfWeight
template<class _Getter > float ImPlot::RendererLineSegments1< _Getter >::HalfWeight mutable
Definition at line 952 of file implot_items.cpp.
Referenced by ImPlot::RendererLineSegments1< _Getter >::Init(), and ImPlot::RendererLineSegments1< _Getter >::Render().
UV0
template<class _Getter > ImVec2 ImPlot::RendererLineSegments1< _Getter >::UV0 mutable
Definition at line 953 of file implot_items.cpp.
Referenced by ImPlot::RendererLineSegments1< _Getter >::Init(), and ImPlot::RendererLineSegments1< _Getter >::Render().
UV1
template<class _Getter > ImVec2 ImPlot::RendererLineSegments1< _Getter >::UV1 mutable
Definition at line 954 of file implot_items.cpp.
Referenced by ImPlot::RendererLineSegments1< _Getter >::Init(), and ImPlot::RendererLineSegments1< _Getter >::Render().
The documentation for this struct was generated from the following file:
examples/implot/implot_items.cpp