SignalProcessing: ImPlotItemGroup Struct Reference
ImPlotItemGroup Struct Reference
#include <implot_internal.h>
Public Member Functions
ImPlotItemGroup ()
int GetItemCount () const
ImGuiID GetItemID (const char *label_id)
ImPlotItem * GetItem (ImGuiID id)
ImPlotItem * GetItem (const char *label_id)
ImPlotItem * GetOrAddItem (ImGuiID id)
ImPlotItem * GetItemByIndex (int i)
int GetItemIndex (ImPlotItem *item)
int GetLegendCount () const
ImPlotItem * GetLegendItem (int i)
const char * GetLegendLabel (int i)
void Reset ()
Public Attributes
ImGuiID ID
ImPlotLegend Legend
ImPool< ImPlotItem > ItemPool
int ColormapIdx
Detailed Description
Definition at line 1011 of file implot_internal.h.
Constructor & Destructor Documentation
ImPlotItemGroup()
ImPlotItemGroup::ImPlotItemGroup () inline
Definition at line 1018 of file implot_internal.h.
References ColormapIdx, and ID.
Member Function Documentation
GetItem() [1/2]
ImPlotItem * ImPlotItemGroup::GetItem (const char * label_id) inline
Definition at line 1023 of file implot_internal.h.
References GetItem(), and GetItemID().
Referenced by GetItem().
GetItem() [2/2]
ImPlotItem * ImPlotItemGroup::GetItem (ImGuiID id) inline
Definition at line 1022 of file implot_internal.h.
References ImPool< T >::GetByKey(), and ItemPool.
Referenced by ImPlot::BeginDragDropSourceItem(), ImPlot::BeginLegendPopup(), ImPlot::GetItem(), ImPlot::IsLegendEntryHovered(), and ImPlot::RegisterOrGetItem().
GetItemByIndex()
ImPlotItem * ImPlotItemGroup::GetItemByIndex (int i) inline
Definition at line 1025 of file implot_internal.h.
References ImPool< T >::GetByIndex(), and ItemPool.
Referenced by ImPlot::EndPlot(), ImPlot::EndSubplots(), and ImPlot::ShowMetricsWindow().
GetItemCount()
int ImPlotItemGroup::GetItemCount () const inline
Definition at line 1020 of file implot_internal.h.
References ImPool< T >::GetBufSize(), and ItemPool.
Referenced by ImPlot::EndPlot(), ImPlot::EndSubplots(), and ImPlot::ShowMetricsWindow().
GetItemID()
ImGuiID ImPlotItemGroup::GetItemID (const char * label_id) inline
Definition at line 1021 of file implot_internal.h.
References ImGui::GetID().
Referenced by GetItem(), and ImPlot::RegisterOrGetItem().
GetItemIndex()
int ImPlotItemGroup::GetItemIndex (ImPlotItem * item) inline
Definition at line 1026 of file implot_internal.h.
References ImPool< T >::GetIndex(), and ItemPool.
Referenced by ImPlot::RegisterOrGetItem().
GetLegendCount()
int ImPlotItemGroup::GetLegendCount () const inline
Definition at line 1027 of file implot_internal.h.
References ImPlotLegend::Indices, Legend, and ImVector< T >::size().
Referenced by ImPlot::BeginSubplots(), ImPlot::CalcLegendSize(), ImPlot::EndPlot(), ImPlot::EndSubplots(), ImPlot::SetupFinish(), ImPlot::ShowLegendEntries(), and ImPlot::ShowMetricsWindow().
GetLegendItem()
ImPlotItem * ImPlotItemGroup::GetLegendItem (int i) inline
Definition at line 1028 of file implot_internal.h.
References ImPool< T >::GetByIndex(), ImPlotLegend::Indices, ItemPool, and Legend.
Referenced by GetLegendLabel(), and ImPlot::ShowLegendEntries().
GetLegendLabel()
const char * ImPlotItemGroup::GetLegendLabel (int i) inline
Definition at line 1029 of file implot_internal.h.
References ImGuiTextBuffer::Buf, ImVector< T >::Data, GetLegendItem(), ImPlotLegend::Labels, Legend, and ImPlotItem::NameOffset.
Referenced by ImPlot::CalcLegendSize(), ImPlot::LegendSortingComp(), and ImPlot::ShowLegendEntries().
GetOrAddItem()
ImPlotItem * ImPlotItemGroup::GetOrAddItem (ImGuiID id) inline
Definition at line 1024 of file implot_internal.h.
References ImPool< T >::GetOrAddByKey(), and ItemPool.
Referenced by ImPlot::RegisterOrGetItem().
Reset()
void ImPlotItemGroup::Reset () inline
Definition at line 1030 of file implot_internal.h.
References ImPool< T >::Clear(), ColormapIdx, ItemPool, Legend, and ImPlotLegend::Reset().
Referenced by ImPlot::BustColorCache(), and ImPlot::BustItemCache().
Member Data Documentation
ColormapIdx
int ImPlotItemGroup::ColormapIdx
Definition at line 1016 of file implot_internal.h.
Referenced by ImPlotItemGroup(), ImPlot::NextColormapColorU32(), and Reset().
ID
ImGuiID ImPlotItemGroup::ID
Definition at line 1013 of file implot_internal.h.
Referenced by ImPlot::BeginDragDropSourceItem(), ImPlot::BeginDragDropTargetLegend(), ImPlot::BeginLegendPopup(), ImPlot::BeginPlot(), ImPlot::BeginSubplots(), ImPlot::EndPlot(), ImPlot::EndSubplots(), ImPlotItemGroup(), ImPlot::IsLegendEntryHovered(), and ImPlot::SetupFinish().
ItemPool
ImPool<ImPlotItem> ImPlotItemGroup::ItemPool
Definition at line 1015 of file implot_internal.h.
Referenced by GetItem(), GetItemByIndex(), GetItemCount(), GetItemIndex(), GetLegendItem(), GetOrAddItem(), and Reset().
Legend
ImPlotLegend ImPlotItemGroup::Legend
Definition at line 1014 of file implot_internal.h.
Referenced by ImPlot::BeginDragDropTargetLegend(), ImPlot::BeginItem(), ImPlot::BeginSubplots(), ImPlot::EndPlot(), ImPlot::EndSubplots(), GetLegendCount(), GetLegendItem(), GetLegendLabel(), ImPlotSubplot::ImPlotSubplot(), ImPlot::RegisterOrGetItem(), Reset(), ImPlot::SetupFinish(), ImPlot::SetupLegend(), ImPlot::ShowLegendEntries(), ImPlot::ShowMetricsWindow(), and ImPlot::ShowPlotContextMenu().
The documentation for this struct was generated from the following file:
examples/implot/implot_internal.h