SignalProcessing: ImPlot::RendererLineSegments2< _Getter1, _Getter2 > Struct Template Reference
ImPlot::RendererLineSegments2< _Getter1, _Getter2 > Struct Template Reference
Public Member Functions
RendererLineSegments2 (const _Getter1 &getter1, const _Getter2 &getter2, ImU32 col, float weight)
void Init (ImDrawList &draw_list) const
bool Render (ImDrawList &draw_list, const ImRect &cull_rect, int prim) const
Public Member Functions inherited from ImPlot::RendererBase
RendererBase (int prims, int idx_consumed, int vtx_consumed)
Public Attributes
const _Getter1 & Getter1
const _Getter2 & Getter2
const ImU32 Col
float HalfWeight
ImVec2 UV0
ImVec2 UV1
Public Attributes inherited from ImPlot::RendererBase
const int Prims
Transformer2 Transformer
const int IdxConsumed
const int VtxConsumed
Detailed Description
template<class _Getter1, class _Getter2>
struct ImPlot::RendererLineSegments2< _Getter1, _Getter2 >
Definition at line 958 of file implot_items.cpp.
Constructor & Destructor Documentation
RendererLineSegments2()
template<class _Getter1 , class _Getter2 > ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::RendererLineSegments2 (const _Getter1 & getter1, const _Getter2 & getter2, ImU32 col, float weight) inline
Definition at line 959 of file implot_items.cpp.
Member Function Documentation
Init()
template<class _Getter1 , class _Getter2 > void ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Init (ImDrawList & draw_list) const inline
Definition at line 966 of file implot_items.cpp.
References ImPlot::draw_list, ImPlot::GetLineRenderProps(), ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::HalfWeight, ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::UV0, and ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::UV1.
Render()
template<class _Getter1 , class _Getter2 > bool ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Render (ImDrawList & draw_list, const ImRect & cull_rect, int prim) const inline
Definition at line 969 of file implot_items.cpp.
References ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Col, ImPlot::draw_list, ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Getter1, ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Getter2, ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::HalfWeight, ImMax(), ImMin(), ImRect::Overlaps(), ImPlot::PrimLine(), ImPlot::RendererBase::Transformer, ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::UV0, and ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::UV1.
Member Data Documentation
Col
template<class _Getter1 , class _Getter2 > const ImU32 ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Col
Definition at line 979 of file implot_items.cpp.
Referenced by ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Render().
Getter1
template<class _Getter1 , class _Getter2 > const _Getter1& ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Getter1
Definition at line 977 of file implot_items.cpp.
Referenced by ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Render().
Getter2
template<class _Getter1 , class _Getter2 > const _Getter2& ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Getter2
Definition at line 978 of file implot_items.cpp.
Referenced by ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Render().
HalfWeight
template<class _Getter1 , class _Getter2 > float ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::HalfWeight mutable
Definition at line 980 of file implot_items.cpp.
Referenced by ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Init(), and ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Render().
UV0
template<class _Getter1 , class _Getter2 > ImVec2 ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::UV0 mutable
Definition at line 981 of file implot_items.cpp.
Referenced by ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Init(), and ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Render().
UV1
template<class _Getter1 , class _Getter2 > ImVec2 ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::UV1 mutable
Definition at line 982 of file implot_items.cpp.
Referenced by ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Init(), and ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Render().
The documentation for this struct was generated from the following file:
examples/implot/implot_items.cpp