SignalProcessing: ExampleDescriptorHeapAllocator Struct Reference
ExampleDescriptorHeapAllocator Struct Reference
Public Member Functions
void Create (ID3D12Device *device, ID3D12DescriptorHeap *heap)
void Destroy ()
void Alloc (D3D12_CPU_DESCRIPTOR_HANDLE *out_cpu_desc_handle, D3D12_GPU_DESCRIPTOR_HANDLE *out_gpu_desc_handle)
void Free (D3D12_CPU_DESCRIPTOR_HANDLE out_cpu_desc_handle, D3D12_GPU_DESCRIPTOR_HANDLE out_gpu_desc_handle)
Public Attributes
ID3D12DescriptorHeap * Heap = nullptr
D3D12_DESCRIPTOR_HEAP_TYPE HeapType = D3D12_DESCRIPTOR_HEAP_TYPE_NUM_TYPES
D3D12_CPU_DESCRIPTOR_HANDLE HeapStartCpu
D3D12_GPU_DESCRIPTOR_HANDLE HeapStartGpu
UINT HeapHandleIncrement
ImVector< int > FreeIndices
Detailed Description
Definition at line 37 of file main.cpp.
Member Function Documentation
Alloc()
void ExampleDescriptorHeapAllocator::Alloc (D3D12_CPU_DESCRIPTOR_HANDLE * out_cpu_desc_handle, D3D12_GPU_DESCRIPTOR_HANDLE * out_gpu_desc_handle) inline
Definition at line 64 of file main.cpp.
References ImVector< T >::back(), FreeIndices, HeapHandleIncrement, HeapStartCpu, HeapStartGpu, IM_ASSERT, ImVector< T >::pop_back(), and ImVector< T >::Size.
Referenced by main().
Create()
void ExampleDescriptorHeapAllocator::Create (ID3D12Device * device, ID3D12DescriptorHeap * heap) inline
Definition at line 46 of file main.cpp.
References ImVector< T >::empty(), FreeIndices, Heap, HeapHandleIncrement, HeapStartCpu, HeapStartGpu, HeapType, IM_ASSERT, ImVector< T >::push_back(), and ImVector< T >::reserve().
Referenced by CreateDeviceD3D().
Destroy()
void ExampleDescriptorHeapAllocator::Destroy () inline
Definition at line 59 of file main.cpp.
References ImVector< T >::clear(), FreeIndices, and Heap.
Free()
void ExampleDescriptorHeapAllocator::Free (D3D12_CPU_DESCRIPTOR_HANDLE out_cpu_desc_handle, D3D12_GPU_DESCRIPTOR_HANDLE out_gpu_desc_handle) inline
Definition at line 72 of file main.cpp.
References FreeIndices, HeapHandleIncrement, HeapStartCpu, HeapStartGpu, IM_ASSERT, and ImVector< T >::push_back().
Referenced by main().
Member Data Documentation
FreeIndices
ImVector<int> ExampleDescriptorHeapAllocator::FreeIndices
Definition at line 44 of file main.cpp.
Referenced by Alloc(), Create(), Destroy(), and Free().
Heap
ID3D12DescriptorHeap* ExampleDescriptorHeapAllocator::Heap = nullptr
Definition at line 39 of file main.cpp.
Referenced by Create(), and Destroy().
HeapHandleIncrement
UINT ExampleDescriptorHeapAllocator::HeapHandleIncrement
Definition at line 43 of file main.cpp.
Referenced by Alloc(), Create(), and Free().
HeapStartCpu
D3D12_CPU_DESCRIPTOR_HANDLE ExampleDescriptorHeapAllocator::HeapStartCpu
Definition at line 41 of file main.cpp.
Referenced by Alloc(), Create(), and Free().
HeapStartGpu
D3D12_GPU_DESCRIPTOR_HANDLE ExampleDescriptorHeapAllocator::HeapStartGpu
Definition at line 42 of file main.cpp.
Referenced by Alloc(), Create(), and Free().
HeapType
D3D12_DESCRIPTOR_HEAP_TYPE ExampleDescriptorHeapAllocator::HeapType = D3D12_DESCRIPTOR_HEAP_TYPE_NUM_TYPES
Definition at line 40 of file main.cpp.
Referenced by Create().
The documentation for this struct was generated from the following file:
examples/imgui/examples/example_win32_directx12/main.cpp