SignalProcessing: ImPlotColormapData Struct Reference
ImPlotColormapData Struct Reference
#include <implot_internal.h>
Public Member Functions
ImPlotColormapData ()
int Append (const char *name, const ImU32 *keys, int count, bool qual)
void _AppendTable (ImPlotColormap cmap)
void RebuildTables ()
bool IsQual (ImPlotColormap cmap) const
const char * GetName (ImPlotColormap cmap) const
ImPlotColormap GetIndex (const char *name) const
const ImU32 * GetKeys (ImPlotColormap cmap) const
int GetKeyCount (ImPlotColormap cmap) const
ImU32 GetKeyColor (ImPlotColormap cmap, int idx) const
void SetKeyColor (ImPlotColormap cmap, int idx, ImU32 value)
const ImU32 * GetTable (ImPlotColormap cmap) const
int GetTableSize (ImPlotColormap cmap) const
ImU32 GetTableColor (ImPlotColormap cmap, int idx) const
ImU32 LerpTable (ImPlotColormap cmap, float t) const
Public Attributes
ImVector< ImU32 > Keys
ImVector< int > KeyCounts
ImVector< int > KeyOffsets
ImVector< ImU32 > Tables
ImVector< int > TableSizes
ImVector< int > TableOffsets
ImGuiTextBuffer Text
ImVector< int > TextOffsets
ImVector< bool > Quals
ImGuiStorage Map
int Count
Detailed Description
Definition at line 320 of file implot_internal.h.
Constructor & Destructor Documentation
ImPlotColormapData()
ImPlotColormapData::ImPlotColormapData () inline
Definition at line 333 of file implot_internal.h.
References Count.
Member Function Documentation
_AppendTable()
void ImPlotColormapData::_AppendTable (ImPlotColormap cmap) inline
Definition at line 353 of file implot_internal.h.
References GetKeyCount(), GetKeys(), ImMixU32(), IsQual(), ImVector< T >::push_back(), ImVector< T >::reserve(), ImVector< T >::size(), TableOffsets, Tables, and TableSizes.
Referenced by Append(), and RebuildTables().
Append()
int ImPlotColormapData::Append (const char * name, const ImU32 * keys, int count, bool qual) inline
Definition at line 335 of file implot_internal.h.
References _AppendTable(), ImGuiTextBuffer::append(), Count, GetIndex(), ImHashStr(), KeyCounts, KeyOffsets, Keys, Map, ImVector< T >::push_back(), Quals, ImVector< T >::reserve(), ImGuiStorage::SetInt(), ImVector< T >::size(), ImGuiTextBuffer::size(), Text, and TextOffsets.
Referenced by ImPlot::AddColormap(), and ImPlot::AddColormap().
GetIndex()
ImPlotColormap ImPlotColormapData::GetIndex (const char * name) const inline
Definition at line 402 of file implot_internal.h.
References ImGuiStorage::GetInt(), ImHashStr(), and Map.
Referenced by ImPlot::AddColormap(), ImPlot::AddColormap(), Append(), ImPlot::GetColormapIndex(), ImPlot::PushColormap(), and ImPlot::ShowStyleEditor().
GetKeyColor()
ImU32 ImPlotColormapData::GetKeyColor (ImPlotColormap cmap, int idx) const inline
Definition at line 406 of file implot_internal.h.
References KeyOffsets, and Keys.
Referenced by ImPlot::GetColormapColorU32(), ImPlot::NextColormapColorU32(), and ImPlot::ShowStyleEditor().
GetKeyCount()
int ImPlotColormapData::GetKeyCount (ImPlotColormap cmap) const inline
Definition at line 405 of file implot_internal.h.
References KeyCounts.
Referenced by _AppendTable(), ImPlot::ColormapButton(), ImPlot::ColormapIcon(), ImPlot::ColormapScale(), ImPlot::ColormapSlider(), ImPlot::GetColormapColorU32(), ImPlot::GetColormapSize(), ImPlot::NextColormapColorU32(), ImPlot::ShowMetricsWindow(), and ImPlot::ShowStyleEditor().
GetKeys()
const ImU32 * ImPlotColormapData::GetKeys (ImPlotColormap cmap) const inline
Definition at line 404 of file implot_internal.h.
References KeyOffsets, and Keys.
Referenced by _AppendTable(), ImPlot::ColormapButton(), ImPlot::ColormapIcon(), ImPlot::ColormapScale(), and ImPlot::ColormapSlider().
GetName()
const char * ImPlotColormapData::GetName (ImPlotColormap cmap) const inline
Definition at line 401 of file implot_internal.h.
References ImGuiTextBuffer::Buf, Count, ImVector< T >::Data, Text, and TextOffsets.
Referenced by ImPlot::GetColormapName(), ImPlot::ShowColormapSelector(), and ImPlot::ShowMetricsWindow().
GetTable()
const ImU32 * ImPlotColormapData::GetTable (ImPlotColormap cmap) const inline
Definition at line 409 of file implot_internal.h.
References TableOffsets, and Tables.
GetTableColor()
ImU32 ImPlotColormapData::GetTableColor (ImPlotColormap cmap, int idx) const inline
Definition at line 411 of file implot_internal.h.
References TableOffsets, and Tables.
Referenced by ImPlot::ShowMetricsWindow().
GetTableSize()
int ImPlotColormapData::GetTableSize (ImPlotColormap cmap) const inline
Definition at line 410 of file implot_internal.h.
References TableSizes.
Referenced by ImPlot::ShowMetricsWindow().
IsQual()
bool ImPlotColormapData::IsQual (ImPlotColormap cmap) const inline
Definition at line 400 of file implot_internal.h.
References Quals.
Referenced by _AppendTable(), ImPlot::ColormapButton(), ImPlot::ColormapIcon(), ImPlot::ColormapScale(), ImPlot::ColormapSlider(), and ImPlot::ShowMetricsWindow().
LerpTable()
ImU32 ImPlotColormapData::LerpTable (ImPlotColormap cmap, float t) const inline
Definition at line 413 of file implot_internal.h.
References ImClamp(), Quals, TableOffsets, Tables, and TableSizes.
Referenced by ImPlot::ColormapButton(), ImPlot::ColormapScale(), ImPlot::ColormapSlider(), ImPlot::float(), ImPlot::GetterHeatmapColMaj< T >::operator()(), and ImPlot::SampleColormapU32().
RebuildTables()
void ImPlotColormapData::RebuildTables () inline
Definition at line 392 of file implot_internal.h.
References _AppendTable(), Count, ImVector< T >::resize(), TableOffsets, Tables, and TableSizes.
Referenced by SetKeyColor().
SetKeyColor()
void ImPlotColormapData::SetKeyColor (ImPlotColormap cmap, int idx, ImU32 value) inline
Definition at line 407 of file implot_internal.h.
References KeyOffsets, Keys, and RebuildTables().
Referenced by ImPlot::ShowStyleEditor().
Member Data Documentation
Count
int ImPlotColormapData::Count
Definition at line 331 of file implot_internal.h.
Referenced by Append(), ImPlot::ColormapButton(), ImPlot::ColormapScale(), ImPlot::ColormapSlider(), ImPlot::GetColormapColorU32(), ImPlot::GetColormapCount(), ImPlot::GetColormapSize(), GetName(), ImPlotColormapData(), ImPlot::PushColormap(), RebuildTables(), ImPlot::SampleColormapU32(), ImPlot::ShowColormapSelector(), ImPlot::ShowMetricsWindow(), and ImPlot::ShowStyleEditor().
KeyCounts
ImVector<int> ImPlotColormapData::KeyCounts
Definition at line 322 of file implot_internal.h.
Referenced by Append(), and GetKeyCount().
KeyOffsets
ImVector<int> ImPlotColormapData::KeyOffsets
Definition at line 323 of file implot_internal.h.
Referenced by Append(), GetKeyColor(), GetKeys(), and SetKeyColor().
Keys
ImVector<ImU32> ImPlotColormapData::Keys
Definition at line 321 of file implot_internal.h.
Referenced by Append(), GetKeyColor(), GetKeys(), and SetKeyColor().
Map
ImGuiStorage ImPlotColormapData::Map
Definition at line 330 of file implot_internal.h.
Referenced by Append(), and GetIndex().
Quals
ImVector<bool> ImPlotColormapData::Quals
Definition at line 329 of file implot_internal.h.
Referenced by Append(), IsQual(), and LerpTable().
TableOffsets
ImVector<int> ImPlotColormapData::TableOffsets
Definition at line 326 of file implot_internal.h.
Referenced by _AppendTable(), GetTable(), GetTableColor(), LerpTable(), and RebuildTables().
Tables
ImVector<ImU32> ImPlotColormapData::Tables
Definition at line 324 of file implot_internal.h.
Referenced by _AppendTable(), GetTable(), GetTableColor(), LerpTable(), RebuildTables(), and ImPlot::ShowMetricsWindow().
TableSizes
ImVector<int> ImPlotColormapData::TableSizes
Definition at line 325 of file implot_internal.h.
Referenced by _AppendTable(), GetTableSize(), LerpTable(), and RebuildTables().
Text
ImGuiTextBuffer ImPlotColormapData::Text
Definition at line 327 of file implot_internal.h.
Referenced by Append(), and GetName().
TextOffsets
ImVector<int> ImPlotColormapData::TextOffsets
Definition at line 328 of file implot_internal.h.
Referenced by Append(), and GetName().
The documentation for this struct was generated from the following file:
examples/implot/implot_internal.h