SignalProcessing: ImGuiPlatformIO Struct Reference
ImGuiPlatformIO Struct Reference
#include <imgui.h>
Public Member Functions
ImGuiPlatformIO ()
void ClearPlatformHandlers ()
void ClearRendererHandlers ()
Public Attributes
const char *(* Platform_GetClipboardTextFn)(ImGuiContext *ctx)
void(* Platform_SetClipboardTextFn)(ImGuiContext *ctx, const char *text)
void * Platform_ClipboardUserData
bool(* Platform_OpenInShellFn)(ImGuiContext *ctx, const char *path)
void * Platform_OpenInShellUserData
void(* Platform_SetImeDataFn)(ImGuiContext *ctx, ImGuiViewport *viewport, ImGuiPlatformImeData *data)
void * Platform_ImeUserData
ImWchar Platform_LocaleDecimalPoint
int Renderer_TextureMaxWidth
int Renderer_TextureMaxHeight
void * Renderer_RenderState
ImVector< ImTextureData * > Textures
Detailed Description
Definition at line 3941 of file imgui.h.
Constructor & Destructor Documentation
ImGuiPlatformIO()
ImGuiPlatformIO::ImGuiPlatformIO ()
Definition at line 1943 of file imgui.cpp.
References Platform_LocaleDecimalPoint.
Member Function Documentation
ClearPlatformHandlers()
void ImGuiPlatformIO::ClearPlatformHandlers ()
Definition at line 15623 of file imgui.cpp.
References Platform_ClipboardUserData, Platform_GetClipboardTextFn, Platform_ImeUserData, Platform_OpenInShellFn, Platform_OpenInShellUserData, Platform_SetClipboardTextFn, and Platform_SetImeDataFn.
Referenced by ImGui_ImplAllegro5_Shutdown(), ImGui_ImplGlfw_Shutdown(), ImGui_ImplSDL2_Shutdown(), ImGui_ImplSDL3_Shutdown(), and ImGui_ImplWin32_Shutdown().
ClearRendererHandlers()
void ImGuiPlatformIO::ClearRendererHandlers ()
Definition at line 15634 of file imgui.cpp.
References Renderer_RenderState, Renderer_TextureMaxHeight, and Renderer_TextureMaxWidth.
Referenced by ImGui_ImplAllegro5_Shutdown(), ImGui_ImplDX10_Shutdown(), ImGui_ImplDX11_Shutdown(), ImGui_ImplDX12_Shutdown(), ImGui_ImplDX9_Shutdown(), ImGui_ImplOpenGL2_Shutdown(), ImGui_ImplOpenGL3_Shutdown(), ImGui_ImplSDLGPU3_Shutdown(), ImGui_ImplSDLRenderer2_Shutdown(), ImGui_ImplSDLRenderer3_Shutdown(), ImGui_ImplVulkan_Shutdown(), and ImGui_ImplWGPU_Shutdown().
Member Data Documentation
Platform_ClipboardUserData
void* ImGuiPlatformIO::Platform_ClipboardUserData
Definition at line 3953 of file imgui.h.
Referenced by ClearPlatformHandlers(), and ImGui_ImplSDL2_Init().
Platform_GetClipboardTextFn
const char *(* ImGuiPlatformIO::Platform_GetClipboardTextFn) (ImGuiContext *ctx)
Definition at line 3951 of file imgui.h.
Referenced by ClearPlatformHandlers(), ImGui::ErrorCheckNewFrameSanityChecks(), ImGui::GetClipboardText(), ImGui_ImplAllegro5_Init(), ImGui_ImplGlfw_Init(), ImGui_ImplSDL2_Init(), ImGui_ImplSDL3_Init(), and ImGui::Initialize().
Platform_ImeUserData
void* ImGuiPlatformIO::Platform_ImeUserData
Definition at line 3963 of file imgui.h.
Referenced by ClearPlatformHandlers().
Platform_LocaleDecimalPoint
ImWchar ImGuiPlatformIO::Platform_LocaleDecimalPoint
Definition at line 3968 of file imgui.h.
Referenced by ImGuiPlatformIO(), and InputTextFilterCharacter().
Platform_OpenInShellFn
bool(* ImGuiPlatformIO::Platform_OpenInShellFn) (ImGuiContext *ctx, const char *path)
Definition at line 3957 of file imgui.h.
Referenced by ClearPlatformHandlers(), ImGui_ImplGlfw_Init(), ImGui_ImplSDL2_Init(), ImGui_ImplSDL3_Init(), ImGui::Initialize(), and ImGui::TextLinkOpenURL().
Platform_OpenInShellUserData
void* ImGuiPlatformIO::Platform_OpenInShellUserData
Definition at line 3958 of file imgui.h.
Referenced by ClearPlatformHandlers().
Platform_SetClipboardTextFn
void(* ImGuiPlatformIO::Platform_SetClipboardTextFn) (ImGuiContext *ctx, const char *text)
Definition at line 3952 of file imgui.h.
Referenced by ClearPlatformHandlers(), ImGui::ErrorCheckNewFrameSanityChecks(), ImGui_ImplAllegro5_Init(), ImGui_ImplGlfw_Init(), ImGui_ImplSDL2_Init(), ImGui_ImplSDL3_Init(), ImGui::Initialize(), ImGui::InputTextEx(), and ImGui::SetClipboardText().
Platform_SetImeDataFn
void(* ImGuiPlatformIO::Platform_SetImeDataFn) (ImGuiContext *ctx, ImGuiViewport *viewport, ImGuiPlatformImeData *data)
Definition at line 3962 of file imgui.h.
Referenced by ClearPlatformHandlers(), ImGui::EndFrame(), ImGui_ImplSDL2_Init(), ImGui_ImplSDL3_Init(), and ImGui::Initialize().
Renderer_RenderState
void* ImGuiPlatformIO::Renderer_RenderState
Definition at line 3979 of file imgui.h.
Referenced by ClearRendererHandlers(), ImGui_ImplDX10_RenderDrawData(), ImGui_ImplDX11_RenderDrawData(), ImGui_ImplDX12_RenderDrawData(), ImGui_ImplSDLGPU3_RenderDrawData(), ImGui_ImplSDLRenderer2_RenderDrawData(), ImGui_ImplSDLRenderer3_RenderDrawData(), ImGui_ImplVulkan_RenderDrawData(), and ImGui_ImplWGPU_RenderDrawData().
Renderer_TextureMaxHeight
int ImGuiPlatformIO::Renderer_TextureMaxHeight
Definition at line 3976 of file imgui.h.
Referenced by ClearRendererHandlers(), ImGui_ImplDX10_Init(), ImGui_ImplDX11_Init(), ImGui_ImplDX9_Init(), and ImGui_ImplOpenGL3_Init().
Renderer_TextureMaxWidth
int ImGuiPlatformIO::Renderer_TextureMaxWidth
Definition at line 3975 of file imgui.h.
Referenced by ClearRendererHandlers(), ImGui_ImplDX10_Init(), ImGui_ImplDX11_Init(), ImGui_ImplDX9_Init(), and ImGui_ImplOpenGL3_Init().
Textures
ImVector<ImTextureData*> ImGuiPlatformIO::Textures
Definition at line 3987 of file imgui.h.
Referenced by ImGui_ImplAllegro5_InvalidateDeviceObjects(), ImGui_ImplDX10_InvalidateDeviceObjects(), ImGui_ImplDX11_InvalidateDeviceObjects(), ImGui_ImplDX12_InvalidateDeviceObjects(), ImGui_ImplDX9_InvalidateDeviceObjects(), ImGui_ImplOpenGL2_DestroyDeviceObjects(), ImGui_ImplOpenGL3_DestroyDeviceObjects(), ImGui_ImplSDLGPU3_DestroyDeviceObjects(), ImGui_ImplSDLRenderer2_DestroyDeviceObjects(), ImGui_ImplSDLRenderer3_DestroyDeviceObjects(), ImGui_ImplVulkan_DestroyDeviceObjects(), ImGui_ImplWGPU_InvalidateDeviceObjects(), InitViewportDrawData(), and ImGui::UpdateTexturesEndFrame().
The documentation for this struct was generated from the following files:
examples/imgui/imgui.h
examples/imgui/imgui.cpp