SignalProcessing: ImRect Struct Reference
ImRect Struct Reference
#include <imgui_internal.h>
Public Member Functions
constexpr ImRect ()
constexpr ImRect (const ImVec2 &min, const ImVec2 &max)
constexpr ImRect (const ImVec4 &v)
constexpr ImRect (float x1, float y1, float x2, float y2)
ImVec2 GetCenter () const
ImVec2 GetSize () const
float GetWidth () const
float GetHeight () const
float GetArea () const
ImVec2 GetTL () const
ImVec2 GetTR () const
ImVec2 GetBL () const
ImVec2 GetBR () const
bool Contains (const ImVec2 &p) const
bool Contains (const ImRect &r) const
bool ContainsWithPad (const ImVec2 &p, const ImVec2 &pad) const
bool Overlaps (const ImRect &r) const
void Add (const ImVec2 &p)
void Add (const ImRect &r)
void Expand (const float amount)
void Expand (const ImVec2 &amount)
void Translate (const ImVec2 &d)
void TranslateX (float dx)
void TranslateY (float dy)
void ClipWith (const ImRect &r)
void ClipWithFull (const ImRect &r)
void Floor ()
bool IsInverted () const
ImVec4 ToVec4 () const
const ImVec4 & AsVec4 () const
Public Attributes
ImVec2 Min
ImVec2 Max
Detailed Description
Definition at line 572 of file imgui_internal.h.
Constructor & Destructor Documentation
ImRect() [1/4]
constexpr ImRect::ImRect () inline constexpr
Definition at line 577 of file imgui_internal.h.
ImRect() [2/4]
constexpr ImRect::ImRect (const ImVec2 & min, const ImVec2 & max) inline constexpr
Definition at line 578 of file imgui_internal.h.
ImRect() [3/4]
constexpr ImRect::ImRect (const ImVec4 & v) inline constexpr
Definition at line 579 of file imgui_internal.h.
ImRect() [4/4]
constexpr ImRect::ImRect (float x1, float y1, float x2, float y2) inline constexpr
Definition at line 580 of file imgui_internal.h.
Member Function Documentation
Add() [1/2]
void ImRect::Add (const ImRect & r) inline
Definition at line 596 of file imgui_internal.h.
References Max, Min, ImVec2::x, and ImVec2::y.
Add() [2/2]
void ImRect::Add (const ImVec2 & p) inline
Definition at line 595 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::BeginBoxSelect(), ImGui::DebugNodeDrawCmdShowMeshAndBoundingBox(), ImGui::NavUpdateCreateMoveRequest(), and SetupDrawListSharedData().
AsVec4()
const ImVec4 & ImRect::AsVec4 () const inline
Definition at line 607 of file imgui_internal.h.
References ImVec2::x.
Referenced by ImGui::InputTextEx().
ClipWith()
void ImRect::ClipWith (const ImRect & r) inline
Definition at line 602 of file imgui_internal.h.
References ImMax(), ImMin(), Max, and Min.
Referenced by ImGui::Begin(), ImGui::BeginMenuBar(), ImGui::BeginTableEx(), ImGui::EndBoxSelect(), ImGui::InputTextEx(), ImGui::IsMouseHoveringRect(), ImGui::RenderDragDropTargetRectForItem(), ImGui::RenderNavCursor(), ImGui::RenderWindowDecorations(), and ImGui::TableEndRow().
ClipWithFull()
void ImRect::ClipWithFull (const ImRect & r) inline
Definition at line 603 of file imgui_internal.h.
References ImClamp(), Max, and Min.
Referenced by ImGui::Begin(), ImGui::BeginColumns(), ImGui::BeginTableEx(), ImGui::DebugRenderViewportThumbnail(), ImGui::NavScoreItem(), ImGui::NavUpdateCreateMoveRequest(), and ImGui::TableUpdateLayout().
Contains() [1/2]
bool ImRect::Contains (const ImRect & r) const inline
Definition at line 592 of file imgui_internal.h.
References Max, Min, ImVec2::x, and ImVec2::y.
Contains() [2/2]
bool ImRect::Contains (const ImVec2 & p) const inline
Definition at line 591 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
Referenced by ImPlot::BeginSubplots(), ImPlot::DragRect(), ImGui::EndBoxSelect(), ImGui::EndMultiSelect(), ImPlot::EndPlot(), ImPlot::EndSubplots(), ImGui::FindBestWindowPosForPopup(), ImGui::FindBestWindowPosForPopupEx(), ImGui::NavUpdateCreateMoveRequest(), ImGui::PlotEx(), ImGui::RenderDragDropTargetRectForItem(), ImGui::RenderNavCursor(), SameLineOrWrap(), ImGui::SetItemDefaultFocus(), ImPlot::ShowAltLegend(), ImGui::TableMergeDrawChannels(), and ImGui::UpdateMouseMovingWindowEndFrame().
ContainsWithPad()
bool ImRect::ContainsWithPad (const ImVec2 & p, const ImVec2 & pad) const inline
Definition at line 593 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::FindHoveredWindowEx(), and ImGui::IsMouseHoveringRect().
Expand() [1/2]
void ImRect::Expand (const float amount) inline
Definition at line 597 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::AcceptDragDropPayload(), ImPlot::BeginDragDropTargetAxis(), CalcResizePosSizeFromAnyCorner(), ImGui::CloseButton(), ImGui::ColorButton(), ImGui::DebugLocateItemResolveWithLastItem(), ImPlot::DragRect(), ImGui::EndBoxSelect(), ImPlot::EndPlot(), ImGui::GetPopupAllowedExtentRect(), ImGui::ProgressBar(), ImPlot::PushPlotClipRect(), ImGui::RenderDimmedBackgrounds(), ImGui::RenderDragDropTargetRectForItem(), ImGui::RenderNavCursor(), ImGui::ScrollbarEx(), and ImGui::SplitterBehavior().
Expand() [2/2]
void ImRect::Expand (const ImVec2 & amount) inline
Definition at line 598 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
Floor()
void ImRect::Floor () inline
Definition at line 604 of file imgui_internal.h.
References IM_TRUNC, ImVec2::x, and ImVec2::y.
GetArea()
float ImRect::GetArea () const inline
Definition at line 586 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::CloseButton().
GetBL()
ImVec2 ImRect::GetBL () const inline
Definition at line 589 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::BeginComboPopup(), ImGui::BeginMenuEx(), ImGui::ColorEdit4(), ImPlot::EndPlot(), ImGui::InputTextEx(), and ImGui::RenderWindowDecorations().
GetBR()
ImVec2 ImRect::GetBR () const inline
Definition at line 590 of file imgui_internal.h.
Referenced by ImGui::BeginMenuEx(), ImPlot::EndPlot(), and ImGui::RenderWindowDecorations().
GetCenter()
ImVec2 ImRect::GetCenter () const inline
Definition at line 582 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
Referenced by ImPlot::BeginSubplots(), ImGui::CloseButton(), ImPlot::ColormapScale(), ImPlot::EndPlot(), ImPlot::GetLocationPos(), NavBiasScoringRect(), ImGui::NavMoveRequestApplyResult(), ImGui::RadioButton(), and ImPlot::SetupFinish().
GetHeight()
float ImRect::GetHeight () const inline
Definition at line 585 of file imgui_internal.h.
References ImVec2::y.
Referenced by ImGui::AcceptDragDropPayload(), ImGui::Begin(), ImPlot::BeginSubplots(), ImGui::DebugNodeTable(), ImGui::DebugRenderViewportThumbnail(), ImGui::EndTable(), ImGui::GetPopupAllowedExtentRect(), ImPlot::LabelAxisValue(), ImGui::NavCalcPreferredRefPos(), ImGui::NavUpdateCreateMoveRequest(), ImGui::NavUpdateCreateWrappingRequest(), ImGui::NavUpdatePageUpPageDown(), ImPlot::RenderColorBar(), ImGui::RenderDimmedBackgrounds(), ImPlot::RenderGridLinesY(), ImGui::ScrollbarEx(), ImGui::ScrollToRectEx(), ImGui::SeparatorTextEx(), ImPlot::SetupFinish(), ImGui::ShowMetricsWindow(), ImPlot::SubplotSetCell(), and ImGui::TabBarLayout().
GetSize()
ImVec2 ImRect::GetSize () const inline
Definition at line 583 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::Begin(), ImGui::BeginListBox(), ImGui::BeginTableEx(), ImGui::BeginViewportSideBar(), ImGui::CloseButton(), ImGui::DebugRenderViewportThumbnail(), ImGui::EndGroup(), ImPlot::EndPlot(), ImPlot::EndSubplots(), ImGui::EndTable(), ImGui::GetItemRectSize(), ImPlot::GetPlotSize(), ImGui::InputTextEx(), ImGui::ItemSize(), RenderViewportsThumbnails(), ImGui::ScrollbarEx(), ImPlot::SubplotSetCell(), ImGui::TabItemEx(), ImGui::TempInputText(), and ImPlot::UpdateInput().
GetTL()
ImVec2 ImRect::GetTL () const inline
Definition at line 587 of file imgui_internal.h.
Referenced by ImGui::BeginMenuEx(), ImPlot::EndPlot(), and ImGui::TabItemEx().
GetTR()
ImVec2 ImRect::GetTR () const inline
Definition at line 588 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::BeginMenuEx(), ImPlot::EndPlot(), and ImGui::TabItemEx().
GetWidth()
float ImRect::GetWidth () const inline
Definition at line 584 of file imgui_internal.h.
References ImVec2::x.
Referenced by ImGui::AcceptDragDropPayload(), ImGui::Begin(), ImGui::BeginComboPopup(), ImPlot::BeginSubplots(), ImGui::ColorPicker4(), ImGui::DebugNodeTable(), ImGui::GetPopupAllowedExtentRect(), ImPlot::LabelAxisValue(), ImGui::NavCalcPreferredRefPos(), ImGui::NavUpdateCreateMoveRequest(), ImGui::NavUpdateCreateWrappingRequest(), ImPlot::RenderColorBar(), ImGui::RenderDimmedBackgrounds(), ImPlot::RenderGridLinesX(), ImGui::RenderWindowTitleBarContents(), ImGui::ScrollbarEx(), ImGui::ScrollToRectEx(), ImPlot::SetupFinish(), ImGui::ShowMetricsWindow(), ImPlot::SubplotSetCell(), TabBarCalcScrollableWidth(), ImGui::TabBarLayout(), ImGui::TabBarScrollClamp(), ImGui::TabItemBackground(), ImGui::TabItemEx(), ImGui::TabItemLabelAndCloseButton(), and ImGui::TableUpdateLayout().
IsInverted()
bool ImRect::IsInverted () const inline
Definition at line 605 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::NavUpdateCreateMoveRequest(), and ImGui::NavUpdatePageUpPageDown().
Overlaps()
bool ImRect::Overlaps (const ImRect & r) const inline
Definition at line 594 of file imgui_internal.h.
References Max, Min, ImVec2::x, and ImVec2::y.
Referenced by ImGui::Begin(), ImGui::BeginComboPreview(), ImGui::Checkbox(), ImGui::InputTextEx(), ImGui::IsClippedEx(), ImGui::IsRectVisible(), ImGui::IsRectVisible(), ImGui::ItemAdd(), ImGui::NavProcessItem(), ImGui::NavScoreItem(), ImPlot::RendererLineStrip< _Getter >::Render(), ImPlot::RendererLineStripSkip< _Getter >::Render(), ImPlot::RendererLineSegments1< _Getter >::Render(), ImPlot::RendererLineSegments2< _Getter1, _Getter2 >::Render(), ImPlot::RendererBarsFillV< _Getter1, _Getter2 >::Render(), ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::Render(), ImPlot::RendererBarsLineV< _Getter1, _Getter2 >::Render(), ImPlot::RendererBarsLineH< _Getter1, _Getter2 >::Render(), ImPlot::RendererStairsPre< _Getter >::Render(), ImPlot::RendererStairsPost< _Getter >::Render(), ImPlot::RendererStairsPreShaded< _Getter >::Render(), ImPlot::RendererStairsPostShaded< _Getter >::Render(), ImPlot::RendererShaded< _Getter1, _Getter2 >::Render(), ImPlot::RendererRectC< _Getter >::Render(), ImGui::Selectable(), and ImGui::TableDrawBorders().
ToVec4()
ImVec4 ImRect::ToVec4 () const inline
Definition at line 606 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
Referenced by SetupDrawListSharedData(), ImGui::SetWindowClipRectBeforeSetChannel(), ImGui::TableEndRow(), and ImGui::TableMergeDrawChannels().
Translate()
void ImRect::Translate (const ImVec2 & d) inline
Definition at line 599 of file imgui_internal.h.
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::NavCalcPreferredRefPos(), and ImGui::NavUpdateCreateMoveRequest().
TranslateX()
void ImRect::TranslateX (float dx) inline
Definition at line 600 of file imgui_internal.h.
References ImVec2::x.
Referenced by ImGui::NavUpdateCreateWrappingRequest(), and ImPlot::RenderColorBar().
TranslateY()
void ImRect::TranslateY (float dy) inline
Definition at line 601 of file imgui_internal.h.
References ImVec2::y.
Referenced by ImGui::NavUpdateCreateMoveRequest(), ImGui::NavUpdateCreateWrappingRequest(), and ImPlot::RenderColorBar().
Member Data Documentation
Max
ImVec2 ImRect::Max
Definition at line 575 of file imgui_internal.h.
Referenced by Add(), ImGui::ArrowButtonEx(), ImGui::Begin(), ImGui::BeginBoxSelect(), ImGui::BeginColumns(), ImGui::BeginCombo(), ImGui::BeginComboPreview(), ImGui::BeginDragDropTargetCustom(), ImGui::BeginDragDropTargetViewport(), ImGui::BeginListBox(), ImGui::BeginMenuBar(), ImPlot::BeginSubplots(), ImGui::BeginTabBar(), ImGui::BeginTabBarEx(), ImGui::BeginTableEx(), ImGui::BeginViewportSideBar(), BoxSelectScrollWithMouseDrag(), ImGui::ButtonEx(), ImGui::CalcClipRectVisibleItemsY(), CalcResizePosSizeFromAnyCorner(), CalcScopeRect(), CalcWindowSizeAfterConstraint(), ImGui::CalcWrapWidthForPos(), ImGui::Checkbox(), ImPlot::ClampLegendRect(), ClampWindowPos(), ClipWith(), ClipWithFull(), ImGui::CloseButton(), ImGui::CollapseButton(), ImGui::CollapsingHeader(), ImGui::ColorButton(), ImPlot::ColormapScale(), ImGui::ColorPicker4(), Contains(), ImGui::DebugBreakButton(), ImGui::DebugDrawItemRect(), ImGui::DebugLocateItemOnHover(), ImGui::DebugLocateItemResolveWithLastItem(), ImGui::DebugNodeDrawCmdShowMeshAndBoundingBox(), ImGui::DebugNodeTabBar(), ImGui::DebugNodeTable(), ImGui::DebugNodeTexture(), ImGui::DebugNodeWindow(), ImGui::DebugRenderViewportThumbnail(), ImGui::DebugTextUnformattedWithLocateItem(), ImPlot::DragLineX(), ImPlot::DragLineY(), ImPlot::DragRect(), ImGui::DragScalar(), ImGui::EndBoxSelect(), ImGui::EndChild(), ImGui::EndColumns(), ImGui::EndComboPreview(), ImGui::EndGroup(), ImPlot::EndPlot(), ImPlot::EndSubplots(), ImGui::EndTabBar(), ImGui::EndTable(), ImGui::FindBestWindowPosForPopup(), ImGui::FindBestWindowPosForPopupEx(), ImGui::GetContentRegionAvail(), ImGui::GetItemRectMax(), ImPlot::GetLocationPos(), ImPlot::GetPlotSelection(), GetResizeBorderRect(), ImGui::GetWindowContentRegionMax(), ImGui::GetWindowScrollbarRect(), ImGui::ImageButtonEx(), ImGui::ImageWithBg(), ImGuiListClipper_StepInternal(), ImGui::InputTextEx(), ImGui::ItemAdd(), ImGui::ItemHoverable(), ImGui::LabelTextV(), NavBiasScoringRect(), ImGui::NavCalcPreferredRefPos(), ImGui::NavProcessItem(), ImGui::NavScoreItem(), ImGui::NavUpdate(), ImGui::NavUpdateCreateMoveRequest(), ImGui::NavUpdateCreateWrappingRequest(), ImGui::NavUpdatePageUpPageDown(), ImGui::NextColumn(), Overlaps(), ImPlot::PadAndDatumAxesX(), ImPlot::PadAndDatumAxesY(), ImGui::PlotEx(), ImGui::ProgressBar(), ImGui::PushColumnClipRect(), ImPlot::PushPlotClipRect(), ImGui::RadioButton(), ImPlot::RendererMarkersFill< _Getter >::Render(), ImPlot::RendererMarkersLine< _Getter >::Render(), ImPlot::RenderColorBar(), ImGui::RenderColorComponentMarker(), ImGui::RenderDimmedBackgroundBehindWindow(), ImGui::RenderDimmedBackgrounds(), ImGui::RenderDragDropTargetRectEx(), ImPlot::RenderGridLinesX(), ImPlot::RenderGridLinesY(), ImGui::RenderNavCursor(), ImGui::RenderRectFilledInRangeH(), ImGui::RenderRectFilledWithHole(), ImGui::RenderTextClippedEx(), ImGui::RenderWindowDecorations(), RenderWindowOuterSingleBorder(), ImGui::RenderWindowTitleBarContents(), ImGui::Scrollbar(), ImGui::ScrollbarEx(), ImGui::ScrollToRectEx(), ImGui::Selectable(), ImGui::SeparatorEx(), ImGui::SeparatorTextEx(), ImGui::SetScrollHereX(), ImPlot::SetupFinish(), ImPlot::ShowAltLegend(), ImPlot::ShowLegendEntries(), ImGui::ShowMetricsWindow(), ImPlot::ShowMetricsWindow(), ImGui::SliderScalar(), ImGui::TabBarLayout(), ImGui::TabBarScrollingButtons(), ImGui::TabItemBackground(), ImGui::TabItemEx(), ImGui::TabItemLabelAndCloseButton(), ImGui::TableAngledHeadersRowEx(), ImGui::TableBeginCell(), ImGui::TableCalcMaxColumnWidth(), ImGui::TableDrawBorders(), ImGui::TableEndRow(), ImGui::TableGetCellBgRect(), ImGui::TableHeader(), ImGui::TableMergeDrawChannels(), ImGui::TableSetBgColor(), ImGui::TableSetupDrawChannels(), ImGui::TableUpdateBorders(), ImGui::TableUpdateLayout(), ImGui::TextAlignedV(), ImGui::TextEx(), ImGui::TextLink(), ImGui::TreeNodeBehavior(), ImGui::TreeNodeDrawLineToTreePop(), ImPlot::UpdateInput(), ImGui::UpdateWindowManualResize(), ImGui::VSliderScalar(), ImGui::WindowRectAbsToRel(), and ImGui::WindowRectRelToAbs().
Min
ImVec2 ImRect::Min
Definition at line 574 of file imgui_internal.h.
Referenced by Add(), ImGui::ArrowButtonEx(), ImGui::Begin(), ImGui::BeginBoxSelect(), ImGui::BeginCombo(), ImGui::BeginComboPopup(), ImGui::BeginComboPreview(), ImGui::BeginDragDropTargetCustom(), ImGui::BeginDragDropTargetViewport(), ImGui::BeginListBox(), ImGui::BeginMenuBar(), ImPlot::BeginSubplots(), ImGui::BeginTabBar(), ImGui::BeginTabBarEx(), ImGui::BeginTableEx(), ImGui::BeginViewportSideBar(), BoxSelectScrollWithMouseDrag(), ImGui::Bullet(), ImGui::BulletTextV(), ImGui::ButtonBehavior(), ImGui::ButtonEx(), ImGui::CalcClipRectVisibleItemsY(), CalcResizePosSizeFromAnyCorner(), CalcScopeRect(), CalcWindowSizeAfterConstraint(), ImGui::Checkbox(), ImPlot::ClampLegendRect(), ClampWindowPos(), ClipWith(), ClipWithFull(), ImGui::CloseButton(), ImGui::CollapseButton(), ImGui::CollapsingHeader(), ImGui::ColorButton(), ImPlot::ColormapScale(), ImGui::ColorPicker4(), Contains(), ImGui::DebugBreakButton(), ImGui::DebugDrawItemRect(), ImGui::DebugLocateItemOnHover(), ImGui::DebugLocateItemResolveWithLastItem(), ImGui::DebugNodeDrawCmdShowMeshAndBoundingBox(), ImGui::DebugNodeTabBar(), ImGui::DebugNodeTable(), ImGui::DebugNodeTexture(), ImGui::DebugNodeWindow(), ImGui::DebugRenderViewportThumbnail(), ImGui::DebugTextUnformattedWithLocateItem(), ImPlot::DragLineX(), ImPlot::DragLineY(), ImPlot::DragRect(), ImGui::DragScalar(), ImGui::EndBoxSelect(), ImGui::EndChild(), ImGui::EndColumns(), ImGui::EndGroup(), ImPlot::EndPlot(), ImPlot::EndSubplots(), ImGui::EndTable(), ImGui::FindBestWindowPosForPopup(), ImGui::FindBestWindowPosForPopupEx(), ImGui::GetItemRectMin(), ImPlot::GetLocationPos(), ImPlot::GetPlotPos(), ImPlot::GetPlotSelection(), GetResizeBorderRect(), ImGui::GetWindowContentRegionMin(), ImGui::GetWindowScrollbarRect(), ImGui::ImageButtonEx(), ImGui::ImageWithBg(), ImGuiListClipper_StepInternal(), ImGui::InputTextEx(), ImGui::IsItemHovered(), ImGui::ItemAdd(), ImGui::ItemHoverable(), ImGui::LabelTextV(), NavBiasScoringRect(), ImGui::NavCalcPreferredRefPos(), ImGui::NavProcessItem(), ImGui::NavScoreItem(), ImGui::NavUpdate(), ImGui::NavUpdateCreateMoveRequest(), ImGui::NavUpdateCreateWrappingRequest(), ImGui::NavUpdatePageUpPageDown(), Overlaps(), ImPlot::PadAndDatumAxesX(), ImPlot::PadAndDatumAxesY(), ImGui::PlotEx(), ImGui::ProgressBar(), ImGui::PushColumnClipRect(), ImPlot::PushPlotClipRect(), ImGui::RadioButton(), ImPlot::RendererMarkersFill< _Getter >::Render(), ImPlot::RendererMarkersLine< _Getter >::Render(), ImPlot::RenderColorBar(), ImGui::RenderColorComponentMarker(), ImGui::RenderDimmedBackgroundBehindWindow(), ImGui::RenderDimmedBackgrounds(), ImGui::RenderDragDropTargetRectEx(), ImPlot::RenderGridLinesX(), ImPlot::RenderGridLinesY(), ImGui::RenderNavCursor(), ImGui::RenderRectFilledInRangeH(), ImGui::RenderRectFilledWithHole(), ImGui::RenderTextClippedEx(), RenderViewportsThumbnails(), ImGui::RenderWindowDecorations(), RenderWindowOuterSingleBorder(), ImGui::RenderWindowTitleBarContents(), ImGui::Scrollbar(), ImGui::ScrollbarEx(), ImGui::ScrollToRectEx(), ImGui::Selectable(), ImGui::SeparatorEx(), ImGui::SeparatorTextEx(), ImGui::SetScrollHereX(), ImPlot::SetupFinish(), ImPlot::ShowAltLegend(), ImPlot::ShowLegendEntries(), ImGui::ShowMetricsWindow(), ImPlot::ShowMetricsWindow(), ImGui::SliderScalar(), ImGui::SplitterBehavior(), ImPlot::SubplotSetCell(), ImGui::TabBarLayout(), ImGui::TabBarQueueReorderFromMousePos(), ImGui::TabBarScrollingButtons(), ImGui::TabBarTabListPopupButton(), ImGui::TabItemBackground(), ImGui::TabItemEx(), ImGui::TabItemLabelAndCloseButton(), ImGui::TableAngledHeadersRowEx(), ImGui::TableBeginCell(), ImGui::TableBeginRow(), ImGui::TableDrawBorders(), ImGui::TableEndRow(), ImGui::TableGetCellBgRect(), ImGui::TableHeader(), ImGui::TableMergeDrawChannels(), ImGui::TableSetupDrawChannels(), ImGui::TableUpdateBorders(), ImGui::TableUpdateLayout(), ImGui::TempInputText(), ImGui::TextEx(), ImGui::TextLink(), ImGui::TreeNodeBehavior(), ImGui::TreeNodeDrawLineToTreePop(), ImGui::TreePop(), ImPlot::UpdateInput(), ImGui::UpdateWindowManualResize(), ImGui::VSliderScalar(), ImGui::WindowRectAbsToRel(), and ImGui::WindowRectRelToAbs().
The documentation for this struct was generated from the following file:
examples/imgui/imgui_internal.h