SignalProcessing: ExampleAppDocuments Struct Reference
ExampleAppDocuments Struct Reference
Public Member Functions
ExampleAppDocuments ()
void GetTabName (MyDocument *doc, char *out_buf, size_t out_buf_size)
void DisplayDocContents (MyDocument *doc)
void DisplayDocContextMenu (MyDocument *doc)
void NotifyOfDocumentsClosedElsewhere ()
Public Attributes
ImVector< MyDocument > Documents
ImVector< MyDocument * > CloseQueue
MyDocument * RenamingDoc = NULL
bool RenamingStarted = false
Detailed Description
Definition at line 10206 of file imgui_demo.cpp.
Constructor & Destructor Documentation
ExampleAppDocuments()
ExampleAppDocuments::ExampleAppDocuments () inline
Definition at line 10213 of file imgui_demo.cpp.
References Documents, and ImVector< T >::push_back().
Member Function Documentation
DisplayDocContents()
void ExampleAppDocuments::DisplayDocContents (MyDocument * doc) inline
Definition at line 10230 of file imgui_demo.cpp.
References ImGui::Button(), CloseQueue, MyDocument::Color, ImGui::ColorEdit3(), MyDocument::Dirty, MyDocument::DoSave(), ImGuiCol_Text, ImGuiInputFlags_Tooltip, ImGuiKey_M, ImGuiKey_R, ImGuiKey_S, ImGuiKey_W, ImGuiMod_Ctrl, MyDocument::Name, ImGui::PopID(), ImGui::PopStyleColor(), ImVector< T >::push_back(), ImGui::PushID(), ImGui::PushStyleColor(), RenamingDoc, RenamingStarted, ImGui::SameLine(), ImGui::SetNextItemShortcut(), ImGui::Text(), ImGui::TextWrapped(), and ImVec4::x.
Referenced by ShowExampleAppDocuments().
DisplayDocContextMenu()
void ExampleAppDocuments::DisplayDocContextMenu (MyDocument * doc) inline
Definition at line 10264 of file imgui_demo.cpp.
References ImGui::BeginPopupContextItem(), CloseQueue, MyDocument::DoSave(), ImGui::EndPopup(), ImGui::MenuItem(), MyDocument::Name, MyDocument::Open, ImVector< T >::push_back(), and RenamingDoc.
Referenced by ShowExampleAppDocuments().
GetTabName()
void ExampleAppDocuments::GetTabName (MyDocument * doc, char * out_buf, size_t out_buf_size) inline
Definition at line 10224 of file imgui_demo.cpp.
References MyDocument::Name, and MyDocument::UID.
Referenced by ShowExampleAppDocuments().
NotifyOfDocumentsClosedElsewhere()
void ExampleAppDocuments::NotifyOfDocumentsClosedElsewhere () inline
Definition at line 10288 of file imgui_demo.cpp.
References Documents, and ImGui::SetTabItemClosed().
Referenced by ShowExampleAppDocuments().
Member Data Documentation
CloseQueue
ImVector<MyDocument*> ExampleAppDocuments::CloseQueue
Definition at line 10209 of file imgui_demo.cpp.
Referenced by DisplayDocContents(), DisplayDocContextMenu(), and ShowExampleAppDocuments().
Documents
ImVector<MyDocument> ExampleAppDocuments::Documents
Definition at line 10208 of file imgui_demo.cpp.
Referenced by ExampleAppDocuments(), NotifyOfDocumentsClosedElsewhere(), and ShowExampleAppDocuments().
RenamingDoc
MyDocument* ExampleAppDocuments::RenamingDoc = NULL
Definition at line 10210 of file imgui_demo.cpp.
Referenced by DisplayDocContents(), DisplayDocContextMenu(), and ShowExampleAppDocuments().
RenamingStarted
bool ExampleAppDocuments::RenamingStarted = false
Definition at line 10211 of file imgui_demo.cpp.
Referenced by DisplayDocContents(), and ShowExampleAppDocuments().
The documentation for this struct was generated from the following file:
examples/imgui/imgui_demo.cpp