SignalProcessing: ImPlot::HugeTimeData Struct Reference
ImPlot::HugeTimeData Struct Reference
Public Member Functions
HugeTimeData (double min)
~HugeTimeData ()
Static Public Member Functions
static double GetY (double t)
Public Attributes
double * Ts
double * Ys
Static Public Attributes
static const int Size = 60*60*24*366
Detailed Description
Definition at line 168 of file implot_demo.cpp.
Constructor & Destructor Documentation
HugeTimeData()
ImPlot::HugeTimeData::HugeTimeData (double min) inline
Definition at line 169 of file implot_demo.cpp.
References GetY(), Size, Ts, and Ys.
~HugeTimeData()
ImPlot::HugeTimeData::~HugeTimeData () inline
Definition at line 177 of file implot_demo.cpp.
References Ts, and Ys.
Member Function Documentation
GetY()
static double ImPlot::HugeTimeData::GetY (double t) inline static
Definition at line 178 of file implot_demo.cpp.
Referenced by ImPlot::Demo_TimeScale(), and HugeTimeData().
Member Data Documentation
Size
const int ImPlot::HugeTimeData::Size = 60*60*24*366 static
Definition at line 183 of file implot_demo.cpp.
Referenced by ImPlot::Demo_TimeScale(), and HugeTimeData().
Ts
double* ImPlot::HugeTimeData::Ts
Definition at line 181 of file implot_demo.cpp.
Referenced by HugeTimeData(), and ~HugeTimeData().
Ys
double* ImPlot::HugeTimeData::Ys
Definition at line 182 of file implot_demo.cpp.
Referenced by HugeTimeData(), and ~HugeTimeData().
The documentation for this struct was generated from the following file:
examples/implot/implot_demo.cpp