SignalProcessing: ImPlot::RendererLineStripSkip< _Getter > Struct Template Reference
ImPlot::RendererLineStripSkip< _Getter > Struct Template Reference
Public Member Functions
RendererLineStripSkip (const _Getter &getter, ImU32 col, float weight)
void Init (ImDrawList &draw_list) const
bool Render (ImDrawList &draw_list, const ImRect &cull_rect, int prim) const
Public Member Functions inherited from ImPlot::RendererBase
RendererBase (int prims, int idx_consumed, int vtx_consumed)
Public Attributes
const _Getter & Getter
const ImU32 Col
float HalfWeight
ImVec2 P1
ImVec2 UV0
ImVec2 UV1
Public Attributes inherited from ImPlot::RendererBase
const int Prims
Transformer2 Transformer
const int IdxConsumed
const int VtxConsumed
Detailed Description
template<class _Getter>
struct ImPlot::RendererLineStripSkip< _Getter >
Definition at line 899 of file implot_items.cpp.
Constructor & Destructor Documentation
RendererLineStripSkip()
template<class _Getter > ImPlot::RendererLineStripSkip< _Getter >::RendererLineStripSkip (const _Getter & getter, ImU32 col, float weight) inline
Definition at line 900 of file implot_items.cpp.
References ImPlot::RendererLineStripSkip< _Getter >::Getter, ImPlot::RendererLineStripSkip< _Getter >::P1, and ImPlot::RendererBase::Transformer.
Member Function Documentation
Init()
template<class _Getter > void ImPlot::RendererLineStripSkip< _Getter >::Init (ImDrawList & draw_list) const inline
Definition at line 908 of file implot_items.cpp.
References ImPlot::draw_list, ImPlot::GetLineRenderProps(), ImPlot::RendererLineStripSkip< _Getter >::HalfWeight, ImPlot::RendererLineStripSkip< _Getter >::UV0, and ImPlot::RendererLineStripSkip< _Getter >::UV1.
Render()
template<class _Getter > bool ImPlot::RendererLineStripSkip< _Getter >::Render (ImDrawList & draw_list, const ImRect & cull_rect, int prim) const inline
Definition at line 911 of file implot_items.cpp.
References ImPlot::RendererLineStripSkip< _Getter >::Col, ImPlot::draw_list, ImPlot::RendererLineStripSkip< _Getter >::Getter, ImPlot::RendererLineStripSkip< _Getter >::HalfWeight, ImMax(), ImMin(), ImNan(), ImRect::Overlaps(), ImPlot::RendererLineStripSkip< _Getter >::P1, ImPlot::PrimLine(), ImPlot::RendererBase::Transformer, ImPlot::RendererLineStripSkip< _Getter >::UV0, ImPlot::RendererLineStripSkip< _Getter >::UV1, ImVec2::x, and ImVec2::y.
Member Data Documentation
Col
template<class _Getter > const ImU32 ImPlot::RendererLineStripSkip< _Getter >::Col
Definition at line 924 of file implot_items.cpp.
Referenced by ImPlot::RendererLineStripSkip< _Getter >::Render().
Getter
template<class _Getter > const _Getter& ImPlot::RendererLineStripSkip< _Getter >::Getter
Definition at line 923 of file implot_items.cpp.
Referenced by ImPlot::RendererLineStripSkip< _Getter >::Render(), and ImPlot::RendererLineStripSkip< _Getter >::RendererLineStripSkip().
HalfWeight
template<class _Getter > float ImPlot::RendererLineStripSkip< _Getter >::HalfWeight mutable
Definition at line 925 of file implot_items.cpp.
Referenced by ImPlot::RendererLineStripSkip< _Getter >::Init(), and ImPlot::RendererLineStripSkip< _Getter >::Render().
P1
template<class _Getter > ImVec2 ImPlot::RendererLineStripSkip< _Getter >::P1 mutable
Definition at line 926 of file implot_items.cpp.
Referenced by ImPlot::RendererLineStripSkip< _Getter >::Render(), and ImPlot::RendererLineStripSkip< _Getter >::RendererLineStripSkip().
UV0
template<class _Getter > ImVec2 ImPlot::RendererLineStripSkip< _Getter >::UV0 mutable
Definition at line 927 of file implot_items.cpp.
Referenced by ImPlot::RendererLineStripSkip< _Getter >::Init(), and ImPlot::RendererLineStripSkip< _Getter >::Render().
UV1
template<class _Getter > ImVec2 ImPlot::RendererLineStripSkip< _Getter >::UV1 mutable
Definition at line 928 of file implot_items.cpp.
Referenced by ImPlot::RendererLineStripSkip< _Getter >::Init(), and ImPlot::RendererLineStripSkip< _Getter >::Render().
The documentation for this struct was generated from the following file:
examples/implot/implot_items.cpp