SignalProcessing: ExampleAppPropertyEditor Struct Reference
ExampleAppPropertyEditor Struct Reference
Public Member Functions
void Draw (ExampleTreeNode *root_node)
void DrawTreeNode (ExampleTreeNode *node)
Public Attributes
ImGuiTextFilter Filter
ExampleTreeNode * VisibleNode = NULL
Detailed Description
Definition at line 9405 of file imgui_demo.cpp.
Member Function Documentation
Draw()
void ExampleAppPropertyEditor::Draw (ExampleTreeNode * root_node) inline
Definition at line 9410 of file imgui_demo.cpp.
References ImGui::AlignTextToFramePadding(), ImGui::BeginChild(), ImGui::BeginGroup(), ImGui::BeginTable(), ImGuiTextFilter::Build(), ImGui::Checkbox(), ExampleTreeNode::Childs, ImGui::DragScalarN(), DrawTreeNode(), ImGui::EndChild(), ImGui::EndGroup(), ImGui::EndTable(), ExampleTreeNodeMemberInfos, Filter, IM_ARRAYSIZE, IM_ASSERT, ImGuiChildFlags_Borders, ImGuiChildFlags_NavFlattened, ImGuiChildFlags_ResizeX, ImGuiDataType_Bool, ImGuiDataType_Float, ImGuiDataType_S32, ImGuiDataType_String, ImGuiInputFlags_Tooltip, ImGuiInputTextFlags_EscapeClearsAll, ImGuiItemFlags_NoNavDefaultFocus, ImGuiKey_F, ImGuiMod_Ctrl, ImGuiTableColumnFlags_WidthFixed, ImGuiTableColumnFlags_WidthStretch, ImGuiTableFlags_Resizable, ImGuiTableFlags_RowBg, ImGuiTableFlags_ScrollY, ImGuiTextFilter::InputBuf, ImGui::InputText(), ImGui::InputTextWithHint(), ImGuiTextFilter::PassFilter(), ImGui::PopID(), ImGui::PopItemFlag(), ImGui::PushID(), ImGui::PushItemFlag(), ImGui::SameLine(), ImGui::Separator(), ImGui::SetNextItemShortcut(), ImGui::SetNextItemWidth(), ImGui::SliderScalarN(), ImGui::TableNextColumn(), ImGui::TableNextRow(), ImGui::TableSetupColumn(), ImGui::Text(), ImGui::TextDisabled(), ImGui::TextUnformatted(), and VisibleNode.
Referenced by ShowExampleAppPropertyEditor().
DrawTreeNode()
void ExampleAppPropertyEditor::DrawTreeNode (ExampleTreeNode * node) inline
Definition at line 9500 of file imgui_demo.cpp.
References ExampleTreeNode::Childs, ExampleTreeNode::DataMyBool, DrawTreeNode(), ImGui::GetStyle(), ImGuiCol_Text, ImGuiCol_TextDisabled, ImGuiTreeNodeFlags_Bullet, ImGuiTreeNodeFlags_DrawLinesToNodes, ImGuiTreeNodeFlags_Leaf, ImGuiTreeNodeFlags_NavLeftJumpsToParent, ImGuiTreeNodeFlags_None, ImGuiTreeNodeFlags_OpenOnArrow, ImGuiTreeNodeFlags_OpenOnDoubleClick, ImGuiTreeNodeFlags_Selected, ImGuiTreeNodeFlags_SpanFullWidth, ImGui::IsItemFocused(), ExampleTreeNode::Name, ImGui::PopID(), ImGui::PopStyleColor(), ImGui::PushID(), ImGui::PushStyleColor(), ImVector< T >::Size, ImGui::TableNextColumn(), ImGui::TableNextRow(), ImGui::TreeNodeEx(), ImGui::TreePop(), ExampleTreeNode::UID, and VisibleNode.
Referenced by Draw(), and DrawTreeNode().
Member Data Documentation
Filter
ImGuiTextFilter ExampleAppPropertyEditor::Filter
Definition at line 9407 of file imgui_demo.cpp.
Referenced by Draw().
VisibleNode
ExampleTreeNode* ExampleAppPropertyEditor::VisibleNode = NULL
Definition at line 9408 of file imgui_demo.cpp.
Referenced by Draw(), and DrawTreeNode().
The documentation for this struct was generated from the following file:
examples/imgui/imgui_demo.cpp