SignalProcessing: ImPlot::RollingBuffer Struct Reference
ImPlot::RollingBuffer Struct Reference
Public Member Functions
RollingBuffer ()
void AddPoint (float x, float y)
Public Attributes
float Span
ImVector< ImVec2 > Data
Detailed Description
Definition at line 152 of file implot_demo.cpp.
Constructor & Destructor Documentation
RollingBuffer()
ImPlot::RollingBuffer::RollingBuffer () inline
Definition at line 155 of file implot_demo.cpp.
References Data, ImVector< T >::reserve(), and Span.
Member Function Documentation
AddPoint()
void ImPlot::RollingBuffer::AddPoint (float x, float y) inline
Definition at line 159 of file implot_demo.cpp.
References ImVector< T >::back(), Data, ImVector< T >::empty(), ImVector< T >::push_back(), ImVector< T >::shrink(), Span, ImVec2::x, ImPlot::x, and ImPlot::y.
Referenced by ImPlot::Demo_RealtimePlots().
Member Data Documentation
Data
ImVector<ImVec2> ImPlot::RollingBuffer::Data
Definition at line 154 of file implot_demo.cpp.
Referenced by AddPoint(), ImPlot::Demo_RealtimePlots(), and RollingBuffer().
Span
float ImPlot::RollingBuffer::Span
Definition at line 153 of file implot_demo.cpp.
Referenced by AddPoint(), ImPlot::Demo_RealtimePlots(), and RollingBuffer().
The documentation for this struct was generated from the following file:
examples/implot/implot_demo.cpp