SignalProcessing: ImGuiViewportP Struct Reference
ImGuiViewportP Struct Reference
#include <imgui_internal.h>
Public Member Functions
ImGuiViewportP ()
~ImGuiViewportP ()
ImVec2 CalcWorkRectPos (const ImVec2 &inset_min) const
ImVec2 CalcWorkRectSize (const ImVec2 &inset_min, const ImVec2 &inset_max) const
void UpdateWorkRect ()
ImRect GetMainRect () const
ImRect GetWorkRect () const
ImRect GetBuildWorkRect () const
Public Member Functions inherited from ImGuiViewport
ImGuiViewport ()
ImVec2 GetCenter () const
ImVec2 GetWorkCenter () const
Public Attributes
int BgFgDrawListsLastFrame [2]
ImDrawList * BgFgDrawLists [2]
ImDrawData DrawDataP
ImDrawDataBuilder DrawDataBuilder
ImVec2 WorkInsetMin
ImVec2 WorkInsetMax
ImVec2 BuildWorkInsetMin
ImVec2 BuildWorkInsetMax
Public Attributes inherited from ImGuiViewport
ImGuiID ID
ImGuiViewportFlags Flags
ImVec2 Pos
ImVec2 Size
ImVec2 FramebufferScale
ImVec2 WorkPos
ImVec2 WorkSize
void * PlatformHandle
void * PlatformHandleRaw
Detailed Description
Definition at line 1951 of file imgui_internal.h.
Constructor & Destructor Documentation
ImGuiViewportP()
ImGuiViewportP::ImGuiViewportP () inline
Definition at line 1967 of file imgui_internal.h.
References BgFgDrawLists, and BgFgDrawListsLastFrame.
~ImGuiViewportP()
ImGuiViewportP::~ImGuiViewportP () inline
Definition at line 1968 of file imgui_internal.h.
References BgFgDrawLists, and IM_DELETE().
Member Function Documentation
CalcWorkRectPos()
ImVec2 ImGuiViewportP::CalcWorkRectPos (const ImVec2 & inset_min) const inline
Definition at line 1971 of file imgui_internal.h.
References ImGuiViewport::Pos, ImVec2::x, and ImVec2::y.
Referenced by GetBuildWorkRect(), and UpdateWorkRect().
CalcWorkRectSize()
ImVec2 ImGuiViewportP::CalcWorkRectSize (const ImVec2 & inset_min, const ImVec2 & inset_max) const inline
Definition at line 1972 of file imgui_internal.h.
References ImMax(), ImGuiViewport::Size, ImVec2::x, and ImVec2::y.
Referenced by GetBuildWorkRect(), and UpdateWorkRect().
GetBuildWorkRect()
ImRect ImGuiViewportP::GetBuildWorkRect () const inline
Definition at line 1978 of file imgui_internal.h.
References BuildWorkInsetMax, BuildWorkInsetMin, CalcWorkRectPos(), CalcWorkRectSize(), ImVec2::x, and ImVec2::y.
Referenced by ImGui::BeginViewportSideBar().
GetMainRect()
ImRect ImGuiViewportP::GetMainRect () const inline
Definition at line 1976 of file imgui_internal.h.
References ImGuiViewport::Pos, ImGuiViewport::Size, ImVec2::x, and ImVec2::y.
Referenced by ImGui::Begin(), and ImGui::RenderDimmedBackgroundBehindWindow().
GetWorkRect()
ImRect ImGuiViewportP::GetWorkRect () const inline
Definition at line 1977 of file imgui_internal.h.
References ImGuiViewport::WorkPos, ImGuiViewport::WorkSize, ImVec2::x, and ImVec2::y.
Referenced by ImGui::Begin().
UpdateWorkRect()
void ImGuiViewportP::UpdateWorkRect () inline
Definition at line 1973 of file imgui_internal.h.
References CalcWorkRectPos(), CalcWorkRectSize(), WorkInsetMax, WorkInsetMin, ImGuiViewport::WorkPos, and ImGuiViewport::WorkSize.
Member Data Documentation
BgFgDrawLists
ImDrawList* ImGuiViewportP::BgFgDrawLists[2]
Definition at line 1954 of file imgui_internal.h.
Referenced by GetViewportBgFgDrawList(), ImGuiViewportP(), and ~ImGuiViewportP().
BgFgDrawListsLastFrame
int ImGuiViewportP::BgFgDrawListsLastFrame[2]
Definition at line 1953 of file imgui_internal.h.
Referenced by GetViewportBgFgDrawList(), and ImGuiViewportP().
BuildWorkInsetMax
ImVec2 ImGuiViewportP::BuildWorkInsetMax
Definition at line 1965 of file imgui_internal.h.
Referenced by ImGui::BeginViewportSideBar(), and GetBuildWorkRect().
BuildWorkInsetMin
ImVec2 ImGuiViewportP::BuildWorkInsetMin
Definition at line 1964 of file imgui_internal.h.
Referenced by ImGui::BeginViewportSideBar(), and GetBuildWorkRect().
DrawDataBuilder
ImDrawDataBuilder ImGuiViewportP::DrawDataBuilder
Definition at line 1956 of file imgui_internal.h.
Referenced by AddWindowToDrawData(), and InitViewportDrawData().
DrawDataP
ImDrawData ImGuiViewportP::DrawDataP
Definition at line 1955 of file imgui_internal.h.
Referenced by AddWindowToDrawData(), ImGui::DebugNodeViewport(), ImGui::GetDrawData(), and InitViewportDrawData().
WorkInsetMax
ImVec2 ImGuiViewportP::WorkInsetMax
Definition at line 1963 of file imgui_internal.h.
Referenced by ImGui::DebugNodeViewport(), and UpdateWorkRect().
WorkInsetMin
ImVec2 ImGuiViewportP::WorkInsetMin
Definition at line 1962 of file imgui_internal.h.
Referenced by ImGui::DebugNodeViewport(), and UpdateWorkRect().
The documentation for this struct was generated from the following file:
examples/imgui/imgui_internal.h