SignalProcessing: ImVector< T > Struct Template Reference
ImVector< T > Struct Template Reference
#include <imgui.h>
Public Types
typedef T value_type
typedef value_type * iterator
typedef const value_type * const_iterator
Public Member Functions
ImVector ()
ImVector (const ImVector< T > &src)
ImVector< T > & operator= (const ImVector< T > &src)
~ImVector ()
void clear ()
void clear_delete ()
void clear_destruct ()
bool empty () const
int size () const
int size_in_bytes () const
int max_size () const
int capacity () const
T & operator[] (int i)
const T & operator[] (int i) const
T * begin ()
const T * begin () const
T * end ()
const T * end () const
T & front ()
const T & front () const
T & back ()
const T & back () const
void swap (ImVector< T > &rhs)
int _grow_capacity (int sz) const
void resize (int new_size)
void resize (int new_size, const T &v)
void shrink (int new_size)
void reserve (int new_capacity)
void reserve_discard (int new_capacity)
void push_back (const T &v)
void pop_back ()
void push_front (const T &v)
T * erase (const T *it)
T * erase (const T *it, const T *it_last)
T * erase_unsorted (const T *it)
T * insert (const T *it, const T &v)
bool contains (const T &v) const
T * find (const T &v)
const T * find (const T &v) const
int find_index (const T &v) const
bool find_erase (const T &v)
bool find_erase_unsorted (const T &v)
int index_from_ptr (const T *it) const
Public Attributes
int Size
int Capacity
T * Data
Detailed Description
template<typename T>
struct ImVector< T >
Definition at line 2194 of file imgui.h.
Member Typedef Documentation
const_iterator
template<typename T > typedef const value_type* ImVector< T >::const_iterator
Definition at line 2203 of file imgui.h.
iterator
template<typename T > typedef value_type* ImVector< T >::iterator
Definition at line 2202 of file imgui.h.
value_type
template<typename T > typedef T ImVector< T >::value_type
Definition at line 2201 of file imgui.h.
Constructor & Destructor Documentation
ImVector() [1/2]
template<typename T > ImVector< T >::ImVector () inline
Definition at line 2206 of file imgui.h.
References ImVector< T >::Capacity, ImVector< T >::Data, and ImVector< T >::Size.
ImVector() [2/2]
template<typename T > ImVector< T >::ImVector (const ImVector< T > & src) inline
Definition at line 2207 of file imgui.h.
References ImVector< T >::Capacity, ImVector< T >::Data, ImVector< T >::operator=(), and ImVector< T >::Size.
~ImVector()
template<typename T > ImVector< T >::~ImVector () inline
Definition at line 2209 of file imgui.h.
References ImVector< T >::Data, and IM_FREE.
Member Function Documentation
_grow_capacity()
template<typename T > int ImVector< T >::_grow_capacity (int sz) const inline
Definition at line 2233 of file imgui.h.
References ImVector< T >::Capacity.
Referenced by ImVector< T >::insert(), ImVector< T >::push_back(), ImVector< T >::resize(), and ImVector< T >::resize().
back() [1/2]
template<typename T > T & ImVector< T >::back () inline
Definition at line 2229 of file imgui.h.
References ImVector< T >::Data, IM_ASSERT, and ImVector< T >::Size.
Referenced by ImDrawList::_SetTexture(), ImGui::AddContextHook(), ImFontAtlas::AddFont(), ImPlot::RollingBuffer::AddPoint(), ImPlotTicker::AddTick(), ExampleDescriptorHeapAllocator::Alloc(), ImGui::Begin(), ImGui::BeginDisabledOverrideReenable(), ImGui::BeginDragDropSource(), ImGui::BeginGroup(), ImGui::BeginMultiSelect(), ImGui::BringWindowToDisplayFront(), ImGui::BringWindowToFocusFront(), ImGui::ColorEdit4(), ImGui::ColorPicker4(), ImGui::DebugNodeDrawList(), DemoWindowWidgetsSelectionAndMultiSelect(), ImGui::End(), ImGuiTextBuffer::end(), ImGui::EndDisabled(), ImGui::EndDisabledOverrideReenable(), ImGui::EndGroup(), ImGui::EndMenuBar(), ImGui::EndTabBar(), ImGui::EndTable(), ImGui::ErrorRecoveryTryToRecoverWindowState(), ImGui::FindOrCreateColumns(), ImDrawList::GetClipRectMax(), ImDrawList::GetClipRectMin(), ImGuiWindow::GetID(), ImGuiWindow::GetID(), ImGuiWindow::GetID(), ImGuiWindow::GetIDFromPos(), ImGuiWindow::GetIDFromRectangle(), ImDrawListSplitter::Merge(), ImGui::NavUpdateCancelRequest(), ImGui::NewFrame(), ImGui::OpenPopupEx(), ImDrawList::PathBezierCubicCurveTo(), ImDrawList::PathBezierQuadraticCurveTo(), ImGui::PopClipRect(), ImPlot::PopColormap(), ImGui::PopFocusScope(), ImGui::PopFont(), ImGui::PopItemFlag(), ImGui::PopItemWidth(), ImPlot::PopStyleColor(), ImGui::PopStyleColor(), ImPlot::PopStyleVar(), ImGui::PopStyleVar(), ImGui::PopTextWrapPos(), ImGui::PushClipRect(), ImGui::PushItemFlag(), ImGui::RenderDimmedBackgroundBehindWindow(), SetCurrentWindow(), ShowExampleAppCustomRendering(), ImGui::TabItemEx(), ImGui::TableMergeDrawChannels(), and ImGui::TreePop().
back() [2/2]
template<typename T > const T & ImVector< T >::back () const inline
Definition at line 2230 of file imgui.h.
References ImVector< T >::Data, IM_ASSERT, and ImVector< T >::Size.
begin() [1/2]
template<typename T > T * ImVector< T >::begin () inline
Definition at line 2223 of file imgui.h.
References ImVector< T >::Data.
Referenced by CheckProgram(), CheckShader(), ImGui::DebugNodeDrawList(), DemoWindowWidgetsTextInput(), ExampleAppConsole::ExecCommand(), ImFontAtlasUpdateNewFrame(), InputTextLineIndexGetPosOffset(), and Platform_GetClipboardTextFn_DefaultImpl().
begin() [2/2]
template<typename T > const T * ImVector< T >::begin () const inline
Definition at line 2224 of file imgui.h.
References ImVector< T >::Data.
capacity()
template<typename T > int ImVector< T >::capacity () const inline
Definition at line 2219 of file imgui.h.
References ImVector< T >::Capacity.
Referenced by DemoWindowWidgetsTextInput().
clear()
template<typename T > void ImVector< T >::clear () inline
Definition at line 2211 of file imgui.h.
References ImVector< T >::Capacity, ImVector< T >::Data, IM_FREE, and ImVector< T >::Size.
Referenced by ImDrawList::_ClearFreeMemory(), ImGuiTextBuffer::clear(), ExampleAppLog::Clear(), ImBitVector::Clear(), ImChunkStream< T >::clear(), ImGuiTextIndex::clear(), ImGuiKeyRoutingTable::Clear(), ImVector< T >::clear_delete(), ImVector< T >::clear_destruct(), ImGui::ClearDragDrop(), ImGuiIO::ClearEventsQueue(), ImDrawListSplitter::ClearFreeMemory(), ImGuiInputTextDeactivatedState::ClearFreeMemory(), ImGuiInputTextState::ClearFreeMemory(), ImFontAtlas::ClearInputData(), ExampleAssetsBrowser::ClearItems(), ExampleAppConsole::ClearLog(), ImFontBaked::ClearOutputData(), DemoWindowTables(), ExampleDescriptorHeapAllocator::Destroy(), ImGui::GcCompactTransientMiscBuffers(), ImGui::GcCompactTransientWindowBuffers(), ImGui_ImplVulkan_DestroyWindowRenderBuffers(), ImGui_ImplVulkanH_CreateWindowSwapChain(), ImGui_ImplVulkanH_DestroyWindow(), ExampleDualListBox::MoveAll(), ImVector< T >::operator=(), Platform_SetClipboardTextFn_DefaultImpl(), ShowExampleAppCustomRendering(), ShowExampleAppDocuments(), ImGui::Shutdown(), and ImGui::TableGcCompactTransientBuffers().
clear_delete()
template<typename T > void ImVector< T >::clear_delete () inline
Definition at line 2212 of file imgui.h.
References ImVector< T >::clear(), ImVector< T >::Data, IM_DELETE(), and ImVector< T >::Size.
Referenced by ImStableVector< T, BLOCKSIZE >::clear(), ImFontAtlas::ClearFonts(), ImGui::Shutdown(), and ImFontAtlas::~ImFontAtlas().
clear_destruct()
template<typename T > void ImVector< T >::clear_destruct () inline
Definition at line 2213 of file imgui.h.
References ImVector< T >::clear(), ImVector< T >::Data, and ImVector< T >::Size.
Referenced by ImGui::GcCompactTransientMiscBuffers(), ImGui::Shutdown(), and ImGuiWindow::~ImGuiWindow().
contains()
template<typename T > bool ImVector< T >::contains (const T & v) const inline
Definition at line 2248 of file imgui.h.
References ImVector< T >::Data, and ImVector< T >::Size.
Referenced by ImGui::BeginMenuEx(), DemoWindowTables(), ImFontAtlasAddDrawListSharedData(), ImFontAtlasBuildSetupFontSpecialGlyphs(), ImFontAtlasRemoveDrawListSharedData(), and ImGui::UpdateWindowInFocusOrderList().
empty()
template<typename T > bool ImVector< T >::empty () const inline
Definition at line 2215 of file imgui.h.
References ImVector< T >::Size.
Referenced by ImPlot::RollingBuffer::AddPoint(), ImGui::Begin(), ExampleDescriptorHeapAllocator::Create(), ImDrawData::DeIndexAllBuffers(), DemoWindowWidgetsTextInput(), ImGui::EndTabBar(), FlattenDrawDataIntoSingleLayer(), Platform_GetClipboardTextFn_DefaultImpl(), ImFontAtlas::RemoveFont(), and ShowExampleAppDocuments().
end() [1/2]
template<typename T > T * ImVector< T >::end () inline
Definition at line 2225 of file imgui.h.
References ImVector< T >::Data, and ImVector< T >::Size.
Referenced by ImGui_ImplOpenGL3_UpdateTexture(), and InputTextLineIndexGetPosOffset().
end() [2/2]
template<typename T > const T * ImVector< T >::end () const inline
Definition at line 2226 of file imgui.h.
References ImVector< T >::Data, and ImVector< T >::Size.
erase() [1/2]
template<typename T > T * ImVector< T >::erase (const T * it) inline
Definition at line 2244 of file imgui.h.
References ImVector< T >::Data, IM_ASSERT, and ImVector< T >::Size.
Referenced by DemoWindowWidgetsTabs(), ExampleAppConsole::ExecCommand(), ImVector< T >::find_erase(), ImFontAtlasUpdateNewFrame(), ImGuiListClipper_SortAndFuseRanges(), ImDrawListSplitter::Merge(), ExampleDualListBox::MoveSelected(), ImGui::NewFrame(), ImFontAtlas::RemoveFont(), ImGui::RemoveSettingsHandler(), ImGui::TabBarRemoveTab(), ImGui::UpdateInputEvents(), and ImGui::UpdateWindowInFocusOrderList().
erase() [2/2]
template<typename T > T * ImVector< T >::erase (const T * it, const T * it_last) inline
Definition at line 2245 of file imgui.h.
References ImVector< T >::Data, IM_ASSERT, and ImVector< T >::Size.
erase_unsorted()
template<typename T > T * ImVector< T >::erase_unsorted (const T * it) inline
Definition at line 2246 of file imgui.h.
References ImVector< T >::Data, IM_ASSERT, and ImVector< T >::Size.
Referenced by ImVector< T >::find_erase_unsorted().
find() [1/2]
template<typename T > T * ImVector< T >::find (const T & v) inline
Definition at line 2249 of file imgui.h.
References ImVector< T >::Data, and ImVector< T >::Size.
Referenced by ImVector< T >::find_erase(), ImVector< T >::find_erase_unsorted(), ImVector< T >::find_index(), and ImGui::FindWindowDisplayIndex().
find() [2/2]
template<typename T > const T * ImVector< T >::find (const T & v) const inline
Definition at line 2250 of file imgui.h.
References ImVector< T >::Data, and ImVector< T >::Size.
find_erase()
template<typename T > bool ImVector< T >::find_erase (const T & v) inline
Definition at line 2252 of file imgui.h.
References ImVector< T >::Data, ImVector< T >::erase(), ImVector< T >::find(), and ImVector< T >::Size.
Referenced by ImFontAtlasRemoveDrawListSharedData(), ImFontAtlas::RemoveFont(), ImGui::UnregisterFontAtlas(), and ImGui::UnregisterUserTexture().
find_erase_unsorted()
template<typename T > bool ImVector< T >::find_erase_unsorted (const T & v) inline
Definition at line 2253 of file imgui.h.
References ImVector< T >::Data, ImVector< T >::erase_unsorted(), ImVector< T >::find(), and ImVector< T >::Size.
Referenced by ImDrawList::_SetDrawListSharedData(), and DemoWindowTables().
find_index()
template<typename T > int ImVector< T >::find_index (const T & v) const inline
Definition at line 2251 of file imgui.h.
References ImVector< T >::Data, ImVector< T >::find(), and ImVector< T >::Size.
front() [1/2]
template<typename T > T & ImVector< T >::front () inline
Definition at line 2227 of file imgui.h.
References ImVector< T >::Data, IM_ASSERT, and ImVector< T >::Size.
Referenced by ImGuiTextBuffer::begin().
front() [2/2]
template<typename T > const T & ImVector< T >::front () const inline
Definition at line 2228 of file imgui.h.
References ImVector< T >::Data, IM_ASSERT, and ImVector< T >::Size.
index_from_ptr()
template<typename T > int ImVector< T >::index_from_ptr (const T * it) const inline
Definition at line 2254 of file imgui.h.
References ImVector< T >::Data, IM_ASSERT, and ImVector< T >::Size.
Referenced by ImGui::DebugNodeColumns(), ImGui::FindWindowDisplayIndex(), ImFontAtlasBuildSetupFontBakedFallback(), ImFontAtlasPackReuseRectEntry(), ImFontAtlasTextureRepack(), InputTextLineIndexGetPosOffset(), ImGui::PushPasswordFont(), ImGui::ShowFontAtlas(), ImGui::TabBarGetTabOrder(), ImGui::TabBarQueueReorderFromMousePos(), and ImGui::TabItemEx().
insert()
template<typename T > T * ImVector< T >::insert (const T * it, const T & v) inline
Definition at line 2247 of file imgui.h.
References ImVector< T >::_grow_capacity(), ImVector< T >::Capacity, ImVector< T >::Data, IM_ASSERT, ImVector< T >::reserve(), and ImVector< T >::Size.
Referenced by ImGuiStorage::GetFloatRef(), ImGuiStorage::GetIntRef(), ImGuiStorage::GetVoidPtrRef(), ImVector< T >::push_front(), ImGuiStorage::SetFloat(), ImGuiStorage::SetInt(), and ImGuiStorage::SetVoidPtr().
max_size()
template<typename T > int ImVector< T >::max_size () const inline
Definition at line 2218 of file imgui.h.
operator=()
template<typename T > ImVector< T > & ImVector< T >::operator= (const ImVector< T > & src) inline
Definition at line 2208 of file imgui.h.
References ImVector< T >::clear(), ImVector< T >::Data, ImVector< T >::resize(), and ImVector< T >::Size.
Referenced by ImVector< T >::ImVector().
operator[]() [1/2]
template<typename T > T & ImVector< T >::operator[] (int i) inline
Definition at line 2220 of file imgui.h.
References ImVector< T >::Data, IM_ASSERT, and ImVector< T >::Size.
operator[]() [2/2]
template<typename T > const T & ImVector< T >::operator[] (int i) const inline
Definition at line 2221 of file imgui.h.
References ImVector< T >::Data, IM_ASSERT, and ImVector< T >::Size.
pop_back()
template<typename T > void ImVector< T >::pop_back () inline
Definition at line 2242 of file imgui.h.
References IM_ASSERT, and ImVector< T >::Size.
Referenced by ImDrawList::_OnChangedClipRect(), ImDrawList::_OnChangedTexture(), ImDrawList::_PopUnusedDrawCmd(), ImDrawList::_TryMergeDrawCmds(), ImFontAtlas::AddFont(), ExampleDescriptorHeapAllocator::Alloc(), DemoWindowWidgetsSelectionAndMultiSelect(), ImGui::End(), ImGui::EndDisabled(), ImGui::EndDisabledOverrideReenable(), ImGui::EndGroup(), ImGui::EndTabBar(), ImDrawListSplitter::Merge(), ImDrawList::PopClipRect(), ImPlot::PopColormap(), ImGui::PopFocusScope(), ImGui::PopFont(), ImGui::PopID(), ImGui::PopItemFlag(), ImGui::PopItemWidth(), ImPlot::PopStyleColor(), ImGui::PopStyleColor(), ImPlot::PopStyleVar(), ImGui::PopStyleVar(), ImDrawList::PopTexture(), ImGui::PopTextWrapPos(), ImGui::RenderDimmedBackgroundBehindWindow(), ImFont::RenderText(), ImPlot::ShowStyleEditor(), ImGui::TableMergeDrawChannels(), and ImGui::TreePop().
push_back()
template<typename T > void ImVector< T >::push_back (const T & v) inline
Definition at line 2241 of file imgui.h.
References ImVector< T >::_grow_capacity(), ImVector< T >::Capacity, ImVector< T >::Data, ImVector< T >::reserve(), and ImVector< T >::Size.
Referenced by ImPlotColormapData::_AppendTable(), ImDrawList::_PathArcToFastEx(), ImDrawList::_PathArcToN(), ImDrawList::_ResetForNewFrame(), ImDrawList::_SetDrawListSharedData(), ImGui::AddContextHook(), ImDrawList::AddDrawCmd(), ImGui::AddDrawListToDrawDataEx(), ImGuiIO::AddFocusEvent(), ImFontAtlas::AddFont(), ImGuiIO::AddInputCharacter(), ExampleAssetsBrowser::AddItems(), ImGuiIO::AddKeyAnalogEvent(), ExampleAppConsole::AddLog(), ExampleAppLog::AddLog(), ImGuiIO::AddMouseButtonEvent(), ImGuiIO::AddMousePosEvent(), ImGuiIO::AddMouseWheelEvent(), ImPlot::ScrollingBuffer::AddPoint(), ImPlot::RollingBuffer::AddPoint(), ImGui::AddSettingsHandler(), ImPlotTicker::AddTick(), AddWindowToSortBuffer(), ImPlotColormapData::Append(), ImPlotAnnotationCollection::AppendV(), ImPlotTagCollection::AppendV(), ExampleSelectionWithDeletion::ApplyDeletionPostLoop(), ImGui::Begin(), ImGui::BeginColumns(), ImGui::BeginDisabled(), ImGui::BeginDisabledOverrideReenable(), ImGui::BeginMenuEx(), ImGui::BeginTabBarEx(), ImGui::BeginTableEx(), ImFontGlyphRangesBuilder::BuildRanges(), ExampleAppLog::Clear(), ExampleDescriptorHeapAllocator::Create(), CreateNewWindow(), ImPlot::Demo_Querying(), DemoWindowTables(), DemoWindowWidgetsSelectionAndMultiSelect(), DemoWindowWidgetsTabs(), DemoWindowWidgetsTextInput(), ExampleAppDocuments::DisplayDocContents(), ExampleAppDocuments::DisplayDocContextMenu(), ExampleAssetsBrowser::Draw(), ExampleAppConsole::ExampleAppConsole(), ExampleAppDocuments::ExampleAppDocuments(), ExampleTree_CreateNode(), ExampleAppConsole::ExecCommand(), ImGui::FindOrCreateColumns(), ExampleDescriptorHeapAllocator::Free(), ImGui::GetShortcutRoutingData(), ImFontAtlasAddDrawListSharedData(), ImFontAtlasBakedAddFontGlyph(), ImFontAtlasPackAddRect(), ImFontAtlasTextureAdd(), ImFontAtlasTextureBlockQueueUpload(), ImGui_ImplGlfw_ContextMap_Add(), ImGui_ImplSDL2_SetGamepadMode(), ImGui_ImplSDL2_UpdateGamepads(), ImGui_ImplSDL3_SetGamepadMode(), ImGui_ImplSDL3_UpdateGamepads(), ImGuiSelectionBasicStorage_BatchSetItemSelected(), ImGuiWindow::ImGuiWindow(), ImGui::Initialize(), ImGui::InputTextEx(), InputTextLineIndexBuild(), main(), ExampleDualListBox::MoveSelected(), ImGui::MultiSelectAddSetAll(), ImGui::MultiSelectAddSetRange(), ImGui::NewFrame(), ImGui::OpenPopupEx(), ImDrawList::PathArcTo(), ImDrawList::PathArcToFast(), ImDrawList::PathBezierCubicCurveTo(), PathBezierCubicCurveToCasteljau(), ImDrawList::PathBezierQuadraticCurveTo(), PathBezierQuadraticCurveToCasteljau(), ImDrawList::PathEllipticalArcTo(), ImDrawList::PathLineTo(), ImDrawList::PathLineToMergeDuplicate(), ImVector< T >::push_front(), ImDrawList::PushClipRect(), ImPlot::PushColormap(), ImGui::PushFocusScope(), ImGui::PushFont(), ImGui::PushID(), ImGui::PushID(), ImGui::PushID(), ImGui::PushID(), ImGui::PushItemFlag(), ImGui::PushItemWidth(), ImGui::PushMultiItemsWidths(), ImGui::PushOverrideID(), ImGui::PushStyleColor(), ImGui::PushStyleColor(), ImPlot::PushStyleColor(), ImPlot::PushStyleColor(), ImGui::PushStyleVar(), ImGui::PushStyleVar(), ImPlot::PushStyleVar(), ImPlot::PushStyleVar(), ImPlot::PushStyleVar(), ImGui::PushStyleVarX(), ImGui::PushStyleVarY(), ImDrawList::PushTexture(), ImGui::PushTextWrapPos(), ImGui::RegisterFontAtlas(), ImPlot::RegisterOrGetItem(), ImGui::RegisterUserTexture(), ImGui::SaveIniSettingsToMemory(), ImGui::SetNavFocusScope(), SetupVulkan(), ShowExampleAppCustomRendering(), ShowExampleAppDocuments(), ImGui::ShowMetricsWindow(), ImPlot::ShowStyleEditor(), ImGuiTextFilter::ImGuiTextRange::split(), ImGui::TabItemEx(), ImGui::TableAngledHeadersRow(), ExampleAppConsole::TextEditCallback(), ImGui::UpdateFontsNewFrame(), ImGui::UpdateInputEvents(), ImGui::UpdateKeyRoutingTable(), ImGui::UpdateTexturesEndFrame(), and ImGui::UpdateWindowInFocusOrderList().
push_front()
template<typename T > void ImVector< T >::push_front (const T & v) inline
Definition at line 2243 of file imgui.h.
References ImVector< T >::Data, ImVector< T >::insert(), ImVector< T >::push_back(), and ImVector< T >::Size.
Referenced by CreateNewWindow(), and ImGui::RenderDimmedBackgroundBehindWindow().
reserve()
template<typename T > void ImVector< T >::reserve (int new_capacity) inline
Definition at line 2237 of file imgui.h.
References ImVector< T >::Capacity, ImVector< T >::Data, IM_ALLOC, IM_FREE, and ImVector< T >::Size.
Referenced by ImPlotColormapData::_AppendTable(), ImDrawList::_PathArcToN(), ExampleAssetsBrowser::AddItems(), ImPlotColormapData::Append(), ExampleSelectionWithDeletion::ApplyDeletionPostLoop(), ImGuiSelectionBasicStorage::ApplyRequests(), ImGui::BeginColumns(), ExampleDescriptorHeapAllocator::Create(), ImGui::EndFrame(), ImGui::GcAwakeTransientWindowBuffers(), ImGui_ImplWGPU_Init(), ImGui::InputTextEx(), ImVector< T >::insert(), ImDrawList::PathArcTo(), ImDrawList::PathEllipticalArcTo(), ImVector< T >::push_back(), ImGuiTextBuffer::reserve(), ImPool< T >::Reserve(), ImVector< T >::resize(), ImVector< T >::resize(), ImPlot::RollingBuffer::RollingBuffer(), ImPlot::ScrollingBuffer::ScrollingBuffer(), ImDrawListSplitter::Split(), ImGui::TableAngledHeadersRow(), ImGui::TableFixDisplayOrder(), ImGui::TableGcCompactSettings(), and ImGui::TableMergeDrawChannels().
reserve_discard()
template<typename T > void ImVector< T >::reserve_discard (int new_capacity) inline
Definition at line 2238 of file imgui.h.
References ImVector< T >::Capacity, ImVector< T >::Data, IM_ALLOC, and IM_FREE.
Referenced by ImDrawList::AddConcavePolyFilled(), ImDrawList::AddConvexPolyFilled(), and ImDrawList::AddPolyline().
resize() [1/2]
template<typename T > void ImVector< T >::resize (int new_size) inline
Definition at line 2234 of file imgui.h.
References ImVector< T >::_grow_capacity(), ImVector< T >::Capacity, ImVector< T >::reserve(), and ImVector< T >::Size.
Referenced by ImDrawList::_PathArcToFastEx(), ImDrawList::_ResetForNewFrame(), ImDrawList::AddCallback(), ImPlot::AddColormap(), ImChunkStream< T >::alloc_chunk(), ImGui::Begin(), ImGuiListClipper::Begin(), ImGui::BeginColumns(), ImGui::BeginGroup(), ImGui::BeginMultiSelect(), ImPlot::BeginSubplots(), ImGui::BeginTableEx(), CheckProgram(), CheckShader(), ImGuiSelectionBasicStorage::Clear(), ImDrawData::Clear(), ImFontGlyphRangesBuilder::Clear(), ImGuiIO::ClearInputKeys(), ImGuiMultiSelectTempData::ClearIO(), ImGui::ClosePopupToLevel(), ImBitVector::Create(), ImGui::DebugHookIdInfo(), DebugItemPathQuery_UpdateAndGetHookId(), ImDrawData::DeIndexAllBuffers(), DemoWindowTables(), DemoWindowWidgetsTextInput(), ImGui::EndFrame(), ImGui::EndMultiSelect(), ImGui::EndTable(), ImPlot::FillRange(), FlattenDrawDataIntoSingleLayer(), ImGui::GetTypingSelectRequest(), ImFileOpen(), ImFontAtlasPackAllocRectEntry(), ImFontAtlasUpdateNewFrame(), ImFontBaked_BuildGrowIndex(), ImGui_ImplAllegro5_RenderDrawData(), ImGui_ImplFreeType_FontBakedLoadGlyph(), ImGui_ImplOpenGL3_UpdateTexture(), ImGui_ImplSDL2_CloseGamepads(), ImGui_ImplSDL3_CloseGamepads(), ImGui_ImplStbTrueType_FontBakedLoadGlyph(), ImGui_ImplVulkan_CreateMainPipeline(), ImGui_ImplVulkan_RenderDrawData(), ImGui_ImplVulkanH_CreateWindowSwapChain(), ImGui_ImplVulkanH_SelectPhysicalDevice(), ImGui_ImplVulkanH_SelectPresentMode(), ImGui_ImplVulkanH_SelectQueueFamilyIndex(), ImGui_ImplVulkanH_SelectSurfaceFormat(), ImGui_ImplWGPU_RenderDrawData(), ImGui::Initialize(), InitViewportDrawData(), ImGui::InputTextDeactivateHook(), ImGui::InputTextEx(), ImGuiInputTextCallbackData::InsertChars(), ImGui::LoadIniSettingsFromMemory(), LogTextV(), main(), ImDrawListSplitter::Merge(), ImGui::MultiSelectAddSetAll(), ImGui::MultiSelectItemFooter(), ImGui::NewFrame(), ImVector< T >::operator=(), Platform_SetClipboardTextFn_DefaultImpl(), ImDrawList::PrimReserve(), ImPlotColormapData::RebuildTables(), ImStableVector< T, BLOCKSIZE >::reserve(), ImGuiListClipperData::Reset(), ImGuiTextBuffer::resize(), ImGui::SaveIniSettingsToMemory(), SDL_RenderGeometryRaw8BitColor(), ImGui::SetDragDropPayload(), ImGui::SetNavFocusScope(), SetupVulkan(), ShowExampleAppCustomRendering(), ImPlot::ShowLegendEntries(), ImGui::ShowMetricsWindow(), ImGuiTextFilter::ImGuiTextRange::split(), ImDrawListSplitter::Split(), ImStb::STB_TEXTEDIT_INSERTCHARS(), ImGui::TabBarLayout(), ImGui::TableAngledHeadersRow(), ImGui::TableMergeDrawChannels(), ImGui::TableSortSpecsBuild(), TreeNodeStoreStackData(), ImGui::UpdateInputEvents(), ImGui::UpdateKeyRoutingTable(), and ImGui::UpdateTexturesEndFrame().
resize() [2/2]
template<typename T > void ImVector< T >::resize (int new_size, const T & v) inline
Definition at line 2235 of file imgui.h.
References ImVector< T >::_grow_capacity(), ImVector< T >::Capacity, ImVector< T >::Data, ImVector< T >::reserve(), and ImVector< T >::Size.
shrink()
template<typename T > void ImVector< T >::shrink (int new_size) inline
Definition at line 2236 of file imgui.h.
References IM_ASSERT, and ImVector< T >::Size.
Referenced by ImPlot::RollingBuffer::AddPoint(), ImPlotPlot::ClearTextBuffer(), ImPlot::Demo_Querying(), ImPlot::EndPlot(), ImPlot::ScrollingBuffer::Erase(), ImDrawList::PrimUnreserve(), ImPlotAnnotationCollection::Reset(), ImPlotTagCollection::Reset(), ImPlotTicker::Reset(), and ImPlotLegend::Reset().
size()
template<typename T > int ImVector< T >::size () const inline
Definition at line 2216 of file imgui.h.
References ImVector< T >::Size.
Referenced by ImPlotColormapData::_AppendTable(), ImPlot::ScrollingBuffer::AddPoint(), ImPlotTicker::AddTick(), ImPlotColormapData::Append(), ImPlot::Demo_Querying(), ImPlot::Demo_RealtimePlots(), DemoWindowWidgetsTextInput(), ImPlot::ScrollingBuffer::Erase(), ImPlotItemGroup::GetLegendCount(), and ShowExampleAppCustomRendering().
size_in_bytes()
template<typename T > int ImVector< T >::size_in_bytes () const inline
Definition at line 2217 of file imgui.h.
References ImVector< T >::Size.
Referenced by ImGui::DebugNodeStorage(), DemoWindowWidgetsSelectionAndMultiSelect(), ExampleAssetsBrowser::Draw(), ImGui_ImplVulkan_CreateMainPipeline(), ImGui_ImplVulkan_RenderDrawData(), and ImGui_ImplVulkanH_CreateWindowSwapChain().
swap()
template<typename T > void ImVector< T >::swap (ImVector< T > & rhs) inline
Definition at line 2231 of file imgui.h.
References ImVector< T >::Capacity, ImVector< T >::Data, and ImVector< T >::Size.
Referenced by ExampleSelectionWithDeletion::ApplyDeletionPostLoop(), ImDrawData::DeIndexAllBuffers(), ImGui::EndFrame(), ImFontAtlasTextureRepack(), ImGui_ImplVulkan_CreateMainPipeline(), ImGui::PopPasswordFont(), ImGui::PushPasswordFont(), ImChunkStream< T >::swap(), ImGuiSelectionBasicStorage::Swap(), and ImGui::UpdateKeyRoutingTable().
Member Data Documentation
Capacity
template<typename T > int ImVector< T >::Capacity
Definition at line 2197 of file imgui.h.
Referenced by ImVector< T >::_grow_capacity(), ImVector< T >::capacity(), ImVector< T >::clear(), ImGui::DebugNodeInputTextState(), ImGui::GcCompactTransientWindowBuffers(), ImVector< T >::ImVector(), ImVector< T >::ImVector(), ImVector< T >::insert(), ImVector< T >::push_back(), ImVector< T >::reserve(), ImVector< T >::reserve_discard(), ImVector< T >::resize(), ImVector< T >::resize(), and ImVector< T >::swap().
Data
template<typename T > T* ImVector< T >::Data
Definition at line 2198 of file imgui.h.
Referenced by ImDrawList::_OnChangedClipRect(), ImDrawList::_OnChangedTexture(), ImDrawList::_OnChangedVtxOffset(), ImDrawList::_PathArcToFastEx(), ImDrawList::_PopUnusedDrawCmd(), ImDrawList::_TryMergeDrawCmds(), ImDrawList::AddCallback(), ImPlot::AddColormap(), ImDrawList::AddConcavePolyFilled(), ImDrawList::AddConvexPolyFilled(), ImGui::AddDrawListToDrawDataEx(), ImDrawList::AddPolyline(), ImPlotTicker::AddTick(), ImPlotTicker::AddTick(), AddWindowToSortBuffer(), ImChunkStream< T >::alloc_chunk(), ExampleDualListBox::ApplySelectionRequests(), ImVector< T >::back(), ImVector< T >::back(), ImVector< T >::begin(), ImChunkStream< T >::begin(), ImVector< T >::begin(), ImGuiTextBuffer::begin(), ImGui::BeginTabBarEx(), ImGui::BringWindowToDisplayBehind(), ImGuiStorage::BuildSortByKey(), ImGuiTextBuffer::c_str(), CalcRoutingScore(), ImVector< T >::clear(), ImFontGlyphRangesBuilder::Clear(), ImVector< T >::clear_delete(), ImVector< T >::clear_destruct(), ImBitVector::ClearBit(), ImVector< T >::contains(), ImBitVector::Create(), ImGui::DebugNodeDrawCmdShowMeshAndBoundingBox(), ImGui::DebugNodeDrawList(), DemoWindowTables(), DemoWindowWidgetsSelectionAndMultiSelect(), DemoWindowWidgetsTabs(), ExampleAssetsBrowser::Draw(), ImVector< T >::end(), ImChunkStream< T >::end(), ImVector< T >::end(), ImGuiTextBuffer::end(), ImVector< T >::erase(), ImVector< T >::erase(), ImVector< T >::erase_unsorted(), ImVector< T >::find(), ImVector< T >::find(), ImVector< T >::find_erase(), ImVector< T >::find_erase_unsorted(), ImVector< T >::find_index(), ImFontBaked::FindGlyph(), ImFontBaked::FindGlyphNoFallback(), FlattenDrawDataIntoSingleLayer(), ImVector< T >::front(), ImVector< T >::front(), ImPlotPlot::GetAxisLabel(), ImFontBaked::GetCharAdvance(), ImGuiStorage::GetFloat(), ImGuiStorage::GetFloatRef(), ImGuiStorage::GetInt(), ImGuiStorage::GetIntRef(), ImPlotItemGroup::GetLegendLabel(), ImPlotColormapData::GetName(), ImGuiSelectionBasicStorage::GetNextSelectedItem(), ImPlotAnnotationCollection::GetText(), ImPlotTagCollection::GetText(), ImPlotTicker::GetText(), ImPlotPlot::GetTitle(), ImGui::GetTopMostAndVisiblePopupModal(), ImGui::GetTopMostPopupModal(), ImGuiStorage::GetVoidPtr(), ImGuiStorage::GetVoidPtrRef(), ImPlot::if(), ImFileOpen(), ImFontAtlasBakedDiscardFontGlyph(), ImFontCalcTextSizeEx(), ImFontCalcWordWrapPositionEx(), ImFormatStringToTempBufferV(), ImGui_ImplAllegro5_RenderDrawData(), ImGui_ImplDX10_RenderDrawData(), ImGui_ImplDX11_RenderDrawData(), ImGui_ImplDX12_RenderDrawData(), ImGui_ImplDX9_RenderDrawData(), ImGui_ImplFreeType_FontBakedLoadGlyph(), ImGui_ImplOpenGL2_RenderDrawData(), ImGui_ImplOpenGL3_RenderDrawData(), ImGui_ImplOpenGL3_UpdateTexture(), ImGui_ImplSDLGPU3_PrepareDrawData(), ImGui_ImplSDLRenderer2_RenderDrawData(), ImGui_ImplSDLRenderer3_RenderDrawData(), ImGui_ImplStbTrueType_FontBakedLoadGlyph(), ImGui_ImplVulkan_CreateMainPipeline(), ImGui_ImplVulkan_RenderDrawData(), ImGui_ImplVulkanH_CreateWindowSwapChain(), ImGui_ImplVulkanH_SelectPhysicalDevice(), ImGui_ImplVulkanH_SelectPresentMode(), ImGui_ImplVulkanH_SelectQueueFamilyIndex(), ImGui_ImplVulkanH_SelectSurfaceFormat(), ImGui_ImplWGPU_RenderDrawData(), ImGuiListClipper_SortAndFuseRanges(), ImGuiSelectionBasicStorage_BatchSetItemSelected(), ImVector< T >::ImVector(), ImVector< T >::ImVector(), ImVector< T >::index_from_ptr(), ImGui::InputTextDeactivateHook(), ImGui::InputTextEx(), ImVector< T >::insert(), ImGuiInputTextCallbackData::InsertChars(), ImFontBaked::IsGlyphLoaded(), ImGui::LoadIniSettingsFromMemory(), ImPlot::Locator_Time(), main(), ImDrawListSplitter::Merge(), ImGui::MultiSelectAddSetRange(), ImChunkStream< T >::offset_from_ptr(), ImVector< T >::operator=(), ImVector< T >::operator[](), ImVector< T >::operator[](), ImGuiTextBuffer::operator[](), ImDrawList::PathFillConcave(), ImDrawList::PathFillConvex(), ImDrawList::PathLineToMergeDuplicate(), ImDrawList::PathStroke(), ImDrawList::PopClipRect(), ImDrawList::PopTexture(), ImDrawList::PrimReserve(), ImDrawList::PrimUnreserve(), ImChunkStream< T >::ptr_from_offset(), ImVector< T >::push_back(), ImVector< T >::push_front(), ImFont::RenderText(), ImVector< T >::reserve(), ImVector< T >::reserve_discard(), ImVector< T >::resize(), ImGuiTextBuffer::resize(), SDL_RenderGeometryRaw8BitColor(), ImBitVector::SetBit(), ImDrawListSplitter::SetCurrentChannel(), ImGui::SetDragDropPayload(), ImGuiStorage::SetFloat(), ImGuiStorage::SetInt(), ImGui::SetNavFocusScope(), ImPlot::SetupAxisTicks(), SetupVulkan(), ImGuiStorage::SetVoidPtr(), ImGui::SetWindowClipRectBeforeSetChannel(), ImGui::ShadeVertsLinearColorGradientKeepAlpha(), ImGui::ShadeVertsLinearUV(), ImGui::ShadeVertsTransformPos(), ImGui::ShowIDStackToolWindow(), ImPlot::ShowLegendEntries(), ImGui::ShowMetricsWindow(), ImPlot::ShowMetricsWindow(), ImPlot::ShowStyleEditor(), ImStb::STB_TEXTEDIT_DELETECHARS(), ImStb::STB_TEXTEDIT_INSERTCHARS(), ImVector< T >::swap(), ImGui::TabBarGetTabName(), ImGui::TabBarLayout(), ImGui::TableAngledHeadersRow(), ImGui::TableFixDisplayOrder(), ImGui::TableMergeDrawChannels(), ImGui::TableSortSpecsBuild(), ImBitVector::TestBit(), ImGui::TreeNodeBehavior(), ImGui::TreeNodeDrawLineToChildNode(), TreeNodeStoreStackData(), ImGui::TreePop(), ImGui::UpdateInputEvents(), ImGui::UpdateWindowInFocusOrderList(), and ImVector< T >::~ImVector().
Size
template<typename T > int ImVector< T >::Size
Definition at line 2196 of file imgui.h.
Referenced by ImDrawList::_OnChangedClipRect(), ImDrawList::_OnChangedTexture(), ImDrawList::_OnChangedVtxOffset(), ImDrawList::_PathArcToFastEx(), ImDrawList::_PathArcToN(), ImDrawList::_PopUnusedDrawCmd(), ImDrawList::_TryMergeDrawCmds(), ImDrawList::AddCallback(), ImDrawList::AddCircle(), ImDrawList::AddCircleFilled(), ImDrawList::AddDrawCmd(), ImDrawData::AddDrawList(), ImGui::AddDrawListToDrawDataEx(), ImFontAtlas::AddFont(), ImDrawList::AddImageRounded(), ExampleAssetsBrowser::AddItems(), AddWindowToSortBuffer(), ExampleDescriptorHeapAllocator::Alloc(), ImChunkStream< T >::alloc_chunk(), ExampleSelectionWithDeletion::ApplyDeletionPostLoop(), ImGuiSelectionBasicStorage::ApplyRequests(), ImVector< T >::back(), ImVector< T >::back(), ImGui::Begin(), ImGuiListClipper::Begin(), ImGui::BeginColumns(), ImGui::BeginGroup(), ImGui::BeginMenuEx(), ImGui::BeginMultiSelect(), ImGui::BeginPopup(), ImGui::BeginPopupModal(), ImGui::BeginTabBarEx(), ImGui::BeginTableEx(), ImGui::BringWindowToDisplayBack(), ImGui::BringWindowToDisplayFront(), ImGui::BringWindowToFocusFront(), ImGuiStorage::BuildSortByKey(), CalcFontGlyphSrcOverlapMask(), CalcRoutingScore(), ImVector< T >::clear(), ImPool< T >::Clear(), ImVector< T >::clear_delete(), ImVector< T >::clear_destruct(), ImBitVector::ClearBit(), ImDrawListSplitter::ClearFreeMemory(), ExampleAppConsole::ClearLog(), ImGui::CloseCurrentPopup(), ImGui::ClosePopupsExceptModals(), ImGui::ClosePopupsOverWindow(), ImGui::ClosePopupToLevel(), ImGui::ColorPicker4(), ImVector< T >::contains(), ImBitVector::Create(), ImGui::DebugHookIdInfo(), DebugItemPathQuery_FormatLevelInfo(), DebugItemPathQuery_GetResultAsPath(), DebugItemPathQuery_UpdateAndGetHookId(), ImGui::DebugNodeDrawCmdShowMeshAndBoundingBox(), ImGui::DebugNodeDrawList(), ImGui::DebugNodeFont(), ImGui::DebugNodeInputTextState(), ImGui::DebugNodeStorage(), ImGui::DebugNodeTabBar(), ImGui::DebugNodeWindow(), ImGui::DebugNodeWindowsList(), ImDrawData::DeIndexAllBuffers(), DemoWindowInputs(), DemoWindowTables(), DemoWindowWidgetsSelectionAndMultiSelect(), DemoWindowWidgetsTabs(), ExampleAppConsole::Draw(), ExampleAssetsBrowser::Draw(), ExampleAppLog::Draw(), ExampleAppPropertyEditor::DrawTreeNode(), ImVector< T >::empty(), ImGuiTextBuffer::empty(), ImChunkStream< T >::empty(), ImGui::End(), ImVector< T >::end(), ImChunkStream< T >::end(), ImVector< T >::end(), ImGui::EndComboPreview(), ImGui::EndFrame(), ImGui::EndGroup(), ImGui::EndMenu(), ImGui::EndPopup(), ImGui::EndTable(), ImVector< T >::erase(), ImVector< T >::erase(), ImVector< T >::erase_unsorted(), ImGui::ErrorCheckEndFrameSanityChecks(), ImGui::ErrorRecoveryStoreState(), ImGui::ErrorRecoveryTryToRecoverState(), ImGui::ErrorRecoveryTryToRecoverWindowState(), ExampleTree_CreateNode(), ExampleAppConsole::ExecCommand(), ImVector< T >::find(), ImVector< T >::find(), ImVector< T >::find_erase(), ImVector< T >::find_erase_unsorted(), ImVector< T >::find_index(), ImGui::FindBestWindowPosForPopup(), ImGui::FindBlockingModal(), ImFontBaked::FindGlyph(), ImFontBaked::FindGlyphNoFallback(), ImGui::FindHoveredWindowEx(), FindLatestInputEvent(), ImGui::FindOrCreateColumns(), FindWindowNavFocusable(), FlattenDrawDataIntoSingleLayer(), ImGui::FocusTopMostWindowUnderOne(), ImVector< T >::front(), ImVector< T >::front(), ImGuiTextIndex::get_line_begin(), ImGuiTextIndex::get_line_end(), ImFontBaked::GetCharAdvance(), ImFont::GetDebugName(), ImGui::GetDefaultFont(), ImGuiStorage::GetFloat(), ImGuiStorage::GetFloatRef(), ImGuiStorage::GetInt(), ImGuiStorage::GetIntRef(), ImPool< T >::GetMapSize(), ImGui::GetMousePosOnOpeningCurrentPopup(), ImGuiSelectionBasicStorage::GetNextSelectedItem(), ImGui::GetShortcutRoutingData(), ImGui::GetTopMostAndVisiblePopupModal(), ImGui::GetTopMostPopupModal(), ImGuiStorage::GetVoidPtr(), ImGuiStorage::GetVoidPtrRef(), ImFontAtlas_FontHookRemapCodepoint(), ImFontAtlasBakedAddFontGlyph(), ImFontAtlasBakedDiscardFontGlyph(), ImFontAtlasBuildMain(), ImFontAtlasDebugLogTextureRequests(), ImFontAtlasPackAddRect(), ImFontAtlasPackAllocRectEntry(), ImFontAtlasPackGetRectSafe(), ImFontAtlasPackReuseRectEntry(), ImFontAtlasTextureRepack(), ImFontAtlasUpdateDrawListsTextures(), ImFontAtlasUpdateNewFrame(), ImFontBaked_BuildGrowIndex(), ImFontCalcTextSizeEx(), ImFontCalcWordWrapPositionEx(), ImFormatStringToTempBufferV(), ImGui_ImplAllegro5_RenderDrawData(), ImGui_ImplDX10_RenderDrawData(), ImGui_ImplDX11_RenderDrawData(), ImGui_ImplDX12_RenderDrawData(), ImGui_ImplDX9_RenderDrawData(), ImGui_ImplOpenGL2_RenderDrawData(), ImGui_ImplOpenGL3_RenderDrawData(), ImGui_ImplSDL2_UpdateGamepads(), ImGui_ImplSDL3_UpdateGamepads(), ImGui_ImplSDLGPU3_PrepareDrawData(), ImGui_ImplSDLGPU3_RenderDrawData(), ImGui_ImplSDLRenderer2_RenderDrawData(), ImGui_ImplSDLRenderer3_RenderDrawData(), ImGui_ImplVulkan_RenderDrawData(), ImGui_ImplWGPU_RenderDrawData(), ImGuiListClipper_SortAndFuseRanges(), ImVector< T >::ImVector(), ImVector< T >::ImVector(), ImVector< T >::index_from_ptr(), ImGui::InputTextEx(), ImVector< T >::insert(), ImGuiInputTextCallbackData::InsertChars(), ImFontBaked::IsGlyphLoaded(), ImGui::IsPopupOpen(), IsRootOfOpenMenuSet(), ImGui::IsWindowAbove(), ImGui::IsWindowInBeginStack(), ImDrawListSplitter::Merge(), ExampleDualListBox::MoveSelected(), ImGui::MultiSelectAddSetRange(), ImGui::NavUpdateCancelRequest(), ImGui::NavUpdateWindowing(), ImGui::NavUpdateWindowingOverlay(), NavUpdateWindowingTarget(), ImGui::NewFrame(), ImGui::OpenPopupEx(), ImVector< T >::operator=(), ImVector< T >::operator[](), ImVector< T >::operator[](), ImDrawList::PathArcTo(), ImDrawList::PathClear(), ImDrawList::PathEllipticalArcTo(), ImDrawList::PathFillConcave(), ImDrawList::PathFillConvex(), ImDrawList::PathLineToMergeDuplicate(), ImDrawList::PathStroke(), ImVector< T >::pop_back(), ImDrawList::PopClipRect(), ImPlot::PopColormap(), ImGui::PopFocusScope(), ImGui::PopFont(), ImGui::PopID(), ImGui::PopItemFlag(), ImGui::PopItemWidth(), ImGui::PopPasswordFont(), ImPlot::PopStyleColor(), ImGui::PopStyleColor(), ImPlot::PopStyleVar(), ImGui::PopStyleVar(), ImDrawList::PopTexture(), ImGui::PopTextWrapPos(), ImDrawList::PrimReserve(), ImDrawList::PrimUnreserve(), ImChunkStream< T >::ptr_from_offset(), ImVector< T >::push_back(), ImVector< T >::push_front(), ImGui::PushPasswordFont(), ImGui::RegisterFontAtlas(), ImFontAtlas::RemoveFont(), ImGui::Render(), ImGui::RenderDimmedBackgroundBehindWindow(), ImGui::RenderDimmedBackgrounds(), ImFont::RenderText(), RenderViewportsThumbnails(), ImVector< T >::reserve(), ImVector< T >::resize(), ImVector< T >::resize(), ImGuiTextBuffer::resize(), ImGuiStorage::SetAllInt(), ImBitVector::SetBit(), ImDrawListSplitter::SetCurrentChannel(), ImGuiStorage::SetFloat(), ImGuiStorage::SetInt(), ImGui::SetNavFocusScope(), SetupVulkan(), ImGuiStorage::SetVoidPtr(), ImGui::SetWindowClipRectBeforeSetChannel(), ExampleDualListBox::Show(), ImGui::ShowAboutWindow(), ShowExampleAppCustomRendering(), ShowExampleAppDocuments(), ImGui::ShowFontAtlas(), ImGui::ShowIDStackToolWindow(), ImGui::ShowMetricsWindow(), ImPlot::ShowMetricsWindow(), ImPlot::ShowStyleEditor(), ImVector< T >::shrink(), ImGuiTextIndex::size(), ImVector< T >::size(), ImGuiTextBuffer::size(), ImChunkStream< T >::size(), ImVector< T >::size_in_bytes(), ImDrawListSplitter::Split(), ImStb::STB_TEXTEDIT_INSERTCHARS(), ImVector< T >::swap(), ImGui::TabBarFindTabByID(), ImGui::TabBarFindTabByOrder(), ImGui::TabBarGetCurrentTab(), ImGui::TabBarGetTabName(), ImGui::TabBarLayout(), ImGui::TabBarProcessReorder(), ImGui::TabBarQueueReorderFromMousePos(), ImGui::TabBarScrollingButtons(), ImGui::TabBarScrollToTab(), ImGui::TabBarTabListPopupButton(), ImGui::TabItemEx(), ImGui::TableAngledHeadersRow(), ImGui::TableGcCompactSettings(), ImGui::TableMergeDrawChannels(), ImBitVector::TestBit(), ExampleAppConsole::TextEditCallback(), ImPlotTicker::TickCount(), ImGui::TreeNodeBehavior(), ImGui::TreeNodeDrawLineToChildNode(), TreeNodeStoreStackData(), ImGui::TreePop(), ImGui::UpdateHoveredWindowAndCaptureFlags(), ImGui::UpdateInputEvents(), ImGui::UpdateKeyRoutingTable(), ExampleAssetsBrowser::UpdateLayoutSizes(), ImGui::UpdateViewportsNewFrame(), ImGui::UpdateWindowInFocusOrderList(), ExampleAppConsole::~ExampleAppConsole(), and ImDrawListSharedData::~ImDrawListSharedData().
The documentation for this struct was generated from the following file:
examples/imgui/imgui.h