SignalProcessing: ImPlot::RendererStairsPre< _Getter > Struct Template Reference
ImPlot::RendererStairsPre< _Getter > Struct Template Reference
Public Member Functions
RendererStairsPre (const _Getter &getter, ImU32 col, float weight)
void Init (ImDrawList &draw_list) const
bool Render (ImDrawList &draw_list, const ImRect &cull_rect, int prim) const
Public Member Functions inherited from ImPlot::RendererBase
RendererBase (int prims, int idx_consumed, int vtx_consumed)
Public Attributes
const _Getter & Getter
const ImU32 Col
float HalfWeight
ImVec2 P1
ImVec2 UV
Public Attributes inherited from ImPlot::RendererBase
const int Prims
Transformer2 Transformer
const int IdxConsumed
const int VtxConsumed
Detailed Description
template<class _Getter>
struct ImPlot::RendererStairsPre< _Getter >
Definition at line 1143 of file implot_items.cpp.
Constructor & Destructor Documentation
RendererStairsPre()
template<class _Getter > ImPlot::RendererStairsPre< _Getter >::RendererStairsPre (const _Getter & getter, ImU32 col, float weight) inline
Definition at line 1144 of file implot_items.cpp.
References ImPlot::RendererStairsPre< _Getter >::Getter, ImPlot::RendererStairsPre< _Getter >::P1, and ImPlot::RendererBase::Transformer.
Member Function Documentation
Init()
template<class _Getter > void ImPlot::RendererStairsPre< _Getter >::Init (ImDrawList & draw_list) const inline
Definition at line 1152 of file implot_items.cpp.
References ImDrawList::_Data, ImPlot::draw_list, ImDrawListSharedData::TexUvWhitePixel, and ImPlot::RendererStairsPre< _Getter >::UV.
Render()
template<class _Getter > bool ImPlot::RendererStairsPre< _Getter >::Render (ImDrawList & draw_list, const ImRect & cull_rect, int prim) const inline
Definition at line 1155 of file implot_items.cpp.
References ImPlot::RendererStairsPre< _Getter >::Col, ImPlot::draw_list, ImPlot::RendererStairsPre< _Getter >::Getter, ImPlot::RendererStairsPre< _Getter >::HalfWeight, ImMax(), ImMin(), ImRect::Overlaps(), ImPlot::RendererStairsPre< _Getter >::P1, ImPlot::PrimRectFill(), ImPlot::RendererBase::Transformer, ImPlot::RendererStairsPre< _Getter >::UV, ImVec2::x, and ImVec2::y.
Member Data Documentation
Col
template<class _Getter > const ImU32 ImPlot::RendererStairsPre< _Getter >::Col
Definition at line 1167 of file implot_items.cpp.
Referenced by ImPlot::RendererStairsPre< _Getter >::Render().
Getter
template<class _Getter > const _Getter& ImPlot::RendererStairsPre< _Getter >::Getter
Definition at line 1166 of file implot_items.cpp.
Referenced by ImPlot::RendererStairsPre< _Getter >::Render(), and ImPlot::RendererStairsPre< _Getter >::RendererStairsPre().
HalfWeight
template<class _Getter > float ImPlot::RendererStairsPre< _Getter >::HalfWeight mutable
Definition at line 1168 of file implot_items.cpp.
Referenced by ImPlot::RendererStairsPre< _Getter >::Render().
P1
template<class _Getter > ImVec2 ImPlot::RendererStairsPre< _Getter >::P1 mutable
Definition at line 1169 of file implot_items.cpp.
Referenced by ImPlot::RendererStairsPre< _Getter >::Render(), and ImPlot::RendererStairsPre< _Getter >::RendererStairsPre().
UV
template<class _Getter > ImVec2 ImPlot::RendererStairsPre< _Getter >::UV mutable
Definition at line 1170 of file implot_items.cpp.
Referenced by ImPlot::RendererStairsPre< _Getter >::Init(), and ImPlot::RendererStairsPre< _Getter >::Render().
The documentation for this struct was generated from the following file:
examples/implot/implot_items.cpp