SignalProcessing: ImPlotTagCollection Struct Reference
ImPlotTagCollection Struct Reference
#include <implot_internal.h>
Public Member Functions
ImPlotTagCollection ()
void AppendV (ImAxis axis, double value, ImU32 bg, ImU32 fg, const char *fmt, va_list args) IM_FMTLIST(6)
void Append (ImAxis axis, double value, ImU32 bg, ImU32 fg, const char *fmt,...) IM_FMTARGS(6)
const char * GetText (int idx)
void Reset ()
Public Attributes
ImVector< ImPlotTag > Tags
ImGuiTextBuffer TextBuffer
int Size
Detailed Description
Definition at line 501 of file implot_internal.h.
Constructor & Destructor Documentation
ImPlotTagCollection()
ImPlotTagCollection::ImPlotTagCollection () inline
Definition at line 507 of file implot_internal.h.
References Reset().
Member Function Documentation
Append()
void ImPlotTagCollection::Append (ImAxis axis, double value, ImU32 bg, ImU32 fg, const char * fmt, ...) inline
Definition at line 523 of file implot_internal.h.
References AppendV().
AppendV()
void ImPlotTagCollection::AppendV (ImAxis axis, double value, ImU32 bg, ImU32 fg, const char * fmt, va_list args) inline
Definition at line 509 of file implot_internal.h.
References ImGuiTextBuffer::append(), ImGuiTextBuffer::appendfv(), ImPlotTag::Axis, ImPlotTag::ColorBg, ImPlotTag::ColorFg, ImVector< T >::push_back(), ImGuiTextBuffer::size(), Size, Tags, TextBuffer, ImPlotTag::TextOffset, and ImPlotTag::Value.
Referenced by Append(), and ImPlot::TagV().
GetText()
const char * ImPlotTagCollection::GetText (int idx) inline
Definition at line 530 of file implot_internal.h.
References ImGuiTextBuffer::Buf, ImVector< T >::Data, Tags, and TextBuffer.
Referenced by ImPlot::EndPlot().
Reset()
void ImPlotTagCollection::Reset () inline
Definition at line 534 of file implot_internal.h.
References ImGuiTextBuffer::Buf, ImVector< T >::shrink(), Size, Tags, and TextBuffer.
Referenced by ImPlotTagCollection(), and ImPlot::ResetCtxForNextPlot().
Member Data Documentation
Size
int ImPlotTagCollection::Size
Definition at line 505 of file implot_internal.h.
Referenced by AppendV(), ImPlot::EndPlot(), and Reset().
Tags
ImVector<ImPlotTag> ImPlotTagCollection::Tags
Definition at line 503 of file implot_internal.h.
Referenced by AppendV(), ImPlot::EndPlot(), GetText(), and Reset().
TextBuffer
ImGuiTextBuffer ImPlotTagCollection::TextBuffer
Definition at line 504 of file implot_internal.h.
Referenced by AppendV(), GetText(), and Reset().
The documentation for this struct was generated from the following file:
examples/implot/implot_internal.h