SignalProcessing: ImPlot::RendererRectC< _Getter > Struct Template Reference
ImPlot::RendererRectC< _Getter > Struct Template Reference
Public Member Functions
RendererRectC (const _Getter &getter)
void Init (ImDrawList &draw_list) const
bool Render (ImDrawList &draw_list, const ImRect &cull_rect, int prim) const
Public Member Functions inherited from ImPlot::RendererBase
RendererBase (int prims, int idx_consumed, int vtx_consumed)
Public Attributes
const _Getter & Getter
ImVec2 UV
Public Attributes inherited from ImPlot::RendererBase
const int Prims
Transformer2 Transformer
const int IdxConsumed
const int VtxConsumed
Detailed Description
template<typename _Getter>
struct ImPlot::RendererRectC< _Getter >
Definition at line 1338 of file implot_items.cpp.
Constructor & Destructor Documentation
RendererRectC()
template<typename _Getter > ImPlot::RendererRectC< _Getter >::RendererRectC (const _Getter & getter) inline
Definition at line 1339 of file implot_items.cpp.
Member Function Documentation
Init()
template<typename _Getter > void ImPlot::RendererRectC< _Getter >::Init (ImDrawList & draw_list) const inline
Definition at line 1343 of file implot_items.cpp.
References ImDrawList::_Data, ImPlot::draw_list, ImDrawListSharedData::TexUvWhitePixel, and ImPlot::RendererRectC< _Getter >::UV.
Render()
template<typename _Getter > bool ImPlot::RendererRectC< _Getter >::Render (ImDrawList & draw_list, const ImRect & cull_rect, int prim) const inline
Definition at line 1346 of file implot_items.cpp.
References ImPlot::RectC::Color, ImPlot::draw_list, ImPlot::RendererRectC< _Getter >::Getter, ImPlot::RectC::HalfSize, IM_COL32_A_MASK, ImMax(), ImMin(), ImRect::Overlaps(), ImPlot::RectC::Pos, ImPlot::PrimRectFill(), ImPlot::RendererBase::Transformer, ImPlot::RendererRectC< _Getter >::UV, ImPlotPoint::x, and ImPlotPoint::y.
Member Data Documentation
Getter
template<typename _Getter > const _Getter& ImPlot::RendererRectC< _Getter >::Getter
Definition at line 1355 of file implot_items.cpp.
Referenced by ImPlot::RendererRectC< _Getter >::Render().
UV
template<typename _Getter > ImVec2 ImPlot::RendererRectC< _Getter >::UV mutable
Definition at line 1356 of file implot_items.cpp.
Referenced by ImPlot::RendererRectC< _Getter >::Init(), and ImPlot::RendererRectC< _Getter >::Render().
The documentation for this struct was generated from the following file:
examples/implot/implot_items.cpp