SignalProcessing: ImGuiSelectionBasicStorage Struct Reference
ImGuiSelectionBasicStorage Struct Reference
#include <imgui.h>
Public Member Functions
ImGuiSelectionBasicStorage ()
void ApplyRequests (ImGuiMultiSelectIO *ms_io)
bool Contains (ImGuiID id) const
void Clear ()
void Swap (ImGuiSelectionBasicStorage &r)
void SetItemSelected (ImGuiID id, bool selected)
bool GetNextSelectedItem (void **opaque_it, ImGuiID *out_id)
ImGuiID GetStorageIdFromIndex (int idx)
Public Attributes
int Size
bool PreserveOrder
void * UserData
ImGuiID(* AdapterIndexToStorageId)(ImGuiSelectionBasicStorage *self, int idx)
int _SelectionOrder
ImGuiStorage _Storage
Detailed Description
Definition at line 3071 of file imgui.h.
Constructor & Destructor Documentation
ImGuiSelectionBasicStorage()
ImGuiSelectionBasicStorage::ImGuiSelectionBasicStorage ()
Definition at line 8420 of file imgui_widgets.cpp.
References _SelectionOrder, AdapterIndexToStorageId, PreserveOrder, Size, and UserData.
Member Function Documentation
ApplyRequests()
void ImGuiSelectionBasicStorage::ApplyRequests (ImGuiMultiSelectIO * ms_io)
Definition at line 8522 of file imgui_widgets.cpp.
References _SelectionOrder, _Storage, AdapterIndexToStorageId, Clear(), ImGuiStorage::Data, GetStorageIdFromIndex(), IM_ASSERT, ImGuiSelectionBasicStorage_BatchFinish(), ImGuiSelectionBasicStorage_BatchSetItemSelected(), ImGuiSelectionRequestType_SetAll, ImGuiSelectionRequestType_SetRange, ImGuiMultiSelectIO::ItemsCount, ImGuiMultiSelectIO::Requests, ImVector< T >::reserve(), SetItemSelected(), ImVector< T >::Size, and Size.
Referenced by ExampleDualListBox::ApplySelectionRequests(), DemoWindowWidgetsSelectionAndMultiSelect(), and ExampleAssetsBrowser::Draw().
Clear()
void ImGuiSelectionBasicStorage::Clear ()
Definition at line 8429 of file imgui_widgets.cpp.
References _SelectionOrder, _Storage, ImGuiStorage::Data, ImVector< T >::resize(), and Size.
Referenced by ExampleSelectionWithDeletion::ApplyDeletionPostLoop(), ApplyRequests(), ExampleAssetsBrowser::ClearItems(), DemoWindowWidgetsSelectionAndMultiSelect(), ExampleDualListBox::MoveAll(), and ExampleDualListBox::MoveSelected().
Contains()
bool ImGuiSelectionBasicStorage::Contains (ImGuiID id) const
Definition at line 8443 of file imgui_widgets.cpp.
References _Storage, and ImGuiStorage::GetInt().
Referenced by ExampleSelectionWithDeletion::ApplyDeletionPostLoop(), ExampleSelectionWithDeletion::ApplyDeletionPreLoop(), DemoWindowWidgetsSelectionAndMultiSelect(), ExampleAssetsBrowser::Draw(), and ExampleDualListBox::Show().
GetNextSelectedItem()
bool ImGuiSelectionBasicStorage::GetNextSelectedItem (void ** opaque_it, ImGuiID * out_id)
Definition at line 8457 of file imgui_widgets.cpp.
References _Storage, ImGuiStorage::BuildSortByKey(), ImVector< T >::Data, ImGuiStorage::Data, IM_ASSERT, ImQsort(), ImGuiStoragePair::key, PairComparerByValueInt(), PreserveOrder, ImVector< T >::Size, and ImGuiStoragePair::val_i.
Referenced by DemoWindowWidgetsSelectionAndMultiSelect(), and ExampleAssetsBrowser::Draw().
GetStorageIdFromIndex()
ImGuiID ImGuiSelectionBasicStorage::GetStorageIdFromIndex (int idx) inline
Definition at line 3089 of file imgui.h.
Referenced by ExampleSelectionWithDeletion::ApplyDeletionPostLoop(), ExampleSelectionWithDeletion::ApplyDeletionPreLoop(), and ApplyRequests().
SetItemSelected()
void ImGuiSelectionBasicStorage::SetItemSelected (ImGuiID id, bool selected)
Definition at line 8477 of file imgui_widgets.cpp.
References _SelectionOrder, _Storage, ImGuiStorage::GetIntRef(), and Size.
Referenced by ExampleSelectionWithDeletion::ApplyDeletionPostLoop(), ApplyRequests(), and DemoWindowWidgetsSelectionAndMultiSelect().
Swap()
void ImGuiSelectionBasicStorage::Swap (ImGuiSelectionBasicStorage & r)
Definition at line 8436 of file imgui_widgets.cpp.
References _SelectionOrder, _Storage, ImGuiStorage::Data, ImSwap(), Size, and ImVector< T >::swap().
Referenced by ExampleDualListBox::MoveAll(), and ExampleDualListBox::MoveSelected().
Member Data Documentation
_SelectionOrder
int ImGuiSelectionBasicStorage::_SelectionOrder
Definition at line 3078 of file imgui.h.
Referenced by ApplyRequests(), Clear(), ImGuiSelectionBasicStorage(), SetItemSelected(), and Swap().
_Storage
ImGuiStorage ImGuiSelectionBasicStorage::_Storage
Definition at line 3079 of file imgui.h.
Referenced by ApplyRequests(), Clear(), Contains(), GetNextSelectedItem(), ImGuiSelectionBasicStorage_BatchFinish(), ImGuiSelectionBasicStorage_BatchSetItemSelected(), SetItemSelected(), and Swap().
AdapterIndexToStorageId
ImGuiID(* ImGuiSelectionBasicStorage::AdapterIndexToStorageId) (ImGuiSelectionBasicStorage *self, int idx)
Definition at line 3077 of file imgui.h.
Referenced by ApplyRequests(), ExampleDualListBox::ApplySelectionRequests(), DemoWindowWidgetsSelectionAndMultiSelect(), ExampleAssetsBrowser::Draw(), and ImGuiSelectionBasicStorage().
PreserveOrder
bool ImGuiSelectionBasicStorage::PreserveOrder
Definition at line 3075 of file imgui.h.
Referenced by GetNextSelectedItem(), and ImGuiSelectionBasicStorage().
Size
int ImGuiSelectionBasicStorage::Size
Definition at line 3074 of file imgui.h.
Referenced by ExampleSelectionWithDeletion::ApplyDeletionPostLoop(), ExampleSelectionWithDeletion::ApplyDeletionPreLoop(), ApplyRequests(), Clear(), DemoWindowWidgetsSelectionAndMultiSelect(), ExampleAssetsBrowser::Draw(), ImGuiSelectionBasicStorage(), ImGuiSelectionBasicStorage_BatchFinish(), ImGuiSelectionBasicStorage_BatchSetItemSelected(), SetItemSelected(), ExampleDualListBox::Show(), and Swap().
UserData
void* ImGuiSelectionBasicStorage::UserData
Definition at line 3076 of file imgui.h.
Referenced by ExampleDualListBox::ApplySelectionRequests(), DemoWindowWidgetsSelectionAndMultiSelect(), ExampleAssetsBrowser::Draw(), and ImGuiSelectionBasicStorage().
The documentation for this struct was generated from the following files:
examples/imgui/imgui.h
examples/imgui/imgui_widgets.cpp