SignalProcessing: ImPlotAxis Struct Reference
ImPlotAxis Struct Reference
#include <implot_internal.h>
Public Member Functions
ImPlotAxis ()
void Reset ()
bool SetMin (double _min, bool force=false)
bool SetMax (double _max, bool force=false)
void SetRange (double v1, double v2)
void SetRange (const ImPlotRange &range)
void SetAspect (double unit_per_pix)
float PixelSize () const
double GetAspect () const
void Constrain ()
void UpdateTransformCache ()
float PlotToPixels (double plt) const
double PixelsToPlot (float pix) const
void ExtendFit (double v)
void ExtendFitWith (ImPlotAxis &alt, double v, double v_alt)
void ApplyFit (float padding)
bool HasLabel () const
bool HasGridLines () const
bool HasTickLabels () const
bool HasTickMarks () const
bool WillRender () const
bool IsOpposite () const
bool IsInverted () const
bool IsForeground () const
bool IsAutoFitting () const
bool CanInitFit () const
bool IsRangeLocked () const
bool IsLockedMin () const
bool IsLockedMax () const
bool IsLocked () const
bool IsInputLockedMin () const
bool IsInputLockedMax () const
bool IsInputLocked () const
bool HasMenus () const
bool IsPanLocked (bool increasing)
void PushLinks ()
void PullLinks ()
Public Attributes
ImGuiID ID
ImPlotAxisFlags Flags
ImPlotAxisFlags PreviousFlags
ImPlotRange Range
ImPlotCond RangeCond
ImPlotScale Scale
ImPlotRange FitExtents
ImPlotAxis * OrthoAxis
ImPlotRange ConstraintRange
ImPlotRange ConstraintZoom
ImPlotTicker Ticker
ImPlotFormatter Formatter
void * FormatterData
char FormatSpec [16]
ImPlotLocator Locator
double * LinkedMin
double * LinkedMax
int PickerLevel
ImPlotTime PickerTimeMin
ImPlotTime PickerTimeMax
ImPlotTransform TransformForward
ImPlotTransform TransformInverse
void * TransformData
float PixelMin
float PixelMax
double ScaleMin
double ScaleMax
double ScaleToPixel
float Datum1
float Datum2
ImRect HoverRect
int LabelOffset
ImU32 ColorMaj
ImU32 ColorMin
ImU32 ColorTick
ImU32 ColorTxt
ImU32 ColorBg
ImU32 ColorHov
ImU32 ColorAct
ImU32 ColorHiLi
bool Enabled
bool Vertical
bool FitThisFrame
bool HasRange
bool HasFormatSpec
bool ShowDefaultTicks
bool Hovered
bool Held
Detailed Description
Definition at line 645 of file implot_internal.h.
Constructor & Destructor Documentation
ImPlotAxis()
ImPlotAxis::ImPlotAxis () inline
Definition at line 691 of file implot_internal.h.
References ColorAct, ColorBg, ColorHiLi, ColorHov, ColorMaj, ColorMin, ColorTick, ColorTxt, ConstraintRange, ConstraintZoom, Datum1, Datum2, Enabled, FitExtents, FitThisFrame, Flags, Formatter, FormatterData, HasFormatSpec, HasRange, Held, Hovered, ID, IM_COL32_BLACK_TRANS, ImPlotAxisFlags_None, ImPlotScale_Linear, LabelOffset, LinkedMax, LinkedMin, Locator, ImPlotRange::Max, ImPlotRange::Min, OrthoAxis, PickerLevel, PixelMax, PixelMin, PreviousFlags, Range, Scale, ShowDefaultTicks, TransformData, TransformForward, and TransformInverse.
Member Function Documentation
ApplyFit()
void ImPlotAxis::ApplyFit (float padding) inline
Definition at line 876 of file implot_internal.h.
References Constrain(), FitExtents, ImAlmostEqual(), ImNanOrInf(), IsLockedMax(), IsLockedMin(), ImPlotRange::Max, ImPlotRange::Min, Range, ImPlotRange::Size(), and UpdateTransformCache().
Referenced by ImPlot::EndPlot().
CanInitFit()
bool ImPlotAxis::CanInitFit () const inline
Definition at line 901 of file implot_internal.h.
References Flags, HasRange, ImHasFlag(), ImPlotAxisFlags_NoInitialFit, LinkedMax, and LinkedMin.
Referenced by ImPlot::SetupFinish().
Constrain()
void ImPlotAxis::Constrain () inline
Definition at line 806 of file implot_internal.h.
References ConstraintRange, ConstraintZoom, ImConstrainInf(), ImConstrainNan(), ImPlotRange::Max, ImPlotRange::Min, Range, and ImPlotRange::Size().
Referenced by ApplyFit(), SetRange(), and ImPlot::SetupFinish().
ExtendFit()
void ImPlotAxis::ExtendFit (double v) inline
Definition at line 860 of file implot_internal.h.
References ConstraintRange, FitExtents, ImNanOrInf(), ImPlotRange::Max, and ImPlotRange::Min.
Referenced by ImPlot::FitterY< _Getter1 >::Fit(), ImPlot::FitterX< _Getter1 >::Fit(), ImPlot::FitPointX(), and ImPlot::FitPointY().
ExtendFitWith()
void ImPlotAxis::ExtendFitWith (ImPlotAxis & alt, double v, double v_alt) inline
Definition at line 867 of file implot_internal.h.
References ConstraintRange, ImPlotRange::Contains(), FitExtents, Flags, ImHasFlag(), ImNanOrInf(), ImPlotAxisFlags_RangeFit, ImPlotRange::Max, ImPlotRange::Min, and Range.
Referenced by ImPlot::Fitter1< _Getter1 >::Fit(), ImPlot::Fitter2< _Getter1, _Getter2 >::Fit(), ImPlot::FitterBarV< _Getter1, _Getter2 >::Fit(), ImPlot::FitterBarH< _Getter1, _Getter2 >::Fit(), ImPlot::FitterRect::Fit(), and ImPlot::FitPoint().
GetAspect()
double ImPlotAxis::GetAspect () const inline
Definition at line 804 of file implot_internal.h.
References PixelSize(), Range, and ImPlotRange::Size().
Referenced by ImPlot::EndPlot(), ImPlot::SetupFinish(), ImPlot::ShowAxisContextMenu(), ImPlot::ShowAxisMetrics(), and ImPlot::UpdateInput().
HasGridLines()
bool ImPlotAxis::HasGridLines () const inline
Definition at line 893 of file implot_internal.h.
References Flags, ImHasFlag(), and ImPlotAxisFlags_NoGridLines.
Referenced by ImPlot::EndPlot(), ImPlot::SetupFinish(), ImPlot::ShowAxisContextMenu(), and WillRender().
HasLabel()
bool ImPlotAxis::HasLabel () const inline
Definition at line 892 of file implot_internal.h.
References Flags, ImHasFlag(), ImPlotAxisFlags_NoLabel, and LabelOffset.
Referenced by ImPlot::EndPlot(), ImPlot::PadAndDatumAxesX(), ImPlot::PadAndDatumAxesY(), ImPlot::SetupFinish(), ImPlot::ShowAxisContextMenu(), and ImPlot::ShowPlotContextMenu().
HasMenus()
bool ImPlotAxis::HasMenus () const inline
Definition at line 909 of file implot_internal.h.
References Flags, ImHasFlag(), and ImPlotAxisFlags_NoMenus.
Referenced by ImPlot::EndPlot(), and ImPlot::ShowPlotContextMenu().
HasTickLabels()
bool ImPlotAxis::HasTickLabels () const inline
Definition at line 894 of file implot_internal.h.
References Flags, ImHasFlag(), and ImPlotAxisFlags_NoTickLabels.
Referenced by ImPlot::PadAndDatumAxesX(), ImPlot::PadAndDatumAxesY(), ImPlot::SetupFinish(), ImPlot::ShowAxisContextMenu(), and WillRender().
HasTickMarks()
bool ImPlotAxis::HasTickMarks () const inline
Definition at line 895 of file implot_internal.h.
References Flags, ImHasFlag(), and ImPlotAxisFlags_NoTickMarks.
Referenced by ImPlot::EndPlot(), ImPlot::ShowAxisContextMenu(), and WillRender().
IsAutoFitting()
bool ImPlotAxis::IsAutoFitting () const inline
Definition at line 900 of file implot_internal.h.
References Flags, ImHasFlag(), and ImPlotAxisFlags_AutoFit.
Referenced by IsInputLocked(), IsInputLockedMax(), IsInputLockedMin(), IsPanLocked(), ImPlot::SetupFinish(), and ImPlot::ShowAxisContextMenu().
IsForeground()
bool ImPlotAxis::IsForeground () const inline
Definition at line 899 of file implot_internal.h.
References Flags, ImHasFlag(), and ImPlotAxisFlags_Foreground.
Referenced by ImPlot::EndPlot(), and ImPlot::SetupFinish().
IsInputLocked()
bool ImPlotAxis::IsInputLocked () const inline
Definition at line 908 of file implot_internal.h.
References IsAutoFitting(), and IsLocked().
Referenced by IsPanLocked(), ImPlot::SetupFinish(), and ImPlot::UpdateInput().
IsInputLockedMax()
bool ImPlotAxis::IsInputLockedMax () const inline
Definition at line 907 of file implot_internal.h.
References IsAutoFitting(), and IsLockedMax().
IsInputLockedMin()
bool ImPlotAxis::IsInputLockedMin () const inline
Definition at line 906 of file implot_internal.h.
References IsAutoFitting(), and IsLockedMin().
IsInverted()
bool ImPlotAxis::IsInverted () const inline
Definition at line 898 of file implot_internal.h.
References Flags, ImHasFlag(), and ImPlotAxisFlags_Invert.
Referenced by ImPlot::SetupFinish(), and ImPlot::UpdateInput().
IsLocked()
bool ImPlotAxis::IsLocked () const inline
Definition at line 905 of file implot_internal.h.
References IsLockedMax(), and IsLockedMin().
Referenced by IsInputLocked(), and SetAspect().
IsLockedMax()
bool ImPlotAxis::IsLockedMax () const inline
Definition at line 904 of file implot_internal.h.
References Enabled, Flags, ImHasFlag(), ImPlotAxisFlags_LockMax, and IsRangeLocked().
Referenced by ApplyFit(), IsInputLockedMax(), IsLocked(), IsPanLocked(), SetAspect(), SetMax(), and ImPlot::ShowAxisContextMenu().
IsLockedMin()
bool ImPlotAxis::IsLockedMin () const inline
Definition at line 903 of file implot_internal.h.
References Enabled, Flags, ImHasFlag(), ImPlotAxisFlags_LockMin, and IsRangeLocked().
Referenced by ApplyFit(), IsInputLockedMin(), IsLocked(), IsPanLocked(), SetAspect(), SetMin(), and ImPlot::ShowAxisContextMenu().
IsOpposite()
bool ImPlotAxis::IsOpposite () const inline
Definition at line 897 of file implot_internal.h.
References Flags, ImHasFlag(), and ImPlotAxisFlags_Opposite.
Referenced by ImPlot::EndPlot(), ImPlot::PadAndDatumAxesX(), ImPlot::PadAndDatumAxesY(), and ImPlot::SetupFinish().
IsPanLocked()
bool ImPlotAxis::IsPanLocked (bool increasing) inline
Definition at line 911 of file implot_internal.h.
References ConstraintRange, Flags, ImHasFlag(), ImPlotAxisFlags_PanStretch, IsAutoFitting(), IsInputLocked(), IsLockedMax(), IsLockedMin(), ImPlotRange::Max, ImPlotRange::Min, and Range.
Referenced by ImPlot::UpdateInput().
IsRangeLocked()
bool ImPlotAxis::IsRangeLocked () const inline
Definition at line 902 of file implot_internal.h.
References HasRange, ImPlotCond_Always, and RangeCond.
Referenced by IsLockedMax(), IsLockedMin(), and ImPlot::ShowAxisContextMenu().
PixelSize()
float ImPlotAxis::PixelSize () const inline
Definition at line 802 of file implot_internal.h.
References ImAbs(), PixelMax, and PixelMin.
Referenced by GetAspect(), SetAspect(), and ImPlot::ShowAxisMetrics().
PixelsToPlot()
double ImPlotAxis::PixelsToPlot (float pix) const inline
Definition at line 850 of file implot_internal.h.
References ImPlotRange::Min, PixelMin, Range, ScaleMax, ScaleMin, ScaleToPixel, ImPlotRange::Size(), TransformData, and TransformInverse.
Referenced by ImPlot::EndPlot(), ImPlot::PixelsToPlot(), and ImPlot::UpdateInput().
PlotToPixels()
float ImPlotAxis::PlotToPixels (double plt) const inline
Definition at line 840 of file implot_internal.h.
References ImPlotRange::Min, PixelMin, Range, ScaleMax, ScaleMin, ScaleToPixel, ImPlotRange::Size(), TransformData, and TransformForward.
Referenced by ImPlot::EndPlot(), ImPlot::PlotToPixels(), and ImPlot::SetupFinish().
PullLinks()
void ImPlotAxis::PullLinks () inline
Definition at line 930 of file implot_internal.h.
References LinkedMax, LinkedMin, SetMax(), SetMin(), and SetRange().
Referenced by ImPlot::ApplyNextPlotData(), and ImPlot::SetupAxisLinks().
PushLinks()
void ImPlotAxis::PushLinks () inline
Definition at line 925 of file implot_internal.h.
References LinkedMax, LinkedMin, ImPlotRange::Max, ImPlotRange::Min, and Range.
Referenced by ImPlot::EndPlot().
Reset()
void ImPlotAxis::Reset () inline
Definition at line 718 of file implot_internal.h.
References ConstraintRange, ConstraintZoom, Enabled, FitExtents, FitThisFrame, Formatter, FormatterData, HasFormatSpec, ImPlotScale_Linear, LabelOffset, Locator, ImPlotRange::Max, ImPlotRange::Min, OrthoAxis, ImPlotTicker::Reset(), Scale, ShowDefaultTicks, Ticker, TransformData, TransformForward, and TransformInverse.
Referenced by ImPlot::BeginPlot().
SetAspect()
void ImPlotAxis::SetAspect (double unit_per_pix) inline
Definition at line 789 of file implot_internal.h.
References IsLocked(), IsLockedMax(), IsLockedMin(), ImPlotRange::Max, ImPlotRange::Min, PixelSize(), Range, SetRange(), and ImPlotRange::Size().
Referenced by ImPlot::EndPlot(), ImPlot::SetupFinish(), ImPlot::ShowAxisContextMenu(), and ImPlot::UpdateInput().
SetMax()
bool ImPlotAxis::SetMax (double _max, bool force = false) inline
Definition at line 757 of file implot_internal.h.
References ConstraintRange, ConstraintZoom, ImPlotTime::FromDouble(), ImConstrainInf(), ImConstrainNan(), IsLockedMax(), ImPlotRange::Max, ImPlotRange::Min, PickerTimeMax, Range, and UpdateTransformCache().
Referenced by PullLinks(), ImPlot::ShowAxisContextMenu(), and ImPlot::UpdateInput().
SetMin()
bool ImPlotAxis::SetMin (double _min, bool force = false) inline
Definition at line 738 of file implot_internal.h.
References ConstraintRange, ConstraintZoom, ImPlotTime::FromDouble(), ImConstrainInf(), ImConstrainNan(), IsLockedMin(), ImPlotRange::Max, ImPlotRange::Min, PickerTimeMin, Range, and UpdateTransformCache().
Referenced by PullLinks(), ImPlot::ShowAxisContextMenu(), and ImPlot::UpdateInput().
SetRange() [1/2]
void ImPlotAxis::SetRange (const ImPlotRange & range) inline
Definition at line 785 of file implot_internal.h.
References ImPlotRange::Max, ImPlotRange::Min, and SetRange().
SetRange() [2/2]
void ImPlotAxis::SetRange (double v1, double v2) inline
Definition at line 776 of file implot_internal.h.
References Constrain(), ImPlotTime::FromDouble(), ImMax(), ImMin(), ImPlotRange::Max, ImPlotRange::Min, PickerTimeMax, PickerTimeMin, Range, and UpdateTransformCache().
Referenced by ImPlot::ApplyNextPlotData(), PullLinks(), SetAspect(), SetRange(), ImPlot::SetupAxisLimits(), and ImPlot::ShowAxisContextMenu().
UpdateTransformCache()
void ImPlotAxis::UpdateTransformCache () inline
Definition at line 828 of file implot_internal.h.
References ImPlotRange::Max, ImPlotRange::Min, PixelMax, PixelMin, Range, ScaleMax, ScaleMin, ScaleToPixel, ImPlotRange::Size(), TransformData, and TransformForward.
Referenced by ApplyFit(), SetMax(), SetMin(), SetRange(), and ImPlot::SetupFinish().
WillRender()
bool ImPlotAxis::WillRender () const inline
Definition at line 896 of file implot_internal.h.
References Enabled, HasGridLines(), HasTickLabels(), and HasTickMarks().
Referenced by ImPlot::SetupFinish().
Member Data Documentation
ColorAct
ImU32 ImPlotAxis::ColorAct
Definition at line 680 of file implot_internal.h.
Referenced by ImPlotAxis(), ImPlot::SetupFinish(), and ImPlot::UpdateAxisColors().
ColorBg
ImU32 ImPlotAxis::ColorBg
Definition at line 680 of file implot_internal.h.
Referenced by ImPlotAxis(), ImPlot::SetupFinish(), and ImPlot::UpdateAxisColors().
ColorHiLi
ImU32 ImPlotAxis::ColorHiLi
Definition at line 680 of file implot_internal.h.
Referenced by ImPlot::BeginItem(), ImPlotAxis(), and ImPlot::SetupFinish().
ColorHov
ImU32 ImPlotAxis::ColorHov
Definition at line 680 of file implot_internal.h.
Referenced by ImPlot::EndPlot(), ImPlotAxis(), ImPlot::SetupFinish(), and ImPlot::UpdateAxisColors().
ColorMaj
ImU32 ImPlotAxis::ColorMaj
Definition at line 680 of file implot_internal.h.
Referenced by ImPlot::EndPlot(), ImPlotAxis(), ImPlot::SetupFinish(), and ImPlot::UpdateAxisColors().
ColorMin
ImU32 ImPlotAxis::ColorMin
Definition at line 680 of file implot_internal.h.
Referenced by ImPlot::EndPlot(), ImPlotAxis(), ImPlot::SetupFinish(), and ImPlot::UpdateAxisColors().
ColorTick
ImU32 ImPlotAxis::ColorTick
Definition at line 680 of file implot_internal.h.
Referenced by ImPlot::EndPlot(), ImPlotAxis(), and ImPlot::UpdateAxisColors().
ColorTxt
ImU32 ImPlotAxis::ColorTxt
Definition at line 680 of file implot_internal.h.
Referenced by ImPlotAxis(), ImPlot::SetupFinish(), and ImPlot::UpdateAxisColors().
ConstraintRange
ImPlotRange ImPlotAxis::ConstraintRange
Definition at line 655 of file implot_internal.h.
Referenced by Constrain(), ExtendFit(), ExtendFitWith(), ImPlotAxis(), IsPanLocked(), Reset(), SetMax(), SetMin(), ImPlot::SetupAxisLimitsConstraints(), and ImPlot::SetupAxisScale().
ConstraintZoom
ImPlotRange ImPlotAxis::ConstraintZoom
Definition at line 656 of file implot_internal.h.
Referenced by Constrain(), ImPlotAxis(), Reset(), SetMax(), SetMin(), and ImPlot::SetupAxisZoomConstraints().
Datum1
float ImPlotAxis::Datum1
Definition at line 676 of file implot_internal.h.
Referenced by ImPlot::EndPlot(), ImPlotAxis(), ImPlot::PadAndDatumAxesX(), ImPlot::PadAndDatumAxesY(), and ImPlot::SetupFinish().
Datum2
float ImPlotAxis::Datum2
Definition at line 676 of file implot_internal.h.
Referenced by ImPlotAxis(), ImPlot::PadAndDatumAxesX(), ImPlot::PadAndDatumAxesY(), and ImPlot::SetupFinish().
Enabled
bool ImPlotAxis::Enabled
Definition at line 682 of file implot_internal.h.
Referenced by ImPlot::ApplyNextPlotData(), ImPlot::BeginPlot(), ImPlotPlot::EnabledAxesX(), ImPlotPlot::EnabledAxesY(), ImPlot::EndPlot(), ImPlotAxis(), IsLockedMax(), IsLockedMin(), ImPlot::PadAndDatumAxesX(), ImPlot::PadAndDatumAxesY(), Reset(), ImPlot::SetAxes(), ImPlot::SetAxis(), ImPlot::SetupAxis(), ImPlot::SetupAxisFormat(), ImPlot::SetupAxisFormat(), ImPlot::SetupAxisLimits(), ImPlot::SetupAxisLimitsConstraints(), ImPlot::SetupAxisLinks(), ImPlot::SetupAxisScale(), ImPlot::SetupAxisScale(), ImPlot::SetupAxisTicks(), ImPlot::SetupAxisZoomConstraints(), ImPlot::SetupFinish(), ImPlot::ShowMetricsWindow(), ImPlot::ShowPlotContextMenu(), ImPlot::UpdateInput(), and WillRender().
FitExtents
ImPlotRange ImPlotAxis::FitExtents
Definition at line 653 of file implot_internal.h.
Referenced by ApplyFit(), ExtendFit(), ExtendFitWith(), ImPlotAxis(), and Reset().
FitThisFrame
bool ImPlotAxis::FitThisFrame
Definition at line 684 of file implot_internal.h.
Referenced by ImPlot::EndPlot(), ImPlotAxis(), Reset(), ImPlot::SetupFinish(), and ImPlot::UpdateInput().
Flags
ImPlotAxisFlags ImPlotAxis::Flags
Definition at line 648 of file implot_internal.h.
Referenced by CanInitFit(), ImPlot::EndPlot(), ExtendFitWith(), HasGridLines(), HasLabel(), HasMenus(), HasTickLabels(), HasTickMarks(), ImPlotAxis(), IsAutoFitting(), IsForeground(), IsInverted(), IsLockedMax(), IsLockedMin(), IsOpposite(), IsPanLocked(), ImPlot::SetupAxis(), ImPlot::SetupFinish(), ImPlot::ShowAxisContextMenu(), and ImPlot::ShowAxisMetrics().
FormatSpec
char ImPlotAxis::FormatSpec[16]
Definition at line 661 of file implot_internal.h.
Referenced by ImPlot::SetupAxisFormat(), ImPlot::SetupAxisTicks(), and ImPlot::SetupFinish().
Formatter
ImPlotFormatter ImPlotAxis::Formatter
Definition at line 659 of file implot_internal.h.
Referenced by ImPlotAxis(), ImPlot::LabelAxisValue(), Reset(), ImPlot::SetupAxisFormat(), ImPlot::SetupAxisTicks(), and ImPlot::SetupFinish().
FormatterData
void* ImPlotAxis::FormatterData
Definition at line 660 of file implot_internal.h.
Referenced by ImPlotAxis(), ImPlot::LabelAxisValue(), Reset(), ImPlot::SetupAxisFormat(), ImPlot::SetupAxisTicks(), and ImPlot::SetupFinish().
HasFormatSpec
bool ImPlotAxis::HasFormatSpec
Definition at line 686 of file implot_internal.h.
Referenced by ImPlotAxis(), Reset(), ImPlot::SetupAxisFormat(), ImPlot::SetupAxisTicks(), and ImPlot::SetupFinish().
HasRange
bool ImPlotAxis::HasRange
Definition at line 685 of file implot_internal.h.
Referenced by ImPlot::ApplyNextPlotData(), CanInitFit(), ImPlotAxis(), IsRangeLocked(), ImPlot::SetupAxisLimits(), ImPlot::SetupFinish(), and ImPlot::ShowAxisMetrics().
Held
bool ImPlotAxis::Held
Definition at line 689 of file implot_internal.h.
Referenced by ImPlot::EndPlot(), ImPlotAxis(), ImPlot::SetupFinish(), ImPlot::ShowAxisMetrics(), and ImPlot::UpdateInput().
Hovered
bool ImPlotAxis::Hovered
Definition at line 688 of file implot_internal.h.
Referenced by ImPlot::EndPlot(), ImPlotAxis(), ImPlot::IsAxisHovered(), ImPlot::SetupFinish(), ImPlot::ShowAxisMetrics(), and ImPlot::UpdateInput().
HoverRect
ImRect ImPlotAxis::HoverRect
Definition at line 678 of file implot_internal.h.
Referenced by ImPlot::BeginDragDropSourceAxis(), ImPlot::BeginDragDropTargetAxis(), ImPlot::SetupFinish(), ImPlot::ShowMetricsWindow(), and ImPlot::UpdateInput().
ID
ImGuiID ImPlotAxis::ID
Definition at line 647 of file implot_internal.h.
Referenced by ImPlot::BeginDragDropSourceAxis(), ImPlot::BeginDragDropTargetAxis(), ImPlotAxis(), ImPlot::SetupAxis(), ImPlot::ShowAxisMetrics(), ImPlot::ShowMetricsWindow(), and ImPlot::UpdateInput().
LabelOffset
int ImPlotAxis::LabelOffset
Definition at line 679 of file implot_internal.h.
Referenced by ImPlotPlot::GetAxisLabel(), HasLabel(), ImPlotAxis(), Reset(), ImPlotPlot::SetAxisLabel(), ImPlot::ShowAxisContextMenu(), and ImPlot::ShowAxisMetrics().
LinkedMax
double* ImPlotAxis::LinkedMax
Definition at line 665 of file implot_internal.h.
Referenced by ImPlot::ApplyNextPlotData(), CanInitFit(), ImPlotAxis(), PullLinks(), PushLinks(), ImPlot::SetupAxisLinks(), and ImPlot::ShowAxisMetrics().
LinkedMin
double* ImPlotAxis::LinkedMin
Definition at line 664 of file implot_internal.h.
Referenced by ImPlot::ApplyNextPlotData(), CanInitFit(), ImPlotAxis(), PullLinks(), PushLinks(), ImPlot::SetupAxisLinks(), and ImPlot::ShowAxisMetrics().
Locator
ImPlotLocator ImPlotAxis::Locator
Definition at line 662 of file implot_internal.h.
Referenced by ImPlotAxis(), ImPlot::LabelAxisValue(), Reset(), ImPlot::SetupAxisScale(), and ImPlot::SetupFinish().
OrthoAxis
ImPlotAxis* ImPlotAxis::OrthoAxis
Definition at line 654 of file implot_internal.h.
Referenced by ImPlot::EndPlot(), ImPlotAxis(), Reset(), ImPlot::SetupFinish(), ImPlot::ShowAxisMetrics(), ImPlot::ShowPlotContextMenu(), and ImPlot::UpdateInput().
PickerLevel
int ImPlotAxis::PickerLevel
Definition at line 667 of file implot_internal.h.
Referenced by ImPlotAxis(), and ImPlot::ShowAxisContextMenu().
PickerTimeMax
ImPlotTime ImPlotAxis::PickerTimeMax
Definition at line 668 of file implot_internal.h.
Referenced by SetMax(), SetRange(), and ImPlot::ShowAxisContextMenu().
PickerTimeMin
ImPlotTime ImPlotAxis::PickerTimeMin
Definition at line 668 of file implot_internal.h.
Referenced by SetMin(), SetRange(), and ImPlot::ShowAxisContextMenu().
PixelMax
float ImPlotAxis::PixelMax
Definition at line 673 of file implot_internal.h.
Referenced by ImPlotAxis(), PixelSize(), ImPlot::SetupFinish(), ImPlot::ShowAxisMetrics(), and UpdateTransformCache().
PixelMin
float ImPlotAxis::PixelMin
Definition at line 673 of file implot_internal.h.
Referenced by ImPlotAxis(), PixelSize(), PixelsToPlot(), PlotToPixels(), ImPlot::SetupFinish(), ImPlot::ShowAxisMetrics(), and UpdateTransformCache().
PreviousFlags
ImPlotAxisFlags ImPlotAxis::PreviousFlags
Definition at line 649 of file implot_internal.h.
Referenced by ImPlotAxis(), and ImPlot::SetupAxis().
Range
ImPlotRange ImPlotAxis::Range
Definition at line 650 of file implot_internal.h.
Referenced by ApplyFit(), ImPlot::AxisPrecision(), Constrain(), ImPlot::EndPlot(), ExtendFitWith(), GetAspect(), ImPlot::GetPlotLimits(), ImPlotAxis(), IsPanLocked(), ImPlot::LabelAxisValue(), PixelsToPlot(), PlotToPixels(), PushLinks(), SetAspect(), SetMax(), SetMin(), SetRange(), ImPlot::SetupFinish(), ImPlot::ShowAxisContextMenu(), ImPlot::ShowAxisMetrics(), and UpdateTransformCache().
RangeCond
ImPlotCond ImPlotAxis::RangeCond
Definition at line 651 of file implot_internal.h.
Referenced by ImPlot::ApplyNextPlotData(), IsRangeLocked(), and ImPlot::SetupAxisLimits().
Scale
ImPlotScale ImPlotAxis::Scale
Definition at line 652 of file implot_internal.h.
Referenced by ImPlotAxis(), ImPlot::PadAndDatumAxesX(), Reset(), ImPlot::SetupAxisScale(), ImPlot::SetupAxisScale(), and ImPlot::ShowAxisContextMenu().
ScaleMax
double ImPlotAxis::ScaleMax
Definition at line 674 of file implot_internal.h.
Referenced by PixelsToPlot(), PlotToPixels(), ImPlot::ShowAxisMetrics(), and UpdateTransformCache().
ScaleMin
double ImPlotAxis::ScaleMin
Definition at line 674 of file implot_internal.h.
Referenced by PixelsToPlot(), PlotToPixels(), and UpdateTransformCache().
ScaleToPixel
double ImPlotAxis::ScaleToPixel
Definition at line 675 of file implot_internal.h.
Referenced by PixelsToPlot(), PlotToPixels(), ImPlot::ShowAxisMetrics(), and UpdateTransformCache().
ShowDefaultTicks
bool ImPlotAxis::ShowDefaultTicks
Definition at line 687 of file implot_internal.h.
Referenced by ImPlotAxis(), Reset(), ImPlot::SetupAxisTicks(), and ImPlot::SetupFinish().
Ticker
ImPlotTicker ImPlotAxis::Ticker
Definition at line 658 of file implot_internal.h.
Referenced by ImPlot::AxisPrecision(), ImPlot::EndPlot(), ImPlot::PadAndDatumAxesX(), ImPlot::PadAndDatumAxesY(), Reset(), ImPlot::SetupAxisScale(), ImPlot::SetupAxisTicks(), ImPlot::SetupFinish(), and ImPlot::ShowAxisMetrics().
TransformData
void* ImPlotAxis::TransformData
Definition at line 672 of file implot_internal.h.
Referenced by ImPlotAxis(), PixelsToPlot(), PlotToPixels(), Reset(), ImPlot::SetupAxisScale(), ImPlot::SetupAxisScale(), and UpdateTransformCache().
TransformForward
ImPlotTransform ImPlotAxis::TransformForward
Definition at line 670 of file implot_internal.h.
Referenced by ImPlotAxis(), PlotToPixels(), Reset(), ImPlot::SetupAxisScale(), ImPlot::SetupAxisScale(), and UpdateTransformCache().
TransformInverse
ImPlotTransform ImPlotAxis::TransformInverse
Definition at line 671 of file implot_internal.h.
Referenced by ImPlotAxis(), PixelsToPlot(), Reset(), ImPlot::SetupAxisScale(), and ImPlot::SetupAxisScale().
Vertical
bool ImPlotAxis::Vertical
Definition at line 683 of file implot_internal.h.
Referenced by ImPlot::EndPlot(), ImPlotPlot::ImPlotPlot(), and ImPlot::LabelAxisValue().
The documentation for this struct was generated from the following file:
examples/implot/implot_internal.h