SignalProcessing: ExampleDualListBox Struct Reference
ExampleDualListBox Struct Reference
Public Member Functions
void MoveAll (int src, int dst)
void MoveSelected (int src, int dst)
void ApplySelectionRequests (ImGuiMultiSelectIO *ms_io, int side)
void SortItems (int n)
void Show ()
Static Public Member Functions
static int CompareItemsByValue (const void *lhs, const void *rhs)
Public Attributes
ImVector< ImGuiID > Items [2]
ImGuiSelectionBasicStorage Selections [2]
bool OptKeepSorted = true
Detailed Description
Definition at line 2498 of file imgui_demo.cpp.
Member Function Documentation
ApplySelectionRequests()
void ExampleDualListBox::ApplySelectionRequests (ImGuiMultiSelectIO * ms_io, int side) inline
Definition at line 2530 of file imgui_demo.cpp.
References ImGuiSelectionBasicStorage::AdapterIndexToStorageId, ImGuiSelectionBasicStorage::ApplyRequests(), ImVector< T >::Data, Items, Selections, and ImGuiSelectionBasicStorage::UserData.
Referenced by Show().
CompareItemsByValue()
static int ExampleDualListBox::CompareItemsByValue (const void * lhs, const void * rhs) inline static
Definition at line 2537 of file imgui_demo.cpp.
Referenced by SortItems().
MoveAll()
void ExampleDualListBox::MoveAll (int src, int dst) inline
Definition at line 2504 of file imgui_demo.cpp.
References ImVector< T >::clear(), ImGuiSelectionBasicStorage::Clear(), IM_ASSERT, Items, Selections, SortItems(), and ImGuiSelectionBasicStorage::Swap().
Referenced by Show().
MoveSelected()
void ExampleDualListBox::MoveSelected (int src, int dst) inline
Definition at line 2514 of file imgui_demo.cpp.
References ImGuiSelectionBasicStorage::Clear(), ImVector< T >::erase(), Items, OptKeepSorted, ImVector< T >::push_back(), Selections, ImVector< T >::Size, SortItems(), and ImGuiSelectionBasicStorage::Swap().
Referenced by Show().
Show()
void ExampleDualListBox::Show () inline
Definition at line 2547 of file imgui_demo.cpp.
References ApplySelectionRequests(), ImGui::BeginChild(), ImGui::BeginMultiSelect(), ImGui::BeginTable(), ImGui::Button(), ImGuiSelectionBasicStorage::Contains(), ImGui::EndChild(), ImGui::EndMultiSelect(), ImGui::EndTable(), ExampleNames, ImGui::GetFontSize(), ImGui::GetFrameHeight(), ImGui::GetFrameHeightWithSpacing(), ImGui::GetTextLineHeightWithSpacing(), ImGui::GetWindowSize(), ImGuiChildFlags_FrameStyle, ImGuiChildFlags_ResizeY, ImGuiKey_Enter, ImGuiKey_KeypadEnter, ImGuiMultiSelectFlags_None, ImGuiSelectableFlags_AllowDoubleClick, ImGuiTableColumnFlags_WidthFixed, ImGuiTableColumnFlags_WidthStretch, ImGuiTableFlags_None, ImGui::IsItemFocused(), ImGui::IsKeyPressed(), ImGui::IsMouseDoubleClicked(), Items, MoveAll(), MoveSelected(), ImGui::NewLine(), ImGui::Selectable(), Selections, ImGui::SetNextItemSelectionUserData(), ImGui::SetNextWindowContentSize(), ImGui::SetNextWindowSizeConstraints(), ImVector< T >::Size, ImGuiSelectionBasicStorage::Size, ImGui::TableNextRow(), ImGui::TableSetColumnIndex(), ImGui::TableSetupColumn(), ImGui::Text(), and ImVec2::y.
Referenced by DemoWindowWidgetsSelectionAndMultiSelect().
SortItems()
void ExampleDualListBox::SortItems (int n) inline
Definition at line 2543 of file imgui_demo.cpp.
References CompareItemsByValue(), and Items.
Referenced by MoveAll(), and MoveSelected().
Member Data Documentation
Items
ImVector<ImGuiID> ExampleDualListBox::Items[2]
Definition at line 2500 of file imgui_demo.cpp.
Referenced by ApplySelectionRequests(), DemoWindowWidgetsSelectionAndMultiSelect(), MoveAll(), MoveSelected(), Show(), and SortItems().
OptKeepSorted
bool ExampleDualListBox::OptKeepSorted = true
Definition at line 2502 of file imgui_demo.cpp.
Referenced by MoveSelected().
Selections
ImGuiSelectionBasicStorage ExampleDualListBox::Selections[2]
Definition at line 2501 of file imgui_demo.cpp.
Referenced by ApplySelectionRequests(), MoveAll(), MoveSelected(), and Show().
The documentation for this struct was generated from the following file:
examples/imgui/imgui_demo.cpp