SignalProcessing: ImPlot::ScrollingBuffer Struct Reference
ImPlot::ScrollingBuffer Struct Reference
Public Member Functions
ScrollingBuffer (int max_size=2000)
void AddPoint (float x, float y)
void Erase ()
Public Attributes
int MaxSize
int Offset
ImVector< ImVec2 > Data
Detailed Description
Definition at line 126 of file implot_demo.cpp.
Constructor & Destructor Documentation
ScrollingBuffer()
ImPlot::ScrollingBuffer::ScrollingBuffer (int max_size = 2000) inline
Definition at line 130 of file implot_demo.cpp.
References Data, MaxSize, Offset, and ImVector< T >::reserve().
Member Function Documentation
AddPoint()
void ImPlot::ScrollingBuffer::AddPoint (float x, float y) inline
Definition at line 135 of file implot_demo.cpp.
References Data, MaxSize, Offset, ImVector< T >::push_back(), ImVector< T >::size(), ImPlot::x, and ImPlot::y.
Referenced by ImPlot::Demo_DigitalPlots(), and ImPlot::Demo_RealtimePlots().
Erase()
void ImPlot::ScrollingBuffer::Erase () inline
Definition at line 143 of file implot_demo.cpp.
References Data, Offset, ImVector< T >::shrink(), and ImVector< T >::size().
Member Data Documentation
Data
ImVector<ImVec2> ImPlot::ScrollingBuffer::Data
Definition at line 129 of file implot_demo.cpp.
Referenced by AddPoint(), ImPlot::Demo_RealtimePlots(), Erase(), and ScrollingBuffer().
MaxSize
int ImPlot::ScrollingBuffer::MaxSize
Definition at line 127 of file implot_demo.cpp.
Referenced by AddPoint(), and ScrollingBuffer().
Offset
int ImPlot::ScrollingBuffer::Offset
Definition at line 128 of file implot_demo.cpp.
Referenced by AddPoint(), ImPlot::Demo_DigitalPlots(), ImPlot::Demo_RealtimePlots(), Erase(), and ScrollingBuffer().
The documentation for this struct was generated from the following file:
examples/implot/implot_demo.cpp