SignalProcessing: ExampleAssetsBrowser Struct Reference
ExampleAssetsBrowser Struct Reference
Public Member Functions
ExampleAssetsBrowser ()
void AddItems (int count)
void ClearItems ()
void UpdateLayoutSizes (float avail_width)
void Draw (const char *title, bool *p_open)
Public Attributes
bool ShowTypeOverlay = true
bool AllowSorting = true
bool AllowDragUnselected = false
bool AllowBoxSelect = true
float IconSize = 32.0f
int IconSpacing = 10
int IconHitSpacing = 4
bool StretchSpacing = true
ImVector< ExampleAsset > Items
ExampleSelectionWithDeletion Selection
ImGuiID NextItemId = 0
bool RequestDelete = false
bool RequestSort = false
float ZoomWheelAccum = 0.0f
ImVec2 LayoutItemSize
ImVec2 LayoutItemStep
float LayoutItemSpacing = 0.0f
float LayoutSelectableSpacing = 0.0f
float LayoutOuterPadding = 0.0f
int LayoutColumnCount = 0
int LayoutLineCount = 0
Detailed Description
Definition at line 10542 of file imgui_demo.cpp.
Constructor & Destructor Documentation
ExampleAssetsBrowser()
ExampleAssetsBrowser::ExampleAssetsBrowser () inline
Definition at line 10572 of file imgui_demo.cpp.
References AddItems().
Member Function Documentation
AddItems()
void ExampleAssetsBrowser::AddItems (int count) inline
Definition at line 10576 of file imgui_demo.cpp.
References Items, NextItemId, ImVector< T >::push_back(), RequestSort, ImVector< T >::reserve(), and ImVector< T >::Size.
Referenced by Draw(), and ExampleAssetsBrowser().
ClearItems()
void ExampleAssetsBrowser::ClearItems () inline
Definition at line 10585 of file imgui_demo.cpp.
References ImVector< T >::clear(), ImGuiSelectionBasicStorage::Clear(), Items, and Selection.
Referenced by Draw().
Draw()
void ExampleAssetsBrowser::Draw (const char * title, bool * p_open) inline
Definition at line 10614 of file imgui_demo.cpp.
References ImGuiSelectionBasicStorage::AdapterIndexToStorageId, AddItems(), ImDrawList::AddRectFilled(), ImDrawList::AddText(), AllowBoxSelect, AllowDragUnselected, AllowSorting, ExampleSelectionWithDeletion::ApplyDeletionPostLoop(), ExampleSelectionWithDeletion::ApplyDeletionPreLoop(), ImGuiSelectionBasicStorage::ApplyRequests(), ImGui::Begin(), ImGuiListClipper::Begin(), ImGui::BeginChild(), ImGui::BeginDragDropSource(), ImGui::BeginMenu(), ImGui::BeginMenuBar(), ImGui::BeginMultiSelect(), ImGui::BeginPopupContextWindow(), ImGui::BeginTable(), ImGui::CalcTextSize(), ImGui::Checkbox(), ClearItems(), ImGuiSelectionBasicStorage::Contains(), ImVector< T >::Data, ImGuiPayload::DataSize, ImGuiListClipper::DisplayEnd, ImGuiListClipper::DisplayStart, ImGui::End(), ImGuiListClipper::End(), ImGui::EndChild(), ImGui::EndDragDropSource(), ImGui::EndMenu(), ImGui::EndMenuBar(), ImGui::EndMultiSelect(), ImGui::EndPopup(), ImGui::EndTable(), ImGui::GetColorU32(), ImGui::GetContentRegionAvail(), ImGui::GetCursorScreenPos(), ImGui::GetDragDropPayload(), ImGui::GetFontSize(), ImGui::GetFrameHeight(), ImGui::GetIO(), ImGuiSelectionBasicStorage::GetNextSelectedItem(), ImGui::GetStyle(), ImGui::GetTextLineHeightWithSpacing(), ImGui::GetWindowDrawList(), ImGui::GetWindowPos(), HelpMarker(), IconHitSpacing, IconSize, IconSpacing, ExampleAsset::ID, IM_ARRAYSIZE, IM_CLAMP, IM_COL32, IM_MIN, ImGuiChildFlags_Borders, ImGuiCol_Text, ImGuiCol_TextDisabled, ImGuiCond_FirstUseEver, ImGuiInputFlags_Repeat, ImGuiKey_Delete, ImGuiMod_Ctrl, ImGuiMultiSelectFlags_BoxSelect2d, ImGuiMultiSelectFlags_ClearOnClickVoid, ImGuiMultiSelectFlags_ClearOnEscape, ImGuiMultiSelectFlags_NavWrapX, ImGuiMultiSelectFlags_SelectOnClickRelease, ImGuiSelectableFlags_None, ImGuiStyleVar_ItemSpacing, ImGuiTableFlags_Borders, ImGuiTableFlags_SizingFixedFit, ImGuiTableFlags_Sortable, ImGuiTableFlags_SortMulti, ImGuiWindowFlags_MenuBar, ImGuiWindowFlags_NoMove, ImGuiListClipper::IncludeItemByIndex(), ImGui::IsAnyItemActive(), ImGui::IsItemToggledSelection(), ImGui::IsKeyDown(), ImGui::IsRectVisible(), ImGui::IsWindowAppearing(), ImGui::IsWindowHovered(), Items, LayoutColumnCount, LayoutItemSize, LayoutItemSpacing, LayoutItemStep, LayoutLineCount, LayoutOuterPadding, LayoutSelectableSpacing, ImGui::MenuItem(), ImGuiIO::MousePos, ImGuiIO::MouseWheel, ImGui::PopID(), ImGui::PopItemWidth(), ImGui::PopStyleVar(), ImVector< T >::push_back(), ImGui::PushID(), ImGui::PushItemWidth(), ImGui::PushStyleVar(), ImGuiMultiSelectIO::RangeSrcItem, RequestDelete, RequestSort, ImGui::SameLine(), ImGui::Selectable(), Selection, ImGui::Separator(), ImGui::SeparatorText(), ImGui::SetCursorScreenPos(), ImGui::SetDragDropPayload(), ImGui::SetKeyboardFocusHere(), ImGui::SetNextItemSelectionUserData(), ImGui::SetNextWindowContentSize(), ImGui::SetNextWindowSize(), ImGui::SetScrollY(), ImGui::Shortcut(), ShowTypeOverlay, ImVector< T >::Size, ImGuiSelectionBasicStorage::Size, ImVector< T >::size_in_bytes(), ImGui::SliderFloat(), ImGui::SliderInt(), ExampleAsset::SortWithSortSpecs(), ImGuiTableSortSpecs::SpecsDirty, ImGuiListClipper::Step(), StretchSpacing, ImGui::TableGetSortSpecs(), ImGui::TableHeadersRow(), ImGui::TableSetupColumn(), ImGui::Text(), ExampleAsset::Type, UpdateLayoutSizes(), ImGuiSelectionBasicStorage::UserData, ImGuiStyle::WindowPadding, ImVec2::x, ImVec2::y, and ZoomWheelAccum.
Referenced by ShowExampleAppAssetsBrowser().
UpdateLayoutSizes()
void ExampleAssetsBrowser::UpdateLayoutSizes (float avail_width) inline
Definition at line 10593 of file imgui_demo.cpp.
References IconHitSpacing, IconSize, IconSpacing, IM_MAX, Items, LayoutColumnCount, LayoutItemSize, LayoutItemSpacing, LayoutItemStep, LayoutLineCount, LayoutOuterPadding, LayoutSelectableSpacing, ImVector< T >::Size, StretchSpacing, ImVec2::x, and ImVec2::y.
Referenced by Draw().
Member Data Documentation
AllowBoxSelect
bool ExampleAssetsBrowser::AllowBoxSelect = true
Definition at line 10548 of file imgui_demo.cpp.
Referenced by Draw().
AllowDragUnselected
bool ExampleAssetsBrowser::AllowDragUnselected = false
Definition at line 10547 of file imgui_demo.cpp.
Referenced by Draw().
AllowSorting
bool ExampleAssetsBrowser::AllowSorting = true
Definition at line 10546 of file imgui_demo.cpp.
Referenced by Draw().
IconHitSpacing
int ExampleAssetsBrowser::IconHitSpacing = 4
Definition at line 10551 of file imgui_demo.cpp.
Referenced by Draw(), and UpdateLayoutSizes().
IconSize
float ExampleAssetsBrowser::IconSize = 32.0f
Definition at line 10549 of file imgui_demo.cpp.
Referenced by Draw(), and UpdateLayoutSizes().
IconSpacing
int ExampleAssetsBrowser::IconSpacing = 10
Definition at line 10550 of file imgui_demo.cpp.
Referenced by Draw(), and UpdateLayoutSizes().
Items
ImVector<ExampleAsset> ExampleAssetsBrowser::Items
Definition at line 10555 of file imgui_demo.cpp.
Referenced by AddItems(), ClearItems(), Draw(), and UpdateLayoutSizes().
LayoutColumnCount
int ExampleAssetsBrowser::LayoutColumnCount = 0
Definition at line 10568 of file imgui_demo.cpp.
Referenced by Draw(), and UpdateLayoutSizes().
LayoutItemSize
ImVec2 ExampleAssetsBrowser::LayoutItemSize
Definition at line 10563 of file imgui_demo.cpp.
Referenced by Draw(), and UpdateLayoutSizes().
LayoutItemSpacing
float ExampleAssetsBrowser::LayoutItemSpacing = 0.0f
Definition at line 10565 of file imgui_demo.cpp.
Referenced by Draw(), and UpdateLayoutSizes().
LayoutItemStep
ImVec2 ExampleAssetsBrowser::LayoutItemStep
Definition at line 10564 of file imgui_demo.cpp.
Referenced by Draw(), and UpdateLayoutSizes().
LayoutLineCount
int ExampleAssetsBrowser::LayoutLineCount = 0
Definition at line 10569 of file imgui_demo.cpp.
Referenced by Draw(), and UpdateLayoutSizes().
LayoutOuterPadding
float ExampleAssetsBrowser::LayoutOuterPadding = 0.0f
Definition at line 10567 of file imgui_demo.cpp.
Referenced by Draw(), and UpdateLayoutSizes().
LayoutSelectableSpacing
float ExampleAssetsBrowser::LayoutSelectableSpacing = 0.0f
Definition at line 10566 of file imgui_demo.cpp.
Referenced by Draw(), and UpdateLayoutSizes().
NextItemId
ImGuiID ExampleAssetsBrowser::NextItemId = 0
Definition at line 10557 of file imgui_demo.cpp.
Referenced by AddItems().
RequestDelete
bool ExampleAssetsBrowser::RequestDelete = false
Definition at line 10558 of file imgui_demo.cpp.
Referenced by Draw().
RequestSort
bool ExampleAssetsBrowser::RequestSort = false
Definition at line 10559 of file imgui_demo.cpp.
Referenced by AddItems(), and Draw().
Selection
ExampleSelectionWithDeletion ExampleAssetsBrowser::Selection
Definition at line 10556 of file imgui_demo.cpp.
Referenced by ClearItems(), and Draw().
ShowTypeOverlay
bool ExampleAssetsBrowser::ShowTypeOverlay = true
Definition at line 10545 of file imgui_demo.cpp.
Referenced by Draw().
StretchSpacing
bool ExampleAssetsBrowser::StretchSpacing = true
Definition at line 10552 of file imgui_demo.cpp.
Referenced by Draw(), and UpdateLayoutSizes().
ZoomWheelAccum
float ExampleAssetsBrowser::ZoomWheelAccum = 0.0f
Definition at line 10560 of file imgui_demo.cpp.
Referenced by Draw().
The documentation for this struct was generated from the following file:
examples/imgui/imgui_demo.cpp