SignalProcessing: ImFont Struct Reference
ImFont Struct Reference
#include <imgui.h>
Public Member Functions
ImFont ()
~ImFont ()
bool IsGlyphInFont (ImWchar c)
bool IsLoaded () const
const char * GetDebugName () const
ImFontBaked * GetFontBaked (float font_size, float density=-1.0f)
ImVec2 CalcTextSizeA (float size, float max_width, float wrap_width, const char *text_begin, const char *text_end=NULL, const char **out_remaining=NULL)
const char * CalcWordWrapPosition (float size, const char *text, const char *text_end, float wrap_width)
void RenderChar (ImDrawList *draw_list, float size, const ImVec2 &pos, ImU32 col, ImWchar c, const ImVec4 *cpu_fine_clip=NULL)
void RenderText (ImDrawList *draw_list, float size, const ImVec2 &pos, ImU32 col, const ImVec4 &clip_rect, const char *text_begin, const char *text_end, float wrap_width=0.0f, ImDrawTextFlags flags=0)
const char * CalcWordWrapPositionA (float scale, const char *text, const char *text_end, float wrap_width)
void ClearOutputData ()
void AddRemapChar (ImWchar from_codepoint, ImWchar to_codepoint)
bool IsGlyphRangeUnused (unsigned int c_begin, unsigned int c_last)
Public Attributes
ImFontBaked * LastBaked
ImFontAtlas * OwnerAtlas
ImFontFlags Flags
float CurrentRasterizerDensity
ImGuiID FontId
float LegacySize
ImVector< ImFontConfig * > Sources
ImWchar EllipsisChar
ImWchar FallbackChar
ImU8 Used8kPagesMap [(0xFFFF+1)/8192/8]
bool EllipsisAutoBake
ImGuiStorage RemapPairs
float Scale
Detailed Description
Definition at line 3830 of file imgui.h.
Constructor & Destructor Documentation
ImFont()
ImFont::ImFont ()
Definition at line 5091 of file imgui_draw.cpp.
References Scale.
~ImFont()
ImFont::~ImFont ()
Definition at line 5099 of file imgui_draw.cpp.
References ClearOutputData().
Member Function Documentation
AddRemapChar()
void ImFont::AddRemapChar (ImWchar from_codepoint, ImWchar to_codepoint)
Definition at line 5216 of file imgui_draw.cpp.
References RemapPairs, and ImGuiStorage::SetInt().
CalcTextSizeA()
ImVec2 ImFont::CalcTextSizeA (float size, float max_width, float wrap_width, const char * text_begin, const char * text_end = NULL, const char ** out_remaining = NULL)
Definition at line 5576 of file imgui_draw.cpp.
References ImDrawTextFlags_None, and ImFontCalcTextSizeEx().
Referenced by ImGui::CalcTextSize(), and ImGui::RenderTextEllipsis().
CalcWordWrapPosition()
const char * ImFont::CalcWordWrapPosition (float size, const char * text, const char * text_end, float wrap_width)
Definition at line 5480 of file imgui_draw.cpp.
References ImDrawTextFlags_None, and ImFontCalcWordWrapPositionEx().
CalcWordWrapPositionA()
const char * ImFont::CalcWordWrapPositionA (float scale, const char * text, const char * text_end, float wrap_width) inline
Definition at line 3868 of file imgui.h.
ClearOutputData()
void ImFont::ClearOutputData ()
Definition at line 5104 of file imgui_draw.cpp.
References ImFontAtlasFontDiscardBakes(), LastBaked, OwnerAtlas, and Used8kPagesMap.
Referenced by ImFontAtlasFontDestroyOutput(), ImFontAtlasFontSourceAddToFont(), and ~ImFont().
GetDebugName()
const char * ImFont::GetDebugName () const inline
Definition at line 3857 of file imgui.h.
References ImVector< T >::Size.
Referenced by ImGui::DebugNodeFont(), ImFontAtlasBakedDiscard(), and ImGui::ShowFontSelector().
GetFontBaked()
ImFontBaked * ImFont::GetFontBaked (float font_size, float density = -1.0f)
Definition at line 5305 of file imgui_draw.cpp.
References ImFontAtlas::Builder, CurrentRasterizerDensity, ImFontAtlasBuilder::FrameCount, ImGui::GetRoundedFontSize(), ImFontAtlasBakedGetOrAdd(), LastBaked, ImFontBaked::LastUsedFrame, OwnerAtlas, ImFontBaked::RasterizerDensity, and ImFontBaked::Size.
Referenced by ImFontAtlas::AddCustomRectFontGlyphForSize(), ImPlot::AddTextVertical(), ImFontCalcTextSizeEx(), ImFontCalcWordWrapPositionEx(), RenderChar(), RenderText(), ImGui::RenderTextEllipsis(), and ImGui::UpdateCurrentFontSize().
IsGlyphInFont()
bool ImFont::IsGlyphInFont (ImWchar c)
Definition at line 5267 of file imgui_draw.cpp.
References ImFontAtlas::FontLoader, ImFontLoader::FontSrcContainsGlyph, ImFontAtlas_FontHookRemapCodepoint(), OwnerAtlas, and Sources.
Referenced by ImFontAtlasBuildSetupFontSpecialGlyphs().
IsGlyphRangeUnused()
bool ImFont::IsGlyphRangeUnused (unsigned int c_begin, unsigned int c_last)
Definition at line 5115 of file imgui_draw.cpp.
References Used8kPagesMap.
Referenced by ImGui::DebugNodeFontGlyphesForSrcMask().
IsLoaded()
bool ImFont::IsLoaded () const inline
Definition at line 3856 of file imgui.h.
Referenced by ImGui::SetCurrentFont(), and ImGui::UpdateFontsNewFrame().
RenderChar()
void ImFont::RenderChar (ImDrawList * draw_list, float size, const ImVec2 & pos, ImU32 col, ImWchar c, const ImVec4 * cpu_fine_clip = NULL)
Definition at line 5582 of file imgui_draw.cpp.
References ImFontGlyph::Colored, ImFontBaked::FindGlyph(), GetFontBaked(), IM_TRUNC, ImDrawList::PrimRectUV(), ImDrawList::PrimReserve(), ImFontBaked::Size, ImFontGlyph::U0, ImFontGlyph::U1, ImFontGlyph::V0, ImFontGlyph::V1, ImFontGlyph::Visible, ImVec4::w, ImVec2::x, ImVec4::x, ImFontGlyph::X0, ImFontGlyph::X1, ImVec2::y, ImVec4::y, ImFontGlyph::Y0, ImFontGlyph::Y1, and ImVec4::z.
Referenced by ImGui::DebugNodeFontGlyphesForSrcMask(), and ImGui::RenderTextEllipsis().
RenderText()
void ImFont::RenderText (ImDrawList * draw_list, float size, const ImVec2 & pos, ImU32 col, const ImVec4 & clip_rect, const char * text_begin, const char * text_end, float wrap_width = 0.0f, ImDrawTextFlags flags = 0)
Definition at line 5622 of file imgui_draw.cpp.
References ImDrawList::_IdxWritePtr, ImDrawList::_VtxCurrentIdx, ImDrawList::_VtxWritePtr, ImDrawList::AddDrawCmd(), ImFontGlyph::AdvanceX, ImDrawList::CmdBuffer, ImDrawVert::col, ImFontGlyph::Colored, ImVector< T >::Data, ImFontBaked::FindGlyph(), GetFontBaked(), ImDrawList::IdxBuffer, IM_ASSERT, IM_TRUNC, ImDrawTextFlags_CpuFineClip, ImFontCalcWordWrapPositionEx(), ImMemchr, ImStrlen, ImTextCalcWordWrapNextLineStart(), ImTextCharFromUtf8(), ImVector< T >::pop_back(), ImDrawVert::pos, ImDrawList::PrimReserve(), ImDrawList::PrimUnreserve(), ImVector< T >::Size, ImFontBaked::Size, ImFontGlyph::U0, ImFontGlyph::U1, ImDrawVert::uv, ImFontGlyph::V0, ImFontGlyph::V1, ImFontGlyph::Visible, ImDrawList::VtxBuffer, ImVec4::w, ImVec2::x, ImVec4::x, ImFontGlyph::X0, ImFontGlyph::X1, ImVec2::y, ImVec4::y, ImFontGlyph::Y0, ImFontGlyph::Y1, and ImVec4::z.
Referenced by ImDrawList::AddText(), and ImGui::InputTextEx().
Member Data Documentation
CurrentRasterizerDensity
float ImFont::CurrentRasterizerDensity
Definition at line 3836 of file imgui.h.
Referenced by ImFontAtlas::AddFont(), GetFontBaked(), and ImGui::UpdateCurrentFontSize().
EllipsisAutoBake
bool ImFont::EllipsisAutoBake
Definition at line 3846 of file imgui.h.
Referenced by ImFontAtlasBuildSetupFontSpecialGlyphs(), and ImFontBaked_BuildLoadGlyph().
EllipsisChar
ImWchar ImFont::EllipsisChar
Definition at line 3843 of file imgui.h.
Referenced by ImGui::DebugNodeFont(), ImFontAtlasBakedDiscardFontGlyph(), ImFontAtlasBuildSetupFontBakedEllipsis(), ImFontAtlasBuildSetupFontSpecialGlyphs(), ImFontBaked_BuildLoadGlyph(), and ImGui::RenderTextEllipsis().
FallbackChar
ImWchar ImFont::FallbackChar
Definition at line 3844 of file imgui.h.
Referenced by ImGui::DebugNodeFont(), ImFontAtlasBakedDiscardFontGlyph(), ImFontAtlasBuildSetupFontBakedFallback(), and ImFontAtlasBuildSetupFontSpecialGlyphs().
Flags
ImFontFlags ImFont::Flags
Definition at line 3835 of file imgui.h.
Referenced by ImFontAtlas::AddFont(), ImFontAtlasBakedGetOrAdd(), ImFontAtlasBuildDiscardBakes(), ImFontBaked_BuildLoadGlyph(), ImGui::PopPasswordFont(), and ImGui::PushPasswordFont().
FontId
ImGuiID ImFont::FontId
Definition at line 3840 of file imgui.h.
Referenced by ImFontAtlas::AddFont(), and ImFontAtlasBakedGetOrAdd().
LastBaked
ImFontBaked* ImFont::LastBaked
Definition at line 3833 of file imgui.h.
Referenced by ClearOutputData(), GetFontBaked(), and ImFontAtlasBakedDiscard().
LegacySize
float ImFont::LegacySize
Definition at line 3841 of file imgui.h.
Referenced by ImFontAtlas::AddCustomRectFontGlyph(), ImFontAtlas::AddFont(), ImGui::PushFont(), and ImGui::UpdateFontsNewFrame().
OwnerAtlas
ImFontAtlas* ImFont::OwnerAtlas
Definition at line 3834 of file imgui.h.
Referenced by ImDrawList::AddPolyline(), ImGui::Begin(), ClearOutputData(), ImGui::DebugNodeFont(), ImGui::DebugNodeFontGlyph(), GetFontBaked(), ImFontAtlasBuildSetupFontBakedFallback(), ImFontAtlasFontSourceAddToFont(), ImFontBaked_BuildLoadGlyph(), IsGlyphInFont(), ImFontAtlas::RemoveFont(), and ImGui::SetCurrentFont().
RemapPairs
ImGuiStorage ImFont::RemapPairs
Definition at line 3847 of file imgui.h.
Referenced by AddRemapChar(), and ImFontAtlas_FontHookRemapCodepoint().
Scale
float ImFont::Scale
Definition at line 3849 of file imgui.h.
Referenced by ImGui::DebugNodeFont(), ImFont(), ImGui::SetCurrentFont(), and ImGui::UpdateCurrentFontSize().
Sources
ImVector<ImFontConfig*> ImFont::Sources
Definition at line 3842 of file imgui.h.
Referenced by ImFontAtlas::AddCustomRectFontGlyphForSize(), ImFontAtlas::AddFont(), CalcFontGlyphSrcOverlapMask(), ImGui::DebugNodeFont(), ImFontAtlasBakedAdd(), ImFontAtlasBakedAddFontGlyph(), ImFontAtlasBakedAddFontGlyphAdvancedX(), ImFontAtlasBakedDiscard(), ImFontAtlasBuildSetupFontSpecialGlyphs(), ImFontAtlasFontDestroyOutput(), ImFontAtlasFontInitOutput(), ImFontAtlasFontSourceAddToFont(), ImFontBaked_BuildLoadGlyph(), ImGui_ImplFreeType_FontBakedInit(), ImGui_ImplFreeType_FontBakedLoadGlyph(), ImGui_ImplStbTrueType_FontBakedLoadGlyph(), ImGui_ImplStbTrueType_FontSrcInit(), IsGlyphInFont(), and ImFontAtlas::RemoveFont().
Used8kPagesMap
ImU8 ImFont::Used8kPagesMap[(0xFFFF+1)/8192/8]
Definition at line 3845 of file imgui.h.
Referenced by ClearOutputData(), ImFontAtlasBakedAddFontGlyph(), and IsGlyphRangeUnused().
The documentation for this struct was generated from the following files:
examples/imgui/imgui.h
examples/imgui/imgui_draw.cpp