SignalProcessing: ImGuiTextBuffer Struct Reference
ImGuiTextBuffer Struct Reference
#include <imgui.h>
Public Member Functions
ImGuiTextBuffer ()
char operator[] (int i) const
const char * begin () const
const char * end () const
int size () const
bool empty () const
void clear ()
void resize (int size)
void reserve (int capacity)
const char * c_str () const
void append (const char *str, const char *str_end=NULL)
void appendf (const char *fmt,...)
void appendfv (const char *fmt, va_list args)
Public Attributes
ImVector< char > Buf
Static Public Attributes
static char EmptyString [1] = { 0 }
Detailed Description
Definition at line 2736 of file imgui.h.
Constructor & Destructor Documentation
ImGuiTextBuffer()
ImGuiTextBuffer::ImGuiTextBuffer () inline
Definition at line 2741 of file imgui.h.
Member Function Documentation
append()
void ImGuiTextBuffer::append (const char * str, const char * str_end = NULL)
Definition at line 3062 of file imgui.cpp.
References ImStrlen.
Referenced by ImPlotTicker::AddTick(), ImPlotTicker::AddTick(), ImPlotColormapData::Append(), ImPlotAnnotationCollection::AppendV(), ImPlotTagCollection::AppendV(), ImGui::DebugHookIdInfo(), DebugItemPathQuery_GetResultAsPath(), ImPlot::EndPlot(), ImPlot::RegisterOrGetItem(), ImPlotPlot::SetAxisLabel(), ImPlotPlot::SetTitle(), ImGui::TabItemEx(), TableSettingsHandler_WriteAll(), ImGui::TableSetupColumn(), and WindowSettingsHandler_WriteAll().
appendf()
void ImGuiTextBuffer::appendf (const char * fmt, ...)
Definition at line 3080 of file imgui.cpp.
Referenced by DebugItemPathQuery_GetResultAsPath(), ImGui::DebugLogV(), ShowExampleAppLongText(), TableSettingsHandler_WriteAll(), and WindowSettingsHandler_WriteAll().
appendfv()
void ImGuiTextBuffer::appendfv (const char * fmt, va_list args)
Definition at line 3089 of file imgui.cpp.
References ImFormatStringV(), and va_copy.
Referenced by ExampleAppLog::AddLog(), ImPlotAnnotationCollection::AppendV(), ImPlotTagCollection::AppendV(), ImGui::DebugLogV(), and LogTextV().
begin()
const char * ImGuiTextBuffer::begin () const inline
Definition at line 2743 of file imgui.h.
References Buf, ImVector< T >::Data, EmptyString, and ImVector< T >::front().
Referenced by ImGui::DebugLogV(), ExampleAppLog::Draw(), ImGui::LogFinish(), and ShowExampleAppLongText().
c_str()
const char * ImGuiTextBuffer::c_str () const inline
Definition at line 2750 of file imgui.h.
References Buf, ImVector< T >::Data, and EmptyString.
Referenced by DebugItemPathQuery_GetResultAsPath(), ImGui::DebugLogV(), ImPlot::EndPlot(), LogTextV(), ImGui::SaveIniSettingsToMemory(), ImGui::ShowDebugLogWindow(), and ImGui::ShowMetricsWindow().
clear()
void ImGuiTextBuffer::clear () inline
Definition at line 2747 of file imgui.h.
References Buf, and ImVector< T >::clear().
Referenced by ExampleAppLog::Clear(), ImGui::ClearIniSettings(), ImGui::LogFinish(), ImGui::ShowDebugLogWindow(), ShowExampleAppLongText(), ImGui::Shutdown(), and ImGui::TableGcCompactTransientBuffers().
empty()
bool ImGuiTextBuffer::empty () const inline
Definition at line 2746 of file imgui.h.
References Buf, and ImVector< T >::Size.
Referenced by ImPlot::EndPlot(), ImGui::LogBegin(), and ImGui::LogFinish().
end()
const char * ImGuiTextBuffer::end () const inline
Definition at line 2744 of file imgui.h.
References ImVector< T >::back(), Buf, ImVector< T >::Data, and EmptyString.
Referenced by ExampleAppLog::Draw(), and ShowExampleAppLongText().
operator[]()
char ImGuiTextBuffer::operator[] (int i) const inline
Definition at line 2742 of file imgui.h.
References Buf, ImVector< T >::Data, and IM_ASSERT.
reserve()
void ImGuiTextBuffer::reserve (int capacity) inline
Definition at line 2749 of file imgui.h.
References Buf, and ImVector< T >::reserve().
Referenced by TableSettingsHandler_WriteAll(), and WindowSettingsHandler_WriteAll().
resize()
void ImGuiTextBuffer::resize (int size) inline
Definition at line 2748 of file imgui.h.
References Buf, ImVector< T >::Data, ImVector< T >::resize(), ImVector< T >::Size, and size().
Referenced by DebugItemPathQuery_GetResultAsPath(), and DebugItemPathQuery_UpdateAndGetHookId().
size()
int ImGuiTextBuffer::size () const inline
Definition at line 2745 of file imgui.h.
References Buf, and ImVector< T >::Size.
Referenced by ExampleAppLog::AddLog(), ImPlotTicker::AddTick(), ImPlotTicker::AddTick(), ImPlotColormapData::Append(), ImPlotAnnotationCollection::AppendV(), ImPlotTagCollection::AppendV(), ImGui::DebugHookIdInfo(), ImGui::DebugLogV(), LogTextV(), ImPlot::RegisterOrGetItem(), resize(), ImGui::SaveIniSettingsToMemory(), ImPlotPlot::SetAxisLabel(), ImPlotPlot::SetTitle(), ShowExampleAppLongText(), ImGui::ShowMetricsWindow(), ImGui::TabItemEx(), TableSettingsHandler_WriteAll(), ImGui::TableSetupColumn(), and WindowSettingsHandler_WriteAll().
Member Data Documentation
Buf
ImVector<char> ImGuiTextBuffer::Buf
Definition at line 2738 of file imgui.h.
Referenced by ImPlotTicker::AddTick(), ImPlotTicker::AddTick(), begin(), ImGui::BeginTableEx(), c_str(), clear(), ImPlotPlot::ClearTextBuffer(), DebugItemPathQuery_FormatLevelInfo(), empty(), end(), ImPlot::EndPlot(), ImPlotPlot::GetAxisLabel(), ImPlotItemGroup::GetLegendLabel(), ImPlotColormapData::GetName(), ImPlotAnnotationCollection::GetText(), ImPlotTagCollection::GetText(), ImPlotTicker::GetText(), ImPlotPlot::GetTitle(), ImGui::LoadIniSettingsFromMemory(), ImPlot::Locator_Time(), LogTextV(), operator[](), reserve(), ImPlotAnnotationCollection::Reset(), ImPlotTagCollection::Reset(), ImPlotTicker::Reset(), ImPlotLegend::Reset(), resize(), ImGui::SaveIniSettingsToMemory(), ImGui::ShowMetricsWindow(), ImPlot::ShowMetricsWindow(), size(), ImGui::TabBarGetTabName(), ImGui::TabBarLayout(), and ImGui::TableGetColumnName().
EmptyString
char ImGuiTextBuffer::EmptyString = { 0 } static
Definition at line 3060 of file imgui.h.
Referenced by begin(), c_str(), and end().
The documentation for this struct was generated from the following files:
examples/imgui/imgui.h
examples/imgui/imgui.cpp