SignalProcessing: ImTriangulator Struct Reference
ImTriangulator Struct Reference
Public Member Functions
void Init (const ImVec2 *points, int points_count, void *scratch_buffer)
void GetNextTriangle (unsigned int out_triangle[3])
void BuildNodes (const ImVec2 *points, int points_count)
void BuildReflexes ()
void BuildEars ()
void FlipNodeList ()
bool IsEar (int i0, int i1, int i2, const ImVec2 &v0, const ImVec2 &v1, const ImVec2 &v2) const
void ReclassifyNode (ImTriangulatorNode *node)
Static Public Member Functions
static int EstimateTriangleCount (int points_count)
static int EstimateScratchBufferSize (int points_count)
Public Attributes
int _TrianglesLeft = 0
ImTriangulatorNode * _Nodes = NULL
ImTriangulatorNodeSpan _Ears
ImTriangulatorNodeSpan _Reflexes
Detailed Description
Definition at line 1835 of file imgui_draw.cpp.
Member Function Documentation
BuildEars()
void ImTriangulator::BuildEars ()
Definition at line 1899 of file imgui_draw.cpp.
References _Ears, _Nodes, _TrianglesLeft, ImTriangulatorNodeType_Convex, ImTriangulatorNodeType_Ear, ImTriangulatorNode::Index, IsEar(), ImTriangulatorNode::Next, ImTriangulatorNode::Pos, ImTriangulatorNode::Prev, ImTriangulatorNodeSpan::push_back(), and ImTriangulatorNode::Type.
Referenced by GetNextTriangle(), and Init().
BuildNodes()
void ImTriangulator::BuildNodes (const ImVec2 * points, int points_count)
Definition at line 1873 of file imgui_draw.cpp.
References _Nodes, ImTriangulatorNodeType_Convex, ImTriangulatorNode::Index, ImTriangulatorNode::Next, ImTriangulatorNode::Pos, ImTriangulatorNode::Prev, and ImTriangulatorNode::Type.
Referenced by Init().
BuildReflexes()
void ImTriangulator::BuildReflexes ()
Definition at line 1887 of file imgui_draw.cpp.
References _Nodes, _Reflexes, _TrianglesLeft, ImTriangleIsClockwise(), ImTriangulatorNodeType_Reflex, ImTriangulatorNode::Next, ImTriangulatorNode::Pos, ImTriangulatorNode::Prev, ImTriangulatorNodeSpan::push_back(), and ImTriangulatorNode::Type.
Referenced by GetNextTriangle(), and Init().
EstimateScratchBufferSize()
static int ImTriangulator::EstimateScratchBufferSize (int points_count) inline static
Definition at line 1838 of file imgui_draw.cpp.
Referenced by ImDrawList::AddConcavePolyFilled().
EstimateTriangleCount()
static int ImTriangulator::EstimateTriangleCount (int points_count) inline static
Definition at line 1837 of file imgui_draw.cpp.
Referenced by Init().
FlipNodeList()
void ImTriangulator::FlipNodeList ()
Definition at line 1950 of file imgui_draw.cpp.
References _Nodes, ImTriangulatorNode::Next, and ImTriangulatorNode::Prev.
Referenced by GetNextTriangle().
GetNextTriangle()
void ImTriangulator::GetNextTriangle (unsigned int out_triangle[3])
Definition at line 1913 of file imgui_draw.cpp.
References _Ears, _Nodes, _Reflexes, _TrianglesLeft, BuildEars(), BuildReflexes(), ImTriangulatorNodeSpan::Data, FlipNodeList(), IM_ASSERT, ImTriangulatorNodeType_Convex, ImTriangulatorNode::Index, ImTriangulatorNode::Next, ImTriangulatorNode::Prev, ReclassifyNode(), ImTriangulatorNodeSpan::Size, ImTriangulatorNode::Type, and ImTriangulatorNode::Unlink().
Referenced by ImDrawList::AddConcavePolyFilled().
Init()
void ImTriangulator::Init (const ImVec2 * points, int points_count, void * scratch_buffer)
Definition at line 1861 of file imgui_draw.cpp.
References _Ears, _Nodes, _Reflexes, _TrianglesLeft, BuildEars(), BuildNodes(), BuildReflexes(), ImTriangulatorNodeSpan::Data, EstimateTriangleCount(), and IM_ASSERT.
Referenced by ImDrawList::AddConcavePolyFilled().
IsEar()
bool ImTriangulator::IsEar (int i0, int i1, int i2, const ImVec2 & v0, const ImVec2 & v1, const ImVec2 & v2) const
Definition at line 1973 of file imgui_draw.cpp.
References _Reflexes, ImTriangulatorNodeSpan::Data, ImTriangleContainsPoint(), ImTriangulatorNode::Index, ImTriangulatorNode::Pos, and ImTriangulatorNodeSpan::Size.
Referenced by BuildEars(), and ReclassifyNode().
ReclassifyNode()
void ImTriangulator::ReclassifyNode (ImTriangulatorNode * node)
Definition at line 1986 of file imgui_draw.cpp.
References _Ears, _Reflexes, ImTriangulatorNodeSpan::find_erase_unsorted(), ImTriangleIsClockwise(), ImTriangulatorNodeType_Convex, ImTriangulatorNodeType_Ear, ImTriangulatorNodeType_Reflex, ImTriangulatorNode::Index, IsEar(), ImTriangulatorNode::Next, ImTriangulatorNode::Pos, ImTriangulatorNode::Prev, ImTriangulatorNodeSpan::push_back(), and ImTriangulatorNode::Type.
Referenced by GetNextTriangle().
Member Data Documentation
_Ears
ImTriangulatorNodeSpan ImTriangulator::_Ears
Definition at line 1854 of file imgui_draw.cpp.
Referenced by BuildEars(), GetNextTriangle(), Init(), and ReclassifyNode().
_Nodes
ImTriangulatorNode* ImTriangulator::_Nodes = NULL
Definition at line 1853 of file imgui_draw.cpp.
Referenced by BuildEars(), BuildNodes(), BuildReflexes(), FlipNodeList(), GetNextTriangle(), and Init().
_Reflexes
ImTriangulatorNodeSpan ImTriangulator::_Reflexes
Definition at line 1855 of file imgui_draw.cpp.
Referenced by BuildReflexes(), GetNextTriangle(), Init(), IsEar(), and ReclassifyNode().
_TrianglesLeft
int ImTriangulator::_TrianglesLeft = 0
Definition at line 1852 of file imgui_draw.cpp.
Referenced by ImDrawList::AddConcavePolyFilled(), BuildEars(), BuildReflexes(), GetNextTriangle(), and Init().
The documentation for this struct was generated from the following file:
examples/imgui/imgui_draw.cpp