SignalProcessing: ImPlot::RendererBarsFillH< _Getter1, _Getter2 > Struct Template Reference
ImPlot::RendererBarsFillH< _Getter1, _Getter2 > Struct Template Reference
Public Member Functions
RendererBarsFillH (const _Getter1 &getter1, const _Getter2 &getter2, ImU32 col, double height)
void Init (ImDrawList &draw_list) const
bool Render (ImDrawList &draw_list, const ImRect &cull_rect, int prim) const
Public Member Functions inherited from ImPlot::RendererBase
RendererBase (int prims, int idx_consumed, int vtx_consumed)
Public Attributes
const _Getter1 & Getter1
const _Getter2 & Getter2
const ImU32 Col
const double HalfHeight
ImVec2 UV
Public Attributes inherited from ImPlot::RendererBase
const int Prims
Transformer2 Transformer
const int IdxConsumed
const int VtxConsumed
Detailed Description
template<class _Getter1, class _Getter2>
struct ImPlot::RendererBarsFillH< _Getter1, _Getter2 >
Definition at line 1024 of file implot_items.cpp.
Constructor & Destructor Documentation
RendererBarsFillH()
template<class _Getter1 , class _Getter2 > ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::RendererBarsFillH (const _Getter1 & getter1, const _Getter2 & getter2, ImU32 col, double height) inline
Definition at line 1025 of file implot_items.cpp.
Member Function Documentation
Init()
template<class _Getter1 , class _Getter2 > void ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::Init (ImDrawList & draw_list) const inline
Definition at line 1032 of file implot_items.cpp.
References ImDrawList::_Data, ImPlot::draw_list, ImDrawListSharedData::TexUvWhitePixel, and ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::UV.
Render()
template<class _Getter1 , class _Getter2 > bool ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::Render (ImDrawList & draw_list, const ImRect & cull_rect, int prim) const inline
Definition at line 1035 of file implot_items.cpp.
References ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::Col, ImPlot::draw_list, ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::Getter1, ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::Getter2, ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::HalfHeight, ImAbs(), ImMax(), ImMin(), ImRect::Overlaps(), ImPlot::PrimRectFill(), ImPlot::RendererBase::Transformer, ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::UV, ImVec2::y, and ImPlotPoint::y.
Member Data Documentation
Col
template<class _Getter1 , class _Getter2 > const ImU32 ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::Col
Definition at line 1056 of file implot_items.cpp.
Referenced by ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::Render().
Getter1
template<class _Getter1 , class _Getter2 > const _Getter1& ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::Getter1
Definition at line 1054 of file implot_items.cpp.
Referenced by ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::Render().
Getter2
template<class _Getter1 , class _Getter2 > const _Getter2& ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::Getter2
Definition at line 1055 of file implot_items.cpp.
Referenced by ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::Render().
HalfHeight
template<class _Getter1 , class _Getter2 > const double ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::HalfHeight
Definition at line 1057 of file implot_items.cpp.
Referenced by ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::Render().
UV
template<class _Getter1 , class _Getter2 > ImVec2 ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::UV mutable
Definition at line 1058 of file implot_items.cpp.
Referenced by ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::Init(), and ImPlot::RendererBarsFillH< _Getter1, _Getter2 >::Render().
The documentation for this struct was generated from the following file:
examples/implot/implot_items.cpp