SignalProcessing: ImPlotAnnotationCollection Struct Reference
ImPlotAnnotationCollection Struct Reference
#include <implot_internal.h>
Public Member Functions
ImPlotAnnotationCollection ()
void AppendV (const ImVec2 &pos, const ImVec2 &off, ImU32 bg, ImU32 fg, bool clamp, const char *fmt, va_list args) IM_FMTLIST(7)
void Append (const ImVec2 &pos, const ImVec2 &off, ImU32 bg, ImU32 fg, bool clamp, const char *fmt,...) IM_FMTARGS(7)
const char * GetText (int idx)
void Reset ()
Public Attributes
ImVector< ImPlotAnnotation > Annotations
ImGuiTextBuffer TextBuffer
int Size
Detailed Description
Definition at line 446 of file implot_internal.h.
Constructor & Destructor Documentation
ImPlotAnnotationCollection()
ImPlotAnnotationCollection::ImPlotAnnotationCollection () inline
Definition at line 452 of file implot_internal.h.
References Reset().
Member Function Documentation
Append()
void ImPlotAnnotationCollection::Append (const ImVec2 & pos, const ImVec2 & off, ImU32 bg, ImU32 fg, bool clamp, const char * fmt, ...) inline
Definition at line 467 of file implot_internal.h.
References AppendV().
AppendV()
void ImPlotAnnotationCollection::AppendV (const ImVec2 & pos, const ImVec2 & off, ImU32 bg, ImU32 fg, bool clamp, const char * fmt, va_list args) inline
Definition at line 454 of file implot_internal.h.
References Annotations, ImGuiTextBuffer::append(), ImGuiTextBuffer::appendfv(), ImPlotAnnotation::Clamp, ImPlotAnnotation::ColorBg, ImPlotAnnotation::ColorFg, ImPlotAnnotation::Offset, ImPlotAnnotation::Pos, ImVector< T >::push_back(), ImGuiTextBuffer::size(), Size, TextBuffer, and ImPlotAnnotation::TextOffset.
Referenced by ImPlot::AnnotationV(), and Append().
GetText()
const char * ImPlotAnnotationCollection::GetText (int idx) inline
Definition at line 474 of file implot_internal.h.
References Annotations, ImGuiTextBuffer::Buf, ImVector< T >::Data, and TextBuffer.
Referenced by ImPlot::EndPlot().
Reset()
void ImPlotAnnotationCollection::Reset () inline
Definition at line 478 of file implot_internal.h.
References Annotations, ImGuiTextBuffer::Buf, ImVector< T >::shrink(), Size, and TextBuffer.
Referenced by ImPlotAnnotationCollection(), and ImPlot::ResetCtxForNextPlot().
Member Data Documentation
Annotations
ImVector<ImPlotAnnotation> ImPlotAnnotationCollection::Annotations
Definition at line 448 of file implot_internal.h.
Referenced by AppendV(), ImPlot::EndPlot(), GetText(), and Reset().
Size
int ImPlotAnnotationCollection::Size
Definition at line 450 of file implot_internal.h.
Referenced by AppendV(), ImPlot::EndPlot(), and Reset().
TextBuffer
ImGuiTextBuffer ImPlotAnnotationCollection::TextBuffer
Definition at line 449 of file implot_internal.h.
Referenced by AppendV(), GetText(), and Reset().
The documentation for this struct was generated from the following file:
examples/implot/implot_internal.h