SignalProcessing: examples/imgui/examples/libs/usynergy/uSynergy.c File Reference
uSynergy.c File Reference
#include "uSynergy.h"
#include <stdio.h>
#include <string.h>
Macros
#define USYNERGY_IS_PACKET(pkt_id) memcmp(message+4, pkt_id, 4)==0
Parse a single client message, update state, send callbacks and send replies.
Functions
static int16_t sNetToNative16 (const unsigned char *value)
Read 16 bit integer in network byte order and convert to native byte order.
static int32_t sNetToNative32 (const unsigned char *value)
Read 32 bit integer in network byte order and convert to native byte order.
static void sTrace (uSynergyContext *context, const char *text)
Trace text to client.
static void sAddString (uSynergyContext *context, const char *string)
Add string to reply packet.
static void sAddUInt8 (uSynergyContext *context, uint8_t value)
Add uint8 to reply packet.
static void sAddUInt16 (uSynergyContext *context, uint16_t value)
Add uint16 to reply packet.
static void sAddUInt32 (uSynergyContext *context, uint32_t value)
Add uint32 to reply packet.
static uSynergyBool sSendReply (uSynergyContext *context)
Send reply packet.
static void sSendMouseCallback (uSynergyContext *context)
Call mouse callback after a mouse event.
static void sSendKeyboardCallback (uSynergyContext *context, uint16_t key, uint16_t modifiers, uSynergyBool down, uSynergyBool repeat)
Send keyboard callback when a key has been pressed or released.
static void sSendJoystickCallback (uSynergyContext *context, uint8_t joyNum)
Send joystick callback.
static void sProcessMessage (uSynergyContext *context, const uint8_t *message)
static void sSetDisconnected (uSynergyContext *context)
Mark context as being disconnected.
static void sUpdateContext (uSynergyContext *context)
Update a connected context.
void uSynergyInit (uSynergyContext *context)
Initialize uSynergy context.
void uSynergyUpdate (uSynergyContext *context)
Update uSynergy.
void uSynergySendClipboard (uSynergyContext *context, const char *text)
Send clipboard data.
Macro Definition Documentation
USYNERGY_IS_PACKET
#define USYNERGY_IS_PACKET (pkt_id) memcmp(message+4, pkt_id, 4)==0
Parse a single client message, update state, send callbacks and send replies.
Definition at line 205 of file uSynergy.c.
Function Documentation
sAddString()
static void sAddString (uSynergyContext * context, const char * string) static
Add string to reply packet.
Definition at line 81 of file uSynergy.c.
References uSynergyContext::m_replyCur.
Referenced by sProcessMessage(), and uSynergySendClipboard().
sAddUInt16()
static void sAddUInt16 (uSynergyContext * context, uint16_t value) static
Add uint16 to reply packet.
Definition at line 103 of file uSynergy.c.
References uSynergyContext::m_replyCur.
Referenced by sProcessMessage().
sAddUInt32()
static void sAddUInt32 (uSynergyContext * context, uint32_t value) static
Add uint32 to reply packet.
Definition at line 116 of file uSynergy.c.
References uSynergyContext::m_replyCur.
Referenced by sProcessMessage(), and uSynergySendClipboard().
sAddUInt8()
static void sAddUInt8 (uSynergyContext * context, uint8_t value) static
Add uint8 to reply packet.
Definition at line 93 of file uSynergy.c.
References uSynergyContext::m_replyCur.
Referenced by uSynergySendClipboard().
sNetToNative16()
static int16_t sNetToNative16 (const unsigned char * value) static
Read 16 bit integer in network byte order and convert to native byte order.
Definition at line 41 of file uSynergy.c.
Referenced by sProcessMessage().
sNetToNative32()
static int32_t sNetToNative32 (const unsigned char * value) static
Read 32 bit integer in network byte order and convert to native byte order.
Definition at line 55 of file uSynergy.c.
Referenced by sProcessMessage(), and sUpdateContext().
sProcessMessage()
static void sProcessMessage (uSynergyContext * context, const uint8_t * message) static
Definition at line 206 of file uSynergy.c.
References uSynergyContext::m_clientHeight, uSynergyContext::m_clientName, uSynergyContext::m_clientWidth, uSynergyContext::m_clipboardCallback, uSynergyContext::m_connected, uSynergyContext::m_cookie, uSynergyContext::m_hasReceivedHello, uSynergyContext::m_isCaptured, uSynergyContext::m_joystickButtons, uSynergyContext::m_joystickSticks, uSynergyContext::m_mouseButtonLeft, uSynergyContext::m_mouseButtonMiddle, uSynergyContext::m_mouseButtonRight, uSynergyContext::m_mouseWheelX, uSynergyContext::m_mouseWheelY, uSynergyContext::m_mouseX, uSynergyContext::m_mouseY, uSynergyContext::m_screenActiveCallback, uSynergyContext::m_sequenceNumber, uSynergyContext::m_sleepFunc, sAddString(), sAddUInt16(), sAddUInt32(), sNetToNative16(), sNetToNative32(), sSendJoystickCallback(), sSendKeyboardCallback(), sSendMouseCallback(), sSendReply(), sTrace(), USYNERGY_FALSE, USYNERGY_IS_PACKET, USYNERGY_NUM_JOYSTICKS, USYNERGY_PROTOCOL_MAJOR, USYNERGY_PROTOCOL_MINOR, and USYNERGY_TRUE.
Referenced by sUpdateContext().
sSendJoystickCallback()
static void sSendJoystickCallback (uSynergyContext * context, uint8_t joyNum) static
Send joystick callback.
Definition at line 187 of file uSynergy.c.
References uSynergyContext::m_cookie, uSynergyContext::m_joystickButtons, uSynergyContext::m_joystickCallback, and uSynergyContext::m_joystickSticks.
Referenced by sProcessMessage().
sSendKeyboardCallback()
static void sSendKeyboardCallback (uSynergyContext * context, uint16_t key, uint16_t modifiers, uSynergyBool down, uSynergyBool repeat) static
Send keyboard callback when a key has been pressed or released.
Definition at line 172 of file uSynergy.c.
References uSynergyContext::m_cookie, and uSynergyContext::m_keyboardCallback.
Referenced by sProcessMessage().
sSendMouseCallback()
static void sSendMouseCallback (uSynergyContext * context) static
Call mouse callback after a mouse event.
Definition at line 156 of file uSynergy.c.
References uSynergyContext::m_cookie, uSynergyContext::m_mouseButtonLeft, uSynergyContext::m_mouseButtonMiddle, uSynergyContext::m_mouseButtonRight, uSynergyContext::m_mouseCallback, uSynergyContext::m_mouseWheelX, uSynergyContext::m_mouseWheelY, uSynergyContext::m_mouseX, and uSynergyContext::m_mouseY.
Referenced by sProcessMessage().
sSendReply()
static uSynergyBool sSendReply (uSynergyContext * context) static
Send reply packet.
Definition at line 131 of file uSynergy.c.
References uSynergyContext::m_cookie, uSynergyContext::m_replyBuffer, uSynergyContext::m_replyCur, and uSynergyContext::m_sendFunc.
Referenced by sProcessMessage(), and uSynergySendClipboard().
sSetDisconnected()
static void sSetDisconnected (uSynergyContext * context) static
Mark context as being disconnected.
Definition at line 462 of file uSynergy.c.
References uSynergyContext::m_connected, uSynergyContext::m_hasReceivedHello, uSynergyContext::m_isCaptured, uSynergyContext::m_replyBuffer, uSynergyContext::m_replyCur, uSynergyContext::m_sequenceNumber, and USYNERGY_FALSE.
Referenced by sUpdateContext(), and uSynergyInit().
sTrace()
static void sTrace (uSynergyContext * context, const char * text) static
Trace text to client.
Definition at line 69 of file uSynergy.c.
References uSynergyContext::m_cookie, and uSynergyContext::m_traceFunc.
Referenced by sProcessMessage(), sUpdateContext(), and uSynergySendClipboard().
sUpdateContext()
static void sUpdateContext (uSynergyContext * context) static
Update a connected context.
Definition at line 476 of file uSynergy.c.
References uSynergyContext::m_cookie, uSynergyContext::m_getTimeFunc, uSynergyContext::m_hasReceivedHello, uSynergyContext::m_lastMessageTime, uSynergyContext::m_receiveBuffer, uSynergyContext::m_receiveFunc, uSynergyContext::m_receiveOfs, uSynergyContext::m_sleepFunc, sNetToNative32(), sProcessMessage(), sSetDisconnected(), sTrace(), USYNERGY_FALSE, USYNERGY_IDLE_TIMEOUT, and USYNERGY_RECEIVE_BUFFER_SIZE.
Referenced by uSynergyUpdate().
uSynergyInit()
void uSynergyInit (uSynergyContext * context)
Initialize uSynergy context.
This function initializes context for use. Call this function directly after creating the context, before filling in any configuration data in it. Not calling this function will cause undefined behavior.
Parameters
context Context to be initialized
Definition at line 570 of file uSynergy.c.
References sSetDisconnected().
uSynergySendClipboard()
void uSynergySendClipboard (uSynergyContext * context, const char * text)
Send clipboard data.
This function sets new clipboard data and sends it to the server. Use this function if your client cuts or copies data onto the clipboard that it needs to share with the server.
Currently there is only support for plaintext, but HTML and image data could be supported with some effort.
Parameters
context Context to send clipboard data to
text Text to set to the clipboard
Definition at line 603 of file uSynergy.c.
References uSynergyContext::m_sequenceNumber, sAddString(), sAddUInt32(), sAddUInt8(), sSendReply(), sTrace(), USYNERGY_CLIPBOARD_FORMAT_TEXT, and USYNERGY_REPLY_BUFFER_SIZE.
uSynergyUpdate()
void uSynergyUpdate (uSynergyContext * context)
Update uSynergy.
This function updates uSynergy and does the bulk of the work. It does connection management, receiving data, reconnecting after errors or timeouts and so on. It assumes that networking operations are blocking and it can suspend the current thread if it needs to wait. It is best practice to call uSynergyUpdate from a background thread so it is responsive.
Because uSynergy relies mostly on blocking calls it will mostly stay in thread sleep state waiting for system mutexes and won't eat much memory.
uSynergyUpdate doesn't do any memory allocations or have any side effects beyond those of the callbacks it calls.
Parameters
context Context to be updated
Definition at line 583 of file uSynergy.c.
References uSynergyContext::m_connected, uSynergyContext::m_connectFunc, uSynergyContext::m_cookie, sUpdateContext(), and USYNERGY_TRUE.